### ISSUE TITLE
Painting - put the sliders into the toolbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#100]
This is most probably mission impossible. But let's have a look if we can place the most important sliders like radius and strength into the toolbar.

![slidersintoheader](https://user-images.githubusercontent.com/13919702/37758755-9c50cde0-2db1-11e8-9d2b-9abb7c3af9e7.jpg)

**Comment by Draise14** [comment]
Hope you can, would be nice. Krita has the sliders to the top of the UI too.

**Comment by ReinerBforartists** [comment]
Some elements cannot be placed in header. And i think to remember that sliders is one of those. But we will see.

**Comment by ReinerBforartists** [comment]
That would be a double menu entry :)

But a simplified mode is no bad idea. I have already made a thread to hide the colorpicker. And the three checkboxes doesn't necessarily need to be text checkboxes. Meanas making it compact is at its way ;)

**Comment by ReinerBforartists** [comment]
As expected, no way.

Was worth a shot. Closing.
