### ISSUE TITLE
Video Sequencer - compare merge side panel changes from Blender 2.8 to Bforartists 2

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1000]
# Issue
Blender: 
![blender_2019-07-03_11-02-47](https://user-images.githubusercontent.com/35357409/60607367-bfc24500-9d82-11e9-8663-4274394fa224.png)
Bforartist 2: 
![bforartists_2019-07-03_11-02-59](https://user-images.githubusercontent.com/35357409/60607212-7a9e1300-9d82-11e9-9d61-c1c1d6bc1cf8.png)

Seems there has been a regression that is pulling in errors and doesn't have some of the latest UI updates with menus/submenus from the 2.8 paradigm. We have 139 codes missing or in conflict from the new updated master of Beta Blender 2.8.0. 

![atom_2019-07-03_11-05-04](https://user-images.githubusercontent.com/35357409/60607253-8db0e300-9d82-11e9-9221-fe953ec4cf29.png)

# Task
Go through the code and merge in the correct code preserving BFA changes.

**Comment by ReinerBforartists** [comment]
Merges -.-

**Comment by Draise14** [comment]
Ok, done, pull request.  Took a bit of effort but now I can edit video like normal with normal features.
