### ISSUE TITLE
Redo the icons -  Row by row

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1009]
We have already converted and created quite a few icons for the new icon sheet. The new monochrome Blender icons are gone. The modifier and constraints icons are redone. But there are lots of old Blender icons left. And we need also to convert our old Bforartists icons to the new palette to have a consistent look.

Go through the rows of the icon sheet, one by one, and fix everything up. The new created icons should go into the file repository. Preferable a single svg file that can be thrown into the sheet, plus the PNG file it was created from. Additionally, the original gimp file to create the PNG files doesn't hurt.

This task will last several months. I will every now and then commit the content of a fixed row.

**Comment by Draise14** [comment]
Great! Maybe to speed things up and to keep things consistent: maybe we should make a design wireframe targets for icon design so anyone can be assigned a row in a new task and do the updates and keep it all consistent (eg, me! or anyone else). 

**Example of an Icon Design Wireframe:** 
1. Colour coding (what colour varients is for what data type/use)
2. Line width and when/where to use
3. Bevel/corner styles
4. Silluette targets
5. Global symbolisms that can be combined with new logos (+, -, x, playhead, select, up arrow, down arrow, right arrow, etc) _So that we don't redesign reused symbolism which BFA has done a number of times_
6. Design Dimensions
7. Padding
8. Volume/Form shading techniques

**Comment by ReinerBforartists** [comment]
Hm. I still think the icon sheet should be done by one person. Point 2 to 8 depends too much of the icon itself. It can be 16 pixels it can be 14 pixels, the line width can vary, bevel may or may not fit and so on. Every icon is a individual piece of art.

For the palette, i use currently one of the Gimp palettes. Visibone (336)

![visibone](https://user-images.githubusercontent.com/13919702/60758869-991f3b00-a01c-11e9-9408-01c8cbf9f758.png)

**Comment by ReinerBforartists** [comment]
Forgot to say, you could study the icons that are already in the file repository.

**Comment by ReinerBforartists** [comment]
Edit 2, this step is not to create a complete new set of icons. We convert the old ones to the new style. And try to keep the old shape and symbolism as much as possible.

**Comment by ReinerBforartists** [comment]
Starting with row 1 now.

**Comment by ReinerBforartists** [comment]
Hm, no gradients and no transparency is catching me here ...

![gradientsntransparent](https://user-images.githubusercontent.com/13919702/60789592-c294af80-a15f-11e9-8389-1c3069dec247.jpg)

**Comment by ReinerBforartists** [comment]
Progressing row 2 ...

**Comment by ReinerBforartists** [comment]
Progressing Row 3 ...

**Comment by Draise14** [comment]
Question, where are you storing the original icon SVG/PNG files per icon?

**Comment by ReinerBforartists** [comment]
In the file repository.

https://github.com/Bforartists/files/tree/master/iconset_bforartists_2

**Comment by ReinerBforartists** [comment]
Progressing Row 5 ...

**Comment by ReinerBforartists** [comment]
Progressing Row 6 ...

**Comment by ReinerBforartists** [comment]
Progressing row 7 ...

**Comment by ReinerBforartists** [comment]
Progressing row 8 ...

**Comment by ReinerBforartists** [comment]
Progressing Row 9 ...

**Comment by ReinerBforartists** [comment]
Progressing Row 10

**Comment by ReinerBforartists** [comment]
Progressing row 11 ...

**Comment by ReinerBforartists** [comment]
Progressing row 12 ...

**Comment by ReinerBforartists** [comment]
Progressing row 13 ...

**Comment by ReinerBforartists** [comment]
Progressing row 14 ...

**Comment by ReinerBforartists** [comment]
Progressing row 15 ...

**Comment by ReinerBforartists** [comment]
Progressing row 16 ...

**Comment by ReinerBforartists** [comment]
Progressing row 17 ...

**Comment by ReinerBforartists** [comment]
Progressing row 18 ...

**Comment by ReinerBforartists** [comment]
Progressing row 19 ...

**Comment by ReinerBforartists** [comment]
Progressing row 20 ...

**Comment by ReinerBforartists** [comment]
Progressing row 21 ...

**Comment by ReinerBforartists** [comment]
Hm, some icons are missing in row 20 folder. They are already remade, but the source files are not there. First check them ...

**Comment by ReinerBforartists** [comment]
Done. On with row 21 ...

**Comment by ReinerBforartists** [comment]
Progressing row 22 ...

**Comment by ReinerBforartists** [comment]
Progressing row 23 ...

**Comment by ReinerBforartists** [comment]
Progressing row 24 ...

**Comment by ReinerBforartists** [comment]
Progressing row 25 ...

**Comment by ReinerBforartists** [comment]
Progressing row 26 ...

**Comment by ReinerBforartists** [comment]
Progressing row 27 ...

**Comment by ReinerBforartists** [comment]
The im and export icons turned out ugly. Should be better now.

**Comment by ReinerBforartists** [comment]
Progressing row 28 ...

**Comment by Draise14** [comment]
Nearly done!

**Comment by ReinerBforartists** [comment]
Progressing row 29 ...

**Comment by ReinerBforartists** [comment]
Progressing row 30 ...

**Comment by ReinerBforartists** [comment]
Progressing ro ... wait 

Task fulfilled. Fixed in master :)

**Comment by Draise14** [comment]
huzzah!
