### ISSUE TITLE
Edit mode - missing tools when hiding the top bar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1010]
We have some missing content when we hide the top bar in edit mode.

![missingtools](https://user-images.githubusercontent.com/13919702/60771288-05b23c80-a0e6-11e9-91a1-5d5a1ebbcbb0.jpg)

**Comment by ReinerBforartists** [comment]
First check if this also happens in Blender. Then check if edit mode is the only mode where it happens. Also check with other object types.

**Comment by ReinerBforartists** [comment]
Blender bug. Or better said, a feature. A double menu entry. Hmm, which set to remove? When we kill the entries in the Options popup then we have a problem in the sidebar and the tools tab in preferences.

![blenderbug](https://user-images.githubusercontent.com/13919702/60787965-bf97c000-a15b-11e9-8bbc-cf3da6394a9b.jpg)

**Comment by ReinerBforartists** [comment]
Let's sleep a nigth over this one.

**Comment by Draise14** [comment]
I use the Automerge feature a lot. I have had friends ask for where it is, having it exposed like in 2.79/BFA1 is nice. Mirror not sure...

**Comment by ReinerBforartists** [comment]
The problem would be the inconsistency. Yes, it would be one more click for a frequently used tool. But it's a double entry. And we cannot place the automerge completely into the header. It has some settings.

**Comment by ReinerBforartists** [comment]
Postponing. We never know what last minute changes happens here ...

**Comment by ReinerBforartists** [comment]
This is in more than one mode ...

![morethanone](https://user-images.githubusercontent.com/13919702/60906748-332eef80-a278-11e9-88ea-892e15458c5b.jpg)

**Comment by ReinerBforartists** [comment]
The Options menu in the header is removed. Which makes this task obsolete.
