### ISSUE TITLE
Unknown icon during linux build

### ISSUE THREAD

**Issue by naetherm** [Bforartists/Bforartists#1014]
While building on linux the following error is produced:

```
make[2]: *** No rule for build target „/tmp/bforartists.git/release/datafiles/blender_icons16/icon16_file_3d.dat“
```

**Comment by ReinerBforartists** [comment]
Ah, the icon system strikes back. Forgot to remove deleted icons from the obscure source/blender/editors/datafiles/CmakeLists.txt file where the icons under linux gets recreated for no reason. 

It should have moaned about two icons. file_3d and file_cache. Fingers crossed that this is the only two problems.

**Comment by ReinerBforartists** [comment]
Still troubled. Thanks for checking ktotheoz. Will do a full check tomorrow.

**Comment by naetherm** [comment]
Next:
```
make[2]: *** No rule for buld target „/tmp/bforartists.git/release/datafiles/blender_icons16/icon16_bbox.dat“
```

**Comment by ReinerBforartists** [comment]
Compared all entries now. It should be fixed ...

**Comment by ReinerBforartists** [comment]
Reported as fixed. Closing.
