### ISSUE TITLE
Snap panel -  shorten the tool names

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#103]
I am not really happy with the long tool names here. We have already labels above the buttons. So we can shorten the tool names!
![snaptosymmetry](https://user-images.githubusercontent.com/13919702/37760957-8c77131e-2db8-11e8-9dfa-fc6ac7211ff6.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/1a0068e0c0df9e134b3fbe67c0f0c87cd0f67413

Much better.

There was also a problem with the button order, which is fixed now. In text button mode the order was different than in icon button mode. 

![shortertoolnames](https://user-images.githubusercontent.com/13919702/37761833-0429c83c-2dbb-11e8-8fdf-b48773d56783.jpg)

**Comment by Draise14** [comment]
Oh my, what an amazing fix. It's the details!
