### ISSUE TITLE
Properties Editor - Transparent toggle should be in File Output

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1037]
# Issue
![bforartists_2019-07-25_09-06-55](https://user-images.githubusercontent.com/35357409/61881068-9dbc6e00-aebb-11e9-9542-44e6c674b3e7.png)

In the file output panel, you have the option to have an RGBA, RGB and other file properties concerning colour channels. This is unlinked from the transparent settings. Right now, the render transparency is in the "Film" panel in the render settings tab. In BFA1, we moved this to be with the RGBA settings in the file output. Can we do the same here with BFA2? 

I have already done hundreds of frames with no alpha due to forgetting to toggle the transparency in the obscure Film panel - when it should an Alpha colour channel toggle for RGBA file output settings. 

I am not the only one who gets it lost - I am sure we all have struggled to output alpha though we apply it intentionally by choosing RGBA in the file colour channels. 

# Solution
Move the Transparent toggle to File>Output panel.

**Comment by ReinerBforartists** [comment]
Not this easy. The workbench rendering has just this item in the film panel. But yeah, we need to investigate here.

![workbench](https://user-images.githubusercontent.com/13919702/61888874-a2f1db00-af04-11e9-9f19-8336abac0670.jpg)

**Comment by ReinerBforartists** [comment]
As told, a bit more complicated. With cycles you have some sub panel settings ...

Need to think a bit more about this. Postponing.

![transparent](https://user-images.githubusercontent.com/13919702/62024914-db303c80-b1d6-11e9-853e-2ba92b6bffdd.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![transparent](https://user-images.githubusercontent.com/13919702/67616227-91a3bd80-f7d6-11e9-87e0-504523508d29.jpg)

**Comment by ReinerBforartists** [comment]
Something went wrong here. Cycles transparent settings are back in the film panel. 

Reopen this issue.

**Comment by ReinerBforartists** [comment]
Fixed in master
