### ISSUE TITLE
Node Editor - Input shelf has Principled Volume missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1039]
# Issue
![bforartists_2019-07-30_12-41-50](https://user-images.githubusercontent.com/35357409/62152261-c8e1fb80-b2c7-11e9-8254-9da33e126c6c.png)
Right now the new Principled Volume node is missing from the input panels in the Material Node Editor. 

# Solution
- Add the Principled Volume somewhere

**Comment by ReinerBforartists** [comment]
There must be more than this shader missing. I remember we have now a principled hair shader too somewhere.

So first step is to go through the shaders, and check for all missing ones.

**Comment by ReinerBforartists** [comment]
Let's add this button. Then check for more missing stuff.

**Comment by ReinerBforartists** [comment]
Haven't found anything obvious. So i hope this was the only one.

Fixed in master
