### ISSUE TITLE
Broken scripting functionality

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1042]
The newest merge has killed the ability to open the UI scripts in Bforartists. In Blender everything still works as thought.

Needs investigation.

![brokenscriptingfunctionality](https://user-images.githubusercontent.com/13919702/62280771-dbd20880-b44c-11e9-92e2-ebffd311a142.jpg)

**Comment by naetherm** [comment]
Does the file exist at the proposed filesystem location?

**Comment by ReinerBforartists** [comment]
Of course. It's the UI files of Bforartists. They don't vanish ^^

It's about the edit source functionality in the right click menus of buttons.

![editsource](https://user-images.githubusercontent.com/13919702/62281152-89451c00-b44d-11e9-90c0-2d7809cc3e18.jpg)

**Comment by Draise14** [comment]
Is this for any addon panel? 

What are the steps to reproduce this?

**Comment by ReinerBforartists** [comment]
Go to scripting layout. Right click at any operator, choose edit source. Normally the code should then open in the scripting editor. It throws an error instead.

This works fine in the last developer build from sunday.

**Comment by Draise14** [comment]
I cannot reproduce. I tried top toolbar, the properties editor, panels, the headers, everywhere. I can't pull the error. I merged and compiled yesterday. Should I fetch master, pull and build again to test again? Has much changed from yesterday?

**Comment by ReinerBforartists** [comment]
Yeah, been there already. But that's just the end that throws the error. We need the cause.

**Comment by naetherm** [comment]
@Draise14 are you investigating that issue? Otherwise I could take a look into it but unfortunately I don't have time until two weeks from now.

**Comment by ReinerBforartists** [comment]
I am investigating. But without luck so far.

**Comment by naetherm** [comment]
> I am investigating. But without luck so far.

Okay, then the assignment is still correct. I was a bit confused about @Draise investigating although you are assigned.

**Comment by ReinerBforartists** [comment]
Nailed it down to a Blender bug.  I have tested it with Blender 2.80 final. Here it worked. But i had not tested it with the version that i have pulled at wednesday. Here it failed. The newest buildbot build works fine again. And also compiling this Blender version results in a working solution.

So the fix here is, merge the newest changes. And the bug should vanish.

Merging ...

**Comment by ReinerBforartists** [comment]
... and still at merging. Moar easter eggs ... -.-

**Comment by Draise14** [comment]
@naetherm Yeah, I just was curious and "helped". haha! Reiner is assigned to this one. 

What other easter eggs are we finding?

**Comment by ReinerBforartists** [comment]
All defaults are gone. Addons and User Pref settings.

As told, still at merging.

**Comment by ReinerBforartists** [comment]
Great. Seems that these settings are not longer stored with the startup.blend. But where now? O_O

**Comment by Draise14** [comment]
For being "opensource" - figuring out all these changes to the sourcecode is really hard to track. -_-

**Comment by ReinerBforartists** [comment]
That's development ;)

There's still the log.  And that's where i found the problem now. This problem is definitely something bigger. They indeed don't store the infos in the startup.blend anymore. That's a change in the system. Not even a bad one. It's about time that they use proper preset files instead of storing the settings in this unexpected way. The bad part is the lack of proper comments, as usual. So called self explaining code  -.-
 
Either way, we have to solve it. Maybe we can add some useful comments in the code. This commit seems to be the trouble maker. Now let's find out what is what. I am still lost where they store the active addons now:

Revision: 07499c04f6126b325e1d6db68e430f36b514b355
Author: Campbell Barton <ideasman42@gmail.com>
Date: 30.07.2019 03:04:02
Message:
Preferences: don't store preferences in the startup

Simplify preferences by removing the ability to load them from
either the startup.blend or userpref.blend.

Also simplifies updating default preferences by moving
them to a struct definition.
----
Added: release/datafiles/userdef/userdef_default.c
Modified: source/blender/blenkernel/BKE_blendfile.h
Modified: source/blender/blenkernel/CMakeLists.txt
Modified: source/blender/blenkernel/intern/blendfile.c
Modified: source/blender/blenloader/BLO_readfile.h
Modified: source/blender/blenloader/intern/versioning_defaults.c
Modified: source/blender/windowmanager/intern/wm_files.c

**Comment by ReinerBforartists** [comment]
This task here is fixed with this commit into sync_blender_master branch

https://github.com/Bforartists/Bforartists/commit/8ba00dc384f5b840e297b60bd8bd6f50c96fc992
