### ISSUE TITLE
Keymap - Ctrl+G and Alt+G to Group/Ungroup nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1053]
## Issue
![bforartists_2019-08-06_16-23-16](https://user-images.githubusercontent.com/35357409/62578338-80e24c00-b866-11e9-8951-d45699077a52.png)

Right now to make node groups you have to go to the header, to a sub menu, then hit the operator. I think in BFA1, this hotkey was present as CTRL+G and ALT+G to ungroup. 

## Request
Can we ad these hotkeys CTRL+G to make group and ALT+G to ungroup?

**Comment by ReinerBforartists** [comment]
Those hotkeys never existed in BFA1. Again here, please always use a vanilla installation. Not your custom keymap.

We have the Relations tab for this. One click at top level UI. No need to dive into the menu.

This taks is invalid. Closing.

![groupfunctionality](https://user-images.githubusercontent.com/13919702/62599042-75853400-b8eb-11e9-87f5-4d8df89047a3.jpg)

**Comment by Draise14** [comment]
I forgot about this panel. I will pin it as a workflow now, it's a better solution.
