### ISSUE TITLE
Keymap - Tab to toggle node group

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1054]
## Issue
![bforartists_2019-08-06_16-25-54](https://user-images.githubusercontent.com/35357409/62578510-ed5d4b00-b866-11e9-8061-321865883c08.png)

In Bforartists 1 and in Blender, you can hit tab to toggle a group. Right now you have to go into the header, submenu, then hit the operator to exit a group view (or go to a header button). 

![bforartists_2019-08-06_16-29-46](https://user-images.githubusercontent.com/35357409/62578703-6c528380-b867-11e9-96b4-e80164a93acb.png)

You also have to hit an icon on the node group to enter it and at far distances this is near impossible. 

Now, for consistency sake:

- the Sequencer has **Tab** to enter strip groups
- The NLA has **Tab** to enter active animclips (keyframe groups)

I think it should be expected that **Tab** do the same to enter node groups.

## Request
Add **Tab** to toggle node group and enter/exit node group.

**Comment by ReinerBforartists** [comment]
This functionality does not exist in BFA1. We have the hotkey in the NLA, but not in the Node editor.

Draise, could it be that you use your custom keymap again here? This is highly dangerous! I cannot trust you here anymore. We had this problem once, and i have then spent weeks to fix things afterwards after you did a commit to the keymap. Please always check with a vanilla version.

Closing. Task is invalid.

![notabinnode](https://user-images.githubusercontent.com/13919702/62598478-c98f1900-b8e9-11e9-9b3a-6ee5f501789c.jpg)

**Comment by ReinerBforartists** [comment]
Just realized that you might use the FULL keymap in BFA1. But the official keymap is the reduced. 

In general and as a design goal, Bforartists tries to get rid of as many hotkeys as possible. Not to add even more. When you need hotkeys, then chances are that we need to improve the UI in this area. And when you still need hotkeys, then you as a user should assign it by yourself.

**Comment by Draise14** [comment]
Dammit, right yeah. I used the full BFA keymap as it was what it came with. I guess I am missing it as the UI still is a WIP.
