### ISSUE TITLE
Outliner - add collection icon needs consistency throughout UI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1055]
## Issue
![PureRef_2019-08-06_16-33-29](https://user-images.githubusercontent.com/35357409/62578932-03b7d680-b868-11e9-89a2-707b5c8e80b0.png)
Right now there are three ways to add a new collection. 
1. In the header of the outliner (correct icon)
2. In the Object menu for collection (incorrect icon)
3. Right click context menu in outliner (incorrect icon)

## Request
To make them all the same icon: "Add Collection" for consistency.

**Comment by ReinerBforartists** [comment]
We have a ton of such double icon entries thanks to the Blender developers. The most prominent example is the light bulb, which exists five or six times in the sheet. Will be tackled when the icons are ported.

Postponing.

**Comment by ReinerBforartists** [comment]
Related task: Redo the icons - Row by row #1009

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/67376698-e223dc80-f584-11e9-875c-a2605764bd4d.jpg)
