### ISSUE TITLE
Outliner - Object Collection Management entries don't exist in outliner

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1056]
## Issue
![PureRef_2019-08-06_16-36-57](https://user-images.githubusercontent.com/35357409/62579102-80e34b80-b868-11e9-9cb0-0c34ee4604f7.png)

Right now in the outliner, you have object control by either drag and drop, or right click to select or delete. But there is no button to remove from a collection - though the operators exist to do so. 

In the object mode under the Object>Collection - you do have some operators to control how objects are handled inside a collection, like adding the selection to current and removing it. 

## Request
These operators should also be in the Rclick context menu of the outliner. 

### Observations
I know there is an outliner branch being working on for Blender, but I was wondering if these could be fast-tracked. I also not sure if these are added to the outliner GSOC branch. 

I'm also not sure if these are context sensitive to the view they run in, meaning these might not be useable in the outliner at all.... This could be a dud.

**Comment by ReinerBforartists** [comment]
Isn't the delete button already deleting the selected object? Why add a extra delete button?

**Comment by ReinerBforartists** [comment]
Waiting for the changed Outliner, which will come wiht Blender 2.81. Postponing.

**Comment by Draise14** [comment]
> Isn't the delete button already deleting the selected object? Why add a extra delete button?

"Remove from collection" is not delete, just.. move selected object/all/unlinked out of the collection. I would also consider that icon incorrect.

**Comment by ReinerBforartists** [comment]
Okay, let's see what the changes to the outliner introduces :)

**Comment by ReinerBforartists** [comment]
Let's see if this is even possible and necessary.

**Comment by ReinerBforartists** [comment]
This doesn't work. 
Move and link to collection and add and remove from active does simply not work in the outliner menu. Delete does already remove the selected object.

The only interesting point would be remove from all collections. But this doesn't work neither.

Closing, nothing to fix here.

**Comment by ReinerBforartists** [comment]
Hm, move and link to collection would work from a dropdown menu.

**Comment by ReinerBforartists** [comment]
I have added it as a header menu now. Minus two menu items. Delete is already in the right click menu. And create collection is already in the header.
Not so sure about the last two menu items. But they make the same disfunctional nonsense than in the 3D view menu. So keeping it for now.

![headermenu](https://user-images.githubusercontent.com/13919702/68527500-d60b7f00-02e7-11ea-813d-30ff927b5f9c.jpg)

**Comment by ReinerBforartists** [comment]
Reopen it, forgot an important bit.

Now that we have the menu in the outliner means that we have a double menu entry. And that we need to remove one of it. 

We have implemented it into the outliner, which is the better place to deal with collections. So away with the one in the object menu.

**Comment by ReinerBforartists** [comment]
Reread the remove from collection part. Hmm, need to check this one again.

**Comment by ReinerBforartists** [comment]
Remove removes the object completely. It is not put up one hierarchy.

**Comment by ReinerBforartists** [comment]
Fixed in master
