### ISSUE TITLE
3D View - Clear Parent icons inconsistent with Toolbar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1057]
#  Issue
![bforartists_2019-08-08_11-36-09](https://user-images.githubusercontent.com/35357409/62721008-e4888880-b9d0-11e9-9a8a-eece0d101919.png)

The Alt+P clear parent operator in the toolbar has correct icon - but elsewhere in the UI it's incorrect. Right now it shows a "delete" icon. It's confusing. 

# Solution
Make the clear parent icon consistent throughout the UI.

**Comment by ReinerBforartists** [comment]
Good find. Will be solved when we are through with recreating the icons.

https://github.com/Bforartists/Bforartists/issues/1009

**Comment by ReinerBforartists** [comment]
Already fixed with an icon improvement

![alreadyfixed](https://user-images.githubusercontent.com/13919702/67374098-0087d900-f581-11e9-8bb7-a6697f2ee4ff.jpg)
