### ISSUE TITLE
Keymap - BFA full keymap for professionals

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1058]
# Issue
Right now the Industrial Keymap, Blender official and Bforartists default now has minimist keymaps, which has been a good start to learn a software and lean more on the GUI to understand a software - which will be great for future tutorials. 

But now for a professionals who has learnt all the default hotkeys and the UI may still want to optimize the work - as they have with 2.79 and BFA1 full era levels of complete keymaps. 

**Examples:**
- Shift+G to hit a menu to select children without moving away from viewport
- Tab to toggle groups without needing to move away from the node viewport
- Alt+C to convert curve to mesh and viceversa
- M to move to collection/layer
- etc

The reason why hotkeys exist is to optimize ergonomics with a mouse cursor - even if the operator is in the UI somewhere, exposed, or as it should be. 

# Solution
Like in Bforartists 1, there was an optional shipped hotkey map which included the minimist map and **full** keymap for most operators. To add this back would be great.  

Maybe rename this keymap "Pro" could work. 

## Reasons
- though there are many hotkeys, which can have hundreds of entries - it was handy to learn with time for professional use to cut milliseconds away from navigating header menus and sub menus (instead of multiple mouse zigzag movements with one hand you can use a muscle memory hotkey from a left hand + short straight line on the right hand if in a floating panel).  
- It's more consistent through the editors (like Shift G in some editors to select similar but not in all editors is an issue with the mini-mist keymaps right now)
- it gives people the option to not need to customize and get full key access if necessary (right now, to have a professional access to an already great UI, you'd need to set hundreds of hotkeys per editor yourself, every single time you install or use it on another machine at work, or with others. You can't just have anyone download, switch to the pro keymap, and work. They might program their own keymaps differently, so working with others who also work in this method becomes a little slower)
- It is secondary, and should be, but it is an optimization ultimately.  
 
### Extra notes
I can do this one if it seems like a chore. I've been needing it for work, as work slows down to reprogram or copy keymap entries from Blender - and again once I have an update from the default BFA keymap.

**Comment by ReinerBforartists** [comment]
I would vote to use the industrial keymap then instead. But yeah, nothing to say against a bfa full keymap :)

**Comment by Draise14** [comment]
The industrial Keymap is also minimal, as mentioned. So there is no "full" map other than Blender 2.79 right now.

**Comment by ReinerBforartists** [comment]
For good reason ;)

I don't see the need for a full keymap. But when you eagerly need one, then i am not against it.

**Comment by ReinerBforartists** [comment]
Any news here?

**Comment by ReinerBforartists** [comment]
I guess we can close this task. I won't do it. And there is no movement. 

Closing.
