### ISSUE TITLE
Keymap - Fusion Industrial Compatible into Bforartists

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1059]
# Issue
![bforartists_2019-08-08_12-17-05](https://user-images.githubusercontent.com/35357409/62724095-cd00ce00-b9d7-11e9-8b1b-bca2edf18331.png)

Right now BFA keymap is somewhat consistent with general 3D apps as it was it's original goal - and also it worked on ergonamizing the viewport with less modifiers to interact, but now there is another industry compatible keymap introduced in Blender 2.8 which has had some work on studied consistency. 

Key differences are some general hotkeys for UI features and F to focus on selected. 

# Solution
Fusion the Industry Compatibly keymap to Bforartists and resolve conflicts in the BFA keymap preserving priority functionality.

- Keep priority on viewport navigation
- Keep double rightclick on context menus where relevant to preserve the former
- Preserve other high priority hotkey interactions

## Reason
- So that we are still up to date and artist friendly with most tools the industry and other artists use based on other peoples work.

**Comment by ReinerBforartists** [comment]
I am against throwing out the BFA keymap. We have resolved most hotkey conflicts there. And BFA users are used to it. While i am not sure what conflicts are still in the industrial keymap.

When somebody wants to use the industrial keymap, then he can already do so.

Won't fix.

**Comment by Draise14** [comment]
Yeah, I wasn't thinking of throwing BFA out, just fusioning one to the other and keeping key aspects of the BFA map. They already are somewhat similar. 

But oh well, all good.

**Comment by ReinerBforartists** [comment]
But in some aspects completely different. As told, our keymap is already stable. Every change can introduce inconsistencies again. And the industry keymap has some things that i dislike.
