### ISSUE TITLE
Default Theme - Panel Parent Header colour to Child background needs to be different

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1060]
# Issue
![bforartists_2019-08-09_16-42-54](https://user-images.githubusercontent.com/35357409/62810821-e03d9780-bac4-11e9-8d80-5136b2a5060f.png)

Right now, the header of a panel is a good dark grey, but now children collapsable headers are also dark grey. They are confusing as it is not clear what the hierachy is - so when you collapse a parent panel, a lot of panels you thought were open dissappear. 

# Solution
Maybe change the children panel header and/or background colours on default.

**Comment by ReinerBforartists** [comment]
I tried to find a good balance here before. But wasn't really succcessful.

**Comment by Draise14** [comment]
Where are the entries for this one? I tried figuring it out but couldn't find it.

**Comment by ReinerBforartists** [comment]
Woah, i can't remember, sorry ^^

**Comment by Draise14** [comment]
Ah.. I'll duplicate and botch the theme while I turn everything pink to find it, haha.

**Comment by ReinerBforartists** [comment]
Fixed in master

You can just influence the transparency against black. So there is not really a good solution. But we have the same value everywhere now.

![fixed](https://user-images.githubusercontent.com/13919702/67558924-3612fa80-f718-11e9-8658-13ad035fbe25.jpg)
