### ISSUE TITLE
Quick Favorites - Add icons to added entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1063]
# Issue
![bforartists_2019-08-10_12-06-22](https://user-images.githubusercontent.com/35357409/62824696-804bfd00-bb67-11e9-8e2c-769b27f87944.png)

Right now the Quick Menu in the header has no iconology with the operators that do - meaning.. it's still not that visually useful and have to revert to old "read the operator" to understand them - making things slow. 

# Task
- Investigate how the entries are added to the quick menu
- See if the same operator icons can be also added

**Comment by ReinerBforartists** [comment]
Most probably mission impossible. This custom menu does not allow icons from what i know. But we will see when we investigate.

**Comment by ReinerBforartists** [comment]
There is simply no way. The design does not allow it. Closing.
