### ISSUE TITLE
3D View - Edit Mode - Subdivide Edge Ring has a white background on icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1064]
# Issue
![bforartists_2019-08-10_13-45-13](https://user-images.githubusercontent.com/35357409/62825666-35d17d00-bb75-11e9-8bcd-95c8a98cf74f.png)

**Edit Mode > Edge > Subdivide Edge Ring** has a white background on icon. 

# Solution
Remove the white background (make it transparent) in the icon sheet and regenerate it.

**Comment by ReinerBforartists** [comment]
Fixed with this commit: https://github.com/Bforartists/Bforartists/commit/4ea1e7245a9504c1056bd97900fb8808c443be67
