### ISSUE TITLE
3D View - Object Type Visibility needs iconology and alignment

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1065]
# Feature Request
![bforartists_2019-08-10_15-17-38](https://user-images.githubusercontent.com/35357409/62826488-168d1c80-bb82-11e9-9032-a9a8c6496c32.png)

Right now the Object Type visibility has a list that is... not aligned, for starters, and can have the type icon added (eg. lamps shows a lamp, objects show an object, etc)

It's a C menu from what I see, so **VIEW3D_PT_object_type_visibility** would be the one to dig for. 

# Task
- Align text Left
- Add type icons Left of text

**Comment by ReinerBforartists** [comment]
Most probably related

https://github.com/Bforartists/Bforartists/issues/1072

**Comment by ReinerBforartists** [comment]
Icons are impossible with the current code. And also the alignment is a special problem, which i solved with some cheating for now.

Fixed in master

![aligned](https://user-images.githubusercontent.com/13919702/63503013-f9841200-c4ce-11e9-8a74-dd710b8f2180.jpg)
