### ISSUE TITLE
Outliner -  keymap manager - wrong icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1075]
The expand collapse icons are wrong in the outliner.  Left BFA1, right what we have now.

![wrongicons](https://user-images.githubusercontent.com/13919702/63364837-a8f9a100-c376-11e9-91b0-8d3d8cd1d00c.jpg)

**Comment by Draise14** [comment]
I've always wondered if this was on purpose or not. It has thrown me off.

**Comment by ReinerBforartists** [comment]
You can always report such issues :)

**Comment by ReinerBforartists** [comment]
Okay, this is two issues. The one is the usual crap that the Blender devs doesn't define the icon name, but uses some nerdy algebra to define the next icon. And when the order doesn't fit then the wrong icon gets displayed. The other is, they have removed the plus and minus signs, and added the tri buttons instead.

For now i want to keep the plus minus buttons. Improvements are a different task. So let's switch the order of the icons, and then everything should fit again.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/63412559-43e68f80-c3f8-11e9-9763-4657951ff9d0.jpg)
