### ISSUE TITLE
Keymap - Node Editor - check broken functionality

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1076]
# Issue
Right now I have troubles with daily work with node manipulation in the BFA keymap, and a friend of mine trying out both Blender and BFA for the first time has found a couple of issue and found it actually more intuitive in Blender due to a couple of reasons: 

Here are the notes: 
- Dragging on a node output/input will move the tree instead of spawn a connection line to connect, often (it's not garunteed this works 100% of the time, which is annoying)
- You cannot resize a node even when the cursor turns to "resize", right now it's near impossible to resize from an edge/corner, selected or unselected. 
- Clicking off a node does not deselect it

# Task
Add back "Deselect on Nothing" on Select
![bforartists_2019-08-20_13-52-59](https://user-images.githubusercontent.com/35357409/63375909-4393b900-c352-11e9-8853-24f62ac0d874.png)

Add back Tweak Left on Resize Node
![bforartists_2019-08-20_13-55-22](https://user-images.githubusercontent.com/35357409/63375905-4098c880-c352-11e9-8eee-26b017337842.png)

This fixes the resize issue, it fixes the node connection spawning issue and adds the function of deselecting when you click off a node (instead of dragging a tree by accident)

**Comment by ReinerBforartists** [comment]
Good catch. Seems that we need to check the full keymap at one point again.

**Comment by ReinerBforartists** [comment]
Fixed in master
