### ISSUE TITLE
Addon - Stored View - Missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1085]
![bforartists_2019-09-02_15-42-00](https://user-images.githubusercontent.com/35357409/64132861-54075300-cd98-11e9-86df-d6ad0e3f787a.png)

# Issue
There are some missing icons that case console errors in the Store Views addon (used to save cameras). This may be due to how Bforartist handles some icons. 

![bforartists_2019-09-02_15-43-28](https://user-images.githubusercontent.com/35357409/64132878-6d100400-cd98-11e9-9b44-9deef3e30fea.png)

## Solution:
Fix is simple, just change the lines reported, but.. it's an addon.

**Comment by ReinerBforartists** [comment]
Unfunny.

We need to readd this icon.

**Comment by ReinerBforartists** [comment]
Just curious, you just documented ONE missing icon. But talk about more than one. Could you please document the others too?

**Comment by ReinerBforartists** [comment]
Fixed in master

Found just one so far. Please make a new issue for other icons.

![storedviewfixed](https://user-images.githubusercontent.com/13919702/64148937-e5240b80-ce24-11e9-9341-9a0864242a3a.jpg)
