### ISSUE TITLE
Outliner - right click collection - remove View Layer menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1087]
The current icons does fit to the confusing Blender python operator names. But the icons does not fit to the functionality. You enable or disable the collection. And so we need a enable and disable icon here.

At least they have meanwhile fixed the menu names.

![disable](https://user-images.githubusercontent.com/13919702/64168525-04825f00-ce4c-11e9-9812-90639e00b8ee.jpg)

**Comment by ReinerBforartists** [comment]
The hotkey system is fubar anyways. So let's ignore it.

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by Draise14** [comment]
you can assign the hot key to the outline entry in the ui right?

**Comment by ReinerBforartists** [comment]
Yes. But why would you want to hotkey this? It's one click.
