### ISSUE TITLE
Navigation elements, rearrange them horizontal

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1090]
The newest merge arranges the navigation elements vertical. This is not good. Now you might come accidentally at the controls.

Realign it horizontally.

![notgood](https://user-images.githubusercontent.com/13919702/64608871-e4aee600-d3cb-11e9-8785-3c6d97443c81.jpg)

**Comment by Draise14** [comment]
At first I thought it was a good idea. But we have minimized the headers so it's not cluttering now. maybe their later iterations will make sense.

**Comment by ReinerBforartists** [comment]
Or we find a way to let the user decide the arrangement. I don't like the current arrangement.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/65942260-3677e880-e42d-11e9-8b1f-317443042534.jpg)
