### ISSUE TITLE
Edge menu - remove loop cut and slide down to Bridge Edge Loops

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1097]
Seems that the Blender developers finally realized that it is a bad idea to have the old tools and the new tools in the viewport. They removed the edge tools from the edge menu that are in the tool shelf.

We should do the same. Means tools that can be found in the tool shelf already doesn't deserve a menu entry anymore.

We have also two other issues here. Bridge Edge Loops is a double entry anyways. And Loop Cut and Slide shows another hotkey when you perform the tool. Funny behaviour.

![doubletools](https://user-images.githubusercontent.com/13919702/64924590-aa3bb380-d7e6-11e9-8818-cc630d9f7a0c.jpg)

**Comment by Draise14** [comment]
Oh good. I hope the toolshelf entries naming conv entions in the hotkey editor also improve. I kinda miss the old coloured icons from the headers to go into the toolshelf also (as it's more consistent, has colour coding, and I feel are more descriptive). Will those also be scheduled to be updated?

**Comment by ReinerBforartists** [comment]
Please make a individual task for each of your ideas. This task here is just to remove the obsolete operators from the menu.

We will come to color coding and icon optimizations when the icons are all converted. I am at row 25 at the moment. So we getting closer :)

**Comment by ReinerBforartists** [comment]
Fixed in master
