### ISSUE TITLE
Outliner - Confusion with Visibility Icons for Viewport and Disable functionality. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1100]
![bforartists_2019-09-17_08-57-54](https://user-images.githubusercontent.com/35357409/65048211-5e455780-d929-11e9-9926-60048356d55b.png)

# Issue
Right now there are two icons for visibility in the viewport. One to hide temporarily in viewport, and the other to disable + hide in viewport. They both are the same icon. But apparently they are different in functionality. It's confusing, feels redundant. 

## Solution and Request
These icons should be different and more symbolic of what they do to atleast feel like they are different functions (especially the Disable in Viewport one). 

### Alternatives
Remove the "Disable in Viewport" from the outliner all together as it could be a redundant feature. Visibility in Viewport is to hide it yet still render. We can do that with the Viewport Visibility. The Render disables it's rendering, but still can be visible. The select toggle dissables selectability. Disabling all those does what the "Disable in Viewport" does - almost making it redundant.

**Comment by ReinerBforartists** [comment]
Blender uses the viewport icon here. So we should do the same.

![restricticons](https://user-images.githubusercontent.com/13919702/65059033-8eb2e300-d975-11e9-98ff-d3851748bdc5.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
