### ISSUE TITLE
Context Menus - Missing Icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1101]
![bforartists_2019-09-17_09-14-39](https://user-images.githubusercontent.com/35357409/65049777-f3e1e680-d92b-11e9-80ad-e4dd297a27be.png)

# Issue
With the context menus now added to double click (which has been welcome, as staff I have had work with it prefer the double click over the single click) which has been a good move. 

But now.. there are no icons. It is inconsistent and also inefficient. 

## Solution 
Add icons to the operators to be similar to the Header menus and toolbar iconology.

**Comment by ReinerBforartists** [comment]
Shall we really iconize the not contextual context menu? ^^

**Comment by Draise14** [comment]
Well, the outliner context menu has it all iconized already - just thought it would be consistent elsewhere, as I have found myself to use it but only shy away from it because I have to read the operators.

**Comment by ReinerBforartists** [comment]
That's the plan :D

I don't want the users to use this menu really. But you can iconize it when you want. For me that's lowest priority.

**Comment by Draise14** [comment]
I guess so. Though, having everything in a header with a large screen takes up a lot of time to move mouse up then back down to use them. The context menu cuts the mouse movement time and distance to access the header menus, so it's usefulness depends on screen size. But yeah, my argument really is just to have it consistent with the rest of the UI. 

_I can do this a task... when I finish the manual when I finish client work when I find a day ... sigh._

**Comment by ReinerBforartists** [comment]
I know this feeling XD

**Comment by ReinerBforartists** [comment]
Postponed until it has a taker.

**Comment by ReinerBforartists** [comment]
Ah, what the heck, and just to get this one out of the way ...

**Comment by ReinerBforartists** [comment]
This was the easy part. Now for the sub menus ...

![submenus](https://user-images.githubusercontent.com/13919702/68069393-04c1ac80-fd60-11e9-847d-7aa29c120c42.jpg)

**Comment by ReinerBforartists** [comment]
Lattice context menu has some missing ones.

![latticecontext](https://user-images.githubusercontent.com/13919702/68112419-8f85e100-fef1-11e9-9263-aaa79a355e43.jpg)

**Comment by ReinerBforartists** [comment]
Grease Pencil in Edit mode and stroke sub mode has some missing ones 

![strokecontext](https://user-images.githubusercontent.com/13919702/68113972-46379080-fef5-11e9-87a1-a9595ba67a89.jpg)

**Comment by ReinerBforartists** [comment]
That was it.

Fixed in master
