### ISSUE TITLE
General - Expand and collapse icons are very small

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1103]
# Issue
![bforartists_2019-09-17_11-45-21](https://user-images.githubusercontent.com/35357409/65062217-34982a80-d941-11e9-97a5-88f46fb20caf.png)

It's small. The collapse/expand buttons. This is true in most of the UI. When you compare it to a tick box, they are a quarter the size and the click trigger space is now not even 10 pixels wide. 

On a large screen this become troublesome, and almost has me map a hotkey to toggle these.. 

![bforartists_2019-09-17_11-56-09](https://user-images.githubusercontent.com/35357409/65062691-2bf42400-d942-11e9-94f3-0fadf2f7b1b6.png)

The crazy thing is, you can click off them in their icon space and they will still toggle. This is unexpected. 

## Solution
Size them up by 50-75%, so they are a little more consistent in size with other icon toggles (tick box, highlighted toggle icons, etc) throughout the UI.

**Comment by ReinerBforartists** [comment]
I don't want to make them too big really. But yeah, we could expand the size a bit :)

**Comment by ReinerBforartists** [comment]
Hm, we could also use triangles, like Blender does. Looks like the cleaner solution to me.

![trisorplusminus](https://user-images.githubusercontent.com/13919702/65369730-2a33a480-dc51-11e9-8d8d-cd365e175967.jpg)

**Comment by Draise14** [comment]
That could be a good solution. We have both arrow and +- circle systems in the UI, unifying the expand/collapse to the one and same could work.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

And our tris are bigger than in Blender.

![trianglebuttons](https://user-images.githubusercontent.com/13919702/65814364-01775600-e1e1-11e9-9b92-07b5695800f3.jpg)
