### ISSUE TITLE
Toolbar Editor - Screen Dimension window resize offsets editor size (when multiple)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1104]
# Issue
![2019-09-17_16-19-09](https://user-images.githubusercontent.com/35357409/65080583-47bdf100-d967-11e9-99d9-548336acf173.png)

When you open up a file from another computer (edited on a smaller screen) and load on a larger screen on another computer, the toolbar has these empty offsets. They are no-longer collapsed. 

When you resize the editor with windows hotkeys, like to the bottom corner then maximize, the toolbar will get the same offsets also. 

It seems the editor is not remembering that it is in collapsed state and dynamically and responsively resizes when the window goes bigger. 

## Solution
Make the toolbar editor always collapsed to the "header" regardless of resize in window.

**Comment by ReinerBforartists** [comment]
There is no solution. I have reported this to the Blender developers before. And they said they would need to rewrite the whole windows system for that. They won't fix it. And for us it's simply too big.

As sorry as i am, i have to close this one as won't fix.
