### ISSUE TITLE
Add menu - Nurbs Curve versus Nurbs Curve

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1105]
Different objects should not have same name. This leads to confusion. I'm an old man, and am now confused ^^

First step here to find out if it is a different object at all. Two objects affected. Nurbs Curve and Nurbs Circle.

![nurbscircleproblem](https://user-images.githubusercontent.com/13919702/65143241-c15fe880-da14-11e9-9de7-5873d925bce7.jpg)

**Comment by ReinerBforartists** [comment]
What a name mess. But yeah, it's different objects. The one is a nurbs curve. The other a surface curve.

![surface](https://user-images.githubusercontent.com/13919702/65143462-5662e180-da15-11e9-9f64-b29292be55c8.jpg)

**Comment by Draise14** [comment]
This too has confused me, and I'm in the prime of life.haha

**Comment by ReinerBforartists** [comment]
So what to rename here ...

**Comment by ReinerBforartists** [comment]
Fixed in master

Much more consistent.

![surface](https://user-images.githubusercontent.com/13919702/65813758-9a09d800-e1d9-11e9-903e-f8119558d948.jpg)
