### ISSUE TITLE
In UV Edit Mode, "Rotate and Press 9 button" Crashes!! Bforartists2 alpha!!

### ISSUE THREAD

**Issue by djmoneygirlfire** [Bforartists/Bforartists#1126]
**Describe the bug**
In UV Edit Mode, "Rotate and Press 9 button" Crashes!! Bforartists2 alpha!!

**Desktop (please complete the following information):**
Windows 10, AMD!!

**Screenshots, Example Files**
![image](https://user-images.githubusercontent.com/54245346/65823704-4f9a6100-e296-11e9-8563-0a15125336b8.png)

**Comment by ReinerBforartists** [comment]
Thanks for the report. 

I  can unfortunately not reproduce the behaviour. Here everything works as thought.

 Maybe it's a AMD graphics card related issue, which i couldn't test then. Could you please check if the same happens with an actual version of Blender? The Blender Buildbot is located here:

https://builder.blender.org/download/

**Comment by naetherm** [comment]
When BFA, just like Blender crashes, it writes out a text file which contains information that may help identify the cause of the crash.

On a crash, a file is written based on the name of the currently loaded blend-file, so ```test.blend``` will create a file called ```test.crash.txt```. The crash log for unsaved files will be written into the Temporary Directory directory.

The temporary directory is selected based on the following priority:
- Environment variables ```TEMP``` on Windows

**Comment by djmoneygirlfire** [comment]
I checked out that it was fixed in devbuild-22-09-2019!!
Fortunately it is only alpha version's problem.

![image](https://user-images.githubusercontent.com/54245346/65831454-94ed7b80-e2f4-11e9-8099-c8cce58f1ba7.png)
