### ISSUE TITLE
Object mode- rotation move and scale with wer keys is broken

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1129]
Move rotate and scale in object mode by hotkeys wer is broken. We move rotate and scale the pivot point instead.

Needs a fix.

**Comment by ReinerBforartists** [comment]
Not to find and running out of ideas. Seems that i have to follow previous commits up to the point where it has fallen apart.

**Comment by ReinerBforartists** [comment]
Devbuild from 15 and 22.09 works fine. This broke with latest merge.

**Comment by Draise14** [comment]
![ShareX_2019-10-01_04-54-34](https://user-images.githubusercontent.com/35357409/65952479-98bdf280-e407-11e9-92fe-37a2e753058f.png)

Do you have the transform "origins" turned on? Or is it off?

**Comment by ReinerBforartists** [comment]
Is off. As told, i was able to reproduce the problem. And the new merge fixes it. It was a Blender bug.

Currently at committing the results ...

**Comment by ReinerBforartists** [comment]
Fixed with latest push
