### ISSUE TITLE
Blender Ribbon Customization branch from wwestrop

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#113]
We have decided not to use Ribbons. They eat ways too much space. 

There is nevertheless an interesting Blender branch from wwestrop that mimics a Ribbon UI. We migth be able to borrow the one or another idea here. Our toolbar branch has a whole area that could be filled with functionality ...

https://github.com/wwestrop/blender/wiki/Ribbon-customisation

**Comment by Draise14** [comment]
I would be pro this if the popup properties of an operator tool would populate a ribbon and free the lower toolbar area to the bottom left side. It's annoying only seeing scrunched up tabs to the side (no matter the screen size) and having to rescale these properties (or resort to floating menu through shortcut) to get to all the properties. It also doesn't make sense.. there is a properties sidebar and a tool sidebar.. why are operator properties in the tool sidebar? A ribbon would make the properties available at a glance in its own area, and the toolbar would have fullscreen real estate making the tabs finally legible. 

![2018-03-28_14-26-14-note](https://user-images.githubusercontent.com/35357409/38052283-5a4266cc-3296-11e8-9368-a4d3fc360724.png)

**Comment by ReinerBforartists** [comment]
It would of course be nice when we could put this last operator elsewhere. Every place is better than the current location. But this area is C code. And i have yet to find out how it is implemented. I once tried to move it to the Properties editor. No way.

**Comment by Draise14** [comment]
Currently to access the properties is the in the Tool shelf at the bottom (which can collapse) and with F6 for the floating popup. 

I am suggesting, maybe having the Tool shelf duplicate into a ribbon with the code above - maybe making it into a double entry, but also maybe making it easier to access. Doesn't have to drag/place into a ribbon. 

But if it's too hard wired in, then it's ok as is I suppose.

**Comment by ReinerBforartists** [comment]
First time compile. It is based at Blender 2.76, compiled with some errors, and doesn't show the ribbon at all. What is discouraging is that there is no error message in the console. So i have no idea why the ribbon does not show.

Let's have a look to remove the compile errors, then let's decide if it is worth to invest more time here ...

**Comment by ReinerBforartists** [comment]
Narp. No way to get rid of all the errors. I guess the current libs at my system are simply too new, they are for 2.79a. It compiles, even with the errors. And the exe starts. But no ribbon in the info editor. And that's the part that i wanted to investigate and to understand. 

I could follow the commits in this branch to see what files gots changed. But that's senseless since the result isn't working as expected. And so there is no way to figure out how to do it right.

Labeling it as won't fix. Maybe somebody else wants to invest here.

![ribbon](https://user-images.githubusercontent.com/13919702/38161134-62b21cc8-34c9-11e8-9914-09f8b0bf75d4.jpg)
