### ISSUE TITLE
File Browser - remove "create new folder?" confirmation dialogue

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1139]
# Issue
![bforartists_2019-09-26_08-00-16](https://user-images.githubusercontent.com/35357409/66229799-40f1e680-e6a8-11e9-83fe-6dd5e1bc0096.png)
![bforartists_2019-09-26_08-05-19](https://user-images.githubusercontent.com/35357409/66229804-43544080-e6a8-11e9-96f0-6897d678401b.png)

Confirm to create folder? Well yes. I clicked the button to do exactly that. This dialogue box is useless and annoying. 

# Solution
Remove the confirmation dialogue

**Comment by ReinerBforartists** [comment]
It's a trap :D

**Comment by ReinerBforartists** [comment]
Fixed in master.
