### ISSUE TITLE
Properties Editor - Armature - Display - add back quick button toggles

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1141]
# Issue
Display As options: 

**Bforartist 2**
![bforartists_2019-09-30_16-35-11](https://user-images.githubusercontent.com/35357409/66230917-dbebc000-e6aa-11e9-9cf3-5cb74aed34cf.png)

**Bforartists 1**
![bforartists_2019-10-04_13-27-58](https://user-images.githubusercontent.com/35357409/66230939-e9a14580-e6aa-11e9-9167-5eb10fab5e69.png)

The issue with the bone visibility (other than not being able to do it per bone) is that now it's under a dropdown, adding a click and mouse move to quickly toggle bone visibilities. When rigging characters I find I toggle this view quite often and the extra click instead of mouse over and done is a little bit frustrating. 

It would be nice to implement the philosophy to put in quick visual toggles to a single mouseover again like in Bforartist 1, specially within these panels, and especially here in Armature Bone display.

**Comment by ReinerBforartists** [comment]
Yeah, i dislike the dropdown boxes too.

**Comment by ReinerBforartists** [comment]
Pest an cholera ...

With just expand we have tiny buttons

![expanded](https://user-images.githubusercontent.com/13919702/66382597-c8e33380-e9bb-11e9-909f-a11d22c8a8ae.jpg)

With expanded and no text we have no text everywhere ..

![notext](https://user-images.githubusercontent.com/13919702/66382626-d8627c80-e9bb-11e9-9e3a-26ef7c9e4c83.jpg)

And when we make Property.split = False then we loose the animation buttons ...

![noani](https://user-images.githubusercontent.com/13919702/66382667-eb754c80-e9bb-11e9-9d4f-cc14f0500f6b.jpg)

Postponing. Maybe we find a solution to keep the animation buttons with Property.split = False. I have no high hopes though. I tried it before, and failed.

https://github.com/Bforartists/Bforartists/issues/794

**Comment by Draise14** [comment]
Maybe we can use icons on the small buttons instead of text and then just have the tooltip?

**Comment by ReinerBforartists** [comment]
Having an idea here ... testing

**Comment by ReinerBforartists** [comment]
Fixed in master. For now.

Animate buttons are kept, and we have our button row back.

The only thing that makes me unhappy is that it is obviously a double menu entry, right besides each other. But hey. When moses cannot come to the mountain, then the mountain must come to moses. 

![doubleentry](https://user-images.githubusercontent.com/13919702/67140698-6b71a100-f25d-11e9-9272-52e44f648a43.jpg)
