### ISSUE TITLE
Tool shelf - two rows

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1145]
At least the sculpting tools needs two rows in the tool shelf. Let's fix the layouts.

![tworows](https://user-images.githubusercontent.com/13919702/66306449-f53a7980-e901-11e9-8213-2a9ffae3e732.jpg)

**Comment by ReinerBforartists** [comment]
Houston this is a bug. In Blender you can save the state of the tool shelf. In Bforartists not.

This can be everything. From reading to writing the important bit. I don't even know where this could hide.

**Comment by ReinerBforartists** [comment]
Hm, i can set this afterwards by saving the startup file. But not with the defaults. When i compile with the very same startup.blend then we have a single row again.

Will need to do some tests now with Blender if it behaves the same.

**Comment by ReinerBforartists** [comment]
Blender behaves the same. Smells like a bug. Question is if we should report it. That's the Blender defaults. I am pretty sure they don't want to change it. And so there is no need for them to fix this bug.

Let's do a test if i can work around the problem. If not i will try to report it.

**Comment by ReinerBforartists** [comment]
Not to catch. Seems that i have to ask the blender devs for help here.

**Comment by ReinerBforartists** [comment]
Already reported as a bug

https://developer.blender.org/T69002

**Comment by ReinerBforartists** [comment]
I doubt that they will fix this issue soon. So let's have a look if we can catch it. We need it for our toolbar branch.

**Comment by ReinerBforartists** [comment]
Bforartists 0.7.0 seems still to work. Let's have a look at which date it breaks ...

**Comment by ReinerBforartists** [comment]
Devbuild 01.09. is already broken. Odd one. Since BFA 0.7.0 seemed to work fine. Oh, i see lots of fun ahead here ...

**Comment by ReinerBforartists** [comment]
It's two bugs it seems. The first is with compiling with the startup file. The other is with saving the startup file. The first may fail, while the other still works. Blender from 25.08 is such a case. Unfunny.

So first let's catch at which point the compiling with the startup file fails.

**Comment by ReinerBforartists** [comment]
Can't go far enough backwards to find the flipping point with compiling the startup.blend. I use VS 2019 here now. And everything before 25.07 fails to compile with an audaspace problem.

Let's have a look if we can catch the second issue. Maybe this will open a path to find the first one.

**Comment by ReinerBforartists** [comment]
Not to catch. But made an observation that may lead to a solution. When you save the startup file before you saved the current settings in the splash screen then the state will be lost. When you first save the current settings in the splash screen and save the startup file afterwards, then the state of the tool shelf will be kept.

**Comment by ReinerBforartists** [comment]
Managed to go back to a working version. Current state:
30.07 - works
31.07 - works not

So the commit in question who has messed this up is somewhere in the commits from 31.07.2019 in the Blender repository.

**Comment by ReinerBforartists** [comment]
That's the rewrite of the storing system, and introducing the userdef_default.c

This fish is too big for me. That's something that the Blender devs have to fix. Postponing.

> The problem appears at the commits from 31.07.2019. The commit from 30.07 are fine. The commits from 1.08 have the problem. I can unfortunately not get any closer since the commits from this day does not compile with Visual Studio. It throws errors with FFmpeg and another file, which gots fixed later at this day. But one special commit jumped into my eyes here. Better said two.
> 
> 31.07.2019 - Cleanup: remove BLO_update_defaults_userpref_blend
> 31.07.2019 - Preferences: don't store preferences in the startup
> 
> This is a rewrite of how some settings are stored. And that's where storing the state of the tool shelf rows may got lost. My C fu is unfortunately too weak to fix the problem. But i hope the informations can be of use.

**Comment by Draise14** [comment]
Where is the userdef_default.c kept?

**Comment by ReinerBforartists** [comment]
release\datafiles\userdef

**Comment by ReinerBforartists** [comment]
This is no bug, but intended. See here

https://developer.blender.org/T73688

**Comment by ReinerBforartists** [comment]
Okay, this can easily be fixed with reverting this commit here: https://developer.blender.org/rB255615867c1751eb94d6cb4428458c988fcdca53

Will go through the layouts now and create a new startup.blend with two rows where possible and needed.

The active button in the tool shelf is then another chapter. Still at investigating.

**Comment by ReinerBforartists** [comment]
And finally fixed in master
