### ISSUE TITLE
Implement buttons for Radial Control hotkeys

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#115]
We have made two buttons for radial control in the sculpt mode. That way the user knows this functionality exists, and can set the brush size with the hotkey then. The button shows the hotkey. And here you can also change it then.

But we haven't implemented it in the other modes where you can set a brush size or strength. And the keymap contains quite a few of them.

Task: add a radial control button to the corresponding sliders.

![radialbuttonsvertexpaint](https://user-images.githubusercontent.com/13919702/38132741-aebc245a-340c-11e8-9756-181f484e1b27.jpg)

![radialcontrols](https://user-images.githubusercontent.com/13919702/38132747-b2047838-340c-11e8-9fc3-0cdb482b9a68.jpg)

**Comment by Draise14** [comment]
What happens to the "activate pen sensitivity" button? These sliders can be toggled to use the pen pressure. That is the finger icon. Are you replacing them?

**Comment by ReinerBforartists** [comment]
No. This button is also important.

**Comment by ReinerBforartists** [comment]
Grease pencil section done. Fixed in workflow branch.
https://github.com/Bforartists/Bforartists/commit/cdb704a3b705fe2ecbad8e162a6f4d32aead3c6e
The eraser size had no visual entry in the UI yet. Losing a line here. But we need to add it somewhere. And it should not be too far away from the eraser.

![greasepencil](https://user-images.githubusercontent.com/13919702/38161656-90712032-34d3-11e8-8327-8b8c0f723538.jpg)

**Comment by ReinerBforartists** [comment]
The paint panel is a unified prop, for all painting panels. This one is getting pretty complicated now.

**Comment by ReinerBforartists** [comment]
Ah, need to fix the erasersize entry. We need a separator here ...

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/ab272bc7ccc1b40297d44817c56f85218747f904
![eraserpositionfixed](https://user-images.githubusercontent.com/13919702/38161870-f7da1c4e-34d6-11e8-9f05-86a0f26c0f8b.jpg)

**Comment by ReinerBforartists** [comment]
Texture painting - fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/c5f812a2648a6261f64e771240ba57aac70b5694
![texpainting](https://user-images.githubusercontent.com/13919702/38165327-e8d2729c-3511-11e8-9298-d02957774259.jpg)

**Comment by ReinerBforartists** [comment]
I knew it will make trouble. Now the radial button from texture paint shows up in vertex paint. And is of course disfunctional -.-

**Comment by ReinerBforartists** [comment]
Problem solved in this commit:
https://github.com/Bforartists/Bforartists/commit/dc4e9fc543d783da7767496e386c30bc58c6684d

**Comment by ReinerBforartists** [comment]
Vertex paint buttons fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/d254f5c5711634d267fb79ea4d1ad51e7a338bd0
![radialvertex](https://user-images.githubusercontent.com/13919702/38188385-1bb75862-365c-11e8-8ae8-0047da2f86a8.jpg)

**Comment by ReinerBforartists** [comment]
Weight paint fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/ccf1a335ba91cbb4d251ae249f97213c753a8891
![radialweightpaint](https://user-images.githubusercontent.com/13919702/38188657-2d8c475e-365d-11e8-9391-861e6fd4cf25.jpg)

**Comment by ReinerBforartists** [comment]
Sculpt fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/a77a276465f3cef48f91a7ac6ca7d68e23fece21
![sculptradial](https://user-images.githubusercontent.com/13919702/38189095-d5c6c588-365e-11e8-80c5-18b5cdc3236a.jpg)

**Comment by ReinerBforartists** [comment]
And last but not least, UV sculpting. Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/e4ca44ebbf650e5b1c1babeb921f1070f77a59ef

There is unfortunately no slider for this available. So just the buttons for the hotkeys ...

Task done. Closing.

![uvsculptradial](https://user-images.githubusercontent.com/13919702/38190150-44f73ca4-3663-11e8-9d75-c0868dbf0953.jpg)
