### ISSUE TITLE
Re-release Alpha 2 - 0.7.1 with Denoiser

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1162]
## Issue
The openimage denoiser is a strong feature that people look for from Blender 2.81 and would love to have in Bforartists 2. 

But due to a cmake change, it was disabled by default. 

But now it's fixed. But.. it's not accessible to those who just want an installer. 

![image](https://user-images.githubusercontent.com/35357409/66865701-68c13400-ef5d-11e9-8482-e7eec16fb5d7.png)

## Solution
Maybe we can.. release a 0.7.1 binary version that includes the latest updates and also the OpenImage Denoiser?

**Comment by ReinerBforartists** [comment]
We can't release an official build with every new Blender feature. That's why we have the Devbuild. And the Devbuild has it on already.

Blender 2.81 will be released within the next three or four weeks anyways. So let's wait this few days.
