### ISSUE TITLE
Toolbar - Missing icon in Misc

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1163]
# Issue
![bforartists_2019-10-15_17-11-52](https://user-images.githubusercontent.com/35357409/66874440-b6936780-ef70-11e9-94a8-b5bbaa8fa7ce.png)

A typo in the **space_toolbar.py** file cause console error on icon find
EMPTY_SINGLEARROW

Should be:
EMPTY_SINGLE_ARROW

# Fix
Should be:
EMPTY_SINGLE_ARROW

**\\Bforartists\release\scripts\startup\bl_ui\space_toolbar.py**
Line 778

**Comment by Draise14** [comment]
I labeled this as fixed as it's committed, and I have pulled it.. not sure when I'll close? I'll let you close after revision I suppose.

**Comment by ReinerBforartists** [comment]
You have fixed it in the code and did a commit. So you can close it. The pull request is another separate chapter then.
