### ISSUE TITLE
Check Animation Nodes addon

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#117]
There's a report for a not working addon. Animation nodes.

https://github.com/JacquesLucke/animation_nodes

**Comment by ReinerBforartists** [comment]
See this thread: https://www.bforartists.de/content/cant-install-animation-nodes-bforartists-096#comment-8366

**Comment by Draise14** [comment]
Version 2.1 works with Python 3.6, have tested in BFA 0.9.6 without a problem and works. Version 2.0 is compiled with Python 3.5 so won't work with latest release of BFA. 

https://github.com/JacquesLucke/animation_nodes/releases

**Comment by ReinerBforartists** [comment]
Perfect. Thanks for checking.

Closing.
