### ISSUE TITLE
Tool shelf - tooltips

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1171]
We have a problem with our tool shelf versus what Blender offers regarding tooltips

The curious part is, it seems to be dependant of the chosen keymap. Even in Blender. So we need to investigate here why our keymap does not display the hotkey for box select, but Blender does.

This is something for the tool shelf branch.

![missingtooltipcontent](https://user-images.githubusercontent.com/13919702/67005599-40fbd880-f0e3-11e9-8ca8-79e23399ad88.jpg)

**Comment by ReinerBforartists** [comment]
Hm, we could even report this as a bug to Blender. Would save us quite a bit of work.

**Comment by ReinerBforartists** [comment]
https://developer.blender.org/T71423

**Comment by iyadahmed** [comment]
started going through old tasks,
this one seems to be fixed now?

**Comment by ReinerBforartists** [comment]
Ah, yes, indeed. Let's close it :)
