### ISSUE TITLE
Properties - Increase Volumetric Samples and Shadow Samples limit

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1173]
## Issue
![bforartists_2019-10-18_18-13-24](https://user-images.githubusercontent.com/35357409/67133638-5ea86b00-f1d3-11e9-9510-ccd2b37b1983.png)

Properties Editor > Render Tab > Volumetrics

Right now the Eevee volumetric samples are capped to 256 volume samples max and 128 shadow samples max. With 128 shadow samples, regardless of normal render samples and volume samples maxed out, will almost always create strobing artifacts due to the lack of shadows samples when you move the camera in animation. 

Example:
https://imgur.com/uPNpMo1

## Solution
Upping the volume samples (optional) and shadow sample cap to double or the same level may remove the prominince of this issue. 

File: 
\\Bforartists\source\blender\makesrna\intern\rna_scene.c

**Comment by Draise14** [comment]
I'm compiling a build to see if that helps mitigate the issue.

**Comment by ReinerBforartists** [comment]
This limit exists for good reason. I think you run into a Eevee limit here that is not so easy to fix. And i would be surprised if increasing this limit would really help. For me this looks like a much more general problem with how the volumetrics are done in Eevee. And then it would be wiser to report this to the Blender developers.

But first let's see what increasing the limit really does :)

**Comment by Draise14** [comment]
I get much smoother artifact sample card issue free renders, but the shadow "froxel" is still doing this worldspace layered system artifact. I had a deeper look into the code, but now it's beyond me. There are a lot of comments about features/work that still need to be implemented, so maybe in the future this will improve. 

Files that do the things like this is in the **eevee_volumes.c** file. 
Folder: `\\Bforartists\source\blender\draw\engines\eevee\`

I'll do some more tests anyway..

**Comment by Draise14** [comment]
I did some tests. The shadow samples going up does help a lot, it's nice, but doesn't get rid of the full issue. Density seems to up the shadow bug the most and yes, that would be to how the engine does it. Oddly enough, the card samples issue also is prevalent in Cycles. My graphics are not premo, Nvidia GTX 1060, but it can handle it.

**Comment by ReinerBforartists** [comment]
Hm, but a weaker card may not be able to handle it. And i don't want to be responsible to burn hardware through. Handle this one with care please ;)

**Comment by Draise14** [comment]
My GTX640 and Quadro 400 on another computer that I  have cannot hack the default volume sample limits, it just crashes BFA/Blender, having them higher does the same. Would it really burn a card if it can't even start a render?

**Comment by ReinerBforartists** [comment]
Dunno, but i don't want to test it ^^

**Comment by Draise14** [comment]
How about we just up the shadow samples so they are 256, the same as normal volume samples?

**Comment by ReinerBforartists** [comment]
The Blender devs have introduced this limit for a reason at one point. When you need to increase the samples this dramatic then you may do something wrong at another point. And as told, my expection is that the realtime volumetrics is simply not meant for animation. The technical limit is not the number of samples here.

I would say ask them first why the limit is so low.

**Comment by Draise14** [comment]
Yeah.. probably should. I just don't know how Blender dev proposals work. Here it's a "feature request" tag for a feature request in the one tracker where work is done. Simple, easy. 

There, to propose something in Blender.. it's Rclick Select voted topics in a third party site (that aren't tasks), Blender Dev Talk forums (which aren't tasks), then there is a convoluted hard to understand custom tracker where.. you can't propose anything or do feature requests because it's not accepted to propose feature requests?!!

**Comment by ReinerBforartists** [comment]
Blender <3 :D

I have no idea ^^

**Comment by Draise14** [comment]
lol, I personally still don't even know how to commit anything to Blender, let alone jump through the delayed hoops of getting approval to be merged into master.

**Comment by ReinerBforartists** [comment]
No wonder. 99% of the code is written by the paid developers. Really getting something into the trunk was always hard work ;)

You could join their chat and directly ask one of the developers there. Currently is a bad time though. It's Blender Conference ...

**Comment by ReinerBforartists** [comment]
... or i could give up my resistance and you set the new limit to 256 ^^

**Comment by Draise14** [comment]
I posted it to the blender tracker. There is no tag what-so-ever for feature requests. 

https://developer.blender.org/T71266

**Comment by ReinerBforartists** [comment]
Let's see what happens :)

**Comment by Draise14** [comment]
It has been nearly two weeks and it hasn't even been triaged/reviewed by anyone. I really can't be bothered going through the beurocracy to triage it myself, make a commit and find out how to do this for the Blender community... so.. here is a new solution:

1. Up the sample limit carefully (just equal shadow samples and up the total by 50%)
2. Add warnings to both volume sample areas in the tooltips.

**Comment by ReinerBforartists** [comment]
Ah, they have chosen the other option, ignore :D

I would still be interested where the limit comes from. As told i am pretty sure that there is a reason. But i'm green with this change. Fingers crossed that it does not strike back.

**Comment by Draise14** [comment]
This has been answered and commented, but they closed it saying that I could submit a patch to do the change optionally, but essentially it's a non-bug - but there would be not much of an issue with the limits suggested, though they would need to triage it with the person who benchmarks.

**Comment by ReinerBforartists** [comment]
Not this easy. Every difference to Blender makes the maintaining harder. That's why i love to limit those changes to the minimum.

But when they said there is no issue with it, besides that they don't want to do it, then you can make the patch here and do a pull request.

**Comment by ReinerBforartists** [comment]
Draise, have you contacted Jaques Lucke to get this patch submitted to Blender?

**Comment by Draise14** [comment]
Not yet. Just working on client work and the VSE manual copy task in the documentation. I admit I'm terribly slow with it all. The time I can dedicate to BFA is so limited...... =(

**Comment by ReinerBforartists** [comment]
I know this feeling too well ^^

Take your time. It is done when it's done. I just wanted to know the state of things :)

**Comment by ReinerBforartists** [comment]
What happened to this issue here? :)

**Comment by Draise14** [comment]
Got closed in Blender, they won't do it unless I commit to their patch system - which is.. zip's¡!? 

So I guess we could do it here. There is another volume based task I have to make this the defacto eevee volume rendering build to go to.

**Comment by ReinerBforartists** [comment]
I thought we were already at this point. I wait for the patch ^^

But yeah, just wanted to know if we shall keep this task open. Take your time. It takes as long as it takes :)

**Comment by ReinerBforartists** [comment]
Bump

Any news here? Or shall we finally abandon it?

**Comment by Draise14** [comment]
I can commit this. I'll do it later today.

**Comment by ReinerBforartists** [comment]
Yay \o/

**Comment by ReinerBforartists** [comment]
Perfect. Many thanks :)
