### ISSUE TITLE
Rotation with knife tool

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1185]
With ALT + MMB you should be able to rotate with the knife tool active. But we have a overriding problem. It switches to the closest orthographic view instead. With the Blender keymap you can navigate. Needs a solution.

**Comment by Draise14** [comment]
I have not enjoyed this and noticed this issue. Consistency says Rclick alone should rotate the view. It's a double entry to cancel on Rclick + ESC. 

![2019-10-24_16-56-17](https://user-images.githubusercontent.com/35357409/67528532-504cca00-f67f-11e9-9ee9-8d6e6dc91d45.png)

**Comment by Draise14** [comment]
Woah, I tried to take a look at the keymap, I have no idea howto change any of this, the code is identical in the keymap.

**Comment by ReinerBforartists** [comment]
Yes, this is one of the rare cases where the tool collides with our navigation.

What you see in the footer is not in the keymap. This part is hardcoded.

**Comment by ReinerBforartists** [comment]
Unfunny can of worms -.-

**Comment by ReinerBforartists** [comment]
I have no idea how to solve this at the moment. Unassigning for now, and waiting for inspiration.

**Comment by ReinerBforartists** [comment]
Conflict is that alt f is now used by Flip Quats. Why the heck does this rarely used item need a hotkey? O_O

Okay, remove flip quats, reassign Center View to Mouse to Alt F. Add hotkey Alt MMB for rotation

**Comment by ReinerBforartists** [comment]
The keymap manager is completely fubar ...

![unrealiable](https://user-images.githubusercontent.com/13919702/67550475-dfe98b80-f706-11e9-8f5c-78a1f6041239.jpg)
