### ISSUE TITLE
Keymap - File Browser - Add "context" menu to double right click for consistency. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1187]
## Issue
There is a new "context" menu in the file browser. We have these menus under double right click. Would be good to have this one also accessible on double right click for consistency. 

![ApplicationFrameHost_2019-10-24_16-41-58](https://user-images.githubusercontent.com/35357409/67527907-ab7dbd00-f67d-11e9-886d-f9458eb3cb7c.png)

# Solution
Add the Blender entry for the context menu with double right click.

**Comment by ReinerBforartists** [comment]
Another set of double menu entries -.-

**Comment by ReinerBforartists** [comment]
Fixed in master
