### ISSUE TITLE
Rendering effects like Smoke could be more intuitive

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#1190]
As of Bforartists Alpha 0.7 (and Blender 2.81), users that add an effect (e.g. Smoke) must save the project and then bake the animation before they can render it.  Ideally, a more intuitive solution would be appreciated so that artists can focus more on what they're creating.

**Describe the solution you'd like**
There are 2 solutions that come to mind:

1.  Upon adding an effect that requires file saving, automatically trigger the auto-save feature allowing the user to go directly to baking and rendering.

OR

2.  Provide a more visible notification to the user that their project must be Saved and Baked (if necessary) before they can do a final render.

**Additional context**
As a noob artist, I was frustrated at seeing an effect like smoke, play out perfectly in preview but not render.  I went through a few forum threads and youtube videos where I saw a fair number of other users (newbies) like myself complaining of the same issue.  This lead me to realize that this process (although understandable from a dev perspective) was rather counter-intuitive to the creative process.
![smoke](https://user-images.githubusercontent.com/57046940/67625023-6bd5e300-f7ed-11e9-9d39-15b2cbdd0fd1.gif)

**Comment by ReinerBforartists** [comment]
Hey Slippystance,

Thanks for your report. To change the way how the tools works is behind our scope. The fork is to improve the UI. Feature requests should go directly to Blender. But we could add a little string with a hint somewhere. I'll have a look.

**Comment by ReinerBforartists** [comment]
Hm, one possible way would to implement the bake button to the quick effects menu too. So that people are aware that they need to bake the smoke sim to make it render.

**Comment by slippystance** [comment]
Agreed.  The workflow for this is just awkward at the moment.  Would it be possible to clarify via the tooltip?

Current:
![image](https://user-images.githubusercontent.com/57046940/67631632-34e7e780-f856-11e9-949c-4617f24e5f39.png)

Possible change:
![image](https://user-images.githubusercontent.com/57046940/67631645-5cd74b00-f856-11e9-9b7f-57e7fb06639b.png)

**Comment by ReinerBforartists** [comment]
Sure :)

**Comment by ReinerBforartists** [comment]
Just curious, what about the other quick effects? Any thoughts?

**Comment by slippystance** [comment]
I'll have to try them out, but do I add equivalent issues to this feature request or create new ones?  Some devs like stuff in a single incident report while others prefer separate incidents to differentiate tasks.  Just let me know.

**Comment by ReinerBforartists** [comment]
Yes, it's better to make a new issue then. Thanks :)

**Comment by ReinerBforartists** [comment]
Okay, can't put the bake button into the quick effects menu. Too much other settings involved, and no matter what i try it remains greyed out. Remains to update the tooltip.

**Comment by ReinerBforartists** [comment]
Fixed in master

At least the tooltip fits now better.

![baketooltip](https://user-images.githubusercontent.com/13919702/67660996-59c88180-f960-11e9-91c0-2c9fb676bd38.jpg)

**Comment by slippystance** [comment]
Nicely done.  Until Blender devs address this flow I think the tooltip you added will be a welcome addition for artists like myself.  If I run into another situation like this, I'll open another feature request and reference this ticket.

**Comment by ReinerBforartists** [comment]
Always welcome :)
