### ISSUE TITLE
Quick Explode does not return target object to original shape

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#1191]
**Describe the bug**
After applying the Quick Explode modifier, the object affected does not return to its initial shape once the animation is played

**Desktop (please complete the following information):**
Windows 10, 1080TI

**Screenshots, Example Files**
![xeqW4WWrPO](https://user-images.githubusercontent.com/57046940/67636117-7d20fd00-f88a-11e9-9c16-711953ab204b.gif)

Note:  My assumption is that this is a core Blender 2.8 bug, so I searched for issues with the Explode modifier and didn't find anything (https://developer.blender.org/search/query/GNDkj7fxkbvx/#R).  So I wanted to bring the issue up here.

**Comment by ReinerBforartists** [comment]
Thanks for the report. 

This is as far as i know expected behaviour. The tool splits the object into several subparts. But i can have a look at it.

You can also try to report it as a bug in the Blender bugtracker.

**Comment by slippystance** [comment]
Agreed, I looked into some tutorials on the effect and it looks to be a Blender core issue.  Can you please close this?

**Comment by ReinerBforartists** [comment]
Done :)

Copy the object, then explode the copy and make the original object invisible ...
