### ISSUE TITLE
Grease Pencil Context menu - iconize Reproject strokes and put it into strokes menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1196]
We have an operator in the grease pencil context menu in edit mode that just exists there. Reproject strokes should also be in the strokes menu. And needs an icon.

Shot is from Blender, this menu does currently not show in BFA

![contextgreasepencil](https://user-images.githubusercontent.com/13919702/68023032-59085600-fca6-11e9-8416-c957cb9d020a.jpg)

**Comment by Draise14** [comment]
This is a terrrible design choice. 

Why is this menu not showing? Is it a right click context menu?

**Comment by ReinerBforartists** [comment]
I don't know why it is not showing. That's why we have this issue here now ^^

Yes, it's a right click menu

**Comment by ReinerBforartists** [comment]
Fixed in master

![reproject](https://user-images.githubusercontent.com/13919702/68468078-9bd2ac80-0217-11ea-96b6-9c788fb56aba.jpg)
