### ISSUE TITLE
Toolshelf - 3D View - Remove double entry Box, Circle and Lasso select

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1224]
Two contradicting tool systems that does the same is no go. So the first step is to reduce it to one, and use the better one in the future. That's the toolshelf select tools. 

Remove double entry Box, Circle and Lasso select from the select menu and the keymap. Add the hotkeys to the tool shelf. In all editors and modes where available.

![select](https://user-images.githubusercontent.com/13919702/68655113-b49cd400-052f-11ea-9e64-066bea2ece41.jpg)

**Comment by ReinerBforartists** [comment]
First in the 3D view. And let's check how the handling turns out then after assigning the hotkeys to the tool shelf tools.

**Comment by ReinerBforartists** [comment]
Lasso select is already a problem. It works with ctrl + right mouse. The tool in the tool shelf can't be called that way.

Hm, we could leave the entry in the keymap. But then we have the double toolset mess again. The cleanup must be consequent. And not half arsed like in Blender.

So for now we remove the old tool hotkey completely. Lasso select happens from the tool shelf. In this case by manually activating the tool.

**Comment by ReinerBforartists** [comment]
Leaving the rmb hotkey for lasso select intact for now.

**Comment by Draise14** [comment]
> It works with ctrl + right mouse. The tool in the tool shelf can't be called that way.
I can call the toolshelf lasso select with ctrl+press any mouse. CTRL + Lmouse or Rmouse will activate it with the toolshelf lasso select - I just gotta disable the legacy lasso select. What are you referring to?

**Comment by ReinerBforartists** [comment]
I refer to the RMB drag behaviour for lasso select. That's the old tool behaviour. For the tool shelf we would need a new hotkey.

**Comment by Draise14** [comment]
Could there be a way that we put the legacy lasso select and box select into the toolshelf and hide the new ones? So that when you activate it, use it, it would then revert back to tweak or transform mode?

**Comment by ReinerBforartists** [comment]
I dunno. It's two contradicting systems. The one does not play together with the other. Proof is that you can box select with the old tool while one of the new tools is active.

**Comment by ReinerBforartists** [comment]
Hm, seems that i have forgotten to close this one ^^

Fixed in toolshelf branch
