### ISSUE TITLE
Toolshelf - UV Editor - UV / Transform menu - remove move rotate scale

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1243]
... and assign the hotkeys to the ones in the tool shelf

Double toolset is no go.

![moverotatescale](https://user-images.githubusercontent.com/13919702/68756530-95bf4000-060a-11ea-8d41-6309028f00b6.jpg)

**Comment by ReinerBforartists** [comment]
Hm, the biggest problem that i see here is that the widget can get into the way here to select further elements. But this does not justify to have two transform toolsets.

Hm in trueSpace you were able to hide the widget temporarily. But that's another possible task then.

**Comment by ReinerBforartists** [comment]
Fixed in toolshelf branch

**Comment by Draise14** [comment]
Softimage could also temporarily hide/toggle widgets with the tab button. 

I put the widget transforms to mouse tweak so can select through them to workaround this issue.

**Comment by ReinerBforartists** [comment]
Hide widgets can be done up right in the options area. But yeah, show gizmo isn't hotkeyed yet. I wanted to use the tab key for the tweak tool though ...
