### ISSUE TITLE
View menu and Sidebar -  Render Border versus Render Region + Tooltip

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1248]
In the View menu the menu item is called Render Border. In the View panel in the Sidebar it is called Render Region. 

Rename Render Region to Use Render Border to make its useage obvious. Render Region could be everything. There is no hint towards Render Border.

And while at it, improve the bad tooltip.

![tooltip](https://user-images.githubusercontent.com/13919702/68787025-0c773000-0641-11ea-9334-d7f1626aea02.jpg)

![renderbordervsrenderregion](https://user-images.githubusercontent.com/13919702/68787017-097c3f80-0641-11ea-90f1-b7abdb0bd1ef.jpg)

**Comment by ReinerBforartists** [comment]
Hmmm. The menu items in the Image editor are called Render Region. And in Blender it is called Render Region too. So it's wiser to rename the two Render Border items too.

Also, update the Render Border item tooltips. They miss the use case Cycles only, and the two use cases in camera view and outside camera view. The one is for rendering a portion of the viewport in the viewport. The other a portion of the image in the final render.

**Comment by Draise14** [comment]
I have been confused by these two terms for a while now. Good idea to unify them.

**Comment by ReinerBforartists** [comment]
Draise, when something confuses you, then please make a task. Maybe we can improve it :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![renderregion](https://user-images.githubusercontent.com/13919702/68851190-b86a5b00-06d5-11ea-952c-43b0a16b8411.jpg)
