### ISSUE TITLE
3D View - Transform Orientation lists confusion

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1249]
# Issue
![2019-11-14_13-11-28](https://user-images.githubusercontent.com/35357409/68884094-6d097a00-06e0-11ea-9e82-8cc6ad46c7d5.png)

The Tranform widget and modes have two orientation lists with equal entries. One is for "transform" and the other "orientation transform". Both tooltips are the same. One list is located in the tool's transform panel, and the other is in the 3D View header toolbar. If the extra toolbar is showing, the tool's transform orientation will also show here.   

![bforartists_2019-11-14_13-20-25](https://user-images.githubusercontent.com/35357409/68884905-2a48a180-06e2-11ea-8bb5-ae27c4ec2bd3.png)
![bforartists_2019-11-14_13-20-35](https://user-images.githubusercontent.com/35357409/68884909-2b79ce80-06e2-11ea-85fc-cf50292c687d.png)

I am still confused as to what does what in the UI and the UX is not intuitive as they clearly have different functionality. After some digging.. it works like this:

1. **transformation orientation** = the global transform orientation for all widgets/modes. 
- if the tools _transform_ list is on "default", any new transform mode will default to this
- Can be understood as either _default_ or _global_ transform orientation logically. 
2. **orientation** = the current tool's orientation override, overriding the global orientation. 

This isn't so clear right now. 

# Solution

It would be great if the tooltips differentiated or the lists were labeled correctly to avoid functionality confusion and understand it's hierarchy in the UI and UX with transformations. 

**Re-label entries:** 
1. Transform Orientation = Default Transform Orientation / Global Transform Orientation / Scene Orientation
2. Orientation = Tool Orientation

**Re-lable tooltips to reflect and show how they work.** 
1. Default / Global / Scene Transform Orientation
- Scene Transformation Orientation: #
- Default / Global / Scene Transform Orientation for all widgets and transform tools
2. Tool Orientation
- Tool Transformation Orientation: #
- Tool specific transform orientation, or set to Default for "Scene Transform Orientation" 

These are just examples. Could be refined.

**Comment by ReinerBforartists** [comment]
Hm. It does the same and is the same. And this means the tooltip is correct. We would in fact make it more confusing with changing the tooltip.

The difference is that the tool settings are just valid for the current tool operation. And nothing else. And i don't see a good way to incorporate this into a tooltip really. Needs more thinking.

**Comment by Draise14** [comment]
I just want the tooltip to be consistent with the idea that one is for all tools and the other for just the selected tool. Right now it confuses and feels like a broken double entry.

**Comment by ReinerBforartists** [comment]
Yes i know. But this is already given by being a tool setting. I am not even sure if this is even separated under the hood.

Task remains open. As told, needs more thinking.

**Comment by Draise14** [comment]
Well, I missed the obvious... even the student I was teaching BFA found it tricky to grasp up front. 

I think that is because tool settings and the 3D Viewport settings in the same header (in the properties panel it's clear).

**Comment by ReinerBforartists** [comment]
The Python tooltip tells me that it's in fact the same prop, so we have a problem ^^

**Comment by ReinerBforartists** [comment]
Investigated. We can't even recolor the toolsettings bar independant from the header, which would have helped to make a better separation. And as told, it is the same tool under the hood. So we can't relabel the one without to relabel the other. I fear this will remain a nice dream. There is nothing left that we could improve here.

It's after all really simple. As told before, the one in the tool setting will just affect the current tool operation. And it will override the global orientation mode. While the other is the global orientation mode.

Closing.
