### ISSUE TITLE
Select Groups icons inconsistent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#125]
Floating menu called by SHIFT+G doesn't have icons. 
Menu in header does have icons - though it's two clicks and 3 mouse movements to get to. 

Version 0.9.6

Should they be iconized? Or are these floating menus going to be left as is till a good alternative comes? (Like a consistent BFA pies?)

![bforartists_2018-04-02_19-43-35](https://user-images.githubusercontent.com/35357409/38223084-9157b358-36ae-11e8-8e1b-060ba45a7ea5.png)
![bforartists_2018-04-02_19-43-46](https://user-images.githubusercontent.com/35357409/38223086-92997634-36ae-11e8-9fbc-017d1da46cfd.png)

**Comment by ReinerBforartists** [comment]
Floating menus is not the way to use Bforartists. They exists for historical reasons. That the Blender keymap does not throw an error here. This menus are usually enumerations that you cannot iconize. I would need to rewrite this menus to give them icons. 

The plan was to replace this floating menus with pie menus at a later point.
