### ISSUE TITLE
Developer Build Bug

### ISSUE THREAD

**Issue by emilsvfx** [Bforartists/Bforartists#126]
![clover_2018-04-03_10-38-52](https://user-images.githubusercontent.com/22729351/38235920-59a80700-372b-11e8-804b-42a5851ba136.png)

**Comment by ReinerBforartists** [comment]
Thanks for the report. Seems that it was no good idea to upload a developer build ^^

You can either wait until next sunday. Then i will upload a normal build again. Or you can install the missing dll at your pc :)

**Comment by emilsvfx** [comment]
yes of course :)

**Comment by ReinerBforartists** [comment]
Long gone. And i hope the new developer builds are working again.

Closing.
