### ISSUE TITLE
Redefine Display/Shader/View & other display inconsistencies with better terminology & organization

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#127]
I noticed when I first used Blender that the viewport view options, the armature and separate bone view options AND object view options and then their naming conventions were confusing and all over the place. In fact, it was the hardes software to toggle anything viewport related because I had to know the WHOLE ui to even have some kind of control. Even then, the ergonomics is annoying. 

First of all, all of them had the same name: "display". 
Second, some of those view options were under "Shader" of which also had a similar attribution to object materials and material shaders and global viewport "display" functionality - causing confusion due to other software using "Shading" for different workflows.
Third, everything was everywhere and then again no where. 

So I wanted to propose a possible solution and naming convention (not unfamiliar with other software and terminology): 

1. Introduce "Visibility" toggle areas
2. Remove, Organize or rename "Shader/Display" areas
3. Standerize requirements to be a viewport "Display" toggle/control

**Purpose:** 
- Have viewport display settings for the scene in general that makes sense (without dividing into two local/global criteria based areas with same name)
- Have a consistent object based viewport toggles (that won't mix with viewport display settings)
- Have better terminology to keep things less mixed up and to their purpose (so that one won't be confused with the other)

**How** 
1. "Visibility" terminlogy would be the terminology for object based data viewport toggles: xray, wireframes, wiretools, etc. Why? Because the word Vsibility is to what extent can we see with clarity. These options toggle clarity for object data specifically and portrayal of that data exclusively - including wireframes. 
2. "Shading" should not be confused with data visibility displays in the viewport, by only toggling options that affect materials and lighting in the viewport (matcap, ao, dof, material, etc). In this case anything to do with global viewport data display, like wireframes - would be moved to "Display". 
3. The word in itself for "Display" is similar to screen, viewport, show what you'd like to see, like a piece of art in a meseum - the overall viewport. If anything in display is per object based or per object data visibility based, then it should be moved/renamed to Visibility. 

**Potential tasks:**
1. Rename Object>Display to Visibility
2. Rename Armature>Display to Visibility
3. Rename Bone>Display to Visibility
4. (optional) create an easy access Property Sidebar panel for "Visibility" and put in all armature, bone and object visibility toggles (dynamically) to have similar control like the Transform and Object Name tools and name that panel "Visibility. 
5. Rename "Display" to "Viewport Display"  to make sure there are no misunderstandings (or just do this and don't touch anything else, just reorganize and clean up according to correct criteria)
6. Move/limit global wireframe tools to "Viewport Display" panel away from the "Shader" panel or limit/move wireframe tools to visibility panel if exclusively used on a per-object basis. If both systems are intact, then it must be evident which one is for global and which is for local and each in their Display/Visibiilty panels respectively and exclusively. 
7. Move world background to "Shading" which really affects lighting/rendering of that viewport - not viewport global data displays typical of the "Display" panel. "Shading" is more an artistic tool for the viewport really, not global data display. 

What do you think? Would this make the whole "Display" confusion better? Does it seem doable? Would it sove a number of issues? Would it make the UI a little more sensible and discovarable?

**Comment by Draise14** [comment]
If this makes sense, I don't mind making the tasks for that each separately then closing this. If not, then all good.

**Comment by ReinerBforartists** [comment]
Yes. Please make single tasks. That way it's easier to decide what change is a good one and what not.

**Comment by Draise14** [comment]
Ok, done and done. I grouped them to the case as a milestone - which can close later on once resolved. All the tasks are feature requests so.. no biggy if nothing comes of it... 

I just remember clearly how frustrated I was trying to control the viewport with all those areas when I started Blender 3 years ago.
