### ISSUE TITLE
Bforartists 0.8.0 does not start

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1270]
As reported in the forum, Dev Build Bforartists 2 - Alpha 0.8.0 was reported to be again built in Debug mode. And throws an error at startup.

Related: developerbuild startup bug #324

Forum topic: https://www.bforartists.de/content/bfa-080-does-not-start#comment-9627

![69378368-39989380-0c7c-11ea-912d-47929053f357](https://user-images.githubusercontent.com/13919702/69403449-e31e6a00-0cfa-11ea-872a-c3b7619aaad6.png)

**Comment by ReinerBforartists** [comment]
The packed version is the correct one. The debug build packed has a size of over 300 Mb. So what is the problem here?

**Comment by ReinerBforartists** [comment]
Seems that Blender has linked the missing library static, means it is included into the exe. Proof is when you compare the release version with a version that i have compiled by myself.

Now just to find out how to link static with Visual Studio ...

![static](https://user-images.githubusercontent.com/13919702/69408597-9ee59680-0d07-11ea-8d1f-dc1896bc0810.jpg)

**Comment by ReinerBforartists** [comment]
Trying to compile static is not really successful so far ...

![statisch1](https://user-images.githubusercontent.com/13919702/69415050-305b0580-0d14-11ea-8cdc-61e928001538.jpg)

**Comment by ReinerBforartists** [comment]
When i just would know which projects are made static. All of them? That's a ton of linker errors. blender / bforartists for sure. And makesdna and makesrna too. But what else?

**Comment by ReinerBforartists** [comment]
For now i have simply put the VCRUNTIME140_1.dll into the target folder. Seems to work at my laptop. Blender starts.

But investigation continues. When Blender builds with static libraries then we should do the same.

**Comment by ReinerBforartists** [comment]
Update. It's a bug in Cmake.

https://gitlab.kitware.com/cmake/cmake/issues/19829

**Comment by Draise14** [comment]
When you update to the latest Cmake, would it fix it? Have you tested yet? _I updated Cmake not last week._

**Comment by ReinerBforartists** [comment]
Yes, upgrading to newest Cmake version should fix it. I have 3.15.3 installed. I want to wait for 3.16 final before i test. That's currently a release candidate. There is no pressure anymore now that we know what the problem is.

**Comment by ReinerBforartists** [comment]
Tested now. Version 3.15.5 fixes it. 

Closing.

**Comment by Draise14** [comment]
Awesome.
