### ISSUE TITLE
Properties Editor - Remove the tools tab

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1278]
The Blender devs have made the Tools tab for the 3D View only now. No other editor shows its tool settings anymore in this area. And they have put the content into the sidebar. This makes this tab imho obsolete. It's the third location with the same information.

Shall we remove it completely? Or shall we keep it like in Blender? What do you think?

![rewrite](https://user-images.githubusercontent.com/13919702/69632051-dbd6c380-104e-11ea-8d6d-ac0c250e0692.jpg)

**Comment by Draise14** [comment]
I have seen more than a few dozen issues in Rclickselect, the Papercuts thread, and Blender design forum discussions, etc -arguing that these settings are in too many redundant places. We have them in the Properties Shelf, in the Tools header, and also in the Properties Editor along with object settings? You'd think you'd want to use tools with the properties of the object showing (vertex groups, etc), not the tools. If the tool is for the current editor, then the settings in the Properties Editor are... really really redundant.. and I'd say... 

Remove it.

Not once have I used this tab, only to learn what it was. 

On the contrary, the Workspace panel of that tab (why it's there, who knows) should be moved to the scene settings tab or something.

**Comment by ReinerBforartists** [comment]
Hm. That's in fact the only useful thing where this tab could be good for. For the workspace settings. And just the workspace settings. Then we could remove it from the sidebar.

**Comment by ReinerBforartists** [comment]
Postponing. First finish some issues of the tool shelf.

**Comment by ReinerBforartists** [comment]
Let's have a look ...

**Comment by ReinerBforartists** [comment]
Aaand it's gone. Fixed in master

![gone](https://user-images.githubusercontent.com/13919702/73064022-8b3de400-3ea0-11ea-86f6-47982d6f5413.jpg)
