### ISSUE TITLE
Image Editor  - Tool Shelf - rename Clone Tool to Stencil Brush?

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1279]
A clone tool in any image software works in a way that you set a starting point, and the area around this starting point gets cloned by painting then.

In the 3D view it works as intended. But the clone tool in the image editor is no clone tool. It is a stencil brush.

We need to change the name and the icon here. And to add a proper tooltip. But that's a general problem of the whole tool shelf integration.

![stencilbrush](https://user-images.githubusercontent.com/13919702/69704482-cb2c5900-10f3-11ea-87de-081542fa2abd.jpg)

**Comment by ReinerBforartists** [comment]
We should better remove it completely. It does the same than the draw tool with a texture and in stencil mode. But much worse and ways more limited.

Or we fix it to make it a real clone tool like in the 3D view. But this would mean to develop tools. And we are more than busy with just the UI.

**Comment by ReinerBforartists** [comment]
I am lost at the moment here, so changed it into a question.

**Comment by Draise14** [comment]
Ok, gave it a try out. For sure these two modes work totally differently when in 3D and 2D. 

Here is what I found: 
1. Bforartists keymap doesn't have the Grab Stencil Clone hotkey (Blender is Rclick when you have the UV Stencil configured to 2D
![2019-11-30_12-00-15](https://user-images.githubusercontent.com/35357409/69903560-07b4ba80-1369-11ea-9db9-343bee3ef553.png)

2. For sure the UV clone brush is a Stencil brush. It does take some leg work out of configuring a normal brush to stencil paint, but it's..... not a clone. It's a stencil projection brush. You are right here. 

# Possible Solution

![2019-11-30_12-03-28](https://user-images.githubusercontent.com/35357409/69903585-6f6b0580-1369-11ea-8109-e61ff65227d3.png)
1. Grab Clone should be added to the BFA keymap
2. Grab Clone in UV mode should be renamed to the same from the Image Editor to 3D View Editor
3. The Grab Clone setting for the UV should be renamed "UV Stencil mode" and tooltip modified accordingly. 

That is the quick fix. 

The second fix is making another brush with the toggle hidden, then remove the 3D clone from the image editor paint mode, and then add a new brush to the Image Editor that automatically turns on the 2D toggle and name that brush Stencil Brush.

**Comment by ReinerBforartists** [comment]
Thanks Draise :)

When we have missing keymap items, especiallly hotkey only ones, then we need to add them for sure. For the rest, well, I guess i first need to understand what exactly you mean. Give me a few days ^^

**Comment by ReinerBforartists** [comment]
>Grab Clone should be added to the BFA keymap
What hotkey is this?

**Comment by Draise14** [comment]
![bforartists_2019-12-01_12-46-30](https://user-images.githubusercontent.com/35357409/69917846-9ba18780-1438-11ea-8f0a-cb54ed7f78e0.png)
**Image Editor:**
`paint.grab_clone`

**Comment by ReinerBforartists** [comment]
Thanks buddie. Gonna fix this one now :)

**Comment by ReinerBforartists** [comment]
Hotkey added.

**Comment by ReinerBforartists** [comment]
> 2 - Grab Clone in UV mode should be renamed to the same from the Image Editor to 3D View Editor
> 3 - The Grab Clone setting for the UV should be renamed "UV Stencil mode" and tooltip modified accordingly.

Where do we have a grab clone in the UV editor? Or do you mean the Image Editor?

**Comment by ReinerBforartists** [comment]
Things have changed here meanwhile. The Blender devs have redesigned the brushes panels. But the tool is still a stencil brush.

I am still lost if we should change the name. And when in doubt better leave it alone before breaking it. So let's close this task as won't fix.
