### ISSUE TITLE
Image Editor - clone tool - clone from image/uv map subpanel is missing the content

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1281]
No idea what goes wrong here. But the content of this tab is not showing. There is no error message.

![missingclonepanel](https://user-images.githubusercontent.com/13919702/69900222-01c2d780-1371-11ea-8735-b74808549eea.jpg)

**Comment by ReinerBforartists** [comment]
The code is the same. But it does not show. When i save the scene from blender then i have the source clone slot. But i cannot get it to show in Bforartists. 

I am really clueless here.

**Comment by ReinerBforartists** [comment]
Ah, this requires to have a material attached to the object. So no bug. Still no idea how to show something in this panel. Investigation continues.

![material](https://user-images.githubusercontent.com/13919702/69903537-f1bfed80-139a-11ea-859c-69899ed0e276.jpg)

**Comment by ReinerBforartists** [comment]
This feature is not documented in the manual yet. http://builder.openhmd.net/blender-hmd-viewport-temp/sculpt_paint/painting/texture_paint/tools.html

But this would be another issue anyways. Nothing to fix here. Closing.

**Comment by Draise14** [comment]
You need a texture selected to be able to use it - it just shows what texture is selected in the node editor/material.

**Comment by ReinerBforartists** [comment]
So i need to create a second material with a texture? Okay, will give it a try tomorrow :)

**Comment by ReinerBforartists** [comment]
I have reopened it until i have figured out the workflow here.

**Comment by Draise14** [comment]
> So i need to create a second material with a texture? Okay, will give it a try tomorrow :)

Just assign a texture to the current texture. You can't really paint or use the texture you're painting to stencil/stamp anything till you have that texture assigned and selected in the brush (you can even select other textures to stencil).

**Comment by ReinerBforartists** [comment]
This part is clear. It's about the Source Clone Slot. No matter what i try, it remains empty.

I have two cubes here, with two materials. And two different textures. But the Source Clone Slot remains empty.

Draise, what is the trick here?

File: [testcase.zip](https://github.com/Bforartists/Bforartists/files/3908151/testcase.zip)

![sourcecloneslotproblem](https://user-images.githubusercontent.com/13919702/69913404-909a2780-1437-11ea-8cb9-c9ac78afdeb3.jpg)

**Comment by Draise14** [comment]
![bforartists_2019-12-01_12-43-44](https://user-images.githubusercontent.com/35357409/69917819-3baae100-1438-11ea-8f46-3aad18b39271.png)

1. Select the texture in the node editor
2. It should show up in the list. The list is... now really useful really, just shows what texture is selected in the node-editor.

**Comment by ReinerBforartists** [comment]
I am too dumb. I cannot get it to work :(

And the test file is also shot down. Materials shows pink in the viewport at import. What the heck is going on here? -.-

![nocontent](https://user-images.githubusercontent.com/13919702/69946145-58542100-14eb-11ea-89b2-caccfdf624fb.jpg)

**Comment by ReinerBforartists** [comment]
Whatever the hiccup was, now i have content in the source clone slot.
![cloneslot](https://user-images.githubusercontent.com/13919702/73921469-b32d3e80-48c7-11ea-8012-51d4775b242a.jpg)

Let's update the manual here ...

**Comment by ReinerBforartists** [comment]
Manual update is a bigger issue. And will be covered in the Manual tracker. Closing this issue. It has fulfilled its purpose.
