### ISSUE TITLE
3D View - Weight paint default colors to include alpha 0 for 0 weight

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1283]
# Feature Request
![EKiINsfWkAA-4_Q](https://user-images.githubusercontent.com/35357409/69918904-29836f80-1445-11ea-9236-51cc4afbcbab.jpg)
> I suggest changing the color responsible for 0 Weight, from Blue to a transparent color.
> Red color - maximum weight
> Blue color - the minimum value, for example 0.01 - 0.0001 (or something like that)
> Transparent color - weight 0. Under this you can see the matkap.

![EKiINsfXkAAnq-F](https://user-images.githubusercontent.com/35357409/69918941-8121db00-1445-11ea-9db8-46d7eb9dd605.jpg)

Original Idea:
[https://blender.community/c/rightclickselect/lYdbbc/](https://blender.community/c/rightclickselect/lYdbbc/)

## Reason
> What is it for?

> 1. Working with a model painted completely in dark blue is uncomfortable for the eyes.
> 2. It is very difficult to recognize really small weight values, because they merge with blue color.
> 3. Skinning is a very difficult job. And the current color palette negatively affects eye health.

![64ce8122ec304ec0b69b399f06001f25-l](https://user-images.githubusercontent.com/35357409/69918936-7d8e5400-1445-11ea-9013-3ccd901c5d55.jpg)

# Task
Can we include this as a default into Bforartists? I doubt Blender will do this, as this is set in as a custom color profile by user preference - but for weight painting, this will give BFA a leg up. 

Is there a way to make it default on compilation? 

_I know the pain of the cursed blue weight that you can't tell if it's assigned or zero._

**Comment by ReinerBforartists** [comment]
Hm, dunno. That's why we made the default weight paint display method to Active already. Zero weights diesplays as black here. Isn't this exactly what you are looking for?

![zeroweight](https://user-images.githubusercontent.com/13919702/69940311-402bd400-14e2-11ea-9eb9-d6f4d906b455.jpg)

**Comment by Draise14** [comment]
Ah, there it is. 

Dark black on dark blue has little or no contrast. It's easy to miss.

**Comment by ReinerBforartists** [comment]
But white can make trouble with yellow ...

**Comment by Draise14** [comment]
Transparent is... whatever the model or view mode is, it's not just white. It's transparent. So you could see the models textures, matcap, or whatever you want in whichever view. Black doesn't even show 3D volume and contrasts even worse with the blue. The yellow is surrounded by green/teal and red, which is in itself already contrasting.

**Comment by ReinerBforartists** [comment]
So we need a fourth mode ^^

**Comment by Draise14** [comment]
Right. Yeah. 0.000001 or something might be more like it. 

I think there doesn't really need to be a 4th mode. Just the mode with the black could do a change, as the black is.. really really bad for this.

**Comment by ReinerBforartists** [comment]
No, it must be exactly zero. Everything above, and be it as small as possible, is a weighting. And not a zero weighting.

Best solution would be when the color would be customizable from the properties. Or a switch from black to white.

**Comment by Draise14** [comment]
The weight color is customizable in the properties with custom weight color. But the request is to make 0 default transparent (not white) in the default modes (instead of black or blue). If it needs to be an integer switch where >0 shows, whatever works. 0 just should not show anything. 

Why? For volume comprehension and easier discoverability of low weights you typically want to avoid painting.

**Comment by ReinerBforartists** [comment]
Let's have a look if we can catch something here.

**Comment by ReinerBforartists** [comment]
First, the custom colors is no solution here. Even a weight of 0.001 is still a weight. And that's usually the baddies. You have white with 0.005 here. So remains to find the color value for having the black background color. But i fear it blends with the weight color blue ...

**Comment by ReinerBforartists** [comment]
The colorband is defined in source\blender\draw\intern\draw_common.c in 

static void DRW_evaluate_weight_to_color(const float weight, float result[4])

Line 454

float hsv[3] = {(2.0f / 3.0f) * (1.0f - weight), 1.0f, pow(0.5f + 0.5f * weight, gamma)};

I have no solution though how we could fill the canvas with white first. Giving up here. This fish is too big for me. This is best asked the Blender devs. Does a rightclickselect entry exist yet?

**Comment by Draise14** [comment]
Ah, looks like it'd hardcoded. Oh well. A setup to custom colours is the workaround and saved to the setup... no biggie.
