### ISSUE TITLE
Toolshelf - We need a hotkey for Tweak

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1288]
We really need a hotkey for Tweak. It will be our base key, to which you will return when done with other tools. Especially things like box select or navigation. It should be good to reach with left hand, and a one keyer.

I would love to use Tab for that. But we could run into a conflict here.

Any ideas?

![tweakhotkey](https://user-images.githubusercontent.com/13919702/70130765-676cd780-1681-11ea-9fb4-48f8aaa57577.jpg)

**Comment by Draise14** [comment]
Yeah, got an idea from another thread. 


# Solution
![image](https://user-images.githubusercontent.com/35357409/70146779-e73e7600-1670-11ea-86ae-810e6a0a7399.png)

Double Lclick should activate the Tweak tool. Right now it has no legacy equivalent, so it would be the mode we'd default to in all views. Double Lclick on anything or anywhere will activate this mode and escape any other mode, so lasso select can be done with CTRL+Rmouse or Lmouse and then double click will go back to tweaking/transforming - keeping the keyboard relatively free and most usability default toggling within the mouse actions. 

## Reasons
- Double Rclick is already a workflow. Double Lclick should also be a concept that makes sense: go back to tweaking (eg. so you don't get stuck in lasso select needing to use another hotkey to go out of it or back to the toolshelf to go out of it)
- It's quicker than going to the toolshelf and to a hotkey to go out of a tool to get back to work. 
- It makes tweaking and selecting things default by just clicking around, intuitive. 

### Notes
I gave it a whirl, there are no or non-discovered conflicts, it's pretty straight forward. I have tried it out. Might need more testing.

**Comment by ReinerBforartists** [comment]
Double click sounds like lots of trouble ahead. But yeah, worth an idea ^^

**Comment by Draise14** [comment]
Yeah.. Found that it makes things deselect when you go to tweak tool after making a selection, so tweaking a selection is tricky. 

An alternative I have used is just double tap W.

**Comment by ReinerBforartists** [comment]
I  would nevertheless prefer an hotkey, not a mouse action here. Still at dancing around tab here. Or D

**Comment by Draise14** [comment]
I have used a hotkey for Tweak for months now, and on projects, it doesn't really solve anything... I might try the double click to default to Tweak, the experience feels a little more snappy and less keyboard/hotkey dependent. 

Though Tab could be logical. Tab out of any tool to default tweak, makes sense. 

CTRL+Tab is the mode change now right?

**Comment by ReinerBforartists** [comment]
Phew, i dunno, haven't really modeled since months :D

But yes i remember that was ctrl tab :)

**Comment by ReinerBforartists** [comment]
I still wonder why the selection modes needs to be permanent. How often do you really box select something before you continue with another tool? The old way with performing the selection operation just once was the better one.

Hm, how did trueSpace handle this? It's this long ago that i have forgotten ^^

**Comment by Draise14** [comment]
My best reference was the great UX of Softimage, the select tools was just dragging (with a modifier if needs be) and then when you select, you go back to normal tweak mode with the widget displayed. TrueSpace worked in a similar way. Maya and Max work in similar ways. 

Indeed the legacy versions of the select tools in Blender are... more logical, you don't want to be stuck in a select mode. You select to act on it, not.. select to then change your mind and select again. 

This is why I like the idea of double Lclick to go to tweak, because it's hotkey free, it's like resetting your state to default tweak. It's like an ESC key to just... get out of a tool to the default mode. 

Maybe it could be ESC? But then I can think of a dozen conflicts there....

**Comment by Draise14** [comment]
MY WORD. I just opened up truespace. You move objects in real 3D space with depth, and Rclick moves it up in 3D space - without widgets. THIS IS WHAT I LOVED OF TS. And yes, I can confirm. SHIFT or CTRL did the box select and it would disactivate and go back to select/tweak mode.

**Comment by ReinerBforartists** [comment]
Yes, this was nice. But we can't turn Blender into trueSpace unfortunately. We would need to start at point zero again ^^

**Comment by ReinerBforartists** [comment]
Postponing this one until the tool shelf branch goes into master. We still do changes at the keymap here and there. And this would conflict then.

**Comment by ReinerBforartists** [comment]
Hm, what about the escape key? We need to check though if this conflicts with abandoning tool operation, which is also escape.

**Comment by ReinerBforartists** [comment]
This one needs a fix now.

**Comment by ReinerBforartists** [comment]
Esc does not work. So it will be D

**Comment by ReinerBforartists** [comment]
This issue is not this easy since the keymap manager is broken. Bigger operation at a one by one case ...

**Comment by ReinerBforartists** [comment]
Fixed in toolshelf branch 

https://github.com/Bforartists/Bforartists/commit/06ae3fcfa2204513fd7204fc869699195cb13f8a

**Comment by ReinerBforartists** [comment]
The change did not arrive at the master for unknown reason. So we need to repeat the task in the master.

**Comment by ReinerBforartists** [comment]
Beware of a hotkey conflict in the shader editor. Cut in the tool shelf uses D. We need to reassign this functionality.

**Comment by ReinerBforartists** [comment]
Fixed in master now too.
