### ISSUE TITLE
Raname Object Display options to Visibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#129]
**Task**

Rename the Properties>Object>Display panel to Visibility to not cause confusion with the viewport Display panel - as one is global data visibility and the other local data visibility and the two "Display" panels are causing confusion.  

![bforartists_2018-04-03_13-59-16_li](https://user-images.githubusercontent.com/35357409/38269840-44e8746e-3747-11e8-9383-d7d1be76f26d.jpg)

**Comment by ReinerBforartists** [comment]
Could you please add an image here?

**Comment by Draise14** [comment]
Image added.

**Comment by ReinerBforartists** [comment]
Also here, this options in the panel has nothing to do with visibility. It's object display options. We cannot call it visibility therefore.

**Comment by ReinerBforartists** [comment]
Closing.
