### ISSUE TITLE
General UI - Tweak Tool hotkey to Lmouse double click

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1292]
# Issue
Since legacy tools are being migrated to toolshelf tools (eg, Lasso Select), these tools become modes, meaning they don't snap back to original default modes. Once you are in lasso select, you stay in lasso select. More often than not you need to revert to the default mode - object/component selection and tweaking/transformation. 

So... typically you'd have to use the keyboard WER to do this, ok. But that is a lot of key presses every time you use another tool to select things. 

This is not a great workflow. BFA/Blender doesn't have sticky keys or temporary pressed modes unless it's legacy which is being phased out, so.... 

# Solution
![image](https://user-images.githubusercontent.com/35357409/70146779-e73e7600-1670-11ea-86ae-810e6a0a7399.png)

Double Lclick should activate the Tweak tool. Right now it has no legacy equivalent, so it would be the mode we'd default to in all views. Double Lclick on anything or anywhere will activate this mode and escape any other mode, so lasso select can be done with CTRL+Rmouse or Lmouse and then double click will go back to tweaking/transforming - keeping the keyboard relatively free and most usability default toggling within the mouse actions. 

## Reasons
- Double Rclick is already a workflow. Double Lclick should also be a concept that makes sense: go back to tweaking (eg. so you don't get stuck in lasso select needing to use another hotkey to go out of it or back to the toolshelf to go out of it)
- It's quicker than going to the toolshelf and to a hotkey to go out of a tool to get back to work. 
- It makes tweaking and selecting things default by just clicking around, intuitive. 

### Notes
I gave it a whirl, there are no or non-discovered conflicts, it's pretty straight forward. I have tried it out. Might need more testing.

**Comment by ReinerBforartists** [comment]
This is why i opened this issue here ^^ 

Toolshelf - We need a hotkey for Tweak #1288
