### ISSUE TITLE
Put the navigation widget down right?

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1299]
There is a request to have the navigation widget down right.

First we need to discuss if this is even a good idea. It would be a floating element at the bottom then since you can't really put it in the corner because of the sidebar. The benefit would be a less crowded upper right corner.

So shall we try? Or leave it alone?

**Comment by Draise14** [comment]
I think top right makes sense sinçe the distance to other viewport controls (toggles) are right there. Though it might be nice to see.

**Comment by ReinerBforartists** [comment]
That's the second leave it alone then. I also thought to skip this request ^^

So if even then with a toggle in the preference. And something for cold winter evenings when we ever find time ...

**Comment by ReinerBforartists** [comment]
Decision time. Won't do this since i see lots of potential trouble ahead. And no benefit really. The time is better spent at other features.
