### ISSUE TITLE
Rename Armature>Display to Visibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#130]
**Task**
 
Rename the Properties>Armature>Display panel to Visibility to not cause confusion with the viewport Display panel - as one is global data visibility and the other local data visibility and the two "Display" panels are causing confusion.

![bforartists_2018-04-03_13-58-00_li](https://user-images.githubusercontent.com/35357409/38269793-1ccfe002-3747-11e8-9188-3e27b7dee984.jpg)

**Comment by ReinerBforartists** [comment]
Could you please add an image here?

**Comment by Draise14** [comment]
Image added.

**Comment by ReinerBforartists** [comment]
Things like displaying names has nothing to do with visibility. While Display is a fine label here, Visibility does not fit. We could name it Object Display Options. But that's too long.

**Comment by ReinerBforartists** [comment]
Forgot to close this one. Won't do that.
