### ISSUE TITLE
Node Editor - Shader to RGB is missing from converters

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1303]
# Issue
![bforartists_2019-12-11_16-53-18](https://user-images.githubusercontent.com/35357409/70666333-6832da00-1c3c-11ea-9756-2f4f3fb06cdf.png)

Shader to RGB is missing from the side panel. Couldn't find it. 

# Solution
Add this to the Converter nodes panel

**Comment by ReinerBforartists** [comment]
Yep, that's indeed missing. Good catch.

![missing](https://user-images.githubusercontent.com/13919702/70692368-825fcd00-1cbb-11ea-86e5-ad5fd023204b.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master.

I have also chatched a few bugs with two wrong icons and row and col problems. You always overlook something. But it was too small to make an issue for it.
