### ISSUE TITLE
Hotkeys - Outliner - Box select in outliner needs Tweak to work correctly

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1304]
# Issue
Box Select on Bforartists outliner default is broken. You can't click and drag on items to move them to other collections. Right now Box select is permanantly on. 

# Solution
![bforartists_2019-12-11_18-12-13](https://user-images.githubusercontent.com/35357409/70668606-12613080-1c42-11ea-895d-3865ec7e14f2.png)

By adding Tweak to on on the Box Select entries, then the box select only works when you drag on empty spaces.

**Comment by ReinerBforartists** [comment]
This issue already exists here: https://github.com/Bforartists/Bforartists/issues/1221

Closing it as a duplicate now.
