### ISSUE TITLE
3D View - Gizmo Tweak to Click Drag

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1305]
_I know we are doing the toolshelf branch right now, but needed to put this out there to not forget it._ 
# Issue
Right now, Blender keymap has a toggle between mouse press then tweak or click drag for the gizmo transform widgets. Reason being is because the transform widget gizmos take priority over selection underneath the widget sometimes, which is not a desired effect if you want to select things under a widget. 
![bforartists_2019-12-13_14-15-07](https://user-images.githubusercontent.com/35357409/70825682-f9c45800-1db2-11ea-8a6f-7670b5b319be.png)

It can be very frustrating when you are selecting components, and you can't because you have moved the widget, an undesired effect. Because right now, the gizmo gets in the way of selecting things, especially in edit mode. You only want to use the widget when you want to move things, meaning you already are dragging the action - so it should logically only work on click+drag. Single press should select what I want.

# Solution

You can mitigate this by using the gizmo widget with click+drag. 
I think this should be Bforartists default. It's intuitive and makes the widget not get in the way of selecting componenents and objects. 

# Task
![image](https://user-images.githubusercontent.com/35357409/70826484-09dd3700-1db5-11ea-87a3-13467b072392.png)

This is what would change on the default keymap to do this.

**Comment by ReinerBforartists** [comment]
That's okay. I just won't touch it for a while ^^

We have still a task somewhere to find out how to get the same header than with the Blender keymap. Then the user could switch like with the Blender keymap.

**Comment by ReinerBforartists** [comment]
Hm, i can't really see any difference between the two settings. Could you please make an example to make the difference more obvious?

**Comment by Draise14** [comment]
Here is a video showing it.
[https://youtu.be/XjBpN4Vhphk](https://youtu.be/XjBpN4Vhphk )

Basically it's this: 

**Gizmo on press = widget always active under mouse.** Any selection below widget is impossible to select)
**Gizmo on clickdrag = widget only active when using it.** Any selection below widget is now available to select.

**Comment by ReinerBforartists** [comment]
I see. Thanks for the video :)

**Comment by ReinerBforartists** [comment]
Fixed in master
