### ISSUE TITLE
Outliner - Extend Range missing functionality in Keymap

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1306]
_Another one to just document for another day_

# Issue
Right now the Outliner has added extended range functionality. In Blender, it works well. SHIT to add to selection, click off on empty deselects. 
CTRL to select from active to range, click off on empty deselects
CTRL + SHIFT to select from active to range and add to current selection, click off on empty deselects

Bforartists doesn't have this. 

# Solution
Adding back the Blender default keymap functionality for this will help.

# Task
![image](https://user-images.githubusercontent.com/35357409/70838830-0f984400-1dd8-11ea-81fd-336e6e1e5b58.png)

Adding the right Extent Range toggles to these mouse L click combos in the outliner will add this very useful outliner feature.

**Comment by ReinerBforartists** [comment]
Does this functionality exist this way in Blender?

**Comment by Draise14** [comment]
Yes, this is a mirror from the new Blender Keymap.

**Comment by ReinerBforartists** [comment]
Then it's a no brainer.

**Comment by ReinerBforartists** [comment]
Fixed in master
