### ISSUE TITLE
Smart Fill Add-On Modifiers Fail

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#1308]
**Describe the bug**
The Smart Fill Add-On (https://gumroad.com/l/Blender_addons_smart_fill) works correctly in Blender 2.81, but in the latest Bforartists release, the Add-On modifiers do not function at all.

**Desktop (please complete the following information):**
The Operating system: Windows 10 Pro
Both apps launched with Admin priv's

**Screenshots, Example Files**
Blender:
![blender](https://user-images.githubusercontent.com/57046940/70966927-9f90f480-2049-11ea-8c9b-4d61d8d8ef66.jpg)

Bforartist:
![bfor](https://user-images.githubusercontent.com/57046940/70966954-addf1080-2049-11ea-9b2c-7b4daf8b90d8.jpg)

**Comment by ReinerBforartists** [comment]
Thanks for the report. Is there any error in the console?

The curious part is, it is the same code under the hood. We at Bforartists just change the UI. I can't even have a look where the problem could be. It is a paid addon. Best is to contact the addon author.

**Comment by ReinerBforartists** [comment]
Edit says, we could run into a hotkey conflict here. Could you try to use the default Blender keymap?

**Comment by slippystance** [comment]
There's nothing in the console that refers to Smart Fill in respects to an error thrown.  I'll try with the default keybindings as suggested.

**Comment by slippystance** [comment]
Using the default keybindings didn't resolve the issue:

1.  Specified Blender Keybindings in Prefs
2.  Saved prefs (even though it is done automatically)
3.  Quit B4
4.  Launched B4
5.  Attempted to repro issue

Result:  Same results as before.  Modifiers do not work.

**Comment by ReinerBforartists** [comment]
Okay, was worth a shot. Thanks for testing :)

There is nothing that we could do here. So closing this case.

As told, i don't even have the addon code. And even if, we can't maintain addons from others. I fear you have to contact the addon author and ask if he can fix it, sorry. It's his responsibility.
