### ISSUE TITLE
Rename Bone>Display to Visibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#131]
**Task**
 
Rename the Properties>Bone>Display panel to Visibility to not cause confusion with the viewport Display panel - as one is global data visibility and the other local data visibility and the two "Display" panels are causing confusion.

![bforartists_2018-04-03_13-56-48_li](https://user-images.githubusercontent.com/35357409/38269731-eca8e1e4-3746-11e8-88a9-dadb9f4e7133.jpg)

**Comment by ReinerBforartists** [comment]
Could you please add an image here?

**Comment by Draise14** [comment]
Image added.

**Comment by ReinerBforartists** [comment]
Can't do this. It contains display settings. Not Visibility settings. The wireframe or custom shape does not hide. That's display.

We can rename it to Bone Display.

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/13d29d53d26d9d43cb91b7cbbcdd2eb992e584c0
