### ISSUE TITLE
Bforartists toolshelf icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1317]
We migth want to add our own icons in the toolshelf. Not only new ones with adding new tools. But also replacing the current ones. They are too equal in look, color and shape. The eye does not find an anchor. I find it hard to work with those icons. 

![customicons](https://user-images.githubusercontent.com/13919702/71245643-7f955580-2315-11ea-9284-6ae6c8e051bb.jpg)

**Comment by Draise14** [comment]
Oh yes please. Make them consistent with the other designs and also more colourful. The color coding does help a little, but some of them are lineart icons and I prefer the former equivalents. 

I was going to feature request this, but now I know it's a given! Exciting!

**Comment by ReinerBforartists** [comment]
The good news is, we should have most of the icons already. We just need to convert the existing icons from the iconsheet to the new size :)

**Comment by ReinerBforartists** [comment]
I rotate around this task since eons. What once sounded like a good idea is in real not so great the longer you look at it. Just fix what is really broken. When these icons would have been monochrome, then we would have a reason to improve them. 

The icons can be improved for sure. The question is just if it is worth it. As it is now, and especially with the current building system, chances are that we make it worse instead. And we would investigate months to do so.

Hm.

**Comment by Draise14** [comment]
Maybe tackle it at an icon by icon case? There are some icons I would like updating, but some of them so work out nicely as they are, and some already follow our iconography rules. Maybe it's just making the "style" of what exists to be consistent with the rest, like make sure there is no "lineart" shapes, make sure there is form and silluette and true categorized and consistent color coding. There is a bit too much lineart for my tastes on some icons. 

EI, the knife tool. 

In this case.. why not split it up into modes and tool groups as new tasks? Then analyze which could be updated, and which could just be left as is?

And if the system is about generating new icons from Blend, the good thing is we can import SVG to the blends now for the established workflow there. 

But yeah, this is bordering on aesthetic and less about funcitonality and could just be extra work for little. 

Though.. I would love that kind of polish.

**Comment by ReinerBforartists** [comment]
Ah, thanks for the hint of importing svg via grease pencil. Always good to brainstorm. Maybe we have a working pipeline here to create single dat files :)

**Comment by ReinerBforartists** [comment]
> There are some icons I would like updating,

Could you name one or two? Maybe we can do some tests then ...

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/115585961-b674d600-a291-11eb-93f8-ab4ef195f390.png)

Knife and Bisect icons are too similar and are not clear which does what. Bisect is a bit more clear, but knife no.

**Comment by ReinerBforartists** [comment]
Thanks. This would be a good test case if our method with the blend file to create a single icon works :)

**Comment by ReinerBforartists** [comment]
Err, what was the url for the original blend file? ^^

**Comment by ReinerBforartists** [comment]
Ah, have it https://developer.blender.org/diffusion/BL/browse/trunk/lib/resources/

**Comment by ReinerBforartists** [comment]
This is the correct link: https://svn.blender.org/svnroot/bf-blender/trunk/lib/resources/

**Comment by ReinerBforartists** [comment]
What the heck?
This is equal "well" organized than the svg it seems. Geez.


![notorganized](https://user-images.githubusercontent.com/13919702/116657721-30dadf80-a98f-11eb-8c7c-6c8fa2f4c9f0.jpg)

**Comment by ReinerBforartists** [comment]
So far so good. Deleted everything but the knife icon. But the blend file is still full of undeletable things, and has still a size of 5 mb. Not what i want. 

At least i got the first svg imported. With the size of 0.004. And all curves are separated. Means i need to parent it proper after import. And i think i need to convert it to Blender 2.79 then too.

But first let's have a look how big the svg needs to be to import in a proper size. One step after another.

![import](https://user-images.githubusercontent.com/13919702/116664328-98495d00-a998-11eb-8247-6c44799ac1de.jpg)

**Comment by ReinerBforartists** [comment]
Scaling issue resolved.  The units in the svg needs to be cm, not pixels. And with 20 cm it imports as 2 Blender units then. Smelling a bug here, since it should be 200 cm, but anyways.

The blender icon is not 2 units big though, but has a frame area around. So scaled the import size down to 15 cm to stay within the frame bounds. Then converted the Curves to Mesh. Then parented to the ops.mesh.knife_tool, and deleted the meshpart of the original icons.

We have our new knife icon.

Now comes the funny part. Create this icon by script, and have a look if the pipeline works. I expect a fail first. I have used Bforartists 3 Alpha here. The script requires Blender 2.79 from what i remember. 

![rightsize](https://user-images.githubusercontent.com/13919702/116668808-1c521380-a99e-11eb-8a20-8addc9d067cc.jpg)

![parentedconverted](https://user-images.githubusercontent.com/13919702/116668830-23792180-a99e-11eb-8625-25310d66b646.jpg)

![circle](https://user-images.githubusercontent.com/13919702/116668839-2542e500-a99e-11eb-9962-7f804b1930a7.jpg)

**Comment by ReinerBforartists** [comment]
>3

![script](https://user-images.githubusercontent.com/13919702/116670628-41478600-a9a0-11eb-9dbe-a08c533dcccc.jpg)

**Comment by ReinerBforartists** [comment]
>3

![stillnot](https://user-images.githubusercontent.com/13919702/116671725-9041eb00-a9a1-11eb-9741-938ffb943b01.jpg)

**Comment by ReinerBforartists** [comment]
Again one step further. I have managed to compile the icons at Ubuntu.

The icons_geom.blend must be in lib/resources/ . Not in the release/datafiles folder.  

Still stuck though. The advice is for Linux, and works with make icons_geom. That's not how it works at Windows. And here i still get the not found error ...

![ubuntu](https://user-images.githubusercontent.com/13919702/116675505-31cb3b80-a9a6-11eb-9802-3bd8d595da15.jpg)

**Comment by ReinerBforartists** [comment]
One more picture, this time in the blender repo at C

![isthere](https://user-images.githubusercontent.com/13919702/116677534-9e473a00-a9a8-11eb-91ed-c0ccc0952dc0.jpg)

**Comment by ReinerBforartists** [comment]
Tried to create the icon in Ubuntu instead. No luck. I did the mistake to delete all other icons. And destroyed the required structure with it.

Description says the icon must be in the collection Export. Well, we have the collection Export in the Orphan data mode. But not in the Scenes or View Layer mode.  Now go figure. This should not be possible. What's in the Orphan data mode should also be available in the other modes.

![where](https://user-images.githubusercontent.com/13919702/116722046-3ca1c280-a9de-11eb-9cc1-4d51be3a97dd.jpg)

**Comment by ReinerBforartists** [comment]
I still don't undertstand the file structure that is required here. Further experiments ahead ...

**Comment by Draise14** [comment]
Yeah... Maybe just working with the original and swapping things out might work. Removing it all maybe wasn't a great idea. I assume the script compiles everything at once from the same scene. Like.. add a pink dot to an icon from original. Then see and compile.

**Comment by ReinerBforartists** [comment]
Yeah, but i want to reduce it to one icon so that we don't search ourselves to death all the time :)

What i don't get is, i have parented the geometry to the correct object. As shown in the View layer view. But in the Blender view it is not parented. And here we also see why it does not export the icon. It is not in the Export group, errr collection.

![blend](https://user-images.githubusercontent.com/13919702/116724257-b76bdd00-a9e0-11eb-86ca-1c1d71c9af19.jpg)

**Comment by ReinerBforartists** [comment]
The trouble part is to get our new graphics into the export group/collection at all. Let's see if today i am more lucky ...

**Comment by ReinerBforartists** [comment]
No luck. I am clueless how you could move the knife icon into the export collection. There is no way to. The export collection just shows in the blender file mode. I have then dragged it over, it greys out, and Linux fails to compile exactly this icon because it is empty.

This blend file method is an even bigger nightmare than the SVG method.

**Comment by ReinerBforartists** [comment]
This is the problem. There is no way to move or append or parent this new object to the export collection. Not in the outliner, not in the Move to Collections menu.

It must be something obvious. Like running three times around the table and casting a spell or so ...

![movetoexportcollection](https://user-images.githubusercontent.com/13919702/116775896-f42de780-aa65-11eb-92e5-b8812c0d1622.jpg)

**Comment by ReinerBforartists** [comment]
In case you want to test I have added the file to our cloud

https://cloud.bforartists.de/index.php/s/Xnn9Ctt9NJ8MQam

**Comment by ReinerBforartists** [comment]
In case someboy wants to have a look too, i have added the example file to our cloud 

https://cloud.bforartists.de/index.php/s/7RXd6JsLeHaPdFb

**Comment by iyadahmed** [comment]
Maybe it could be linked to the collection using Python, but indeed there should be an easy way 🤔

**Comment by ReinerBforartists** [comment]
We were beaten by the obvious here. Have a look into the properties editor at the right. Add to collection ...

I think it would be a good idea to add this functionality to the outliner too. I haven't even thought to search in the outliner here.

**Comment by iyadahmed** [comment]
XD glad it was found

**Comment by ReinerBforartists** [comment]
Still doomed. I miss an important step here ...

![nonetype](https://user-images.githubusercontent.com/13919702/116860432-da290c00-ac01-11eb-8006-33e99560e9b4.jpg)

**Comment by iyadahmed** [comment]
Seems like an object needs to be active for the script t work

**Comment by iyadahmed** [comment]
Hmm, seems like an object needs to have an active vertex color for the script to work

**Comment by ReinerBforartists** [comment]
Yes, but it has already one. Investigating into the materials at the moment too. Ah the fun ... ^^

**Comment by iyadahmed** [comment]
Ah the fun, I hope the issue is found soon

**Comment by ReinerBforartists** [comment]
So, from scratch. I have reduced the whole icon file down to the bevel icon now. Changing the material changes the compiled result. So the color is not in the vertices, but material based.

![result](https://user-images.githubusercontent.com/13919702/116977687-05bffb00-acc3-11eb-97e5-020f704237df.jpg)

![ base](https://user-images.githubusercontent.com/13919702/116977755-196b6180-acc3-11eb-83e9-7015c745795b.jpg)

**Comment by ReinerBforartists** [comment]
Here the blend file. Now starting with some experiments again ...

[icon_geom_bevelicon.zip](https://github.com/Bforartists/Bforartists/files/6420109/icon_geom_bevelicon.zip)

**Comment by ReinerBforartists** [comment]
Added a knife icon placeholder. Now let's have a look how we can get our knife graphics in here ...

![test](https://user-images.githubusercontent.com/13919702/116986939-b5e73100-acce-11eb-80d2-3435da56a538.jpg)

**Comment by ReinerBforartists** [comment]
Houston we have a material problem. The knife arrives white O_O . But hey, i think we have a pipeline \o/

One of the meshes did not have a vertex color assigned. That was most probably the trouble maker before. 

Anyways, we have now a reduced file to just one icon where we can create all new icons in. And we need to test the pipeline with new tools then too. But first let's solve the material issue here ...

![arrived](https://user-images.githubusercontent.com/13919702/116990432-622b1680-acd3-11eb-86db-089efb3158c8.jpg)

**Comment by Draise14** [comment]
When you import SVG, there most likely would be Zclip. So you might have to pop up and out the different layers so they are stacked correctly - this might be the reason why it's all one colour instead of multiple. 

The other debate is.. do the files it generates support more than one colour?

**Comment by ReinerBforartists** [comment]
The layers are no problem. The parts doesn't overlap. And i have to convert it to mesh before i can export it again. And it is one material per mesh. We have four mesh parts here, and so we have four materials.

What still bafles me is the size of the exported dat file. It should not be this big. Heaven knows what extra information gets stored here. Maybe it is really a layer for each material and its color. We will see.

**Comment by ReinerBforartists** [comment]
Works. Will try to document it tomorrow.

![done](https://user-images.githubusercontent.com/13919702/117038223-acc68600-ad07-11eb-98ed-95d82b4cae2a.jpg)

**Comment by ReinerBforartists** [comment]
Any more wishes to change icons?

**Comment by ReinerBforartists** [comment]
What makes me really angry here is that we are again limited to just a few colors and sharp shapes. That we can't use prerendered icons that just comes in as they look at the png file, with color gradients when there are some. And that we have to use a this massive and super complicated nerd pipeline to create png files out of png files that gets finally converted to dat. Still at thinking if it was really a wise idea to close the other task to create a script that creates our icons directly. 

But on the other hand, i tried really hard to understand the code mess to create the dat files, and i was never able to get a foot into the door. I could never find out how this is all connected and how it works. Sad :(

**Comment by ReinerBforartists** [comment]
Not happy with the look of the knife icon in this size and location here. I will try to improve it.

**Comment by iyadahmed** [comment]
> What makes me really angry here is that we are again limited to just a few colors and sharp shapes. That we can't use prerendered icons that just comes in as they look at the png file, with color gradients when there are some. And that we have to use a this massive and super complicated nerd pipeline to create png files out of png files that gets finally converted to dat. Still at thinking if it was really a wise idea to close the other task to create a script that creates our icons directly. 
> 
> 
> 
> But on the other hand, i tried really hard to understand the code mess to create the dat files, and i was never able to get a foot into the door. I could never find out how this is all connected and how it works. Sad :(

Maybe we can keep the other task open in hopes it will br solved

**Comment by ReinerBforartists** [comment]
Do you want to have a crack at it? :)

**Comment by iyadahmed** [comment]
Yep I can try

**Comment by ReinerBforartists** [comment]
Oki. Task is open again: Good luck :)

**Comment by ReinerBforartists** [comment]
Improved the knife tool icon ...

![betterknife](https://user-images.githubusercontent.com/13919702/117287711-efed3a00-ae6a-11eb-9b58-82abfe2eefe1.jpg)

**Comment by ReinerBforartists** [comment]
The work of this day. Will also link it in the developer section of the page.

https://www.youtube.com/watch?v=xrz_vZa1psM

**Comment by Draise14** [comment]
This is excellent, but crazy how.. large the process is. 

Thanks for changing the knife tool. I might have added a bit of a contextual thing for the knife, like the geo it is drawing a little (since we have more realestate) - but I like the new trend! Color and silhouette on the icons - and more readability and uniqueness. Know I know it's a knife. 

I can't help but want to be greedy and have them ALL changed to be consistent BFA icons and remove the lineart icons completely. 

Just look at this! It was nearly impossible. You had to read. 
![image](https://user-images.githubusercontent.com/35357409/117382362-f4821480-aea3-11eb-9986-bde49f94bbf5.png)

**Comment by ReinerBforartists** [comment]
Yes, now we know that we have the knife tool active. But "All" is quite a task. Not sure if we can manage this :)

And yes, this pipeline is plain crazy. Even when we have a working way now. There is no way to work pixel perfect or color perfect. The result will always turn out washy. And the emission colors makes other colors than expected. And we are limited to a handful colors and no gradients.

I guess i will wait until Iyad had a crack at the png to dat script before we continue here. This way here is everything but funny. So postponing for now.

But feel free to list a few icons that needs a change. Just not "ALL", this is no task to solve. This task here needs to be done step by step :)

**Comment by ReinerBforartists** [comment]
I have uploaded the reduced icon_geom.blend to our file repository
https://github.com/Bforartists/files/tree/master/blender_toolshelf_icons

And the new toolshelf icons goes now here. Each in a folder with their ops name, to keep things well organized: https://github.com/Bforartists/files/tree/master/iconset_bforartists_2/toolshelf_icons/ops.mesh.knife_tool

**Comment by ReinerBforartists** [comment]
Related

Create script to create single dats from icon images for toolshelf #1318

**Comment by ReinerBforartists** [comment]
This task has fulfilled its purpose. Closing.
