### ISSUE TITLE
Create script to create single dats from icon images for toolshelf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1318]
I want to get rid of the Blender nerd way to create the toolhself icons. Which is to create a model of the icon, put them all into one blend file, and export them then by a special script. 

It's the same crap system that we have with the svg file already. There is no need for the 3D models. Just convert a png to dat.

See this thread: https://www.bforartists.de/content/tool-shelf-blend-file-new-icons

**Comment by Draise14** [comment]
... just curious, the toolshelf icons are actually - after all - DAT files!? I thought they did them from 3D because.. they wanted vectorized icons to scale them better.

**Comment by ReinerBforartists** [comment]
Of course they are :)

They are in \release\datafiles\icons

**Comment by ReinerBforartists** [comment]
Magic happens in source\blender\datatoc

**Comment by ReinerBforartists** [comment]
Other things first. Postponing.

**Comment by vic3t3chn0** [comment]
About this issue of the script. I dig it up now and I found a few issues on
the python scripts.

I am building a version to test, then I will make another one with the
right png files and callbacks for python scripts.

We need stable icons for Bforartists software. The error on Mac for that is
inside the release/darwin folder in conjunction with source/blender.

Later I will let everybody what happened.

**Comment by ReinerBforartists** [comment]
Could you please make a separate issue or post it in the script issue? This issue here was about the blend file, and is solved :)

**Comment by vic3t3chn0** [comment]
My mistake.

**Comment by ReinerBforartists** [comment]
No problem :)

**Comment by ReinerBforartists** [comment]
Oops, i was wrong. You are already in the right thread. Mondays is not my day it seems. Big sorry from my side.

Just curious, what exactly is your issue at Mac with the icon creation scripts? As told, we want to get rid of the old Blender scripts anyways if even possible, and have a script that does just convert one icon at a time.

**Comment by ReinerBforartists** [comment]
EDIT says, note that there are two scripts. blender_icons_update.py for the traditional 16 px icons. And the one that converts the blend file. blender_icons_geom_update.py Bot in release\datafiles directory.

**Comment by vic3t3chn0** [comment]
I saw. I am seeing that for Mac and Ubuntu

**Comment by ReinerBforartists** [comment]
And what is the problem you encountered?

**Comment by vic3t3chn0** [comment]
The icons are not set correctly.

**Comment by ReinerBforartists** [comment]
Okay, then we have a bug. It should create the icons just fine. At Windows it does. This is a different issue then, and my first thought was right.

Could you please open a new issue for it, and describe the problem in detail?

**Comment by ReinerBforartists** [comment]
Best with a screenshot if possible, and error message if available ...

**Comment by vic3t3chn0** [comment]
Sure. I will send later.

**Comment by ReinerBforartists** [comment]
Draise had the idea to go across the blend method, with a svg. When we have just one 3d mesh in the file then we should theoretically produce one icon only. Maybe a possible pipeline, without to write a script from scratch. Maybe it is done by some small modifications at the blender_icons_geom.py script.

**Comment by ReinerBforartists** [comment]
Related

Bforartists toolshelf icons #1317

**Comment by ReinerBforartists** [comment]
This task is obsolete now. We have a working pipeline to create toolshelf icons.

Closing.

**Comment by ReinerBforartists** [comment]
Reopened. Good luck :)

**Comment by iyadahmed** [comment]
interesting
https://devtalk.blender.org/t/splitting-the-icons-svg-file/18937

**Comment by ReinerBforartists** [comment]
I have already commented at the issue in the Blender tracker. I doubt that something useful will happen. But we will see :)

**Comment by ReinerBforartists** [comment]
Another task that simply lasts too long now. There is a open blender issue to separate the svg files. Which goes into the direction what we wanted to do here: https://developer.blender.org/T88467

We can come back to this issue in case the task gets abandoned. For now let's do the blender devs their work.
