### ISSUE TITLE
Installing a new version - add hint to uninstall the old version first

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1320]
As the title says, we need to add a hint to uninstall the old version first. Or alternatively i need to investigate how to modifiy the installer so that you can have multiple versions installed.

**Comment by ReinerBforartists** [comment]
Phew, making an installer that handles all possible changes is mission impossible. And i don't want to install in different directions neither. It is Bforartists 2. All of it. So one possible way is to remove all possible old content first. Investigating into InstallDelete

http://www.jrsoftware.org/ishelp/index.php?topic=installdeletesection

**Comment by ReinerBforartists** [comment]
This should do the trick when i have understood it right:

[InstallDelete]
Type: filesandordirs; DestDir: "{app}"

But let's wait for the next official version. Then we can test this change.

For now let's update the manual first.

**Comment by ReinerBforartists** [comment]
Updated the manual: https://github.com/Bforartists/Manual/commit/9788ab37c4b80619737f3e4d3534e9056ff1a482

**Comment by ReinerBforartists** [comment]
Hm, doesn't work. Looking for another solution.

**Comment by ReinerBforartists** [comment]
Okay, it's now two independant apps. That's the easiest solution.

![differentapp](https://user-images.githubusercontent.com/13919702/74525349-2e729e00-4f21-11ea-9f45-0fc9ef35693e.jpg)

Fixed.

**Comment by Draise14** [comment]
Ah yes, great. Good solution.
