### ISSUE TITLE
File Browser - make blend file folder icons less transparent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1328]
# Issue
![bforartists_2020-01-02_15-46-54](https://user-images.githubusercontent.com/35357409/71692179-38787d00-2d77-11ea-9a8d-060fdb988627.png)

The icons for the folders are great when you open a blend file.. just.. they are really transparent. 

# Solution
Can default be less transparent?

**Comment by ReinerBforartists** [comment]
What the heck? O_O

**Comment by ReinerBforartists** [comment]
This is by Blender design.

![bydesign](https://user-images.githubusercontent.com/13919702/71711990-b2564800-2e03-11ea-8e4d-cb2c98d27e08.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![miniicons](https://user-images.githubusercontent.com/13919702/72976714-63cd1580-3dd3-11ea-89a0-8c821f71b88d.jpg)

**Comment by Draise14** [comment]
Excellent! Nicely done.
