### ISSUE TITLE
Rename "Display" side panel to "Viewport Display"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#133]
Rename "Display" to "Viewport Display" to make sure there are no misunderstandings. 

This area has caused confusion with other display panels, as this generally is a global viewport data toggle areas elsewhere in the UI.

**Comment by ReinerBforartists** [comment]
This lengthen the names. And makes it harder to read. But i think it is worth the longer name!

**Comment by ReinerBforartists** [comment]
Fixed in master
https://github.com/Bforartists/Bforartists/commit/e4688c18523090625a3253f6aa0330ea4576a33b
