### ISSUE TITLE
Change Bforartists keymap to press down behaviour at selection

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1331]
Blender selects at release. Max selects at press down. That's a tad bit more responsible. So we should investigate if we from Bforartists can change our keymap to that behaviour too.

See polycount Blender mega thread: https://polycount.com/discussion/comment/2712958/#Comment_2712958

**Comment by ReinerBforartists** [comment]
Seems that Blender developers are aware of the problem too. So we definitely need to update our keymap to this.

https://devtalk.blender.org/t/20-january-2020/11270

> Extend selection with the Tweak tool is now more responsive, happening on mouse press. (William Reynish)

**Comment by ReinerBforartists** [comment]
This is more complicated than thought. There is no release event in the keymap at all. They are already all Press. Also in the Blender keymap. I guess i need to ask the guy over at polycount what exactly he has changed.

**Comment by Draise14** [comment]
They removed Release?

**Comment by ReinerBforartists** [comment]
No. But the events are all set to press, not release.

**Comment by ReinerBforartists** [comment]
I have written one of the folks in the polycount thread a pm now. Postponing until i got an answer.

**Comment by ReinerBforartists** [comment]
No response. And from my point of view there is nothing to fix at this point. Closing this task for now. We can recreate or reopen it at any point.
