### ISSUE TITLE
Drop Down Menus from Tool Settings bar - Needs Iconology (and buttons instead of checkboxes)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1332]
# Issue 
![unknown(4)](https://user-images.githubusercontent.com/35357409/72630619-b3699800-3920-11ea-8ba8-a0c35d23c2eb.png)

These drop down menus from tools settings bar are handy that they are available and there - organizing panels for quick access hidden away from larger screen realestate. 

BUT

They are hard to use as a good UX. There is no quick glance system to use them well, no quick mouse toggling system intuitively. 

# Solution
![bforartists_2020-01-17_11-53-10](https://user-images.githubusercontent.com/35357409/72630598-aa78c680-3920-11ea-8ad8-c977bfb2a62b.png)
They need icon labeling to make them easier to use. They need to be toggle buttons instead of checkboxes. 

This might also be true of Panels tool settings. 

When we change toggle check boxes into buttons, it's easier to know what's on, what to click on it become easier to use (buttons are bigger, labels are on the button, buttons can have an icon that makes sense). 

![bforartists_2020-01-17_11-59-23](https://user-images.githubusercontent.com/35357409/72630668-d136fd00-3920-11ea-8684-1656d8706f30.png)

Bigger clicking real estate helps. Iconology also saves on reading these menus. If the labels or buttons had icons for the functionality, it might be easier to memorize, understand at a glance and create better visual muscle memory more efficiently. 

# Notes
If these drop down double entries get updated to buttons and iconofied, then panel equivalent in the tools settings in the Properties Shelf and Properties editor might need to also update that system for consistency. 

There is nothing wrong with Checkboxes... just... labeling or the UX for interactivty could be improved. It's not always logical to click on a title to activate a tickbox to the side. Elsewhere in the UI, this is not possible. 

# Reason
Making checkboxes into buttons adds to the intuition that you can click on a label to select. Sometimes a checkbox requires precision toggling (if a user is not aware that a title will turn or turn off the tickbox).

Adding icons to buttons or to the labels ads to visual muscle memory.

**Comment by ReinerBforartists** [comment]
This task is too general. Please make tasks that can be solved at a one by one case.

In general, most of the checkboxes are checkboxes for good reason. No good idea to make them icons then. But in the cases where it makes sense, see ablove. Please make tasks that can be solved at a one by one case :)

**Comment by Draise14** [comment]
What is the good reason for checkboxes in this UX? 

This is more a design proposal/discussion to later close then make into tasks.

**Comment by ReinerBforartists** [comment]
On Off
