### ISSUE TITLE
Organize wireframe workflow by defining global and local wireframe workflows. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#134]
The wirerfame tools are in two unclear areas and the workflow is unclear. 

One wireframe feature is global, and the other local - and another feature is based on colours and another on Wiretools which work both globally and locally on toggle. 

This task attempts to create a unified and clear workflow. 

**How?**
Move/limit global wireframe tools to "Viewport>Display" panel away from the "Shader" panel or limit/move local wireframe tools to a new object "Visibility" panel (_mentioned in the Redifine Display milestone_)  if exclusively used on a per-object basis. If both systems are intact, then it must be evident which one is for global and which is for local and each in their Display/Visibiilty panels respectively and exclusively - once.

This may need to look at how the Wiretools works and modifying to keep it consistent with the other panels and wireframe feature tools. 

**Task**
Seperate Global and Local wireframe modes and move to correct areas (Display and Object>Display respectively)  - remove from "Shader" panel. 

![bforartists_2018-04-03_13-44-29_li](https://user-images.githubusercontent.com/35357409/38269551-79ce67fc-3746-11e8-8fa8-fa43c59b5628.jpg)

![epicpen_2018-04-03_14-03-18](https://user-images.githubusercontent.com/35357409/38270063-eea9be7c-3747-11e8-90dd-fd8da33e3818.png)

**Comment by ReinerBforartists** [comment]
What is the task here?

**Comment by Draise14** [comment]
Added task to keep it more clear and image to illustrate. Would this one need to be broken down to smaller tasks?

**Comment by ReinerBforartists** [comment]
I don't understand a single word here, sorry :)

May i suggest not to use hand drawn letters in the image? In Gimp you can add text ...

**Comment by ReinerBforartists** [comment]
When you can break it down, then you better break it down ;)

**Comment by Draise14** [comment]
Ok, gonna close this and make 1 - though there are.. 3, but will update the image - they are cascading, cant'do one without the first... so....
