### ISSUE TITLE
Move World Background toggle to "Shading" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#135]
**Task**
Move world background toggle in "Display" panel to "Shading" panel. 

**Why?** 
Because this really affects and uniquely affects lighting/rendering of that viewport - not viewport global data displays typical of the "Display" panel. "Shading" is more an artistic tool for the viewport really, not global data display.

![bforartists_2018-04-03_13-41-41_li](https://user-images.githubusercontent.com/35357409/38268930-ebf0126a-3744-11e8-9168-6c52b7b69f9a.jpg)

**Comment by ReinerBforartists** [comment]
Could you please add a image ?

**Comment by Draise14** [comment]
Added

**Comment by ReinerBforartists** [comment]
Can't do this, sorry. World background is a Display option for the Viewport, no Shading option for the mesh.

**Comment by Draise14** [comment]
Ah ok... Ambient occlusion, backface culling, depth of feild.. are not mesh options either... but shading options for the viewport. Background colour/image is not data to be viewed in the viewport, but aesthetic as much as the AO and DOF is - but yeah.. I guess it's debateable.

**Comment by ReinerBforartists** [comment]
They are mesh related. Background is not.

**Comment by Draise14** [comment]
Ok. I had trouble finding that toggle in Blender and BFA and so have my teammates, just saying... So the "Shader" Panel is not the viewport toggles, but really... mesh display toggles? Hmm..

**Comment by ReinerBforartists** [comment]
That's the curse of the subtabs. We could remove this subtab again. Then you have everything in the view again.
