### ISSUE TITLE
Wire Tools - Seperate wireframe workflow to global and local

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#136]
**Task**
Separate Global and Local wireframe modes workflow. (Display and Object>Display respectively) by creating a set of local wireframe buttons and global wireframe buttons (instead of a toggle to change function of buttons). This workflow is confusing. 

**Cascading task**
If this can be done, would open up possibility to clear out the Shader panel and cleaun up the wireframe workflow and UI areas to single entries. 

![epicpen_2018-04-03_14-09-29_li](https://user-images.githubusercontent.com/35357409/38270420-f8c5e862-3748-11e8-94f2-aaa11a19a4c0.jpg)

**Comment by ReinerBforartists** [comment]
Wire Tools is an addon. When you want to rewrite this addon, feel free to do so :)

**Comment by ReinerBforartists** [comment]
We don't maintain addons. 

Closing.
