### ISSUE TITLE
Toolshelf Editor - Custom button entries with new category

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1361]
# Issues
Right now, the custom toolshelf is very very useful, one of the strongest features of BFA, and more, but when it comes to addons and other development tools, a button cannot be assigned any custom operators nor be created - you can't edit or add to it to further customize it with a bit more depth.

# Solution
In the addon, you can toggle which toolbars are available. 

Could it be possible to have slot based buttons in a custom category where you can assign an operator in the addon preferences of the toolshelf editor? 

### Tasks
- Add a category with custom buttons (fixed or dynamic list)
- Add ability to assign custom operators to buttons 
- Add the ability to potentially choose an icon for the button

## Benefits
So now there are a set number of buttons you could assign and put to use with custom operators, kinda like a stronger Quick Menu but in the toolshelf and with potential icons. 

#### Notes
The custom button row could be just numbers for the icons, without custom icons.

To assign an operator could just be a right click dialogue on the button. 

Documentation would just need to add the feature that you can copy data path/operator and paste into the slot of the addon (or even say so in the addon). 

### Examples
The Modifier List addon has a number of dynamic slots where you can choose or select the modifier. The Toolshelf Editor addon could also have a similar system to show/add buttons from addon operators and other custom operators. 
![bforartists_2020-02-10_17-51-41](https://user-images.githubusercontent.com/35357409/74197784-0ab40d00-4c2e-11ea-8dca-15da46dbc9ab.png)

**Comment by ReinerBforartists** [comment]
Interesting idea for sure. But i don't see a way to do this in our toolbar code. So as sorry as i am, i fear i have to close this one. 

But we already have such a feature in the UI. It's called quick favourites menu.

**Comment by xan2622** [comment]
Oh, I am pretty sad and disappointed that you closed this feature request this quickly. 
Customizable toolbars are pretty common (**and so useful**) in other 3D softwares.

The _Quick Favourites_ and this idea (custom buttons on toolbars) are slightly different concepts. 
Of course, both allow to add custom commands (buttons) onto an area, area that is quickly accessible to the user. 

But frankly, the _Quick Favourites_ menu is not very user-friendly. It's just a vertical list of favourite commands. AFAIK, there's no way to group or sort these entries.

Customizable toolbars : 
- would allow to have all the user's favourite commands at sight, quickly accessible,
- would allow to groups user's favourite buttons, 
- would allow to separate buttons thanks to empty icons (separators)

Please change your mind 🙏

**Comment by Draise14** [comment]
It might be due to a limited architecture in the code structure of addons, so it's not possible to add customization without a large investment of time/investigation... so it's not easy to add. 

Someone will have to look at example addons and see how to make custom entries elsewhere, then see how to implement it - but so far for now, the code can't allow it... 

@xan2622 , maybe try do some investigation of differnt addons that make customizable buttons elsewhere in the interface and see how they work, so that some of the leg work can be saved.

**Comment by xan2622** [comment]
> It might be due to a limited architecture in the code structure of addons, so it's not possible to add customization without a large investment of time/investigation... so it's not easy to add.

Don't worry, I do understand that sometimes, features can't be easily added. I just hope that this idea (custom buttons entries on toolbars) can be implemented in the future.

> Someone will have to look at example addons and see how to make custom entries elsewhere, then see how to implement it - but so far for now, the code can't allow it...

> @xan2622 , maybe try do some investigation of different addons that make customizable buttons elsewhere in the interface and see how they work, so that some of the leg work can be saved.

The first addon that I think of, is **Pie Menu Editor**: https://blenderartists.org/t/pie-menu-editor-1-16-4/662456

Unfortunately, I have zero knowlege in development/coding (but I have just started learning python a few days ago).

**Comment by ReinerBforartists** [comment]
Hi xan,

It's not that i don't see the usefulness of such a feature. But this would most probably keep me busy for months. It would be a complete rewrite of how the toolbar addon works. And i am still not sure if i  could manage what you want here. Nor if i could come up then with something that is really an improvement over the current situation. As told, we have the quick favourites menu already for this purpose.

And the toolbar has its limits. Blender code design does not longer allow to call operators that depends of a specific editor type. Like most of the polygon tools in the 3D view.

And this all leaded to the decision to decline this request as not manageable.

Kind regards
Reiner
