### ISSUE TITLE
The flash screen shows wrong version details of the Bforartists and Blender.

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#1362]
**Describe the bug**
The flash screen shows wrong version details of the Bforartists and Blender.

**Desktop (please complete the following information):**
Windows 10 (but it is irrelevant here)
The Bforasrists version is **devbuild-09-02-2020.zip** 

**Screenshots, Example Files**

![image](https://user-images.githubusercontent.com/9047168/74228430-6cd04900-4ce6-11ea-9ebd-2f9349f507ae.png)

This flash screen shows Bforartists version as 0.8.0. **[BUG#1]**
How can it be a static number if it is a nightly?
The date of release (09-02-2020) should be embedded in its version number.

The flash screen shows the source Blender version as "2.81 final/2.82 alpha". **[BUG#2]**
But the download page describes that the development version is based on **Blender 2.83 Alpha**.
Therefore, replace "2.81 final/2.82 alpha" with "Blender 2.83 alpha" 
- If it is actually based on the latest **nightly version of Blender**, then its version should be mentioned (date).

**Comment by ReinerBforartists** [comment]
Thanks for the report. 

The idea is of course nice. But at this point it would be too much effort to care of these entries for the nightly builds too. I want to keep my workload as small as possible.

As mentioned at the page:

> Note that there is no version hint in the developer build. It shows the splashscreen and version number from the last official release when you start it. The folder name shows you the creation date. The newer, the more actual.

**Comment by Draise14** [comment]
Ah, I have been wanting this personally, cause I use different build versions. How would you technically do this? Out of curiosity?

**Comment by ReinerBforartists** [comment]
This is hardcoded in release\scripts\startup\bl_operators\wm.py , line 1712

**Comment by Draise14** [comment]
Thanks, now I can have an official and dev builds from branches without getting confused which is which.
