### ISSUE TITLE
rna_uiItemR: property not found: SceneEEVEE.shadow_method

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1363]
This bug came out of the blue. Needs investigation.

![shadowpropertynotfound](https://user-images.githubusercontent.com/13919702/74262568-66010080-4cfd-11ea-8f9f-ccdba6305d38.jpg)

**Comment by Draise14** [comment]
This is due to the change in Shadow method under Properties Editor>Render Settings>Shadow. Removing that line will fix it (they changed the shadow method recently). _I forgot to report this one cause I fixed it myself... oops. *embarrassed face*_

**Comment by ReinerBforartists** [comment]
AAAaaah hah! Going to fix this one now ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
