### ISSUE TITLE
Rename "Display" to "Object Display" or "Local Display" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#137]
**Task**
Rename "Display" to "Object Display" or "Local Display" to make sure there are no misunderstandings. There is not mouseover on the bar title and it is easily confused with the viewport display panel for global settings. 

**Why:**
This area has caused confusion with other display panels, as this generally is a local mesh viewport data toggle area.

![bforartists_2018-04-03_13-59-16_li](https://user-images.githubusercontent.com/35357409/38270601-7e1825ca-3749-11e8-951e-9c8164a37c4e.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/1198bbd387a456085e7e64c729c1409224252ec5
![objectdisplay](https://user-images.githubusercontent.com/13919702/38927027-c2b11fe0-4304-11e8-97b4-209906788c04.jpg)
