### ISSUE TITLE
Mesh Relax addon needs a menu entry

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#138]
The mesh relax addon just shows in the Specials menu. Crazy decision. Bforartists does not access this specials menu.

Adding a menu entry for it is not too complicated, and we don't change functionality of the addon. And this addon is really handy. So let's fix it.

![meshrelax](https://user-images.githubusercontent.com/13919702/38354373-a962983e-38b9-11e8-8bcd-9229b12f2ffb.jpg)

**Comment by Draise14** [comment]
Would be awesome.

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/971095ff5be46277d4f0b3982603840810630667
![meshrelax](https://user-images.githubusercontent.com/13919702/38407711-d7c50506-397a-11e8-87b5-113b82cde21b.jpg)
