### ISSUE TITLE
3D View - Left click deselect problem

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1384]
We have assigned the move rotate and scale tools to the tool shelf. The problem now is, activating for example the move tool and a drag click asides not longer moves the object, but deselects it. This is a workflow killer. And i consider it as a showstopper for polygon modeling. You can't pull vertices around this effective anymore.

We need to investigate how Blender behaves here, and if we can get our old workflow back somehow.

**Comment by ReinerBforartists** [comment]
Draise, what is your opinion here?

**Comment by ReinerBforartists** [comment]
Seems that we need to readd our old keys here to get old functionality back. Let's have a look if we can get this even to work to have the same key for two operators. Maybe with press and release.

**Comment by Draise14** [comment]
Hmm. I have my setup different. I can't seem to reproduce your issue. 

Is the problem: you click+drag off any object/component and it deselects - and you just want to continue transforming instead? 

I drop my drag threshold to 1px and my mouse drag threshold to 1px also (default is 30px to 3px respectively). As you can see, 30px to trigger the drag (with no drag, it "selects/deselects") is ridiculously high. Having it less makes the tweaking more responsive (no frame drops as you drag) and also more predictable (only a quick click would deselect as expected - no chance an accidental press + drag will deselect/select)

Dropping the dragging thresholds makes the tweaking/transforming more responsive and removes the accidental de-selecting/selecting when you don't drag enough to keep the transformation mode on.

**Comment by Draise14** [comment]
![bforartists_2020-02-24_10-16-52](https://user-images.githubusercontent.com/35357409/75164433-cf661380-56ee-11ea-9637-62b1f50af41a.png)
Ah. Now I see it. It's not working with Tweak tool. 

I had to change the move in 3D View (Global) to Tweak Left.

**Comment by Draise14** [comment]
Now, the tweak thresholds for more responsive predictable behaviour probably should be another task.

**Comment by ReinerBforartists** [comment]
Thanks Draise. I'll have a look at it tomorrow. But you can assign here too, and fix it if you want :)

**Comment by ReinerBforartists** [comment]
Okay, let's have a look at this one.

**Comment by ReinerBforartists** [comment]
Hmm, your fix doesn't work here. Not sure if i do something wrong, or if we misunderstand each other.

**Comment by ReinerBforartists** [comment]
I made a video of the problem. As told, maybe we misunderstand each other here.

The problem is that the left click deselects. We loose the ability to move already selected vertices around since we basically need to select them again for the next transform operation. Remember, the click in the off deselects the object.

https://www.bforartists.de/data/dev/videos/deselect.mp4

**Comment by ReinerBforartists** [comment]
We need to revert this one: 3D View - click in empty space does not deselect #901

**Comment by ReinerBforartists** [comment]
Woah, this one was a challenge. But i think i have it. The tweak tool made the fun. Deselect on Nothing. I still don't understand why unticking this option fixes the issue with move, rotate and scale, since Tweak is not active and in use then, but it does. 

Still at evaluating if this change causes problems. But looking good so far. The tool is working now as i expect it. And the deselect on clicking into the empty space is still working fine.

![deselect](https://user-images.githubusercontent.com/13919702/75234394-d8241b80-57ba-11ea-92e8-df083336587f.jpg)

**Comment by ReinerBforartists** [comment]
Challenge accepted!

Most probably caused by one of the latest merges. Let's see if this disappears after changing the keymap. If not then this becomes a own task.

![keymapprob](https://user-images.githubusercontent.com/13919702/75235548-b0ce4e00-57bc-11ea-9033-6c8d13189088.jpg)

**Comment by ReinerBforartists** [comment]
/&)%)(&HOÜ(/&ASDFASDF!!!!

![wrong](https://user-images.githubusercontent.com/13919702/75235894-4538b080-57bd-11ea-9f4e-57670746d36c.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master.

Finally \o/

And the moaning in the console is also gone. As expected a hiccup from one of the latest merges where they have changed something at the keymap again.
