### ISSUE TITLE
addon mesh tinycad dont work

### ISSUE THREAD

**Issue by emilsvfx** [Bforartists/Bforartists#139]
mesh tinycad disappear  don't appear in mesh tools property
@bfa 9.6.0

**Comment by ReinerBforartists** [comment]
Thanks for the report. 

Another addon that just shows in the Specials menu, which Bforartists does not access. Will be fixed.

![tinycad](https://user-images.githubusercontent.com/13919702/38386577-5152f862-3915-11e8-8c79-a5a05f3a22c8.jpg)

**Comment by ReinerBforartists** [comment]
Made a mistake here. Tools belongs into the tool shelf. So reopening.

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/f925a0487ed81403fa73ca8ad76c766340226ef9
Panel is definitely the better location ...

![tinycadpanel](https://user-images.githubusercontent.com/13919702/38408672-d918150c-397e-11e8-90b4-c67787c4a4a3.jpg)
