### ISSUE TITLE
Toolshelf - readd tabs

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1402]
In Blender 2.79 we had tabs in the tool shelf. This got removed in Blender 2.8 because of the new tool shelf buttons. 

This issue might still be a mission impossible. We haven't managed it yet. And won't for Bforartists 2 gold. But i want to keep this issue alive. Maybe we find a way at a later point.

Commits in question are:

Revision: c10f137
Author: Campbell Barton ideasman42@gmail.com
Date: 10.06.2018 15:40:02
Message:
UI: remove tab use in the tool-settings

Revision: 6be7a98
Author: Campbell Barton ideasman42@gmail.com
Date: 26.10.2018 06:05:07
Message:
PyAPI: raise error when toolbar panels use tabs

Add-ons that register panels in the toolbar can
no longer use 'bl_categories' (tabs).
Modified: release/scripts/startup/bl_ui/space_toolsystem_toolbar.py
Modified: source/blender/editors/screen/area.c
Modified: source/blender/makesdna/DNA_screen_types.h
Modified: source/blender/makesrna/intern/rna_ui.c
Modified: source/blender/windowmanager/WM_toolsystem.h

**Comment by ReinerBforartists** [comment]
I guess i need to find the commit where they have added the tabs to the sidebar ...

**Comment by Draise14** [comment]
Good luck with this one. I miss this feature from BFA1.

**Comment by ReinerBforartists** [comment]
Tools region code is still in source\blender\makesrna\intern\rna_space.c , line 779

**Comment by ReinerBforartists** [comment]
@iyadahmed , i eagerly need your help here. I am completely lost with this chapter :)

**Comment by iyadahmed** [comment]
I have tried at this but unfortunately didn't manage, maybe we could try again in near future, I had another idea of removing the tool shelf system and creating a new one, but that would take longer

**Comment by ReinerBforartists** [comment]
So you are trapped here too. Damnit, you were my last hope :D

Thanks for having a look at it :)

Well, there is not this much work left in the tracker. Now's the time to tackle this beast. In the one or another way. 

There must be an easy solution somewhere. Adding panels still works. It just doesn't show the tabs anymore. And the movie clip editor for motion tracking still has the toolshelf with tabs. It is all there, it is just implemented in the Blender way. Hard to understand, hard to figure out. And as usual badly documented. Have you had a look at the two commits from above that i have digged out? These are the ones that made the toolshelf tabs disfunctional. But reverting them just leads to a ton of errors.

The alternative would be a native OpenGL panel system. But i am everything but keen to try this route. since we would need to replace the toolshelf then too with our solution. And maintain such a system will be a nightmare for sure.

**Comment by iyadahmed** [comment]
I took a look at it, but it seems there are part of other commits, I couldn't make up much from them.

I believe we don't have to do native OpenGL, we just need to remove the current tool system entirely from UI code and keymaps, then register regular panels in the "TOOLS" region (left area), just like regular panels in the "UI" region (right area), it would take time but it would be our own system, the hope is it would be easier to maintain because it is our own system, and it is just regular panels.

**Comment by Draise14** [comment]
What we do have: 
- Panels can show in the toolshelf
- The toolshelf is mode based UX operators (activate, stay activated till turned off)
- The tools we want there is act once UX operators (activate, turns off after appyling - reverts to former)
- There is not enough room for everything to the left with this system because we don't have tabs. 

**Alternative Ideas:**
What if we work on panels... but at the other side? But also the ability to have them contextual a bit like the Right Click menu? In vertex mode: vertex operators, when in edge mode: edge operators, so we don't need so many operators in so many tabs. And only show panels from the header menus? 

Additionally:
Create and stick to 3 tabs for the current Property Shelf dedicated to iconized tools, like the Node Shelves system. 
- Consistent with Node Editor tools for adding: Add, Modify, Relations
- Uses old tabs and panels, just.. to the right, nothing new in code (much). 
- Easier access than the header menu's. Point and click, and panels can be pinned and customized order. 
- Clear to document by showing that mode operators are to the left, act once operators to the right
![image](https://user-images.githubusercontent.com/35357409/114243064-93712a80-9951-11eb-9be9-f5c58e81c3a7.png)
Here is an example where Textools adds UV tools to the right as act once operators, not modal ones. It's clear, iconized, and with a layout that helps UX instead of only relying on scanning lists or diving deeper into bigger lists. I used this heavily and it's pleasant and intuitive. 
![image](https://user-images.githubusercontent.com/35357409/114243266-e4811e80-9951-11eb-9ebc-8f542099ec9a.png)

**Tab space dilema:**
Use a single icon symbol for the tools tabs, a UNIX symbol to work similar to an icon, and only take up one character for many tabs. 
▶ = Add
◩ = Modify
⬤ = Selection/Relationships

For consistency, equivalent header menu character could be added if we keep it optionally a double entry.

**Comment by iyadahmed** [comment]
> What we do have: 
> 
> - Panels can show in the toolshelf
> 
> - The toolshelf is mode based UX operators (activate, stay activated till turned off)
> 
> - The tools we want there is act once UX operators (activate, turns off after appyling - reverts to former)
> 
> - There is not enough room for everything to the left with this system because we don't have tabs. 
> 
> 
> 
> **Alternative Ideas:**
> 
> What if we work on panels... but at the other side? But also the ability to have them contextual a bit like the Right Click menu? In vertex mode: vertex operators, when in edge mode: edge operators, so we don't need so many operators in so many tabs. And only show panels from the header menus? 
> 
> 
> 
> Additionally:
> 
> Create and stick to 3 tabs for the current Property Shelf dedicated to iconized tools, like the Node Shelves system. 
> 
> - Consistent with Node Editor tools for adding: Add, Modify, Relations
> 
> - Uses old tabs and panels, just.. to the right, nothing new in code (much). 
> 
> - Easier access than the header menu's. Point and click, and panels can be pinned and customized order. 
> 
> - Clear to document by showing that mode operators are to the left, act once operators to the right
> 
> ![image](https://user-images.githubusercontent.com/35357409/114243064-93712a80-9951-11eb-9be9-f5c58e81c3a7.png)
> 
> Here is an example where Textools adds UV tools to the right as act once operators, not modal ones. It's clear, iconized, and with a layout that helps UX instead of only relying on scanning lists or diving deeper into bigger lists. I used this heavily and it's pleasant and intuitive. 
> 
> ![image](https://user-images.githubusercontent.com/35357409/114243266-e4811e80-9951-11eb-9ebc-8f542099ec9a.png)
> 
> 
> 
> **Tab space dilema:**
> 
> Use a single icon symbol for the tools tabs, a compatible symbol to work similar to an icon, and only take up one character for many tabs. 
> 
> ▶ = Add
> 
> ◩ = Modify (idea, not compatible)
> 
> ⬤ = Selection/Relationships (idea, not compatible)
> 
> Test:
> 
> ![image](https://user-images.githubusercontent.com/35357409/114244031-55750600-9953-11eb-97ad-ce134c8cec25.png)
> 
> 
> 
> For consistency, equivalent header menu character could be added if we keep it optionally a double entry. 
> 
> 
> 
> **Benefit:**
> 
> If we stick to both sides for tools with a hierarchy of tabs using the current arquetecture, we can then justify a full screen workflow a bit better - mode left, act once right, and other addons and tools and properties, show what you want, pin what you want, customize how you need, point and click. 
> 
> ![image](https://user-images.githubusercontent.com/35357409/114244366-ef3cb300-9953-11eb-858e-394e595f9fe1.png)
> 
> 

This is a really creative idea to solve the issue, but tools on left would be redundant I think

**Comment by Draise14** [comment]
There is no redundency unless there are repeat tools. But we have removed repeated tools to "Legacy" panels. The UX of the left is modal, and the UX of the right is act-once. So.. the redundency wouldn't be there concerning what is a toolshelf modal tool, and what is a property shelf tool tab act-once tools. 

Right now, replacing the entire modal toolshelf would mean replacing or fusioning the entire UX of how you use act-once and modal operators. And right now the majority of the tools are not modal... and working that would be a huge task.

**Comment by iyadahmed** [comment]
made some progress on it, we still have to figure out how to make the toolshelf work with tabs

![image](https://user-images.githubusercontent.com/25552173/117203805-c3480c80-adef-11eb-877f-41bef8d2dfd5.png)

**Comment by ReinerBforartists** [comment]
This is cool!

**Comment by iyadahmed** [comment]
> This is cool!

Yep finally found the root of problems ![image](https://user-images.githubusercontent.com/25552173/117283397-093fb780-ae66-11eb-8cbb-d781b1ee9742.jpeg)

**Comment by ReinerBforartists** [comment]
Heh, excellent catch. I had a task before a while with a similar masking problem. Can't find it anymore at the moment though. And i was just to investigate in this direction here too. But there was always other things in the way ^^

So good find. I guess our tracker will explode with new tasks soon :)

**Comment by iyadahmed** [comment]
> Heh, excellent catch. I had a task before a while with a similar masking problem. Can't find it anymore at the moment though. And i was just to investigate in this direction here too. But there was always other things in the way ^^
> 
> 
> 
> So good find. I guess our tracker will explode with new tasks soon :)

Great yeah it was very interesting to find.

Yep indeed :)

**Comment by ReinerBforartists** [comment]
Just that it is not forgotten, we have a branch where i once toyed around with the toolshelf problem. It contains for example an experimental panel that resizes with the width of the toolshelf area like the original toolshelf icons.

Is in this file here: https://github.com/Bforartists/Bforartists/blob/toolshelf/release/scripts/startup/bl_ui/space_toolsystem_toolbar.py

I am currently busy with some real life needs and music, so things goes a bit slow here at the moment. I will make a thread then when i am back into business. Then we can start to plan how the new old toolshelf tabs are most useful for us.

One of my ideas is to have the content either in the tool shelf, or in the text menus. Maybe we can add a switch in the View menu. Or in the viewport settings.

But first make your commit when you are ready for it. To have the tabs support back is already a big milestone :)

**Comment by iyadahmed** [comment]
More progress, the toolshelf works nicely in a tab, I had to fight a little with snapping, create new startup.blend s, because default snap width cut the toolshelf buttons, (the tabs area took some space)
![image](https://user-images.githubusercontent.com/25552173/117361842-d378ee00-aeba-11eb-8e30-eb115dbb7626.png)

**Comment by iyadahmed** [comment]
I also added the panel
![image](https://user-images.githubusercontent.com/25552173/117362852-138ca080-aebc-11eb-9564-eaf9707a0f84.png)


> Just that it is not forgotten, we have a branch where i once toyed around with the toolshelf problem. It contains for example an experimental panel that resizes with the width of the toolshelf area like the original toolshelf icons.
> 
> Is in this file here: https://github.com/Bforartists/Bforartists/blob/toolshelf/release/scripts/startup/bl_ui/space_toolsystem_toolbar.py
> 
> I am currently busy with some real life needs and music, so things goes a bit slow here at the moment. I will make a thread then when i am back into business. Then we can start to plan how the new old toolshelf tabs are most useful for us.
> 
> One of my ideas is to have the content either in the tool shelf, or in the text menus. Maybe we can add a switch in the View menu. Or in the viewport settings.
> 
> But first make your commit when you are ready for it. To have the tabs support back is already a big milestone :)

**Comment by iyadahmed** [comment]
https://user-images.githubusercontent.com/25552173/117364845-b3e3c480-aebe-11eb-8dc5-df30f7328277.mp4

**Comment by iyadahmed** [comment]
Tab pining and reordering
Also now tools panel is collapsable
![image](https://user-images.githubusercontent.com/25552173/117384109-84df4a00-aee2-11eb-87ee-8b5569f6980a.png)

**Comment by ReinerBforartists** [comment]
Cool progress :)

You don't need to solve everything at once. We have to do some design decisions anyways. For example if we really want to have the original buttons in a collapsible panel with grey background.

**Comment by iyadahmed** [comment]
> Cool progress :)
> 
> 
> 
> You don't need to solve everything at once. We have to do some design decisions anyways. For example if we really want to have the original buttons in a collapsible panel with grey background.

Agree :)

**Comment by ReinerBforartists** [comment]
As told, all questions that can be solved at the way. I'm a big fan of evolutionary prototyping :)

Bforartists1 is a good keyword. Most of the panels can be grabbed from there. All iconized already. We just need to replace the switch code part between icon and text. But this is also a bridge that can be crossed at a later point.

Waiting for the pull request ^^

**Comment by ReinerBforartists** [comment]
> Tabs: Yes (max 7)
This one makes me wonder though. Where does this limit come from?

**Comment by Draise14** [comment]
> 
> 
> > Tabs: Yes (max 7)
> 
> This one makes me wonder though. Where does this limit come from?

Webdesign UI and UX guidelines. A menu shouldn't contain more than 7 items as the brain has "limited recall" to about 7 digits, or items. More from there then the brain has to think and read a larger list, or split to categories and chunks of lists, making the extra energy to choose between more options slow and limited, worsening the UX. Also the way the tabs collapse has no min height, so more tabs would collapse incorrectly on smaller editor heights.

**Comment by ReinerBforartists** [comment]
That's already the case in the sidebar with all the addons :D

I just wondered if this is a hardcoded limit. Addons developers might love us for the opportunity to have tabs in the toolshelf again. So a hardcoded limit would not be good here. I agree though that we should target to have not more than 7 default tabs. We already had just a handful tabs in Bforartists 1 from what i remember :)

**Comment by ReinerBforartists** [comment]
While at defining goals, we should move our tab classes into our own python file ...

**Comment by iyadahmed** [comment]
> As told, all questions that can be solved at the way. I'm a big fan of evolutionary prototyping :)
> 
> 
> 
> Bforartists1 is a good keyword. Most of the panels can be grabbed from there. All iconized already. We just need to replace the switch code part between icon and text. But this is also a bridge that can be crossed at a later point.
> 
> 
> 
> Waiting for the pull request ^^

So the pull request should only enable tabs, and not add headers or snap panel, or is it fine if it included?

**Comment by iyadahmed** [comment]
> It is fine to have it included. We can have a look at a later point to polish it then.
> 
> 
> 
> As told, i am a big fan of evolutionary prototyping. Throw in a few things, take a look how it turns out, fix the problems, throw in the next things ...

Great!, that's a relief
