### ISSUE TITLE
Graph Editor - Missing Keyframe Handle Type dropdown 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1405]
# Issue
![bforartists_2020-03-10_13-24-10](https://user-images.githubusercontent.com/35357409/76346166-8ad39e00-62d2-11ea-99ac-92c1f7944f23.png)
![bforartists_2020-03-10_13-24-22](https://user-images.githubusercontent.com/35357409/76346170-8c04cb00-62d2-11ea-88e0-a36beffcfc22.png)

Right now the **Keyframe Handle Type** drop down in the header and header toolbar area (right) is missing in the graph editor. This only exists in the Dopesheet, though there is a menu here in the graph editor (in Blender) with Blender hotkey (V). 

Missing operator types should be a no-go, these should be added to the UI of the graph editor. 

Operator in question:
`bpy.ops.graph.handle_type`

# Solution
Add this drop down, like in the dopesheet, to the graph editor.

**Comment by ReinerBforartists** [comment]
Is it missing in Blender too?

**Comment by Draise14** [comment]
Blender has it on hotkey V and in the header menu. Bforartists2 - Alpha 0.9.0 has neither hotkey nor entry header in the graph editor. 

![blender_2020-03-10_15-05-07](https://user-images.githubusercontent.com/35357409/76354537-a47be200-62e0-11ea-87ea-065a6f125191.png)

Bforartists typically in the Dopesheet made it an exposed dropdown, but in Blender it's in the header submenu and on a hotkey floating menu.

**Comment by ReinerBforartists** [comment]
Thanks. Will have a look.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/76392512-fcaef480-6371-11ea-87dd-0c3474d00561.jpg)
