### ISSUE TITLE
Graph Editor - Decimate entries have no icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1406]
# Issue 
![bforartists_2020-03-10_15-20-35](https://user-images.githubusercontent.com/35357409/76355716-caa28180-62e2-11ea-8bff-77a4293459f3.png)
There are two missing icons in the **Graph Editor>Key** section. 

Operators:
- Decimate (Allowed Change) 
- Decimate (Ratio)

# Task
Add the icons if they already exist, if not, create them.

**Comment by ReinerBforartists** [comment]
Fixed in master
