### ISSUE TITLE
3D View - Possible regression: missing Collection entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1407]
# Issue
![bforartists_2020-03-10_19-40-20](https://user-images.githubusercontent.com/35357409/76371070-0a7b6000-6307-11ea-8126-df6399f39b69.png)

This might be a workflow regression, but from within the 3D view, you can move objects to and from and create collections (usually by header entry or hotkey in Blender) so you don't have to navigate to the Outliner to do this. BUT, the hotkeys you assign to the outliner don't work in the 3D view. You have to right click on a hotkey in the header to make it work in the 3D view - but we removed these collection entries from the 3D view header. 

Ehm... maybe it's now a regression? If I want to add this functionality of hotkey collection management to collection work in the 3D view, I'd have to actually know the 3D view collection operators by memory and add it to the keymap instead of rightclick then add hotkey. 

# Solution/Question
Can we revert and add back the Collections menu to the 3D view - even if it's a double entry?

## Reason
I have found that some functionality work in both editors, but the hotkeys don't - so when you assign to one editor, it won't work in the other - and unless you're a big nerd, you'd know how to change the operator name per editor and make that hotkey entry in the hideous hotkey editor, buuuuut most people aren't that able - which means it's beurocratic to move mouse to an editor to use it when you could in another. So... if the hotkey can be assigned to both editors through the UI, it would make life easier, and maybe this entry should be in both editors (similar to delete, select, view, etc) - _even when we already removed it previously_....

**Comment by ReinerBforartists** [comment]
It was your wish to move it ^^

**Comment by Draise14** [comment]
Well yeah, it was a debate..... I hadn't thought this workflow through thoroughly (as ignorance thought that they would be the same operator in all editors, which is really just bad software UX from Blenders behalf), but now working with others on the team and in training, it showed it wasn't useful. _I'm teaching my interns Bforartists, and it's pretty good to QA things... sorry, just brings things out..._ 

Ideally it should only exist once, when you add a hotkey to it, the hotkey for the operator would exist for all editors that have that operator....

**Comment by ReinerBforartists** [comment]
Keep it coming :)

Well, the design goal is to remove the redundancies, not to add even more. And to have everything at one place. And the best place to manage collections is the outliner. So i don't see a solution here really.

The keymap editor is fubar. That a hotkey from the menu gets added in the right section is wishful thinking nowadays anyways. So you should get away with adding the hotkeys in the 3d view editor global section too. By hand. This would be the best solution. I just wonder how often you work with this feature that you want to create a hotkey for it.

**Comment by Draise14** [comment]
Yeah, it's really better to have less redundency, and yes.. editing hotkeys is ridiculous. I still don't understand why Blender users pride in their hotkeys when the editor is one of the worst out there, and it's really bad for editing globally with no conflict management.

In generally, adding object to active collection to group objects in a tidy way from the 3D View was the workflow optimization, but direct creating and deleting collections from the 3D view is not necessary. 

Let's just close this.
