### ISSUE TITLE
Merge regression in Dopesheet Editor

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1413]
We have a merge regession in the dopesheet editor. It's actually two, but i expect it to be connected. The one is the header content. The other a error message when switching to other animation editors.

![invalidcall](https://user-images.githubusercontent.com/13919702/76700563-08bfec80-66b9-11ea-84f5-98c1913f7d4d.jpg)

![regression](https://user-images.githubusercontent.com/13919702/76700565-0e1d3700-66b9-11ea-827e-138bb55b2c66.jpg)

**Comment by ReinerBforartists** [comment]
See also in 2d animation layout. There are a few obscure buttons now, and another one is missing.

**Comment by ReinerBforartists** [comment]
Okay, the error message is another bug. It happens when you click at the button from the current editor. Splitting ...

**Comment by ReinerBforartists** [comment]
Splitted here: Animation editors - invalid operator call 'WM_OT_switch_editor_in_XXX' #1424

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by Draise14** [comment]
Ah, so these are not in 0.9.1? Damn.. I use these way too often.

**Comment by ReinerBforartists** [comment]
Will be in the next devbuild at sunday :)
