### ISSUE TITLE
3D View - Left click tweak select/deselect on click

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1426]
# Issue
In the new Bforartists 2 Beta - 0.9.1, the issue from #1384 still persists, where you can't drag anywhere in a transform as it will select or deselect anything and not transform! 

# Solution
I found that we have a inconsistency with the selection modes. In the 3D View (Global) we have Click to select anything. Which works well as you actually have to click (not just press) to select thigns. In the Tweak tool (which also affects all the other transform tools) it is on **press**. So now when I transform, I press, and it then selects/deselects (regardless that toggle is on/off). So.. it's annoying. I just want to move things! Not select them. 

So...

I changed the **3D View Tool: Tweak** to Click and this fixed the issue. It's predictable now. 

![bforartists_2020-03-19_10-28-12](https://user-images.githubusercontent.com/35357409/77084277-c0604180-69cc-11ea-9297-6906c03a9f3f.png)

## Task
Change this Tweak Select entry to click instead of Press. 

_I have my maps heavily modified right now, so not sure how to commit this one without a hard reset.._

**Comment by ReinerBforartists** [comment]
As told in this thread, it's another issue. 

In what mode are you?

**Comment by ReinerBforartists** [comment]
Ah, now i see what you mean. Fixing ...

**Comment by ReinerBforartists** [comment]
Hm, here it is already with click. Can it be that you toy around with your custom keymap again?

**Comment by Draise14** [comment]
I doubt it. It was on default (no revert keymap) and on Bforartists default. When I switched to my map exported/imported, I didn't have the issue. Maybe it was fixed with something after the 0.9.1 release? Or would it be a factory setting carried over from 0.9.0? 

I guess when you install a new version, the BFA keymap default is not overwritten in the user data?

**Comment by ReinerBforartists** [comment]
I have double checked the code, even in the keymap code. It is already at Click. 

https://github.com/Bforartists/Bforartists/blob/master/release/scripts/presets/keyconfig/bforartists.py#L1149

When you have modified your keymap then the changes automatically gets saved in the appdata folder. And these modifications will of course also show up with a next version as long as it uses the same target folder. Bfa 0.9.1 shares the same foder with Bfa 0.9.0. Maybe that's your footangle here? I always delete the bforartists folder in my appdata directory immediately after a commit.

**Comment by ReinerBforartists** [comment]
github link does not jump to Line 1149 where this code resides -.-

**Comment by Draise14** [comment]
Ah ok. Yeah, most likely. I can't usually delete my appdata often due to work and the configuration I need to work with (as I'm currently using this version in production), I'm only able to do it on a work lull to dev, so yeah.. sloppy troubleshooting. I guess I'll close this.

**Comment by ReinerBforartists** [comment]
Just rename the bforartists folder for a moment. Then you can check if the problem persists :)
