### ISSUE TITLE
3D View - Workbench - Show Xray toggle hide Cavity settings

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1430]
# Issue
![bforartists_2020-03-25_12-06-40](https://user-images.githubusercontent.com/35357409/77564762-39f6a480-6e91-11ea-82bb-e6210aa9d69d.png)

When you toggle Xray, the Cavity settings hide, they should be exposed always regardless of Xray state. 

# Task
Check and remove the hide Cavity settings conditional when you toggle Xray.

**Comment by ReinerBforartists** [comment]
This is by design as far as i remember. You can have xray or cavity, not both. But i will check tomorrow.

**Comment by Draise14** [comment]
But.. you can have both at the same time. Xray at 100% shows cavity, it's just not easily seen when things go transparent, but it's there, and toggleble. So.. to toggle cavity when in Xray, I have to turn off Xray, then tune, then turn Xray back on again.. it's not right. Cavity should be independent. 

![enter image description here](https://i.imgur.com/faoTj18.gif)

**Comment by ReinerBforartists** [comment]
As told, this is by blender design. When you activate X Ray, then the other options are greying out. That's why i have hidden it.

![bydesign](https://user-images.githubusercontent.com/13919702/77617346-31a37580-6f34-11ea-82b2-e2c756ecf444.jpg)

**Comment by Draise14** [comment]
It's a pretty bad design choice... if keeping it so, maybe grouping the Xray toggle with those settings visually might make it feel more logical and less broken. Right now it's pretty random that those settings disappear with the xray, though in the viewport they don't.

**Comment by ReinerBforartists** [comment]
Well, it's logical. When X Ray is on, then everything is transparent. Shadows and cavity are very hard to see then, if even. Those sesttings makes no sense with X Ray. And i can't group them all together since these are no X Ray settings. Quite the opposite. It is either X Ray or the other settings.

I'm really lost what i could improve here.

**Comment by Draise14** [comment]
It's only logical with Xray when everything is transparent, until it's not. I don't use Xray with transparent, I can't see anything when everything is transparent, it's not a good viewport setting in general... 

I keep it solid and use it to select behind and see edited wireframes behind meshes - not look through meshes to see another transparent mesh, so the toggles are relevant but hidden. 

It should be decoupled logically, as even by correlation, what does cavity and shadow have to do with Xray transparency!? They are separateviewport settings. 

The other things that could be done is that they only these hidden toggles when Xray is set to 1.000, or solid - and the toggles become relevant again.

**Comment by ReinerBforartists** [comment]
Hmmhmm. I understand your concerns. I am just not sure if a change would really improve things. Give me a few days to think about this problem :)

**Comment by ReinerBforartists** [comment]
Okay, i will have a look to show these props permanently.
Shadow shows when X Ray is at strength 1. So no need to grey it out at all.
And the other two props also works with X Ray on. No idea why Blender geys them out then.

**Comment by ReinerBforartists** [comment]
I'm a moron. They are greyed out because they are off XD

**Comment by ReinerBforartists** [comment]
Code says nope, they hide it. Fixing ...

**Comment by ReinerBforartists** [comment]
Reverted to the Blender state of things. And cavity and depth of field stays visible now. Haven't managed to hide the sliders though. This code makes me headache. So i leave it the way it is. The functionality is given. Maybe at a later point.

**Comment by Draise14** [comment]
Thanks for this update. You are once again my hero. It's all these small things that makes me really love this fork.

**Comment by ReinerBforartists** [comment]
Well, in this case it was me who broke it. Sorry ^^

**Comment by Draise14** [comment]
Strangely enough, Blender also hides when I tried it (to make sure it wasn't just BFA), so you made a default Blender thing better.. ;)
