### ISSUE TITLE
Lock camera to view, make it a top UI tool.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1434]
To turn off Lock camera to view can be useful to adjust the passepartout. To adjust or add some geometry that is outside the camera view for example. And it is imho often enough needed to deserve a top hierarchy entry.

Two possible locations. The navigation widget. Which i would dislike, since it is a setting. Or the header area. My favourite.

Not sure if this setting will make it in the final of Bforartists 2. We have feature freeze. But afterwards we can.

Now for the pitfalls. We would split the button away from the camera lock settings. Or we leave it there too, and have a double entry.

So, does it make sense at all?

![locktoview](https://user-images.githubusercontent.com/13919702/78340842-086b9080-7597-11ea-9305-f59513ed50f6.jpg)

**Comment by Draise14** [comment]
yes yes yes yes and yes please. I toggle this so often, having it in a menu, then collapsable menu all the time at the bottom of a list of camera toggle I barely touch needs it.. to be exposed. The hotkey for this also is on the other side of the keyboard, I'd prefer it as a visibly exposed toggle. 

I think it doesn't have to be a double entry. Keep the locks in their group.. and this would really be a "Freeze Camera" type of logical lock - completely separate concerning "logic". 

I personally would prefer it by the camera controls.. though it technically is a setting, I feel it is more a camera/viewport toggle/control.

**Comment by Draise14** [comment]
Also, my interns and those who've I trained have missed this functionality and get confused by it, not connecting dots between camera/view settings and the viewport controls which generally are hidden on first use (you start in the tool tab).

**Comment by ReinerBforartists** [comment]
Okay. Will have a look at it once BFA2 is out of the door :)

**Comment by ReinerBforartists** [comment]
Ah. What the heck. Let's have a look at this one here.

**Comment by ReinerBforartists** [comment]
Fixed in master.

Button in the header is just visible in the camera view. Checkbox in panel still exists.

![cam1](https://user-images.githubusercontent.com/13919702/78421067-4333fe00-7655-11ea-82da-fb8f75df88d0.jpg)

![cam2](https://user-images.githubusercontent.com/13919702/78421073-46c78500-7655-11ea-801b-1c573ba6fcdd.jpg)
