### ISSUE TITLE
UV Editor, clicking into the off deselects immediately

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1439]
We had this problem with other editors before. Activating a transform tool and not clicking at the widget deselects everything. Unwanted behaviour. 

Related: https://github.com/Bforartists/Bforartists/issues/1423

**Comment by Draise14** [comment]
Ah, this is the press vs. click tweak select in UV Editor issue. Fixed this for myself, thought it was my old keymap.

**Comment by ReinerBforartists** [comment]
You are always welcome to fix the bugs in the source code instead of doing your own customizations :)

**Comment by Draise14** [comment]
To do hotkey changes... just to clarify: 

1. Remove the app data
2. load defaults
3. Do change to keymap
4. export new input .py file
5. replace the input .py file in the repository
6. build and test with the new default
7. commit to relevant thread

This would be cleanest way to do commits for the hotkey map? 

_I remember once I did a hotkey fix and screwed up the whole system making a weeks worth of reversions... I don't wanna repeat that. woops..._

**Comment by ReinerBforartists** [comment]
Yes, that's the way to go. But, yeah, true, keep the keymap better in one hands. I'll do it ^^

But you can report such problems :)

**Comment by ReinerBforartists** [comment]
Draise, how have you fixed this one? When i remove deselect then i select other vertices instead.

**Comment by ReinerBforartists** [comment]
Ah, nevermind. Have it. Had the wrong tool selected ^^

**Comment by ReinerBforartists** [comment]
Something is still super odd here. It deselects all, then selects the closest element now. And this new drag feature makes me nuts. Everytime i start in tweak mode. I don't want to tweak, i want to click in the off and navigate.

**Comment by ReinerBforartists** [comment]
Hmm, Blender now behaves like Bforartists when it comes to clicking into the off. Seems that we might want to revert our changes.

Another can of worms -.-

Unassigning, first fixing the other can of worms.

**Comment by ReinerBforartists** [comment]
Nevertheless, here the deselect fix.

**Comment by ReinerBforartists** [comment]
Ah, forgot the click part ...

**Comment by ReinerBforartists** [comment]
Okay. Click does not work. We have to choose Release here to get tweak to work. Then we have the same behaviour than in 3d view. Dragging will keep the selection. And clicking will deselect everything.

**Comment by ReinerBforartists** [comment]
Calling this one fixed in master

**Comment by ReinerBforartists** [comment]
Bug is back -.-

**Comment by ReinerBforartists** [comment]
Dunno what i did here. But it should work now.
