### ISSUE TITLE
Video Sequencer - Change Active and Selected colors in theme

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1449]
# Issue
Right now the selected and active clip are both black... 

![bforartists_2020-04-09_09-56-12](https://user-images.githubusercontent.com/35357409/78909083-9a1c4780-7a48-11ea-9ba3-3f4e4eac75d4.png)

# Task/Solution
It would be great to make them a little more evident or consistent with the 3D Viewport by default. 

### Version
Latest devbuild `devbuild-05-04-2020`

**Comment by ReinerBforartists** [comment]
Already fixed here, comes with the next devbuild

https://github.com/Bforartists/Bforartists/issues/1442


![fixed](https://user-images.githubusercontent.com/13919702/78913837-e5a31580-7a89-11ea-9caa-037abc938c2a.jpg)
