### ISSUE TITLE
Properties Editor - View Layer - Left alight check boxes in Eevee mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1463]
# Issue
![image](https://user-images.githubusercontent.com/35357409/79573020-90679500-8083-11ea-8796-be1cc2d836e0.png)
Looks like all these check boxes are right aligned. We want consistency with Left aligned, which is (I agree) a lot easier to read. 

The eevee render engine view layer AOV's have not been updated yet. 

This might be a regression from a merge. 

**Version**
Bforartists 2 - 1.0.0 RC

# Task
Left align them

**Comment by ReinerBforartists** [comment]
Ah, indeed. Sysiphos strikes back. Thanks for the report :)

So yet another last minute fix ^^

**Comment by ReinerBforartists** [comment]
Fixed in master

The prop with the decorator remains right aligned. I really wish i would be able to catch this one too ...

![fixed](https://user-images.githubusercontent.com/13919702/79589475-bf0e5b80-80d5-11ea-87d4-71d3f4f23ba4.jpg)
