### ISSUE TITLE
File Browser - Filter icon missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1464]
# Issue
![bforartists_2020-04-17_20-13-44](https://user-images.githubusercontent.com/35357409/79624565-030a5c00-80e8-11ea-886f-d2bd6da511ca.png)

![image](https://user-images.githubusercontent.com/35357409/79624571-0b629700-80e8-11ea-9242-a1eaa15a68be.png)

The icon for the new Volume object type of 2.83 is missing. **Line 151**

To reproduce the missing icon warning: Activate the filters in the file browser. 

![bforartists_2020-04-17_20-16-45](https://user-images.githubusercontent.com/35357409/79624611-60061200-80e8-11ea-8e4a-d29c1174125a.png)

# Task
We need to make a new one for .

**Comment by ReinerBforartists** [comment]
Ah these unfunny merge regressions ... Thanks buddie. Will fix it :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![missingicon](https://user-images.githubusercontent.com/13919702/79630223-dd18a200-814f-11ea-9b13-d010923f2103.jpg)
