### ISSUE TITLE
Mouse Interactions in interface not responsive on first open

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1465]
# Issue
A first time user has reported an unusual bug in FB. He has a high spec machine, but when he installs, and runs on factory settings... the UI loads, but mouse interactions are frozen or not working and BFA is only responsive to keyboard input. Mouse clicks do nothing. Here is a video of the issue:

[Video of Issue on Youtube](https://youtu.be/VrrCV-6zoZA)

Here is his message:
> "Any reason why this would not work on a win 10 64bit machine with 64 gb ram and a 2080 ti with a ryzen 7 3800x? I can't add a mesh, open any menus, mouse does not work at all."

Note: the wheel does work. The mouse is a Logitech m185. 

He has authorized the ability to contact privately for more info here:  davidpolensky(at)gmail dot com

## Troubleshooting
1. I've removed the appdata with him
2. We've installed to another harddrive
3. We've installed to defaults
4. Ran with Admin rights
5. Turned off "Quick Edit" in the Windows Command Prompt according to this issue [here](https://developer.blender.org/T75431)
6. Zip packed installation also has the issue.
7. We launched it from the Windows Powershell to find console errors, there are none. 
8. Blender doesn't have this issue

The only other thing I didn't think about is... is... a python installation missing? 

It's a strange bug..

**Comment by ReinerBforartists** [comment]
Thanks for the report. 

Wow, that's bad. I have not the slightest idea what is going on here. Give me a few moments, i will test the installation at my win 7 laptop again.

**Comment by ReinerBforartists** [comment]
Could you please ask him if there is something to see in the console? hotkey f2. And if the same happens with the zip version too?

**Comment by Draise14** [comment]
Have passed the message on, he's trying it out.

**Comment by ReinerBforartists** [comment]
Works just fine at my win 7. I am clueless.

**Comment by Draise14** [comment]
He got no errors in both. I've asked him to try the dev build. 

![](https://scontent.xx.fbcdn.net/v/t1.15752-0/p480x480/94259700_656679455164395_877535567456239616_n.jpg?_nc_cat=110&_nc_sid=b96e70&_nc_oc=AQkUWOUd3NFddmIRpDrB338520Iq7imaOUzaHyk5Gdylr-aPqfkhOYCKeXdrTw3Kk8U&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&_nc_tp=6&oh=8e66cf57a6418d0286275651b784ed57&oe=5EC43056)

EDIT: The dev build doesn't have the problem. 
`devbuild-20-04-2020`

**Comment by Draise14** [comment]
So... dev build works, official doesn't. Bizzare!

**Comment by ReinerBforartists** [comment]
I am glad that there is at least a solution.

The dev build is a zip file. That's why i asked if the zip has also the problem.  It could be a rights problem when installing. But it works just fine at my win 7 machine. And i can just fix what i can reproduce, unfortunately.

**Comment by ReinerBforartists** [comment]
To answer the question of a quick update, yes, the bug should disappear. But there is Blender 2.83 around the corner, which i expect to arrive in two or three weeks anyways. And then we do a update here too. So a quick update wouldn't make sense at the moment. But just lead to confusion at the user end and lots of work at our end.

**Comment by Draise14** [comment]
Makes sense.

**Comment by ReinerBforartists** [comment]
Let's keep the issue open until Blender 2.83 arrives. In case we get more reports then we can talk about a point update at any point.

**Comment by ReinerBforartists** [comment]
Long resolved issue. Closing.
