### ISSUE TITLE
Display options in toolbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#147]
I remember that this one turned out to be pretty complicated. The tools in the toolbar are also global. And not local like the settings in the editor window. And so i abandoned further development. But it would be nice when we could have some often used viewport settings in the toolbar. Here then of course globally, for all open editor windows of the same type.

I also thought of putting this into the header. But the header is already ways too crowded. And we would introduce a double menu entry. So the better place is the toolbar.

Highly needed is things like hiding the 3d cursor, or hiding the whole groundgrid. Which i both often use.

![viewsettingsintoolbar](https://user-images.githubusercontent.com/13919702/38452810-ba2ea70a-3a4b-11e8-82e8-47eefab524e0.jpg)

**Comment by Draise14** [comment]
I toggle "Only Display" often too, mostly in animation.

**Comment by ReinerBforartists** [comment]
Yes, that's why a toolbar with this toggles would be a gift ...

**Comment by ReinerBforartists** [comment]
Doesn't work. This options are view dependant. And the header is already ways too crowded.

Closing.
