### ISSUE TITLE
Freeze with Ctrl N to create a new scene

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1474]
When you press Ctrl N then you can create a new scene. When you repeat Ctrl N, or when you do this after opening Bforartists, then BFA becomes unresponsible.

No error messages, no hint what is going on. Unfunny bug.

**Comment by Draise14** [comment]
Confirmed, can reproduce... but can't find clues.

**Comment by ReinerBforartists** [comment]
Yes, this is possibly related to: Crashbug with new from template #1431

Blender doesn't call read_homefile with the hotkey. They call the quiz menu instead where you can choose what kind of template you want to create. 

There is nothing that i could follow down here. No hint where the problem could reside really. I fear i have to start over for these kind of issues, and put all our things into Blender again, up to the point where we catch this baddies here. Will take a few weeks or even months. But first some other things first ...

**Comment by Draise14** [comment]
It's an odd one. The same python operator does work in the console in Blender, but not in BFA.

**Comment by ReinerBforartists** [comment]
Related issue remains the crashbug here: Crashbug with new from template #1431

When Load UI is on then the freeze does not appear. Let's have a look if i can repeat the freeze with Load UI off in Blender.

**Comment by ReinerBforartists** [comment]
Fixed with the lastet merge
