### ISSUE TITLE
VIEW3D Toolbar does not work

### ISSUE THREAD

**Issue by kurasdan** [Bforartists/Bforartists#1475]
In Blender 2.82, pressing the "N" key will reveal the VIEW3D bar containing tabs to installed addons. This does not happen in Bforartists2. I've uninstalled Bforartists2, downloaded and installed a new copy.  Problem still exists.

OS: Windows 10 Professional, 24GB RAM, GTX1080 graphics card.

**Comment by Draise14** [comment]
This is because the hotkey has changed in the keymap to CTRL+T. So it's all in the left hand without needing to cross the keyboard to the N key. That key could be remapped to N, but that key is now to clear seam when UVing in Edit mode.

**Comment by ReinerBforartists** [comment]
Indeed. N is clear seam in our keymap.

Thanks for the report. Closing now.

**Comment by kurasdan** [comment]
Thank you.
