### ISSUE TITLE
Property Editor - Mesh tab - Vertex and Shapekeys Dropdown menus - Missing icons, wrong icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1476]
# Issue
![bforartists_2020-04-24_22-31-22](https://user-images.githubusercontent.com/35357409/80272158-8568c200-868c-11ea-800e-72cb166fc157.png)

Missing icon here. 

Version: Bforartists 2 - 2.0.0

**Comment by ReinerBforartists** [comment]
Hm, this menu seems to contain wrong icons too. Delete should be red cross. We have an extra icon for remove from all groups. And we have a Clear icon ...

**Comment by ReinerBforartists** [comment]
Found more rascals here in a neighbour menu. Doing this in one task.

![shapekeysmenu](https://user-images.githubusercontent.com/13919702/80273680-bec52000-86d4-11ea-85bd-3de3a6dbf0bc.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/80273856-3e072380-86d6-11ea-8f79-a5ac96422d0f.jpg)

**Comment by ReinerBforartists** [comment]
Ah, wait, there are two mirror icons too ...

**Comment by ReinerBforartists** [comment]
And fixed

![mirror](https://user-images.githubusercontent.com/13919702/80273923-d30a1c80-86d6-11ea-9473-2dace6c760b2.jpg)
