### ISSUE TITLE
3D View - Sculpt Mode - Remesh shortcut bug and inconsistencies

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1480]
# Issue
![bforartists_2020-04-25_20-39-15](https://user-images.githubusercontent.com/35357409/80295109-843f9f80-8735-11ea-8b80-4981b4a36fd7.png)
This blender hotkey is missing, and is causing issue. 

In Bforartists, this hotkey can't be assigned as there is a console issue. 

![bforartists_2020-04-25_20-43-07](https://user-images.githubusercontent.com/35357409/80295116-93bee880-8735-11ea-8bb0-511d961d1f7f.png)

The Quadriflow remish option is also missing from the panel. 

# Task
- Fix the bug by setting the hotkey by default? 
- Make the quadriflow option also exposed in the panel and rename button to make it consistent.

**Comment by ReinerBforartists** [comment]
Hmm. I see this as one of the tools that does not require a hotkey. You don't click at it every second.

**Comment by ReinerBforartists** [comment]
Thought again. And the goal of Bforartists is to provide an easy to access graphical UI, not to add even more hotkeys. 

The real culprit is that we miss the double menu entry in the header for dyntopo and remesh. And so users needs to dig for it in the tools. That's scrolling and searching. I am not even sure if this isn't a merge regression.

We should put those two panels back into header, and remove it from the tools if possible. Makes both areas more accessible then.

![dyntoporemeshmissing](https://user-images.githubusercontent.com/13919702/80303492-e4275c00-87b0-11ea-9e8f-2efd08739fd5.jpg)

**Comment by ReinerBforartists** [comment]
Closing this one. We cannot fix the broken keymap manager. And i don't want to add a hotkey here.

**Comment by Draise14** [comment]
But it's a console bug that need to be fixed. And I technically cannot add a hotkey to that function. I've used this operator a dozen times in a half hour... the bug is slowing performance....

**Comment by Draise14** [comment]
The bug is not present in the blender keymap...

**Comment by ReinerBforartists** [comment]
Ah okay. Then let's reopen it.

**Comment by ReinerBforartists** [comment]
That you can't assign a hotkey here is a known blender bug. I cannot fix it. 

Let's have a look for the NoneType error now. How do i reproduce it?

**Comment by ReinerBforartists** [comment]
Draise could you please create a task for just the quadriflow issue?

**Comment by ReinerBforartists** [comment]
I cannot reproduce your issue. I have added both hotkeys, shift r and ctrl r, and don't get a error message in console. So i need a way how you managed to get this error in the console.

**Comment by Draise14** [comment]
Theoretical Steps to reproduce:
1. Use default BFA 2 - 2.0.0 bforartists keymap
2. Go into sculpt mode
3. Hover mouse over Remesh button
4. See error in console

Fix (?!):
1. Assign hotkey in the Input Editor to Remesh modifier
2. Error dissappears. 
3. Delete hotkey in editor, error still doesn't appear. 

I can't reproduce it now. After you assign the hotkey, it fixes. Bizzare. 

Let's just close this. I'll make another task for the Quadriflow Remesh option.
