### ISSUE TITLE
3D View - Sculpt Mode - Edit Voxel Size for Remesher is not exposed in UI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1481]
# Issue
This operator and Blender hotkey is not exposed in the UI:
![bforartists_2020-04-25_20-39-15](https://user-images.githubusercontent.com/35357409/80295145-dda7ce80-8735-11ea-8c37-47c3b4105c46.png)

This should be exposed either in the header or in the Remesh panel. A hotkey assigned to this might also be nice on default. 

# Task
Expose this in the UI. Icon option. 

Debate to where might need to be discussed.

**Comment by ReinerBforartists** [comment]
Also here, voxel size already exists in the UI. We would add a redundant entry when we would add it as an operator now.

We could add a hotkey hint to the tooltip.

![voxelsize](https://user-images.githubusercontent.com/13919702/80298902-e1b50a00-8790-11ea-8f46-eef2fe6efb6a.jpg)

**Comment by Draise14** [comment]
This is a separate mode. Once triggered, it shows a visual widget to sample then set at cursor position and mouse drag, like a brush. The exposed sample button is a dropper and samples from mesh only. 

They are different functions for the same goal. but the UX needs to be defined in the UI in  the BFA way: the brushes on the texture paint mode had these mouse gesture/widget functions exposed as a button beside the sliders for discoverability. It would only be consistent and hotkey only operators would be exposed to UI per the BFA way. 

Differences:
1. sample from mesh
2. sample from mouse gesture at cursor position through widget (missing from UI) 

Related operator differences that need to be exposed to UI: #1482

**Comment by ReinerBforartists** [comment]
Made it a task. Thanks for your effort :)

**Comment by ReinerBforartists** [comment]
As told, this is just another way to adjust the voxel size. Yes it adds a widget when you use it by hotkey. But it is still the values from the slider. 

I have added the hotkey hint already. But made a mistake with the text, it differed from the other entries. And it should be consistent. 

Corrected with the newest commit.

![hotkeyhint](https://user-images.githubusercontent.com/13919702/80857184-5c2dd000-8c50-11ea-8201-252fc637668f.jpg)
