### ISSUE TITLE
3D View - Sculpt Mode - Set Detail Size for Dynamesh is not exposed in UI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1482]
# Issue
![bforartists_2020-04-25_20-49-22](https://user-images.githubusercontent.com/35357409/80295182-5149db80-8736-11ea-8b22-bba7b3edbc42.png)

The hotkey Shift D is not exposed in the UI. It's a button that should have a shortcut, but it's not assigned in BFA, so should be able to be assigned easily. It's a Dynatopo action (set's a mode to scale the detail size then set).

# Task
- Expose this operator to the UI, either in the header or Dynatopo panel
- Maybe add this hotkey back to BFA defaults

**Comment by ReinerBforartists** [comment]
Detail size is already in the UI. There is no useful place where we could add a second operator to show the hotkey. We would add a redundancy here.

We could update the tooltip to tell the user that the hotkey exists.

![detailsize](https://user-images.githubusercontent.com/13919702/80298769-fb098680-878f-11ea-93fc-14f2e6597331.jpg)

**Comment by Draise14** [comment]
This is a separate sampling mode. This hotkey only operator makes a grid at cursor in the viewport to set the detail size with visual feedback. It's really really useful and I'd be using it at least once a minute during sculpting sessions. 

The panel only has sample setting, and when used they give no visual feedback and the slider has no visual feedback. The hotkey only operator is a completely different method to sample because of the widget. The way to trigger the widget method of sampling needs a UI entry.

If the function is redundant, we should change the sample button to trigger the widget sample method instead of the default legacy sample because better UX is with visual feedback.

**Comment by Draise14** [comment]
The sample detail button beside the slider could trigger this. Or another button by the sample button with some two way arrows ( consistent with the brush buttons we added to expose how to change brush sizes by hotkey).

**Comment by ReinerBforartists** [comment]
Thanks for pointing this one out. I will investigate into this one when i claim the task. The best place is directly besides the slider then i guess.

**Comment by ReinerBforartists** [comment]
It is as i have initially said. This is connected with the Detail Size slider. It is just a way to adjust this panel by hotkey. 

It makes no sense to add an extra button here. The widget would be covered by the panel. 

We had a little button behind the silder with the brushes for a while, but i was not happy with it. I have then added a hint to the hotkey in the default keymap. Which is valid for the Bforartists keymap and the Blender default keymap. I will now do the same here.

![setdetailsize](https://user-images.githubusercontent.com/13919702/80856743-c5134900-8c4c-11ea-89e5-c9cf7afc996f.jpg)

![hotkeyindefault](https://user-images.githubusercontent.com/13919702/80856744-c93f6680-8c4c-11ea-95a6-5c4cbaa1b4e5.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![hokteydefault](https://user-images.githubusercontent.com/13919702/80857030-2b00d000-8c4f-11ea-8af3-0672c87eee33.jpg)
