### ISSUE TITLE
3D View - Sculpt Mode - Expand Mask needs to be more intuitive in BFA

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1483]
# Issue
![image](https://user-images.githubusercontent.com/35357409/80295259-07152a00-8737-11ea-8ccf-fb676709a23f.png)
Right now, these Expand Mask options are only discoverable and useable from in the header, but they way they work is by cursor position on mesh. The BFA way: a trigger from the header, makes the last remembered position of the cursor to then expand, which means you ahve to place the cursor THEN run the operator from header. But intuitively, you'd want to position the cursor BEFORE you activate the tool (via a hotkey, pie or context menu), but right now.. it's not possible. The BFA way to expand mask is worse right now. 

# Task
- Add the hotkeys to BFA default
![image](https://user-images.githubusercontent.com/35357409/80295316-886cbc80-8737-11ea-9ade-d293bbe9c66d.png)

- Or add a button to the Context menu or sculpt pie menu to trigger from cursor position via mouse. 
- Or add Expand Mask operator to double Lclick in sculpt mode, maybe? Make it intuitive through mouse or a modifier for the mouse.

**Comment by ReinerBforartists** [comment]
Adding the hotkeys is required when it is a hotkey only tool. In this case we should also add a hint to the tooltip that this is hotkey only tools.

**Comment by ReinerBforartists** [comment]
Fixed in master
