### ISSUE TITLE
3D View - Sculpt Mode - Face Sets hide operators needs to be exposed in UI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1484]
# Issue
![bforartists_2020-04-25_21-06-17](https://user-images.githubusercontent.com/35357409/80295507-c28a8e00-8738-11ea-8d1c-61492aa85630.png)
The hide and show face set operators are not exposed in the UI, only the ALT+H one, to show all facesets. As far as I know, all hotkey only operators should be in the UI, exposed and customizable. 

# Task
- Add these with icons to the header for Facesets

`I've found so many hotkey dependant operators in the sculpt mode.. sorry... But eh.. yeah, I'm sculpting, thus finding workflow and UI issues: `
![bforartists_2020-04-25_16-53-57](https://user-images.githubusercontent.com/35357409/80295501-b9012600-8738-11ea-8212-447d1d10cd1b.png)

**Comment by ReinerBforartists** [comment]
Facesets is a new feature, under development. So no wonder we still find issues. Good catch.

**Comment by ReinerBforartists** [comment]
Fixed in master

![hide](https://user-images.githubusercontent.com/13919702/80349617-cbca4680-886f-11ea-8d38-8d6a222c00ac.jpg)
