### ISSUE TITLE
Put Dyntopo and Remesh panels back into header

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1486]
Currently the Dyntopo and Remesh settings and tools are hard to reach. We should put it back into the header.

![dyntoporemeshmissing](https://user-images.githubusercontent.com/13919702/80303521-0f11b000-87b1-11ea-92c4-e622ffb0a47e.jpg)

**Comment by ReinerBforartists** [comment]
Related 3D View - Sculpt Mode - Remesh shortcut bug and inconsistencies #1480

**Comment by Draise14** [comment]
Who knew I'd kiss this without even knowing about it!

**Comment by ReinerBforartists** [comment]
Merges always brings the danger of such regressions, unfortunately. That's the price of working with two code bases ...

**Comment by ReinerBforartists** [comment]
Hmm, now we have of course the double menu entry again.

**Comment by ReinerBforartists** [comment]
Fixed in master.
