### ISSUE TITLE
3D View - Sculpt Mode - Remesh panel inconsistencies with Quadriflow

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1496]
# Issue
![image](https://user-images.githubusercontent.com/35357409/80389489-c15c7c80-8870-11ea-80af-749f1a172f8a.png)

The Remesh panel in the Properties editor > Object Data has a Quadrify and Voxel mode, but the Remesh panel in the Properties Shelf in the 3D Editor doesn't. There are some inconsistencies. 

# Task
Add the Quadriflow/Voxel mode to the Remesh panel.

**Comment by ReinerBforartists** [comment]
Fixed in master

Found and fixed some other cosmetics too.

![fixed](https://user-images.githubusercontent.com/13919702/80464789-976f8c80-893a-11ea-8914-c60bbebc47c8.jpg)

**Comment by ReinerBforartists** [comment]
Related because of the micro fixes here 

Sculpt mode - Sidebar - fix right aligned props #1497
