### ISSUE TITLE
Video Sequencer - Select - Channel - Attribute error in console

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1503]
# Issue
![image](https://user-images.githubusercontent.com/35357409/80517217-57180a80-894a-11ea-8e29-7f34a70fde93.png)
![image](https://user-images.githubusercontent.com/35357409/80517429-ae1ddf80-894a-11ea-8db6-6df2ee2518f3.png)

Missing attribute defined in the channel submenu of the Select header menu. 
Line 372 and 373 are not present in the latest Blender builds. 

# Fix
Remove these lines, or verify if these operators exist and set them to work. 

_heh, this is one I could fix. I need to commit and finish my VSE documentation commit..._

**Comment by Draise14** [comment]
![bforartists_2020-04-28_12-37-19](https://user-images.githubusercontent.com/35357409/80519060-01912d00-894d-11ea-91e3-ac2c0d4a2924.png)
Did some digging, can't find the operator for the trouble lines. Maybe we could delete them? I guess Blender devs finally are cleaning up some redundency.

**Comment by ReinerBforartists** [comment]
Yes, there is just select_side left in Blender. select_active_side is gone. And there is also no keymap binding to find. I would say you can savely remove the two select_active_side entries in the class SEQUENCER_MT_select_channel(Menu): in space_sequencer.py

![channel](https://user-images.githubusercontent.com/13919702/80564539-62bd0d00-89ee-11ea-822e-d65827242e2a.jpg)

**Comment by Draise14** [comment]
Ok, committed the fix and did a pull request.
