### ISSUE TITLE
Remove Blender version number from the Scene Info in the footer

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1505]
The footer contains a version string for the current Blender version. We don't need this number. Remove it.

![blenderversionhint](https://user-images.githubusercontent.com/13919702/80590342-053fb500-8a1c-11ea-80cf-aefe62f375b3.jpg)

**Comment by Draise14** [comment]
Would the Blender version this is forked from still be set in the Splashscreen?

**Comment by ReinerBforartists** [comment]
Sure. But this number does not belong into our scene info.

**Comment by ReinerBforartists** [comment]
Fixed in master
