### ISSUE TITLE
Quick Menu - Make consistent in all editors

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1509]
# Issues
Right now the 3D View has the quick menu exposed. It can also be called in a floating menu with the button Q. The exposed header menu is nice, specially to save on using hotkeys and submenus.   
![bforartists_2020-04-29_12-55-52](https://user-images.githubusercontent.com/35357409/80629651-c4926c80-8a18-11ea-856c-76bcbf14c01e.png)

But...it is nowhere else. 

You can call a custom quick menu from any editor with the Q key, yet some editors really would benefit from this custom menu. Eg. The animation editors, the video sequence editor, the shader editor, etc. 

Can we expose this floating and hotkey only menu to all editors that have it? 

# Task
Add the Quick Menu entries to the headers of all editors with relevant headers and quick menus.

**Comment by ReinerBforartists** [comment]
Hm, i decided to implement it everywhere since it adds noise. And the 3d view is usually the only editor where you really consider to use it. But i can of course also have a look to implement it in other editors.

**Comment by Draise14** [comment]
Yeah, the outliner, the toolbar, and a couple of other editors would be a bit noisy. Maybe only some could get it, where we think it could be useful, like the VSE (a completely different tool space) and the motion tracking. Also in the node and animation editors, no-where else.

**Comment by ReinerBforartists** [comment]
Fixed in master. Added the quick menu noise also to the other editors.

**Comment by Draise14** [comment]
Cool! Another hotkey less. Thanks for this.
