### ISSUE TITLE
Video Sequencer and Graph Editor - Black numbers on "row" numbers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1510]
# Issue
Black numbers on track/y axis numbers. Should be white like the X axis and frame numbers. I tried to find these settings in the theme editor, but failed. The issue is in the Video Sequencer, The Driver Editor and the Fgraph Editor. 

**Video Sequencer**
![image](https://user-images.githubusercontent.com/35357409/80640198-ae8ca800-8a28-11ea-8bf4-097db232faef.png)

**Graph Editor**
![image](https://user-images.githubusercontent.com/35357409/80640482-14792f80-8a29-11ea-83b1-10a4f6c49447.png)

Contrast is a key thing of the BFA theme, here there is none. 

# Task
Make them white somehow?

**Comment by Draise14** [comment]
Ah, found it.

![image](https://user-images.githubusercontent.com/35357409/80640749-7b96e400-8a29-11ea-994f-cf9625787a36.png)

**Comment by ReinerBforartists** [comment]
This one is a bug.

**Comment by ReinerBforartists** [comment]
Hm, i have white letters here in the defaults. Can it be that you toyed around with the theming at one point? Remember, such things are all stored in the appdata directory ...

Closing as invalid. There's nothing to fix for me here.

![alreadywhite](https://user-images.githubusercontent.com/13919702/80694263-8d819100-8ad4-11ea-8287-719de9f5e943.jpg)
