### ISSUE TITLE
Presets for the Principled Shader

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#152]
Presets for the Principled shader would be a fine thing!

**Comment by Davis-BfA** [comment]
How would you integrate them into BfA, just add them to the VX library?

**Comment by Davis-BfA** [comment]
I always have the material preview open on the right anyway to see the effect of the changes done in the node editor. - Library VX is a good system, the only pity is that it does not show any material previews, so it is a bit tiresome to find the right material easily when browsing.
Something like dynamat would be cool. http://www.dragoneex.com/downloads/dynamat-add-on
Unfortunately they stopped developing it at version 0.1 already as it seems. But the way to browse and preview the materials looks perfect.

**Comment by ReinerBforartists** [comment]
Thanks for the link. Looks interesting. Unfortunately the download doesn't work :/

**Comment by Davis-BfA** [comment]
It works here. It redirects to gumroad ... https://gumroad.com/d/c33d4becc2e394a13a50e7d9314d89a7

**Comment by ReinerBforartists** [comment]
Chrome doesn't work. Firefox redirects me to Paypal. Your above link tells me that i am blocked, and that i have to reenter my email adress ...

As told, it does not work ^^

**Comment by Davis-BfA** [comment]
Weird. ^^ ... Well for testing purposes, I uploaded the zip file to wetransfer. ;)
https://we.tl/xQXYgSuqFI

**Comment by Draise14** [comment]
I like the idea of Dynamat more than the VX material browswer, to be honest. Though a fusion would be amazing.

**Comment by ReinerBforartists** [comment]
Adding both is a bad idea. We can't have several addons for the same thing.

**Comment by Draise14** [comment]
Fusion as in a new addon. With a bit of both in one. The quick cycle and previewer and the categories and name filter.

**Comment by ReinerBforartists** [comment]
Just when you write it ^^

**Comment by ReinerBforartists** [comment]
We fill the materials library vx with more materials at the moment. Which makes this task obsolete.
