### ISSUE TITLE
Dopesheet - set keyframe type afterwards fails

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1524]
We have a problem here. We cannot change the keyframe type afterwards like in Blender.

![keyframetype](https://user-images.githubusercontent.com/13919702/81469211-1a6acf80-91e4-11ea-9698-47c46bb8cd33.png)

**Comment by ReinerBforartists** [comment]
Fixed in master

Using the menu enum now, not the prop anymore. Which gives us the same behaviour than in Blender.

Catched some trailing whitespaces too.

**Comment by Draise14** [comment]
Beautiful.
