### ISSUE TITLE
Node Editors - Make the Add Header Menus consistent with the Add Properties Shelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1525]
# Issue
![image](https://user-images.githubusercontent.com/35357409/81477049-18504300-91db-11ea-8012-4f52172624ad.png)

Right now, the node property shelf is neatly organized into panels with icons - highly preferable. 

But the add menu in the header is drastically different. 
1. It has no icons
2. It's structure is completely different, bloated and inconsistent (Blender style)

# Solution
In the Node editor and the Compositor, it would be good to make the Add header menus iconized and consistent with the panels in the properties shelf. 

## Notes
I think these menus are enumerated in C, so might be a bit of a too big fish to fry..? 

This might make it less compatible to blender tutorials, but it will make it better to have the same system in the documentation and our own tutorials, and keeps it consistent and visual.

**Comment by ReinerBforartists** [comment]
Nice dream. I think i failed at this one before ^^

**Comment by ReinerBforartists** [comment]
The icon part has its own task meanwhile: Node Editors - iconize add menus #2043

Remains the order.

I am not sure what to do with the consistent menus here. The add menu is hard to modify. And even when we modify it, this could become a maintaining nightmare with Blender changes then pretty quick. 

On the other hand, the order in the sidebar has its structure for good reason. The most used nodes are at the top. So when we reorder it in the Blender way then the user are quickly in trouble to find the relevant nodes. 

That's the choice between pest and cholera. Not happy about either change. But i see the need for consistency.

**Comment by ReinerBforartists** [comment]
Looking at the maintaining nightmare, we only have the choice to do it the Blender way really, or leave it alone.

The new structure was once introduced to make it easier to pick the most used nodes. I don't want to revert it. And i don't want to change the order of the Add menu, since this can quickly escalate with every new node.

So, decision time. We leave it the way it is. The user can decide which structure he likes best.

Closing. Won't fix.
