### ISSUE TITLE
Add a material system in the shader editor

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1526]
It is cumbersome to open the material library vx addon in the properties editor all the time to manage materials. It should show when you enter the shading workspace. And it should stay in sight.

Maybe we can manage to add it to the sidebar. Or implement another material system addon here.  Maybe even a self made one.

![matlib](https://user-images.githubusercontent.com/13919702/81478853-270d1900-9220-11ea-824c-1f3d3038646a.jpg)

**Comment by ReinerBforartists** [comment]
While at it, we need some more basic shaders. Like an Ocean shader. We have an ocean modifier, so we need an ocean shader. 

basic != simple ...

**Comment by ReinerBforartists** [comment]
Ah this needs to be an extra task ...

**Comment by ReinerBforartists** [comment]
Not sure if this one still makes sense. We have now an asset manager. So it would be better to incorporate the asset manager into this layout, and provide the materials as an asset library. 

I wish the development of the new asset manager would be a bit more progressed already. So that we know what we really get ...

**Comment by ReinerBforartists** [comment]
This task has become obsolete with the upcoming asset manager. What we need instead is to integrate the asset manager into the shader editor layout.

**Comment by Draise14** [comment]
Sounds good. Will this mean having some good presets already included with BFA asset libraries?

**Comment by ReinerBforartists** [comment]
This is the plan. To provide quite a few assets: Remember the trueSapce libraries? :)

But first they need to finish the asset manager. They have made it a developer feature again.  And i think quite a few things are to change before we see it as a productive feature. So it may still take a while.
