### ISSUE TITLE
Properties Editor - Object Tab > Collection Panel > Drop Down arrow missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1528]
# Issue
![bforartists_2020-05-09_23-25-11](https://user-images.githubusercontent.com/35357409/81490829-5fc2e780-924c-11ea-863b-920d8296a3c0.png)
Missing icons in the Properties Editor - Object Tab > Collection Panel > Drop Down arrow 

An object needs to be added to a collection to see. 

Version `devbuild-03-05-2020`

# Solution 
Add them? I think they exist.

**Comment by ReinerBforartists** [comment]
Fixed in master

I have also renamed Unlink to Delete. Artists are not programmers.

![FIXED](https://user-images.githubusercontent.com/13919702/81532153-38f7d480-9364-11ea-8214-52b84e2db31e.JPG)
