### ISSUE TITLE
Turn Phyton tooltips off by default

### ISSUE THREAD

**Issue by Davis-BfA** [Bforartists/Bforartists#153]
For the tooltips it might be better to turn the phyton tooltips off by default. - Although very practical for coding, they make the tooltips look more complicated than they are to the average artist. That under the hood info might be better kept behind the scenes to make the interface feel even less intimidating. 

Since it can be turned on in the user preferences with one click, no developer should complain about this change anyway,

![phyton tooltips](https://user-images.githubusercontent.com/37657420/38471430-5e31e1d4-3b71-11e8-90ec-56a4ee7bccf1.jpg)

**Comment by Draise14** [comment]
Unless I'm coding I usually have these off myself.

**Comment by ReinerBforartists** [comment]
Reminder, this is for the official version. So postponing until we have the next version ready.

**Comment by ReinerBforartists** [comment]
Hm, there are a few tooltips that we cannot separate where the python string tells you about the functionality. So it's not really wise to turn them off  :/

**Comment by ReinerBforartists** [comment]
Closing this one since we simply cannot do this.
