### ISSUE TITLE
Addon Icon Compatibility Check

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1535]
# Issue
I've been testing out a number of addons that work with 2.8, and they are pulling icon errors, thought they don't in Blender. Have some icon index names changed? 

These addons are ones like Sverchok, COA tools, Matalogue, etc. They have been updated to Blender 2.8, but now in the `devbuild-03-05-2020` they are pulling errors. 

Icons I've found missing so far are **ANIM**, **MATERIAL** and **TRIPLE DOT** that aren't in Bforartists.  

# Solution/Task
Is there a possibility that all icons in Blender still be listed in the index, even if empty for addon compatibility? 

Have they done any cleanup these days, maybe addons will need to refactor to 2.9 icons?? Why are so many now becoming incompatible?

### Reason
Addons are pretty big in the opensource community, would be great to make sure they can atleast find all blender icons.

**Comment by ReinerBforartists** [comment]
Should be possible. But first please find them all ^^

**Comment by ReinerBforartists** [comment]
I'll go through the UI_icons.c file here.

**Comment by ReinerBforartists** [comment]
Hm, not really happy to add all possible missing icons here. We have removed the doubles for good reasons. So i will start with the three told ones here, and add them back in case we stumble across a missing icon.

**Comment by ReinerBforartists** [comment]
Ah what the heck, let's try to catch as much as possible, to avoid future conflicts.

**Comment by ReinerBforartists** [comment]
Fixed in master. Addons should not fail anymore because of missing icons.

**Comment by Draise14** [comment]
Phew... that was a lot of icons. Sucks it has to be messy, but glad to hear most addons will not glitch out now. I think that's the second question after "What is Bforartists?" that people have most asked me: "Does it work with Blender addons?". Yes, I can guarantee now.

**Comment by ReinerBforartists** [comment]
Ah, it was fewer than expected. But our sheet starts to burst at the seams now ^^
