### ISSUE TITLE
Preferences - Add Open Preferences Folder to Preferences save dialogues

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1538]
# Issue
When developing addons, fixing addon bugs, and also when you need to do a hard factory reset for testing.. I've noticed a lot of users don't know how to get to the appdata config folder to troubleshoot, and/or I go there way to often to be comfortable fixing things. 

A user in the discord threw an idea with some code, and I scripted it a little more to make it hopefully relative: 

Tadaa! 

An entry to open the appdata folder: 
![image](https://user-images.githubusercontent.com/35357409/81711325-2a2f2180-9439-11ea-80b3-ee33fcec9d01.png)

# Task
Add an operator with a redirect icon to open the relative configuration path. 

### Reason
It will show users that a configuration folder exists when you use BFA through the UI (in Blender it's just.... expected prior knowledge), and with that exposed, users can also potentially easily learn how to factory reset to troubleshoot if needed, or get to know where their addons/script/hotkeys/configurations are. It is just to show and give access to artists and developers without any prior knowledge of how to get to these settings. It will also make it easier to give support when testing bugs when people sometimes request help in Facebook, Discord or in the forums. 

### Notes
I've already implemented and use this now. It's handy. 
I have a commit for this. 
I don't know if the relative path will work in MAC or Linux. This needs testing.

**Comment by ReinerBforartists** [comment]
Looks indeed useful. I need to think this through. 

I will test if it works under Linux when i find the time for.

**Comment by ReinerBforartists** [comment]
First thought: the preferences should be at the end of the menu. They are most used, and that way they are easiest to reach. The folder is something that a user opens once in a lifetime. Which raises the second question. Wouldn't this menu item not better fit into the preferences panel?

**Comment by Draise14** [comment]
Good point. I put it on a surface level due to the script editor, for loading scripts for addons and things, but if it's psychologically more related to preferences, then yes.. it should go in the preferences, not in the Edit category. 

![image](https://user-images.githubusercontent.com/35357409/81715886-58633000-943e-11ea-80ca-aece00bbe68d.png)

Sidenote: this menu has missing icons? 

**Observations:** 
Maybe we can add "Open Preferences Folder" into the preferences editor.
Then also add "Open Scripts Folder" into the script editor, which would be the subfolder for the addons/scripts.

**Comment by ReinerBforartists** [comment]
Yes, yes and yes. Please make a tracker entry ^^

**Comment by ReinerBforartists** [comment]
And you might want to grey out the menu item in case the folder does not exist yet ...

**Comment by Draise14** [comment]
Eh... how do I make it check if a folder exists then grey out? That's a bit new for me.

**Comment by Draise14** [comment]
> Yes, yes and yes. Please make a tracker entry ^^

Ok, will do that, and close this one.

**Comment by Draise14** [comment]
Related: #1539

**Comment by ReinerBforartists** [comment]
Why do you want to close this one now? Just the destination has changed. The taks remains. You can also rename tasks :)

Next time ^^

> Eh... how do I make it check if a folder exists then grey out? That's a bit new for me.

Have a look at the Materials Library VX addon. It does unfortunately exactly this. And makes us trouble now with firststart ...

**Comment by ReinerBforartists** [comment]
With make a task i meant to create one for the missing icons ...

**Comment by Draise14** [comment]
I have committed to the wrong task, but the commit is referenced.

I have added a variable that declares the LOCAL instead of USER if the USER folder doesn't exist. So.. the button should still be useful even if the folder isn't written to the USER defaults. But it will default to USER once it's saved (checks if it exists).  

But.. I just did a test, needs more work. Sorry for the rush.

**Comment by Draise14** [comment]
Ok, pull request done. I'll do the icons next after.

**Comment by ReinerBforartists** [comment]
As told in the pull request, not so fast please. We still need testing for linux and mac. And do we have the same menu item at two locations now?

**Comment by Draise14** [comment]
Sure. It can wait. No problem

Concerning the two places, it's only now in the one place in the Preferences Editor save/open submenu. I reverted the first proposal technically.

**Comment by ReinerBforartists** [comment]
Hm, what about the location in the text editor. That's where you need it most as an addon developer. The hidden menu where you have currently added it is a bit too hidden. No user will ever find this.

Another thing, we still need to test what happens if the folder does not exist. Have you tested it and found a solution?

Linux can be tested by installing VMWare at Windows, and Ubuntu at it.

I will wait now until your next pull request :)

**Comment by Draise14** [comment]
> Hm, what about the location in the text editor. That's where you need it most as an addon developer. The hidden menu where you have currently added it is a bit too hidden. No user will ever find this.

I'll make another task for this. I'll make it open in the scripts folder directly instead of the preferences folder, but that will be another task. 
 
> Another thing, we still need to test what happens if the folder does not exist. Have you tested it and found a solution?

Right now, I have a conditional that tests the existence of the folder, and if it doesn't exist, it goes to the LOCAL folder: the root of the executable. I've tested it by deleting, recreating, deleting, starting deleted, started created, etc. No issues. The same could be applied to the VX library addon. 

> Linux can be tested by installing VMWare at Windows, and Ubuntu at it.
> 
> I will wait now until your next pull request :)

My friends who use linux have managed to run the script conditional in question and it's finding the USER folder location without a problem, but I'll have to also test on the VMware. I'm gonna make another test script - gotta learn how to do addons to make the testing with my friendly user base easier... it's surprising how many use linux (mostly Arch and Manjaro). 

This was the first test, the OS is finding the USER settings folder perfectly fine. If it doesn't exist, it should be able to see, as it does in Windows. The paths use the LOCAL/USER api of Blender which is theoretically OS agnostic.  
![](https://cdn.discordapp.com/attachments/690583457545453660/710053991937081394/unknown.png)

**Comment by ReinerBforartists** [comment]
Sounds good :)

**Comment by ReinerBforartists** [comment]
Please make an extra task for the missing icons! To fix everything in one big commit is bad.

**Comment by ReinerBforartists** [comment]
Ah, you already have. And postponed it. That's why i had overlooked it ^^

**Comment by seanr** [comment]
FYI, USER resolves to the correct path on all OSes so there shouldn't be anything else needed here for Mac OS, but if you're curious, the Mac location is at `~/Library/Application\ Support/Bforartists/[Blender version]/config`. Right now, this is `~/Library/Application\ Support/Bforartists/2.92/config`. Similarly, scripts are here: `~/Library/Application\ Support/Bforartists/[Blender version]/scripts`. In those examples, the `\` is escaping the space for command line usage.

**Comment by ReinerBforartists** [comment]
Thanks for the information :)

**Comment by ReinerBforartists** [comment]
Mh, what was the state of this issue? Did we have a working entry somewhere?

**Comment by Draise14** [comment]
Yeah, the code worked fine. It just needs committing I guess, and an icon. I wasn't sure which icon to put it nor where to put it in the end.

**Comment by ReinerBforartists** [comment]
The icon you used was just fine. And we just still discussed the location from what i remember.

**Comment by ReinerBforartists** [comment]
What is the state here?

**Comment by Draise14** [comment]
Code works fine and in all OS as it's relative to user or local relative paths. We have an icon for it. 

Just it's not clear where to put the entries. 

Once we decide where, I can commit it.

**Comment by ReinerBforartists** [comment]
Edit menu looks fine to me :)

**Comment by Draise14** [comment]
I'll pull this one after the first task in #2344 is merged.

**Comment by Draise14** [comment]
Ok, pulling this one now. #2351

**Comment by ReinerBforartists** [comment]
Perfect. Many thanks :)
