### ISSUE TITLE
Preferences - Add icons to save & load dialog

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1539]
# Issue
Icons missing:

Here is an example:
![image](https://user-images.githubusercontent.com/35357409/81718780-c8bf8080-9441-11ea-9d01-75aa128b058e.png)

# Task
Add icons

**Comment by Draise14** [comment]
I made it point to the %appdata%/Bforartists/Bforartists/ folder, but not the subfolder, so it wouldn't need to be greyed out. Thent he user can go into the 2.9/2.8 folder accordingly.

**Comment by ReinerBforartists** [comment]
When the folder does not exist then the user could experience a error message. That's not good ...

**Comment by ReinerBforartists** [comment]
This task was split from another task, and contains invalid data for it. So here again the problem. We have missing icons here:

![missing](https://user-images.githubusercontent.com/13919702/81913796-be7fbc80-95d0-11ea-8153-4c6556a1208a.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/81915098-6ea1f500-95d2-11ea-8f08-22a64b971247.jpg)
