### ISSUE TITLE
Properties Editor - Render Tab - Sub Surface Scattery property not found error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1542]
# Issue
![Discord_2020-05-13_13-51-21](https://user-images.githubusercontent.com/35357409/81852629-f0d1e100-9520-11ea-8561-5cfe7b7bd048.png)

Missing property in the Subsurface Scattering panel. 

Version: `devbuild-03-05-2020`

# Task
Check and compare if a missing property is somewhere else, or just deprecated.

**Comment by ReinerBforartists** [comment]
This one was a merge regression. They removed the prop. We had it still in the code.

Fixed in master
