### ISSUE TITLE
Rework handle type icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1549]
Just noticed that the dopesheet displays different handle types of the keyframes by different shapes. These shapes should be present in the icons for the handle types. Because at the moment there is no connection between the shape of the keyframe and the handle type type.

That's of course just the case in dopesheet. And the handle type menu is more used in graph editor. But maybe we can improve our icons here a bit. And give the center spot the needed shape.

![handletype](https://user-images.githubusercontent.com/13919702/82112730-024d0000-9750-11ea-819d-a7fff3eae36a.jpg)

**Comment by Draise14** [comment]
I like the angles and how they work, but yes, the connection from the dopsheet form and the icon will help a tonne. Maybe a fusion of the angles and the icon shape?

**Comment by ReinerBforartists** [comment]
Problem here is the limited icon space ...

**Comment by ReinerBforartists** [comment]
Doesn't work to include the symbols into the icons. We can either have the one or the other. I will nevertheless have a look to improve these icons. They are a bit thin.

**Comment by ReinerBforartists** [comment]
Fixed in master. They stick out better now.

![fixed](https://user-images.githubusercontent.com/13919702/99374904-61d4c580-28c3-11eb-978f-4223e3805e09.jpg)
