### ISSUE TITLE
Middle Click on Header menu entry to repeat last action of select menu, possible? 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#155]
In Softimage (and now Maya) every menu header would have a memory and if you middle click a menu it would repeat the last action used uniquely in that menu - meaning if I wanted to, I could turn a menu into a single operator button with repeat use without needing to use a shortcut or open the same menu over and over again, I wouldn't even need a toolbar. 

**Example:** 
Choose from the header menu _3D View>View>View Global/Local_
Now middle click on _3D View>View_ in the header and it will repeat the last action in that submenu "View Global/Local"

Now if I go to the same menu and choose _3D View>View>Toggle Quad View_
I now can middle click on _3D View>View_ and it will now "Toggle Quad View" without me needing to open, move mouse and choose or use a hotkey. 

I know Blender has it's limits to it's core - and changing anything would require a lot of work - but technically, could it be possible to make a watchdog for each menu write a memory of last used operator and create conditional triggers when middle clicking on a menu of last remembered use - would this be possible? Maybe through an addon? 

This is NOT the "Repeat Last" action for global operations, it is custom to the header parent menu entries. 

Just curious to know if this is even possible.

**Comment by ReinerBforartists** [comment]
I don't see any way to implement this with the Blender UI solution, sorry.
