### ISSUE TITLE
Properties Editor - Output Properties - Output - double entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1551]
## Issue
![bforartists_2020-05-15_22-41-25](https://user-images.githubusercontent.com/35357409/82130809-6db8c100-9794-11ea-8b20-a6f5badaad51.png)

You have two of the same entries double up right on top of each other, Placeholder and Overwrite under the Image Sequence options of File Ouptut. These are very redundant. 

Version: `devbuild-10-05-2020 `

## Solution
Remove the secondary ones, keep them only under Options collapsible menu.

**Comment by ReinerBforartists** [comment]
Good catch!

**Comment by ReinerBforartists** [comment]
Hm. Blender does not have the options tab anymore.

**Comment by ReinerBforartists** [comment]
We keep the options tab. 

Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/82181130-39531b00-98e2-11ea-8cf4-6cdf15a5e8c7.jpg)
