### ISSUE TITLE
3D View - Grease Pencil Drawing mode - Colour Pallettes Vertex Colour Mode in Context Menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1552]
# Issue
![bforartists_2020-05-15_18-51-34](https://user-images.githubusercontent.com/35357409/82131077-16682000-9797-11ea-8310-f510cd599cf5.png)

Right now, there is a double right click floating panel for quick GP colours and pen options, even a way to change brush material, but it's not too useful. BUT, there is a strange square showing the current colour, and not any other colour .

This is the colour palette that is very useful:
![bforartists_2020-05-15_18-51-47](https://user-images.githubusercontent.com/35357409/82131043-a5286d00-9796-11ea-9808-ffb8867a3633.png)

# Possible Solution
1. Add the colour pallete options or flags to the context meny when in Color Vertex drawing mode
2. Make the layout more consistent with the tool settings dropdowns, like the two colours, swapping them over, etc. 

# Notes
This might not be... possibly great fun. It's a "contextual" menu afterall, it's double click to access, it's also a double entry. It only exists to save time moving and loading sub menus with the mouse when you can trigger and use it there under mouse to save time. But.. making it a little more functional with color pallettes might make it more useful.

**Comment by ReinerBforartists** [comment]
Hm, i don't really want to change and develop the rmb menus too. You know my opinion about it ^^

But let's make it a task.

**Comment by ReinerBforartists** [comment]
Checked, and it is all there already. 

When you paint with material, then you have the dropdown box to choose the material.

![materialpaint](https://user-images.githubusercontent.com/13919702/99285913-7455ed00-2838-11eb-878c-e1d02de5f408.jpg)

When you turn on to paint with vertex colors, then the rmb menu changes. It shows the color wheel, and a way to change the vertex color. Only the palette is missing. But it is this big that it makes more sense to adjust it in the sidebar anyways.

![vertcol](https://user-images.githubusercontent.com/13919702/99286017-951e4280-2838-11eb-9804-4586a5087b2c.jpg)

Nothing to do here really. I will close this task now.
