### ISSUE TITLE
3D View - Greasepencil - Draw Mode - Add D and E to draw and erase

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1553]
# Request
![image](https://user-images.githubusercontent.com/35357409/82131128-98f0df80-9797-11ea-8f0c-c404c40817f2.png)

![image](https://user-images.githubusercontent.com/35357409/82131183-fedd6700-9797-11ea-87b3-fee0108c8500.png)

I love drawing in the GP, but it clearly is not a replacement for Annotations just yet. It would be great to make the experience a little more consistent when in Annotation mode or in any other mode where Tweak is the default, so that the instinctive "D to draw" when in Draw mode, will make you draw, and E to erase. So that you can quickly fall back to the default of the draw mode.. like D for tweak - a default action on the index finger. 

## Reason
Will save time moving to the toolshelf all the time
Will make it more consistent with the other D to default of the other edit modes. 

# Task
Add D and E to the Grease Pencil Draw Mode to Draw and Erase respectively.

**Comment by ReinerBforartists** [comment]
Makes sense.

**Comment by ReinerBforartists** [comment]
Postponing for when we reenter development. This one needs testing for workflow and conflict potential.

**Comment by ReinerBforartists** [comment]
Fixed in master

Added D for Push in sculpt mode too to have the D like default key here.
