### ISSUE TITLE
.deb installer does not create menu items

### ISSUE THREAD

**Issue by Atrixium** [Bforartists/Bforartists#1554]
When installing with the .deb on Linux Mint 19.3 Cinnamon there is no menu item created and the only way to launch the application is by running /usr/bforartists

**Comment by csehszlovakze** [comment]
Also occurs on Kubuntu 18.04. Also, the starting script/executable should be in `/usr/bin` as it's the standard location and is on $PATH.

**Comment by naetherm** [comment]
> Also occurs on Kubuntu 18.04. Also, the starting script/executable should be in `/usr/bin` as it's the standard location and is on $PATH.

That's not how it should work, as it is stated in the FHS too [0].
```/usr/bin``` is for distribution-managed user commands and as bfa is not in the repositories of *buntu it should - in my opinion - not be placed there (as it is for now a foreign package it is more common, and specified by the FHS, to place it in /opt/bforartists). 
But I see the problem from the previous post and the wrong path, which seems to be a  problem of the cmake installation process. I will take a look asap.

[0] https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf#page=20

**Comment by ReinerBforartists** [comment]
The problem should be long fixed, we did quite a few adjustments meanwhile. And i cannot reproduce it anymore with Ubuntu 20.04

Please feel free to reopent the isssue in case it persists.
