### ISSUE TITLE
3D View - Grease Pencil - Add hotkeys to change modes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1555]
# Request
![bforartists_2020-05-16_17-10-06](https://user-images.githubusercontent.com/35357409/82131307-74960280-9799-11ea-86a9-f8bfca4b9e81.png)

The Grease Pencil object doesn't have the hotkeys for the modes. So you can't go to edit mode, sculpt mode, etc. 

I have done an example of adding in the SHIFT+2 to go to draw mode, to be consistent with object related modes like SHIFT+2 Pose mode of the Armature. 

# Task
Add the hotkeys to change modes
Add SHIFT+2 to go to draw mode when in Grease Pencil object

**Comment by ReinerBforartists** [comment]
Mission impossible. That's a Blender bug. I tried it several times. The keys overrides and conflicts with the normal mode hotkeys.

But feel free to do your own experiments. Maybe you find a way that doesn't break :)

**Comment by ReinerBforartists** [comment]
Here is the original task: https://github.com/Bforartists/Bforartists/issues/488

And the Blender bug report: https://developer.blender.org/T63273

Known issue, also known as we will never fix this ...

**Comment by ReinerBforartists** [comment]
Draise, we should continue the discussion here. The other task is closed ...

**Comment by Draise14** [comment]
Ah sure.  

I have it working using the assigned hotkeys without conflict in day to day work this week. I may need to compile with the hotkey changes to see if it doesn't glitch out.

**Comment by ReinerBforartists** [comment]
Related: https://developer.blender.org/D7835

**Comment by Draise14** [comment]
Ok, just reinstalled the OS to my ssd, so should be able to run a virtual linux build and compile again.

**Comment by ReinerBforartists** [comment]
Landed in the industry compatible keymap with the latest merge. Let's have a look to incorporate it into our keymap too.

**Comment by ReinerBforartists** [comment]
Looking good now. Of course, saving the keymap will now kill these hotkeys again and again. As expected. But this is an easy fix now since the keymap does not completely change with every save. And the keys seems to work just fine now, and doesn't conflict anymore like in the days when i have tried it first.

So fixed in master.

![gpencilmodes](https://user-images.githubusercontent.com/13919702/83398094-fffcce00-a3fe-11ea-8438-c6702d7d972b.jpg)
