### ISSUE TITLE
3D View - Grease Pencil - Sculpt mode resize and strength hotkey pulls an error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1556]
# Issue
![bforartists_2020-05-16_17-22-03](https://user-images.githubusercontent.com/35357409/82157552-c4330780-9847-11ea-9d66-a4d33bd039bd.png)

When pressing the hotkey to resize or change strength of the sculpt brush in Grease Pencil object>Sculpt Mode, it pulls this strange error. I can't see it in the console, and can't find a lot more info about it, but it's pulling issues. 

Version: `devbuild-10-05-2020`

# Task
Check and see why it's doing this, and try to fix. 

### Notes
The hotkey system is fubar.. I agree... 
Postponed

**Comment by Draise14** [comment]
`bpy.ops.wm.radial_control(data_path_primary="tool_settings.gpencil_sculpt_paint.brush.size")
`
The blender hotkey is ok. 

![image](https://user-images.githubusercontent.com/35357409/82157949-43c1d600-984a-11ea-8454-d784258815b4.png)

Found the issue. The BFA map has a changed API. 

gpencil_sculpt = gpencil_sculpt_paint

**Comment by ReinerBforartists** [comment]
We should not postpone bugs ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
