### ISSUE TITLE
UV Editor - UV menu - missing Snap to Pixels and Reset

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1563]
Two missing functionalities. Reset should be in the UV menu. Snap to pixels is something for either the options in the image tab. Or we make it top UI in the header.

![missing](https://user-images.githubusercontent.com/13919702/82350666-f1281b80-99fb-11ea-9bde-7b3c7f4e9512.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

I am not happy with the dropdown box though. But haven't found a useful method yet to turn this into radio buttons. So i will not close this task but postpone it. 

![fixed](https://user-images.githubusercontent.com/13919702/82354026-888f6d80-9a00-11ea-84fb-ee9a790e023c.jpg)

**Comment by iyadahmed** [comment]
what is the state of this issue now, I think it was addressed recently

**Comment by ReinerBforartists** [comment]
Ah, good catch. Yes it was. We have the options in the header now, and the snap to pixels is a button row. 

Closing :)
