### ISSUE TITLE
File Browser - Selection mouse Hotkey modifiers are broken

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1564]
# Issue
Situation: linking/appending multiple folders from a *.blend subfolder using the mouse and keyboard modifiers is impossible. 

Right now, per a report on discord, you can't fill select, nor multiselect very easily. In the BFA keymap, it's impossible unless you use CTRL+SHIFT for a fill/extend select, which is inconsistent with the outliner behaviour - and ultimately broken. 

- You can't select multiple blend sub-folders. 
- You can't fill select blend sub-folders. 
- And when you click once anywhere, you enter the sub folder, you can't even select folders. 
- You also have to use a hotkey to deselect anything to select again. 

This means the experience to append/link data is broken, and inconsistent right now. 

# Task 
Go through the Blender keymap and make the BFA hotkeys consistent in the filebrowser, just like in Outliner Main hotkeys similar or consistent with how the outliner should work in the BFA keymap. 

**Hotkeys to resolve:**

![bforartists_2020-05-21_11-13-51](https://user-images.githubusercontent.com/35357409/82581416-29437180-9b56-11ea-8f13-9a79570107a9.png)

1. L Click = turn off "open"and turn on "Deselect on Nothing"
_This fixes the the ability to select folders, instead of opening them, and allows to remove a hotkey to deselect things._

2. Shift + L click = turn off "open"
_This allows to select multiple folders without going into them immediately_

3. Change SHIFT + CTRL + L click = change to only CTRL + L click, then this can be either removed, and/or turn off "open". Change CTRL + L Click to F2. 
_Reason is, this is a double hotkey WITH a mouse, which is ok, but not really ideal. An alternative for this entry is just CTRL+L click like in the outliner, then change the Rename Folder/File to F2 to make it consistent with OS standards. Make sure the "open" is off._ 

![bforartists_2020-05-21_11-14-00](https://user-images.githubusercontent.com/35357409/82581404-25175400-9b56-11ea-8797-4103b38a8de8.png)

4. Add Double L click = to "open" any folder or file. 
_ This an OS standard to open files and folders, like in Windows. It opens doors to select multiple files/folders without opening the first one you select._

![bforartists_2020-05-21_11-15-53](https://user-images.githubusercontent.com/35357409/82581656-84756400-9b56-11ea-8527-3ac99838096b.png)

**Comment by ReinerBforartists** [comment]
So you mean we should fix the Blender keymap to work like in Bforartists and not like in Blender?

**Comment by Draise14** [comment]
The Bforartists one is broken. Blenders one is working better here.

**Comment by ReinerBforartists** [comment]
Ah okay :)

**Comment by ReinerBforartists** [comment]
Hm, Blender does not have Shift Ctrl Left Mouse. And we don't have double left mosue for select. Plus a few more inconsistencies. 

I will try to implement the Blender keymap here now ...

**Comment by ReinerBforartists** [comment]
Left a few hotkeys away. F2 is still under discussion for example. And a extra hotkey for refresh makes no sense when the refresh button is top UI anyways. But the keymap is now consistent against the Blender keymap.

Now let's fix the manual ...

**Comment by ReinerBforartists** [comment]
Manual updated here: https://github.com/Bforartists/Manual/commit/2253188a473a001d3391563744b374d069359de6

Closing. Fixed in master.
