### ISSUE TITLE
Hotkeys - F2 Rename and CTRL+F2 Batch Rename added to OS standards and ergonomics

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1566]
# Issue
Right now there is not default hotkey to rename and batch rename objects. In any operating system, you generally press F2 to rename. 

The renaming experience throughout the UI also is a little disjointed. 

![bforartists_2020-05-21_11-50-33](https://user-images.githubusercontent.com/35357409/82584437-1c288180-9b5a-11ea-9b64-5a8c617e91ab.png)

# Solution
So, I thought to make it a little more consistent, by adding in the F2 of the OS standard, to both the outliner, file browser and the general Window UI. I also added CTRL+F2 for the batch rename. I use this often, and having to go all the way to the other side of the screen to do this with a sub menu is very slow, specially if my focus is the outliner. 

**Gere are the changes:**
![bforartists_2020-05-21_11-50-33](https://user-images.githubusercontent.com/35357409/82584659-69a4ee80-9b5a-11ea-9543-768981cf8987.png)

- CTRL+Lcick to rename is generally either removed or changed to F2 where it works (Outliner and File Browser). 

- CTRL+Lclick to rename in the animation channels is removed, as it is redundant. 

- F2 and CTRL F2 for rename and batch rename are added to the Window hotkeys, so they are global and useable eg. in the outliner directly, similar to Blender

- Console view (F2) is changed to F5. 

**Conflicts to resolve:**
The console view should be set to a hotkey, it's currently F2. But F5 is free, and the start of a group of function keys. I thought it would be fitting to put it to F5, which is pretty obvious to know that functionality behind the inner workings of BFA is on a key that is in the top center of the keyboard.  

**Removals**
There is a double hotkey for the same operator in the Animation channels, so I suggest to remove one, the inconsistent one (the now stray CTRL+Lclick).

**Comment by ReinerBforartists** [comment]
I use F2 to call the console at Windows. This hotkey is occupied.

**Comment by Draise14** [comment]
I know it's your preference for the console editor, but it's not a strong argument... 

Most users use F2 more for renaming than using it to trigger the console, in many areas and different softwares, even entire OS's, it's a known and often triggered key. The Outliner has no entries to rename in the UI except in Data submenus, the 3D view has no entries to rename objects, and a batch rename as another key would be completely irrelevant to a known functionality in different software - it doesn't make sense.. 

This entry is only in the global header concerning UI, and it's far away from the 3D view, far away from the outliner. The suggestions is for global consistency sake and ergonomics, and putting the artists that would rename a lot first, over the dev who would need the console first, the console could be nearby with the F5 key.

**Comment by ReinerBforartists** [comment]
Hm. Not really. My argument is that i want to have as few hotkeys as possible. Bforartists useage happens with mouse and UI. Not by hotkeys.

**Comment by ReinerBforartists** [comment]
Hmhmmm. the Rename channels items in the Animation section seems to be a double. One of it can be removed then. But that's another task. Could you please split it? :)

**Comment by Draise14** [comment]
> 
> 
> Hm. Not really. My argument is that i want to have as few hotkeys as possible. Bforartists useage happens with mouse and UI. Not by hotkeys.

Not sure how the Renaming experience can improve if the mouse/ui version of renaming and batch renaming is really uncomfortable and unintuitive. Maybe if these operators were listed in the 3D View and in the Outliner, it would make sense to not add hotkeys, but right now.. in the global header?!

**Comment by ReinerBforartists** [comment]
The question is, how often do you rename items to really require a hotkey for it. Every two seconds?

You know the UI principles. As few hotkeys as possible. That's why i always struggle to add new ones without to think the consequences through :)

**Comment by Draise14** [comment]
I work with hundreds of objects per day sometimes, I rename most things to keep tidy as often as I can. When it comes to cleanup.. without the hotkey, it gets tedious. 

When working with bones, I work with rigs +50 or more bones per armature, each bone has to be renamed specifically, along with controls, shapes, etc. I use this a lot. Imagine needing to rename a blocked layout system after working on it, and you gotta cross the screen over and over to the submenu, or assign a random hotkey you aren't used to using that you'd have to investigate to be free, or stick it to the quick favorites and toggle the panel where you are, then hit the text only operator of a list who knows how long over and over again, or stick to only renaming with mouse in the outliner... 

Just... I changed this for my workflow, it has been helpful more so than the current UI options, I think it would be great to have as a default. It's a muscle memory system fortunately (windows F2 to rename, etc). 

I guess it's not that important. I know the philosophy is to go minimal with hotkeys, and allow the UI to do the heavy lifting, and user a way to assign the hotkey - which in consequence actually makes things MORE efficient as you know the software visually and mechanically, but sometimes a good default hotkey is a nice perk.

**Comment by ReinerBforartists** [comment]
Fixed in master

Moved the hotkey to call the console to F5. It's mainly a developer feature for me anyways. And now rename is F2.

The file browser main entry does not exist anymore, also not in Blender. But the F2 hotkey also works in the file browser with an object selected. So leaving it alone.

**Comment by Draise14** [comment]
Was batch rename also added? (CTRL+F2) I can't see it in the commit.

**Comment by ReinerBforartists** [comment]
Sure.

("wm.batch_rename", {"type": 'F2', "value": 'PRESS', "ctrl": True}, None),

**Comment by Draise14** [comment]
lol, last line I glanced over. Sorry. Cool man. I like this. I use these every day multiple times often.

**Comment by ReinerBforartists** [comment]
We slowly come to the workflow side of UI design, such things here are highly welcome. As long as it fits into the philosophy of course :)
