### ISSUE TITLE
Add a show / hide prop for the channel list in the view menus of the animation editors

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1569]
In 3D view you can show and hide the toolbar with the toolbar checkbox in the view menu. The animation editors have the channel list, which can also be hidden. The timeline starts with channel list hidden. And so you can easily overlook that this list is even available in the timeline.

The idea is to make the channel list panel at the left the same way hidable than the tool shelf in the 3d view. Would at least be more consistent. 

For now just an idea.

![channellistbyhotkey](https://user-images.githubusercontent.com/13919702/82759230-501ad580-9dec-11ea-84b9-30023558819f.jpg)

**Comment by ReinerBforartists** [comment]
Test, test ...

**Comment by ReinerBforartists** [comment]
:'3

![shownotfound](https://user-images.githubusercontent.com/13919702/115427257-9b5a8580-a201-11eb-9ecc-52aa08b2e5eb.jpg)

**Comment by ReinerBforartists** [comment]
:'3

![error](https://user-images.githubusercontent.com/13919702/115505330-8f120f00-a279-11eb-9184-a7e68ffc8579.jpg)

**Comment by ReinerBforartists** [comment]
=3

![fixed](https://user-images.githubusercontent.com/13919702/115509944-642ab980-a27f-11eb-83e5-f837bc3b57ff.jpg)

Fixed in master

Now you also know how this area is called ...

Needs work, needs update in the manual.

@iyadahmed , how's the work at the manual updates going? :)

**Comment by iyadahmed** [comment]
Pushing updates today

**Comment by ReinerBforartists** [comment]
Sorry for poking. It's normally not my style. Usually it is done when it's done. But in this case ... 

At least you know now why i am usually  a bit quiet at the beginning of the week ^^

**Comment by iyadahmed** [comment]
> Sorry for poking. It's normally not my style. Usually it is done when it's done. But in this case ... 
> 
> 
> 
> At least you know now why i am usually  a bit quiet at the beginning of the week ^^

Ah no worries, I agree it should be done quick

**Comment by ReinerBforartists** [comment]
WHERE IS MAH MANUAL O_O

@iyadahmed, when it becomes too much, then please tell me. Then i'll do this. It's no problem, i just need to know. To have the manual updated and committed is vital since i cannot go on as long as the updates are not there. And it needs to be fixed before the next merge.

**Comment by Draise14** [comment]
His ISP has restricted GIT flow just now, no repository was pulling nor pushing, meaning he was trying to figure that out yesterday and day before. Concerning the manual, maybe that work CAN be delegated.

**Comment by Draise14** [comment]
The Documentation tag helps know what needs updating, so I be can assigned anything, then go through the commit and check. A comment on where the chapter/section needs updating could also help make things efficient.

**Comment by iyadahmed** [comment]
> WHERE IS MAH MANUAL O_O
> 
> 
> 
> @iyadahmed, when it becomes too much, then please tell me. Then i'll do this. It's no problem, i just need to know. To have the manual updated and committed is vital since i cannot go on as long as the updates are not there. And it needs to be fixed before the next merge :)

I apologise sincerely for that, yep like Draise said I had some problems, spent time debugging

**Comment by ReinerBforartists** [comment]
So why don't you tell me then? :/

As told, when something is blocking, no problem. I am very open in this regards. And i know too well that sometimes life is cruel. And this is a volunteer task. So i force nobody to work when he don't want to. But i have now wasted three days with waiting since you promised to finish the task. Well, i guess we have at least learned a lesson here.

> The Documentation tag helps know what needs updating, so I be can assigned anything, then go through the commit and check. A comment on where the chapter/section needs updating could also help make things efficient.

As told in the other thread, that's not how it works. Going through the commits and then make an extra task for each little change costs even more time, and blocks the manual more for further edits. Since the manual is nothing where you can merge. When you work at the same document, then you will loose half of the work with the commit.

**Comment by iyadahmed** [comment]
> So why don't you tell me then? :/
> 
> 
> 
> As told, when something is blocking, no problem. I am very open in this regards. And i know too well that sometimes life is cruel. And this is a volunteer task. So i force nobody to work when he don't want to. But i have now wasted three days with waiting since you promised to finish the task. Well, i guess we have at least learned a lesson here.
> 
> 
> 
> > The Documentation tag helps know what needs updating, so I be can assigned anything, then go through the commit and check. A comment on where the chapter/section needs updating could also help make things efficient.
> 
> 
> 
> As told in the other thread, that's not how it works. Going through the commits and then make an extra task for each little change costs even more time, and blocks the manual more for further edits. Since the manual is nothing where you can merge. When you work at the same document, then you will loose half of the work with the commit.

I thought would be able to fix it, but it took too long, indeed my fault I should have reported

**Comment by ReinerBforartists** [comment]
Next time then. Lesson learned :)

Documentation comes with the next merge manual commit. Closing.
