### ISSUE TITLE
Timeline Sidebar - Cache panel - indent the cache types

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1572]
The cache types is a subset of all cache objects. So we should indent it visually like in this mockup here:

![timelinesidebar](https://user-images.githubusercontent.com/13919702/82807849-e69cd480-9e88-11ea-9886-2b8d872b8464.jpg)

**Comment by iyadahmed** [comment]
we should hide sub and triangle too right?

**Comment by ReinerBforartists** [comment]
Ah, yes, good idea.

**Comment by iyadahmed** [comment]
ok great

**Comment by ReinerBforartists** [comment]
Example code in case you want to align the triangle in the middle. I have done this in quite a few areas ....

```
        split = layout.split()
        col = split.column()
        col.use_property_split = False
        col.prop(my, "example_operator")
        col = split.column()
        if rd.use_border:
			col.label(icon='DISCLOSURE_TRI_DOWN')
			... add more content here
        else:
            col.label(icon='DISCLOSURE_TRI_RIGHT') 
```



With factor you can also do some more fine control 

`split = row.split(factor = 0.55)`

**Comment by iyadahmed** [comment]
oh I see, great
