### ISSUE TITLE
Camera clipping issues

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#158]
In world view you have a far clipping of 1000. In camera clipping you have a far clipping of 100. Crazy default.

Change the default to 1000 like the world view camera. 

Maybe we can also have a look to set the Reset value to this 1000 value. That's at the moment 0.

Change the label clip to clipping like in the properties editor.

Start and end is also no good term here. It is Far and Near clipping in every other 3d app. Not Start and End clipping.

![clippingissues](https://user-images.githubusercontent.com/13919702/38659653-b8a66c8c-3e2a-11e8-8cb4-08cfd4b7ba20.jpg)

**Comment by Draise14** [comment]
I somehow grew tolerant to this, and happy to see that you also found this annoyance. This would be great to make the same.

**Comment by ReinerBforartists** [comment]
Not to catch. I have located the prop. But adding a default like for the world camera in rna_space does simply nothing. The default stays nailed at 100.

![rnacamera](https://user-images.githubusercontent.com/13919702/38921564-60e6df06-42f6-11e8-9c6f-e96a69ac749c.jpg)

![rnaspace](https://user-images.githubusercontent.com/13919702/38921566-64170a34-42f6-11e8-9f5e-67373449d20a.jpg)


Postponing ...

**Comment by ReinerBforartists** [comment]
Let's have a second look at this.

**Comment by ReinerBforartists** [comment]
Gotcha. Fixed in master
https://github.com/Bforartists/Bforartists/commit/153822d4d0cc5e0468ba5766817338fa09cb141b

I was in the wrong file ...
The reset to default value was not to catch. That's another task then.

![clippingdefaults](https://user-images.githubusercontent.com/13919702/39241240-7bfd7a3a-4886-11e8-8864-39ca02a78d11.jpg)
