### ISSUE TITLE
Splash Screen - Add youtube quickstart playlist to splashscreen

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1581]
# Request
![https://i.imgur.com/JDjWhmh.png](https://i.imgur.com/JDjWhmh.png)

The youtube playlist for the quickstart videos are useful, but it would be nice to have them in a link in the splashscreen just like in help menu. 

![image](https://user-images.githubusercontent.com/35357409/83310330-453bb880-a1d1-11ea-8ef9-ab037c3f5be9.png)

**Comment by ReinerBforartists** [comment]
YIKES a double menu entry O_O

Will do ^^

**Comment by ReinerBforartists** [comment]
Fixed in master

![splashfixed](https://user-images.githubusercontent.com/13919702/83323324-45ce6080-a25e-11ea-8ff2-6741726b7ad8.jpg)

**Comment by Draise14** [comment]
Thanks for treating me! Yeah, it is a double, but the idea was from a Discord user and made sense I guess. Thanks again.

**Comment by ReinerBforartists** [comment]
Yes, one of those rare cases where it makes sense :)
