### ISSUE TITLE
3D View - Hidden Lock Rotation operator add to UI 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1584]
# Request
Right now, there is hidden operator to lock view rotation, which would be useful for locking orthographic rotations and GP pencil drawing modes. 

Here is an example bit of the code. 
[https://gist.github.com/Fweeb/bb61c15139bff338cb17](https://gist.github.com/Fweeb/bb61c15139bff338cb17)

# Task
Maybe adding and exposing this to the source might be a good idea? 

I think this could be similar to the camera lock button in the header, or just added to the view options as a toggle.

**Comment by ReinerBforartists** [comment]
Yes, this could indeed be useful. In the 2d drawing layouts one of the first things i did was to rotate the view out of orthographic. So a rotation lock would be very useful here.

**Comment by ReinerBforartists** [comment]
Fixed in master

![lockview](https://user-images.githubusercontent.com/13919702/108046445-e5c65700-7044-11eb-8da2-f9f1995dfd07.jpg)
