### ISSUE TITLE
Outliner - Missing SRNA 'outliner.collection_delete'

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1593]
# Issues
![image](https://user-images.githubusercontent.com/35357409/83921136-5e99b300-a743-11ea-9fbb-af563a9b988b.png)

The outliner and dev builds used to have two delete operators, one for collections and the other for objects. Now the operator is the one and the same. 

This causes an issue that hard crashes BFA ver 2.1.0. 

# Task
Review the code, and clean it up.

**Comment by ReinerBforartists** [comment]
The operator is now called outliner.collection_hierarchy_delete

Fixed in master
