### ISSUE TITLE
3D View - Sculpt Mode - ERROR (bke.modifier):

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1594]
# Issue
![image](https://user-images.githubusercontent.com/35357409/83932467-599b2a80-a768-11ea-8b9e-3fb375c8c233.png)

When going into sculpt mode, I get these issues in the console. 

# Task
Investigate why it's happening and add a fix.

**Comment by ReinerBforartists** [comment]
That's just the Blender way of implementing new tools in the tool shelf. Do it half arsed. Then deliver the missing bits like icons after a few weeks :)

This is nothing that we could fix. We need to wait for the Blender devs to deliver this missing icon. So closing this task.
