### ISSUE TITLE
Mesh Info missing from Status Bar

### ISSUE THREAD

**Issue by Faye3D** [Bforartists/Bforartists#1596]
The mesh info appears to be missing in 2.1.0. Adding the Info toolbar to the top header is also the same, only displaying the memory.

I tried both the Windows install and portable version.

![bforartists_info](https://user-images.githubusercontent.com/46456273/83950024-84948580-a81f-11ea-8887-be339382ed6c.jpg)

Thanks

**Comment by Draise14** [comment]
This is now located in the 3D view as a statistics toggle in the overlays.

**Comment by Faye3D** [comment]
Oh! Thanks for letting me know. That's actually loads better.
