### ISSUE TITLE
Toolbar -None type object has no attribute brush error

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1597]
No text. Console says it all.

![noneerror](https://user-images.githubusercontent.com/13919702/84000658-59b44980-a965-11ea-8dc2-9ed758b9fbbf.jpg)

**Comment by ReinerBforartists** [comment]
Hm, is with cloth filter brush in sculpt mode. And Dyntopo panel doesn't show neither.

**Comment by ReinerBforartists** [comment]
Okay, that's a Blender bug. Reporting ...

**Comment by ReinerBforartists** [comment]
https://developer.blender.org/T77606

**Comment by Draise14** [comment]
Ah, stumbled into this one but it refers to another file. Would this be a similar issue? 
![bforartists_j6aeGMeTjk](https://user-images.githubusercontent.com/35357409/88327445-ade47480-ccec-11ea-8c6c-0ecfac7d4ca5.png)

**Comment by ReinerBforartists** [comment]
Yes, that's the issue from what i can see.

**Comment by ReinerBforartists** [comment]
Long fixed. Closing.
