### ISSUE TITLE
UV Editor - Textools Addon - Error in Console

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1598]
I get the following error in the console when in the UV Editor. I am using the Textools addon. How do you troubleshoot this one?

> Error, region type 12 missing in - name:"Toolbar", id:23

Version **Bforartists 2.0.0**

**Comment by ReinerBforartists** [comment]
Screenshot please :)

**Comment by Draise14** [comment]
Ok, troubleshooted without the addon. I think this may now be a bug with my setup. 

When I switch to the UV layout, I get this twice... so.. I might have to rebuild my defaults startup. 
![bforartists_OPx1eJE8Gv](https://user-images.githubusercontent.com/35357409/84160771-2db3c980-aa34-11ea-9ced-284268d5405d.png)

**Comment by Draise14** [comment]
Fixed it by remaking the toolbar. It was missing an ID instance or something. Just removed it, instanced it again, and all good.
