### ISSUE TITLE
Global - Responsive double column layout for long lists in panels

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1604]
# Issue
![image](https://user-images.githubusercontent.com/35357409/84408619-f844e280-abd1-11ea-8cc0-35f6d8ebf52e.png)

Right now, the new right aligned list system with titles is nice and clean.. but it's very single column and no-longer responsive to how wide the layout is. They don't collapse to two columns when the layout has enough width. This adds to A LOT of scrolling, expanding and collapsing, and a lot of white empty unused space. 

# Research
Is this intentional? Or is there something broken? 

Can this be improved technically? 

# Task
Research if this can be improved, then make tasks to implement it in long lists (View Tab in the Properties Editor, eg)

**Comment by ReinerBforartists** [comment]
Not sure if jumping away checkboxes is really an improvement ...

**Comment by ReinerBforartists** [comment]
Proof ... 

![blender](https://user-images.githubusercontent.com/13919702/84415856-afae1900-ac13-11ea-968d-f89523b937bb.jpg)

**Comment by Draise14** [comment]
The far left align to all is better than the blender way, alteast it's now along an editor edge, but yeah.. there is SO MUCH WHITE SPACE. And scrolling...

**Comment by iyadahmed** [comment]
I think the solution might be to use a grid_flow, example is relations panel in object props, it adjusts automatically based on space

**Comment by ReinerBforartists** [comment]
Yes. That's one possible solution. But we could also get away with a simple layout.split() and two rows. Imho users rarely pull the properties editor fullscreen. But work with the current layout. A grid would be more elegant though :)
