### ISSUE TITLE
Node Editor - Cycles - Add Sky Texture to Node Input Tab

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1606]
# Issue
![https://i.imgur.com/SEBVlfQ.png](https://i.imgur.com/SEBVlfQ.png)
There is a new node in 2.8.2 that needs to be added to the Textures panel in the Properties Shelf in the Node Editor. 

# Task
Add the node to the panel. 
Make it dependant to the Cycles render mode, as right now.. it doesn't work with Eevee.

**Comment by ReinerBforartists** [comment]
The sky texture already exists. You even point at it. Sky will add a sky texture :)

Closing ...

**Comment by Draise14** [comment]
Ah, didn't see it. Sorry.

I wish the nodes headers had the same icons as the buttons.
