### ISSUE TITLE
Node Editor - Add nodes icons to node headers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1609]
# Issue
Right now, the nodes panels is awesome and has some great icons for the node types, but once you drag them into the node editor, they are visually disconnected. 

# Request
Is there a way to code in the same icon from the button into the headers of the icons? So you can collapse and rename icons, but still show what kind they are?

**Comment by ReinerBforartists** [comment]
The same problem exists with dragging them from the add menu. I had this problem before too. But the nodes are a very special beast. I have no idea what we can really change here.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/84581133-71dffa80-ada3-11ea-8124-85b07dc9df07.png)

Ok, found an addon that adds icons to the nodes of its editor. Might take a look into there.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/84581658-5546c100-ada9-11ea-840e-eedc0360c6b1.png)

![image](https://user-images.githubusercontent.com/35357409/84581666-642d7380-ada9-11ea-9176-8708c990ca8c.png)


I guess it's adding code to call icons in the node code, which I'll have to try dig and find in BFA. They listed a format code also, for colours and such, if BFA has it, then the icons could be called and added from there.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/84584022-2cccc000-adc5-11ea-8a59-d69fd895e37f.png)

Another addon that does it is Sverchok.

**Comment by ReinerBforartists** [comment]
Nice catch :)

**Comment by ReinerBforartists** [comment]
Ah, just as a side note, you can usually claim postponed tasks here too. Postponed just means that i will not touch them yet since my focus is at the manual. And when there is really a reason to postpone it in general, then i will point at it.

**Comment by iyadahmed** [comment]
progress :)
file in source/blender/editors/space_node/node_draw.c, the lead was that node group node had an icon
![image](https://user-images.githubusercontent.com/25552173/100546678-841ef980-325a-11eb-8dd1-4a8f66cec209.png)

**Comment by iyadahmed** [comment]
now we need to write cases for every node type, maybe we can have some sort of automation, but the easiest is to set icon per node type using if or switch case
![image](https://user-images.githubusercontent.com/25552173/100546743-e5df6380-325a-11eb-8db6-bdc4178741d5.png)

**Comment by ReinerBforartists** [comment]
Cool :)

**Comment by iyadahmed** [comment]
btw is Bevel node missing from node panels?, couldn't find it
will use bevel modifier icon for now I think

**Comment by Draise14** [comment]
Missing Bevel mode from panels could be a new task.

**Comment by iyadahmed** [comment]
indeed, will create a task

**Comment by ReinerBforartists** [comment]
Ah, a new node? Yes, that's a task then. We need to add new nodes manually to the sidebar. I'll make the task.

**Comment by ReinerBforartists** [comment]
Task created. And the bevel node is just fine for it.

Node Editor - add bevel node to the sidebar #2036
