### ISSUE TITLE
Right click menus and the old operators

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1610]
We have removed the old operators from the UI where there are the same operators in the tool shelf. 

The non contextual context menus still contains lots of these old entries. And i am honestly not sure what to do with them. They work different. So i would love to remove them to have a consistent UI. At the same time i promised to have the same functionality than Blender.

Needs further thinking.

Examples ... 

![editmodemesh](https://user-images.githubusercontent.com/13919702/84562745-2869be00-ad57-11ea-82b7-ea2490aec484.png)

![editmodemeshedgemode](https://user-images.githubusercontent.com/13919702/84562748-2dc70880-ad57-11ea-9717-cb8c72410dc0.png)

![facecontext](https://user-images.githubusercontent.com/13919702/84562749-30c1f900-ad57-11ea-9cdd-4958cbbff827.png)

**Comment by ReinerBforartists** [comment]
Oh, and we have some missing icons here again.

**Comment by ReinerBforartists** [comment]
Still no idea what to do here ^^

I would love to have a known issue section here. But Github just allows to have either open or closed issues ...

**Comment by Draise14** [comment]
**Option 1 (for repeat operators from the toolshelf):** 
Create a quick operator menu in the header (shows they exist) and rename them in right click. They are redundant operators, but they have no widget and they only act once, so another workflow, a "quick" workflow. From there we can still assign hotkeys if necessary and discover them. Leave the rest as is. 

**Option 2:** 
Re-organize the redundant ones to a "Quick Operator" section of the specials menu and the non-redundant ones similar to how the header is organized. No new entries in a header menu.

**Comment by ReinerBforartists** [comment]
Ah, but it's just about the entries in the so called context menus. What you mean is a completely different story :)

**Comment by Draise14** [comment]
... so what is this task about?

**Comment by ReinerBforartists** [comment]
The task is: Shall i leave them where they are for a while longer, or shall i remove them alltogether right now.

The far away goal is to make the old operators obsolete and to remove them from the UI. So that just the new operators in the toolshelf remains available.

I will postpone this task again. This is something for when we have managed to implement the tabs in the toolshelf again. Which can then become a place for the old obsolete operators.

**Comment by Draise14** [comment]
Keep them for compatibility with blender tutoriales and user request. 
 
I've had long and hard conversations in Discord with a few regular users of BFA about these and the general consensus is only organize or add. Don't remove features. 

I know they are the same. I know they are redundant. but I also know they act once then stop. unlike the toolshelf. 

We can justify changing them to "feel" different to not be redundant. but we can't justify removing.

**Comment by ReinerBforartists** [comment]
Then let's close this issue now
