### ISSUE TITLE
Memoryblock crash during autosave

### ISSUE THREAD

**Issue by Faye3D** [Bforartists/Bforartists#1615]
**The bug**
Bforartists 2.1.0, if using a modal operator during autosave I'm crashing every time.
edit: it also happens with autosave turned off

In cmd debug:

*Memoryblock free: pointer not in memlist*
*Memoryblock Chunk buffer: double free*

Reportedly this is fixed in a newer version of Blender 2.9 Alpha (rB67b17684e699)
see here: https://developer.blender.org/T77479

**Desktop:**
Windows 10 v1909
GTX 1080 Nvidia 441.41

Thanks for your hard work!

**Comment by ReinerBforartists** [comment]
Hi Faye3D,
Thanks for the report. We do a merge once in a week to import the newest changes from Blender. And so the fix will arrive in our builds soon. 

You can find the newest developer build in our download section. https://www.bforartists.de/download/#devbuild
Kind regards
Reiner
