### ISSUE TITLE
Bug - Crash on selecting objects in 3D View

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1626]
# Issue
When selecting and moving things in devbuild, I got this issue. It happened over and over again, till I changed selection, then I couldn't reproduce. This is the crash log it wrote to the TEMP directory I had. 

Version **devbuild-14.06.2020**

```
# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF6146A84B9
Exception Module      : bforartists.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000208


Stack trace:
bforartists.exe     :0x00007FF6146A84B9  Symbols not available

```

**Comment by ReinerBforartists** [comment]
I would need a way to reproduce this. Then we could start a debug. But without a way to reproduce this bug we have no chance to catch it i fear :(

**Comment by Draise14** [comment]
I'll see if I can catch it again.

**Comment by ReinerBforartists** [comment]
There are lots of crashbugs recently, even i experience them. But very random :/

**Comment by ReinerBforartists** [comment]
Blender has become much more stable lately. And i haven't experienced the random bugs as often as before. 

We have no way to reproduce this one, so let's close it.
