### ISSUE TITLE
Compositor, put backdrop navigation elements besides the backdrop options

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1628]
I find it cumbersome to have the navigation settings for the backdrop in the view menu. As a user i would not want to use it from there. I have learned the hotkeys instead. And this is against Bforartists useage philosophy of an easy discoverable and usable UI without hotkeys where possible.

It would be better when we could access this functionality right besides the big Backdrop button in the header. I am just not sure if i want to use a dropdown menu here, or place these four buttons as icon buttons besides it. Second would make more sense.

![backdropnavi](https://user-images.githubusercontent.com/13919702/85114804-e939e200-b21a-11ea-8f3b-8dff1d9938d1.jpg)

**Comment by Draise14** [comment]
I saw a dev in the Softimage Forums fork Bforartists to try make something like XSI with BFA (prefered this over Blender) and implemented some header buttons for the background controls. Makes sense. 

![image](https://user-images.githubusercontent.com/35357409/85137187-6870eb00-b206-11ea-9199-82081c403776.png)

**Comment by ReinerBforartists** [comment]
Good design will succeed ^^

**Comment by ReinerBforartists** [comment]
Forgot to ask, is this fork available somewhere?

**Comment by ReinerBforartists** [comment]
Oh look what we already have ...

![double](https://user-images.githubusercontent.com/13919702/101982114-03a4c380-3c72-11eb-8a75-9e7fbd2864f4.jpg)

**Comment by ReinerBforartists** [comment]
And we should imho hide the backdrop controls for colors and such. We don't grey out, we hide.

**Comment by ReinerBforartists** [comment]
Fixed in master

Catched quite a few doubles here. Now most of the needed functionality is at one place. And the tools are now hidden when you don't use a backdrop. Zoom and offset values are still in the Backdrop panel. But most of the time you don't need this fine control. 

![fixed](https://user-images.githubusercontent.com/13919702/114261910-48045e00-99dd-11eb-8a0c-692587530b2e.jpg)
