### ISSUE TITLE
Apply transform from toolbar fails with appended object

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#163]
.. but works fine with the apply menu item in the object menu. 
![applytransformfails](https://user-images.githubusercontent.com/13919702/38748751-6f4efa4c-3f4f-11e8-9293-65350ea5365a.jpg)

**Comment by Draise14** [comment]
I have ran into this bug. I found making a new toolbar or using a new layout fixes this issue from the toolbar.

**Comment by ReinerBforartists** [comment]
Hm. But should not work that way. I fear it's one of those tools that has to stay in the 3D view. But first let's find out what exactly is going on here.

**Comment by ReinerBforartists** [comment]
Curious bug. Appending seems not to be the problem. A simple sphere worked just fine. 

I need a case to reproduce this one. Maybe i  will go through the snail in forest scenes again. That's where i stumbled across it. But for now Postponing.

**Comment by ReinerBforartists** [comment]
Not to catch, not to reproduce. Closing.
