### ISSUE TITLE
Research - Check BforartistsXT (Softimage user fork of Bforartists) for ideas

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1633]
# Information
Re: #1628
> Forgot to ask, is this fork available somewhere?

This is a fork of Bforartists trying to incorporate UI and workflow ideas prevalent from the now EOL Softimage XSI. 

It is hosted in the [SI Community](https://www.si-community.com )forum and dropbox, though I have asked if he had it somewhere on github, apparently it's just local file changes mostly. It's mostly surface python level changes to some key UI files that are overwritten. I've been meaning to propose a couple of his ideas here for a while now, but keep been bogged by work. 

Here is the download and the two recent updates 
[The Original Version Bforartists XT](https://dl.dropboxusercontent.com/s/x1c7c6tqyd07s9p/BforArtistsXT%200.1.zip?dl=0)

[First Update](http://dl.dropboxusercontent.com/s/nethqvfcn87zuvu/BforArtistsXT-0.1_update3.zip)

[Second Update](http://dl.dropboxusercontent.com/s/lgnjku1ir0vxum6/BforArtistsXT-0.1-u4.zip)

To install, practially just extract the first link and overwrite the files in order with the other two links. I have not tested overwriting an original BFA extract. 

**Warning:** there are a lot more double entries that you'd probably not like, and I'm also not too keen. It bloats things somewhat - but other ideas are great. . 

But here are my key favorite ideas implemented:
1. - Sorcar, animation nodes and sverchok are already included, exponentially adding a lot of power to the defaults. 
2. - The View>View panel is much more organized and functional.
![image](https://user-images.githubusercontent.com/35357409/85156342-8eef5000-b21f-11ea-8215-d48a9ea95f67.png)
3. - The 3D View> view controls has a quick toggle for grid, wireframe and decorations (without turning off overlays). I think this is Genius and useful. 
![bforartists_Ve1lbfMdCg](https://user-images.githubusercontent.com/35357409/85156133-3e77f280-b21f-11ea-8a90-c450ec323c21.png)
![bforartists_GwJYjAQWZc](https://user-images.githubusercontent.com/35357409/85156139-3f108900-b21f-11ea-8084-2884f16a502d.png)
![bforartists_gtiiRYkyif](https://user-images.githubusercontent.com/35357409/85156140-3fa91f80-b21f-11ea-90ce-e59b3ea64cc6.png)
4. - Added quick editor toggles (similar to the Animation Editor Toggles) to all the node trees and image editors, which kinda makes sense and would be relatively consistent to implement. 
5. - Added a view layer system into the render settings, so the View Layers are not disjointed from rendering, which also makes sense. I also like how he set it up to work by fusioning the two systems - which Softimage was indeed good for. 
![image](https://user-images.githubusercontent.com/35357409/85156463-ba723a80-b21f-11ea-8f5f-b0ee68347e01.png)
6. - He made an interesting proposal to reorganize and separate the way the Properties Editor should be shown (eg. Object related and Scene related properties are in two seperate layouts, almost seperate editors). He did opt to keep the Active Tools tab with that logic in mind - like having and Object Properties Editor and Scene Properties Editor seperately.  
7. - Added a very great thing I miss from Softimage, which is 4 stored views in the 3D View Header with quick access. It has two rows of buttons, to store, and then the other row to select. It works with the Stored Views addon which might be modified. 
![image](https://user-images.githubusercontent.com/35357409/85156800-2f457480-b220-11ea-9e38-10f13fd9b90d.png)
8. He changed the order of the animation playback tools of the timeline - to something, in my opinion, to be more logical and consistent with other animation or video software. 
![image](https://user-images.githubusercontent.com/35357409/85157161-b561bb00-b220-11ea-8a3a-6c27476ea70c.png)

There are a few more other changes which are more.. akin to how XSI would work? Like hotkeys, splashscreen on load, render settings and view layer workflows (which I have to commend, feels a lot more useful than what we have - even attempts to expose more tools to the properties panel - something we've been wanting to do unsuccesfully, and I can't say the implementation in the properties shelf is great either (look at the UV Editor) - but some ideas are still great if you just look past all the double entries and other small things that don't align.  

# Feature Request
- Investigate mutually if there are some good ideas to incorporate to the BFA master
- If there are, go through features 1-8 (or more) and make tasks for them, check and see if they are reasonable and doable.
- Close this feature request and work on the separate relevant tasks made from these ideas.

**Comment by ReinerBforartists** [comment]
Thanks. Will download and have a look :)

You could make the single ideas where you think it is an improvement into a feature request when you find the time for. All at once is not to handle. And the more splitted it is the better it is to organize and to handle. We need to split the ideas into single issues.

**Comment by Draise14** [comment]
Sure, I can do that. I did not that as the request, so will do that.

**Comment by Draise14** [comment]
Did one, a few more to go, but have to get back to work.

**Comment by ReinerBforartists** [comment]
Thanks :)

**Comment by ReinerBforartists** [comment]
This is a all in one thread. And i think we have extracted the useful ideas already. Draise, in case you find further ideas, then please make one issue per idea ;)

**Comment by Draise14** [comment]
Sure thing.
