### ISSUE TITLE
NLA - sidebar - align checkboxes left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1635]
Left please ...

![alignleft](https://user-images.githubusercontent.com/13919702/85199120-777e9880-b2ed-11ea-9ca3-7bb4bb114b1c.jpg)

**Comment by ReinerBforartists** [comment]
:'3

![nopython](https://user-images.githubusercontent.com/13919702/85199636-5e77e680-b2f1-11ea-96c1-da14e7db545f.jpg)

**Comment by iyadahmed** [comment]
was fixed
![image](https://user-images.githubusercontent.com/25552173/98161418-645d1580-1ee8-11eb-9a85-f71fede57a77.png)

**Comment by ReinerBforartists** [comment]
Thanks :)

**Comment by iyadahmed** [comment]
No problem :)
