### ISSUE TITLE
Mesh - Select Through

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1636]
I am usually super careful not to implement too much C features since they can make trouble and break with every merge. But this feature seems so super useful - and is abandoned by the Blender developers. They once more don't see the value of the feature ...

We might need to change the one or another bit. The patch is already one and a half years old. And so i am not sure if we can get it to work at all. Lots has changed since then. But it is worth a try.

https://developer.blender.org/D6322

Discussion with more information: https://devtalk.blender.org/t/decoupling-x-ray-and-limit-selection-to-visible/3498/78

**Comment by ReinerBforartists** [comment]
Hm. We better wait a bit longer here. They have made another task ... 

https://developer.blender.org/T73479

**Comment by ReinerBforartists** [comment]
Bump. Shall we add this patch ?

**Comment by Draise14** [comment]
Ah.. this was declined? But still alright? If it's not too hard to add and.. maintain, sure. But this almost borders on a big feature, though it targets better UX. 

I would say yes, do it - if it's manageable and not too invasive in the code. 

If not... Maybe we can book mark these kinds of patches for later. It would be nice to get Blender patches in if they are great for UX and UI, but don't get approved by the Blender Foundation - this will drive potential developers here ultimately.

**Comment by ReinerBforartists** [comment]
It's not much work for me. The feature already works. I just need to add the code to our code base, and add the needed comments :)

Made it a task now.

**Comment by Draise14** [comment]
I'm excited to be able to use this.

**Comment by ReinerBforartists** [comment]
Hm. They still wildly discuss the other task. But who knows for how many more years they do. Let's have a look how the abandoned feature turns out. It's not this much code, and quickly removed in case they really implement another solution into Blender.

**Comment by ReinerBforartists** [comment]
First try failed.

Was a nice dream but the number of errors is a bit too high for my C fu. Too much changes since the original patch was released i guess, which we would need to correct first. **ar** is for example gone, and replaced by **region** ...

Unassigning. Maybe i will give it a second go at a later point. 

![toomanyerrors](https://user-images.githubusercontent.com/13919702/108831645-b5456680-75ca-11eb-9959-3d78aada1539.jpg)

**Comment by ReinerBforartists** [comment]
So, let's give it another shot ...

**Comment by ReinerBforartists** [comment]
>3

![battle](https://user-images.githubusercontent.com/13919702/109953647-a18fb380-7ce0-11eb-9da6-d16f8d6a4d85.jpg)

**Comment by ReinerBforartists** [comment]
There was a bracket missing. Mean mistake. Many thanks @naetherm for finding the trouble maker  :)

Now we are down to one error. Let's see what happened with the modifiers_getCageIndex variable. It is now undefined ...

![downtoone](https://user-images.githubusercontent.com/13919702/110086757-0e638600-7d93-11eb-9cad-9612e62ced22.jpg)

**Comment by ReinerBforartists** [comment]
Works. I love this patch already :)

Now let's fix the checkbox, which is currently middle aligned ...

![middlealigned](https://user-images.githubusercontent.com/13919702/110089872-eb3ad580-7d96-11eb-9c92-1f6252663c2d.jpg)

**Comment by ReinerBforartists** [comment]
Aand we have a select through \o/

**Comment by iyadahmed** [comment]
Amazing work 👌

**Comment by ReinerBforartists** [comment]
Thanks, but the work was done by one of the Blender devs. I just have applied it, and fixed a few small things to get it working in higher blender versions :)

**Comment by Draise14** [comment]
I like this trend, forgotten awesome patches that don't make it to Blender but can here... I think that's awesome, and very attractive for other devs.

**Comment by ReinerBforartists** [comment]
Everything is welcome in case you find something useful. But this example also shows that one minor version can make the patch implementation worthless already.
