### ISSUE TITLE
Dope Sheet - Quick toggles for keyframe visibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1651]
# Issue 
![image](https://user-images.githubusercontent.com/35357409/86404737-c3c6c280-bc75-11ea-8379-e9361bb94cdf.png)
Blender 2.83

![image](https://user-images.githubusercontent.com/35357409/86404958-261fc300-bc76-11ea-9dbf-f1721a0efc29.png)
Bforartists 1.0.0 

In Bforartists 1 and Blender 2.8+, there are quick toggles in the dopesheet that are now missing. 

The quick toggles were for show selected, show hidden and show errors. 

The first two we toggled a lot during animation. 

# Feature Request
Add these toggles back to the header like in BFA 1.

**Comment by ReinerBforartists** [comment]
They are in the filter menu now. I know it's one click more. But it's cleaner.

**Comment by Draise14** [comment]
I know they are there, but additionally to the additional click, it's another mouse movement. I have to either map to hot key or the quick menu to not burn time toggling selected by crossing screen space so often (not great solutions anyway). More often than not I have two dopesheets or fcurve editors open at once because it's now too much work to just quick toggle the filter when I need it. But this takes up much space, essentially lowering my quality of the animation unless I have two screens. I was wondering why I did this when in BFA 1 I never had to. This is why. We used those toggles a lot.

Can we have at least the most used selection and hidden toggles exposed to header just like x-ray and overlays toggles in the 3D viewport?

Show errors is not necessary to expose. We could minimize there.

**Comment by ReinerBforartists** [comment]
We will see. When you say you use it very often then it makes more sense to have them in the header.

**Comment by ReinerBforartists** [comment]
Toggles are now back in the header. The filter by methods are in the filter popup. In Dope Sheet editor the Filter prop just shows in the dope sheet mode. And hides in the other modes sinve there is no filter by method available anymore. 

![dopesheet](https://user-images.githubusercontent.com/13919702/98918938-877e5b00-24ce-11eb-998e-e9a02ea3ffcd.jpg)

![action](https://user-images.githubusercontent.com/13919702/98918949-8b11e200-24ce-11eb-9940-19433d6ce3fc.jpg)

![nla](https://user-images.githubusercontent.com/13919702/98918964-8ea56900-24ce-11eb-98f8-f65dca4a79d3.jpg)
