### ISSUE TITLE
Enable "Auto Depth" by default

### ISSUE THREAD

**Issue by MightyBOBcnc** [Bforartists/Bforartists#1657]
**Is your feature request related to a problem? Please describe.**
While navigating the 3D viewport, when the user zooms in a lot they will reach a point where they cannot zoom in anymore and the viewport's camera is 'frozen'.  The user cannot zoom in anymore, and they cannot pan the view either.

**Describe the solution you'd like**
There is already a solution built into Blender.  Open the Preferences and look at the Navigation section.  Enable "Auto Depth" and the user will be able to continue zooming and to freely navigate after lots of zooming as long as there is an object under the cursor.  

I propose that this checkbox should be **enabled by default** in Bforartists because it represents a better user experience than having it disabled by default (especially for satisfying new users who are trying out Bforartists after coming from other software).  It is more consistent with other DCC programs that zoom this way and it has been reported by other users as desirable.  https://devtalk.blender.org/t/zoom-to-mouse-position-auto-depth/7033

**Comment by ReinerBforartists** [comment]
Thanks for the idea. Sounds good. I'll have a look at it.

Please be patient, my main focus is currently at the manual. I'll investigate when the manual is done  :)

**Comment by ReinerBforartists** [comment]
Fixed in master
