### ISSUE TITLE
Allow "Scene View" to have equivalent operations as "View Layer"

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#1662]
Summary:  In the Layer view, there are operations to add/create/move/delete objects and collections.  It would be beneficial to have the same functions available in the "View Scene"

**Describe the solution you'd like**
Allow the operations available in the Layer view available in the scene view. 
Include operations for a Scene: create/duplicate/move (contents)/delete

![image](https://user-images.githubusercontent.com/57046940/87259179-40b82000-c45e-11ea-9c97-aed9280c7669.png)

**Comment by ReinerBforartists** [comment]
Not this easy. It's another level, and i seem to remember that this functionality is missing there for a good reason.

Let's investigate.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/87368095-50a93000-c542-11ea-9d8f-e76fa7e2a5a9.png)

I guess some controls on the view layers in the scene view of the outliner is the desired thing. Right now they only list. But this might have some core code limits...

**Comment by ReinerBforartists** [comment]
As told, i need to investigate here.

**Comment by slippystance** [comment]
Given my Adobe ways, I am coming at this from a layer-centric mindset.  So
I was hoping for something the same as Photoshop:

[image: image.png]
In the above, Layers are at the top of the hierarchy.  The contents of each
laver would be as visible as they are now in the Layer view in B4.  Please
ignore the placement of icons and functions.  I'm simply introducing the
idea that layer visibility and contents could be part of the Layer view.
This provides a strong compositional ability to B4.

**Comment by ReinerBforartists** [comment]
The image is unfortunately missing :)

**Comment by slippystance** [comment]
[image: LayerView.png]

**Comment by ReinerBforartists** [comment]
I think you have to post it here at Github and drag the image into the text field.

**Comment by slippystance** [comment]
Updated my post above.  Apparently right out of the box, Gmail and Github are not friendly where attachments are concerned.

**Comment by slippystance** [comment]
Updated image to better reflect concept

**Comment by ReinerBforartists** [comment]
Thanks :)

**Comment by ReinerBforartists** [comment]
Investigated. Scenes display mode allows to create new collections. So it makes sense to add the collections functionality to the header here too. Fingers crossed that it works out as expected.

**Comment by ReinerBforartists** [comment]
Fixed
