### ISSUE TITLE
Headers - Right Click menu should also show Area options

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1666]
# Issue
Right now, when you want to split or duplicate editor to a floating windows.. you have to go to the view menu. Not all editors have the view menu entry (eg. the properties editor). To duplicate it to a new windows, you have to duplicate the 3D view, then change it. 

Also.. the editor options are... hidden in the editor relevant view menus instead of in the rightclick designated editor menus (show-hide editor menus, etc). 

![bforartists_iFsvRF920M](https://user-images.githubusercontent.com/35357409/87345958-7f111600-c516-11ea-8a44-8f526ae86317.png)
This is the current global editor right click options, great... but not complete. 

![bforartists_IMWBy6wbGQ](https://user-images.githubusercontent.com/35357409/87345986-89331480-c516-11ea-8b49-9fd00b888a06.png)
These are the other editor options I would love to access in all editors, but they aren't in all editors. 

# Task
- Make these consistent, move or add the Editor "Area" options to the Rightclick header context menu for all editors. 
- Or just Add "Duplicate Area into New Window", "Toggle Fullscreen Area", "Horizontal and Vertical Split" to make it consistent
- Make the naming and iconography for the operators consistent between these two menus

**Comment by ReinerBforartists** [comment]
I would go the other route and remove Maximize area from the RMB menu. It's a double ^^

**Comment by Draise14** [comment]
So to access these editor operators where the view menu doesn't exist means a hotkey if these aren't in the header right click menu? 

_ hehe indeed I found a double. _

**Comment by ReinerBforartists** [comment]
The editor types without the view menu aren't meant to be maximized.

**Comment by Draise14** [comment]
I have needed them to be duplicated to another screen, often though. Eg, the property editor and outliner on the other screen. Right now, I have to open an editor that has this entry, duplicate it, then show the properties editor through a multi-step process.... another eg, to duplicate the toolbar instead of the entire instance of the window to the other screen for a new second screen layout, I'd have to do the same. 

If the Area menu is in the global header right click, it would also be nice to discover that I can globally split the editors no-matter if I don't know or can't see of the corner drag feature in the editors as a new user (a completely hidden feature disjointed in a editor view menu, not a global menu). It would make that experience a little more discoverable and consistent with the kind of operator it is, a global one for all editors like the right click menu on the headers. 

If not.. I guess I can just change the task to remove the double entry from the Rclick.

**Comment by ReinerBforartists** [comment]
Draise, you should know me good enough now. I decide when i claim the task. Not earlier. And my focus is still at the manual :)

But why is maximize area not enough? For what do you need full screen?

**Comment by ReinerBforartists** [comment]
Just stumbled across the context menu ...

![contextmenu](https://user-images.githubusercontent.com/13919702/87520416-39be2700-c683-11ea-82e5-ffc77a282dfe.jpg)

**Comment by Draise14** [comment]
looool, that's in the sidebar context menu?

**Comment by ReinerBforartists** [comment]
I told you it's a double :D
