### ISSUE TITLE
Node Editor - Compositing - same icon for Hue Saturation and Hue correct

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#167]
We have the same icon for two different tools. Hue Saturation and Hue correct. Needs a fix.

![sameicons](https://user-images.githubusercontent.com/13919702/38793963-9569de08-4153-11e8-87de-aa0c538e55f0.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/215425c24b54f6259c6e6903527bd0c16b4b633e


![huecorrect](https://user-images.githubusercontent.com/13919702/38806009-38960948-4178-11e8-9253-f77c4dd9cd84.jpg)

**Comment by Draise14** [comment]
Good fix. I use that node a lot too.

**Comment by ReinerBforartists** [comment]
Mh, is it even useful to have the two color panels separated? Or should it be one panel?
