### ISSUE TITLE
OpenCL GPU rendering Split Kernel error: failed to load_path_init

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1679]
Reported by an user. Seems that we have a problem with AMD cards with OpenGL cpu rendering. He gets a warning when trying to render with the GPU.

Split Kernel error: failed to load_path_init

The unfunny part is, the code is the same than in Blender. But Blender works for him, Bforartists not. And i cannot test it. I have a Nvidia card.

**Comment by Draise14** [comment]
I also have a Nvidias cards..

**Comment by ReinerBforartists** [comment]
We have been at least been able to reproduce the issue with opencl and cycles with gpu rendering. But i have no amd card, and so no chance to find out what goes wrong here.

**Comment by iyadahmed** [comment]
can the full blender-error.txt be provided?

**Comment by ReinerBforartists** [comment]
Same here. I cannot reproduce it, i don't have a ati card. And my ubuntu runs in a VM. 

The warning appears in the render window from what i remember. So there is no full error to provide. It's one of those Blender messages when something goes wrong. And this doesn't necessarily mean a bug in the code. It can also be a wrong driver.

I'll ask mnaether again if he can reproduce the problem.

**Comment by naetherm** [comment]
I could test on an AMD GPU, but unfortunately everything is working fine for me. An error-log would be highly recommended, including all releveant system information.

**Comment by ReinerBforartists** [comment]
Closing this issue finally since we cannot reproduce nor fix it. Sorry.
