### ISSUE TITLE
Properties Editor Pose Library panel - put apply button below list

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1680]
This Apply button should have a better icon ...

Or we put it below as a text button. Which would make more sense, usabilitywise. Or both ^^

![applypose](https://user-images.githubusercontent.com/13919702/87921790-58edf780-ca7b-11ea-8409-69e36e4332b6.jpg)

**Comment by Draise14** [comment]
Vote to make it a text button to apply, like the check marks of the modifier tools - list apply.

**Comment by ReinerBforartists** [comment]
Yes, is the better usabiltiy. And consistent with the rest of the UI then.

**Comment by ReinerBforartists** [comment]
Fixed in master

![applypose](https://user-images.githubusercontent.com/13919702/98239155-d163c000-1f67-11eb-81a7-25890300cab8.jpg)
