### ISSUE TITLE
Consistent right click

### ISSUE THREAD

**Issue by lcsondes** [Bforartists/Bforartists#1684]
**Is your feature request related to a problem? Please describe.**
As a new user I was frustrated by not being able to right-click in the large 3D view in the center despite it generally working everywhere else. Only after looking at the documentation did I learn that it's double right click there and only there, it never occurred to me to try that since nothing I know of ever uses double right click for anything. As far as I'm aware single right click doesn't do anything (it certainly seems like it) but dragging with the right mouse button does.

**Describe the solution you'd like**
Eliminate double right click and make single right click pop up a context menu. Right-button-drag would remain as is. This is similar to how Unreal Engine works.

**Describe alternatives you've considered**
Make any form of a right-click **or drag** a context menu (pretty much ignoring the dragging part) and leave camera rotation to the always-present X/Y/Z gizmo in the corner since it's next to other buttons that are also intended to be dragged around to move the camera anyway. This is similar to how 3ds Max works.
![image](https://user-images.githubusercontent.com/11299975/88058018-d177b580-cb5a-11ea-8f20-fa7a6e7421cf.png)

**Comment by ReinerBforartists** [comment]
Hi Icsondes,

Thanks for reporting.

We cannot return to this kind of calling the rmb menu, sorry. This collides with our rmb viewport navigation. Which has for me the higher priority over the rmb menu that i personally never use and don't even recommend.

But you don't have to use the Bforartists keymap at all. As an alternative, you could use the Industry compatible keymap. Or the Blender keymap.

You could also change the navigation by yourself. In the keymap manager search for the rmb entry for rotate. Change it to whatever you like. Then search for the context menu entries with dbl-right mouse, and change them back to rmb.

![keymap](https://user-images.githubusercontent.com/13919702/88076717-b1f08500-cb7a-11ea-952c-2c1a5b4c4ed4.jpg)

![rotateview1](https://user-images.githubusercontent.com/13919702/88076592-8e2d3f00-cb7a-11ea-9370-bdf48156d605.jpg)

![rotateview2](https://user-images.githubusercontent.com/13919702/88076737-b74dcf80-cb7a-11ea-929a-25633895e4d9.jpg)
