### ISSUE TITLE
Weird and unintuitive left-click behavior in the Outliner

### ISSUE THREAD

**Issue by lcsondes** [Bforartists/Bforartists#1685]
**Is your feature request related to a problem? Please describe.**
Add a cube to a new scene. Expand it on the outliner so it looks like this:
![image](https://user-images.githubusercontent.com/11299975/88070112-38e93180-cb6a-11ea-98ba-7a1e223f57c2.png)
Now keep left-clicking on each of the "Cube" words. Instead of moving selection back-and-forth between two different things, this will keep cycling through 4 different states:

1. Object mode with the cube object selected
2. Edit mode with the cube object selected
3. Same as 2. but now the top one appears to be selected on the Outliner but nothing is selected in the main 3D view
4. Object mode with nothing selected

Additionally, clicking the white triangle icon next to the bottom Cube in the Outliner switches modes between Object and Edit suggesting that it's a button, but the orange triangle icon next to the top Cube looks the same (even with a rounded rectangle border and highlight) but it's not a button. (Technically that highlight is there because it's the selected object, but if that's a highlight then don't make it _sometimes_ a  button) There are additional icons (an arrow, an eye, and a camera) to the right of this row that do not have borders but are clickable. This whole thing is a mess (and I'm aware that it's inherited from vanilla Blender, I'm only blaming them).

**Describe the solution you'd like**
Consistent behavior and intuitive looks. Clicking on the name of something should select it. If it's not selected (perhaps it's something that can't be selected?), the row should not get the blue highlight misleadingly indicating that the selection changed when it hasn't. Buttons should intuitively look like buttons and non-clickable icons/selection highlights should not.

**Comment by ReinerBforartists** [comment]
Hi lcsondes.

I'm a bit lost with your description at the moment. But what we have here is the exact same behaviour than in Blender. The top hierarchical name is the object name. This is the container so to say. The one below in the hierarchy is the mesh name. What is inside this containter. This container can contain much more. Materials for example.

You can select the object by clicking at the object name. When you open the hierarchy of the cube object, and click at the mesh part, then it enters the edit mode. To edit the geometry, the mesh, of this object type.

As told, this is Blender behaviour. And i don't see what we should improve here. It's more a communication problem than a UI problem really.

Kind regards
Reiner

**Comment by lcsondes** [comment]
I know that it's the exact same behavior as Blender, I thought the whole point of this project was to have a better UI. Anyway if you want to keep the vanilla Blender behavior there's nothing more for me to add, feel free to close this.

**Comment by ReinerBforartists** [comment]
Yeah sure, that's the point of this project. And i am open to anything :)

But i don't see the improvement here, sorry. The Blender solution is imho already consistent and good enough. 

For the icons, well, in the Outliner an icon is not necessarily a button. But an indicator what type of data you have here. How else would you display that?
