### ISSUE TITLE
Outliner - Hide Object Contents as a default. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1686]
# Issue
![bforartists_uE7FXwdUw3](https://user-images.githubusercontent.com/35357409/88081363-e433bf80-cb45-11ea-9d3b-5772367aec3b.png)

As reported here and in discord: #1685
Right now, the default outliner view layer system is a little novel and interesting for new users usually confusing when it comes to mesh data and more - adding functionality to what appears to be an object outliner principally. 

Other users have also reported that in normal workflows, they don't use this system a lot and have athis filter applied per default to keep work minimized and to the point: organize objetcs in collections. Having the object contents and mode toggles showing is generally an advanced user experience. 

# Task
Make Object Contents hidden in the filter by default. 

OR

Add this filter button prop toggle into the outliner header for a quick mouseover toggle to show-hide object contents and then default to hidden, so that it's quickly discoverable and adds to the UX that.. object contents is NOT the same as just objects - to avoid confusion and also imply advanced use of the outliner. 

# Debate
The issue with this is that for new users, it would make the default outliner experience streamlined and intuitive. But for advanced use, it might be a hidden feature. Unless we expose this directly into the header to make it clear that advanced use is available, but start minimal. 

The pro is... on first use and early in project management, you won't get bogged down by noise and mode toggles buttons that you might not use till you get to the stage of lookdev and renders. 

There was another suggestion of only showing object contents on active, and have all the rest hidden in the hierarchy, but that would be a Blender feature request and might not be too practical with multiple selections.

**Comment by ReinerBforartists** [comment]
Woah, dangerous feature :D

Let me sleep a few nights over this before i say no ^^

**Comment by ReinerBforartists** [comment]
A quick nap later ...

The pro is already the biggest con here. It is hard to make this features discoverable to the users again once it is hidden away. And this makes it a pro user feature. It is better for the pro users to hide this away in the cases where it is too much noise than for the beginners and intermediate users to find out that this functionality even exists.

So as sorry as i am. i have to decline this idea.

Closing.
