### ISSUE TITLE
Improve visibility of safe areas lines in camera view

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1690]
Safe area lines are nearly not to see when you activate the feature. In Blender it's even worse. Maybe we can improve the visibility of this lines. 

![safeareas](https://user-images.githubusercontent.com/13919702/88451977-4c8ee380-ce5b-11ea-9371-cef6fb58caf1.png)

**Comment by ReinerBforartists** [comment]
Same goes for the guides under Viewport Display. Nearly not to see with our and also the Blender standard theme.

![guides](https://user-images.githubusercontent.com/13919702/88461195-cd70ce00-cea1-11ea-81c3-71cc34750f9d.jpg)

**Comment by seanr** [comment]
I'm guessing these are set by the theme? On my Mac, at least, I have no trouble seeing them but I assume this would be a matter of just changing the defaults in the B4a theme?

**Comment by ReinerBforartists** [comment]
Probably. There are a few things that can't be themed this easy.

**Comment by ReinerBforartists** [comment]
Found it. This value is coupled to the View Overlay color in the 3d view theming section. But when we change this value then we change other things like the mini axis for the 3D cursor too. And i cannot say what the other things are. Hmm.

White looks good. But would this really be an improvement? The white could conflict with bright colors then. I need help here, i cannot decide ^^

Best would be to have a color dialog in the safe areas panel. But that's behind my skills.

![viewoverlay](https://user-images.githubusercontent.com/13919702/98223647-b5095880-1f52-11eb-8561-06dc68063754.jpg)

**Comment by ReinerBforartists** [comment]
Unassigning for now. Needs a bit more thinking.

**Comment by ReinerBforartists** [comment]
Hmmm. No matter if black or with white, you will run into situations where it does not fit. But we have a dark theme. And so white is the more logical choice to me. Let me sleep a night over this.

**Comment by ReinerBforartists** [comment]
Let's make it white. As told, we have a dark theme, and so the white color is the more logical choice.

**Comment by ReinerBforartists** [comment]
Fixed in master
