### ISSUE TITLE
Move Mist Pass settings from World Properties to View Layer Properties, Passes Panel

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1693]
When you want to have mist, then you go to View Layer Panels and turn on the Mist layer. Then you start to search for the settings ...

Put the Mist Pass settings to the Passes panel, as a sub panel. Saves searching.

![mistpass](https://user-images.githubusercontent.com/13919702/88456646-7b1eb580-ce7f-11ea-815c-af751899bd2d.jpg)

**Comment by ReinerBforartists** [comment]
I am alwasys surprised how something that looks this easy becomes mission impossible because the spaghettis goes from table to table to table ... -.-

Needs more investigation. Unassigning for now.

**Comment by Draise14** [comment]
Bizzare area to have it.

**Comment by ReinerBforartists** [comment]
Yea, and it is nailed. I cannot transfer it :D

**Comment by iyadahmed** [comment]
I think it is very doable, but there's a small problem, we have to edit Cycles addon
![image](https://user-images.githubusercontent.com/25552173/100544935-0aced900-3251-11eb-8e2b-77327a6baad5.png)

**Comment by ReinerBforartists** [comment]
That's no problem. We have quite a few modifications in the cycles addon already.

**Comment by iyadahmed** [comment]
ok great
