### ISSUE TITLE
Brush settings panel

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#170]
I hate scrolling. And so i permanently search for ways to improve the UI.

There are currently five tabs for brush settings that you need to open and to scroll into view. This could be one panel, with five buttons to switch between the settings. Much more compact, and faster to access.

This is an experimental task. And i will create an experimental build with it. When i can get it to work, and when it turns out to be useful, then we could have a look where else we could do the same to reduce the clutter. Of course in the other paint modes. But also for all the viewport settings in the properties sidebar.

![brushsettingspanel](https://user-images.githubusercontent.com/13919702/38802478-d4bbdcdc-416c-11e8-8caa-b19680b06808.jpg)

**Comment by Draise14** [comment]
Great experiment. Hope it works. Sounds.. complicated. Hope the CTRL+Scroll will make them switch on mouseover.

**Comment by ReinerBforartists** [comment]
I fear that will not be the case. I am not even sure how to do the tab menu. We will see :)

**Comment by Draise14** [comment]
The IK3D Sculpt Brushes addon has a "Show Options" panel with tick boxes, each tick box loads the content from the panels you want to condense in UI realestate, which you can toggle in and out (show/hide). It's not exclusive to one panel at a time, but maybe it can show you some code how to show/hide these options. 

You can find it in the addon tab>Show Options panel. 

https://www.youtube.com/watch?v=sZlD1rK-biI&t=209s

https://drive.google.com/file/d/0B-XHii26cfvWQ21zNDkxNWF1N28/view

Iconizing the toggles could make it cool, and adopting this might just be the quick solution and the hard part would be removing the other code bloat in the original UI and incorporating this one into the original.

**Comment by ReinerBforartists** [comment]
Thanks for the links. I'll have a look :)

**Comment by ReinerBforartists** [comment]
This will most probably go into the Blender 2.8 port. Postponing.

**Comment by ReinerBforartists** [comment]
That's a task for the Blender 2.8 series.

**Comment by ReinerBforartists** [comment]
This one becomes obsolete in 2.8. There the brushes are completely different solved. So it makes no sense to keep it active.

Closing.
