### ISSUE TITLE
Full Keymap - Property not found warnings in keymap item Operator Properties

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#171]
We have a bunch of property not found warnings in the new Full keymap.

![warning](https://user-images.githubusercontent.com/13919702/38821892-1a51f288-41a2-11e8-916b-98c938c48a26.jpg)

**Comment by ReinerBforartists** [comment]
>     ##Added from MayaSilo hotkeys, adding box drag select, shift select from top to bottom (doesn't work), and other standard features found in a number of software (added outliner features and improvements) - by Draise

Haven't we said that experimental changes should be a job for the experimental keymap? Now how much below the comment is change, and how much is original Blender keymap? :/

Removing at least the set_vsr ones. That's the ones that makes trouble. But that's just half of the show. Now let's try to find the other three rascals.

**Comment by ReinerBforartists** [comment]
Great. That's just around 200 possiblities or so :/

**Comment by Draise14** [comment]
The maya/silo are exclusive to outliner. We had them approved but its ok to move them to the experimental maps. The other added code is from the VSE transform tool in the Map Sequencer.  The rest is just Blender. I organized it that anything in a Map group can be removed below BFA code without issues and it's all commented. 

As mentioned earlier. It all still needs cleaning up which I can do with time. But I had these in for production sake. sorry for letting them slip.

**Comment by ReinerBforartists** [comment]
No problem. Now that the full keymap is in the repository we can at least hold everything under control :)

Do you have an idea where the other errors could come from?

And before i forget, you should always check the console output after a change. That's where you find such surprises here :)

**Comment by Draise14** [comment]
The first 7 errors there are 3 from Map Outliner and 4 from Map Sequencer (I think) They are addon based. I forget to disactivate add-ons on testing. With them on I get no errors. 

The last Type error I have no idea.

I should make a testing template with the right settings and default essentials.

**Comment by ReinerBforartists** [comment]
Yeah, always test with a blank installation. Hint, rename your bforartists folder in the appdata directory to something like bfa_old, then test, then rename back.

Could you be a bit more specific with the addon please?

**Comment by ReinerBforartists** [comment]
Properties not found errors are gone. Updated keymap committed in workflow branch:

https://github.com/Bforartists/Bforartists/commit/3e9c911e022279daaa28686a54a59065ddc91793

Remains the "ALL" error. This one's most probably somewhere in the text editor.
![allerror](https://user-images.githubusercontent.com/13919702/38860288-2905cd84-4230-11e8-961a-24a0a3d08087.jpg)

**Comment by ReinerBforartists** [comment]
Got it. Was in the Map Font category. font.delete with ctrl, type was set to all. But needed to be previous_word.

Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/1d6518772a2c25efd40314936204770f037717ca

No errors anymore. Closing.

**Comment by Draise14** [comment]
Oh good, glad you figured it out. I actually felt helpful this time, haha Go team!
