### ISSUE TITLE
Corrections to Home (landing page)

### ISSUE THREAD

**Issue by ErikPotsdam** [Bforartists/Bforartists#1713]
There are a few mistakes in the language in the Bforartists webpages. For now, I corrected a few things on the Home page (see attached PDF, .odt is not supported here :-( ).
Corrections are in green, words to be omitted in red with one strikethrough, and comments are in pink in square brackets.

 
[20200803_bforartists_web.pdf](https://github.com/Bforartists/Bforartists/files/5017515/20200803_bforartists_web.pdf)

**Comment by ReinerBforartists** [comment]
Many thanks. I'll incorporate the changes :)

**Comment by ReinerBforartists** [comment]
Some notes.  Bforartists is a complete free and open source 3D suite to create 3D content. This sentence should remain this way. It is a complete solution.

**Comment by ReinerBforartists** [comment]
Rearranged User Interface. Some things are better accessible now, some are not so much in the way anymore.
Einige Dinge sind jetzt besser zugänglich, andere stehen nicht mehr so sehr im Weg.

versus 

Rearranged User Interface. Some things are better accessible now, some are not such a big obstacle any more.
Einige Dinge sind jetzt besser zugänglich, andere sind kein so großes Hindernis mehr.

The first one is what i have meant. Sie stehen nicht mehr so sehr im Weg.

**Comment by ReinerBforartists** [comment]
>Bforartists is a complete, free and open source 3D suite to create 3D content. 

I have added a comma now, to make the sense more clear.

**Comment by ReinerBforartists** [comment]
Fixed
