### ISSUE TITLE
3D View - Header - Missing relations entries issue due to Library Override

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1720]
# Issue
![image](https://user-images.githubusercontent.com/35357409/89319765-3399e580-d646-11ea-874a-18319c81fcc5.png)

![image](https://cdn.discordapp.com/attachments/662282900691222528/740231506290671656/bfa2_2-4-0_feedback_menu_relation_missing.jpg)

Right now, the object>relations menu is broken and pulling an error, and thus it is practically empty. A user in Discord gave a detailed description of what's happening with the bug. 

Version: Bforartists 2.4.0

# Task
Fix the library override entry that's pulling the issue.

**Comment by ReinerBforartists** [comment]
Thanks for the report. Have you tested if the same happens in the newest Blender Alpha version? I remember that they wanted to remove the library overrides in favour of a new system. Maybe we see the first problems of it here.

Investigating.

**Comment by ReinerBforartists** [comment]
Should be fixed.
