### ISSUE TITLE
Corrections to Features Page

### ISSUE THREAD

**Issue by ErikPotsdam** [Bforartists/Bforartists#1722]
Please find some corrections in the attached PDF.
[20200804_bforartists_features.pdf](https://github.com/Bforartists/Bforartists/files/5030350/20200804_bforartists_features.pdf)
In the text, I used the same color code as last time: pink for remarks, red for words to be omitted and green for corrections.

**Comment by ReinerBforartists** [comment]
Thanks. Will incorporate them :)

**Comment by ReinerBforartists** [comment]
Fixed
