### ISSUE TITLE
Eevee - Transparent not working on render time

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1726]
# Issue
Right now with the devbuild-02-08-2020 and Bforartists 2.4.0, rendering Eevee with transparent on puts out no alpha. 

RGBA is set on the image file, Transparent is turned on - but it's still not doing the alpha. Alpha is solid. 
Composite has alpha setup, but even from the output node the Alpha is solid. 

I am getting no console errors.

![Image](https://i.imgur.com/30O7jEH.png)
![image](https://user-images.githubusercontent.com/35357409/89676173-cf2e8e80-d8b0-11ea-861d-7dd21aa23279.png)

# Task
Investigate why
Try Fix.

**Comment by Draise14** [comment]
Tested in latest 2.91 builds of Blender, same issue.

This is a really big eff up....

**Comment by ReinerBforartists** [comment]
So the bug is in Blender? Then you should report it ! And link it here then :)

**Comment by ferweer** [comment]
[EEVEE Film transparent not working](https://developer.blender.org/T79568)
Hi, I saw this bug report casually. maybe this bug is same too.

**Comment by ReinerBforartists** [comment]
Thanks ferweer, this seems to be the issue here :)

**Comment by Draise14** [comment]
Clement fixed it, was a single line of code... 
[Task](https://developer.blender.org/rB6a6cb83eb306d2b774ad2f029dc7beadc43bf28b)
