### ISSUE TITLE
Feature Request - Slow down the bleeding edge merges with Blender master for Beta branches only

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1727]
# Issue
![firefox_DP050vPvlF](https://user-images.githubusercontent.com/35357409/89677514-33eae880-d8b3-11ea-9f9e-62e6c6b83b3c.png)

Right now we are running the bleeding edge with official Bforartists builds based on Alpha development of Blender AND the LTS branches being merged in - I guess? (Bforartists 2.4.0 has Blender 2.91 Alpha + 2.83.4 LTS). I like the new features, but sometimes we get some really ridiculous bugs from Blender that puts up walls for production sometimes - and work and art depends on a bit of stability and features working with some pre-testing already done. Upgrading any official build of Bforartists is inheriting the Alpha and sometimes Beta bugs of Blender development, which puts a lot of frustration into every day work. I've had a couple of users like the bleeding edge features, myself included, but more often than not we have found some stability issues due to the Alpha nature of the code we merge in every official release. I've found myself using dev builds weekly hoping some Blender bugs are fixed in the alpha - which generally do get fixed, but sometimes they have bigger showstopping bugs or even addon incompatibility.

I know we merge in the Blender Master every week - which should be stable version of Blender by default. But I notice there are also branch versions for the 2.90 branch and a 2.83 branch. But no 2.91 branch (That's the master?) - is the Blender Master the WIP Alpha!?

From what I read in the forums, we merge in the Blender Master exclusively. I now assume Blender Master is the 2.91 Alpha release (I don't know why a Master would be Alpha), but there is a 2.90 branch in Beta. 

# Feature Request
Can we slow down merging in the the bleeding edge development of the Blender Master (the Alpha build) till they work out the kinks so we have a stabler version of Bforartists when we do official releases? - by merging in and using Branched versions either set as Beta or LTS? 

Eg. 
1. Never merge an **Alpha** branch, only **Beta** branches of Blender. 
2. Or only merge in branches that are official releases to the current day of Blender (eg, 2.83.4 LTS exclusively till they do an official release that's not beta? - though this is not great solution - we do still want bleeding edge feature sets...)

## Reason
- We still like the new features of Blender
- But we also need stability, preferably a Beta stability. 
- We want most addons to be supported still

![firefox_2qX59CungN](https://user-images.githubusercontent.com/35357409/89682317-2423d200-d8bc-11ea-9fef-d82d4c7fa8c1.png)

# Alternative
## Feature Request
Can we NOT release an official version every time Blender releases an LTS version (a 2.83 Branch version)? Only release when a new non-alpha or beta version of Blender is released (example, when 2.90 or 2.91 is official and/or no-longer Alpha or Beta)? 

- So we can develop from Master in a more casual way 
- So the dev builds can get more time to be tested before an official release of BFA
- So former releases get a bit more life as the new release cycle would be slower
- So that builds are based on no new features that are still Alpha.

**Comment by Draise14** [comment]
The only thing I see with this being irrelevant is that.. maybe the Blender master has the most amount of bug fixes and thus is technically the most stable version - even if it sometimes has a showstopping feature bug.

**Comment by ReinerBforartists** [comment]
The dilemma is not at our end. The dilemma is that the Blender devs have an unstable master. But i have no influence to their master. And as told, i miss the man power to maintain several branches. I work with the master. And release a new version when Blender releases a new version.

The Beta of 2.90 is misleading by the way. The master is now at 2.91 already.

The point is, i have promised to release a new version when Blender releases a new version. I can't break this promise. We would fall behind.

We can agree though that it is not wise to release a BFA release with every little LTS release. And i have in fact skipped one now.  Blender has released 2.83.4 LTS before two days, which would bring another 20 bug fixes - for the lts version. But who knows what bugs we will get from the master then. And so i have skipped it.

Either way, nothing to fix here. And i have heard you. So closing.

**Comment by Draise14** [comment]
Sounds alright, yeah.. slowing down the official releases to not go with the LTS cycles but the master release cycles I think is a good idea. Glad to hear. Thanks for listening.
