### ISSUE TITLE
Problems with Linux release versions

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1728]
Seems that we still have a problem with our linux release versions. ErikPotsdam has reported that he couldn't get them to work at Ubuntu 20.04 and Linux Mint.

>[This is not related to language, but none of these files worked for me on Ubuntu 20.04 and Linux Mint 20. I had to compile the program as described in the youtube video for Ubuntu 20.04. That worked just fine, but may be a little daunting for unexperienced users.]

**Comment by ReinerBforartists** [comment]
The devbuild opens fine in a vanilla Ubuntu 20.04. Let's have a look for the tar.gz release version

**Comment by ReinerBforartists** [comment]
And now i am baffled. The tar.gz version from Bforartists 2.2.0 also works just fine.

@ErikPotsdam, is there an error message? What exactly is failing?

**Comment by ReinerBforartists** [comment]
What i can see is that the folder for the tar.gz is Bforartists 2.90.0, which is incorrect. It should be 2.2.0. And it seems that the wrong version was used. Splash shows 2.1.0. Ah, Linux ^^

**Comment by ErikPotsdam** [comment]
When I download the .zip file; I can unpack it, but when I then double click on the program symbol, nothing happens, it simply remains inactive. The .deb file can be opened, and it seems to be installed in the software center, but then the program does not appear anywhere in the GUI, neither under "activities" nor in the software center in the tab "installed".
Contrary to that, I tried the developer build, and when I unzip it and click on the program symbol, bforartists starts as expected.

**Comment by ReinerBforartists** [comment]
Interesting. Thanks for the information. 

Hm, the release versions are compiled at Ubuntu 18.04 from what i know. But as told, the tar.gz version worsk just fine in a fresh installed Ubuntu 20.04

**Comment by ReinerBforartists** [comment]
Could you pelase try to start Bforartists from the console? That way we can catch console warnings that could give us a hint what goes wrong.

**Comment by ErikPotsdam** [comment]
I think I tried a while ago and got the message that bforartists was not found. But to be really certain, I need to try again. I am writing this message from another computer, on which I can't perform the test (The OS is Debian instead of Ubuntu, and though Ubuntu is based on Debian, I wouldn't make a bet they behave the same in this respect). I'll let you know ASAP.
One little detail I forgot to mention in my previous message: during the installation in the software center, the description of the software says "License: proprietary". That's not correct, I guess.

**Comment by ReinerBforartists** [comment]
Thanks for the hint. I'll have a look :)

**Comment by ReinerBforartists** [comment]
We have now a tar.gz version for Bforartists 2 2.4.0 available in the download section. SH, rpm and deb are still missing but under investigation.

**Comment by ErikPotsdam** [comment]
I tried the installation again. The .deb file does not work. The attached images illustrate the situation before and after the installation.
Before trying to open bforartists via command line, I tested the method with Libreoffice, and it started as expected.
However, the tar.gz file worked. The program started. If I remember correctly, the version was still 2.2.0, when I tried last time.
![2_after_installation](https://user-images.githubusercontent.com/69164432/89738091-49f4d680-da76-11ea-84da-1bcccfc2878d.png)
![3_after_installation_no_bforartists](https://user-images.githubusercontent.com/69164432/89738100-511be480-da76-11ea-9df4-bd8159b29430.png)
![4_command_line](https://user-images.githubusercontent.com/69164432/89738108-5711c580-da76-11ea-819c-e97377878d6a.png)
![1_before_installation](https://user-images.githubusercontent.com/69164432/89737938-4745b180-da75-11ea-9eaa-1a59f22d569d.png)

**Comment by ReinerBforartists** [comment]
Thanks for the pictures. Let's have a look if we can get it to work correct.

**Comment by naetherm** [comment]
@ReinerBforartists could you verify the behaviour regarding the licence with the new 2.4.0 version?
@ErikPotsdam ```bforartists``` should now be available from ```$PATH```, the information within the software center of Ubuntu will take a bit.

**Comment by ReinerBforartists** [comment]
The deb opens as an archive at double click at Ubuntu. It installs when i right click, and choose Software install.  But it does not appear anywhere then. As reported by Erik.

![stillbroken](https://user-images.githubusercontent.com/13919702/89757033-73e4e200-dae4-11ea-9cfd-d90ee4006948.jpg)

**Comment by ReinerBforartists** [comment]
Not found in the software list then, no desktop icon, no start menu entry, and the console does not find the software neither. It is installed though. There is this neat remove button here ...

![nobfa](https://user-images.githubusercontent.com/13919702/89757897-d8a13c00-dae6-11ea-8c76-c1e14bea2757.jpg)

**Comment by ReinerBforartists** [comment]
One step further. Works from the console now.

![stepfurther](https://user-images.githubusercontent.com/13919702/89760371-87944680-daec-11ea-9889-4235874f6bb4.jpg)

**Comment by ErikPotsdam** [comment]
My images were not displayed in the correct chronological order, but I hope my comments were helpful, nonetheless. I'll try the .deb file with the changes you have made.

**Comment by ReinerBforartists** [comment]
It is not changed yet. We still try to fix it :)

**Comment by ReinerBforartists** [comment]
Related commits: 

https://github.com/Bforartists/Bforartists/commit/04203af751e02821f63fa25759fd18170e05003a
https://github.com/Bforartists/Bforartists/commit/13bc50060757ad8368b9fc86aeb6d0ef8ffb610d

**Comment by ReinerBforartists** [comment]
The further fixes have added the icon to the software list. So the main problems seems to be solved.

However ...

![somethingwrong](https://user-images.githubusercontent.com/13919702/89866177-60eb1400-dbaf-11ea-9d65-46b6315f9f50.jpg)

And we have still a proprietary license ^^

**Comment by ReinerBforartists** [comment]
Proof that the software is in the list now. 

![inthelist](https://user-images.githubusercontent.com/13919702/89866534-01413880-dbb0-11ea-8bfe-435711716d11.jpg)

**Comment by ReinerBforartists** [comment]
License issue is not to catch. And we have still a problem. It does not appear in the ubuntu software center. But we are not even sure if this should be the case. 

Either way, tthe software installs. It is in the quickstart list, and can be removed with apt remove using the console.

**Comment by naetherm** [comment]
The licence problem within the software center is a well "known" problem, see all these issues (and other mentioned ones):

https://github.com/electron-userland/electron-builder/issues/4270
https://github.com/eez-open/studio/issues/48

**Comment by ReinerBforartists** [comment]
Thanks for additional information :)

@ErikPotsdam, i have updated the download before a few moments with a new created deb and rpm version. Could you be so kind to test if they work now as expected?

https://www.bforartists.de/download/

**Comment by ReinerBforartists** [comment]
Some further research reveals that the Ubuntu Software center will most probably not show any third party deb installations. At least that's how i have understood it. So there is little that we can do here. 

https://wiki.ubuntuusers.de/Ubuntu_Software/

**Comment by ErikPotsdam** [comment]
I made a quick test in my lunch break, and I found that the behaviour of the .deb package and the unpacked program is not consistent across the two latest Ubuntu LTS releases, 18.04 and 20.04. But I need to verify that again. I'll get back to you later with a detailed report.

**Comment by ErikPotsdam** [comment]
Ubuntu 18.04:

Installation of .deb file: proceeds as expected, bforartists shows up among the list of installed programs, when pressing Super+A, but it does not start when clicked

The command line "knows" that bforartists is installed, the program name is completed, when I type "bfor"+tab, but when pressing return, the progran does not start, and the following messages appear:

bforartists: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by bforartists)
bforartists: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by bforartists)

I removed the program with sudo apt purge bforartist and tried starting from the unpacked .tar.gz file.
The program file is recognised, but when double clicked, nothing happens. 


Ubuntu 20.04: 

Installation of .deb file: proceeds as expected, bforartists shows up among the list of installed programs, when pressing Super+A, and starts when clicked

Again, I removed the program to try the unpacked version.

After unpacking, clicking on the program file starts bforartists

Everything works as expected in Ubuntu 20.04! :-)

**Comment by ErikPotsdam** [comment]
I cannot judge, how much work it would be to fix the 2.4.0 version for Ubuntu 18.04, but if it can't be done, a hint on the website that 20.04 is required would not hurt.

On another day, I will also test the .rpm file, but to do so, I have to put another drive into my computer. I always try software on bare metal, not in virtual machines, because they sometimes exhibit strange behaviour.

But whatsoever:
Thanks a lot for all your efforts! Linux is often neglected, and I really appreciate that bforartists is available as a Linux version!

**Comment by naetherm** [comment]
Yes, AFAIK the given *.deb version was compiled with Ubuntu 20.04. 
Ubuntu 18.04 has an upper support limit of GLIB 2.27, so one should build an additional version for 18.04.

**Comment by ReinerBforartists** [comment]
Yes, compiled with 20.04.

It could be done, we could also compile a version with Ubuntu 18.04. But we would end in a version mess. One linux version must be enough.

Either way, thanks for testing. I will put a warning above the download :)

Case fixed. Closing. Thanks for testing and support.
