### ISSUE TITLE
Graph Editor - Snapping menu not obvious: add the Magnet icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#173]
![bforartists_2018-04-17_17-27-51](https://user-images.githubusercontent.com/35357409/38902104-ac75d554-4264-11e8-86c9-c95adf52988c.png)

There is a drop down menu that both me and an experienced Blender artist couldn't find after about an hour digging around. Documentation wasn't obvious, the UI wasn't obvious, and we even went to forums looking for help. Eventually it was hidden right under our nose in a drop menu in the header with no obvious marking or iconography. Once you know it, you know it.. but it was.. surprisingly frustrating to find it. 

I know the magnet is the snap tool for the 3D View, would it be possible to somehow add it to the dropdown or header to activate/tune the snapping for the Graph Editor?

**Comment by ReinerBforartists** [comment]
Good catch. I could have a look to add the magnet tool to the whole sub menu items.

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/708200d32c69f71d75ab2096c37205b8a4a5b0b1
![dopesheetsnap](https://user-images.githubusercontent.com/13919702/38915431-ec010a02-42e3-11e8-8e23-5f2a0931ef21.jpg)
