### ISSUE TITLE
Mark props with hidden content

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1735]
Long term issue.

We usually hide content away when a checkbox where this content belongs to is off. But currently you cannot see if a prop has child content when it is off. And there are cases where you cannot say what child prop belongs to what parent prop. We have a ton of sliders where you cannot say if this is a solitare setting, or if it depends of another prop.

I want to indent such properties that cannot simply put behind a checkbox. And i want to mark checkboxes with child content with a special letter. Just searching for the right sign here. A > could do the trick. Or an asterix. Or an arrow ->

Ideas?

![indent and sign](https://user-images.githubusercontent.com/13919702/89888950-1d090680-dbd1-11ea-9b9c-5e3c622c7da9.jpg)

**Comment by ReinerBforartists** [comment]
Hm, the tool name updates too with such a change. Difficult.

![toolname](https://user-images.githubusercontent.com/13919702/93300464-1b95b400-f7f7-11ea-99a4-3a94041ca2fd.jpg)

**Comment by ReinerBforartists** [comment]
Hmmm, what about a placeholder for the hidden prop. This would introduce move visual noise again though.

**Comment by seanr** [comment]
Is the idea here just to show that an item has hidden children? Any parent checkbox could have a ► icon to the right that when checked changes to ▼ with the items below it. I wouldn't do that just as a character in the title, but a UI icon or something that appears in every similar such circumstance so it won't appear in those tooltips.

**Comment by seanr** [comment]
Icons might be better as ▼ (to expand) and ▲ (to collapse). We need a "needs UX" label for stuff like this.

**Comment by ReinerBforartists** [comment]
Everything here is UI / UX :D

Yes, that would be the best solution. I was in search for an easier solution because it's unfortunately not as easy as simply showing an icon. And i wanted to avoid to make it one of the usual tabs since these tabs sorts at the bottom. And such tabs adds a second line. At the moment this prop shows content behind the first checkbox. But maybe we need to check this idea too.

More experiments ahead ^^

**Comment by ReinerBforartists** [comment]
Happy with this solution. The triangle icon behind the checkbox, middle aligned. I think we have a working prototype solution here.

Having the icon in Front would mean people thinks this is a subtab. And subtabs open with a click at the triangle button. I found myself clicking at the triangle button too instead of the checkbox. So no good solution. The triangle icon could also be at the right side. But that's too far away from the checkbox text then, it is visually out of the way.

![motrack1](https://user-images.githubusercontent.com/13919702/94784320-46266600-03ce-11eb-9515-2f8fb842a8ed.jpg)
![motrack2](https://user-images.githubusercontent.com/13919702/94784327-4888c000-03ce-11eb-8b51-c116a8213551.jpg)

**Comment by ReinerBforartists** [comment]
Separating the issue with indent the content. That's another task.

**Comment by ReinerBforartists** [comment]
Let's search for such props with hidden content ...

**Comment by ReinerBforartists** [comment]
Here we have one, with the checkbox at the wrong side too

![overscan](https://user-images.githubusercontent.com/13919702/94989225-79562a00-0573-11eb-9a35-1e370030f4b0.jpg)

**Comment by ReinerBforartists** [comment]
Fixed

![overscan](https://user-images.githubusercontent.com/13919702/94989950-ba047200-0578-11eb-894d-716abac74fed.jpg)

**Comment by ReinerBforartists** [comment]
Show margin in the text editor in the sidebar needs a triangle button.

![showmargin](https://user-images.githubusercontent.com/13919702/95103669-304dd380-0735-11eb-8256-e3fb0925e02c.jpg)

**Comment by ReinerBforartists** [comment]
Cycles, Sampling , square samples needs a triangle ...

![squaresamples](https://user-images.githubusercontent.com/13919702/95106910-76a53180-0739-11eb-8a72-fdcd4c94bace.jpg)

**Comment by ReinerBforartists** [comment]
Denoising panel one below has two props with greyed out content. And the checkbox belongs to the left side ...

![denoising](https://user-images.githubusercontent.com/13919702/95107201-e0254000-0739-11eb-9699-18e1e204b493.jpg)

**Comment by ReinerBforartists** [comment]
Output properties - Dimensions - render region

![renderregion](https://user-images.githubusercontent.com/13919702/95296081-73fd2600-0878-11eb-8a60-bed8eb302461.jpg)

**Comment by ReinerBforartists** [comment]
Output properties - Output - Transparent - Transparent glass

![transparentglass](https://user-images.githubusercontent.com/13919702/95296700-84fa6700-0879-11eb-8472-69f7329ed411.jpg)

**Comment by ReinerBforartists** [comment]
Mesh object - Object properties - Viewport Display - Bounds

![bounds](https://user-images.githubusercontent.com/13919702/95299794-8e3a0280-087e-11eb-9d63-66d821586a4d.jpg)

**Comment by ReinerBforartists** [comment]
Physics - Force Field - Falloff - min and max distance

![forcefields](https://user-images.githubusercontent.com/13919702/95301557-06092c80-0881-11eb-934d-b1c165abfd1b.jpg)

**Comment by ReinerBforartists** [comment]
Physics -  Cloth - Shape - Sewing

![sewing](https://user-images.githubusercontent.com/13919702/95303596-ae1ff500-0883-11eb-8e9e-2110f73d92ca.jpg)

**Comment by ReinerBforartists** [comment]
Phsyics - Fluid - Domain - Use adaptive time steps

![adaptivetimesteps](https://user-images.githubusercontent.com/13919702/95306457-bd08a680-0887-11eb-8a21-53c7f9441b9c.jpg)

**Comment by ReinerBforartists** [comment]
Rigidbody constraint - collisions - sensitivity - collision margin

![collisionmargin](https://user-images.githubusercontent.com/13919702/95310294-897c4b00-088c-11eb-8b69-dc416e1942d2.jpg)

**Comment by ReinerBforartists** [comment]
Rigidbody constraint - Breakable

![constarint](https://user-images.githubusercontent.com/13919702/95314430-93ed1380-0891-11eb-8ac6-ac31ad3b66f7.jpg)

**Comment by ReinerBforartists** [comment]
Object data - normals - Autosmooth

![autosmooth](https://user-images.githubusercontent.com/13919702/95315984-7e78e900-0893-11eb-9f8f-b3b3d745c08d.jpg)

**Comment by ReinerBforartists** [comment]
Material - Settings panel

![settings](https://user-images.githubusercontent.com/13919702/95321245-10382480-089b-11eb-80b3-25afcd658739.jpg)

**Comment by ReinerBforartists** [comment]
Image tab - Image panel- Sampling - MIP mapping
![mipmap](https://user-images.githubusercontent.com/13919702/95322489-dbc56800-089c-11eb-945d-f7878096c7cb.jpg)

**Comment by ReinerBforartists** [comment]
Camera object - object data properties - Viewport Display - passepartout

![passepartout](https://user-images.githubusercontent.com/13919702/95323910-3233a600-089f-11eb-9c53-6b296f8c91f3.jpg)

**Comment by ReinerBforartists** [comment]
Sculpt - Brushsettings - planetrim

![planetrim](https://user-images.githubusercontent.com/13919702/95358063-ebf33c80-08c8-11eb-91fe-f8486000b8ea.jpg)

**Comment by ReinerBforartists** [comment]
Pose mode - Tool tab - Pose options - X-axis mirror

![xaxismirror](https://user-images.githubusercontent.com/13919702/95360717-0f6bb680-08cc-11eb-9b44-d4c0e611b579.jpg)

**Comment by ReinerBforartists** [comment]
Hm, xaxis mirror is a bit more complicated. Auto IK on turns Relative Mirror off again since you can just have the one or the other. Let's have a look how Blender has solved it.

**Comment by ReinerBforartists** [comment]
Motion tracking - sidebar - stabilization tab - rotation+autoscale

![rotationautoscale](https://user-images.githubusercontent.com/13919702/95426853-ef2d0d80-0946-11eb-80ae-86f1b7da655d.jpg)

**Comment by ReinerBforartists** [comment]
I think i have most of them catched now. 

Calling this task done. We might still have props with hidden content. But we will fix them at a one by one base then.
