### ISSUE TITLE
3D View - Properties Shelf needs consistency with animate property buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1736]
# Issue
![ShareX_X4ujo3aRL8](https://user-images.githubusercontent.com/35357409/89942134-a3c5df80-dbe1-11ea-87e9-3d387a461b11.png)
Right now, when you animate things in the 3D View, you have to press a hotkey then use a floating menu to set a key. You have to also mouse over an entry then press a hotkey alternatively. You could use the properties editor that has animation buttons that you can click and slide to record without a hotkey or submenu, great.. but not great... it's not in the properties shelf and if I'm animating anything else in the properties editor, I can't access those buttons. 

Where animation is relevant, it's either hidden in a submenu or with a hotkey, a floating context menu, or with a double right click floating menu. It's bureaucratic. The properties editor has it right with animation buttons exposed beside the operator. The 3D View also needs an exposed method to just hit record on a mouseover. 

# Feature request
Can we also make the animation system consistent in the Properties editor and add at least the animation buttons to the transform controls under the item panel?

**Comment by ReinerBforartists** [comment]
This crap panel is C code ...

**Comment by Draise14** [comment]
Dammit... 

Yeah, they are crap panels...

**Comment by iyadahmed** [comment]
work in progress, matching location UI done,
![image](https://user-images.githubusercontent.com/25552173/97456131-3a807d80-1941-11eb-94b0-4e288375b381.png)

**Comment by Draise14** [comment]
So exciting!

**Comment by iyadahmed** [comment]
should we rename this issue to say like "remake view3d transform panel to match object prop transform panel"

or create another task?

as this is not only to make keyframe appear, but it will copy the behaviour of the object properties tab panel, and retain prober behaviour when in pose mode for example (because this panel is usable inside edit/pose/ etc.. mode as well)

here's example of old panel, it deactivates location if in pose mode and bone has a parent, we should hide instead I believe.
![image](https://user-images.githubusercontent.com/25552173/97463557-8aaf0e00-1948-11eb-8740-6928c555eba0.png)

**Comment by iyadahmed** [comment]
there's no issue in changing panel UI and keeping right behaviour, I'm asking if we should create another task or rename the old task

**Comment by Draise14** [comment]
I suggest splitting it up into smaller easier to manage and review/discuss tasks. Smaller the better. 

This task can focus on Object mode animation buttons as you're managing to do. The other topics could be other tasks just to be tidy.

But then again, if making the panel the same as the properties editor in behaviour and funcitonlality as the task.. we could just then rename this one. I think @ReinerBforartists should know what to do.

**Comment by ReinerBforartists** [comment]
Yes. We had already an extended task , and lots of fun with it ;)

Please make a new issue for everything that does not fit here into the original task.

**Comment by iyadahmed** [comment]
ok, great, I agree with splitting, having a "rewrite view3d transform panel" task, which includes animation seems to be the way to go, it will fix this task and addresses hiding instead of disabling

oh ok, was writing the above
should we rename it to "rewrite view3d panel"?

**Comment by ReinerBforartists** [comment]
Not anymore. Split it up i would say :)

**Comment by iyadahmed** [comment]
oh ok, creating an issue now
