### ISSUE TITLE
Filebrowser button - change Accept to Browse or Open

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1739]
Dunno what the Blender devs have thought here. The tooltip clearly says this button opens a file browser. It is no Accept button.

Change the tool name to browse or open or choose directory.

![acceptiswrong](https://user-images.githubusercontent.com/13919702/90111223-9f6b0500-dd4e-11ea-823d-8b1ac62fd0f7.jpg)

**Comment by Draise14** [comment]
God yes please.

**Comment by ReinerBforartists** [comment]
Fixed in master
