### ISSUE TITLE
Addon - FBX Batch Export is pulling an error, not reproduceable with Blender

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1741]
# Issue
A friend of mine has kindly made an addon to help with a workflow to batch export FBX files from each collection. It runs perfectly in Blender 2.83+ and 2.91+. But in Bforartists 2.0.0+ it pull an error, though it does execute. I would like some feedback and maybe some clues as to know why the a "Unit_Setting" of BFA is somewhat different to how Blender is doing it. 

Why do you think it's pulling the error when Blender doesn't? 

**The Addon "FBX Batch Export":**
[Github Repository](https://github.com/Twiggeh/BlenderAddon-Batch_FBX_Export/tree/master)

**The Test Scene**
[EXPORT TEST_01.zip](https://github.com/Bforartists/Bforartists/files/5070111/EXPORT.TEST_01.zip)

To reproduce:
1. Install and activate the addon
2. Open the scene
3. Run the operator under File>Export>Batch Export
4. Choose a location to export each collection content
5. Review the FBX files, and check if there is any error in the console or info editor

**The error Bforartists pulls:**

``` Python: Traceback (most recent call last):
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.91\scripts\addons\BlenderAddon-Batch_FBX_Export-master\__init__.py", line 43, in execute
    use_subsurf=True, path_mode='COPY', embed_textures=True)
  File "E:\3D stuff\Bforartists\Bforartists 2 - 2.4.0\2.91\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "E:\3D stuff\Bforartists\Bforartists 2 - 2.4.0\2.91\scripts\addons\io_scene_fbx\__init__.py", line 636, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "E:\3D stuff\Bforartists\Bforartists 2 - 2.4.0\2.91\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3261, in save
    scene.unit_settings.system = best_src_scene.unit_settings.system
AttributeError: 'NoneType' object has no attribute 'unit_settings'

location: E:\3D stuff\Bforartists\Bforartists 2 - 2.4.0\2.91\scripts\modules\bpy\ops.py:201



location: <unknown location>:-1 
```

**Comment by ReinerBforartists** [comment]
I have no idea what is different, sorry. And the error doesn't tell me something. It uses the Blender FBX addon under the hood, right? I usually care to keep the addons up to date, and equal to the Blender ones. So it should work.

I will have a look. Maybe i find something obvious. But i can't promise anything.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/90196408-4cff0800-dd91-11ea-9df7-0f09d4f9da33.png)

Ok, managed to reproduce the error in Blender finally, with some other objects and test scene. It's a 700mb one though, so not sure it's practical to share. So maybe it's the way it is doing it with some kinds of objects..

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/90197076-2f32a280-dd93-11ea-86a2-50096bd2632c.png)

Looks like removing these lines where the unit_settings is set will ah.. make it run correctly. This is a Blender issue in the FBX addon. How do we report this?

**Comment by ReinerBforartists** [comment]
Phew, gratulations for catching the baddie. And lucky me that i don't have to investigate here  :D

It's an official Blender addon. So you can report it like you would report a regular bug. I would not hang my hopes too high that they will fix it. But maybe you get at least an explanation what the units are good for.

**Comment by ReinerBforartists** [comment]
Problem long solved, no Blender bug report connected with this issue, and we don't maintain addons. 

So closing this issue :)
