### ISSUE TITLE
Toolbar - Add Revert scene to File group

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1746]
# Request
![bforartists_wsibbfAQsF](https://user-images.githubusercontent.com/35357409/90272836-9ac45080-de23-11ea-8673-65cda66b0c7f.png)

When doing layout and game development, but mostly layout, you work with a tonne of linked data. This is specially true in multi-user projects. So to update all the assets, you have to revert/refresh the scene often. Sometimes also, doing development on particular things and when the undo proves unstable or doesn't log heavy changes on particular data, a revert is nice. 

I use this a lot. 

# Task
It would be nice to have this also exposed in the toolbar for a quick mouse and click.

**Comment by ReinerBforartists** [comment]
Fixed in master

I have added the whole recover functionality as a group

![recoverfixed](https://user-images.githubusercontent.com/13919702/97776954-ccb89980-1b6c-11eb-8358-71b23a6c833a.jpg)
