### ISSUE TITLE
Make tooltip name equal UI name equal python operator name

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1753]
I stumble again and again across inconsistencies in the documentation. The worst case is when you have an operator name that is different from the tooltip name which is different from the name that this tool has in the UI. I have seen this too. How do you call this tool then? All three names are valid, dependant of where you look ...

Worst of it, which part to rename so that Blender users still knows what tool is meant?

This is a long term goal. And will first need some more thinking what to do here.

![differentnames](https://user-images.githubusercontent.com/13919702/90338948-85028700-dfed-11ea-9843-4e719e219d0d.jpg)

**Comment by ReinerBforartists** [comment]
Hm, changing the operator name would mean to break the Python api. It remains nasty ...

**Comment by Draise14** [comment]
I would recommend trying to keep the API as intact and similar to Blender as possible, but update the tooltip and the name of the UI entry to be the one and the same for consistency. 

Example with the  the example above:

**Ui Entry:**
Samplings Steps

**Tooltip:**
Sampling Steps

**API:**
effector_settings.subframes

## Reason
An artists may not even use the API, only advanced python able users. If the API is important, you'd look at the python code snippet anyway. 

If you want to keep documentation consistent, I would document, index and list the operator by the UI name, with the tooltip, and then list the API snippet below that entry in the documentation if necessary.

**Comment by ReinerBforartists** [comment]
Yes, that's probably the way to go. I will also keep my eyes open to find one of those examples where we have three different entries. And will post this then as a bug report to Blender. Maybe they are to convince to stop this babylonic language chaos.

**Comment by ReinerBforartists** [comment]
I will close this one as too general. We agree that we need to have the same tool name everywhere, but that the operator name can differ. The rest is keeping the eyes open and make a tracker issue once we find same tool with different name.
