### ISSUE TITLE
Addon - Default Bforartists Material VX error - Missing Libraries or Library Inconsistencies in the source

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1775]
# Issue
Error: missing libraries in Windows BFA 2.4.0 dev build 
![bforartists_phSV9w9AuL](https://user-images.githubusercontent.com/35357409/90907032-12502d80-e398-11ea-9b95-1f57007257c1.png)

Error - Linux Ubuntu BFA - 2.4.0 and a devbuild (reported from Discord)
- Libraries are showing, but they are pulling an error. Same repository. 
![image](https://user-images.githubusercontent.com/35357409/90907054-19773b80-e398-11ea-90e5-8feaa74f6af8.png)

It seems there are some library issues with the VX addon again. 

I have tried to deactivate and activate the addon to get the libraries to write, but with no success. My defaults don't load the libraries, and on linux builds of BFA, they are getting libraries but pulling errors. 

Something is wrong here....

**Comment by ReinerBforartists** [comment]
I will close this report now. Besides that i don't have any idea how to fix this, it is a Blender addon. And we don't maintain addons.

Maybe i stumble across a solution when i try to rewrite the addon to our needs. But no promises.
