### ISSUE TITLE
Cycles - Performance - Fixed Threads count extends beyond hardware limits - Check UX

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1776]
# Issue
In Blender 2.83 and BFA builds from a few months back, we had fixed thread limits increase beyond the core count, and if your PC was multithreaded you could take advantage of that. 

But now in 2.91+ builds, this thread limit is now is limited to CPU cores, and not threads. 
Example: 
1. Cycles CPU mode: you have an i7 with 8 cores, but then if you increase the thread count to 12, 12 tiles would render in Blender 2.83 and older versions of BFA. The thread limits are working as expected. 
2. Cycles CPU mode: in Blender 2.9+ and BFA 2.4.0 now with the same hardware, the thread count is capped at 8 threads = 1 thread per core. Even if you add more threads, it will still cap to 8 threads.  

The "fixed threads" naming is misleading, or now it is limited to cores and/or broken. 
![image](https://user-images.githubusercontent.com/35357409/90912219-d7ea8e80-e39f-11ea-81a6-fe355da6dbfc.png)

Ultimately, this adds a performance hit or cap on multi-threaded CPU's. It is also a misleading UX as if you wanted to take advantage of more threads, you wouldn't be able to even if the number extends beyond your core count. 

# Task
1. Check and see why older versions of Blender works with better multithreading, but 2.9+ is now limited to CPU cores instead of threads. 
2. Rename "Threads" and Tooltip information to be about "Cores" instead of "Threads" to reflect the hardware limits of 2.9+ versions of the source. 
3. If there is a feature inconsistency with the UX and indeed it should be about threads that are more than cores per multi-threaded CPU's, then this will need to be reported back to Blender to fix. (Blender 2.91 works the same as BFA 2.4.0 - so this is a Blender change)

**Comment by Draise14** [comment]
Reported:
[Blender Bug Report](https://developer.blender.org/T80080)

**Comment by ReinerBforartists** [comment]
Blender issue is marked as fixed. So we'll close this issue too.
