### ISSUE TITLE
Website - Devbuild link is broken

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1784]
# Issue
> Hey! Just a heads up, in case anyone wants to download the current developer build for windows.
> The current link to download the developer build for windows on the BforArtists' website seams to be broken. I noticed the current URL uses (dots) on its URL instead of "dashes".
> So a quick workaround to download for windows, on the URL bar, replace the (dots) to (dashes) so the download works again. :slight_smile:

> The correct link uses "dashes" instead: :slight_smile:
> **https://www.bforartists.de/data/dev/devbuild-23-08-2020.zip**

![image](https://user-images.githubusercontent.com/35357409/90987389-538b3d80-e550-11ea-875e-3e50137411e6.png)

Reported in Discord. 

# Task
Fix the link.

**Comment by ReinerBforartists** [comment]
Fixed. Thanks for catching this one :)
