### ISSUE TITLE
Can add v1.0.0 bforartist for linux?

### ISSUE THREAD

**Issue by ferweer** [Bforartists/Bforartists#1785]
Hi, Sorry for strange English.
I know nothing maintainer for linux on BFA. But i want v1.0.0 blender 2.79base bforartist for linux.
Can add Downloads to Bforartist 1.0.0 to download section?

I try compiled on ubuntu 18.04LTS. Can't compiled.
install_deps syntax error, So can't install.
`./install_deps.sh: 741: ./install_deps.sh: Syntax error: "(" unexpected`

And make update. >
`make update
if [ "linux" = "darwin" ] && [ ! -d "../lib/linux" ]; then \
        svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux ../lib/linux ; \
fi
if [ -d "../lib" ]; then \
        svn cleanup ../lib/* ; \
        svn update ../lib/* ; \
fi
git pull --rebase
fatal: not a git repository (or any of the parent directories): .git
GNUmakefile:427: recipe for target 'update' failed
make: *** [update] Error 128`

**Comment by ferweer** [comment]
And make>
`-- Could NOT find Boost
-- Could NOT find OpenImageIO (missing: OPENIMAGEIO_LIBRARY OPENIMAGEIO_INCLUDE_DIR) 
-- OpenImageIO not found, disabling WITH_CYCLES
CMake Error at CMakeLists.txt:913 (message):
  Cycles requires WITH_OPENIMAGEIO, the library may not have been found.
  Configure OIIO or disable WITH_CYCLES

And
`make full BUILD_CMAKE_ARGS="-U *LLVM* -D WITH_LLVM=ON -D LLVM_VERSION=6.0"` this is discover on forum.
`CMake Error at CMakeLists.txt:913 (message):
  Cycles requires WITH_OPENIMAGEIO, the library may not have been found.
  Configure OIIO or disable WITH_CYCLES

**Comment by ReinerBforartists** [comment]
We don't have a Linux version for Bforartists 1. And as sorry as i am, i cannot help you here. Bforartists 1 and all its required files and dependencies is not longer maintained. We are lucky enough that we managed to offer a Linux version nowadays. This OS makes us big trouble.

One thought. Ubuntu 18 is too new. You might have more luck with Ubuntu version 14 or 16. But no guarantee. And then you still might have some dependency trouble.

Kind regards
Reiner
