### ISSUE TITLE
Crash - Instancing a new toolbar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1786]
# Issue
![image](https://user-images.githubusercontent.com/35357409/91064825-660b8280-e5f5-11ea-9f92-aa8338e84ee2.png)
When I create a new toolbar (split 3D View, then toggle the tool settings, then switch to toolbar editor) I get an Exception_Access_Violation. 

I have removed config setup, tested to see if it was my layout, preferences, or just a factory install. It is reproducible. 

**Crash Report:**
[blender.crash.txt](https://github.com/Bforartists/Bforartists/files/5118808/blender.crash.txt)

**Build:** devbuild-23-08-2020

**Video Example:**
[Video on Youtube](https://youtu.be/iT7eFfSw7xo)

**Comment by ReinerBforartists** [comment]
Confirmed. Very unfunny -.-

**Comment by ReinerBforartists** [comment]
Fixed in master.

Blender devs did a refactoring. We missed a change here.

**Comment by Draise14** [comment]
I'm very glad we slowed the release cycle since we can only work from the one Blender Master, these things can be squashed quick, thanks for the fix. Looking forward to the next dev build! Almost tempted to build this one myself.

**Comment by ReinerBforartists** [comment]
Just do it, it's not this hard :)
