### ISSUE TITLE
Topbar - error message with hotkey ctrl + spacebar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1787]
Pressing ctrl + spacebar in the topbar area pulls an error.

![ctrlspacebar](https://user-images.githubusercontent.com/13919702/91069311-89eeb880-e635-11ea-9446-eddfc0ec80b0.jpg)

**Comment by Draise14** [comment]
Do you think this has something to do with the other bug?

**Comment by ReinerBforartists** [comment]
Nope :)

**Comment by ReinerBforartists** [comment]
Fixed in master
