### ISSUE TITLE
Add menu entries for the available pie menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1789]
We have several pie menus. But the user has no way to find out that they exist. We need entries for them in the regular menus somewhere. 

![piemenu](https://user-images.githubusercontent.com/13919702/91150028-2196ea00-e6bc-11ea-8926-b1c238cc8840.png)

**Comment by Draise14** [comment]
YES! Please. I was going to suggest this one, but wasn't sure how to suggest it... so didn't. Being able to see pie menus in the UI to make it easier to add hotkeys to them if anything.. AND much easier to discover them. It would make life that much easier. Glad you are thinking of it.

**Comment by ReinerBforartists** [comment]
View menu seems a good place to me. It exists in nearly every editor.

**Comment by ReinerBforartists** [comment]
Not this much than thought.

![pie](https://user-images.githubusercontent.com/13919702/97541058-cbe50380-19c4-11eb-82e1-b28d1b985571.png)

**Comment by ReinerBforartists** [comment]
Ah, there is much more. We just have removed most of them in the BFA keymap.

![morepies](https://user-images.githubusercontent.com/13919702/97542263-bf61aa80-19c6-11eb-8a05-222714bc94b7.jpg)

**Comment by ReinerBforartists** [comment]
The ones in the python menus

  VIEW3D_MT_object_mode_pie,
    VIEW3D_MT_view_pie,
    VIEW3D_MT_transform_gizmo_pie,
    VIEW3D_MT_shading_pie,
    VIEW3D_MT_shading_ex_pie,
    VIEW3D_MT_pivot_pie,
    VIEW3D_MT_snap_pie,
    VIEW3D_MT_orientations_pie,
    VIEW3D_MT_proportional_editing_falloff_pie,
    VIEW3D_MT_sculpt_mask_edit_pie,
    VIEW3D_MT_wpaint_vgroup_lock_pie,
    VIEW3D_MT_sculpt_face_sets_edit_pie,
	
	
    IMAGE_MT_pivot_pie,
    IMAGE_MT_uvs_snap_pie,
	
	CLIP_MT_pivot_pie,
    CLIP_MT_marker_pie,
    CLIP_MT_tracking_pie,
    CLIP_MT_reconstruction_pie,
    CLIP_MT_solving_pie,
	
	DOPESHEET_MT_snap_pie,
	
	GRAPH_MT_pivot_pie,
    GRAPH_MT_snap_pie,
	
	NLA_MT_snap_pie,
	
	GPENCIL_MT_snap_pie

**Comment by ReinerBforartists** [comment]
Two more from the Blender keymap

	wm.toolbar_fallback_pie
	view3d.object_mode_pie_or_toggle

**Comment by ReinerBforartists** [comment]
Fixed in master

![piemenus](https://user-images.githubusercontent.com/13919702/97551479-52a0dd00-19d3-11eb-94b6-806f6158e9ce.jpg)
