### ISSUE TITLE
Move menu entry for Toggle Quad View upwards

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1790]
While going through the list of hotkey only tools i stumbled across the hotkey for quad view. Ctrl Alt Q. 

It has no menu entry anymore from what i can see. We need to readd it.

**Comment by ReinerBforartists** [comment]
Ah, wrong alert. It exists. 

Hm, would it be useful to have it top level UI? Or is it disturbing?

**Comment by Draise14** [comment]
Move it up one level. I would use it if I knew where it was (much quicker than making new editors or splitting them.. 3 times). This is very 3D View Editor related exclusively, so having it in the global Area menu doesn't make too much sense.

**Comment by ReinerBforartists** [comment]
Indeed. We will see. It would make sense to add it to the quick navigation buttons. And to move it one level up iun the View menu too.

**Comment by ReinerBforartists** [comment]
Separating the task with adding the button to the addon too.

**Comment by ReinerBforartists** [comment]
Fixed in master

![quadviewfixed](https://user-images.githubusercontent.com/13919702/97433009-1f037b80-191d-11eb-805e-30c051818c96.jpg)
