### ISSUE TITLE
Outliner - Remove hotkeys E and Alt E to disable and enable collections.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1792]
Nonsense Hotkey. A Blender fragment. You need to have the collection selected. And in this case it is easier to simply click at the checkbox instead of clicking at the collection and press E then.

![eandalte](https://user-images.githubusercontent.com/13919702/91199408-22e90680-e6fe-11ea-9c16-8b3fa34ff55d.jpg)

**Comment by Draise14** [comment]
Man, all these hotkeys really are odd. No I completely understand what you were on about minimal keymap. I don't discover hotkeys, I discover a UI. I then can assign - but only if it's more efficient. If it's directly there, then why use the hotkey? 

Remove sounds like a good idea.

**Comment by ReinerBforartists** [comment]
Fixed in master
