### ISSUE TITLE
Outliner - Remove hotkeys Ctrl D and Ctrl Alt D for add and remove driver

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1793]
There is no content in the outliner where you can add drivers too. Usually you do this to checkboxes and sliders.

But better investigate a bit more here.

**Comment by Draise14** [comment]
I use drivers on render and viewport visibility often. But I usually use the Right Click context for that. Anything animatable can have a driver.

**Comment by ReinerBforartists** [comment]
So we should keep this hotkeys? Okay, closing. Thanks  :)

**Comment by Draise14** [comment]
Nah, it's in the right click menu - minimize and remove. Never used these hotkeys.

**Comment by ReinerBforartists** [comment]
Hm. 
Hmm hmm. Lemme reopen this and sleep a night over it :)

**Comment by Draise14** [comment]
Another thought, these driver hotkeys in the Properties Editor, eg, would still be there and are set like these. If the outliner removed them, then it might be an idea to also remove them from the Properties Editor and elsewhere that can take drivers (properties shelf, properties editor, etc). 

Or.. just leave as is. It's not that invasive to keep them.

**Comment by ReinerBforartists** [comment]
Yes this is my thought too. They don't hurt. And so i might close this issue here again ...

**Comment by ReinerBforartists** [comment]
Wasn't this issue already closed? O_O

Closing ...
