### ISSUE TITLE
Crashbug with shading workspace

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1794]
Very curious bug. Crash to desktop with clicking at the  Shading tab.

I compile a debug build, all works. I compile a release build, we get a crash to desktop. Now go figure. I would need the debug build to find out what causes it ...

**Comment by ReinerBforartists** [comment]
Hm, i was able to crash the self compiled blender version too. And it also crashes at the shading 2d workspace.

**Comment by ReinerBforartists** [comment]
Updating the Blender build now in hope that they have fixed the crash meanwhile.

**Comment by ReinerBforartists** [comment]
Still crash with blender. Okay, let's clone the repo to another drive, to have a clean environment

**Comment by ReinerBforartists** [comment]
@Draise14 , could you please download the latest devbuild, click at the Shading tab and tell me if it crashes for you too? I need to know if it is my PC or a more general problem.

**Comment by ReinerBforartists** [comment]
Okay, merging the newest master from Blender seems to have fixed the problem. Further testing ahead.

**Comment by Draise14** [comment]
Testing

**Comment by Draise14** [comment]
So far so good. No crash.

**Comment by ReinerBforartists** [comment]
Thanks for testing. I declare this one as fixed.

**Comment by Jackle4Foxy** [comment]
I have the same problem with Bforartists v 3.4.1 both when attempting to open the shading tab & when attempting to create a shader in the materials tab...

**Comment by ReinerBforartists** [comment]
Hey Jackle4Foxy, 

Could you please make a new bug report. This one is closed, over two years old, and very unlikely to be the cause for your problem. Even when it sounds familiar :)

Kind regards
Reiner
