### ISSUE TITLE
3D View - Default addon View Align Navigation, is this a double entry? 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1795]
# Question
![bforartists_Fat1JuI1mt](https://user-images.githubusercontent.com/35357409/91211510-83634e00-e6d4-11ea-817a-4a5a2e229cdb.png)
Bforartists has a view widget AND view toggle buttons in the 3D View header. 

I personally use the widget most to tap into snapped views, or use the ALT+Middle Drag to change a view snap. 

I am wondering, are these UI entries double entries? 

What is the benefit of one over the other? Why both? 

Both require a mouse over and a tap. If I want to inverse the view, I just tap again on the widget, or move the mouse a little on the button rows and tap again. Is one supposed to snap orthographic and the other not? Or are they BOTH tied to auto perspective toggling or both preserve the orthographic toggle all together? 

I know this is a default of BFA, yet I have put my own defaults to keep it turned off - and I've seen some youtubers review Bforartists and comment on this double entry - so now I'm just wondering, is this a double entry?

Shouldn't we have the default start with one or the other turned off? 

# Task
1. I can see this NOT being a double entry if the View Align Navigation snapped to orthographic like the little houses in the icons and that the group also had the view reset button (super useful from BFA1) - so I can keep the 3D widget as a Perspective View Align Navigation (and then not have them both as a double entry) - can we add these features to this addon? 
- View Align Navigation switches to orthographic snapping
- Perspective and view Reset button added

2. Or... can we just hide one or the other 3D view navigation snapping systems by default?

**Comment by ReinerBforartists** [comment]
I think i explained before why i have implemented this one. I was never able to proper navigate with this widget with one click to my needed view. With the buttons i can. But the widget shows the orientation. Which the buttons doesn't. And so both have their use.

Reset 3d view could find its way into this block. It was never part of this addon though. The perspective button, hmmm. This would be a double then. Same functionality already exists in the widget.

**Comment by Draise14** [comment]
Ah ok. Yeah, the perspective button is not necessary. Just the reset one. 

Can the View Align Buttons go to orthographic when you use them? And the view widget stick to perspective or whatever node you're in?

**Comment by ReinerBforartists** [comment]
Unfortunately not. I have never managed to get this to work.

**Comment by ReinerBforartists** [comment]
Question is answered. I don't see a job here, so closing.
