### ISSUE TITLE
3D View - Sunlamp Shadow with Cascade Shadows at 2048px glitches

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1797]
# Issue
![image](https://user-images.githubusercontent.com/35357409/91342524-cab71080-e7a0-11ea-853a-b97adb0f1570.png)
1. Create a large plane (2000m, eg)
2. Add a sunlamp and rotate
3. Set Cascade shadows to 2048px or higher in the Render Properties in the Shadow panel
4. Shadows will glitch. 

You may need to switch editors to trigger the glitch. 

This wasn't true of earlier builds. This might be a blender bug. 

# Task
- Investigate why
- Investigate if it's a Blender issue and report

**Comment by Draise14** [comment]
This was introduced this week, btw.. last week it was fine.

**Comment by Draise14** [comment]
![blender_KJwjbYL4m9](https://user-images.githubusercontent.com/35357409/91343981-e6bbb180-e7a2-11ea-9a6b-69cd2bbb5e7f.png)

Ok, tested it in todays devbuild of 2.91 of Blender. Works ok.

**Comment by Draise14** [comment]
I'll update my drivers.

**Comment by ReinerBforartists** [comment]
I'll do a merge before the final release anyways. Chances are that we get this fix then too.

**Comment by Draise14** [comment]
Latest dev build fixed this.

**Comment by Draise14** [comment]
Oops, tested not deeply. Yes, still there, 2048px on sunlamp cascade shadows still causes the bug. 

Happens only after switching a workspace, first open it's fine.

**Comment by ReinerBforartists** [comment]
I hope you have reported it :)

**Comment by Draise14** [comment]
![blender_N59xQsbEXN](https://user-images.githubusercontent.com/35357409/91778779-2cb8b100-ebb9-11ea-8983-58334eb791b1.png)

Ok, tried on the latest 2.91 build (blender-2.91.0-68797982025c-windows64), no problem. So it's now ok in Blender, but not in BFA. Maybe in the next dev build or merge.

**Comment by ReinerBforartists** [comment]
I will do a merge now for the release version. So the fix should hopefully arrive in BFA too.

**Comment by Draise14** [comment]
Ok, awesome! Fixed with the new release and merge - thanks Reiner.
