### ISSUE TITLE
Toolbar - Add View Dropdown selected to Misc group

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1798]
# Request
![image](https://user-images.githubusercontent.com/35357409/91365794-9b67ca00-e7c7-11ea-8bd8-da9d111612e3.png)

In heavy compositing driven rendering, I flick and change through view layers a lot. Having a few per character, etc. I would need a quicker way to work around changing view layers, and having them exposed optionally in the toolbar like the scene switcher might be handy. 

Add the View Layer dropdown as an option to the toolbar in the misc channel.

**Comment by ReinerBforartists** [comment]
Fixed in master

![viewlayer](https://user-images.githubusercontent.com/13919702/97420578-c677b280-190b-11eb-9a87-c4b5accce7fb.jpg)

**Comment by ReinerBforartists** [comment]
Ah, shows by default. Needs a fix.
