### ISSUE TITLE
Update problem with changing images in trexture paint.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1799]
Reported by a user. When changing images in texture paint, then the image does not update. In Blender 2.83.5 lts it does.

See here: https://www.3d-board.de/thread/35184-bforartists-2-version-2-4-0/?postID=322188#post322199

**Comment by Flytronik** [comment]
Error from debug

Warning : Trying to set parameter on a texture not bound.
./bforartists(BLI_system_backtrace+0x26) [0xab0dc83]
./bforartists(_BLI_assert_print_backtrace+0x16) [0xaa6bc47]
./bforartists(GPU_texture_update_sub+0xe3) [0x9e757bb]
./bforartists(GPU_texture_update+0x54) [0x9e7611d]
./bforartists() [0x3fdd873]
./bforartists() [0x3fde020]
./bforartists() [0x3fdeb89]
./bforartists() [0x3fe227f]
./bforartists() [0x3fe24f0]
./bforartists() [0x351dafb]
./bforartists() [0x351f414]
./bforartists() [0x351f623]
./bforartists(wm_draw_update+0xc5) [0x351fc48]
./bforartists(WM_main+0x48) [0x351c819]
./bforartists() [0x30ee7a4]
/lib64/libc.so.6(__libc_start_main+0xea) [0x7f2412f2a34a]
./bforartists(_start+0x2a) [0x30ee18a]
BLI_assert failed: /home/holger/bin/Bforartist-dev/Bforartists/source/blender/gpu/intern/gpu_texture.cc:1492, GPU_texture_update_sub(), at '0'
Abgebrochen (Speicherabzug geschrieben)

**Comment by Flytronik** [comment]
Ein build von Blender 2.91 ergab das hier Blender das Problem hat nicht Bforartists.

**Comment by ReinerBforartists** [comment]
Danke :)

Ich mache den hier mal zu. Du hast das Problem ja auch selber gemeldet.
