### ISSUE TITLE
3D View problem in shading mode

### ISSUE THREAD

**Issue by Flytronik** [Bforartists/Bforartists#1800]
Ich muss das Fenster vergrößern um keine Anzeigefehler zu bekommen. Das ist bei allen Reitern so. Ich muss die Anzeige auf eine gleiche Größe ziehen wo die Seitenverhältnisse gleich sind, dann geht es.

![Screenshot_20200828_193819](https://user-images.githubusercontent.com/70403462/91600653-a4dc6800-e968-11ea-9c50-fe8dd3c6daa0.png)
![Screenshot_20200828_193847](https://user-images.githubusercontent.com/70403462/91600663-a73ec200-e968-11ea-8b54-c7e64f35c206.png)
![Screenshot_20200828_194147](https://user-images.githubusercontent.com/70403462/91600671-aa39b280-e968-11ea-8e4b-3d24697d95e3.png)
![Screenshot_20200828_194639](https://user-images.githubusercontent.com/70403462/91600676-ac037600-e968-11ea-805d-65113006b26c.png)

**Comment by ReinerBforartists** [comment]
Danke für die Meldung. Aber was genau ist hier der Anzeigefehler? :)

**Comment by Flytronik** [comment]
Sobald ich das Fenster verkleinere sehen die Modelle alle weiß aus wie in den 3 Bildern drunter. Im Editmode ist nichts mehr zu erkennen. Arbeiten nicht mehr möglich.

**Comment by Flytronik** [comment]
Ein build von Blender 2.91 ergab das hier Blender das Problem hat nicht Bforartists.

**Comment by ReinerBforartists** [comment]
Ah okay. Die Anzeige wird also weiss. Vielen Dank dass du da auch noch mal mit Blender gecheckt hast. Da kann ich dann natürlich nicht viel tun.

Hast du das Problem bei Blender gemeldet?

**Comment by Flytronik** [comment]
Nein habe ich nicht.

**Comment by ReinerBforartists** [comment]
Wärst du so lieb? :)

Das geht von Blender aus. Aber lass besser die Bforartists Screenshots weg. Sonst machen die den Report gleich wieder zu ^^

**Comment by ReinerBforartists** [comment]
Nachdem für uns hier leider nichts zu fixen ist mache ich hier mal zu. Danke noch mal fürs melden :)
