### ISSUE TITLE
Mac about screen pulls the Blender version number instead of the Bforartists version number

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1803]
Reported by seanr in his pull request Add release files for Darwin (Mac) build. #1801

Wrong version number ...

<img width="308" alt="91602041-a55d0a80-e938-11ea-804d-f7e6b8286fa3" src="https://user-images.githubusercontent.com/13919702/91667380-80b58e00-eb04-11ea-90b6-92d49b9ec073.png">

**Comment by ReinerBforartists** [comment]
Possible fix. Waiting for somebody to test ...

**Comment by seanr** [comment]
Just saw this, will test tomorrow (well, today really, but after sleep 😄 ).

**Comment by ReinerBforartists** [comment]
Sweet dreams :)

I really hope this is it ...

**Comment by seanr** [comment]
Confirmed working.
