### ISSUE TITLE
BFA only uses low resolution splash image due to upstream change

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#1805]
**Describe the bug**
In https://developer.blender.org/D6999 the splash screen was reconfigured to just used a single image, scaled appropriately  at run time. Additionally, in some later commit, the splash_2x.png code was removed altogether, so it only uses splash.png. We are thus only serving the low-res image for BFA now.

**Desktop (please complete the following information):**
OS-independent.

**Screenshots, Example Files**
Hard to make out, but this is pixelated on a Mac Retina display:
<img width="507" alt="Screen Shot 2020-09-04 at 4 34 48 PM" src="https://user-images.githubusercontent.com/199713/92282928-ae1b8680-eecc-11ea-8b00-1e2a4ced1c02.png">

**Comment by seanr** [comment]
The commits above (combined) make both images the same size. I'm not sure that's the right approach elsewhere, but it is correct on Mac. Interestingly, the code actually doesn't reference splash_2x.png _anywhere_ (full search  of the codebase yields nothing), but when I had that removed I got some pretty horrid graphics glitching so I restored it.

Here's the updated splash screen:
<img width="509" alt="Screen Shot 2020-09-04 at 5 24 47 PM" src="https://user-images.githubusercontent.com/199713/92285935-998ebc80-eed3-11ea-8710-9cb20f8f3aac.png">

**Comment by seanr** [comment]
One more quick followup - that 2x image does not exist in the official Blender repo: https://developer.blender.org/diffusion/B/browse/master/release/datafiles/

**Comment by ReinerBforartists** [comment]
Reopening. I will have a look to remove the splash2x.png ...

**Comment by ReinerBforartists** [comment]
And good catch. Thanks. This one slipped through :)

**Comment by ReinerBforartists** [comment]
Removing the splash2x.png works flawless. No errors. Compiles fine. And no graphics glitches. I have compiled from scratch though. Maybe you still had it in the cmake cache somewhere, causing conflicts.

**Comment by ReinerBforartists** [comment]
Fixed in master
