### ISSUE TITLE
Graphics glitches startup Blender

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1808]
I have spotted a graphics glitch here. I have seen this with Bforartists before. But now i have seen it in Blender too, and was able to make a screenshot.

Some icons and the splash screen is missing. I needed to restart Blender. And with the restart the missing graphics came back.

Not sure what causes this. Maybe my graphics card is getting retired. Or we have a bug here.

![blenderglitch](https://user-images.githubusercontent.com/13919702/92299683-f9797780-ef54-11ea-90b5-a2b492cecd93.jpg)

![blenderglitch2](https://user-images.githubusercontent.com/13919702/92299690-026a4900-ef55-11ea-80b8-f2d36e6dbe06.jpg)

**Comment by ReinerBforartists** [comment]
Reproduced with a fresh downloaded buildbot build. Reporting ...

**Comment by ReinerBforartists** [comment]
Task created https://developer.blender.org/T80488

**Comment by ReinerBforartists** [comment]
Not funny. This is Bforartists 2.5.0 ...

![glitchy](https://user-images.githubusercontent.com/13919702/92302627-ea52f380-ef6d-11ea-846a-85df8ed95f91.jpg)

**Comment by Draise14** [comment]
This also is true of Blender 2.91 builds. 
[Glitch on Twitter with Blender](https://twitter.com/rileybrownart/status/1301188380458328065)

**Comment by ReinerBforartists** [comment]
Yes i know. My report is already merged ^^

**Comment by Wikinggaffa** [comment]
I encountered similar glitches. 
I had FreeCAD open when I decided to hop into bforartist and there was no glitching. 
I then tested closing both programs and opening bforartists only. -Yep glitches where back. 
Opening FreeCAD first and then bforartists seems to solve the glitch for me :-)

**Comment by ReinerBforartists** [comment]
Curious ^^
The glitch happens pretty random. So chances are that it has nothing to do with each other. But who knows :)

I wait for the next point upgrade of Blender. Then the glitch should be gone. Haven't experienced it in the last Dev build so far.

**Comment by ReinerBforartists** [comment]
Glitches are solved. Closing this task.
