### ISSUE TITLE
Improve Weightpaint workflow

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1809]
Weight painting has become pretty cumbersome in Blender 2.8x. In 2.79 you did not need to select the skeleton too to be able to switch the bones in weight painting. 

And it was possible to pose the armature in weight painting from what i remember. 
Now you need to 

leave the weightpaint mode, 
select just the armature, 
switch to pose mode, 
set the pose, 
go back to object mode, 
select armature, 
shift select the mesh, 
switch to weightpainting.

And then you can finally go on with the weightpaint task. It's too much steps. Maybe we find a solution to improve this workflow.

**Comment by ReinerBforartists** [comment]
As optimistic as i was, i don't see a way to pose the armature in weight paint mode since we have the mesh selected. We have no access to any transform of the armature then.

Closing this one as won't fix.

**Comment by Draise14** [comment]
I just hit this problem just now... 

`Tool 'builtin.move' not found for space 'VIEW_3D'`

**Comment by Draise14** [comment]
Found the solution, the legacy operator transform.translate that was W (debated to be CTRL+W now) allows to pose without changing modes. 

![image](https://user-images.githubusercontent.com/35357409/130830858-a66ac899-705e-4ead-a1c6-0eeea54d7066.png)

This was the old Blender transform hotkey G that did this.
