### ISSUE TITLE
can you set exact measures of lines ?

### ISSUE THREAD

**Issue by Wikinggaffa** [Bforartists/Bforartists#1817]
Hi 
I have not found an answer when digging around Google so hope to find here.
When designing an object say a box that needs to have some precise dimensions like 11,6x20,4 mm. I find it difficult in blender to set these dimension on the fly. To change the size I need to scale but it can be difficult to set the exact length of a side/line. 
Is this better/easier in bforartists? 

In my head I should be able to select any line/edge and say "you need to be 11,6mm!"

**Comment by ReinerBforartists** [comment]
This is indeed impossible in Blender. In Edit Mode you scale relative to the initial value. But in Bforartists we have a tool that allows to scale in world dimensions in Edit mode. It's called Set Dimension.

Switch to Edit Mode
Select the geometry that you want to scale. 
Go to Mesh > Transform, and activate the Set Dimension tool.
Down left open the Adjust Last Operation panel. And here you can set the dimensions in world units.

You need to activate the tool for every new selection!

Hope this helps you :)

Kind regards
Reiner

![part1](https://user-images.githubusercontent.com/13919702/93014724-c322a480-f5b3-11ea-9b83-21d0d0da938a.png)

![setdimensionspanel](https://user-images.githubusercontent.com/13919702/93014726-c74ec200-f5b3-11ea-9c82-b4bf515970af.jpg)

**Comment by Wikinggaffa** [comment]
Thank you @ReinerBforartists 
I will try this out. 
I want to design some things for 3d printing or CNC. Some of them needs to be millimeter precise so the scaling option will not work in the long run I think.
The CAD-softwares I have been looking at seems either difficult to work with or to simple to do anything useful with. They don't seem to have the designer in mind ;-)

**Comment by ReinerBforartists** [comment]
Please note that Blender, and so also Bforartists, is no CAD software. It is not designed with precision in mind. And there is little that we at Bforartists can do.

Closing this question as resolved. Thanks for asking :)
