### ISSUE TITLE
UV Editor -  new Unwrap menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1818]
Blender has now implemented a new Unwrap menu into the UV editor too. It has no icons. Which would be a quick fix. Icons exists already in the 3d view menu.

I have no idea what to to with this menu though. Is it really necessary? Shouldn't we separate it like in the 3D view, and put the menu directly into the header? And we need to modify the menu. We have split the methods angle based and conformal apart ...

![newunwrapmenu](https://user-images.githubusercontent.com/13919702/93014811-8d31f000-f5b4-11ea-9f15-ba89f37fa321.jpg)

**Comment by seanr** [comment]
For comparison, this is the menu in stock Blender:

<img width="230" alt="Screen Shot 2020-09-15 at 9 39 51 AM" src="https://user-images.githubusercontent.com/199713/93217776-77990380-f737-11ea-8780-158a3c4144b6.png">

To get this right I think will require more than just icons. We're missing the Live Unwrap item, for one, but the organization of the menu overall is different as well (that new submenu isn't a submenu in either the previous version of BFA or stock Blender 2.9).

**Comment by ReinerBforartists** [comment]
Thanks for the hint with the live unwrap. We have two live unwrap in the sidebar of the 3D view now. And it is missing in the UV editor. Needs a check and a fix for sure.

In general, options like live unwrap, does not belong into a text menu in Bforartists. But in the sidebar. Or in a dropdown menu in the header. Left tools and menus, right options.

**Comment by ReinerBforartists** [comment]
Ah, live unwrap is not missing in the UV editor. It is already in the options. But it is a bit ugly, since it is the image options. We need a better place ...

![liveunwrap](https://user-images.githubusercontent.com/13919702/93238641-ff0b6480-f781-11ea-811c-53d10b9da5ed.jpg)

**Comment by ReinerBforartists** [comment]
Separating the two live unwrap issues. They do not belong here.

**Comment by ReinerBforartists** [comment]
We have a space problem in the header. It's already too crowded. And you unwrap in the 3d view. So keeping the menu in the current location. Remains the re iconize task, and to split the unwrap into abf and conformal.

**Comment by ReinerBforartists** [comment]
Fixed in master

![unwrap](https://user-images.githubusercontent.com/13919702/97416092-4a2ea080-1906-11eb-8527-c5f6bd72ffb5.jpg)
