### ISSUE TITLE
UV Editor - find a better place for live unwrap

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1825]
We have live unwrap in the image options. But it is a uv mapping option, and has nothing to do with images.

We need a  better place for it.

![93238641-ff0b6480-f781-11ea-811c-53d10b9da5ed](https://user-images.githubusercontent.com/13919702/96680783-79796680-1376-11eb-8e30-4a4793eb3bfa.jpg)

**Comment by ReinerBforartists** [comment]
Hm, the uv vertex u v box is also a uv feature, not an image feature. 

So either we introduce a new uv tab. Or we leave the content as it is, and rename the current Image tab to Image / UV.

Opinions?

**Comment by Draise14** [comment]
This in the 3D Viewport is in the Options dropdown. Maybe keep it in the same place, but in the UV editor. 

![bforartists_m8F4DBlvBO](https://user-images.githubusercontent.com/35357409/96638541-ea247280-12e5-11eb-99c4-5405e750ab0f.png)

**Comment by ReinerBforartists** [comment]
Yeah, good idea. An options popup is easier to reach. But we still have the UV transform box in the image tab, which bothers me. 

Ah, no need to hurry. Waiting for inspiration ^^

**Comment by ReinerBforartists** [comment]
UV Vertex is a C panel. Ah this goddamn inconsistent design -.-

**Comment by ReinerBforartists** [comment]
I would have loved to remove the options panel from the sidebar. But we have a space problem in the header. The options dropdown in the header jumps in the off when you create an image.

![options](https://user-images.githubusercontent.com/13919702/96986749-5ab7d300-1522-11eb-9e5c-5a495ea81ac5.jpg)

**Comment by ReinerBforartists** [comment]
Unassigning for now. We first need to do some steps at the header to free some space.

**Comment by ReinerBforartists** [comment]
Related since i have in this task put the UV layers prop into the toolsettings area to have more space in the header. Image Editor - fix property arrangement in header #1897

Now let's have a look if it makes sense to remove the options panel from the sidebar. Note that there is also the Image editor involved here. Not just the UV editor.

**Comment by ReinerBforartists** [comment]
Fixed in master
