### ISSUE TITLE
Toolbar - Custom buttons and categories

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1827]
# Case
Someone has made a way to customize and make a toolbar - which means the code to customize the BFA toolbar is possible. Maybe some of this code from this addon can be spliced into the Bforartists toolbar. We did talk of it here but was closed #1361 ... though it might be worth discussing again, since it has been a user request a number of times and now there is code that could be adapted for it. 

[Link to Addon](https://blenderartists.org/t/shelves/1253560)

![image](https://user-images.githubusercontent.com/35357409/93604060-7b709400-f98a-11ea-9364-979bad3a18bd.png)

![image](https://user-images.githubusercontent.com/35357409/93604076-81ff0b80-f98a-11ea-8464-822ba1de3cbf.png)

# Request
Can we take a deeper look into this addon and maybe add customizability to the toolbar to make it even more powerful by adding addon button functionality, customizability, and more into the official Bforartists toolbar?

**Comment by ReinerBforartists** [comment]
Sure. One more point at the list ^^

**Comment by ReinerBforartists** [comment]
We could simply modify the addon to display in the toolbar :)

As a sidenote, most operators depends of the right editor to perform the tool. And so most of the tools that you can add with this addon will not work from the toolbar ...

**Comment by ReinerBforartists** [comment]
I had a look at it now. It was a nice idea. But i have to close this one. The addon does not keep the settings. You need to add the buttons again and again every time you open Blender/Bforartists. So it's missing the really interesting part.

We miss the manpower to develop and maintain third party addons. Our toolbar may be limited, you can't change the order, but it is functional. And the tools that we have added works from the toolbar. We would add lots of development and maintaining overhead with this solution. There are too much operators that does not work when you don't use it from the editor where the tool is performed. That's a special can of worms.

I will keep an eye at the addon, thanks for linking it. Maybe we can adopt the one or another thing for us. But i have to close this feature request here. Sorry.

**Comment by Draise14** [comment]
Ah, no problem.
