### ISSUE TITLE
Add new switch object operator to the UI

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1828]
Blender has added a hotkey only functionality to switch to another object without leaving the edit mode. It cycles through the available mesh objects. The key is currently D.

Hotkey only functionality is no go. And we have occupied D with tweak anyways. So we need to add this functionality somewhere.

![switchobject](https://user-images.githubusercontent.com/13919702/93868090-391cbf00-fcca-11ea-96c1-0ecee0452bfc.jpg)

![cyclethrough](https://user-images.githubusercontent.com/13919702/93868051-2e622a00-fcca-11ea-8721-9b85b1ebaf99.jpg)

**Comment by ReinerBforartists** [comment]
Hey Iyad,
Any plans where you would want this tool to be? :)

**Comment by ReinerBforartists** [comment]
Note, the functionality also exists in sculpt mode.

**Comment by ReinerBforartists** [comment]
Sorry for spamming. Just noticed that the hotkey is currently disfunctional in Blender and of course also in BFA with the Blender keymap.

So i made a bug report. https://developer.blender.org/T81881

**Comment by iyadahmed** [comment]
Hi, the operator seems to switch to the object under cursor (says so in
operator docs), so putting it in a menu might not be good, should we create
a similar operator with object selection pop up?

**Comment by iyadahmed** [comment]
Oh thanks for heads up

**Comment by iyadahmed** [comment]
Oh ok, I’m currently testing it too

**Comment by ReinerBforartists** [comment]
I have to thank you. Didn't notice that you need to use the mouse too. This makes the whole story much more complicated, Blender UI design ...

Hm. To switch to the object under the mouse doesn't work neither here. So bug report seems to be valid. Phew.

The idea with a popup is nice. We could place this in the header in edit and sculpt mode. But i would say first let's wait what the outcome of the bug report is. Saves us some work :)

**Comment by iyadahmed** [comment]
Agree, do you recommend any other tasks to start with?

**Comment by ReinerBforartists** [comment]
Sorry that your first issue already is a troubled one. It's always the easy looking ones that makes most trouble :D

There are a few really easy tasks around. Like this one. It's basically just putting an operator at another location: https://github.com/Bforartists/Bforartists/issues/1812

But you can really assign to any task. I search for example still for a way to reactivate the tabs in the toolshelf area. Just in case you prefer the hardcore mode  :)

https://github.com/Bforartists/Bforartists/issues/1402

**Comment by iyadahmed** [comment]
No problem, yeah :)
Great, will check the tasks you recommended

**Comment by ReinerBforartists** [comment]
Turns out that this is a deactivated developer feature. I will postpone this issue now.

https://developer.blender.org/T81617

**Comment by iyadahmed** [comment]
Ok

**Comment by ReinerBforartists** [comment]
This is, or better was a developer feature. The feature is removed for now. And so it makes no sense to keep this tracker issue open. We might come back to this once they decide to make it an official feature. 

Closing.
