### ISSUE TITLE
Cycles - Bake panel in Diffuse mode has missing options

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1830]
# Issue
![bforartists_hH61TFVbbv](https://user-images.githubusercontent.com/35357409/93943764-cbd45280-fcf8-11ea-98ae-32a697a4a365.png)
![bforartists_Kia05NzPOg](https://user-images.githubusercontent.com/35357409/93943768-cd9e1600-fcf8-11ea-8289-729e93ba4436.png)
In Cycles, under Bake then Diffuse mode, there are missing parameters under the group "Influence" due to a row issue. 

Blender for comparison:
![image](https://user-images.githubusercontent.com/35357409/93943842-f4f4e300-fcf8-11ea-9539-a552677b08b8.png)

# Task
Fix the row issue on the prop.

**Comment by ReinerBforartists** [comment]
Fixed in master
