### ISSUE TITLE
Outliner - Color Tag menu item in collections rmb menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1835]
Blender devs have added a way to color the icons for collections. This works with monochrome icons. But we have colored icons. And so i haven't implemented this feature into our rmb menu yet.

Needs further thinking and experiments.

![colortag](https://user-images.githubusercontent.com/13919702/93984921-b573d880-fd84-11ea-9c77-9ec9120af73b.jpg)

**Comment by Draise14** [comment]
How is this one going to be fixed?

**Comment by Draise14** [comment]
Looks like there are separate icons for each colour, meaning we could just colour the icons in the SVG, manually - keep them fixed and theme agnostic. 

`'COLLECTION_COLOR_01', 'COLLECTION_COLOR_02', 'COLLECTION_COLOR_03', 'COLLECTION_COLOR_04', 'COLLECTION_COLOR_05', 'COLLECTION_COLOR_06', 'COLLECTION_COLOR_07', 'COLLECTION_COLOR_08'`

**Comment by ReinerBforartists** [comment]
I don't want to add ten more icons really, with different colors. My idea was to test how our standard icon turns out when it is colored.

**Comment by ReinerBforartists** [comment]
We need to change the colors here to the Blender default colors then ...

![fixed](https://user-images.githubusercontent.com/13919702/96331517-31003700-105e-11eb-9552-968de7f34505.jpg)

**Comment by Draise14** [comment]
I can't find the entries for these to test.. are they hidden? 
![image](https://user-images.githubusercontent.com/35357409/96731413-daa43880-137c-11eb-8bfd-6e02d1ab1bcb.png)

**Comment by ReinerBforartists** [comment]
It's Blender code.  We don't have this code yet. That's what this issue is about :)

**Comment by ReinerBforartists** [comment]
Updating icons fails at the moment. Unfunny. Maybe it's the newest Inkscape version. Checking ...

![problem](https://user-images.githubusercontent.com/13919702/96863507-4662d000-1467-11eb-94d7-3b6c5f961da3.jpg)

**Comment by ReinerBforartists** [comment]
Ahahah, it IS Inkscape ^^

> The --without-gui option has been removed. Most parameters trigger Inkscape to run without GUI by default now. Instead enable GUI mode specifically using --with-gui if needed.

https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line#:~:text=The%20--without-gui%20option,--with-gui%20if%20needed.

So back to a 0.9x version ...

**Comment by ReinerBforartists** [comment]
As expected, since we had this problem with the old icons, the colored icon makes trouble here. It turns out dull. Seems that i  need to create a bright version of our group icon just for the outliner display.

![oldproblem](https://user-images.githubusercontent.com/13919702/96903936-bd638d00-1496-11eb-9051-56633c967b1d.jpg)

**Comment by ReinerBforartists** [comment]
Still a bit dull, since making it brighter desaturates of course the colors. But i don't want to make it completely white really.

So fixed in master. At least for now.
