### ISSUE TITLE
Mac Version of Bforartists 2.5.1

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1836]
Hey sean,

I have created a new version of Bforartist. Bforartists 2 version 2.5.1 brings the changes and fixes of Blender 2.90.1. Would you be so kind to create a mac version for it? :)

Kind regards
Reiner

**Comment by ReinerBforartists** [comment]
@seanr, are you still here? :)

**Comment by Draise14** [comment]
Yep, he's still around. Just got swamped with all the github notifications and missed the memo on Discord.

**Comment by seanr** [comment]
I'll get this out this evening (NYC time; I have a meeting in the late afternoon with some stuff to do to prep for that).

**Comment by ReinerBforartists** [comment]
Ah, great. Many thanks :)

**Comment by Draise14** [comment]
File got done just now, but shared to Gdrive. Apparently it's a little unstable, the dev builds have proven a lot more stable. 

[https://drive.google.com/file/d/1gipoEKqKgnboAu31E0SouBdvqIuBipzM/view?usp=sharing](https://drive.google.com/file/d/1gipoEKqKgnboAu31E0SouBdvqIuBipzM/view?usp=sharing)

**Comment by ReinerBforartists** [comment]
Thanks a bunch buddies :)

Downloaded and currently uploading. Closing this task as done.

I don't have a mac to compile dev builds of it too. Mac users has to live with that, sorry.
