### ISSUE TITLE
Viewport Overlays, redesign Guides section

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1845]
I am not happy with the guides section. The ever confusing greyed out Grid button since you are in no ortho view. The greyed out Subdivisions box ( i need to have a look into the manual again here too, i have forgotten with what settings it activates), the names in the sliders, and last but not least no master button to turn everything off. Needs always five clicks to turn really everything guides off.

![guides](https://user-images.githubusercontent.com/13919702/94986569-2f177d80-0560-11eb-8d73-a7f39159a0cd.jpg)

**Comment by ReinerBforartists** [comment]
First step is to implement a master switch to turn really everything off at once.

**Comment by Draise14** [comment]
Yes please. This is a huge illogical mess only understood by pressing buttons.

**Comment by ReinerBforartists** [comment]
Related 

Viewport Overlays - make Grid checkbox work for all views, not just orthographic #1479

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/99565204-aba8d300-29cb-11eb-9a1b-550e9cef8416.jpg)
