### ISSUE TITLE
Motion Tracking - sliders with text in the slider

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1866]
The whole tracking workspace contains sliders that has the description text inside of the slider instead in front or above it. Inconsistent. Either we have in the whole UI the prop name in front or above the sliders, or inside of the sliders. Even when it eats more space then.

![slidertext](https://user-images.githubusercontent.com/13919702/95428450-4c29c300-0949-11eb-82f0-517716d1df49.jpg)

**Comment by ReinerBforartists** [comment]
Hm, it's not as easy it seems. We have for example in the 3d view in the sidebar also the text in the sliders here and there.

![textinslidersa](https://user-images.githubusercontent.com/13919702/95430640-55685f00-094c-11eb-989c-2614151948cb.jpg)

**Comment by ReinerBforartists** [comment]
No. For consistency reasons we need to have the text in front of the prop. Not one time this and one time that solution. So task remains.

**Comment by iyadahmed** [comment]
we should use the proposed style in #2033 then, when its discussion finishes

**Comment by ReinerBforartists** [comment]
Indeed.
