### ISSUE TITLE
Rrewrite the Important Hotkeys addon as static

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1886]
I am still unhappy that we can't show the user a list of the most important hotkeys. The trouble with the old BFA 1 addon was that it is not longer reliable. In BFA 1 it worked flawless. With Bforartists 2 it shows not all existing hotkeys, and, even worse, shows wrong hotkeys. And i never found out why. One of the Blender changes has broken the addon.

We need a replacement. Maybe just a simple text file for the currently chosen keymap. Without to check the keys in the keymap really. The down side: every change must be adopted. And customized keymaps doesn't fit anymore.

Or we find out what goes so miserably wrong now. Addon is attached here: 

[important_hotkeys_BFA.zip](https://github.com/Bforartists/Bforartists/files/5408139/important_hotkeys_BFA.zip)

![importanthotkeys](https://user-images.githubusercontent.com/13919702/96576771-f226e700-12d2-11eb-992c-860cfe90681b.jpg)

**Comment by ReinerBforartists** [comment]
Related: https://github.com/Bforartists/Bforartists/issues/311

**Comment by iyadahmed** [comment]
looking at iskeyfree addon certainly helps
release/scripts/addons/development_iskeyfree.py

**Comment by ReinerBforartists** [comment]
Thanks for the heads up.
The curious part is, our addon worked just fine in Blender 2.79. But i have yet to find out why it fails here and there now in 2.8x

**Comment by iyadahmed** [comment]
Indeed, I think because of changed API

**Comment by ReinerBforartists** [comment]
Yeah, but i never found it. And i am so impatient sometimes ^^

I would need to isolate one entry and go from there i guess. Ah, so much work ...

**Comment by iyadahmed** [comment]
Indeed the changes are not easy to find, if they only document it in detail ....

**Comment by ReinerBforartists** [comment]
Let's have a last crack here, and reduce the script to one of the trouble makers. Maybe we can catch the baddies that way.

**Comment by Draise14** [comment]
Screencast Keys somewhat works key detection, this may hold code that might come in handy. 

[https://github.com/nutti/Screencast-Keys/releases/tag/v3.0](https://github.com/nutti/Screencast-Keys/releases/tag/v3.0)

**Comment by ReinerBforartists** [comment]
Thanks for the link :)

I have the code for the update detection already. It worked in 2.79, but fails in 2.80x now ...

**Comment by ReinerBforartists** [comment]
Damn. I knew why i did not want to make new tasks until the old ones are solved. Now i am distracted again by the new toolshelf tabs :D

Unassigning XD

**Comment by iyadahmed** [comment]
you won't believe the fix :)
single word XD

`wm.keyconfigs.active` instad of `wm.keyconfigs.default`

seems to do the job, can you confirm?
@ReinerBforartists 

addon with changes
[important_hotkeys_BFA.zip](https://github.com/Bforartists/Bforartists/files/6526572/important_hotkeys_BFA.zip)

**Comment by ReinerBforartists** [comment]
Woah, this is great news :)

I have not the time at the moment to check it. Merge ahead, and preparing the dev builds at the moment ...

Reset 3d view will need further investigation then. But this fix is already a big step forwards. And i am optimistic that we will find this problem then too.

Good catch :)

**Comment by ReinerBforartists** [comment]
Still excited about this catch =3

I have changed the title since we found a way around the biggest of the bugs.

**Comment by ReinerBforartists** [comment]
I can confirm that the faulty entries now works. Good job :)

However, there is now the trouble between the old and new tool system. Blender still uses the old tool system to rotate the object for example. We have assigned this key to the new tool system.

The display origin should also be a bit more right. With text buttons in the tool shelf you hide the text of the addon. It should be at least readable with three button rows.

![bfakeymap](https://user-images.githubusercontent.com/13919702/121862779-7105df80-ccfb-11eb-9aad-624ee8334bfb.jpg)

![blenderkeymap](https://user-images.githubusercontent.com/13919702/121862789-74996680-ccfb-11eb-983e-59c1d9c378ef.jpg)

**Comment by ReinerBforartists** [comment]
Oops. Damn close button ...

I fear we have a mission impossible here with the new tool system, since it is not part of the keymap. I have reported this as a bug, and it is open since a pretty while. The developer has unassigned since even he was lost with this code. 

https://developer.blender.org/T84510

Point is, when the new tool system is not part of the keymap, then there is also no way to retreive it. Which raises the question if it makes sense to continue with work at this addon at all. Or if we should go a much simpler route. Simply display a list of text for the default keymaps. Without to read it from the actual keymap. The latter would of course be more elegant. But makes the most trouble since months now.

**Comment by iyadahmed** [comment]
maybe we can do it manually but won't be dynamic, it is the toolsystem's fault, even iskeyfree addon struggles with it

**Comment by ReinerBforartists** [comment]
Okay, seems that you see it the same way than i do. So let's skip the scan of the keymap completely ,and make a static list for the default keymaps instead. We can still make it mode dependand. 

This means a complete new addon then.

**Comment by ReinerBforartists** [comment]
I have changed the title to reflect the new goal.

**Comment by iyadahmed** [comment]
> Okay, seems that you see it the same way than i do. So let's skip the scan of the keymap completely ,and make a static list for the default keymaps instead. We can still make it mode dependand. 
> 
> 
> 
> This means a complete new addon then.

I see but what if user has custom map?

**Comment by ReinerBforartists** [comment]
Then he has enough skills to read what is written in the keymap manager, and doesn't need the addon :)

**Comment by iyadahmed** [comment]
> Then he has enough skills to read what is written in the keymap manager, and doesn't need the addon :)
> 
> 
> 
> I am still open to a better solution. But i don't see one. And reading the keymap is not reliable anymore.
> 
> 
> 
> EDIT, mh, maybe we can implement a check for modifications. In case this is even possible.

Maybe there will be a way in future

**Comment by ReinerBforartists** [comment]
But we live now, and need a solution now. And this dilemma lasts already quite a while. 

Nothing will change in the nearer future. The keymap manager is this broken that even blender developers stops investigating since they are completely lost with it.

**Comment by iyadahmed** [comment]
I see, we could wait for a new system, but idk, if the addon is really wanted manual is the way then

**Comment by ReinerBforartists** [comment]
... or we just make the parts static that we cannot read.

I cannot let the addon go, it is too close to working ^^

**Comment by iyadahmed** [comment]
> ... or we just make the parts static that we cannot read.
> 
> 
> 
> I cannot let the addon go, it is too close to working ^^

Yep only toolshelf I believe should be static, other are working
Indeed it is a very useful addon, especially for new users

**Comment by ReinerBforartists** [comment]
Ideas how we could write it?

I thought of a hint in the panel that tool shelf tools cannot be read.

And instead of "not found" we display a "not found or not readable - default tooltip is XX"

**Comment by iyadahmed** [comment]
> Ideas how we could write it?
> 
> 
> 
> I thought of a hint in the panel that tool shelf tools cannot be read.
> 
> 
> 
> And instead of "not found" we display a "not found or not readable - default tooltip is XX"
> 
> 

A dictionary for toolshelf hotkeys, so all of them in one place

These hints sound good

**Comment by ReinerBforartists** [comment]
A dictionary?

**Comment by iyadahmed** [comment]
ah right ok dictionary is not required then

**Comment by ReinerBforartists** [comment]
The blender python api makes me nuts -.-

How do i retreive the name of the active keymap? bpy.types.KeyMap.active() throws an error that KeyMap has no attribute active. But it is listed in the api.

https://docs.blender.org/api/current/bpy.types.KeyMap.html

**Comment by ReinerBforartists** [comment]
Still wip.  So not included yet.

I managed to fix the reset 3d view entry and the switch to camera view entry. But struggle with retreiving the name for the currently active keymap. This would make our life easier with the static entries.

I think i will also ask at blender stack exchange and blender developer if there is really no way to retreive hotkeys from the new tool system. This bugs me.

[important_hotkeys_BFA_1-2-1.zip](https://github.com/Bforartists/Bforartists/files/6680339/important_hotkeys_BFA_1-2-1.zip)

![fixedtwoentries](https://user-images.githubusercontent.com/13919702/122637205-a7719f00-d0ed-11eb-9f28-f486f25e09b2.jpg)

**Comment by ReinerBforartists** [comment]
Addon is on board again, and activated by default. So fixed in master. Thanks again for finding the baddie @iyadahmed  :)

![importanthotkeys](https://user-images.githubusercontent.com/13919702/122872966-80a3aa80-d331-11eb-9203-436f517448c9.jpg)

**Comment by iyadahmed** [comment]
> Addon is on board again, and activated by default. So fixed in master. Thanks again for finding the baddie @iyadahmed  :)
> 
> 
> 
> Remains to add it to the manual ...
> 
> 
> 
> ![importanthotkeys](https://user-images.githubusercontent.com/13919702/122872966-80a3aa80-d331-11eb-9203-436f517448c9.jpg)
> 
> 
> 
> 
> 
> 

Awesome!!
