### ISSUE TITLE
Sculpt Mode - Tool tab - Brush Settings - Align Front Faces Only prop left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1890]
We align props at the left side.

Removed part, since we agree about the change to be a good thing:
(And we don't grey out if we don't have to. We don't show the prop then.

There are corner cases where it makes sense to show a greyed out prop. And this prop here could be one of them. So we should discuss this part.)

![alignpropleft](https://user-images.githubusercontent.com/13919702/96746184-3693af00-13c7-11eb-9691-ea1f67f41f09.jpg)

**Comment by iyadahmed** [comment]
considering grey out, I read in the task "This is one of the rare cases where greyed out would make sense so that the user knows this tool exists.", I also tested with hiding it but realised user might not know the feature exists until changing falloff
given this, not sure about hiding

**Comment by ReinerBforartists** [comment]
I just changed my mind while you have typed your answer ^^
Yes, in this case we can leave this alone. It's a good change.

**Comment by ReinerBforartists** [comment]
While at it, could you please first make a tracker issue before you start to change something. We work in a team here. And it's especially the small things that can easily conflict then. You change something, i edit the same file, and whoosh we have a merge conflict.

So please, first make a tracker issue here in the tracker. And please give me a chance to read it :)

**Comment by iyadahmed** [comment]
great, working on left align

**Comment by ReinerBforartists** [comment]
Have a look at equal looking props. It's in most cases a simple layout.use_property_split = False
And you might need to put a lyout.use_property_split = True at the end so that the rest doesn't go crazy ^^

**Comment by iyadahmed** [comment]
> While at it, could you please first make a tracker issue before you start to change something. We work in a team here. And it's especially the small things that can easily conflict then. You change something, i edit the same file, and whoosh we have a merge conflict.
> 
> So please, first make a tracker issue here in the tracker. And please give me a chance to read it :)

**Comment by ReinerBforartists** [comment]
No problem. Teamwork simply requires some rules, sorry :)

**Comment by iyadahmed** [comment]
> While at it, could you please first make a tracker issue before you start to change something. We work in a team here. And it's especially the small things that can easily conflict then. You change something, i edit the same file, and whoosh we have a merge conflict.
> 
> So please, first make a tracker issue here in the tracker. And please give me a chance to read it :)

btw sorry for spam, can you help me with creating that, should I just create a new issue, or deal with tracker system?

**Comment by ReinerBforartists** [comment]
No, it's no spam. This is the needed communication. Better talk too much than not enough ;)

Simply make a new tracker entry by clicking the green Create New Issue button up right. Like you would create a bug report. It's as simple as this :)

**Comment by iyadahmed** [comment]
> No, it's no spam. This is the needed communication. Better talk too much than not enough ;)
> 
> Simply make a new tracker entry by clicking the green Create New Issue button up right. Like you would create a bug report. It's as simple as this :)

Great, thanks

**Comment by ReinerBforartists** [comment]
Hint: I usually make a screenshot of what the problem is. Sometimes an image explains more than thousand words.

**Comment by iyadahmed** [comment]
> Hint: I usually make a screenshot of what the problem is. Sometimes an image explains more than thousand words.
yep :)
