### ISSUE TITLE
3D View - Hotkey only Operator - Transform Axis Target on lights has no UI entry

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1892]
# Issue
The SHIT+T operator "transform Axis to Target" when selecting a light has no UI entry, not in the Right Click specials menu nor in the light context sensitive menu. it's a hotkey only operator. 

`bpy.ops.object.transform_axis_target()`

![image](https://user-images.githubusercontent.com/35357409/96886667-6c797780-1449-11eb-80ce-11135efb158f.png)

# Task
Needs an icon
Needs to be placed both in the context based light selection operators and double right click Specials menu

**Comment by ReinerBforartists** [comment]
I can have a look, but as far as i remember it's a mouse operator.

**Comment by Draise14** [comment]
Even so.. never knew it existed. Could we still add it to the UI so it's easier to manage it's hotkey and know that the feature exists? With a tooltip to say it's an under mouse operation. 

Maybe we can show these kinds of mouse only operators in the UI with the tooltip and a little asterisk in the name saying it's there to know it exists, learn about it, understand it - but it's use is hotkey recommended. 

Like this:
**Transform Axis to Target***


_I literally have used Blender and sometimes BFA for years before finding out the hotkey exclusive operators - and one of the reasons I use BFA is because you've added many to the UI again._

**Comment by ReinerBforartists** [comment]
As told, i can have a look. But no promises. 

I have a section for the hotkey only functionality in every editor chapter in the first chapter of it. And i think this entry is listed there. If not then we need to add it there.

**Comment by ReinerBforartists** [comment]
Hm, the context menu is mouse position dependant. Here we could definitely add the operator.

**Comment by ReinerBforartists** [comment]
Now what to do with the regular UI entry. The object menu would be a place for it, when a lamp of the correct type is selected. We would need to add a hint towards hotkey only functionality then.

**Comment by iyadahmed** [comment]
hmmm, should we edit the hint message?
![image](https://user-images.githubusercontent.com/25552173/97203812-fe70df80-17bd-11eb-93d4-468c40d4b182.png)

**Comment by ReinerBforartists** [comment]
Hm hm hm, never tested with a camera object. But yeah, does not work.

The functionality would be of interest for the camera too though. That's the point where one would have to start some investigation in the Blender manual ^^

**Comment by iyadahmed** [comment]
indeed, the camera doesn't seem to work

maybe I should check the source of the operator
![image](https://user-images.githubusercontent.com/25552173/97205256-e4d09780-17bf-11eb-9e13-c92dcde2b791.png)

**Comment by iyadahmed** [comment]
hmmm
![image](https://user-images.githubusercontent.com/25552173/97205757-8a840680-17c0-11eb-9f19-e76c511a9308.png)

**Comment by iyadahmed** [comment]
found a nicer name for the menu entry
![image](https://user-images.githubusercontent.com/25552173/97207119-4b56b500-17c2-11eb-921d-edd72ae6622e.png)

**Comment by iyadahmed** [comment]
also this explains why it works only for these light types
![image](https://user-images.githubusercontent.com/25552173/97207268-7e00ad80-17c2-11eb-8206-a08770ae0202.png)

**Comment by ReinerBforartists** [comment]
I have somehow the feeling that this operator is deprecated. It does not appear in the operators list. And it is buggy -.-

Hm. the new name is a bit misleading. It is meant to point a light towards an object. You need to shift select the object, then the light. That the functionality is a bit awkwards is typical Blender design ^^

**Comment by ReinerBforartists** [comment]
Ah, there it is. So scratch the camera from the tooltip. 

We should also add a note how to use this tool. Something like this:

Select object, hold down shift, select camera, perform tool.

**Comment by iyadahmed** [comment]
great, will add the note to the hint while at it

**Comment by ReinerBforartists** [comment]
One of those rare cases where it makes sense to expand the original issue ...

Still think about the tool name here. What about Light track to ? Or light transform to. Or simply use the original Blender operator name.

**Comment by iyadahmed** [comment]
agree, the names came from the name property of the operator, indeed "cursor" might be misleading, it refers to the mouse cursor instead
![image](https://user-images.githubusercontent.com/25552173/97208831-3d099880-17c4-11eb-8661-76038cf0b7df.png)

**Comment by ReinerBforartists** [comment]
Yeah it points to the mouse. But through the target object. Makes it difficult to choose a good name here :)

**Comment by ReinerBforartists** [comment]
Ah, you have removed the ctrl part from the tooltip. But i think this part is vital. With holding down ctrl too you can move the light and it still tries to point towards the target object.

So much to consider here ^^

**Comment by iyadahmed** [comment]
indeed, so tooltip needs to change again
should I enable the camera to be target-able?, I couldn't get it to work without enabling it

**Comment by ReinerBforartists** [comment]
No. As told, i think this operator is simply deprecated.

**Comment by iyadahmed** [comment]
ok will edit back the tooltip
