### ISSUE TITLE
use column/row headings for weight painting > tool tab > symmetry panel

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1893]
Consistent with Sculpting symmetry panel, and adhering to https://developer.blender.org/D7430
this also fixes #1811 
note this panel is shared with vertex and weight paint so now all these panels are consistent
edits are made to `release/scripts/startup/bl_ui/space_view3d_toolbar.py`
![image](https://user-images.githubusercontent.com/25552173/96919148-a713fc00-14ab-11eb-98df-09cb87f86744.png)

screen-shots from local build
![image](https://user-images.githubusercontent.com/25552173/96918289-5f40a500-14aa-11eb-9158-ec1bde634fde.png)
![image](https://user-images.githubusercontent.com/25552173/96918396-84351800-14aa-11eb-8344-edec8bd0e6bd.png)

**Comment by ReinerBforartists** [comment]
Closing the duplicate.
