### ISSUE TITLE
use row.prop with expand True for Image Editor - Options - Pixel Snap Mode

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1898]
related: #1896 
label and row of options will exist in a column
tried using heading (label on left of options), but icons made the row wide, it didn't look good until the panel was expanded
changes made to: `release/scripts/startup/bl_ui/space_image.py` in `IMAGE_PT_image_options`
![image](https://user-images.githubusercontent.com/25552173/97002993-0f5dee80-153b-11eb-8ca4-a4e2b8c9d67f.png)

**Comment by ReinerBforartists** [comment]
Ah, so simple ^^

**Comment by iyadahmed** [comment]
yep ^_^
