### ISSUE TITLE
Bforartists Full keymap needs documentation.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#190]
As the title says. Bforartists Full keymap needs documentation.

**Comment by Draise14** [comment]
Cool, a new projects. Seems manageable. Pushing to the Documentation github would be this task?

**Comment by ReinerBforartists** [comment]
I hope you don't mind that i have assigned you here :D

Yes. We have also a repository for the manual. You can find it here: https://github.com/Bforartists/Manual

This could be a good exercise to learn how to work with git and github. Just one file to deal with. A new chapter for the full keymap. So i thought about you here :)

**Comment by Draise14** [comment]
Sure, that's a good first challenge. I do follow that repository also. Thanks for counting on me.

**Comment by Draise14** [comment]
Ok, delivered 3 out of 6 projects, so have a little more time! Will try work on the downloading, committing and visuals for the work.

**Comment by Draise14** [comment]
Ok, learnt how to push and branch to Github successfully. I can now do this task.. 

I think I will start making subtasks for the hotkeys maps and work (many documents!) from now on and push to a new branch.

**Comment by ReinerBforartists** [comment]
Yay \o/

**Comment by ReinerBforartists** [comment]
Just curious, have you started here? :)

**Comment by Draise14** [comment]
Personally.. I'm paused and a little concerned with that changes in 2.8 and I'm pending on the final Blender map for 2.8, or else I'm just repeating work. 

I think I will make the documentation once I double check the full 2.8 map with updated BFA minimal map.

**Comment by ReinerBforartists** [comment]
Good idea :)

**Comment by ReinerBforartists** [comment]
Seems that this task became obsolete meanwhile. Documentation for BFA1 is closed. We need a new keymap in BFA2. And we most probably won't have a full keymap here anymore. 

Closing
