### ISSUE TITLE
change vertexes to vertices, typo in Blender

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1902]
while doing a previous commit I found this typo in the hint message of Sculpt Mode > Brush Settings > Front Faces Only (previously Advanced)

it is possible that this typo exists also in other places
![image](https://user-images.githubusercontent.com/25552173/97060876-1dd8f400-1595-11eb-9a03-efe0ff85ba75.png)

**Comment by iyadahmed** [comment]
still not sure, I think vertexes is valid too, will investigate more to be in favor of consistency

**Comment by ReinerBforartists** [comment]
> it is possible that this typo exists also in other places

Do a grep search and we know :)

When you are at windows: https://tools.stefankueng.com/grepWin.html

**Comment by ReinerBforartists** [comment]
Two more in tooltips are here: source\blender\makesrna\intern\rna_brush.c

**Comment by iyadahmed** [comment]
great will change them now

**Comment by ReinerBforartists** [comment]
Just noticed that in your commits the issue number is missing in the commit message. Could you please add them in the next commits? It's the #1234 number at the end of the issue title. Makes my live with writing the manual much easier :)

**Comment by iyadahmed** [comment]
oh ok will mention them

**Comment by ReinerBforartists** [comment]
Thanks a bunch. Best practice is to simply copy the issue title including the number.

**Comment by iyadahmed** [comment]
Great I've just added the new commit

**Comment by ReinerBforartists** [comment]
Okay, I will now delete your branch. We will continue with the new method now, and create a new branch for every issue. I hope you have read the PM and the forum entry meanwhile. 

If not, here are the new commit rules:

Create a new branch for every new commit and its pull request. As the name for the branch use an issue_ as a prefix. Followed by the issue number.

For example:

3D View – Lights defaults to have Contact Shadows turned on #1903
becomes a branch with the name
issue_1903

This way you can make as much pull requests as you want, and we never run into a conflict here :)

**Comment by iyadahmed** [comment]
oh I have just noticed the PMs, I didn't check the forums, reading through it now
great yeah I think branch per feature is good.
some changes can be like one line but the branches are disposable, so no probs.

**Comment by ReinerBforartists** [comment]
Yup :)
We simply did it wrong in the past. Sorry. Git was never meant to work with a dev branch. But you never stop learning. And it's never too late to make it right :)
