### ISSUE TITLE
UV Editor - Options - Pixel Snap Mode improvements

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1905]
The current implementation is a bit too noisy for my flavour. Neither the icons nor the text is really good to read.

I see two options here. Either we use pure icon buttons. Or we use pure text buttons.

What speaks for the pure icon buttons is that we could make it to a one liner, which reduces visual noise. What speaks for the text buttons is that you don't need to hover over the button to read the tooltip ...

And i don't like the term pixel snap mode. A snap to pixels is much clearer imho.

Suggestions? Ideas?

![pixelsnapmode](https://user-images.githubusercontent.com/13919702/97077360-63bca900-15e3-11eb-9803-4d5827719ffa.jpg)

**Comment by iyadahmed** [comment]
indeed Snap to Pixels is better, I think icons only too is good, because the icons are very clear, I believe other software also use icons only in a toolbar or so

**Comment by ReinerBforartists** [comment]
Okay, then let's change the string to Snap to Pixels, and put the three buttons with icon only behind the string i would say :)

**Comment by iyadahmed** [comment]
ok :)

**Comment by iyadahmed** [comment]
but should it be moved entirely to other place, maybe the header?
it doesn't look good with only icons and label, maybe we make it only icons in the header
![image](https://user-images.githubusercontent.com/25552173/97081534-5b746600-1603-11eb-942f-16411d0a8ba3.png)

**Comment by ReinerBforartists** [comment]
For me it looks good the way it is. One line :)

**Comment by iyadahmed** [comment]
ok great
