### ISSUE TITLE
Properties Editor -  Physics - Fluid - Liquid subtab - hide greyed out props for Fractional obstacles

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1920]
... , add a triangle button at the end, and indent the Obstacle Distance and the Threshold prop to mark it as sub content of the Fractional Obstacles checkbox.

We hide, we don't grey out when we don't have to.

![hideindent](https://user-images.githubusercontent.com/13919702/97170089-63f7a880-178b-11eb-84fb-201432b24c1f.jpg)

**Comment by iyadahmed** [comment]
I see this triangle all over UI, is it possible to do it like other drop down menus?

**Comment by Draise14** [comment]
I think it's an iconized indicator of hidden content. I do like it specially if I need to know if things are hidden - so these would be steps to make it consistent - a hidden content indicator when things are not active. 

![image](https://user-images.githubusercontent.com/35357409/97202057-21c96980-1781-11eb-814b-d1777c8935b0.png)

**Comment by ReinerBforartists** [comment]
Indeed. The design with the triangle button after a prop was to make it possible to hide content that belongs to this prop. But stays where it is in the list. This reduces visual noise. But gives a hint that there is more to see. And is mainly meant for single liners with a slider behind the checkbox. Before this solution we had hidden content that was not indicated in any way. Different from Blender we hide not needed content away. But even they have some props hidden instead greyed out. It's an inconsistent UI.

Well, you could make this content here a panel too, and set the parent to the liquid panel. But this method has some drawbacks. Subpanels just sorts at the end of it all. You would need to play with the subpanel order to make it fit. But, yeah, the content is at the end anyways. So it's a question of flavour here. Both seems to be valid solutions.

**Comment by iyadahmed** [comment]
Indeed, it seemed like a design choice, great to know it was for sure
agree, both seems to work good.

**Comment by ReinerBforartists** [comment]
As told, it depends of the situation. Here both would fit :)

**Comment by iyadahmed** [comment]
ok great :)

**Comment by ReinerBforartists** [comment]
Ah, there is by the way one more use case for the triangle behind the prop instead of making it a panel. Subpanels does not work proper in popovers in the header. They don't close there like they do in the sidebar for example.

But i think we can leave this one alone ...

![noclose](https://user-images.githubusercontent.com/13919702/97204306-3b38d880-17b6-11eb-9cfc-5fc194efae3a.jpg)

**Comment by iyadahmed** [comment]
oh I see

**Comment by ReinerBforartists** [comment]
Looks good. But could you please indent the sub content? :)

**Comment by iyadahmed** [comment]
hmm, I think it is indented
![image](https://user-images.githubusercontent.com/25552173/97426037-8e786b80-191b-11eb-828c-ddc76558d69e.png)

**Comment by iyadahmed** [comment]
oh I see, will do now

**Comment by iyadahmed** [comment]
should I mark as fixed?

**Comment by ReinerBforartists** [comment]
Yes, all well  :)
