### ISSUE TITLE
Recolor the dialog icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1921]
In the dialogs we have big grey icons. Defined in the alert_icons.svg in the release/datafiles folder. I would prefer to have them colored. Yellow for a warning. Red for a stop and so on.

Another thought is if we want to update to the new Blender icons. They have updated them before a few days, with a slimmer look.

![coloreddialgicons](https://user-images.githubusercontent.com/13919702/97171291-81c60d00-178d-11eb-9874-c18fcbeee997.jpg)

![blendericons](https://user-images.githubusercontent.com/13919702/97171302-85599400-178d-11eb-99de-c8a8b8693798.jpg)

**Comment by Draise14** [comment]
Colours, yes please. 

Line art icons, no thanks. Silhouette is a key aspect of good iconography and is faster to see. Maybe update the old ones a little like making the edge ring thicker in this example.

**Comment by ReinerBforartists** [comment]
Ah, this would mean to make the icons new. I'm lazy ^^

**Comment by ReinerBforartists** [comment]
Fixed in master

![alert_icons](https://user-images.githubusercontent.com/13919702/97279287-1dfa1d80-183b-11eb-8208-0ee135c654b3.jpg)
