### ISSUE TITLE
add Transform Axis to Target to Sun, Spot and Area lamps context menu

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1925]
related #1892 
changes are made to `scripts/startup/bl_ui/space_view3d.py`
screen shots after change, is there a better name for the prop?
![image](https://user-images.githubusercontent.com/25552173/97202731-a9809980-17bc-11eb-8caf-c97548f8d5d7.png)

**Comment by ReinerBforartists** [comment]
Not that i know of. Blender names ... ^^

**Comment by ReinerBforartists** [comment]
Ah just curious, why do you open another task here?

**Comment by iyadahmed** [comment]
oh, I just wanted to note it was only for sun, area, spot, and where changes are
will close it and mark as duplicate, will

**Comment by ReinerBforartists** [comment]
Just use the original thread for it ;)

**Comment by iyadahmed** [comment]
will do :)
