### ISSUE TITLE
3D View -  split Navigate into Widget and Navigate

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1933]
This one bugs me since the first incarnation. Why can't i hide the white buttons away and keep the widget?

We should split it up like in this mockup:

![mockup](https://user-images.githubusercontent.com/13919702/97434542-6e4aab80-191f-11eb-8418-574fcad7b4ce.jpg)

**Comment by ReinerBforartists** [comment]
The widget can be changed and hidden in the preferences. Still searching where the buttons resides ...

![axis](https://user-images.githubusercontent.com/13919702/99873953-23e9e100-2be4-11eb-90c2-93d27ec66dbb.jpg)

**Comment by ReinerBforartists** [comment]
Hm, checkbox is implemented. But i cannot get the flag to show or hide the buttons. They are either on or off, and remains on or off -.-

**Comment by ReinerBforartists** [comment]
Changes so far 

release\scripts\startup\bl_ui\space_view3d.py -  line 7285

```
        row = colsub.row()
        row.separator()
        row.prop(view, "show_gizmo_navigate_buttons", text="Show Navi Buttons")
```
source\blender\editors\space_view3d\view3d_gizmo_navigate.c - line 309

```
    if (V3D_GIZMO_HIDE_NAVIGATE_BUTTONS == false) {

....

{

```
\source\blender\makesdna\DNA_view3d_types.h - line 599

`  V3D_GIZMO_HIDE_NAVIGATE_BUTTONS = (1 << 4),`

source\blender\makesrna\intern\rna_space.c - line 4173

```
    /*bfa - navigate gizmo buttons*/
  prop = RNA_def_property(srna, "show_gizmo_navigate_buttons", PROP_BOOLEAN, PROP_NONE);
  RNA_def_property_boolean_negative_sdna(prop, NULL, "gizmo_flag", V3D_GIZMO_HIDE_NAVIGATE_BUTTONS);
  RNA_def_property_ui_text(prop, "Buttons Gizmo", "Hide the Buttons in the Viewport navigation gizmo ");
  RNA_def_property_update(prop, NC_SPACE | ND_SPACE_VIEW3D, NULL);
```

**Comment by ReinerBforartists** [comment]
Too dumb to get it to work at the moment. Unassigning.

**Comment by ReinerBforartists** [comment]
Thanks Markus. The toggle to turn on or off the buttons already exists. Which makes this taks simply obsolete.

I will make a new task now to put this toggle where it belongs. Maybe we can manage to implement it into the UI too.

![navcontrols](https://user-images.githubusercontent.com/13919702/99941109-bcf83380-2d6d-11eb-9709-c743a7e73e42.jpg)

**Comment by naetherm** [comment]
Issue replaced by new issue #2012
