### ISSUE TITLE
3D View - rewrite Transform panel

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1935]
rewrite 3D View transform panel to match Object properties transform panel

related: #1736

it will also retain proper behaviour of the old panel (in pose mode for example)
![image](https://user-images.githubusercontent.com/25552173/97468971-8be33980-194e-11eb-896c-0a050cd272cc.png)

this will also hide location instead of deactivating it for child bones (could be another task?, but it will be fixed by this one too, so, not sure)
![image](https://user-images.githubusercontent.com/25552173/97469442-15930700-194f-11eb-8ddf-6ed09cdd8e7f.png)

what will be another task however is removing the "4L" button, as it is easy, but needs discussion (blender bug maybe?) not a really a bug, but it is legacy thing, with no reason to keep, as it seems ...
https://github.com/blender/blender/search?q=lock_rotations_4d

![image](https://user-images.githubusercontent.com/25552173/97469873-8e925e80-194f-11eb-897f-a6bdfc306308.png)

**Comment by iyadahmed** [comment]
assigned Reiner by accident :)

**Comment by ReinerBforartists** [comment]
In general we should keep the Blender features where possible. Especially when unsure about the functionality.

4L is about quaternions when i remember right. Eulers rotates around three axis. Quaternions around 4.

**Comment by iyadahmed** [comment]
ok will keep for now, looking through blender it seems to be a legacy property, just being copied, imported and exported, but not actually used

but agree even if it is legacy we should keep

if a task is created it will be to change the icon or so, because now the button looks same, pressed or not

**Comment by ReinerBforartists** [comment]
Good idea, please make a task :)

That's always the way it is, you fix something and see the next issue already ...

**Comment by iyadahmed** [comment]
great will make a task

**Comment by iyadahmed** [comment]
progress
![image](https://user-images.githubusercontent.com/25552173/97505165-10e74680-1981-11eb-8537-34902efe3627.png)

**Comment by iyadahmed** [comment]
final steps, I:m having a problem with the 4L button can't keep it is size fixed when it uses text, this option is only for "only icon" probs, will leave it for the other task, pushing branch now
![image](https://user-images.githubusercontent.com/25552173/97553933-ba105a00-19de-11eb-8544-891884a243ca.png)
