### ISSUE TITLE
3D View - Transform panel change 4L button icon

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1937]
the button looks same, pressed or not
either change icon, or enable emboss
![image](https://user-images.githubusercontent.com/25552173/97471505-79b6ca80-1951-11eb-9dba-761d05b040eb.png)

**Comment by ReinerBforartists** [comment]
There is no icon here, this is pure text. And it is C code from what i see. So the first quesiton is, color the text or insert an icon? Emboss seems to be the easier method. A real button the cleaner one.

**Comment by iyadahmed** [comment]
I see, I just tried embossing, and it colors the text green if it is not pressed, and white if it was

I think we can just use the lock icon, because this controls the lock_rotations_4d property, so it is consistent with others

**Comment by ReinerBforartists** [comment]
Your task, decide what fits better :)

The lock icon could be misleading here though. How turned out the text color?

**Comment by iyadahmed** [comment]
but actually the text isn't better it is as misleading, a lock is better on the other hand, and the tooltip is always there

**Comment by ReinerBforartists** [comment]
Welcome to UI design. It will not become easier later :D

**Comment by iyadahmed** [comment]
indeed :D XD

**Comment by ReinerBforartists** [comment]
What speaks for the text is that Blender has handled it that way. Former Blender user will know and recognize what it is.

**Comment by iyadahmed** [comment]
I agree, I thought so, decided on text

**Comment by iyadahmed** [comment]
will postpone for now, may reopen again, using text isn't perfect, can't keep fixed size when resizing, but with a icon only it can be, so ideally we would create an icon for 4L, the icon would an image of the text 4L, when the property is fasle the text has a red mark

**Comment by ReinerBforartists** [comment]
Related: https://github.com/Bforartists/Bforartists/issues/1943

When we know what the button is good for then we can decide what icon to shape.

**Comment by iyadahmed** [comment]
agree, the button could end up removed :)

**Comment by ReinerBforartists** [comment]
New icon is in progress.

**Comment by iyadahmed** [comment]
> New icon is in progress.

Awesome

**Comment by ReinerBforartists** [comment]
Icons are added. And committed to the master.

Name of the icons : 4L_ON and 4L_OFF

Pink background comes from the icon sheet. Is transparent.

![4l_icons](https://user-images.githubusercontent.com/13919702/97798845-33e85380-1c2a-11eb-8568-60edabbb42bb.jpg)

**Comment by iyadahmed** [comment]
great editing the prop icon now

**Comment by iyadahmed** [comment]
looking great
![image](https://user-images.githubusercontent.com/25552173/97799334-5d0ee100-1c36-11eb-91da-de690335316e.png)

**Comment by ReinerBforartists** [comment]
Much better than the previous version. And now you can really say what state is on and what is off :)

**Comment by iyadahmed** [comment]
Indeed, much better after this change :)
