### ISSUE TITLE
Adjust last operation panel - align Proportional Editing props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1938]
Time to start to collect all these C panels with middle aligned content.

Proportional editing is a general sub content of quite a few last operations. Align these three checkboxes left.

![proportional](https://user-images.githubusercontent.com/13919702/97473117-e7abc380-194a-11eb-8c46-d1223d7d6887.jpg)

**Comment by iyadahmed** [comment]
it seems that last operator panels are defined panel by panel, but generated from the operator
`source/blender/windowmanager/intern/wm_operators.c`
`line 1297`
so any change would affect all other panels

**Comment by ReinerBforartists** [comment]
Even better :)

**Comment by iyadahmed** [comment]
indeed :)

**Comment by iyadahmed** [comment]
did some investigation
there seems to be 3 ways of writing UI in Blender, the most low level one uses UI_block, uiDefBut, etc.. (C)
the other one uses uiItem, uiLayout, etc.. (C)
and third one is Python
2nd and 3rd are somewhat easy to convert between

2nd one seems to be build on 1st one
so we can use 1st and 2nd together

last operation panel and #1940  uses the first system

**Comment by ReinerBforartists** [comment]
I once tried to dive into this concept and got mad at it. So good luck ^^

**Comment by iyadahmed** [comment]
indeed, the way to go seems if we could try to rewrite at least some low level UI using the higher level one, currently experimenting with this, this would make UI more consistent, and easily fix issues like this and #1940, instead of figuring out two different UI codes, we just write one and use it for both.

**Comment by ReinerBforartists** [comment]
What i always searched is the location where they define the middle aligned props at all.

**Comment by iyadahmed** [comment]
I think it is defined here, they use a recursive function to draw all props of the operator, so they don't define a panel for each it is generated automatically from the last operator

![image](https://user-images.githubusercontent.com/25552173/97609317-1fcf0700-1a1c-11eb-80dd-fc26419594de.png)

so alignment is defined there, and also here, they disable split layout if all operator props are boolean (check box), this makes them align left, so I think all we need to do is try to do this also for check boxes when also there are other types of props

![image](https://user-images.githubusercontent.com/25552173/97609419-455c1080-1a1c-11eb-8855-408d78dca551.png)

**Comment by ReinerBforartists** [comment]
Sounds so easy :D

**Comment by iyadahmed** [comment]
it should be yeah :D

**Comment by ReinerBforartists** [comment]
I was in this file already before. But couldn't manage it. But yeah, my C fu is against zero  ^^

**Comment by iyadahmed** [comment]
I hope everything goes right ^^
