### ISSUE TITLE
Delete Marker - confirm dialogue 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#194]
**Task**
Remove "Delete Marker" confirm dialogue when using Delete on the marker timeline in the Animation editors and VSE. 

At the moment it says "Ok [to delete]?"

![bforartists_2018-04-30_17-44-15](https://user-images.githubusercontent.com/35357409/39453939-1e965daa-4c9e-11e8-9291-ee1fc69ac772.png)

**Comment by ReinerBforartists** [comment]
Fixed in master.
https://github.com/Bforartists/Bforartists/commit/a0f3d0465bd5d6ccabb61da35ed5b040cd1eccbf

There was also one in the tracking editor. Turned off too.
