### ISSUE TITLE
Transform panel in Edit mode - text inside sliders

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1940]
In Edit mode with a primitive object we have some sliders that has still the text of the prop inside of the silders. This is inconsistent with the rest of the UI. Text with the name of the prop should be in front of the sliders. 

Mesh object, curve object, surface object, metaball object, bone object, lattice object.

![transformedit](https://user-images.githubusercontent.com/13919702/97558347-48cfa780-19dc-11eb-81da-51804c228bb3.jpg)

**Comment by ReinerBforartists** [comment]
Damn, wrong commit -.-

**Comment by iyadahmed** [comment]
oh ok

**Comment by iyadahmed** [comment]
progress
this took a while :)
moral of story, the "lower level" way gives you absolute control, we can change step size and precision for floats, and change a float value directly, the down side is some of the work is manual, but, using the uiLayout for arranging the panel is easy enough, so no probs, we can use uiLayout for arrangment, and the lower level for the actual buttons (they were already used in this panel for example)
![image](https://user-images.githubusercontent.com/25552173/97635893-d349f280-1a40-11eb-9002-f28263d59f3c.png)

**Comment by ReinerBforartists** [comment]
Not sure why, but i still have the text inside the sliders.

Let me do a clean compile first ...

![stillinside](https://user-images.githubusercontent.com/13919702/97672400-49267c00-1a8a-11eb-9bdb-f602ab79e899.jpg)

**Comment by ReinerBforartists** [comment]
Clean build, same problem. The commit has definitely arrived in the master code.

![arrived](https://user-images.githubusercontent.com/13919702/97673092-7aec1280-1a8b-11eb-8cfb-4220318dda5e.jpg)

**Comment by iyadahmed** [comment]
Oh the mean bevel weight and so still not done, my bad 🤦‍♂️

**Comment by ReinerBforartists** [comment]
Don't forget the other object types too :)

Mesh object, curve object, surface object, metaball object, bone object, lattice object.

**Comment by iyadahmed** [comment]
working on it, will not :)

**Comment by iyadahmed** [comment]
btw what should we do about the label of Vertices/Edges Data and so?
should I continue like this
![image](https://user-images.githubusercontent.com/25552173/97710424-6841ff80-1ac4-11eb-8360-8a32c5f59bd6.png)

**Comment by ReinerBforartists** [comment]
The cleaner method is indent if possible. But the sidebar is a bit short of space. So it depends how it turns out.

**Comment by iyadahmed** [comment]
ok, great will try indention, I think it will look good

**Comment by iyadahmed** [comment]
here's how it looks with indention
btw while at it, shouldn't the factor slider have the slider look, I think that is left for another task
![image](https://user-images.githubusercontent.com/25552173/97720309-d1c80b00-1ad0-11eb-981b-47891c22b5e1.png)

**Comment by ReinerBforartists** [comment]
Looking good to me :)

Mh, quick idea, we could save some space when we put the term mean into the label. Example:

Vertices Data Mean:
    Bevel Weight

Not sure what you mean with a slider look though. These sliders here already looks like any other slider :)

**Comment by iyadahmed** [comment]
indeed will test out with terms next to label
I mean sliders have a slider thing when they change, this one seems to not have this effect, it only changes number, no sliding overlay

**Comment by iyadahmed** [comment]
Mesh object, curve object, surface object, metaball object, bone object, lattice object.
it turned out to be a one big big commit :) , each one of these is defined for each object type, not a panel that dynamically changes..
e.g for metaball
v3d_editmetaball_buts
v3d_editarmature_buts for armature
v3d_transform_butsR this was the one rewritten #1935 
and so on
but working on it

**Comment by iyadahmed** [comment]
write now working on v3d_editvertex_buts

**Comment by ReinerBforartists** [comment]
Yeah. I already expected so. But these changes belongs to each other. So we can get away to manage it all in one issue. It does not need to be one big commit. Just make severtal small commits until the main task is done. I usually use the main issue as the commit message plus the actual change then. Example:

My main issue #1234 - changed some sub issue issues
My main issue #1234 - changed some other small things
My main issue #1234 - colored the colors a bit more

And so on. 

You could also split the tasks up into the single objects if you want and when you have the feeling that it becomes too much at once. And make a single task for each of them. In this case it all depends of what is more comfortable for you.  Allowed is what works :)

The only thing that we should not do is to mix the issues here. When it's a fix that does not belong to the current issue then we need to create another issue for it. Like this one: 

> great idea, will test out with terms next to label
> I mean factor sliders have a slider thing when they change, this one seems to not have this effect, it only changes number, no sliding overlay
> bevel and crease are factors so they should have this blue overlay

This would be another job then, which doesn't belong to the current issue to put the text in front of the prop. Please create a new issue for it :)

**Comment by iyadahmed** [comment]
I see, great, will create another issue for labels :)

**Comment by iyadahmed** [comment]
> I see, great, will create another issue for labels :)

forgot about slider effect, will create another one for that too

**Comment by ReinerBforartists** [comment]
Mh, it is no slider. It is a value box with slider functionality. I think that's why there is no blue here. To have a distinction to real sliders.

**Comment by iyadahmed** [comment]
oh ok, I meant the bevel factor, it goes from 0 to 1, it would be nice to have the blue overlay

**Comment by ReinerBforartists** [comment]
Green :)

**Comment by iyadahmed** [comment]
great :)
