### ISSUE TITLE
Properties Editor - Transform Panel - 4L button does not hide the lock at the Z value

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1943]
Not sure if we can do anything here. But in the properties editor the lock does not vanish like in the sidebar when you deactivate 4L.

This problem becomes even more a problem when you lock the Z value and turn off 4L ...

![part1](https://user-images.githubusercontent.com/13919702/97611911-11322100-1a17-11eb-8ac8-cad07af7be8b.jpg)

![part2](https://user-images.githubusercontent.com/13919702/97611919-13947b00-1a17-11eb-8949-6824967946fb.jpg)

**Comment by ReinerBforartists** [comment]
Related

Pose mode - Transform panel in Properties editor misses 4L button #1941

**Comment by ReinerBforartists** [comment]
Haha, we have a even bigger problem here. In Blender the lock behind the W value vanishes ...

![4l](https://user-images.githubusercontent.com/13919702/97613817-6ec76d00-1a19-11eb-8565-163a4432c5e5.jpg)

**Comment by ReinerBforartists** [comment]
Asked at Blender Stack exchange too 

https://blender.stackexchange.com/questions/200339/transform-panel-quaternion-mode-what-is-the-4l-button-good-for

**Comment by ReinerBforartists** [comment]
I have accepted the pull request. But i want to keep this task open until we get an answer from Blender Stack exchange. Maybe this answer brings us more clarification what the tool really does and what use case it has.

**Comment by ReinerBforartists** [comment]
There is even a paper available. naetherm pointed me to it. So it is quaternion functionality. It is just not documented what the difference is.

https://www.sciencedirect.com/science/article/pii/S0022314X99924484

**Comment by ReinerBforartists** [comment]
Ha! Found a explanation https://blendervn.org/t/blender-quaternion-rotations-or-eulers/232
 
The x y and z axis are real axis. And so they have by default a lock. But not the W axis, this is a calculated value that has no lock by default since it is calculated through the other three values. 4L turns on a lock for this W axis too.

In Blender this prop is off by default. In Bforartists it is on by default. I just don't know why ^^

Either way, now that we know what it is good for we can shape an icon, and update the manual here ...

**Comment by ReinerBforartists** [comment]
Or we simply remove this button, and show a lock at W by default. Less visual noise, and no riddle anymore what this button is good for. I think you already suggested this solution.

**Comment by iyadahmed** [comment]
great, yeah the 4L is kinda obsolete, because we can already lock W component
thanks for searching this, it is much more clear now

**Comment by ReinerBforartists** [comment]
Just make sure that the lock does not vanish then ^^

**Comment by iyadahmed** [comment]
Sure will :)

**Comment by iyadahmed** [comment]
aha I think I figured out the use of the 4L button, it is kinda obscure,
when it is false, the W lock is hidden, and if all other rotation components are locked then the W or angle component will be also locked,
if one or more of other components is unlocked then W is unlocked too

if 4L is true, then the locking state is controlled by the W lock

**Comment by ReinerBforartists** [comment]
Hm, and i thought it is just to show or hide the w lock. In this case it sounds like we should  keep this lock. 

I will shape an icon next week ...

**Comment by ReinerBforartists** [comment]
Closing this one. The task for the icon is here: https://github.com/Bforartists/Bforartists/issues/1937
