### ISSUE TITLE
3D view - Transform panel - put "Mean" term after 

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1948]
after completing the task the panel would look like this
![image](https://user-images.githubusercontent.com/25552173/97784544-06f35c80-1ba8-11eb-84ed-939c813c97ce.png)

**Comment by ReinerBforartists** [comment]
Looking good :)

**Comment by ReinerBforartists** [comment]
To make the task more obvious, it's about to remove the dots here, so that you can read all the text in default width.

![obvious](https://user-images.githubusercontent.com/13919702/97786338-2d66c700-1bab-11eb-88d6-65bddc41d952.jpg)
