### ISSUE TITLE
View 3D - Transform Panels - slider overlay for relevant sliders

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#1950]
factor like sliders like bevel weight should have a slider overlay
like this
this is defined in source/blender/editors/space_view3d/view3d_buttons.c
in calls to uiDefButF
![image](https://user-images.githubusercontent.com/25552173/97786066-9fdaa580-1bb1-11eb-8760-b7f7dbbc601a.png)

**Comment by iyadahmed** [comment]
hmm this has been kept for so long, I need help with decision, is it worth it, carrets may go away and it shows too many digits, any way to solve, or better to close the issue?

![image](https://user-images.githubusercontent.com/25552173/101514087-91886200-3985-11eb-9d67-3c63461ce574.png)

**Comment by ReinerBforartists** [comment]
Hmm. This becomes indeed quickly a monster task. You would need to go through any slider. I would vote to close this issue therefore. But you made the task. Your decision :)

**Comment by iyadahmed** [comment]
alright, closing for now, focusing on other tasks :)
