### ISSUE TITLE
3D View - UX - Add Global Mirror functionality

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1957]
# Issue
When doing a global mirror transform in Object mode, the object mirrors to the axis and orientation of the local origin. But when doing a global mirror... it SHOULD mirror to the world axis and orientation, but it mirrors to the object axis and orientation as if it was in Local. Is this expected behavior? If so.. the operator is redundant or broken as it's doing the same thing between local and global. 

![image](https://user-images.githubusercontent.com/35357409/97900678-00c8c180-1d09-11eb-960a-494e3e0e5004.png)

![image](https://user-images.githubusercontent.com/35357409/97900663-f9091d00-1d08-11eb-970e-07e416a27dd3.png)
![image](https://user-images.githubusercontent.com/35357409/97900669-fc040d80-1d08-11eb-98c5-51219876da9f.png)

# Posible Task/s
- Verify if it's supposed to work this way **DONE**
- If it is supposed to work this way, remove one of the redundant mirror entries to have only one = Local. **WON'T DO**
- If global is needed, then find a fix or report to Blender. **DONE - WON'T DO**
- If Blender is not up to fixing this, add a new Global mirror operator for object mode. 

### Observations:
![image](https://user-images.githubusercontent.com/35357409/97900889-54d3a600-1d09-11eb-8e76-75ce16cf5b17.png)

Testing has the API work correctly, but it's not working.

Blender has the same UX, btw.

**Comment by ReinerBforartists** [comment]
Interesting observation :)

**Comment by seanr** [comment]
Why is orient_matrix_type set to LOCAL in both?

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/97902111-1b9c3580-1d0b-11eb-9054-65667d07dc08.png)

Even if both are global, it doesn't work.

**Comment by ReinerBforartists** [comment]
Does this happen in Blender too? If so then i would suggest to make a bug report.

**Comment by Draise14** [comment]
Yes, happens in Blender too. Man.. every time I make a bug to Blender it's like throwing the issue into an abyss..

**Comment by Draise14** [comment]
Issue reported by @seanr . 

[https://developer.blender.org/T82334](https://developer.blender.org/T82334)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/98125423-76a46880-1e82-11eb-9cb9-0c0d3c21ee71.png)

Ok.. they closed it as invalid and even suggest to just minimize it to be "local". Anything else is a feature request which they won't allow. 

So that means... having these entries as global or local is just... pointless as indeed they all work locally. We could remove 3 entries here... for now.

**Comment by ReinerBforartists** [comment]
Thanks folks. I already feared it. It works as designed, even when this design is ass forward :)

I don't want to remove the global operators really. But we will keep this task open. Maybe we find a way to improve things here. Even when this chance is very small.

**Comment by Draise14** [comment]
Yeah, I get it. It would have to be a new operator I guess. I changed the title to keep it relevant.

**Comment by ReinerBforartists** [comment]
Thanks :)

**Comment by seanr** [comment]
> I don't want to remove the global operators really. But we will keep this task open. Maybe we find a way to improve things here. Even when this chance is very small.
I don't see any point in keeping the global ones actually visible in the menu if they don't do jack differently. It's incredibly misleading and therefor worse than redundant, IMO. As for the reaction from the Blender folks, how very _typical_. 😡

**Comment by ReinerBforartists** [comment]
They have reopened the issue and commited a patch

https://developer.blender.org/rBec39d8de4adf46161d81fb525a73278fe08a8704

Could somebody have a look at Blender and check if this fixes the trouble? If so then we could close this issue.

**Comment by ReinerBforartists** [comment]
*bump*

**Comment by Draise14** [comment]
Tried it out on a daily build, no fix. The issue linked is for another thing, the method of mirroring. 

Not.. the global origin.

**Comment by ReinerBforartists** [comment]
Good job :D

**Comment by ReinerBforartists** [comment]
Hm. Just tested. And for me global and local mirroring works in object and edit mode. There is clearly a difference between the two mirroring results. Desired or not.

Either way, a fix is behind my skills. So let's finally close this issue. There is nothing that we can do here.

**Comment by Draise14** [comment]
![9jhjhrJcDQ](https://user-images.githubusercontent.com/35357409/108069179-0dabbf80-7031-11eb-9f11-75215aa6d572.gif)

Ah I see now.. It is based on orientation, not the actual world pivot point, or origin. I guess this is where the confusion lies, you'd expect mirror on world origin, and local origin. Not world orientation and object orientation. 

@seanr looks like if you want to mirror based on world origin and local origin, it would be a new feature - but looks like they fixed the orientation issue at least.

**Comment by ReinerBforartists** [comment]
Thanks for clarification :)
