### ISSUE TITLE
3D View - UX - Add world space (move along plane) navigation like in UE4/trueSpace

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1962]
# Issue
Right now when you transform anything, it's in view space. XY of mouse is XY on screen. Z is completely accessible without hotkey modals to constrain an axis after the fact or a viewport widget. This is slow, cumbersome and not obvious. 

In Unreal Engine and some other 3D Software (like trueSpace) you were defaulted to true global 3D space or had the option to use it: where XY of mouse was XY of world, or local, and another button would be in global Z or world, or even to view (meaning you could access the Z axis of the screen, world or local). 

It's very useful for 3D workflows.. since we are in XYZ..
![6FJ2OKMcON](https://user-images.githubusercontent.com/35357409/98150140-32be5d00-1e9c-11eb-8b5a-549c25e86859.gif)

# Task
Add two new hotkey entries (no conflicts):
1. ALT+CTRL+L press - Move in XY 
2. ALT+CTRL+R press - Move in Z
![image](https://user-images.githubusercontent.com/35357409/98149758-a2801800-1e9b-11eb-993f-65288568d991.png)

Which hotkey can be open to debate, but for now these are free and still relatively easy to use. Though just ALT+L press is free, but  ALT+R is not, it places cursor (these would be ideal, just one modal that many are used to using to navigate). 

Another good one is SHIFT+ALT+L press and R press. Also free. Shift is translation related in name. 

## Notes
In general, in UE4, it would be CTRL then Lmouse X, Rmouse Y and Double Mouse for the Z axis, but we can't do double mouse. So a double modal with a single mouse press that doesn't conflict then open one button to XY in 3D world or local and the other to Z would be great UX (though one modal would be nice, but none free), similar to how trueSpace works by default (without the modals - the ideal).

**Comment by ReinerBforartists** [comment]
I could swear that we had already hotkeys for this ... I'll have a look.

**Comment by ReinerBforartists** [comment]
I just knew i had seen it before :)

It's the modal hotkeys for transform. Here you can lock single axis. But also to a plane. Shift X allows movement in y and z. That's what you want, right? :)

We can continue the discussion. But I will close the issue since there is nothing to do for us here.

![alongaplane](https://user-images.githubusercontent.com/13919702/98212836-766ca180-1f44-11eb-8ae5-c04b596fa428.jpg)

**Comment by Draise14** [comment]
This is completely different task. 
This is not to constrain axis after the transform activation... this is to move IN 3d space without preconstraining anything.  

No extra key or mouse presses after the move, just move in 3d space.

**Comment by ReinerBforartists** [comment]
Move in XY is Z Plane

**Comment by Draise14** [comment]
Can we reopen this? This task is to make this 3D control not a post-hotkey system with modals, but an intuitive action for mouse.

**Comment by Draise14** [comment]
I'll have to make a video to showcase the pro's and why this is not post-modal feature (that indeed already exists). That method is clunky, slow and hotkey biased.

**Comment by Draise14** [comment]
Here is the video showcasing how it works in UE4 and how it works in trueSpace and why we want it to work with Bforartists and why post-modal hotkeys is not a good method to solve this. 

[https://youtu.be/mtZV4FwTnCk](https://youtu.be/mtZV4FwTnCk)

**Comment by Draise14** [comment]
Another alternative is to not touch anything and just add these two entries (SHIFT+Ltweak and SHIFT+ALT+Ltweak) for transformation in 3D but with only one hotkey modifier and L tweak. Add ALT to go in Z. No conflicts, and works ok with everything. 

Other tweaks with the same modifiers can open up XY scale on SHIFT+ALT+Rtweak, or Z rotate SHIFT+ALT+MIDtweak (those are free). 

![image](https://user-images.githubusercontent.com/35357409/98265219-d53b1680-1f56-11eb-9a5f-577f425c79b3.png)

In general, the discord community like the idea. 
![image](https://user-images.githubusercontent.com/35357409/98265493-25b27400-1f57-11eb-9868-88e082699090.png)

**Comment by ReinerBforartists** [comment]
Draise, it is nothing else than the constraint :)

**Comment by Draise14** [comment]
Sigh.... program it, test it out. 

Oroginal functionality you have to press (no need to remove): 
Lpress + hold + S + move = 2 actions, but you are limited to only one axis at a time, and you have to confirm place, bordering on 3 actions.  
Lpress + hold + Z/Y/Z (global) + move = 3 actions, 3 variables in the same sequence to memorize and use
Lpress + hold + Z/Y/Z + X/Y/Z (local) + move = 4 actions, 3 variables in the same sequence to memorize and use
Lpress + hold + Shift + X/Y/Z (global) + move = 4 controls for two axis action, 3 variables in the same sequence
Lpresss + hold + Shift + X/Y/Z + X/Y/Z (local) + move = 5 controls for two axis action, 3 variables in the same sequence

All of these pause mouse movement UNTIL you have the system setup they way you want it. So it's like.. press, do a dance on the keyboard, THEN move. This is valuable time to move things, and done thousands of time a day - and it's hard to use. 

**VS**

SHIFT + hold + Ltweak (press and move) = 2 actions for XY constrained in 3D space, 2 actions ending on mouse press to move immediately
SHIFT + ALT + hold + Ltweak (press and move) = 3 actions for constrained Z in 3D space, 3 actions ending on mouse press to move immediately

This is: activate, press and move immediately as soon as you press down on one mouse button, no need for any sequences for the functionality. 

There is no argument that it's more efficient, easier to learn and use, and on top of that, it works in 3D space. Also, it is discoverable by accident: pressing these keys then L tweak is what you do when you start up a program.. you don't automatically do a whole keyboard sequence while holding down a mouse button for desired control! 

It is an added UX for the same functionality, but a better UX.

**Comment by ReinerBforartists** [comment]
Yes, i know all this. And i understand that for you it is the better workflow. But how many workflows should we implement? One for every user so that everybody is satisfied? How many transforms along a plane do you really need? That's the culprit. And for me it's lmb and one fast keypress versus holding down shift + alt and then move. There is no gain. It is just different. Both requires to hold down a key.

But before we continue, the other issue that you have created would provide a third method to move along a plane, if it would just work. And this would be the fastest method. 

3D View - Transform - Restrict axis with middle click #1961

Because the automatic constraint double entry from this bug report here is not really a double entry. But the one is meant to move along a single axis. and the other along a plane. I have already added it to the keymap. 

https://developer.blender.org/T82423

So i would say, we wait with further discusison until Blender devs have fixed it.

**Comment by Draise14** [comment]
Ideally I'd have it default 3D navigation with Lclick alone - only move in screenspace when screenspace is chosen in the orientation - like trueSpace. 

This is more about 3D space transforms, not axis restrictions.

**Comment by ReinerBforartists** [comment]
That would be a completely different movement scheme then :)

**Comment by Draise14** [comment]
This is what I'm asking for with this task. XY (current orientation) is XY of mouse, Z is XY of mouse with a modifier. BFA and Blender is limited to Screenspace regardless or orientation with no easy axis to Z, there are a dozen buerocratic ways to Z, or anything other than screenspace - or default to widget.

**Comment by ReinerBforartists** [comment]
Yes i know. And this is what we cannot do, sorry. As told, let's wait what happens to the autoconstraint along a plane. Maybe this opens up a good way for you.

**Comment by Draise14** [comment]
I will probably have to resort to a custom map. =(
I can add this to all transforms, Lclick XY in the current space, then Z with a single modifier (ALT) + Ltweak.

**Comment by ReinerBforartists** [comment]
> 3D View - Transform - Restrict axis with middle click #1961
> 
> Because the automatic constraint double entry from this bug report here is not really a double entry. But the one is meant to move along a single axis. and the other along a plane. I have already added it to the keymap.
> 
> https://developer.blender.org/T82423
> 
> So i would say, we wait with further discusison until Blender devs have fixed it.


Bug report is fixed. And it fixes this issue here too. At least from my angle. Now we have a way to constraint along a plane too.

Draise, can we please close this issue now? :)

**Comment by ReinerBforartists** [comment]
Okay, no it is not. The constraining to the axis works. But not to the plane.

**Comment by ReinerBforartists** [comment]
Ah, so simple! But we need a few fixes here. We have already x plane, y plane and z plane in the modal map. But repeat is ticked. And then it flickers. And it is tied to shift, which conflicts with the precision movement. Draise, what do you think to use ALT here instead of shift?

Subtask, go through the modal map and turn off repeat where necessary.

![planemovement](https://user-images.githubusercontent.com/13919702/101261636-0f0b6280-3739-11eb-9e57-8a06aa1965b0.jpg)

**Comment by ReinerBforartists** [comment]
Separating repeat task from here. There is more across the whole keymap.

**Comment by ReinerBforartists** [comment]
We could use x c v instead x y z. Then we cover the american european switch of z and y. But loose at the same time the connection between x y z and the buttons.

**Comment by Draise14** [comment]
I have been using ALT and left drag for XY and ALT+SHIT left drag to Z for a few weeks now, Alt is fine. Alt is "alternate move". Indeed Shift was conflicting. 

Having it as ALT+X,Y,Z to constrain those particular axis feels more like trueSpace back in the day. I don't use modals often, mostly stick to widget or the ALT+Left press to XY plane, has become second nature now.

**Comment by Draise14** [comment]
Just to say, this task really was to try find a hotkey-less method to use a transform plane for XY and another for Z like in UE4 or trueSpace to tranform, or find a minimal keymap system based on mostly one hotkey + mouse action of a sort for the equivalent (which I managed to do with ALT+Ldrag and ALT+SHIFT+Ldrag). If we do combo hotkeys to restrict a single axis like we would with the post transform modal constraints.. this would be another task and not relevant to the feature request here. 

So I will close this and just keep the plane edit to mouse drag as a custom mod. I would like other user to enjoy being able to move things in 3D space without needing to change settings nor press many hotkeys nor use modals after the fact of moving - moving along plane with intention, not as an after thought nor finger gymnastics concerning UX.

**Comment by Draise14** [comment]
> 
> 
> We could use x c v instead x y z. Then we cover the american european switch of z and y. But loose at the same time the connection between x y z and the buttons.

I suggest making this another task.

**Comment by ReinerBforartists** [comment]
So let's switch the second key from shift to alt key.

C and V could be an additional key. We keep the z and y, and add c and v as an alternative for faster navigation. I'll make another task for this.

**Comment by ReinerBforartists** [comment]
> Just to say, this task really was to try find a hotkey-less method to use a transform plane for XY and another for Z like in UE4 or trueSpace to tranform,

Long understood. But we have already a method to constraint by the transform modal keymap. But i don't really want to repeat the discussion. Your hotkey is something for a custom keymap at the user end.

**Comment by Draise14** [comment]
OH well...

**Comment by ReinerBforartists** [comment]
Separating the change to alt to its own task.
