### ISSUE TITLE
3D View - Expose transform orientation up a level (or just 3 then a dropdown)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1964]
# Issue
The pie menu is the "." on the keyboard - ergonomically far away from both hands. The transforms are in a drop down hidden away also. But more often than not I toggle and changes these dozens of times - mousing over the drop down and selecting, which is a double mouse move and a click, or release. 

It would be great to be able to toggle these with a single mouse move and click - like in the toolbar. 

# Request
Move the most common + dropdown or all of these up a level into the toolbar header, or into the toolbar editor as an optional system. 
![image](https://user-images.githubusercontent.com/35357409/98280585-9c586d00-1f69-11eb-8575-d3a404a9265e.png)

**Comment by ReinerBforartists** [comment]
This would crowd the header quite a bit. And we could not remove the Transform Orientations panel since the custom orientation cannot be placed into the header. Means we would have a double entry here.

**Comment by Draise14** [comment]
The dropdown shouldn't be removed yeah, but I want to expose atleast a few common. 
![image](https://user-images.githubusercontent.com/35357409/98282751-aaf45380-1f6c-11eb-9674-c533c52d5d0a.png)
If the menu needs to be minimizd, sure. 

It would look a bit like how the Snapping entry looks, but with 3 new buttons. Remove the title in the toolbar settings.

**Comment by ReinerBforartists** [comment]
Yes i know. But it needs to be consistent. This one needs a better planning.

**Comment by ReinerBforartists** [comment]
I knew there was something tickling me here. We cannot remove content from the orientation dropdown since it is reused in several other places like the tool settings and the adjust last operation panels.

To make the confusion complete, every orientation can be unique here ^^

Anyways. We cannot remove content, and adding buttons to the header would be a double. So let's have a look if we can create a toolbar entry here, with expanded content. I don't have high hopes though. The orientation seems to be tied to the 3d view editor.

![orientation](https://user-images.githubusercontent.com/13919702/99147051-d1597380-267d-11eb-84e9-bb700834686a.jpg)

**Comment by Draise14** [comment]
Yeah. Guess you're right there. 

If the toolbar idea can't fly, Hmm... I think the pie menu could be a good alternative option that already exists, but having it as the "." key is really obscure and far away.

_I really miss the tabs and panels from the toolshelf.. It allowed for so many options._

**Comment by ReinerBforartists** [comment]
Me too. But my C fu was so far too weak to resurrect it.

**Comment by ReinerBforartists** [comment]
Well, i was able to implement the dropdown box in the toolbar. And it works also from there. But i was not able to make single buttons for the single then. The functionality is tied to the array, which i cannot access it seems. 

Blender Python API has an entry bpy.types.TransformOrientationSlot. But i get an error that types has no attribute transform_orientation_slot. So this entry seems to be faulty.

I think we reached the end of road here. Sorry that i have no better news. You could search for a better hotkey. But the good ones for the left hand are already occupied. And changing the orientation isn't something that a normal user does every five seconds. 

Closing.

**Comment by ReinerBforartists** [comment]
Just wanted to add, you can assign a shortcut to the Global prop too. I find the menu under the mouse more handy than the pie menu.

![assignshortcut](https://user-images.githubusercontent.com/13919702/99179091-7f1a6000-271a-11eb-8480-3a18639f587d.jpg)
