### ISSUE TITLE
Rigging - Parenting to bone is not working

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1965]
# Issue
When trying to parent an object to bone using the parent menu (parent to bone, parent to bone relative) it does nothing. 

1. Select box
2. Select armature in pose mode (Lock Object turned off)
3. Select bone to make active
4. Parent to bone

Nothing happens.

What should happen?

The bone becomes the parent of the object in relations panel. 

Version:
devbuild-01-11-2020

Was working in this version:
devbuild-25-10-2020

# Task
Find out what's happening, fix.

**Comment by ReinerBforartists** [comment]
Does it work in Blender?

**Comment by ReinerBforartists** [comment]
Yes it does. Investigating.

**Comment by ReinerBforartists** [comment]
It is not only to bone. Parenting is in general broken. Unfunny.

**Comment by seanr** [comment]
I actually noticed this today but it's not entirely broken. Parent one
object to a second. It will not show in relationships. Select only the
parent and move it. The child does move with the parent as expected. I do
this sort of thing fairly often since Blender 2.8+ doesn't support real
groups (this is the least awful alternative for me usually).

**Comment by ReinerBforartists** [comment]
Yes, but both will most probably have the same cause. I'm going through the code at the moment.

**Comment by ReinerBforartists** [comment]
Very unfunny. Compared the code against Blender, and the bug is not to find. 

Let's have a look at the single commits.

**Comment by ReinerBforartists** [comment]
Hah, i was able to show not working parenting in Blender. But how did i achieve this ? O_O

**Comment by ReinerBforartists** [comment]
I need to wait for the merge tomorrow. There is some specific circumstances where the Blender version from last week fails to parent too. The actual buildbot version does not show this bug anymore.

**Comment by ReinerBforartists** [comment]
Cause identified. 

SHA-1: ad35fa1993a49f663f782af1c9c41640e94b7eb8

* Parenting: fix return value when parenting object to itself

Ensure parenting an object to itself is seen as error, by returning
`false`.

This error was introduced as part of a supposed-to-be-non-functional
cleanup rBb8d4a2aff8069dd7d6fb91ad0d9427eed489b68f.

When i revert this change then pareting is back working. Waiting for tomorrow for after the actual merge. Most probably the new Blender version will bring a fix here.

**Comment by ReinerBforartists** [comment]
Parenting is back working by the lastest merge. Closing.
