### ISSUE TITLE
Mac System Requirements Incorrect

### ISSUE THREAD

**Issue by greenishapple** [Bforartists/Bforartists#1966]
On the Download page/**System Requirements** it says that you need MacOS 10.12 or newer.
I downloaded it and tried to open it but it said I needed MacOS 10.13 (I'm using MacOS 10.12.6)

I was wary about downloading it, knowing that Blender 2.9 would not work, but I thought I'd give it a try.

As b4artists 2.51 is based on Blender 2.9 it will only work with MacOS **10.13** or higher.

**Comment by ReinerBforartists** [comment]
Good catch. Thank you. I will correct the informations :)

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by greenishapple** [comment]
Cool, thanks.
I might be upgrading to MacOS 10.13/High Sierra sometime.
I do have b4artists v1.00
