### ISSUE TITLE
Properties - Object Properties tab - Relations panel - align camera lock parent prop left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1969]
This prop gots moved from user preferences to this relations panel. Is now middle aligned, should be left aligned.

![camlocparent](https://user-images.githubusercontent.com/13919702/98461343-aa95cb80-21ab-11eb-9f14-ace716a15d79.jpg)

**Comment by iyadahmed** [comment]
should we hide parent type and camera parent lock instead of greying out?
