### ISSUE TITLE
Properties Editor - Object Properties - Relations tab - hide inactive content

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1973]
Sometimes you stare at something and don't see the problem anymore. Happened to me here. We hide not used content, we don't grey it out. 

No idea how we could or if we should implement a triangle button here. We have lots of other content that is also just visible when you are in a specific mode. So this time it's simply hiding it away. No parent object, no parent object settings. This should be obvious enough.

![greyedout](https://user-images.githubusercontent.com/13919702/98471506-1b110c80-21ed-11eb-9c48-27b5d9fe44e6.jpg)

**Comment by ReinerBforartists** [comment]
Ah and we need to indent this content so that it is clear that it is connected to parenting ...

**Comment by iyadahmed** [comment]
> Ah and we need to indent this content so that it is clear that it is connected to parenting ...
yep
