### ISSUE TITLE
Toolbar - Separate tooltips with UV Clear and Mark seam

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1979]
# Issue
![image](https://user-images.githubusercontent.com/35357409/98994890-8b29d600-24fe-11eb-8a28-5e1a5a509a19.png)

A user has reported the UV mark seam and clear seam has the same tooltip in the toolbar.

# Task
Separate the tooltip to clarify which is which in functionality.

**Comment by ReinerBforartists** [comment]
Fixed in master
