### ISSUE TITLE
Video Editing - sidebar - type text strip - align triangle buttons with the rest of the panel content

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1985]
We hide not needed content away with a triangle button. This triangle button should be aligned with the rest of the properties where possible. Which can be done with a split = layout.split()

In this case the props are not centered, so we need a split factor. It was around 0.65 from what i remember. Could also be a bit more or less. Try out.

Example code

```
        split = layout.split(factor = 0.65)
        col = split.column()
        col.use_property_split = False
        col.prop(my, "example_operator")
        col = split.column()
        if my.flag:
			col.label(icon='DISCLOSURE_TRI_DOWN')
			... add more content here
        else:
            col.label(icon='DISCLOSURE_TRI_RIGHT') 
```

![vsealign](https://user-images.githubusercontent.com/13919702/99143612-26d25800-265f-11eb-9a3e-67dadcd5e491.jpg)

**Comment by iyadahmed** [comment]
I just had an idea, can we make simple panels instead?, it wouldn't take much time

**Comment by ReinerBforartists** [comment]
That's the culprit. When it's just one prop then the triangle is the better solution. Also, subpanels sorts at the end of the panels, they append

**Comment by ReinerBforartists** [comment]
That's indeed the culprit. When it's just one prop then the triangle is the better solution. Also, subpanels appends at the end of the panel.
