### ISSUE TITLE
Make single user popup + adjust last operation panel - align props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1986]
It's time to collect all the middle aligned props in the C code panels. Let's collect them one by one.

Make single user called from the tools toolbar opens a popup dialog with middle aligned content. It's the same content than in the adjust last operation panel when you call the tool from the object menu.

![makesingleuserdialog](https://user-images.githubusercontent.com/13919702/99144869-eaf0c000-2669-11eb-894c-2190bde5dba0.jpg)

![operator](https://user-images.githubusercontent.com/13919702/99144873-f9d77280-2669-11eb-9205-2617cd987904.jpg)

**Comment by iyadahmed** [comment]
while working on #1938 I could apply use split = false to all of them,
by adding so in interface_templates.c, got there by tracking calls in the recursive function mentioned in that issue

**Comment by ReinerBforartists** [comment]
Yeah sure. I already expected that this might be fixed with working at the lowest UI level. 

I can just not say at which UI level the popup dialog content of this dialog resides. Might be the same than the last operator, but might also be an independend panel. So we better document what we find. It's no problem to close the issue then when it is already resolved by another task :)

**Comment by iyadahmed** [comment]
> Yeah sure. I already expected that this might be fixed with working at the lowest UI level.

> I can just not say at which UI level the content of this popup dialog resides. Might be the same than the last operator, but might also be an independend panel. 

indeed, still investigating, so far it seems to be same level, I think we are getting close to solving this issue :)

> So we better document what we find. It's no problem to close the issue then when it is already resolved by another task :)

I think so too ^^

**Comment by iyadahmed** [comment]
turned out to be a very small change :), but took time to find exactly where to change ^^, finally fixed
