### ISSUE TITLE
camera-calibration-pvr _BFA_Crash

### ISSUE THREAD

**Issue by emilsvfx** [Bforartists/Bforartists#199]
I use camera Calibration https://github.com/mrossini-ethz/camera-calibration-pvr in BFA 0.9.7 but in BFA 0.9.5 witch out any crash. 
Video
https://youtu.be/KMTy0JSAQVM

Blend file
[camera.zip](https://github.com/Bforartists/Bforartists/files/1967485/camera.zip)

My estimation that BFA 9.5.0 is more stable relation to many add-ons, New BFA has some issue with new add-ons, they don't work or won't install.

**Comment by ReinerBforartists** [comment]
Not more stable, but simply compatible. Quite a few things have changed with 0.9.7. Which makes now problems with this addon. 

As usual, there is little that we can do, sorry. You need to contact the developer of the addon.

As sorry as i am , closing.
