### ISSUE TITLE
Version Number - minor version number contains empty space in API

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1995]
# Issue
![image](https://user-images.githubusercontent.com/35357409/99199541-ef9e9c80-276d-11eb-8fa9-9878423f8b95.png)
Right now with todays build (devbuild-15-11-2020) I tried to install an addon that calls for the version number of the API. 

1. Run code in blender: no spaces, converts to float without a problem
`bpy.app.version_string`

2. Run same code in BFA: space in minor version number, confusing it as a string failing the addon instalation. 

It contains a space and outputs a string. This cuases issues with the addon "Modifier List". 

# Task
Check the versioning and remove the space to keep it as a float for addon compatibility.

**Comment by Draise14** [comment]
![bforartists_9FU4Z3mrQU](https://user-images.githubusercontent.com/35357409/99200502-b49f6780-2773-11eb-983a-8064a6881028.png)

Here is the issue from the addon, as an example. Bug is not present in Blender.

**Comment by ReinerBforartists** [comment]
Did it work with older Bforartists versions?

**Comment by ReinerBforartists** [comment]
Caused by Remove Blender version hint in the footer #1703

I will revert the change, and have a look to find another way.

**Comment by ReinerBforartists** [comment]
Reverted in master.

**Comment by ReinerBforartists** [comment]
Proof of working concept

![fixed](https://user-images.githubusercontent.com/13919702/99238358-ebb85c00-27f9-11eb-9165-6d605d1e89a8.jpg)

**Comment by Draise14** [comment]
Yes, was working fine in previous versions, even if it said 2.5.0. So it was just the space. Thanks for fixing this. This broke only 2 weeks ago, so all good.

**Comment by Draise14** [comment]
BTW, the modifier list is exactly how I would want to make the modifier panel, it's super awesome, and shows the stack and one at a time, no scrolling at all - with all in iconized buttons exposed on surface level controls. It's a very good addon that fits right in with BFA.

**Comment by ReinerBforartists** [comment]
It was not just the space. With the former implementation the addon would have retreived 2.5.0 while the minimum requirements for the addon are 2.80. It would have failed.

And yes, the addon is already linked in the task. It does not allow to collapse the header though.

**Comment by Draise14** [comment]
Ah right. 

Concerning the collapse in the modifier header of the addon, since one modifier is shown when you select in the list, collapsing and drag/drop is now a useless UX so was removed in the addon.

**Comment by ReinerBforartists** [comment]
Not so sure if we should go this route really. We will see.
