### ISSUE TITLE
Toolbar - Save As and Save Copy tooltip might need splitting and clarification

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2006]
# Issue
![bforartists_T2MJP7jwA2](https://user-images.githubusercontent.com/35357409/99825551-29ccbd00-2b25-11eb-82bb-c44a06620ab1.png)

A user has asked about a clarification between Save As and Save Copy, and I noticed the tooltip is the one and the same for both operators. He only figured out the differences by going to the file browser and doing it there. 

# Request
Can we split these tooltips and also clarify the differences in the tooltips?

_Just for the record, people seem to use the toolbar a lot and like it. Good thing!_

**Comment by ReinerBforartists** [comment]
I am not sure if this was one of the cases where this was not possible. There is the file dialog involved. And that made trouble from what i remember. But let's check again.

**Comment by ReinerBforartists** [comment]
Not to solve at python level. The call of the file browser doesn't arrive. We would need to create a complete new operator in C

**Comment by ReinerBforartists** [comment]
Theoretically solved at C level, but this terrain is highly slippery. I cannot say if i have broken here something now, and if it really saves a copy or just the usual save as.

I have made a Blender bug report now for it. Let's see what they say.

https://developer.blender.org/T82918

**Comment by ReinerBforartists** [comment]
Fixed by the Blender devs. Let's wait for the next buildbot build to check. And then we might need to change our tootlip too.

**Comment by ReinerBforartists** [comment]
Confirming that the tooltip is now separated in Blender. I need to wait for the next merge though so that we can fix our tooltip too. We have changed it at one point.

**Comment by ReinerBforartists** [comment]
Fixed in master
