### ISSUE TITLE
Tool - Edit Panel - Autosmooth Angle slider: hide

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#201]
**Task**
Hide the Angle slider when Auto Smooth is disactivated. 

Location: Toolshelf>Tools Tab>Edit Panel under the Autosmooth tickbox. Ver 1.0.0 RC1

![2018-05-04_16-53-10_li](https://user-images.githubusercontent.com/35357409/39654764-ddfc123c-4fbb-11e8-9987-bed333a6b140.jpg)

**Comment by ReinerBforartists** [comment]
Good catch!

**Comment by ReinerBforartists** [comment]
Fixed in master
https://github.com/Bforartists/Bforartists/commit/c43a802c63e4ff9f3006b1135f9b1bc04b3a6870
![autosmooth](https://user-images.githubusercontent.com/13919702/39675200-cc307e1a-5157-11e8-9a0f-edb5a551528c.jpg)
