### ISSUE TITLE
Grease Pencil - put the options in the header to the right side

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2010]
For a mesh object íts options like automerge are at the right side. For a grease pencil object the options are at the left side. The typical Blender manner to solve the same thing in as much possible different ways as possible.

Task: put the grease pencil options in all modes to the right side where they belong to.

![automerge](https://user-images.githubusercontent.com/13919702/99900832-74c80b00-2cb2-11eb-8b0b-aec1eed31973.jpg)

![editmodeautomerge](https://user-images.githubusercontent.com/13919702/99900834-77c2fb80-2cb2-11eb-9cc5-015e287e744f.jpg)

**Comment by ReinerBforartists** [comment]
Hmm, complicated issue. Some buttons here are options, some are modes. Needs to be solved at a one by one base.

**Comment by ReinerBforartists** [comment]
Can of worms. Shall we really?

Let's put at least the autosnap to the right side.

**Comment by ReinerBforartists** [comment]
I need help with the decision ^^

All of the buttons in draw modes are options, not modes. So all of them should move to the tool header at the right.

**Comment by iyadahmed** [comment]
It makes sense to move them, as they are not modes, hmm, it might be worth the work, but I guess it is less priority

**Comment by ReinerBforartists** [comment]
It is clearer for sure. Options belongs to the right side. But i struggled a bit with the different modes where you can find more options too. That's why i unassigned to get a better planning here. I first need the big picture.

Unassigned does not mean that i don't think about this issue anymore. I do this often. I unassign, and from time to time i dive into it again. Up to the point where i reassign and fix it then ^^

**Comment by iyadahmed** [comment]
indeed it is better to plan,
yep I noticed ^^

**Comment by ReinerBforartists** [comment]
For now i have put the option buttons in draw to the right side of the header.  The buttons in the other modes, well, I think we should leave them where they are. Select mode is a mode. And curve editing and multi frame could also be a mode, even when i tend them more to see as an option.

![options](https://user-images.githubusercontent.com/13919702/100738560-0849bc00-33d6-11eb-8faa-a2caa032c8e0.jpg)
