### ISSUE TITLE
3D View - View Element Filter - bad alignment

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2015]
# Issue
Windows 10
![image](https://user-images.githubusercontent.com/35357409/99975717-98518b00-2d70-11eb-87b9-56fe35908a9a.png)

Mac
![image](https://media.discordapp.net/attachments/662282900691222528/780082830193328148/Screen_Shot_2020-11-22_at_9.50.16_AM.png?width=245&height=684)

Right now the alignment of the words in the element view filter of the 3D view are off. Ther aren't aligned correctly. This may be causing icon misalignment on some other OS's. 

Build: devbuild-22-11-2020

# Task
Align the words. 

### Notes
Windows 7-8
![image](https://user-images.githubusercontent.com/35357409/99976218-29c0fd00-2d71-11eb-98b5-d9c0de4e1164.png)

With windows 7 and 8, we also seem to be getting an extra column between the icons with Bforartists 2.5.1 official

**Comment by ReinerBforartists** [comment]
I'll have a look if this is even easily possible. I remember that this is a c enum ...

**Comment by ReinerBforartists** [comment]
Ah yes, i was already in this area and have cheated in the enum :D

**Comment by ReinerBforartists** [comment]
Fixed it without cheating the labels now.

![fixed](https://user-images.githubusercontent.com/13919702/99994114-e5594f80-2db8-11eb-94dc-3b167d5d724d.jpg)

**Comment by Draise14** [comment]
Discord user happy! 

![image](https://user-images.githubusercontent.com/35357409/99996946-749b3e80-2d8a-11eb-9763-dfa92b8a9a71.png)
