### ISSUE TITLE
New Mac Devbuild for download

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2016]
@seanr has compiled another dev build for mac, available here: 

[Download from Dropbox](https://www.dropbox.com/s/npsstx6hnbpzzs3/Bforartists-2.5.x-dev-Mac.dmg?dl=0)

# Task
Add to the devbuild downloads page on the website

**Comment by ReinerBforartists** [comment]
Thanks folks :)

They have changed some settings, and now the github actions, which we use to create the mac devbuild, fails. naetherm will have a second look at it once he finds the time for.

**Comment by ReinerBforartists** [comment]
Closing. I have downloaded it, and am at uploading now.
