### ISSUE TITLE
Bforartists 2.6.0 Mac Version

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2018]
Hey Sean,

Would you be so kind to create the mac version of Bforartists 2.6.0? :)

Kind regards
Reiner

**Comment by seanr** [comment]
@ReinerBforartists: https://www.dropbox.com/s/w78sfggbv2vhb84/Bforartists-2.6.0-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
You're my hero \o/

**Comment by ReinerBforartists** [comment]
Up and running. Closing the issue. Thanks again :)
