### ISSUE TITLE
NLA Editor - Snap dropdown menu has no icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#202]
![bforartists_2018-05-04_17-11-45](https://user-images.githubusercontent.com/35357409/39655270-46158d88-4fbe-11e8-93d5-4d7f24a424b2.png)

All other animation editors have the drop down icon for frame snapping, but the NLA editor does not. Must have slipped. 

Ver 1.0.0 RC1

**Comment by ReinerBforartists** [comment]
Indeed. For graph editor it's also missing. Those are separate menus, that's why ^^

Will fix it.

**Comment by ReinerBforartists** [comment]
Fixed in master
https://github.com/Bforartists/Bforartists/commit/ea0cab95d29d8028ca3f69b9c37c4b9947ea1494
