### ISSUE TITLE
Animation Editors - Unify Dopesheet and Timeline to be the same editor

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2024]
# Issue
The timeline is like a stripped back version of the dopesheet. Do we really need two different versions of the same thing?

Regarding #2023, maybe we could avoid this all together and remove one editor and improve playback controls for the other animation editors. 

# Request
Move the timeline controls to the dopesheet, NLA, VSE and Fcurve editor
Move the playback controls to the dopesheet, NLA, VSE and Fcurve editor
Remove the timeline all together

Features to move from Timeline to other animation editors:
![image](https://user-images.githubusercontent.com/35357409/100476042-93fbd980-30b2-11eb-9836-69ffa34b0c51.png)
![image](https://user-images.githubusercontent.com/35357409/100476045-95c59d00-30b2-11eb-8978-6f565921fa59.png)

## Cons
This.. might crowd the other animation editor header UI. So this is really only a half request. 
The fact that the timeline is like an animation header in the layout, which is good, to make sure the timeline is in every workspace with animation.. is fine... but I think that's the only reason we use the timeline, for the frame range and playback controls.

**Comment by iyadahmed** [comment]
Interesting, it would take not little work to move these features, but I think it is a nice idea.

**Comment by ReinerBforartists** [comment]
Definitely interesting, and no easy task. But the killer here is unfortunately that we need to stay compatible to Blender for the merges. Not the first time that i wish we could act compeltely independent. But that's the way it is. They have the manpower for the features. We not.

**Comment by ReinerBforartists** [comment]
The cons in conjunction with the above point makes me close this issue. Nice dream. But not one that we should waste time at.

In the end it's even useful to have the headers separated. Even when for the content it's not.

Closing. Thanks for the idea.
