### ISSUE TITLE
General UI Layout - Make Left Handed to accomodate the Property Shelf UX hotspots better

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2025]
# Issue
Right now, BFA has the same workspace layout as Blender where the property shelf and the property editor are located to the right. 

![image](https://user-images.githubusercontent.com/35357409/100479721-01146c80-30bd-11eb-9ebd-db3a9ddebd85.png)

This causes the property shelf to be overshot with the mouse, and makes the properties and settings double up in the same area of the screen creating weight to the UX to be biased to the right. This also offsets the center of the eye which should be the center of the viewport, but is to the left. 

Key Issues:
- Overshooting the property shelf is typical
- Outliner is behind a UI distance
- UX hotspot for property editing has a bias to be at the far right, with two areas that conflict UX with each other
- Viewport center is offset to the left

# Request
![image](https://user-images.githubusercontent.com/35357409/100480007-0b833600-30be-11eb-856c-f5de6e54a7c2.png)

Change the default workspaces to be Left Handed, meaning moving the outliner and the properties editor to the left instead of the right.

## Pro's
- The viewport becomes more centered and focused
- The property shelf has no overshoot so easier to target
- The outliner is now a UX hotspot along with the toolshelf tools,
- Outliner is easier to access without so much distance to traverse before accessing it from the active viewport with key controls more accessible with less distance from 3D View
- The repeated panels and properties are now with a purpose: if on left screen, you can go left, if on right screen, you can go right, no overshoot nor senseless repetition.
- Property Shelf feels like more of a property based toolshelf for the 3D View instead of a miscellaneous shelf that doubles the properties editor. 
- Bforartists becomes more thought out concerning UI and also unique from Blender, this could be the Bforartists UI trademark = left handed balance. 

## Cons
It's different to what normal blender users are used to. 

To be honest, I don't see any reason to keep the right handed system other than.... it was traditionally this way because we had Left and Right tabbed shelves in Bforartists 1/Blender 2.79 which created the centering and balanced UX hotspots with no obvious overshoot (principled tabbed toolshelf and panels was to the left), but now this is not the case. We need to update.

**Comment by ReinerBforartists** [comment]
You destroy the left tools right options design with that :D

**Comment by Draise14** [comment]
There are no left tools right options design. 

What are you talking about?

**Comment by iyadahmed** [comment]
so this boils down to changing statup.blend right?

**Comment by Draise14** [comment]
Just to say, I have been testing this out for a few months now, just to know what I'm talking about. I have really found no reason to keep the old system, I have only found reasons to put that part of the UI to the left. I've been watching many users use Blender live, and they either don't use the properties toolshelf, or usually overshoot it, which is detrimental to the general UX. 

Another pro:
- The tool shelf is now not so set away from the far left of the screen, making them easier to use with the mouse, less hotkeys.

**Comment by ReinerBforartists** [comment]
The whole properties editor is nothing else than all the options.

**Comment by Draise14** [comment]
I guess the cons you are implicating is this:
- Properties and Options from two different areas are no-long grouped to the same location/weight on screen (but they really never were together in the same editor)
- Documentation would have to be rewritten
- It would be harder explain than to just say "tools to the left (and in the header) and options/properties to the right with that group of other things". 
- the Toolshelf might now be overshoot to get to outliner

You'd now have to say (if Lefty):
"Scene and other Properties Editor to left under outliner. Tools to 3D View top left. 3D View, addons and tool properties to right. "

**Comment by ReinerBforartists** [comment]
Sorry to play the party pooper here. But i simply have to veto this idea. Some ideas make it, some don't. That's simply the way it is. Don't let it discourage you. Keep the ideas coming :)

Your told points plays a role too. But as told, this is against the design pattern that i follow since years now. Left tools, right options. For me the outliner is also option. And i would love to put the addons back to the left. They are tools.

There is simply no benefit. But quite a few drawbacks. We would have an immense workload here. You name it, we would need to rewrite parts of the manual and change all layouts. When somebody prefer to have the properties editor at the left then he can simply split the 3d view and open the properties editor there.

**Comment by ReinerBforartists** [comment]
Forgot to add, you could create a custom layout with your workspaces that contains the property editor left, which you could share with other users then. But this would need to stay outside of the repository. Everything inside the repository needs to be maintained and documented.

**Comment by ReinerBforartists** [comment]
Closing the issue because of told reasons.

**Comment by Draise14** [comment]
Shame.. Yeah, the key reason is it is new, requires work to change, and key users wouldn't be used to it because they are used to the old paradigm. 

I personally have tested this in all my work spaces for months and see more benefits than cons, and yes, I have used blender and bforartists for near 7 years total now, it wasn't much to change to left. It felt more centered balanced as a lefty. 

There are more benefits than drawbacks if based on a point based system. The only cons.. is it takes work to change. 

I do use a custom layout, but sharing it is like sharing a startup blend and a whole bunch of workspace startup blends, it's not artist friendly. 

Is there a way we can have an "All Left" workspace group included in the workspaces? We won't need to document it, default are right handed, but the left can be quickly shared and included, and briefly mentioned in the chapter 3 manual.

**Comment by ReinerBforartists** [comment]
This is what i meant. A whole template with left sided properties. But i cannot include it in Bforartists, sorry. There can just be one default.

**Comment by Draise14** [comment]
Yes, I agree, that is why Right side is default, but the workspace group is an additional group. Not default.

**Comment by Draise14** [comment]
Meet me halfway here, please.

**Comment by Draise14** [comment]
# Alternative Request 2
### The even LESS invasive one
Add an application template to the website download for left handed layout, mention it briefly in chapter 3 of the manual.
![image](https://user-images.githubusercontent.com/35357409/100617249-3e107700-32e8-11eb-8e73-057ad78f62bc.png)

**Comment by ReinerBforartists** [comment]
I cannot, sorry. I heavily disagree with the idea to have the content at the left side. It's against my UI design. And there is also no compromise possible since there can just be one default.

With template i meant indeed what you show here. You could attach this template in the forums then for example. That way everybody interested could download it and try it out.

![apptemplate](https://user-images.githubusercontent.com/13919702/100617087-4a152c80-331a-11eb-8030-a95586928a32.jpg)

**Comment by Draise14** [comment]
Cool, let's do that - I can upload an application template, mention it in the interface chapter. 
I would like it shared a bit more obviously, even from the download page directly. But at least you're negotiating and being opensource about it. Thanks for that.

**Comment by ReinerBforartists** [comment]
Draise i think you have misunderstood me. I cannot make your wish official. I will not accept your template in the repository or in the manual.

**Comment by Draise14** [comment]
That is unreasonable. There are more points to a pro for it than against. This is for the artists. We are negotiation a non-invasive inclusion that doesn't affect the master, and the artist here is really being flexible here. All I'm asking is for a bit more flexibility from your part. 

Where is the "be for artists" here with this request?

**Comment by ReinerBforartists** [comment]
Could you please calm down? I don't do this to make you angry. What you ask for here is anarchy. Everybody implements what he wants and how he wants. But that's not how software development works.  I have to care for the big picture. 

We have discussed the idea, it did not make it. And so the case is closed. Could you please accept this?

**Comment by Draise14** [comment]
Steps:
1. Application template I commit to the Files repository
2. I add one paragraph and title and download link to Chapter 3 - Interface.pdf

Done. I maintain the left hand layout when interface defaults change. 

What is NOT done:
- It's not added to master
- It's not added to the download page
- It's not affecting anything in the documentation
- It is not changing defaults
- It is not included with Bforartists official download nor master

We both win. You don't affect the current installation and workflow, nor documentaition. 
The artists and the pipeline both win because now it's an option. 

We all win. The world is a better place.

**Comment by Draise14** [comment]
Just for the record, I'm not angry (passionate yes, but angry no), and I admire your decisions and all, but I also know the big picture is to be for the artists. I know development can't do every ones favours, but in this case this is just a customization available for the artists. As the big picture implies in the name.. "be for the artists", I am very clear this is what we do. I don't mean to make you feel like I'm trying to impose, I am in fact trying to negotiate a middle ground with a bias towards what you would like. I just hope I can do it here with you.

**Comment by Draise14** [comment]
But with all that is said and done, I guess we can leave it as is. I'll make an application template and put it free on gumroad or something. No worries.

Sorry bout the insistance. Thanks for all the work here with BFA! My favorite thing online and with my daily work.

**Comment by ReinerBforartists** [comment]
Good idea. And no worries. As told, you are always welcome to share your ideas. And you know that more than one has made it into the master already. But one has simply to make the decisions and to care for the general direction :)

**Comment by Draise14** [comment]
haha, someone saw me use the left hand layout with Bforartists in a competition live and made a video on it: 
[Watch on Youtube: https://www.youtube.com/watch?v=8X8xpuIysdY&t](https://www.youtube.com/watch?v=8X8xpuIysdY&t)
