### ISSUE TITLE
Add back the old operators into the edit menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2028]
Draise, this is something that will make you happy i guess. I want to add the old operators back to the UI :)

But not as before. The plan is to create a sub menu called legacy, where you can find the old operator doubles then. The initial plan was to put these operators into the tool shelf at one point. But we didn't manage to get this one back working. So let's do this (hopefully) intermediate solution to add them back in a sub menu.

I am also open to suggestions. Maybe we get the tabs in the tool shelf back to work. Then we could put this content directly there.

![legacy](https://user-images.githubusercontent.com/13919702/100521761-de11b780-31a5-11eb-8b7d-ac8d9bb77393.jpg)

**Comment by ReinerBforartists** [comment]
Or simply put a (Legacy) behind the tool name.

**Comment by ReinerBforartists** [comment]
Let's start with the select menus.

**Comment by Draise14** [comment]
Ah cool, this was more a request from users I've talked to on Discord. It was hard to counter their points. 

What about "Quick" to the tool name and menu group "Quick Edit" instead of "legacy"? Then add "Legacy" to the tooltip description? 

They are "act once" operators, feeling "quick"... Legacy makes them feel like they will be removed one day, but we don't know if Blender will ever, or if we will be able to replicate or modify the UX from the toolshelf to move them...

**Comment by ReinerBforartists** [comment]
Well, it's the old and legacy way to do things. And we had them removed already :)

At the moment it looks like this.

![legacy](https://user-images.githubusercontent.com/13919702/101059864-08d98280-358f-11eb-8cdb-26030b7ea5dd.jpg)

**Comment by Draise14** [comment]
That too also works, a legacy sub menu.

**Comment by ReinerBforartists** [comment]
Extrude menu 

![extrude](https://user-images.githubusercontent.com/13919702/101143494-4124a380-3617-11eb-9eae-7ff0bae0a7c5.jpg)

**Comment by ReinerBforartists** [comment]
The legacy content in edit mode. Vertex, Edge and Face menu.

What i have not readded back is all the doubles. And now i first need to dig a bit more. Since i think that was it already. 

![editmode](https://user-images.githubusercontent.com/13919702/101149163-d5decf80-361e-11eb-9758-e605adbbfe94.jpg)

**Comment by ReinerBforartists** [comment]
Challenge accepted!

![challengeaccepted](https://user-images.githubusercontent.com/13919702/101194194-f417f000-365d-11eb-80e0-38cc027945b7.jpg)

**Comment by ReinerBforartists** [comment]
Extrude Manifold needs a legacy label.

![manifold](https://user-images.githubusercontent.com/13919702/101238133-6af4cd80-36de-11eb-837b-07bdee71efe2.jpg)

**Comment by ReinerBforartists** [comment]
Haven't found more. Please report them in case you find missing ones.

Closing. Fixed in master
