### ISSUE TITLE
Load UI toggle in File Browser - bug

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#203]
It seems to not be working - it still loads UI when disactivated. 

Version 1.0.0 RC1

![bforartists_2018-05-09_14-41-24](https://user-images.githubusercontent.com/35357409/39835836-0f84095c-5397-11e8-86d4-aff639f58413.png)

**Comment by Draise14** [comment]
Never mind. Found out the issue, I was stuck in the loaded UI and it was just reloading. Creatinga new scene then loading the other scene fixed this.

**Comment by ReinerBforartists** [comment]
Phew ^^
