### ISSUE TITLE
New expanded property UI style

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2033]
I'm not happy about how much space the labels steals here from the edit boxes. Just not sure how to fix this one here.

One solution would be to put the label at the top above instead in the first x row, then the x row x with just an X label , closely followed by the edit box. This would give us most space here i guess.

![morespace](https://user-images.githubusercontent.com/13919702/100542341-99d7f300-3249-11eb-8ca0-8d3f48c70090.jpg)

Mockup: 

![mockup](https://user-images.githubusercontent.com/13919702/100542347-9fcdd400-3249-11eb-84c0-8f75d841c16c.jpg)

**Comment by ReinerBforartists** [comment]
I would prefer to use this for all content where you have an x y z component then.

**Comment by iyadahmed** [comment]
Indeed this issue was mentioned earlier, I like the mock up design, solves the issue and much neater

**Comment by seanr** [comment]
I agree - much nicer layout. I'm less concerned about the vertical space
here but we would want to check that it doesn't have unintended
consequences elsewhere.

**Comment by ReinerBforartists** [comment]
Then let's use this layout from the mockup if possible.

**Comment by Draise14** [comment]
Never liked the "Location X" then the other Y then Z... I would rather the label, then the XYZ and wide sliders per the mockup. It does add some vertical, but only 3 rows.

**Comment by ReinerBforartists** [comment]
So we all agree, yay \o/

**Comment by iyadahmed** [comment]
code for new design
![image](https://user-images.githubusercontent.com/25552173/101197012-347d6b00-366a-11eb-87cd-1c0118ad803a.png)

**Comment by ReinerBforartists** [comment]
What? :D

**Comment by iyadahmed** [comment]
it looks like this, same code, hmmm
![image](https://user-images.githubusercontent.com/25552173/101198259-db163b80-366b-11eb-8c9d-9cbc017cb9fa.png)

**Comment by ReinerBforartists** [comment]
I always go the other way around. First column, then row. Maybe that's why.

col = layout.column(align = True)
row = col.row()
row.mycontent
row.myothercontent

And then you could even come much closer with row = col.row(align = True)

**Comment by iyadahmed** [comment]
alright trying now

**Comment by iyadahmed** [comment]
indeed while trying earlier, right and left alignment seemed to work only with row

**Comment by ReinerBforartists** [comment]
So it works now in the way you want it? Great. Whatever works :)

**Comment by iyadahmed** [comment]
unfortunately still not working, but trying to find a workaround

**Comment by iyadahmed** [comment]
found a workaround
![image](https://user-images.githubusercontent.com/25552173/101200907-98566280-366f-11eb-89d7-ea3477575fac.png)

**Comment by ReinerBforartists** [comment]
Hm. I personally it too complicated for this purpose. I could live with the resizing gaps. But whatever works ^^

I still don' t understand why you want to align the content at the right at all. With a row layout the whole content usually fills the whole line.

**Comment by iyadahmed** [comment]
I thought so too, but without align right it doesn't work
I tried multiple ways before arriving at this, maybe I missed something though, but this works great
![image](https://user-images.githubusercontent.com/25552173/101201286-2df1f200-3670-11eb-9ee3-0e8b7956dc08.png)

**Comment by iyadahmed** [comment]
earlier I tried putting " " in prop text, achieves the new style, but doesn't align all the way to left
![image](https://user-images.githubusercontent.com/25552173/101201693-d3a56100-3670-11eb-9729-b6c894b445f4.png)

**Comment by ReinerBforartists** [comment]
Ah now i understand. ,That's the use_property_split that is kidding you here. Use false, and the big gap should vanish :)

And you miss content here! Don't forget the locks and the decorators! But i guess you are simply not at this point yet :)

![locksanddecorators](https://user-images.githubusercontent.com/13919702/101201672-67266400-3668-11eb-8857-4f12138163e4.jpg)

**Comment by iyadahmed** [comment]
but without prop_split it shows text inside slider, sure won't forget them, it is just that dimension can't be animated or locked :)

**Comment by ReinerBforartists** [comment]
Ah, true ^^

**Comment by iyadahmed** [comment]
> Ah now i understand. That's the use_property_split that is kidding you here. Use false, and the big gap should vanish :)
> 

oh right, will try, I suppose set it to false for other than the slider itself, because that would show text inside

**Comment by ReinerBforartists** [comment]
That's where set text to "" comes in handy :)

**Comment by iyadahmed** [comment]
tried but unfortunately shows text inside
![image](https://user-images.githubusercontent.com/25552173/101202804-6f839c80-3672-11eb-8129-6986053bf280.png)

**Comment by iyadahmed** [comment]
wrote a simple function since we would use this a lot, maybe a better way will be found

**Comment by ReinerBforartists** [comment]
That's crazy, it shouldn't O_O

Blender is always good for bad surprises it seems.

**Comment by iyadahmed** [comment]
indeed XD

**Comment by ReinerBforartists** [comment]
Wouldn't it be easier to modify the c code then? This one becomes more complicated with every iteration ^^

**Comment by iyadahmed** [comment]
I think so too, but maybe it is still an interesting idea to try

**Comment by ReinerBforartists** [comment]
Yes, interesting is the right word :D
Point is, we have xyz dimension boxes in edit, pose and other modes too. And so i see double work here, which might complicate things instead of making it easier.

**Comment by iyadahmed** [comment]
indeed, but the plan is to replace transform panel in all modes but edit and pose, will give a try, everything is going well so far.

**Comment by Draise14** [comment]
> 
> 
> indeed, but the plan is to replace transform panel in all modes but edit and pose, 

Ah, I think for consistency, if a transform panel changes somewhere, it should change for all modes and instances of that panel. Just to clarify. ;)

**Comment by iyadahmed** [comment]
Indeed we should modify C instead, my bad I was thinking about the other issue

**Comment by ReinerBforartists** [comment]
One task at a time. This may make some extra work here and there, but is easier to develop, follow and maintain :)

**Comment by Draise14** [comment]
Looks like there is a pull request for this one, but has been sitting there waiting a bit. Is there anything that needs to be reviewed before being approved @ReinerBforartists ?

**Comment by ReinerBforartists** [comment]
It's a draft. And drafts cannot be merged.
