### ISSUE TITLE
Move Sub View toggles closer to the View toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#204]
As far as I know, this may change in 2.8, but I wondered if this could easily be done for the 1.0.0 RC2 version. Moving them over makes sense. 

![2018-05-09_14-42-45_li](https://user-images.githubusercontent.com/35357409/39835916-59ce3708-5397-11e8-9266-97e3ab39cb23.jpg)

**Comment by ReinerBforartists** [comment]
I know what you mean. The element jumps around, dependant of how much text menu items you have. But it's a bit too late to redesign the whole concept now, whith 2.8 in front of the door, where this changes anways. Which is first the text menus, then all other elements. 

Can't do that. Closing.
