### ISSUE TITLE
Release - Add the mac version to the release pages on Git

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2041]
# Request
Can we get the Mac versions added to the Github releases, like this one? 

[Github Release Example](https://github.com/Bforartists/Bforartists/releases/tag/v2.6.0 )

**Comment by ReinerBforartists** [comment]
Ah i knew i missed something. Uploading the ones that i have ...

**Comment by ReinerBforartists** [comment]
Done. Thanks for the reminder :)
