### ISSUE TITLE
Node Editors - tooltips for the single nodes

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2044]
The add menu in the node editors does not have proper tooltips for the single nodes so far.The tooltips all says "Add a node to the active tree". A short description of what the node does would do miracles here.

I failed at this one before, but that's no reason not to try it again ...

![tooltip](https://user-images.githubusercontent.com/13919702/100849539-ff62f400-3482-11eb-9799-c5a529603080.jpg)

**Comment by iyadahmed** [comment]
since 2.81 It is possible to dynamically change operator tooltip by defining "description" classmethod
found answer here
https://blender.stackexchange.com/questions/56727/changing-tooltip-for-menu-entries-which-use-the-same-operator
which mentioned this link
https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Python_API#Operators

by modifying release/scripts/startup/bl_operators/node.py
![image](https://user-images.githubusercontent.com/25552173/105554776-b441c080-5d10-11eb-8e8a-35a024ddd577.png)

result 
![image](https://user-images.githubusercontent.com/25552173/105554671-7e9cd780-5d10-11eb-9132-333c4830b159.png)

**Comment by ReinerBforartists** [comment]
@iyadahmed , shall we go the def description route here? I remember you mentioned somewhere that the tooltips are already defined somewhere, but are simply blank for now.

**Comment by ReinerBforartists** [comment]
Ah, found it. https://github.com/Bforartists/Bforartists/pull/2308

> PS: NOD_static_types.h already has a place for description for each node which we can use for this task #2044
> description can be then accessed in NodeItem just like label and icon
> bpy.types.Node.bl_rna_get_subclass(self.nodetype).description

**Comment by ReinerBforartists** [comment]
Hm, i am lost. I have added the def description to the node.py as shown. But i have no idea where i should add our node descriptions then.

Halp :(

**Comment by ReinerBforartists** [comment]
This should work, shouldn't it? But throws me an error that NODE_OT_add_node has no attribute 'arg'

```
#Input nodes tab, connect panel. Just in shader mode
class NODES_PT_Input_connect(bpy.types.Panel):
    """Creates a Panel in the Object properties window"""
    bl_label = "Connect"
    bl_space_type = 'NODE_EDITOR'
    bl_region_type = 'UI'
    bl_category = "Input"
    
    arg: bpy.props.StringProperty()
    
    @classmethod
    def description(cls, context, properties):
        return properties.arg

    @classmethod
    def poll(cls, context):
        return (context.space_data.tree_type == 'ShaderNodeTree') # Just in shader mode

    @staticmethod
    def draw(self, context):
        layout = self.layout#### Textbuttons
        default_context = bpy.app.translations.contexts.default

        scene = context.scene

        preferences = context.preferences
        addon_prefs = preferences.addons["bforartists_toolbar_settings"].preferences

        ##### Textbuttons

        if not addon_prefs.Node_text_or_icon:

            col = layout.column(align=True)

            props = col.operator("node.add_node", text=" Add                   ", icon = "NODE_ADD_SHADER").arg = 'this is my tooltip'
            props.use_transform = True
            props.type = "ShaderNodeAddShader"
```

**Comment by ReinerBforartists** [comment]
Doesn't work at all it seems. Maybe since we have already a tooltip here?

![noarg](https://user-images.githubusercontent.com/13919702/114265746-d59e7880-99f2-11eb-8d39-4985e467584e.jpg)

**Comment by ReinerBforartists** [comment]
Unassigning. I need help here :)

**Comment by ReinerBforartists** [comment]
I'm still in halp status here. @iyadahmed , do you have an idea what i do wrong here, besides everything? ^^

**Comment by iyadahmed** [comment]
Ah no worries ^^, We just need to edit 

source\blender\nodes\NOD_static_types.h

It has a UI Description placeholder for each node

after that we need to edit NodeItem and node add operator 

And just like label property, we do same for description property

Description defined for each node can be accessed in Python using

bpy.types.Node.bl_rna_get_subclass(self.nodetype).description

![image](https://user-images.githubusercontent.com/25552173/115370413-56b2f800-a1c9-11eb-927e-d7fda20dfba6.png)

**Comment by ReinerBforartists** [comment]
I tried and failed at this. It doesn't show the tooltip :'3

**Comment by iyadahmed** [comment]
> I tried and failed at this. It doesn't show the tooltip :'3

Oh, hmm, we should also add a description method to the Node add operator, that would return the node description, just like title

**Comment by ReinerBforartists** [comment]
I hate it when i am not clever enough. It sounds so easy when you talk about it. I guess this job is something for you then ^^

**Comment by iyadahmed** [comment]
it sounds easy but it is not XD, we could work on it in very near future

**Comment by ReinerBforartists** [comment]
First finish the manual. I wait that i can continue here :P

**Comment by iyadahmed** [comment]
Agree ^^
