### ISSUE TITLE
Compositor - Add icons to nodes headers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2046]
# Request
The shader editor now has icons in the headers of the nodes in the editor. Thanks @iyadahmed  ! But now the compositor also has the iconized toolshelf but no icons in the header. 

# Task
Do the same from the Shader Editor to the Compositor Editor

### Note
This is similar to task #1609

**Comment by iyadahmed** [comment]
should the preview button icon be replaced with the icon, it doesn't feel right having different icons for same functionality
![image](https://user-images.githubusercontent.com/25552173/102676480-6d5b2b00-41a6-11eb-946f-abc06a45505f.png)

**Comment by ReinerBforartists** [comment]
Hm. One icon makes more sense. On the other hand, having a dedicated preview button makes also sense. I keep it in your hands, im am green with both solutions. With a tendency to keep both buttons.

**Comment by ReinerBforartists** [comment]
Ah, the reason why i think that two icons are better here is that you can distinguish then that this special node has a preview window that can be hidden, and potentially is.

**Comment by iyadahmed** [comment]
Agree with two icon solution, currently it is set to material icon, maybe we could change this in future, would be another task

**Comment by ReinerBforartists** [comment]
Yes. Please make another task for it :)
