### ISSUE TITLE
Shader Node Editor - Missing Nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2047]
# Issue
We've found a couple of new nodes that aren't shown in the node toolshelf panels. 

1) Hair principled
2) dispalcement and vector displacment
3) Vector rotate
4) Specular
5) IES

# Task
Add them with icons to the toolshelf panels. 

### Notes
Some of these are Cycles only, like the first two. Others are light based only, like IES. 
Should they be shown when in Eevee mode?

**Comment by ReinerBforartists** [comment]
Good question. I will look at it.

**Comment by Draise14** [comment]
Since you can have hybrid materials to go both to eevee and cycles, maybe we should keep them both together in both modes - come to think of it.

**Comment by ReinerBforartists** [comment]
Usually the ones for Cycles only are hidden when Eevee is chosen.

**Comment by ReinerBforartists** [comment]
Fixed in master
