### ISSUE TITLE
Concept: Toggle visibility of panel content when disactivated in header toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#205]
Many panels in the UI are greyed out when they are disactivated - this creates a lot of useless noise. It would be nice to have them **hide** automatically if the panel header toggle is disactivated - saving the extra UI toggle work to close the extra UI noise after you've disabled it to work without headaches. 

![bforartists_2018-05-09_14-45-32](https://user-images.githubusercontent.com/35357409/39836051-c51c3c58-5397-11e8-9b31-f47b6529cd7b.png)

I have attached an image of how this is making so much noise when turned off (implying I myself should clean up the UI to keep working). 

_I doubt this will be anything changed for 2.8 and it would still be a new feature for future BFA. This feature is just.. a concept that might make BFA better and less noisy even with panels open._ 

**Cons**
The collapse Arrow would be irrelevant if everything is hidden. In this case, maybe adding a feedback note "Disabled" into the panel and hide all the content would make sensewhen the header toggle is disactivated (if open). When closed, it's normal functionality.

**Comment by ReinerBforartists** [comment]
Well, in this case we cannot hide the props away, since all props in the panel are affected. And the greyed out elements have the purpose to tell the user that the whole panel is currently deactivated. Users would think it is broken when we hide them away now.

Can't do this. Closing.

**Comment by Draise14** [comment]
Option 1: A "Disabled" icon or notification "Activate to show" in the panel that would replace the greyed out items and hide all the rest could substitute, essentially automatically collapsing. It would be consistent with some of the UI visibility toggles when you activate/disactivate on tickbox. 

Option 2: Making the panel autocollapse and open when you disactivate/activate?

**Comment by ReinerBforartists** [comment]
The "Disabled" icon is the dechecked checkbox. And the greyed out panel content.

And option 2, besides that it is technically not possible, activating it does not mean that you want to tweak settings in it.
