### ISSUE TITLE
Separated tooltips - Implement the different tooltips in the original operator

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2052]
I have separated quite a few tooltips by adding a new operator in the python UI files, and calling the operator with its arguments to perform the other tool. This works just fine. The more elegant way would be to separate the tooltips in the original operator already. Benefit: fewer classes, fewer code. Also worth a commit to the Blender code base then. And this way we might catch other tooltips that we haven't separated yet.

This task has low priority though. It already works. So no improvement to the user really.

Example Blender code how to solve this in the c code base already. I hope it is really this easy: https://developer.blender.org/rB7bab87c119f4bef0c52cdadeb84a86336193296c

![separated](https://user-images.githubusercontent.com/13919702/101151842-8d291580-3622-11eb-8aee-1ea45c694d8a.jpg)

**Comment by ReinerBforartists** [comment]
There is also an api change that allows to use separated tooltips for one operator. See https://blender.stackexchange.com/questions/207421/blender-2-8-how-to-execute-an-operator-in-another-window/207995#207995
and
https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Python_API#Operators

**Comment by iyadahmed** [comment]
> There is also an api change that allows to use separated tooltips for one operator. See https://blender.stackexchange.com/questions/207421/blender-2-8-how-to-execute-an-operator-in-another-window/207995#207995
> and
> https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Python_API#Operators
> 
> But this just helps when the original class is already python.

Ah yes didn't see this, just found same link, can be used to fix #2044

**Comment by ReinerBforartists** [comment]
Ah, cool :)

**Comment by ReinerBforartists** [comment]
Let's have a look how much python operators we can kick out here and implement the tooltips in the C part instead.

**Comment by ReinerBforartists** [comment]
Ah, we need to fix our keymap then too. We have quite a few hotkeys mapped to the python operators that we have created to separate the tooltips.

![hotkeyproblems](https://user-images.githubusercontent.com/13919702/110202724-d4fe4980-7e6a-11eb-8ba2-5735a5ca7f96.jpg)

**Comment by ReinerBforartists** [comment]
We have double A as a secondary hotkey for select none. I think this was a design decision at one point since this was the old method. But this hotkey is not defined in the UI. And one hotkey should be enough.

Shall we keep it, or shall we remove it? Who is still using double A , and not ctrl A?

**Comment by ReinerBforartists** [comment]
mask.select_all

This one was a bit more work.

![fixed](https://user-images.githubusercontent.com/13919702/110215185-b8810200-7ea8-11eb-9982-06e7380b7aa0.jpg)

**Comment by ReinerBforartists** [comment]
Related: File menu, clean up sub menu - add proper tooltips #2272

**Comment by ReinerBforartists** [comment]
Related: Sculpt mode - mask menu - separate tooltips for the mask slice operators #2292

**Comment by ReinerBforartists** [comment]
Particle edit select menu has no hotkeys for select all none inverse. Will go into its own task.

![nohotkeys](https://user-images.githubusercontent.com/13919702/113408623-f2fa9380-93af-11eb-9668-484f8b9600e8.jpg)

**Comment by ReinerBforartists** [comment]
Wrong alert. The hotkeys shows when the menu is active, with particle type hair.

**Comment by ReinerBforartists** [comment]
>3

Why can't they use the same identifier name everywhere? -.-

![notdeclared](https://user-images.githubusercontent.com/13919702/113475905-446e5580-9478-11eb-89d5-b72beda243cb.jpg)

**Comment by ReinerBforartists** [comment]
Not to catch. I can just guess that it misses an important include somewhere. But i cannot find out which one. Skipping this part for now.

source\blender\editors\sculpt_paint\paint_utils.c - PAINT_OT_face_select_all

**Comment by ReinerBforartists** [comment]
The missing include for paint.face_select_all is most probably #include "ED_select_utils.h". I ran into the same problem with paint.vert_select_all. And here the include fixes the problem.

**Comment by ReinerBforartists** [comment]
That was it. No more tooltip workarounds. 

Fixed in master.

**Comment by iyadahmed** [comment]
> That was it. No more tooltip workarounds. 
> 
> 
> 
> Fixed in master.

Amazing work 👌

**Comment by ReinerBforartists** [comment]
Thanks. But the solution came as usual from the Blender devs. I have just applied it to Bforartists :)
