### ISSUE TITLE
Convert some C UI code into Python

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2054]
Currently potential goals:
* 3D View transform panel (except edit modes)
*  Modifiers UI

**Comment by ReinerBforartists** [comment]
Whatever works :)

The edit mode made me stop a similar project a few years ago ...

**Comment by ReinerBforartists** [comment]
Closing this task since we agreed to do the changes at the C code.

**Comment by iyadahmed** [comment]
I really think we could do it, there's no contradiction, we can modify C for new design, and have this panel in Python too, it would be a copy of Object prop one
but closing for now is ok, may be reopened in future

**Comment by ReinerBforartists** [comment]
Sure. But there is this litte gap between could and should ^^

I can understand your reasoning. But it is better this way. Every difference between Blender and Bforartists should have a good reason. And we can reopen the task at a later point when this good reason arrives :)

**Comment by iyadahmed** [comment]
I feel the urge to reopen this issue again, at least as experimental, the main reasons behind this are:
* Better maintainability
* More consistency in UI code and appearance
* Easier to modify in future

**Comment by ReinerBforartists** [comment]
Okay. No guarantee that this goes into the master then though :)

I still think that we should bring down the number of tracker entries a bit more before tackling new issues. We have a few heavy ones in the list, like bringing back the tabs in the toolshelf :)

**Comment by iyadahmed** [comment]
Agree, alright we could close it for now then open later
