### ISSUE TITLE
Keymap - turn off Repeat in the default keymap

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2055]
At one point Blender introduced a Repeat checkbox for the hotkeys. We have now a few key items where repeat is on by default. But then the hotkey flickers. We need to find them, and to turn them off. This is for example the case with the Transform Modal Map.

![repeat](https://user-images.githubusercontent.com/13919702/101261921-ec7a4900-373a-11eb-9d84-3a8770b34779.jpg)

**Comment by ReinerBforartists** [comment]
Basically all our key menu items have repeat on now, while the Blender keymap has them all off. Not to distinguish anymore where it makes sense and where not. Our keymap is in this regards destroyed. Unfunny.

**Comment by ReinerBforartists** [comment]
This moment when you want to burn down everything ... ^^

**Comment by Draise14** [comment]
Search and Replace in the hotkey py?

**Comment by Draise14** [comment]
> 
> 
> This moment when you want to burn down everything ... ^^

Yeah.. the repeat, not sure the use case for this. I guess we can turn them all off, then turn them on in any specific use case. It might be for things like..... transform nudging increments? No idea.

But also! Rest your wrists! Take it easy.

**Comment by ReinerBforartists** [comment]
There are some cases where repeat true is useful. Like increase selection. So a simple replace did not do it. I have ran it against the default Blender 2.7x keymap now, which is in big parts similar to the BFA keymap. And eliminated a ton of the repeat: true entries. Let's have a look how it turns out.

And yes, i should have a break :( . Doing it now ... :)

**Comment by ReinerBforartists** [comment]
Fixed in master
