### ISSUE TITLE
Vertex Paint, Grease Pencil Draw, Texture Paint Mode - Tool Header UX - Expose colour swap and secondary colour

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2057]
# Request
![bforartists_RbNPCQVCNp](https://user-images.githubusercontent.com/35357409/101275115-3a11a880-3771-11eb-901e-7c585dcbf4f2.png)

Right now, to do a quick colour switch and select the secondary colour, and also to set the colour of the secondary, you need the properties shelf open, making the header brush settings redundant when it comes to colour. Ideally you could use the property shelf for other view settings or addon settings and stick to the header for the brush settings, but now you need both open to effectively paint with two colours creating a lot of unused clutter and double entries just to paint colours. 

In other painting software exposes a button to swap and both colours in the header, and this is extremely handy. 
![image](https://user-images.githubusercontent.com/35357409/101275184-a5f41100-3771-11eb-8061-b8a56c14cad7.png)
_taken from Krita_

# Task
- Investigate if possible
- Check how to streamline the UI to not clutter more than two or three icon widths, right now the colour tab is usually 4 icons wide. 
- Implement the mockup

## Mockup of suggestion:
![image](https://user-images.githubusercontent.com/35357409/101275276-6679f480-3772-11eb-8d0f-b3a3d0773f8f.png)
Here is a rough mockup, but basically expose the two colours with the colour pickers dropdowns and the swap colour button, just like the property shelf.

**Comment by ReinerBforartists** [comment]
Draise, have you actually clicked at the color field once? It exposes the whole color panel, Where you can pick the palette, and swap the colors.

I could just implement the two color props and the toggle. But then you just get the normal color dialog, without the palette.

Or we have in the first color the palette. And in the second color just the color wheel.

Or we just implement the second color switch.

Or we leave it as is ^^



![colorpanel](https://user-images.githubusercontent.com/13919702/101895997-9416d180-3ba8-11eb-8c87-1c60ab0e1349.jpg)

**Comment by Draise14** [comment]
> 
> 
> Draise, have you actually clicked at the color field once? It exposes the whole color panel, Where you can pick the palette, and swap the colors.
> 

**Vertex Paint Mode:**
Yes, that is how I do my screen captures. The default colour from the header does the colour wheel only, no palettes, swap or dual colour or more. Unless there is a new dev build that has fixed this automatically, I only get the colour wheel, one colour, and no swap button. 

Screen Capture:
![image](https://user-images.githubusercontent.com/35357409/101911842-eba84380-3b8e-11eb-81b2-d3355a21ee3d.png)

**Texture Paint Mode:**
![image](https://user-images.githubusercontent.com/35357409/101912424-b819e900-3b8f-11eb-8ccb-e1db0c814c5f.png)

Same state. 


What has been implemented so far? 

This task is to show two colours and the swap button in the header. There is another task to discuss what to show when you click on a colour here: #2058 as a separate task delinked from this one.

**Comment by Draise14** [comment]
I've updated the description, maybe this is why the confusion. 

This one is to expose 2 colours and the swap in the header only. 

Dropdown consistency and design is separate in #2058. What happens when you select/click a colour can be discussed in the other task, it already has a mockup and different feature request.

**Comment by ReinerBforartists** [comment]
Now i am REALLY confused :D

**Comment by Draise14** [comment]
> 
> 
> Now i am REALLY confused :D

![image](https://user-images.githubusercontent.com/35357409/101932048-3c786600-3ba8-11eb-9609-391b647588ca.png)
This image is aweseome, would be great to use.. but neither the official nor dev builds have this. It is currently ONLY one colour and colour wheel when you click on that one colour.

**Comment by ReinerBforartists** [comment]
Okay, then let's use the simple color picker for the second color. That's what i wanted to know :)

**Comment by ReinerBforartists** [comment]
Ah, this is always different solved, dependant in what mode and with what object -.-

**Comment by ReinerBforartists** [comment]
Geez, how unintuitive can you make the grease pencil drawing. I need to go to OBJECT mode to see what vertex color i DRAW in DRAW mode. In draw mode it just shows the material color. How can you even paint with that?  -.-

Anyways, this is how it looks with a grease pencil object in draw mode now.

Continuing with the mesh object modes and panels now. But i fear the worst. I remember that this color picker is a C prop ...

![vertexcolor](https://user-images.githubusercontent.com/13919702/101934786-5a60bd80-3bde-11eb-8a71-ed675b8649fa.jpg)

**Comment by Draise14** [comment]
The dual colour is looking nice. But yes, the workflow for the GP is really not thought out well.

**Comment by Draise14** [comment]
> 
> 
> Just found out how to show the vertex color in the viewport in object mode too. You need to be in Viewport Shading Material. Another riddle solved ^^

These things really need optimization.. where if you click it, it should just.. work.. toggle to the right mode, chain the operators a bit for a nicer UX. I can imagine many artists kinda go.. this is "broken".. Maybe this could be another task.

**Comment by ReinerBforartists** [comment]
Yes. Definitely. But they still change ways too much at the grease pencil. And when we start to implement our own changes then we are always at fixing this. And it is code wise implemented in a way that makes me cry anyways. Which leads me to the rest of this task.

Bad news for the mesh and similar object types. It is an so called unified panel. Which in Blender case just means the bits are cluttered across several files and classes, and everything is somehow connected to each other. Hard to access, even harder to change.

So for now just the grease pencil has this solution implemented. No idea if i can manage to modify the rest.

**Comment by ReinerBforartists** [comment]
Was quite a hunt, but Gotcha!

Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/101979502-da7a3800-3c5d-11eb-8058-9ae61ccaa9f8.jpg)

**Comment by Draise14** [comment]
Oooooohhhh yeaaaaaaah!!!
