### ISSUE TITLE
Painting Modes - Expose linked Color Palette in all modes per default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2059]
# Request
Grease Pencil Vertex Paint Mode
![image](https://user-images.githubusercontent.com/35357409/101275653-33853000-3775-11eb-9a27-346d05632621.png)

Other paint modes
![image](https://user-images.githubusercontent.com/35357409/101275765-4815f800-3776-11eb-8bc6-a8398e887f85.png)

The grease Pencil Vertex paint mode comes with a built in color palette, and the palette manager is built in with the rest of the UI - but when you go into Vertex Paint or Texture paint mode, this palette is not exposed in the UI. 

It's a simple default layout setup inconsistency. 

# Task
Expose the color palette in all defaults. 

- Select the colour palette in other paint modes
- Save the startup

**Comment by ReinerBforartists** [comment]
To clarify, 

Grease Pencil
The Draw mode starts with material based colors first. Switch to vertex and the palette is showing when you click at the Palette subpanel. Is this your request? That this sub panel already shows expanded?

Mesh Object
We have the palette in Vertex Paint and in Texture paint. But we don't want the Color Palette subpanel to be expanded. But to show the palette when we expand the Color subpanel, right?

**Comment by Draise14** [comment]
Yeah, just show the pallete as loaded where relevant/expose the linked colour palette (Texture Draw, Vertex Paint, Grease Pencil Vertex Paint) - the panel doesn't have to be open per default, put the palette should be loaded and selected in all relevant drawing modes - accessible without guessing it already exists in other draw modes. 

Right now it only shows selected in Grease Pencil Vertex Paint. 

We can make another task to see if we should keep this panel open on default if you'd like. Right now it's just selecting it in the relevant drawing modes, save the startup, and.. carry on. =)

**Comment by ReinerBforartists** [comment]
Oki. Will do :)

**Comment by ReinerBforartists** [comment]
Fixed in master
