### ISSUE TITLE
Iconize the Transform Orientation dropdown

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#206]
![bforartists_2018-05-09_14-53-53](https://user-images.githubusercontent.com/35357409/39836392-d676de94-5398-11e8-9bd5-8777dfcac155.png)

Might be nice to have some icons there.

**Comment by ReinerBforartists** [comment]
That's a task for 2.8

Postponing.

**Comment by ReinerBforartists** [comment]
Blender devs already fixed that for us in 2.80. Closing.

![transformicons](https://user-images.githubusercontent.com/13919702/52771815-36121500-3037-11e9-9137-ad8d421ad5b5.jpg)
