### ISSUE TITLE
Grease Pencil - Draw Mode - Hotkey - Change draw mode to "Shift+2" like Pose Mode with armatures

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2060]
# Request
![bforartists_hTALmxlIeK](https://user-images.githubusercontent.com/35357409/101275808-95926500-3776-11eb-82c5-ff21c9a7d65d.png)

In armatures, you can press SHIFT+2 to get into it's custom mode to pose, a common mode to use. It was 7, but we changed to Shift+2 for ergonomic reasons (closer to left hand)

Can we do the same for Draw mode for the Grease Pencil object type? 

**Reason**
1. Consistency with the extra mode from a custom object. 
2. It's more ergonomic, to reach for the left hand
3. It's a priority mode to use with the grease pencil. 

# Task
Change the current draw mode hotkey to Shift+2

**Comment by ReinerBforartists** [comment]
Fixed in master
