### ISSUE TITLE
Compilation warning - missing format arguments for BLI_sprintfN

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2064]
![image](https://user-images.githubusercontent.com/25552173/101284203-7849af00-37e7-11eb-94d8-03610828898c.png)

**Comment by ReinerBforartists** [comment]
O_O

**Comment by ReinerBforartists** [comment]
Related: Compilation warning - use *UNUSED() for unused arguments #2065

**Comment by iyadahmed** [comment]
I think Blender fixed the tooltip issue
https://github.com/blender/blender/blob/3d0b65f89b2ddad5141acb00685885a995fdc9f3/source/blender/editors/interface/interface_region_tooltip.c#L814

**Comment by iyadahmed** [comment]
apparently the if statement was written to fix an issue that was caused by a previous commit #1031
![image](https://user-images.githubusercontent.com/25552173/101318970-d9b26200-3869-11eb-9b12-edc0d86d9a33.png)

the if statement, was added here #1293,
should we revert this and use the AND statement instead?, like it was before

**Comment by ReinerBforartists** [comment]
Does it harm? If not i would keep it in the Blender way.

**Comment by iyadahmed** [comment]
it doesn't, alright, writing Blender way now

**Comment by ReinerBforartists** [comment]
Maybe i misunderstand something here, but why do you want to change it at all? Isn't it already the Blender way?

**Comment by ReinerBforartists** [comment]
I haven't understood this issue, sorry. As told, in the pull request, this is our own code. It is meant to show the tooltip title everywhere. When you revert it then you remove our feature. Not good ^^

There must be a way to remove the warning without to kill our feature. Or when in doubt, leave it alone. Windows doesn't even moan.

And could you please make one pull request per issue?

**Comment by iyadahmed** [comment]
> I haven't understood this issue, sorry. As told, in the pull request, this is our own code. It is meant to show the tooltip title everywhere. When you revert it then you remove our feature. Not good ^^
> 
> There must be a way to remove the warning without to kill our feature. Or when in doubt, leave it alone. Windows doesn't even moan.
> 
> And could you please make one pull request per issue?

oh ok, sure, will do, I think I did now, seeing messages late, anyways, I saw the comment about the feature, hmmm, I think there's a way, let me try
