### ISSUE TITLE
Compilation warning - use *UNUSED() for unused arguments

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2065]
![image](https://user-images.githubusercontent.com/25552173/101284292-e68e7180-37e7-11eb-9690-80e41eb6003f.png)

**Comment by ReinerBforartists** [comment]
O_O

**Comment by ReinerBforartists** [comment]
I have not a single warning :D

The toolbar editor is from me though. It can be that they changed once again something at the editor implementations. The Blender devs updates their editor types then. But our own editor then follows still the old rules. I will have a look if there was a general change somewhere.

![notasinglewarning](https://user-images.githubusercontent.com/13919702/101286714-628ab880-37ec-11eb-88bf-f7734385a630.jpg)

**Comment by ReinerBforartists** [comment]
First task in question

https://developer.blender.org/D8459

**Comment by ReinerBforartists** [comment]
I still have the problem that i don't have any warning. Iyad, where do you get this one from?

**Comment by ReinerBforartists** [comment]
Unassigning for now. First comes the update of the manual. And i am unfortunately disabled at the moment. My hand makes trouble. Too much, simply too much. I need a rest for a few days. My body says no. So feel free to fix this warning :)

**Comment by ReinerBforartists** [comment]
Nope, i simply don't get this warning. And i can just fix what i can reproduce.

The warnings may be valid in case we want to show content in the toolbar area. I have never dived this deep into creating the editor to show content in the window too. For me the header was enough. And i use the same valid code as used in other editor types. Like the graph editor.

![noproblem](https://user-images.githubusercontent.com/13919702/101288067-ba2d2200-37f4-11eb-88e4-0360ffb3ce40.jpg)

**Comment by iyadahmed** [comment]
> I still have the problem that i don't have any warning. Iyad, where do you get this one from?

hmm, I just got it from the terminal while doing a full recompile

**Comment by iyadahmed** [comment]
> Unassigning for now. First comes the update of the manual. And i am unfortunately disabled at the moment. My hand makes trouble. Too much, simply too much. I need a rest for a few days. My body says no. So feel free to fix this warning :)

don't worry I think I got this one ^^, oh I hope you get better soon
