### ISSUE TITLE
Point Cloud - Properties Editor - Add Attribute menu needs icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2071]
New functionality, old problems ...

We need to iconize this new menu here.

![attmenu](https://user-images.githubusercontent.com/13919702/101335702-d9ba5e00-3879-11eb-9f33-2946e8e75c4e.jpg)

**Comment by ReinerBforartists** [comment]
Custom label does not need three dots. One of those things that i have never understood. What is these three dots good for?

**Comment by iyadahmed** [comment]
I honestly don't know, I think they are just like that for no reason

**Comment by Draise14** [comment]
Points to make a "cloud" with lineart? Like.. points made of line art... yeah.. Needs a new design.

**Comment by ReinerBforartists** [comment]
I can't even ...

Try to add an icon here. Can't they just one time implement the same thing in the same way instead of using yet another brainfart method? -.-

![wtf](https://user-images.githubusercontent.com/13919702/101607144-832d5b00-3a04-11eb-8149-1cb4a98eac41.jpg)

**Comment by ReinerBforartists** [comment]
Found a way. Fixed in master.

![fixed](https://user-images.githubusercontent.com/13919702/101611569-f5ed0500-3a09-11eb-8c5e-bdd94846f71e.jpg)
