### ISSUE TITLE
Fix empty space in some tooltips

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2075]
related #2064 
file of interest:
source/blender/editors/interface/interface_region_tooltip.c
![image](https://user-images.githubusercontent.com/25552173/101349955-cff32380-3896-11eb-9993-9a89b0b3f096.png)

**Comment by ReinerBforartists** [comment]
It's just five pixels. Dunno if it is really worth the investigation.

**Comment by iyadahmed** [comment]
> It's just five pixels. Dunno if it is really worth the investigation.

agree, maybe we keep it as low priority.

**Comment by ReinerBforartists** [comment]
I'm closing this one as won't fix. Functionality is given. The five more pixels are by most people not even to notice. So let's leave it alone.
