### ISSUE TITLE
Keymap - improve tablet navigation

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2081]
From one of the youtube videos:

> Have you plans to optimize the keymap for navigation also for Graphic Tablets ? Because on a stylus, there is no scroll wheel. You can only pan zoom by clicking the middle mouse button mapped on one of the Pen keys. But in Bforatist this key is used to pan. 
> There is a special tablet optimated mode in Blender, but this maps the ALT Key to navigations. While this is not bad in gerneral, in Blender this setting conflicts with the heavly used ALT Key for loop selection and inverting some tool functions. But the answer from Blender to an Bug report said its a known conflict but no problem at all.

I have unfortunately no tablet. What keys should change here?

**Comment by Draise14** [comment]
Right now my work around for this was map one of the two side clicks to middle, and CTRL+Middle would zoom. Right works as expected, and tap for Left. We have this already configured with BFA hotkeys, so it's a tablet configuration.

**Comment by ReinerBforartists** [comment]
Ah, i see. So there is nothing really to fix or to improve for us here, right?

The posting is six months old, it was a comment at one of the youtube videos. I guess it doesn't really make sense to post an answer there ...

**Comment by ReinerBforartists** [comment]
Okay. Closing. Thanks :)
