### ISSUE TITLE
Node Editor - Rename UX on nodes/frames should also rename visible label

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2084]
# Issue
![image](https://user-images.githubusercontent.com/35357409/101522908-dc8a8100-3955-11eb-8354-f51b164cd64e.png)

When renaming a frame, node or anything in a node editor (rename operator or F2), you name it, but not the label. So visually, you see nothing. This is rarely useful unless coding a script. For an artist, I want to name the node, frame or anything with one operation. 

# Task
- Check and see if it's possible to make the operator chain to also rename label. 
- Implement it in the general GUI.

**Comment by ReinerBforartists** [comment]
Does it work in Blender?

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/101524775-5facd680-3958-11eb-9c24-9d315d577f99.png)

Yes.. just tested in 2.91, and it only renames the label. *shock*

Looks like something in BFA is not configured in the operator variables.

**Comment by ReinerBforartists** [comment]
So it works in Blender?

**Comment by iyadahmed** [comment]
> So it works in Blender?

Just tested, it works in Blender

**Comment by ReinerBforartists** [comment]
Odd. Then it should work in Bforartists too. We have the same code.

**Comment by ReinerBforartists** [comment]
Fails in Blender too from what i can say. Tried to rename the Principled node. And the name does not arrive.

So under what circumstances does it work in Blender and in Bforartists not? In what node editor? We have more than one. With which node? And what are the exact steps to reproduce?

![blender](https://user-images.githubusercontent.com/13919702/101625815-4bcaa880-3a1c-11eb-90df-afba70f152af.jpg)

**Comment by Draise14** [comment]
This applies for all node based editors, including those of addons. 

Bforartists 2.6.0 (Bforartists Hotkeys)
1. Create Cube and Select
2. Create Material in Shader Editor
3. Press F2 to rename any selected node, test on Principled
4. Renames name, not label. Panel indicate "Rename label"
5. Check Item>Node to verify

Blender 2.91.0 (Blender Hotkeys)
1. Select Cube
2. Create Material in Shader Editor, test on Principled
3. Press F2 to rename any node
4. Renames Label. 
5. Check Item>Node

Works in Blender, doesn't in BFA. Yes, the panel code and operator call is the same, so I assume the C operator must be a tad different.

**Comment by ReinerBforartists** [comment]
Ah, now i managed to reproduce it. Thanks friends :)

Blender changes the label. Bforartists changes the name though. And so the label remains unchanged. I have just no idea why ^^

Let's have a look at the hotkey F2 ...

![bfa](https://user-images.githubusercontent.com/13919702/101628151-ac0f1980-3a1f-11eb-8300-70880b644bf8.jpg)

![blender](https://user-images.githubusercontent.com/13919702/101628161-af0a0a00-3a1f-11eb-90ea-3497faa5ac58.jpg)

**Comment by ReinerBforartists** [comment]
It's not the hotkey. It just calls the TOPBAR_PT_name popup.

**Comment by ReinerBforartists** [comment]
Once more i have no idea what the problem is. And not even an idea how to catch this one.

**Comment by Draise14** [comment]
It is bizzare.

**Comment by Draise14** [comment]
Found it! It's just a single entry in the space_topbar.py. 

Instead of "Name", it should be "Label" at line 717

This has been reported to Blender before. Found the task and relevant code. 

Looks like something slipped through.
[Differential Patch](https://developer.blender.org/D4631)

**Comment by ReinerBforartists** [comment]
Excellent catch :)
