### ISSUE TITLE
Geometry Nodes Editor - add the nodes content to the sidebar, create new icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2096]
We have a new editor type. The Geometry Nodes Editor. It comes with new nodes. They should be in the sidebar too. And we need new icons here. This requires most probably to extend the iconsheet. We run out of space.

![geometrynodeeditor](https://user-images.githubusercontent.com/13919702/102019006-063a1280-3d71-11eb-8554-ab78d968af02.jpg)

**Comment by Draise14** [comment]
Huzzah, yeah, can't wait to have this intergrated the BFA way, but yes.. moar icons.

**Comment by ReinerBforartists** [comment]
First the manual. Very time consuming job. And my hands are still in trouble. So it will take a while.

**Comment by ReinerBforartists** [comment]
Fixed in master

![addsidebar](https://user-images.githubusercontent.com/13919702/103799305-3365a200-504b-11eb-9d21-722776138fe9.jpg)
