### ISSUE TITLE
[Feature Request] Generate Navigation Mesh

### ISSUE THREAD

**Issue by ivnnv** [Bforartists/Bforartists#2097]
The old Blender Engine used to have a great generation tool for navigation meshes. As the game engine was completely removed starting on Blender 2.8, theres nothing like that in the current build Bforartists fork against.

But the code is there! (in the old sources of course), I dont really know the amount of work it will require to import this feature into the actual codebase, but it its relatively easy, it would be a great feature to implement as this is a common problem people have in the game industry (specially now when implementing AI npc's) as theres no much options out there to "automatically" generate navigation meshes (other than [Recast](https://github.com/recastnavigation/recastnavigation), but it is a complex thing to compile and run).

![nav mesh](https://user-images.githubusercontent.com/23552631/102020595-68e3dc00-3d7a-11eb-8dcc-6450be2a9285.png)

Demo on how easy was to generate a Navigation Mesh in Blender Game Engine 2.79: https://youtu.be/aMWeTXL98mM?t=288

**Comment by ReinerBforartists** [comment]
Hi,

Thanks for the idea. This idea has lots of pros and cons. Biggest con is, there is no need for it anymore. The game engine is removed. And navigation meshes are usually better created in the game engine where you use it. So what would be the real benefit then?

**Comment by ivnnv** [comment]
Well technically a navigation mesh is just another kind of object at the end and then you can manipulate it and create something else from it, indeed it will be mainly used for game physics but it could also be used for artistic purposes.
Anyway yes it makes sense to at least trying it to have it back on Blender itself, I'll ask there if that could be possible.

**Comment by ReinerBforartists** [comment]
Okay, closing. And good luck with the feature request :)
