### ISSUE TITLE
Armature Edit - Confusion with Bone Size and Envelope Size

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2098]
# Issue
![image](https://user-images.githubusercontent.com/35357409/102167169-d87dc800-3e5b-11eb-9632-745a52cd092c.png)
There seems to be a bit of a confusion when it comes to using the toolshelf when changing bone sizes and envelope. One does envelopes, the other bone size, but the bone envelope is changing the size and the change size is changing the envelope. 

They may be inversed

[Video Showcase](https://youtu.be/KmRgGZ3SPT0)

# Task
- Verify
- Fix

**Comment by ReinerBforartists** [comment]
And in Blender?

**Comment by ReinerBforartists** [comment]
You need to switch to Envelope display. The grey semitransparent area is the envelope area. The white areas in the middle is the size.  Watch the transform panel. With the envelope tool the envelope value changes. With the bone size tool the radius values changes. Wich represents the radius of the head and tail joints.

Closing, this works as designed.

![envelope](https://user-images.githubusercontent.com/13919702/102191054-2d9bf700-3eb9-11eb-98ed-9f24f065e01c.jpg)

**Comment by Draise14** [comment]
Ok.. but there still is an inconsistency. 

When in Bounding Bone mode, you can't scale bones, but you use the Evelope tool to scale Bounding bones. Finding a way to scale bounding bones has no default hotkey and the feature is hidden in the "Envelope Scale". 

Not intuitive at all. 

![hFAoleVQsg](https://user-images.githubusercontent.com/35357409/102253980-0dc6fc00-3ed6-11eb-8269-7ace6a0152f9.gif)

**Comment by Draise14** [comment]
Could we add a Change Bounding Bone Size button or make the operator change name dynamically based on the rig visibility type?

**Comment by ReinerBforartists** [comment]
This is a classical bug report to Blender ^^
