### ISSUE TITLE
Workspace for Geometry nodes

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2100]
We need a workspace for the new geometry node editor. Blender does not have one yet.

![nodespanel](https://user-images.githubusercontent.com/13919702/102210163-1e757300-3ed2-11eb-9a7a-0036f406b3fb.jpg)

**Comment by Draise14** [comment]
I recommend having the viewport on top. Very few software has the node editor on top causing quite a bit of disorientation. Have it like an ultrawide shader workspace.

**Comment by ReinerBforartists** [comment]
@Draise14 , Do we really need a new workspace here? We can now switch between the node editors. The compositing workspace comes with everything needed already.

**Comment by ReinerBforartists** [comment]
Ah, yes. We need definitely our toolbar with the primitives at the top.

**Comment by Draise14** [comment]
Issue with shader and composite editor is the viewport is polluted with other editors to the left and right. Ideally you'd want one with only a node editor and a single viewport. 

We could include the compositor layout with only Node Editor and 3D View, and the outliner and properties shelf, and just call it "Nodes". Would be also useful as a layout for the asset manager.

**Comment by ReinerBforartists** [comment]
Thanks for your thoughts here :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![nodesworkspace](https://user-images.githubusercontent.com/13919702/109937720-7bade300-7ccf-11eb-8da8-c13ab46c8840.jpg)
