### ISSUE TITLE
Armature Edit - Add button or dynamically rename "Bone Envelope" to "Scale B-Bone" in Toolshelf OR change tooltip/name

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2101]
# Issue
![hFAoleVQsg](https://user-images.githubusercontent.com/35357409/102255521-33550500-3ed8-11eb-9dcd-a39ee6f2dac9.gif)

Right now, it is nearly impossible to know that you can scale Bendy Bones (when rig display is set to Bendy Bones) by using the Bone Envelope tool. 

Could we add a Change Bounding Bone Size button or make the operator change name dynamically based on the rig visibility type? Or find some other solution, maybe in operator name and tooltip. 

Ideally:
When rig is in Envelope mode, this tool has the name "Bone Envelope"
When the rig is in Bendy Bone mode, this tool has the name "B-Bone Scale" - optionally changing icon.

Reason:
UI Discoverability

 # Task
 - Investigate how to dynamically show and hide tools based on rig visibility modes
 - OR add button for bendy bone scale with new icon
 - OR change tooltip to be a better tooltip and name for the operator: "Envelope/B-Bone Scale"
 
 
 ### Notes
 Related and solved task:
 #2098

**Comment by ReinerBforartists** [comment]
I highly suggest to keep it the Blender way for now. BBone is not envelope.

**Comment by ReinerBforartists** [comment]
Now i see what you mean. Hm, smells like a bug. Envelope tool should scale the envelope, not the bone. And the envelope value does not change.

Would you be so kind and report it to Blender? :)

**Comment by Draise14** [comment]
Ah.. a Blender thing. I guess I can throw it to the wild. I'll do that later this week.

Yeah. I don't even see the tooltip. 
![image](https://user-images.githubusercontent.com/35357409/102258951-7dd88080-3edc-11eb-9c24-b99b8624c57f.png)

**Comment by ReinerBforartists** [comment]
Seems we have a bug here O_O

In Blender it works, and i have no idea why it does not work in Bforartists -.-

![tooltip](https://user-images.githubusercontent.com/13919702/102259465-6f578c80-3f0f-11eb-916c-011fa08c013d.jpg)

**Comment by ReinerBforartists** [comment]
It's connected with our keymap it seems. With the Blender keymap the tooltips shows. Hm, i seem to remember that i had reported this one before. Let's have a look if i can find it ...

**Comment by ReinerBforartists** [comment]
Separated into 

Some tooltip content in the tool shelf does not show with Bforartists keymap #2102

**Comment by Draise14** [comment]
Hmm.. yeah, if it was in the tooltip, it might help. Bizzare ho wtooltips are tied to hotkey maps. It's like.. saying when you flush the toilet, the stove turns on.

**Comment by ReinerBforartists** [comment]
Definitely a curious error. Let's see if the Blender devs fixes it. It is reported now.

**Comment by Draise14** [comment]
I totally agree here....

**Comment by ReinerBforartists** [comment]
Have you reported the issue meanwhile?

**Comment by Draise14** [comment]
The tooltips was reported, but I haven't reported the UX by having two tools in the same tool issue. I am.. nervous they will confuse the UX bug to be a feature request.... then get it closed, but I can do it sometime this week I guess.

**Comment by ReinerBforartists** [comment]
Yes, always just report one issue at a time. They will to 99% not fix the second issue in the report :)

**Comment by ReinerBforartists** [comment]
Have you? ^^

**Comment by Draise14** [comment]
I haven't dug far enough into their backlog (kinda big) to find anything on it yet, but as soon as I can confirm that nothing is out there, I will make one. No problem.

**Comment by ReinerBforartists** [comment]
Have you? ^^

**Comment by ReinerBforartists** [comment]
Mh, i will close this issue since it is nothing that we should fix at our end. When we would do so then we would just introduce confusion.

**Comment by Draise14** [comment]
Ok, found an open task on it in Blender - they are aware. Lot's of debate, and priority normal (meaning.. low). 

**Relevant Blender Task:**
[https://developer.blender.org/T75465](https://developer.blender.org/T75465)

**Comment by ReinerBforartists** [comment]
At least there is movement :)
