### ISSUE TITLE
Revert some of the "improvements" in the data browser

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2106]
Blender developers were in the mood to "improve" things. They have added a menu behind the prop. Now you need two clicks to open a file. And the Unlink option is now a double. And you don't see anymore if a prop has a fake user assigned or not.

We should at least put the new and open buttons back to where they were before.

![revert](https://user-images.githubusercontent.com/13919702/102722897-8a0d7500-4304-11eb-95aa-0e36fd31941f.jpg)

**Comment by ReinerBforartists** [comment]
SHA-1: 2250b5cefee7f7cce31e388cb83515543ffe60f0

18.12.2020

* UI: Redesigned data-block selectors

https://developer.blender.org/D8554

Design discussed and agreed on with the UI team, also see T79959.

**Comment by Draise14** [comment]
Jeesus.. what are they thinking!?!

**Comment by ReinerBforartists** [comment]
Thinking? :D

To be fair, it's a good idea to hide the fake user thing. As a normal user it is not this often needed. But open and create new should be top level for quickest access.

**Comment by Draise14** [comment]
Hmm... guess some things hidden makes sense. The menu is.. tidy, just not a nice UX. 

I liked the fake user exposed to one mouseover and click though. As there is no real asset manager, having it exposed means I don't have to go to outliner>orphan data to quickly toggle elements to save for what I will loose in the area I'm working in, like the material area or such. A quick toggle in the asset relevant lists helps save time when making libraries of assets, like animations, materials, and such. It would be tedious once getting into the hundreds of assets and the only way to toggle is by double clicking in a drop down and moving twice to force save or switching to a completely different editor to do it the "quicker" way... in the "orphan data" area, which is not a clear UX for an already unclear data management paradigm. I really am not looking forward to those days working with that kind of data management...

**Comment by Draise14** [comment]
_I am starting to realize, my every day work is getting more and more complex the deeper I get into the career... I like BFA because it makes the small things easier, saves time, more production - though the target market is the hobbyist and independent artists - but I think the alternative is just bizzare if you want to be productive._

**Comment by ReinerBforartists** [comment]
We will do our best to improve the productivity where we can. But 3D was always a very complex matter, and always will be. Even the best UI will not change this.

> As there is no real asset manager,

We have now. It arrived this sunday. Besides other UI improvements and changes. I have for this merge quite a workload now to fix the manual ...

![assetbrowser](https://user-images.githubusercontent.com/13919702/102804717-6b69b580-43ba-11eb-8fdc-d52f61432062.jpg)

**Comment by Draise14** [comment]
Oh well, having discussed it with some other artists, we kinda do need some kind of top-level visible way of knowing the fake user - specially since we can't really know if a multiuser object is one except through the old exposed way. The old way was alright. 

Yeah, been looking at the asset browser. I hope they eventually add in curve profiles, colour palletes, textures, brushes, animation clips, and more. We'll see.

**Comment by ReinerBforartists** [comment]
Well, in that case we would make this little menu obsolete. And end in 8 little buttons besides the edit box ...

As told, the menu itself makes sense, the idea is good. It's simply too much content at top level. And it cleans things up a bit. Copy is not needed at top level. And add fake user imho neither. You can completely live without ever touching this button.

**Comment by Draise14** [comment]
Yeah, just new material/texture and maybe delete material top level could make sense here. 

These changes are in multiple areas everywhere...

**Comment by ReinerBforartists** [comment]
Yes, they are. Every data prop has this menu now.

**Comment by ReinerBforartists** [comment]
Reminder to myself. Don't forget the properties editor with all object types. Lots of changed data props here ...

![propertieseditor](https://user-images.githubusercontent.com/13919702/102871767-1f148900-443f-11eb-9c51-bf54c9297681.jpg)

**Comment by ReinerBforartists** [comment]
And don't forget the nodes and modifiers and constraints. 

Geez, i am at rewriting half of the manual at the moment ...

**Comment by ReinerBforartists** [comment]
They have reverted the change. The task is obsolete therefore. We might resurrect it once the props are changed again. But for now, closing.

Nightmare ahead: revert all the changes in the manual ...

![reverted](https://user-images.githubusercontent.com/13919702/104558317-e84b2080-5642-11eb-8c9d-130cec0137dc.jpg)
