### ISSUE TITLE
Compositor - Pick better preview toggle icon in nodes' headers

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2107]
Most compositor nodes have an icon shaped button that toggles node preview,
currently it uses "material" icon, it doesn't really match its function,

it is defined here:
source/blender/editors/space_node/node_draw.c

Code:
![image](https://user-images.githubusercontent.com/25552173/102726097-88ec4000-4324-11eb-9486-bc7ffe689d8d.png)

related: #2046

![image](https://user-images.githubusercontent.com/25552173/102725636-e67e8d80-4320-11eb-80d6-d9ea586bf0eb.png)

**Comment by ReinerBforartists** [comment]
Thanks for creating the task. Now let's have a look what icon could fit best here ...

**Comment by ReinerBforartists** [comment]
We have already a TOGGLE_NODE_PREVIEW icon. It's a bit ugly. But should do the trick :)

![previewnode](https://user-images.githubusercontent.com/13919702/102767278-94208980-437f-11eb-94d5-4a174e74cc3e.jpg)

**Comment by iyadahmed** [comment]
Great, there's also another idea, but needs a bit time, make a "show preview" button on top of preview, that way it is more explicit

or at least we could emboss the preview toggle icon, as it wasn't clear at first that it can be clicked, also for node group node header icon

**Comment by ReinerBforartists** [comment]
Yes, this needs fine tuning.
