### ISSUE TITLE
New file selector property - Disabled copy - change data-block to data

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2111]
Not supported here? Why is it even showing then? And while at it, also here, change data-block to data ...

And since when is duplicating an existing data equal to creating a new data?

![disabledhere](https://user-images.githubusercontent.com/13919702/102774926-37779b80-438c-11eb-958e-96f74adc7a5e.jpg)

**Comment by ReinerBforartists** [comment]
Geez, the data-block cholera is back in all of those new menus -.-

**Comment by iyadahmed** [comment]
Maybe keeping data block is fine, we could just explain what data block means, it is more efficient if blender devs keep adding the term

**Comment by ReinerBforartists** [comment]
This doesn't fit to the rest then. I have already renamed everything data-block to data. Stupid me :)

**Comment by iyadahmed** [comment]
oh, yeah it is my fault too, I should have spoken earlier, is reverting these changes an option?

**Comment by ReinerBforartists** [comment]
Not really. I dislike the term data-block. It is no artists vocabulary. It is programmers vocabulary.

**Comment by ReinerBforartists** [comment]
This design is so fubar ...

Here we have a menu full of just disabled menu items. Only the number of users is active. But this has no meaning here.

![nomenucontent](https://user-images.githubusercontent.com/13919702/102875831-9f89b880-4444-11eb-870d-0d4461f7d42c.jpg)

**Comment by iyadahmed** [comment]
Oh I see

**Comment by ReinerBforartists** [comment]
When you find a better term, i am open to anything :)

I thought of data set. But data hits the core, and is shorter.

**Comment by iyadahmed** [comment]
I think so too, data fits it well :)

**Comment by ReinerBforartists** [comment]
They have reverted the change. The task is obsolete therefore. We might resurrect it once the props are changed again. But for now, closing.

Nightmare ahead: revert all the changes in the manual ...

![reverted](https://user-images.githubusercontent.com/13919702/104558317-e84b2080-5642-11eb-8c9d-130cec0137dc.jpg)
