### ISSUE TITLE
Dopesheet - Sidebar - Make panel props more compact

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2112]
![image](https://user-images.githubusercontent.com/25552173/102803722-62301700-43c1-11eb-8400-95e7f4af8b2c.png)

**Comment by ReinerBforartists** [comment]
Yes, the props could be a bit closer to each other. Note that the gaps are by design to give a visual anchor. And not to end in a long list of props.

**Comment by iyadahmed** [comment]
Yep, I suggested this because there was similar one for NLA #1629
