### ISSUE TITLE
Compositor - Nodes - Movie distortion node menu name different from node title

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2114]
![image](https://user-images.githubusercontent.com/25552173/102819977-22772880-43dd-11eb-807c-4b27d5dd3eaf.png)

**Comment by ReinerBforartists** [comment]
Good catch. This babylonic term chaos is found quite often, unfortunately.

**Comment by iyadahmed** [comment]
Hmm, the label is dynamic
![image](https://user-images.githubusercontent.com/25552173/102908639-6c651a80-4480-11eb-87b6-810bb74bc417.png)

should we remove that "feature", just for the sake of matching menu name and title?

**Comment by ReinerBforartists** [comment]
Ah now i see the problem. Yes, some nodes shows the mode they are in, not what node type they are. Which is of interest when you collapse the node. 

Well we have now the icon that tells us what node type it is. So i would say we leave it the way it is. And close this issue.

**Comment by ReinerBforartists** [comment]
Closing.
