### ISSUE TITLE
Compositor - Node Panels - Change map range icon to match shader nodes panel

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2115]
Map range button has "range" icon, but there's a map range icon available, and used by shader nodes panel
![Screenshot_2020-12-21_22-32-03](https://user-images.githubusercontent.com/25552173/102820067-4e92a980-43dd-11eb-84ae-3d50318b500d.png)

**Comment by ReinerBforartists** [comment]
Good catch!
