### ISSUE TITLE
Nodes - Indicate clickable icons in header

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2120]
Preview Toggle and Node Group header icons are clickable, but there's no indication they are, not sure what indication to use, tried emboss but doesn't fit nicely in the header
![image](https://user-images.githubusercontent.com/25552173/102905238-7f292080-447b-11eb-819a-e028098d01b9.png)

**Comment by ReinerBforartists** [comment]
Doesn't the triangle button at the left indicate that it is collapsible?

**Comment by iyadahmed** [comment]
> Doesn't the triangle button at the left indicate that it is collapsible?

yes, but I'm referring to the icons on the right, they are clickable

**Comment by ReinerBforartists** [comment]
Ah, right. The problem remains that there is no easy solution. I know of none. And then i usually keep it the Blender way. Sometimes there is no improvement possible.
