### ISSUE TITLE
Last Operator Panel - Props are not left aligned

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2127]
![image](https://user-images.githubusercontent.com/25552173/102931613-5d459300-44a7-11eb-8600-af4680902240.png)
![image](https://user-images.githubusercontent.com/25552173/102931642-6afb1880-44a7-11eb-81e2-2ec30e959acd.png)

**Comment by ReinerBforartists** [comment]
Wasn't it already working? Maybe a merge has killed our changes. As a reminder, please comment every little change in the C code.

**Comment by ReinerBforartists** [comment]
Fixed in master

Ah, mergefun ...

![fixed](https://user-images.githubusercontent.com/13919702/102971929-90fdd880-44fa-11eb-8bd6-a3029413b4ea.jpg)
