### ISSUE TITLE
Modifier header, switch remove modifier button with the menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2129]
For my flavour the x button to close the modifier is a bit too close to the apply button. This could lead to accidental clicks. So imho it would be better when the delete button is at the end. The menu acts then as a separator to the apply button. Which reduces missclicks. And the delete button should be at the end of the list anyways.

Task, switch positions of delete modifier button and the modifier header menu.

![switchxandmenu](https://user-images.githubusercontent.com/13919702/102972763-dd95e380-44fb-11eb-9981-04412753acc6.jpg)

**Comment by iyadahmed** [comment]
Ah I see, agree
