### ISSUE TITLE
Asset Manager - Add Mark and Clear Asset to editor

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2132]
# Issue
![image](https://user-images.githubusercontent.com/35357409/103018585-826feb00-4513-11eb-93a0-efdd2645e1bd.png)
Right now.. to even use the asset library, you have to go to a disconnected editor, go into two sub menus with the right click and THEN and only then do you know how to add and remove assets. Not to mention.. the idea of the asset manager use is hidden in a nerdy speak of "ID Data" which is disconnect from the asset manager. 

In other words, to manage assets, you use operators that have nothing to do with the asset manager. 

# Request
If there is a way, add the "Mark Asset" and "Clear Asset" to the Asset browser UI into it's header or somewhere obvious. 

Reason: you'd be using this A LOT. 

# Task
- Investigate if this is an operator that can work outside the outliner
- Add operator and new icons to the asset manager exposed to top level as big buttons ir iconized buttons. 

# Alternative Task
- If not possible to use outside the outliner editor, add to a top level, either exposed to header or exposed in the Rightclick top level in it's own asset management group.

**Comment by ReinerBforartists** [comment]
I would wait a few more days. The current implementation is just a very first iteration. There is for sure lots of changes coming. At least i hope so. It's not this useful in its current state than it could be.

**Comment by Draise14** [comment]
Yeah.. feels half baked still.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/103020307-29ee1d00-4516-11eb-8e17-cd777762f2b6.png)
Looks like it's an outliner operator..... God I hope they work this A LOT.

**Comment by ReinerBforartists** [comment]
Asset browser is removed again. So it will arrive with Blender 2.83 earliest. And i am pretty sure that it has a ton of changes.

Closing this issue. This can take months. And not sure if this task remains valid. We will create it again then.
