### ISSUE TITLE
Image/UV Editor - Add Mark Asset and Clear Asset for textures to the texture sub menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2133]
# Issue
![image](https://user-images.githubusercontent.com/35357409/103019393-bf88ad00-4514-11eb-80a2-05de9ff45e21.png)

When trying to learn how to add textures in the image editor or UV editor to the Asset Manager, it took a long while, a call with a friend, and then a lot of digging to find a method. It wasn't obvious at all.  

Found out that it's in the header right click menu - only shown when right click on the icon of the dropdown list for textures... Bizzare.

# Request
![image](https://user-images.githubusercontent.com/35357409/103019204-6fa9e600-4514-11eb-99c7-d03cbe910946.png)
- Add these entries to the texture data management drop down sub menu.

**Comment by ReinerBforartists** [comment]
As told, let's wait what changes in the future. The asset manager is not finished yet.

**Comment by ReinerBforartists** [comment]
Asset browser is removed again. So it will arrive with Blender 2.83 earliest. And i am pretty sure that it has a ton of changes.

Closing this issue. This can take months. And not sure if this task remains valid. We will create it again then.
