### ISSUE TITLE
3D View - Make Links - Missing icon on Link Effects

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2134]
# Issue
![image](https://user-images.githubusercontent.com/35357409/103019915-8e5cac80-4515-11eb-8f7f-77f7763733bc.png)

Missing icon on **Link Effects** under the Make Links menu in the **3D View>Object>Make Links** menu. 

# Task
Add icon.

**Comment by ReinerBforartists** [comment]
Fixed in master

![makelinks](https://user-images.githubusercontent.com/13919702/103211866-a499ac80-4909-11eb-9088-193b222f683d.png)
