### ISSUE TITLE
3D View - Weight Paint Mode - Expose Brushes to Toolbar to improve UX

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2136]
# Issue
![bforartists_FCY1CEQVEE](https://user-images.githubusercontent.com/35357409/103022828-bb5f8e00-451a-11eb-8df6-b73e6cfa5a78.png)

Currently in Weight Paint mode, you have a number of brushes, but then one master brush with up to 7 presets. 

So.... there is no quick toggle to subtract or add, and some of them are like mix, lighten, darken, etc. In a typical workflow, you paint, then you want to subtract, you'd have to change brush settings, then paint, then change settings to add again, then paint again, or repeat process just solid mix... and.. every time you do a stroke, you have to go into a sub menu, search the brush, then work again. Changing brush settings over and over again. It slows down the painting process a lot. 

# Feature Request
It would be great to add in in some of these preset brush settings into the toolshelf directly, so when you select the brush in the toolshelf, the settings preset could be already applied, instead of needing to change the bush preset everytime you change the process of the weight painting UX. 

# Task
- Investigate if you can copy and add brushes in an easy way, with the preset applied
- Create icons for the new brush settings
- Add the new brushes to the toolshelf with the new icons and the right brush presets

# Reason
If we create brushes with settings exposed in Weight Paint (and/or others), but being the same type of brush accessing the sub-settings library will make the brush management system like a global brush settings system, instead of a per brush settings library - and exposes some very useful top level brush presets to be more discoverable and easier to use.

**Comment by Draise14** [comment]
![bforartists_xwcnxgEIaw](https://user-images.githubusercontent.com/35357409/103025096-1bf0ca00-451f-11eb-9f86-56cea7716d1d.png)

This feature request is also relevant to the Vertex Paint mode.

**Comment by ReinerBforartists** [comment]
I am every but keen to touch this hacky toolshelf code. But the blender devs plan to completely redo the brush system. They have understood that they have made a mistake here. It is just not known in which century they will deliver it ^^

**Comment by Draise14** [comment]
.. yeah, saw the task for it, but it's really just a design discussion. The tracker in Blender is a lot of vague tasks and many lumped tasks into other tasks, hard to keep track of things... I guess we'll see with 2.92. 

Should I postpone this idea?

**Comment by Draise14** [comment]
Relevant tasks to keep an eye on:
[https://developer.blender.org/T56744](https://developer.blender.org/T56744)
[https://developer.blender.org/T70412](https://developer.blender.org/T70412)

**Comment by ReinerBforartists** [comment]
Yes, let's postpone this one please.

**Comment by ReinerBforartists** [comment]
Ah the fun of waiting ...
The Blender solution will most probably never arrive. But this shoe is still ways to big for me ^^

**Comment by Draise14** [comment]
Yeah, both Iyad and I had a look at the code. We can duplicate brushes, and refer to the same brush enumerated lists,  but it's not easy feat to make a new enumerated list with same or similar brushes, nor to make a new brush with same functionality, even just instance a new single brush, as essentially each brush is really a list of brushes and the brush entry in the toolbar would refer to the same list and you change one, it changes the other, because the toolbar refers to the list index... We would have to practically write in a whole new brush and library system to make another brush --- the code for this toolbar is just.. everywhere. 

For Blender to update it.... they would have to re-write 3-5 different documents minimum to update their brush system, I can see why there is a delay. There are no tasks in sight for it, imo not even for 3.0 really... I guess they know it's all spagetti and the design proposals are still debate. 

I think the only way I can really think of things is doing the addon approach at how they add new tools, which has a system to add buttons to the toolbar and maybe a custom brush, but I'm not sure how to make it target a particular brush clone/library - yet. I am still digging around for other addons that makes new brush types for more clues.

**Comment by Draise14** [comment]
Ok, found a clue, some code that can select brushes with a certain tag. I could make another "brush" button that could select the right brush - like.. quick selectors.

**Comment by ReinerBforartists** [comment]
I am curious to what this leads ^^

**Comment by Draise14** [comment]
Did some more experiments. I have found some options, all failures:

1.    A button that create a widget, another operator runs a watchdog of that widget and it, and when detected, it can run a set of operators to “set brush settings”, but it gets stuck in that mode as it’s a modal operator and won’t switch back to the brush and it’s brush-data I would like to use. I can’t trigger a toggle to go back to former eg. draw brush to use those settings I just set from the toolbar.
2.    A script that sets the active brush-data to pre-sets, but I can’t trigger scripts from the toolbar, only from another panel and act once custom buttons - still not in toolbar.
3.    A duplicate of the builtin_brush ID, all good, but the settings and active brush data is identical and useless (double entry of the same). I can’t customize which index the builtin brushes will use from the toolbar
4.    I dug the code to compile duplicates, new libraries, new brushes - but the code for the brush library is spread out very thinly accross multiple documents. This is hard to maintain and near impossible to figure out.

I think.. now it's.. a custom tool class that somehow accesses the builtin_brushes system, and when it's triggered, it creates a widget and a widget watchdog can run the brush settings. 

Or.. find more code that can trigger a brush swap.

or.. find another way to expose these enumerated menus to a top level.

**Comment by Draise14** [comment]
A method to select brush groups (modal tool of existing brushes):
`bpy.ops.paint.brush_select(tex_tool='DRAW')`

Hey cool, this switches to certain brushes within an existing group:
`bpy.context.tool_settings.image_paint.brush = bpy.data.brushes['AlphaErase']`

I also could find a way to make brushes with certain settings if it doesn't exist also. 

Now concerning design, using these operatores is not allowed in modal operator "rendering" modes. So the widget watchdog system won't work. But these could be customized icons in a panel or locations somewhere.....

**Comment by ReinerBforartists** [comment]
What about the brushes panel? Added as a subpanel?

**Comment by Draise14** [comment]
> 
> 
> What about the brushes panel? Added as a subpanel?

A brushes box panel could work, with some buttons to manage them. The list might be dynamic - and atleast it's surface level and uses established systems. Iconography, not sure... also not sure how that list could populate it. I would still need to study more. 
![image](https://user-images.githubusercontent.com/35357409/114893763-a5305300-9dd3-11eb-87d9-4139ab019ed6.png)

Or a row of buttons with custom icons, which wouldn't be a dynamic list. 

Or both, with two panels. 
![image](https://user-images.githubusercontent.com/35357409/114894999-b88fee00-9dd4-11eb-8a01-21e9ba6929e8.png)

1. A quick brush system, where there are rows and columns of brushes (4 x 2 groups per brush group) it selects the brush group and sub-group for you with a custom icon. If brush doesn't exist, it will make it for you then select it. A seperate panel you can pin or collapse, in "tool" or "paint" tab, or as a sub-panel in existing panel. This alternatively is also be able to code a method to add custom icon - but that will require more investigation. 

2. Another would be another panel but with a list similar to vertex groups or particles lists, where you can see top level brushes, and when you click on it, it will select the brush. It also is an alternative brush manager. Icons wouldn't be customized though, but it would be dynamic for custom brushes and still be alot easier than a drop down. But this will require more investigation as to how to do this. 

I like the first option to a degree, but I will need more time and experiments to make it work. But the core code might work already. The second option would be even MORE time and effort. 

I am still in client crunch with 3-4 active clients, so slow. But something could be made. Atleast I see some light now.

**Comment by Draise14** [comment]
Question, the code from the nodeshelf add buttons could be used here too right? The responsiveness.

**Comment by ReinerBforartists** [comment]
When you want to add nodes, yes. Otherwise no ^^

**Comment by Draise14** [comment]
**Update:**
![image](https://user-images.githubusercontent.com/35357409/145838622-e4907c7f-e357-4e98-a393-16862d2c69af.png)

Iyad has been kind to take a look at it. There is a list now - dynamic to the panel in the toolshelf, and clicking in the toolshelf uses the brushes directly now. A dream come true @iyadahmed thanks for taking a look at it for me! What a maaaassive time saver. 

It even lists custom brushes and adds them to the list. We are now looking at custom iconography and the responsiveness of the buttons.

So here is the UX that still is under WIP:
1. Preset brushes has their own icon, and come premade with the toolshelf (built in with Bforartists). Iconography could probably be done by you @ReinerBforartists or should I make some proposals? Should we use existing iconography (like add, lighten, draw, etc)? 
2. Custom brushes (any new one) comes with either a prebuilt icon or optionally switches to the custom user icon, the method is still being explored 
3. Toolshelf should be responsive like the rest of the other toolshelves, but that's just some work more and done.  

What's done:
1. Has it's own brush tab and panel 
2. List of brushes is exposed to top level and is dynamic (counts and shows custom brushes)
3. Setup to be an addon

**Comment by ReinerBforartists** [comment]
To use existing icons is to prefer. Saves us a ton of work. And in case you nevertheless need some more icons, just tell me what icons you need. I'll have a look then :)

**Comment by iyadahmed** [comment]
Current progress, it will use builticons, and if custom icon is enabled and set it will use it
![image](https://user-images.githubusercontent.com/25552173/147628367-35f8da36-9380-4b3f-ac50-4463f50defad.png)

**Comment by iyadahmed** [comment]
Progress:
![image](https://user-images.githubusercontent.com/25552173/149050968-d7e9eca4-c256-4231-84ac-411b0602120b.png)

**Comment by Draise14** [comment]
Yeah! We had some progress today. 

- Found a way to update icons of brushes based on brush blend type
- Made button highlight of brush when active
- Fixed the custom icon refresh so that when you add or change the custom icon, it shows correctly (it will show custom icons)

We've nearly hit all the features we need for the other modes. 

I am starting to see I may need some icons for the blend modes though.

**Comment by ReinerBforartists** [comment]
Just implement it with a placeholder icon, and i'll add them :)

I usually use the delete icon for that needs

**Comment by Draise14** [comment]
Great, we'll focus on finishing up the abilaty to customize icons per blend type and the responsiveness, and then we can call it done for the weight paint mode. We'll commit then you can commit the new icons, we can then finish the rest.

**Comment by ReinerBforartists** [comment]
Deal :)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/151067080-3db08e75-8cc1-455c-91b1-4d91cc4dc949.png)

**Update:**
- Responsive layout is now included (same as other default systems). 
- Default Icon list done

We are ironing out bugs now, stress testing. 

**Known issues:**
- When making brushes, the panel doesn't refresh
- When deleting and unselecting brushes, there is an issue

We also noticed the panel code for brushes is a little taller than wider, and how they collapse on 3 column is a little odd, but that is another task for another day.

**Comment by Draise14** [comment]
Ok. We got the addon done for the next steps:
1. Design and compile Iconography, then add it into the addon
2. Add in a Bforartists patch to trigger panel refresh when a new brush or deleted brush runs their operators. 

**Known issue:**
- when making or deleting brushes, the panel won't refresh till you mouse over it. 

So.. I will make a new task for the panel refresh patch. 

How do I commit the addon to start the iconography @ReinerBforartists ? As a commit to a branch for this task?

**Comment by ReinerBforartists** [comment]
Yes, Make a commit that adds this addon to the repository. Simply drop it into release\scripts\addons

You could also simply attach the addon here, and i have a look to iconize it then.

**Comment by Draise14** [comment]
I think he uses the tagged branch mostly.

**Comment by Draise14** [comment]
Ok @ReinerBforartists! Addon is now in a branch for this addon "2136". I'll assign you here till you have the icongraphy setup in the master, then I'll continue to add the other brush modes.  

The addon is called `bforartists_brush_panel.py`. I have filled it with comments so you know what's up and things. 

So... To do:
```
# We need to add the other paint modes: Grease Pencil Draw Mode, Vertex Paint Mode, Texture Paint Mode and potentially Sculpt Mode
# When the built in icons are setup, I will proceed with the other modes for version 1.0.0! Can't wait! 
# In use cases, this has already proven a huge time saver when weighting rigs - very intuitive. 
```

**Comment by ReinerBforartists** [comment]
Okay, so i shall add the icons now? Checking ...

**Comment by ReinerBforartists** [comment]
Hm. Sunday is the next merge. Which will come with new nodes for sure, and so the need for new icons. We will most probably run into a conflict with this branch here when i add the required icons in the branch.

Hmmhmm.

**Comment by Draise14** [comment]
Ah, sure, I can add that to the queue.

**Comment by Draise14** [comment]
> Hm. Sunday is the next merge. Which will come with new nodes for sure, and so the need for new icons. We will most probably run into a conflict with this branch here when i add the required icons in the branch.
> 
> Hmmhmm. Let's sleep a night over this.

Maybe you can add the icons in another task and then to the master - then I can continue the addon in this task.

**Comment by ReinerBforartists** [comment]
Yes, best is to add the icons directly into the master. Now i know what icons are required.

**Comment by ReinerBforartists** [comment]
A shame that the big icons from the tool shelf are not accessible. I need to redo them.

Is Gradient missing by design?

![gradientmissing](https://user-images.githubusercontent.com/13919702/153361160-b25d2a12-51f8-474b-89b0-94f17352b31f.jpg)

**Comment by ReinerBforartists** [comment]
Blur is double entry
![BLURDOUBLE](https://user-images.githubusercontent.com/13919702/153363899-56a37975-495c-4854-bacf-d886c09d9ad8.JPG)

**Comment by iyadahmed** [comment]
> A shame that the big icons from the tool shelf are not accessible. I need to redo them.
> 
> 
> 
> Is Gradient missing by design?
> 
> 
> 
> ![gradientmissing](https://user-images.githubusercontent.com/13919702/153361160-b25d2a12-51f8-474b-89b0-94f17352b31f.jpg)
> 
> 
> 
> 

Yeah gradient is a tool not a brush

**Comment by iyadahmed** [comment]
> Blur is double entry
> 
> ![BLURDOUBLE](https://user-images.githubusercontent.com/13919702/153363899-56a37975-495c-4854-bacf-d886c09d9ad8.JPG)
> 
> 
> 
> 

I think that happened after edit to split into panels, should be easy to fix

**Comment by ReinerBforartists** [comment]
Okay, then let's throw out the gradient icon again ^^

**Comment by ReinerBforartists** [comment]
Here comes the icons. They are now in the master. So please do a merge so that you can continue in the branch.

PAINT_ADD
PAINT_AVERAGE
PAINT_BLUR
PAINT_DARKEN
PAINT_DRAW
PAINT_LIGHTEN
PAINT_MIX
PAINT_MULTIPLY
PAINT_SMEAR
PAINT_SUBTRACT

![newicons](https://user-images.githubusercontent.com/13919702/153402491-8b2064ac-8ef1-4331-9876-bedb3caafa9b.jpg)

**Comment by Draise14** [comment]
Ok, will continue. 

**Tasks left:**
- Update the icons
- Fix the tooltip
- Remove the double "Blur" brush. 

Then this can close and another task and version opens:
- (new task) Add the other brush modes

**Comment by iyadahmed** [comment]
A new branch
https://github.com/Bforartists/Bforartists/tree/weight_brush_panel

**Comment by Draise14** [comment]
_Commit to the branch of this task (wasn't sure how to switch to the addon task). The branch 2136 Should be up to date with master I think._ 

**Update 0.0.7**
- Added more, suggested, icons to the brush modes. They can finally be something else if necessary. 
- Commented out "MIX" since it overrides all other default brushes
- Added an experimental brush to header of the panels to make the UX a little more intuitive.

![bforartists_BuNTAHEoDT](https://user-images.githubusercontent.com/35357409/156952193-3d1a75a0-298b-4b2a-9ae4-60ed567ae345.png)

**Comment by ReinerBforartists** [comment]
> Added an experimental brush to header of the panels to make the UX a little more intuitive.

May i suggest to remove this icons? For me it adds visual noise instead of making it better. Also, it seems that you mix the 24 pixel icons in here. How do you even manage this?

**Comment by Draise14** [comment]
The icons are pulled from the brush type from the built in ones dynamically since the buttons are defined as enumerated. It's the brush type default icon. 

I'll remove the header icons sure. 

Though for feature UX sake: I was having difficulty reading the brush groups visually in a practical sense. The icons in header made it easier specially with the more custom brushes I added. Like the ux has a top level visual aid and sub level visual aid on buttons per blend type or custom icon. The sub level visual aid unless a default icon didn't show too much top level categorization. Though maybe it is enough.

It might be busy due to the icon inconsistency? 

Maybe we need the 16px version of the brushes as some of the icons are not formatting well and replace the enumerated defaults que the 16px versions of the same icon for consistency.

Maybe we also need some color categories and consistency from top level brush icon to show its sub-level group better with it's sub level on the blend mode types? (Like white plus for group and color groups like in the modifier stack). Right now it's a mixed bag.

**Comment by ReinerBforartists** [comment]
I see. It's just a suggestion. It's your addon.

> I'll make another task for the 16px version of the brush icons. We already have the smear and average brush.

As told, we have this icons already. Just not monochrome. We would end in a monochrome version and a colored version. For what reason?

**Comment by ReinerBforartists** [comment]
Not impossible. But unbelievable nasty. I don't want to touch it ^^

**Comment by ReinerBforartists** [comment]
It is also not this easy. The big icons are the ones that comes from the blend files. So there is no way to grab the graphics really. And you cannot simply scale down the 24px icon, even when we could extract it from the blend file. This will turn out washy and inconsistent.

**Comment by Draise14** [comment]
So the iconography design can not go upstream...hm... For consistency a brush icon design would have to flow down down to the 16px version as a near copy I guess (yes... Monochrome)?

We could maybe export the blend curve data as SVG then add the white 16px version in into the sheet. I know how to do that and vice versa, use a SVG to blend. 

To flow up stream - I can convert icon SVG to Blend - is the process to generate the dat's from blend something a mortal can do? Could I do that? Or too hard?

**Comment by ReinerBforartists** [comment]
You can try. But I am not even sure if i could manage this :)

But there is something else heavily tickling me here. The panels are a subset to the current active brush, right? Why do you display all the possible panels at once then? And not just display the set that is currently active? Means for the draw brush just the draw pencil subset. And for the blur brush just the blur related sub panel.

That way you would also save all the icons in the header.

**Comment by Draise14** [comment]
To have them displayed all at once is so that you can select and change brush type and brush preset with a single click. If the other brush types in panels were hidden, then you couldn't swap brush types to another direct preset.

**Comment by ReinerBforartists** [comment]
Is the branch actual? I'll pull and have a look ...

**Comment by Draise14** [comment]
Yes, the brushes switch automatically when you click on the buttons. 

The branch is the "2136" one

**Comment by ReinerBforartists** [comment]
Thanks. So i switched to the wrong branch already ^^

And thanks for explanation. That's indeed a time saver then.

Anyways. I think the best is you develop as far as you can go. I'll have a look at it when you are close to the merge then, and add my comments and ideas if required. Icons is the least to worry, and can be added at the very end of the development. I'll create them in case they are really required, as promised. 

I am as a user just not happy about the visual noise of the icons in the header. And also not really happy to have monochrome icons residing between colored ones. This doesn't really fit. But as told, these are suggestions. It is your addon :)

**Comment by Draise14** [comment]
Sure, I'll clean up the headers in the future commit. 

The default brush icon at the moment is the monochrome 24px ones directly from the brush type for user "connection/association" to the Brush Type and it's how we default the brush icon type dynamically in the code - we would have to make a new icon enumerated list for every single brush default if we don't use what's built in.  Might be doable and worth it since the icon size is inconsistent and looks broken when 24px large is used with the 16px ones - might be worth trying to work that code to default to 16px ones all with the coloured ones... I'll put that to the to do list. 

We were just thinking ahead to not have to remake all the all the 24px icons to 16px colored versions, specially when we start porting all the brush presets from the other modes, specially the mammoth sculpt set. All good to default to 16px ones though.

**Comment by ReinerBforartists** [comment]
Yes, you cannot use the 24 px icons in the old buttons. The origin doesn't fit as you might have noticed ...

**Comment by ReinerBforartists** [comment]
Related: Brushes - Toplevel Brush Switcher Addon #2233

I would even say it's the same issue. We should if possible just have one tracker issue for one task. Shall i close it?

**Comment by ReinerBforartists** [comment]
Isn't this also part of this task? 

3D View - Iconography - Make the Draw and Blur brush icons consistent #2919

**Comment by Draise14** [comment]
> Isn't this also part of this task?

> 3D View - Iconography - Make the Draw and Blur brush icons consistent https://github.com/Bforartists/Bforartists/issues/2919

Yeah, I split it to another task to keep the commits and discussion tidy. This one is getting big.

**Comment by ReinerBforartists** [comment]
I see. You can make a project to manage several related tasks at once. See upright, Projects.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/159508409-a85583a2-9b25-4bd7-a3a8-adc5f3e800db.png)

Looks like I don't have creation rights to make projects yet. The project creation button from documentation isn't there?

**Comment by ReinerBforartists** [comment]
I received a mail, but its content is not here. 

Just in case, do you see the Projects tab at the top? And can you create a project there?

It can of course be that just the repository owners are allowed to manage projects. I haven't found anyhting in the rights settings yet that explicitely allows the usage of projects for collaborators.

![projects](https://user-images.githubusercontent.com/13919702/159532483-aa326875-dbf1-43e1-9312-f16edcfcf077.jpg)

**Comment by Draise14** [comment]
Yeah, I was in "Beta" mode. All good. Just making publicity, then will work it.

**Comment by ReinerBforartists** [comment]
\o/

**Comment by Draise14** [comment]
@iyadahmed I'm having a little difficulty changing the default icons of the brush types to the 16px versions. How could we re-work that enumerated icon list to change the default icon types? Do you have any ideas?

**Comment by iyadahmed** [comment]
Sure let's catch up on Discord voice chat so I can see screen, it is easier to communicate

**Comment by Draise14** [comment]
Update

**Ver 0.0.10:**
- Added a dictionary to use the 16 px new brush icons as defaults 

I am going to close this task and make new ones in the project to keep better track of the addon. 

**Pending:**
- Expanded tooltips needs a small fix
- Other brush modes needs a fix
- There is an open task to add the ability to refresh the interface when making a brush
