### ISSUE TITLE
Mac Devbuild 27.12.20

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2147]
Mac Devbuild from Yesterday up. 

[https://www.dropbox.com/s/pf689s5pssa016u/Bforartists-devbuild-28-12-20-Mac.dmg?dl=0](https://www.dropbox.com/s/pf689s5pssa016u/Bforartists-devbuild-28-12-20-Mac.dmg?dl=0)

# Task
Add to download page

Thanks  @seanr !

**Comment by ReinerBforartists** [comment]
Thanks sean :)
