### ISSUE TITLE
Property Editor - Bone - Viewport Display panel - Add Selectability Toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2148]
# Issue 
![image](https://user-images.githubusercontent.com/35357409/103328680-cb4e0500-4a27-11eb-92aa-dcc653c96b07.png)

Currently there is a Viewport Display panel that toggles bone Hide, but there is no other toggles for Select per the Pose/Edit modes. This means, toggling selectability on bones is arduous because you have to do it one by one or click dragging in the outliner (or make a script)

Ideally, you could ALT+Click this property toggle in the panel so it toggles selectability (just like the visibility) on all selected bones. 

# Task
Add this API toggle to the GUI to the Bone Viewport Display panel. 

`bpy.data.armatures['Armature'].bones['bone'].hide_select = False/True`

# Alternative Task:
Add this feature/operator to the bone settings sub-menu (apply to selected):

![image](https://user-images.githubusercontent.com/35357409/103331182-ac08a500-4a32-11eb-8db7-873f97cca45a.png)

```
import bpy

# Script run to set selectability of the selected bones 

context = bpy.context

if context.active_object.mode == 'POSE':
    for pb in context.selected_pose_bones:
        pb.bone.hide_select = True
elif context.active_object.mode == 'EDIT':
    for pb in context.selected_bones:
        pb.bone.hide_select = True
```

**Comment by Draise14** [comment]
I have to admit, being able to toggle rendered, hidden, selectable on selected could be just... a general UX request for everything, as you can't do that to all selected with a single click unless it's with collection hierarchy (not bones though).

**Comment by ReinerBforartists** [comment]
One more crazy entry does no harm ^^

I would love to solve this one in a more elegant way though. But not sure how. So do it the planned way. Maybe we have some better inspiration at a later point.

**Comment by ReinerBforartists** [comment]
*bump*

**Comment by Draise14** [comment]
Task was expose a method to toggle "Selectable" of selected bones from the GUI, without haven't to do it one by one by one by one.

**Comment by ReinerBforartists** [comment]
Well, the fastest method is across the outliner i guess ...

**Comment by Draise14** [comment]
Yeah. `CTRL+LMB` doesnt work. It only toggles one. So you'd have to click drag. But then you can't do it on staggered selections.. which goes back to one by one by one. 

Ideally there would be a method like ALT click on the toggle to do it to all somewhere, or a new single click which was our original sugestion.

I'll have to revisit this one.

**Comment by ReinerBforartists** [comment]
Isn't this what the object visibility dropdown menu in the 3d view is good for? This one works at least in pose mode.

![visibility](https://user-images.githubusercontent.com/13919702/146806701-f46d933d-eb77-4e9d-b27a-5c8b7b158435.jpg)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/146807685-93c6f966-4d1f-439b-a030-8430b5f4b99f.png)

This might explain it better, this is for selectability/editability of a rig bones, so you can quickly toggle hundreds of control bones or deform bones and make them non-selectable for the animator - with a single click. You can do this with visibility already, but not for selectability. 

This is decoupled from view properties right now. 

This is bordering on a feature request....

**Comment by ReinerBforartists** [comment]
This IS a feature request. And one for which you better ask Iyad. I am lost here ^^

**Comment by ReinerBforartists** [comment]
Just curious, have you bothered to ask the Blender developers about this?

**Comment by Draise14** [comment]
Feature request got close. My friend made a addon that can do this so I guess this is no longer needed. Haggis Tools, though paid makes life easier with workflows like this. 

So I'll close this one since we try not make too many new operators.
