### ISSUE TITLE
Pose Breakdown from toolbar exaggerated

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#215]
![2018-06-05_15-47-39](https://user-images.githubusercontent.com/35357409/41001951-00d14108-68d8-11e8-8a35-99265b7fae3c.png)

When activating the Pose Breakdown tool from the Animation Toolbar becomes exagerrated - each mouse interval does 100% when it should be at intervales of 1%. 

BFA version 1.0.0

![2018-06-05_15-47-28](https://user-images.githubusercontent.com/35357409/41001942-fea0d0ec-68d7-11e8-8562-ead74585423b.png)

**Comment by ReinerBforartists** [comment]
Hm, seems that you have catched yet another tool that must be used from the 3D view, and cannot be placed in the toolbar.

**Comment by Draise14** [comment]
Maybe it's due to the button not in the right context? Out of the pose buttons, the other two buttons work alright.

**Comment by ReinerBforartists** [comment]
Most probably. As told, some tools needs to be performed in the editor type where they belong to.

**Comment by ReinerBforartists** [comment]
Removing pose breakdown from the toolbar ...

**Comment by ReinerBforartists** [comment]
This one is something bigger. Pose push, relax and breakdown doesn't work as expected. The propagate button and the propagate menu doesn't show the last operator. So we need to throw out this functionality too.

**Comment by ReinerBforartists** [comment]
Fixed in master.
