### ISSUE TITLE
Save new version

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2150]
In Blender / Bforartists when you want to save a new version, then you choose save as, click at the + button in the file dialog, hit enter. The focus is now at the edit box. And so you cannot hit enter again to save the file, but you need to move the mouse to the save button.

Cumbersome. 

What we need is a save new version feature. My favourite DAW FL Studio has this button for example. And it is super handsome.

![savenewversion](https://user-images.githubusercontent.com/13919702/103622518-23f53480-4f37-11eb-94b7-7c19e23d52a9.jpg)

**Comment by ReinerBforartists** [comment]
Related https://blenderartists.org/t/addon-save-incrementally/639523

**Comment by ReinerBforartists** [comment]
Hm. There is a save versions feature in the preferences. What it does is to add a number at the end, at the extension name. The user then needs to rename the file in case he wants to go back.

This is not what i want. I want it to increment the file name, not the extension name. But maybe we should follow this feature down to its core ...

![versions](https://user-images.githubusercontent.com/13919702/108603405-fc9fdd00-73a7-11eb-9d94-8c981682fc10.jpg)
![saveversions1](https://user-images.githubusercontent.com/13919702/108603411-00cbfa80-73a8-11eb-841a-544eb4d670b2.jpg)

**Comment by Draise14** [comment]
You can open the *.blend1, *.blend2, and so forth directly from inside blender, and load them without renaming. This may not be necessary to re-write this feature.

**Comment by ReinerBforartists** [comment]
Ah good to know. Thanks Draise. This means we can trash the original feature request then. 

Save versions is currently at 1 by default. One of these features where the user has first to study the manual to even find out that it exists. I still think to increase it. But then the users may ask themselves where all the blend1, blend2 etc. comes from when saving a file. Since it is not an explicit save new version feature.

Maybe i will come back to this at a later point. But for now let's close this issue.

**Comment by ReinerBforartists** [comment]
Coming back to it by reading this thread at devtalk. Maybe they even implement it by default:

https://devtalk.blender.org/t/option-to-automatically-count-one-up-while-pressing-save/19693/8

**Comment by ReinerBforartists** [comment]
Incremental save already exists in an addon. 

![piemenus](https://user-images.githubusercontent.com/13919702/141170291-51f708b7-2f6b-4a77-8162-4c674181e980.jpg)

**Comment by ReinerBforartists** [comment]
The tooltip is not to catch. the filepath pointer is simply not recognized, even when it is part of the WM_OT_save_as_mainfile operator. And i don't want to add yet another operator here, which would complicate the whole thing even more.
![filepath](https://user-images.githubusercontent.com/13919702/141286956-c7d5a8cc-4480-42b7-b4ce-baa8e1e86e80.jpg)

**Comment by ReinerBforartists** [comment]
Workaround for the tooltip dilemma. A tooltip that explains both tools.

Fixed in master

![savefixed](https://user-images.githubusercontent.com/13919702/141295332-bae3b12f-00dd-426c-8eb3-166447c9dcdb.jpg)
