### ISSUE TITLE
Node Editor - Expose listed Node Groups dynamically in Node shelf. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2151]
# Issue
![image](https://user-images.githubusercontent.com/35357409/103669508-6a9e5b00-4f46-11eb-8e85-c505d2255770.png)

Currently, node groups are only accessible in the Add menu then group sub-menu. You can't just click and drag them into use. You have to search, or go into sub-menus to use them. 

# Feature Request
Bforartists exposes nodes into a panel, it would be great to be able to have these group nodes also exposed in the side panel with names dynamically, so it's easier to see what groups are available and to re-use them easily.

**Comment by ReinerBforartists** [comment]
Good idea. Shouldn't be too hard to add the enumeration into a panel (famous last words and so :D  ) . This would best go into the relations tab then.

**Comment by ReinerBforartists** [comment]
Ah, i expected it already. This is nothing easy. I have lost the spaghetti after the fourth class :/

**Comment by ReinerBforartists** [comment]
release\scripts\startup\nodeitems_builtins.py
line 85
def node_group_items(context):

No idea how this can be incorporated into a panel. The whole add menu is a sphaghettimonster, cluttered across several classes.

**Comment by ReinerBforartists** [comment]
Giving up. This menu is over my head. I could print a list of the group items, at least this i have managed to some degree. But i cannot enumerate the buttons like in the sub menu. And that's the vital part. These groups can be reused and inserted from the Add menu.

Maybe Iyad has an idea here. I am lost.

![group](https://user-images.githubusercontent.com/13919702/104089410-0abdf200-526f-11eb-87f0-c89b6b4f585b.jpg)

**Comment by Draise14** [comment]
Someone posted an answer on stack exchange, so can be done. Looks like you've already got a commit! Nicely done. 
[https://blender.stackexchange.com/questions/207676/node-editor-python-expose-listed-node-groups-dynamically-in-node-shelf-panel?noredirect=1#comment351057_207676]( someone posted an answer. 
https://blender.stackexchange.com/questions/207676/node-editor-python-expose-listed-node-groups-dynamically-in-node-shelf-panel?noredirect=1#comment351057_207676)

**Comment by ReinerBforartists** [comment]
Ah, nice, thanks :)
