### ISSUE TITLE
Geometry Nodes - Add icons to nodes headers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2153]
# Issue
![image](https://user-images.githubusercontent.com/35357409/103901099-b4ae4a80-50c6-11eb-8fc5-96db967fd7ee.png)

Now that we have icons with goemetry nodes, I guess for consistency and usability sake, they should also be added to the headers of the nodes. 

# Task
Add the icons to the node headers

**Comment by ReinerBforartists** [comment]
What icons precisely do we talk about here?

**Comment by Draise14** [comment]
I updated the description to have an image. It's like what we have been doing with the shader and compositor editors, adding in icons to the top right corners of the actual nodes in the tree.

**Comment by ReinerBforartists** [comment]
Ah, now i see. Thanks :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/104130839-4510b780-5373-11eb-9156-b4101eec4951.jpg)
