### ISSUE TITLE
Add area dependant operators to the toolbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2154]
Some operators are global. Some not. We have quite a few operators that just works in the window that they get called. Transform operations for example. They need to be executed in the window where you want to transform your selection.

 In my current case i thought of adding the Rotate + 90 degree button back into the toolshelf. But it doesn't work. My guess is that we need to write a own operator for each entry. Which i have done before in the middle of Bfa 1 development. Just can't remember where it was. And the old issues are not accessible anymore. In that case forget about this idea. It would be too much effort. But maybe we find a more elegant way.

Found so far this example, which i think was what i did. I just can't remember how i did the tricky part, and added my operator here: https://docs.blender.org/api/blender_python_api_2_77_0/bpy.ops.html

```
for window in bpy.context.window_manager.windows:
    screen = window.screen

    for area in screen.areas:
        if area.type == 'VIEW_3D':
            override = {'window': window, 'screen': screen, 'area': area}
            bpy.ops.screen.screen_full_area(override)
            break
```

![readd](https://user-images.githubusercontent.com/13919702/103884449-e7fcd380-50de-11eb-951c-2d44a3a4168f.jpg)

**Comment by ReinerBforartists** [comment]
Ah i already had a crack at it and did not get it to work. A fragment is to find in space_toolbar.py in line 1025.

**Comment by ReinerBforartists** [comment]
The way goes across own operators. Example from an earlier version of the space_toolbar.py before i have removed this operators then:

############### Change view classes

class VIEW3D_MT_totop(bpy.types.Operator):
    """Change view to Top\nThis button is global, and changes all available 3D views\nUse the View menu to change the view just in selected 3d view"""
    bl_idname = "view3d.totop"
    bl_label = "view from top"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context): 
        for area in bpy.context.screen.areas:
            if area.type == 'VIEW_3D':
                override = bpy.context.copy()
                override['area'] = area
                bpy.ops.view3d.viewnumpad(override, type='TOP', align_active=False)
        return {'FINISHED'} 

Let me sleep a night over this, but i think this task is too big. We would add over 1000 new classes here, an own for each tool.

**Comment by Draise14** [comment]
I guess for merging sake, maybe making a new separate document with said operators would make sense - but if you had these in the toolshelf instead of the toolbar - then we wouldn't need to do this.... but it may still need similar amount of code with a workaround for run-once operators rebuilt to work for the toolshelf.

**Comment by ReinerBforartists** [comment]
Makes no difference if we separate the classes. I am just no friend of spaghetti code. What belongs together should have the same location.

This here looks interesting. https://blender.stackexchange.com/questions/6101/poll-failed-context-incorrect-example-bpy-ops-view3d-background-image-add

**Comment by ReinerBforartists** [comment]
Hm, no. We end in the same dilemma. A own class for each operator.

**Comment by ReinerBforartists** [comment]
Let's have a look if we can at least add a working entry for the rotate uv tool.

**Comment by ReinerBforartists** [comment]
Rotate works. I think it's also a good idea to add the mirroring functionality into the header this way.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

Now we have at least examples how to achieve this goal. And mirror and rotate is something that you might use very often. But we should use this method very rarely. As told, you need to add an extra operator here for every tool. So it might be wiser to have a look in the C code if we can lift the area restrictions, and make further tools operating global instead.


![fixed](https://user-images.githubusercontent.com/13919702/104044917-17463a00-51de-11eb-9303-7b5be40574b0.jpg)

**Comment by ReinerBforartists** [comment]
Let's close this for now.
