### ISSUE TITLE
Sverchok addon doesn't populate Add header menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#216]
**Problem**
Procedural modeling via nodes workflow Sverchok addon doesn't populate header menu like the Animation Nodes addon. 

http://nikitron.cc.ua/sverchok_en.html

Add header menu empty: 
![bforartists_2018-06-11_17-34-48](https://user-images.githubusercontent.com/35357409/41260620-c1ca9e12-6d9d-11e8-8869-b28f9b1486c1.png)

Add menu of Sverchok by Shift+A hotkey:
![bforartists_2018-06-11_17-34-10](https://user-images.githubusercontent.com/35357409/41260622-c3cad132-6d9d-11e8-8801-c6b4363f9b41.png)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/41261251-73ca58d0-6da0-11e8-9fb5-f2a72c79607f.png)
I think I'm pulling errors too.

**Comment by ReinerBforartists** [comment]
Sverchock is not part of Blender. And by grabbing a quote from the github account i guess that's 2.80 out at the moment ...

> addon for: Blender (version 2.78 and above).

Closing. We have the original Blender menus back. In case it works in Blender 2.80 but doesn't work in Bforartists 2, then please make a new tracker issue.

Closing.
