### ISSUE TITLE
Animation - Apply Animation to all selected through UI Animate property buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2163]
# Issue
![bforartists_i2dNYBJh37](https://user-images.githubusercontent.com/35357409/104210977-818af480-5401-11eb-8c63-5a0edc0d3bb1.png)

Currently, when you animate with characters or multiple objects, you can key all of them by pressing I then selecting which properties you want to animate from a very long un-iconized list. 

Like in Bforartsits as in Blender, if you use the UI entries, you can only set animation on Active object properties.
![bforartists_vb1Zrgy5dx](https://user-images.githubusercontent.com/35357409/104211036-95365b00-5401-11eb-95b5-acb02204ab02.png)

In general, the UX for all selected is holding down ALT then editing the sliders and it would apply to all selected. 

# Feature Request
It would improve the UX if we could animate all selected by holding down ALT then pressing the keyframe UI entry, then it would add and set keyframes for all selected, just like the "I" then Keyframe Panel operators. 

This may be... a global change, but here the focus is to focus on the animation properties of the Transform Panel

# Task
![image](https://user-images.githubusercontent.com/35357409/104212274-0591ac00-5403-11eb-8eff-3686b3c1e4f3.png)

- Research to see if this is possible, to be able to use the UI entry to then trigger animation key to all selected
- Evaluate how this can be implemented
- Evaluate if this is a feature that should be committed to Blender directly, or set here

## Method
I've asked @iyadahmed to do some research into this, document it and find away to save some time figuring it out to give us some options.

**Comment by ReinerBforartists** [comment]
I thought it works already with  multiple objects. I can for sure add keyframes to the selected objects at once.

https://blender.stackexchange.com/questions/1621/how-to-add-keyframes-for-multiple-objects-at-once

**Comment by Draise14** [comment]
> 
> 
> I thought it works already with multiple objects. I can for sure add keyframes to the selected objects at once.
> 
> [blender.stackexchange.com/questions/1621/how-to-add-keyframes-for-multiple-objects-at-once](https://blender.stackexchange.com/questions/1621/how-to-add-keyframes-for-multiple-objects-at-once)

Yes, you can pressing I then using the floating menu with the big list, but you can't using the UI buttons. Thus this task.

**Comment by ReinerBforartists** [comment]
Ah you mean the decorator buttons behind the sliders? Hm, isn't this better asked the Blender devs? It's a feature, not a UI issue.

**Comment by Draise14** [comment]
Yeah, guess so. To me seems like an overlooked UX, but yeah, got it that it might be a feature request for the blender devs. I'll also post to Blender and link it here, but later this week.

**Comment by Draise14** [comment]
Ah Iyad, before taking a look at this, I think we probably should report the request to Blender - this might be a core feature...

**Comment by ReinerBforartists** [comment]
Indeed a good idea. Maybe we even overlook something and it is already possible.

**Comment by iyadahmed** [comment]
made progress, decorator now adds a keyframe to all selected objects.
TODO:
- do the same for deleting keyframes
- do it only when alt is held

https://user-images.githubusercontent.com/25552173/107594931-f1b4b200-6c1b-11eb-8890-03b285b3dcfc.mp4

code bits
![image](https://user-images.githubusercontent.com/25552173/107595035-393b3e00-6c1c-11eb-8cab-95b71d57b6fb.png)

**Comment by iyadahmed** [comment]
Deleting keyframes now works
![image](https://user-images.githubusercontent.com/25552173/107604292-5da51380-6c38-11eb-9918-66725ae6369e.png)
TODO:
* Pose bones
* Alt key (if doable)

**Comment by iyadahmed** [comment]
Progress
![image](https://user-images.githubusercontent.com/25552173/128037384-2725b46f-bf48-43e5-acff-0c9fad264ae1.png)

**Comment by iyadahmed** [comment]
More progress, better, more elegant
![image](https://user-images.githubusercontent.com/25552173/128080406-93f63691-add6-48d5-9ff8-ca89254c8cb0.png)

**Comment by ReinerBforartists** [comment]
So where is this prop added now? Could you please make a screenshot so that i can document it?

**Comment by ReinerBforartists** [comment]
Ah, video helped. It's the decorators.

**Comment by ReinerBforartists** [comment]
Done. Closing.

Please always add a screenshot of the fixed state where possible. This helps me enourmous with the manual task. Even i do this most of the times.

**Comment by iyadahmed** [comment]
> Ah, video helped. It's the decorators.

Yep

**Comment by iyadahmed** [comment]
> Done. Closing.
> 
> 
> 
> Please always add a screenshot of the fixed state where possible. This helps me enourmous with the manual task. Even i do this most of the times.

Ah ok will do so
