### ISSUE TITLE
Geometry Nodes - split Add nodes into two tabs: Modify and Input

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2169]
# Issue 
![bforartists_PAyXUR9cdN](https://user-images.githubusercontent.com/35357409/104829513-9d97f700-5842-11eb-8184-09cb0d072e21.png)
Right now, we have an iconized add tab in Geometry Nodes, but to be consistent with other node editors, we should split them into two tabs: Input and Modify repsectively.  

Reason being, the workflow can be a lot more self explanitory, one to create/get data input, one to modify data. 

# Task 
Split the Add tab into Input and Modify tabs to minimize how many panels show and to define the workflow of geometry nodes a bit better.

**Comment by ReinerBforartists** [comment]
Yes. This would be more consistent then with the other panels.

**Comment by ReinerBforartists** [comment]
Hm, yes, the group nodes adds the input tab already. But ddoes it really make sense to split the content here? Currently nearly the whole expanded content can be displayed at once at a 1920x1080 screen. Just the vector panel is out of sight. With two tabs you have to start searching again already.

What we could do is to collapse all but one panel. Never a good idea to throw the user to death with all content at once.

I would say let's postpone this issue until more nodes are in the editor. Then decide again.

**Comment by ReinerBforartists** [comment]
Hm, let's at least collapse all the open panels here. Input could remain open, as a starting point.

**Comment by ReinerBforartists** [comment]
We have already a problem with inconsistent content between the add menu and the sidebar content. I don't want to repeat the mistake here again. Let's keep the order and the content of the panels in sync with the add menu and its sub menus.

Closing.
