### ISSUE TITLE
Armory addon doesn't populate Add header menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#217]
**Problem**
Another addon based on a game engine Armory 3D also doesn't populate the header add menu

http://armory3d.org/

Shift+A also is broken. 
New composite tabs also are broken. 

Missing menu entries
![bforartists_2018-06-11_17-44-53](https://user-images.githubusercontent.com/35357409/41260933-27d308ce-6d9f-11e8-812c-cb80abd6248b.png)

Intended menus: 
![blender_2018-06-11_17-44-18](https://user-images.githubusercontent.com/35357409/41260917-1890e458-6d9f-11e8-9714-f1383a57c11c.png)

I know the node system has been improved, and the former hidden - but for some custom node systems like Animation Nodes, these menu entries are not hidden. We now have two custom node addons broken  - even though Animation Nodes works with the Add header menu entry and Shift+A menu entry. There must be a workaround to make BFA more compatible?

**Comment by Draise14** [comment]
I am pulling console errors too.

![image](https://user-images.githubusercontent.com/35357409/41261293-9b0aea9a-6da0-11e8-9e37-27548d1a62d9.png)

No "Tree Types".

**Comment by ReinerBforartists** [comment]
That's because we have removed the double menu entries. 

The problem here is that the Blender code is plain crazy. It was a real challenge to implement the current solution. And i don't want to revert it to the Blender state really.

I will have a look at it when the 2.8 port is starting.

**Comment by Draise14** [comment]
Yeah, I expect things might change in 2.8. 

I'm just wondering though, how to make custom node addons more compatible. The nodes editor does add new tabs from some addons, but not others. It adds the Add header menu and Shift+A menu to some addons, but not others. Why would this be, I have no idea. 

I guess the code is indeed a big compatibility nightmare mess.

**Comment by ReinerBforartists** [comment]
Closing this one. We won't fix anything for Bforartists 1 anymore. And there is no hint at the Armory webpage if the engine is even compatible with Blender 2.80. We have the Blender code in place. So everything should work. Please make a new tracker issue in case it doesn't.
