### ISSUE TITLE
3D View - Show Active Camera in overlays

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2183]
# Issue
Currently, there is a notice to show you if you are in Camera mode or Perspective mode, or Orthographic. 
![image](https://user-images.githubusercontent.com/35357409/105203556-424f5880-5b11-11eb-96d7-21f904ec426e.png)

But currently, the only method of knowing which camera is active is by going to Properties Editor>Scene>Camera. 
![image](https://user-images.githubusercontent.com/35357409/105203524-39f71d80-5b11-11eb-8878-e84964652f99.png)

You can optionally also.. bind cameras to the timeline. 

But.. you can't tell which camera is active by name in the 3D View, and you would have to go into another editor to know. It's a 3D View aspect. 

# Request
1. Have the Active Camera name show in the 3D View overlays when in Camera mode. 
2. Optionally show the active camera in the View Panel

Notes: Make it an overlay toggle or just there by default, kinda like the statistics dialogue.

**Comment by ReinerBforartists** [comment]
The active camera is the one with the filled triangle in the 3d view. Who needs more :P

Irony off. Good idea actually :)

**Comment by seanr** [comment]
I often have the view with overlays off. Otherwise you end up with this:

<img width="1552" alt="Screen Shot 2021-01-20 at 12 45 52 PM" src="https://user-images.githubusercontent.com/199713/105214024-7761a800-5b1d-11eb-868a-efc2cc6d4a36.png">

😉

**Comment by ReinerBforartists** [comment]
:D

Maybe you can ask Iyad here. I am bound to manual and keymap at the moment ...

**Comment by iyadahmed** [comment]
It can be shown through camera settings, but only when viewing through the camera

![image](https://user-images.githubusercontent.com/25552173/105249143-4e263380-5b80-11eb-86c7-bbc24fa0a297.png)

**Comment by Draise14** [comment]
Yeah, seems like there already is a feature to show the camera name in the 3D View. 

Should this be a default?
Should the name be shown even if Active camera is not viewed? That is another debate and task.
