### ISSUE TITLE
File Browser - Move Advanced Filters to the right panel, as it's hidden in the left.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2188]
# Issue
![image](https://user-images.githubusercontent.com/35357409/105543806-3954b780-5cc8-11eb-9e1d-817546a6c065.png)
There is an Advanced Filters panel.. iconized and everything... that you will never see unless by accident. Reason being, it's below all the file shortcuts. 

Mode: Linking/Appending 

# Request
Move this panel to the other side panel to the right, so you can see them and use them immediately.

**Comment by ReinerBforartists** [comment]
Friends, i would prefer when you would wait with such changes until we have spoken about it. Please give me at least a chance to have a look at your ideas before you start to do code changes.

**Comment by ReinerBforartists** [comment]
First look at the issue: The advanced filter is usually in sight. But the settings area at the right is usually closed. So your solution is imho a downgrade.

**Comment by ReinerBforartists** [comment]
Hm, the filter settings could reside in the header as a dropdown. But it's one more click compared to the position at the left.

**Comment by ReinerBforartists** [comment]
Ah, now i see where it is. Appending and linking. Sidebar is open. So no extra click. It is a panel with options. Which fits into the right side. 

Green with the change. Thanks for listening :)

**Comment by iyadahmed** [comment]
> Ah, now i see where it is. Appending and linking. Sidebar is open. So no extra click. It is a panel with options. Which fits into the right side. 
> 
> 
> 
> Green with the change. Thanks for listening :)

Great!, indeed I shouldn't have rushed glad it worked out, it was just one line in the end too :)
