### ISSUE TITLE
Mac version of Bforartists 2 version 2.7.0

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2199]
We have a new release. Sean, could you be so kind to create the mac version for it? You would make an old man happy with that :)

**Comment by seanr** [comment]
Can we get a fix for #2200 in first? @ReinerBforartists

**Comment by seanr** [comment]
Turns out it's that way in stock Blender too. Ugh. Doing the build now.

**Comment by ReinerBforartists** [comment]
Great :)

When a new build is ready then it's usually feature freeze. We have to make the cut somewhere. Means everything else behind this point goes into the next build. When it's a show stopper then that's something for a point upgrade. But the outliner issue is no showstopper. So we will fix it in the next build then.

**Comment by seanr** [comment]
Here's the new build: https://www.dropbox.com/s/3ip49mx0lmdpo8x/Bforartists-v2.7.0-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Many thanks. Build is uploaded and live :)

Closing.
