### ISSUE TITLE
Typo in Compiling Tutorial documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#220]
![2018-06-25_07-41-08_li](https://user-images.githubusercontent.com/35357409/41853239-f70b52d2-7852-11e8-9f5d-367e0a09e288.jpg)

Document:
http://www.bforartists.de/data/tuts/Building_Bforartists_with_Cmake_and_VS_2013_at_Windows_7.pdf

I found a typo in the documentation that had me doing erros when trying to compile. It couldn't find the Win64_vc12 libraries due to the fact that the documentation said to make and checkout the folder "Wine64_vc12" - though this is not the case in the image.

**Comment by ReinerBforartists** [comment]
Fixed here: https://github.com/Bforartists/Bforartists/issues/221

Closing.
