### ISSUE TITLE
More buttons indicator missing from Tweak button

### ISSUE THREAD

**Issue by clintonman** [Bforartists/Bforartists#2206]
**Describe the bug**
In edit mode the tweak button does not show the little triangle indicating more buttons.

**Desktop (please complete the following information):**
Windows 10

**Screenshots, Example Files**
![b4a_noTriangle](https://user-images.githubusercontent.com/5383136/106060009-63cbb980-60a8-11eb-9b00-d0d23f1d36c9.jpg)

# Task
Improve contrast of arrow in theme

**Comment by Draise14** [comment]
It's there, just.. it's not contrasting with the blue highlight when activated..

**Comment by clintonman** [comment]
Ah, now that you mention it I can see it. It's almost invisible when my screen is at an angle. Even when not blue the contrast is still low though.

**Comment by Draise14** [comment]
Yeah, improving the contrast seems like a good thing to do. I guess that can be the task, a theming issue most likely, or that little arrow icon too grey.

**Comment by clintonman** [comment]
I took a look at the preferences and found
Preferences > Themes > User Interface > Toolbar Item > Item has alpha 0.561
When alpha is changed to 1.0 it looks better to me.

**Comment by ReinerBforartists** [comment]
Theming. This part comes from Blender. We need to fix it.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

Made the white triangle completely opaque now.

![betterreadable](https://user-images.githubusercontent.com/13919702/107621879-3ad62780-6c57-11eb-8aa5-e030d2ffa1ca.png)
