### ISSUE TITLE
2D Image Editors - Expose switches like in the Animation Editor quick toggles

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2215]
# Issue
To access the image editing capabilities, we have 2 separate editors, and some modes within one of the editors. To change the workflow of processing images in the image editor means.. changing workspaces, or changing editors AND change mode, and/or a mix of both, and/or trigger a render to load up the editor automatically. 

Right now, I have to 1. Be in the right editor, and 2. use a dropdown to get into the right mode. 

This makes quick texture painting and UV correction a multi editor/mode system for what should be a quick toggle like toggling the animation editor modes. 

Right now, the same system for images is splintered, not clear that you can do the same/similar in all the editors and you can't quick toggle to see the feature differences (subtle). I'd have to switch editor, or use a dropdown with multiple clicks to see any changes that might not be that evident. I minor nuesance, but one nonetheless. 

# Request
![image](https://user-images.githubusercontent.com/35357409/106471131-554a1d00-646f-11eb-94d7-4289a09f1265.png)
Add a one click solution to switch editors (UV and Image) and the modes, so that the UX is unified and easier to use. 

**Reasons**
- It's consistent with the Animation Editor quick toggles
- It's consistent with the outliner/properties quick toggles
- It ties the image editors together so it's easier to switch modes
- It ties the image UX together in a system that implies there are steps to a pipeline to the editor system for images
- It makes it easier to switch to UV editing mode and texture painting mode when the workflow requires it
- It's easier to switch to another mode quickly to add missing functionality from say.. the view mode.

**Comment by ReinerBforartists** [comment]
How many image editors do we currently have? That's two, right? UV Editor and Image Editor.

As told in the other thread, i would love to keep the mode dropdown a dropdown menu to make clear that this is a mode menu.

**Comment by Draise14** [comment]
I get it, it's like not exposing the action, GP and dopesheet modes of the Dopesheet Editor. But each mode has the same tools system regardless of modes. 

I would consider texture paint mode it's own editor almost: it has it's own toolbar, tool system. The view mode also has it's own tool system. It is almost like they are their own editors. 

## Alternative Request
Maybe having a quick toggle for only UV and Image editor would be useful, and then the image editor modes can still have a dropdown.

**Comment by ReinerBforartists** [comment]
Understood. We will find a way to improve here :)

**Comment by ReinerBforartists** [comment]
Task 1: add a button to switch between image and uv editor at the front.
Task 2: add hotkeys to the modes. I am not sure if we can get this part to work properly. Keymap is a own beast ...

**Comment by ReinerBforartists** [comment]
Separating the hotkey issue ...

**Comment by ReinerBforartists** [comment]
Image Editor - add hotkeys to View, Paint and Mask mode #2262

**Comment by ReinerBforartists** [comment]
Fixed in master

It is just one button for now, since we just connect two editors here.

![fixed](https://user-images.githubusercontent.com/13919702/109780536-65d4eb00-7c07-11eb-9d89-7e080c486f90.jpg)
