### ISSUE TITLE
Adjust last operation convert to - align keep original prop left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2216]
Is middle aligned, should be left aligned.

![alignleft](https://user-images.githubusercontent.com/13919702/106495285-c31c3600-64bb-11eb-9b1f-73b1ceffb346.jpg)

**Comment by ReinerBforartists** [comment]
Let's have a look ...

**Comment by ReinerBforartists** [comment]
Hm. this leads to source\blender\editors\object\object_add.c
static void object_convert_ui(bContext *UNUSED(C), wmOperator *op)
line 3080
 uiItemR(layout, &ptr, "keep_original", 0, NULL, ICON_NONE);

How do i aling this one left? Ah, C ....

**Comment by ReinerBforartists** [comment]
@iyadahmed, you use !is_boolean in 

 uiLayoutSetPropSep(col, !is_boolean); /* bfa - align left if boolean prop */

in source/blender/editors/interface_utils.c

When i do the same in our panel code, then i get a error message, not declared identifier.

So for now i use this method here. I am just not happy with this solution. How do we get is_boolean to work here? I cannot find where it is defined.


```
static void object_convert_ui(bContext *UNUSED(C), wmOperator *op)
{
  uiLayout *layout = op->layout;
  PointerRNA ptr;

  RNA_pointer_create(NULL, op->type->srna, op->properties, &ptr);
  uiLayoutSetPropSep(layout, true); /*bfa - split*/
  uiItemR(layout, &ptr, "target", 0, NULL, ICON_NONE);
  uiLayoutSetPropSep(layout, false); /*bfa - boolean, don't split*/
  uiItemR(layout, &ptr, "keep_original", 0, NULL, ICON_NONE);

  if (RNA_enum_get(&ptr, "target") == OB_GPENCIL) {
    uiLayoutSetPropSep(layout, true); /*bfa - split*/
    uiItemR(layout, &ptr, "thickness", 0, NULL, ICON_NONE);
    uiItemR(layout, &ptr, "angle", 0, NULL, ICON_NONE);
    uiItemR(layout, &ptr, "offset", 0, NULL, ICON_NONE);

    uiLayoutSetPropSep(layout, false); /*bfa - boolean, don't split*/
    uiItemR(layout, &ptr, "seams", 0, NULL, ICON_NONE);
    uiItemR(layout, &ptr, "faces", 0, NULL, ICON_NONE);
  }
}
```

**Comment by ReinerBforartists** [comment]
Tried to follow the definition of is_boolean , and the definition tail became longer and longer and longer. Well, my current method works. It is not elegant, but functional. As told @iyadahmed, when you know a method to make this one nicer, every help is welcome :)

Fow now it's fixed. 

![convert](https://user-images.githubusercontent.com/13919702/107504454-9d69ed80-6b9b-11eb-9f10-38f7e88511de.png)

![convertgp](https://user-images.githubusercontent.com/13919702/107504464-a064de00-6b9b-11eb-8926-e2f91ee22259.png)

**Comment by iyadahmed** [comment]
> Tried to follow the definition of is_boolean , and the definition tail became longer and longer and longer. Well, my current method works. It is not elegant, but functional. As told @iyadahmed, when you know a method to make this one nicer, every help is welcome :)
> 
> 
> 
> Fow now it's fixed. 
> 
> 
> 
> ![convert](https://user-images.githubusercontent.com/13919702/107504454-9d69ed80-6b9b-11eb-9f10-38f7e88511de.png)
> 
> 
> 
> ![convertgp](https://user-images.githubusercontent.com/13919702/107504464-a064de00-6b9b-11eb-8926-e2f91ee22259.png)
> 
> 

I didn't notice this at first, thanks for the heads up :)

**Comment by iyadahmed** [comment]
My bad I didn't see notifications 🤦‍♂️

is boolean was useful in the last operator panel because it generated ui for each prop

Here UI is already declared so we can do it normally

**Comment by ReinerBforartists** [comment]
Perfect. Thanks. And no problem :)
