### ISSUE TITLE
Please allow users to download the latest help manual and open it by pressing F1 from Bforasrtists itself 

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2218]
In the advocacy for bforartists, the "why bforartists?" section points out that it has "better documentation".

So the user should be able to enjoy this strong selling point by pressing F1.
Better still, if he has pressed F1 from a screen, the help file should show the relevant section automatically.
(In other words, the manual should open at the correct bookmark and show him help for the _exact screen_ he is looking at.)

Instead, at present, he has to select the **Help > Manual** menu, and then download his chapter.

Can we have a better use of the manual?

I am not saying it has to be a pdf: It may be an online help.
But opening the correct section of the manual will help the user a lot; even if the manual is not accessible offline.

**Comment by ReinerBforartists** [comment]
Hey raindropsfromsky,

Thanks for the idea. But it does not work this way unfortunately. Hardcoded links to specific items are a source of trouble. And the chapters still changes permanently with new tools. One little update is enough to break the links then. Our help > manual link is our best bet. This link will always be valid. And does not make any extra work.

Blender had a system where every tool leaded to its manual entry. They did not manage to maintain this with all their manpower. Their links are all broken now. Which is a fine example of a good idea and the trouble it makes. The idea is not bad. But unmanageable as you can see. Nobody wants to maintain this nightmare anymore. And so i don't even want to start it with our limited resources.

For the manual, there was an attempt to create a online version out of the manual. It can be found here, closed because of inactivity: https://github.com/Bforartists/Manual/issues/163

**Comment by ReinerBforartists** [comment]
F1 key is free. We can assign it to the help > manual menu item.

**Comment by raindropsfromsky** [comment]
OK, given these problems, the next best thing is to launch the pdf manual to the user whenever he presses **F1**.

- When he is pressing **F1** for the first time, B4A should check if the pdf manual is available locally. <br> Also check if that local file is the latest. <br> If the latest version does not exist locally, fetch the file and place it in the installation folder, and then launch it. <br> Let the user browse the pdf manual locally.
- IMHO there is no point in showing the users the mega list of chapters. That's too complicated.<br> When the manual is updated regularly, there is no need to show all chapters to the readers. <br> The chapters are just like code: Good as a building block for the final product; but not exposed to readers directly. <br> The more energetic readers will browse and discover the chapters anyway.

**Comment by ReinerBforartists** [comment]
That's imho too complicated. And i still think that calling the manual page works fine. The user can decide if he wants to work with the all in one pdf, or with the single chapters. We don't have a online manual. The single chapters is the closest thing to it :)

**Comment by Draise14** [comment]
Hmm.... Maybe we can include the PDF with the download/installation, that it will unpack and install with the software? I mean, it will add another more or less 100mb, but it's one of our selling points. Then the link can go to the `SYSTEM` folder where it was installed, and then the links would never break AND be automatically available offline and from within the software directly. The link to open the SYSTEM folder and sub folders, or the LOCAL folders and subfolders works, we made a button concept for it once. 

So.. technically each installation could have the most recent documentation for that release installed locally. But auto updating I think might not be possible. So we could include the online documentation file links also. Issue is, link can only go to folder, not necessarily open file - so it's pretty much the same UX, click a link, go to a place, use the place to open documentation.  

**But with that said, potential tasks:** 
1. Include complete PDF/s with installation
2. Link to local PDF from software with the correct paths, this would never need updating again (if file name stays same). 
3. Also link to online documentation list in the help menu. 
4. Have two different tooltips giving options to offline and online documentation locations. 

As Reiner pointed out, maintaining online documentation is feat in itself, as it's 3500 pages of content that would need updating regularly, and doing it all in markup languages is painfully slow, which we don't have a lot of time nor manpower to do. We did do a script to convert current documentation into Sphinx (similar system to Blenders..), but we don't have a method of hosting it yet, nor a maintainer who can update the online documentation regularly. 

But yes, trying to save a step to access documentation and integrating it more into the software, valid....yet it miiight not be worth the effort just yet, unless we find someone willing to prototype a more direct documentation link to software solution.

**Comment by ReinerBforartists** [comment]
Hm. 100 Mb is even nowadays quite a lot to download for some.

**Comment by raindropsfromsky** [comment]
I don't understand:

1. "better documentation" is a major scoring point over Blender.

2. Both Blender and bforartists are extremely complex software. The user
just cannot survive without referring to the documentation.

3. bforartists is strongly pitched to new users of Blender, who are not
familiar with how blender works.
    Now a newbie would need to refer to this "better" documentation every
step of the way.

4. Especially for a newbie, it is extremely difficult to select a chapter
from a huge list, which will teach him the subject he wants.
    He cannot judge this from the titles of the chapters.

Thus it's a foregone conclusion that the full manual should be presented to
the user at the earliest opportunity.
And yet the full manual is not supplied with the software. Why?

Under the circumstances, the manual should be bundled even if the user has
low bandwidth.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ReinerBforartists** [comment]
Thanks for your ideas. But i simply don't share your point of view. Not everybody needs the manual offline. That's why. The manual is available at the webpage. I personally find this way better. It is very common to have the manual separated from the product nowadays.

For the problems to understand the manual, there is a chapter called How to use the Manual. It is chapter 1.1, the second chapter already. And explains how to use the manual and how everything is connected.

**Comment by ReinerBforartists** [comment]
I have thougth now a pretty while if we should really add the hotkey. And came to the conclusion not to do it. Blender does not have it. And our philosophy is to have as much free hotkeys available as possible. Maybe a user wants to use the F1 key for a tool instead. The linkbutton in the Help menu is more than enough to lead the users to the manual.
