### ISSUE TITLE
Please provide a help menu item: Check for updates

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2219]
The B4A is based on the cutting edge version of Blender (currently 2.93 alpha, rather than 2.92).
That means keeping it at the bleeding edge is important.
That means B4A should be updated frequently (the Blender alpha gets updated daily, but B4A can update slower).

Consequently, the B4A user should be alerted whenever a new version of B4A is available.

This can be done in two different ways, and both can be implemented:
1. Whenever B4A is launched, it should check if an update available at the site. If so, alert the user.
2. Allow the user to manually check for updates.

**Comment by ReinerBforartists** [comment]
Thanks for the idea raindropsfromsky. 

Blender has no internal updater yet. And this tells me that this is nothing really trivial. I have no idea how this could be achieved. I would need to do some research first.

**Comment by Draise14** [comment]
There are quite a few addons that check for updates and install - like Sverchok has one.

**Comment by ReinerBforartists** [comment]
I worry more about my server ... :)

**Comment by ReinerBforartists** [comment]
I did a research at the matter now. And we will not do this, sorry. Nevertheless, thanks for the idea.

The reasons are that i have just a small server.  And it can cause security issues by being vulnerable against man in the middle attacks. And so the time that goes into such an update feature is better spent at the UI.
