### ISSUE TITLE
Missing Icons for 1.0 on Linux

### ISSUE THREAD

**Issue by astearon** [Bforartists/Bforartists#222]
I compiled Bforartists 1.0 for debian but when launching i get no icons for any button.

Note that I am running 1.0 on a very old Acer Aspire One with the following parameters enabled:
`MESA_GL_VERSION_OVERRIDE=2.1 MESA_GLSL_VERSION_OVERRIDE=210`
The old prebuilt version has the icons rendered with the same parameters active.

![screenshot_2018-06-28_04-08-22](https://user-images.githubusercontent.com/7342330/42007474-ff70bb96-7a88-11e8-8f30-586580075fbd.png)

**Comment by ReinerBforartists** [comment]
Hm, then i am honestly lost :/

**Comment by astearon** [comment]
The only thing in console I see is this:
`Color management: using fallback mode for management
Read prefs: /home/astearon/.config/bforartists/2.79/config/userpref.blend
found bundled python: /home/astearon/bforartists/build_linux/bin/2.79/python
Read blend: /tmp/quit.blend`
Tried recompiling from fresh git clone but same result.

**Comment by ReinerBforartists** [comment]
Me neither, sorry. I am lost with Linux anyways.

**Comment by astearon** [comment]
Is there a way to compile Bforatists without the OpencolorIO and have it use the same color management as the old 0.95 version ? As I said 0.95 loads the icons for me.

you mentioned further up that i should check the icons in a certain path `Bforartists\release\datafiles\` but the make file creates Bforatists with diferrent paths:
`cloned-git\build_linux\release\datafiles` and the executable is in a whole different place: `cloned-git\build_linux\bin\bforartists`
Perhaps the makefile does not place the right stuff in the right place ?

**Comment by ReinerBforartists** [comment]
Then it would fail for your other linux installations too. But here it works fine. And for you it works also fine at other machines.

You usually clone the whole repository. I do this in a Bforartists folder. The release\datafiles\ path is for the icons in the repository, before compiling. The binary has the icons compiled into the exe. That's two different things.

It is definitely something with your linux installation going on. But i have no idea what it could be, sorry :/

**Comment by Gavinmc42** [comment]
I have the same thing when compiling in Gentoo64 on a Raspberry Pi.
I will check my names/paths.
I also had some build deps issues which may or may not be related.

**Comment by Gavinmc42** [comment]
Changed bforartists folder name, compiled with the make lite option in Raspbain

**Comment by astearon** [comment]
The thing is, the exact same build works on another laptop with icons... just not here. With nothing changed between them.
And i know the laptop can show icons because the old prebuilt binary of B works WITH icons.
So unless they changed how the icons are rendered between these builds i cannot figure out what the problem actually is.

**Comment by Gavinmc42** [comment]
Got the 0.95 source
Ok, could not get install_deps to work but I had already done it for 1.0.
Crossed my fingers and did a make lite, yippee b4a 0.95 has icons.
Seems to have more jitters than 1.0 but probably usable if I knew how.
I suspect it is still OpenGL driver issues, but that was the point of getting stuff that does OpenGL.

**Comment by ReinerBforartists** [comment]
So in the sum it is most probably a problem with this exact configuration. Which means there is nothing to fix for us.

Thanks for your work here.

Closing.
