### ISSUE TITLE
The snap function is unable to snap the object to the grid

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2220]
I enabled **snap** and **increment** option.

But the object is not snapping to the grid (it remains offset).

In other words, the object origin does not snap to the World origin.

Here is a screenshot from b4a:
![image](https://user-images.githubusercontent.com/9047168/106992076-9dce4700-679d-11eb-8ea1-79cd4ece2c25.png)

And here is a comparative screenshot from Blender 2.93:
![image](https://user-images.githubusercontent.com/9047168/106992007-7d05f180-679d-11eb-9038-c652fcb8de38.png)

**Comment by ReinerBforartists** [comment]
Just tested and it works fine. Note that by default rhe object remains offset when you offset the object before you turn snapping on. It does not snap TO incremental steps, but BY incremental steps. This works the same in Blender too.

You can change this behaviour by ticking Absolute Grid Snap in the snapping panel. Then it snaps to the nearest grid point.

![absolutegridsnap](https://user-images.githubusercontent.com/13919702/107002317-58a11980-678b-11eb-9c8a-107334d036a0.jpg)

**Comment by Draise14** [comment]
Also, you can change snapping increments by changing the..... grid dimensions?! 

Snapping is always kinda bizzare with the Blender system.
