### ISSUE TITLE
The manual does not explain the basics first

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2221]
The bforartists is a completely a visual program. Therefore, the user must be introduced to the visual elements first (like how a child is introduced to objects like BAT, CAT, BALL, etc).

Once you are familiar with elements, then you can use those terms in some context, such as-
- The cat is black. (attributes- color)
- The cat is eating. (action)

This is how a child builds up his mental model of the world.

But the manual does not explain basic terms like "world origin", "object origin" and "3D cursor". It straightaway starts using these terms in explanation. This makes it difficult to understand.

For example, the term "3D cursor" should be explained, and its symbology should also be explained.
- What does the white-and-red circle mean?
- What does the three pairs of ticks mean? (axes)
- In what ways does it help you?
- How does it behave when you move around in the 3D space? when you manipulate objects?

**Desired:** 
Each chapter should have a separate section in the beginning that describes and explains the terms and concepts used in that chapter. Thus if a user sees a new term, he can quickly jump to this introductory section to look it up.

**Comment by ReinerBforartists** [comment]
Hi Narayan,

Thanks for the ideas. Chapter 35 explains this already. The glossary contains all this explanations. Feel free to improve this chapter further.

In general, the manual is no general CG tutorial. It is the reference manual. It explains the tools. Not the workflow. 

Please post further manual issues in the Manual tracker. Thanks. https://github.com/Bforartists/Manual
