### ISSUE TITLE
old changes shadowing newer changes introduced by Blender

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2224]
release\scripts\startup\bl_ui\space_clip.py

some classes are defined twice, this was possibly caused by a merge, or was this intended?

example: CLIP_MT_track_transform

**Comment by ReinerBforartists** [comment]
Good catch. That's the price for working with two code bases ...

Please document every double that you find.

**Comment by iyadahmed** [comment]
Great, will do so

**Comment by iyadahmed** [comment]
draw defined twice in release\scripts\startup\bl_ui\space_sequencer.py
![image](https://user-images.githubusercontent.com/25552173/107094822-62209500-6810-11eb-97ed-50972e236161.png)

**Comment by iyadahmed** [comment]
draw defined twice in release\scripts\startup\bl_ui\space_topbar.py

![image](https://user-images.githubusercontent.com/25552173/107095100-dfe4a080-6810-11eb-960e-5462bdf2d612.png)

**Comment by ReinerBforartists** [comment]
Thanks buddy :)

I am currently into music. Once done, and after the next merge i will try to catch these baddies.

**Comment by ReinerBforartists** [comment]
Fixed in master
