### ISSUE TITLE
Port the theme to Blender 2.8

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#223]
Blender 2.8 comes with some changes in the theming. So we need to adopt our standard theme to the new possibilities.

**Comment by Draise14** [comment]
Will this include also updating the icons in the new Tool shelf - or will they remain the same as 2.8?

**Comment by ReinerBforartists** [comment]
Narp. Theme does not change the UI code. Just colors.

**Comment by Draise14** [comment]
Ah ok, just wondering. The icons in the Toolbar are *.Blend files that you can edit - could be another task another day.

**Comment by ReinerBforartists** [comment]
This new icons is a big can of worms. A mega hack that will bring us most probably a ton of fun -.-

**Comment by ReinerBforartists** [comment]
One special trouble maker is the text in the header of the 3D view. The header background color is now connected with the gradient color. And with our current colors it turns out white.

Let's have a look if making the text color black will help here. No idea if this change strikes back somewhere ...

![headerbar1](https://user-images.githubusercontent.com/13919702/44159827-e028d880-a0b8-11e8-9f37-645ef000596b.jpg)

![headerbar2](https://user-images.githubusercontent.com/13919702/44159834-e5862300-a0b8-11e8-8e02-8c362a9aecde.jpg)

**Comment by ReinerBforartists** [comment]
Wasn't this much. I expected ways more. Just two changes actually. 

Current version:

[bfa_28.zip](https://github.com/Bforartists/Bforartists/files/2293148/bfa_28.zip)

Now we need to wait for the merge here ...

**Comment by ReinerBforartists** [comment]
Found a quirk that we need to fix. Panel colors differs here and there compared to the Bforartists theme.

For now it's just the movie clip editor. Let's check the other editors too.


![panelcolors](https://user-images.githubusercontent.com/13919702/44385740-99a40580-a520-11e8-9abb-813f93676cce.jpg)

**Comment by ReinerBforartists** [comment]
They have now subtabs too in the properties editor. May need a color fix ...

![gpencil](https://user-images.githubusercontent.com/13919702/44538780-ac763000-a702-11e8-9a40-913f04f5741b.jpg)

**Comment by ReinerBforartists** [comment]
Readded the new theme to bfamerge280 branch

https://github.com/Bforartists/Bforartists/commit/ac9a43e5980df1c42cda11796f986d9a06192847

**Comment by ReinerBforartists** [comment]
Another theming problem in the user prefs ...

![error](https://user-images.githubusercontent.com/13919702/49700406-67590980-fbde-11e8-8288-5ae387834fda.jpg)

**Comment by ReinerBforartists** [comment]
Let's try to fix this issue so that we can close this chapter finally.

**Comment by ReinerBforartists** [comment]
Seems that this issue was a Blender bug. Theming looks okay now. So this task is fulfilled. The theme is already working as expected. And it is included already. So we are done here.
