### ISSUE TITLE
Weight Paint - Add "quick toggles" to weight strength into header and tool settings

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2230]
# Feature Request
![PureRef_tP8nJBOsrP](https://user-images.githubusercontent.com/35357409/107540863-8673cd00-6b94-11eb-8aa6-cacc92e890be.png)
![PureRef_5nb5sqfYEW](https://user-images.githubusercontent.com/35357409/107540865-870c6380-6b94-11eb-8f62-3659743df815.png)

According to #2164, making new brushes sucks. 

So, maybe we can optimize workflows per areas by exposing some common operators or needs (UX) to the user to make life easier. 

**Request:** Add a toggle button to make weight strength 0 or 1, and quick buttons to set pre-set weight strength. 

## Issue
Right now to paint, then remove weight, you have to either use a brush toggle then dropdown, then choose another brush. OR you can use a slider to toggle the weights to erase, but the UX is not obvious. So.. if I paint a weight, it's too much, then i need to erase a bit, then I do the ritual to toggle, paint, then repeat the ritual to go back to normal and... it just is too much work to just toggle weights. We need more weight control and erase/add weight control to the default brush system. 

## Solution
If we add in buttons for pre-set weight values and/or a toggle button for the strength slider, we could then use the same brush with a single mouse over to paint and erase weights, and to set weights with more control and consistency - without the need of changing brushes nor blending modes in a sub menu/dropdown. 

1. Add button to toggle weight strength 0-1 in the Brush of the Weight Paint mode
2. Add buttons with scales 1-5 at increments of 20% weight.

**Comment by ReinerBforartists** [comment]
Hm. Looks super confusing to me. And i am not convinced that this is really an improvement. It is yet another place where you need to look. I would love to union the settings to one location instead. We have already ways too much separated settings cluttered around the UI.

Yes i know that you know. But they have plans to overhaul the whole brush system at one point ^^

**Comment by ReinerBforartists** [comment]
Have read it twice now. And now i have understood what you need. I am still not happy with the five buttons. The values are too arbitrary, and might not be what you need. But what about a snapping feature when increasing the value. like in 1/10 steps?

And the 1 and 0 value button, what about a feature to have a switch between two weights? Like in painting. Primary and secondary color. But with a weight value?

And maybe this can be done by an addon?

**Comment by ReinerBforartists** [comment]
Shift ctrl F does already the snapping part. So, remains the secondary weight value.

**Comment by Draise14** [comment]
_Yeah.. I can't wait that long with a redesign. They have no code, no tasks, nothing. Only promises and design documentation proposals. It's not even in their kanban.. (tasks set over the next 6-12 months)_ 

These weight toggles are standard to any weight addons or general workflows elsewhere, also consistent with any other paint modes (toggle colours black and white, color palette, etc) - so it would be more intuitive than digging through a 3 step process to do the same thing. Addons usually are not free when it comes to weighting improvements, so there is no real FOSS solution to this. 

Here is an example of Weight Tool, a paid addon. But I don't like using a hotkey then pie all the time, unless it's on the mouse right click or something (like in Krita).  
![image](https://user-images.githubusercontent.com/35357409/107545249-1582e400-6b99-11eb-8983-121193c6a2a0.png)


And the improvement is this.. 1 mouse over and click VS. mouse over, click, search, mouse over again, click _(OR search for addon, buy addon, install addon, and now press hotkey, use pie, or use a system that's not consistent with the other paint systems of Bforartists. )_ 

And yeah, the preset values on buttons are arbritrary, so not necessary, but it helps. Maybe +/- step could help A toggle between 0 and 1 would be very useful. 

Like this:
![image](https://user-images.githubusercontent.com/35357409/107544864-a73e2180-6b98-11eb-9127-6c6c9daf8371.png)

- Plus and minus (add/remove increment)
- Toggle (swap 0/1)

Or use the same as elsewhere driving the float weight values somehow:
![image](https://user-images.githubusercontent.com/35357409/107544997-c472f000-6b98-11eb-921f-f4fa8db58558.png)

**Comment by ReinerBforartists** [comment]
Cross posting. See above :)

**Comment by ReinerBforartists** [comment]
My problem with the core features is, we need to maintain it then. An addon you can turn off. A change in the main code can make big trouble though.

**Comment by Draise14** [comment]
Right yeah.. the extra work. There is such a fine line between better UX and actual features... 

Hmm.. wouldn't an addon appending the toggles go to the end of the list? I guess I can give it a go with Serpens. 
![image](https://user-images.githubusercontent.com/35357409/107546244-2718bb80-6b9a-11eb-8273-c031679dc4bf.png)

**Comment by ReinerBforartists** [comment]
Sure, but this is a completely new feature, not a UI improvement :)

And yes, currently addons can just append or prepend to menus and panels. Or you make your own panels instead.

**Comment by ReinerBforartists** [comment]
Just that it is not overlooked: Shift ctrl F does already the snapping part, and increments in 1/10 steps. So, remains the secondary weight value.

**Comment by Draise14** [comment]
> Just that it is not overlooked: Shift ctrl F does already the snapping part, and increments in 1/10 steps. So, remains the secondary weight value.

Which operator is this? I can't find this hotkey entry in the UI for this.

**Comment by ReinerBforartists** [comment]
This is general snapping behaviour i think. I would also need to investigate here now. I just stumbled across it since i had the idea to replace your buttons by simple snapping functionality. And found out, it already snaps :)

**Comment by ReinerBforartists** [comment]
It is, The increment snapping of sliders by holding down control seems to work with all sliders in the UI. That's a tooltip out. 

I need to have a look if we have documented it in the manual.

**Comment by ReinerBforartists** [comment]
I have added the snapping information to every main chapter now.

**Comment by ReinerBforartists** [comment]
Okay, decision time. When you want to do this as an addon then you have green light from me. But i don't want to have it as a core implementation.

**Comment by Draise14** [comment]
Found a "Weight Palette" addon with a panel for similar functionality. 
![image](https://user-images.githubusercontent.com/35357409/107854454-f5962f00-6de9-11eb-8a2d-5cd3611168e6.png)

It's a free one, not the beeeeest solution, but does the trick.

**Comment by ReinerBforartists** [comment]
Sounds good :)

**Comment by ReinerBforartists** [comment]
I will close this issue for now since it seems that you use the third party addon instead. And we don't maintain third party addons.

You can always make a new issue in case you want to modify the addon further, and want it to be included into Bforartists.

**Comment by Draise14** [comment]
Sure, we can close. No problem. The addon helps, but doesn't quite solve the issue (add/subtract quick toggle) but atleast it helps. 

I'll let you know if I manage to work an addon
