### ISSUE TITLE
Make Orbit around Selection the default

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2239]
Currently the orbit rotation behaviour is a bit erratic here and there. So i had a look in the preferences. And noticed that the orbit rotation does not happen around the center of the selected element by default. 

I think we should change this. Orbit around selection by default would make much more sense.

Opinions?

![orbitdefault](https://user-images.githubusercontent.com/13919702/107927876-e218ce80-6f77-11eb-818c-5672a75807d3.jpg)

**Comment by Draise14** [comment]
I have this as a personal default, yeah, having it on will make it better. I have had a couple of users ask how to make things "just work" when navigating, and having these on helps that.

**Comment by ReinerBforartists** [comment]
Thanks. Made it a task :)

**Comment by ReinerBforartists** [comment]
Fixed in master
