### ISSUE TITLE
Video Sequencer - View Waveform options missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2241]
# Issue
Blender
![blender_z7NIwtuJAb](https://user-images.githubusercontent.com/35357409/107979289-52c9e600-6f8c-11eb-9b9f-d1f4c7fcd013.png)

BFA
![bforartists_S2bBPTEJ4O](https://user-images.githubusercontent.com/35357409/107979297-56f60380-6f8c-11eb-9c53-2a5e9d58791e.png)

The Show waveforms view options are missing in the GUI. 

# Task
Add them to the view tab

**Comment by ReinerBforartists** [comment]
Good catch!

**Comment by ReinerBforartists** [comment]
Hm, this seems to be something bigger. I can't even find the cache entry anymore in the newest version. Could you please make a screenshot of Blender in which editor and menu you are? I know it was once in the View menu ...

![blender](https://user-images.githubusercontent.com/13919702/107982293-0ac6b580-6fc4-11eb-89be-af037d4f0237.jpg)

I found a double though ...

![doubleshowcache](https://user-images.githubusercontent.com/13919702/107982206-e9fe6000-6fc3-11eb-9e47-36f3d2b7f89a.jpg)

**Comment by Draise14** [comment]
Hmm.. maybe they removed it in 2.93. I will download and try find them.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/108005130-dd7b0700-6fc5-11eb-9e8d-c2650f374a4b.png)
Found it. It's in this new options dropdown like from the other editors...

**Comment by ReinerBforartists** [comment]
Thanks buddy :)

Okay, we have it at the same location. So nothing to fix. Remains the chache. 

![waveform](https://user-images.githubusercontent.com/13919702/108026678-18faed00-7029-11eb-9c37-e152ee3b33e0.jpg)

**Comment by ReinerBforartists** [comment]
Good task. Found and fixed a manual inconsistency too ...

**Comment by ReinerBforartists** [comment]
Removed the double. Nothing else left to do. Closing.
