### ISSUE TITLE
Node Editors - Add quick toggles to the different node editors

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2245]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/108069985-ff11d800-7031-11eb-85d9-d4a841c702ab.png)

![image](https://user-images.githubusercontent.com/35357409/108070534-a131c000-7032-11eb-95a4-7c05836209a7.png)
With new node editors requires new workspaces or faster editor switching. Just like we have quick toggles in the animation editors and in the outliner/properties, it might be useful to have quick toggles to the node editors also. 

# Task
Add a quick editor button switches to the compositor, shader and geometry nodes editor, and optionally the texuture nodes editor (which is a very broken editor from the Blender Render days). 

## Reason

It would be consistent with BFA UI, and save on using too many workspaces, it also aids in customizing editors a little easier. Also, in the future when the texture node editor is updated to be more compatible with GN and Shaders, it would be toggled often, or you'd need all three or two editors open at a time.

#### Status
Task is open to debate, not a task yet.

**Comment by ReinerBforartists** [comment]
Already thought about this. The only reason that i don't write such things down at the moment is that i want to empty the tracker down to the not so comfortable issues. So that we tackle these issues too.

Luckily we have a Draise ... :D

**Comment by ReinerBforartists** [comment]
Fixed in master

![switch](https://user-images.githubusercontent.com/13919702/109133812-a9d27680-7755-11eb-8b62-e7a70fcbf747.jpg)
