### ISSUE TITLE
Timeline Editor - Re-organize playback and keyframe controls to be more standard

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2246]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/108070737-da6a3000-7032-11eb-94bb-1dca6044d559.png)

According to a Bforartistst XT fork, the timeline was re-arranged to be similar or the same as many software playback controls. I thought this a good idea. 

1. Frame Range and start/end grouped together
2. To start, play/pause back, play/pause front, to end grouped together and standardized
3. Keyframe controls: last keyframe, keyframe, remove keyframe, next keyframe grouped together
4. Then the keying set, which wouldn't change. 

### Reason
![image](https://user-images.githubusercontent.com/35357409/108071109-52d0f100-7033-11eb-98b9-a9a47c60e8aa.png)
Currently the keyframe jump controls are seperated from the keyframe controls, and the timeline and playback doesn't have much of a hierarchy. Using the animation controls requires some getting used to as it's not a standard nor have a clear UI hierarchy for a clear UX and feature comprehension. 

# Task
Re-arrange the timeline playback controls. 

#### Status:
Open to debate, not a task yet.

**Comment by Draise14** [comment]
The cons I see about this is that the keying set keyframes may be also disconnect from the keyframe jump. 

But the issue right now is that the keyframe jump looks like a fast forward or rewind, not a keyframe jump. 

# Alternative task:
Change the fastforward and rewind icons to include a keyframe, so we know it is "fastforward to keyframe" and "rewind to keyframe".

**Comment by ReinerBforartists** [comment]
The red keyframe symbol is no playback functionality. That's why it is visually separated. This is by design. I don't want the user to record or to remove keyframes while playing back and do a wrong click ...

So please understand that i want not to change the playback arrangement here :)

**Comment by Draise14** [comment]
Ah sure, no problem. So I guess we can just modify the icons of the jump to keyframe buttons to make more sense?

**Comment by ReinerBforartists** [comment]
What exactly do you want to modify here? It's a general playback element.

**Comment by Draise14** [comment]
I think I will close this one and do another to just update the jump keyframe button icons to be a bit more explicit.

**Comment by ReinerBforartists** [comment]
Please also take into account that the same playback element is used to play videos for example. I don't really see a way to improve the icons here.
