### ISSUE TITLE
3D View - Integrate the Stored View addon more into the UI for ease of UX

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2247]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/108071951-52852580-7034-11eb-9cff-9ecdcf21654a.png)

With Bforartists XT fork, and in Softimage - you have the stored views exposed and set in the header of the viewport. In the image above, the top row is to write the stored view, and the one below is to activate it. 

This has kinda been already achieved with a prototype, and makes the stored view addon much more accessible and useful, without needing to dig through tabs and panels to quickly store a view and get back to it. 

![image](https://user-images.githubusercontent.com/35357409/108072494-f7076780-7034-11eb-804e-0c3390010f60.png)

# Task 
Evaluate if it's worth adding in UI entries or to modify the addon or create an addon for the addon so that these entries work with stored views seamlessly. 
Evaluate how to create the panel. 
Implement it if approved. 

#### Status
Needs debate and testing (how easy can it break?)
After aproval, might become a task.

**Comment by ReinerBforartists** [comment]
I am not happy to maintain a third party addon. The benefit is that the stored views is already onboard. But every update may break the modifications at the addon then.

**Comment by ReinerBforartists** [comment]
I simply miss the manpower. I have already problems to keep the handful modifications intact that i did at the original im and export addons. 

So closing, sorry.
