### ISSUE TITLE
Keymap - Update the brush to confirm on release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2249]
# Request
[https://twitter.com/jfranmatheu/status/1360540856667828226](https://twitter.com/jfranmatheu/status/1360540856667828226)

The keymap system has a new feature to confirm brush sliders resizing and such upon release. 

So... you press and hold F to resize (example), and when you release, it confirms. 

# Task 
This may need updating in the Bforartists keymap.

**Comment by ReinerBforartists** [comment]
Sounds like a useful improvement. But what exact keys are affected?

**Comment by ReinerBforartists** [comment]
Ah i see, all radial control hotkeys.

![allradialcontrols](https://user-images.githubusercontent.com/13919702/108587733-97bb9700-7355-11eb-9cf0-58c7069f452a.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
