### ISSUE TITLE
Radial Control hotkeys not longer showing in the text menu items

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2250]
We have changed the hotkeys for the radial controls. 

Keymap - Update the brush to confirm on release #2249

Now the menu items doesn't show the hotkeys anymore, which was the purpose to have these hotkey only tools in the text menus at all. Needs a fix.

![draw](https://user-images.githubusercontent.com/13919702/108621651-3d453800-7434-11eb-9106-85b781eab656.png)

**Comment by ReinerBforartists** [comment]
We have still a problem with the functionality here anyways. The radius shows in the header when calling the tool from the menu, not in the viewport. Maybe we should even remove the menu items completely.

**Comment by ReinerBforartists** [comment]
Let's remove the menu items in all editors and modes. They made nothing but trouble anyways since i invented them. Let's add a hint towards the hotkey into the tooltip instead. I had already started it. But there are a few missing.

I would still be interested how to show the correct hotkey in the slider tooltip. But when i look at the troubles we have here with just the menu items, then we better drop this idea, and give a hint towards a hardcoded hotkey instead.

**Comment by ReinerBforartists** [comment]
Detected two broken hotkeys too. Will be fixed with this issue.

**Comment by Draise14** [comment]
Ah, this sucks. I liked these entries in the menu to be able to see and modify and assign hotkeys easily in the GUI. Sucks it broke. But yeah, makes sense to second them to the tooltip. 

Blender community takes pride in hotkeys, but their hotkey management is some of the worst I've seen in any software. Ironic.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

Menu entries removed. The tooltips of the sliders with the radial functionality now all have a hint to the correct hotkey in the tooltip
