### ISSUE TITLE
Animation editors, make tab buttons wider

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2257]
Currently the buttons to switch between the animation editors have the same size than the rest of the tools. They don't visually stick out really. And looks more like other tools than tabs.

This saves on the one hand space. But doesn't really separate the tab elements from the rest of the UI. And with the small buttons it's hard to see which one is active. And bigger buttons is easier to click too.

Ideally would be tab riders. Maybe i should study the python api again. But i haven't achieved it so far. I doubt that we can add it into the header. More on top of it. And that would cost us precious space.

Alternatively we could make these buttons simply a bit wider. Not much, 1.2 looks okay. And maybe we find a way to color the buttons, so that the active tab sticks out more. I think i had this working somewhere already. Just need to find the commit ^^

Opinions?

![widertabbuttons](https://user-images.githubusercontent.com/13919702/108818553-d9e51280-75b9-11eb-9b2d-be47b5326c39.jpg)

**Comment by ReinerBforartists** [comment]
row. alert = True makes the buttons in this row red. 

See also here, alert: https://docs.blender.org/api/current/bpy.types.UILayout.html

But i know there was a trick to use other colors too. Not much, but one other color would be enough. And it's not in the API. I just can't find it anymore.

Anyways, making the buttons wider is imho already a little improvement.

**Comment by ReinerBforartists** [comment]
Ah, leaving it alone. We want to connect more editor types. And with outliner and properties editor we run into trouble in the header. Not really much space here.

Won't fix.

**Comment by Draise14** [comment]
Yeah, I think for consistency sake and the other editor header real estate, just having them grouped together is fine for now. I haven't had too much issue with that.
