### ISSUE TITLE
Grammar Improvement - Feature Page - Better Theme

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2261]
# Issue
Some grammar in the Features page about the default theme is a bit off:

> A theme with high contrast that doesn’t hurt your eyes, and is good to read without to get headache after ten minues.

Recommended, should be:
"A high contrast default theme that is easy on the eyes that helps reading without eye strain and prevents headaches over time."

**Comment by ReinerBforartists** [comment]
Bad english is the language of the world ^^

Will change it :)

**Comment by ReinerBforartists** [comment]
Fixed
