### ISSUE TITLE
Crash when using autocomplete with "bpy.types." multiple times

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2265]
**Describe the bug**
Crash when using autocomplete with "bpy.types." multiple times

can someone reproduce this? tested on master branch

the website release is not affected

Can't reproduce on Blender

https://user-images.githubusercontent.com/25552173/109251809-cec9f680-77f4-11eb-998f-397f4c183ac9.mp4

**Comment by ReinerBforartists** [comment]
Yes, is reproduceable. Unfunny. But i can also reproduce it with the Blender version that i have compiled last sunday. Let me pull the latest official builder version and check there ...

**Comment by ReinerBforartists** [comment]
Not to reproduce in the newest buildbot build. Let's wait for the sunday merge. I expect the crash to be gone then.

**Comment by iyadahmed** [comment]
Ok that's a relief, I think it will be gone then too

**Comment by ReinerBforartists** [comment]
Crash is still there -.-

**Comment by ReinerBforartists** [comment]
Crazy, when i run it from the console then it does not crash. But it takes a pretty while with every new try.

This one can be everything. I will do a debug build once the new Bforartists version is out.

**Comment by iyadahmed** [comment]
phew close one, glad it was gone

**Comment by ReinerBforartists** [comment]
Me too :D
Release is always a special pressure. I prepare version Bforartists 2.8.0 at the moment ...

**Comment by iyadahmed** [comment]
Awesome, excited for the new release!
