### ISSUE TITLE
Node Editors - Quick Toggle icon inconsistency with Shader and Texture

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2270]
# Issue
![image](https://user-images.githubusercontent.com/35357409/109518076-eebd1c80-7a77-11eb-86c8-c2c716062a82.png)
Right now, the quick toggle to the Shader Editor has the Texture Node Editor icon, not the Shader Editor icon. This is causing a little bit of confusion. 

# Task
Change icon to Shader Editor icon.

**Comment by ReinerBforartists** [comment]
Whoops ^^

Just curious, where do you get the Mtree Node Tree editor from? It's not in teh official release O_O

**Comment by Draise14** [comment]
It's an addon, to generate trees. Same with the Bake Node Editor. Eh.. just ignore in the capture.

**Comment by ReinerBforartists** [comment]
NEEED :D

**Comment by Draise14** [comment]
Here it is:
[Article about the addon](https://blender-addons.org/modular-tree-addon/)

**Comment by ReinerBforartists** [comment]
Thanks :)
I was just curious since addons usually don't add themselves as editors in this menu :)

**Comment by ReinerBforartists** [comment]
Fixed in master
