### ISSUE TITLE
Node Editor - Missing entries error from Eevee when using Cycles

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2274]
# Issue
![image](https://user-images.githubusercontent.com/35357409/109883990-3dbaab80-7c4a-11eb-906b-214abf10d6d3.png)
When using cycles and then going to the Modify/Converter panel, there a few missing nodes and an error in console. 

Bforartists 2.8.0

# Task
Find out why
Fix

**Comment by ReinerBforartists** [comment]
Thanks for the report. Investigating.

**Comment by ReinerBforartists** [comment]
Fixed in master
