### ISSUE TITLE
Build for Windows 10 ARM64

### ISSUE THREAD

**Issue by anonimo82** [Bforartists/Bforartists#2276]
**Is your feature request related to a problem? Please describe.**
I'd like to use it on my Lumia 950 XL, which I flashed Windows in

**Describe the solution you'd like**
I'd like to be able to use BForArtists on my phone

**Describe alternatives you've considered**
none

**Comment by ReinerBforartists** [comment]
Hi anonimo82,

We don't offer custom builds. sorry. Just Windows, Linux and Mac :)

What you could do is to google for Blender + arm64. And try to make a custom build with Bforartists. The way is the same.
Kind regards
Reiner

**Comment by anonimo82** [comment]
AFAIK, it's just a matter of compile for Windows on Arm, which is what, in example, did VideoLan with VLC.
I'm not asking a customized build, just target the arm architecture with yours

**Comment by ReinerBforartists** [comment]
Hi anonimo82,

As told, this would be a custom build. And we don't offer such a service. We just offer for the x64 platforms. When you need a build that runs on ARM, then you need to do that by yourself.

Kind regards
Reiner
