### ISSUE TITLE
Default Theme - Make noodles straight

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2277]
# Issue
![image](https://user-images.githubusercontent.com/35357409/110222868-84efa900-7ea3-11eb-8420-a5277aaaa95f.png)
Currently the default theme has curved noodles. For a lot of noding, sometimes it more organized and easier for the eye to lead to other nodes with a direct straight connection and eye movement. Having the eye lead a sine curve is not as efficient and with many connections, can be somewhat confusing. 

So..

# Task
![image](https://user-images.githubusercontent.com/35357409/110222870-87520300-7ea3-11eb-8916-5f1142b4e164.png)
![image](https://user-images.githubusercontent.com/35357409/110222871-88833000-7ea3-11eb-848e-6b8d0ebcc197.png)
Make the noodles straight by putting curve to 0.

**Comment by ReinerBforartists** [comment]
This is more a question of taste. I for example prefer the curved noodles. You can use reroute points to lead the noodles around other nodes.

In the end there can just be one default. And i don't want to change the current default for no real reason. So as sorry as i am, i have to decline this feature request.
