### ISSUE TITLE
Asset Browser: wrong environment icon

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2283]
![image](https://user-images.githubusercontent.com/25552173/110759462-4caaea80-8256-11eb-8b27-c0c6e87ebe85.png)

**Comment by ReinerBforartists** [comment]
Thanks for the report. 
The asset browser is still under heavy development. Who knows what changes will come here. So let's postpone this issue until the first final version appears.

**Comment by Draise14** [comment]
Yeah, the postpone makes sense. This editor and workflow is really half baked. It has half a dozen bugs, and the implementation is super inconsistent. Just a minor nuisance.

**Comment by ReinerBforartists** [comment]
Just to move this one out of the way ...

Fixed in master

![outoftheway](https://user-images.githubusercontent.com/13919702/114681823-cda24980-9d0e-11eb-92ee-fbef473d56f8.jpg)
