### ISSUE TITLE
Make it touch friendly

### ISSUE THREAD

**Issue by anonimo82** [Bforartists/Bforartists#2285]
**Is your feature request related to a problem? Please describe.**
No, it's just about usability

**Describe the solution you'd like**
I'd like a touch friendly key/mouse mapping, in order to use it with only left click and click and drag

**Describe alternatives you've considered**
I tried the MacOS key mapping, but it doesn't statisfy me

**Additional context**
Nothing

**Comment by ReinerBforartists** [comment]
Hi anonimo,
Have you tried the Industry compatible keymap?
My general problem is, i don't have a touchscreen and no tablet. So it's simply impossible for me to fulfill your request, sorry.

**Comment by anonimo82** [comment]
Well, you could try with your mouse using only the left button. By the way, no, I didn't try what you just adviced.

**Comment by ReinerBforartists** [comment]
That's not how things works, unfortunately. Blender, and also Bforartists, is meant to be used with the mouse or a tablet. Not b a pure touch screen :)

As told, there is little that we can do here. You could poke the Blender developers. They can change the features under the hood. We just change the UI.

So as sorry as i am, i have to close this feature request. We simply cannot achieve what you need.

Kind regards
Reiner

**Comment by anonimo82** [comment]
No problem, thanks for your help.

**Comment by anonimo82** [comment]
Just for the records, I found "Industry Compatible" ShortCuts to be what I was looking for.
Thanks so much =)

**Comment by ReinerBforartists** [comment]
Perfect :)

**Comment by anonimo82** [comment]
Hello again.
I'm in a context where I need the BForArtists keymap inside **regular** Blender, because I'm gonna use on a PinePhone, which is ARM based.
Any clue on what to do?

Thanks in advance for any help.

Cheers =)

**Comment by anonimo82** [comment]
Thanks for your help, but I saw in latest Blender there already is an option for industry compatible keymap.

**Comment by anonimo82** [comment]
Yes, but as I said earlier, I need it in "stock" Blender.
Just pointing out.
