### ISSUE TITLE
Geometry Nodes - Add new primitive nodes to sidebar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2294]
# Request
![image](https://user-images.githubusercontent.com/35357409/111650808-a752c200-87d3-11eb-815f-71f8197c8bd5.png)
Add iconography and node add panels for the new Geometry Nodes primitives committed from Blender. 

# Task
- Create icons
- Add to sidebar in new panel

**Comment by ReinerBforartists** [comment]
Wouldn't that be a double entry? :)
The nodes workspace has already the toolbar at the top.

**Comment by Draise14** [comment]
These are new nodes in the Geometry Nodes, used to create procedural assets. They are created in the node graph - and are forever dynamic.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/111656555-a2444180-87d8-11eb-9021-f56989ffe7ac.png)

Relevant commit: 
[https://developer.blender.org/D10715](https://developer.blender.org/D10715)

**Comment by ReinerBforartists** [comment]
Ah, glad that i have asked. When it's in the Add menu then it belongs to the sidebar too :)

**Comment by ReinerBforartists** [comment]
Not there yet. This will most probably arrive at Bforartists with the next merge.

![notyet](https://user-images.githubusercontent.com/13919702/111668369-f883a580-8815-11eb-8914-88cebba359b2.jpg)

**Comment by ReinerBforartists** [comment]
Here we go ...

![newmeshtypes](https://user-images.githubusercontent.com/13919702/111976881-6c69ca80-8b02-11eb-8ec8-ddcf056eefa7.jpg)

**Comment by ReinerBforartists** [comment]
Line needs a new icon.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/112306571-3b270100-8ca0-11eb-9d99-4a14ffd2ec8e.jpg)
