### ISSUE TITLE
New Collections tab - Restrictions panel - align props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2302]
We have a new tab in the properties editor. Collections. In the restrictions panel the props are middle aligned.

![lineartpanel](https://user-images.githubusercontent.com/13919702/111960066-8cdc5980-8aef-11eb-90d3-755aef20c5cd.jpg)

**Comment by Draise14** [comment]
Interesting new feature.

**Comment by ReinerBforartists** [comment]
Indeed. I have no idea what this should ever be good for ^^

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/112141339-74466f00-8bd5-11eb-8ed9-b8e4f9e4b5b4.jpg)
