### ISSUE TITLE
Context Menu - Missing shader icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2307]
# Issue
![image](https://user-images.githubusercontent.com/35357409/112234020-922dc700-8c09-11eb-8b6b-96e4900eab62.png)
The Shade Smooth and Shade Flat are missing their icons. 

Build: devbuild-21-03-2021

# Task
Add them back

**Comment by ReinerBforartists** [comment]
Ah, merges. The add current file icon seems to be wrong too ^^

**Comment by ReinerBforartists** [comment]
Ah cool, things like add current file is new features, and has slipped through it seems. The manual isn't up to date here neither.

**Comment by ReinerBforartists** [comment]
Draise, i cannot find the add current file entry. What kind of object is selected here? In what mode? Is this an addon maybe?

**Comment by Draise14** [comment]
The "add current file" is an Addon for an asset manager Connector. You can ignore. It was only the shade flat and smooth.

**Comment by ReinerBforartists** [comment]
Okay, thanks :)

Closing.
