### ISSUE TITLE
Node editors - Add menu - iconize Group and Layout submenus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2309]
The add submenus are now all iconitzed. Except two little sub menus. Group and Layout. 

Add icons to these menu items too if possible.

![missingicons](https://user-images.githubusercontent.com/13919702/112351338-16e01a00-8cca-11eb-8ac3-b2a8d2c5a96f.jpg)

**Comment by ReinerBforartists** [comment]
Hmm. Make Group and Ungroup is not to catch. Let's see if i get the needed inspiration tomorrow ...

**Comment by iyadahmed** [comment]
I think the icon should be set here, in the layout.operator 
![image](https://user-images.githubusercontent.com/25552173/112578245-4a23c580-8dfe-11eb-8eda-2e3400731607.png)

**Comment by ReinerBforartists** [comment]
Ah, thanks buddie. I already landed there too :)

**Comment by ReinerBforartists** [comment]
And fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/112598967-93c8dc00-8e0f-11eb-8655-dbbd7ead8126.jpg)
