### ISSUE TITLE
Geometry Node editor - add icons to the missing mesh node headers

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2310]
I have overlooked this one while adding the content to the sidebar. The new primitives nodes needs icons in the headers of the nodes too.

![missing](https://user-images.githubusercontent.com/13919702/112356265-b8696a80-8cce-11eb-8bfe-81aff2ec6cd6.jpg)

**Comment by iyadahmed** [comment]
Note that now the switch code is in rna_nodetree.c

**Comment by ReinerBforartists** [comment]
Thanks for the hint :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/112467055-d682a980-8d66-11eb-9675-a43c8b93f959.jpg)
