### ISSUE TITLE
3D View - Move "Vertex Group>Assign to New Group" up a level. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2312]
# Issue
![image](https://user-images.githubusercontent.com/35357409/112382879-64ed2180-8cba-11eb-97c7-6e088e6f6b7c.png)
This has a sub menu, and I'm not sure why. 

Would be nice to have this at a top level. 

# Task
- Move it up a level. 
- Rename the operator to "Assign to New Vertex Group"

**Comment by ReinerBforartists** [comment]
It is not just one operator. It's a whole bunch of tools that shows when you have a vertex group assigned to a mesh. Including a enumeration of the currently available vertex groups.

There is nothing to fix here, sorry :)

![vertexfunctionality](https://user-images.githubusercontent.com/13919702/112432455-37978680-8d41-11eb-9884-c91a9f7d07d8.jpg)

**Comment by Draise14** [comment]
Ah woops, totally forgot about those.
