### ISSUE TITLE
Fire+Smoke and Explosion macros

### ISSUE THREAD

**Issue by anonimo82** [Bforartists/Bforartists#2314]
**Is your feature request related to a problem? Please describe.**
No, it's not.

**Describe the solution you'd like**
Fire+smoke (Macro for the Particle System to procedurally generate fire and smoke)
Explosion (Like for fire+smoke, but oriented to the explosions - may be also add debris?)

**Describe alternatives you've considered**
It's already possible with using Particles, but I'd prefer an Out-of-the box Macro, so the user will just Add->Explosion or Add->Fire and have some parameters to set, having it working

**Additional context**
Nope

**Comment by ReinerBforartists** [comment]
Hey anonimo,

Thanks for the idea. This feature already exists. Have a look at the Object menu for the Quick Effects. You still have to adjust some parameters though.

![quickeffects](https://user-images.githubusercontent.com/13919702/112450940-340dfa80-8d55-11eb-9b43-6dc489098daa.jpg)

**Comment by anonimo82** [comment]
Oh, shame on me =)

**Comment by ReinerBforartists** [comment]
No problem :)
