### ISSUE TITLE
Node icon implementation problems - expected a string enum, not dict

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2316]
Houston we have a problem with our new icons in the add menu of the node editors.

The new argument icon leads to icons in the add menu. But also to a problem now. The new nodegroups fails to show in the group menu.

Not sure if this is a general problem, or connected to my latest change where i tried to give this node groups an icon. Investigating ...

![bug](https://user-images.githubusercontent.com/13919702/112604021-03da6080-8e16-11eb-851b-7dc802cc1c32.jpg)

![blendergroup](https://user-images.githubusercontent.com/13919702/112604036-06d55100-8e16-11eb-8ad3-6e86624b4903.jpg)

**Comment by ReinerBforartists** [comment]
@iyadahmed , i have to assign you here. This is a problem with your implementation. When i remove the icon=self.icon, then we have the group back in the menu, but the icons are gone ^^

**Comment by ReinerBforartists** [comment]
Where is this enum. I can't catch it :/

**Comment by ReinerBforartists** [comment]
And another symptom: readding the groups from the add menu items is broken too. We now produce nodes with missing data. Unfunny :(

![brokenfunctionality](https://user-images.githubusercontent.com/13919702/112608061-2c645980-8e1a-11eb-95e3-b1c89cce3646.jpg)

**Comment by iyadahmed** [comment]
> @iyadahmed , i have to assign you here. Could you please have a look? This is a problem with your implementation. When i remove the icon=self.icon, then we have the new created groups back in the menu, but the icons are gone ^^

Oh looking into it now

**Comment by iyadahmed** [comment]
Got it

**Comment by iyadahmed** [comment]
We just need to move the icon argument to the end, because node_group_items create NodeItems with a dict passed as 3rd argument
