### ISSUE TITLE
Subsurface radius fields are difficult to reach

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#2318]
**Describe the bug**
I don't use this very often, but every time I do, it's a bitch to use. The natural inclination is to click on or near the down arrow. The problem is that the popup/overlay/whatever-this-nonstandard-thing-is isn't full width and doesn't stay open, so when you try to move the cursor over to it, it disappears unless you carefully move sideways and _then_ down.

**Desktop (please complete the following information):**
macOS Big Sur

**Screenshots, Example Files**
<img width="232" alt="Screen Shot 2021-03-27 at 9 45 02 PM" src="https://user-images.githubusercontent.com/199713/112739927-6763ab80-8f46-11eb-8a59-3ef56a252d78.png">

**Comment by seanr** [comment]
Additionally, those subfields need to be labeled. What are the three values? Without looking at the docs, I have no idea that it's separate radii for each of the RGB channels.

**Comment by ReinerBforartists** [comment]
Thanks for the report. Not sure if we can fix this. This is internal node code. And i don't see a way to improve it. But let's keep it open.

**Comment by ReinerBforartists** [comment]
We could expose the three vector values. But this would make the node longer by three entries.

source\blender\nodes\shader\nodes\node_shader_bsdf_principled.c ,
class static bNodeSocketTemplate sh_node_bsdf_principled_in[] = {
Line 36, remove SOCK_COMPACT

But first i would love to hear other opinions here since i am not really happy to edit node code ...

![exposed](https://user-images.githubusercontent.com/13919702/113126609-1a1e5d00-9218-11eb-9c47-75a8aaa353ca.jpg)

**Comment by seanr** [comment]
Can that be made so that it expands to show the three fields rather than the popup? Your first mockup with the updated text in the second would be OK to me, but even better if it's normally collapsed.

**Comment by ReinerBforartists** [comment]
Well, you can have either expanded or collapsed. But the collapsed solution is what your request is about. That's the ugly popup then  :)

**Comment by ReinerBforartists** [comment]
So what is the state here? 
Shall we add RGB to the name?
Shall we make the sliders expanded?
Or shall we leave it as is? :)

**Comment by Draise14** [comment]
Hmm.. I am in theory ok with expanded, but yes, this is a huge node already. I do access this way too often though. 

It is RGB, though it's is a vector socket. Maybe we could make this more of a colour entry? Where the colour wheel pops up instead? I could be dreaming here. I never quite understood why an RGB was treated as a vector for this value.

**Comment by ReinerBforartists** [comment]
This is completely above my head. I can make it expanded or collapsed :)

**Comment by iyadahmed** [comment]
I believe that this option is not color, it is instead a value (radius) per channel.

**Comment by ReinerBforartists** [comment]
To be precise, it is a vector 3. With one value for each rgb channel. The result is of course a color then. But a color picker would imho not make much sense here.

**Comment by iyadahmed** [comment]
> To be precise, it is a vector 3. With one value for each rgb channel. The result is of course a color then. That's at least how i understand it. But a color picker would imho not make much sense here.
> 
> 
> 
> EDIT, i have to correct me, i think Iyad is right here. No color. But a radius per color channel. 

I think your words and my words are same 😅

**Comment by ReinerBforartists** [comment]
Yeah, it wears the word radius already in the title. 

Remains the question what to do here. Shall we expand it, or leave as is? :)

**Comment by iyadahmed** [comment]
I think if we want to solve the popup issue we would just expand it, and not worry about it being longer, it was already long, users hide unused sockets anyways, but that's just my opinion

**Comment by ReinerBforartists** [comment]
Then let's expand it.

**Comment by ReinerBforartists** [comment]
Fixed in master

![principled](https://user-images.githubusercontent.com/13919702/114140930-33f32a80-9911-11eb-97fc-fad5931dd9e1.png)
