### ISSUE TITLE
Document - Warn that any custom template or startup.blend crashes Bforartists Devbuild or Next Official Release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2324]
# Issue
![image](https://user-images.githubusercontent.com/35357409/112848405-ab050500-906d-11eb-85c8-b699c47e4966.png)
![image](https://user-images.githubusercontent.com/35357409/112848746-03d49d80-906e-11eb-9378-b06f5566585c.png)
If you have a custom startup or template, then they will crash Bforartists. 

I assume this is due to incompatible older versions of blend files with the latest editor updates and the toolbar.

# Task
Create a social media campaign to educate and warn users for next official release
Create a troubleshooting document to fix this

**Comment by ReinerBforartists** [comment]
I have placed a warning now at the devbuild section. The other half, to warn the users with the new version, will follow with the next  bforartists release then.

**Comment by iyadahmed** [comment]
Can you send the blend that crashes?

**Comment by Draise14** [comment]
A quick fix with old blends is to append the Scenes data to a new blend, and save as new file. I could quickly make a short document for that.

**Comment by ReinerBforartists** [comment]
Yes please :)

**Comment by Draise14** [comment]
File uploaded. 
[https://github.com/Bforartists/files/blob/master/tutorials/Updating%20old%20fIles%20to%20Bforartists%202.9.0.odt](https://github.com/Bforartists/files/blob/master/tutorials/Updating%20old%20fIles%20to%20Bforartists%202.9.0.odt)

**Comment by Draise14** [comment]
Ok, come to think of it, we may need two tutorials or to expand. As.. I wrote how to update old files, but I didn't troubleshoot when the old Startup.blend files would break and how to fix. So, will do that tomorrow.

**Comment by ReinerBforartists** [comment]
Also here, have you checked if the crash still happens with the newest dev version?

**Comment by Draise14** [comment]
Yes, still happens.

**Comment by ReinerBforartists** [comment]
Thanks :)

**Comment by ReinerBforartists** [comment]
This task has become obsolete. Closing.
