### ISSUE TITLE
Bug - Old *.blend files crashes devbuild-28-03-2021

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2325]
# Issue
![image](https://user-images.githubusercontent.com/35357409/112851411-9118f180-9070-11eb-80b0-017a83dff786.png)
When trying to load up any *.blend saved in previous versions, the devbuild hard crashes. 

Bforartists Version:  devbuild-28-03-2021

**Crash Log:**
````
# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF7251F89E2
Exception Module      : bforartists.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000020


Stack trace:
bforartists.exe     :0x00007FF72514A230  PyInit_aud
bforartists.exe     :0x00007FF724A07028  Symbols not available


Loaded Modules :
0x00007FF720800000 2.8.0.0              bforartists.exe  
0x00007FF9ADC70000 10.0.19041.844       ntdll.dll  
0x00007FF9AD5B0000 10.0.19041.804       KERNEL32.DLL  
0x00007FF9AB600000 10.0.19041.906       KERNELBASE.dll  
0x00007FF9AD7B0000 10.0.19041.906       USER32.dll  
0x00007FF9AB480000 10.0.19041.906       win32u.dll  
0x00007FF9AD3D0000 10.0.19041.746       GDI32.dll  
0x00007FF9AB930000 10.0.19041.746       gdi32full.dll  
0x00007FF9AB3B0000 10.0.19041.789       msvcp_win.dll  
0x00007FF98AC90000 2020.2.0.0           tbb.dll  
0x00007FF9AB4B0000 10.0.19041.789       ucrtbase.dll  
0x00007FF9ABDB0000 10.0.19041.906       SHELL32.dll  
0x00007FF9AB5B0000 10.0.19041.546       CFGMGR32.dll  
0x00007FF9467E0000 8.0.1.0              openvdb.dll  
0x00007FF9ABD40000 10.0.19041.546       WS2_32.dll  
0x00007FF976AA0000 10.0.19041.844       OPENGL32.dll  
0x00007FF93FE90000 3.9.2150.1013        python39.dll  
0x00007FF9AC680000 10.0.19041.746       RPCRT4.dll  
0x00007FF9ACE70000 7.0.19041.546        msvcrt.dll  
0x00007FF9AD670000 10.0.19041.610       ADVAPI32.dll  
0x00007FF9ADB00000 10.0.19041.746       ole32.dll  
0x00007FF9AD4B0000 10.0.19041.906       sechost.dll  
0x00007FF9ACB10000 10.0.19041.906       combase.dll  
0x00007FF9319F0000 58.29.100.0          avformat-58.dll  
0x00007FF9ABD30000 10.0.19041.546       PSAPI.DLL  
0x00007FF9949D0000 58.8.100.0           avdevice-58.dll  
0x00007FF931D30000 58.54.100.0          avcodec-58.dll  
0x00007FF9AC500000 10.0.19041.746       SHLWAPI.dll  
0x00007FF9ACA30000 10.0.19041.804       OLEAUT32.dll  
0x00007FF98AB60000 56.31.100.0          avutil-56.dll  
0x00007FF9ACF30000 10.0.19041.546       IMM32.dll  
0x00007FF9AB450000 10.0.19041.662       bcrypt.dll  
0x00007FF947270000 5.5.100.0            swscale-5.dll  
0x0000000070440000 1.0.28.0             libsndfile-1.dll  
0x00007FF93FD40000 1.20.1.0             OpenAL32.dll  
0x000000006ACC0000                      libgmp-10.dll  
0x00007FF93F970000 2.0.12.0             SDL2.dll  
0x00007FF9A8C50000 2020.2.0.0           tbbmalloc_proxy.dll  
0x00007FF98AAD0000 14.28.29913.0        MSVCP140.dll  
0x00007FF9ACF60000 10.0.19041.844       SETUPAPI.dll  
0x00007FF9A8BE0000 14.28.29913.0        VCRUNTIME140.dll  
0x00007FF99A9E0000 14.28.29913.0        VCRUNTIME140_1.dll  
0x00007FF994C90000 6.10.19041.844       COMCTL32.dll  
0x00007FF9A5A80000 10.0.19041.546       VERSION.dll  
0x00007FF98A9A0000 10.0.19041.1         AVIFIL32.dll  
0x00007FF976A70000 10.0.19041.844       GLU32.dll  
0x00007FF98F2B0000 10.0.19041.546       Secur32.dll  
0x00007FF9905A0000 10.0.19041.867       dbghelp.dll  
0x00007FF978500000 3.5.100.0            swresample-3.dll  
0x0000000070680000                      libfftw3-3.dll  
0x00007FF98C540000 10.0.19041.1         AVICAP32.dll  
0x00007FF99D400000 10.0.19041.546       WINMM.dll  
0x00007FF95F6A0000 2020.2.0.0           tbbmalloc.dll  
0x00007FF984540000 10.0.19041.1         MSACM32.dll  
0x00007FF968E10000 10.0.19041.1         MSVFW32.dll  
0x00007FF985580000 10.0.19041.1         winmmbase.dll  
0x00007FF9AB270000 10.0.19041.906       SSPICLI.DLL  
0x00007FF9AD400000 10.0.19041.746       shcore.dll  
0x00007FF9A9310000 10.0.19041.546       kernel.appcore.dll  
0x00007FF9A9510000 10.0.19041.906       windows.storage.dll  
0x00007FF9AAE20000 10.0.19041.662       Wldp.dll  
0x00007FF9A8E50000 10.0.19041.746       uxtheme.dll  
0x00007FF9ABA40000 10.0.19041.662       bcryptPrimitives.dll  
0x00007FF9919B0000 1.2.1.0              ShadowFX_64.dll  
0x00007FF9AB2F0000 10.0.19041.844       profapi.dll  
0x00007FF9AC5D0000 2001.12.10941.16384  clbcatq.dll  
0x00007FF9A5FC0000 10.0.19041.789       MMDevApi.dll  
0x00007FF9AB160000 10.0.19041.546       DEVOBJ.dll  
0x00007FF999310000 10.0.19041.906       AUDIOSES.DLL  
0x00007FF9AA9A0000 10.0.19041.546       powrprof.dll  
0x00007FF9AA810000                      UMPDC.dll  
0x00007FF9AC7B0000 10.0.19041.906       MSCTF.dll  
0x00007FF994FE0000 10.0.19041.746       dataexchange.dll  
0x00007FF9A80E0000 10.0.19041.906       dcomp.dll  
0x00007FF9A7170000 10.0.19041.746       d3d11.dll  
0x00007FF9A9CF0000 10.0.19041.746       dxgi.dll  
0x00007FF9A4EA0000 10.0.19041.746       twinapi.appcore.dll  
0x00007FF9A5E00000 10.0.19041.906       AppXDeploymentClient.dll  
0x00007FF96D000000 27.21.14.5671        nvoglv64.dll  
0x00007FF9A7150000 10.0.19041.546       WTSAPI32.dll  
0x00007FF9AAFA0000 10.0.19041.546       msasn1.dll  
0x00007FF9A4D80000 10.0.19041.906       cryptnet.dll  
0x00007FF9ABAC0000 10.0.19041.844       CRYPT32.dll  
0x00007FF9AAD80000 10.0.19041.546       cryptbase.dll  
0x00007FF9AB8D0000 10.0.19041.804       WINTRUST.dll  
0x00007FF9AA0F0000 10.0.19041.546       ntmarta.dll  
0x00007FF9A22D0000 10.0.19041.546       dxcore.dll  
0x00007FF97A910000 3.20.4.14            nvspcap64.dll  
0x00007FF9A9020000 10.0.19041.746       dwmapi.dll  
0x00007FF9AA160000 10.0.19041.546       WINSTA.dll  
0x00007FF999210000 10.0.19041.906       textinputframework.dll  
0x00007FF9A89B0000 10.0.19041.746       CoreMessaging.dll  
0x00007FF9A8650000 10.0.19041.546       CoreUIComponents.dll  
0x00007FF9A7F40000 10.0.19041.906       wintypes.dll  
0x00007FF9A3A20000 7.2.19041.746        Oleacc.dll  
0x00007FF931820000 1.0.5.8              Wintab32.dll  
0x00007FF931630000 5.3.5.3              Pen_Tablet.dll  
0x00007FF989F50000 10.0.19041.844       explorerframe.dll  
0x00007FF95BFF0000 14.28.29913.0        VCOMP140.DLL  
0x00007FF9A6FF0000 7.0.19041.867        propsys.dll  
0x00007FF9AAD60000 10.0.19041.546       CRYPTSP.dll  
0x00007FF9AA4C0000 10.0.19041.546       rsaenh.dll  

# Python backtrace
````

Are older scenes now incompatible? Is the next release not going to be backwards compatible? 

# Task
Find out what's up. Try fix, or merge in any Blender fixes.

**Comment by Draise14** [comment]
**Relevant Blender Task:**
[https://developer.blender.org/T86298](https://developer.blender.org/T86298)

**Comment by Draise14** [comment]
Looks like I will have to roll back a dev build release to keep working, but man, what a showstopper! Can't believe that bleed through to master.

**Comment by Draise14** [comment]
They have done a commit to fix, something about saving from new to old, then back to new.

**Comment by ReinerBforartists** [comment]
Thanks for the report and research. And sorry for the inconvenience.

This fix will then arrive next sunday here i guess. Then let's have another look at it.

**Comment by Draise14** [comment]
Ok, done some new tests. The issue remains, but it may be to a number of variables in production - be it broken addons, the toolbar issue, the bugs from Blender, or something else. Appending data to new usually fixes this. 

I have also tested with Iyad, that crashed on first use, then second use it didn't, so it's inconsistent. I think I will close this for now. 

I think the tasks in #2324 to troubleshoot this might help incase this bug happens.

**Comment by ReinerBforartists** [comment]
I think our bug here has nothing to do with the Blender bug that you have linked. This fail here is the enumeration of the editor types. I have just no idea how to fix this. The curious part is, it is not the first time that we get a new editor. But this time we are in trouble.

Somebody an idea here?

![crash](https://user-images.githubusercontent.com/13919702/113706137-9f08eb00-96de-11eb-8c35-e45d580b7eb2.jpg)

**Comment by ReinerBforartists** [comment]
Possibly related: https://github.com/Bforartists/Bforartists/issues/2286

**Comment by ReinerBforartists** [comment]
Ah, by the way, the merge happened after the devbuild, we are now a week behind. But the crash still persists as you can see.

**Comment by Draise14** [comment]
Ah ok, maybe it can fix in the next merge next week. I'll wait and do more tests. The pinning of this is a bit tricky - so I'll attach an old scene that causes the bug.
 
[Shader Ball_07.zip](https://github.com/Bforartists/Bforartists/files/6265109/Shader.Ball_07.zip)

**Comment by ReinerBforartists** [comment]
Killer bug. 

I have now set SPACE_SPREADSHEET to be the last number in the enum. The old file loads now. But Bforartists crashes in the moment when i try to load another template. I have replaced the default startup.blend. But not the startup.blend from the other templates.

source\blender\makesdna\DNA_space_types.h

    SPACE_TOPBAR = 21,
    SPACE_STATUSBAR = 22,
    SPACE_TOOLBAR = 23, /*bfa - toolbar*/
    SPACE_SPREADSHEET = 24,
  
  #define SPACE_TYPE_LAST SPACE_SPREADSHEET
  } eSpace_Type;

Well, it's at least the proof that the cause is indeed the order of the editors in the enum. A fix could be to set the SPACE_SPREADSHEET indeed to be the last editor in the list. But then we have the problem that loading a blend file with UI ticked will not longer load the correct editor types. They have it at number 23, we have it at number 24 then. See here: https://github.com/Bforartists/Bforartists/issues/2286#issuecomment-798939977

Hmmhmm.

**Comment by iyadahmed** [comment]
I think wrong editors are better than crash, it is still annoying though but less, until this issue is fix d

**Comment by ReinerBforartists** [comment]
There is no fix really then. Once we have it this way the startup.blend needs to stay the way they are. Or we run into crashes again. This is what worries me most. That we might run into the crash situation again with the next Blender editor.

But yeah, crash is worst solution ...

**Comment by Draise14** [comment]
No crash is always better. We have Load UI off anyway.

**Comment by ReinerBforartists** [comment]
Okay. Let's hope that we don't run into future trouble with this decision ...

**Comment by ReinerBforartists** [comment]
Crashes are gone. But as told, blender files with load ui ticked will load wrong when the new spreadsheet editor is open.

**Comment by Draise14** [comment]
No problem, as long as there is no crash, we are fine. Good thing anyone using BFA will default to load UI off, so it's a minor nuisance.
