### ISSUE TITLE
3D View - move lock camera to view widget to the align view button addon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2328]
# Request
Blender had added the lock camera to view to the top level as a viewport widget button. This means our camera lock to view will be a double entry our implementation should be a toggle for a personalization. 

Relevant Task:
[https://developer.blender.org/D10835](https://developer.blender.org/D10835) 

_I remember we wanted it as a widget but didn't figure it out and it's nice to see Blender catch up here. It is also nice to have used this feature often many times since it came to Bforartists. So much time saved!_

# Task
Add Lock Camera to View to custom header view toggles addon.

**Comment by ReinerBforartists** [comment]
After next merge. First the feature has to arrive here ...

**Comment by ReinerBforartists** [comment]
Fixed in master
