### ISSUE TITLE
Properties Editor - move Clear Custom Split Normals Data button to the Normals panel to make clear why Auto Smooth sometimes becomes dysfunctional

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2329]
# Issue
![image](https://user-images.githubusercontent.com/35357409/113356097-6399a580-9307-11eb-8a4b-64d470709d99.png)
Every now and then, the angle of the Autosmooth drop down ceases to open up, stuck frozen. 

# Task
Investigate if this is reproduceable or dependent on another setting
Figure out how to make this UX for this drop down a bit better.

**Comment by ReinerBforartists** [comment]
O_O

The condition is: 

if mesh.use_auto_smooth and not mesh.has_custom_normals:

My guess is that your mesh has custom normals. And then Autosmooth has no effect anyways. We could grey the auto smooth checkbox out when custom normals are involved.

I really feel more and more that i have lost connection to modeling. Just curious,  how do you add custom normals to a mesh?

**Comment by ReinerBforartists** [comment]
Ah, here you can reset the normals.

![clear](https://user-images.githubusercontent.com/13919702/113387987-a8681f80-938d-11eb-8843-79fa55db1990.jpg)

**Comment by ReinerBforartists** [comment]
Hmm, we could move this button into the normals panel. Then we have our "warning"

**Comment by Draise14** [comment]
YES PLEASE. Keep these normal info in the same section as.. Normals. I had no idea this was there.

**Comment by ReinerBforartists** [comment]
This is Blender usabiltiy. Spread the functionality across as many panels as possible :D

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixedinmaster](https://user-images.githubusercontent.com/13919702/114263086-ca901c00-99e3-11eb-906c-90b9e3ab19b5.jpg)
