### ISSUE TITLE
General - Header Preset Dropdown lists panels should close on selection

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2330]
# Request
![image](https://user-images.githubusercontent.com/35357409/113361078-bc217080-9310-11eb-99cc-b0d4b2989c6b.png)

In the header presets panel, when you select an option you get no feedback that it executed the change. It would be good if this panel would close when selecting an item. 

Reason:
Feedback that a setting was applied
Immediate exposure back to top level to keep working. 
A user in the discord requested it. 

# Task
Investigate if this is possible, then do it. 
If not possible easily, then report to Blender.

**Comment by ReinerBforartists** [comment]
I don't see a way to fix this at our end. This is best reported to Blender. But honestly i find the current way better. I hate dialogs that closes immediately. Maybe you did a misclick, and want to correct this mistake.

**Comment by ReinerBforartists** [comment]
Closing as won't fix.

**Comment by Draise14** [comment]
Ah ok. Well for good UI, there should be some kind of feedback when selecting something - but yeah, keeping it open is nice. I think at the root, you can't really tell if the setting is applied or not.
