### ISSUE TITLE
Bforartists won't load on Linux

### ISSUE THREAD

**Issue by WW773** [Bforartists/Bforartists#2337]
Hi, i'm currently using the most updated version of debian. When I found out about bforartists, I wanted to give it a shot, After it finished downloading, I launched it, and has been stuck on the application loading. I meet all the system requirements and it still won't load. Can you please help me?
![Screenshot 2021-04-06 9 20 05 AM](https://user-images.githubusercontent.com/82038699/113717238-6dc9f400-96b9-11eb-8ae5-2b0f5b5a6280.png)

**Comment by naetherm** [comment]
Could you start bforartists from the terminal and post the output, if there is no usable output you can try append --verbose.

**Comment by WW773** [comment]
Could you give the command line to do so? Thank you for your help!

**Comment by naetherm** [comment]
Should work with the following:
bforartists --verbose

**Comment by WW773** [comment]
ok. I will try it and give you an update

**Comment by WW773** [comment]
Update: Here's what happened
![Screenshot 2021-04-06 9 44 51 AM](https://user-images.githubusercontent.com/82038699/113720652-dcf51780-96bc-11eb-9cba-85b7ca7b1897.png)

**Comment by naetherm** [comment]
Thanks for the log, we are currently working on that issue #2284, #2205, #1728

**Comment by WW773** [comment]
Ok. Thank You so much!! and one more question. Since this runs on linux, how would save an animation you rendered, while being able to launch the file?

**Comment by ReinerBforartists** [comment]
Sorry, we don't understand this question :)

As for the glibc problem, the current developer build is made with Ubuntu 20.04 again. And it uses an older glibc version therefore. Could you please check if this version starts for you?

Linux Ubuntu  https://www.bforartists.de/data/dev/ubuntudevbuild-04-04-2021.tar.xz – 172 Mb

It can also be found in the download section of our page. https://www.bforartists.de/download/

In case everything else fails you could also build Bforartists by yourself. It misses Cuda and Optix then though with the defaults. And to get it compiled with Cuda and Optix is a bit of work ...

We have made a tutorial how to compile by yourself for Ubuntu a while ago: https://www.youtube.com/watch?v=sUhM2YSw1gQ

Kind regards
Reiner

**Comment by WW773** [comment]
Hi. So using the ubuntu way didn't work, but can you please tell me how to build Bforartists by myself?

**Comment by ReinerBforartists** [comment]
> In case everything else fails you could also build Bforartists by yourself. It misses Cuda and Optix then though with the defaults. And to get it compiled with Cuda and Optix is a bit of work ...
> 
> We have made a tutorial how to compile by yourself for Ubuntu a while ago: https://www.youtube.com/watch?v=sUhM2YSw1gQ

This way should work on most other linux distributions too.

**Comment by WW773** [comment]
How can I add the sudo apt add repository command? I use debian and that command line won't work

**Comment by ReinerBforartists** [comment]
It is all shown in the video. The console commands are the same :)

https://www.youtube.com/watch?v=sUhM2YSw1gQ

**Comment by WW773** [comment]
it's saying no file or directory. Do I have to download the .deb file first?

**Comment by ReinerBforartists** [comment]
This has nothing to do with a deb. This is compiling Bforartists by yourself, from scratch.

As sorry as i am, i have reached the border of support that i am able to give. The necessary steps are all described in the video.  And i have even pasted the console commands in my above post. You most probably overlook one. I love to help, but at this point i am simply lost how i could assist you any further.

I would say, wait for the next Bforartists version. It will most probably work on older Linux versions then too. 

Closing this issue now. The problem that the current Bforartists version does not run at older Linux distributions is known and in the works. And has their own issues already.

Kind regards
Reiner
