### ISSUE TITLE
Bforartists troubleshoot on linux debian

### ISSUE THREAD

**Issue by WW773** [Bforartists/Bforartists#2338]
Hi, i'm currently using the most updated version of debian. When I found out about bforartists, I wanted to give it a shot, After it finished downloading, I launched it, and has been stuck on the application loading. I meet all the system requirements and it still won't load. Is their any other way I can get it to launch without it being stuck on loading?
Screenshot 2021-04-06 9 20 05 AM

**Comment by ReinerBforartists** [comment]
Closing this as a duplicate. The same task exists here already: Bforartists won't load on Linux #2337
