### ISSUE TITLE
main screen goes blank switching cameras 

### ISSUE THREAD

**Issue by shawnp30** [Bforartists/Bforartists#2339]
i haave run into an issue. if i use a cube add an emission node and belzier curve, fit camera to that belzier curve and try to use the render camera and zoom in or pan all of my objects disappear. i can see my cube in the other windows, just not the main start up object window 
![snip](https://user-images.githubusercontent.com/20215592/113954615-268e5100-97e8-11eb-98c2-d8f7dcf56cb3.PNG)

**Comment by ReinerBforartists** [comment]
Hi,

Thanks for the report. I don't think this is a bug. But that there is simply nothing to see through the camera. We need more informations. Have you checked if this happens with Blender too? Could you please provide the blend file?

Kind regards
Reiner

**Comment by shawnp30** [comment]
https://user-images.githubusercontent.com/20215592/114053170-b53cb580-985c-11eb-8599-4178fdccccd2.mp4

**Comment by ReinerBforartists** [comment]
> Have you checked if this happens with Blender too? Could you please provide the blend file?

**Comment by shawnp30** [comment]
https://user-images.githubusercontent.com/20215592/114058767-c0deab00-9861-11eb-8eb8-947b83075954.mp4


[blend.zip](https://github.com/Bforartists/Bforartists/files/6279917/blend.zip)

**Comment by ReinerBforartists** [comment]
Thanks :)

I have reproduced it in Blender meanwhile. Definitely an interesting bug in connection with the follow path constraint. The camera jumps completely away in the moment when you do any navigation while being in camera view. It already jumps in the moment when you add the constraint. 

So the solution is to press reset 3d view when outside of the camera view. And putting the camera back to a position within usable workspace values. And don't do any camera navigation anymore.

As told, Blender behaves exactly the same. So this is best reported to Blender. We usually don't fix broken Blender features. We at Bforartists just modify the UI.

![cameralocation](https://user-images.githubusercontent.com/13919702/114059559-c6a1b400-9894-11eb-911a-ad4d396bac2c.jpg)

**Comment by shawnp30** [comment]
I don’t have that problem in blender. Only in blender  for artist. 
![4F71A958-B290-4834-8DD4-BDF0C2B2EDBC](https://user-images.githubusercontent.com/20215592/114060919-dbb21f00-9863-11eb-98e4-2dc9120503d1.jpeg)
![034844B8-D9D5-47E6-9313-9D0437D2510C](https://user-images.githubusercontent.com/20215592/114060923-dc4ab580-9863-11eb-93b9-916eb8cf41ed.jpeg)
This is what shows when using bfora blender shows regular numbers with no disappearing. How is this. It a bfora bug?

**Comment by ReinerBforartists** [comment]
No it is not. We just have Lock camera to view on by default. That's the secret. Means you navigate in the camera already. As told, i have reproduced the bug in Blender. And reported it. Let's see what the outcome is.

https://developer.blender.org/T87313

**Comment by ReinerBforartists** [comment]
I'll gonna close this one as known issue. We can't do anything here anyways. Waiting for the Blender developers to fix it.
