### ISSUE TITLE
Building Bforartists

### ISSUE THREAD

**Issue by WW773** [Bforartists/Bforartists#2341]
Hi, I was wondering how can I build bforartists step by step on Linux? My Linux OS is debian 10

**Comment by ReinerBforartists** [comment]
Hey ww773,
We have explained it here already: https://github.com/Bforartists/Bforartists/issues/2337

As told in the other issue, and as sorry as i am, i have reached the border of support that i am able to give. The necessary steps are all described in the video. And i have even pasted the console commands in my above post. You most probably overlook one. I love to help, but at this point i am simply lost how i could assist you any further. It does not play a role if you try to build at Ubuntu or Debian.  Ubuntu is in fact based at Debian. You need in both cases the console. And the console commands are the same.

Kind regards
Reiner
