### ISSUE TITLE
Hotkeys - Reset to Default with hover + Backspace missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2343]
# Request
![image](https://user-images.githubusercontent.com/35357409/114285536-86ba0880-9a1d-11eb-8f56-96ed818006f2.png)

When you hover over a value, you either have to use an arbitrary hotkey in the right click menu or the right click menu entry to reset a slider value. Or sometimes you can just press backspace over the entry when hovering and it can reset. This is a Blender hotkey feature. 

# Task
Add this to the BFA defaults. 

### Reason
A user in Discord and myself included have needed this.

**Comment by ReinerBforartists** [comment]
Fixed in master
