### ISSUE TITLE
Eevee Volumes - Tile Size 1px

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2345]
# Request
![2px](https://user-images.githubusercontent.com/35357409/114287489-d3591000-9a2c-11eb-856b-9ede1e1aa754.jpg)
Currently, the Eeevee Volumetrics tile is set to 2px. 

![1px](https://user-images.githubusercontent.com/35357409/114287499-dce27800-9a2c-11eb-8d4a-f68d10c2951f.jpg)
For high fidelity renders, sometimes 1px is required. 

This can be changed to higher fidelity renders. 

# Task
Add a 1px tile size as an option
![image](https://user-images.githubusercontent.com/35357409/114287389-0b138800-9a2c-11eb-9f64-34ef087df0e4.png)

Add a warning about 1px to the tooltip on a new line
![image](https://user-images.githubusercontent.com/35357409/114287514-fb487380-9a2c-11eb-8635-215ad5cacbef.png)

**Comment by ReinerBforartists** [comment]
Do it :)

**Comment by Draise14** [comment]
Will commit this one tomorrow.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/116127391-64ff8900-a68d-11eb-91e8-096528e4b035.png)

Ok, committed. I added the a note to the tooltip that this also increases render times.

**Comment by Draise14** [comment]
Wait, will tag as fixed, and close when merged.

**Comment by ReinerBforartists** [comment]
Ah, overlooked. You can link pull requests. Then the issue closes when the pull request is fulfilled :)

Have a look at the right side, the menu item Linked Pull Requests.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/121788189-e5703f80-cb90-11eb-9466-ade0fd1bdda7.png)

The change reverted somehow, the 1 px volumetric tilesize now is the one and the same as the 2 px. A digit should be "1" instead of "2". 

# Task
Fix again. 

Line 6941

**Comment by ReinerBforartists** [comment]
This happens when you forget to comment the change ;)

**Comment by seanr** [comment]
Is this worth a release?

**Comment by ReinerBforartists** [comment]
It is not broken, so no. It's just back at the Blender defaults.

**Comment by ReinerBforartists** [comment]
Fixed in master
