### ISSUE TITLE
Remove select through patch

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2348]
The select through patch makes too much trouble. Selecting in face mode does not work. And we have a conflict with old tools. It also raises a few questions. The patch was never finished, but abandoned. And i don't really want to develop this patch to a higher level. Bforartists stands for development at the UI, not at the features end. 

So let's remove this patch again. Was a nice try.

Related: https://github.com/Bforartists/Bforartists/issues/2287

**Comment by Draise14** [comment]
Yeah.. makes sense. It has some troubles and the maintainer of this patch is a bit awol. It was an exciting ride nonetheless! 

I guess a rule of thumb for patches is that it needs an active maintainer before going in. most likely the author of the patch.

**Comment by ReinerBforartists** [comment]
No, that's not necessary. But the patch should already work. And this select through patch has some issues.

**Comment by ReinerBforartists** [comment]
Done. 

Now the manual ...
