### ISSUE TITLE
Grease Pencil Vertices not highlighting

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#235]
When you go into the Grease Pencil editing mode, the vertices do not highlight. You can show the vertices, but they just won't highlight. 

Bforartists 1.0.0

Maybe in 2.8 it will be fixed. 
**Issue**
![2018-07-12_17-27-17](https://user-images.githubusercontent.com/35357409/42662889-efa879c6-85f8-11e8-838d-cf8c7ca58584.png)

**Supposed to work like this:**
![pureref_2018-07-12_17-28-35](https://user-images.githubusercontent.com/35357409/42662916-03686ec6-85f9-11e8-81bb-8db458cb922c.png)

**Comment by Draise14** [comment]
Hmm.. ok, seems it's with my template. I reset to factory, no issue. Ergh.

**Comment by ReinerBforartists** [comment]
I think we have been at the point before that the template system is not useable in 2.79 ...

**Comment by ReinerBforartists** [comment]
Just curious, do we still have a task here? You have resolved the issue, right?

**Comment by Draise14** [comment]
Yeah, I reset everything and rebuilt everything. This time keeping a backup.
