### ISSUE TITLE
Edit Menu - move new Open Preferences folder one upwards

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2352]
Just found out while testing that the Preferences are not so good to reach anymore. We open the Preferences a bit more often than the path. So i want to have Preferences at the end of the menu. Better for the muscle memory.

![edit](https://user-images.githubusercontent.com/13919702/114423809-d5030f00-9bb7-11eb-9c79-85cbef19a90e.png)

**Comment by ReinerBforartists** [comment]
Fixed in master

![editmenu](https://user-images.githubusercontent.com/13919702/114424296-404ce100-9bb8-11eb-8dc2-bb56549f638c.png)

**Comment by Draise14** [comment]
Sounds like a good position! Did not think of that. Good call.

**Comment by ReinerBforartists** [comment]
I haven't thought of this neither, until i tried. So all is well :)
