### ISSUE TITLE
Workspaces - Missing Toolbar in some layouts

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2353]
# Issue
![image](https://user-images.githubusercontent.com/35357409/114427078-56d74600-9b80-11eb-8ab0-8292535b4e8f.png)
Just been going through the default layouts, rebuilding them to work around the past weeks issues. 

I noticed there are some workspaces missing the toolbar startup "All". 
- Masking
- Compositing

# Task
- Add the toolbar to these workspaces with **File** group and **Misc** Groups activated.

**Comment by ReinerBforartists** [comment]
Odd. Here they show. O_O

![isthere](https://user-images.githubusercontent.com/13919702/114426651-90c53e00-9bba-11eb-9d9c-46f9aee0a363.jpg)

**Comment by Draise14** [comment]
The layout in the capture has no toolbar.

**Comment by ReinerBforartists** [comment]
Ah, you mean the toolbar. It does not exist in this layouts yet. So they are not missing, but not implemented yet :)

**Comment by ReinerBforartists** [comment]
Fixed in master
