### ISSUE TITLE
Preferences - Blender Version shows incorrectly

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2356]
# Issue
![bforartists_lSLMKrKjWP](https://user-images.githubusercontent.com/35357409/114893284-2d622880-9dd3-11eb-865e-f9aa9cb0ef16.png)
Currently you can toggle the Status Bar to show blender version number, but it's incorrect and this is Bforartists, so it might be useful to clarify. Though for feature's sake and Blender publicity, Bforartists could still "refer" to the blender version we fork off from. Though I recommend turning it off by default. 

# Task
- Correct Blender version number
- Change from "Blender Version" to "Blender Source Version"
- Turn off by default in the default settings or config.blend.

**Comment by ReinerBforartists** [comment]
We need to rename this prop. It shows the Bforartists number, not the Blender number anymore.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fits](https://user-images.githubusercontent.com/13919702/114902230-e77a8400-9e15-11eb-835e-3388e5556a7b.jpg)
