### ISSUE TITLE
Texture Paint - Texture Stencil overlay missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2358]
# Issue
![image](https://user-images.githubusercontent.com/35357409/114904363-669f9600-9ddd-11eb-91a9-61b98e9cf186.png)
In Bforartists 2.8.0 and devbuilds, it looks like the texture-paint stencil mode is broken. It's not showing in the overlays, regardless of settings. 

Desired result from Bforartists 2.7.0:
![bforartists_nvLRiMe6k7](https://user-images.githubusercontent.com/35357409/114904368-68695980-9ddd-11eb-9ff1-91598bcb236a.png)

# Task
Investigate why
Fix or work out an easier UX to make it work (if not broken)

**Comment by Draise14** [comment]
Ah ok, tested the date of the dev builds of blender - issue is the same in Blender as it is in Bforartists. So this is a top level issue.

**Comment by Draise14** [comment]
Wait, something is wrong in the scene.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/114910800-f0526200-9de3-11eb-8ef8-cc464b938614.png)

Ok. I have got Blender to show stencil, ok. But in Bforartists, I can only make the stencil show in the Paint Image mode, not in the 3D view. Stencil is working though, but the overlay is still missing.

**Comment by Draise14** [comment]
Ah. I think I found it. 

Blender task (from last week)
[https://developer.blender.org/D10915](https://developer.blender.org/D10915)

I am running a build to test it. Maybe this will fix next merge.

**Comment by ReinerBforartists** [comment]
Don't forget, we are a week behind with the merges. This fix will then come with the devbuild of sunday in a week ;)

**Comment by Draise14** [comment]
Ah sh*t, just wasted half of my labour day with deadlines because of this. Though this was a fix from a week ago (7th), it should come this Sunday no?

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/114922162-fb5fbf00-9df0-11eb-981f-78c24428b608.png)

Ok, that was the bug, and the fix.

== was supposed to be !=

**Comment by ReinerBforartists** [comment]
As told, we do the dev build before the merge now. One week delay for this fix to arrive, sorry :)

**Comment by Draise14** [comment]
No problem. I will have to maybe think of using stable releases for work, yet keep experimenting with dev builds to find things like this meanwhile. Sometimes I just can't wait to use the dev build UI features in production - but yeah.. comes with hiccups sometimes. Even stable releases have their brand of hiccups devbuilds usually fix also. So.. I guess I have to learn to jump back a version or two if anything. And MAYBE have a blender daily with the settings of Bforartists applied just in case.. And also put my render node to compiling Bforartists so I can keep working resources free.  

Just thinking out loud.

**Comment by ReinerBforartists** [comment]
The issue seems to be fixed. So closing.

![fixed](https://user-images.githubusercontent.com/13919702/115367211-49483e80-a1c6-11eb-810b-ab17f349615a.jpg)
