### ISSUE TITLE
Mesh Relax - Bforartists Version: Error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#236]
I get an error trying to get the **Mesh Relax - Bforartists version** working when activating the addon. 

Bforartists 1.0.0

![bforartists_2018-07-12_19-05-50](https://user-images.githubusercontent.com/35357409/42665727-ac60974e-8606-11e8-9af6-fa083f3b1c40.png)

![bforartists_2018-07-12_19-06-35](https://user-images.githubusercontent.com/35357409/42665746-b3a40202-8606-11e8-8ff0-5fb64eb76390.png)

**Comment by ReinerBforartists** [comment]
This bug is already fixed in master since a while.

https://github.com/Bforartists/Bforartists/issues/211
