### ISSUE TITLE
Properties Editor - Dimensions needs better labeling

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2360]
# Issue
![image](https://user-images.githubusercontent.com/35357409/115058279-b8fab880-9eaa-11eb-83cf-86cbefae63bd.png)

Right now the labels and sub-lables of Resolution and Aspect are pretty rough. We fixed labeling to have the header label and sub-labels more organized and readible. Can we do the same here?

# Task
Move the words "Resolution" and "Aspect" up a line before the slider group. 

Example:
![image](https://user-images.githubusercontent.com/35357409/115058496-ee070b00-9eaa-11eb-9583-f6b1f7d8dba1.png)

**Comment by ReinerBforartists** [comment]
Ah yes, that's the Blender way of labeling still.

**Comment by ReinerBforartists** [comment]
Hm, not sure what exactly to improve here. The edit boxes are already pretty tall.

**Comment by ReinerBforartists** [comment]
Fixed in master.

Needs documentation.

![fixed](https://user-images.githubusercontent.com/13919702/115362421-cde48e00-a1c1-11eb-968c-810535d54e85.jpg)

**Comment by ReinerBforartists** [comment]
Documentation comes with the next merge manual commit. Closing.
