### ISSUE TITLE
News Post - Change title to look less.. like a warning about Bforartists

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2361]
# Issue
![image](https://user-images.githubusercontent.com/35357409/115059291-f90e6b00-9eab-11eb-856c-22b4c8163853.png)

Right now the title of this announcement grammatically means "Beware of Bforartists, it could be a scam", not quite the right message. 

# Task
It should be "Beware of users scamming with Bforartists!" and with maybe a quick addition of  "Bforartist is and will remain free".

**Comment by ReinerBforartists** [comment]
Done. Thanks for the heads up :)
