### ISSUE TITLE
Add Camera Lock Gizmo again after merge

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2362]
it seems they removed a function needed for it
![image](https://user-images.githubusercontent.com/25552173/115140747-22a8cd00-a039-11eb-9483-c7631898f811.png)

here's the function we could simply restore it:
in out current code `view3d_gizmo_navigate.c` Line 84
![image](https://user-images.githubusercontent.com/25552173/115140764-3fdd9b80-a039-11eb-84e3-634dc70bb7dd.png)

**Comment by iyadahmed** [comment]
https://developer.blender.org/D10835

**Comment by iyadahmed** [comment]
ok they are trying to remove it
https://github.com/blender/blender/commit/4baf3964aee251a491a0315a104b234515a6dd0e

**Comment by ReinerBforartists** [comment]
That's the conflict that i have meant :)

As told, when unsure, revert the code to Blender state. Then make a task, then resolve it.

I am still unsure here what to do. The Lock ot Camera View operator still works. But they have removed the Lock in the navigation elements again. And i want this element back. It was useful. The patch was from Harley when i remember right. We need to dig for it.

![gone](https://user-images.githubusercontent.com/13919702/115141367-2722b500-a03c-11eb-84c4-71f616236931.jpg)

**Comment by ReinerBforartists** [comment]
Why do you close it? It's a task ^^

**Comment by iyadahmed** [comment]
Ok the task then is to add the operator again,
Apparently they removed it because of this bug

https://developer.blender.org/T87386

**Comment by ReinerBforartists** [comment]
So they don't resolve the crash but remove the feature? Great :/

**Comment by iyadahmed** [comment]
Yeah XD

**Comment by ReinerBforartists** [comment]
I remember that i have seen this crash before with reload UI. So what they did was just to remove a clear way to reproduce this bug.

Anyways, a normal user will never ever reload the complete UI. And addon developer develops more at Blender than at Bforartists. So for me it's a no brainer to add the lock back to where it was :)

**Comment by iyadahmed** [comment]
Yep, and we can also later investigate the actual problem

**Comment by ReinerBforartists** [comment]
Let's revert this change, and bring our toggle back.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/115358435-f10d3e80-a1bd-11eb-93bf-8189f4644fd2.jpg)
