### ISSUE TITLE
Spreadsheet editor theme

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2363]
the new editor seems to have new theme entries, update BFA themes to take it into account

**Comment by ReinerBforartists** [comment]
It is what we call Nodes. In our templates this layout exists in the All and the VFX templates. The spreadsheet editor didn't exist when we made this workspace.

Shall we add the workspace to the default workspace too? It seems to become an important workspace.

We should keep our shorter name. We have a switch to switch between the different node editors.

![nodes](https://user-images.githubusercontent.com/13919702/115192544-3f9dd880-a0eb-11eb-8f4d-9d3d2c9cdad9.jpg)

![blender](https://user-images.githubusercontent.com/13919702/115192614-55ab9900-a0eb-11eb-8daf-3f85245a5365.jpg)

**Comment by iyadahmed** [comment]
Yep, but I meant the spread sheet colours themselves

**Comment by ReinerBforartists** [comment]
XD

Theme entries. Now i have understood it ^^

Will make a new issue for the workspaces.

**Comment by ReinerBforartists** [comment]
The theme does fit from what i can see. The only thing that we could improve is to use the outliner background colors in the spreadsheet area too. It sticks a bit out at the moment.

![brighter](https://user-images.githubusercontent.com/13919702/115225830-d7f98480-a10e-11eb-9275-9ff68ff49133.jpg)


![same](https://user-images.githubusercontent.com/13919702/115225729-b7312f00-a10e-11eb-87bc-6a4e8d35f401.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/115269595-c5e20b00-a13b-11eb-91b4-fedb310b2cbe.jpg)
