### ISSUE TITLE
Fork addons repos and use submodules

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2364]
It would be easier if we forked Blender's addons and addons_contirib repos, add BFA changes, so that Bforartists has its own version

**Comment by ReinerBforartists** [comment]
Hm. I'm no friend of sub modules. For me it would complicate things. And the amount of work is the same. Just that we currently have everything at one place. We need to check for changes regularly anyways. And this is best done when merging.

**Comment by iyadahmed** [comment]
Ok, closing then, it would be more organised but yeah not necessary

**Comment by ReinerBforartists** [comment]
I respect your opinion, but i don't see that it would be more organized. It would be imho just more cluttered. More places that you happily forget about maintaining it. The sub modules also gave me a hard time in the beginning until i realized where the addons are ...
