### ISSUE TITLE
Update nodes workspace

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2367]
Our nodes workspace needs an update. The spreadsheet editor did not exist when we made our nodes workspace.

Add it to the default templates too. It will become an important workspace.

![nodes](https://user-images.githubusercontent.com/13919702/115195209-c30cf900-a0ee-11eb-8cd2-41d45eda87fc.jpg)

![blender](https://user-images.githubusercontent.com/13919702/115195265-d4ee9c00-a0ee-11eb-836a-2e2126e5c53b.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

Needs work, needs update in the manual. Waiting for merge task to be finished.

**Comment by iyadahmed** [comment]
> Fixed in master
> 
> 
> 
> Needs work, needs update in the manual. Waiting for merge task to be finished.

The spread sheet needs a while new section right?

**Comment by ReinerBforartists** [comment]
Already has. Im a busy little rascal sometimes :)

https://github.com/Bforartists/Manual/blob/master/30%20Editors%20-%20Spreadsheet.odt

**Comment by iyadahmed** [comment]
> Already has. Im a busy little rascal sometimes :)
> 
> 
> 
> https://github.com/Bforartists/Manual/blob/master/30%20Editors%20-%20Spreadsheet.odt
> 
> 
> 
> But the chapter that needs an update for this task is the chapter around the workspaces. New screnshots  and descriptions ...

Ah ok 😄

**Comment by Draise14** [comment]
I like the Nodes layout without the spreadsheet. If we have a geometry nodes layout added, I'd be ok with that (one with the spreadsheet added), but the nodes layout is good for other addons like Animation Nodes, Sverchok, Node Wrangler, Modular Tree, etc.

**Comment by ReinerBforartists** [comment]
Too late, i have added it already :)

Mh, we simply need one layout that has the spreadsheet editor open so that the users knows it exists. And the nodes layout makes most sense here. Here is also the place where you might need the spreadsheet editor.

**Comment by ReinerBforartists** [comment]
Documentation comes with the next merge manual commit. Closing.
