### ISSUE TITLE
Fix Point Cloud Attribute Names

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2371]
![image](https://user-images.githubusercontent.com/25552173/115362737-23209f80-a1c2-11eb-97ab-d6c5d5c37a13.png)

**Comment by ReinerBforartists** [comment]
What exactly is to fix here?

**Comment by iyadahmed** [comment]
it was like this before
![image](https://user-images.githubusercontent.com/25552173/115363535-d7222a80-a1c2-11eb-9970-7e4b3a87c212.png)

**Comment by ReinerBforartists** [comment]
O_O

Ah, merges ^^
