### ISSUE TITLE
Readd im and export icons for gltf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2372]
This one slipped through with the last merge. We lost the gltf im and export icons in the file menu.

Add the icons back.

![gltf](https://user-images.githubusercontent.com/13919702/115364319-8fe86980-a1c3-11eb-88b2-d4990e966587.jpg)

**Comment by ReinerBforartists** [comment]
Here comes the backup in handy ;)

**Comment by iyadahmed** [comment]
Yep exactly :)
