### ISSUE TITLE
Remove double menu entry Area

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2379]
Blender devs have added the area sub menu content to the right click menu in the header now. For Bforartists that's one menu too much though.

Question is which one to keep. For consistency reasons i would even vote to remove the entries in the view menu. And keep the ones in the right click menu of the header. Since some editors doesn't have a view menu. We would need to iconize the entries in the header right click menu then though. On the other hand, the header can be hidden ...

Ideas?

![doublemenu](https://user-images.githubusercontent.com/13919702/115986041-c13fab80-a5ae-11eb-985c-8dfddee468e9.jpg)

**Comment by Draise14** [comment]
Yeah. Remove form view menu as it's not always in all editors but it's an operator for all editors.

**Comment by ReinerBforartists** [comment]
Okay, we have our task ^^

Thanks :)

**Comment by ReinerBforartists** [comment]
New icons ...

![headermenu](https://user-images.githubusercontent.com/13919702/116275355-d7eb2b80-a783-11eb-8cf2-b6b078e6dbd4.png)

**Comment by ReinerBforartists** [comment]
Fixed in master.
