### ISSUE TITLE
Sculpting with Dynatopo extremely unstable

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#238]
I have been trying to sculpt with Dynatopo in Bforartists 1.0.0, and I have recorded how long it usually takes me to crash it in that workflow - and about 3-5 minutes of sculpting will hard crash Bforartists, almost garunteed (even on default cube). 

I have had this happen multiple times on multiple machines. I will be testing also on Blender, but thought to put it out there. I'm now running it with the Windows Power Shell console so it stays open and shows me any new errors - if there are any. I'll be reporting.

**Comment by ReinerBforartists** [comment]
I think i have seen this crashes in Blender too.

**Comment by Draise14** [comment]
Yes. Probably. I have spent hours sculpting in Bforartists with up to 6 million tris without crashes - and I've found the culprit.

The Symmetry panel axis makes it immediately unstable. I can sculpt for a couple of minutes with a garunteed crash. No error in the console. 

Maybe since the Dynatopo has a "Symmetrize" operator, nearing on a double entry - it might be best to grey out the Symmetry/Lock axis panel - it would make things "feel" more stable.

**Comment by ReinerBforartists** [comment]
Interesting observation. Is this reproduceable in Blender? In that case a bug report to Blender would be useful. But we need to be able to reproduce it in Blender 2.8. They won't fix anything in Blender 2.79 anymore.

For your suggestion, i am not really keen to lock a feature that is available in Blender ...

**Comment by Draise14** [comment]
I also found another factor. Symmetry is stable at higher Constant detail than lower ones.

**Comment by Draise14** [comment]
Let's try reproduce in Blender.

**Comment by Draise14** [comment]
Ok.. I ... hate using Blender. But I couldn't crash it. I also tried out the new workflows of upping the constant Dyntopo detail in Bforartists, and now I don't get crashes and it's stable again. 

It might be combination of the low detail size, constant, and symmetry in early models that causes the glitch when it tries to collapse few vertices far apart.

**Comment by ReinerBforartists** [comment]
So we can close this ...

Thanks for testing Draise :)

**Comment by Draise14** [comment]
Still having difficulty... I have noticed not applying scale may also have something to do with it. 0.9.6 was certainly more stable. I wish I could easily reproduce it. Each sculpt is so unique.

**Comment by ReinerBforartists** [comment]
But there is nothing that we could do here. We don't change tool code. We change UI. Tool code comes from Blender.
