### ISSUE TITLE
NLA Editor - Isolate in header should be inversed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2383]
# Issue
![image](https://user-images.githubusercontent.com/35357409/116742501-13bd0580-a9bd-11eb-93ff-da02bd4efad9.png)
1. The isolate checkmark prop needs to be inversetd, because it blends all when activated, when it should only blend all when de-activated. Checks to isolate to one track. 
2. The tweak highlight and icon change is really nice, BUT it only updates when mouseover happens on the header. It needs a better system of changing state, probably when the operator is hit. 

# Task
- Invert the check mark
- Make sure the tweak button updates when running the TAB operator

**Comment by ReinerBforartists** [comment]
Is it the same in Blender? If so we should consider to report it as a bug.

**Comment by ReinerBforartists** [comment]
*Bump*

**Comment by ReinerBforartists** [comment]
Hm, this is the solution that i have implemented to bypass the two menu entries. Seems that i have mixed the state. Will investigate.
![action](https://user-images.githubusercontent.com/13919702/116865445-f3ce5180-ac09-11eb-8476-2e03b565fcf8.jpg)

**Comment by ReinerBforartists** [comment]
Hm, code looks valid. It shows the isolate_action toolset when checked. That's the Start Editing Stashed Action in Blender.

Draise, could you please check if Start Editing Stashed Action in Blender works as odd as in Bforartists? If so then we need to report it to Blender.

![action](https://user-images.githubusercontent.com/13919702/116866360-90452380-ac0b-11eb-9231-c3bfae2bd7fe.jpg)

**Comment by Draise14** [comment]
Sure. I'll take a look later today. I was away from computer this weekend.

**Comment by ReinerBforartists** [comment]
Ah, when you use the hotkey, then the icon doesn't update. Unfunny :/

**Comment by ReinerBforartists** [comment]
Isolating the update problem. One tracker entry for one task please.

**Comment by ReinerBforartists** [comment]
Done: NLA - tweak prop in header does not update with hotkey #2390

**Comment by ReinerBforartists** [comment]
From what i can see, Blender behaves the exact same way than Bforartists. So this behaviour is nothing for us to fix. The opposite: we would break compatibility. Please report it to Blender instead.

Closing.
