### ISSUE TITLE
Animation Preferences - Change default to have Channel Group Colors on

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2384]
# Request
![image](https://user-images.githubusercontent.com/35357409/116744061-6d263400-a9bf-11eb-89f5-9f0b405693dd.png)

Turn on Channel Group Colors by default

# Reason
This allows the ability to see bone group channels and group the channels by colours, a much nicer UX when animating complex rigs. Even simple ones. 

**With:**
![bforartists_mKRR2f15Rw](https://user-images.githubusercontent.com/35357409/116744179-9646c480-a9bf-11eb-9815-2743831678e8.png)

**Without:**
![bforartists_jsUyv8LGje](https://user-images.githubusercontent.com/35357409/116744193-9a72e200-a9bf-11eb-90e2-c731dcb39232.png)

**Comment by ReinerBforartists** [comment]
Fixed in master
