### ISSUE TITLE
Graph Editor - Delete Keyframe confirmation dialoge is annoying

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2385]
# Request
![image](https://user-images.githubusercontent.com/35357409/116756566-f0508580-a9d1-11eb-917f-101754dec5d2.png)

Please remove. 

# Task
Remove confirmation dialogue like the delete dialogue in the 3D view.

**Comment by ReinerBforartists** [comment]
Ah, did we overlook one? Sure thing, will be removed :)

**Comment by ReinerBforartists** [comment]
Fixed in master
