### ISSUE TITLE
Add the Add to Collection functionality to the outliner

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2386]
Not sure how yet, but we should add the Add to Collection to the Outliner. We have the Move to Collection operator already there too.

![addto](https://user-images.githubusercontent.com/13919702/116787845-cf0d9900-aaa6-11eb-8678-ab11bacd46ae.jpg)

**Comment by Draise14** [comment]
Add to collection is the same as Link to collection no? 

They are just.... Differently named. Essentially when you add to any collection, the data block is linked. So the object could be in multiple collections.

**Comment by ReinerBforartists** [comment]
No. Completely different behaviour and python tool name. There was a reason why i haven't found a way to add the icons to the export collection from the Outliner :)

**Comment by ReinerBforartists** [comment]
Hmm, at the moment i doubt if it is really a good idea. We would confuse the users to have two link tools available. And most people would use the Add tool then instead of the Link tool then. Which still works fine. But the Link tool does not list the global collections.

So, abandoning this issue. I will do my best to explain the situation in the documentation instead.

Working at it ...

**Comment by ReinerBforartists** [comment]
Done. Closing.
