### ISSUE TITLE
Dopesheet Editor - View Menu - same hotkey for View Frame and View Selected

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#239]
We have a key inconsistency here in the view menu of the Dopesheet Editor. View Frame and View Selected have both the Numpad 0 hotkey assigned. Check all keymaps here ...

![viewframeviewselected](https://user-images.githubusercontent.com/13919702/42735795-99591d32-885a-11e8-9806-1bedaeb5a695.jpg)

**Comment by Draise14** [comment]
Just curious, if I were to fix this conflict in the Input map python file, where do I put the update in the Repository? Where are the input maps stored? I've dug around, but the compiled version and the repository are.. different.

**Comment by ReinerBforartists** [comment]
Yeah, surprise, the binary is different from the source code :D

The keymap python files are lcoated in release\scripts\presets\keyconfig

![keyconfig](https://user-images.githubusercontent.com/13919702/42768948-1feccd5a-8921-11e8-8584-04bb16fa520d.jpg)

**Comment by Draise14** [comment]
_haha, ok. Yeah, I was too impatient for the file search. I turned off indexing on that hard-drive._ 
Great, I'll get the hang of this. 

Thanks, cool. I can edit those file maps and play around with the experimental on keymap branches now, I suppose.

**Comment by ReinerBforartists** [comment]
Long fixed in 2.80 keymap. Closing.
