### ISSUE TITLE
NLA - tweak prop in header does not update with hotkey

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2390]
The tweak button in the header does not update its state when you use the hotkey. You need to move with the mouse over the header.

![tweakproblem](https://user-images.githubusercontent.com/13919702/117419928-60549380-af1d-11eb-84ee-c59423ef0024.jpg)

**Comment by ReinerBforartists** [comment]
I fear we are unlucky with that. This Blender task here is from 2012. But it seems nothing has changed in this regards. https://developer.blender.org/T33199

@iyadahmed , do you have an idea here?

**Comment by ReinerBforartists** [comment]
This is not to solve i fear. I have used a hack here already to set the state to active. And this state does not update when you are not over the header. The only thing i could do is to remove the button state again. Then this button remains grey, no matter in what state.

Suggestions?

![state](https://user-images.githubusercontent.com/13919702/117429269-2e482f00-af27-11eb-9f3c-ff9a65eac9de.jpg)

**Comment by iyadahmed** [comment]
> I fear we are unlucky with that. This Blender task here is from 2012. But it seems nothing has changed in this regards. https://developer.blender.org/T33199
> 
> 
> 
> @iyadahmed , do you have an idea here?

Looking into it now

**Comment by iyadahmed** [comment]
I think part of the answer may be here

https://docs.blender.org/api/current/bpy.msgbus.html

**Comment by ReinerBforartists** [comment]
Phew :/

**Comment by ReinerBforartists** [comment]
I'm too dumb here :/

**Comment by iyadahmed** [comment]
Not 100% how to tackle this too, msgbus might be useful, might be not

**Comment by ReinerBforartists** [comment]
No idea. Unassigning.

**Comment by ReinerBforartists** [comment]
Giving up. Sometimes there is no solution. The prop should update automatically.
