### ISSUE TITLE
Theme - Outliner - Make active and selected highlight more distinct

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2391]
# Request
![image](https://user-images.githubusercontent.com/35357409/117494729-57be8600-af3a-11eb-928d-3dd0e38ec3a2.png)
Right now, there is a light orange and a dark orange with little hue difference that shows what is selected and active in the outliner - and it's very hard to tell what is what. 

I would like to suggest having a Bforartists blue highlight for active, and a paler or stronger orange/yellow for selected but not active. This will make it very clear what is the active object and what is only selected.

**Comment by ReinerBforartists** [comment]
Sure, whatever improves the distinction. Did you have a look at the theming yet?

**Comment by Draise14** [comment]
I have. I changed it to this myself for a custom theme - but thought it would be good default for the other artists. 

It's in **Properties>Themes>Outliner** Active and Selected highlight colours.

**Comment by ReinerBforartists** [comment]
It is the xml file. And you need to run the blender_theme_as_c.py in \source\tools\utils to update the userdef_default_theme.c in release\datafiles\userdef

Could you please make a screenshot of the old and new values? Then i can do that.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/118016808-74cccd80-b31b-11eb-901f-9be36b203f3c.png)

Here it is, work week started in a flurry. Thanks for the patience.

**Comment by ReinerBforartists** [comment]
Many thanks :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![improved](https://user-images.githubusercontent.com/13919702/118091569-41e21280-b3cb-11eb-805a-5aea1edd0b7e.jpg)
