### ISSUE TITLE
Theme - Add Null, Camera, Light wireframe colours

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2392]
# Issue
We don't have coloured wireframes, but we do have themed colors for certain elements in the viewport. 

When we have many non-geometry elements, we get... a hard time to select things when there is many. 
![bforartists_V1BngYREhs](https://user-images.githubusercontent.com/35357409/117510103-14bbdd00-af51-11eb-9284-205390e8c341.png)

But if we had better color coding on the element wireframes of cameras, lights and nulls, it will make life a bit easier to work in the viewport. 

**Example:**
- Blue for cameras
- Red for nulls
- Yellow for lights

![bforartists_co0NLky93t](https://user-images.githubusercontent.com/35357409/117510443-b5120180-af51-11eb-9d0f-914afa67cfd3.png)

Here is a real world use case from my work:

Without colours:
![bforartists_GxX9VjXfvG](https://user-images.githubusercontent.com/35357409/117510461-b9d6b580-af51-11eb-920f-1c3108f36b39.png)
Without, things get.... too complex. I have to use visibility toggles to know what I'm selecting, or organize by collections, or in general just add a lot more work to select things. 

Here it is with a similar idea applied:
![image](https://user-images.githubusercontent.com/35357409/117510522-d5da5700-af51-11eb-9d44-5152baf3b4bc.png)
As you can see, you can immediately tell what is what, how much of what, and where is what. 

# Request
![image](https://user-images.githubusercontent.com/35357409/117510085-0bcb0b80-af51-11eb-9aa6-50ee49d22ff3.png)
Add some colour coding to the nulls, lights and cameras.

**Comment by ReinerBforartists** [comment]
Good catch! I made it a task.

**Comment by ReinerBforartists** [comment]
Fixed in master
