### ISSUE TITLE
Transparent background for the toolshelf tools

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2398]
Not sure if manageable independently. But at the moment it looks odd with the grey background. Maybe we can make just the tools panel background transparent, but keep the background of the other panels intact.

![tools](https://user-images.githubusercontent.com/13919702/117529836-4a58d880-afda-11eb-8ba0-8acef2e76a48.jpg)

**Comment by ReinerBforartists** [comment]
This taks is to solve first: https://github.com/Bforartists/Bforartists/issues/2400

**Comment by ReinerBforartists** [comment]
We really should make the background transparent again. This is a global setting. The toolbars in the other editors are now all with opaque background too.

**Comment by Draise14** [comment]
I think that when we have a header toggle to collapse, it makes sense to show what will be collapsed with the header (to what extent). Toggling a header with floating buttons is a bit disjointed. 

What we loose is editor realestate behind with opaque..we could do a 30% or 40% transparency to both show a collapsible panel and the toolshelf transparent. This allows to select behind. And see behind. And see panel realestate that can collapse. 

This changes the other panels though, so the property shelf also is transparent a bit. 

Might help destinguish the shelves belong to editor (visual transparency) separate from opaque properties editor panels.

Or else we would need to somehow work the themeing code system deep in C.... Which I had a look at with wireframes a bit. It's a rabbit hole.

**Comment by iyadahmed** [comment]
Should we dive into C?

**Comment by ReinerBforartists** [comment]
With we you mean you? :D

I have a working solution here at the moment. But as usual very unelegant. This makes it possible though to show the headers when needed, and hide them simply away when done with panel sorting by ticking a checkbox. I have currently connected it to the mesh checkbox

So this would be one working method to have the best of both worlds. Full panel control when needed, hide away the disturbing headers when not needed. Very ugly solution of course, with a panel for every state. But a possibility. 

What are your ideas here? Shall we go the C route instead? And add our own bl_option that just makes the background transparent? I'm unsure what to do here.

![panels](https://user-images.githubusercontent.com/13919702/117786170-8643a600-b245-11eb-888b-3888ed1f341e.jpg)

**Comment by ReinerBforartists** [comment]
Unassigning. Needs further thinking and research.

@iyadahmed, you can also have a look if delving into the C code brings a solution here.

**Comment by iyadahmed** [comment]
Maybe solution is in C
I wonder how transparent would work with header on

**Comment by ReinerBforartists** [comment]
We would need to implement our own method here. As told, i have already tried to follow the HIDE_HEADER tag. And it is implemented in quite a few places.

**Comment by ReinerBforartists** [comment]
Or we separate the theming of the toolshelf from the theming of the sidebar. That's currently one theming.

**Comment by Draise14** [comment]
I recommend not hiding the header of the toolshelf panel, as you'd want to pin it when changing tabs - as a consistent UX. Hope you guys find a way to make the panels float on transparent - split the theming.

If anything, I do think a 30% or 20% transparency is still ok and legible and won't touch up much code, and allows to see behind. This is why we want transparency no? To see and control behind floating buttons. 

![image](https://user-images.githubusercontent.com/35357409/117854838-7cbf3b80-b24f-11eb-80bd-b0655de3ea93.png)

**Comment by Draise14** [comment]
Oh... But just for the record, if it's easy to split theme, I am all for transparency.

**Comment by ReinerBforartists** [comment]
I don't think that it is easy. But it might be easier than to hunt down the panel approach and to implement our own bl_option. Well, the latter gives more fine control. Then you can have the one panel transparent and keep the other opaque.

I personally would be happy to have a working method at all. I followed already the bl_option path up to the point where i gave up.

**Comment by ReinerBforartists** [comment]
For now i have readded the bl_options = {'HIDE_HEADER'} to the new tool system panels.

**Comment by ReinerBforartists** [comment]
Toyed around a bit. This could be the places where the magic happens.

source\blender\makesrna\intern\rna_ui.c
source\blender\editors\interface\interface.c

![one](https://user-images.githubusercontent.com/13919702/118351950-0e37f180-b55f-11eb-83af-7e0b0960c57c.jpg)

![two](https://user-images.githubusercontent.com/13919702/118351953-11cb7880-b55f-11eb-9c20-d45b634bb636.jpg)

**Comment by iyadahmed** [comment]
> For now i have readded the bl_options = {'HIDE_HEADER'} to the new tool system panels.

about this, until the background is figured out, we could restore background for now, because right now, it cannot be reordered

**Comment by ReinerBforartists** [comment]
It can be reordered. You can grab all the panels around the new tool system and put them before or after the new tool system. So no need to make this part opaque again. And it is currently also a good way to distinguish between the old and new toolsystem panels.

**Comment by iyadahmed** [comment]
I see, it is still a bit annoying but ok

**Comment by iyadahmed** [comment]
progress
`NO_BG` option is done
I was thinking to change that name though, any ideas?

testing on snap panel
![image](https://user-images.githubusercontent.com/25552173/120533595-2f169880-c3e1-11eb-80d6-aa02350d0270.png)

also tiny detail, the grab icon should be not transparent when that option is enabled
fixing now

**Comment by ReinerBforartists** [comment]
Not only the grab icon. The whole header needs to be opaque too. We need to be able to pin it and drag it around with the drag handler :)

Is this possible?

For the name, what about HIDE_PANEL_BG ?

**Comment by iyadahmed** [comment]
> Not only the grab icon. The whole header needs to be opaque too. We need to be able to pin it and drag it around with the drag handler :)
> 
> Is this possible?
> 
> For the name, what about HIDE_PANEL_BG ?

Yep possible, now the drag is not issue then :)

good name, changing now

**Comment by ReinerBforartists** [comment]
I think my name idea would be more precise. Then you know that it's about the panel. But it's your code, you decide :)
