### ISSUE TITLE
Dropdown links + page links to the Documentation tracker

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#240]
![firefox_2018-07-16_11-35-12](https://user-images.githubusercontent.com/35357409/42771873-2a5d12c8-88ee-11e8-8063-a801da2eb072.png)

## Case
In the navigation bar on the website, there is a link to the tracker that doesn't really say it's to the tracker but instead "Report a Bug".  There is a subpage that goes to the tracker, great. But there is no link to the Documentation tracker. 

## Task
- Change Navigation link to  "Tracker" and the mouseover hint to "Report a Bug". 
- Add a link to the Documentation Tracker to the Navigation and Subpage

**Comment by ReinerBforartists** [comment]
Hm, i find the "Report a Bug" link makes more sense. 90% out there doesn't even know what a tracker is. So that would lead to confusion. 

I could have a look to improve the tooltip.

**Comment by Draise14** [comment]
Righteo. What do you think of also adding a link to the Documentation tracker in the dropdown?

**Comment by ReinerBforartists** [comment]
Hm. Documentation is more a internal thing. Let me sleep one night over it :)

**Comment by ReinerBforartists** [comment]
Goes quicker. We have already a link to the Manual repository in the Manual section of the page. So no need for a top hierarchy link ... https://www.bforartists.de/wiki/Manual#manual_odt

**Comment by ReinerBforartists** [comment]
Fixed

![bugtrackerlink](https://user-images.githubusercontent.com/13919702/42803528-7aaec088-89a6-11e8-87c7-e9b700baad3e.jpg)

**Comment by ReinerBforartists** [comment]
Also fixed.

Closing.

![supportlinks](https://user-images.githubusercontent.com/13919702/42803803-67788692-89a7-11e8-9a63-5b19fe1c1de1.jpg)
