### ISSUE TITLE
Make tab panel buttons bigger

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2400]
We should investigate if we should make the buttons in the tab panels bigger. Currently they have the usual 16 pixel graphics size, and the 21 pixel button size. We can set the size to the size of the tools icons by row.scale_X and row.scale_y. That's better to work with then. And we might then be able to display the same number of buttons than in the tool shelf. And we can make the background transparent again.
 
The only problem is the icon. It remains 16 pixels in size since this is hardcoded. And the label is in trouble without background too. So we would need to leave the labels away. Maybe make it a own panel then? Or is it too big then, and we scroll too much?  

Ideas? Opinions? 

![size](https://user-images.githubusercontent.com/13919702/117530357-0915f800-afdd-11eb-9753-6f9825e2cf27.jpg)

**Comment by ReinerBforartists** [comment]
First things first ...

**Comment by ReinerBforartists** [comment]
This looks better. On with number of icons per row. The important bit was the scale value here.

![fixed](https://user-images.githubusercontent.com/13919702/117535151-c6601a00-aff4-11eb-9dc0-d75fad151ec4.jpg)

**Comment by iyadahmed** [comment]
Yep that was a good change
