### ISSUE TITLE
Make tabs in toolshelf optional

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2401]
With the tabs we introduce a set of double menu entries. This crowds the UI, even when we have a good reason here. Maybe we can manage to make the tabs optional.

I still think if it makes sense to just hide the tabs then, or if we should hide the menu entries when tabs are active. This would be a bit more complicated then though.

Mockup:

![mockup](https://user-images.githubusercontent.com/13919702/117530978-711a0d80-afe0-11eb-8206-e09a8c0c53b7.jpg)

**Comment by Draise14** [comment]
It's exciting to see the new tasks!!

Concerning this task... Optional is good, but maybe a second option to minimize headers? But thinking again I think it should be one then the other: a toggle. Or else it will feel very bloated when on. I loved how light the headers were in Bforartist 1. If I had the option, I wouldn't use headers for tools if at all. 

I feel like all these menus could have conditional visibility code set by a prop - yet it might make merging tricky if there are new features from Blender. How the menus update.. I know append and prepend, and visibility based on modes. But it must be possible with a prop. 

 But I'm all for for less redundecy and customization. 

I think it could be done like the task #2402, panel per panel after a prototype.

**Comment by ReinerBforartists** [comment]
We will see :)

**Comment by ReinerBforartists** [comment]
Fixed in master

A little hiccup remains. The toolshelf width is not updated automatically. So after turning it off or on you need to resize the tool shelf manually so that the buttons fits again.

I have added the toggle to the overlay code since i haven't found a better location for it. Works ...

![fixed](https://user-images.githubusercontent.com/13919702/118106959-7c08df80-b3de-11eb-8513-457435539dd8.jpg)
