### ISSUE TITLE
Tutorials/Social Media files on Github with seperate or unified tracker

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#241]
## Case
Currently to work collaboratively on tutorials and social network publicity, you need to go to the youtube channel and download, then upload to facebook again. I can't create and upload to youtube, there is no filesharing workflow. If you want the logo to share content about Bforartists or just add it to your artwork, you have to dig through forum posts/threads and deep documentation to find the unlinked "Press Kit" or *.SVG files. If I want to upload something official to youtube with an official task, it's impossible. If I want a collaborative post or opensource content to share to facebook (and/or instagram and twitter) then I will have to run a third party system. 

There is no way to track what tutorials or social media content needs to be done. Some documentation files are attached to the tracker thread (easily lost) and it's.. just everywhere. 

I like and pride in the idea that Bforaritsts also is documentation and tutorial based and centralized. I just think the organization of that information could or should be unified and task orientated for faster, more efficient and clear collaboration. 

## Task
- Create a Github tracker for the Tutorials and "Press Kit" material with tracker
**OR**
- Expand the file structure and files in the "Documentation" Tracker and work from there.

## Example
File structure:
- Icons/Logos 
- Videos *(official and archive to upload to)*
- Social Network images *(with subfolders, as I have them locally - storing assets as an archive to share around or have them available to other social network managers)*
- Stock Image Bank *(for images that can be reused for other assets)*
- Presskit Assets *(and/or a link to the presskit in the website)*

**Comment by ReinerBforartists** [comment]
We have a WIKI section here at the Github account. This could be the place for such files.

But i am not happy to have two places to care for such things. We have our wiki section at the page.

**Comment by Draise14** [comment]
My proposal is more for files and material for tutorials and publicity and collaboration - not the wiki documentation persay. Regardless, double areas wouldn't do, you're right. The wiki/tutorials pages on the website is unfortunately impossible to edit collaboratively at the current state unless going to (I assume) the documentation tracker and repository (or the one for the software repository) and waiting for someone who has access the server to update things from files in a tracker thread with no versioning. 

We do already have the "Documentation" github repository and tracker. Maybe we could do the publicity/tutorial repository there and put tasks to update links in the Website wiki (as far as I know, they are static CMS filled pages with links to the PDF's stored and created from the repository, stored on a private server, right)? 

We just need a clear task distribution system and file structure to make **documentation_(done)_/tutorial/publicity** workflows a little more collaborative and organized - centralized. Maybe just a workflow clarified. 

_Just mentioning this because a lot of the tutorials, documentation, publicity material, etc is on the server for the website somewhere in forums, tracker posts, different pages, but it's inaccessible nor organized for those who want to work with BFA. A good example is the Compiling tutorial. Where is this file and where does it get stored and where do I create/make tasks for it? It doesn't exist in the Documentation repository, It's tasks could be in the documentation tracker. It could be branched and developed there instead of uploading a zip file and hoping it doesn't get lost in the Github thread by being updated to the server by someone else, with no version tracking. Putting some of those files and a file structure, tasks and workflow to the documentation repository could solve this._ 

Maybe just elaborating the repository for the Documentation Manual could solve this request. 

I already have the documentation manual synced locally, I could push a branch with a proposal for the other publicity/tutorial areas into the same Bforartits Manual repository. So when you need a specific tutorial, someone can record and another can voice over, or someone can edit video footage, or I can download then upload from there instead of ripping from Youtube - or I upload files for your end of the publicity or can also find another fan that could work with us in graphics design in a centralized task system for/with the documentation with task towards the site dev.

**Comment by ReinerBforartists** [comment]
Yes, you need server access to upload new tutorials and the manual. That's my job.

In my opinion we don't have enough tutorials in general to justify a own section and its own pipeline. Manual is in permanent change, tutorials not. We have a handful. And they were all written by me over the last three years. Tutorials is also usually nothing where you collaborate. That you rewrite parts of my tutorial is a special case at the moment. That's why i struggle here a bit.

Github tracker entries cannot be lost as long as they are not closed. And you usually close them when you are done or when you decide not to fix this issue. So that's imho the best thing to do.

**Comment by Draise14** [comment]
Ah.. Just thinking to try get more people involved in the tutorial/documentation. Blender is TOO fragmented. if there were a central repository for everything then it might not get so fragmented. 

Example: I could upload new text documentation for different files, or transcribe videos to text documentation and upload them to the repository. Someone else could make an artistic series in Spanish or English and upload them too. 

I am just trying to think about... keeping things centered - so I don't fragment Bforartists educational material for future fans - giving people the option to keep their tutorials in a central area and index. 

Keeping track of educational things through tracker tasks in the software tracker, instead of having a central library for it in the documentation tracker and repository - just seems messy to me... Just thinking ahead. I know right now it's not necessary, but I just want things to grow fluidly.

**Comment by ReinerBforartists** [comment]
I see your point. But reality is that we lack of manpower to even get the manual in good shape. So little resources, and so much to do. And that's why i struggle with everything that makes me work if you know what i mean :)

**Comment by ReinerBforartists** [comment]
The discussion is not forgotten. But i'll close it for now. We can reopen it at a later point when there is a need to.
