### ISSUE TITLE
Nodes sidebar - make icons bigger

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2410]
The small icons here could be a bit bigger in size. Not sure if we should make it as big as in the tool shelf. But a bit bigger wouldn't hurt.

![sidebar](https://user-images.githubusercontent.com/13919702/117634012-d0158900-b17e-11eb-94fb-56e878479f5f.jpg)

**Comment by ReinerBforartists** [comment]
When we have working tooltips that shows the toolnames here too, then we could try to use a layout.grid_flow. And for the size, i don't want to go as big as in the tool shelf. But 1.4 or 1.5  and aligned will most probably be an improvement here.

**Comment by ReinerBforartists** [comment]
Should go quick ...

**Comment by ReinerBforartists** [comment]
Looks definitely nicer. And here we can live with the non square buttons. Curious enough, i can have three rows here. I should go back experimenting with this in the toolshelf too i guess ^^

![improvement](https://user-images.githubusercontent.com/13919702/118235798-8508b800-b495-11eb-8bc4-b4a5d5a04ab8.jpg)

![flowlayout](https://user-images.githubusercontent.com/13919702/118235809-876b1200-b495-11eb-876e-289713398855.jpg)

**Comment by ReinerBforartists** [comment]
Ah, here comes the caveat ...

![caveat](https://user-images.githubusercontent.com/13919702/118236479-6b1ba500-b496-11eb-85c8-9b3399c0005d.jpg)

**Comment by ReinerBforartists** [comment]
The alternative is worse ...

flow.alignment = 'LEFT'
![alignment](https://user-images.githubusercontent.com/13919702/118237465-a23e8600-b497-11eb-874c-2cf210cae7f2.jpg)

**Comment by iyadahmed** [comment]
> Looks definitely nicer. And here we can live with the non square buttons. Curious enough, i can have three rows here. I should go back experimenting with this in the toolshelf too i guess ^^
> 
> 
> 
> ![improvement](https://user-images.githubusercontent.com/13919702/118235798-8508b800-b495-11eb-8bc4-b4a5d5a04ab8.jpg)
> 
> 
> 
> ![flowlayout](https://user-images.githubusercontent.com/13919702/118235809-876b1200-b495-11eb-876e-289713398855.jpg)
> 
> 
> 
> 

This one looks great I think

**Comment by ReinerBforartists** [comment]
Yes, much cleaner. We need to scroll a bit more now. But the look is cleaner, and the elements are easier to distinguish that way. Even with all the panels open. It is not so much at once at the screen anymore. And the icons are much easier to read without the frame directly at its borders.

![improved](https://user-images.githubusercontent.com/13919702/118241785-d8cacf80-b49c-11eb-83b0-91506fe08962.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
