### ISSUE TITLE
Secondary Tabs in the Properties Editor - intentional feature?

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2415]
# Feature?
![image](https://user-images.githubusercontent.com/35357409/117860782-505aed80-b256-11eb-912d-dd58365d09f7.png)

The latest dev build has some addons register tabs and panels in the Properties editor, as a secondary tab list for panels (so click on a tab, then you get another tab for panels in that tab). 

Addon in question: Eevee Presets. 
[https://blender-addons.org/eevee-presets-addon/](https://blender-addons.org/eevee-presets-addon/)

Was this intentional to allow this? 

Right clicking on it creates a bug due to missing context menu. 
![image](https://user-images.githubusercontent.com/35357409/117861340-f1e23f00-b256-11eb-889b-3a6141880840.png)

You can even pin panels! 
![image](https://user-images.githubusercontent.com/35357409/117862625-7bded780-b258-11eb-8421-1648e2c6daed.png)

# Request
- Should we take advantage of this? (Create tabbed panels with settings that could be in their own group for streamlining the UX?)
- Should this be hidden? 

# Task
Check out the addon to see what it's doing (typical behaviour is that the addon adds the panel to the same tab/category)

**Comment by iyadahmed** [comment]
hmmm how did this happen?
can you please try pulling latest change after, there was another change after #2409 
![image](https://user-images.githubusercontent.com/25552173/117865645-77391400-b296-11eb-91b5-e2ec9aae15e1.png)

**Comment by ReinerBforartists** [comment]
I don't even understand the problem. You have an addon that produces a bug?

**Comment by iyadahmed** [comment]
I think this issue was before #2409

**Comment by Draise14** [comment]
Yeah, I am doing another test build, but yeah, the addon was making a feature and bugs by the way it was registering a panel.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/117890120-30d5bc00-b27a-11eb-829f-0ffdbec5c2ef.png)

Ok, latest build and merge of the last patch #2409 has this fixed, issue is irrelevant.

**Comment by ReinerBforartists** [comment]
Ah, there it is. Didn't see them. Yes, this was the missing category issue. Good that you have fixed it @iyadahmed :)

**Comment by iyadahmed** [comment]
> Ah, there it is. Didn't see them. Yes, this was the missing category issue. Good that you have fixed it @iyadahmed :)

Yep indeed :)
