### ISSUE TITLE
Outliner - Changed hide one level operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2416]
# Issue
![image](https://user-images.githubusercontent.com/35357409/118039242-bbc7bc80-b335-11eb-8fb8-a5e695e7cf74.png)
There is a broken operator, no-longer exists as it is implemented slightly differently. Notice that there is a missing operator at the end of the sub-menu list. 

Blender (works fine):
![image](https://user-images.githubusercontent.com/35357409/118039192-af436400-b335-11eb-938c-cd31756e6a67.png)

# Task
- Update the operator in `space_outliner.py` like below:
![image](https://user-images.githubusercontent.com/35357409/118039633-28db5200-b336-11eb-8441-6c91eb3875b1.png)

**Comment by ReinerBforartists** [comment]
Good catch :)

**Comment by ReinerBforartists** [comment]
Fixed in master
