### ISSUE TITLE
Outliner - Change "Purge" to recursive + "cleanup" name and entry to the Orphan View of the outliner

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2417]
# Request
![image](https://user-images.githubusercontent.com/35357409/118041185-1b26cc00-b338-11eb-8dd0-97bbeb7c0aff.png)

Sometimes when you purge from the outliner, you have to purge multiple times as there is no recursive method of doing it other than in the file menu, which might not be so easily discovered. You purge a rig, it pruges the armature, not the object, then purge again, then the mesh data, purge again, then the materials and textures.. it's not great. 

I suggest also adding this menu or a second recursive purge to the outliner Orphan View

Here is an example suggestion:
![image](https://user-images.githubusercontent.com/35357409/118041379-5628ff80-b338-11eb-8517-e2d574e22e23.png)

## Alternative
Make the purge button a recursive purge, so it definately purges everything that's an orphan unless it's in use, instead of only one step of purging.

**Comment by ReinerBforartists** [comment]
Question is, does this really belong to each other?

**Comment by Draise14** [comment]
Yes. They are essentially the same. Just named differently. 

I will confirm the operator though later today

**Comment by Draise14** [comment]
Ok.. verified.

**Outliner:**
![bforartists_XmiCUmVOJg](https://user-images.githubusercontent.com/35357409/118207030-653baa80-b429-11eb-962d-3ad79c32e75e.png)

**File Menu**
![bforartists_4w1W3a6FNs](https://user-images.githubusercontent.com/35357409/118207033-666cd780-b429-11eb-9db9-d61499542308.png)

They are the same operator, just with some variables. It's a double entry, with different name.

**Comment by ReinerBforartists** [comment]
It's not the question if it's the same operator. It is. It's the question if the cleanup menu belongs to the orphan mode in the outliner. The question of usability is: the entries in the file menu are easy to discover. While the user may never ever discover the functionality of the orphan mode in the outliner. We would need to keep this menu at one place, to prevent double menu entries. And when we move it to the outliner then we might remove the easy way to clean up the file.

**Comment by Draise14** [comment]
True. File menu makes sense. Let me change the request. 

1. Change "purge" name of the cleanup button in outliner to "clean up" to be consistent with the operator. 
2. Make the single button in outliner a recursive orphan data clean up. 

The button is unclear what it does from the name and feels broken when it purges only some orphan data, not all. It also is a big haul to go to the file menu to recursively clean up when the outliner could be on another screen or is at the full right of screen.

**Comment by ReinerBforartists** [comment]
Rename sounds good. Not sure though if we should change the method. Hmm. Let me sleep a few nights over this.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

We cannot change the method since we need to stay compatible with Blender. Not good when the same tool behaves different.

![cleanup](https://user-images.githubusercontent.com/13919702/118350213-bcd73480-b555-11eb-9b63-5ecbb1da7c70.png)

**Comment by ReinerBforartists** [comment]
Ah, what the heck, let's make a double menu entry here. It is crazy workflow that you need to go to the file menu to have fine control over the clean up methods.

**Comment by ReinerBforartists** [comment]
Done

Now the question raises if we should keep the clean up menu in the file menu or not: The reason why i had a hard time to remove it is the same. The file menu content is easy to discover, while the Orphan panel is something that users may never ever open.

So let's keep it as one of the exceptions of the rule.

![cleanup](https://user-images.githubusercontent.com/13919702/118350787-ec3b7080-b558-11eb-8c19-5702d11224e1.jpg)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/118704749-1309d900-b7dd-11eb-8582-4f43d37de5c0.png)

Thank you very much for this. Feels more.... in the relevant editor and UX now. Specially on another monitor.
