### ISSUE TITLE
Geometry node editor - sidebar - empty tab Input

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2418]
We have a tab called Input in the geometry nodes editor. The panel in it is empty. It is for adding node groups once there are some. This is add functionality. And should be in the Add tab. And it should be better labeled. You don't know what it is good for until you create a node group.

![inputtab](https://user-images.githubusercontent.com/13919702/118155669-c1e29980-b418-11eb-8527-262279166f9b.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/118156601-d5423480-b419-11eb-8c69-0f7137ca0714.jpg)

**Comment by Draise14** [comment]
This panel is now adding another tab "Add" to the other node editors with the Node Group panel. Though everything concerning adding is under "Input". Was this intentional?

**Comment by ReinerBforartists** [comment]
Yes. This is wanted behaviour in the Compositor and the Shader editor. I still think if we should reunion the Input and Modify tab under the Add label.
