### ISSUE TITLE
conflict with Light Architect Addon

### ISSUE THREAD

**Issue by QuickR** [Bforartists/Bforartists#242]
conflict in Camera definition when trying to enable Light Architect Addon.  Addon fails to enable.

**Comment by ReinerBforartists** [comment]
Thanks for the report.

That's unfortunately a commercial addon. So we cannot even check for the error.

As sorry as i am, we have to close this issue. We cannot fix anything here. The only thing that you could try is if the addon works in Bforartists 0.9.5.
