### ISSUE TITLE
3D View - Missing remesh, options and dynatopo dropdown in header in Sculpt Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2426]
# Issue
![image](https://user-images.githubusercontent.com/35357409/118541069-e8ede380-b716-11eb-8091-023372184565.png)
This is blender sculpt mode dropdown for dynatopo and remesh. These are not present in Bforartists. 

These are useful when using full screen mode and when you don't want to use the properties shelf. 

# Task
Add them back

**Comment by ReinerBforartists** [comment]
Looks like a regression. We had this problem before ... https://github.com/Bforartists/Bforartists/issues/1486

**Comment by Draise14** [comment]
I have dug the code a bit, trying to make it work (because I need them) but I can't seem to find the relevant code. I compared with Blender and both have identical in areas where relevant, I wonder how you will fix this? 

_I need to read the commits more often._

**Comment by ReinerBforartists** [comment]
I will simply assign and fix it. Hopefully  :D

**Comment by ReinerBforartists** [comment]
Hmmm. I am in sculpt mode and the panels are where they should be. Under what circumstances are they missing? I need a way to reproduce.

![allthere](https://user-images.githubusercontent.com/13919702/118619621-0f6a5800-b7c5-11eb-9f32-60bad19cc103.jpg)

**Comment by Draise14** [comment]
Hm. I'll factory reset. I've done a normal reset so far.

**Comment by Draise14** [comment]
Ok, factory reset fixed the issue (removed config folders). Reset to factory did not. I have to rebuild my work spaces....

**Comment by Draise14** [comment]
It was the user preferences that had it broken, might have been an addon, a setting, or anything stored in the userpref.blend file. It wasn't the actual startup.blend.

**Comment by ReinerBforartists** [comment]
Phew.  Glad we got it sorted :)
