### ISSUE TITLE
Pose sliding tools improvements - bone system starts invisible

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2428]
With the following commit the Blender developers made the bones invisible when you use the In-Between tools. I reported it as a bug. But the report gots declined. That the bones starts hidden is now intended behaviour. They want you to judge the mesh, not the bones anymore when using the In-Betweens. 

Well, you can make it visible with hotkey H. But that's clumsy. And the pose is defined by the bones, not the mesh. So we better start with the bones visible. They can be hidden with H then if desired.

We need to have a look if we can start with the bones visible.  It should be a tiny change at the state of the flag, means when we find it. 

Pose sliding tools improvements, SHA-1: 9797b95f617561dc87b702e1bce829a551260689

Improve the "In Betweens" tools:

Push Pose from Rest Pose
Relax Pose to Rest Pose
Push Pose from Breakdown
Relax Pose to Breakdown
Pose Breakdowner

Bug report: https://developer.blender.org/T88340

**Comment by ReinerBforartists** [comment]
Wait a few days. Maybe they change their mind. But i have no high hopes here. The task has the closed resolved label already.

**Comment by ReinerBforartists** [comment]
I hope i have catched the right part. But the bones doesn't go invisible, and functionality is given. And you can hide the bones away with H while in the in-betweens. Like it was before this commit.

Fixed in master

**Comment by iyadahmed** [comment]
> I hope i have catched the right part. But the bones doesn't go invisible, and functionality is given. And you can hide the bones away with H while in the in-betweens. Like it was before this commit.
> 
> 
> 
> Fixed in master

Yep looks right
