### ISSUE TITLE
Node Shelf - Shader Editor - Icon Only doesn't show Principled Volume

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2429]
# Issue
![image](https://user-images.githubusercontent.com/35357409/118695204-8b1ed180-b7d2-11eb-9924-2b527de6fc10.png)
This has two principled.

![image](https://user-images.githubusercontent.com/35357409/118695197-89550e00-b7d2-11eb-8454-9a0f5b7bef38.png)
Icon only shows only one. 

Version: devbuild-15-05-2021

**Comment by ReinerBforartists** [comment]
Oops. Will investigate :)

**Comment by ReinerBforartists** [comment]
Fixed in master
