### ISSUE TITLE
New Labels and Folder for Publicity Archive + Publicity Tasks and Tutorial Archive + Tutorial Tasks

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#243]
### Case
We've had a couple of discussion [here](https://github.com/Bforartists/Manual/issues/17) about making a new repository or area for publicity files, tutorial files and other files to organize data around education and publicity. 

The reason to do this is to have a container for third-party collaborators to build, create, update and work on task and files used in the website wiki and for publicity in different social networks. This is needed so files don't go missing, masters are kept, trackers are concise and clear, and the database can be worked on local filestructures and pushed to branches if needs be. 

### Issue
Another repository is another fragmented workflow - which is feared to make more work. 

Currently the issue is that most files are hosted by one person in a closed source, managed and upload by one person who principally is working in programing the software, and thus this one person has limited time and inevetibally will get swamped with many tasks. That's you Reiner, ;P 

Currently to propose or work on new tutorials requires attaching them to a task thread within messages - with no versioning other than in the filename or message date. 

How does a tutorial proposal become a downloadable and indexed PDF in the website? How can a new user make a good tutorial series? A Developer tutorial? An open artistic project with Bforartists? How can this workflow area be delegated to someone else? 

How do we avoid the educational/opensource fragmentation plague that Blender is famous for? 

### Possible Solution?

I'm not thinking of a Blender Cloud system behind a paywall, just a tool that can help work with Bforartists educational material and opensource those files and clarify those updates to the website articles/links/database. 

When quantity increases, more people get involved, more need for more official material will come, more will want to make content relative to BFA. Myself included. 

I'm just thinking of a **file structure** and **tracker labels** fit for developing tutorials, publicity and other misc file systems would be great - or a new repository with this to keep the pushing and pulling and committing less heavy and clean. 

How this updates to the website or social networks would now be onto the tasks assigned in that repository.. but at least information won't go lost, be overwritten or at risk of never being updated/loaded to the website and ultimately, the workload shared and less over time. 

### Tasks
**Plan A**
Create a repository for publicity and tutorial files and tasks
		*Workflow 
				- Will imply tasks to update articles and website database for those with access
				- Will allow branching to make new tasks and keep file versioning clear and clean
				- Will keep the project files lean to fetch and pull.
				- Will make tutorial and publicity tasks delegatable and updateable* 

**Plan B**
Create a file structure and tracker labels in the Main Repository or Documentation Repository for Bforartists
		*Workflow 
				- Will imply tasks to update articles and website database for those with access
				- Will keep everything in one place
				- Will make tutorial and publicity tasks delegatable and updateable*

**Comment by ReinerBforartists** [comment]
I thought we have already a solution: we make the new repository :)

**Comment by ReinerBforartists** [comment]
Repository is up and running. https://github.com/Bforartists/files

Closing here ...

**Comment by Draise14** [comment]
Nice! I'm excited. Thanks.

**Comment by ReinerBforartists** [comment]
Your wish is my command :D
