### ISSUE TITLE
Node Shelf - Shader Editor - Different icons for Vector and normal Displacement and Principled

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2430]
# Request
![image](https://user-images.githubusercontent.com/35357409/118695546-f072c280-b7d2-11eb-8a3e-e76ac50c35f9.png)

Right now in icon only mode, the two displacement nodes for Displacement and Vector Displacement are the same. The only way to tell them apart is from the python tooltip, it's hard to read. 

Would be good to change these two icons, just a bit. 

Ver: devbuild-15-05-2021

**Comment by ReinerBforartists** [comment]
Difficult. It is both displacement.

**Comment by ReinerBforartists** [comment]
Principled reuses the icon too. I will have a look to create two new icons here.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/118785271-ffb84580-b890-11eb-942d-dfdef1cd3225.jpg)
