### ISSUE TITLE
Texture Nodes - Nodeshelf Icon panels needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2433]
# Request
![image](https://user-images.githubusercontent.com/35357409/118737180-ed46f900-b809-11eb-91a6-fb9f1cd1bd6a.png)
The texture nodes, though not a useful editor right now, has an inconsistent node shelf icon layout. It can be somewhat useful for brushes mostly. 

This may need updating like the other node shelves.

**Comment by ReinerBforartists** [comment]
Texture nodes editor is deprecated, and may  be replaced by something completely different in the future. I don't know the plans from Blender though.

Either way, this editor does currently exactly nothing. So we won't do any work at it. That's wasted time.
