### ISSUE TITLE
Principled Shader - SSS Radius doesn't apply to all when changing values

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2436]
# Issue
![image](https://user-images.githubusercontent.com/35357409/118887196-a1ef2200-b8bf-11eb-866d-0c5f5426208d.png)
When click dragging the three slider, you can change their values, but when you press enter, it only changes one of them. 

Ideally like all other group sliders, if you click and drag on all three or two, and then enter a value, all of them would apply that value.

**Comment by Draise14** [comment]
Weird, only failed that few times. Now I can't reproduce.

**Comment by ReinerBforartists** [comment]
Wasn't there an update problem with the nodes sometimes?

**Comment by iyadahmed** [comment]
> Wasn't there an update problem with the nodes sometimes?

I think that was unrelated, it was only observed with an addon

**Comment by ReinerBforartists** [comment]
Okay :)
