### ISSUE TITLE
Mirrortools - separate tooltips

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2437]
We have seven mirrortools, and seven equal tooltips.  In the sidebar we have also seven equal tool names ...

Taks: Separate the mirror tooltips.

![mirrortooltips](https://user-images.githubusercontent.com/13919702/118943389-dad8d680-b953-11eb-9c46-462d67431b96.jpg)

![mirrortooltipstabs](https://user-images.githubusercontent.com/13919702/118943409-e0ceb780-b953-11eb-8934-98aa1442e210.jpg)

**Comment by ReinerBforartists** [comment]
Phew, this is something complicated ...

**Comment by ReinerBforartists** [comment]
No way. orient_type GLOBAL  and LOCAL are not recognized at all. And throws an error. No idea where this is defined. To include the only H file with orient_type did not help.

I wanted to have at least the axis separated. But also no luck. The  constraint_axis flags state is not recognized. The tooltip always shows the first entry.

Postponing. Maybe we will find a way at a later point. 

![noway](https://user-images.githubusercontent.com/13919702/119104653-ca406300-ba1c-11eb-9b9c-03113360eba6.jpg)

**Comment by ReinerBforartists** [comment]
```
/*bfa - descriptions*/
static char *transform_ot_mirror_get_description(bContext *UNUSED(C),
                                                               wmOperatorType *UNUSED(ot),
                                                               PointerRNA *ptr)
{
  if (RNA_boolean_get(ptr, "constraint_axis") == (true, false, false)) {
      return BLI_strdup(
          "Mirror selected items around the X axis in global space");
  }
  else if (RNA_boolean_get(ptr, "constraint_axis") == (false, true, false)) {
    return BLI_strdup("Mirror selected items around the Y axis in global space");
  }
  else if (RNA_boolean_get(ptr, "constraint_axis") == (false, false, true)) {
    return BLI_strdup("Mirror selected items around the Z axis in global space");
  }
  return NULL;
}

static void TRANSFORM_OT_mirror(struct wmOperatorType *ot)
{
  /* identifiers */
  ot->name = "Mirror";
  ot->description = "Mirror selected items around one or more axes";
  ot->idname = OP_MIRROR;
  ot->flag = OPTYPE_REGISTER | OPTYPE_UNDO | OPTYPE_BLOCKING;

  /* api callbacks */
  ot->invoke = transform_invoke;
  ot->exec = transform_exec;
  ot->get_description = transform_ot_mirror_get_description; /*bfa - descriptions*/
  ot->modal = transform_modal;
  ot->cancel = transform_cancel;
  ot->poll = ED_operator_screenactive;
  ot->poll_property = transform_poll_property;

  Transform_Properties(ot, P_ORIENT_MATRIX | P_CONSTRAINT | P_GPENCIL_EDIT | P_CENTER);
}
```

**Comment by ReinerBforartists** [comment]
Committed to the wrong issue. And committed the broken try too.  -.-

**Comment by ReinerBforartists** [comment]
Also here: 

I guess the easiest method is to use the Python approach that we have used for quite a long time. Make a new operator with a new tooltip.

Related: Separated tooltips - Implement the different tooltips in the original operator #2052

**Comment by iyadahmed** [comment]
But we have moved away from that, we could try first using C.

**Comment by ReinerBforartists** [comment]
I tried already ^^

**Comment by iyadahmed** [comment]
> I tried already. But feel free to try too ^^

Ok ^^

**Comment by ReinerBforartists** [comment]
At least divided into global and local. But i cannot find a way to retreive the vector3. -.-

![globallocal](https://user-images.githubusercontent.com/13919702/120013126-a9f64280-bfe0-11eb-8e2c-7647add4b94c.jpg)

**Comment by ReinerBforartists** [comment]
Remains this beast here ...

**Comment by ReinerBforartists** [comment]
Fixed in master
