### ISSUE TITLE
Pie Menu - Consistent Snap Icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2443]
# Request:
![image](https://user-images.githubusercontent.com/35357409/119202838-48216000-ba57-11eb-9063-1d34453c3b16.png)
Right now the snap panel has icons I can read, but the pie menu does not. It's inconsistent. 

Can we make the pie menu have the same iconography as the snap panel?

**Comment by ReinerBforartists** [comment]
Blender Icons <3

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/119474515-861ace80-bd4c-11eb-9a9d-3f61150393c9.jpg)
