### ISSUE TITLE
3D View - Add Lock View Rotation toggle to optional header toggles

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2444]
# Request
![bforartists_Q1BDHWsw6f](https://user-images.githubusercontent.com/35357409/119207419-c2f07800-ba63-11eb-99d7-764cb8354d4b.png)

Can we add Lock View Rotation to the header optional toggles? This is really handy specially when using grease pencil.

**Comment by ReinerBforartists** [comment]
Sure :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![lockviewrotation](https://user-images.githubusercontent.com/13919702/119219366-89605100-bae5-11eb-9900-8274312d9e68.jpg)
