### ISSUE TITLE
Per Node Description

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2448]
after #2044  is closed, we should fill rest of descriptions in
`source/blender/nodes/NOD_static_types.h`
![image](https://user-images.githubusercontent.com/25552173/119227930-acecc100-bb10-11eb-916f-ffaf4d0e146c.png)
![image](https://user-images.githubusercontent.com/25552173/119227884-7b73f580-bb10-11eb-8366-f2b074328db3.png)

**Comment by ReinerBforartists** [comment]
A task where even i cannot fail i hope ^^

**Comment by ReinerBforartists** [comment]
Even when we might not manage to change the title, the description has now a hint what node you add with this button.

Part two: add a description of what the node does. This part is a bit more cumbersome ...

![tooltip](https://user-images.githubusercontent.com/13919702/121926001-c531b380-cd3d-11eb-96ae-ae76c7ae61c2.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/122186381-47c98880-ce8e-11eb-8ae3-b156851bd39f.jpg)
