### ISSUE TITLE
Run .\make format

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2449]
this should keep the code style clean, we should run this after every change just to make sure

**Comment by ReinerBforartists** [comment]
Code formatting should indeed be done from time to time, to keep our changes clean too. But this is mostly done by the Blender devs already. And remember, i am not at Linux ^^

What i fear here is that the clean up may produce some unexpected differences to the Blender code. So not sure if we should do this at all. We have not this much changes at the C code.

**Comment by iyadahmed** [comment]
> Code formatting should indeed be done from time to time, to keep our changes clean too. But this is mostly done by the Blender devs already. And i am not at Linux. So .\make format will not work here i fear ^^
> 
> 
> 
> What i fear here is that the clean up may produce some unexpected differences to the Blender code. So not sure if we should do this at all. We have not this much changes at the C code. 

It should work on windows too, I fear this too, but it shouldn't make difference with Blender, Blender does it.

**Comment by ReinerBforartists** [comment]
Just tested. make format also works at Windows, yay.

It corrects quite a few of our changes. But it also corrects quite a few Blender formattings that we have never touched. And these changes will then now show up as differences to the Blender code. And are potential sources of merge conflicts. So i am still not sure if i really want to do this. Hm.

![bfachanges1](https://user-images.githubusercontent.com/13919702/119310938-bc831b80-bc70-11eb-84bd-4767511523f8.jpg)

![formatting2](https://user-images.githubusercontent.com/13919702/119310948-c0af3900-bc70-11eb-81d4-65ca15377ada.jpg)

**Comment by iyadahmed** [comment]
Awesome!!
Maybe we can try and see if it causes differences?, maybe resolve them if any

**Comment by ReinerBforartists** [comment]
As told, it does cause differences. The question is if they are significantly in the way then :)

I will now do a test compile first, and check if these changes have broken something.

**Comment by iyadahmed** [comment]
> As told, it does cause differences. The question is if they are significantly in the way then :)
> 
> 
> 
> I will now do a test compile first, and check if these changes have broken something.

Great!, I hope it goes well

**Comment by ReinerBforartists** [comment]
Works. No problems. And i did run make format at Blender now too. Just one tiny change. Means your idea was great :)

Committing ...

**Comment by ReinerBforartists** [comment]
Fixed in master :)

**Comment by iyadahmed** [comment]
> Fixed in master :)

Awesome!!
Yep Blender devs run make format after every change, but while they are working some changes may not be yet formatted :)

**Comment by ReinerBforartists** [comment]
I find the formatted parts now harder to read. But one style for everything is better i guess.

**Comment by iyadahmed** [comment]
> I find the formatted parts now harder to read. But one style for everything is better i guess.

I guess so yes, there's something we can do though

Functions like this
fun(
  arg1, arg2, arg3)

We could write it like this I think and it will still obey the style (no long lines)


fun(arg1,
    arg2,
    arg3)

But it would be manual

**Comment by ReinerBforartists** [comment]
Yes, and that's this one out then ^^

I can live with the automated formatting. I just hate it :)
