### ISSUE TITLE
Edit translation disfunctional

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#245]
I tried before a few moments to document the way of how to translate the UI. But couldn't get it to work. I always end in a error message, no matter what i do. 

Task, investigate into how it's done in Blender, then check why it is failing in Bforartists.

Doesn't make much sense to dive into this issue for Bforartists 1. But becomes of interest with the Blender 2.8 port again. At least when they readd the translation feature. Blender 2.8 in its current state doesn't allow localizations.

**Comment by Draise14** [comment]
The method of the User Preferences in Bforartists 1.0.0 works fine. Me and a few others I've shared BFA with have done it - atleast to Spanish. 

Is this an issue with 2.8 sourcecode?

**Comment by Draise14** [comment]
Ah yeah, it is. Sorry, misread.

**Comment by ReinerBforartists** [comment]
No, it fails here with Bforartists 1.0.0. I must do something wrong.

Mh, i have added the steps in the new manual chapter. Maybe you can have a look at it and tell me where i fail? It's the very last chapter ...

https://www.bforartists.de/data/manual/3.13.1%20Editors%20-%20User%20Preferences%20by%20tools.pdf

**Comment by Draise14** [comment]
Hmm.. It just works on my end with the first steps. The first description of the manual is fine.
I can't reproduce your error though. No console erros.. it's working as intended. 

1. User Preferences>System tab
2. Check **International Fonts**
3. Choose language from "Language" Dropdown
4. Hit a button "Interface" or the other two to translate. 
5. Changes show, no issues. 

I have the System: **Manage UI translations** disabled. I also don't have the paths defined. 

Maybe it's a bad system configuration? 

Here are my user preferences: 
![bforartists_2018-07-28_12-38-48](https://user-images.githubusercontent.com/35357409/43359173-c21f2672-9263-11e8-9a38-9c75b7675411.png)
![bforartists_2018-07-28_12-38-53](https://user-images.githubusercontent.com/35357409/43359175-c4878d32-9263-11e8-8018-2ed25bbc93e3.png)
![bforartists_2018-07-28_12-39-01](https://user-images.githubusercontent.com/35357409/43359176-c5c058f0-9263-11e8-857a-c43e2f913f91.png)
![bforartists_2018-07-28_12-39-07](https://user-images.githubusercontent.com/35357409/43359178-c6fe4506-9263-11e8-825e-c469838eecdc.png)
![bforartists_2018-07-28_12-40-07](https://user-images.githubusercontent.com/35357409/43359179-cb27fc6c-9263-11e8-917f-22ac31433344.png)
![bforartists_2018-07-28_12-40-23](https://user-images.githubusercontent.com/35357409/43359180-cd233c8e-9263-11e8-9028-e78ed62f0eb2.png)
The last cap is the translation Spanish as proof that it's working. Other translations work also, no problem. Even Chinese. 

I put in a screen cap of keyboard layouts I've added to the OS as maybe it's a clue? I'm on W10. 
![2018-07-28_12-42-04](https://user-images.githubusercontent.com/35357409/43359181-d6306b6c-9263-11e8-8030-a60d2d392de5.png)

**Comment by ReinerBforartists** [comment]
Not that we misunderstand us here, i try to modify the translation, through the right click menu. Displaying it is not the problem. This works indeed fine :)

**Comment by Draise14** [comment]
# AH! 
I tested that feature, now I see. I can not edit the translation - this is a developer feature no?

I think you may need to direct the files to the *.po's in the repository, set the "source" to the repository source of bforartists (not Blender), then maybe put the path to the repository source also - then when it's working rebuild it to see the changes.  I'll try test in Blender first.

I assume a built BFA won't pull edits to live *.po files and apply them to the *.mo's in the binary version right away. 

I think also, till you get up to the step of the second error (path not found) the "source" path in the addon is incorrect... 

I guess it's the "Release" in the repository or something else. There isn't much documentation eh?

**Comment by ReinerBforartists** [comment]
Giving up at this one. It's in the end the Blender implementation.
