### ISSUE TITLE
Align View Buttons: typo in "Lock Caymera to view"

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2450]
Reported by a user
![image](https://user-images.githubusercontent.com/25552173/119252618-9183c380-bbad-11eb-8b28-5db21c16d8b1.png)

**Comment by ReinerBforartists** [comment]
Hm, what typoe? It's the align buttons in the align view buttons addon :)

**Comment by iyadahmed** [comment]
> Hm, what typoe? :)
> 
> EDIT, Ah , now ay sy it !

no worries fixing it :)
