### ISSUE TITLE
Iconcreation fails

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2456]
Houston we have a problem. The creation of the icons fails. Normally just the new icons should be created. But currently half of the 16pixel icons are recreated. And when i compile the result then we get an error message.

Means i cannot add any new icons anymore. This goddamn nerd pipeline ...

![conflict](https://user-images.githubusercontent.com/13919702/119321567-11c52a00-bc7d-11eb-9b56-ac1efb1a46ea.jpg)

**Comment by ReinerBforartists** [comment]
Cool. Have thrown out all icons and recreated them from scratch, and now the folder has 24 icons fewer than before.

But at least it compiles again. Now let's investigate into the missing icons before we continue.


![compilesagain](https://user-images.githubusercontent.com/13919702/119323067-98c6d200-bc7e-11eb-9e3e-0f8a3895845f.jpg)

![missingicons](https://user-images.githubusercontent.com/13919702/119323084-9cf2ef80-bc7e-11eb-85bc-632c2a852c26.jpg)

**Comment by ReinerBforartists** [comment]
Always the first icon of the row. But not all 30. Just 24 of them.

Hm. I have added an icon at friday i think. So either the commit has brought changes that i have overlooked. Or tthe code formatting done by make format has mixed things up here. Reverting and testing.

![firsticon](https://user-images.githubusercontent.com/13919702/119325154-e6443e80-bc80-11eb-98e1-7bf62b3f1ef9.jpg)

**Comment by ReinerBforartists** [comment]
Reverted to the state before make format, and everything works fine. The formatting is breaking the icon creation \o/

**Comment by iyadahmed** [comment]
Hmmm but why it only formats code, is there an error?

**Comment by iyadahmed** [comment]
it might be just a git issue

can you commit changes for icons then do format?
Then commit it, and after try creating icon

**Comment by ReinerBforartists** [comment]
I better don't commit anything before i haven't found the trouble maker ;)
And i have. make format has killed a define in source\blender\editors\include\UI_icons.h . And then things goes wonky.

![broken](https://user-images.githubusercontent.com/13919702/119328621-98313a00-bc84-11eb-9d5f-e88be3c81532.jpg)

**Comment by iyadahmed** [comment]
Great!, that comment should be on it sown line then above the define

**Comment by ReinerBforartists** [comment]
This was indeed the problem. And yes, i have put it above now. Isn't code formatting a fine thing ^^

Fixed in master
