### ISSUE TITLE
Render > Lock Interface: possibly missing from everywhere

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2461]
can't find this option anywhere
![image](https://user-images.githubusercontent.com/25552173/119705673-54435e00-be59-11eb-8116-3797daa843d7.png)

**Comment by ReinerBforartists** [comment]
Indeed.

Related: https://github.com/Bforartists/Bforartists/issues/807

**Comment by iyadahmed** [comment]
> Indeed.
> 
> 
> 
> Related: https://github.com/Bforartists/Bforartists/issues/807

Cool, added issue label

**Comment by ReinerBforartists** [comment]
Fixed in master
