### ISSUE TITLE
Toolbar - Decrease scrollbar threshold or visibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2462]
# Request
![bforartists_Yq78vrBXUG](https://user-images.githubusercontent.com/35357409/119859773-4a623f00-bedb-11eb-9484-85c458f8ddba.png)

The new toolbar is wonderful. But the scroll bar is a little obnoxious. It's activation hotspot is 50% of the toolbar. 

Is there a way to decrease the hotspot and/or hide the scroll bar intentionally? Or make it smaller? I know in theming it's coupled with the rest of the UI, but I'm not sure about the hotspot. This may need a look at....

**Comment by ReinerBforartists** [comment]
No. This is defined for all scrollbars from what i know. I don't see a chance to influence this behaviour, sorry.

When it's about me then we wouldn't hide the scrollbars at all. But this is also just a nice dream. 

Closing as won't fix.
