### ISSUE TITLE
Global Header - Expose Area menu entries to "Window" sub-menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2463]
# Request
![image](https://user-images.githubusercontent.com/35357409/120043720-13bb2000-bfd2-11eb-9b7e-c2fc09290e25.png)

A user who has been using Bforartists to teach users from other software has commented that the discoverability of the Editor Area entries is a little hard to find now, since we removed the redundency. 

He had a case though, you'd have to randomly pre-know where to right click to know how to manage the editor areas. So... the GUI should have them somewhere. 

We had a discussion about it, and realized that maybe having relevant ones discoverable in the "Window" menu might implicate that the window relevant or editor relevant operators exist there. How a user learns how to right click on a header or on an edge can come later - but list these operators away from a hidden floating panel somewhere in the UI. 

So.. can we do that?

**Comment by ReinerBforartists** [comment]
No, unforutnately not. This functionality is editor by editor. An entry in the Window menu would not maximize the 3D view for example.

We could put the menu back into the View menu. Abd remove it from the header right click menu. But we discussed this one already. And the decision was to put the content into the right click menu instead. Which was quite a bit of work. I will for sure not revert this one. For me this is the better place. 95% of the users will never split or maximze the windows at all. And the rest knows the hotkey after a few times.

So closing. Nevertheless, thanks for the input.
