### ISSUE TITLE
Merge - Implement changes at cmake files

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2466]
The newest merge comes with changes at the cmake files. I wasn't able to port all the changes, and did run into errors again and again. And it compiles fine with the old files. So i will separate this part from the merge, and solve it separately. 

What makes me wonder is the Windows 32 bit part here. We don't offer 32 bit anymore. 

Affected files: 
\build_files\cmake\packaging.cmake
\source\creator\CMakeLists.txt

There is also a new file in the source\creator directory which is involved here. blender_launcher_win32.c

I will link the commit too once i find it in the log.

**Comment by ReinerBforartists** [comment]
This commit changes the name of the blender-launcher.c file.

SHA-1: e8ca635e43f0b642361c898797c3a3ab3f7dc27e

* Cleanup: rename blender-launcher source file.

**blender-laucher.c was not an ideal name for this file
since it's not directly clear it is windows only.

This change renames it to blender_launcher_win32.c
to be more in line with other win32 specific files
we have.
**

**Comment by ReinerBforartists** [comment]
Just realized that i need to search in the blender commits. The changes are not in Bforartists yet XD

**Comment by iyadahmed** [comment]
> The newest merge comes with changes at the cmake files. I wasn't able to port all the changes, and did run into errors again and again. And it compiles fine with the old files. So i will separate this part from the merge, and solve it separately. 
> 
> 
> 
> What makes me wonder is the Windows 32 bit part here. We don't offer 32 bit anymore. 
> 
> 
> 
> Affected files: 
> 
> \build_files\cmake\packaging.cmake
> 
> \source\creator\CMakeLists.txt
> 
> 
> 
> There is also a new file in the source\creator directory which is involved here. blender_launcher_win32.c
> 
> 
> 
> I will link the commit too once i find it in the log


I believe win32 just refers to windows in general, not 32bit only

**Comment by ReinerBforartists** [comment]
Here's the trouble maker: https://developer.blender.org/D11094

**Comment by ReinerBforartists** [comment]
Fixed in master
