### ISSUE TITLE
Geometry nodes - add new mesh to curve to sidebar, add icon

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2467]
New geometry node, needs entry in the sidebar and icon.

![meshtocurve](https://user-images.githubusercontent.com/13919702/120098560-e1770300-c136-11eb-9e8f-a01be3e4743c.jpg)

**Comment by ReinerBforartists** [comment]
RGB Curves is also new

![rgbcurves](https://user-images.githubusercontent.com/13919702/120111450-4ef45500-c172-11eb-9df3-215839ed1a4c.jpg)

**Comment by ReinerBforartists** [comment]
The RGB curves node already existed in the shader editor. That's why it already has an icon.

**Comment by iyadahmed** [comment]
Interesting

**Comment by ReinerBforartists** [comment]
Fixed in master
