### ISSUE TITLE
Area Options - iconize the Area menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2469]
# Issue
![image](https://user-images.githubusercontent.com/35357409/120224109-63832c80-c208-11eb-9759-c390a2348d48.png)

Currently the Area options to maximize, close and split are located in a right click menu located from the header - but you can also right click the borders of editors to work them (split, join, swap, etc). 

For discoverability sake, I think when headers are hidden you are also hiding the area options accesibility, but you can still access this "Area" menu by right clicking the border of the editor. 

The key issue: for discoverability, you need to right click on an editor header to find this menu - but when there is no header, it's hidden. 
![image](https://user-images.githubusercontent.com/35357409/120211674-ccfa3f80-c1f6-11eb-9e8f-79881219fec0.png)

# Request
Add the Area operators and iconography to the **Area Options** right click menu globally. 

Essentially.. make the header right click floating menu and the Area Options floating menu the one and the same.

**Add:** 
- Close Area
- Maximize Area
- Full Screen Area
- Duplicate Area into New Window

**Change:**
- Rename and iconize Vertical and Horizontal Split
- Iconize the Swap Area and Join Area entries 

Reasons: Discoverability and consistency between area related floating menus. (So it's one for all area operators, and more discoverable - not just in header right click, but editor edge right click)

### Related:
#2379

**Comment by ReinerBforartists** [comment]
The header options have a different purpose than the area options. And i don't want to make them equal.

We could add icons here though :)

**Comment by Draise14** [comment]
The header exclusive options don't have to migrate to the Area Options, only the area `ops.screen.` operators. Right now the `ops.screen` are hidden in a logically irrelevant floating menu (right click on header only). We are already getting user feedback that it's hard to find these operators because they are not obvious. 

Idea is to put the Area relevant operators from the Header Area floating menu to the Area Options menu. It's not redundant, it's complete.

**Comment by Draise14** [comment]
Here is a visual example of the proposal. I didn't mean "make them identicle" as one is a Header Area, the other is Area. But the Header Area has global `ops.screen` Area operators that should be in the Area panel, which are missing. 
![image](https://user-images.githubusercontent.com/35357409/120223918-fa9bb480-c207-11eb-810d-a0fe99537c0e.png)

**Comment by ReinerBforartists** [comment]
Again, this menu has a completely different purpose. I will not make it equal.

**Comment by Draise14** [comment]
I don't get why you are against adding the missing operators to the Area Options. One is to edit the Areas. The other is to edit the areas AND header. Both have "split area" as an example, identical. 

Both have operators for the areas.

The request is to make the **Area Options** have ALL the area related operators. Not just.... 4 of the 8. There are 8 operators related to editing the Area options, shouldn't they all be in the same place? Not spread out over two disconnected floating menu's? Isn't that a design guide for Bforartists, expose and group relevant use cases? 

Why are you against merging these menus and exposing relevant operators? The alternative is.. set your hotkeys and depend on them - or randomly right click on editors with headers - and the property editor doesn't have that.

**Comment by ReinerBforartists** [comment]
Because this two menus has a different purpose.

**Comment by Draise14** [comment]
How are you defining the purposes of these operators? 

I'm basing the proposal and purpose on user request, the operator names, code group of operators and better (more direct) accesibility and consistency

Example: 

Purpose of Header Area:
- Split **area**. 
- maximize **áreas**
- close **area**
- toggle _header_ stuff
- swap _header_ location

Purpose of Area Options
- split **areas**
- swap and join **area**

Those operators are all area operators. It's in the name... Area operators. 

Should the header Area operators also include Join and Swap? And the Area Options also have the maximize and close? 

I think yes. It serves the operators purpose for area operators to be together, in my opinion.

Humour me.. then I'll let it be.. What are the difference in purpose?

**Comment by ReinerBforartists** [comment]
>How are you defining the purposes of these operators?

The one is for the editor window. The other for the border between the editor windows. That's two different purposes.

And sorry when my answers are a bit short at the moment. Lots to do ...

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/120298030-fdf77480-c2c9-11eb-99c0-8dd809cccaa3.jpg)
