### ISSUE TITLE
Global - Area View Entries - Revert and expose Area operators to View menus like before

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2470]
# Issue
![image](https://user-images.githubusercontent.com/35357409/120358381-09e43600-c2cc-11eb-8c5d-a78658dad836.png)
_Image from user_

After strong user feedback, even a call - a number of users have pointed out that we made the wrong choice when we removed a double entry introduced by Blender. 

**Context:**
There  are users who is starting to teach Bforartists live on Twitch, and they are a productive artists; ([https://www.artstation.com/rodrigopixel](https://www.artstation.com/rodrigopixel))

I got into a call and he clarified the case. There are a few other users who use BFA a long time in Discord also who weren't too happy with the change, and another didn't even know where we moved those Area menus to! (ei, it's not discoverable).. so I'm trying to revisit this for the users. 

Right now we have a number of issues:
1. When the header is hidden, the area menu is not accessible by GUI. 
2. When teaching, you can't teach a hotkey, specially if custom (and default doesn't have hotkeys) - so you need the UI. But the current solution has a lot of zigzag - and it's hidden. 
3. The floating menu for the header options is.. about the header, and not about the Editor Area View options by logic
4. Users didn't even know of the change, they just noticed that the menu just disappeared. 
5. The standard of finding all the operators in the headers is expected behaviour and easier to discover
6. Right click on headers is not intuitive. 

I think we chose the wrong redundancy removal with these menus by going the "Blender Way" and hid these panels unintentionally. 

## Task to Revisit
#2379 

# Proposals Suggested
Solution:
- Remove from the Header Right Click menu - add back to the View Menus of all the editors just like we had before. 
- Add the view and Area menu to editors that don't have it (optional). 

### Benefits
- More discoverable
- It was already 98% consistent before, so the old way was still passible
- Lot's of our regular user have requested this.

**Comment by ReinerBforartists** [comment]
Related: Remove double menu entry Area #2379

**Comment by ReinerBforartists** [comment]
Fixed in master
