### ISSUE TITLE
Global - Change "Area Options" title to "Edge Options"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2471]
# Issue 
I was confused with the area operators in the right click on the edge, when in reality it about the edge area operators.  

# Request
![image](https://user-images.githubusercontent.com/35357409/120364806-436c6f80-c2d3-11eb-84a9-974be5751159.png)
Can we change the title to not be confused about it?

**Comment by Draise14** [comment]
Postponed, no rush to think about.

**Comment by ReinerBforartists** [comment]
Hm. I would be confused with edge options since Blender calls it Area options. And so i think we should keep the name for consistency reasons.

**Comment by Draise14** [comment]
AH ok, just a minor nuasance. Will close!
