### ISSUE TITLE
Global - Expose all the optional floating menus into the View headers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2473]
# Request
![image](https://user-images.githubusercontent.com/35357409/120381139-abc54c00-c2e7-11eb-9e27-d2e574cc83d9.png)

Right now, we have **3D View>View>Pie Menus** to see and access all the pie menus of an editor, and right click to assign a hotkey. 

This is great, because we can discover all the pie menus without needing to inherent knowing the hotkey or specific pie addon. We can also manage the hotkeys for them without being locked into defaults. It's just... good for everyone. 

What would happen if we also expose all the floating menus? So we can also apply the same UX to floating menu's and give even more UX customization and GUI exposure to the user? 

**Use Case:**
A user wants to UV more often, but uses a custom keymap with no "U" hotkey calling a floating panel default. So he assigns a hotkey to the floating UV panel from the interface, and works much more efficiently without needing to zig zag to a header or assign to individual hotkeys per operator. 

**Example code:**
I tested the code to see if it could work, and it does... just I don't know how many floating panels there are to make it. What would be the list of existing panels? Would they all be the the _MT_ menus? I could commit this one. 

`layout.operator("wm.call_menu", text = "UV Unwrap Menu", icon = "MENU_PANEL").name = 'VIEW3D_MT_uv_map'`

## Benefits
- Expose that floating menus can be customizable
- Expose ease of use to manage hotkeys for panels
- Extra customization for the end user
- Discoverability that there are more than a few floating panels you could use. 
- This could remedy issues requests from users like the following: #2472
- This could also help learn default hotkeys is assigned already to these panels
- Adding these floating menus also allows to search for them from the editor for teaching

### The old way
The old way of customizing these floating menus was... to find the python name of the panel in the code somewhere (not easy), then copying that code piece command, register a new hotkey in the hotkey manager as "wm.call_menu" then configure the hotkey entry to contain the menu code name you want to call. Then save the hotkeys.

**Comment by Draise14** [comment]
Again, no rush. Just logging community ideas from other users - I will slow down the proposals now!

Thanks for all the awesome work.

**Comment by ReinerBforartists** [comment]
This task is not to resolve since every keymap has other menus hotkeyed. 

The pie menus are fixed. To call menus with a hotkey not. You can assign a hotkey to every menu. It's as simple as adding a new key item, and adding the python menu name in the name field.

Closing, sorry.

**Comment by Draise14** [comment]
Problem is... How on earth do you dig up these menu names to then add to the Hotkeys? You can't search for these menus, you can not filter then menu and the only way you can find existing menu items is a filter with an existing hotkey. 

The only method of getting menu names is actually going into the python code and understanding it.

Maybe we can only list the Bforartist floating panels which are "fixed" to those keys. They don't have to show the key but already they show customisability and discoverability. 

We need to give the artist some options for these floating panels without becoming "hacker man" to do so. Maybe just the BFA floating panels can be exposed to the GUI. 

Another benefit is when it's in the UI, you can search for them.

**Comment by ReinerBforartists** [comment]
As told, this job is not to solve, sorry. You name it, you need to dive into the python files. The python tooltip may give you a hint about some of them. But sub menus are not to discover that way. And it is also not our job to teach the users programming their keymap. We offer a software.

![python](https://user-images.githubusercontent.com/13919702/120511621-dc31e680-c3ca-11eb-949d-6d6fd319631c.jpg)
