### ISSUE TITLE
Show header for new tool system when tabs are on

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2476]
Currently the header for the new tool system is off. It should remain off when the tabs are disabled. And for every other area than the 3D view for now. But maybe we find a way to show it when the tabs are on.

I guess we need two classes then with a def poll since bl_options is a startup call, and cannot be changed at runtime.

**Comment by iyadahmed** [comment]
as a note, this is the case when no header is annoying, I can't reorder this, unless I 
![image](https://user-images.githubusercontent.com/25552173/120823249-8b032d80-c557-11eb-81a3-23ce81bea1fb.png)

**Comment by ReinerBforartists** [comment]
Yes you can. Just drag the panel below to be above ;)

**Comment by ReinerBforartists** [comment]
This part is fixed in master

Remaining task: hide the panel header when we turn off tabs.

![fixedpart](https://user-images.githubusercontent.com/13919702/120829369-9e18fc00-c55d-11eb-8c72-7bfec2f1e85c.jpg)

**Comment by iyadahmed** [comment]
> Yes you can. Just drag the panel below to be above ;)
> 
> 
> 
> Haha, i stand corrected. Doesn't work. wtf? O_O
> 
> 
> 
> Hm. I thought it works. And this changes the game. Let's add the bl_options = {'HIDE_BG'} to the toolshelf in 3d view. 

Yep it didn't work then unfortunately, but with header it works

**Comment by ReinerBforartists** [comment]
Postponing. This is somehting for when the tabs are all implemented.

**Comment by ReinerBforartists** [comment]
Had to use the unelegant method. Dulicated the whole class. 

Fixed in master
