### ISSUE TITLE
Bforartist 2 version 2.9.0 Mac version

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2497]
The new Bforartists version is out.

@seanr, could you be so kind to create the Mac version of Bforartists 2 version 2.9.0 :)

Note that we had a few changes in the cmake files regarding Mac last week. And i am not this sure if everyhting still works as expected. I can't test such changes ...

Note that we have meanwhile a place to share our files here: https://cloud.bforartists.de/index.php/apps/dashboard/

But Dropbox is also fine :)

**Comment by seanr** [comment]
@ReinerBforartists I created an account on that site but will need someone to approve it.

Regarding the cmake changes, what exactly were they?

**Comment by ReinerBforartists** [comment]
Yes, that's me :D

Your account should be enabled now. I just want to keep spammers and non Bforartists members out. That's why the manual activation :)

**Comment by seanr** [comment]
OK, thanks. I've already got it up on Dropbox now, but I'll use that for the next one:

https://www.dropbox.com/s/kvr7l7tgtxsmfbp/Bforartists-v2.9.0-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Many thanks. Downloaded, and uploading :)

**Comment by ReinerBforartists** [comment]
The file is up. Many thanks sean :)
Closing, task is fulfilled.
