### ISSUE TITLE
Weight paint problems

### ISSUE THREAD

**Issue by porky11** [Bforartists/Bforartists#25]
You disabled or at least hided the menuentry "X Mirror" and "Topology Mirror" for Weight Paint mode, which is helpful for symmetric weight painting.
Also it seems not to be possible anymore to select bones while weight painting (selecting was done using right and now uses left like the painting)

**Comment by ReinerBforartists** [comment]
Hi porky11,

Thanks for the report.

Bforartists is not Blender. And quite a few menu entries are now at different locations. X Mirror and Topology Mirror is in the tool shelf. To select another bone in weight paint mode hold down ctrl and click your target bone.

Let me know if this fixes it for you :)

May i ask for the favour that you report future issues in the Bforartists tracker at the Bforartists page? It is hard for us to maintain two trackers. And issues here can easily slip through. The Bforartists tracker is located here: https://www.bforartists.de/project/issues/bforartists_bugtracker

Kind regards - Reiner

![xaxismirrorinweightpaint](https://user-images.githubusercontent.com/13919702/33980094-9f0084ba-e0a7-11e7-8708-85f1ca3ea6e3.jpg)

![xaxismirror](https://user-images.githubusercontent.com/13919702/33980091-9beecb6a-e0a7-11e7-99a9-d218fc4884b5.jpg)

**Comment by ReinerBforartists** [comment]
Closing since there's nothing to fix here.
