### ISSUE TITLE
Toolbar - Image Group - Double menu entry for clear seam

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2501]
# Request
![image](https://user-images.githubusercontent.com/35357409/121926081-3142f600-cd03-11eb-9ca5-83f8720aa1e5.png)

> On the Toolbar, these "UV Clear seams" icons, they seems to be duplicated. Cheers!

Looks like there might be two of the same tool. 

# Task
Check and see what's up
Update icons
Remove duplicate if they exist.

**Comment by ReinerBforartists** [comment]
Even i am not immune to accidental double entries it seems^^

**Comment by ReinerBforartists** [comment]
Fixed in master
