### ISSUE TITLE
Default Theme - Remove roundness from interface for readibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2502]
# Request
![bforartists_cPbuDd7VUu](https://user-images.githubusercontent.com/35357409/121980520-b05f1b00-cd51-11eb-8c45-907a548ce6bf.png)
_This is a custom layout I use, but for the demonstration purposes of using the theme with customized UI of Bforartists I'll use it as the example:_
The Default theme has rounded corners to 0.400. Notice the rounding in the the toolshelf, the toolbar icon groups in the headers, the rounding in all the UI elements and buttons. It's relatively consistent, but attention to interface borders and sliders and more all fight for icon readability and priority overall, specially when using it for hours a day - which can be ultimately noisy over time and tires the eyes for all the detail. 

![bforartists_aup1ZAK2TX](https://user-images.githubusercontent.com/35357409/121980538-b9e88300-cd51-11eb-9825-7e791ad8190a.png)
**Suggestion:** make the default theme have no rounded corners, allowing only rounding in the default editor borders and icons themselves only - increasing UI contrast and readability. 

# Task
![image](https://user-images.githubusercontent.com/35357409/121980691-05029600-cd52-11eb-82f2-af1494ba146c.png)
Remove Roundness in the general Interface section of the theme - set to 0.000. 

### Reason
Now that we have 1400+ icons and many of them being able to be shown on screen at the same time, the other visual elements of the scene with rounded corners fight for attention along with the rounded corners of the icons. If the interface corners were not rounded it could make the icons fight less for attention - meaning they are more readable. 

![PureRef_PernBqz9Ym](https://user-images.githubusercontent.com/35357409/121982118-89561880-cd54-11eb-9268-89009a9bd448.png)

Another addition to the visual UX is that any UI roundness is in editor borders only, meaning it makes them _different_ to show they have context menus and draggability, and the icons can stand out a bit more without being distracted by rounding elsewhere - now irrelevant. Also a subtle less noise when working in it hours upon hours and hours. 

I've been using this setup for a few months now, can't go back to the factory theme. I thought it would be good for others in the default and a slight upgrade for BFA 3.0.0 with Blender 3.0.0 to enjoy a bit more attention to readability when many icons are showing at once.

**Comment by ReinerBforartists** [comment]
This is a matter of taste. And as such no valid task, sorry. I personally find the rounded corners more attractive and better to read.

The icons does not bleed. They have a border anyways. They are 16 pixel tall, and the buttons have 20 pixel.

**Comment by Draise14** [comment]
Concerning the "bleed", the corners loose padding with rounded corners on some icons. This is what I mean by bleed, a loss of padding, even if it's a pixel or two, it's a loss. Not enough padding is not enough silhouette, which is more effort to read. When blurring eyes with rounded corners, those corners makes it "bleed" due to less padding at rounded corners. 

Another reason, just to mention, is that it's more modern also: a fine balance between iconography and "modern" minimal UI's. Less graphical decoration is more emphasis elsewhere sometimes - emphasis on iconography for functionality (and good functionality is good design), this is a design goal we have. So thought it more than just personal taste. 

Oh well. I will throw those reasons out there, then just let it lie. I guess if you think it's personal taste, there is not much I can do about it. Thanks for reading nonetheless.

**Comment by ReinerBforartists** [comment]
There can just be one default. And i am not willing to downgrade. When you prefer sharp corners, it is an easy operation in the theme.
