### ISSUE TITLE
3D View - Pose Mode - Make unique icons for in-between tools

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2505]
# Request
![image](https://user-images.githubusercontent.com/35357409/122578773-d4ed1880-d019-11eb-8fe1-f493b4f6928e.png)

1. The pose breakdowner and pusher has a borderline double entry in the toolshelf now. 

2. Also the icons of the legacy breakdowner and pusher are similar, and need to be split. 

3. Also.. I would love the breakdowner, pusher and Relax up a level to be exposed all the time. 

This is more a general request, I guess this could all be 3 tasks if they are approved. I think these just need a little maturing. 

# Task
Create tasks for each of the topics if approved.

**Comment by ReinerBforartists** [comment]
What is the task here?

**Comment by ReinerBforartists** [comment]
Okay, we need different icons.

**Comment by ReinerBforartists** [comment]
As a reminder, please just one task per issue please. "Fix it all" is no resolvable task.

**Comment by ReinerBforartists** [comment]
Fixed in master

![inbetweens](https://user-images.githubusercontent.com/13919702/122633580-9f0f6900-d0d9-11eb-8569-51c07db4d1d7.jpg)
