### ISSUE TITLE
3D View - Toolshelf - Missing addon entries in tabbed toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2508]
# Issue
![bforartists_xLoibepFKk](https://user-images.githubusercontent.com/35357409/122853554-072b9e00-d2d8-11eb-9415-c7e556f86d62.png)
Here is an addon toolshelf entry. 

![bforartists_nnp97BmZUU](https://user-images.githubusercontent.com/35357409/122853665-33471f00-d2d8-11eb-9722-4bdf82ba1ab0.png)
Here is the same toolshelf in Tabbed mode, but the entries from the addons are missing. 

It's a bit of a hassle to turn the toolshelf tabs on and off to use these addons. 

# Request
Looks like when addons add to the toolshelf, they are not reflected in the code of the tabbed toolshelf panel.

**Comment by ReinerBforartists** [comment]
There is nothing that we can do, unfortunately. We could remove the header again. But then you can't sort the panels anymore.

**Comment by ReinerBforartists** [comment]
Or we keep the header in sight all the time.

**Comment by ReinerBforartists** [comment]
Okay, doesn't help. Addon compatibility goes over aesthethics. Let's use bl_options = {'HIDE_BG'} in the default class, and remove our extra class.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

The tools panel now shows permanently the header, no matter if tabs are on or off.

**Comment by Draise14** [comment]
Oh well, was worth a shot for the logic of no header when tabs are off, but yeah, addons working in both methods would be a good priority. Thanks for taking a look at it and fixing this.
