### ISSUE TITLE
3D View - Edit Mode - improve Grid Fill icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2509]
# Request
![bforartists_NMwImkbNFl](https://user-images.githubusercontent.com/35357409/123345040-cec7d200-d51a-11eb-93b4-0298626a46e5.png)

The grid fill icon... is similar to the other fill icons, but it fills in grids. It would be good to differenciate it a bit more and make it more of a "grid" fill, atleast with a cross line in the middle.

**Comment by ReinerBforartists** [comment]
This is a double icon. I will have a look to create an extra icon for it.

**Comment by ReinerBforartists** [comment]
Great, we have already a gridfill icon. It is just not in use.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/123376241-74665a00-d58a-11eb-96bd-74a9681c7a8e.jpg)
