### ISSUE TITLE
Edit mode: Mesh > "Transform"and some others not shown

### ISSUE THREAD

**Issue by ReaderfRik** [Bforartists/Bforartists#251]
![mesh -transform not shown](https://user-images.githubusercontent.com/29224963/43770772-999c57d8-9a3d-11e8-937a-10fa1741a13e.jpg)
But in the tutorial "Set dimensions addon" on 0'27 these options should appear.
Mesh-addon is activated under User pref.

**Comment by ReinerBforartists** [comment]
Hi ReaderfRik,

The transform tools including the Set Dimensions addon is now in the tool shelf.

I know i should redo the youtube tutorials. But with Blender 2.8 and the port of Bforartists in front of my nose i decided not to continue at the old tutorial material anymore. This work is better spent at Bforartists 2.

![setdimensions](https://user-images.githubusercontent.com/13919702/43777673-c550045e-9a53-11e8-9d91-431d4013e368.jpg)

**Comment by ReaderfRik** [comment]
Thanks for the quick reply, it is clear now. 
I am looking forward to BfA 2.0 ! BfA is a relief, after all the effortless puzzling in the classic Blender layout -_-

**Comment by ReinerBforartists** [comment]
Yes they have been very good at cluttering the Blender interface. 2.8 is a bit better in this regard, but there is still lots of room for improvements.

**Comment by ReinerBforartists** [comment]
Hi michaelbuet,

For general help it's best to use the Bforartists forum. The tracker is for development issues and bug reports.

https://www.bforartists.de/forum

Set dimensions is in the Transform panel. Note that it jumps into Edit mode when you modify the values. It's an edit mode tool.

![setdimensions](https://user-images.githubusercontent.com/13919702/50676991-a6b92100-0ff7-11e9-970e-5c46730f1cad.jpg)

For your other question, i don't understand the problem, sorry. What exactly do you want to achieve? When you wan to create a cube for example, then have a look in the toolbar for the button with the cube at it. Or have a look in the Create tab in the tool shelf.

![setdimensions](https://user-images.githubusercontent.com/13919702/50677060-0d3e3f00-0ff8-11e9-8e46-6339ca48f90b.jpg)


Kind regards - Reiner

**Comment by michaelbuet** [comment]
Reiner,

Tanks again!!  The problem I have is that the Tutorials I am looking at
show and use tools that are not located the same (or even "show up"!) on my
1.0 Startscreen setup, even though the title of the Tutorial "says" it is
for Bforartists 1.0...  "Duffers" like me would need a Tutorial starting
from the basic Download Screen Setup showing them how to setup their tools
the same way as the Instructor - I waste a lot of time with Tutorials on
"Pause" trying to do what they say not knowing where the tool actually
"hides" in my setup!!!

I now know where the Dimension tool "hides" (LOL), thanks to your last
email response - And once more, Thanks again!  :-)

Michael

"We endevour to persevere"
Cherokee Chief Lone Watie

PS:  Are you German?

Michael Buet,
LEAN/Six-Sigma-Black-Belt (LSSBB)
EE/ME - ISO Certification/CI Consultant
Dana Point, CA 92629
(843)489-6505

Punctuation is everything:
*I'm-possible...*

**Comment by ReinerBforartists** [comment]
The tutorials were made with a beta version. And some small things have changed in the final. Sorry for the confusion. With Bforartists 2 we will wait for the final version before we record tutorials. Promised :)
