### ISSUE TITLE
3D View - Armature - Edit/Pose Mode - Add name, IK and constraints panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2510]
# Request
![bforartists_c35X2D3Yu9](https://user-images.githubusercontent.com/35357409/123345892-ae991280-d51c-11eb-903a-d2aeacac25ac.png)

When making rigs, you often use a lot of these operators to build rigs - renaming, constraints and bone setting toggles: 

**Edit Mode:**
![bforartists_lCz37InsKZ](https://user-images.githubusercontent.com/35357409/123346160-45fe6580-d51d-11eb-9d60-03245b1f32bd.png)

**Pose Mode:**
![bforartists_E7kiBugytd](https://user-images.githubusercontent.com/35357409/123346162-4696fc00-d51d-11eb-9db0-9e847ee79719.png)
![bforartists_EAXzDDJVgv](https://user-images.githubusercontent.com/35357409/123346164-4696fc00-d51d-11eb-8f98-0fa16cb3855d.png)
![bforartists_ZIN9LLG82f](https://user-images.githubusercontent.com/35357409/123346165-4696fc00-d51d-11eb-8a99-ee558fb4167f.png)

I would really love to have some of these at a top level, now that my current workflow is hotkeys or digging in the menus many times over, or hotkey + floating panels. 

## Task 
So.. if there were a new tab for "Create", can we add in these 4 panels? 
- Names
- Inverse Kinematics
- Constraints
- Bone Settings

**Comment by ReinerBforartists** [comment]
Hm. We have agreed that not everything makes sense to be in the panels. I have left these panels out for good reason. 

The bones settings cannot be added. This is a very very odd enumerated C menu. I tried it once with Bforartists 1 already. And the rest is imho too special to deserve a own panel. IK and Constraints is best set up from the properties editor. And is no tool, but a setting. It adds IK and Constraints in the properties editor. Groups is also no tool that you use to modify something, and nothing that you click every second. So it better fits into the text menu. Same counts for names. This should imho remain in the text menu. Like copy and paste.

**Comment by ReinerBforartists** [comment]
Anyways. Let's have a look if we can add at least the last three here.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/123382798-a7ace700-d592-11eb-94b3-ccfa43a591fb.jpg)
