### ISSUE TITLE
Bforartists 2 version 2.9.2 Mac version

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2513]
Hey sean,

Could you please be so kind to create us the mac version of the newest release? :)

Kind regards
Reiner

**Comment by ReinerBforartists** [comment]
Please wait a few more days until we have 2.9.2 out of the door ...

**Comment by ReinerBforartists** [comment]
The version 2.9.2 is in the repo now.

**Comment by ReinerBforartists** [comment]
Bump

**Comment by seanr** [comment]
https://www.dropbox.com/s/8cdu0ovz16y6ty1/Bforartists-v2.9.2-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Perfect. Thanks a lot :)
