### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by robverhoef** [Bforartists/Bforartists#2514]
**Is your feature request related to a problem? Please describe.**
As an Apple Silicon (M1) user I was looking for an M1 build or build instructions. I couldn't find it.

**Describe the solution you'd like**
Could you please mention something about how to build this project, in the README.md or Wiki?
A simple link to Blender's build instructions will do the job. https://wiki.blender.org/wiki/Building_Blender/Mac

I have just successfully built an M1 version of 2.9.1. Nothing special worth mentioning, no exceptions: the standard Blender instructions worked out fine.

**Comment by ReinerBforartists** [comment]
Hi robverhof,

Thanks for the idea. We already describe that at our download page. See chapter source code download. But i will have a look to include it into our description here at github too :)

Kind regards
Reiner

https://www.bforartists.de/download/

> In case that you want to compile Bforartists by yourself, the advice is the same as for Blender. Here’s a short tutorial that shows the whole process under Linux Ubuntu 17 www.bforartists.de/data/tuts/Building_with_Ubuntu17.pdf
> And here a youtube video that shows how to compile Bforartists 2 on Ubuntu 20: www.youtube.com/watch?v=sUhM2YSw1gQ
> 
> Here’s the Blender advice for Linux, which goes a bit more into detail: wiki.blender.org/wiki/Building_Blender/Linux
> Here’s the advice for Mac: wiki.blender.org/index.php/Dev:Doc/Building_Blender/Mac
> For Windows have a look here: www.bforartists.de/data/tuts/Building_Bforartists_with_Cmake_and…
> 
> You might want to compile an older Bforartists version where the newest precompiled libs do not work. Here you can find the precompiled libs for all previous Blender versions:
> 
> svn.blender.org/svnroot/bf-blender/tags/

**Comment by ReinerBforartists** [comment]
Done. This text is to find in the readme of the repo now too. Thanks for the report.
