### ISSUE TITLE
Error when enabling industry standard keymap on latest website release

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2515]
Reported by user on Discord, confirmed
![image](https://user-images.githubusercontent.com/25552173/123526082-cf589800-d6d5-11eb-965b-4e28e3ca0e40.png)

**Comment by ReinerBforartists** [comment]
Thanks for the report. That's a Blender bug. Let me do the merge today and check if the problem persists ...

![blenderbug](https://user-images.githubusercontent.com/13919702/123535232-d2c64080-d722-11eb-9c88-830bad338b21.jpg)

**Comment by ReinerBforartists** [comment]
Problem is gone with the new blender build. Means we will see a new Bforartists version this week. And i think i will create a dev version after the merge this time too.

But first go through the merge and check what new things are broken ...

**Comment by ReinerBforartists** [comment]
Error is gone with newest merge. So closing this issue and preparing a devbuild ...

**Comment by ReinerBforartists** [comment]
Developer builds are up. Please test.

I will wait a few more days before i release 2.9.2. Mid week to end of next week. Who knows what showstopper bugs the new merge has brought ...

**Comment by iyadahmed** [comment]
> Developer builds are up. Please test.
> 
> 
> 
> I will wait a few more days before i release 2.9.2. Mid week to end of next week. Who knows what showstopper bugs the new merge has brought ...

Great, will test till then
