### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2519]
A task for future, some tests are failing, which means there is certain possibility of crash when user does some things

We should find why it is failing, either fix it, or edit the test

![image](https://user-images.githubusercontent.com/25552173/123561463-b8cf4100-d7a8-11eb-9626-25bdfb7f2e59.png)

**Comment by ReinerBforartists** [comment]
I have honestly no idea wa these tests are, nor how to fix them ^^

**Comment by ReinerBforartists** [comment]
Well, i can understand why the keymap test fails. We have our own keymap. But the rest should pass just fine. We offer after all the same features than Blender. Yet it doesn't. These tests remains curious since i don't even know what exactly is tested with them.

**Comment by iyadahmed** [comment]
Indeed but it gives us clues, the exact file that fails, it is a task for future anyways

**Comment by iyadahmed** [comment]
For more clarification this is `.\make test` command

**Comment by ReinerBforartists** [comment]
Is this still an issue? At windows no tests are found ^^

![tests](https://user-images.githubusercontent.com/13919702/142856736-2a9a7e1d-0c6f-47cb-9624-2dc68b31c34d.jpg)

**Comment by iyadahmed** [comment]
Ah yes still issue it helps prevent crashes, but honestly we can just close it
