### ISSUE TITLE
Auto Smooth Dilemma

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2525]
To reach and adjust autosmooth is still quite a journey. And not self explaining. You really need to know where it hides.

One possible solution would be to add an autosmooth operator to the object menu, and open the Normals panel under the mouse then. Maybe we can also add the Autosmooth settings directly to the shading panel in the tool shelf. But that's a bit fuzzy since we have by default just a two buttons width.

![autosmooth](https://user-images.githubusercontent.com/13919702/124079125-0c5fba00-da49-11eb-9f27-ac57099450ac.jpg)

![shading](https://user-images.githubusercontent.com/13919702/124079128-0ec21400-da49-11eb-8260-81696d225aec.jpg)

**Comment by ReinerBforartists** [comment]
Part of the job: improve this nerd tooltip to include the information that smooth shading is required to get it to work.

![autosmooth](https://user-images.githubusercontent.com/13919702/124079889-ff8f9600-da49-11eb-99a1-48892b31a2c7.jpg)

**Comment by ReinerBforartists** [comment]
Or even better, switch to smooth shading when activating autosmooth. But this part would most probably be C code ...

**Comment by Draise14** [comment]
Having it added into the normals panel and normals menu sounds good to me, like some quick preset buttons or something. You press it, and it turns it on and sets the smooth angle directly in the 3D Viewport.  

- AutoSmooth 30°
- Autosmooth 45°
- Autosmooth 60°
- Autosmooth 75°
- Autosmooth 90°
- Reset Autosmooth (turns off)

**Comment by ReinerBforartists** [comment]
Haven't thought of fixed angles. But sounds also useful :)

**Comment by ReinerBforartists** [comment]
This is plain crazy. I cannot put the autosmooth checkbox elsewhere. The code is so wicked ...

**Comment by ReinerBforartists** [comment]
Pic or it didn't happen ...

Should work, since it works in the properties editor just fine. But doesn't. I also tried to move the MeshButtonsPanel to the toolbar code. But didn't help neither. And shouldnt be required anyways. The MeshButtonPanel class is registered.

![autosmoothdilemma](https://user-images.githubusercontent.com/13919702/141514337-ead47232-5c52-4920-8105-e821d62b4254.jpg)

**Comment by iyadahmed** [comment]
hmm why not we just create an operator that does this?

```py
import bpy


class BFA_OT_shade_automooth(bpy.types.Operator):
    bl_idname = "bfa.shade_autosmooth"
    bl_label = "Shade Auto-smooth"
    bl_options = {"UNDO"}
    
    @classmethod
    def poll(cls, context):
        if context.active_object is None:
            return False
        
        if context.active_object.type != "MESH":
            return False
        
        return True
    
    def execute(self, context):
        context.active_object.data.use_autosmooth = True
        return {"FINISHED"}
```

**Comment by ReinerBforartists** [comment]
Where do we put this?

**Comment by ReinerBforartists** [comment]
Do you want to have a crack at it? :)

**Comment by iyadahmed** [comment]
sure, what is the desired end result?

**Comment by ReinerBforartists** [comment]
To have it like shown in the screenshot. A dropdown panel to set the autosmooth on and off, and to set the angle

**Comment by iyadahmed** [comment]
Cool working on it now

**Comment by ReinerBforartists** [comment]
Mockup:
![mockup](https://user-images.githubusercontent.com/13919702/141515217-e922d64f-a6d7-46b1-903a-8a0f34895c12.jpg)

I also think of adding it in the tabs, to the shading buttons. The culprit is that the user has always to hunt for the autosmooth settings once he clicked the smooth button. This is what i want to fix :)

![shading](https://user-images.githubusercontent.com/13919702/141515334-1bc8114c-869c-4531-a61b-f00fca341c19.jpg)

**Comment by ReinerBforartists** [comment]
Iyad to the rescue ^^

**Comment by ReinerBforartists** [comment]
I think the problem here is that we deal with an object in object mode ...

**Comment by iyadahmed** [comment]
found a fix
we need to just add some lines before using the panel as popover,
one moment sending
![image](https://user-images.githubusercontent.com/25552173/141516122-f874c0d4-0e8b-4019-86e5-964f7608fe73.png)

**Comment by ReinerBforartists** [comment]
Ah cool. Which part did i miss? :)

**Comment by iyadahmed** [comment]
I think this fixes it

```py
if context.active_object is not None:
    if context.active_object.type == "MESH":
        row.context_pointer_set("mesh", context.active_object.data)
        row.popover(panel="DATA_PT_normals", text="", icon="DELETE")
```

**Comment by ReinerBforartists** [comment]
Many thanks :)

I'll have a further look tomorrow. Or you can also make a pull request :)

**Comment by iyadahmed** [comment]
Sure will make one now

**Comment by ReinerBforartists** [comment]
I have found a fitting icon for it, NORMAL_SMOOTH

**Comment by iyadahmed** [comment]
> I have found a fitting icon for it, NORMAL_SMOOTH

Awesome using it instead

**Comment by iyadahmed** [comment]
there's a problem though

**Comment by iyadahmed** [comment]
even when setting the context pointer when calling poll still gives issue
![image](https://user-images.githubusercontent.com/25552173/141517480-03ae2390-72d3-4121-ba5c-00f9fee55564.png)

hmm I would just create our own panel, one moment let me do it

**Comment by ReinerBforartists** [comment]
I told you it's wicked :D

**Comment by iyadahmed** [comment]
haha yeah

**Comment by ReinerBforartists** [comment]
Awesome. Many thanks :)

I have to reopen it since it is not completely finished yet. As told i want to add this panel to the tabs too. But this shouldn't be a big deal anymore :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/141612044-d11316b8-bbb3-4886-b747-87cc5022724f.jpg)

**Comment by ReinerBforartists** [comment]
Ah, the tooltip ...

**Comment by ReinerBforartists** [comment]
Fixed in master

Much better ...
![tooltip](https://user-images.githubusercontent.com/13919702/141612406-0e27dd07-7e46-4d38-8432-2eb1123e7292.jpg)
