### ISSUE TITLE
Asset browswer - Dragging assets is broken in 2.9.2

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2526]
The asset browser can't drag assets into the 3D view in 2.9.2 version. This may be a blender bug. But it bleed through to BFA.

**Comment by ReinerBforartists** [comment]
The asset browser is still WIP. This will most probably receive a fix in future versions.

**Comment by Draise14** [comment]
Yeah.. I was using it for materials, so that kinda broke that pipeline, but I will close this as soon as a future merge fixes this - just wanted to log it, incase someone else noticed the issue too.

**Comment by Draise14** [comment]
Tested a build from Blender today, works again. SO.. guess it will come with the next merge

**Comment by ReinerBforartists** [comment]
New devbuild is up. Is it back working?

**Comment by Draise14** [comment]
Tested, and it works again.
