### ISSUE TITLE
Interactive Objects does not work correctly as in blender

### ISSUE THREAD

**Issue by EAZY5D** [Bforartists/Bforartists#2527]
**Describe the bug**
Add cube interactively does not work correctly with b4artist compared to blender

**Desktop (please complete the following information):**
The Operating system. Windows 10

**Screenshots, Example Files**
![IrRHqyhgfn](https://user-images.githubusercontent.com/55167211/124338493-9ffbcc80-dba8-11eb-996a-3c8a06d49262.gif)

**Comment by ReinerBforartists** [comment]
Thanks for the report EAZY5D. I will have a look.

You could check if a developer build of Blender behaves the same. I expect that it is not different from Bforartists then. We rely at the master code from Blender, not the release version. And in master they are always a bit ahead, including such changes.

**Comment by ReinerBforartists** [comment]
I have checked it now. And Bforartists behaves the exactly same way than the Blender version at which it is based. Which is currently Blender 3.0.

They have most probably changed the defaults. You need to adjust these defaults by yourself now in the Tools panel.

Either way, there is nothing to fix for us here. So i will close the issue. Thanks for the report.

![surface](https://user-images.githubusercontent.com/13919702/124636902-5d2c4400-de89-11eb-9069-167eb29fdf10.jpg)

**Comment by EAZY5D** [comment]
Thank you
