### ISSUE TITLE
Open Preferences folder opens the installation path instead - improve tooltip

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2529]
We once introduced this feature to deal with the content of the appdata folder. But this button now leads to the installation path of Bforartists. I seem to remember that it once worked though. Needs investigation.

![prefsfolder](https://user-images.githubusercontent.com/13919702/124345105-013a9480-dbd7-11eb-9ff5-c7e45d87fd9e.jpg)

**Comment by raindropsfromsky** [comment]
Works for me. I see three subfolders only: 2.92, 3.0 and Matlib.

Reporting for devBuild, installed through zip on Win 10, Home edition, 64 bit.

**Comment by ReinerBforartists** [comment]
Thanks for confirming. I have meanwhile found out what is going on. When there is no settings saved then the path goes of course into nirvana. When i save the settings then i arrive at the goal.

Hmm, maybe we can catch this exception somehow. Or at least explain it in the manual.

**Comment by Draise14** [comment]
It is a conditional..if appdata doesn't exist it will go to the installation folder LOCAL path. If it exists it goes to USER path. Reason being is.. if there is no user settings saved, it would bug out.

**Comment by Draise14** [comment]
Maybe it needs a more explicit tooltip.

**Comment by ReinerBforartists** [comment]
Maybe. Doesn't run away :)

**Comment by iyadahmed** [comment]
https://docs.blender.org/api/master/bpy.utils.html#bpy.utils.resource_path
