### ISSUE TITLE
In the manual, create a hierarchy of topics in the bookmarks

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2530]
**Is your feature request related to a problem? Please describe.**
The manual presents all bookmarks in a flat list.
![image](https://user-images.githubusercontent.com/9047168/124347828-314c5c80-dc04-11eb-93c4-fc03f5c242be.png)

In comparison, the TOC in any chapter has a nice hierarchical order:
![image](https://user-images.githubusercontent.com/9047168/124347934-bd5e8400-dc04-11eb-9297-9c1eaed28e2d.png)

**Describe the solution you'd like**
The bookmarks can also be re-arranged in a properly hierarchical ordered tree, by assigning a proper hierarchy in the source odt files.

Alternatively, once the combined manual pdf is made, the bookmarks can be manually moved in a hierarchical tree, like this. 
![image](https://user-images.githubusercontent.com/9047168/124347968-e252f700-dc04-11eb-9c54-4b9eb0cc92a9.png)

This is a trivial job, and if needed, I can volunteer to do it for every version of the manual.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ReinerBforartists** [comment]
This is unfortuantely everything but trivial. We merge the single pdfs with PDF Sam, and we have no influence at this detail.

So as sorry as i am, we have to close this request.
