### ISSUE TITLE
Constraints - align props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2534]
One chapter that we haven't tackled yet is the text alignment in all the constraints. Ideally also here the text and props should be left aligned.

This most probably needs to happen at a one by one base. One constraint after another ...

![constraints](https://user-images.githubusercontent.com/13919702/124552547-00eb0500-de34-11eb-88ba-9bd07cd44c3c.jpg)

**Comment by ReinerBforartists** [comment]
Let's start to dig here. Fingers crossed ...

**Comment by ReinerBforartists** [comment]
Ah, nice, the defs are python code =3

**Comment by ReinerBforartists** [comment]
Not sure what to do with these here ... 

![whattodo](https://user-images.githubusercontent.com/13919702/142906632-79dd6add-745b-461d-bc78-331b4e92faa0.jpg)

**Comment by ReinerBforartists** [comment]
To do, machete through the subsub chaos here ...

![machete](https://user-images.githubusercontent.com/13919702/142907256-7fef6431-0595-42ec-9347-d08301b8fbc8.jpg)

**Comment by ReinerBforartists** [comment]
Same for the action constraint
![action](https://user-images.githubusercontent.com/13919702/142907641-c4564f58-075b-4dc7-9df3-f33ffae986cc.jpg)

**Comment by ReinerBforartists** [comment]
And in the shrikwrap modifier

![shrinkwrap](https://user-images.githubusercontent.com/13919702/142909751-f8e18549-dedc-4a58-8035-62064900574d.jpg)

**Comment by ReinerBforartists** [comment]
I would also say we add our triangle button here to hide the unused content away.

**Comment by ReinerBforartists** [comment]
Transform cache needs also a special treatament ...
![cache](https://user-images.githubusercontent.com/13919702/142992167-e5591f44-9bbf-47fd-a5b3-a481a09327ab.jpg)

**Comment by ReinerBforartists** [comment]
The three props at the top are c code, part of layout.template_cache_file(con, "cache_file")

source\blender\editors\interface\interface_templates.c, starts at line 6519  

`if (!engine_supports_procedural) {`

**Comment by ReinerBforartists** [comment]
Stretch to constraint.

![stretchto](https://user-images.githubusercontent.com/13919702/143080402-d96162dc-d462-4f5b-b64a-af51da9e1ad6.png)

**Comment by ReinerBforartists** [comment]
Limit location constraint
![limitloc](https://user-images.githubusercontent.com/13919702/143200244-392f4fb3-0b74-4268-80a6-9c6631f9936b.png)
![loc](https://user-images.githubusercontent.com/13919702/143200257-869b153f-bbea-4ffa-ba9d-078d765cb12f.png)

**Comment by ReinerBforartists** [comment]
Rotation constraint
![limitrotation](https://user-images.githubusercontent.com/13919702/143209741-4b7ab303-17b4-4790-adcf-1ae3d02f2e5c.png)
![rotationon](https://user-images.githubusercontent.com/13919702/143209756-6349b5f6-0a68-4f43-8496-7d6edaed5663.png)

**Comment by ReinerBforartists** [comment]
Remains the transform cache constraint with its c code ...

**Comment by ReinerBforartists** [comment]
One prop left ...

![onesmissing](https://user-images.githubusercontent.com/13919702/143219224-b45eb3b3-c176-4ecd-9534-3152beb0eae0.jpg)

**Comment by ReinerBforartists** [comment]
What is the problem here?

![problem](https://user-images.githubusercontent.com/13919702/143224851-29372ac9-c113-4f14-a0e1-e3edacf73515.jpg)

**Comment by iyadahmed** [comment]
Duplicated property? hmmm

> What is the problem here?
> 
> ![problem](https://user-images.githubusercontent.com/13919702/143224851-29372ac9-c113-4f14-a0e1-e3edacf73515.jpg)

**Comment by ReinerBforartists** [comment]
No, the duplicate comes from me :D

The checkbox is not left aligned though. Which it should.

**Comment by ReinerBforartists** [comment]
Ah wait, i think there is a line missing that tells the prop not to use separation ...

**Comment by ReinerBforartists** [comment]
Not my day. Catched by cpt obvious. This was indeed the problem. On with the battle. I want to have the triangle button here ...
![problemfixed](https://user-images.githubusercontent.com/13919702/143233341-76cab099-5a72-4d0f-b34b-6274a2105e1a.jpg)

**Comment by ReinerBforartists** [comment]
So far so good. But how do i add a layout.label(icon='DISCLOSURE_TRI_RIGHT')  in c code?

![transformcache](https://user-images.githubusercontent.com/13919702/143236068-a1d3c78e-ebe7-4cdb-94b4-c83cdd0f5478.png)

**Comment by ReinerBforartists** [comment]
Ah we have already an example in the interface_templates.c file. Let's have a look if we can adopt this.

```
    if (BKE_scene_uses_cycles(scene) && !BKE_scene_uses_cycles_experimental_features(scene)) {
      uiItemL(
          row,
          TIP_(
              "The Cycles Alembic Procedural is only available with the experimental feature set"),
          ICON_INFO);
    }
```

**Comment by ReinerBforartists** [comment]
That for the triangle icon ...

![fixed](https://user-images.githubusercontent.com/13919702/143283785-7a396ba1-cf82-422b-afcd-370f28431c4e.png)

**Comment by ReinerBforartists** [comment]
IK constraint
![ik](https://user-images.githubusercontent.com/13919702/143286555-7cff823f-05c3-49b9-967a-2db11d422a1e.jpg)

**Comment by ReinerBforartists** [comment]
And last but not least the spline IK constraint. 

Fixed in master

![splineik](https://user-images.githubusercontent.com/13919702/143290714-6b1ef9af-49e1-41bb-bc48-61fd9376a043.png)

![chainscaling](https://user-images.githubusercontent.com/13919702/143290739-d7bc04b9-1cab-4940-b98d-54633314e2db.png)
