### ISSUE TITLE
Fix left aligned text at a button in the Vertex Weights panel

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2538]
This left aligned text at this button looks odd. Because by default the text is middle aligned at buttons. 

The value in the edit box is also right aligned here. It should be centered like in the rest of the UI.

This left aligned text could be useful though. We have a ton of buttons where left aligned text at buttons makes much more sense. The whole add panels in the node editors sidebar for example.

![vertweightpanel](https://user-images.githubusercontent.com/13919702/124635892-3c172380-de88-11eb-8abb-35423f1a2158.jpg)

**Comment by ReinerBforartists** [comment]
C prop. And no idea how i could aling the text in the middle here.

We could report it as a bug and see what happens :)

**Comment by ReinerBforartists** [comment]
Ah, this is one of our changes that strikes back here. Blender has it also not correct though. Here it is right aligned.

![right](https://user-images.githubusercontent.com/13919702/124654260-a2a73c00-de9e-11eb-8d0c-dbebe0da5c76.jpg)

**Comment by iyadahmed** [comment]
for some reason this panel doesn't show in BFA but shows in Blender?

**Comment by iyadahmed** [comment]
hmm in blender master it is removed too?

**Comment by ReinerBforartists** [comment]
It's a trap! :)

It is not removed. But just shows under special circumstances. 

To show this panel you need to be in edit mode with exact one vertex selected. And this vertex needs to have a weight paint assigned.

You can also show it in weight painting with the vertex selection setting active. 

![editmode](https://user-images.githubusercontent.com/13919702/128622689-78c663ee-19d7-43f5-8611-dfe31e245848.jpg)

![weightpaint](https://user-images.githubusercontent.com/13919702/128622690-327115b3-f44d-4121-a5c8-e6625d020acf.jpg)

**Comment by iyadahmed** [comment]
Ah ok, Blender UX :D, very special requirements imho :)

**Comment by ReinerBforartists** [comment]
But fits perfect into the UI philosophy of hiding away what is not needed :)

**Comment by iyadahmed** [comment]
> But fits perfect into the UI philosophy of hiding away what is not needed :)

yes, fixing turned to be easy, idk why it was aligned right on purpose, commenting out the line fixes it
![image](https://user-images.githubusercontent.com/25552173/128629333-8099a102-a755-4209-b5c0-40c967a509ce.png)
![image](https://user-images.githubusercontent.com/25552173/128629356-180e9794-c105-49dc-a786-1e249f837f74.png)

**Comment by ReinerBforartists** [comment]
Nice :)
