### ISSUE TITLE
Feature request to add a Krita like timeline for the Bforartists version of Blender 2.8 (Grease Pencil only)

### ISSUE THREAD

**Issue by ArtsyCosmicDreamer** [Bforartists/Bforartists#254]
I have been using both BforArtists and Blender 2.8 and have felt in love, and I know the BforArtists fork will fix even more once 2.8 is released. However, coming from the perspective of a 2D artist that is using Blender for 2D and 3D purposes, I found that the dope sheet worked well for 3D (As that is what it was meant for) but is very clunky with 2D. As a frame by frame 2D artist, I'm used to just having one frame and then drawing to add the next, and while everything to the drawing tools and how it functions is perfect for what I need, this area is where I find I am having issues or lacking in, which makes sense as the dope sheet was designed specifically for puppet animation.

My solution is to implement the Krita timeline within BforArtists, making it an incredible powerhouse of an animation program. The issue with the Krita timeline is that while it is very good and functional, it is often neglected in development by the Krita developers considering it is primarily meant to be an art program. I feel like this change will not only help make Blender a far better tool, but also streamline it for 2D frame by frame artists.

When it comes to alternatives, there aren't any I can think of besides maybe opting for Opentoonz timeline instead as it might be easier to implement into Blender, or just using the standard animation in Blender, though I still feel it has issues with my frame by frame workflow.

https://github.com/KDE/krita
https://docs.krita.org/en/reference_manual/dockers/timeline.html

Opentoonz:
https://github.com/opentoonz
![opentoonz_4](https://user-images.githubusercontent.com/33948645/43988511-14eb9e8e-9cec-11e8-9dfa-0810729ccb49.png)

Another alternative I have considered is making my own bounty, and finding funding to implement this feature.

I hope this is feasable to implement by making Blender easier and more efficient for 2D artists!

**Comment by ReinerBforartists** [comment]
Hi ArtsyCosmicDreamer,

The idea is nice. But i fear this fish is too big for us. It might take us years to get back to the state with the Blender 2.8 merge that we have with Bforartists 1.0 now. 

And this would be more than just a cosmetic change at the UI. This one would affect the whole underlying code, and require a rewrite of big parts of it. There is unfortunately no separation between core code and UI code in Blender ...

But you are very welcome to make a branch and try it by yourself. Every improvement is welcome :)

Kind regards

Reiner

**Comment by ReinerBforartists** [comment]
Closing this one for now. The idea is not forgotten, but the task is too general. What we can change is small details, one by one, starting from what we have. But that's already the dilemma. Blender 2.8 is not yet merged into our master, it is not ready yet. We don't even know what we will have.
