### ISSUE TITLE
In the 3D viewport, the purpose of pinning is not clear; the shortcut is wrong

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2540]
**Describe the bug**
In the 3D viewport, click on the **Object** tab at left. 
A stack of toolbar headers appears.
(In the screenshot below, the header of the **Apply** toolbar is encircled, just as an example.)
![image](https://user-images.githubusercontent.com/9047168/125168436-35a7e500-e1c3-11eb-98b3-be47b81acbf6.png)

The header can be pinned using two different methods:
1. **One-step method:** SHFT+LMB on the header
2. **Two-step method:** Right-click on the header and then left-click on the header.

But when we use the second method, b4a shows the checkbox and says "SHFT Left click".
This is wrong: The text should say only "Left-click"  **[BUG#1]**

Better, when the mouse hovers over the toolbar headers, then the status line should show that LMB pins the header. 
By "status line", I mean the strip at bottom of the GUI that shows display like this:
![image](https://user-images.githubusercontent.com/9047168/125169162-8836d080-e1c6-11eb-8acd-15c1b7167d5b.png)

Secondly, the pinning has no effect at all on the toolbar. **[BUG#2]**
1. It does not prevent collapsing of the toolbar.
2. It does not prevent moving the toolbar to another position in the stack.
(These are the only two intuitive uses of pinning a toolbar.)

**Desktop (please complete the following information):**
Wiondows 10 Home, 64 bit (not relevant here)

**Screenshots, Example Files**
See above

**Comment by ReinerBforartists** [comment]
Thanks for the report. I will have allook at this.

**Comment by Draise14** [comment]
Ah, just to clarify, pinning is for panels exclusively.. not the entire toolshelf.

**Comment by ReinerBforartists** [comment]
I can't see a bug here neither. Also not the first one. Shift left mouse is the only hotkey to pin the panels. There is no right click then left click. Right click brings up the rmb menu. Where you can pin the panel then. And it shows the correct hotkey. The status bar is at no point involved.

So thanks for the report. But this task is unfortunately invalid.

![rmbpin](https://user-images.githubusercontent.com/13919702/125169560-0f764b00-e1ab-11eb-9281-1ee5fa624482.jpg)

**Comment by raindropsfromsky** [comment]
> pinning is for panels exclusively.. not the entire toolshelf.

I saw your YouTube video, and realized the actual functionality. Actually, the word "pinning" is used for a specific purpose in English GUIs: To make that part non-movable, or non-hidable. The non-pinned parts can be moved around or hidden with a command.

But here it is used to make the header available in all (both) tabs. 
In that context, the use of "pin" is inappropriate, IMHO.
The name of this checkbox should be changed from "Pin" to "All tabs".
The message is unmistakable: It is not "pinned" within the current tab, but made available to all tabs.

**Comment by ReinerBforartists** [comment]
But this would add confusion about the functionality. It does not all tabs, whatever that would mean. Pin is what it does, and that is what it is called. Pin is also what the Blender users are used to.

Just fix what is broken. This functionality works as designed  :)

**Comment by raindropsfromsky** [comment]
> It does not **all tabs, whatever that would mean.** Pin is what it does, and that is what it is called.

Well, the tooltip for this control itself says "show on all tabs"!
![image](https://user-images.githubusercontent.com/9047168/125218936-988f9e00-e2e1-11eb-8286-ecf0152689e5.png)

**Comment by ReinerBforartists** [comment]
This tooltip is correct. Once pinned the panel shows in all tabs.
