### ISSUE TITLE
Fix Github workflows

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2541]
I work since days at it and forgot to make a tracker issue for it. That for my so called holiday XD

Ubuntu is finally working. Now comes Mac. Not sure if we can manage to get Windows working. I remember there was a problem with not enough ram ... :D

**Comment by ReinerBforartists** [comment]
Windows is not to convince. No error, but it simply doesn't compile. And then there is of course also nothing to upload. 

No idea where the problem is. Reading through the actions manual at the moment

**Comment by ReinerBforartists** [comment]
Unassigning for now. No idea how we can convince the Windows file ...

**Comment by iyadahmed** [comment]
can I try at this?, I think it only needs minor changes

**Comment by ReinerBforartists** [comment]
Sure you can. Merged and running at the moment.

**Comment by ReinerBforartists** [comment]
I was so close but yet so far. Many thanks for this fix Iyad :)

Did some last cleanups. All tasks done. Closing.
