### ISSUE TITLE
Filter for Preferences

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2548]
**Is your feature request related to a problem? Please describe.**
B4A has a filter for Properties editor, which makes it easy to find a property.
Well, the Preferences box also contains a similar huge number of parameters, but there is no such filter to quickly locate them.

**Describe the solution you'd like**
We should have a similar filter for the Preferences also.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ReinerBforartists** [comment]
What search? And what preferences box? The search in the preferences editor does not have any additional filter functionality. So i am a bit lost here at the moment. Could you please provide a screenshot?

**Comment by raindropsfromsky** [comment]
Search in **Properties** pane:
![image](https://user-images.githubusercontent.com/9047168/125217973-89a7ec00-e2df-11eb-9fcb-eec29b5c2249.png)

It should be here also:
![image](https://user-images.githubusercontent.com/9047168/125217870-536a6c80-e2df-11eb-8099-a01f8c887e94.png)

**Comment by ReinerBforartists** [comment]
Thanks for the screenshot. Now i see what you mean :)

Such a change is out of scope for Bforartists. This is no easy operation. And so it is a feature that is best asked the Blender developers.

You can make a request at Rightclickselect: https://blender.community/c/rightclickselect

**Comment by raindropsfromsky** [comment]
Thanks! Will do!
