### ISSUE TITLE
Known Issue (2.9.2) - Appending and Linking in Thumbnail view broken in the Browser and Asset Manager

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2550]
# Issue
Current build 2.9.2 has an issue with the asset browser and the file browser which made selecting in the thumbnail view impossible (you can't use the file browser in thumbnail mode) and also impossible to use to drag in assets from the Asset browser.  

The devbuild 10-07-2021 has the fix merged in, as this issue and fix was coming in from Blender.

**Comment by ReinerBforartists** [comment]
Hm. We simply can't make a point release every two weeks without a good reason.

The asset browser is no official Blender feature yet. Use at own risk. This does not qualify for a point release. And what is wrong with the file browser? It works okay here.

![browser](https://user-images.githubusercontent.com/13919702/126042926-4473baef-bdbd-43f0-bba8-bff9f662cb68.jpg)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/126043170-f42fade8-25a9-410c-a386-04e757a0421e.png)

Tested in 2.9.2 factory and custom. Fixed in the dev build. 

1. File>Append 
2. Navigate to a blend
3. Open the blend
4. Go to thumbnail view
5. Double click to enter any of the data folders of the blend file

Nothing will happen, it's broken, you can't enter the blend file data folders in thumbnail view. This is also true of the Asset Browser, since it's the same code and hotkeys. Same is true using the Blender hotkeys.

**Comment by ReinerBforartists** [comment]
Works like charm here.

**Comment by Draise14** [comment]
How did you fix it? I have done a factory reset, deleted the config folder. Another user in Discord also reported this.

**Comment by ReinerBforartists** [comment]
Didn't fix it, had the current version open ^^

**Comment by Draise14** [comment]
Bizzare, what is going on!? I seriously can't make it work, only the newest devbuild fixed the issue.

**Comment by ReinerBforartists** [comment]
As told, i had the wrong version open, not 2.9.2

**Comment by ReinerBforartists** [comment]
Just as a sidenote, appending in 2.9.1 works just fine ...

**Comment by Draise14** [comment]
haha, ah ok. For a moment I had an existential panic mode activated, wondering if I was going crazy. =P

**Comment by ReinerBforartists** [comment]
Just me who is crazy here ^^

**Comment by ReinerBforartists** [comment]
That for my holidays. I try since four weeks to do some of my other things ... ^^

Blender master is currently amazingly troubled. Could you please check the current developer version that i have uploaded before a few moments. And check if you find yet another showstoper? 

I don't want to release yet another point upgrade next week. The plan was to re-enter development in autumn, when Blender 3 is out. When we know what exactly the direction is. And not every two weeks to do yet another point release.

**Comment by Draise14** [comment]
Just for the record, I agree with the point release being soon.. maybe we can wait till the next Blender LTS release? I just have been redirecting the users who notice to the devbuild. Though for production sake, having a working "official" release is nice for work. 

This doesn't have to be rushed.

**Comment by Draise14** [comment]
I'll change the title to just log the known issue that is fixed in the next potential release in Autumn.

**Comment by ReinerBforartists** [comment]
Well, not being able to assign assets is a showstopper. We need to fix this. I just want to make sure that we don't end in the same situation in two weeks again, with yet another showstopper bug.

**Comment by Draise14** [comment]
Ok, tell you what, on the next developer build, I'll test it in production for a week then let you know. I have stuck to 2 weeks ago due to production issues when migrating and a need for a custom SSGI build in a current project, but that is finishing. I can then continue another project with the devbuild like normal.

**Comment by ReinerBforartists** [comment]
Nice to hear. But i will prepare the new point update tomorrow ^^

**Comment by ReinerBforartists** [comment]
New version with the fixes released. Closing.
