### ISSUE TITLE
Server migration

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2579]
I am at transfering our server to new hardware at the moment. This becomes something bigger and bigger and bigger the longer i work at it. And it would be nice to keep the informations somewhere in case i ever succeed at it. So i make it a task.

First i tried to transfer all the settings manually, with a fresh installed system. But this turned out to be a sysiphos task with lots and lots of errors. So i tried the rsync route. Which turns out to be a sysiphos task with lots and lots of errors too :D

Make sure the source and target server is the same OS with the same version. Run apt update and upgrade to make sure the software has the same version too. Rsync is by default installed at Debian. Furthermore OpenSSH should be installed and working too. That's how rsync connects to the old server then.

The following happens at the new server at the bash.

The rsync command that i currently use is grabbed from a youtube video tutorial, and received a few modifications:

_nano rsync.sh_

paste in the following:

`rsync -auHxvz -P --stats --human-readable --numeric-ids --exclude=/etc/fstab --exclude=/etc/network/* --exclude=/proc/* --exclude=/tmp/* --exclude=/sys/* --exclude=/dev/* --exclude=/mnt/* --exclude=/boot/* --exclude=/root/* -e 'ssh -p XXX' --progress root@178.238.xxx.xxx:/* /`

the three XXX is the port number that i use at my old server. I don't use the standard port 22. When you use the standard port, then the -p switch is not needed. Note that after rsync the new server will also use the port from the old server. And the IP needs of course to be made of numbers, not xxx.

Save the file. then run

_sh rsync.sh_

This step works after two days of battling with the rsync command surprisingly well now. And in the youtube video the new server worked nearly immediately.

But currently neither Apache nor the database is starting at our new server. The cause is most probably that i carried over the settings from the old server without removing the original settings at the new server. And then a few files are double. Apache moans for example about a double set of mpm.

Currently at melding through the etc folder of the old and new server to catch these doubles.

**Comment by ReinerBforartists** [comment]
Apache was to resurrect. Database not. And Postfix was broken then too. We miss around 30 users, including the Postfix one. And  it was not possible to add it properly back by hand ...

So from scratch. Just not sure what strategy to use now. Rsync speeds things up for sure. But we need a way not to mess up the installation with it.

This is so mean. I have read through dozens of "how to easily migrate your server with rsync" articles and youtube videos now. And they all snip with the fingers and the new server just works ^^

**Comment by ReinerBforartists** [comment]
To port everything including databases and configs with rsync does not work. The old config files will conflict with the new ones. At least for apache. So i have now used apt-clone to transfer at least the packages. Now let's have a look what to do with the rest.

I hope i have still all the passwords for the different data bases ^^

**Comment by ReinerBforartists** [comment]
Rsync saved me to download and upload the content of the www directory ...

rsync -avz -e 'ssh -p 6448' --progress root@178.238.xxx.xxx:/var/www/ /var/www/

**Comment by ReinerBforartists** [comment]
Now comes the fuzzy part. To reapply all the changes that we did over the years to the config files.

The php defaults are as usual in the way of reuploading the data bases. The 2 megabyte default is a joke since years. And our databases aren't even this big with maximum 10 mb ...

**Comment by ReinerBforartists** [comment]
Took me hours now to find out why Adminer refused to go over the 2m limit. Webmin just shows two php.ini. one for apache, one for cli. I modified both upload_max_filesize to 128m. No success. The php.ini that i need to modify is in fmp. Geez, Linux. ONE config file should be more than sufficient ...

And i run as usual with every step into new trouble. Not a single one without research. Let alone being self explaining. Currently i run into a (1046): No database selected error when trying to import a database. Seems that i first have to create the database structure before i can import anything.

**Comment by ReinerBforartists** [comment]
Ah, the adminer import requires a sql file exported with adminer. The sql dump created by the log rotate misses the required create, drop & create and insert settings. So this dump is just good when the database already exists.

Note to myself: make a manual backup from time to time.

**Comment by ReinerBforartists** [comment]
Okay. Single files was for the birds. The users doesn't transfer this way. So let's try an all in one export. Means after i have resolved the error that post_max_file is again too small. Geez, why does linux config defaults always need to be unuseable? -.-

**Comment by ReinerBforartists** [comment]
All in one file also fails. Unfunny.

**Comment by ReinerBforartists** [comment]
Hm, seems that rsync comes to the rescue again. Let's test it.

> rsync -avz /var/lib/mysql/* user@example.com:/var/lib/mysql/

**Comment by ReinerBforartists** [comment]
The correct command, run at the new server: 

> rsync -avz -e 'ssh -p 6448' --progress root@178.238.xxx.xxx:/var/lib/mysql/ /var/lib/mysql/

All database passwords are then from the old server, including the mysql password!

On with the apache configs.

**Comment by ReinerBforartists** [comment]
Small fixes:

Resurrected Webalizer, which is a statistics module in Webmin. It has nothing to record at the moment though. Since the traffic still goes to the old server.
Reinstalled Webminstats. Another Webmin module. But none that comes by default.

Made ssh login possible again by adding an ./ssh folder in the root directory that contains the authorized_keys file. I grabbed it from the old server. Putty creates keys where you first have to extract the key value to put it into the authorized_keys file.
chroot for ./ssh is 700, chroot for authorized_keys is 600

For now you can still log in into putty with password. But this will then changed to ssh once the server migration is done.

**Comment by ReinerBforartists** [comment]
Rewriting all the apache configs turned out to be a daunting task. So i simply copied over the apache directives from sites-available and sites-enabled. Now i need to wait 24 hours for the dns entry to update. I have changed the dns entry of my old reinerstilesets domain to the new server now. And in case everyhting works then i can continue with the let's encrypt and certbot part. But i expect trouble ahead ^^

Still need to go through the configs of the most important software. So that's the task for the rest of the day.

**Comment by ReinerBforartists** [comment]
As expected, now starts the work ...

ERR_CONNECTION_REFUSED

**Comment by ReinerBforartists** [comment]
There were some apache modules missing. Now i am stuck with the certbot. At least i hope that it is really just a certbot problem. And not one with moving Wordpress ...

**Comment by ReinerBforartists** [comment]
Phew, this was quite a challenge. But now my old page is running at the new server. 

Trouble was most probably the default debian page in var/www/http folder. There was a conflict that i couldn't catch. So i deleted all apache virtual servers, created new virtual servers for the domain, one for port 80 one for port 443, copied over the apache directives from the old server. Then installed and set up snap and certbot, and voila. This time the page is showing. With https. What a relief.

Next week after the merge i will have a look at the bforartists content and server hardening. We're getting close :)

**Comment by ReinerBforartists** [comment]
I cheered too early. There is trouble with all the download links. Clicking at a link does nothing anymore. And even "save as" hangs up then, and never finishes the download. Hm. No idea what causes this. And nothing to find in the web about it.

**Comment by ReinerBforartists** [comment]
> Google announced in early 2020 that it will block content that is served via the insecure HTTP if the originating page uses HTTPS. The company decided to roll out the feature gradually by adding more and more file types to the blocklist. Executable files, e.g. .exe or .bat, are the first file types to be blocked, and the release of Chrome 86 put that block in place. Future versions of Chrome will block non-executable file types such as PDF, ZIP, or JPG files.

Wow! Just Wow!

This means that most of my content at my old page wasn't downloadable anymore since a pretty while.

**Comment by ReinerBforartists** [comment]
The dns entries are changed now. The Bforartists domain should point to the new server within the next few hours. Certbot is still making fun with me though, i had a hard battle to convince it from a subdomain. So not sure if the page will vanish once the domain routes to the new server. Especially not our cloud, which is tied as as a subdomain to the bforartists domain. Fingers crossed ...

**Comment by ReinerBforartists** [comment]
It remains curious. I refresh the ssl certificates for the one domain, and the other domain that worked just fine breaks, and throws a error about no secure connection ...

**Comment by ReinerBforartists** [comment]
Woah. mnaether came to the rescue and fixed the last two remaining errors. Bforartists page and cloud is up and running again. 

Remains cleaning up and server hardening. And check if we haven't forgotten something at the old server.

**Comment by Draise14** [comment]
So happy to see it back again.

**Comment by ReinerBforartists** [comment]
So happy to be through with it :D

I hope it was worth the hassle. It is still the same hoster. But newer hardware. It can happen that i leave this hoster very quick in case this doesn't bring the promised speed boost.

**Comment by ReinerBforartists** [comment]
Calling this job done. Server is up and running.
