### ISSUE TITLE
[CI] Builds on Travis CI are all failing

### ISSUE THREAD

**Issue by probonopd** [Bforartists/Bforartists#258]
All the builds are red: https://travis-ci.org/Bforartists/Bforartists/builds

`/opt/lib/blosc/lib/libblosc.so: undefined reference to '__cpu_model'`

**Comment by ReinerBforartists** [comment]
Yesm we are aware about this issue. MoxFulder has started this one as an experiment. But has no time at the moment to maintain it.

**Comment by probonopd** [comment]
I would highly appreciate if the continuous builds could be made work, as they would serve as the basis for making AppImages. Thanks for your kind consideration!

**Comment by ReinerBforartists** [comment]
Me too. But volunteer work is ... voluntary ^^

**Comment by probonopd** [comment]
To the developer, binaries without source code are worthless.
To the user, source code without binaries is worthless.

So to be useful, developers need to put out source code that actually compiles :-)

**Comment by ReinerBforartists** [comment]
It does. Travis fails here. Not the source code.

**Comment by probonopd** [comment]
> Travis fails here. Not the source code.

Let's say "this source code does not compile on the Ubuntu trusty environment that Travis CI uses" ;-)

**Comment by ReinerBforartists** [comment]
But compiled fine at my Ubuntu in my VM ;)

As told, i have no idea what goes wrong here. I think it could be the travis settings in our repository. But i have no idea how this all works.

**Comment by probonopd** [comment]
> But compiled fine at my Ubuntu in my VM ;)

Ubuntu 14.04 (trusty)?

**Comment by ReinerBforartists** [comment]
No, Ubuntu 14 doesn't work. I compiled here at Ubuntu 17. MoxFulder compiled at Arch.

**Comment by probonopd** [comment]
That's the issue then. Since Ubuntu 14.04 is still an officially supported distribution, I don't understand why people see it as "deprecated".

**Comment by ReinerBforartists** [comment]
It's simply too old. Even Ubuntu 17 is a old version nowadays :)

**Comment by ktotheoz** [comment]
The support for TravisCI is deprecated for now due to the usage of AppVeyor. The problem with TravisCI is the usage of rather "old" Ubuntu versions. The support of 16.04 Docker image took a very long time and from the current point of view it is not clear when and whether there will be a 18.04 image at any time (https://github.com/travis-ci/travis-ci/issues/9460) [we had a discussion about exactly this issue this morning].

This leads to AppVeyor, which adds Linux support some months ago with an initial Ubuntu version of 16.04 and support for 18.04 coming soon (https://www.appveyor.com/blog/2018/05/15/appveyor-for-linux-is-generally-available/).

That's the reason for closing this issue. I will open a new issue regarding the unified AppVeyor integration.

**Comment by probonopd** [comment]
That's actually a bad decision, since Ubuntu 14.04 is currently the oldest still-supported version and applications compiled on later versions will not be able to run on it. So Travis CI is doing the correct thing by offering the oldest still-supported release to compile stuff on.

Compiling on 16.04 (and possibly on 18.04 soon) does not offer any advantage to users of 16.04 or 18.04 but comes at a disadvantage of users of older versions of the distribution that will be excluded from running the compiled application.

**Comment by ReinerBforartists** [comment]
I see your point. But this doesn't really help us when the software itself does not even compile at this "oldest supported" version anymore. Linux has its drawback exactly in this area. Windows 7 will always run software made for Windows 7. But not Linux. You will run into the dependency hell sooner or later with older versions. And with Ubuntu 14 you do. It does not support the required Python version anymore.

To have compatibility with old Linux versions like Ubuntu 14 would have been a bonus. A luxury problem. At the moment we struggle to have a working linux build at all.

**Comment by ktotheoz** [comment]
Unfortunately AppVeyor has a time limitation of 1 hour per build, leading to problems when additionally calling install_deps.sh. 
So, I'm currently reintegrating travis.yml, which is already building, with Ubuntu support for 14.04 and 16.04 (and experimental Mac).

In a latter step it will not be very hard to integrate AppImage support as well.

**Comment by probonopd** [comment]
> Linux has its drawback exactly in this area. Windows 7 or 10 will always run software made for Windows 7 or 10. Windows 10 even runs most of the Windows 7 software. But not Linux. 

Perhaps this is a misconception. Like on Windows, an application compiled on an _older_ version of the Linux stack will run on a _newer_ version of the Linux stack, _if bundled properly_. But not the other way around, an application will normally not run on _older_ versions of the OS than what it was compiled on (this is true not only for the Linux stack but also for other OSes).

**Comment by ReinerBforartists** [comment]
That's called forward compatibility. A Windows 10 software will not run at Windows 95. And a Ubuntu 18 software may not run at Ubuntu 14. Which is clear.

I talk about backwards compatibility. Windows 7 is now ten years old, and runs all Windows 7 software. And even Windows 10 runs still Windows 95 software.

Ubuntu has a new major version every year. And does not run some older versions anymore. As told, they skipped Python 3.4 at one point.

**Comment by probonopd** [comment]
> Ubuntu has a new major version every year. And does not run some older versions anymore. As told, they skipped Python 3.4 at one point. And when a software requires Python 3.4, then that was it. You are faster to simply install a newer Ubuntu version then.

...that's where my "if bundled properly" comes in: If you ship the version of Python that you need alongside your application, it will work just great. This is what may apps are doing, for example https://ultimaker.com/en/products/ultimaker-cura-software

**Comment by ReinerBforartists** [comment]
Okay :)

**Comment by ReinerBforartists** [comment]
This was a task for Bforartists 1. We don't fix anything for Bforartists 1 anymore. So closing.

**Comment by probonopd** [comment]
No, not just Bforartists 1, but __all__ Bforartists builds (no matter which branch or version), as can be seen here:

- https://travis-ci.org/Bforartists/Bforartists
- https://travis-ci.org/Bforartists/Bforartists/builds
- https://travis-ci.org/Bforartists/Bforartists/branches

**Comment by ReinerBforartists** [comment]
Okay, reopening.

The situation is still the same though. We won't fix anything for Bforartists 1 anymore. And we still don't have somebody to fix this issue here.

**Comment by probonopd** [comment]
Thanks. I'd be fine if it could be fixed for Bforartists 2 then.

**Comment by tkaczz** [comment]
Error message is clean
```The job exceeded the maximum time limit for jobs, and has been terminated.```

I see that everything is being built from source using blenders script. Many deps can be installed using simple pip3 install so that would cut build times.

**Comment by tsal** [comment]
I noticed the Xcode 8 builds were failing due to this:

```
/Users/travis/Library/Developer/Xcode/GPUToolsAgent.sock: tar format cannot archive socket
```

I'm thinking this might be a cache config issue? If you exclude /Users/travis/Library/* it might fix this issue.

I have access to a Mac and build tools, if you guys need someone who can (occasionally) help troubleshoot, let me know! I'm not a pro at making Mac apps, but I do develop cross-platform tools on one.

**Comment by ReinerBforartists** [comment]
Hi tsal,
Your help is more than welcome. Shall i add you as a collaborator? :)

**Comment by ReinerBforartists** [comment]
Closing this issue. We use Github actions now. And there Linux and Mac compiles fine. Just Windows is failing, since the project is too big for Github Actions.

**Comment by tsal** [comment]
Sorry I never replied! This whole year has been out of whack! I'm glad your switch fixed some of your issues

**Comment by ReinerBforartists** [comment]
Well, we switched from pest to cholera. For a while actions ran just fine. Then they changed something, and we never managed to fix that. Now everything is failing :D

**Comment by tsal** [comment]
> No problem. Well, we switched from pest to cholera. For a while actions ran just fine. Then they changed something, and we never managed to fix that. Now everything is failing :D

I think I see the issue. You're using a python script to output to STDOUT to create an environment variable. That was turned off due to security issues recently, and [a new method was provided](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable).

**Comment by ReinerBforartists** [comment]
Many thanks. Let's see if we can fix this :)
