### ISSUE TITLE
Sequencer - Turn on Snapping by default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2580]
# Request
![image](https://user-images.githubusercontent.com/35357409/128199076-94fb1cf5-19fd-4187-b0ff-f4b6e50736ff.png)

Turn on snapping by default. The blender devs have decided to keep this default turned off - but I can only see users go to the sequencer, turn it on, and then work. There was a vote by Tinwotin and 83% of his following (he's a big Sequencer dev) suggest to have it on by default. 

![image](https://user-images.githubusercontent.com/35357409/128199559-1f454361-d995-491c-8e90-b560aa4c58c9.png)

Maybe we can have this turned on by default.

**Comment by ReinerBforartists** [comment]
Blender and defaults ... ^^

Sure thing :)

**Comment by ReinerBforartists** [comment]
(Hopefully) Fixed in master
