### ISSUE TITLE
Sequencer - Context Menu - Fade Sub Menu - Needs Iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2581]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/128267277-628972ae-e35c-46c8-994b-a04717ab9a5d.png)

Right now when using the fade sub-menu in the context menu, there are no icons. This is also true of the fade entry in the header

![image](https://user-images.githubusercontent.com/35357409/128267333-3ad6e488-0a45-418e-ac5c-c7ff96ded200.png)

There are a few presets, but having them iconized would be nice. I am using these quite a bit.

**Comment by ReinerBforartists** [comment]
This is a python enum. And the other location of the sub menu is the add menu. I have done this before, i just need to find where ...

![faede](https://user-images.githubusercontent.com/13919702/136588666-28a87677-61e4-4a32-b35b-a342258e27d7.jpg)

![pytonenum](https://user-images.githubusercontent.com/13919702/136588684-0a553258-e44e-4487-a47f-5a862e2f228c.jpg)

**Comment by ReinerBforartists** [comment]
Hm. No idea where this was. No idea how to solve it. Unassigning.

**Comment by ReinerBforartists** [comment]
What goes on with Github here? The images are missing O_O

**Comment by ReinerBforartists** [comment]
Images are back. But i still have no idea how to solve this. Postponing for some other takers.

**Comment by ReinerBforartists** [comment]
Nope, haven't done this before. I have no idea how one could add an icon to this enum.

This requires a new strategy ...

**Comment by ReinerBforartists** [comment]
Geez, why did i always wanted to iconize the enum? XD

We haz python operators. And so we can make our own menu with python operators and icons ...

Fixed :)
![fade](https://user-images.githubusercontent.com/13919702/146914402-6c77a60c-ef39-43b8-948a-82c4a5e370ba.jpg)

**Comment by ReinerBforartists** [comment]
Ah wrong suffix in the class name ...
![wrongsuffix](https://user-images.githubusercontent.com/13919702/146979697-f88fe00a-6e23-4a86-b96e-5e702460bddd.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
