### ISSUE TITLE
Add the tabbed toolshelf to more editors

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2582]
# Feature Request
![bforartists_vUEj9WHxM1](https://user-images.githubusercontent.com/35357409/128267846-442dba99-9539-4e18-9dfe-1d57c153e0a6.png)

I have been loving the new tabbed toolshelf, excellent work there. 

I have been breaking the UX though since it's only available in the 3D view. When going to another editor, I am approached by the old way of using hidden menus behind hotkeys or header menus and submenus, with a lot of zigzag and repeat motion. I wish things could be as efficient as say using an exposed panel from the 3D View. 

Would it be possible to also add the tabbed toolshelf and operators to other editors?

Example, a tabbed toolshelf here:
- Sequencer
- Image Editor
- UV Editor
- Nodes Editors

Reason being... many operators could be on hand, but they are still hidden either in a right click context menu (double right click in the Sequencer) or in header entries and sub-menus (image editors). 

Also, some node operations like framing and others could be hotkey free if exposed to the tabs. 

This also will give more use to the toolshelf when there are no many operators (usually just the annotation and select tool, eg from the Node editors). 

### Important Notes
I know this is a general request, which would mean a lot of bigger code work, so this task is ONLY to confirm the direction of the toolshelf in the other editors. 

1. Should we add them? Is this part of the vision?
2. If so, then we can make tasks per editor and close this one.

**Comment by ReinerBforartists** [comment]
No bad idea at all. We should make this single tasks though. A task for every editor where this makes sense.

**Comment by Draise14** [comment]
Cool! So I think it's green then! Let's do it. I'll close this task and open new ones per editor.

**Comment by Draise14** [comment]
Relevent tasks:
#2586
