### ISSUE TITLE
3D View - Toolshelf - Panel is a pixel out

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2584]
![image](https://user-images.githubusercontent.com/35357409/128271597-ccf61c64-9cd5-4793-a8a2-bc0fb2b1d22d.png)

A user in the discord forum has pointed out that there is a pixel misalignment from the tabs and the panels. Minor nuisance, but noticed.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/128272134-9dd46bc6-0a6e-45d0-b20b-569e5237b0e0.png)

This is also true of the other side.

**Comment by Draise14** [comment]
Ah.. also true in Blender
![image](https://user-images.githubusercontent.com/35357409/128272290-4ef4b7d1-e994-4b60-8909-5bb8a4e928bc.png)

**Comment by ReinerBforartists** [comment]
It's a feature!
