### ISSUE TITLE
UV Editor - Add the tabbed toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2586]
# Request
![image](https://user-images.githubusercontent.com/35357409/128378394-5d1b3cb2-934b-4876-b1b9-318ab9830a72.png)

Add the tabbed toolshelf and header entries (common) to the toolshelf in the UV Editor. 

We already have some of the UV operators in the topbar editor, but it would be nice to have relevent ones in the toolshelf panels for a more consistent and streamlined workflow also. Also, not all operators are listed nor work from the topbar - the toolshelf tabs could solve that.

**Comment by ReinerBforartists** [comment]
Thanks for separating :)

You can add the task label to these issues. No need for the feature request label :)

**Comment by ReinerBforartists** [comment]
I haz the dumb -.-

How can i reuse the show_toolshelf_tabs prop in other editors? I thought i have implemented it in a way that transfers across the editors, like the tool settings, toolbar and sidebar toggles too. But narp ...

![chekcboxproblem](https://user-images.githubusercontent.com/13919702/141758912-7b2bfe44-fd1a-4a92-9b61-73b6a4675b0d.jpg)

**Comment by ReinerBforartists** [comment]
At least one little success here. But still no idea what to do with the prop.

![success](https://user-images.githubusercontent.com/13919702/141767440-14a6b656-1f8e-4aeb-8c9a-4ef6c1dff265.jpg)

**Comment by ReinerBforartists** [comment]
Then let's use an addonpref bool for now. Not enough brain left today to fix the prop issue at C level ...

Downside is of course then that this prop is global. And counts for all instances of the UV editor. But on the other hand, you don't need to save the startup file to make a change permanent. addonprefs is part of the preferences ...

![addonprefs](https://user-images.githubusercontent.com/13919702/141779141-01a019bd-fcad-4dd9-80f5-20a1985643c1.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/141835276-f10645e3-356d-4029-85e3-591bc84fd6a5.jpg)
