### ISSUE TITLE
Node Editors - Add tabbed toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2587]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/128380894-83f76cfa-5828-43c0-ab92-bdc616f84fdc.png)

Right now, direct commmon node commands are either in a context menu, or in a header. Sometimes you have to go into hidden menus to use them or resort to hotkeys (most have a hotkey, great). 

But maybe we could have them optional in a tabbed toolshelf also.

**Comment by ReinerBforartists** [comment]
Two tools still needs new icons .
![newicons](https://user-images.githubusercontent.com/13919702/141987965-6c03c60a-b8ef-4bce-afc0-2b0194146d32.jpg)
..

**Comment by ReinerBforartists** [comment]
Don't forget to tename node tools to frame tools.

**Comment by ReinerBforartists** [comment]
Fixed in master
![fixed](https://user-images.githubusercontent.com/13919702/142187855-946c41e3-5742-40b1-9bc6-b7ed0430237b.jpg)
