### ISSUE TITLE
Sequencer - Add tabbed toolshelf 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2588]
# Request
![image](https://user-images.githubusercontent.com/35357409/128381585-f2351644-9872-47a6-9bf6-92d07bc02a4b.png)

Currently, there are many many operators for the sequencer hidden away in right click (double click) menus, also in the headers - a tonne. These are used often, so having them also exposed to a top level would be very very useful. 

Relevent ones like the Add menu, Fade, some actions you can do with strips, etc. Even possibly markers for cameras and such - it could be a powerful animatic tool with these top level, where most editors and directors are used to top level buttons for these things. 

This may need some dynamic panels as there are 3 modes for the panels, with the preview, without preview, and fusion  but it would be very useful.

**Comment by ReinerBforartists** [comment]
Wow. The mixture of preview and sequencer window makes me really trouble here ...

**Comment by ReinerBforartists** [comment]
I run into an update problem with all the different strip types. I need to hover with the mouse over the tool shelf to change the toolset.

I fear we cannot put this content into the tabs.

![updateproblem](https://user-images.githubusercontent.com/13919702/142773096-9da9ff71-d060-4d38-84ff-9275123d0433.jpg)

**Comment by ReinerBforartists** [comment]
Okay, i guess this was it then. The add menu content contains things like Scene that we cannot put into the tool shelf. And just adding half of it doesn't make sense. The marker menu content imho doesn't deserve a tab entry neither. Not often enough used. So i call this task done.

@Draise14 we can always come back to this issue in case you have some further requests. The tabs now exists. Which was the main purpose of this task.

**Comment by Draise14** [comment]
Sure, sounds like a plan to me. Exposing even a few of these is a huge leap ahead. Thanks again! 

For consistency sake, the Marker menu is in header in all animation editors, so no worry there. 
Also, we usually have add menus to the right in the node editor, or in header menus - so also no worry there to add to this shelf. It is all consistent.
