### ISSUE TITLE
3D View - Object Types Visibility - "checkmark" left aligned toggles for legibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2591]
# Request
![image](https://user-images.githubusercontent.com/35357409/128385974-27da7322-b447-4977-a0e0-60985da76653.png)
The object types visibility panel has a bunch of toggles that are right aligned with text left aligned, which makes the reading a long X movement over the panel to line up the check mark to the text.

For legibility reasons, aligning the Y was the right move, but now aligning X with the toggles would also be nice to make it easier to see and read. 

So.. is it possible to shift the word column to the right of the toggles, and keep the toggles to the left?

**Comment by ReinerBforartists** [comment]
Not sure if we should really do this. In the outliner the toggles are also at the right.

**Comment by Draise14** [comment]
But we have visual rows and highlights in the outliner. Here we have no rows at the moment. This could be more consistent with how we treat check marks for the same reason. 

But if not it's ok. Maybe we can use iconography instead of/and use words?

**Comment by ReinerBforartists** [comment]
I will close this as won't fix. It would become inconsistent with the outliner when we put the toogles at the left.
