### ISSUE TITLE
Shader Editor - Differentiate the Principled Shader Icons to be more clear

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2592]
# Request
![image](https://user-images.githubusercontent.com/35357409/128387228-0e20083f-71a4-4ab8-9cb4-ed5997ea6547.png)

The principled icons, are.. a little abstract, so the hammer (mult-purpose) icon could be more clear (larger hammer?). Also, the principled volume icon could contain a could instead of a circle to differentiate them a bit more. 

1. Make hammer symbol larger, more evident, or minimize so it's just two rectangles instead of a hammer shape (minimize)
2. Make the principled volume have a cloud shape instead of a circle shape in the background to show a "volume".

**Comment by ReinerBforartists** [comment]
I thought i already have. The one is round the other square. A cloud will simply vanish under the hammer.

**Comment by Draise14** [comment]
Maybe the round sphere could be white instead, with a small gradient, make it "translucent".

**Comment by ReinerBforartists** [comment]
Gradients are tough with the current awkward icon creation system. I could recolor the hammer or the background.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/133880828-7a617ff8-f74e-4cb0-8a42-d45423755933.jpg)

**Comment by Draise14** [comment]
Thanks for this, immediate use really made a difference.
