### ISSUE TITLE
Toolbar - Misc Group - Differentiate the two search types of icons. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2593]
# Request
![unknown (5)](https://user-images.githubusercontent.com/35357409/128390829-b10bcb81-dfbd-41a0-b7eb-b242a853c3f4.png)

These two icons for the two methods of searching is a little confusing. Maybe one of these could have a plus sign or something to differentiate the two search methods.

**Comment by ReinerBforartists** [comment]
![fixed](https://user-images.githubusercontent.com/13919702/134210683-5a97368b-7aad-41b4-9af4-51035f439962.jpg)
