### ISSUE TITLE
Enhancements for systems with limited resources

### ISSUE THREAD

**Issue by chuuko** [Bforartists/Bforartists#26]
Blender has serious performance issues on older Intel Atom configurations. Material mode is slow as hell, the interface occasionally glitches and sometimes it crashes. In the terms of viewport rendering performance, a Windows-only proprietary 3D application under Wine beats Blender.
It would be good if a better rendering strategy is implemented or the interface is made less dependent on OpenGL.

**Comment by ReinerBforartists** [comment]
Hi chuuko, 

Thanks for the suggestion. But the goal of the fork is just to fix the UI and usability issues. We miss the manpower and knowledge to rewrite the Blender core. That's a task for the Blender developeres. And in fact they have already started to rewrite the viewport engine quite a few years ago. it's just not finished yet. The new render engine is called Eevee. It will ship with Blender 2.8 this year. This new viewport render engine will of course also find its way into Bforartists at one point.

The bad news for you is, it is still heavily dependant at OpenGL. And will not help you with your Atom chip. This is a very cheap and weak chip. And simply not designed and capable for heavy tasks like 3D graphics. 

Kind regards

Reiner
