### ISSUE TITLE
Global - Remove VX Library and integrate pre-made Asset Library from VX alternative

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2600]
# Request
![image](https://user-images.githubusercontent.com/35357409/128581146-da5e4315-3a4c-496b-940c-742622510c55.png)

I've seen a number of issues with VX addon lately, and we now have an asset library, which is a superior and easier UX. 

Maybe we can figure out a way to include a number of libraries already with the Asset Browser made from the VXmaterials? 

They already exist in a repository as blend file and marked assets, now it's just figuring out how to ship them and configure the default distro to start up with the libraries based on a dynamic %LOCAL% path where blender unpacks or is installed - or to unpack and install these files to a location with a install dialogue to help configure (and dynamically write the userpref to the custom install location). 

[https://github.com/don1138/blender-materials](https://github.com/don1138/blender-materials)

# Tasks
![image](https://user-images.githubusercontent.com/35357409/128582277-f15ff605-c35d-40ab-b331-ebc0b974e8cf.png)

- Include the blends with the download
- Add an install dialogue wizard to help automatically setup the libraries (maybe a separate download?)
- OR make a system that automatically sets the paths of the libraries to the local folder where it unzips or installs to setup the library.

**Comment by Draise14** [comment]
I guess this is more a task to figure out how to setup a library via python...

**Comment by ReinerBforartists** [comment]
I guess we wait what happens to the Materials Library VX addon. I expect that the blender developers will remove it once the asset library is working proper.

**Comment by ReinerBforartists** [comment]
Same problem here. The current incarnation of the asset browser does not allow to include asset libs that are active with the default installation from what i can see. And it is very unlikely to happen.

So what to do here? We can make it an asset lib, no question. But where to store then? And how can the user load it then?

**Comment by ReinerBforartists** [comment]
This will for a very long time not work. The asset browser develops into the completely wrong direction. As usual when Blender developers tries to invent the wheel from scratch. And this means we will keep the addon alive, since we cannot move our libs to the asset browser. And so this task has become obsolete.

Closing.
