### ISSUE TITLE
Asset Browser - Add icons to new Context Menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2612]
# Request
![image](https://user-images.githubusercontent.com/35357409/128711700-24863dcf-8e11-4bd9-8471-a0cadb82c9b9.png)

They added a new context menu to the Asset Browser, so in the next merge next week these would need some iconography to be added.

**Comment by ReinerBforartists** [comment]
How do you call this? A right click does nothing here.

**Comment by ReinerBforartists** [comment]
The Miscellaneous menu is also missing an icon.

![miscmenu](https://user-images.githubusercontent.com/13919702/128820451-1e04230d-3cce-409a-9536-71959e5f3210.jpg)

**Comment by Draise14** [comment]
Has to be merged in next week. I've postponed it.

**Comment by ReinerBforartists** [comment]
Ah, no wonder can't i find it ^^

**Comment by ReinerBforartists** [comment]
Still no right click menu to fix. See https://github.com/Bforartists/Bforartists/issues/2621

**Comment by Draise14** [comment]
Can't find the context menu either, in BFA keymap. 

But in the blender hotkeymap, it's there. So the hotkey map may need updating. 
![image](https://user-images.githubusercontent.com/35357409/129774986-14f9964f-90ef-492e-8745-e30dc274a802.png)

**Comment by ReinerBforartists** [comment]
Okay, so an update to the keymap is required first. Thanks for checking :)

**Comment by Draise14** [comment]
Should that be another task?

**Comment by ReinerBforartists** [comment]
Is :)

**Comment by Draise14** [comment]
Speedy Gonzalez!

**Comment by ReinerBforartists** [comment]
Already fixed. Closing.

![aassetbrowser](https://user-images.githubusercontent.com/13919702/141163772-6a63a2ea-4344-4fb7-a851-b6ac669db0b1.jpg)
