### ISSUE TITLE
Keymap, odd double entries

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2617]
While working at #2601 i stumbled across this double entry. One mode line should be enough here. 

Check if Blender produces equal results. Report. Else ignore.

![doubles](https://user-images.githubusercontent.com/13919702/128844443-1469ec22-b660-4e14-971f-513bd6824114.jpg)

**Comment by ReinerBforartists** [comment]
Not to reproduce or to provoke in Blender. 

Let's keep an eye at it.

**Comment by ReinerBforartists** [comment]
Still a problem, but not to reproduce in Blender. I guess this is the same game than with the mode hotkeys. With the modes I also need to keep a closer eye at it every time i do changes at the keymap. Ah the fun ...

**Comment by Draise14** [comment]
I hate the keymap manager system. I wish it would just detect conflicts. It would be X2 better...

**Comment by ReinerBforartists** [comment]
It is completely broken, it doesn't even detect hotkeys that are onboard ^^
