### ISSUE TITLE
Asset browser and pose library

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2621]
Unexpected changes remains unexpected. And as usual not to find out how to use it. Blender UI design ...

The asset browser has once more changed its interface. There is just the pose library left. But you cannot insert anything to it.

How is this meant to work?

> SHA-1: 05879f2c36e9e59ca62011aafb266a7b8dd64656
> 
> * File/Asset Browser: Select/Activate File on Right Click for Context Menu
> 
> Right clicking would spawn the context menu under the cursor, but some
> operators would actually act on the active asset/file which wasn't
> the one clicked on.
> 
> When multiple files are selected and one of them is right-clicked on,
> selection is not changed to allow operations on multiple files. E.g.
> deletion.
> 
> This makes the File/Asset Browser match the Outliner (in behavior, not
> implementation).
> 
> For the right-click selection keymap:
> * The context menu still only spawns on W.
> * Bonus: Right click now does something, it actually selects files!
>   I could have done additional changes here to avoid this, but it seems
>   like a good addition.
> 
> This is also a better alternative to rB5edfde58fe60, which didn't work
> properly either. Using rename from the context menu would only work if
> the clicked on file was also active...
> 
> Differential Revision: https://developer.blender.org/D12065
> 
> Reviewed by: Campbell Barton

![poselib](https://user-images.githubusercontent.com/13919702/129475928-b807b35b-6b7d-4334-80de-ca5f22f11259.jpg)

**Comment by Draise14** [comment]
This is now the official version, but the other version is experimental. You may have to activate the experimental asset browser features to get the features we usually use.

**Comment by ReinerBforartists** [comment]
Well, i have activated it, and it does not help. And it's about the official part, not the experimental part. I have simply no idea how this pose library is meant to work and how to use it. 

Do you have an idea how one could add a pose to this library?

**Comment by Draise14** [comment]
Let me download and check out. This is in the current dev build? I am starting to be pre-upset that the old asset library is hidden away now.

**Comment by ReinerBforartists** [comment]
Mh, devbuild is one week behind. So next week :)

**Comment by Draise14** [comment]
Ok, testing

**Comment by Draise14** [comment]
![bforartists_7JCJ5TyiJF](https://user-images.githubusercontent.com/35357409/129775123-56705f11-81e8-4e3b-b326-cc1ea30666a3.png)

Oh thank god, the complete thing is still there. Might need to be activated as a BFA default. 

![bforartists_qKcUyoit7Y](https://user-images.githubusercontent.com/35357409/129775171-0eae8ee0-3be2-4f87-b947-b19032a61f63.png)

The pose library works from a panel and tab in the 3D View... AND in a misc tab in the asset browser.. and listed under "Animation"... a huge mess. You go to an armature pose mode, then pose, and it will save the pose in the library with a quick camera capture from workbench. 

![bforartists_sjP3dWItzQ](https://user-images.githubusercontent.com/35357409/129775222-71da2a96-71e5-42f6-91c1-52a11caa2249.png)
These should also be operators in the 3D View panel, and the dynamic buttons should/could also be in the asset browser, but they are bordering on being double entries for convenience. Should be customizable/toggle to show/hide?

So many sub-tasks can be made from this....

**Comment by ReinerBforartists** [comment]
What about throwing it out of the window? ^^

**Comment by Draise14** [comment]
lol! I can see it useful... just it's half baked..... "official" my armpit. It needs a lot of consistency work and maybe more evident tooltips and UX to make it a little more.. discoverable and intuitive.

**Comment by ReinerBforartists** [comment]
Yeah, half baked. We really need to wait until they declare it finished before we can do anything at it :)

**Comment by ReinerBforartists** [comment]
Okay, closing this one since the main question about the workflow is solved. Odd as usual, and not self explaining.

> Oh thank god, the complete thing is still there. Might need to be activated as a BFA default.

Better not. It is still in heavy change. That's why i have stopped documentation for it. We first need to wait that the work at the asset browser is declared as finished before we can really start to change things there.

Thanks for the help here :)
