### ISSUE TITLE
File Browser - Make Bookmarks default tab in default startup

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2625]
# Request
![image](https://user-images.githubusercontent.com/35357409/130090865-922bba0b-374f-446e-8382-072bdb36a985.png)

With the new asset browser updates.. there is a new tab.... And now the bookmark panels are not default. 

Make them default again? 

_I still don't know why they made the asset browser and the file browser the same "code" and group of hotkeys and essentially the same editor... when they are two different systems..._

**Comment by ReinerBforartists** [comment]
Where do you find this? My file browser still looks the old way.

![stilltheoldway](https://user-images.githubusercontent.com/13919702/130099981-25f63d6b-ac84-4d57-89cb-f03014f9f650.jpg)

**Comment by Draise14** [comment]
Ah, it only shows with the experimental asset browser on, which we had on by default earlier. Now it's off by default.

**Comment by ReinerBforartists** [comment]
Then let's close this report. We might come back to it at a later point when the asset browser is stable.
