### ISSUE TITLE
AUR needs updating

### ISSUE THREAD

**Issue by Chrispynutt** [Bforartists/Bforartists#2627]
Using an old version and does not currently build. https://aur.archlinux.org/packages/bforartists/
Please look into this thanks.

**Comment by naetherm** [comment]
Thanks for reporting. Will take care ASAP.

**Comment by Chrispynutt** [comment]
Here is the output from Pamac:
`Preparing...
Cloning bforartists build files...
Checking bforartists dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building bforartists...
==> Making package: bforartists 2.8.0-1 (Fri 20 Aug 2021 12:42:53 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v2.8.0.tar.gz
  -> Found usd_python.patch
  -> Found embree.patch
==> Validating source files with sha256sums...
    v2.8.0.tar.gz ... Passed
    usd_python.patch ... Passed
    embree.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v2.8.0.tar.gz with bsdtar
==> Starting prepare()...
Skipped patch 'build_files/cmake/Modules/FindEmbree.cmake'.
Skipped patch 'intern/cycles/blender/CMakeLists.txt'.
Skipped patch 'build_files/cmake/platform/platform_unix.cmake'.
Skipped patch 'source/blender/io/usd/CMakeLists.txt'.
==> Removing existing $pkgdir/ directory...
==> Starting build()...
loading initial cache file /var/tmp/pamac-build-chris/bforartists/src/Bforartists-2.8.0/build_files/cmake/config/blender_release.cmake
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- WITH_DRACO requires WITH_PYTHON_INSTALL to be ON, disabling WITH_DRACO for now
-- Found Git: /usr/bin/git (found version "2.32.0") 
-- Found JPEG: /usr/lib/libjpeg.so (found version "80") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.37") 
-- Found Freetype: /usr/lib/libfreetype.so (found version "2.10.4") 
-- Found PythonLibsUnix: /usr/lib/libpython3.9.so  
-- #define OPENEXR_VERSION_STRING "3.1.1"
-- Found OpenEXR: OPENEXR_HALF_LIBRARY-NOTFOUND;/usr/lib/libIex-3_1.so;OPENEXR_ILMIMF_LIBRARY-NOTFOUND;/usr/lib/libIlmThread-3_1.so;/usr/lib/libImath-3_1.so  
-- Found OpenJPEG: /usr/lib/libopenjp2.so  
-- Found TIFF: /usr/lib/libtiff.so (found version "4.3.0")  
-- Found OpenAL: /usr/lib/libopenal.so  
-- Found SDL2: /usr/lib/libSDL2.so  
-- Found SndFile: /usr/lib/libsndfile.so  
-- Found Fftw3: /usr/lib/libfftw3.so  
-- Found OpenCOLLADA: /usr/lib64/opencollada/libOpenCOLLADAStreamWriter.so;/usr/lib64/opencollada/libOpenCOLLADASaxFrameworkLoader.so;/usr/lib64/opencollada/libOpenCOLLADAFramework.so;/usr/lib64/opencollada/libOpenCOLLADABaseUtils.so;/usr/lib64/opencollada/libGeneratedSaxParser.so;/usr/lib64/opencollada/libMathMLSolver.so;/usr/lib64/opencollada/libbuffer.so;/usr/lib64/opencollada/libftoa.so;/usr/lib64/opencollada/libUTF.so  
-- Found PCRE: /usr/lib/libpcre.so  
-- Found XML2: /usr/lib/libxml2.so  
-- Found JeMalloc: /usr/lib/libjemalloc.so  
-- Found Spacenav: /usr/lib/libspnav.so  
-- Found OSL: /usr/lib/liboslcomp.so;/usr/lib/liboslexec.so;/usr/lib/liboslquery.so  
-- Found OpenVDB: /usr/lib/libopenvdb.so  
-- Found Blosc: /usr/lib/libblosc.so  
-- Could NOT find NanoVDB (missing: NANOVDB_INCLUDE_DIR) 
-- NanoVDB not found, disabling it
-- Could NOT find sse2neon (missing: SSE2NEON_INCLUDE_DIR) 
-- Found Alembic: /usr/lib/libAlembic.so  
-- Could NOT find USD (missing: USD_LIBRARY USD_INCLUDE_DIR) 
-- Found Boost: /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0") found components: filesystem regex thread date_time wave locale iostreams system 
-- Found PugiXML: /usr/lib/libpugixml.so  
-- Found OpenImageIO: /usr/lib/libOpenImageIO.so  
-- Found OpenColorIO: /usr/lib/libOpenColorIO.so;/usr/lib/libyaml-cpp.so;/usr/lib/libexpat.so;/usr/lib/libpystring.so (found suitable version "2.0.1", minimum required is "2.0.0") 
-- Found Embree: /usr/lib/libembree3.so (Required is at least version "3.8.0") 
-- Found OpenImageDenoise: /usr/lib/libOpenImageDenoise.so  
-- Found LLVM: /usr/lib/libLLVM-12.0.1.so  
-- Could NOT find Clang (missing: _CLANG_LIBRARIES) 
-- Clang not found
-- Found OpenSubdiv: /usr/lib/libosdGPU.so;/usr/lib/libosdCPU.so  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found TBB: /usr/lib/libtbb.so  
-- Found XR_OpenXR_SDK: /usr/lib/libopenxr_loader.so  
-- Found GMP: /usr/lib/libgmp.so  
-- Found Potrace: /usr/lib/libpotrace.so  
-- Could NOT find Haru (missing: HARU_LIBRARY HARU_INCLUDE_DIR) 
CMake Warning at build_files/cmake/platform/platform_unix.cmake:489 (message):
  Haru not found, disabling WITH_HARU
Call Stack (most recent call first):
  CMakeLists.txt:912 (include)


-- Found Threads: TRUE  
-- Found Jack: /usr/lib/libjack.so  
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Performing Test SUPPORT_NEON_BUILD
-- Performing Test SUPPORT_NEON_BUILD - Failed
-- Performing Test SUPPORT_SSE_BUILD
-- Performing Test SUPPORT_SSE_BUILD - Success
-- Performing Test SUPPORT_SSE2_BUILD
-- Performing Test SUPPORT_SSE2_BUILD - Success
-- SSE2 SIMD instructions enabled
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found GLEW: /usr/lib/libGLEW.so  
-- Performing Test C_WARN_ALL
-- Performing Test C_WARN_ALL - Success
-- Performing Test C_WARN_CAST_ALIGN
-- Performing Test C_WARN_CAST_ALIGN - Success
-- Performing Test C_WARN_ERROR_IMPLICIT_FUNCTION_DECLARATION
-- Performing Test C_WARN_ERROR_IMPLICIT_FUNCTION_DECLARATION - Success
-- Performing Test C_WARN_ERROR_RETURN_TYPE
-- Performing Test C_WARN_ERROR_RETURN_TYPE - Success
-- Performing Test C_WARN_ERROR_VLA
-- Performing Test C_WARN_ERROR_VLA - Success
-- Performing Test C_WARN_STRICT_PROTOTYPES
-- Performing Test C_WARN_STRICT_PROTOTYPES - Success
-- Performing Test C_WARN_MISSING_PROTOTYPES
-- Performing Test C_WARN_MISSING_PROTOTYPES - Success
-- Performing Test C_WARN_NO_CHAR_SUBSCRIPTS
-- Performing Test C_WARN_NO_CHAR_SUBSCRIPTS - Success
-- Performing Test C_WARN_NO_UNKNOWN_PRAGMAS
-- Performing Test C_WARN_NO_UNKNOWN_PRAGMAS - Success
-- Performing Test C_WARN_POINTER_ARITH
-- Performing Test C_WARN_POINTER_ARITH - Success
-- Performing Test C_WARN_UNUSED_PARAMETER
-- Performing Test C_WARN_UNUSED_PARAMETER - Success
-- Performing Test C_WARN_WRITE_STRINGS
-- Performing Test C_WARN_WRITE_STRINGS - Success
-- Performing Test C_WARN_LOGICAL_OP
-- Performing Test C_WARN_LOGICAL_OP - Success
-- Performing Test C_WARN_UNDEF
-- Performing Test C_WARN_UNDEF - Success
-- Performing Test C_WARN_INIT_SELF
-- Performing Test C_WARN_INIT_SELF - Success
-- Performing Test C_WARN_MISSING_INCLUDE_DIRS
-- Performing Test C_WARN_MISSING_INCLUDE_DIRS - Success
-- Performing Test C_WARN_NO_DIV_BY_ZERO
-- Performing Test C_WARN_NO_DIV_BY_ZERO - Success
-- Performing Test C_WARN_TYPE_LIMITS
-- Performing Test C_WARN_TYPE_LIMITS - Success
-- Performing Test C_WARN_FORMAT_SIGN
-- Performing Test C_WARN_FORMAT_SIGN - Success
-- Performing Test C_WARN_RESTRICT
-- Performing Test C_WARN_RESTRICT - Success
-- Performing Test C_WARN_NO_NULL
-- Performing Test C_WARN_NO_NULL - Success
-- Performing Test C_WARN_ABSOLUTE_VALUE
-- Performing Test C_WARN_ABSOLUTE_VALUE - Success
-- Performing Test C_WARN_UNINITIALIZED
-- Performing Test C_WARN_UNINITIALIZED - Success
-- Performing Test CXX_WARN_UNINITIALIZED
-- Performing Test CXX_WARN_UNINITIALIZED - Success
-- Performing Test C_WARN_REDUNDANT_DECLS
-- Performing Test C_WARN_REDUNDANT_DECLS - Success
-- Performing Test CXX_WARN_REDUNDANT_DECLS
-- Performing Test CXX_WARN_REDUNDANT_DECLS - Success
-- Performing Test C_WARN_SHADOW
-- Performing Test C_WARN_SHADOW - Success
-- Performing Test C_WARN_NO_ERROR_UNUSED_BUT_SET_VARIABLE
-- Performing Test C_WARN_NO_ERROR_UNUSED_BUT_SET_VARIABLE - Success
-- Performing Test CXX_WARN_ALL
-- Performing Test CXX_WARN_ALL - Success
-- Performing Test CXX_WARN_NO_INVALID_OFFSETOF
-- Performing Test CXX_WARN_NO_INVALID_OFFSETOF - Success
-- Performing Test CXX_WARN_NO_SIGN_COMPARE
-- Performing Test CXX_WARN_NO_SIGN_COMPARE - Success
-- Performing Test CXX_WARN_LOGICAL_OP
-- Performing Test CXX_WARN_LOGICAL_OP - Success
-- Performing Test CXX_WARN_INIT_SELF
-- Performing Test CXX_WARN_INIT_SELF - Success
-- Performing Test CXX_WARN_MISSING_INCLUDE_DIRS
-- Performing Test CXX_WARN_MISSING_INCLUDE_DIRS - Success
-- Performing Test CXX_WARN_NO_DIV_BY_ZERO
-- Performing Test CXX_WARN_NO_DIV_BY_ZERO - Success
-- Performing Test CXX_WARN_TYPE_LIMITS
-- Performing Test CXX_WARN_TYPE_LIMITS - Success
-- Performing Test CXX_WARN_ERROR_RETURN_TYPE
-- Performing Test CXX_WARN_ERROR_RETURN_TYPE - Success
-- Performing Test CXX_WARN_NO_CHAR_SUBSCRIPTS
-- Performing Test CXX_WARN_NO_CHAR_SUBSCRIPTS - Success
-- Performing Test CXX_WARN_NO_UNKNOWN_PRAGMAS
-- Performing Test CXX_WARN_NO_UNKNOWN_PRAGMAS - Success
-- Performing Test CXX_WARN_POINTER_ARITH
-- Performing Test CXX_WARN_POINTER_ARITH - Success
-- Performing Test CXX_WARN_UNUSED_PARAMETER
-- Performing Test CXX_WARN_UNUSED_PARAMETER - Success
-- Performing Test CXX_WARN_WRITE_STRINGS
-- Performing Test CXX_WARN_WRITE_STRINGS - Success
-- Performing Test CXX_WARN_UNDEF
-- Performing Test CXX_WARN_UNDEF - Success
-- Performing Test CXX_WARN_FORMAT_SIGN
-- Performing Test CXX_WARN_FORMAT_SIGN - Success
-- Performing Test CXX_WARN_RESTRICT
-- Performing Test CXX_WARN_RESTRICT - Success
-- Performing Test CXX_WARN_MISSING_DECLARATIONS
-- Performing Test CXX_WARN_MISSING_DECLARATIONS - Success
-- Performing Test C_WARN_IMPLICIT_FALLTHROUGH
-- Performing Test C_WARN_IMPLICIT_FALLTHROUGH - Success
-- Performing Test CXX_WARN_IMPLICIT_FALLTHROUGH
-- Performing Test CXX_WARN_IMPLICIT_FALLTHROUGH - Success
-- Performing Test C_WARN_NO_DEPRECATED_DECLARATIONS
-- Performing Test C_WARN_NO_DEPRECATED_DECLARATIONS - Success
-- Performing Test C_WARN_NO_UNUSED_PARAMETER
-- Performing Test C_WARN_NO_UNUSED_PARAMETER - Success
-- Performing Test C_WARN_NO_UNUSED_FUNCTION
-- Performing Test C_WARN_NO_UNUSED_FUNCTION - Success
-- Performing Test C_WARN_NO_TYPE_LIMITS
-- Performing Test C_WARN_NO_TYPE_LIMITS - Success
-- Performing Test C_WARN_NO_INT_IN_BOOL_CONTEXT
-- Performing Test C_WARN_NO_INT_IN_BOOL_CONTEXT - Success
-- Performing Test C_WARN_NO_FORMAT
-- Performing Test C_WARN_NO_FORMAT - Failed
-- Unsupported CFLAG: -Wno-format
-- Performing Test C_WARN_NO_SWITCH
-- Performing Test C_WARN_NO_SWITCH - Success
-- Performing Test C_WARN_NO_UNUSED_VARIABLE
-- Performing Test C_WARN_NO_UNUSED_VARIABLE - Success
-- Performing Test CXX_WARN_NO_CLASS_MEMACCESS
-- Performing Test CXX_WARN_NO_CLASS_MEMACCESS - Success
-- Performing Test CXX_WARN_NO_COMMENT
-- Performing Test CXX_WARN_NO_COMMENT - Success
-- Performing Test CXX_WARN_NO_UNUSED_TYPEDEFS
-- Performing Test CXX_WARN_NO_UNUSED_TYPEDEFS - Success
-- Performing Test CXX_WARN_NO_UNUSED_VARIABLE
-- Performing Test CXX_WARN_NO_UNUSED_VARIABLE - Success
-- Performing Test C_WARN_NO_IMPLICIT_FALLTHROUGH
-- Performing Test C_WARN_NO_IMPLICIT_FALLTHROUGH - Success
-- numpy found at '/usr/lib64/python3.9/site-packages'
-- numpy include files found at '/usr/lib64/python3.9/site-packages/numpy/core/include'
-- Performing Test C_MACRO_PREFIX_MAP
-- Performing Test C_MACRO_PREFIX_MAP - Success
-- Performing Test CXX_MACRO_PREFIX_MAP
-- Performing Test CXX_MACRO_PREFIX_MAP - Success
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- CUDA compiler not found, disabling WITH_CYCLES_CUDA_BINARIES
-- Performing Test CXX_HAS_SSE
-- Performing Test CXX_HAS_SSE - Success
-- Performing Test CXX_HAS_AVX
-- Performing Test CXX_HAS_AVX - Success
-- Performing Test CXX_HAS_AVX2
-- Performing Test CXX_HAS_AVX2 - Success
-- Could NOT find OptiX (missing: OPTIX_INCLUDE_DIR) 
-- OptiX not found, disabling it from Cycles
-- Performing Test _has_cxxflag_float_conversion
-- Performing Test _has_cxxflag_float_conversion - Success
-- Performing Test _has_cxxflag_double_promotion
-- Performing Test _has_cxxflag_double_promotion - Success
-- Performing Test _has_no_error_unused_macros
-- Performing Test _has_no_error_unused_macros - Success
-- Tests: Using Python executable: /usr/bin/python3.9
-- Disabling render tests because tests folder does not exist at /var/tmp/pamac-build-chris/bforartists/src/Bforartists-2.8.0/../lib/tests
-- RPM Build Not Found (rpmbuild). RPM generation will not be available
-- C Compiler:   "GNU"
-- C++ Compiler: "GNU"

Bforartists Configuration
=====================

  Build Options:
  - WITH_ALEMBIC                ON
  - WITH_BULLET                 ON
  - WITH_CLANG                  OFF
  - WITH_CYCLES                 ON
  - WITH_FFTW3                  ON
  - WITH_FREESTYLE              ON
  - WITH_GMP                    ON
  - WITH_HARU                   OFF
  - WITH_IK_ITASC               ON
  - WITH_IK_SOLVER              ON
  - WITH_INPUT_NDOF             ON
  - WITH_INTERNATIONAL          ON
  - WITH_OPENCOLLADA            ON
  - WITH_OPENCOLORIO            ON
  - WITH_OPENIMAGEDENOISE       ON
  - WITH_OPENVDB                ON
  - WITH_POTRACE                ON
  - WITH_PUGIXML                ON
  - WITH_QUADRIFLOW             ON
  - WITH_TBB                    ON
  - WITH_USD                    OFF
  - WITH_XR_OPENXR              ON

  Compiler Options:
  - WITH_BUILDINFO              ON
  - WITH_OPENMP                 ON

  System Options:
  - WITH_INSTALL_PORTABLE       OFF
  - WITH_MEM_JEMALLOC           ON
  - WITH_MEM_VALGRIND           OFF
  - WITH_SYSTEM_GLEW            ON
  - WITH_X11_ALPHA              ON
  - WITH_X11_XF86VMODE          ON
  - WITH_X11_XFIXES             ON
  - WITH_X11_XINPUT             ON

  Image Formats:
  - WITH_IMAGE_CINEON           ON
  - WITH_IMAGE_DDS              ON
  - WITH_IMAGE_HDR              ON
  - WITH_IMAGE_OPENEXR          ON
  - WITH_IMAGE_OPENJPEG         ON
  - WITH_IMAGE_TIFF             ON
  - WITH_OPENIMAGEIO            ON

  Audio:
  - WITH_CODEC_AVI              ON
  - WITH_CODEC_FFMPEG           ON
  - WITH_CODEC_SNDFILE          ON
  - WITH_JACK                   ON
  - WITH_JACK_DYNLOAD           OFF
  - WITH_OPENAL                 ON
  - WITH_SDL                    ON
  - WITH_SDL_DYNLOAD            OFF

  Compression:
  - WITH_LZMA                   ON
  - WITH_LZO                    ON

  Python:
  - WITH_PYTHON_INSTALL         OFF
  - WITH_PYTHON_INSTALL_NUMPY   
  - WITH_PYTHON_MODULE          OFF
  - WITH_PYTHON_SAFETY          OFF

  Modifiers:
  - WITH_MOD_FLUID              ON
  - WITH_MOD_OCEANSIM           ON
  - WITH_MOD_REMESH             ON

  OpenGL:
  - WITH_GL_EGL                 OFF
  - WITH_GL_PROFILE_ES20        OFF
  - WITH_GLEW_ES                OFF

  
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENEXR_HALF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /var/tmp/pamac-build-chris/bforartists/src/Bforartists-2.8.0/intern/cycles/kernel/osl
    linked by target "cycles_render" in directory /var/tmp/pamac-build-chris/bforartists/src/Bforartists-2.8.0/intern/cycles/render
OPENEXR_ILMIMF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /var/tmp/pamac-build-chris/bforartists/src/Bforartists-2.8.0/intern/cycles/kernel/osl
    linked by target "cycles_render" in directory /var/tmp/pamac-build-chris/bforartists/src/Bforartists-2.8.0/intern/cycles/render

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_ALEMBIC_HDF5


CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERROR: A failure occurred in build().
    Aborting...

`

**Comment by floris-max** [comment]
Hi!
Please help me to install on Manjaro 20.2.1
the following is the issued I have on the installation log
 Thanks

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENEXR_HALF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/kernel/osl
    linked by target "cycles_render" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/render
OPENEXR_ILMIMF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/kernel/osl
    linked by target "cycles_render" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/render

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_ALEMBIC_HDF5


CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...

**Comment by ReinerBforartists** [comment]
Hi floris-max. I have separated the issue into its own task called Maranjo 20.2.1 installation issues #2864

Please let's continue the discussion in the new thread.

**Comment by Draise14** [comment]
@floris-max any luck?

**Comment by iyadahmed** [comment]
are those fixed now?

**Comment by ReinerBforartists** [comment]
Not that i know of. Mnaether has no time for this anymore, unfortunately. So i fear this will remain unfixed.

**Comment by ReinerBforartists** [comment]
We have a duplicate with the same error message here: Maranjo 20.2.1 installation issues #2864

**Comment by ReinerBforartists** [comment]
Shall we finally close this one? I doubt that it will ever be fixed ...

**Comment by Draise14** [comment]
Yeah.. I think so.
