### ISSUE TITLE
Play hotkey conflict with apply knife tool

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2629]
We have spacebar to play. But we also have spacebar to apply knife tool. And every once in a while it starts to play. Which means the widgets disappear ...

**Comment by ReinerBforartists** [comment]
What about making play ctrl + spacebar?

**Comment by Draise14** [comment]
Apply should be Enter or click to confirm like everywhere else. I never could get used to spacebar to apply...

**Comment by ReinerBforartists** [comment]
That's not this easy. And spacebar is in reach. So it does make sense. I am just not happy that i start to play the anmiation all the time ^^

**Comment by ReinerBforartists** [comment]
Shift p would be free

**Comment by Draise14** [comment]
With character animation, all the time. Though yes, it does trigger automatically. But don't you have to be in object mode to make it trigger?

**Comment by Draise14** [comment]
Maybe the solution is assigning the play to only the 3D view Object and Pose mode. Also in the 3D editors and VSE. But nowhere else.we could have the Space key free for search and add node, filter or other operators in other editors. The space for play is a global hotkey but that can be removed and placed per editor and per mode

**Comment by ReinerBforartists** [comment]
No, triggers in edit mode too. And to turn it off in edit mode might introduce other conflicts.

Seems that we have an unsolveable conflict here. The knife modal map is not to modify without bad result, the play hotkey is not to modify without bad result.

So be it. Closing. Won't fix.

**Comment by ReinerBforartists** [comment]
Ah, can't do this, we need a solution. 

The default play hotkey in nearly all other software is ctlr p. But this is occupied by parent already.

So i will change the play hotkey to shift spacebar.

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by Draise14** [comment]
Which software uses CTRL P?! 

That is not handy at all...

**Comment by ReinerBforartists** [comment]
Unity :)

**Comment by Draise14** [comment]
Ah ok.. it's not the defacto animation software but a game engine...... but I see there is no standard:

Maya: `Alt+V`
Max: `/`
Cascaduer: `X`
Cinema 4D: `F8`
Houdini: `Up Arrow`

`CTRL+Space` and `SHIFT+Space` does make sense for forward and backward playback. 

Using two hands on a keyboard to playback is really not cool, you don't want to remove hand from mouse to press CTRL+P to preview animation. You can't reach left CTRL then P with one hand.

**Comment by ReinerBforartists** [comment]
This is what we nearly have now. Backward is ctrl shift space though. The Blender default :)
