### ISSUE TITLE
Timeline Header - Add missing operator "Animation Cancel" or "Loop back and stop". 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2631]
# Feature request
![image](https://user-images.githubusercontent.com/35357409/130338469-1bd2eba1-1792-4e59-8da5-488734faad7b.png)
There is a the `screen.animation_cancel`operator hidden from the GUI at the moment. It should be in the timeline and be exposed. 

Functionality: When animation is playing, it will loop back to last frame and stop. It's like "jump to cue". We have a philosophy to expose to the GUI all operators, so this one was hidden - till now! 

Here is the code Stev put in, with a suggested icon and position in the timeline. Line 55. 
![image](https://user-images.githubusercontent.com/35357409/130338474-877290b9-2730-4fdc-9ed6-0e1bdbd74a6f.png)

Here is a video on the idea (has two ideas, but this tracker only focuses on the hidden operator)
[https://youtu.be/p9rhQ9AZA_w](https://youtu.be/p9rhQ9AZA_w)

## Notes
We could put this in between the playback buttons instead of at the end. 
_I had no idea this existed till he pointed it out, should be in the UI; would have saved me a tonne of time._

**Comment by ReinerBforartists** [comment]
Interesting catch.

**Comment by ReinerBforartists** [comment]
Fixed in master
