### ISSUE TITLE
Numeric input with the new transform tools

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2633]
The new transform tools works different for transform when it comes to the numeric input. The old blender way was for example to press R for rotate, then type in a value.

With the new tools that we use you need to activate the hotkey, grab the widget. Hold down the mouse. And THEN you can type in numbers. With your left hand. since your right hand is occupied with holding down the mouse.

There is of course the adjust last operator panel where you can adjust the transformation in the needed way. But it is not as elegant to use.

I think we had this issue at the table before. It's the choice between pest and cholera. The new tools has the widgets, the old tools the better access to the numeric input. And we have removed the old transform tools from the UI.

Ideas? Thoughts?

**Comment by ReinerBforartists** [comment]
We could map the old transform methods to ctrl + w, ctrl e and ctrl r. The only conflict is set rotation mode in pose mode. But this does imho not deserve its own hotkey.

And i guess we should add the old method back to the UI then. Not a happy bunny here ...


![ctrl](https://user-images.githubusercontent.com/13919702/130593350-c3e529e1-9dde-433a-823f-4fb5bb7a1aaa.jpg)

**Comment by iyadahmed** [comment]
I agree on using the old method, that is in Blender activate tool then type number

**Comment by Draise14** [comment]
Do not... For the love of all things good... Revert to the old method of transforming as a default... The mode of WER on widget is standard in software like max, Maya, trueSpace, unreal, unity, modo, Houdini,. Cinema4D and others. With that out of the way... 

This is a legacy operator, you can just put it in the legacy sub group in a header. 

The CTRL + transform hotkey is an ok solution though.

But I personally haven't had too much issue with numeric input and the widgets. I never use the numpad with the right hand, the hand never leaves the mouse unless writing strings. I've used widgets on WER and numeric input for... 2 years now? No issue. 

Maybe the hotkeys can help and exposing the legacy operator in the legacy menu would be useful...but personally I think it's not important to worry about it. Maybe the hotkeys will help for blender heads, but they use blender hotkeys mostly anyway. 

If necessary, put in the hotkeys with CTRL + WER and remove the rotation type. The CTRL+R in armature pose mode are usually set by rig anyway. Not in animation.

**Comment by ReinerBforartists** [comment]
I don't want to revert to the old method. WER will remain mapped to the new toolset. I just stumbled across a situation where it would have been faster to use the old method :)

> The CTRL + transform hotkey is an ok solution though.

That's what i aim at :)

**Comment by Draise14** [comment]
Just found a use case where this is very important. This task shows the issue: #1809 

_WER is used to activate the transform modals from the toolshelf - but they don't exist in the Weight Paint pose transform operators, only the legacy operators work. So in order to pose in weight paint mode, you'd need to use the legacy transform operators. These as a default or exposed in the UI somewhere to assign a hotkey will be important. (CTRL+WER sounds great)_

**Comment by ReinerBforartists** [comment]
hunh, ctrl r is also the loop cut tool ...

**Comment by ReinerBforartists** [comment]
For now the hotkeys. Menu entries follows. Working at a showstopper bug first.

**Comment by ReinerBforartists** [comment]
And finally fixed in master

Move is not to convince to show the correct hotkey though. Dat keymap manager ...


![keymapmanager](https://user-images.githubusercontent.com/13919702/133884106-a66a601d-c50f-4b63-b034-0d712f4dadee.jpg)
