### ISSUE TITLE
Object viewport display settings in the viewport

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2638]
It's always a hunt to find the viewport display settings to activate for example the wireframe display. This should be at the top of the UI somewhere. 

I know the header is already pretty crowded. But maybe we can expose this panel as a dropdown in the header. Or in our toolbar editor. This would save quite a few clicks and searching. 

![viewportdisplay](https://user-images.githubusercontent.com/13919702/131327514-17f2e020-e751-477c-b873-5a2e604b14c7.jpg)

**Comment by ReinerBforartists** [comment]
Works just fine. I'll add it to the misc toolbar.

![VIEWPORT](https://user-images.githubusercontent.com/13919702/141165386-72d85da4-f1fa-4107-a362-3c4c61c75b81.jpg)

**Comment by ReinerBforartists** [comment]
:'(
![nonetype](https://user-images.githubusercontent.com/13919702/141167424-94f926aa-df07-4d49-9eff-d62a265f3a36.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![viewportfixed](https://user-images.githubusercontent.com/13919702/141168145-12f6f5a5-3283-42ca-a2e8-aa010bb8639b.jpg)

**Comment by Draise14** [comment]
OH MY! WHAT A GREAT FEATURE!!!!

**Comment by ReinerBforartists** [comment]
Yeah, a real time saver, especially with bones :)
