### ISSUE TITLE
Add menu entry for legacy set 3d cursor operator

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2639]
I can't remember what happened to the lock 3d cursor feature at the moment. But we should have a look if we can resurrect it. I always place the cursor accidentally around while polygon modeling. Alt is select edge loop ...

**Comment by ReinerBforartists** [comment]
The reason why i haven't reimplemented is of course still true. But in reality i move the 3d cursor around while modeling quite often ...

**Comment by ReinerBforartists** [comment]
Is Ctrl alt right mouse an option? Or is this then too complicated to grab?

**Comment by ReinerBforartists** [comment]
Do we need this hotkey at all? It is an old operator! Set 3d cursor is a tool in the tool shelf already. Top UI.

This operator has no menu entry yet. So i would vote to remove the hotkey, and add the operator into a legacy menu in the navigation menu.

**Comment by Draise14** [comment]
Eh.. I don't use SHIFT+Rmb at all. Usually just static place with ALT+Rmb. The hotkey/operator to lock the cursor I would consider.. rare enough to just keep in the UI. Remove the hotkey. 

This can free it up for the cool rotate canvas and scroll timeline hotkeys of the Grease Pencil tools.

**Comment by ReinerBforartists** [comment]
Just that we don't misunderstand each other, it's not longer about reimplementing the lock 3d cursor, but about to remove the old way to set the 3d cursor, which is alt rmb. We have navigation bound to rmb. And when you are at loop selecting you hold down alt. And so you quickly accidentally pull the 3d cursor around.

**Comment by Draise14** [comment]
Ah ok. 

I use ALT+RMB to set cursor almost constantly. Specially when in layout mode and widget offset mode (widget to cursor). 

I could not live without. 

SHIFT+RMB I can live without. That is transform cursor drag.... Like drag it. A double entry. 

ALT+LMB is loop select no? 

I don't see any conflict... Unless it's custom?

Loop select should be on LMB anyway.

**Comment by ReinerBforartists** [comment]
The conflict is as told that we have mapped world rotate to the right mouse. And when i am at loop select then i accidentally place the 3d cursor around every now and then.

So you would want to keep it as it is? The alt rmb hotkey has no menu entry yet ...

**Comment by ReinerBforartists** [comment]
Made it a task: Loop select with double click like in Maya #2642

**Comment by ReinerBforartists** [comment]
Resurrected the original task to reimplement lock 3d cursor.

**Comment by ReinerBforartists** [comment]
Hm, where to add it. View menu seems to be the best place. There we have center Cursor and Frame all already.

**Comment by ReinerBforartists** [comment]
Okay. Legacy menu makes more sense to mark this as a legacy operator.

**Comment by ReinerBforartists** [comment]
Now the UV editor. And i think there was also a cursor in the Movie Clip Editor.

**Comment by ReinerBforartists** [comment]
Oops, tool also shows in image editor with mask mode. Tooltip needs adjustment ...

**Comment by ReinerBforartists** [comment]
Fixed in master

![legacy1](https://user-images.githubusercontent.com/13919702/133659001-c73fd754-78f3-49a7-84ce-740824548655.jpg)
![legacy2](https://user-images.githubusercontent.com/13919702/133659013-cf59a3ab-cd94-47b4-88bd-eb33e0bc9f72.jpg)
![legacy3](https://user-images.githubusercontent.com/13919702/133659027-b8e35209-4084-4f2b-9c65-16864e0e3e68.jpg)

**Comment by ReinerBforartists** [comment]
Ah, the one in the image editor should just show in mask mode. 

Reopen ...

**Comment by ReinerBforartists** [comment]
Even more complicated since the view menu is the same than in the UV editor. And here we have the 3d cursor tool shelf tool .

**Comment by ReinerBforartists** [comment]
I think now we have it. Closing.
