### ISSUE TITLE
Hard crash when using Autocomplete in Text Editor

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#264]
I've been trying to use the **Autocomplete** with BFA 1.0.0 in W10, but every time I use it on "**bpy.**" it crashes, hard. 

Autocompletion is working fine on other systems (well the list is not populated other than what is in the document). Is there something wrong with my setup to not have the **Text Editor autocomplete** list show up and crash on the "**bpy.**"? 

![powershell_2018-08-23_16-22-04](https://user-images.githubusercontent.com/35357409/44553066-fd315d00-a6f1-11e8-9b72-9842581d2b5c.png)

**Comment by ReinerBforartists** [comment]
Not that i know of. But i can confirm the crash at Windows 7 too. Interesting catch.

**Comment by ReinerBforartists** [comment]
Doesn't happen in BFA2 anymore. Closing.

We can open a new issue in case it comes back.
