### ISSUE TITLE
Materials library vx - error at preview our lib content

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2640]
I have run into this twice now. Sometimes the material preview fails with an error. I have yet to find out why. In a new scene it works then. Saving and reloading the scene also makes the preview working again. So no idea how to reproduce it.

![applyfails](https://user-images.githubusercontent.com/13919702/131462469-c796c9e5-09fd-4d32-a454-08bcafa46ff4.jpg)

**Comment by iyadahmed** [comment]
Should be fixed with merge

https://developer.blender.org/D12214

**Comment by ReinerBforartists** [comment]
I doubt that they will ever approve it. Blender 3.0 comes with the asset browser. And then it's a matter of time until they throw out the materials library vx addon ...

Well, we have it fixed in our master. But as you can see, it still strikes back. I still search for a way to reproduce ...

**Comment by ReinerBforartists** [comment]
Hm did we kill our improvement here with a merge? Let's wait until this update comes back to us.

**Comment by iyadahmed** [comment]
> Hm did we kill our improvement here with a merge? Let's wait until this update comes back to us.

Ah not sure, we can check code maybe there's another load method needs to be edited

**Comment by iyadahmed** [comment]
Glanced at patch I think it should fix so yeah maybe merge will fix it

**Comment by iyadahmed** [comment]
Hmm looking at master here it seems to be already fixed

![image](https://user-images.githubusercontent.com/25552173/131473837-732d391a-5d51-4f80-9806-40c6ab2646c5.jpeg)

**Comment by ReinerBforartists** [comment]
Yeah so it must be something else. It reamins curious. I will have a second look how i managed to get this error message ...

**Comment by iyadahmed** [comment]
Maybe it is an old build or old addon folder

**Comment by ReinerBforartists** [comment]
Maybe. I work since three weeks at a scene. And so i haven't deleted the bforartists folder in the appdata directory for three weeks to keep my setup and the addons intact. But i remember that the fix came in earlier.

Either ways. Not to reproduce so far. But i think i have found yet another error XD

Open matlib, select no library, but click immediately at the Preview or Apply button ... BAM. Unexpected since such kind of errors should be catched while development already. But the error itself is logical. Nonetype means we have no library selected yet. And so the apply button cannot apply anything.

Maintaining third party addons was and is a nightmare ^^

![error](https://user-images.githubusercontent.com/13919702/131489424-37b7b4b5-f74a-4e73-8f28-ba67cf10a630.jpg)

**Comment by iyadahmed** [comment]
Oh 😅

**Comment by iyadahmed** [comment]
this seems to be a different issue than what the patch fixed
NonType object, should be checked before access

**Comment by ReinerBforartists** [comment]
NoneType problem is indeed a different problem. And i still think that the first issue is too. But i can't reproduce it. 

My dilemma is still that i don't want to maintian addons at all. This is killing us.

**Comment by iyadahmed** [comment]
Agree maybe we can just leave it, no need to maintain 3rd party addons, the previous issue was an exception and it merged to Blender anyway

**Comment by ReinerBforartists** [comment]
What we could do is to report it to Blender. It is one of the included addons. And so they might be interested to fix it.

**Comment by iyadahmed** [comment]
> What we could do is to report it to Blender. It is one of the included addons. And so they might be interested to fix it.

Exactly

**Comment by ReinerBforartists** [comment]
I have reported it :)

https://developer.blender.org/T91115

For the initial issue, i still search for a way to reproduce it. So let's postpone this issue ...

**Comment by iyadahmed** [comment]
The first issue won't reproduce I believe because it was fixed

**Comment by iyadahmed** [comment]
Ah right

**Comment by ReinerBforartists** [comment]
Closing this one. Not to reproduce anymore.
