### ISSUE TITLE
Clone Brush in texture paint - set 3d cursor happens with ctrl + lmb

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2643]
In texture paint you set the 3d cursor to define the clone area with holding down ctrl + lmb. This is inconsistent mapping. And not to discover by the user. We still don't have a tooltip for the new tools in the tool shelf.

What is also missing is the set 3d cursor button. But i guess this is for good reason. Since placing the cursor with ctrl+lmb places the cursor at the surface. 

Solution: use the same mapping to place the 3d cursor than in other modes. Alt RMB

![placecursor](https://user-images.githubusercontent.com/13919702/131795578-f50b58e9-9c58-42a2-9ba8-23d821ef8480.jpg)

**Comment by ReinerBforartists** [comment]
Hmhmhm. And again i stumble across the missing tooltip, which is reported since months but still not fixed. I would have loved to write a hint about the hotkey into it ...

![clonebrush](https://user-images.githubusercontent.com/13919702/132084750-4199a2e1-1643-430b-b768-67beed18b392.jpg)

**Comment by ReinerBforartists** [comment]
I don't know why but my inner self cries while thinking about to remove this hotkey. We could produce lots of unhappy users with that. It's part of the clone tool, the goal is not to set the cursor. Even when this is what technically happens. The goal is to mark the area to clone. And this is in other graphics software indeed ctrl + lmb. And not alt rmb.

Ideas?

**Comment by Draise14** [comment]
Ehm.... I would make the tooltip hotkey agnostic and use the same cursor placement as the rest of the UI. And.. well if there is no conflict, maybe both hotkeys for same functionality is still ok, despite the inconsistency - this is a feature flaw from the source...  

Why did the keymap_data build fail? 

**Tooltip Suggestion:**
"The Clone brush copies the texture at the the 3D Cursor position. 
Place cursor in the target area to clone paint the texture."

**Comment by ReinerBforartists** [comment]
Yeah, i think to keep both too. Maybe that's the way to go.

The data_build failed because i haven't found a way to add the tools from the new tooshelf, wasn't able to implement flag states, wasn't able to implement old tools, nothing is documented, and because the whole keymap manager is one big fubar. Starts with that the files in the keymap_data folder are config files for config files. And doesn't really end with that every report about the keymap is ignored hard since even Blender developers are lost with it.

**Comment by ReinerBforartists** [comment]
Hmm, maybe we can place a hint in the footer? But no idea how the tooltips that displays there for edit mode tools are called.

![footertooltip](https://user-images.githubusercontent.com/13919702/132635925-5d50b24d-1707-4d28-8bd6-00bbf48fabe9.jpg)

**Comment by ReinerBforartists** [comment]
We have a hotkey conflict with alt right mouse. It's the stencil brush control. So we cannot map the functionality to it. Even nicer, i can't even find the builtin_brush.Clone, nor the modal map for it.

Did i mention that the keymap manager is fucked up beyond any repair, also known as fubar? :)

This task is not to fulfill. Closing.

**Comment by ReinerBforartists** [comment]
Hm. Let's have a look at the tooltips ...

**Comment by ReinerBforartists** [comment]
Nope. Not even the Blender keymap shows the added tooltip.

Time to let go ...

![noway](https://user-images.githubusercontent.com/13919702/132839936-5d2b5d2b-f61d-4abc-a6e0-c486a420ec4b.jpg)
