### ISSUE TITLE
Brush images set for painting and sculpting

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2646]
A brush system is just as good as its brushes. Every good paint software has it. Gimp, Krita, Photoshop etc. .Blender has still no set of default brushes for sculpting and painting. Just the standard round one. And so do we.

We should add a set once the asset library is open for other content besides the pose lib. Cracks, blobs, semitransparent, etc. .  This is the task to create this set. 

For licensing reasons it is best to create our own set. But i am open to open source alternatives.

**Comment by Draise14** [comment]
In the Blend Swap site there are a few CC0 packs. 

https://www.blendswap.com/blends/tag/brush

Maybe they can be a good base. The other is replicate the Krista brush defaults pack as that too is opensource to a degree, though it would be more like mimicry for inspiration.

**Comment by Draise14** [comment]
Here is another CC0 texture pack. 4.7 gigs to pick and choose from.

https://www.blendernation.com/2019/03/11/4-7-gb-of-cc0-textures-for-everyone/

**Comment by ReinerBforartists** [comment]
Thanks Draise. This is definitely useful once the asset browser is in place  :)

**Comment by ReinerBforartists** [comment]
Just as a note, i would prefer not to include CC0 content from external sources. CC0 usually requires at least to name the author. And may conflict with the gpl under some circumstances. Ah, licenses ...

**Comment by Draise14** [comment]
Ah ok. From what I've read only CC-BY requires linking to name. CC0 is like public domain.

**Comment by ReinerBforartists** [comment]
Hm, wasn't it the other way around? :D 

Best is not to have to deal with the licenses at all ^^

**Comment by Draise14** [comment]
But you are right. Best to make them from scratch than to risk anything.

**Comment by Draise14** [comment]
Images can now be linked and overridden and officially stored as assets now.

**Comment by Draise14** [comment]
Ah wait, I am mistaken. This is the extended experimental browser that can mark images. 
![image](https://user-images.githubusercontent.com/35357409/174424572-18b1364b-bce1-42a8-8dbc-7d85e70526f5.png)

**Comment by Draise14** [comment]
With the new brush panel, we could include a lot of brushes and still have a good system. Do we still need to wait till we get these into assets?

**Comment by ReinerBforartists** [comment]
Your decision :)

**Comment by Draise14** [comment]
I think to do this, we would need an addon that appends the brushes - since they still can't be listed in the asset browser. But we could build the brush pack in design and "assets" till the brush asset system is ready in Blender 4.0.0 or 4.1.0. Then we would hit the ground running before Blender does.

**Comment by Draise14** [comment]
This task is too big, since we need brushes for different modes, object types and more - and/or only inbuilt consistency for brush icons. So I will close and make new ones for 4.1.0
