### ISSUE TITLE
Addon Defaults - Activate "Mesh: Snap Utilities Line" by default. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2647]
# Request
![image](https://user-images.githubusercontent.com/35357409/132101794-22d0d201-bbe0-4a90-bea8-ca95b9a8b7d1.png)
The Snap Utilities Line addon has a edge drawing tool with snapping that is really good. It has pre-highlight when activated (Knife tool doesn't), and the viewport drawing is really clear and useful. Also, the confirming is Enter like everything else, or Esc to leave. No conflict with Space. It also has intersecting lines between multiple faces, can be used to fill faces from drawing, and.. overall snapping when needed. 

A user on Twitter recommended the default addon be activated by default. 

## Reason
This is a good poly draw method for some cases. 

- The Blender Knife tool has a buggy pre-highlight on first use (doesn't activate, so you're clicking in the dark)
- Incremental Snapping is hard with the Knife tool, if not impossible
- Space to confirm the knife tool sometimes conflicts with space to place, this addon doesn't have any conflict.
- It's a default addon included with the repository. 

I would say it's a nice one on to have on for the toolshel on by default - a bit easier than using the Knife sometimes, and useful due to it's face forming and incremental snapping. 

**Notes:** 
There is some double use with the Knife tool, though it has it's nuances. There is no icon conflict though. 
ESC is.. confirm unfortunatley, like.. leave mode. It doesn't revert like the knife tool.

**Comment by ReinerBforartists** [comment]
Thanks for the suggestion. I'll look into it. It can take a while though :)

**Comment by ReinerBforartists** [comment]
I had a look at it now. And i can see why the Blender developers did not activate it by default. I share their reasoning in this regards.

This addon allows you easily to create unwanted non manifold geometry. It also doesn't really fit to the rest of the official addons with its esc to apply the changes. And we have already a knife tool activated.

So the idea was nice. But please understand that i don't want to put this burden onto our shoulders.

**Comment by Draise14** [comment]
Sure, no problem. It is a bit of a double entry. Both with knife tool and poly build tool.
