### ISSUE TITLE
Animation Editors - Improve tooltip for "Sync Visible Range"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2648]
# Feature Request
![A2UzyczmKM](https://user-images.githubusercontent.com/35357409/132103296-90f40dc8-3ceb-4ee8-93b6-9cb7e0a19c88.gif)

When animating with multiple editors, the frame range usually is assyncopated by default, meaning navigating the timelines between animation editors, the VSE and more is... a hassle. Only recently did I know that they can be synced between the editors in the workspace. 

I think this is a pretty nice feature when animating, not obvious unless you turn it on in all editors that need to be synced, and it would be great to have them synced as a default. I wish I knew this from earlier. 

**Task**
- Turn on the Synced Visible Range as a default
- Improve the tooltip to show that the toggle works only when turned on between multiple editors. 

## Reason
- You have to turn it on in both editors to know that it works, or on in all editors it should be toggled. If it were on by default, it would be a given, then when you find the tick box, you turn it off, and then desired unlinked editor would be true. 
- Having it toggled on from off in on editor feel useless, nothing happens, because I have to toggle the other editor also. The tooltip could be improved to explain that. 

# Alternative Task
Improve only the tooltip to say that it only syncs when this toggle is turned on in all editors that want to be synced. 
![image](https://user-images.githubusercontent.com/35357409/132103445-68726d21-724c-4b3e-8a0a-105d5abba703.png)

"Syncronizes the visibily  timeline range with other time-based editors if they too have the Sync Visible Range toggled on."

**Comment by ReinerBforartists** [comment]
I have thought about this issue now. Syncing the editors by default has some drawbacks . You might want to have the timeline zoomed out, but zoom in in the dope sheet for example. And it costs a bit more performance to have them activated. Neglible for sure, but nevertheless. So i think the current default is the better default.

We could talk about to make the sync button more prominent. But it already is in the options. And i don't want to put it into the header really. You don't click it every five seconds. But just when you need it. 

Remains the task to improve the tooltips.

**Comment by ReinerBforartists** [comment]
Fixed in master
