### ISSUE TITLE
Improve Matcaps

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2650]
We have quite a few matcaps available. But i found most of them distracting and not really useful. Maybe we can add a few more useful matcaps. 

Source of inspiration: https://pixologic.com/zbrush/downloadcenter/library/

![matcaps](https://user-images.githubusercontent.com/13919702/132124555-8d016e52-85aa-4785-8d55-3b6e66abe277.jpg)

**Comment by ReinerBforartists** [comment]
Files are in release\datafiles\studiolights\matcap, and they are in exr format

**Comment by ReinerBforartists** [comment]
Quick test, simply recolored the toon matcap ...

![quicktest](https://user-images.githubusercontent.com/13919702/132133679-8348f94c-bbda-40c7-af69-cb72967b004d.jpg)

**Comment by iyadahmed** [comment]
This repo can help too, but not sure it we can use directly because of license 

https://github.com/nidorx/matcaps

**Comment by ReinerBforartists** [comment]
Thanks Iyad. Ah, this repo is a shame. It is plain illegal since it grabs images from unknown sources, without proper licensing nor proper permission. We might use them as a source of inspiration. But this makes it impossible to include them. 

I start to realize that the best method is really to create our own matcaps from scratch. Then the licensing is clear.

**Comment by iyadahmed** [comment]
> Thanks Iyad. Ah, this repo is a shame. It is plain illegal since it grabs images from unknown sources, without proper licensing nor proper permission. We might use them as a source of inspiration. But this makes it impossible to include them. 
> 
> 
> 
> I start to realize that the best method is really to create our own matcaps from scratch. Then the licensing is clear.

Ah right inspiration it is

**Comment by ReinerBforartists** [comment]
First step is done ...

Not sure how much matcaps i will really do. I have found around 50 matcaps that are of interest, and am at recreating the look. I will upload the matcaps plus blend files into the file repo once done. 

![firstmatcap](https://user-images.githubusercontent.com/13919702/132247724-bb49372d-3e45-43d0-8e83-223329faa9e5.jpg)

**Comment by ReinerBforartists** [comment]
Green glass

![greenglass](https://user-images.githubusercontent.com/13919702/132302721-64b4efdd-3acd-45c3-a962-6cd9a43dd81a.jpg)

**Comment by ReinerBforartists** [comment]
Harder than thought. I end in spending a day or more at each matcap ...

**Comment by ReinerBforartists** [comment]
Fixed in master. Ten new matcaps. I think that these ten matcaps are a good complement. But for now i don't want to add more really. One matcap eats one mb.

There were some interesting matcaps that i wanted to recreate. But i failed at it. As told, not this easy as it looks ...

Updating the manual and the file repo now.

![newmatcaps](https://user-images.githubusercontent.com/13919702/132501326-434d2e6f-8fb3-4695-a488-bcb8b6ed7f77.jpg)

![morematcaps](https://user-images.githubusercontent.com/13919702/132501437-8dc1cb8b-46f0-4538-9d80-92eed9469ade.jpg)
