### ISSUE TITLE
Update the mini lightlib assets to collections

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2655]
Once the asset browser is fully functional we should migrate the light library from the mini lightlib into the asset browser. Then remove the addon from the repo.

![minilightlib](https://user-images.githubusercontent.com/13919702/132636418-fa0a827a-fdce-4100-8535-8f9d171faa6d.jpg)

**Comment by ReinerBforartists** [comment]
Hm. The current incarnation of the asset browser does not allow to include asset libs that are active with the default installation from what i can see.

So what to do here?

**Comment by ReinerBforartists** [comment]
Hm, the asset lib could be part of the startup.blend. Which is the current scene. But we need different libs. Which makes things complicated.

But one step after another. First let's turn this into an asset lib. And then do some experiments with it.

**Comment by ReinerBforartists** [comment]
Wow, this asset browser is really frustrating to work with. No way to add a default custom library path. No way to manage asset files from within the asset browser. No way to work with the startup.blend. Since then these assets all end in the file that you want to produce. No way to drop assets to the exact center of the scene. And so on. Sheesh, what did they do the last five years here? This is all how a asset browser should not be -.-

**Comment by Draise14** [comment]
Yeah. It's still incredibly raw. 

I find the only way to use it is in experimental full mode and with collections, but there is a bug when adding custom thumbnails to collections.

**Comment by ReinerBforartists** [comment]
Okay. We cannot add this to the asset lib since there is no way to define an external default asset lib and no way to store the assets into the startup.blend. The asset browser is a pure user driven experience as it is now. And this means we need to live with our addon for a bit longer.

So for now it's more than time to redo the lib as collections. And have a look that it also works with Eevee.

As a second step, we could of course create an asset library that the user then can load. Question is, where to install/store it then. Hmmhmm, this is even worth a question at blender developers.

**Comment by iyadahmed** [comment]
> Okay. We cannot add this to the asset lib since there is no way to define an external default asset lib and no way to store the assets into the startup.blend. The asset browser is a pure user driven experience as it is now. And this means we need to live with our addon for a bit longer.
> 
> So for now it's more than time to redo the lib as collections. And have a look that it also works with Eevee.
> 
> As a second step, we could of course create an asset library that the user then can load. Question is, where to install/store it then. Hmmhmm, this is even worth a question at blender developers.

I think we can use this to load assets on startup or creating new blend files
https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.load_post

**Comment by ReinerBforartists** [comment]
Interesting find. Bookmarked. Thanks :)

I don't see though how this could help with the asset libraries. Could you make an example? 

Best is to make a new task for it ...

**Comment by ReinerBforartists** [comment]
Hmm, eevee would require a complete new library. Not really keen to do that ...

**Comment by ReinerBforartists** [comment]
Updated the libs to work with collections now. 

The downside is, collections comes in acticated, no matter in what state you save it. But are easier to handle than the empties that i had in use before.

![fixed](https://user-images.githubusercontent.com/13919702/147240334-85dbf3b5-8e47-495c-ba6a-608d0ef3d7b7.jpg)

**Comment by ReinerBforartists** [comment]
> > Okay. We cannot add this to the asset lib since there is no way to define an external default asset lib and no way to store the assets into the startup.blend. The asset browser is a pure user driven experience as it is now. And this means we need to live with our addon for a bit longer.
> > So for now it's more than time to redo the lib as collections. And have a look that it also works with Eevee.
> > As a second step, we could of course create an asset library that the user then can load. Question is, where to install/store it then. Hmmhmm, this is even worth a question at blender developers.
> 
> I think we can use this to load assets on startup or creating new blend files https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.load_post

I have made it a task here: bpy.app.handlers to load a default asset library #2832
