### ISSUE TITLE
3d view sidebar - view - quad view options - hide greyed out content, indent, add triangle button

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2662]
We hide, we don't grey out. Hide not used content.

These three props are dependant of each other. First unticked makes the other two grey. Second unticked makes the third grey. So it's a bit complicated with the indentation. But we should do it. Not sure how to deal with the triangle button then though that indicates hidden content. We will see.

![quadview](https://user-images.githubusercontent.com/13919702/132995265-084bedf7-1a10-4fc1-813d-08877285eb74.jpg)

**Comment by ReinerBforartists** [comment]
Triangle buttons would add confusion in this area. So just indent.

Fixed in master

![quadview](https://user-images.githubusercontent.com/13919702/132996849-fc9c313a-19ca-42d7-a3db-e98d5c871b6c.png)

**Comment by iyadahmed** [comment]
> Triangle buttons would add confusion in this area. So just indent.
> 
> 
> 
> Fixed in master
> 
> 
> 
> ![quadview](https://user-images.githubusercontent.com/13919702/132996849-fc9c313a-19ca-42d7-a3db-e98d5c871b6c.png)
> 
> 
> 
> 

Ah not sure it it looks good 😅

**Comment by ReinerBforartists** [comment]
Do you want a change? Suggestions? :)

**Comment by ReinerBforartists** [comment]
Okay, let's revert it :'3

**Comment by ReinerBforartists** [comment]
Reverted

**Comment by iyadahmed** [comment]
> Do you want a change? Suggestions? :)

Ah yeah it didn't look very good with indentation I believe 😄
But it is reverted now

**Comment by ReinerBforartists** [comment]
Sometimes i'm in conflict with myself. Since sometimes the inconsistent solution is the better one ...

Thanks for poking :)

**Comment by iyadahmed** [comment]
No problem 😄
