### ISSUE TITLE
Top UI entry for Apply and Shade

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2665]
Apply is one of those essentials that needs a top UI entry. We should enable it by default in the toolbar.

Also to think of is if we want to readd the hotkey to call the menu under the mouse.

**Comment by Draise14** [comment]
I have this with my personal default, so good call. I do use these often.

**Comment by ReinerBforartists** [comment]
I have extended it to shade too. A very often used action. And it's just two buttons.

**Comment by ReinerBforartists** [comment]
Fixed in master
![fided](https://user-images.githubusercontent.com/13919702/133822303-96f5ea5d-dec7-475e-a521-18fa90cca3bd.jpg)

**Comment by ReinerBforartists** [comment]
Ah, overlooked join. And i want to split up the apply buttons even more.

**Comment by ReinerBforartists** [comment]
Fixed in master
