### ISSUE TITLE
VSE - Add Pan Presets (a UX and UI Patch rejected by Blender devs)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2667]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/133627774-ab6a8103-ed1f-4ad4-8475-a8fb558c26b7.png)

This patch by Tintwotin was rejected by the blender devs, but I find it a really good UX for sound in the VSE. 

[https://developer.blender.org/D12114](https://developer.blender.org/D12114)

What it does is it adds presets or indicators to sound panning or position of sound strips. 

Could we alternatively add this to the GUI of Bforartists? _Maybe this will encourage Tintwotin to work with us, since we are open to his UI and UX suggestions for the VSE and probably the script editor. He does some amazing UI and UX features and code - often shut down by Blender devs. It's a tall shot, but it's a gesture and also a good UX for sound panning_

**Comment by ReinerBforartists** [comment]
You know my problem with such things, we need to maintain it then. But yeah, why not. Doesn't look too complicated :)

But which one? There is more than one diff in this discussion. And could this also be done by an addon? I would prefer it.

**Comment by Draise14** [comment]
Ah ok, another Bforartists addon to make. Yeah, the UI may need some refining.

**Comment by Draise14** [comment]
I think now that this addon would be very niche - and Tintwotin made files that could be available for someone who wants to get in. Working sound in 5.1 with surround in the VSE still is.. a very isolated use case, we don't even have VU meters. So.. I think I changed my mind here and will retract this request. 

Relevant files that could "patch" to get surround sound presets:
https://github.com/tin2tin/surround_preset_ui
