### ISSUE TITLE
3D View - Pose Mode - Improve Breakdown, Push and Relax legacy icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2669]
> # (OLD) Feature Request
>  
> Move the Breakdown, Push and Relax tools up a level. Right now they are used all the time in animation, but you have to go into a sub menu over and over and over again. 
> 
> They also don't have a preset hotkey, so default is the toolshelf. Best to have them top level. 

![image](https://user-images.githubusercontent.com/35357409/134025264-c8eb6f22-7a91-4b35-be81-c6c03d66443e.png)

# **Alternate Request**
Maybe we can change this task to improve the icons of the legacy pose icons? They are exposed top level already, just there is no connection with the modal operators hidden away; and the icons, though cute, need to be a bit more explicit. 

Legacy icons are as A and B with a colour of one symbol (the character). 
The pose operators action is between A and B is the C. So the symbol should be between two points to be more destinctive. 

Maybe it can be just a "bone arc": with the colour to categorize (same), an arc to show point A and B, and the rotation of the bone with it's position implying what it's doing - instead of a small character which is hard to understand what is happening.

**Comment by ReinerBforartists** [comment]
You mean ungroup them?

**Comment by ReinerBforartists** [comment]
Mh, isn't that the in-betweens?

If even i would go much further anyways, and offer an option to display all tool shelf tools ungrouped. I am just not really happy to do changes in the tool shelf in general. This can make us big trouble with the merges.

![inbetweens](https://user-images.githubusercontent.com/13919702/133827835-f475bdc7-9ae3-41f1-bbc1-5a5556b2608c.jpg)

**Comment by Draise14** [comment]
Question... Are these double entries? What are the differences?

**Comment by ReinerBforartists** [comment]
These are the legacy tools :)

**Comment by Draise14** [comment]
Ah ok.. Hm... they seem to do exactly the same thing, just one is modal, the other is not. 

Ok.. 

**Problem:**
- It's confusing to know which to use first as a UX, legacy or modal?
- The model version being hidden away feels like they must be secondary
- The icons of the legacy ones are hard to differentiate or read (still can't memorize which is which after animating a few dozen or more hours with them). I resort to the tooltip. 

# **Alternate Request**
Maybe we can change this task to improve the icons of the legacy pose icons? They are exposed top level already, just there is no connection with the modal operators hidden away; and the icons, though cute, need to be a bit more explicit. 

Legacy icons are as A and B with a colour of one symbol (the character). 
The pose operators action is between A and B is the C. So the symbol should be between two points to be more destinctive. 

Maybe it can be just a "bone arc": with the colour to categorize (same), an arc to show point A and B, and the rotation of the bone with it's position implying what it's doing - instead of a small character which is hard to understand what is happening. 

_I will change the task title._

**Comment by ReinerBforartists** [comment]
Hm. I'm a bit lost how to make these icons more explicit. It was hard enough to find different icons for this at all.

**Comment by Draise14** [comment]
I'll draw up some ideas.i had my GPU spazzout from bad electricity. Hope it's ok. But will upload soon

**Comment by ReinerBforartists** [comment]
Take your time. Doesn't run away :)

**Comment by Draise14** [comment]
![bforartists_3TmVcioik9](https://user-images.githubusercontent.com/35357409/134049720-a5f158d9-6b69-4599-949d-a4537b6892db.png)
![bforartists_srROMTUkpN](https://user-images.githubusercontent.com/35357409/134049723-8d8286cc-4200-4a33-887b-51f33a984937.png)

Here is one idea, instead of a character, just use a single bone or two bones - and use something like the graphs used from Blender. Similar colour scheme. 

Example, use the bone as what's happening and the arc to show the animation symbolism - the A-B arc and symbols to show what it's doing. Colour from what we have, the bone as the "character" and the symbolism could clarify it more. 

If we do want to build off blender - I would make the icons of Blender have a bit more silhouette language since it's mostly lineart and you still have to read them. Not great iconography there. 

Or.. maybe fusion the character into the graphs somehow. 

I'd have to sketch more, there are 3 more operators than the modal ones.

**Comment by ReinerBforartists** [comment]
> EDIT we could also fall back to the Blender icons for it. Maybe the better idea since then it is consistent.

Meow?

**Comment by Draise14** [comment]
Blender default icons on Legacy is not great. It's lineart, not clear also, but some of the concepts or symbolism has the right idea. There is not enough silhouette.

**Comment by Draise14** [comment]
Yeah, making the legacy icons more explicit.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/135127984-cf6fd5c1-cfa4-4f25-867e-cc1afc7c4df4.jpg)
