### ISSUE TITLE
Toolbar - Search icons needs differentiation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2678]
#Feature Request
![image](https://user-images.githubusercontent.com/35357409/134083076-7c14f01b-9b6b-478c-b346-89d773c69f53.png)

The two search icons may need some refinement, as I'm not sure which is which.

**Comment by ReinerBforartists** [comment]
Duplicate. This task already exists here: https://github.com/Bforartists/Bforartists/issues/2593
