### ISSUE TITLE
Scale BB in tools panel has no icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#269]
**Is your feature request related to a problem? Please describe.**
Currently in the Pose mode of an armature, the Transform panel under the Tools tab has the BB Scale button without an icon - also it doesn't work with a good default (start's at 0 or collapses to 0 from the toolshelf). 

**Describe the solution you'd like**
It would be nice to have an icon on the BB Bone scale button

**Describe alternatives you've considered**
- Add Icon
- Change default value to 1 upon activation. 

**Additional context**
![bforartists_2018-08-31_14-19-02](https://user-images.githubusercontent.com/35357409/44932527-6127d700-ad2b-11e8-882a-3ef0f0a4bdc9.png)

**Comment by ReinerBforartists** [comment]
Nothing to fix in BFA2 since the tool shelf is completely different now. Closing.
