### ISSUE TITLE
Geometry Nodes - default to legacy till 3.0 official release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2691]
The new fields attributes system of Geometry Nodes is really a huge UX improvement, but at it's current state it's half baked. It's still missing many features. 

The legacy system of Geometry Nodes which is relatively feature complete and included as "experimental". For some reason Blender decided to make the standing version as the experimental when the fields is at the development stage of things. 

# Request
Can we turn ON the legacy system in the dev builds per default till Blender 3.0 is official? 

This would be a default User Pref configuration. 

OR add a notice in the editor somewhere that says that the legacy is feature complete and available as an experimental feature?

### Pro
The devbuilds is like a rolling release and the majority of the GN support in the community is for the legacy system. To keep the devbuilds still production relevant and feature complete, it would be best to keep them as the default. 

When the new fields system is ready both in Blender and Bforartists, then we can switch over. This includes complete documentation on release. 

### Con
The issue here is that.. to get the new experimental attributes fields you have turn OFF the legacy from the experimental menu. Doesn't make much sense... It's weird either way.

**Comment by ReinerBforartists** [comment]
Half baked features in Blender? Nothing new :D

And i would suggest to wait a few more weeks. I am pretty sure that the next weeks will bring the missing bits. In the end we have no influence in that regards, sorry. This would be yet another fork :)
