### ISSUE TITLE
VSE - Preview - assign W E R hotkeys to the tool shelf tools

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2709]
Currently the W E  R hotkeys calls the old transform tools. We use the hotkeys for the new tool system.

![assigntotools](https://user-images.githubusercontent.com/13919702/136826835-59aa3293-b07f-4a2e-9454-23e9071f7e76.jpg)

**Comment by ReinerBforartists** [comment]
Reported https://github.com/Bforartists/Bforartists/issues/2709

**Comment by Draise14** [comment]
Ok, seems to be working now. Will be able to commit this one!

**Comment by ReinerBforartists** [comment]
The Blender bug is now resolved. Means we should be able to finish this task.

**Comment by Draise14** [comment]
Huzzah!

**Comment by ReinerBforartists** [comment]
> 
> They will work, but they won't be listed in the hotkey map editor..
> 

Now they do. But now they don't show at the tooltip. And when you right click then it says assign shortcut. Ah, the fun ...

Will try to reproduce it with blender and report it.


![troubled](https://github.com/Bforartists/Bforartists/assets/13919702/1a507632-ee5e-4a94-a3bc-98808acedbe1)

**Comment by ReinerBforartists** [comment]
Hm, does it make sense to change the keymap at this point? I think i will unassign until the new issue is resolved.

**Comment by ReinerBforartists** [comment]
Reported: https://projects.blender.org/blender/blender/issues/118190
