### ISSUE TITLE
AVCodecContext::me_method is not defined

### ISSUE THREAD

**Issue by kungfooman** [Bforartists/Bforartists#271]
**Describe the bug**

I wanna build bforartists, but I couldnt find any build process description for Windows. So I just followed common sense. Im using these libs, downloaded via:

`svn export https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14/`

Then I generated the solution with cmake-gui for VS2017 64bit

**Screenshots, Example Files**

![bforartistsbug](https://user-images.githubusercontent.com/5236548/44956814-24dead00-aeca-11e8-9980-fb2fb41836f2.png)

**Desktop (please complete the following information):**

Windows 10

**Additional context**

current head https://github.com/Bforartists/Bforartists/commit/0aa1ea2c159f4a5960bd26b5ace6ed1139a5628d

**Comment by Draise14** [comment]
https://www.bforartists.de/wiki/building

This will have some info. We have documented the process with VS2013 and soon once we finesse the VS2017 work flow update these docs. 

You may have a couple of libs or dependencies missing.

**Comment by ReinerBforartists** [comment]
Hm, interesting. The error messages could point to everything. Isn't the first error that a lib cannot be loaded? Maybe your svn is corrupted or has downloaded incomplete. The lib repository is pretty big.

The vc14  libs are correct for VS 2017. I have just today compiled a branch with the newest lib versions with VS 2017 under Windows 7. So it's not the libs and not VS from what i can say.

My guess is that you miss some things that you need to install at your PC first. For example, you need both Python versions, 2.7 and 3.6 (should also work with 3.7). Just curious does Cmake run fine and error free?

Draise already pointed to the Bforartists tutorial. It's made for Bforartists 1 and VS 2013. But should work similar with VS 2017. You could also look for a Blender tutorial. Everything works pretty similar.

**Comment by ReinerBforartists** [comment]
Just to be sure, switching to master, and compiling it at the moment ...

**Comment by ReinerBforartists** [comment]
ARGH!

**Comment by ReinerBforartists** [comment]
I have now merged the sync_blender_master branch into our master. That's the branch where we merge the newest Blender code regularly in our code.

This ends the old Bforartists 1.0.0 line. Everything from now on is Bforartists 2 preparation and development.

Checked, and compiled with blender_full.cmake settings and cuda at Windows 7 64 bit with VS 17 and the newest libs, and it compiles and the binary works without visible errors.

Warning! Don't compile with Jack. Jack is not longer available . Blender devs have removed it. But the blender_full.cmake in the build_files/cmake/config folder still lists it as on required.

And you can ignore the warning about Cuda in Cmake. I have compiled it with the newest Cuda version 9.2, which throws an error in the cmake configuration. 9.0 is the latest official supported version. It compiles fine though, and Cuda works in Bforartists.

Issue should be resolved now by this merge. Closing.
