### ISSUE TITLE
Grease Pencil - Draw Mode - Add common operators to tabbed toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2713]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/137163001-eecab7e6-0a31-46db-bc3c-e50ad2c91d56.png)

Would be nice to have this menu and some of the common operators exposed to a top level. 

- Interpolate
- Animation
- Show/Hide
- Cleanup

**Comment by ReinerBforartists** [comment]
This are not really tools. But i see the need to have them top level UI.

What about we put this as a menu in the header?

**Comment by Draise14** [comment]
A menu in the header? Like buttons in the header? That could also be useful, a lot of the GP functionality is in the tool header already. 

I like the toolshelf as there is a lot of realestate; but a few of these could fit in the header, that can also work.

**Comment by ReinerBforartists** [comment]
Hm, the menu does not have this much entries. What about we move the whole content simply up one level?

**Comment by ReinerBforartists** [comment]
Not happy with toying around with the sub menus here. We run into inconsistencies with other menus. And the more i pull at it, the more would need a change.

I guess we will end in panels in the sidebar instead, which was the initial idea. But let me sleep a few nights over this first.

**Comment by ReinerBforartists** [comment]
Fixed in master
![fixed](https://user-images.githubusercontent.com/13919702/140791307-ceadcdb3-52e7-48d9-a6cf-7d7c03a825bf.jpg)
