### ISSUE TITLE
lights don't work, only Sun is OK

### ISSUE THREAD

**Issue by ReaderfRik** [Bforartists/Bforartists#2716]
I work with Windows 10 and the latest version of Bfa.
It's impossible for me to make the lights visible, although they point into the right direction to the object, and the power is sufficiently increased. I am then in render mode, with camera view, as it sould be.
Only sun has a visible light effect.

I really don't know where furthe to look for a solution, nor in settings, nor in internet....
Looking forward for suggestions, thanks in advance!

**Comment by ReaderfRik** [comment]
Ah, that's strange, they are already jpgs....
But I uploaded them for you, and you can now download them here:
https://filetransfer.io/data-package/mvqn0q1I#link

Op vr 15 okt. 2021 om 20:55 schreef ReinerBforartists <
***@***.***>:

**Comment by ReinerBforartists** [comment]
My edit wasn't fast enough i fear  ^^

Please answer here at github, not by mail. Then you can also attach images. When you send them by mail then they doesn't arrive here.

**Comment by ReinerBforartists** [comment]
Your problem is not to reproduce. And i cannot see what the problem in your settings could be.

As a first step, could you please download the attached scene and have a look if this scene works for you? When it works then you have a settings problem somewhere. When not then i would suggest to test if your scene works in Blender.

But first try the test scene please:  [workingspot.zip](https://github.com/Bforartists/Bforartists/files/7357151/workingspot.zip)

![works](https://user-images.githubusercontent.com/13919702/137578540-381fea95-951f-4fa2-b287-48ad4d2f7ed1.jpg)

**Comment by ReaderfRik** [comment]
Wow, your file works!! And also with other lights, and after a new startup of Bfa ^^
Can you analyse what could be thfailure in my setup? And if not, I made your file as my standard setup for new projects anyway....

**Comment by Draise14** [comment]
This might just be an issue with default light strength. I have notice point and spot and area start with 10 to 100w when to see you need nearly >1000w to get a light over a few meters.

**Comment by ReinerBforartists** [comment]
Hard to say without the file.

**Comment by ReaderfRik** [comment]
I increased the lights indeed, but it had no effect. Tried to attach the file, but strange enough is see that .blend files are not supported for attaching (?)

**Comment by ReaderfRik** [comment]
Thanks!
And sorry, there is another question about scaling down (of this big object). I didn't find the answer on Internet so far, am by far still no Bfa expert..... 
The simple animation it has built-in, is partly disturbed after scaling. 
Should I make this a new post?

**Comment by ReinerBforartists** [comment]
Yes please. 

Scaling is most probably recorded in the keyframes. Also, make sure that you always apply scale ...

**Comment by ReinerBforartists** [comment]
May i also point you to our fabulous discord community? Might be even faster than to post every problem here in the tracker :)

https://discord.com/invite/yKuR77v

**Comment by ReaderfRik** [comment]
🙂 I see, and will take a good look there 👍
