### ISSUE TITLE
Additional Rigging Layout/Workspace

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#272]
# **Request**
Additional Rigging Layout/Workspace with all 3 armature related properties tab already open and organized.

## **Describe the solution you'd like**
Due to having three distinct workflows for rigging with 3 armature related properties tab, it would be nice to have them exposed as soon as I open a new workspace to rig. 
Another feature is have the drivers graph open and ready, and have a script editor open and also ready for creating rigging scripts or to run any on demand (can be collapsed). 

## **Describe alternatives you've considered**

** Views: **

 - Outline Armature Properties (with other tabs exposed) 
 - Bone properties   
 - Bone Constraint properties
 - Script editor
 - Driver Graph
 - 3D View

I have made a mockup layout below:
![pureref_2018-09-03_15-44-53](https://user-images.githubusercontent.com/35357409/45001157-6b96da80-af90-11e8-991e-09baae963e3b.jpg)

**Additional context**
With the new Workspace feature of 2.8, maybe having this quick tab would be nice.

**Comment by ReinerBforartists** [comment]
Hm, that's too much at once. You get thrown to death with options. Yes, it requires a few clicks more. But it is more organized in the current way. And do we really need a scripting editor here? It is one click from animation to scripting layout.

Tough decision, but this proposal is unfortunately the complete opposite of what Bforartists stands for. Organized, easy to use, easy to discover.

Closing.
