### ISSUE TITLE
Geometry Nodes - Make "Get" nodes with equivalent "Set" nodes contain the word in the title. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2724]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/137815677-d9bfb549-cdcb-44ba-af30-398a474b7482.png)

There are "Set" Nodes like `Set Position` but for a clear workflow and search of attribute field searching, the nodes that get the same data should say "Get". But they don't. So it's hard to search and find these nodes when you want to get data. It also confuses the workflow quite a bit. 

Can we make sure the titles of these nodes and their menu entries are "Get" nodes like `Get Position` to know they pair together in the field flow? 

## Reason
- If they say "Get X" then we know they have an equivalent "Set" node. Meaning.. you have to get data, modify it then set it. Right now you can't tell what you need first before you set.

**Comment by ReinerBforartists** [comment]
Good catch. Could you please report this to the Blender devs too? Maybe they can be convinced :)

**Comment by Draise14** [comment]
Reported both as a bug and in the Blender Chat:
[https://developer.blender.org/T92827](https://developer.blender.org/T92827)

**Comment by Draise14** [comment]
They immediately closed it.

I really don't like their code tracker pipeline. You can't make a task, commit to it, pull from it, and solve any UX or UI problem from it. Only bugs... but it's a UX bug in a sense. It doesn't have gitflow to improve features or UX issues. 

So.. I put it to Devtalk. 
[https://devtalk.blender.org/t/geometry-nodes-node-labeling-and-searching-feedback-get-set-labeling-for-consistent-ux/21227](https://devtalk.blender.org/t/geometry-nodes-node-labeling-and-searching-feedback-get-set-labeling-for-consistent-ux/21227)

**Comment by Draise14** [comment]
Yeah, they are closed to the idea.

**Comment by Draise14** [comment]
Had a discussion about it:
1. They believe the "Get Field Data" should be a noun like other nodes. 
2. They believe these two nodes have no connection or are different, so inconsistent naming is ok. 
3. They debated this a while back and are moving forward and don't want to re-debate it.
4. They are closed even to patches that would fix this UX issue. 

So.. now it's inconsistent internally, with other workflows like Unreal Engine and Softimage that uses this field UX... and.. you can't search for equivalent nodes well.

**Comment by ReinerBforartists** [comment]
Sorry to hear that. Well, was worth a try :)

**Comment by ReinerBforartists** [comment]
We will have a order problem with new names. Since the nodes then starts with set. But i think it's okay to pay this price.

**Comment by ReinerBforartists** [comment]
For now just a handful. The counter parts to the set nodes. 

But what to do with the rest of the getters?

![getset](https://user-images.githubusercontent.com/13919702/141466610-a0eecc4b-e8a4-43a9-8887-0c885dbbbbb5.jpg)

**Comment by ReinerBforartists** [comment]
Hm, the node labels are defined elsewhere. I hope i don't run into trouble here.

![labelmissing](https://user-images.githubusercontent.com/13919702/141467030-9422988c-81be-4407-af73-16d64da6bccc.jpg)

**Comment by ReinerBforartists** [comment]
Hmmhmmm. We might get in conflict with the node names between Blender and Bforartists.

**Comment by ReinerBforartists** [comment]
Phew. Can be done. The node label is defined in the single node *.cc files in source\blender\nodes\geometry\nodes

But the more i think about it, we will end in a babylonic language chaos then between Blender and Bforartists. Especially with the Blender tutorials. This is something that should and must be done at the Blender end.

I will now revert the previous commit. And then close this issue.

**Comment by ReinerBforartists** [comment]
Closing as won't fix.

At least i have fixed a few whitespaces and a wrong tooltip at my way ^^
