### ISSUE TITLE
Fix icon size in tool shelf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2731]
The panel appearance has changed. This leads to some unexpected side effects in the icon size.

![iconsize](https://user-images.githubusercontent.com/13919702/138590323-90adf0dd-0ed0-428a-ad53-92123dfd82d3.jpg)

![opaque](https://user-images.githubusercontent.com/13919702/138590171-d5ff9237-386a-4193-9610-797ab88ef2b4.jpg)

**Comment by ReinerBforartists** [comment]
Still lost here. All i can find is a line of code with PANEL_TYPE_NO_HEADER in conjunction with width_no_header. Which i think should also count for our PANEL_HIDE_BG. In hope it fixes the width problem. But my C fu is too weak to understand this code.

\source\blender\editors\screen\area.c

![area](https://user-images.githubusercontent.com/13919702/142774286-c8253061-4b48-465d-8b52-cd19f6c6c779.jpg)

**Comment by ReinerBforartists** [comment]
New comment in UI_interface.h . The line with the margin ...

/* Both these margins should be ignored if the panel doesn't show a background (check
 * #UI_panel_should_show_background()). */

So UI_panel_should_show_background() is the class where we need to connect our hide_bg tag to ...

**Comment by ReinerBforartists** [comment]
Welllllll ... it works .... somehow .... though ....

I miss mah header color ^^

![problem](https://user-images.githubusercontent.com/13919702/143912024-071925fb-5025-4f8a-b92f-4e5699fe1b7f.jpg)

**Comment by ReinerBforartists** [comment]
Let's try another approach ...

**Comment by ReinerBforartists** [comment]
Another failed approach. I tried to connect the snapping to the UI_PANEL_MARGIN_X variable. But then we run into the problem that the icon sorting goes fubar. Snapping width doesn't fit to the sorting width anymore.

Maybe an approach to follow. But we would need to check all the values in the tab panels again then.


![fail](https://user-images.githubusercontent.com/13919702/143920151-14216816-a6f6-4589-844f-09d55940ff68.jpg)

**Comment by ReinerBforartists** [comment]
Running out of ideas. Unassigning.

**Comment by ReinerBforartists** [comment]
I fear i need a super iyad here again. @iyadahmed , could you be so kind to have a look at this issue too? Maybe you find what i overlook. My C fu is simply too weak here.

**Comment by iyadahmed** [comment]
Sure will look at I hope I can fix it

**Comment by ReinerBforartists** [comment]
Found a fix. With a drawback. I turned off the margin for the region type tools. But now the mouse position to drag the panels is off by the margin. Well, now we have at least the margin between the panels and the border of the editors. Blender devs wants to implement permantent scrollers here from what i remember ...

I have for now reduced the UI_PANEL_MARGIN_X to 0.2 to minimize this effect. But we might want to find a better solution once the permanent scrollers are introduced. The first solution was already close. But i cannot find where the header can be set to opaque again.

![uglysolution](https://user-images.githubusercontent.com/13919702/144015978-a2baa5c2-c0a2-4e0d-9f57-0918679d66b7.jpg)

**Comment by ReinerBforartists** [comment]
Had a second dive at this, and am still lost. I cannot nail down the place where the drag area for the panels and the change of the mouse pointer happens.

Halp :(

**Comment by iyadahmed** [comment]
> Had a second dive at this, and am still lost. I cannot nail down the place where the drag area for the panels and the change of the mouse pointer happens.
> 
> 
> 
> Halp :(

Will try to find it now

**Comment by iyadahmed** [comment]
apologies for late reply but I was meaning this
https://github.com/Bforartists/Bforartists/blob/0477c46a180ef218b4b523a7aba53c2cba392390/source/blender/editors/screen/area_utils.c#L56

**Comment by ReinerBforartists** [comment]
Ah. Many thanks. I'll have a look in this class. Fingers crossed. But this shouldn't stop you to investigate further. You know i hate C  ^^

**Comment by iyadahmed** [comment]
Ok ^^

**Comment by ReinerBforartists** [comment]
Mh, i have been at this class before. This has nothing to do with the drag handling, unfortunately. Just with the snapping points.

**Comment by ReinerBforartists** [comment]
Okay, toyed around and found something. First i have set the margin to 1.0f to have a better test scenario with more obvious results.

![highermargin](https://user-images.githubusercontent.com/13919702/147817745-a767bcda-c504-4831-bdd4-1acef5a51291.jpg)

Then i searched for 0.4f values in the files. Which is the original Blender default value. And found an interesting class in area.c. Which i then turned from 0.4f to 1.0f. 

![azone](https://user-images.githubusercontent.com/13919702/147817756-840e10ec-5359-4c82-9cec-434ce8e0f302.jpg)

And now the mouse behaviour at the sidebar fits.

![fits](https://user-images.githubusercontent.com/13919702/147817780-1f393185-e710-4fc7-b513-7b09e63b4024.jpg)

But now the gap where the mouse cursor changes to drag over the tool shelf is even bigger ^^

![tolshelf](https://user-images.githubusercontent.com/13919702/147817875-f6096d10-3c32-4b83-981b-aedc02850ea1.jpg)

I guess it's exactly this 1.0f that is missing now here. But where to add it?

**Comment by ReinerBforartists** [comment]
Hm, seems that i am at the correct location. I have reverted my experimental changes, and changed the value to 0.2f, which is our default for the margin. And now we have a useful result :)

So finally fixed. Let's hope that this doesn't strike back in an unexpected way ^^

![sidebarmargin](https://user-images.githubusercontent.com/13919702/147818760-01647d69-20d1-4cbb-b4b1-66e3a8c98346.jpg)

![toolshelfmargin](https://user-images.githubusercontent.com/13919702/147818764-49473dc9-a278-4166-bfd2-456aef7ed6e3.jpg)
