### ISSUE TITLE
VSE, Preview window. Assign Transform hotkeys to the tool shelf tools, remove Transform from strip menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2746]
As the title says. Assign Transform hotkeys to the tool shelf tools, remove Transform from strip menu.

![removetransform](https://user-images.githubusercontent.com/13919702/139582912-77e9be90-5b7f-47fe-9a20-1e34491030fe.jpg)

**Comment by ReinerBforartists** [comment]
Hm, we should call it legacy instead of removing it ...

**Comment by ReinerBforartists** [comment]
This utter garbage called keymap manager ...

Mission impossible. Unassigning. First we need a bug report for Blender here.

![missionimpossbile](https://user-images.githubusercontent.com/13919702/139844823-174cd308-64e9-4803-a39a-b84ae423b42a.jpg)

**Comment by ReinerBforartists** [comment]
I had it already reported. Forgot to add the bug report here: https://developer.blender.org/T92140

**Comment by Draise14** [comment]
Duplicate of #2709
