### ISSUE TITLE
Paint_OT_weight_sample_group error with creating a new keymap

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2753]
We get currently a error message when we create a new keymap. This was also the case with the Blender version from sunday. But now, two days later, it is not longer happening.

Let's wait for next sunday. Then we can have a look at the fix.

![weightgroup](https://user-images.githubusercontent.com/13919702/139914024-270d2bd5-4a82-41c5-a8a2-b374a52b3c03.jpg)

**Comment by ReinerBforartists** [comment]
This bug remains interesting. None of the commits in this time frame has anything to do with the keymap. And i did not have any conflict with the merge. Means the bug should be gone. It isn't.

**Comment by ReinerBforartists** [comment]
The startup.blend as a cause is out. I have created the assets workspace meanwhile, and resaved all blends

**Comment by ReinerBforartists** [comment]
Ah, got it finally reproduced in Blender. It depends from which keymap you come. With the Blender keymap as the base you don't get an error at  all. But when you use the old Blender 2.5x keymap, then you get this error. 

And this also explains where our error is. Paint_OT_weight_sample_group is not longer in the API. Let's remove it from our keymap ...

**Comment by ReinerBforartists** [comment]
Hm, we don't have a Paint_OT_weight_sample_group in our keymap ...

**Comment by ReinerBforartists** [comment]
Reported to Blender again. I had it reported before, but wasn't able to reproduce the problem anymore, as told above.

https://developer.blender.org/T92906

**Comment by ReinerBforartists** [comment]
In the keymap our entries are identical to the Blender ones. But throws an error. So let's wait for the outcome of the bug report. I expect it has something to do with the keymap defaults and custom keymaps.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/182694563-716fa168-62ea-46b8-b8d0-966085db1cd9.png)

Looks like this one doesn't cause an issue now. I cannot reproduce. 

![image](https://user-images.githubusercontent.com/35357409/182695091-311ff328-6a3d-4b08-86af-380951b9d856.png)

**Comment by ReinerBforartists** [comment]
Still an issue with the 2.7x keymap in Blender and BFA.

**Comment by ReinerBforartists** [comment]
We could of course simply close it as known issue. There is nothing that we could do at our end. But to have it in our tracker makes sure that we don't loose it out of sight.

**Comment by Draise14** [comment]
Will postpone to review for 3.6.0

**Comment by ReinerBforartists** [comment]
Let's finally close this issue. We cannot do anything against it, it is long known, and it doesn't really harm. I haven't experienced any side effects with this. It's just a warning.
