### ISSUE TITLE
Default Workspaces - Shader Editor, add Asset Browser and centralize 3D View

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2759]
# Request

Proposed Shader Workspace:
![image](https://user-images.githubusercontent.com/35357409/140337953-81aaad8a-d367-4c8c-b8ab-1fc04a8a507d.png)

Current state:
- Image editor to see images
- Node editor taking up half the workspace, good
- File browser
- Heavy weight of the 3D view to the right, not central

The file browser is only good for images right now, but for the shader editor, marked textures, node groups and libraries of materials from the Asset Library would be more useful in the shader editor to drag and drop into the 3D view and Node editor. 

We could replace the near useless File Browser for the Asset Browser (minimal version)
We could also move the 3D view to be more center, so it's only one drag and drop for new materials and node groups from the corner asset browser.

**Comment by ReinerBforartists** [comment]
So where is the benefit of the change? 

File browser cannot be replaced. It is needed to drop textures.

**Comment by Draise14** [comment]
**Benefits:**
- Materials can be added quickly to the context of shaders
- Marked textures can be added just like you would from the File Browser
- Node groups from the Asset Browser can be quickly dragged into the shader editor without needing to pre-append or link them to the scene. 
- It's similar to your proposal of an Asset Browser workspace for shader node groups and materials. 
- You can already load images with the image node and "open image" which opens up it's own File Browser. It's currently redundant. 

I personally haven't used the File Browser to import or drag in images, since for the PBR workflow, you use the Node Wrangler which opens up it's own browser and load PBR sets, or you use the File Explorer of the OS to import the images with drag and drop.

**Comment by ReinerBforartists** [comment]
Ah you want to use this as the asset browser workspace? The space for the asset browser is too small then though.

**Comment by Draise14** [comment]
No. This is additional to the asset browser workspace.

**Comment by ReinerBforartists** [comment]
But we run out of space when we add the asset browser here too. There is already too much content in this workspace. And the asset browser needs huuuge space to be useful, so that you don't pull all the windows around all the time. That's why we make the asset workspace at all :)

**Comment by Draise14** [comment]
This is a separate workspace. Refer to the other task for the default asset browser workspace. I have another suggestion there. 

This proposal is NOT the asset browser workspace. But an update to the shader workspace. The idea here is to tie in the assets a bit more to the shader workflow without going massive full screen asset management mode. 

You have higher level use and lower level use though... 

But maybe you are right, it might not be useful here also in this workspace. But in another.

**Comment by ReinerBforartists** [comment]
My argument remains that adding the asset browser here is mission impossible since it occupies too much space. Unfortunately. I would have loved to hide it behind the properties editor. Like in trueSpace. But for that we would need to rewrite the asset browser.

**Comment by Draise14** [comment]
Yeah, sure. Ok! So I guess the asset browser workspace is the way to go about it for now. I'll update my personal layout (I removed the File Browser from everywhere, kept it popup) and test eitherway. 

I would love panels per category in a tab in the Property Shelf also, but that might also be a feat to code. 

I'll close this request to avoid confusion.

**Comment by ReinerBforartists** [comment]
Okay. Nevertheless thanks for the suggestion :)
