### ISSUE TITLE
Move the Armature edit mode "Recalculate Roll" to the tools panel 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#276]
## **Case**
The bone orientation sub-menu is located under "Armature>Recalculate Roll"  or the CTRL+N floating panel. I use it often and having them in through two sub menus - still has me using the hotkey.

## **Request/Task**
Move the "Recalculate Roll" bone transform orientation in Armature edit mode to the tools panel so that it's only one submenu from the toolshelf.  

![bforartists_2018-09-04_08-48-00](https://user-images.githubusercontent.com/35357409/45035294-456c4b80-b01f-11e8-85b8-0eead8761cd9.jpg)

## **Alternative Solutions**
I know the toolshelf will drastically change in 2.8 and hasn't been defined in Bforartists, but it would be nice to have this panel exposed and set of options in the toolshelf somehow for future development - it would save a bunch of hotkeys or mouse movements. 

Another alternative is moving it to the Transforms Panel instead of Tools panel.

**Comment by ReinerBforartists** [comment]
Indeed. We will see how it goes.

**Comment by ReinerBforartists** [comment]
Not longer valid with Blender 2.80. Closing.
