### ISSUE TITLE
Asset Browser - Property Shelf - Make some info collapsable

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2764]
# Request
![image](https://user-images.githubusercontent.com/35357409/140658728-fcc83e4a-cc6a-4b9d-99ae-bf71053121af.png)

There is a lot of info that we rarely touch that could be under a dropdown arrow. 

Other than Name, Description and Author, the other stuff could be under an "Advanced" collapsible panel.

**Comment by ReinerBforartists** [comment]
I still hate to touch the unfinished asset browser. We will surely see the one or another change here ...

**Comment by Draise14** [comment]
Yeah.. I seriously can't wait till they freeze festures for 3.0... which is a bit slow this year.

**Comment by ReinerBforartists** [comment]
Well, it is in Beta. So not this much changes to expect anymore. But the asset browser is still not finished. They have for example pulled out the pose library again from what i can see. It remains difficult.

**Comment by ReinerBforartists** [comment]
This one is more complicated than one would expect. It is a general design rule of the object related panels that the general info is not hidden in a sub panel ...

**Comment by ReinerBforartists** [comment]
Hm, the code tells me that the props UUID and Simple Name are debug values. Just showing when you have turned debug explicitely on. A normal user will not do this. What we can put into a panel is the three props Source, Description and Author

![hideaway](https://user-images.githubusercontent.com/13919702/146907117-a7fe9369-5764-4c9e-b4dd-3e41ed144b77.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![info](https://user-images.githubusercontent.com/13919702/146909441-535fe38e-da97-4be5-994d-e8489c2bfedc.jpg)
