### ISSUE TITLE
Toolbar - Make Proxy still listed when feature is removed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2766]
# Bug
![image](https://user-images.githubusercontent.com/35357409/140797992-ba8bf546-9d02-4e7d-809a-a3eedf3b86f8.png)

`Make Proxy` is no-longer a feature, as any proxy is now a library override. So this 3.1 feature should be removed from the toolbar.

**Comment by ReinerBforartists** [comment]
Replaced by make library override. I have no idea though how this tool works. So fingers crossed that it doesn't throw an error ...

Draise, could you please check it?

**Comment by Draise14** [comment]
What do I need to check? if the Make Library Override operator works from the toolbar?

**Comment by ReinerBforartists** [comment]
Yes please :)

Just replace the operator as done in the commit. I have as told currently no idea how to activate this tool.

**Comment by Draise14** [comment]
Sorry for the late response. It does indeed. 

Just got out of crunch.
