### ISSUE TITLE
Geometry Nodes Editor - CTRL+RMB drag hotkey to cut lines doesn't work

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2769]
# Request
The CTRL+RMB hotkey to cut lines doesn't exist in the Bforaritsts keymap, but in the Blender keymap it does. This is a standard for node work, so would be good to check if there is conflicts or if it can exist without a problem.

**Comment by ReinerBforartists** [comment]
We have a bigger problem here. The cut tool in the tool shelf doesn't work. Also not with the Blender keymap.

I start to loose nerves with the crap that they call keymap manager ...

**Comment by ReinerBforartists** [comment]
I think the Blender devs have finally managed to stop the fork with that. The tool shelf tools from the node editor does not show in the keymap manager. So there is no way to edit them or add other functionality. So what is broken in this area remains broken. Nice. When i remember correct this was even reported before a year or so by me. I need to find the report ...

**Comment by Draise14** [comment]
The keymap manager is the worst. 

Sometimes I wonder what it would take to redesign and make it something better.

**Comment by ReinerBforartists** [comment]
A complete rewrite of Blender. Unfortunately.

**Comment by ReinerBforartists** [comment]
Cool. The right mouse button to cut the spaghetti is in the blender keymap overwritten by the right click context menu. In Bforartists it works since we use a double right click. So let's add at least this part back.

**Comment by ReinerBforartists** [comment]
Ah, another pitfall seems to be the keyconfig_version number of the keymap. Increasing it fixed the ctrl right mouse issue.

Either way, fixed in master. Tools are working again.

**Comment by Draise14** [comment]
A whole rewrite of Blender.. man. The keymap system, the "pride" of Blender devs and users, yet it's the worst system of the entire package.

**Comment by ReinerBforartists** [comment]
Well, it is like with the whole UI. Everything is cluttered across the whole code. There is no separation between core code and UI code, because the core code is the UI code. And same goes for all the input and user interaction code.
