### ISSUE TITLE
Remove/change submenu of Parent/Unparent for a more direct workflow

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#277]
## **Case**
Currently to parent and unparent something, you can access a menu with a hotkey CTRL+P or a button in the toolbar or toolshelf. The button doesn't do the work immediately, and it's always a 2 step action to do parenting of bones and object children. This becomes slow when parenting work needs to be done. 

Typical workflow elsewhere is that you have a mode for offset or no offset and you press the hotkey once or the button once, and then parent, parent parent. If you want to unparent, you press the alternate combo and unparent, unparent. 

## **Request/Task**
**Armature Edit mode:**
Have a "quick" parent workflow that skips the submenu. One button to parent connected and another to parent offset. No submenu.

**Object Mode:**
Have a "quick" parent workflow that skips the submenu. One button for each of the four parent modes and another to parent offset. No submenu.

![bforartists_2018-09-04_08-52-34](https://user-images.githubusercontent.com/35357409/45035758-55d0f600-b020-11e8-85e8-127c2278238f.png)
![bforartists_2018-09-04_08-55-38](https://user-images.githubusercontent.com/35357409/45035759-57022300-b020-11e8-83d9-383c35479d67.png)

## **Alternatives**
Again, this is open to 2.8 new toolshelf workflow changes, so may be irrelevant. 

- Have one button and no submenu: it automatically detects what to parent/unparent. To define the offsets, you'd have another toggle button/tickbox to change if it should have "Keep Transform"  or "Keep offset"  activated when using the button/hotkey in the toolbar or toolshelf. 
- The unparent workflow could also benefit from this. 
- The Relations panel could become bloated quickly, so maybe they may need some categories to compensate all the new buttons/icons; or change the workflow with the parenting system offset toggles or a mix of both

**Additional context**
- May need new icons for new buttons

**Comment by ReinerBforartists** [comment]
This will introduce lots of buttons that you never use. Which pollutes the tool shelf then. Hmm.

**Comment by Draise14** [comment]
Yeah, I thought about that. So I'm.. ***not*** all for that solution. But I thought up another: ultimately we just have three parenting modes: with offset, without offset (connected) and on vertex. 

![bforartists_2018-09-04_11-13-27](https://user-images.githubusercontent.com/35357409/45043793-d64d2200-b033-11e8-8d43-261963e192e5.png)

This can have two buttons and a toggle to change how the button works with offset. 
The parenting would either be parent once (with offset on or off, depending on the toggle). 
Unparenting would also be once with offset toggle on or off. 
Vertex parenting would also be just one new button. 

The order ir arbritrary right now, but could be with the toggle first, then the other three. 


## Armature Edit mode: 
**Parent**
- Connected
- Offset

This can have two parenting buttons, one for object, the other for vertex with an additional toggle to change how the buttons works with/without offset. 

## Object mode
**Parent Object**
-	No offset/Connected
-	With Transform Offset

**Parent Vertex** 
- With Triangle
- Without Triangle (not sure of the difference)

## Edit Mode
**Parent Vertex** (different operator, same function as Parent Vertex)

![pureref_2018-09-04_11-21-42](https://user-images.githubusercontent.com/35357409/45044163-f03b3480-b034-11e8-88cb-c37887d4ae81.png)
Here we have the same function, but a different icon, button, and operator. This could be the same icon and extra button in Object mode.

**Comment by ReinerBforartists** [comment]
I have never ever used vertex parent ... ^^

**Comment by Draise14** [comment]
It is not used often, correct. It's more for rigging and skin based relative control offsets, like muscles. That's why I'm suggesting we remove that entire concept of "Vertex Parent" from the normal "Object Parent" workflow as a separate system.

**Comment by ReinerBforartists** [comment]
Not longer valid with Blender 2.80. Closing.
