### ISSUE TITLE
Asset Browser - Icon to open Asset is misleading (open file)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2778]
# Feature Request
![bforartists_56eVMFVl7N](https://user-images.githubusercontent.com/35357409/141876534-67b3014f-09cd-408c-8303-1382aea80efc.png)

This icon to open up the blend file of the asset is a little misleading (open preferences?) when in reality it opens up the source blend file in a new instance of Bforartists. 

Change to open folder icon maybe? Or arrow to a folder? Or blend file icon? Something a bit more telling. 

Version: devbuild-13-11-2021

**Comment by ReinerBforartists** [comment]
Postponing until at least Blender 3.1. The asset browser is ways not finished ...

**Comment by ReinerBforartists** [comment]
Hm, on the other hand, we just need a file folder icon here, right?

**Comment by ReinerBforartists** [comment]
Fixed in master
![fixed](https://user-images.githubusercontent.com/13919702/146752664-a6942915-421b-4966-9176-db364408fce7.png)
