### ISSUE TITLE
Asset Browser - Theme - Warning when trying to drag assets from Catalogue is too transparent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2779]
# Feature Request
![bforartists_wKZ614iuVk](https://user-images.githubusercontent.com/35357409/141876728-50c98f0f-2477-42cb-990c-f0fd3d531c3d.png)
 
 1. Create an asset in a blend, then mark it in a a catalog
 2. Save blend and add library to the user preferences
 3. Mark the asset then move to catalog. 
 4. Make a new scene
 5. Go to library, then try drag the asset from the other file to a new catalog. 
 6. You'll see a red notice that has a too transparent background. 
 
 Maybe need a better background to be legible. I am not sure what part of the theme this is... But just to log it. 
 
Version: devbuild-13-11-2021.zip

**Comment by ReinerBforartists** [comment]
Sounds like something the Blender devs are responsible of. This is imho best reported in the Blender bugtracker. Even when i fear that they will immediately close it down.

**Comment by ReinerBforartists** [comment]
Postponing until at least Blender 3.1. The asset browser is ways not finished ...

**Comment by Draise14** [comment]
Righteo. Yeah, good call to postpone these. I'm still using a version of Beforartists from October to work the assets on a project, it's still too buggy.

**Comment by Draise14** [comment]
Here is the relevent code, it's hardcoded, but I mentioned it to the Blender people. 
[https://developer.blender.org/diffusion/B/browse/master/source/blender/editors/interface/resources.c$87](https://developer.blender.org/diffusion/B/browse/master/source/blender/editors/interface/resources.c$87)

**Comment by Draise14** [comment]
They fixed it. 
[https://developer.blender.org/rBce0d817bb7d6ea92b4571fd7262b173217c319cb](https://developer.blender.org/rBce0d817bb7d6ea92b4571fd7262b173217c319cb)
