### ISSUE TITLE
Asset Browser - Add list view to offer the same display options as File Browser

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2780]
# Feature Request
![bforartists_RMj2AaTy23](https://user-images.githubusercontent.com/35357409/141877303-8337e796-0f4e-4d07-8a27-4e655aabf2f5.png)

Right now there is a dropdown with a drop down to change thumbnail view sizes. 

This could be either moved up one level or moved up two levels to a row of iconized buttons like in the File Browser. 

These might be an enumerated menu.. so maybe moving them up a level will suffice.

**Comment by ReinerBforartists** [comment]
Postponing until at least Blender 3.1. The asset browser is ways not finished ...

**Comment by ReinerBforartists** [comment]
This can be fixed now. I never understood anyways why this is not in the same shape than in the file browser. This IS the file browser ...

**Comment by ReinerBforartists** [comment]
Well, we can have the same as in the file browser. Or move the view levels one up XD

he list comes without preview icons then though. Which is most probably the reason why they have removed it then for the asset browser. They want it to have icons for the assets.

We could investigate if we can manage to create 16px icons, to have a fifth size feature. The smallest one is 64 px at the moment. But i personally think it is good enough to have one list feature. Even when it lacks the preview icons then. And this would most probably not be an easy operation.

![sameas](https://user-images.githubusercontent.com/13919702/146900190-5bb50492-6f28-4183-bf6b-20b67d4579fc.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by Draise14** [comment]
Even these little details make the asset browser that much more useful!
