### ISSUE TITLE
Node editor - separate tooltips in node menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2781]
These tools have the same tooltip ...

![sametooltip](https://user-images.githubusercontent.com/13919702/141986112-6428111c-de45-45a4-9b79-6acab08eef15.jpg)

**Comment by Draise14** [comment]
Nice!!! Maybe "Node Tools" should be "Frame Tools".

**Comment by ReinerBforartists** [comment]
Good call. Let's rename to frame tools.

**Comment by ReinerBforartists** [comment]
Fixed in master

![copy](https://user-images.githubusercontent.com/13919702/142199206-115c2641-e575-4028-ab59-0b97291abe95.jpg)
