### ISSUE TITLE
Header - Render - OpenGL Render Options missing (removed feature?)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2785]
![bforartists_CSZGxCpiRy](https://user-images.githubusercontent.com/35357409/142517277-9eb6cc38-ee09-485d-92c9-30d0940353dd.png)
![bforartists_Lhns2R8rjA](https://user-images.githubusercontent.com/35357409/142517283-eb2f022e-8e2e-41da-b419-85c594d963a1.png)
![bforartists_qJX12kih8F](https://user-images.githubusercontent.com/35357409/142517294-0a9c5cf4-a070-41a6-bf0d-49e6f63ac6f4.png)

I think there is a missing prop in the Header>Render>OpenGL Render Options

Has this feature been removed by Blender perchance?

**Comment by ReinerBforartists** [comment]
Ah, this just affects the render options. Seems that at least one is gone ...

![renderoptions](https://user-images.githubusercontent.com/13919702/142586931-bed9d054-506f-407f-a8c5-aa547ec11853.jpg)

**Comment by ReinerBforartists** [comment]
Is gone. Blender doesn't have any render settings anymore. So let's remove this sub menu.

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/142587780-ea4bb311-736a-4fca-9fbf-efc6130d2d82.jpg)
