### ISSUE TITLE
Restore feature accidentally removed after merge

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2787]
https://github.com/Bforartists/Bforartists/pull/2594

**Comment by ReinerBforartists** [comment]
Hm?

**Comment by iyadahmed** [comment]
> Hm?

The alt click to key frame selected bones/objects animation decorator feature

I think I opened an issue for this before and you and I concluded that it was removed accidentally

**Comment by iyadahmed** [comment]
Oh it was a discussion not issue
https://github.com/Bforartists/Bforartists/discussions/2701

**Comment by iyadahmed** [comment]
Actually hmm the code still exists maybe it is a keymap issue?, or maybe it was broken only then on the website build, let me check with latest mater build one moment

**Comment by iyadahmed** [comment]
Ok working on master don't know why it wasn't working back then on the website build

**Comment by ReinerBforartists** [comment]
\o/

Now i see. Nevertheless, thanks for investigating again. Better one time too often ... :)
