### ISSUE TITLE
Make some property columns aligned again

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2788]
This used to be aligned before,
![image](https://user-images.githubusercontent.com/25552173/142778299-229df6d6-9c5a-4c34-a85e-18cd091d7cde.png)

**Comment by iyadahmed** [comment]
Already made some edits, but before continuing was this intentional?
![image](https://user-images.githubusercontent.com/25552173/142778354-dc7f46a3-8b24-417b-93bd-20b0c9d12a09.png)

**Comment by ReinerBforartists** [comment]
Hm, this looks fine to me. What exactly is the problem that you see here?

Don't fix what isn't broken ;)

![looksfine](https://user-images.githubusercontent.com/13919702/142823917-909cac09-29cb-4ccb-881e-43c807c3b1cc.jpg)

**Comment by iyadahmed** [comment]
> Hm, this looks fine to me. What exactly is the problem that you see here?
> 
> Don't fix what isn't broken ;)
> 
> ![looksfine](https://user-images.githubusercontent.com/13919702/142823917-909cac09-29cb-4ccb-881e-43c807c3b1cc.jpg)

hmmm it is not algined
see 
this is not aligned
![image](https://user-images.githubusercontent.com/25552173/142825792-52595e82-a00e-45f3-8ca2-e2b2f7a5dbbb.png)

this is aligned, what it should be
![image](https://user-images.githubusercontent.com/25552173/142825870-762a6678-a8ca-4b05-8b08-7fcc6dd578a5.png)

**Comment by ReinerBforartists** [comment]
Ah. Now i see what you mean. It's one block versus single lines.

I have honestly no opinion which one looks better. But when it's this close to each other, then we could also make it a block. I leave it in your hands what to do here. I'm green with leaving it the way it is, and also green to change it :)

**Comment by iyadahmed** [comment]
better to make it all consistent like other places, like blender and like what it was before
![image](https://user-images.githubusercontent.com/25552173/142847108-7ea2fb2a-4f29-454c-9662-70c525898351.png)

**Comment by ReinerBforartists** [comment]
Okay. Then do it :)

**Comment by iyadahmed** [comment]
![image](https://user-images.githubusercontent.com/25552173/142997971-0c4d306a-b38f-4c30-80db-2b88ca013222.png)
done, pushing
