### ISSUE TITLE
Video Sequencer - Tabbed Toolshelf - Add header to tools panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2790]
![image](https://user-images.githubusercontent.com/35357409/142880882-adb23b3f-dd56-4d79-9729-8c05e7cd180f.png)

At the moment, the new toolshelf is very useful. But the header in the tool group is missing, meaning you can't pin nor drag from the first tab. It also would be consistent if similar to the other tabbed toolshelves. 

Request: Show Header like in the other tabbed toolshelves.

**Comment by ReinerBforartists** [comment]
O_O

I could swear ^^

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/142903169-f4da5dc9-63a2-4e13-a69a-c8610524281a.jpg)
