### ISSUE TITLE
Scene + View Layer add dropdown menu - Add icons 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2791]
![image](https://user-images.githubusercontent.com/35357409/142908499-737cbdd1-248f-4ebd-920a-dba8fde767ee.png)

When adding or making new scenes, there is a menu with no icons. 

Would be nice to have these icons.

**Comment by ReinerBforartists** [comment]
Which prop is it?

**Comment by ReinerBforartists** [comment]
Ah, misc toolbar. Scene and View Layer add / duplicate buttons

![moarwork](https://user-images.githubusercontent.com/13919702/142908981-52dcd856-98d3-4b92-ae6e-a4c519ee3ab3.jpg)

**Comment by Draise14** [comment]
Yes, also in the Scene tab of the Property Editor on the + button.

**Comment by ReinerBforartists** [comment]
Yes, it's the same prop.

**Comment by ReinerBforartists** [comment]
View layer
![viewlayer](https://user-images.githubusercontent.com/13919702/142912616-e98d268c-522f-486c-84b9-8a00127279f5.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![newscene](https://user-images.githubusercontent.com/13919702/143070939-b9c1a0aa-fd83-4bfa-8a3e-8561b1bf8085.png)
