### ISSUE TITLE
Outliner - Scenes View - Add context sensitive operators to manage scenes 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2794]
# Feature Request
![image](https://user-images.githubusercontent.com/35357409/143139851-9c066860-0dc1-4748-9402-0c713adf93c9.png)

Out of curiosity, Iyad had a look at making context sensitive operators to manage scenes for me (my initial intention with #2792). So when you right click on any scene, you can duplicate them without needing to rely on the "active scene" to run the scene management. 

And quick summery.... He figured it out! Meaning the context menu can work like collection context menus to create and duplicate scenes just like you would with collections.  Right click on any scene, copy directly (no need for active). 

But they are new extended operators - but we could add these to Bforartist? 

I made this task to keep the code organized and possibly a place to commit to for the patch. 

**Current code status:**
- The operators in the context menu can be context sensitive now, so you can right click on any scene, then duplicate, link, or full copy it. 
- We have the option to automatically switch to scene after running, but currently it just manages them like collections (don't switch to new scene which I prefer, like when you make a new collection)
- The "new empty scene" is in the context menu, though it might be better in the header like in the collection management system as suggested in #2792. 
- They are new modified operators using the API, meaning it was not too hard to extend functionality. But it's new functionality for UX.. worth debating. 

**Pending design discussion:**
Question1:
- Can we add this to Bforartists? This would be a UX improvement, consistent with collection management, and we could close #2792 as redundant. 
- Or is this core feature (new operator functionality) that should be for Blender? Should we try commit there first? 

Question2: 
If the "New Scene" operator is added to header, and the other context sensitive scene operators were in the context menu, would it be a good alternative to #2792? If so, can we implement it and commit the code for it? 

_This would answer a lot of my UX issues with scene management mentioned earlier._

**Comment by ReinerBforartists** [comment]
As told in the other thread already. It is no good idea to create a scene from a scene since you cannot nest a scene into a scene. This is best done with a menu in the header.

And this means i cannot accept this request, sorry. Closing.

**Comment by Draise14** [comment]
The patch is not finished in the capture.

New scene is in header. 
Copy linked, full copy and copy settings is in context menu based on where you right click..

It works. Don't rush the close!

**Comment by Draise14** [comment]
I'm collections you can right click a collection to copy it linked copy.

This code shows that you can copy and linked copy scenes in the same way. 

Confident context sensitive operators and UX. 

New scene can be in header. (The capture is erroneous as we just put them all there)

**Comment by ReinerBforartists** [comment]
Draise, we have the other task for it. Please don't open two tasks for the very same thing in hope to get it through this time.

I have discussed two hours with Iyad yesterday already in this task. A scene is not a collection. You cannot nest a scene into a scene. And this means the right click context menu is not the place to add this content. I will not accept such a patch, sorry.

**Comment by Draise14** [comment]
I would rather close the other task for this one. I also spent hours with iyad designing this solution. 

The other has a "select active" before using the operators issue but this does not.

**Comment by ReinerBforartists** [comment]
You would have better first asked me. You know that i am usually very open to any idea. But this is an idea that will fall us onto our feet. And i explained now more than once why.There was a reason why i asked for a bit time to think the idea through. I cannot accept this patch, sorry.

**Comment by Draise14** [comment]
Take the time you need to think about it. The code is ready and working.
