### ISSUE TITLE
3D View - Insert Keyframe Menu - Icon order is misaligned in Armature>Pose Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2795]
![image](https://user-images.githubusercontent.com/35357409/143589391-3690e243-56e6-4dea-b9c9-b24bd3c838eb.png)

Looks like the transform icon for location is on "Available" and the rotation icon on transform, and so forth. The icon order is off for some reason. 

**Context:**
In armature Pose mode, this seems most evident, as this may not have Deltas? And the icons are enumerated? I sniff a head ache...  

# Task
Investigate why and fix the order, maybe with a new icon for "Available"? Making sure icon order is dynamic to the Pose mode of Armatures.

**Comment by ReinerBforartists** [comment]
I see the problem. When you insert a keyframe to an object that does not have an animation yet, then the menu does not have the key item "available". But once it has a keyframe it shows also the item "available".

@iyadahmed, since this solution came from you and i have just added a few icons, do you want to have a look at this? We might need two different arrays ...

![with](https://user-images.githubusercontent.com/13919702/143612175-c9cbe888-6275-41ca-b748-27a5d7774d82.jpg)

![without](https://user-images.githubusercontent.com/13919702/143612182-06d5a557-df3c-488f-bd37-dab3f0017444.jpg)

**Comment by ReinerBforartists** [comment]
Related: 3D View - Insert Keyframe menu icons #2565

Did a quick dive, and cannot find the place where the Available keyingset gets added. Must be an if somewhere, wich we need to use for our array too. The single keying sets are defined in release\scripts\startup\keyingsets_builtins.py . Which doesn't really help us here ...

**Comment by iyadahmed** [comment]
Hi will take a look at it asap

**Comment by ReinerBforartists** [comment]
As a reminder, it is very likely that Blender 3.0 gets released this week. And so also Bforartists 3. Means we have feature freeze.

I would nevertheless be happy to have this bug fixed if possible ...

**Comment by iyadahmed** [comment]
> As a reminder, it is very likely that Blender 3.0 gets released this week. And so also Bforartists 3. Means we have feature freeze. I start to prepare the release now. Collecting the release note, creating the manual, etc. 
> 
> 
> 
> I would nevertheless be happy to have this bug fixed if possible ...

Will do asap tonight currently in work hours

**Comment by ReinerBforartists** [comment]
Great :)

**Comment by ReinerBforartists** [comment]
I see another problem. In your screenshot there is whole character. So the menu for bones and objects is different. I don't have added icons for that yet.

I vote for reverting the icons in the array for now. This is a bigger operation. Which requires now at least four different arrays ...

Thoughts?

**Comment by iyadahmed** [comment]
> I see another problem. In your screenshot there is a menu item called whole character, and bbone. So the menu for bones and objects is different. And for bendy bones too. I don't have added icons for that yet.
> 
> 
> 
> I vote for reverting the icons in the array for now. This is a bigger operation. Which requires now at least four different arrays ...
> 
> 
> 
> Thoughts?

Sure if it cause problems let's revert it for now, until we find a better way, what do you think Draise @Draise14?

**Comment by Draise14** [comment]
Hmm... 3rd of December is the big date. I have published a quick little capture of the new icons to this menu as an update before finding this issue to the socials, since it was closed - I could retract it. But yeah, there is a lot of variation with armatures. But to be a little stress free - we can revert - then work on it after in the dev build. 

Do you think Blender will be on time? If we do a big release right after Blender after their hype has died down a little, maybe we can come in with a louder bang? This could give us a week to finish this by choice. As you know, they usually publish late anyway.

Do we plan to publish exactly the same day as Blender? If yes, sure, revert and work on it after. If anyone asks in the socials or discord I'll explain what's up. If we publish after a few days, maybe it's enough time to finish it. 

Up to you Reiner!

**Comment by ReinerBforartists** [comment]
Yes, the release date is already set and in the public. Blender 3 will appear at friday. And yes, the plan was to release at the same day. Plus minus a day or two. The culprit here is all the preparation work. The manual for version 3 is already up in the repository.

For the revert, we could simply spam the array with the keyframe item for now as a place holder. No need to remove everything.

**Comment by iyadahmed** [comment]
> Yes, the release date is already set and in the public. Blender 3 will appear at friday. And yes, the plan was to release at the same day. Plus minus a day or two. The culprit here is all the preparation work. The manual for version 3 is already up in the repository.
> 
> 
> 
> For the revert, we could simply spam the array with the keyframe item for now as a place holder. No need to remove everything.
> 
> 
> 
> Or you quickly find a solution to our dilemma. I can wait one or two more days with compiling the final version :)

The proper solution is to add the icon to the keying set data, so each keyingset knows its icon, but that would make merge a little bit involved, but not much will try to get this idea working today hopefully

**Comment by iyadahmed** [comment]
Currently working on it, I have another idea for it which will not be intrusive too, basically we will match the icons by keying set id

**Comment by iyadahmed** [comment]
Worked great
![image](https://user-images.githubusercontent.com/25552173/144129937-40e5f8d4-bb23-48aa-becb-7f25dc6bf3af.png)

creating a PR shortly

**Comment by ReinerBforartists** [comment]
Excellent. I'll have a look to add the missing icons :)

**Comment by ReinerBforartists** [comment]
Means when i ever find out what i need to modify for that XD

Task is of course still open. We miss a few icons ... :)

**Comment by ReinerBforartists** [comment]
@iyadahmed . you forgot about the comments again ...

One merge, and your code is history ^^

**Comment by ReinerBforartists** [comment]
Hmmmm .... just one of four works ^^

![classes](https://user-images.githubusercontent.com/13919702/144195254-e45a200d-b2d8-41ff-b6de-ab0f3cbd328a.jpg)

![arrays](https://user-images.githubusercontent.com/13919702/144195270-03985875-f38c-4a4d-8ae7-1189a790e93c.jpg)

![panel](https://user-images.githubusercontent.com/13919702/144195291-33abab8e-92cf-4526-82be-62d7913f4e6c.jpg)

**Comment by ReinerBforartists** [comment]
Dhads betta! Fixed in master. It was me a pleasure :)

![fixed](https://user-images.githubusercontent.com/13919702/144195890-ed5deffd-615c-4298-a583-29f5f7a204fc.jpg)

**Comment by ReinerBforartists** [comment]
Let's build the release version ...
