### ISSUE TITLE
Toolshelf Panels - add a fourth snapping margin

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2798]
area_utils.c contains the snapping units for the tool shelf. 

Blender has just two icons width. We have three. So we need one more snapping unit for the text buttons.

Task is as easy as adding another margin value to the snap_units area. Just not sure which value to add here.

Related task: https://github.com/Bforartists/Bforartists/issues/2731

![snap](https://user-images.githubusercontent.com/13919702/143924828-f0ff9969-806f-4120-b92b-dbd9f08e332f.jpg)

**Comment by Draise14** [comment]
Would this add 4 column of icons before text?

**Comment by ReinerBforartists** [comment]
No. Three. Best we do this task after we have fixed the issue with the snapping width ...

**Comment by ReinerBforartists** [comment]
Fixed in master
