### ISSUE TITLE
Github - Use consistent branch or tag naming per release (v#.#.#)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2804]
![image](https://user-images.githubusercontent.com/35357409/144723914-2e633693-9a71-4eb7-899c-0fe03410d004.png)

Sean has had a bit of trouble with the compiling scripts due to missing tags/labeling inconsistencies with the current release. 

Also, the name of the branch use to be just a `v#.#.#` instead of including the` bforaritsts_`

Here is the current release branch missing either the tag or branch name:
![image](https://user-images.githubusercontent.com/35357409/144723979-9fa204e7-b18d-4ac8-b436-588e1bc49acd.png)

So ideally, either having the branch with the consistent numbering or a tag with the consistent numbering would mean easier compile from the Mac side. 

We probably should keep these consistent and tidy.

**Comment by seanr** [comment]
You can leave the branch as is, I think, but give it an actual tag of `v3.0.0`.

**Comment by ReinerBforartists** [comment]
Ah okay. For now it's too late. But i will keep this in mind for future releases. Sorry for the trouble :/

**Comment by ReinerBforartists** [comment]
I will close this now since there is nothing we can do really. But i have added it to my records. Future versions will follow the v.x.x.x pattern again.
