### ISSUE TITLE
Sequencer - Missing operators from GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2805]
![PureRef_ZnpfnpMV7Y](https://user-images.githubusercontent.com/35357409/144728634-ee5948a8-a71e-4d68-b59d-eb1d530ed7bc.png)

The Range sub-menu is missing from the View menu of the Sequencer. 
The range has a number of frame range operators, and only one is available in the GUI under the right click. 

**Goal:**
Expose these operators to the View Menu in the header. 

**Version:** Bforartists 3.0.0

**Comment by Draise14** [comment]
I'm downloading the latest Blender 3.0 and 3.1 daily to see if it's actually deprecated or just hidden.

**Comment by ReinerBforartists** [comment]
Seems that the navigation sub menu is also missing.

**Comment by ReinerBforartists** [comment]
Ah, seems that one of the merges has kicked out our implementation. I had the navi menu separated, including the range sub menu ... Is now at its place again :)

![navimenu](https://user-images.githubusercontent.com/13919702/144840760-6fee8c0e-0401-4f6f-8094-5460b40787b4.jpg)
