### ISSUE TITLE
Properties Editor - Improve "Transparent" tooltip to be more explicit about "Transparent Background"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2812]
# Request
![image](https://user-images.githubusercontent.com/35357409/144872416-fe6ee4e6-418a-4487-9385-487b27ace472.png)

A user or two have asked me about where to find the transparent background toggle - since in Blender tutorials it's usually elsewhere (under film). 

It's in an obvoius place, but maybe now the title may need some more obviousness. One of them suggested "Transparent Background" in the label to make it more discoverable in the file output panel.

**Comment by ReinerBforartists** [comment]
I am no friend to even name it different. Then it's even harder to find. 

Maybe we could add a label on top of it. But with what name then?

**Comment by ReinerBforartists** [comment]
I'll add the following label above the prop here.

Render transparent Background

**Comment by ReinerBforartists** [comment]
Hm in Cycles we have a problem with that. Here it is a subpanel. We cannot add a label above it.

Makes me think if we even want to change something here. The prop needs to have the same name everywhere. And we cannot rename it since this would break compatibility with Blender.

![cycles](https://user-images.githubusercontent.com/13919702/144995445-1a0ca2e8-341a-442b-963e-bbe3158f77d2.jpg)

**Comment by Draise14** [comment]
True, best not change anything in the API level. This is a low priority thing. Mainly because people coming in from Blender have old habits. 

Maybe this could just be explained more in the tooltip? 

"Sets the world background to transparent" etc.

**Comment by ReinerBforartists** [comment]
A tooltip can always be improved :)

**Comment by ReinerBforartists** [comment]
Let's have a look at this nerd tooltip ...

**Comment by ReinerBforartists** [comment]
Fixed
![transparent](https://user-images.githubusercontent.com/13919702/145382107-f7cf84cb-6c0e-44df-bb4f-b2ee43545eb6.jpg)
