### ISSUE TITLE
Add Bforartists to Steam

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2813]
Another user mentioned adding Bforartists to Steam, to get automatic updates and notices when things could download. It could also open Bforartists to another market. 

To do this, I am not sure what the process is, or if it would be worth it. But it might be worth investigating.

**Comment by ReinerBforartists** [comment]
I once had a look at it. The outcome was that the GPL is not compatible with the steam license. Don't ask me why then Blender is available there ...

**Comment by Draise14** [comment]
Ah yeah. Curious. The market share there may be smaller too. I think the key point is the user wanted a system for automatic updates, which Steam provides.

**Comment by ReinerBforartists** [comment]
Yeah. Steam is a nice way to distribute Blender. That's also a weapon of marketing. Have the download at as many places as possible. We have just a few such places. So steam would be a nice dream ...

So, what shall we do here? I am not really happy to wear yet another burden around ^^

**Comment by Draise14** [comment]
Let's close it for now. I'll keep it in the back of my mind once we hit 10,000 or 20,000 downloads a month or something. Then I'll think of someone.

**Comment by iyadahmed** [comment]
Hmm but releasing to steam would make downloads go up I think, more publicity, we can give it a try at least

**Comment by Draise14** [comment]
At least know how it's done. True.

**Comment by ReinerBforartists** [comment]
Is this issue now open or closed? ^^

**Comment by Draise14** [comment]
Never mind! I have closed it.
