### ISSUE TITLE
HIP binary kernal for graphics card not found - works in Blender 3.0, not Bforartists 3.0.0

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2814]
![image](https://user-images.githubusercontent.com/35357409/144873024-29c2fb9e-e313-4082-b49d-1df84de2dd1d.png)
![image](https://user-images.githubusercontent.com/35357409/144873046-8c814dbb-a522-49ae-ac7f-9f4eeba34999.png)

In Blender 3.0, you get HIP devices to render with cycles, but we seem to have a bug with Bforartists 3.0.0. The kernels are or the dependencies for them are not compiled with the latest. It works in Blender, but not Bforartists. 

Bforartists
![image](https://user-images.githubusercontent.com/35357409/144873574-8cd08711-9f37-472f-89c5-652ec482c65b.png)

Blender
![image](https://user-images.githubusercontent.com/35357409/144873267-c4b7d3d1-2e62-47bc-8134-a1def6f9ae7a.png)

**Comment by ReinerBforartists** [comment]
Yeah, maybe we miss something. But i have honestly no idea what. I have cycles and optix with the newest versions installed.

What OS is this from?

**Comment by ReinerBforartists** [comment]
Ah, a new checkbox. So yes, it's a cmake thing.

No bug, but simply not activated. I think we should introduce it with our next point upgrade. Makes no sense to rush here. We first need to test this one out in the dev builds.

![hip](https://user-images.githubusercontent.com/13919702/144887607-db2b2499-ffab-44ce-bb66-346a4eec3d09.jpg)

**Comment by ReinerBforartists** [comment]
HIP is now activated in the devbuilds and works trouble free. And it will come with the next release. 

Nothing left to do here. Closing. Thanks for the report!
