### ISSUE TITLE
Website - VPN required in Turkey to access the website

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2817]
A user on Twitter expressed he couldn't access the website without a VPN from inside Turkey. He mentioned that maybe contacting the host to work around that may help. I gave him the link to Github, where he could download without a problem - but maybe there is a setting somewhere to help give Turkey some access? He liked the software, just wished it was more accessible or discoverable from where he's at.

**Comment by ReinerBforartists** [comment]
Phew, tough one. There is little that we can do against internet censorship in other countries :/

So the best bet is indeed to point at other sources. Like the github account.

**Comment by Draise14** [comment]
Yeah, thought so... I wonder why they would censor the *.de domain. 

Would other other domain pointers maybe work?

**Comment by seanr** [comment]
Maybe Erdogan just doesn't want people to use 3D software to mock him? 😂

**Comment by ReinerBforartists** [comment]
:D

**Comment by seanr** [comment]
IMO, you should get the .com if it's available anyway. Most people will
think .com long before they'll remember .de if they're just typing it.

**Comment by ReinerBforartists** [comment]
Yes, maybe. But i am not sure if a redirect won't run into the same trap then.

**Comment by ReinerBforartists** [comment]
I had a look at this again. It's the IP range that is banned. Not the domain ending. That's why a VPN can go around it. It uses another, not blocked, IP. And this means there is nothing that we can do here.

For alternative recommendations, there are pages that hosts our software too. But the best place is here at gitub or our official page.

Closing.
