### ISSUE TITLE
Custom Hotkey Panels - Add icons to Select Grouped hotkey only menu popup

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2821]
When assigning a hotkey to a custom panel that has icons, then using the hotkey to bring up the floating panel - there are usually no icons except for the pre-built ones. 

How do you add back the icons to floating panels with custom hotkeys?

![image](https://user-images.githubusercontent.com/35357409/145841775-d1b9fa14-62c0-4d5e-9c70-a772c39c9b7a.png)

Example: 
1. Assign hotkey to operator "Children" under "Select Grouped" in the 3D view Select header menu. use the hotkey `SHIFT + G` (free)
2. Go to the hotkey manager
3. Search for `SHIFT + G`
4. Remove the sub uption "Children" so it opens up the whole menu
5. Press `SHIFT + G` in the 3D view, the panel will open, but with no iconography

Are these icons built into separate menu areas in the UI files? Can they be added on the fly? Should they be built in, meaning this is broken? Is this a bug or a known issue? Does it take a lot of effort to add them back in? Where is the code for the floating menus from the header? 

So.. I guess I can boil it down to two questions:
1. Is this a known "feature" where custom floating menus don't come with icons? If it shouldn't be, should I report them when I find them?
2. If it's a known feature, how can I add icons? Where are these typically stored?

**Comment by ReinerBforartists** [comment]
You mean dynamically? I know of no way that does this dynamically. You need either an array where you pick from. Or you add the icons directly into the menu operator.

**Comment by ReinerBforartists** [comment]
Ah, wait, this is an existing enum. We could simply add icons to this menu :)

But should we really? This menu is not exposed to the UI.

source\blender\editors\object\object_select.c  , line 759

![enum](https://user-images.githubusercontent.com/13919702/145977372-d99ed19d-879f-438b-a20a-560938597a8c.jpg)

**Comment by ReinerBforartists** [comment]
Yes, you need to compile. To add these icons is a thing of five minutes though. They all exist already. Let me do this quickly ...

In case you have more of such dialogs, keep them coming.

**Comment by ReinerBforartists** [comment]
Fixed in master

Please make a new issue in case you find other menus that needs icons.

![selectgrouped](https://user-images.githubusercontent.com/13919702/146046905-af3a7cc0-0523-47a0-82ae-649ac531ae04.jpg)
