### ISSUE TITLE
Modifier Stack - Geometry Nodes - Align sliders to center consistently

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2823]
![image](https://user-images.githubusercontent.com/35357409/146039786-e4e6680b-79f6-498f-9aa1-10dbdce4a6ec.png)

Right now the Geometry Nodes modifier stack text alignment is a big mess. Some are center aligned, others are left. 

It would be nice if custom input and output attributes are all aligned to the correct method - to the left.

**Comment by Draise14** [comment]
Ah, there is a task for this already.

 #2533
 
 I guess I will change this to allign the sliders

**Comment by ReinerBforartists** [comment]
Where is this? O_O

**Comment by Draise14** [comment]
When you make a Geometry Nodes modifier, THEN use custom input attributes, you get this kind of mess. These are attribute inputs from a single GN modifier in stack. 

![image](https://user-images.githubusercontent.com/35357409/146047047-9edcc13d-3d50-4564-82f5-250d10f832a8.png)

**Comment by ReinerBforartists** [comment]
Could you please show the whole UI? I have still no idea where this appears :)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/146048089-f8b5010c-eb5a-4b4c-9fbb-5938cc0d46eb.png)

Here you go. Custom Input for the Group Input of a Geometry Nodes tree. They show up in the modifier stack like this.

**Comment by ReinerBforartists** [comment]
Sheesh. This goddamn noodles ...

**Comment by ReinerBforartists** [comment]
Aww, i wanted to fork a 3d software, not a programming with noodles software :D

Okay, reproduced. Thanks for the images Draise :)

So the inputs shows in the modifier too. Oddly enough, not everything. I need to document this i guess. I am not sure though if i can catch this one.

![inputs](https://user-images.githubusercontent.com/13919702/146050092-e9825dac-8f4b-45e8-92c7-46090864abc6.jpg)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/146051005-255a7bb8-20ff-48f9-a44c-8ab72ccdaea7.png)

Yeah, I used to be afraid of it - geometry nodes, but for some things.. this is a single curve and now I can generate my painterly bridges instantly. Worth using for the art. Much easier than writing addons and pure code.. MUCH easier. 

_But yeah, it needs a tonne of higher level node groups to really be useful, like Erindales Toolkit, or Bagapie, or even Bygen. All addons that add higher level UI's or node groups to Geometry Nodes. We could do the same with the Asset packs in the future._

**Comment by ReinerBforartists** [comment]
Okay, who ate the python term here? O_O

![python](https://user-images.githubusercontent.com/13919702/146184170-9df0a93d-21be-46e2-b938-54799be34486.png)

**Comment by ReinerBforartists** [comment]
I fear my c fu is too weak here. I found the switch where the middle aligned props gets added. But i cannot find a way to align them left. All i manage is to make it worse ^^

source\blender\modifiers\intern\MOD_nodes.cc

![unsolveable](https://user-images.githubusercontent.com/13919702/146187245-af9d0346-adc9-4d20-b83f-1ee536c094b8.jpg)

**Comment by Draise14** [comment]
Do you think this is worth reporting to Blender? "Line up buttons and sliders"

**Comment by ReinerBforartists** [comment]
Could be. But this is UI design. So they will most probably decline it :)

**Comment by ReinerBforartists** [comment]
Hah, gotcha! One little line. This content is explicitely aligned right. The only thing that i cannot catch is the string edit box. But this is a marginal flaw.

![left](https://user-images.githubusercontent.com/13919702/146765540-0a7baa1f-72b0-4147-a93a-21c65e8b468e.jpg)
