### ISSUE TITLE
3D View - Edit Mode - Add Legacy sub-menus or make the legacy operators consistent in Context Menus

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2825]
# Proposal
In the forums we got a user requesting a legacy operators from the context menu in edit mode. I have also had this requested numerous times in Discord from numerous users. It apparently can be a defining feature request that makes people not want to adopt Bforartists. 

So.. I would like to propose a compromise:

**Add a Legacy Submenus or make operators consistent in order and own "group" in the Edge, Face and Vertice right click edit mode context menus.** 

So here is the argument to why:
1. Users from other software are familiar with the edit mode context menu and the legacy operators
2. We currently have SOME legacy operators in the context menus, but not all, and it's inconsistent. 
3. This has been pointed out and requested a few times, one time, ok - but a few form different artists? Maybe we should take a look at it. 

## Current State
In the Edge Context menu, we have 3 legacy operators exposed. Out of order, but exposed. Could be re-ordered. 
![PureRef_24JxC87EXd](https://user-images.githubusercontent.com/35357409/146378607-f9fdb200-c725-4471-ab1b-f13081b47078.png)

In the Vertex Context menu, we have one operator exposed. The others are not. What's the criteria? Maybe we could add in the sub-menu for "Legacy" and clean that up to "show" that it's a redundant tool and best to use the toolshelf. 
![PureRef_6LEfyUgmgR](https://user-images.githubusercontent.com/35357409/146378685-1c3fe0e5-e4e0-4d78-9215-376c4e6c601f.png)

With the inconsistencies from the other context menus, this one operator has caused some users to talk out about it. The other times I didn't report, knowing the philosophy - but it may need some finessing to be consistent with the other context menus eitherway. We can "be for artists" here with some kind of solution. 
![PureRef_Obexy7ohSs](https://user-images.githubusercontent.com/35357409/146378823-e37e13c0-611d-41de-bf9a-3f149ee34336.png)

# Potential Tasks to resolve:
**Option 1**. Add the "Legacy" sub-menu to the context menus so nothing is missing and it's all consistent. Move any existing legacy operators into the sub-menus so they are no-longer top-level in the context menu, but still discoverable and "accessible" to user who are familiar with this workflow from the majority of other software. 

**Option 2.** Group the existing legacy operators into their own separated group in the context menu and make sure order is the same as the header. Expose the Inset Face Legacy operator into own group also at top level of the Face Context Menu only. Make it more clear they are separate and legacy by the grouping and order. 

**Option 3.** Group top level legacy operators (option 2) AND add the other legacy operators into a sub-menu called "Legacy" (option 1) into context menus. Only expose the Inset Face in the sub-menu in the face context menu as top level, everything else can remain as is. 

**Option 4 (additional).** Be more explicit in the tooltip that the operator is "Legacy" and can be found in and used from the toolshelf. 

All in all, just make the UX more consistent and exposed when it comes to these operators to the right click menu, by putting emphasis either in sub-menu, tooltips, grouping or consistency with what's legacy legacy - since we can't use the toolshelf ones from the context menu and a few users have old habits.

**Comment by ReinerBforartists** [comment]
Well, yeah, we could put the legacy content also in the rmb menu. This would mean though also to put Bevel Vertices into such a legacy sub menu in the rmb menu.

Truth is, i don't care about this menu. When it's about me then i would completely remove it. To keep it was already a compromise. Please don't ask me to make it even nice now. I hate it ^^

**Comment by Draise14** [comment]
I can commit this one for you, no problem. Just gotta pick the solution. 

This is more for the other users who have requested it. I don't use this menu if at all either, but old habits from other software die hard - and being somewhat familiar to some degree is still hitting our goal to be artist friendly. 

The latest user has a point, both Cinema 4D, Max, Maya and Blender all have the Inset Face in the context menu.

**Comment by ReinerBforartists** [comment]
Yeah, but we are Bforartists. And we want to remove bad old habits :)

And yes please. I don't even want to think about this menu. I am green with every solution here. As long as i don't need to touch it ^^

**Comment by Draise14** [comment]
![bforartists_4CxqNVIXci](https://user-images.githubusercontent.com/35357409/147611833-444748b7-e1c2-41bb-9872-c0e9fb14b59e.png)

Ok! Done. Improved the consistency, order and grouping of legacy operators in the context menus of Edit Mode. 

- Added legacy operator "Inset Face" for consistency
- Grouped legacy operators with separators to make sure they are consistently grouped
- Improved order of operators to be consistent after the legacy operators (and in the correct order of grouping)

**Comment by Draise14** [comment]
I forgot the procedure, but I have labled this as 1-Fixed and commit to branch and requested a pull request with the names. 

I assume I can close this to say this is done? And if there needs to be changes, we reopen? 

Hopefully all is well. Happy New Year you all!

**Comment by ReinerBforartists** [comment]
Hm, something went odd here. Where is the code? ^^

**Comment by ReinerBforartists** [comment]
Got it. It remains odd that the code did not show in the pull request. Hm.

Either way, the changes are in the master. Many thanks. I'll clean up the branch now :)

**Comment by ReinerBforartists** [comment]
Hah, no. Draise, can it be that you made a merge after your changes and killed the changes with that then? The only change that arrived is an update for a comment^^

**Comment by ReinerBforartists** [comment]
Hm, but inset Face arrived in the menu. Where is this commit ? O_O

**Comment by ReinerBforartists** [comment]
Ah, it's in the merge pull request part then ... 

All well, all there. Closing again. Sorry for confusion ^^
