### ISSUE TITLE
Geometry Nodes - Compare node in Toolshelf pulls an error and doesn't work

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2826]
![image](https://user-images.githubusercontent.com/35357409/146453188-82d85289-becb-486f-b6a7-580790c27200.png)

![image](https://user-images.githubusercontent.com/35357409/146453219-be4d3d85-afdd-44a5-b068-8f30d66c1061.png)

The Compare node from the toolshelf in the devbuild is currently broken for some reason.

**Comment by ReinerBforartists** [comment]
Fixed in master
