### ISSUE TITLE
Loading a default asset library 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2832]
@iyadahmed pointed me towards the bpy.app.handlers for our default asset library problem. I cannot see at the moment though how this could help us with our dilemma. This thread is to investigate exactly this.

Ideally we would have a button in the asset browser that loads us our default library, stored in a location that is writable so that the user can extend it if he wants to. The appdata directory is usually writable for exactly this purposes.

https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.load_post

**Comment by iyadahmed** [comment]
> @iyadahmed pointed me towards the bpy.app.handlers for our default asset library problem. I cannot see at the moment though how this could help us with our dilemma. This thread is to investigate exactly this.
> 
> Ideally we would have a button in the asset browser that loads us our default library, stored in a location that is writable so that the user can extend it if he wants to. The appdata directory is usually writable for exactly this purposes.
> 
> https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.load_post

ah it would help in automatically loading on startup without a button

**Comment by ReinerBforartists** [comment]
But this would conflict then with libraries that you want to use internal in the current blend file :)

Not this easy ...

**Comment by Draise14** [comment]
Good lord, this is a tricky one. 

The library paths are stored in `userpref.blend` file, overwriting this or modifying this would save the custom libraries. So the pack downloads and installs to the Bforartists or custom location, and the addon or button would run the rest when the user want to configure the libraries. So.. 

**Example:**
1. Download/Extract library with installer to path, either included with Bfor or seperate. 
2. The libraries that come with Bforaritsts are installed/extracted to the SYSTEM path in a sub-folder. 
3. In Bfor, press button and the userpref will automatically populate the Preferences settings with the dynamic paths from SYSTEM. It will also force save preferences so settings stick. 
4. Now you have the user pref have the correct absolute paths in the library and configured correctly in the userpref, but written by the dynamic python SYSTEM variable to get the correct absolute path relative to Bfor installation. 

This is a similar workflow to how Unreal Engine works, it has the libraries in SYSTEM, and you can optionally create projects with those libraries, which would get copied to the new project folder to local preference. In this case they would just be configured once in the library paths of Bforartists directly from the SYSTEM (Bforartists installation directory) folder.

**Comment by ReinerBforartists** [comment]
We could make our life easy and simply offer the libs as an extra download. But that's unelegant.

All we really miss is an additional path in the user preferences. Or a way to add it by code. Then we could install our inhouse library for example in the appdata path. And all the user neeeds to do is to activate this lib in the asset library dropdown then. It would remain writable in the appdata folder. But the Blender file dialog doesn't even allow to navigate to this path -.-

The second option here would be to pollute the user's documents folder with our bforartists library. But this one happens just over my cold rotting body. I hate it when a software does this ^^

Question, are there already user libraries in the wild? How do they deal with the issue?

![noappdata](https://user-images.githubusercontent.com/13919702/147332796-838bbceb-a1ea-4d10-8fab-21d839b10146.png)

**Comment by ReinerBforartists** [comment]
Ah wait, this is a hidden directory ...

So we are back at the additional* path problem. I think i failed at this one before. But i tried to add it directly in the C file. Maybe this can be solved by python instead.

* I don't want to remove the original path to stay compatible with Blender.

![showhidden](https://user-images.githubusercontent.com/13919702/147333430-5752c3ea-3b48-4520-80eb-bdc0fa775395.jpg)

**Comment by Draise14** [comment]
Software that have libraries usually ask where to put the libraries to a custom path with a default suggested path in the installation dialogue. 

I would prefer the defaults with the one installer too.

**Comment by ReinerBforartists** [comment]
Users wants the default library usually available immediately. So installing isn't really an option imo :)

**Comment by Draise14** [comment]
Yeah I mean with the unpacked Bforartists/installation. Yeah. Like in true space or substance.

**Comment by ReinerBforartists** [comment]
Yes, trueSpace had it onboard :)

**Comment by ReinerBforartists** [comment]
The current asset API is lousy thin ...

https://docs.blender.org/api/current/bpy.ops.asset.html

**Comment by ReinerBforartists** [comment]
I have still no idea how we could tackle this :/

**Comment by iyadahmed** [comment]
Maybe people on bpy server have more ideas,
https://discord.gg/pQzvfSmRKe

**Comment by ReinerBforartists** [comment]
It's not so much a question of an api. But i still struggle with the paths at all ...

**Comment by iyadahmed** [comment]
Ah ok

**Comment by ReinerBforartists** [comment]
The easiest solution would be still an external lib to download separately. No code required ...

**Comment by ReinerBforartists** [comment]
Ah this is cool, even with script. Yay.  If he wants to implement the rest into bfa too, i would be happy. And we could add yet another name to our committers list :)

Remains the path dilemma. We might want to move the libs around. A zip might work. But the programs directory is write protected at Windows. 

I will most probably not do anythin bfa related anymore this week. But maybe i'll find some time next week.

**Comment by Draise14** [comment]
The USER path can also be used and written to and from LOCAL, so we could also read and write form the zip or windows default local path to user path. This USER path is dynamic per system. Or we could prompt an opt in and choose custom path from a prop that will copy from LOCAL that comes with the download. 

I'll try that experiment tomorrow. No rush! Take it easy.

**Comment by ReinerBforartists** [comment]
Just that i have asked, does this method then store the loaded lib file into the current blend file? Because this should be avoided ...

**Comment by Draise14** [comment]
No. It only configures the library paths for the asset browser. This would be saved only in the `userpref.blend `

**Comment by ReinerBforartists** [comment]
I will wait what you figure out here. I have my head somewhere else at the moment :)

**Comment by ReinerBforartists** [comment]
I wanted to make a first asset library version out of the mini lightlib addon. Just to stumble across the fact that the asset browser cannot mark collections as an asset -.-

I really hope that they work at this. Hierarchical objects as an asset is vital.

**Comment by Draise14** [comment]
It can but it's the expanded asset experimental mode. Which .... I think should be activated by default.

**Comment by ReinerBforartists** [comment]
Ah i see. This is a good news since this means they work at it. Thanks :)

**Comment by Draise14** [comment]
I guess we have to wait for 3.1. last commits for the asset browser added placement widgetd for the collections.

**Comment by ReinerBforartists** [comment]
Yes. It's not this far away. The usual three months ^^

**Comment by ReinerBforartists** [comment]
3.1 hasn't brought any relief from what i know. So what shall we do here? Cancel the idea? Wait for two more years?

**Comment by Draise14** [comment]
Code works. Copying to USER from LOCAL (download zip), registering the library, saving the library prefs. I have also worked methods to check if library exists, renaming libraries and more. 

We just need libraries now and to wait... for collections. Rumour has it that 3.2 or 3.3 will allow collections. We currently have mesh data and node groups per default. 

I'd say keep the dream open and implement in pieces per default library types.

**Comment by ReinerBforartists** [comment]
Okay, let's keep it open :)

**Comment by Draise14** [comment]
Ok, collections are official now. Maybe making some test libraries to ship and make a button to install libraries or a second downloadable pack.

**Comment by ReinerBforartists** [comment]
It's a shame how the development of the asset browser has slowed down. They have relased it in a state where most users will prefer the traditional libraries and linking/appending over what we have at the moment, and then simply stopped. Sad.

**Comment by Draise14** [comment]
They have a Gsoc to try add drag and drop to the outliner - and I know there might be code for tag colours, but yeah... Sometimes I debate finding code that would make the UX better from addons I've seen (as talked in Discord) but yeah.. maintenance.

**Comment by Draise14** [comment]
Will work this for next release, not this one.

**Comment by Draise14** [comment]
Ok, will first work some simple light libraries first before this task.

**Comment by Draise14** [comment]
Did some research on this one today:

1. Found a way to theoretically download files from somewhere online 

> **Downloading files with Python**
> `import requests`
> https://likegeeks.com/downloading-files-using-python/ 

2. Found a way to detect if library exists then register _(no longer needs to check name to add, thanks Blender devs!)_
3. Found a way to copy libraries from one place to another (to ship with one then copy to a user folder if necessary)

```py
import bpy
import os
import shutil

from pathlib import Path


# System Paths for later
user_path = Path(bpy.utils.resource_path('USER')).parent
local_path = Path(bpy.utils.resource_path('LOCAL')).parent
system_path = Path(bpy.utils.resource_path('SYSTEM')).parent

test_path = Path('E:\\\\3D stuff\\Bforartists\\Development\\Addons\\Addon-Default-Libraries\\')

print (user_path)
print (local_path)
print (system_path)
print (test_path)

shutil.copy(str(test_path)+'\\DEFAULT_LIBRARY.blend', str(test_path)+'\\Target\\')
shutil.copy(str(test_path)+'\\blender_assets.cats.txt', str(test_path)+'\\Target\\')

print("Copied")



### SET NAME of library by path name iteratively 
# First check if it exists
for x in bpy.context.preferences.filepaths.asset_libraries.items():
    path = x[1].path 
    if path.endswith("Target"): 
        print("Found, will do nothing")
        variable = True
    else:
        print("Not found, let's register")
        variable = False

# Now that we did the check, we register it, or not. 
if variable == True:
    print("Already exists")
else: 
    print("Nope")
    bpy.ops.preferences.asset_library_add(directory=str(test_path)+'\\Target\\')        

bpy.ops.wm.save_userpref()```

Here are my test files:
https://github.com/Draise14/Addon-Default-Libraries

Now comes some design decisions:
- What libraries should ship with Bforartists per default? Would it make sense compiling one with the distro?
- Should we allow opt-in downloads of more libraries hosted on a Bforartists server or repository? 
- If shipped with the installer, should these default libraries register on user opt-in or be registered on first load? 
- Or do both, have the opt-in extra libraries and a shipped default library that's already registered (preferred?)

If it's opt-in, I could make an addon that could also ship to Blender and pull something third party, but be supported by Bforartists (shipped with it).

**Comment by ReinerBforartists** [comment]
Mh, does Blender have some additional content in the cloud meanwhile?

a) i would at least love to put the current content into such a library. We have materials and the mini lightlib content.
b) don't overdo. We provide the software, not assets.
c) on first run, given that it is our default lib. This would users also allow to work with this lib for their own needs.
d) see b ...

**Comment by Draise14** [comment]
Cool, that clarifies what to do. I will make a default library to ship and nothing else. I will make it as light as possible, but relatively complete. I'll take a look at blender resources too to see if it's worth having. They don't technically ship any libraries, only demo files, but things could be good. 

I'll focus on converting the light library and the VX material library first. I already have the VX library as assets to some degree, now it's organizing and consolidating and making sure it's light and working well. 

I'll make a new task for it.

**Comment by Draise14** [comment]
As mentioned in #3094, it is too close to a release meaning I will have to postpone for next release.

**Comment by Draise14** [comment]
This will be useful. Someone made a method we could adopt a little. 
https://gist.github.com/BlenderDefender/783a50a267a64e1610cbf636e90005d9

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/181419661-da303345-244b-4577-bfff-da79b3d6a41b.png)

Ok.. library registering with the addon template, nice.. but no tags nor categories.

**Comment by Draise14** [comment]
![dtQmmn76uv](https://user-images.githubusercontent.com/35357409/182688643-2dde11d3-c662-4b2a-978c-d81bb8a7ae77.png)

When on, it registers the library
When off, it removes it. 

The library is stored in the addon folder structure.
