### ISSUE TITLE
Linux - cmake boost warnings 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2835]
When compiling with linux we have some warnings since a pretty while that the newest boost version may not be compatible. I seem to remember that our cmake file is not the original Blender cmake file, which could explain the warning messages. Needs investigation.

![cmakeboostwarnings](https://user-images.githubusercontent.com/13919702/147381525-779d388f-12e7-4f83-8a59-1f0925893a40.jpg)

**Comment by ReinerBforartists** [comment]
Hm, Blender limits the version to 1.48 still. Which explains the moaning. We have removed the versioning number in the cmake file.

\build_files\cmake\platform\platform_unix.cmake

Left Bforartists, right Blender

![boostproblem](https://user-images.githubusercontent.com/13919702/147416423-614bce6a-577f-42f7-b5d9-8ddf4c1eca89.jpg)

**Comment by ReinerBforartists** [comment]
Hm, i have readded the values, and still we get the error message.

**Comment by ReinerBforartists** [comment]
naetherm means this is not the code, but Cmake. We still use Ubuntu 20.04. And this has maximum Cmake 3.16. Which may simply be too old to know the new boost versions ...

Either way, while we cannot fix it, it does no harm. So let's close it as known issue.

**Comment by ReinerBforartists** [comment]
Markus said that i should keep this task open. So reopened :)

**Comment by iyadahmed** [comment]
btw this also happens with Blender
![image](https://user-images.githubusercontent.com/25552173/175989536-70f7026b-865d-47ba-be81-7bc508f7ab8e.png)

**Comment by iyadahmed** [comment]
If i remember correctly this is a known issue to Blender devs

I'm running on a new ubuntu based distro same error happens for Blender and us

**Comment by iyadahmed** [comment]
I guess they chose to ignore it, will ping them in blender.chat

**Comment by iyadahmed** [comment]
![Screenshot_2022-06-27-22-18-27-62_6c2112e95a10afaab76cfa27a6d42c7b.jpg](https://user-images.githubusercontent.com/25552173/176028391-b9da7611-f1f4-4822-8cbe-b0032db6bc6b.jpg)

**Comment by iyadahmed** [comment]
https://stackoverflow.com/a/67720009/8094047

**Comment by ReinerBforartists** [comment]
I finally vote to close this issue. The warning does not harm. And doesn't really justify to modify the code. Every difference between the code bases makes it harder to maintain

**Comment by iyadahmed** [comment]
agree, let's close it, it is not really an issue, it will happen with any software if you use a different version of cmake than what boost expect
