### ISSUE TITLE
Hotkeys - Asset Browser tweak drag and drop conflict with box select

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2843]
![bforartists_KZMAYuK5JA](https://user-images.githubusercontent.com/35357409/147632349-3f4e19c0-6e40-4cca-a979-d99bbc645a2f.png)

Currently with the Bfoartists keymap, we have `LMB Tweak` to box select AND to drag and drop assets. Every now and then the box select works, the drag and drop breaks, and it becomes frustrating. 

When you disable the `LMB Tweak` to box select, then this is resolved. But now box select would need to be a modal (As it already is with `CTRL+LMB Tweak` and to `SHIFT+LMB Tweak` to subtract or extend respectively). 

![bforartists_Xd41hRZ3nF](https://user-images.githubusercontent.com/35357409/147632460-b14daccf-a29a-4dda-8ae1-091bfd7caf53.png)

This may need looking at. Either removed or remedied somehow.

**Comment by ReinerBforartists** [comment]
This also happens with Blender. I already checked. But forgot to make an issue then for it. So thanks for making the issue :)

**Comment by ReinerBforartists** [comment]
This one is a mean one since the asset browser is also the file browser. So no easy fix possible. I would vote for reporting this to the Blender developers.

**Comment by ReinerBforartists** [comment]
Let's have a look if i can come up with a solution here ...

**Comment by ReinerBforartists** [comment]
Mouse Left Click-drag seems to do what we want. No box select with dragging the asset around so far.

@Draise14 , could you be so kind and test if it works without side effects? I haven't found any yet, but you never know ...

![clickdrag](https://user-images.githubusercontent.com/13919702/147914356-db615795-0dc3-49b3-b270-7423ccabb102.jpg)

**Comment by Draise14** [comment]
I'll test after I'm back from my holiday. I'm back on the computer the 11th. 

Haven't had a holiday inn 2 years! 

But by the sound of it it looks like an elegant fix without removing anything.

**Comment by Draise14** [comment]
I'll test after I'm back from my holiday. I'm back on the computer the 11th. 

Haven't had a holiday inn 2 years! 

But by the sound of it it looks like an elegant fix without removing anything.

**Comment by ReinerBforartists** [comment]
Yeah, fingers crossed :)

And happy holidays :)

**Comment by Draise14** [comment]
Ok! Tested. Fixes things! A lot more predictable UX. Beautiful.

**Comment by ReinerBforartists** [comment]
Then let's commit it :)

**Comment by ReinerBforartists** [comment]
Fixed in master
