### ISSUE TITLE
Addon - Minilightlib - Add Eevee contact shadows per default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2854]
![bforartists_e7bOxjIAMD](https://user-images.githubusercontent.com/35357409/149022087-89ae2239-79fd-4584-b8ab-d4c793563666.png)

I tried out the new eevee presets from the mini-lightlib addon updates - which is really nice. I have noticed though, that the contact shadows are disabled. It's probably best to also turn that on. 

_Side note, I pushed this to the socials for next week, so people can see a taste of what comes with Bforartists. They eat this up, I hope we can get the default library system sorted.._ 

![PureRef_mbPRBciyvL](https://user-images.githubusercontent.com/35357409/149022341-45cc37aa-a065-43c7-8333-05e808f06724.png)

**Comment by ReinerBforartists** [comment]
The contact shadows caused issues, so i turned them off :D

But okay, let's turn it on again :)

**Comment by ReinerBforartists** [comment]
Fixed
