### ISSUE TITLE
File - Help - Blender Python API Reference points to old documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2855]
![image](https://user-images.githubusercontent.com/35357409/149177038-9261cbb7-9167-4cba-bb2f-0a9b87ea294c.png)

The current link goes to 2.78 API reference, which is an "old" master. 

The most recent API is located here:
`https://docs.blender.org/api/master/`

The link should probably be updated.

**Comment by ReinerBforartists** [comment]
Aand fixed. 

Good catch :)
