### ISSUE TITLE
Download - The dev build triggers a trojan warning from the ZIP with Bitdefender

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2856]
![image](https://user-images.githubusercontent.com/35357409/149551038-b6423ed1-e106-4086-ab0c-b776d38cf2c2.png)

A user found this warning from the dev build - probably because we are not registered. We should be fine right? But thought to report it regardless.

**Comment by ReinerBforartists** [comment]
Yes, it's a false positive. Please report it to Bitdefender.

datatoc.exe is by the way the exe that is needed to create the icons while compiling. Moving it to quarantine should not affect the functionality of Bforartists.

**Comment by ReinerBforartists** [comment]
I have reported it as false positive now. Let's have a look at the outcome.

**Comment by ReinerBforartists** [comment]
I haven't got any response until yet. Which is a good sign. In case of a true problem they would have mailed back. I will most probably not receive a further mail anymore. They usually fix the false positive, and that was it. Fingers crossed that they meanwhile did.

I will close this issue now. I will nevertheless report back in case i will get a notification from Bitdefender.
