### ISSUE TITLE
Merge conflict with Create new Scene from Outliner

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2858]
I run into a merge conflict at the moment that i cannot resolve. And so i need to revert the changes for now. 

Background: Blender devs did change the outliner_tools.cc file. And this kills our right click menu entries to create a new scene. 

The curious part is, this menu seems to be dysfunctional for a bit longer already. The rmb menu doesn't show the entry anymore in the version from last week already. Good that we have the content in the header too ...

Related task was this one https://github.com/Bforartists/Bforartists/issues/2792

@iyadahmed , do you want to have a look at this tomorrow? I need to remove the code now, finish the merge, and upload the changes to the master first ...

We could alternatively also of course just leave it the way it is. But i remember that Draise needed the new scene functionality in the rmb menu.

![scene](https://user-images.githubusercontent.com/13919702/149670882-b739fb8f-d21e-43aa-92f1-6d42543276fc.jpg)

![outliner](https://user-images.githubusercontent.com/13919702/149670841-168c405a-493e-4dfb-93f2-21cccc6b2add.jpg)

**Comment by iyadahmed** [comment]
Hi, taking a look now

**Comment by iyadahmed** [comment]
I think it is missing `typedef` where the redmark is
![image](https://user-images.githubusercontent.com/25552173/149671059-ce3d274e-f394-48d5-9970-b081d2e10e25.png)

**Comment by ReinerBforartists** [comment]
Please give me a few moments. I first need to upload the newest merge files ^^

**Comment by iyadahmed** [comment]
ok no problem

**Comment by ReinerBforartists** [comment]
Ah, a missing typedef. Let me try to fix that then first. You would need to start from scratch while i simply can throw in the old code again ...

**Comment by iyadahmed** [comment]
ok

**Comment by ReinerBforartists** [comment]
Ah, i am stupid. The rmb menu entry never contained the NEW menu item. 

This means this task is fulfilled. To add back the missing typedef did the trick to compile without errors. Many thanks iyad :)
