### ISSUE TITLE
Shader and Compositor editor - make the sidebar content consistent with the add menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2861]
We had this issue already, and had it closed again. Because back in those days i couldn't convince myself to really change it.

When i initially made the sidebar in the shader editor i thought it is a good idea to have the most used nodes at the top, easy to reach. What i haven't thought of is the consistency problem that arised with that. Two different structures is one too much. And instead of making the search easier it made the search harder in some circumstances.

So i propose again to make the sidebar consinstent to the add menu. We cannot and should not change the structure of the add menu though. This would make too much trouble with staying compatible with Blender and with every merge in this area. So it's really the sidebar that has to change.

After that we can think of a strategy to make the most common nodes better recognized. Which i have one or two ideas for. But for now we simply need to make everything more consistent again.

![nodesdilemma](https://user-images.githubusercontent.com/13919702/149905939-d47b3848-f2f4-480b-95b1-656c8df010fa.jpg)

**Comment by ReinerBforartists** [comment]
Wise decision. Catched already three missing buttons in the sidebar ...

**Comment by Draise14** [comment]
Yeah this has slowed me down a little. It's either one or the other as a UX as is.

Good call.

**Comment by ReinerBforartists** [comment]
This was part one. 

I tried to make the switchpanel between icon and text buttons headerless. But ran into the problem that then the add tab is the active one. And not longer the tools tab. Seems that headerless is internally treaten first abover everything else. Sad. Headerless saved 20 pixel, and looked much better. Anyways.

Now for part two. This requires a few more experiments ...

![consistent](https://user-images.githubusercontent.com/13919702/150300821-279f01bf-ed7b-427c-94eb-4b518f5a340e.jpg)

**Comment by ReinerBforartists** [comment]
Second step. Added a common nodes switch.

In case somebody makes a list i would implement the same for compositor and geometry nodes. I have not enough experience in this areas to decide what node is really common. And especially the geometry nodes is a crazy system that becomes more and more useless for the average user. I would need help here.

But this is another task then. This task here is solved.
