### ISSUE TITLE
Outliner - Make Object Contents icon different to the object 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2863]
![bforartists_rL3NXUedDh](https://user-images.githubusercontent.com/35357409/150643780-d49846c2-547f-4c32-819b-a5c95e6accd7.png)

In the outliner filters, you can show objects, and it's contents. But they are the same icon. This has confused me. This may need a different icon. 

A suggestion is using the modifiers icon.

**Comment by ReinerBforartists** [comment]
Well, it both belongs to the object. And this is the object icon.

**Comment by Draise14** [comment]
Yeah. I know the context... But at first it was hard to find initially. Always slows me down. It's a low priority change though. No worries.

**Comment by ReinerBforartists** [comment]
Again, why should i change it? And what especially is slowing you down here? An icon is an icon :)

**Comment by Draise14** [comment]
Because of confusion, not sure which was objects and which were contents, so it slows things down because they are the same icon.

**Comment by ReinerBforartists** [comment]
A change should not be done for the sake of a change. And i still miss the valid reason here. It is clearly in a hierarchical order. And both belongs to object. I would be confused by a different icon here.

**Comment by Draise14** [comment]
Ah ok. Valid enough. 

I guess my association with the contents is contraints, modifiers and materials. I don't see the object icon in the hierarchy as that's top level. The sub level is always another icon so my mental connection would be another icon. 

But I understand your point. You can close this if you want.

**Comment by ReinerBforartists** [comment]
I'll have a look if i can come up with something better

**Comment by Draise14** [comment]
Perfect! You are so great. Thanks for all the details!

**Comment by ReinerBforartists** [comment]
You're welcome :)
