### ISSUE TITLE
Maranjo 20.2.1 installation issues

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2864]
Hi!
Please help me to install on Manjaro 20.2.1
the following is the issued I have on the installation log
 Thanks

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENEXR_HALF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/kernel/osl
    linked by target "cycles_render" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/render
OPENEXR_ILMIMF_LIBRARY (ADVANCED)
    linked by target "cycles_kernel_osl" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/kernel/osl
    linked by target "cycles_render" in directory /var/tmp/pamac-build-floris/bforartists/src/Bforartists-2.8.0/intern/cycles/render

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_ALEMBIC_HDF5

CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...

_Originally posted by @floris-max in https://github.com/Bforartists/Bforartists/issues/2627#issuecomment-1019431640_

**Comment by ReinerBforartists** [comment]
Seems that you miss at least one library. When you build from scratch, then you need to download the precompiled libraries for Blender.

The advice works in general the same than described in the Blender WIKI https://wiki.blender.org/wiki/Building_Blender/Linux

**Comment by ReinerBforartists** [comment]
Just curious, does our appimage version work at Arch too?

**Comment by naetherm** [comment]
There are still some problems with the applied patch regarding OpenEXR, but I'm onto it.

**Comment by Draise14** [comment]
Will install a Manjaro build for this later.

**Comment by ReinerBforartists** [comment]
Closing as a duplicate of 

AUR needs updating #2627
