### ISSUE TITLE
3D View - All Drawing Modes - Add brush management to header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2869]
![image](https://user-images.githubusercontent.com/35357409/151067520-a8f76cf6-3848-46ac-a6fe-3aa152ebbfe5.png)

At the moment, the only way to duplicate, delete and force save brushes is in the toolshelf - but sometimes you don't want both the header and the toolshelf open since these are two of the same brush editors. 

It would be nice to make both consistent with the other so that you can have one or the other open without redundant brush controls - with both open to have the brush management all in the same editor.  

We could minimize by also allowing to mange the brushes from the header exclusively. 

**Notes:**
This would be added to the header in the following modes:
- Texture paint mode
- Grease Pencil Draw mode
- Weight paint mode
- Vertex paint mode
- Sculpt mode

**Comment by ReinerBforartists** [comment]
This may be not so easy to achieve. These little buttons are part of the brushes prop. And is C code.

**Comment by ReinerBforartists** [comment]
As expected, this task is mission impossible. The whole preview and select element is one big c property. I tried if i can isolate at least the fake user button. But as you can see ...

I think we can live with having just one place to set the fake user for brushes. A average user will not touch this functionality at all. And even you will rarely change this settings every five seconds. You set up brushes once. Then you use it ...

Closing.

![missionimpossible](https://user-images.githubusercontent.com/13919702/151671633-cdbceba1-b6c2-483c-b0d9-0a7823695ba0.jpg)
