### ISSUE TITLE
Crash when using clay strips with dyanmic topology enabled

### ISSUE THREAD

**Issue by dualhammers** [Bforartists/Bforartists#287]
After drawing on the surface of an sphere for 2-5 seconds using the clay strips brush the software will hard quit and close.

If applicable, please add Example material. A screenshot, a blend file, Or even a short video.
![image](https://user-images.githubusercontent.com/7495830/46262639-2f886400-c4c1-11e8-975a-f97ebba42694.png)
Snapshot before crash

Windows 10, Intel HD6400, Geforce 860M

Bforartists 1.0

**Comment by ReinerBforartists** [comment]
Thanks for your report dualhammers.

Yes. Unstable Dyntopo sculpting is a known issue. But unfortunately none that we could fix, sorry. 

The Blender developers have stopped the 2.79 development, and work at 2.8 line now. So a bug report for Blender 2.79 makes no sense anymore. I haven't tested if this crash bug still exists in 2.8. It's a complete new beast under the hood. But if so you could report it to Blender. They work at the crash bugs at the moment.

Either way, we cannot fix here anything. So closing.
