### ISSUE TITLE
Geometry nodes, extrude mesh node - node properties - align Individual prop left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2871]
Not sure if this is the only case. We need to check other nodes too. But this checkbox needs to be aligned left if possible.

![alignpropleft](https://user-images.githubusercontent.com/13919702/151696413-2699dd34-6416-4ae0-8903-2a0440b617e7.jpg)

**Comment by ReinerBforartists** [comment]
Hm. When i use property split false here, then we have a problem with sliders.
Ideas?

![true](https://user-images.githubusercontent.com/13919702/151846254-a98f0fe7-01a4-4d21-a84c-ea2b30cf3e3a.jpg)
![pestandcholear](https://user-images.githubusercontent.com/13919702/151846268-830499cc-0d57-4462-b848-4e7b822c1574.jpg)

**Comment by iyadahmed** [comment]
Maybe we put the checkboxes in rows and set property splits on those rows only

**Comment by ReinerBforartists** [comment]
Thanks Iyad. I have Thought of this too. But then the order doesn't fit with the order in the nodes anymore. There is more than just this one checkbox. The socket.draw operator lists the content for all nodes. And i am not sure if it is really this easy to isolate our checkbox bit.

**Comment by ReinerBforartists** [comment]
It is not so easy. There is no way to separate slider and checkbox display. It is as told one operator that grabs all information and lists it then. Without a way to distinguish between label, slider or checkbox. We would have to write our own UI code here i guess.

Either way. Seems that we have a unsolveable issue here. Closing it as known issue.

@iyadahmed , feel free to reopen the issue and nevertheless have a crack at this problem if you want :)
