### ISSUE TITLE
Property Editor - Mesh Data - Attribute - Convert Attribute need icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2877]
![image](https://user-images.githubusercontent.com/35357409/152576326-0d5e5ad8-50d1-494e-b664-4d71a15874ae.png)

A new operator is in town, and this converts attribute to mesh data.

**Comment by ReinerBforartists** [comment]
Good catch. Something for next week.

**Comment by ReinerBforartists** [comment]
Icon already exists. We have it in use already somewhere ...

![atttib](https://user-images.githubusercontent.com/13919702/152577187-77c85b25-2ae9-492e-8320-f5a2f127541f.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![specials](https://user-images.githubusercontent.com/13919702/152841605-3b3bf51c-2df2-4edc-ab4f-dc4cb43a78ba.png)
