### ISSUE TITLE
Investigate into github pull request template

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2878]
Blender has added a git folder with a github pull request template for a blender mirror repo at github in the addons directory.

We are Bforartists though, and might want to remove this new folder. But first let's find out where this shows up.

![githubfolder](https://user-images.githubusercontent.com/13919702/152674019-ad66d0f6-31f6-4b0a-a9f8-665da6bd5df1.jpg)

**Comment by ReinerBforartists** [comment]
This is at more than one place. Also to find in the addons_contrib,  locale  and tools folder. The sub modules ...

**Comment by iyadahmed** [comment]
Why not keep it for now, it does no harm

**Comment by ReinerBforartists** [comment]
Because we are Bforartists, not Blender. We don't need an advice to push to a Blender repository :)

But we will see ...

**Comment by ReinerBforartists** [comment]
Yes, let's remove it. As told, we are Bforartists, and rarely push to Blender ... ^^

**Comment by ReinerBforartists** [comment]
Hm, the files are greyed out and not versioned. Seems that i have it just local here. Curious. The folders are versioned in Blender. But even better. Let's do a cleanup and call this task a day.

Nothing else to do here. Closing.
