### ISSUE TITLE
outliner-tools.cc, trouble with /* bfa - add scene outliner operators  */

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2880]
We have once more trouble with our rmb scene entries in the context menu of the outliner. There are some changes, the libary overrides are removed and two includes are removed too. And this seems to affect our implementation.

This time we have trouble with the variables DATA_ and ED_editors_flush_edits

No idea what the trouble maker is. It is definitely not to fix quickly. I will comment out the code now, so that we can fix this issue after the merge.

![error](https://user-images.githubusercontent.com/13919702/152676785-52100447-8b58-46ab-af1e-e94ddd5db813.jpg)

![error2](https://user-images.githubusercontent.com/13919702/152676788-f6b163e7-64a8-49d5-a2a0-c9bdf880f33d.jpg)

**Comment by iyadahmed** [comment]
the problem is in top of file missing ED_util and BLT_translation
![image](https://user-images.githubusercontent.com/25552173/152677022-20998ad2-3ab3-405e-b5a1-7bc3d08c6050.png)

**Comment by ReinerBforartists** [comment]
Thanks Iyad. I already expected that it could be one of the includes. Testing ...

**Comment by ReinerBforartists** [comment]
Yes, that was it \o/

Closing. Fixed :)
