### ISSUE TITLE
Quick Feature Update Video - pushed to socials, could go to Youtube

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2888]
I made a quick video feature about a Feature Update for the Add Node Shelf Order. I have pushed it to the files master - and also soon to the socials. 

[https://github.com/Bforartists/files/blob/master/promotional/Videos/Feature%20Updates/Export/Update-Bforartists%20301-Feature_01.mp4](https://github.com/Bforartists/files/blob/master/promotional/Videos/Feature%20Updates/Export/Update-Bforartists%20301-Feature_01.mp4)

You could also push to youtube. With time I'll improve the quality and also the header and footer titles - but idea is keep these videos shorter than 1 minute.

**Comment by ReinerBforartists** [comment]
Thanks for the video Draise. I'll upload it :)

But please don't use the files repo for this kind of content. It is too big. Version control means that this file is now part of the repository. And even when we completely remove it, it remains stored in the repository now, blowing up the repo.

We have our Bforartists cloud where we can share such big files. Or you can use dropbox or similar online storing services to transfer such big files.

Also, Youtube offers a way to share videos from external contributors. So you could make a playlist at your youtube channel, and i could simply share it at our channel then. I have to investigate here first though how exactly this is done. What do you think?

https://www.makeuseof.com/tag/make-collaborative-youtube-playlist/

**Comment by ReinerBforartists** [comment]
I have now created a share playlist where you can upload your content. Please follow the link. It is an invitation link:

https://www.youtube.com/playlist?list=PLB0iqEbIPQTY9Wmyi5kdMqzpDC7CU-Vn9&jct=r1_V3D9Xw8QwoR-khgevHzVw9ysi5g

**Comment by Draise14** [comment]
AH, totally forgot about the cloud storage sharing. Yeah, will use that next time. I should probably sync that.

Concerning playlists, I think that unfortunately the SEO of the video will direct to either the playlist or my channel and the video content as if it were hosted on my channel, not the Bforartists channel and it's ranking. I tried uploading to the playlist, but I can only upload videos to my own playlists directly. I can add videos to that list, any video, but it won't be hosted on the Bforartists channel (ei, I upload to my channel - I add to that Bforartists list - but the video will still remain hosted on my channel). A user can search and filter for playlists of Bforartists content, but the more content I upload about Bforartists on my channel, the more fractured the Bforartists content and directly competes for the Bforartists channel ranking I guess. 

![image](https://user-images.githubusercontent.com/35357409/152989579-95747480-4ff1-4f2f-abb2-274d6a415ea1.png)
![image](https://user-images.githubusercontent.com/35357409/152989902-16f029bc-3ac7-4687-abb0-8ec3919807d7.png)
These are the options I've got, which are few - and the playlist where I can directly upload to is not listed in my upload options... 

The other option is adding "Editors" with limited permission, then I could just directly upload to the Bforartists channel instead of making you work to upload when I make a little video. 

![image](https://user-images.githubusercontent.com/35357409/152990733-2bfa74a8-8bb9-46ab-9260-37021a310cfc.png)

**Comment by ReinerBforartists** [comment]
:/

Would have been too nice ... 

Okay I will upload the video to my channel then :)

**Comment by ReinerBforartists** [comment]
Hm. I could still make you an admin at the channel. Then you would have upload rights. Just found the options to do so. But that's another chapter then.

**Comment by ReinerBforartists** [comment]
Video is live. Task fulfilled. Closing.
