### ISSUE TITLE
Brush Modes - Add Toolshelf refresh when creating and deleting brushes from Property Shelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2890]
When you create/duplicate and delete brushes, the toolshelf doesn't update till you mouse over it. With the new Bforartists Brush Panels, we need the toolshelf to update when a new brush is created so the UX doesn't feel broken. 

@iyadahmed has potentially found a way to patch the button operators to trigger a panel refresh, so we can improve the UX of that addon by allowing it to update on brush creation/deletion. 

This task is made to track that patch and branch. 

**To test:**
- You can use the branch `2136 ` with the addon here #2136 
- You could merge it into this branch, it's just a single `*.py` file
- Create brush presets and delete them once you've activated the addon (in weight paint mode)

**Comment by ReinerBforartists** [comment]
Ah yes, this is one of the sad things in the Blender UI ...

Hopefully you will find a solution. Good luck :)

**Comment by ReinerBforartists** [comment]
Related: 3D View - Weight Paint Mode - Expose Brushes to Toolbar to improve UX #2136

**Comment by iyadahmed** [comment]
Looking into this, it is not good to mess with the data remove operator in this way, I need to find a different way
