### ISSUE TITLE
Script errors, see topic thread for full title

### ISSUE THREAD

**Issue by DrSupermanShadow** [Bforartists/Bforartists#2905]
Avatar creation for VRM Models and VRchat  Models And World:
Script errors and functionality errors>

Also, the user interface is too complex for users with autism.
(gimp)(Inkscape)( and huion tablet drivers) UI  where you can select the tools and use 2 pen buttons would be better ( examples 
 for you>
You may want to create and fix addons for this since blender refuses to create Autism-friendly Interfaces.
having to press 30 key combos is just 2 complex.
I personally am a very visual person who loves icons with hover info and loves using my huion kamva 16 2021 drawing tablet in creative ways.

3 addons have been added in the list file.
I've also included the version I am using. 
I can't find the error reports to screenshot, edit out the personal data, the send the script bug error.

(**Describe the bug**
A clear and concise description of what the bug is, and how to reproduce it.)

**Desktop (please complete the following information):**
The Operating system. Windows 7, 8, 10, Linux, Mac ? What graphics card? 
Window 10, radeon rx vega m GH is the graphics

(**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.)
all file to my knowledge  are  open source so you can recode and improve upon them if you desire

problem: Script and functionally (work fully in blender but not your program)
alter eyes materials to greyed out but can't be reset to pre-installed eyes, for me its just sculerios materials.
Works in blender>
[cats-blender-plugin-master.zip](https://github.com/Bforartists/Bforartists/files/8111880/cats-blender-plugin-master.zip)
SuggestionS:
recodes for use in be for artists.
make it so it can recognize the difference between hair, face, body, and clothing meshes( right now it can't.)
Improve the UI for it

Problem: Script errors and functionality: Materials don't show up or combine in the right way.
This is a must for VRChat avatars.> sometimes works in blender sometime it doesn't>
[material-combiner-addon-master.zip](https://github.com/Bforartists/Bforartists/files/8111886/material-combiner-addon-master.zip)
Suggestion recode The ADD On for your program, 
Improve the UI @ make selection of combining and reducing material more user and intuitive.

This has so many functionalities and script errors its not even funny. Let's just say this add-on really sucks.
But it works in Blender.
[VRM_Addon_for_Blender-release.zip](https://github.com/Bforartists/Bforartists/files/8111889/VRM_Addon_for_Blender-release.zip)
Suggestion recode The ADD On for your program, 
Improve the UI and improve it in every way possible.

The version was installed via installer exe file.( first)
and reinstalled via extracted zip.( to try to  fix  errors)
bforartists3_301

I  Created a system text file from within the program if that helps.
i edited out personal info.
[system-info.txt](https://github.com/Bforartists/Bforartists/files/8112011/system-info.txt)

Signed 1 seriously pissed of avatar and world creator/ content creator
who hates the fact the disability budget-friendly programs
like blender and unity have such overly complicated not autism-friendly user interfaces.

I hate taking 2 hours just to figure out how to create an eyeball. or 
move an imported avatar's parts and meshes around and fix the bones from one bone structure to a prefab one.
and in case it wasn't clear Autism.
Boom Thanks for making the software a little easier to use,

DRSUPERMANSHADOW

**Comment by ReinerBforartists** [comment]
Hi DrSupermanShadow,

Thanks for the report. But we are not responsible for third party addons. You have to ask the addon creator for usability changes.

Regarding the script errors. I don't experience them. The addons loads fine. Could you please elaborate what the errors are?

Kind regards
Reiner

**Comment by DrSupermanShadow** [comment]
What part of not autism user face interface friendly did you not understand,

and I already contacted all of the third party add on user 6 months ago and in 2021
Those who were still active in coding updates said
the files and add on’s are open source, if I wanted to update it to be user friendly I could code it and submit it to them.
But guess what I am not a pro-coder and I’m to  much of a visual person to write straight up code.
So I have to rely on the pros.
And clearly the creators are not going to make an edition that is disabled user/ autism friendly.
hence the reason I suggested you guy use there open source code and make your own version.
(then I would use the b for art version)

I have also been on blenders coders asses since version 1.0 beta to code the user interface to be more autism  user interface friendly.
they are on version 3.0 and clearly are never going to make it disablity friendly.
so guess what?
I have to find new coding teams to do it to their open source program for them.
nd based on what I read about b for artists you guys actually care about if your program is   disabled and autism user friendly. Unles that statement is false advertised..

And like I said if I could figure out what the errors are or where the error menu was or how to fix it my self.
I would not have bothered to contact your development team and I would have given you a screen shot of all the programs script errors.

I also gave you sum example of programs that have graphic design the is autism friendly>
for example in gimp in about 6 hours I could draw and entire 3D human model  using just my tablet pen and tapping on certain tools and mouse gryo/ xyz click mouse movement( hold the wheel down and drag). no need to memorize 50 keyboard button combos,
I can also rearrange the ui in about 5 minutes for better work flow>
But it s not avatar creation software so I can’t use the models….

WITH Your current user interface it to me 6 hours just to figure how to move 1 object to 1 set of bone to another. And in case you are not aware most of the blender tutorials are absolute dog shit. 14 pages of videos and not  a single  tutorial creator tells you how to set up the interface like a gimp lay out or inkscape lay out and how to eliminate the 50 fucking keyboard shortcuts to simple click a tool and use the mouse and pen buttons for actual movement and enable drop down menus to make changes or undo change. So the user interfaces is extremely visual and intuitive.

and I will say it again just so it clear
if I  was  capable of doing the actuall coding scripts.
I would take all of these open source free programs and add ons and recode them
so the user interface was so simple and intuitive  that a 5 year old with an iq of 75  non functioning autism could figure it out. I’m talking video game character creation and building menu like world of warcraft simple but with the abilyt to customize materals. Drag and drop thing like eyeballs, heads, tails hands feet, well you get the point.  The using point selection and right click you could align and fuse the object in about 2 minutes. Simple. 2hours for imported modifications and 6 hours from 1 object to full avatar simple.
Then I would release the code and programs, to ever  User who felt
Daz studio(has sum paid features) unity, unreal engine, blender, and character creator 3(this one is not free) was to complex also your would not have to worry about add ons because  the 3rd party file extensions and optimizers would be pre installed.

Thank you and have  a nice day

**Comment by DrSupermanShadow** [comment]
location: C:\Program Files\Bforartists 3\3.0.1\3.2\scripts\addons\material-combiner-addon-master\operators\ui\include.py:11
Python: Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.0.1\3.2\scripts\addons\material-combiner-addon-master\extend_lists.py", line 18, in draw_item
    row.label(text='', icon_value=item.mat.preview.icon_id)
AttributeError: 'NoneType' object has no attribute 'icon_id'

location: C:\Program Files\Bforartists 3\3.0.1\3.2\scripts\addons\material-combiner-addon-master\operators\ui\include.py:11
Python: Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.0.1\3.2\scripts\addons\material-combiner-addon-master\extend_lists.py", line 18, in draw_item
    row.label(text='', icon_value=item.mat.preview.icon_id)
AttributeError: 'NoneType' object has no attribute 'icon_id'

location: C:\Program Files\Bforartists 3\3.0.1\3.2\scripts\addons\material-combiner-addon-master\operators\ui\include.py:11
  Material error upon vrm  and model imports found

**Comment by ReinerBforartists** [comment]
Thanks for the error messages. Those are errors that the makers of the addons needs to fix. We are not responsible for third party addons. 

Closing.

Kind regards
Reiner
