### ISSUE TITLE
Coder expertise need to fix python error.

### ISSUE THREAD

**Issue by DrSupermanShadow** [Bforartists/Bforartists#2908]
def invoke(self, context, event):
        dpi_value = Common.get_user_preferences().system.dpi
        return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
        
        What is the new correct python 310 script code to correct this line error?
        keep it simple. this python correction notice is way too complex for sum 1 with autism.
        Since pro-coders refuse to correct the plug-in in a timely manner i am going to fix the script codes myself.
        after all its an open-source plugin
        
        
        Info: Saved text "C:\Program Files\SS ART UI\3.2\scripts\addons\cats-blender-plugin-master\ui\armature.py"

Python: Traceback (most recent call last):
  File "C:\Program Files\SS ART UI\3.2\scripts\addons\cats-blender-plugin-master\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\SS ART UI\3.2\scripts\addons\cats-blender-plugin-master\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

**Comment by iyadahmed** [comment]
You just need to convert `dpi_value * 3.25` to integer, like this

`width=int(dpi_value*3.25)`

Also note this isn't a Bforartists issue so it doesn't belong here😄

There's also this server for coding help unrelated to Bforartists

https://discord.gg/CvFYAuQcDT

**Comment by ReinerBforartists** [comment]
Yes. Such issues does not belong into the Bforartists tracker. As much as i would love to, we simply miss the man power to fix addons too.

This is best asked at the forums. Or as mentioned by Iyad Ahmed in the Discord server. I will move it to the discussions board therefore.
