### ISSUE TITLE
3D View - Toolshelf - Add Select Header Menu panels

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2914]
![image](https://user-images.githubusercontent.com/35357409/156231971-980cfce2-12e0-4c2e-9c38-b9e2988fd11a.png)

Currently the second most often used operators in Edit Mode are the select ones, but often these are either hidden or configured to hotkeys or floating menus, or to the header zig zag movements.

From work and using the toolshelf a lot, it would be nice to have the majority of these exposed to a toolshelf tab also, with option to pin panels so it's nicer than using the quick menu, assigning hotkeys to floating panels, or assigning many custom hotkeys just to select things.  

I am not suggesting this for absolutely every editor that has a toolshelf, but for now it would be nice to have the select panels in the toolshelf in the 3D View editor, specially in the Edit mode. 

**Reasons:**
Here is a typical UX as an example:
- Select checkered from header
- Random transform from toolshelf
- Select grouped by Coplanar in header
- Extrude from normals from hotkey
- Subdivide Edges from toolshelf
- Select boundary loops from header
- Bevel Edges from hotkey or toolshelf

As you can see, just normal modeling requires some kind of quick menu, right click menu, or hidden hotkey floating menu or assigned hotkey to work selections - when the header menu sometimes is used every 3 operators in a chain. So.. maybe they deserve a tab with panels (or optionally)

**Comment by ReinerBforartists** [comment]
Agreed. Could be useful. But crowds the tabs a bit more. The reason why i didn't want to put everything into the tabs ...

**Comment by Draise14** [comment]
True, I think just one extra "Select" tab with mostly the common select panel groups (not all) could work. Ei, the ones that are legacy or in the toolshelf already would not be needed (ei, circle, lasso, and box select). Select Linked could also be only 1 operator instead of all 4. Etc - I guess.

**Comment by ReinerBforartists** [comment]
There are quite a few hotkey only tools in there which wouldn't make sense anyways in the tab. Linked Pick Select is one of them.

**Comment by ReinerBforartists** [comment]
Draise, i had a closer look at it now. And remember the second reason why i didn't migrate it. Do we really need it? 

The select menus is full of modes and object specific tools. It's fifteen single menus. Add to this that we cannot make it consistent to the menu content.

**Comment by Draise14** [comment]
Hmm... well as the example in the proposal shows I would use it immediately and often (every 3-4 operators is a special select type of operator), but yeah.. it could be "bloaty" for most users. Though, in pro a modeling, a user would be able to not heavily rely on custom hotkeys to select things, nor use a text only list of quick menu or burning some time zig zagging to the menu. They could be free to discover faster ways to model with the great selection tools maybe previously not used because they aren't exposed to a top level. 

But yes.. making it consistent would be tricky and updating it per mode also.... yeah, would be very complex. I see what you mean.. 

Here are some alternatives after some thought:

**Option A**
Maybe another view toggle show/hide these panels optionally? 

Would solve the bloat, and make the panels optional per the user choice. Doesn't solve the complexity. 

**Option B:**
Maybe we can work on the select menu for only the Edit Modes for modeling? Since this is where it would be used the most. Ei, only do it for a single mode and object type (ei, Object Modeling in Edit Mode)

This would fix the bloat and complexity - since it would only be available for specific UX where you can benefit most from it. Then if we need it in other areas and modes - that can be debated. Workload to implement it would be less. Only issue is expected consistency.. 

This could also be placed in with an opt-in toggle. 

**Option C:**
Or.. close and not do it. 

I guess assigning hotkeys or quick menu to these can work around the frequency of use to optimize, no biggie really. Just thought it could be useful atleast with Edit Mode in mind. But yes, this would be too big for one task - maybe best debate per mode and object type?

**Comment by ReinerBforartists** [comment]
It's not about the size of the task. It's about the consistency. Half of the select tools are mouse / hotkey only tools. Just added to the menu to be consistent and to have them in the UI. A stripped down select tool panel would force you to use the menu reularly anyways. On the contrary, select menu items like grouped, linked and by type are simply better done from the menu. Nobody can remember this much icons.

So what remains is three or four buttons that we could really place into the sidebar. And this makes imho no sense.

**Comment by ReinerBforartists** [comment]
Decision time. 

It makes no sense to have 4/5 of the tools not in the shelf then. This is too inconsistent. So let's not do this.

You could add your favourite select tools also to the Quickmenu. So no need for a hotkey for each of the tools. A dream would be of course to have a toolshelf panel with quickmenu content. But i don't see a way to add our 1600 icons there. It's already a challenge to just display the content of this menu in a panel. But, hmmm, maybe we should have a second go at this idea.
