### ISSUE TITLE
Propery Editor - Shaders - Add/Remove should be greyed out in Edit Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2915]
# UX Issue
You cannot add nor remove shader slots in edit mode...

![bforartists_3icQYGsfE4](https://user-images.githubusercontent.com/35357409/156244513-8b710d5e-2c92-4e89-a14a-474d8fcb24b1.png)

But the buttons show thatyou can. We get a warning, but the temptation still resides when we click, it's somewhat fustrating. 

## Feature Request 
![bforartists_MQWCBFE49z](https://user-images.githubusercontent.com/35357409/156244541-dbb75c36-6e4e-4f15-ac52-0352d86c5acf.png)
If these buttons were greyed out or hidden when in edit mode, we could avoid this warning and UX annoyance a little.

**Comment by ReinerBforartists** [comment]
You can add in edit mode. Just the remove is affected. And just in Edit mode.
