### ISSUE TITLE
Iconography - Make the Draw icons consistent both large and small

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2919]
![image](https://user-images.githubusercontent.com/35357409/234054807-5ab04d44-62c9-4c6b-be9b-29915a32b27c.png)

Right now we have a draw icon at 16px with colour, legible. Great. 
`PAINT_DRAW`

But in the default brush set they are are monochrome and different. This is inconsistent 

It would be nice to make them the one and the same for consistency and legibility.

# Task
Import our SVG into the large icon file to generate the large icons to look the same. A similar task was done with #1317

**Comment by ReinerBforartists** [comment]
That's mission impossible. The one set is the 24 pixels icons. The other is the 16 pixel icons.

**Comment by Draise14** [comment]
Ei, one is the Blend file 3D icons kinda imported from SVG and the other is generated from the SVG directly? But two different *.dat files?

**Comment by ReinerBforartists** [comment]
Yes, as told, the one is toolshelf icons in size of 24 pixels. Our toolshelf code uses the old 16 pixel icons.

I will not touch the 24 pixel icons ...

**Comment by ReinerBforartists** [comment]
I noticed that you still use big icons in this addon. The offset is killing the look. You need small icons here. 

And why so much tabs? The whole purpose of icon only is to have icon only ...

![toomuchpanels](https://user-images.githubusercontent.com/13919702/206151619-1ba8202b-09b6-476c-874d-0a8aab442c0b.jpg)

**Comment by Draise14** [comment]
It's not finished. Gotta make a new task. 

1. Small brush icons.
2. Split them to tabs grouped by the brush color ( since they are so many.

**Comment by Draise14** [comment]
The addon is off by default anyway, so no real double at all.

**Comment by ReinerBforartists** [comment]
Or to use small icons here. It is as told the old code, and requires small icons. Big icons will not help you here. And to rewrite the whole addon with big icons is most likely very hard to not possible. Just have a look at space_toolsystem_toolbar.py . 

There is a reason why Blender devs have put the big icons on top of the existing system, and did not integrate it.

**Comment by Draise14** [comment]
Yea, we use the small icons in the addon (minus the sculpt mode, needs a fix there), that's not the issue here... it's the inconsistent icons. I can import the SVG we have of the small icon to also be the one and the same icon for the large version, making them consistent where relevant.

**Comment by ReinerBforartists** [comment]
No, the screenshot shows big icons.

**Comment by Draise14** [comment]
The task of the large icons I have referenced here #3511 to not confuse anything. This is task is to make the Draw brush icons the same icon both large and small. I will update the description and title to reflect that, keep it simple and separate.

**Comment by Draise14** [comment]
Yikes, getting linux to compile the icon has been more involved than I though - as most things code. This is a stressing thing to do with deadlines.

Status: I've worked through the tutorial and video - and now I'm trying to get linux to compile the icon. I may try do it through Blender - and get Blender compiling first.

**Comment by Draise14** [comment]
![blender_uiEjdA14vF](https://user-images.githubusercontent.com/35357409/236648157-392e2a09-35ec-4020-9072-c52e729cc93c.png)

Eureka! Found a way to make icons in Windows.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/236649028-60a8c8ec-5227-4208-adf9-6e355934f1c3.png)

Wow...

**Comment by Draise14** [comment]
Ok.. tried adding in more icons, but the colors are weird. The brush black is red. And the system for colors I don't understand. They seem to be dynamic... Maybe I still have to compile in from Ubuntu?

I am defeated. I got not bug fixes done for the release, the release is no where close to being ready, I've got two crunch deadlines with clients - I think I will have to postpone this release yet again.

**Comment by ReinerBforartists** [comment]
but the colors are weird. The brush black is red.

Are these icons external or part of the iconsheet? If so, you need to make sure that the icon definition is DEF_ICON_COLOR . Other icon tags leads to that the coloring system from Blender kicks in.

And i found a handful icons with exactly this kind of mistake. I am just not sure if this is really by mistake, or by decision to keep the blender way here. Needs a check. And a comment in case we want to keep it. The heart and fund icons are not used by us for example.

![entries](https://user-images.githubusercontent.com/13919702/236661773-7c55ef2f-ca32-48c2-b99f-62b12fea0cb0.jpg)

![whattouse](https://user-images.githubusercontent.com/13919702/236661786-48480b2f-3597-4f5d-9702-42952e392745.jpg)

**Comment by Draise14** [comment]
Might be a mammoth task... But a worthy one.

**Comment by Draise14** [comment]
Hmm.. might have to break this one up, so will close and approach this on a per or icon group basis. Will also do this after 3.6.1
