### ISSUE TITLE
UV Editor - Tabbed Toolshelf - Translate Panel has labels in single column

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2920]
# Request
![image](https://user-images.githubusercontent.com/35357409/156937968-d13413ec-bbbb-405e-808b-d4d4b5657c71.png)

When scaling the UV editor Tabbed Toolshelf to single column, the Transform panel shows labels instead of only icons.

**Comment by ReinerBforartists** [comment]
That's a bug :)

**Comment by ReinerBforartists** [comment]
Fixed in master
