### ISSUE TITLE
Outliner - Make Library Override Hierarchy labeled incorrectly as "Convert Proxy to Override"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2924]
**Bforartists 3.1.0**
![image](https://user-images.githubusercontent.com/35357409/157714477-8619067e-b0db-4d2e-aeb3-b41b463213c5.png)

**Blender 3.2 Alpha**
![image](https://user-images.githubusercontent.com/35357409/157714594-46ff2614-67fe-44a2-9fa3-1d2f9d49113b.png)

The Make Library Override Hierarchy is missing. 

This is a pretty big operator when using anything linked... where did it go?

**Comment by Draise14** [comment]
Gah damn, this is a showstopper in the pipeline.

**Comment by ReinerBforartists** [comment]
Was it in the latest devbuild?

**Comment by ReinerBforartists** [comment]
Could you please help me with in what display mode an in what constellation this menu shows? I can't find it.

**Comment by Draise14** [comment]
To reproduce:
- Link a collection from another blend
- Right click on the collection
- Go to ID Data
- See that it's missing. 

It only works on linked collections context menu.

**Comment by Draise14** [comment]
> Was it in the latest devbuild?

Yes, same issue in last `devbuild-05-03-2022`

**Comment by Draise14** [comment]
I'm rolling back to try find when it worked. 
`devbuild-26-02-2022` also doesn't show

**Comment by Draise14** [comment]
Found working in last build with it. Man, not sure why I hadn't noticed this sooner!
`devbuild-29-01-2022`

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/157744322-54959bb7-8d91-4466-a21b-d841baa3fcb1.png)

Found it. It's mislabled. 

File:
`//source/blender/editors/space_outliner.h`

Line 1918-1919

**Comment by ReinerBforartists** [comment]
Feel free to submit a bugfix. But i won't create a devbuild this weekend since we have a full release today already. I can't make a new version every two days :)

**Comment by ReinerBforartists** [comment]
Well, the manual should still show the old label too :)

**Comment by ReinerBforartists** [comment]
Make hierarchy override single is also affected.

**Comment by ReinerBforartists** [comment]
Hm, the reset icon doesn't fit anymore ...

![icon](https://user-images.githubusercontent.com/13919702/158152473-845f93a3-370f-4cba-a833-2ec3f7b0c077.jpg)

**Comment by ReinerBforartists** [comment]
Follow up: Missing icon when Make Libary Override Hierarchy, and call the right click menu again.

![canofworms](https://user-images.githubusercontent.com/13919702/158152980-d22a73fd-e5a3-4343-a18e-28f732bfae36.jpg)

**Comment by ReinerBforartists** [comment]
Hm. When i click at Make Libary Override single then the whole collection vanishes. What is the purpose of this menu item?

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by ReinerBforartists** [comment]
Fixed ...
