### ISSUE TITLE
Geometry nodes - add new icons, add tools to sidebar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2931]
New nodes, needs icons, needs entry into the sidebar.

![stored](https://user-images.githubusercontent.com/13919702/159158401-30b8c2aa-257a-4521-8ceb-2d4a535810f7.jpg)

**Comment by ReinerBforartists** [comment]
Indeed

> SHA-1: d4e46c13cc92e01489a031a6afe6bafb5af5ca18
> 
> * Geometry Nodes: Add named attribute nodes behind experimental flag
> 
> This commit adds three nodes:
> - `Remove Attribute`: Removes an attribute with the given name
> - `Named Attribute`: A field input node
> - `Store Named Attribute`: Puts results of a field in a named attribute
> 
> They are added behind a new experimental feature flag, because further
> development of attribute search and name dependency visualization will
> happen as separate steps.
> 
> Ref T91742
> 
> Differential Revision: https://developer.blender.org/D12685

**Comment by Draise14** [comment]
I think this is a duplicate and we added icons to these new operators. It's no-longer experimental.

Done here:
#2996
