### ISSUE TITLE
Interface Flashing at Mac

### ISSUE THREAD

**Issue by thomllama** [Bforartists/Bforartists#2933]
_**Describe the bug**_
while trying to model, the whole interface seems to "flash". it's very disturbing when concentrating. Doesn't happen with Blender so it's likely a BforArtist thing?  Both BFA and Blender are unto date, redownloaded both this morning to make sure. 

_**Desktop (please complete the following information):**_
Mac OSX- 12.3.  -  2020 M1 Mac Mini, - 16g ram   - OS is unto date
_**Screenshots, Example Files**_
video link as it's too big for here I guess... 
https://drive.google.com/file/d/1qAYcwkd1Fk0I4_OXzIFws80GwmsOcEJU/view?usp=sharing

**Comment by ReinerBforartists** [comment]
Many thanks for the bug report. 

Mh, could you please try with a developer build of Blender? The official Blender version is made from a special release branch. And is version 3.1. We rely at the master. And this master is always one version ahead already. Which is 3.2. It can be that the release version still works fine, and the master version shows some side effects from new features.

You can find the alpha 3.2 build here: https://builder.blender.org/download/daily/

**Comment by ReinerBforartists** [comment]
Just to add, i am still clueless what the cause could be here. We have at all the same code. We don't touch the Blender core code this deep that it could show such a side effect. It can be that the problem isn't even in the code. But the mac version that it is compiled with. Unfortunately i don't have a Mac. I can't even test it.

**Comment by ReinerBforartists** [comment]
Not to reproduce at Windows, not to reproduce at Linux.

**Comment by thomllama** [comment]
> Many thanks for the bug report.
> 
> Mh, could you please try with a developer build of Blender? The official Blender version is made from a special release branch. And is currently version 3.1. We rely at the master. And this master is always one version ahead already. Which is already 3.2. It can be that the release version still works fine, and the master version shows some side effects from new features.
> 
> You can find the alpha 3.2 build here: https://builder.blender.org/download/daily/

yup, download alpha blender... no issues with it.  question.. you don't have the Mac versions listed so guessing you are just doing the intel version and not the ARM version?  that may be the issue...?  just a guess here as I never have issues with intel  apps before really

**Comment by ReinerBforartists** [comment]
Thanks for also checking this :)

I unfortunately don't know if it is intel or arm based. I don't have a mac at all. The mac build comes from a volunteer in our team. I personally do the Windows and Linux version. I'll ask him. But it can be that it needs a while until he responds.

It would be interesting to know if a self compiled version at your mac would run fine. And to build it by yourself is not as complicated as under Windows.

I can of course understand when you don't want to do this. But just in case, the advice is the very same than for Blender. With our paths instead of course :)

https://wiki.blender.org/wiki/Building_Blender/Mac

**Comment by Draise14** [comment]
Sean has done a small whirl, though he has been a little busy. Initial testing can't reproduce.

**Comment by Draise14** [comment]
Yeah, I know Sean is on an Intel version of Mac.

**Comment by ReinerBforartists** [comment]
So what can we do? Sean just can create the Intel version.

**Comment by Draise14** [comment]
I guess there is not much we can do... close?

**Comment by ReinerBforartists** [comment]
Unfortunately, yes. There is nothing that we can do here.

**Comment by seanr** [comment]
FYI, I cannot reproduce this on an Intel Mac with the new version here: https://www.dropbox.com/s/hmp3r568c9k2kds/Bforartists-v3.1.2-Mac.dmg?dl=0 - I think this may be an M1 issue?

**Comment by seanr** [comment]
One thing I would suggest is looking at the hardware acceleration options and disabling those if possible. I cannot enable them on Intel so I cannot test. :(

**Comment by ReinerBforartists** [comment]
Thanks for having a look at it @seanr

Our old dilemma. We can just fix what we can reproduce ...
