### ISSUE TITLE
Problematic merge

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2934]
Every now and then we run into a merge that throws errors that are not so easy to resolve.

We experience currently again such a merge. As usual i don’t even have an idea what the problem could be. The difference is, this time i am really in the dark. There is no hint towards a single problem. A whole target is simply not created. And this fires then of course a cascade of bugs. But what the target prevents from building is not to figure out yet.

I am currently at applying every single patch from the last week one by one. Very time consuming task. The Blender developers are very busy at the moment. There is a ton of patches and code to investigate.

Fingers crossed ...

![someerrors](https://user-images.githubusercontent.com/13919702/160346858-49097528-ecb7-47a0-aca1-2fadad3395c5.jpg)

**Comment by ReinerBforartists** [comment]
Ah, now it is getting really complicated. I have simply thrown in the changed files from the failed merge to speed things up. But there are here and there multiple changes at the files. And so some changes from a commit afterwards comes in the way :/

Let's see if this is to resolve.

![compo](https://user-images.githubusercontent.com/13919702/160351958-149a640b-d59d-4b8c-9596-aed8d590b262.jpg)

**Comment by ReinerBforartists** [comment]
Dead road. Too much open ends.

Ideas?

**Comment by ReinerBforartists** [comment]
Trashing the current approach of fixing all the spaghettis. I really need to go through every changed file, and just change what is changed in the current commit.

This sounds more and more like a big party ...

**Comment by Draise14** [comment]
Looks like GP and unity? Huh?

Have you updated the preliminary things like updating the dependencies and renaming the Cmake? I think last week or two they added in the new experimental Eevee which is a tonne of code. It's an experimental toggle fortunately, but maybe it's breaking something since we have some minor changes like TAA on volumes.

**Comment by ReinerBforartists** [comment]
Of course i did. It's the same procedure like every week :)

And yes, there is a ton of new code. That's why i am not really happy to manually apply every patch file by file and commit by commit manually. The chance that something breaks by this is very big.

If only VS would give me a hint where the problem with the merge really is ...

**Comment by Draise14** [comment]
Another change in Eevee is the default volume samples. 

I'll ask Iyad to give it a go.

**Comment by ReinerBforartists** [comment]
Mh, i have done the usual merge with the sync_blender_master branch. But the changes are not in the repo yet, just local

So you need to start from scratch. Update the libs*, switch to sync_blender_master, fetch all, merge the changes from Bforartists master, merge the changes from Blender.

*I have in the same folder a blender repo, which i update and build before i do the merge in the Bforartists repo. And this updates the libraries for me already.

**Comment by ReinerBforartists** [comment]
The build text output:

https://cloud.bforartists.de/index.php/s/7MS98H9woQ5pT2z

**Comment by ReinerBforartists** [comment]
Found the rascal in source\blender\makesdna\DNA_screen_types.h, line 383. They changed our flag to short. And then we don't have   HEADER_NO_EDITORTYPEMENU = (1 << 18), anymore, in line 546

And this means our flag to show / hide the editortype menu is gone. All editors now shows the editortype menu again.

![editortype](https://user-images.githubusercontent.com/13919702/160445043-aa4b8fa9-fd81-4061-97c7-8256d7c594c1.jpg)


The commit in question added   
/** For offscreen areas. */
  AREA_FLAG_OFFSCREEN = (1 << 9),

And 1 << 9 was already occupied by our HEADER_NO_EDITORTYPEMENU , which i then changed to (1 << 18),

Phew. This is one of the areas where mnaether has helped me with. I am more or less lost with it how to fix this. I have no idea why it doesn't work with int anymore.

![shot1](https://user-images.githubusercontent.com/13919702/160445076-942d2f18-8d6e-49e3-96c6-061fc790a4e0.jpg)
![shot2](https://user-images.githubusercontent.com/13919702/160445094-bd27f5c2-c277-4739-bba5-caff540ee3de.jpg)

**Comment by ReinerBforartists** [comment]
@iyadahmed , shall i commit the current compiling result to the sync_blender_master branch so that you can have a look at?

**Comment by ReinerBforartists** [comment]
No, they didn't change anything but adding a new flag. AREA_FLAG_OFFSCREEN = (1 << 9),

Sheesh ...

**Comment by ReinerBforartists** [comment]
Okay, added AREA_FLAG_OFFSCREEN at the end now. Compiles fine again, and our flag is back. Phew. 
![complies](https://user-images.githubusercontent.com/13919702/160448094-6e42410b-8324-4987-9d09-d41c7c25a12e.jpg)

I will now just for the case compile from scratch again, and then push the merge tomorrow.

**Comment by ReinerBforartists** [comment]
This was once again really challenging ^^

Fixed.
