### ISSUE TITLE
Merge the new Blender 2.8 icons into Bforartists

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#294]
Blender 2.8 comes with a new icon set. Some might even be new. Which conflicts with our icon set.

Task: replace the old icons with the new icons in our icon set.

Question is if we should adopt the new icons at all. Or just add the new Blender icons.

**Comment by ReinerBforartists** [comment]
Quite a few new ones. More than 100 from what i can see. And some has changed too ...

2.79

![blender_icons16_279](https://user-images.githubusercontent.com/13919702/46600898-edc47280-caeb-11e8-8d4e-b4953096dfe5.png)

2.8

![blender_icons16_280](https://user-images.githubusercontent.com/13919702/46600903-f157f980-caeb-11e8-83ec-5b02e7aa9ded.png)

**Comment by ReinerBforartists** [comment]
Okay, who has stolen da icons. Give um back!

![iconsgone](https://user-images.githubusercontent.com/13919702/46657707-35610200-cbb1-11e8-8fc7-fa67b9f6fe34.jpg)

**Comment by ReinerBforartists** [comment]
I have no idea how the whole icon creation is done now. Either i am super blind or the blend files for the icons are not delivered in the repository. We have a new script called blender_icons_geom_update.py . But the blend file, icon_geom.blend, where it is pointing at is not existent. Unfunny.

**Comment by Draise14** [comment]
Maybe it's a pre-compiled blend from the repository they haven't merged in completely yet?

**Comment by ReinerBforartists** [comment]
It's most probably a blend file that is not part of the repository, yes. And the process is not documented. Just the python file exists to convert this blend file into an icon.

They promised to document it at one point. But this never happened yet.

Quote from William Reynish, back in april this year:

> Currently, it’s just a .blend file that generates the icons. It’s very easy and fast to add a new icon. You just duplicate an icon in Blender and modify it, and give it the correct tool name. Once we are more finished with the tools we will probably document how people can do this, if anyone wants to make new icons, or change them.

Quoted from this thread. But it doesn't give much more info neither: https://developer.blender.org/T54662

Hm. I found this odd construction already bad with the svg file. Now with using a blend file, mixed with bitmap graphics it's imho plain crazy. Especially since the resulting icon is always a dat file, no matter what the source is.

I remember that i once tried to find out how a single dat file can be created without this crazy toolchain. Without success. I guess i have to sleep a few nights over this issue, and read myself into the script. Maybe i find out how it is meant to work. And maybe they will document the process in the new wiki at one point.

**Comment by ReinerBforartists** [comment]
LOL ! Found them :D

The icons are still there. But they are all white now. Monochrome. And i guess they gets colored in the UI code now.

![newicons](https://user-images.githubusercontent.com/13919702/46788675-ecd55000-cd3a-11e8-8923-eb138541dbab.png)

**Comment by ReinerBforartists** [comment]
So this part works the old way across the blender_icons_update.py script

The new icons from the tool shelf, and which are created from blend files, are located in a new folder called icons.

Stopping at this point for now. The important part here was to figure out the new basics. It gets more and more clearer that we might end in a complete restart from scratch, with a vanilla 2.8 Blender. Meanas the task to merge the new Blender icons with our icons is a job for after the big merge of 2.8 into Bforartists.

But we have our old icons already created. And the other code and addons also already exists. So this time it should go much faster, and not last three years again to reach the current state of Bforartists 1.

![icons](https://user-images.githubusercontent.com/13919702/46790047-4c812a80-cd3e-11e8-98a1-f3337dd943af.jpg)

**Comment by ReinerBforartists** [comment]
Long fixed.

Closing

**Comment by anktkr** [comment]
Some icons are there in icon_geom.blend and this file is not shipped with the build. It is at 

https://developer.blender.org/diffusion/BL/browse/trunk/lib/resources/

and the download link, to save trouble of svn commands it this: 

https://svn.blender.org/svnroot/bf-blender/trunk/lib/resources/

https://developer.blender.org/T64177#787946 This comment by  Yevgeny Makarov (@jenkm) clarifies a bit.

>>! In T64177#787946, @jenkm wrote:
> source file:
> https://developer.blender.org/diffusion/BL/browse/trunk/lib/resources/
> 
> utility to generate geometry icons:
> https://developer.blender.org/diffusion/B/browse/master/release/datafiles/blender_icons_geom.py
> 
> these icons are stored in the `../datafiles/icons/` directory
> 
> `BKE_icon_geom_from_memory` - reading .dat files
> `BKE_icon_geom_rasterize` - icon rasterization


See this answer on blender.stackexchange.com too. 

https://blender.stackexchange.com/questions/124614/how-to-edit-2-8-ui-icons/

**Comment by ReinerBforartists** [comment]
Thanks for your comment. 

Yes, these are the icons in the tool shelf, which is another chapter. Not sure how to deal with them. There is no reason to use 3d geometry here. The only difference is the icon size. And i think about to make it a svg too. We will see.
