### ISSUE TITLE
Mac dev release

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#2944]
https://www.dropbox.com/s/yh73ajjfetzl1ik/Bforartists-devbuild-04-04-22-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Many thanks sean. We have a full release though. See here: https://github.com/Bforartists/Bforartists/issues/2943

Quick question, does this dev release have the new splash screen already? Then i could simply rename it. I don't have a mac to have a look at it, unfortunately :)

**Comment by seanr** [comment]
It should have the updated splash screen but would not include it in the DMG (installer) as that requires some manual work.

**Comment by ReinerBforartists** [comment]
Thanks seanr :)

I don't mind about the installer. The installer icon is a different chapter. It's about the splash screen when you open Bforartists :)

So i will simply rename the installer. 


![splash](https://user-images.githubusercontent.com/13919702/161758792-381310c7-2f4a-47b7-b670-cd279d9671fa.jpg)
