### ISSUE TITLE
3D View - Apply Scale of large objects freezes computer - Bforartists 3.1.2

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2948]
This may need confirming.

**Steps:**
- Use 3.2 daily from sometime this week or last week
- Create sphere
- Scale to 4km
- Apply scale

Log what happens

Lately this has been freezing my computer with 3.1.2 - but not in the devbuilds.

**Comment by Draise14** [comment]
Testing latest devbuild (devbuild-02-04-2022)

**Comment by Draise14** [comment]
Can confirm, the last devbuild doesn't have this issue, but 3.1.2 official release does...

**Comment by ReinerBforartists** [comment]
And Blender latest devbuild?

**Comment by Draise14** [comment]
Works in Blenders latest build. Weird it's working for you... let's see if it's an addon or setting. But I hear maybe the showstopper bug will grant a new release from Bforaritsts - so this might be a minor issue from my end.

**Comment by ReinerBforartists** [comment]
Yes, could also be an addon. Please test with a blank installation :)

**Comment by iyadahmed** [comment]
Hmm, this sounds like the script is running on a Debug build, but that's a purr guess, maybe it is an adddon

**Comment by Draise14** [comment]
I had to roll back to 3.1.0, same addons - no crash. So not sure what's going on here. I'll close this with the next devbuild.

**Comment by ReinerBforartists** [comment]
But just in case it works? ^^

As told, it is not to reproduce here. Did it happen with the test build from the other bug report too?

**Comment by Draise14** [comment]
So far so good with the other build. I will close.

**Comment by ReinerBforartists** [comment]
Thanks :)
