### ISSUE TITLE
General double menu entries in Blender 2.8

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#295]
They always manage it. Every change introduces useless double menu entries. This time for ALL tools that has settings. One set is in the properties editor. One set in the new header area. And this affects even whole panels, which appears as menus in the new header area too.

Seems to be a special Blender solution for a special Blender problem. I am just not sure what their problem really is that they need everything double. Makes me scratch my head. Folks. Please. ONE dataset is more than enough ...

![doublemenuentry jpg](https://user-images.githubusercontent.com/13919702/47555729-d7e8e700-d90c-11e8-9c8f-438939443522.jpg)

![brush](https://user-images.githubusercontent.com/13919702/47559701-79c10180-d916-11e8-968c-0cc865b31530.jpg)

**Comment by ReinerBforartists** [comment]
One more ...

![meshandnormal](https://user-images.githubusercontent.com/13919702/47614420-0519ce80-daa0-11e8-9339-d1348f44866b.png)

**Comment by ReinerBforartists** [comment]
This issue here scares me. No matter which of the double menus you remove, you will make unhappy bunnies.

I think the best we can do here is to simply hide the toptoolbar in our default layouts. People who wants to use it can then pull it down again, and save the layout.

**Comment by Draise14** [comment]
Yeah, I think this toolbar either needs to fusion with BFA1´s toolbar or viceversa so that it´s understood that it´s a customizable double menu entry.

**Comment by ReinerBforartists** [comment]
It is not customizable. That's the problem ^^

**Comment by Draise14** [comment]
It's hardwired in C, not python?

**Comment by ReinerBforartists** [comment]
It's C

**Comment by ReinerBforartists** [comment]
Better said the usual mixture of C and Python.

Anyways. Three times the same settings is minimum one too much here ...

![same](https://user-images.githubusercontent.com/13919702/48256967-6d0dd480-e411-11e8-8918-0dd92a1bbd27.jpg)

**Comment by ReinerBforartists** [comment]
Okay, not three times, but four times ...

We definitely need to do something here then.

![fourth](https://user-images.githubusercontent.com/13919702/48299413-401ef780-e4cd-11e8-9838-f5314ee4a4b7.jpg)

**Comment by ReinerBforartists** [comment]
The double menu entries in the tools tab and the topbar are each a bug. Brecht stated that the double menu entry topbar versus tools tab is intended though. Which makes somehow sense. The user can then decide if he wants to work with the topbar or the tools tab in the properties editor.

**Comment by ReinerBforartists** [comment]
Nothing to fix at this point. The double data set in the header and the properties editor is by design. Like our double data set with the toolbar. 

We will tackle the real double menu entries at a one by one base when we stumble across them.

Closing.
