### ISSUE TITLE
3D View - Grease Pencil - Draw Mode - Icons for "Delete Active Keyframe" and "Delete Duplicate Frames" too similar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2972]
![image](https://user-images.githubusercontent.com/35357409/164364617-ac347305-5ecf-4ca1-9406-17787ce70e1d.png)

Icons for "Delete Active Keyframe" and "Delete Duplicate Frames" too similar. Both are delete icons, but they both do different things. They are also in two different panels - but look very similar. Might be good to have another icon for at least one of these.

**Comment by ReinerBforartists** [comment]
The functionality is very similar. That's why. We cannot invent a own Delete icon for every delete tool. In the clean up panel we have two delete tools. Here it makes sense. But not across different panels. 

The purpose of the icons is to give orientation. And this is given here.

**Comment by Draise14** [comment]
Ah ok. I was having difficulty in icon mode with the panels, there are 4 red X's and I had to either use a tooltip or read the panel title and memorize what each did to use it well. Just pointed it out. 

Do we have another delete icon that could be used to help.. tag a visual difference of some kind?

Should I close? No problem.

**Comment by ReinerBforartists** [comment]
Hm. I will have a look if i can come up with a delete duplicate frames icon. No promise.

But we can in general not invent a single icon for every delete functionality in the UI. This would be several dozens more icons.

**Comment by ReinerBforartists** [comment]
Fixed in master

3D View - Grease Pencil - Draw Mode - Icons for "Delete Active Keyframe" and "Delete Duplicate Frames" too similar #2972
