### ISSUE TITLE
Update knife tool hotkeys

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2973]
We miss two entries for the knife tool in our keymap. The one is mandatory. Only selected. Where i am not so sure with is the Left Mouse entry.

Needs investigation.

![knife](https://user-images.githubusercontent.com/13919702/164749582-b080899f-b5a9-4bd7-bf84-bc4e17a62f01.jpg)

**Comment by Blenux** [comment]
K is to switch to the tool.

Shift+K will only cut the selected faces (notification will popup if none is selected), anything not selected won't get cut, there is a option to enable it in the header or active tool panel.

https://user-images.githubusercontent.com/25260650/164887627-ef42d798-e798-4664-9c57-7c7c3ca252a5.mp4

Left Mouse is the actual cutting.

Hope this helps (watched those Youtube vids :D ).

**Comment by ReinerBforartists** [comment]
Many thanks :)

**Comment by ReinerBforartists** [comment]
Ah, wait, Blender calls still the old knife tool with the hotkey. We use the builtin tool already. 

Now's the question if we can even add a hotkey shift k here to call the knife tool from tool shelf with only selected on. I don't see such an option really. The only thing is we could add the old knife tool. But this would conflict with the new one then. It remains difficult ...

![oldandnew](https://user-images.githubusercontent.com/13919702/165074167-b759723f-e490-4164-918a-8351ce4b5b1f.jpg)

**Comment by ReinerBforartists** [comment]
Interesting. I thought of adding the old knife tool back as a legacy entry. But they don't have a menu entry for the old knife tool in Blender. Hotkey only tool ...

**Comment by ReinerBforartists** [comment]
I had a last idea to add a wm.context_toggle, but this doesn't work. There is no way to add a hotkey to the Only Selected checkbox. Odd.

Okay, giving up here. There is nothing that we can do. Maybe adding back the old knife tool. Let's put this issue on ice and think about it a bit more.

![noway](https://user-images.githubusercontent.com/13919702/165077478-15801e73-0186-4469-aed3-cab95823b694.jpg)

**Comment by ReinerBforartists** [comment]
Giving up here. I will not follow down this rabbit hole.
