### ISSUE TITLE
Sequencer - Strip Context Menu - Fade menu has missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2980]
![bforartists_5qpom3A4Ph](https://user-images.githubusercontent.com/35357409/165887633-ab3ad500-6a97-4ab5-a2bb-3d3e8c3c0336.png)
When you select a strip, then double right click - you will see the strip context menu. Then go to "Fade" and notice there are no icons. 

In the same menu in the header, there are icons that exist. 
![bforartists_r2FWoI9u8D](https://user-images.githubusercontent.com/35357409/165887641-77eb1355-b67d-4cd0-8f0a-9d5eff002710.png)

Probably should make it consistent.

**Comment by ReinerBforartists** [comment]
Hm, shall we use the enum in the regular menu? Or add icons to the enum?
