### ISSUE TITLE
NLA - Bake Action in the Edit Menu needs icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2985]
![rutview_CTg4zJiEml](https://user-images.githubusercontent.com/35357409/166331332-174eb638-44e5-4728-a9cc-5b51f84a083d.png)

Location: NLA>Edit menu

New operator needs new icon.

**Comment by ReinerBforartists** [comment]
New task needs new image ^^

**Comment by Draise14** [comment]
Pending a new build.

**Comment by Draise14** [comment]
Image added now!
