### ISSUE TITLE
Geometry Nodes - New "Named Attribute" Nodes needs update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2986]
![rutview_XsEbYlR2Nv](https://user-images.githubusercontent.com/35357409/166331376-5e1e00e9-a9be-4546-9dcb-dfe646ad356b.png)

![rutview_WCBuMFQhMk](https://user-images.githubusercontent.com/35357409/166331379-896a1c6e-5b0f-4477-aec4-b952cbc0d86a.png)

Task:
- Add icons to new entries in the Add Menu's and Add shelves
- Update documentation
- Update tooltips

**Comment by ReinerBforartists** [comment]
Also here, an image speaks thousand words ...

**Comment by Draise14** [comment]
Images added

**Comment by ReinerBforartists** [comment]
Do you want to try to create this two icons? :)

**Comment by ReinerBforartists** [comment]
We have still the tutorial here: https://www.bforartists.de/data/tuts/Icontutorial.pdf

Note that i use the Visibone palette in Gimp. You should use this palette too to have consistent colors in the UI.

And don't forget to put the created icons also into our file repository. The png file, and the svg file. https://github.com/Bforartists/files/tree/master/iconset_bforartists_2

![visibonepalette](https://user-images.githubusercontent.com/13919702/166420911-eec08419-edfe-4308-9767-5513d79ee909.jpg)

**Comment by Draise14** [comment]
I remember doing this once, but it is quite involved. I will have to try do this tomorrow. I already have a mind for the two icons:

- The attribute tag and delete together
- The attribute tag and save together

**Comment by ReinerBforartists** [comment]
Don't forget to commit the created icons to the file repository when done :)

**Comment by Draise14** [comment]
Gonna try give this a go now. I am trying to get two versions of Inkscape going, since I'm using the beta for speed and features - so 0.96 is a bit behind. Not sure how to have two versions of it though.

**Comment by ReinerBforartists** [comment]
As a note, don't save the icon sheet with the new Inkscape version. The defaults are different. And our python blender_icons_update.py file differs from the blender_icons_update.py in Blender. You would screw up the icon creation.

**Comment by Draise14** [comment]
Ok.. now compiling to test.

**Comment by Draise14** [comment]
Eureka!!!! Back in the icon making business baby!

![image](https://user-images.githubusercontent.com/35357409/167237993-4b8ed4d5-d162-4f63-9133-9418db7bd72c.png)

Can close and commit now.
