### ISSUE TITLE
Presets - Add and remove theme button - separate tooltips

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2989]
We have the same tooltip here for add and subtract. Should be separated.

![twobugs](https://user-images.githubusercontent.com/13919702/166514414-ffebb531-445b-4613-9ea4-5c38812341bd.jpg)

**Comment by Draise14** [comment]
Hey there @ReinerBforartists , looks like I'm out of time before the devbuild, and I'm not sure how to do this one for this week or early next.

**Comment by ReinerBforartists** [comment]
Ah this one is one of those rare cases that is not to resolve. The tooltip resides in a python file. No idea how this is connected.

Well, we could add our own operator here i guess. But that's very unelegant. And this operators are nearly not used by Users.

So giving up here.
![preset](https://user-images.githubusercontent.com/13919702/167242143-f08df674-ee7a-4fae-99b8-4bcb480bc096.jpg)
