### ISSUE TITLE
Wrong mode for keybind

### ISSUE THREAD

**Issue by CoralynnMay** [Bforartists/Bforartists#2992]
**Describe the bug**
assigning a shortcut for voxel remesh in sculpt mode adds the keybind for object mode.

**Desktop (please complete the following information):**
Windows 10, RTX 2070 Super

![image](https://user-images.githubusercontent.com/28240025/166697906-cc1a6a21-97eb-44c3-84df-56e7bf8d2213.png)

**Comment by ReinerBforartists** [comment]
Hi Coralynn,

This is a known issue with the Blender Keymap manager. When you remove this hotkey in Blender, and then reassign it, then you end in the same situation. It's just that Blender has a hotkey assigned to this tool already. You need to manually fix it by yourself, sorry.

There is unfortunately nothing that we can do here. The Blender keymap manager is in big parts simply broken. Even Blender developers are lost with a fix here. This fish is too big for us. I have reported similar issues more than once now.

Sorry that i have no better news here.
