### ISSUE TITLE
Node Editors - New Seperate/Combine Color nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2998]
![image](https://user-images.githubusercontent.com/35357409/167507705-c0e244ff-3eb4-4813-af88-56e199f2041f.png)
![image](https://user-images.githubusercontent.com/35357409/167507777-a39559ab-f2f3-484b-b4b5-ee4a9313161a.png)

New nodes, Combine and Separate Color
Located both in compositor, shading and textures nodes

These need to be added to the toolshelves with icons. 

Relevant Blender task:
https://developer.blender.org/D14034

EDIT:
Located in all 3 node editors: Compositor, Geometry Nodes and Shader Nodes
![rutview_QU9rOT5adG](https://user-images.githubusercontent.com/35357409/168324203-27887e98-084e-4a04-b637-a53343389ebc.png)
![rutview_lTDMK2Abuo](https://user-images.githubusercontent.com/35357409/168324212-7ccaa13e-8094-4358-a6d1-9e878537f7ed.png)
![rutview_nQuWUis4ya](https://user-images.githubusercontent.com/35357409/168324220-cdff831e-d587-46aa-850f-551b0e9b846f.png)

**Comment by ReinerBforartists** [comment]
Ah, and you assigned yourself to the only solveable issue :D

**Comment by Draise14** [comment]
If you want this one, go for it. Will focus on updating the other tasks then try doing them.

**Comment by ReinerBforartists** [comment]
Okay. I'll grab it then. Thanks @Draise14  :)

**Comment by ReinerBforartists** [comment]
Draise, please always add a shot with the whole menu if possible. This makes it easier to find it. 

I now have to go through the three node editors, and have a look at every sub menu in the add menus ...

**Comment by Draise14** [comment]
Ok, updated the description with the screen caps and locations. They are in all 3 editors.

**Comment by ReinerBforartists** [comment]
Many thanks :)

**Comment by ReinerBforartists** [comment]
Have you noticed how "consistent" this again is? Two times in the converter menu, one time in the Color menu ^^

**Comment by ReinerBforartists** [comment]
I guess the tooltips are also missing?
And the entries in the rna_nodetree.c . This is usually part of the merge, to put placeholder icons in place.

**Comment by ReinerBforartists** [comment]
This task is getting bigger and bigger. Seems that we need to fill in the texture nodes already into the rna_nodetree.c file at this point. We will see.

**Comment by ReinerBforartists** [comment]
Take care with the manual update. In the shader and compositor some nodes are now removed.

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/168336435-dff0f88f-6448-4d7d-adb5-21929f987e81.jpg)

**Comment by Draise14** [comment]
Ok, so this is done, can I document this one with all it's spaghetti? 

Just have to say, you have documented the chapters in a easy to browse way. Nice work.

**Comment by ReinerBforartists** [comment]
Thanks :)

What exactly do you mean?

**Comment by Draise14** [comment]
Ah, I can do the documentation for this task, and that the documentation chapters/files is nicely organized.
