### ISSUE TITLE
Dopesheet - Add Discontinuity (Euler) filter to Dope Sheet with icon for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2999]
![rutview_RjSZ6xliHG](https://user-images.githubusercontent.com/35357409/168301287-110694cc-a79f-482e-8c03-66a54ad89c9e.png)

An Fcurve operator is also now accessible from the Dopesheet - and now it located in the header. Needs an icon and made sure it's consistent in the menu order with the Fcurve editor. 

Relevant Blender Task:
[https://developer.blender.org/D14015](https://developer.blender.org/D14015)

**Comment by ReinerBforartists** [comment]
PIIIIIC ! :D

**Comment by Draise14** [comment]
Will work it tomorrow.

**Comment by ReinerBforartists** [comment]
PIIIIIIIIIC :D

**Comment by ReinerBforartists** [comment]
Not to solve without further information
