### ISSUE TITLE
3D View - Curve Object - Edit - New operator mode to snap to surface

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3000]
Status:
This is still an Experimental
![rutview_DeLv6qw85C](https://user-images.githubusercontent.com/35357409/168299628-017a36e8-fb0b-460d-afef-1b0f900750dd.png)

This would be the Curve Object Type edit/sculpt mode. 
![rutview_Kxc7926Tj9](https://user-images.githubusercontent.com/35357409/168299641-79c3ceee-9b98-471e-84cd-098cd4b66448.png)

![image](https://user-images.githubusercontent.com/35357409/167509208-a40b76a7-8be8-423e-9c07-145eadb7352c.png)
There is a new [Experimental] operator mode "Deform" and "Nearest" when snapping to surface. So there is a new operator listed in the Curve header menu.

`snap_curves_to_surface`

This needs an icon and probably tooltip. 

Relevant Blender task:
https://developer.blender.org/D14873

**Comment by ReinerBforartists** [comment]
Let's have a look here

**Comment by ReinerBforartists** [comment]
I cannot find the menu O_O

Which object is it? I have tested a curve, a grease pencil and a mesh with a particle system so far. What do i overlook?

**Comment by ReinerBforartists** [comment]
Not to solve without further information

**Comment by Draise14** [comment]
Yeah, this is an experimental feature, Blender committing development code to master still throws me off on the absurdity...

**Comment by ReinerBforartists** [comment]
I see. Thanks. Haven't thought of experimental features. My fault :)

**Comment by Draise14** [comment]
No longer experimental, now already done and closed.
