### ISSUE TITLE
Bforartists starts with a Blender logo at Linux

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3002]
I thought we have long fixed this issue. But now it is back. Bforartists starts with a Blender logo at Ubuntu 22.04

Needs a fix

![wrongicon](https://user-images.githubusercontent.com/13919702/167597358-f8b8a91a-e38f-4b69-a4a6-3a18102cbb89.jpg)

**Comment by ReinerBforartists** [comment]
Where does this logo come from ...

**Comment by ReinerBforartists** [comment]
This is something to get mad at. I have no idea where this icon comes from. We do have a few Blender icons left for the MSI installer. But besides that, there is no colored Blender logo left in the repo. And there is no Blender installed at this Ubuntu. 

So where does this icon come from O_O

![icon](https://user-images.githubusercontent.com/13919702/168128626-c0e8cd8e-9e83-474e-bed0-339806f2c503.jpg)

**Comment by ReinerBforartists** [comment]
Hm, this folder also contains colored versions. But is it the icon from here? As told, this is for the MSI windows installer. Linux should not pull an icon from here.

![colored](https://user-images.githubusercontent.com/13919702/168129746-131ce325-60ca-43db-a777-cfb8f2039f13.jpg)

**Comment by Blenux** [comment]
Not just a Ubuntu issue, Arch is the same (AppImage also).

**Comment by ReinerBforartists** [comment]
Yes, thanks, already noticed :)

**Comment by ReinerBforartists** [comment]
I will now try to replace these icons. Let's have a look if this helps.

**Comment by ReinerBforartists** [comment]
Now let's have a look what compiles at Ubuntu ...

**Comment by ReinerBforartists** [comment]
Nope. Search continues ...

**Comment by ReinerBforartists** [comment]
I am running out of ideas here. It's no png file, it's no svg. Where does this icon hide? -.-

**Comment by ReinerBforartists** [comment]
Related https://github.com/Bforartists/Bforartists/issues/1745

**Comment by ReinerBforartists** [comment]
No luck. This was not it. 

But i found a blender_thumbnailer.cc file. Seems that the icon gets extracted from a blend file. Crazy stuff ...

source\blender\blendthumb\src\blender_thumbnailer.cc

And related is 

source\blender\blendthumb\src\blender_thumbnailer.cc

**Comment by ReinerBforartists** [comment]
@iyadahmed, i know you don't have Linux anymore. But in case you get a VM with a linux running at your win or mac, could you please have a look here? I am lost with linux.

**Comment by ReinerBforartists** [comment]
Giving up. I have no idea.

**Comment by iyadahmed** [comment]
> @iyadahmed, i know you don't have Linux anymore. But in case you get a VM with a linux running at your win or mac, could you please have a look here? I am lost with linux.

Will do, I think I have a plan to figure out

**Comment by iyadahmed** [comment]
Answer from Blender devs
![image](https://user-images.githubusercontent.com/25552173/169827972-32deadc1-5b78-4f7a-9740-8438c5a578af.png)


so we should work on this file, it even has a script in it to generate the icon
https://github.com/Bforartists/Bforartists/blob/master/intern/ghost/intern/GHOST_IconX11.h#L12

**Comment by ReinerBforartists** [comment]
Please always use the issue title for the commit. This includes the issue number, and then the commit is automatically linked to the issue. And then you can easily follow every old issue and its solution :)

Just curious, which script did you use here to recreate the icon? This might be of interest in case that in five years we are in trouble to change the icon again.

This is another important point. Always make sure to post the solution in the issue once it is solved. You might need to return to it. In the very most cases it is clear by the commit. But here it is not.

**Comment by iyadahmed** [comment]
In the C file above they wrote a Python script in file comments
I exported 16, 32, 48, 64 square pngs from the Bforartists svg icon and used them with the script

**Comment by ReinerBforartists** [comment]
Perfect. Thanks :)
