### ISSUE TITLE
Shader Nodes - Make the Combine/Sperate Nodes mode RGB/RGBA dropdown naming relevant to the editor

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3006]
In the Shader nodes, you can only combine and seperate RGB. But in the other editors you can combine/seperate RGBA

**Shader Nodes:**
![bforartists_AEig1Q51Gg](https://user-images.githubusercontent.com/35357409/168395572-def2b645-26f5-492b-b580-a72eb3e458e2.png)

In the compositor and geometry nodes, you can combine RGBA but the title still says RGB. 

**Geometry Node**
![bforartists_UtZQnvgqMy](https://user-images.githubusercontent.com/35357409/168395619-b3c0fb80-0eed-4df5-98b2-518b3732315c.png)

**Compositor:**
![bforartists_t11JyByC4q](https://user-images.githubusercontent.com/35357409/168395637-9ae596be-1fc9-49ad-aaf4-56ce6f405a28.png)
![bforartists_fQIykhv8IZ](https://user-images.githubusercontent.com/35357409/168395639-2284b4e9-7b95-4c09-b5c3-833549004f12.png)

Making this evident that they are slightly different will help make the shader UX of splitting and combining RGBA obvious by being intentionally different than the common denominator, not to cause confusion. 

If a user is used to combining and splitting RGBA textures, and then works in the shader nodes, he'd have to use the same "equivalent" mode of the same node and then find he has a missing A channel (which in the shaders is included already). 

Task:
- See if it's invasive to rename the drop down entry of RGB to RGBA 
- If not too invasive, work it. 
- Rename the RGB entry of the compositor and geometry nodes to RGBA

**Comment by ReinerBforartists** [comment]
I fear this is nothing that we can do here. There is always the API involved too. And then we break the compatibility. We might want to ask the Blender developers for this change.

**Comment by ReinerBforartists** [comment]
Phew, cannot find the menus at all. 

The commit in question: * Nodes: Add general Combine/Separate Color nodes

**Comment by ReinerBforartists** [comment]
Found it. 

source/blender/makesrna/intern/rna_nodetree.c

```
static const EnumPropertyItem rna_node_combsep_color_items[] = {
    {NODE_COMBSEP_COLOR_RGB, "RGB", ICON_NONE, "RGB", "Use RGB color processing"},
    {NODE_COMBSEP_COLOR_HSV, "HSV", ICON_NONE, "HSV", "Use HSV color processing"},
    {NODE_COMBSEP_COLOR_HSL, "HSL", ICON_NONE, "HSL", "Use HSL color processing"},
    {0, NULL, 0, NULL, NULL},
};
```

This menu is shared across all three nodes. And we would have to implement our own solution here. 

So i vote for closing this issue. RGB is clear enough, no matter if the alpha channel is mentioned or not.

**Comment by ReinerBforartists** [comment]
I'll close this one if you don't mind :)
