### ISSUE TITLE
Add and use the new Geometry Nodes icon after merge

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3007]
New Node Icons
![image](https://user-images.githubusercontent.com/35357409/168633795-4bc7a105-23e3-4581-a355-17877d49ac02.png)

Blender devs made a new icon for geometry nodes, maybe we can use it directly or after modifcation
https://github.com/blender/blender/commit/28240f78cefd880e65c71a971570425fcbab9264

**Comment by ReinerBforartists** [comment]
It's a replacement for an existing icon from what i can see. So you want to throw out our icon, and use their icon instead?

**Comment by iyadahmed** [comment]
Only for geometry node modifier yeah, I mean maybe we can make a different icon for Geometry nodes instead of the generic node tree and modifier icon, if it is not worth it we can close this task

**Comment by ReinerBforartists** [comment]
Could you post a image with the differences? I am currently not sure ...

**Comment by iyadahmed** [comment]
Ah ok
https://code.blender.org/2022/05/geometry-nodes-icon/

**Comment by Draise14** [comment]
Ok, digging the code, doing a pre-compile, and will try fix this. Looks like Blender is starting to add more icons - which is nice. Still monochrome lineart, but it's.. something.

**Comment by ReinerBforartists** [comment]
Just remember, we have as double as much icon in the sheet already. Chances are that we have the needed icon already somewhere.

**Comment by ReinerBforartists** [comment]
Ah, and remember that you need to setup your Inkscape 1.2 correctly now, with the origin down left ...

I have finished the Inkscape task today :)

https://github.com/Bforartists/Bforartists/issues/2157

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/168640011-3fd16e57-4371-4da9-a979-0c5ae7dae0db.png)

Ok.. let's refine this task: 

**Current Status:**
1. We have the geometry nodes group = node group icon. 
2. Blender added a custom Geometry Nodes icon for the stack/modifier. It's a bunch of spheres or circles, like particles. 

![image](https://user-images.githubusercontent.com/35357409/168646978-9947aa1f-2ee9-471f-8b77-de97066f29f3.png)

So I will refine the proposal.

I'm currently trying to find a good icon for GN from what we already have.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/168654045-7253d83a-e806-42b6-bb0c-c725fdf5536f.png)

I think this one is more representative of what is a Geometry Nodes: a simple chunk of geometry, or multiple instances of geometry. It's also grey, so old association to group nodes on the grey would still be there. Grey and white also is "Mesh Data". Not too much of a break with colour coding. 

I do think a new one should be used though...

**Comment by Draise14** [comment]
![inkscape_0Q5EuNdMzQ](https://user-images.githubusercontent.com/35357409/168657316-56147abc-695a-45b9-a1b2-a26efea08260.png)

Ok, my favorite is number 04:
![image](https://user-images.githubusercontent.com/35357409/168657357-14c5b898-986c-4c96-a26c-85a79c74f031.png)

Features:
- Similar layout to the old node groups (grey and general shape)
- Color is of default geometry
- Sticks out as a modifier
- No-longer confused with Node Groups
- Cubes to show Geometry. 

**Compositor Nodes** = Stack of composites
**Shader Nodes** = A Shader Ball
**Geometry Nodes** = Generated Geometry

**Comment by Draise14** [comment]
Compiling a test build on the node now, had to commit beforehand, one second.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/168693557-44b48222-e21a-4e57-91c2-1cd90cf1b6e0.png)

Ok! Now done and compiled successfully. Was a bit of an up and down since I was bouncing between two computers, but got it going. Hopefully I can get my render node working with Inkscape 1.2 in the future to not bounce so much.
