### ISSUE TITLE
Website - Log in has a Critical Error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3014]
![image](https://user-images.githubusercontent.com/35357409/169575290-40cefb2e-b433-4a64-ac4d-dc99ee14d1ad.png)

When trying to log in to the website, there is a critical error and I can't log in again. 

Tested:
- Firefox 
- Chrome

Cleared Cookies, still no fix.

**Comment by Draise14** [comment]
From some quick digging, looks like it's something that needs to be fixed backend. I don't have that access so can't really do much. Could be an addon or theme issue that's breaking it. 

[https://www.wpbeginner.com/wp-tutorials/how-to-fix-the-critical-error-in-wordpress/](https://www.wpbeginner.com/wp-tutorials/how-to-fix-the-critical-error-in-wordpress/)

**Comment by ReinerBforartists** [comment]
Oh nice. I did see this nearly coming, but It is not THIS easy to fix :D

I did two small changes to make the page more secure. Seems that minimum one of these changes strikes back now. I will have a look.

**Comment by ReinerBforartists** [comment]
Should be fixed. Thanks for the report.
