### ISSUE TITLE
3DView - Mesh Object - Missing Auto Shade Smooth Icons 

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3015]
Blender devs added the Shade Auto Smooth operator not long ago and now have a missing Icon in the Object / Object Context Menu's.

![sas1](https://user-images.githubusercontent.com/25260650/169683624-f4cc5039-018c-40f3-bbc3-5e76970c0aed.png)

![Screenshot 2022-05-22 174140](https://user-images.githubusercontent.com/25260650/169685078-61e81deb-d007-43e3-ba27-554ff16485a3.png)

**Comment by Blenux** [comment]
Please let me know if I have done this correctly.

**Comment by Draise14** [comment]
Nicely done! You did it correctly. We will be adding you to the contributors credits list now! Thanks for this. 

Cants wait to see what else you come up with.

**Comment by Draise14** [comment]
The next step here is documentation, but I can do that part without a problem.
