### ISSUE TITLE
Smart delete addon fails

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3017]
The smart delete addon is one of our vital tools in edit mode. But i have a situation where it fails with an error. I still try to reproduce the problem. So no file at this point.

Needs investigation.

![smartdeletefail](https://user-images.githubusercontent.com/13919702/169707125-d2c08446-8cbc-4d42-bdf3-330030bc45e6.jpg)

**Comment by Draise14** [comment]
I haven't found any issues with it lately. What do you need to do to reproduce this?

**Comment by ReinerBforartists** [comment]
If i just would know. I restarted, and the problem is gone XD

**Comment by ReinerBforartists** [comment]
No idea what this hiccup was. But it is not to reproduce anymore. I'll keep an eye at this ...

**Comment by ReinerBforartists** [comment]
Didn't happen again. So i guess it was a unique hiccup. I will nevertheless keep my eyes open here.
