### ISSUE TITLE
Mac Build (5/22)

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#3019]
https://www.dropbox.com/s/h7w943v21669rcd/rw.Bforartists-devbuild-22-05-22-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Hey sean,

Many thanks for this version. But there seems to be something wrong here. This zip file is around 700 Mb big. And the usual version has just around 215 mb. Could you please check your upload again?

Kind regards 
Reiner

**Comment by seanr** [comment]
Oops, looks like the DMG part of the script didn't completely correctly and I failed to notice it. Looking into it.

**Comment by seanr** [comment]
@ReinerBforartists here's the correct one, sorry about that: https://www.dropbox.com/s/rsk0j1dg4658uth/Bforartists-devbuild-22-05-22-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
No problem. Such things happens. Four eyes simply sees more than two. Many thanks for the fix. Uploading :)

**Comment by ReinerBforartists** [comment]
Up and running.
