### ISSUE TITLE
Buggy recent menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3023]
I have run into this twice now, but am still not sure what provokes this behaviour. 

I work since two days at a grammophone mesh. So the recent menu is spammed with these files. Now i have loaded another file. And with that the recent menu shows up some project files before the grammophone mesh. 

When i restart Bforartists, then the recent menu content fits again.

Could you please have an eye at this with me? Could be a Blender bug. I was able to document this behaviour here now, but am still not able to reproduce it.

I will now empty my appdata directory to work with blank material. And then let's try if we can recreate this behaviour.

![recent1](https://user-images.githubusercontent.com/13919702/170671912-a36c5f62-000b-497f-aea9-89b1e38162a8.jpg)

![recent](https://user-images.githubusercontent.com/13919702/170672198-bd8d3f92-f8aa-4490-8c8a-aca0a71a3a34.jpg)

**Comment by Draise14** [comment]
I have only seen conflicts when I have two instances of Bforartists running, the most recent one to close session will overwrite the most recent from the other session. The menu updates per most recent session, if you have two instances running at once, then the most recent will have priority in this menu.

**Comment by ReinerBforartists** [comment]
Ah, this could explain it. I will have an eye at this. Thanks Draise :)

**Comment by iyadahmed** [comment]
Maybe blender has this issue too

**Comment by ReinerBforartists** [comment]
Very likely. But first we need a way to reproduce it.

**Comment by ReinerBforartists** [comment]
Didn't happen again so far after removing the content from the appdata directory. So closing. I'll make a new task when i stumble across again.
