### ISSUE TITLE
Sequencer - Fade Menu entry doesn't have an icon, but others do. Make Consistent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3025]
![image](https://user-images.githubusercontent.com/35357409/170760657-209a7a21-45c9-4f7f-abb4-ab8787838f6f.png)

The Scene, Clip, Mask, Effect Strip, Transform all have icon in their entries. But Fade does not. 

Could be good to make this consistent atleast in this menu, they are useful with iconography, so will make the Fade menu also have an icon.

**Comment by Draise14** [comment]
For next week

**Comment by ReinerBforartists** [comment]
We are here at a point that we have discussed before. Sub menus have no icons by design. There are exceptions. In the add menu for example. But the rule is that sub menus does not have an icon. Which is a way to distinguish them from operators.

So, are you really sure that you want to do this?

**Comment by ReinerBforartists** [comment]
![iconfix](https://user-images.githubusercontent.com/13919702/171805172-4a13dd9a-72ed-4bc7-9930-abd06d71ef9e.jpg)

**Comment by ReinerBforartists** [comment]
Didn't it close automatically?

![autoclose](https://user-images.githubusercontent.com/13919702/171897569-7007629c-614e-4236-9f41-cbe3f99480c5.jpg)

**Comment by Draise14** [comment]
I think not, saw it open.

**Comment by ReinerBforartists** [comment]
:/

Linked issues should close automatically they promise. I will have an eye at it for the next time.
