### ISSUE TITLE
NLA - Default Anim Strip properties - make the NLA more useful as "Combine" on default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3028]
# Issue
![bforartists_2YH91y2SFu](https://user-images.githubusercontent.com/35357409/170824317-28fe823a-21aa-4580-9369-a064c6c26aff.png)
The NLA is designed to blend non-linear animation, combine strips and work with them. **Combine** is the active word here. 

The current default mode of all strips is "Hold" and "Replace". Which means tracks do not stack "layers" of animation nor does it allow chaining of actions over the other. If you have a chain of clips after the other, the first and top track one will take precedence over any other tracks and clips, essentially making the tracks and clips useless on first use. A broken UX. 

Desired use would be this:
![image](https://user-images.githubusercontent.com/35357409/170824305-512d706a-4f3c-48c0-9951-14706b9746b5.png)

1. Allow layering offset of clips when stacking for Animation Layers (no replacement of data, but expected layered data)
2. Allow chaining of clips without interference of other invisible clip data (no default holding of track data)
3. If you want to hold a clip, make it user intentional and secondary

Current defaults do not allow for a desired UX. Every single strip need to be re-configured to be useful. When working with more than a few strips, it's tedious changing them all, it's easy to miss one making the NLA UX frustrating. 

## Desired UX
New Defaults of all animation strips:
![image](https://user-images.githubusercontent.com/35357409/170824204-ed25b0a3-d63a-4be6-83ad-ab3b2a4993b9.png)

1. **Combine** allows the layering of clips easily, essentially allowing built in Animation Layers, a hot requested feature people need to animate (but don't realize it's already built in)
2. **Nothing** on hold allows for chaining of clips and blending them as expected. No invisible influence on an unclear hierarchy of clip influence (unless intentionally toggled)

# Task
- Investigate where these defaults are stored
- See if they can be changed
- Change them 

### Potential Issues
When creating animation clips as libraries for FBX and game engine, each track need to be a single animation clip. So you'd want to "isolate" each track. The "Replace" mode helps to do this with the most top track being the one you show, but we ALREADY have 3 methods of isolating tracks. It is essentially redundant. Existing methods: Star to isolate, Tick to Enable/Disable track, Tweak with the Isolate toggle to view active tweaked track. The "Replace" Mode is not useful as a default, only for special use cases.

**Comment by Draise14** [comment]
Too tired to find this one, and grepwin is a bit slow while I compile. I will hit the sack, and will store this for next release.

**Comment by Draise14** [comment]
Aha, found this one.
![image](https://user-images.githubusercontent.com/35357409/172914506-d42e5bad-bcf4-4f89-bc81-4887b1a435dd.png)

Compiling test build.

**Comment by Draise14** [comment]
Decided to keep the "Hold" so that regardless of the tracks, so it doesn't "jump" when layering. It felt more like layers, and the sequential alignment of tracks after the other still was expected UX... so there. I can breath. No more switching toggle and track types over and over and over again. 
![bforartists_T7TAHiTJlQ](https://user-images.githubusercontent.com/35357409/172951855-1f556cd3-bfe1-43e9-aaf3-516d9309fa57.gif)


Also... I test baking and it is defaulted to "Replace" which would be expected behaviour of combined tracks to a single baked track. 

_Now if only Blender could add colour, draggable handle widgets for the clips, and the ablity to drag THROUGH other clips... that would be great._

**Comment by Draise14** [comment]
Looks like changing the enum was not a good idea.

**Comment by iyadahmed** [comment]
Fixed in https://github.com/Bforartists/Bforartists/commit/f2b49617456d6cda55c2abcdb4da975b1d5d4398
