### ISSUE TITLE
Ubuntu fails to compile 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3029]
We have a problem with the current merge. Ubuntu fails to compile.

Current build text:

`- Build files have been written to: /home/x/bforartists-git/build_linux

Building Bforartists ...
make -s -C "/home/x/bforartists-git/build_linux" -j 2 install
Scanning dependencies of target bf_intern_clog
Scanning dependencies of target bf_intern_ghost
[  0%] Building C object intern/clog/CMakeFiles/bf_intern_clog.dir/clog.c.o
[  0%] Linking C static library ../../lib/libbf_intern_clog.a
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_Buttons.cpp.o
[  0%] Built target bf_intern_clog
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_C-api.cpp.o
Scanning dependencies of target bf_intern_guardedalloc
[  0%] Building CXX object intern/guardedalloc/CMakeFiles/bf_intern_guardedalloc.dir/intern/leak_detector.cc.o
[  0%] Building C object intern/guardedalloc/CMakeFiles/bf_intern_guardedalloc.dir/intern/mallocn.c.o
[  0%] Building C object intern/guardedalloc/CMakeFiles/bf_intern_guardedalloc.dir/intern/mallocn_guarded_impl.c.o
[  0%] Building C object intern/guardedalloc/CMakeFiles/bf_intern_guardedalloc.dir/intern/mallocn_lockfree_impl.c.o
[  0%] Linking CXX static library ../../lib/libbf_intern_guardedalloc.a
[  0%] Built target bf_intern_guardedalloc
Scanning dependencies of target bf_intern_libmv
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_CallbackEventConsumer.cpp.o
[  0%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/autotrack.cc.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_Context.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_ContextNone.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_DisplayManager.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_EventManager.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_ISystem.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_ISystemPaths.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_ModifierKeys.cpp.o
[  0%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_Path-api.cpp.o
[  0%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/camera_intrinsics.cc.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_Rect.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_System.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_TimerManager.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_Window.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_WindowManager.cpp.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/detector.cc.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_NDOFManager.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_DisplayManagerX11.cpp.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/frame_accessor.cc.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_SystemX11.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_TaskbarX11.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_WindowX11.cpp.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/homography.cc.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_ContextGLX.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_DropTargetX11.cpp.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_NDOFManagerUnix.cpp.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/image.cc.o
[  1%] Building CXX object intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_SystemPathsUnix.cpp.o
/home/x/bforartists-git/Bforartists/intern/ghost/intern/GHOST_SystemPathsUnix.cpp:94:1: error: expected unqualified-id before ‘return’
   94 | return user_path.c_str();
      | ^~~~~~
/home/x/bforartists-git/Bforartists/intern/ghost/intern/GHOST_SystemPathsUnix.cpp:95:1: error: expected declaration before ‘}’ token
   95 | }
      | ^
/home/x/bforartists-git/Bforartists/intern/ghost/intern/GHOST_SystemPathsUnix.cpp: In member function ‘virtual const char* GHOST_SystemPathsUnix::getUserDir(int, const char*) const’:
/home/x/bforartists-git/Bforartists/intern/ghost/intern/GHOST_SystemPathsUnix.cpp:92:1: error: control reaches end of non-void function [-Werror=return-type]
   92 | }
      | ^
cc1plus: some warnings being treated as errors
make[3]: *** [intern/ghost/CMakeFiles/bf_intern_ghost.dir/build.make:375: intern/ghost/CMakeFiles/bf_intern_ghost.dir/intern/GHOST_SystemPathsUnix.cpp.o] Fehler 1
make[2]: *** [CMakeFiles/Makefile2:3677: intern/ghost/CMakeFiles/bf_intern_ghost.dir/all] Fehler 2
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/logging.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/reconstruction.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/track_region.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/tracks.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/intern/tracksN.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/autotrack/autotrack.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/autotrack/predict_tracks.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/autotrack/tracks.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/base/aligned_malloc.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/image/array_nd.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/image/convolve.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/conditioning.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/euclidean_resection.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/fundamental.cc.o
[  1%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/homography.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/panography.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/panography_kernel.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/projection.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/multiview/triangulation.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/numeric/numeric.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/numeric/poly.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/bundle.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/camera_intrinsics.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/detect.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/distortion_models.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/initialize_reconstruction.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/intersect.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/keyframe_selection.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/modal_solver.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/packed_intrinsics.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/pipeline.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/reconstruction.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/reconstruction_scale.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/resect.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/simple_pipeline/tracks.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/brute_region_tracker.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/hybrid_region_tracker.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/klt_region_tracker.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/pyramid_region_tracker.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/retrack_region_tracker.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/track_region.cc.o
[  2%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/trklt_region_tracker.cc.o
[  2%] Linking CXX static library ../../lib/libbf_intern_libmv.a
[  2%] Built target bf_intern_libmv
make[1]: *** [Makefile:163: all] Fehler 2
make: *** [GNUmakefile:354: all] Fehler 2
x@ubuntu:~/bforartists-git/Bforartists$ ^C
x@ubuntu:~/bforartists-git/Bforartists$ 
`

**Comment by ReinerBforartists** [comment]
@iyadahmed , i have assinged you here, could you please have a look at the problem?

**Comment by ReinerBforartists** [comment]
Ah i think i have the baddie already. Testing ...

![baddie](https://user-images.githubusercontent.com/13919702/170976020-707bfed8-e512-4699-b42d-d8650ed540c1.jpg)

**Comment by ReinerBforartists** [comment]
The commit fixed the issue. And cool. Now Bfa starts in my VM again =3


![fixed](https://user-images.githubusercontent.com/13919702/170981713-7cd54105-1512-454d-ae5f-89ea7b8e82b7.jpg)

**Comment by ReinerBforartists** [comment]
Ah, forgot to push through a branch. Sorry ^^

**Comment by iyadahmed** [comment]
No need actually just a small change 😄
