### ISSUE TITLE
Dopesheet - Text colours of armature bone tracks text illegible

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3030]
![image](https://user-images.githubusercontent.com/35357409/171080897-ca5bf252-ba18-4457-bc46-a41977faacac.png)

Text contrast of the default theme in the Dopsheet and Timeline are illegible. 

## Task
- Find the theme or C code that formats this
- Improve it, save startup blend and default theme.

**Comment by ReinerBforartists** [comment]
Related https://www.bforartists.de/forums/topic/bfa-colors-makes-text-illegible/

**Comment by ReinerBforartists** [comment]
Hm, The current color scheme can be improve for sure. But we don't have this light blue color in our theme from what i can see. So before continuing here, could somebody please reproduce how to get this light blue color theming in the animation editors?

![nobrightblue](https://user-images.githubusercontent.com/13919702/171573373-4d474678-ba68-4c2f-bcde-cf2939e168ca.jpg)

**Comment by Draise14** [comment]
I think I know how to reproduce this. The colours are set by the bone colours of an armature.

1. Assign bone to a bone group
2. Set the bonegroup colour to something
3. See the colours.

![image](https://user-images.githubusercontent.com/35357409/172016705-f9d12cc5-65eb-45fc-843e-21181dde7d81.png)

**Comment by Draise14** [comment]
To fix this, I would have no idea how, it would have to be a C change on how these colours are drawn after selecting the bone groups, and then a luminescence would have to either be dropped so they are not as light or less saturated. but the colours reflect the bone group colours. Any rig could have any colours, including custom colours so this is hard one to fix. It's not theming - it is how it draws in the dopsheet/timeline.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/172017442-4dd5a0af-dcb6-448f-9180-3294f829e939.png)

Aha, got an idea. Change the bone theme defaults. They are very luminous and saturated, and the "Active/Selected" there is not a lot of contrast. Text goes from black to white when selected. So.. this CAN be fixed by fixing the defaults.

**Comment by ReinerBforartists** [comment]
Good news, and thanks for reproducing :)

**Comment by Draise14** [comment]
![bforartists_8NFth5dsMv](https://user-images.githubusercontent.com/35357409/172021257-30a40d4a-6f24-488c-934d-c58aa3b8db13.gif)

Ok, I found a more legible setup that could help for defaults. 

What I did:
- Made the rainbow organized with 6 colours, for 3 trinary contrasts. 
- Made the rainbow desaturate and deluminate for another set of 6 colours. 
- Added another dark RGB for a couple more colour groups on another luminance level
- Made the "Active" channel a nuetral 0.4-0.5 so it is consistent "Active" colour on all channel colours, and all the "selected" in viewport is the same highlight for legibility. 
- The unselected/selected tracks also is a nuetral grey highlight that works with both white and black text to show the " white/black text without a problem with hue conflicts. 

**Reason:**
The default white text on active and black selected needs to contrast on colour, but this is an issue - the text which is both white and black needs to contrast on hue (current problem). Changing hue to highlight active without a nuetral grey proved difficult to read what was "Active" and unselected/selected channels. The channels have the same active channel colour (white text), though they are unselected (black text)

Example difficulty reading with black and white text with a hue:
![image](https://user-images.githubusercontent.com/35357409/172021423-0087a4ae-c3ba-4de8-b39a-c466724cc552.png)

Difficulty seeing what is the "Active" channel with same colour as unselected:
![image](https://user-images.githubusercontent.com/35357409/172021467-161863eb-f5d8-4750-bc8d-e30f84490fed.png)

I assume the reason is because Hue adds luminence values to the pixels making too much hue actually harder to read with white text (lack of contrast) though it may look ok with black text. Removing hue can only happen with less luminance or saturation, but both make it hard to read for both black and white text. AND we have both white and black text on the same "Active Bone Highlight" track colour! 

So here is the fix:

Example of better legibility using no Hue on Active and all selected/unselected channels:
![bforartists_QAQKNnLz3Y](https://user-images.githubusercontent.com/35357409/172021371-e836cc03-78ca-4184-b05e-7f6baa30ac44.gif)


# Observations:
I think Blender needs to make the UX a little better. Couple the active vs selected bone colours together. 
- Active bone highlight = Active bone channel highlight (black text for light highlight)
- Selected bones highlight = Selected bone channel highlight (white text for dark highlight)
- Unselected bones colour = Unselected channel colour (white text for dark highlight + hue)
- Active track = Active bone channel highlight  (black text for light highlight)
- Selected track = Selected bone channel highlight  (white text for dark highlight)

But alas, the Active vs Selected theming is coupled to the one and same. This makes the channels look like they are active when in reality the white text implies active track/channel only. Not the "Active Bone Channel" colour. 

Un/Selected track = Active Bone Channel highlight

We can fix this by taking hue out of the equation to make the selected track/unselected track the same experience with the coloured bone channels colour UX, and then use white text with they grey of the "active" bone channels - and help visually searching the "Active" track as hueless track without too much backend work. 
![bforartists_0j4VMJZTQ9](https://user-images.githubusercontent.com/35357409/172021844-71756bc3-14a8-427a-9c00-256837fead91.gif)

## Legibility Test with another rig:
![image](https://user-images.githubusercontent.com/35357409/172021960-9ef9b59a-4b50-4679-b12d-003c9c6c7bf3.png)
![image](https://user-images.githubusercontent.com/35357409/172022027-33bd3e68-86d4-435d-9310-0e5299ac8368.png)


Now to commit this...

**Comment by Draise14** [comment]
Compiles successfully! Thanks for the theme tips @ReinerBforartists , more things to note!

![bforartists_CELmZhQAIs](https://user-images.githubusercontent.com/35357409/172026721-5eb52fd6-30cd-43c6-941e-7654cd5599ef.png)
