### ISSUE TITLE
GHOST_SystemPathsUnix.cpp - major differences between Bforartists and Blender

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3032]
@iyadahmed , @Draise14 

I had this fixed already with issue **Ubuntu fails to compile #3029**

Now i made a pull, and found that the GHOST_SystemPathsUnix.cpp is again in the state where it shows big differences between the GHOST_SystemPathsUnix.cpp files. Well, different to before, it compiles. But there shouldn't be differences between the two code bases for no reason. Especially when Blender users nullptr and we still use the old Null can make big trouble in the future.

I had it tested. So i wonder why it still failed for Iyad. He made his push after i pushed the fix. The need to solve a merge conflict should have been a warning that something is going on. Please keep your eyes open for such cases, and double check then.

And the other note is, please ALWAYS make an issue when you change anything, and be it one line in a single file. This change here was not done with the merge, but has its own commit. When i would have seen the issue, then i would have been able to stop the push already. And it also passed the second hurdle as it looks like. There was no pull request created for it. It went directly into the Master.

![noissue](https://user-images.githubusercontent.com/13919702/171807889-f3a41e1a-2f41-41ae-a149-48b15a86c480.jpg)

![differences](https://user-images.githubusercontent.com/13919702/171807897-c8bbed6a-6084-4580-b16c-0c067dfcf346.jpg)

**Comment by ReinerBforartists** [comment]
Cleaning up the file again ^^

**Comment by iyadahmed** [comment]
Hmm

**Comment by iyadahmed** [comment]
I copied Blender s ghost file

**Comment by iyadahmed** [comment]
Did you pull latest blender?

**Comment by iyadahmed** [comment]
https://github.com/blender/blender/blob/master/intern/ghost/intern/GHOST_SystemPathsUnix.cpp

**Comment by ReinerBforartists** [comment]
@iyadahmed , do you want to have a look here? I just realized it is good training :)

**Comment by iyadahmed** [comment]
Ok will take a look
