### ISSUE TITLE
Debug Build error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3040]
![image](https://user-images.githubusercontent.com/35357409/172268874-2a9734de-2659-425a-ad97-ef73f3236f9b.png)
![image](https://user-images.githubusercontent.com/35357409/172268901-8294ec76-d9d6-49e2-942c-101e06d59598.png)

At the moment the master cannot de a debug build.

This might be tied to  #3039

**Comment by iyadahmed** [comment]
Fixed by 497982021d5304b87b45d3c6097805e889123da0
