### ISSUE TITLE
Node grid subdivisions assertion

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3041]
When in debug build assertions are enabled
our node grid subdivisions does not conform to this assertion
Either change the assertion or change the node grid subdivisions option
![image](https://user-images.githubusercontent.com/25552173/172271172-23155365-8237-4ec6-a57a-08a076103d0a.png)

**Comment by Draise14** [comment]
Changing the grid could be done in theme defaults right?

**Comment by ReinerBforartists** [comment]
Not sure. Something to try and investigate.

**Comment by Draise14** [comment]
Ok, I had a look at the code that was provided, it's the same as Blender. But then I looked at the theme. It was at grid subdivisions of 7, instead of the max slider of 3. So I dropped it to three, compiled the theme and commit. 

I'm setting up a debug build now, but might take a while to verify.

**Comment by Draise14** [comment]
@ReinerBforartists I'm going to let my debug build finish, and go to bed, it's 2300 now, then will pull this one in the morning. If you want you can also pull this one for the official release if you think it's not too invasive incase you beat me to waking up.

**Comment by Draise14** [comment]
Wait, debug build done, no assertion error.

**Comment by ReinerBforartists** [comment]
Theme changes always requires to update the userpref_default_theme.c file. Did you update it? :)

**Comment by iyadahmed** [comment]
Btw the assertion happens when you open the editor if the value was out of range

**Comment by iyadahmed** [comment]
> Theme changes always requires to update the userpref_default_theme.c file. Did you update it? :)
> 
> EDIT, ah, yes you did. I found our 7 dots more comfortable by the way ...

We can bring it back to 7 and change the assertion to 7, and the slider to have a max of 7

**Comment by ReinerBforartists** [comment]
Ah didn't notice the conjunction between assertion and max slider value :/

Good catch.

**Comment by iyadahmed** [comment]
It is hardcoded not just max slider, my fault I made it look like so

**Comment by ReinerBforartists** [comment]
I didn't even notice ^^

**Comment by Draise14** [comment]
It was late lastnight. How do you change the assertion max value @iyadahmed? Maybe we can reopen this and revert the theme change. I do like more dots too.

I'll grep for the assertions, see what I find too. But we can do it for next week I guess.

**Comment by iyadahmed** [comment]
Ok one moment will do

**Comment by ReinerBforartists** [comment]
Freeze over. New version and new branch commited :)

Still at preparing the release though. But you can continue with commiting into master now.

**Comment by iyadahmed** [comment]
I noticed there's no difference between 7, 6, 5, or 4 subdivisions, not sure if this is my screen
can you confirm @ReinerBforartists ?

**Comment by ReinerBforartists** [comment]
With which version? We have now 3 ... ^^

**Comment by iyadahmed** [comment]
Maybe I'm missing something can you confirm 7 is different from 3?

**Comment by ReinerBforartists** [comment]
No it is equal in version 3.1.3.  It is capped at 3. No matter if you set it to 7.

But it was different in previous versions before they capped it to 3. In Bforartists 3.1.0 for example. The appearance is different though.

![310](https://user-images.githubusercontent.com/13919702/173103845-c14c4fa3-4d4b-4ef9-bd4b-4b14c4edaa1d.jpg)

**Comment by iyadahmed** [comment]
ah ok, will close it thenm, we can reopen it if needed
