### ISSUE TITLE
Dynamic tooltips for properties editor tabs and title-less tooltips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3042]
We had to revert to blender method of tooltips to fix a bug ( #3039 ), but the idea and objective still remains. 

![firefox_Xfj6wtQc9B](https://user-images.githubusercontent.com/35357409/172285120-335f46b0-02d0-4757-ae8f-f78b750e98f9.png)

- Make sure tooltips are dynamic with titles on properties tabs
- Make sure tooltips titles are consistent (not empty)

**Comment by ReinerBforartists** [comment]
It would be of interest to find the commit that made our code not longer functional.

**Comment by Draise14** [comment]
I am guessing it happened the week after release, since the last working build was the 10th of March. I will have to check the commit logs from that date.

**Comment by ReinerBforartists** [comment]
Checking the devbuilds at the server ...

**Comment by ReinerBforartists** [comment]
Lucky us that i haven't cleaned up the devuilds folder for a while. Devbuild from 16.04 works fine. Devbuild from 23.04 crashes. 

Hint, you can do a log search from the interface_region_tooltip.c file. That way you will only get the changes where this file was involved.

Sadly there are no changes at this file in this time frame. But it gives you at least the last working code.

![nochanges](https://user-images.githubusercontent.com/13919702/172564822-54676c0e-266c-42fa-b82d-4fcf13b844a4.jpg)

**Comment by iyadahmed** [comment]
I think changes in other files are also related

For example the blf.c file, in which the error happens actually

Reverting the interface**.c file prevents that error, so maybe this is a non active Blender bug (it exists but does not trigger with their interface**.c file)

**Comment by ReinerBforartists** [comment]
Indeed. I am not even sure if our code here is really the trouble maker. But a later change where we have to adopt to.
