### ISSUE TITLE
Splashscreen - Bforartists 3.2.0

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3043]
Blender 3.2 is around the corner, stable release is already available for download. 

This means a new splashscreen. We have @seanr great piece that was second voted a while back. It's still a worthy piece and he's been excellent with the mac builds, so let's use his piece this release. 

**Image link:**
https://cdn.discordapp.com/attachments/662286224253517834/976516742190866552/unknown.png

![image](https://user-images.githubusercontent.com/35357409/172655656-f0319c67-ea99-46b3-81a8-68db0b8f57f2.png)

**Task:**
- Create graphics and upload to build

**Comment by ReinerBforartists** [comment]
Ah, it is out. I will grab this splash and start with work tomorrow :)
