### ISSUE TITLE
Mac version for Bforartists 3 version 3.2.0

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3047]
Hey sean,

We have a new version up and running. Would you be so kind to create the mac installer for it? :)

https://github.com/Bforartists/Bforartists/tree/bfa3v3.2.0

**Comment by seanr** [comment]
https://www.dropbox.com/s/eioxpf4bx10j7ke/Bforartists-v3.2.0-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Many thanks. Uploading :)
