### ISSUE TITLE
NLA - Default to open Property Shelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3049]
![bforartists_3nCVc7tSUM](https://user-images.githubusercontent.com/35357409/172948282-b1e83d40-76f5-4e63-b05e-df373f335125.png)

For some reason the NLA has the Property Shelf closed. We default to these open to allow for accessibility and discoverability (tiny arrow not enough). I am caught repeat opening this over and over again.

**Comment by Blenux** [comment]
space_nla.c - line 82 - region->flag = RGN_FLAG_HIDDEN; 

Commenting that makes it appear, may need to do with other editors too for consistency?

I believe they are hidden since nothing is shown, until a action or keyframes (though same can be said for the tools).

**Comment by Draise14** [comment]
Oh glad you found this one. We should maybe go through all others too. I'll leave that for another task.
