### ISSUE TITLE
Export zipped textures package

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3052]
Just a crazy idea for cold winter evenings. In FL Studio you can export a project with all its external samples into one zip file.

Maybe this is achievable in Bforartists too. It would be much more convenient to share scenes this way than using packed blend files where you have to extract the textures afterwards.

![zippedexport](https://user-images.githubusercontent.com/13919702/173112632-a1eb5f80-88ef-4628-805b-0b10040289fa.jpg)

**Comment by iyadahmed** [comment]
Nice idea

**Comment by Draise14** [comment]
A bit like "Pack Project" from Unity also?

Zip everything plus dependencies and keep paths relative, would be awesome. Though packing then unpacking is.. possible, the project structure usually is broken or changed when unpacking. 

Good idea.

**Comment by ReinerBforartists** [comment]
Yes. That's the problem with packing :)

**Comment by ReinerBforartists** [comment]
It seems that such an addon already existed in Blender 2.79. But it got never ported. Let's have a look if it can be ported at all.

![packblendfiles](https://user-images.githubusercontent.com/13919702/197327217-f1172fb2-40a8-4169-957c-94195777c3ad.jpg)

**Comment by ReinerBforartists** [comment]
Hm it activates. These changes were easy. But exporting fails. Well, that was to expect :)

The unfunny part is, this addon is amazingly complex. And most probably takes the old renderer and lots of old Blender 2.7x code into account. So we might be better suited to start with a complete rewrite. The addon might nevertheless give us a few starting points.

Current state: 
[io_blend_utils_port_build1.zip](https://github.com/Bforartists/Bforartists/files/9843841/io_blend_utils_port_build1.zip)


![firststep](https://user-images.githubusercontent.com/13919702/197328149-89287d98-9f9e-4e58-abcc-16ef79a661c0.jpg)

**Comment by ReinerBforartists** [comment]
Another idea is to utilize the pack and unpack feature for our purposes. Then we "just" need to zip the unpacked result, and voila ...

**Comment by ReinerBforartists** [comment]
Haha, this error message is an open Blender bug :D

https://github.com/JacquesLucke/blender_vscode/issues/80

**Comment by ReinerBforartists** [comment]
Changing the trouble line to sys.executable as suggested crashes Bfa then. Seems that trying to port this addon is a dead road. At least for me. A shame, it was what i had in mind. And it already existed in Blender 2.79.

@iyadahmed , do you want to give it a shot?

![secondcrash](https://user-images.githubusercontent.com/13919702/197329634-ec580f71-26e1-4dfa-bf87-efdd7b3eec96.jpg)

**Comment by iyadahmed** [comment]
Soon will do

**Comment by Draise14** [comment]
Will postpone for an attempt for 3.6.0 or 3.7.0

**Comment by ReinerBforartists** [comment]
Shall we give up at it? It would be yet another addon to maintain ...

**Comment by ReinerBforartists** [comment]
> Yeah, let's close.

And closed :)
