### ISSUE TITLE
Template - Make 2D Animation template errors

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3054]
![bforartists_bedQeptVKO](https://user-images.githubusercontent.com/35357409/173199674-4c3670eb-bd24-47e8-bb18-0f73c352c09c.png)

When creating a template from "New from Template" from the 2D Animation template, it crashes. The `Startup.blend` for 2D Animation just needs to be recreated/replaced and this will fix. 

![image](https://user-images.githubusercontent.com/35357409/173199763-d4e5452c-ad40-495c-b806-81eefbf63f5b.png)

Version: Bforartists 3.2.0

**Comment by ReinerBforartists** [comment]
Odd. Here crashes nothing.

**Comment by ReinerBforartists** [comment]
Draise, could you please check again? As told, here it works.

**Comment by Draise14** [comment]
I did reproduce. I'll try on another computer to double confirm.

**Comment by ReinerBforartists** [comment]
Really odd. I don't get the crash, i don't get the error ... Ah bugs ^^

**Comment by Draise14** [comment]
Ok, reinstalled... now I can't reproduce.

**Comment by ReinerBforartists** [comment]
Isn't development mean sometimes ^^

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/173867723-88e234a5-55a6-4d65-8e4b-ce4e3875fce3.png)

```Traceback (most recent call last):
  File "J:\bforartists-repository\bfa_build_windows_Lite_x64_vc16_Release\bin\3.3\scripts\startup\bl_app_templates_system\2D_Animation\__init__.py", line 44, in load_handler
    update_factory_startup_screens()
  File "J:\bforartists-repository\bfa_build_windows_Lite_x64_vc16_Release\bin\3.3\scripts\startup\bl_app_templates_system\2D_Animation\__init__.py", line 16, in update_factory_startup_screens
    space.context = 'TOOL'
TypeError: bpy_struct: item.attr = val: enum "TOOL" not found in ('RENDER', 'OUTPUT', 'VIEW_LAYER', 'SCENE', 'WORLD', 'COLLECTION', 'OBJECT', 'MODIFIER', 'SHADERFX', 'PHYSICS', 'CONSTRAINT', 'DATA', 'MATERIAL', 'TEXTURE')```

Ok, tested again on the other machine, clean compile. Looks like the 2D Animation template may start in the wrong context?

**Comment by ReinerBforartists** [comment]
I#m still curious about this enum. Isn't the tools area the one where the toolshelf is?

bl_region_type = 'TOOLS'

**Comment by Draise14** [comment]
The context it's looking for is in the Properties area
