### ISSUE TITLE
GPU is blocking Cycles material in secondary viewport shading

### ISSUE THREAD

**Issue by Gooorylin1** [Bforartists/Bforartists#3055]
**GPU is blocking Cycles material in secondary viewport shading**
A clear and concise description of what the bug is, and how to reproduce it.

**AMD Ryzen 7 3700X,Geforce GTX 1070 8GB,Asus Gaming Tuf B450**
 

****
![Blender 3 2 0 RC - is hanging,when saving project in secondary material preview viewport (2022) bug](https://user-images.githubusercontent.com/107366077/173247634-17c98120-6dc2-4230-98e1-5020f1aecd12.jpg)

**Comment by Gooorylin1** [comment]
GPU is blocking Cycles material in secondary viewport shading
A clear and concise description of what the bug is, and how to reproduce it.

AMD Ryzen 7 3700X,Geforce GTX 1070 8GB,Asus Gaming Tuf B450
Blender developers fixed that issue.I used: a reflection Cycles material from Blendermada.com - a cycles material,which now does not block GPU.

**Comment by ReinerBforartists** [comment]
Hey Gooorylin1,

Thanks for the report. When it is already fixed in Blender then it will arrive in Bforartists soon too. We are usually one week behind with that though. And last week was a new release, which slows things down. So please be patient. It will come :)

Kind regards
Reiner

**Comment by ReinerBforartists** [comment]
The bug should be history with the newest developer build. Please check.

**Comment by Draise14** [comment]
@Gooorylin1 we have merged in the latest fixes from Blender. Can you try the latest developer build and give it a go? We currently don't have access to AMD cards to test, so we'll need you to give it a quick check.

**Comment by Gooorylin1** [comment]
thank you!that bug - which i have reported to you,has already been fixed.Thank you again Rayner and the developers!


Sent from Yahoo Mail for iPhone


On Monday, June 20, 2022, 5:05 pm, Draise ***@***.***> wrote:




@Gooorylin1 we have merged in the latest fixes from Blender. Can you try the latest developer build and give it a go? We currently don't have access to AMD cards to test, so we'll need you to give it a quick check.

**Comment by Draise14** [comment]
Thank you, will close now.
