### ISSUE TITLE
3D View - Curve - Show/Hide menu has name inconsistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3056]
![image](https://user-images.githubusercontent.com/35357409/173415406-01085cc4-022f-483c-9d2c-f4cd000b35ff.png)

`space_view3d.py` has a menu class I think? That is inconsistent with Blenders nomeclature. This should be the one and the same. 

Bforartists
`VIEW3D_MT_edit_curve_show_hide
`
Blender
`VIEW3D_MT_edit_curve_showhide`

Addon that errors that discovered this from a user in Discord:
https://bookyakuno.gumroad.com/l/hide_only_vertex

**Comment by ReinerBforartists** [comment]
Nope, no conflicts. Then i guess Blender has updated the names at one point and we didn't notice. Should be an easy fix though :)

**Comment by ReinerBforartists** [comment]
All is well. It was really just in space_view3d.py

Closing again.
