### ISSUE TITLE
Outliner - Show Hierarchy only shows one level instead of all in hierarchy 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3058]
Expected Behaviour; (Bforaritsts 3.1.3)
![bforartists_W4qDpUvQ7q](https://user-images.githubusercontent.com/35357409/173721710-c40a9413-8de4-48aa-a9cc-592d573303ff.gif)

Current Bahaviour: (Bforartists 3.2.0)
![bforartists_wuCWTLYYGZ](https://user-images.githubusercontent.com/35357409/173721934-8fa82302-6329-4033-b3e6-66da606a25df.gif)

Tested the Blender hotkeys and the Bforartists hotkeys, both don't work. So I think it's something else. Maybe the operator has some changes from the merge or something broke. 

Version: **Bforartists 3.2.0**

Works in **Blender 3.2**
![blender_6zpu6u45T6](https://user-images.githubusercontent.com/35357409/173722270-9c5b6200-fbdd-4a40-9312-39af1ae12d2d.gif)

**Comment by ReinerBforartists** [comment]
Indeed, Blender behaves different here. The operator is the same. So it must be something under the hood, in the show_hierarchy operator itself.

**Comment by Draise14** [comment]
Let's call in the big guns.

**Comment by ReinerBforartists** [comment]
It behaves different. So there must be a difference somewhere. I have just no idea where.

**Comment by Draise14** [comment]
Downloading todays master from Blender to test, building too, see which finishes first then will confirm. If it's in Blender, we gotta report it. Atleast I have some gifs already of expected behaviour..

**Comment by Draise14** [comment]
![blender_nM6UbvA5sR](https://user-images.githubusercontent.com/35357409/173879242-fff850b6-a75a-4435-aa72-1e9722a79367.gif)

Can confirm, today Blender Master has the same bug.

**Comment by Draise14** [comment]
Reported here:
https://developer.blender.org/T98909

**Comment by Draise14** [comment]
Blender Fixed it, nicely done! It was ultimately in the tree iterator. Apparently they made an update there. 

https://developer.blender.org/rB43ddfdb1a530b5424fa150bb38f8dfe311acd25e
