### ISSUE TITLE
Update align_view_buttons addon to be compatible with Blender 2.8.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#306]
Blender devs decided to make the old addons disfunctional. This means that we need to upgrade all of our own addons to Blender 2.8 so that we can later use it in Bforartists 2.

Update align_view_buttons addon to be compatible with Blender 2.8.

Not sure with this one, since switching to views is now part of the Blender UI too. But at least to change the camera should be added as a functionality somewhere.

**Comment by Draise14** [comment]
Maybe changing the view gimbal widget to the house instead of an axis gimbal? Son they work together?

But yes, weird changing to camera view is not in the view widgets.

**Comment by ReinerBforartists** [comment]
Let's tackle this one after the 2.8 merge. The addon itself is more or less obsolete. It's basically just about the set active camera button.

Postponing.

**Comment by ReinerBforartists** [comment]
Ah, what the heck, it's a good test to find out how the header is now divided ...

**Comment by ReinerBforartists** [comment]
Can't do that. The icons are missing in Blender 2.8.

Postponing again ^^

**Comment by ReinerBforartists** [comment]
This addon is obsolete now in BFA2. Closing.
