### ISSUE TITLE
Texture bake, exclude metallic

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3060]
I had a too dark bake result and made a bug report for it. Since this texture bake is plain useless. Which is the definition of broken and a bug. The bug report was closed as expected behaviour, not a bug.

Maybe we find a way to exclude the metallic slot from baking when baking a diffuse. A diffuse bake should just bake the diffuse information, and not the metallic information too.

https://developer.blender.org/T98880
https://developer.blender.org/T95973

![preview-baketoodark](https://user-images.githubusercontent.com/13919702/174333822-dc87d044-2da5-43cd-a5a5-014d309f532d.jpg)

**Comment by Draise14** [comment]
> This happens due to the bake settings you have chosen. When picking your bake settings for diffuse, you get three options. Direct, Indirect, and Colour.
> Each of these passes are combined together like this: Final output = (Direct + Indirect) x Colour
> When a material has it's metallic slider set below 1, then the Direct and Indirect passes will always be the same. What changes when you change the metallic slider value is the Colour output. When the Metallic slider is set to 0.99, then the Colour output will be really dim, and thus as a result also make the diffuse bake really dim (making it roughly 1% the brightness of the material as most of the light the material is reflecting is in the specular part). When the Metallic slider is set to 0.0, then the Colour output will be really bright.
> In your .blend file, you have the Colour pass disabled. And as such you don't observe this aspect.
> 
> Based on this logic, it could be argued that when a Metallic slider is set to 1.0, then the Direct and Indirect passes should continue to render the same way as they did when below 1.0. But the Colour pass should be set to 0. But as far as I can tell this isn't done because there is literally no diffuse component in the material for Cycles to work with when rendering the Direct and Indirect passes as the material is entirely specular in nature. And thus as an optimization(?) a fake diffuse component of a fully specular material isn't rendered by Cycles and thus the material appears black in diffuse bake passes.

Looks like this is intended behaviour of PBR baking workflows, similar to how all software work. As the task mentioned, this is not an intuitive workflow.

**Comment by ReinerBforartists** [comment]
We should find the place where the metallic gets calculated into the bake. This would make it more intuitive already.

A addon might be nice too. But an addon should not be used to fix a bug like this one.

**Comment by Draise14** [comment]
It might cause issues with interoperability with other engines like UE, Unity, or other DCC's that work to the standard PBR baking. Metal has no diffuse if at all, and if it's a dielectric material, color is baked to gloss if metallic and some onto diffuse - but not everything. This is for energy preservation of the PBR render engine systems.  

> 100% Metallic surfaces will show shadows when baked. They just don't include shadows in the diffuse bake as the material is entirely specular in nature. And thus only shows up in the Glossy bake.
> metals are entirely specular in nature and non-metals (in this context) are diffuse in nature.


> Metal is actually pretty easy to do with PBR. Since metals generally reflect almost 100% of light that hits them, you simply need to make your specular color the final color of reflections you'd like to see. For example, you'd want a light pinkish color for clean copper, or a bright desaturated yellow for most types of gold.
> 
> If you're using metalness maps instead of specular, just put those light colors into your albedo map and then set them to 100% metal.
> 
> Just like with other surfaces, a lot of good information about the surface texture is going to come from your gloss map. Things like scratches are generally rough, and other areas should generally be more glossy.
> 
> There are some good examples of different metals in the preset materials that come with Marmoset Toolbag 2, as well as some good example content out there for Unity if you give it a quick Google.
> 
> Additionally, here are some resources that should be helpful for metals as well as any other type of PBR-type shading:
> 
> 
> Feeding a physically based shading model
> https://seblagarde.wordpress.com/2011/08/17/feeding-a-physical-based-lighting-mode/
> 
> DONTNOD Physically based rendering chart for Unreal Engine 4
> https://seblagarde.wordpress.com/2014/04/14/dontnod-physically-based-rendering-chart-for-unreal-engine-4/
> 
> DONTNOD specular and glossiness chart
> https://seblagarde.wordpress.com/2012/04/30/dontnod-specular-and-glossiness-chart/
> 
> Basic Theory of Physically-Based Rendering
> http://www.marmoset.co/toolbag/learn/pbr-theory
> 
> Tutorial: Physically Based Rendering, And You Can Too!
> http://www.marmoset.co/toolbag/learn/pbr-practice
> 
> Tutorial: PBR Texture Conversion
> http://www.marmoset.co/toolbag/learn/pbr-conversion#spectometal
> 
> PHYSICALLY BASED SHADING IN UNITY 5: A PRIMER
> http://blogs.unity3d.com/2014/10/29/physically-based-shading-in-unity-5-a-primer/
> 
> WORKING WITH PHYSICALLY-BASED SHADING: A PRACTICAL APPROACH
> http://blogs.unity3d.com/2015/02/18/working-with-physically-based-shading-a-practical-approach/
Source: https://polycount.com/discussion/155212/tips-and-techniques-for-pbr-metal

If we were to create a diffuse only without considering metallic energy preservation, then it would have to be an additional model/mode but still preserve the old model for baking diffuse for metallic materials for PBR compatibility. Baking diffuse with metallic would only make sense for NPR rendering.

**Comment by Draise14** [comment]
In this case though, for yours.. you could bake only diffuse by using a Diffuse BSDF or Emit, as you did in the end - but the PBR with 1.0 metallic will affect the way the albedo will and should bake it's enegery if you want the textures to work in a PBR engine.

**Comment by ReinerBforartists** [comment]
Then let's close the issue. I have my workarund. Thanks for it again :)
