### ISSUE TITLE
Geometry Nodes - New Scale and Rotate Instances nodes needs iconography and be added to toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3061]
![bforartists_Oq3rqVC03K](https://user-images.githubusercontent.com/35357409/174345600-a57eedbd-1a0b-44aa-957b-bd4be98aee73.png)

New nodes means they need iconography, added to the toolshelf then documented. 

Todays nodes:
- Instance Rotation
- Instance Scale

**Comment by ReinerBforartists** [comment]
Tooltip is also missing
![missingtooltip](https://user-images.githubusercontent.com/13919702/174427347-ae8ea14a-2ca5-4a89-9ccf-f45ce036cb0c.jpg)
