### ISSUE TITLE
Outliner - Outliner ID Data Operation Context Menu missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3063]
![image](https://user-images.githubusercontent.com/35357409/174388705-76e831fa-6464-422b-9164-3ccd1f90b19e.png)

Right click on a object data (mesh data, material data, etc), we have a few operators without icons. 

Probably should add them back, I recall they must have existed before.

**Comment by ReinerBforartists** [comment]
Let's test the create a branch feature here :)

I am tired to create this locally by hand all the time. And this links the issue to the pull request then when everything works well. Which would save us time. Create branch, fetch, switch, fix, push ...

![createbranch](https://user-images.githubusercontent.com/13919702/174426029-d3979d5f-b809-4a60-8407-a4b10f301e9f.jpg)

**Comment by ReinerBforartists** [comment]
Sexy. This comes even with the bash commands to copy n paste then. But checkout does not switch to the branch it seems. Still by hand ...

![sexy](https://user-images.githubusercontent.com/13919702/174426089-73e8dc5c-3f39-4c6a-9f79-25ab461038fd.jpg)
.

**Comment by ReinerBforartists** [comment]
Something is broken here. I cannot see the branch locally here.

**Comment by ReinerBforartists** [comment]
![fixed](https://user-images.githubusercontent.com/13919702/174426335-d4a6a018-d057-4dc2-a5ee-87ce4a321f8f.jpg)

**Comment by ReinerBforartists** [comment]
Hm, at which point do i create the pull request? So once more, do it here at github ...
