### ISSUE TITLE
Template - Sculpt - Crashes on new load

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3066]
![image](https://user-images.githubusercontent.com/35357409/174424069-42da95e3-316a-4dcc-964f-8364dd1d7db5.png)

![image](https://user-images.githubusercontent.com/35357409/174424075-abca8a6e-62ef-4bc6-a36a-b317446e9ea3.png)

When creating a Sculpting template from new template, it crashes Bforartists. Had a look at the theme factory settings, rebuilt the setup - and still crash. 

![image](https://user-images.githubusercontent.com/35357409/174424341-f9f66c17-347e-415f-b9ba-cc018a46c70c.png)

Then I found the python in that theme does some subdivision and application to a sphere, and it crashes it. Without this file (or commented out lines) it won't crash. 

This is reported by @floorheight

# Solution:
I think this subdivision pre-prep is a little unnecessary, so we could comment it out for Bforaritsts and store the template geometry already subdivided and applied on the sculpt cubic sphere.

I think because we already have a sphere that is subdivided and applied saved in our  startup, the SDS to 6 levels just.. crashes it. 

![image](https://user-images.githubusercontent.com/35357409/174424437-025b514b-9c23-40c7-a087-122c23df3b34.png)

**Comment by ReinerBforartists** [comment]
Coo find. And yet another bug that simply doesn't happen here :D

**Comment by ReinerBforartists** [comment]
Okay, i was wrong. Now it does.

**Comment by ReinerBforartists** [comment]
The code is the same than in Blender. So the cause must be something else.

**Comment by ReinerBforartists** [comment]
Gotcha. The default cube is missing in our template. And so it crashes at the try to subdivide what does not exist.

![cubeismissing](https://user-images.githubusercontent.com/13919702/174425234-e44591f5-6ffc-4d63-bb49-612944672472.jpg)

**Comment by ReinerBforartists** [comment]
3.1.3 did work. I grabbed the startup.blend from there, and it still crashes. Something under the hood has changed. I fear we need to go through the logs here. To change the init_.py is not the solution.

This is something bigger, so i will put this on halt until the next developer build is done. This is something to continue next week.

**Comment by ReinerBforartists** [comment]
I am currently at uploading the developer builds to the cloud so that we can see at which point our template has quit working. Makes the search easier. We have a folder called developerbuilds now there.

Not sure if it is a good idea to link the newest developer builds always from the cloud though. Currently it is one click and the download starts. With linking to the cloud it would be two clicks. So i will try to keep the old dev builds in the cloud, and keep just the current version in the server folder for the direct link.

**Comment by ReinerBforartists** [comment]
Mh, the missing cube in the single template might be its own issue. But we can try to fix it with this thread here too.

**Comment by iyadahmed** [comment]
I think the problem is thr cubr

**Comment by iyadahmed** [comment]
The script tried to subdivide the active object, which is the default cube, if it is missing, the script fails

**Comment by ReinerBforartists** [comment]
As a note, I seem to remember that we have removed the cube from the single templates by design. Same problem as with the default cube in Blender, it was always in the way. But will check again.

**Comment by ReinerBforartists** [comment]
The blank single template is indeed by design. We had it thrown out in Bforartists 2.x somewhere. The quad sphere remained existent in the sculpting template though.

Let's have a look at the devbuilds at which point the crash appears.

**Comment by ReinerBforartists** [comment]
Devbuild from 08.05.2022 works.
Devbuild from 14.05.2022 crashes.

**Comment by ReinerBforartists** [comment]
A debug build tells me something about trouble with the modifier type. Did we have changes in the sds modifier?

![modifiertype](https://user-images.githubusercontent.com/13919702/174545692-f8151b2f-7d73-4bc3-9cfa-5c8dfe2f3702.jpg)

**Comment by ReinerBforartists** [comment]
> Devbuild from 08.05.2022 works. Devbuild from 14.05.2022 crashes.

Means the week from 01.05 upwards , since we are always one week behind ...

**Comment by ReinerBforartists** [comment]
startup blends hasn't changed in blender since eons, means there must be a code part somewhere that leads to this crash.

**Comment by ReinerBforartists** [comment]
Nothing obvious to find in the logs. Time for the big fly swatter it seems

**Comment by ReinerBforartists** [comment]
Spotted some merge regressions in object_relations.c . Let's fix it, and see if this fixes the crash. If not, let's make it a task.
![missingmenucontent](https://user-images.githubusercontent.com/13919702/174568212-a6ce498d-f743-4355-9222-c74e3587dacf.jpg)

![missing](https://user-images.githubusercontent.com/13919702/174568233-0d0e545c-788c-4ff2-84b7-4ec82fbc32b1.jpg)

**Comment by ReinerBforartists** [comment]
Nope, still crashes

**Comment by ReinerBforartists** [comment]
The def load_handler differs from Blender. Changing it to the Blender method did not remove the crash though ...

![defloadhandler](https://user-images.githubusercontent.com/13919702/174642939-bc670f13-89e8-4923-b216-aefaba4de94d.jpg)

**Comment by Draise14** [comment]
Found it. 

![image](https://user-images.githubusercontent.com/35357409/174643404-dd4edfaa-f300-4ab6-b43f-9dcbe75a0892.png)

Our default factory scene doesn't have the correct modifier on the cube (SDS modifier) - so when it tries to apply it from factory, it crashes. Script by itself (the py init) crashes without the modifier. Scene saved WITH the modifier then compiled doesn't crash anymore.

**Comment by ReinerBforartists** [comment]
Do you want to fix it? Please fix also the little difference in the init_.py then ...
