### ISSUE TITLE
3D View - Object mode - new parent menu item just available by hotkey menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3071]
We have  a new parent menu item. It just shows with calling the parent menu with hotkey ctrl p. The new menu item should also be available in the regular menu

Related Merge regression in object_relations.c #3070

![parent1](https://user-images.githubusercontent.com/13919702/174575973-ea8e196c-ae84-4134-acb2-3024ae4a827a.jpg)

![parent2](https://user-images.githubusercontent.com/13919702/174575992-0c5f6f3a-22ce-4168-acc8-280d77dc1929.jpg)

**Comment by iyadahmed** [comment]
For what is worth, this didn't show up as a merge conflict

**Comment by ReinerBforartists** [comment]
Yeah, merges are fun sometimes :)

**Comment by ReinerBforartists** [comment]
Now how shall we name it? Make Parent without inverse is already pretty long ...

**Comment by ReinerBforartists** [comment]
Okay, something is starting to get odd here. Where is the operator gone?

And by the way, we have three parent types in the right click menu. with and without keep transform. And the third is no inverse.

Sometimes, but just sometimes ... ^^

**Comment by ReinerBforartists** [comment]
Something is definitely very odd. Blender has a last operator, Bforartists does not show it. I will now dive into the code and have a look what is going on here. Separating this into its own task. 

![mergeregession](https://user-images.githubusercontent.com/13919702/174966143-f5bb1acf-e1b3-4645-9116-b6b240b3589d.jpg)

**Comment by ReinerBforartists** [comment]
Ahahah, i had an old version compiled. And here the new stuff was missing. 

So on with adding the two missing operators to the main menu ...

**Comment by ReinerBforartists** [comment]
After investigating further, this all makes simply no sense. And i am everything but keen to change anything here.

What the Blender developers did was to move the already in the object menu existing layout.operator("object.parent_no_inverse_set", icon="PARENT") to the one that is called with the hotkey. 

The two operators in the Set Parent To menu is one double, since the Object menu item is already Set Parent to Object with Keep Transform on.

And then it is crazy to pollute our object menu with this double functionality. The only thing that needs an update now is the Set Parent To menu that is called with ctrl P. I don't even know if we have these menus documented somewhere. I'll have a look ...

![identical](https://user-images.githubusercontent.com/13919702/174975971-2004162f-d1d4-4c22-98b3-61ebdf1459cd.jpg)

**Comment by ReinerBforartists** [comment]
Nope, we don't have this menus documented.

I will nevertheless close this issue as won't fix.
