### ISSUE TITLE
3D View - View - Align View to Active - broken menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3074]
![bforartists_cGSu2lUEMq](https://user-images.githubusercontent.com/35357409/174623148-24233f6c-8aec-4b01-9cd5-5bad27f23633.png)
![powershell_5mp855xLJj](https://user-images.githubusercontent.com/35357409/174623153-21d83926-17b1-4586-bfbf-64581070f3d7.png)

Align View to Active menu has an error that makes it missing. I noticed this snuck through in the official 3.2.0 release, and now is in master. Will have to find out what's up with this `NameError: name 'i18n_text_ctxt' is not defined`, and make it work.

**Comment by Blenux** [comment]
Line 1482 needs,

`i18n_text_ctxt = bpy.app.translations.contexts_C_to_py['BLT_I18NCONTEXT_EDITOR_VIEW3D']`

![Screenshot_20220621_015009](https://user-images.githubusercontent.com/25260650/174639135-a39ed705-a8ab-4af9-ba97-578435abf853.png)

**Comment by ReinerBforartists** [comment]
![fixed](https://user-images.githubusercontent.com/13919702/174961971-6cac41f9-1ce6-432d-8d9e-5107958a6e5e.jpg)
