### ISSUE TITLE
Edit mode - point size

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3079]
We have a higher point size than Blender in edit mode. This makes the geometry hard to see with more dense meshes. Maybe we should adopt to the Blender point size here.

![pointsize](https://user-images.githubusercontent.com/13919702/174995581-9521ba42-ab54-4157-8249-c1b49bc36231.jpg)

**Comment by Draise14** [comment]
I guess Blender can handle more topology now so this would be ok. BUUUUT I like thick things that are easier to grab, specially on higher DPI monitors, but that could be a user preference. We still don't have any pre-highlight so grabbing exactly what you want still is not obvious. 

I vote to drop it to 4px or so. 
![image](https://user-images.githubusercontent.com/35357409/175438435-7a9d2dd7-fb83-464d-a578-af7827f3ea9f.png)

It's not often you will be pushing verticies in edit mode like this, only if sculpting and in this case, you wouldn't be needing to see the verts. But indeed 6px is huge.

**Comment by Draise14** [comment]
Just to clarify, this is a theme setting change, so the XML and then regenerate the C would be needed right?

**Comment by ReinerBforartists** [comment]
Yes

**Comment by Draise14** [comment]
Let's drop it to 4px, still ok. No worries!

**Comment by ReinerBforartists** [comment]
Where is mah bfa comment with advice gone O_O

![advicegone](https://user-images.githubusercontent.com/13919702/175915814-53c5847c-4101-491c-999a-57443fc6cf41.jpg)
