### ISSUE TITLE
Fix panel header is cutoff

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3082]
This is a small visual issue because we brought the tabs and tool panels' headers back
not sure we can begin to fix this, but here's the relevant PR https://github.com/Bforartists/Bforartists/pull/2393
![image](https://user-images.githubusercontent.com/25552173/175404930-7ba47299-ae9f-4d27-bb35-2b2b83d984b6.png)

note that both sides should be rounded like the "UI" panels
![image](https://user-images.githubusercontent.com/25552173/175404808-10e42965-e385-4ecd-b7a5-2103daf8f0ae.png)

**Comment by Blenux** [comment]
I've been having a look at this for the past week or so (after reading various commits on it), and I can get it rounded but the blender tool icons end up like this,

![Screenshot 2022-06-24 152333](https://user-images.githubusercontent.com/25260650/175467962-e27dd9a8-f6a9-4bce-abde-df6d57c915ec.png)

This makes it rounded, but icons always end up cut, was also trying it on the laptop last night too.

![Screenshot 2022-06-24 152247](https://user-images.githubusercontent.com/25260650/175468092-4d90ed17-0061-463d-bc23-a9cd010b80cb.png)

**Comment by ReinerBforartists** [comment]
This was the workaround to get the icons displayed in the correct size at all. The price is the cut off header.

**Comment by iyadahmed** [comment]
> This was the workaround to get the icons displayed in the correct size at all. The price is the cut off header.

yes, I hope we can fix both at same time in the future

**Comment by Blenux** [comment]
So close, but not without some issues.

https://user-images.githubusercontent.com/25260650/175577647-b9c182c9-e9d3-4c98-aa8f-2fb58b77fe42.mp4

**Comment by iyadahmed** [comment]
> So close, but not without some issues.
> 2022-06-25.02-26-46.mp4
> 
> Issues:
> 
> 1: Still can snap past the single column, which makes the icons appear above the button.
> 
> ![Screenshot_20220625_023834](https://user-images.githubusercontent.com/25260650/175595887-a4791b29-594c-47b5-ac0a-9ec19795dd73.png)
> 
> 2: Turning of tabs makes snapping completely different, makes me believe tabs is causing the issue somewhere.
> 
> ![Screenshot_20220625_023923](https://user-images.githubusercontent.com/25260650/175600234-3d6ae228-d27a-46a6-b6f2-e0ae1bdf2099.png)
> 
> 3: I completely have no idea how this all works, just putting numbers and words somewhere that might make sense.
> 
> Where I change stuff,
> 
> **area_utils.c** ![Screenshot_20220625_024331](https://user-images.githubusercontent.com/25260650/175603850-e6384485-0b0d-4d5c-b7a1-d06e4fa21532.png)
> 
> **space_toolsystem_common.py (and space_toolsystem_common_tabs.py)** ![Screenshot_20220625_024400](https://user-images.githubusercontent.com/25260650/175604444-972eef84-de06-435e-a84c-77b152ef0741.png)
> 
> Plus the area.c stated above.

awesome work!, we are getting closer

**Comment by Blenux** [comment]
https://user-images.githubusercontent.com/25260650/175773298-8aa00ca8-a99b-4ecc-80c5-e5d0b9011226.mp4

**Comment by Draise14** [comment]
Much closer! But yeah, with tabs off it would be a different game..

**Comment by iyadahmed** [comment]
Maybe a simple check to use the new values if tabs are on, and old values if tabs are off
can you push to a branch so we can work on this together?

**Comment by Blenux** [comment]
Yeah can do, only thing I'm having trouble with is when Tabs are off now.

**Comment by Draise14** [comment]
@Blenux would you like to be assigned this task to commit to for later? Looks like you're a hairs width away from figuring it out.

**Comment by Blenux** [comment]
I've been trying to have another go, and can't for the life of me work it out, think my numbers are off also, so may be best to start from scratch with someone more knowledge then more ( Health issues being annoying also after having covid, insomnia on top).

**Comment by iyadahmed** [comment]
Get better soon :pray:

**Comment by Blenux** [comment]
Think I may have it this time, still have to figure out the misaligned with tabs are toggle off and on, but think that could be a fix another day.

https://user-images.githubusercontent.com/25260650/189485078-9f79bef3-fae2-4238-a00c-11f6158b4179.mp4
