### ISSUE TITLE
Set icon for UV new select similar operator

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3086]
Adding merge conflict tasks as I merge

file
`release/scripts/startup/bl_ui/space_image.py`
![image](https://user-images.githubusercontent.com/25552173/175977569-f74b7c54-14a0-4c9d-879a-e455886e8578.png)

**Comment by Draise14** [comment]
Oops, copied this one

https://github.com/Bforartists/Bforartists/issues/3088 #3088
