### ISSUE TITLE
FCurve Editor - Slide Operators - Blend to Default Value needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3089]
![image](https://user-images.githubusercontent.com/35357409/176233825-7c5f575d-0b36-4e56-afce-671723ec911b.png)

Needs iconography and documentation.

**Comment by ReinerBforartists** [comment]
Fixed

![blendto](https://user-images.githubusercontent.com/13919702/177487730-f3d95fa9-45e6-45f1-961f-3015939a7924.png)
