### ISSUE TITLE
3D View - BFA Brush Panels Add-on - Sculpt Paint Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3092]
![bforartists_2H5nXZFkl3](https://user-images.githubusercontent.com/35357409/176235963-771c585f-faf6-4dae-bd53-53ffc953b6f3.gif)

Add the Sculpt Mode brushes to the addon

NOTE: There are groups of brushes for texture painting and sculpting. I recommend we make a tab for sculpt brushes and then texture brushes to keep it split into two tabs. 

If there are too many panels in one tab, we can split the tabs into groups of brushes (group by brush type, like the yellow, the blue, the red, etc).

**Comment by Draise14** [comment]
New release, too close to date so will will pause for next release.

**Comment by Draise14** [comment]
I have a feeling this will be a mammoth one.

**Comment by iyadahmed** [comment]
> ![image](https://user-images.githubusercontent.com/35357409/178310198-b428fe24-13b1-42e4-bfde-ac8c4ce8b36d.png)
> 
> Hey there @iyadahmed ! Been thinking about the UX of this one. I think there are probably too many brushes to have them all in the same tab - so I was wondering, it is doable to have some brush panels/tab groups in the sculpt mode? Instead of the one tab?

Multiple tabs, yeah doable, I have to make some edits first

**Comment by iyadahmed** [comment]
> I have a feeling this will be a mammoth one.

No worries we will figure it out

**Comment by ReinerBforartists** [comment]
The last time that i tried to change anything here i ended in big gaps. And there are the experimental features too. But we will see :)

**Comment by Draise14** [comment]
Ah oops, not yet. You're on the grease pencil mode now.

**Comment by Draise14** [comment]
Sponsored this to be done sooner than later - who knows when the brush system will change, so may as well make the use of what already exists.
