### ISSUE TITLE
3D View - BFA Brush Panels Add-on - Texture Paint Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3093]
![bforartists_2H5nXZFkl3](https://user-images.githubusercontent.com/35357409/176235963-771c585f-faf6-4dae-bd53-53ffc953b6f3.gif)

Add the texture paint mode to the brush panel addon. This should allow custom bushes on a top level in the texture paint mode.

**Comment by Draise14** [comment]
Oh wow! The system is quicker to implement than expected! Nice! Can't wait to try this one out.

**Comment by iyadahmed** [comment]
Indeed, it still could be better/easier/faster

But not too bad currently 

On another note, the big icons have the middle alignment issue, I can't control this from Python I guess not sure why it happens, this is an issue with the original Blender C code I guess

**Comment by Draise14** [comment]
I guess we will have to use the 16px icons exclusively.
