### ISSUE TITLE
Asset Browser - Create initial Default library to ship

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3094]
![bforartists_jd86wJIjCg](https://user-images.githubusercontent.com/35357409/176245903-75e1b5b7-441b-4db4-9cff-e289b114e58a.png)
![bforartists_fgDcskEIgs](https://user-images.githubusercontent.com/35357409/176246308-dcad9dcf-fef1-4e0c-b384-16c7e8b11d5d.png)

To ship a default library, we need one first. 

## Goals:
- Convert the VX Material Library to assets
- Convert the Light library to assets
- Prepare the blend to ship in the repository so it can compile and then on first load, register as a default. 

### Requirements:
- Everything must be procedural (little geo, few textures)
- Everything must be compatible exclusively for the official build (currently collections, objects, poses, node groups, materials, worlds)
- Everything must be relatively performant 
- Thumbnails should be well rendered, thought out, and designed.  

**Relevant Task:**
Loading a default asset library #2832

**Comment by ReinerBforartists** [comment]
The materials needs a closer look. It seems that we have currently a few materials that doesn't longer proper work. I cannot edit this material here for example ...

![copper](https://user-images.githubusercontent.com/13919702/176628030-1a510dfd-89c1-49cd-9fae-509761fdbf04.jpg)

**Comment by Draise14** [comment]
Yeah, they are severely outdated, and could be improved, labeled and framed correctly. I'll start getting to that maybe next week. 

Here is a repository of the materials also:
https://github.com/don1138/blender-materials

**Comment by ReinerBforartists** [comment]
Beware of copyrights when this materials includes textures.

**Comment by Draise14** [comment]
My goal is to try make it as procedural as possible, yet performant. No textures for file size and also user flexibility.

**Comment by Draise14** [comment]
I think it's too close to release to get this done on time WITH the addon that would register the library, so will postpone this one.

**Comment by Draise14** [comment]
![bforartists_bYJqQ8ZFvU](https://user-images.githubusercontent.com/35357409/180359466-f3961b85-09b3-44b8-b85d-66787a0b9f0f.png)
![bforartists_5EqZG9WfeM](https://user-images.githubusercontent.com/35357409/180359467-f22e77e6-c612-46c3-8969-6619ac5fbd55.png)

Ok, converted the Light library to assets. I am thinking to store collections with an additional icon for the type of collection asset it is.

**Comment by Draise14** [comment]
Ok, now to work on the VX library to assets

**Comment by Draise14** [comment]
![bforartists_P6D7Lz8fct](https://user-images.githubusercontent.com/35357409/181417085-7d1136e0-e03e-49a7-bb6e-2551c9f125b2.png)

Been trying out another shader ball, since.. the default balls don't tell much about the shader. The reason being.. the blender one has the blender logo. And good thumbnails could sell. So far reception of these are quite good. 

![bforartists_OFwwVo7GWt](https://user-images.githubusercontent.com/35357409/181417315-ac8f8ce7-5bc4-42da-8c58-27386b3e3451.png)
![bforartists_9TPf4x3ab6](https://user-images.githubusercontent.com/35357409/181417316-04d9c59d-c996-4ff7-8a42-1de2cdffd728.png)
![bforartists_JWHSIFbHRR](https://user-images.githubusercontent.com/35357409/181417322-bb90f7c0-1735-40fd-9bb2-2630f8ea6a28.png)
![bforartists_m7SZoaLv83](https://user-images.githubusercontent.com/35357409/181417323-ab82f0c1-892c-4c17-a374-170f4de7aeee.png)

Shader balls look smart, might keep the texel density ground for reflections/scale references. 

![bforartists_3sanwIoXqh](https://user-images.githubusercontent.com/35357409/181417112-ccd43def-0e3c-4e66-bf33-1a6d10fc5e63.png)
![bforartists_2NP9FKvuj0](https://user-images.githubusercontent.com/35357409/181417115-2424c451-3d25-49bd-81dd-cf89449d3f0e.png)

Managed to port all the VX library materials, minus the ones from online. They are all still a huge mess and could be frames and cleaned up a lot.... And also updated. I might do that when I go through with the higher quality thumbnails. 

Here are the categories so far. 
![bforartists_BFcuoYFogu](https://user-images.githubusercontent.com/35357409/181417210-b4b9979a-5653-4faa-bf13-bb1bb213b8cf.png)

I have also started adding in some utility nodes, like edge wear nodes and triplanar and worldspace nodes. 
![bforartists_KeKpQLXYyX](https://user-images.githubusercontent.com/35357409/181417237-6722370b-f284-4532-9710-57fd15f514e4.png)

I think I have enough for a first library, atleast it's everything we ship pretty much. 

**Pending:**
- Clean up the default scene of any junk
- Update the materials to have proper frames and be organized, self explanatory for editing
- Update the material thumbnails to be higher quality where relevant

- Document or frame the VX material templates a bit more
- Double check if the VX library is complete from the repository

Optional:
- Maybe add a cycles/eevee/both icon to materials? 
- Create some of the thumbnail generators for higher quality thumbnails (cube, liquid, cloth, plane). 
- Split the thumbnail generator from the asset libraries
- Split the asset libraries to multiple files? Might load slower, but might be easier to handle. Right now I'm working in scenes. I'll bench mark later.

**Comment by Draise14** [comment]
Ok Done.

**Update:**
- Added VX Library materials
- Added "Rubber" as a new category
- Cleaned up floating node groups to not be listed till we have cleaned up these materials, they are all messy.  
- Added the Matlib lights library
- Added Higher quality metal material thumbnails
- Added Node Groups: some vector nodes (triplanar and world space coordinates), some mask nodes, and a simple PBR node. 

**Current Parent Categories:**
- Collections
- Materials
- Node Groups

![image](https://user-images.githubusercontent.com/35357409/182690193-2ecdb602-5045-4cd8-8f23-0bccdb14e765.png)

Commit of this library was done in the Bforartists Default Asset Library addon
https://github.com/Bforartists/Bforartists/issues/2832
