### ISSUE TITLE
Property Editor - Object- New Light Group button is greyed out (for no reason)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3096]
![blender_WYalFZnSCn](https://user-images.githubusercontent.com/35357409/176565078-7cf63b00-195c-4b6a-b864-d2452f7c7cd4.png)
Looks like in both Blender and Bforaritsts, the Object Shading panel in Cycles mode has a greyed out operator that "adds new light group" to help assign objects to uncreated lightgroups, instead of switching tabs to the View Layers tab. 

Thus functionality could be exposed as maybe intended? 
![bforartists_RvoZgIGNk7](https://user-images.githubusercontent.com/35357409/176565085-37930b4b-e489-449a-8f8e-2e89d0d1e907.png)

@cl3m3c7 has made a fix for this one already, so this is mainly to track it and run a branch for it. 

Relevant code to work:
[`48ad17f` (#3095)](https://github.com/Bforartists/Bforartists/pull/3095/commits/48ad17fc3aff5cba4a3edec9562beba412d6c6c2)

**Comment by Draise14** [comment]
Ok, doing a test build now

I made a branch in this repository. Looks like you did it from your own fork. But all good! You should have write access now to make branches within this repository, so it will be easier for you in the future.

**Comment by cl3m3c7** [comment]
yeah I did the changes to the forked one!
and sorry again for mess 😊

**Comment by Draise14** [comment]
No worries! Reminds me of my first times!
