### ISSUE TITLE
Upgrade some themes

### ISSUE THREAD

**Issue by cl3m3c7** [Bforartists/Bforartists#3098]
**Is your feature request related to a problem? Please describe.**

Make the header of the panels in the outliner more visible for some themes!

![light](https://user-images.githubusercontent.com/61097104/176701828-a8e9bec0-8d17-422f-85f5-e4d1b283fe58.png)
![changes](https://user-images.githubusercontent.com/61097104/176701864-423c43a6-9bed-4b3d-bd3c-85d98b9dfe77.png)

**Comment by Draise14** [comment]
What do the Blender Light, Maya and Minimal Dark/White themes looks like with the improvements?

**Comment by ReinerBforartists** [comment]
Even more important, are these default Blender themes? We should not alter their official themes ...

**Comment by cl3m3c7** [comment]
the first image is the actual theme, and the second is the modified version.
![fff](https://user-images.githubusercontent.com/61097104/176758473-0ce8ae2c-9e1b-47d2-b6af-d945606babf4.png)

**Comment by cl3m3c7** [comment]
@ReinerBforartists  Pablo once said in the today live show that he forgot to update the other themes
like if you compare the black and light you will see the difference

**Comment by ReinerBforartists** [comment]
Yes. I notice the difference now. The culprit here is, the official Blender themes lands in Bforartists automatically. So when Pablo fixes the themes, then we will have it in Bforartists in two weeks. So we would make us unnecessary work here :)

**Comment by cl3m3c7** [comment]
I don't know if he will do!
I have already submitted a patch for like almost two months now, I texted him in blender.chat, I even tagged him in the user-interface channel in blender.chat but no replies!

**Comment by ReinerBforartists** [comment]
I see. But the tasks exists. And it can lead to trouble at our end. Plus it makes us unnecessary extra work. 

Best is when the Blender developers fixes the Blender bugs and quirks where possible.

**Comment by Draise14** [comment]
If you comment `BFA - changed for X reason` to the changed lines, it might make it easier to preserver or review these merge conflicts later too.

**Comment by ReinerBforartists** [comment]
Not in this case. Merge conflicts can just arrive where the files are changing. And the next possible change in these files here is the fix that cl2m3c7 is waiting for :)

**Comment by cl3m3c7** [comment]
while fiddling with the themes, I noticed that bforartists theme also "can" be improved in the **preferences** area.
here is a comparison with the blender dark one to see the difference

![theme](https://user-images.githubusercontent.com/61097104/177049929-5a915e0d-337e-4d47-8b0e-9e21012d92cf.jpg)

so, will I change the bforartists theme too with the rest of these changes, create a seperate issue, or no change at all?

**Comment by ReinerBforartists** [comment]
Just do it here. It is the task to improve the theming already :)

**Comment by ReinerBforartists** [comment]
Fixed in master
