### ISSUE TITLE
Bforartists crashes when using the sculpting template

### ISSUE THREAD

**Issue by cl3m3c7** [Bforartists/Bforartists#3101]
**Describe the bug**
create new project using the Sculpting template

**Desktop (please complete the following information):**
OS: archlinux
Graphics card: NVIDIA GeForce GTX 1050 Ti

**Screenshots, Example Files**
![blender bug](https://user-images.githubusercontent.com/61097104/176787746-bc2b5e66-8984-4dde-b8d4-cd89889e3522.gif)

**Comment by Draise14** [comment]
Still crashing?

**Comment by Draise14** [comment]
Related:
https://github.com/Bforartists/Bforartists/issues/3066

**Comment by Draise14** [comment]
Ok, trying to startup replacement fix again, I don't recall committing that one, but it got closed. Maybe something got missed.

**Comment by cl3m3c7** [comment]
> Still crashing?

yep!

**Comment by Draise14** [comment]
Ok, should work now.
