### ISSUE TITLE
Adding subdiv surface modifier using CTRL+3 (shortcut) in the sculpting template does nothing!

### ISSUE THREAD

**Issue by cl3m3c7** [Bforartists/Bforartists#3103]
![bug](https://user-images.githubusercontent.com/61097104/176800118-fd4f3ad5-1ad5-4a31-bcc9-8e4e1c25e404.gif)

Steps to reproduce:
1. Load Sculpting Template (from master)
2. Press CTRL+2/3/4 to try subdivide selection
3. Notice nothing happens 

Optional:
4. Go to Object mode
5. Select the object
6. Go to sculpt mode
7. Press CTRL+2/3/4 to try subdivide selection
8. Multires subdivision happen (should be normal subdivision)

**Comment by cl3m3c7** [comment]
it still shows the last operator panel but does not add the modifier the the stack!

**Comment by Draise14** [comment]
Weird. That's so bizzare. I can reproduce this to a degree.

**Comment by Draise14** [comment]
I will have to take a look at this tomorrow, maybe it's that pesky startup `init` again that screws it over. I think the multires is intentional, but compared to the rest of the software this is unexpected behaviour and inconsistent UX. But even then, deleting it, making a new cube, and it goes back to normal...

**Comment by cl3m3c7** [comment]
> I think the multires is intentional

yep I think so as well!
Multires for sculpting is more convenient than subdiv for the shortcut in my opinion

**Comment by Draise14** [comment]
I think I got it. Rebuilt the entire template from scratch, will upload - it seems to fix this.

**Comment by Draise14** [comment]
Ok, did a release build with the rebuilt one, and all good now.
