### ISSUE TITLE
Sculpting template - tesselation too low

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3108]
I noticed that you have recreated the sculpting template because of ongoing crashes (sorry for the missing modifier, must have applied it at one point. But still curious how this could happen. I could swear ... ). But the tesselation that you use here now is ways too low for sculpting. And we have a gap at the top again. I use a 1920x1280 monitor to create the templates ...

Blender uses a tesselation of 6

![tesselation](https://user-images.githubusercontent.com/13919702/176990998-945d118a-d321-45db-9cbc-3ab185d20f19.jpg)

![toolow](https://user-images.githubusercontent.com/13919702/176990942-d93d502d-5310-4d8e-825d-06d56f5882d9.jpg)

**Comment by ReinerBforartists** [comment]
Related: Bforartists crashes when using the sculpting template #3101

**Comment by Draise14** [comment]
Oh.. another step to add to the setup template modification list. Use a 1080p HD monitor to make the layout, not anything else. Sorry bout that, totally forgot.

**Comment by ReinerBforartists** [comment]
1200, not 1280, sorry, my fault ^^

Do you even have such a monitor? My other monitor is a 1080 in height. But i love the few extra pixels ...
