### ISSUE TITLE
Mac Build (7/03/22)

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#3110]
https://www.dropbox.com/s/vsvsgwtypx4tfyr/Bforartists-devbuild-03-07-22-Mac.dmg?dl=0

**Comment by ReinerBforartists** [comment]
Thanks for the devbuild. But the size tells me that there might be some files missing. It says 1.46 Mb ^^

**Comment by Draise14** [comment]
Can confirm, looks like it's the wrong one?

**Comment by ReinerBforartists** [comment]
Next version is around the corner anyways. So i would say, close this one, and make the release version instead :)
