### ISSUE TITLE
Iconography: Nereast Face Snap

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3112]
![image](https://user-images.githubusercontent.com/25552173/177193580-6f5cec70-9f6f-4742-b7b7-9c6a51a66c78.png)

file: `source/blender/makesrna/intern/rna_scene.c`
![image](https://user-images.githubusercontent.com/25552173/177194080-3a4c07a1-911e-4aeb-8906-494c5860dfb8.png)

Line 161

**Comment by ReinerBforartists** [comment]
Fixed in master

![facenearest](https://user-images.githubusercontent.com/13919702/177282697-dc7bf72c-6996-4c00-902f-964cf2a746e3.jpg)
