### ISSUE TITLE
Left align grease pencil lineart modifier UI after merge

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3113]
![image](https://user-images.githubusercontent.com/25552173/177194164-721d87ad-9e6a-4f56-a8e2-b98d226bf049.png)

**Comment by ReinerBforartists** [comment]
\o/

**Comment by ReinerBforartists** [comment]
Woah, this is something more complicated. Needs a partially redo since the content and panels has changed. We cannot simply modify the old code parts.

So let's do this in more than one step ...

**Comment by ReinerBforartists** [comment]
Three panels to recreate.

![tofix](https://user-images.githubusercontent.com/13919702/177302970-696a73f1-77dd-49ea-8a11-614b4223219b.jpg)

**Comment by ReinerBforartists** [comment]
Hm. I am a tad bit lost with quite a few of the new code snippets. What is this entry pointer good for? And how to deal with it?

![troublecode](https://user-images.githubusercontent.com/13919702/177311933-9b286e3e-7060-4016-a16b-ebb56f9cfdd0.jpg)

**Comment by ReinerBforartists** [comment]
Light Reference and Geometry processing panel are fixed again. Remains the nasty edge types panel. 

![light reference](https://user-images.githubusercontent.com/13919702/177375516-28c0490d-dbb5-4ff9-bb2d-6b16e58ead31.jpg)

![geometryprocessing](https://user-images.githubusercontent.com/13919702/177375527-c243455d-5a1d-42a8-b0c8-00b40ccc799e.jpg)

**Comment by iyadahmed** [comment]
> Hm. I am a tad bit lost with quite a few of the new code snippets. What is this entry pointer good for? And how to deal with it?
> 
> ![troublecode](https://user-images.githubusercontent.com/13919702/177311933-9b286e3e-7060-4016-a16b-ebb56f9cfdd0.jpg)
> 
> 

Not sure too, it is just a row I think

**Comment by ReinerBforartists** [comment]
Thanks :)

@Iyad, do you want to have a look here at the last panel? As told, i am lost what to do with the *entry pointer.

**Comment by ReinerBforartists** [comment]
This is the kind of stuff that is ruining my nerves ^^

**Comment by iyadahmed** [comment]
Hi sure will look tomorrow

**Comment by Draise14** [comment]
Did you get this little rascal @iyadahmed ?

**Comment by ReinerBforartists** [comment]
Any progress here?

**Comment by iyadahmed** [comment]
Nope

**Comment by ReinerBforartists** [comment]
:'3

**Comment by ReinerBforartists** [comment]
I tried to merge at least what we had already. But Automerge is not longer possible. :/

**Comment by ReinerBforartists** [comment]
Giving it another crack. At least the two other panels ...

**Comment by ReinerBforartists** [comment]
Composition panel
![comp](https://user-images.githubusercontent.com/13919702/184476663-4290f3c8-9cec-4fc4-a436-754ebd0aa79f.jpg)

**Comment by ReinerBforartists** [comment]
Vertex Weight Transfer
![verteweight](https://user-images.githubusercontent.com/13919702/184476997-31eefe48-b0ee-4ef1-8865-e8c7e9a6f3c4.jpg)

**Comment by ReinerBforartists** [comment]
Chaining panel
![chaining](https://user-images.githubusercontent.com/13919702/184477284-5e743614-2c5c-4473-b2c0-b89c6b3ec197.jpg)

**Comment by ReinerBforartists** [comment]
Intersection panel
![intersection](https://user-images.githubusercontent.com/13919702/184478014-a6001853-d3f0-4093-bd27-c004d2a16b63.jpg)

**Comment by ReinerBforartists** [comment]
Occlusion panel

![occlusion](https://user-images.githubusercontent.com/13919702/184478624-7c7a28d8-488d-4675-9806-ad1046bcf2d0.jpg)

**Comment by ReinerBforartists** [comment]
Geometry processing

![geoprocessing](https://user-images.githubusercontent.com/13919702/184478821-ac783028-e17a-4893-83b8-23745ce7084c.jpg)

Remains the trouble panel with the code that we don't understand. Edge Types.

**Comment by ReinerBforartists** [comment]
Hm, we have definitely new content.

![new content](https://user-images.githubusercontent.com/13919702/184501520-86f021ad-1e83-4807-8d5f-b4070c74d56c.jpg)

**Comment by ReinerBforartists** [comment]
Edge Type Options. I can for the life of me not figure out though how to reveal the alternative prop here. Must have something to do with baking. But it does not let me bake anything. So it can still be that this is broken. I cannot test it ...

![options](https://user-images.githubusercontent.com/13919702/184502576-3f6bb2c0-6fe6-431b-a7aa-d25a9ca3e4ef.jpg)

![alternativeprop](https://user-images.githubusercontent.com/13919702/184502581-1368f7cc-b8e3-4da2-a14b-c13960974265.jpg)

**Comment by ReinerBforartists** [comment]
Same here, no idea how to activate Illumination filtering, Light Contour and Cast Shadow.

Started with the four easy props where nothing changed.

![howotoactivate](https://user-images.githubusercontent.com/13919702/184527183-8824448e-d670-42aa-88d8-abbe5a6450fd.jpg)

**Comment by ReinerBforartists** [comment]
The code for the remaining four props makes me knots into my head. @iyadahmed , could you please have a look here? I have gone as far as i could. I fear i am lost with the last remaining changes.

The first two most probably needs a split code. It's two props in a row, each.

And the last two deals with two variables and goes in loops between sub and entry. All i was able to achieve at least to align them left. But i am not able to add a row separator here. I fear to break the code.

![remaining](https://user-images.githubusercontent.com/13919702/184529130-4b72ddbe-51af-4d74-be31-37ce41a0b52c.jpg)

**Comment by ReinerBforartists** [comment]
Ah i did split code before at other modifiers. So here an example in the datatransfer modifier.

![splitcode](https://user-images.githubusercontent.com/13919702/184530839-ca223491-52a0-4363-a8c8-963b7298c60a.jpg)

**Comment by ReinerBforartists** [comment]
Narp. It's again this **entry** trap in the way. And this doesn't let me align my content as i want.

`uiLayout *entry = uiLayoutRow(sub, true);`

What does this do? Is it just the usual obfuscation to make the code a bit more complicated to read? Or something vital?

![entry](https://user-images.githubusercontent.com/13919702/184531699-67e1e85d-177e-4010-9dba-c4a169bfbe5a.jpg)

**Comment by iyadahmed** [comment]
I will look into it asap

**Comment by ReinerBforartists** [comment]
Postponing for after the 3.3.1 release

**Comment by Draise14** [comment]
![bforartists_2e4n6eddKv](https://user-images.githubusercontent.com/35357409/224815205-ce8470d5-97c8-4474-8e13-7280ec7f5b8f.gif)

I think the GP Lineart modifier is all left aligned now?

**Comment by ReinerBforartists** [comment]
Narp. One bit is missing You even scroll across it right at the start. The Create part ...

**Comment by Draise14** [comment]
Ah right, the create has two that should be under the label. Ok. Looks like this is nearly done!

**Comment by ReinerBforartists** [comment]
We never figured out how to convert this bit ^^

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/231616157-ac92c032-5bdf-4f46-bd0f-b9d351e6e4a4.png)

Leaving this here to point out what's left.

**Comment by ReinerBforartists** [comment]
Good luck ^^

**Comment by ReinerBforartists** [comment]
>3

**Comment by ReinerBforartists** [comment]
This issue remains frustrating. So close to fix at least the one line here ...

But how the heck do you show the other set? Where do you turn off or on the cache here?

**Comment by ReinerBforartists** [comment]
How unexpected, our manual is completely outdated for the lineart modifier.

-.-

**Comment by ReinerBforartists** [comment]
Added at least the crease prop left aligned :D

I have no idea how to meet the   **_if (use_cache && !is_first) {_**  condition to show the single prop. So i cannot fix this part. The remaining prop above is surrounded by the strange **_*entry_** pointer, and remains unfixable. What i also not did is to hide the crease threshold slider when crease is off. And the permanent greyed out Illumination Filtering prop at the top remains a mystery. 

The whole code looks unfinished in this area. Documentation is as told non existent. And since this modifier is marked as legacy i will simply stop at this point, close this isssue as known issue and update at least the manual for the bits that works.

![onemoreline](https://github.com/Bforartists/Bforartists/assets/13919702/f608d590-cb36-452e-9f81-0fffbc1214f4)

**Comment by ReinerBforartists** [comment]
Updating the manual ...

**Comment by ReinerBforartists** [comment]
I stand corrected, the manual was up to date. Minus  if (use_cache && !is_first) problem. Which i cannot resolve, and so also not document.

Either way, we went as far as we can go. Closing with a last known issue.
