### ISSUE TITLE
3D View and Outliner - Hotkeys - Add SHIFT+DoubleLMB to select collection hierarchy

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3120]
![firefox_NnPrG3MeM6](https://user-images.githubusercontent.com/35357409/177658820-7d739ce4-94cd-47fd-a3d3-8fae91dc1f8c.gif)
![firefox_WLjviSxXrG](https://user-images.githubusercontent.com/35357409/177658516-eba40cb2-d88b-4955-8b06-f559f22b7425.png)
https://twitter.com/CosmoMidias/status/1544498062907047936?s=20&t=DA7nCe6yQOwtPo73gc_UFw
https://twitter.com/CosmoMidias/status/1544342609535303681?s=20&t=AQSEBcLJm4Ppi6k2nV82wA

When working with collections and many objects, sometimes you want to treat collections like groups of objects, which they are. But then it's hard to select all of them, either you have to do it manually in the 3D View or use the context menu to select them in the outliner. Typically you would use group addons like **[Quick Instances](https://blender-addons.org/quick-instance-addon/)** or others to work around this - or you use a null parent. But you still have to toggle in and out of groups, selecte the parent, and working with collection selecting is still finicky. 

It would be good, specially with larger scenes - have the ability to select collection objects easily to transform them as if they were groups, which they are essentially. 

A user on twitter shared an idea that you can do this with an available hotkey:

**In outliner:**
SHIFT+Double Click LMB 
`outliner.collection_objects_select`

**In 3D View:** 
SHIFT+Double Click LMB
`object.select_grouped`
Option: "Extend" and "Collection"

**Comment by ReinerBforartists** [comment]
Was just about to post this idea here too. It's really annoying sometimes :)

**Comment by ReinerBforartists** [comment]
Mh, hotkey only functionality ... is there a way to add this to the regular menu too somewhere? It could also be worth an entry to the important hotkeys addon ...

**Comment by ReinerBforartists** [comment]
Yes, we moved it to the outliner, since this is the place to deal with collections. But selecting the surrounding collection in the 3d view could fit into the select menu.

**Comment by Draise14** [comment]
Quick question - this is a hotkey entry, but am I supposed to also make a new operator or menu entry for this?

**Comment by Draise14** [comment]
Ok, operator is already in the interface.
![image](https://user-images.githubusercontent.com/35357409/194643100-31eb9294-fc30-4f80-ac48-5475acf4d562.png)

Going to commit the hotkey.

**Comment by Draise14** [comment]
I've tested, the extend option per default is not as useful. So will change the existing two and add `CTRL+SHIFT+DBL` as the extend option.

**Comment by Draise14** [comment]
Pushed to master
