### ISSUE TITLE
3D View - Armature - Edit Mode - Add button for Xray Mode (like the addon)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3121]
![image](https://user-images.githubusercontent.com/35357409/177891106-5243319c-8576-4a6d-9612-cacb90ac28a1.png)

https://toshicg.gumroad.com/l/xray_weight_paint

Xray weight painting in blender is a headache, same with BFA. But there is an addon with a simple solution, something we could implement and it would be easy to maintain. Can we add this button for Xray toggle in weight paint? It would save so much time..... and be a consistent UX. 

## Manual Workflow
If you want to do it manually, you have to set these options as follows:

    Front Faces Only: OFF (Default: On)
    Falloff: Projected (Default: Sphere)
    Front-Face Falloff: OFF (Default: Off)

Now try toggle these over and over - and discover how it works!!! I had no idea you could even DO this. But I would have used it a lot. 

# Method
- Add it as a default operator in the GUI?
- Make a separate addon shipped with Bforaritsts and enable by default?

**Comment by ReinerBforartists** [comment]
Looks like a lightweight addon. And so it would not harm to include it. But same problem as with all other addons. Who maintains it then?

And what is the normal workflow, without this addon? Maybe we can improve things without the addon already. I haven't weightpainted since eons, so this question is serious ^^

**Comment by Draise14** [comment]
To toggle x-ray you have to press the 3 steps above in 3 different panels. 
https://public-files.gumroad.com/1q30t9hxsisbo9ck2bktfusuzbj4

We could add the button by default or include an addon. I think it's a relatively easy to maintain if we don't want to build the operator into the GUI files or make our own addon.

**Comment by ReinerBforartists** [comment]
I see. In this case i would say, include the addon. This is the fewest work. But first ask the developer ...

**Comment by Draise14** [comment]
Sent a message to request. Let's see what he says!

**Comment by Draise14** [comment]
Talked to the two developers on Twitter, they both like the idea and gave the green light. Here is the repository:

https://github.com/BlenderBoi/XRayWeightPaint-

**Comment by ReinerBforartists** [comment]
Then it's as simple as throwing the addon into the release\scripts\addons folder.

I would not activate it by default though. Our UI has grown with too much content already. Turn it on when you need it.

**Comment by Draise14** [comment]
Doing a test build with it, just to make sure.

**Comment by Draise14** [comment]
All good:
![bforartists_vrF9NTAR8R](https://user-images.githubusercontent.com/35357409/184196623-1d1d2ecd-1679-4308-98c7-9ad826fdcdfe.png)
