### ISSUE TITLE
Official Release 3.2.1 - Task Logs

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3122]
This task is to work on the official release and track it as I do it for the first time. Gonna branch this so I don't screw up the master till it's working. When it's all good, I'll merge to master and make the tag. 

![splash](https://user-images.githubusercontent.com/35357409/178022102-c6f17e3f-4567-444f-8330-f8c91964d054.png)
I have made an SVG to make work a little easier, since we have the logo now in SVG and the font exactly as used on the socials. Would be good to have this design consistent with the font. Since this is a point release, I will use the same splash.

**Comment by ReinerBforartists** [comment]
Is there a reason why the 3 is offset? And why an svg? The image is an png anyways :)

**Comment by Draise14** [comment]
I prefer working in Inkscape over Gimp, it also would tie the icon/publicity workflow to use the one and same software. 

Also, stylistic choice: 
![image](https://user-images.githubusercontent.com/35357409/178025826-5d3cd66c-f1fb-4589-8ea3-af694c7b80ed.png)

I can move the 3 down if you'd like.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/178026588-58ea9eac-4b3d-4315-af82-bf0371a18362.png)

Doesn't line up as well, but thickness first now. Will commit this verison.

**Comment by Draise14** [comment]
Ok, got the versioning going relatively well. Now just waiting on the release build compile

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/178031088-8b7281a4-2124-4f31-adb9-480fe0823587.png)

Test compile done, now going to finish compile of release.

**Comment by ReinerBforartists** [comment]
:/

NEVER make a pull of the newest libraries for a release version. ALWAYS use the ones that you have used for the latest merge.

You will see if it will cause problems when it doesn't compile.

**Comment by Draise14** [comment]
Ok. Will push forward. I'll also add that to the list of things... Only update LIBs the day the merge happens.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/178064916-24409b41-b4af-406c-bc8f-4856e2bffa29.png)
Oops, overlooked this one. 

But on the good side, got a windows installer working. Just will fix this minor detail.

**Comment by Draise14** [comment]
Ok, I think I found it. Recompiling and testing, then will make the installer. These Youtube Tutorials are very helpful, takes the fear out of it.

**Comment by Draise14** [comment]
Nice, zipped and installer done, and release notes done. Next video.

**Comment by Draise14** [comment]
```
CMake Warning at /usr/share/cmake-3.16/Modules/FindBoost.cmake:1161 (message):
 New Boost version may have incorrect or missing dependencies and imported
 targets
Call Stack (most recent call first):
 /usr/share/cmake-3.16/Modules/FindBoost.cmake:1283 (_Boost_COMPONENT_DEPENDENCIES)
 /usr/share/cmake-3.16/Modules/FindBoost.cmake:1921 (_Boost_MISSING_DEPENDENCIES)
 build_files/cmake/platform/platform_unix.cmake:356 (find_package)
 CMakeLists.txt:1051 (include)
```
Found this one in my linux Cmake.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/178092225-41f77fc7-35b1-4caf-8ef0-f67732c273f5.png)

**Status:**
- Windows builds up with installer - big success!
- Release Notes online
- Linux build still happening
- Documentation compiled and branched, needs to be released and uploaded
- Official release notices still need to be done

I will continue the rest tomorrow after some sleep, it's now 2358hr lol I'm very slow at this, but it has been exciting. I am sure the next one will be faster. I have been taking notes of everything.

**Comment by ReinerBforartists** [comment]
It's not too complicated. But yeah, doing it the first time looks a bit overwhelming :)

**Comment by Draise14** [comment]
**Update:**
- Deb done, used the bin you provided
- Tar done, used the bin you provided
- Linux builds with Optix a success, will send a copy of that after I do another clean test compile of it. 
- Got desktop sync of the nextcloud to send files over
- Got documentation done to PDF
- Got it done to single PDF
- Uploaded documentation to Nextcloud (and shared)
- Updated the windows zip to have the release notes too
- About to do the App Image, just waiting on Github. 

Pending:
- Release online, update the links, send the files to put onto the server.

**Comment by ReinerBforartists** [comment]
Yes. Downloading at the moment. Then testing. Files will be up in a couple of minutes i guess :)

**Comment by ReinerBforartists** [comment]
Task is fulfilled. Do you want to close it?
