### ISSUE TITLE
Missing Cycles mist options in view layer properties

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3126]
We moved mist options for Eevee and Cycles to viewlayer properties tab, I think only eevee one was moved, we need to double check this and fixed if needed

**Comment by ReinerBforartists** [comment]
I don't see anything wrong here. Do i miss something?

![mist](https://user-images.githubusercontent.com/13919702/178779458-76fbbc5e-c297-40e0-b117-bc6d6822cec9.jpg)

**Comment by iyadahmed** [comment]
We moved mist panel to view layer, but inly eevee

**Comment by Draise14** [comment]
Can confirm, release build has both mist passes activated in eevee and cycles in the same place.

**Comment by Draise14** [comment]
![bforartists_UxpZHGicjY](https://user-images.githubusercontent.com/35357409/179079276-f7f1345d-4cd1-4bd2-8c6f-228b694eae52.gif)

This is what was referenced right?

**Comment by iyadahmed** [comment]
Yes, but the problem happened after merge

**Comment by Draise14** [comment]
Oooooooh I'll do a build and see.

**Comment by ReinerBforartists** [comment]
Curious. My build is up to date, pulled after the last merge.

**Comment by iyadahmed** [comment]
Ok lets close it until we find it 😄
