### ISSUE TITLE
Crash - Search (F3) crashes release build

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3127]
I found a crash with the latest release BFA 3.2.1 (date: 2022-07-10)...
![image](https://user-images.githubusercontent.com/35357409/179075961-ad32af13-798f-4336-add3-398390117c48.png)

**Description:**
Accessing the “Menu search” (Edit>Menu Search) crashes BFA.

I tested in clean installation, also tested with default Blender 3.2.1 final release and 3.0 alpha latest releases and all them are working fine the access with "Menu Search" in Blender. So I believe It might be something with BFA only on this version BFA 3.2.1 (date: 2022-07-10).

**Crashed version:** 
BFA v3.2.1 final build (2022-07-10)

**Working versions for reference:**
BFA v3.2 dev build (2022-07-02)
BFA v3.1.3  final build (2022-04-10)

**Comment by Draise14** [comment]
@iyadahmed or @ReinerBforartists any ideas? I wouldn't know where to begin with this one other than do another merge next weekend.

**Comment by iyadahmed** [comment]
Will check asap

**Comment by ReinerBforartists** [comment]
Cannot reproduce. Please deactivate all addons and try again (Clean build) . It can be that one of your addons makes trouble here.

![works](https://user-images.githubusercontent.com/13919702/179159366-a50d4433-b338-4393-9a44-86f9c18a157d.jpg)

**Comment by ReinerBforartists** [comment]
> I wouldn't know where to begin 

Forgot to answer this part here. Several strategies here. Do a debug build could be a first step. First switch to debug. Then set Bforartists as the start type as shown in the image. Then start the debugger, let Bforartists start, proceed to the crash, watch the error message and the connected code, and cry loud for help then :D

The more time consuming method is to have a look for the last working version, and try to find out which commit could be the trouble maker. We have the latest developer builds stored in the cloud.

And then there is the mallet method. Compare the Blender source code with what we have in Bforartists, and try to spot the difference that makes bang. This one can go back to a complete rebuild of Bforartists in the worst case ...

![debugbuild](https://user-images.githubusercontent.com/13919702/179173293-0361dd1c-27b6-4542-b6a6-fe703bda0f55.jpg)

**Comment by Draise14** [comment]
Made a new build. Seems the last merge fixed it. But the bug remains in the release. I can reproduce without fail in 3.2.1

**Comment by ReinerBforartists** [comment]
Indeed.  In the release version i can reproduce.  It's your decision if you want to make a new release. Now you know how to do it ;)

But i wouldn't. It's not worth the hassle. You can call the menu from the toolbar.

**Comment by Draise14** [comment]
I am not sure if this is a showstopper bug, gonna ask the person who reported it to see if it's worth it. If I were to use this build in production though I wouldn't like knowing there is a crash bug I can intentionally do very easily. I would like a point release personally. But.. I'll think about it.

**Comment by Draise14** [comment]
New release of Blender will come out soon (BCON3, beta), so.. I will save some energy and release this with the next release. Also.. sometimes it wouldn't crash, so it's hard to reproduce reliably.
