### ISSUE TITLE
Bforartists 3_3.2.1 closes directly when opening it.

### ISSUE THREAD

**Issue by UserAccount123** [Bforartists/Bforartists#3128]
The latest version of Bforartists 3_3.2.1 crashes directly when opening it. Before that I used the compressed version of the software, but the same problem exists. And the solutions in this post didn't work: https://www.bforartists.de/forums/topic/bforartists-crash-at-start-up/

# Windows 10 Pro.
# Graphic Card: AMD Radeon HD 7650M

https://user-images.githubusercontent.com/109344837/179191718-b65cca9d-dc45-445b-9726-917c4f5a6c04.mp4

**Comment by ReinerBforartists** [comment]
Many thanks for the report

Could you please try to start Bforartists from the console, and have a look for the message that appears when Bforartists shuts down immediately?

And could you please have a look if the same happens with an actual developer build of Blender? The 3.3.0 Alpha ... 

https://builder.blender.org/download/daily/

**Comment by UserAccount123** [comment]
> 

How to start Bforartists from the console ?

**Comment by ReinerBforartists** [comment]
Navigate to your Bforartists folder where the exe is.
Open cmd. Just search for it in the windows search.

In the console first switch to your drive. You can skip this point when the Bforartists exe is at drive C. type in a letter for your drive, followed by a double point. I am for example at drive E. so i type in e: . This switches to drive E then.

Now copy over the path from the open folder. Type in cd , followed by the path name. cd stands for change directory, a old DOS command. Hit enter. The console should now be in the folder. 

All that's left is to type in bforartists to start it.

Please ignore the error with the materials_library_x. This fixes itself when you click at Next in the Bforartists splash screen ...

What is of interest is what appears afterwards.

![cmd](https://user-images.githubusercontent.com/13919702/179194385-b863c77c-3c26-433a-89b9-740db6eefac8.jpg)

![starting it](https://user-images.githubusercontent.com/13919702/179194463-40dab9e2-3f56-4cf7-a69f-4b887157a1fb.jpg)

**Comment by UserAccount123** [comment]
> Navigate to your Bforartists folder where the exe is. Open cmd. Just search for it in the windows search.
> 
> In the console first switch to your drive. You can skip this point when the Bforartists exe is at drive C. type in a letter for your drive, followed by a double point. I am for example at drive E. so i type in e: . This switches to drive E then.
> 
> Now copy over the path from the open folder. Type in cd , followed by the path name. cd stands for change directory, a old DOS command. Hit enter. The console should now be in the folder.
> 
> All that's left is to type in bforartists to start it.
> 
> Please ignore the error with the materials_library_x. This fixes itself when you click at Next in the Bforartists splash screen ...
> 
> What is of interest is what appears afterwards.
> 
> ![cmd](https://user-images.githubusercontent.com/13919702/179194385-b863c77c-3c26-433a-89b9-740db6eefac8.jpg)
> 
> ![starting it](https://user-images.githubusercontent.com/13919702/179194463-40dab9e2-3f56-4cf7-a69f-4b887157a1fb.jpg)

Ok. Thanks.
The same problem exists.

**Comment by ReinerBforartists** [comment]
Of course, This was just to catch the crash error message. 

But what message can you read in the console after the crash?

**Comment by UserAccount123** [comment]
> 


https://user-images.githubusercontent.com/109344837/179198016-e003a697-6170-405a-acce-d68aa5db49fc.mp4

**Comment by UserAccount123** [comment]
> Of course, This was just to catch the crash error message.
> 
> But what message can you read in the console after the crash?

This this it : 

https://user-images.githubusercontent.com/109344837/179198375-b5dc6a95-862f-4c5c-a37a-a05be22c157f.mp4

**Comment by ReinerBforartists** [comment]
Yes, but what is to read in the console AFTER the crash. You cut this part away :)

As a note, it's usually enough to type bforartists. Not "start bforartists.exe"

**Comment by UserAccount123** [comment]
> Yes, but what is to read in the console AFTER the crash. You cut this part away :)
> 
> As a note, it's usually enough to type bforartists. Not "start bforartists.exe"

Oh, Ok.
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00000000027334B7
Module  : atio6axx.dll
Thread  : 00000ad8
Writing: C:\Users\PC\AppData\Local\Temp\blender.crash.txt

**Comment by ReinerBforartists** [comment]
Okay, thank you. This was the part that i was looking for :)

atio6axx.dll is your graphics card. Could you please check if Blender 3.3.0 Alpha starts for you? I had linked it above ...

https://builder.blender.org/download/daily/

**Comment by UserAccount123** [comment]
> Okay, thank you. This was the part that i was looking for :)
> 
> atio6axx.dll is your graphics card. Could you please check if Blender 3.3.0 Alpha starts for you? I had linked it above ...
> 
> https://builder.blender.org/download/daily/

No  it didn't start by double clicking on it, or by CMD method.

**Comment by ReinerBforartists** [comment]
This is what i have feared. From time to time Blender makes some old hardware deprecated. And i fear this is one of these cases. We cannot help you with that, sorry. We are bound to what Blender does in this area.

You could have a look to update your graphic card drivers and see if that helps. And if not you could make a bug report to Blender. But chances are small ...

Good luck

**Comment by UserAccount123** [comment]
> This is what i have feared. From time to time Blender makes some old hardware deprecated. And i fear this is one of these cases. We cannot help you with that, sorry. We are bound to what Blender does in this area.
> 
> You could have a look to update your graphic card drivers and see if that helps. And if not you could make a bug report to Blender. But chances are small ...
> 
> Good luck

OK, thanks, no problem.
Minutes ago I tried [Blender 2.83.21 - Release Candidate _ https://builder.blender.org/download/daily/] it worked fine.

**Comment by UserAccount123** [comment]
> This is what i have feared. From time to time Blender makes some old hardware deprecated. And i fear this is one of these cases. We cannot help you with that, sorry. We are bound to what Blender does in this area. We are tied to their source code.
> 
> You could have a look to update your graphic card drivers and see if that helps. And if not you could make a bug report to Blender. But chances are small ...
> 
> Good luck

OK, thanks, no problem :)

**Comment by ReinerBforartists** [comment]
You're welcome. Sorry that i have no better news :)

**Comment by UserAccount123** [comment]
> 

OK :)
I tried [Blender 2.83.21 - Release Candidate] it worked fine.
