### ISSUE TITLE
Hotkeys - 3D View - Hair Curve Object - Sculpt Mode hotkey 3

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3132]
![image](https://user-images.githubusercontent.com/35357409/179269577-c770843c-5c83-4474-9615-95a9b6f9ca9d.png)

New curve object has a sculpt mode, which could have the consistent hotkey to enter sculpt mode `3`

**Comment by ReinerBforartists** [comment]
Currently not possible because of this Blender bug: 

https://developer.blender.org/T99761

**Comment by ReinerBforartists** [comment]
Crash is resolved. Green light to tackle this one.

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/184605887-54365c99-8a3f-459c-a9e4-7b30f90b2eb7.jpg)
