### ISSUE TITLE
3D View - Hair Curve Object - Sculpt Mode - Add Brush - Left align brush settings check boxes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3133]
![bforartists_oDX5XzQHjV](https://user-images.githubusercontent.com/35357409/179270462-edab2a12-3670-44f0-a61b-cd7c7e470bec.png)
![bforartists_2TODa48Kmf](https://user-images.githubusercontent.com/35357409/179270467-73c96209-b14f-4c06-8f38-8d80559934aa.png)
![bforartists_x6BOEYJEyP](https://user-images.githubusercontent.com/35357409/179270469-63fb23a2-411d-4d38-af7c-95ff2c2da3ec.png)
![bforartists_e3fQavMO6Q](https://user-images.githubusercontent.com/35357409/179270472-8f2fb279-754f-4cb5-9d2d-708565dc9037.png)

There are two brushes that have settings that need right justified tick boxes to the Bforaritsts standard. This is both in the header menu and the toolshelf. There are only two brushes with these tick boxes, everything else seems ok. 

**Brushes:**
- Grow/Shrink
- Add

![bforartists_s9XOssc4pJ](https://user-images.githubusercontent.com/35357409/179270627-64f1d637-8dbd-4b87-a93e-2abed4d2ceb2.png)

**Comment by ReinerBforartists** [comment]
Please make single tasks here. *Fix Everything at once* is no valid task.

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/179348712-9a1e667c-91b5-4e18-bb09-fc241d0b8776.jpg)
