### ISSUE TITLE
3D View - Hair Curve Obejct - Sculpt Mode - Toolshelf needs tabs

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3134]
![image](https://user-images.githubusercontent.com/35357409/179271075-8643d41c-86fe-493a-a4d9-eacd81b1f0c8.png)

New mode means new place to add the tabs. This doesn't have tabs at the moment, so they should be added.

**Comment by ReinerBforartists** [comment]
And what do you want to add in them? There is no content yet that could be placed there.

**Comment by Draise14** [comment]
Ah you're right. So the tabs shouldn't show if there is only one panel of content.
