### ISSUE TITLE
3D View - Property Shelf - Workspae - Left align checkbox in "Pin Scene"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3136]
![image](https://user-images.githubusercontent.com/35357409/179272366-52a200ef-2cc9-438f-9d2b-cc0a6265721c.png)

New pin function for scenes in the Workspace panel in the Tool tab of the Property Shelf needs to be consistent with the rest of Bforaritsts, and put the checkbox justified left before text.

**Comment by ReinerBforartists** [comment]
Fixed in master

3D View - Property Shelf - Workspae - Left align checkbox in "Pin Scene" #3136
