### ISSUE TITLE
3D View - Hair Curve Object - Sculpt Mode - Select menu needs icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3137]
![image](https://user-images.githubusercontent.com/35357409/179272911-39bccd4b-5814-4ea3-b8a2-d05eb6534f16.png)

New mode, new operators = new iconography and documentation.

**Comment by ReinerBforartists** [comment]
Curve has still no sculpt mode. Experimental features should not be documented or touched until they are finished and officially landed in the trunk.

Postponing.

![nope](https://user-images.githubusercontent.com/13919702/179343953-b9ea262b-4e06-40e1-97a5-b6984a777e6a.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![selectmenu](https://user-images.githubusercontent.com/13919702/179347176-024b7d15-c3fb-462c-ac49-348d0e356140.jpg)
