### ISSUE TITLE
3D View - Hair Curve Object - Sculpt Mode - Curve menu needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3138]
![image](https://user-images.githubusercontent.com/35357409/179273193-3067cac4-04c5-4bea-a972-d3feaafdf562.png)

New mode, new operators = new iconography and documentation.

**Comment by ReinerBforartists** [comment]
Curve has still no sculpt mode. Experimental features should not be documented or touched until they are finished and officially landed in the trunk.

Postponing.

![nope](https://user-images.githubusercontent.com/13919702/179343936-bf6d872c-97f4-4016-9ac2-26ccb981376f.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![curvesmenu](https://user-images.githubusercontent.com/13919702/179346225-16dd185c-65c4-4db9-8998-417e4180b56d.jpg)
