### ISSUE TITLE
Hotkeys - 3D View - Global - Rotate View could be Click Drag instead of Press

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3139]
![bforartists_gCg4BZIHkn](https://user-images.githubusercontent.com/35357409/179313776-6e7e4874-0b77-420d-b9a4-cdfaafa105f1.gif)

Right now we use `press` to rotate the view with right click. But when in orthographic view, when you press the right mouse button, you leave orthographic. This makes the context menu unaccessible in orthographic mode, and some right click operations snap you out of orthographic. 

We could make this more stable by making the rotation of the view with `click drag`, meaning you can double click and right click in orthographic without cancelling orthographic view or unintentionally rotating the view when calling the context menu. 

![image](https://user-images.githubusercontent.com/35357409/179313931-2b3ac189-421f-4263-b85e-022539fb770d.png)

**Comment by ReinerBforartists** [comment]
Interesting catch. Never noticed this problem. And a great improvement :)

It's a hotkey conflict that needs a fix. And so it's a no brainer.

**Comment by ReinerBforartists** [comment]
Fixed in master
