### ISSUE TITLE
Crash with switching modes with hair curves editor in sculpting.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3140]
I experience a crash to desktop when i press hotkey 2 when in sculpt mode with the new hair curves object. Blender does not have the modes hotkeyed. So here the crash is not to reproduce. Unfunny.

The blender crash txt file points to a problem in the Blender code though.

![crash](https://user-images.githubusercontent.com/13919702/179344750-051532de-96ad-4ece-b315-1a63748426c1.jpg)

[blender.crash.txt](https://github.com/Bforartists/Bforartists/files/9125339/blender.crash.txt)

**Comment by ReinerBforartists** [comment]
I was able to reproduce the problem in Blender. 

https://developer.blender.org/T99761

**Comment by ReinerBforartists** [comment]
Update, you don't need to toy around with any hotkey. The trouble maker is the set select mode for this new curves object.

![troublemaker](https://user-images.githubusercontent.com/13919702/179364060-72823a84-cb60-46de-ae2a-aa148e7a88ff.jpg)

**Comment by Draise14** [comment]
I guess this will have to wait.

**Comment by ReinerBforartists** [comment]
Crash is resolved. Green light to tackle this one.

**Comment by ReinerBforartists** [comment]
Long fixed by the Blender devs.

Hotkey conflict is resolved with commit Resolve hotkey conflict with Set Select Mode in Sculpt mode and Empty Hair object #3147
