### ISSUE TITLE
Add menu in 3d view - add new curve object Empty Hair to toolbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3143]
Primitives should be equal in add menu and toolbar. We need to add the new object to the toolbar therefore.

![addtotoolbar](https://user-images.githubusercontent.com/13919702/179387042-a05fabac-dfec-44fc-a9ba-5fc794b2b369.jpg)

**Comment by ReinerBforartists** [comment]
Funny one. This is mission impossible. The greyed out button vanishes in the toolbar when you add an object to the scene instead of becoming active ...

There is no hint what is going on. But there is an error message in the console when you reload all the scripts. I am not sure if it belongs to this problem since it hints to a node item. So i made it a own task.

![nope](https://user-images.githubusercontent.com/13919702/179388250-79eab55a-3fa4-408f-a11c-2ef75938d3d5.jpg)

**Comment by ReinerBforartists** [comment]
Related 

Runtime error with nodeitems_builtins.py #3144

**Comment by ReinerBforartists** [comment]
I guess this is one of the operators that can just be called from within the 3d view ...

**Comment by ReinerBforartists** [comment]
Closing as mission impossible.

**Comment by Draise14** [comment]
This might mean that after you make the hair, it selects the hair object, which means you can't add another hair on the hair. You'd have to select the source object again. Did it work if at all? Maybe we can take a look at this one again. 

Also looks like the VX Library is causing issues here too.

**Comment by ReinerBforartists** [comment]
The material library vx causes issues since we have activated it by default. This is expected behaviour.

But now that the asset library contains these materials we could simply deactivate it again. And the user continues with the asset library versions. We just need to activate the asset lib by default then.

**Comment by Draise14** [comment]
Sure, let's disable the VX library once the asset library is default on. That will be for later
