### ISSUE TITLE
3D View - Hair Curve - Sculpt Mode - Select Menu - Separate tooltips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3155]
![image](https://user-images.githubusercontent.com/35357409/180336053-113014c4-d97c-4d6a-9ad8-250be4bb1672.png)

Has the same tooltip as Select All and None. Probably should be unique.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/184529937-a4e6836f-d724-403a-9182-a21f4616c412.jpg)
