### ISSUE TITLE
Extrude along normals misses widget

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3156]
We miss the extrude along normals widget. It's a bug!

![extrudealongnormals](https://user-images.githubusercontent.com/13919702/180834718-36e7b4b8-3054-4326-9f40-4bca803da77b.jpg)

**Comment by Draise14** [comment]
Woah, that's a bizzare one. I can confirm.....

**Comment by ReinerBforartists** [comment]
First find out at which point it broke ...

**Comment by iyadahmed** [comment]
Im on it

**Comment by iyadahmed** [comment]
Will continue, tomorrow confirmed it works in Blender old master

**Comment by iyadahmed** [comment]
file of interest, identical to blender, hmmm
`source/blender/editors/space_view3d/view3d_gizmo_tool_generic.c`

**Comment by ReinerBforartists** [comment]
Never miss the step to check if Blender behaves equal ...

I was able to reproduce it in Blender. It's not in our code. It's this drag thingie in the tool settings. The widget vanishes when drag is set to Active Tool. And we have made this one the default.

I think this is worth a Blender bug report. I hope it is not by design again :)

![activetool](https://user-images.githubusercontent.com/13919702/180986367-602c865a-7a4c-4df6-952e-a11dd2f69485.jpg)

**Comment by iyadahmed** [comment]
oh awesome, I'm relieved

**Comment by ReinerBforartists** [comment]
I know this feeling too well. This is the kind of bugs that can make you heart attacks :D 

But we are not through yet. The bug still needs a fix :)

**Comment by ReinerBforartists** [comment]
Bug report to Blender filed here https://developer.blender.org/T99993

**Comment by iyadahmed** [comment]
After looking at code, i think it is by design, well an old design I guess, the extrude tool has a different gizmo code than the extrude along normals

The latter has generic in its name, as you see in the file path I posted before,

While the first is called gizmo_extrude_3d

So it is a consistency problem, imo Blender should either make all extrude widgets generic, and so the gizmo disappears when drag mode is active, or make them all display gizmo all time

**Comment by ReinerBforartists** [comment]
Yes, i was already told that this seems to be by design. And after thinking about it it even makes sense to some degree. In this mode there is no conflict with the select tools. But it is imho highly inconsistent. It looks broken. Even when this "broken" is just a psychological problem.

I haven't investigated into the code. But thanks for the hint. Maybe this opens a door for us in case the Blender developers are not to convince and we decide to go another route here.

**Comment by ReinerBforartists** [comment]
Shall we keep this open? We can't do anything here anyways. It is reported to Blender. And will arrive in BFA once it is fixed. Or never ...

**Comment by iyadahmed** [comment]
I guess we could close it, it is a blender "bug" after all, and making our improved version with minimal conflict with blender will take some work

**Comment by ReinerBforartists** [comment]
So let's close it. Thanks :)
