### ISSUE TITLE
Properties Editor - Cycles - Scambling Distance is greyed out

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3157]
![bforartists_SwTaBVPPsZ](https://user-images.githubusercontent.com/35357409/181344573-7fad0a58-eeb8-4918-a164-731d1ec83143.png)

> Scrambling distance is greyed out when using adaptive sampling (though both can be used at the same time). The viewport still acts the way I expect so it's just this part of the UI that's confusing me

Probably should check to see why these are greyed out but still usable and make it like Blender. 

Blender:
![image](https://user-images.githubusercontent.com/35357409/181344805-ce5b1094-4326-4af3-83e9-d665892bfd55.png)

**Comment by ReinerBforartists** [comment]
Good catch
