### ISSUE TITLE
Runtime error in toolbar with apply - cannot apply to a multi user / crash with apply from the menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3158]
I have here a curious error in the toolbar with the apply tool. And a crash from the apply menu. Used at some reference images.

The crash is to reproduce in Blender, and is already reported: https://developer.blender.org/T100040

But Blender does not have our toolbar. So this bug is not to reproduce. I expect that both have the same cause though.

What is still curious is how i ended in this state with a multi user involved.

Scene is attached in the zipfile below.

![crash](https://user-images.githubusercontent.com/13919702/181483706-1260f62e-7f46-42bd-9951-d967741451b7.jpg)

![error](https://user-images.githubusercontent.com/13919702/181483718-62a77a3c-25c1-4942-973d-3ea4310018f1.jpg)

[crashbug.zip](https://github.com/Bforartists/Bforartists/files/9208179/crashbug.zip)

**Comment by ReinerBforartists** [comment]
Okay, the popup happens because i use the image in more than one background image. Then the image is multi user. And this is troubled it seems.

**Comment by Draise14** [comment]
Yeah. Anything multiuser can cause a bug with apply. The error is a known issue and over the past months they tried to make this more... Intelligent. But this may be only intelligent with object data, not empty data.

**Comment by ReinerBforartists** [comment]
This issue is resolved, and fixed with the newest merge. Closing.
