### ISSUE TITLE
No autosmooth for reimported obj file

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3160]
Odd one. I have imported a obj file. This mesh part has no setting for autosmooth. You cannot apply autosmooth anymore.

Problem 1: all edges are marked as sharp
Problem 2: even after removing the sharp edges, autosmooth stays greyed out.

Blender bug report is at its way.

![missingautosmooth](https://user-images.githubusercontent.com/13919702/181708330-4c1c6e03-8f33-4906-b2e2-a378345ee850.jpg)

![autosmooth](https://user-images.githubusercontent.com/13919702/181708352-c913f9d4-4068-4984-b6f1-da98548f67e5.jpg)

**Comment by ReinerBforartists** [comment]
Hm. no. The sharp edges is a problem in BFA only. We need to check the im- and exporter, and if we are up to date here.

**Comment by ReinerBforartists** [comment]
Bug report created: https://developer.blender.org/T100055

**Comment by ReinerBforartists** [comment]
FBX has the same problem. Great :/

**Comment by ReinerBforartists** [comment]
And the sharp edges comes from the exported mesh being faceted, not smoothed. 

Either way, this is a really big showstopper bug. I hope it is fixed soon ...

**Comment by ReinerBforartists** [comment]
Bug report is closed as invalid. I am speechless.

**Comment by ReinerBforartists** [comment]
Okay, the bug report is closed as invalid. So we have to take action here. 

First thing is, grey out Autosmooth with custom normals. Hiding will not do since it looks broken. And we might want to add a warning text to make clear why autosmooth is deactivated. 

Second place to look is our toolbar. Add remove custom normals button here, and do the same than in the normal panel. Grey out and add a message.

![second problem](https://user-images.githubusercontent.com/13919702/182191248-cf6bacbb-5166-41e3-a35b-ed18e7abedcd.jpg)

**Comment by cl3m3c7** [comment]
the problem is in the (legacy) obj exporter!
to fix this for the imported mesh, you have to:
1. clear sharp edges
2. clear custom split normals data (Properties Editor - Object Data - Geometry Data - Clear Custom Split Normals Data)

**Comment by cl3m3c7** [comment]
I think you will get the desired result for the legacy one by **disabling** Write Normals option.

![fix](https://user-images.githubusercontent.com/61097104/182257450-9a48f8f7-57c9-437f-a354-7e3bc8aba85d.png)

**Comment by ReinerBforartists** [comment]
Yes. Normals is the trouble maker. But Blender imports every normals as split normals. We need a better UX here. Simply disabling the normals is no option since external meshes may come from other apps, with normals activated.

**Comment by ReinerBforartists** [comment]
Changed it to a task, since it is expected behaviour at the moment.

**Comment by ReinerBforartists** [comment]
Not happy. but Happier. Fixed in master

Let's document this change ...

![1](https://user-images.githubusercontent.com/13919702/182538623-0378e442-0f65-4094-a49e-bc76c9efb43e.jpg)

![2](https://user-images.githubusercontent.com/13919702/182538645-672820e2-50b2-44a7-abd2-689198835675.jpg)
