### ISSUE TITLE
Image Editor - Texture Paint - Brush Addon Panels and tabs

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3164]
![image](https://user-images.githubusercontent.com/35357409/181933898-2557e425-b559-4b66-b504-b0a0faccc73c.png)

Looks like the image editor could also do with the brush panel addon for the tabs and such. Not sure if this is a larger job since this toolshelf has no tabs yet - but the brush type tab should also be in the Paint mode of the Image Editor.

**Comment by iyadahmed** [comment]
Closed by #9b2c157bcc6bf68587722848561b395cfe76961b
