### ISSUE TITLE
3D View - Edit Mode - Select Similar floating menu (Blender hotkeys) - Missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3165]
![image](https://user-images.githubusercontent.com/35357409/182025495-8afcd085-cc5b-4317-9a0d-bfb201f5bbe4.png)

In the blender hotkeys `SHIFT+G` you call a floating menu to select similar. I do this often so I use this hotkey in the BFA keymap too. But this menu has missing icons. If a user comes in from Blender and uses the blender hotkeys, this menu might feel inconsistent. 

Add icons.

**Comment by cl3m3c7** [comment]
if I understand what you said correctly:

1. I changed the hotkey to blender
2. Add some meshes
3. Go to edit mode
4. Change select mode to face (numpad 3)
5. press SHIFT+G

it shows the icons in the menu!

![fff](https://user-images.githubusercontent.com/61097104/182227607-152a6009-3809-4124-a2f0-ca0358ace218.png)

**Comment by Draise14** [comment]
Ok. Thats weird. 

Try this:
1. Go to Bforartists Keymap
2. Go to the menu entry and assign hotkey through the right click menu
3. Go to the hotkey editor and search for the hotkey
4. Remove the setting so that the Hotkey will call the menu
5. Trigger


I have been over worked this week and did 7 days straight.. I could have been confused with an older version (3.1.3).

**Comment by cl3m3c7** [comment]
yes, indeed it is missing in BFA keymaps.
I thought it was missing from the Blender keymaps.

**Comment by cl3m3c7** [comment]
btw, if you invoke the same operator using the search functionality, the behavior is the same. (no icons)

**Comment by Draise14** [comment]
Ok, so there are hidden operator panels with no icons still.... and somehow the Blender keymap calls the right one, but no other custom keymap.

**Comment by ReinerBforartists** [comment]
This could be one of the cases where we added the python menu instead of iconizing the old c menu. So first let's have a look if Blender also uses the python menu or not.

**Comment by ReinerBforartists** [comment]
Indeed. We have python operators. Blender uses a enum to enumerate the C menus.

I would vote to use the C menu too. And iconize it proper. The fewer not necessary differences to Blender, the better the maintaining is.

![enum](https://user-images.githubusercontent.com/13919702/182300289-901de42f-09f8-4072-94f7-d29879198ea7.jpg)

**Comment by ReinerBforartists** [comment]
Wise decision. Select similar vertex crease is already missing in our python operators.
![vertexcrease](https://user-images.githubusercontent.com/13919702/182301658-e83ff5c3-8827-44c7-a56a-a3f8c806264c.jpg)

**Comment by ReinerBforartists** [comment]
Resolved

![similar](https://user-images.githubusercontent.com/13919702/182315581-2f540093-4c74-4aa6-885d-06b3ed201389.jpg)

**Comment by ReinerBforartists** [comment]
Now documenting the missing operator ...
