### ISSUE TITLE
Geometry Nodes - New node: Shortest Path

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3170]
![image](https://user-images.githubusercontent.com/35357409/182691206-63493546-2576-4fb3-adeb-65ed8da46d82.png)

![image](https://user-images.githubusercontent.com/35357409/182514866-48338aa6-0ddc-4a2f-b1c5-7962a0b572ad.png)
New node means new entries, icon and documentation. 

There are three new nodes here:
**Shortest Edge Paths** uses Dijkstra's algorithm with a priority queue implementation to output a field of indices to the next vertex.
**Edge Paths to Curves** takes the field of next vertices and outputs the selected paths as curve splines.
**Edge Paths to Selection** outputs a selection of all edges included in any path.

**Relevant Blender Path:**
https://developer.blender.org/D15274

**Comment by ReinerBforartists** [comment]
Fixed
![solved](https://user-images.githubusercontent.com/13919702/183025555-9054f525-d609-40fb-bcf5-19d14cff6665.jpg)
