### ISSUE TITLE
View 3D Toolshelf: Buggy transparent panel backgorund under Linux

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3172]
![image](https://user-images.githubusercontent.com/25552173/182538307-834766b0-a47b-446f-973e-2b10231022ed.png)

**Comment by ReinerBforartists** [comment]
Nice :D

Hm, this looks more like a graphics card glitch. And i cannot reproduce it here. I cannot fully test it though. The VM doesn't allow me to turn on HIP or oneAPI. Is one of it active?

![nottoreproduce](https://user-images.githubusercontent.com/13919702/182540737-8f67574b-41ff-4197-821d-166218e1e319.jpg)

**Comment by iyadahmed** [comment]
Nope no oneapi or hop, just my amd laptop with amd internal gpu

**Comment by ReinerBforartists** [comment]
Internal ... :)

**Comment by iyadahmed** [comment]
> Internal ... :)
> 
> You could check if Blender has similar problems with panels. But it doesn't have our tool shelf tabs ...

Yeah I should check, but my feeling is that there's something off, I have to double check the transparent background code

**Comment by ReinerBforartists** [comment]
Sure. But when it's the code then all panels would show this behaviour. This looks like a graphics card glitch to me. And internal graphics chips are officially not supported.

**Comment by iyadahmed** [comment]
> Sure. But when it's the code then all panels would show this behaviour. This looks like a graphics card glitch to me. And internal graphics chips are officially not supported.

Right it is either gpu or some weird code bug (pointers or something)

**Comment by iyadahmed** [comment]
I found clues
Blender changed the file to .cc extension a while ago, .c file is not used by Blender any more, we have both files

**Comment by iyadahmed** [comment]
I think this the problem, our .c file is not used at all

**Comment by iyadahmed** [comment]
actually wait, non of that is right, I was trying to revert the old commit and it confused me, our changes were merged into the .cc file

**Comment by Blenux** [comment]
I have same issue, though black with a Intel GPU.

![Screenshot_20220808_002151](https://user-images.githubusercontent.com/25260650/183295346-1987a443-d73a-438d-ba2f-5e476fe79e40.png)

If I open the Mirror Local Tab (and then Transform above for the Mirror Local Tab), the black goes away.

![Screenshot_20220808_003503](https://user-images.githubusercontent.com/25260650/183296038-93ff2537-3ffe-4569-93c3-55033d0b46b2.png)

**Comment by iyadahmed** [comment]
@Blenux 
can we test again with master?,
I think the manual merge commit fixed this too

**Comment by Blenux** [comment]
Yeah it was. notice it earlier when on my Linux Laptop.

**Comment by iyadahmed** [comment]
Fixed by https://github.com/Bforartists/Bforartists/commit/6ed67260a41714fb8c5963792c2ffc640a45b1b2
