### ISSUE TITLE
Brush Panel Addon - Texture Paint mode - 3D View+Texture Paint - icons of 24px to 16px versions

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3176]
![image](https://user-images.githubusercontent.com/35357409/182723586-ec5e0309-564f-42c6-a272-4b42364ca6a5.png)
 Some icons of the brush panel are still at 24px instead of the 16px versions. We have some alternative icons, not quite the same, but they would sit better if we change them a little. So this task is to log that change of the 4 icons of the Texture Paint mode of the addon. 

- Clone
- Fill
- Mask
- Soften

Here are some alternatives:
Mask = OVERLAY
Clone = BRUSH_CLONE
Soften = BRUSH_SOFTEN
Fill =  FLOODFILL

**Comment by iyadahmed** [comment]
![image](https://user-images.githubusercontent.com/25552173/183126861-4e75297c-4237-4633-bc0d-794dc9293f39.png)
they look great

**Comment by ReinerBforartists** [comment]
We have an explicit mask icon. Just saying ^^

**Comment by Draise14** [comment]
Ah right. We need 16px versions of all the larger brush icons... It's becoming confusing knowing which is which for which...

**Comment by ReinerBforartists** [comment]
Not really. Just the new tool system works with the big ones. Everything else needs the small icons.
