### ISSUE TITLE
Sequencer - Preview Mode - Right click Sequencer Preview Context Menu needs an icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3177]
![bforartists_7uVbVMC7BK](https://user-images.githubusercontent.com/35357409/182736469-0979d01c-f907-4435-8776-c7795e817df2.png)

The preview window now has a context menu, and with that a single operator. Rename. This has no icon.

**Comment by ReinerBforartists** [comment]
Needs documentation too i guess :)

**Comment by ReinerBforartists** [comment]
![fixed](https://user-images.githubusercontent.com/13919702/183008108-7fd8d914-4aa5-4775-b1c3-54b7e11d549f.jpg)
