### ISSUE TITLE
Missing icon in UV Editor - UV menu - snap

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3181]
Cursor to Origin needs icon 
![missing](https://user-images.githubusercontent.com/13919702/183239339-cc9fcb42-33c2-4bcb-b5d9-587df67f8625.jpg)

**Comment by iyadahmed** [comment]
Mmm I think this is fixed in master

**Comment by ReinerBforartists** [comment]
Ah indeed. Closing. Thanks :)

![confirmed](https://user-images.githubusercontent.com/13919702/183240416-1c96bba8-9c86-404f-a7fa-f0badcd885b0.jpg)
