### ISSUE TITLE
UV Editor - center selected UV patches

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3182]
Currently you cannot center the selected UV Patches in the UV space directly. The center of the selection is calculated by all the positions of the single vertices, and middled then. Means this point can be completely off from the middle of the selection. Like in my shot.

To achieve to put the patches really into the middle is a two step process at the moment. First set the 3D cursor to the center, then use selected to cursor - Offset. 

This needs a bit thinking. And is not obvious to users. So i think a button that centers the selection with one click would be a good idea :)

Maybe we can also achieve to have the values not working with the middled values, but with the center of the bounding box.

![trouble](https://user-images.githubusercontent.com/13919702/183239747-40bed8e3-be19-421e-83d3-c8c8620a3156.jpg)

**Comment by Draise14** [comment]
Textools addon has this and much more.. it is the UV editor 2.0. it's ah soon with icons too. It fits in nicely.

**Comment by ReinerBforartists** [comment]
Okay, then we don't need this task anymore i guess :)

Closing.
