### ISSUE TITLE
Keep widgets onscreen or provide a substitute

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3183]
Widgegs are a fine thing. When they are in reach. They can easily go offscreen when you zoom in to do some fine tuning ...

Not sure if this task is even manageable. Maybe we can make some buttons in the header as a substitute to manipulate the things that you can manipulate with the widgets. Or like with the navigation elements up right.

![widgetsproblem](https://user-images.githubusercontent.com/13919702/183240154-91a24fea-36c5-42d8-a89d-5703660de6e3.jpg)

**Comment by Draise14** [comment]
We can make widgets stick to the cursor, so you can move from there, and place the cursor (and the widget with it) to anywhere. Would this be the workaround? Could that process be automated maybe with a button (like reset widget)

I feel this would be a core architecture issue with the way widgets draw that would need to be done with Blender devs...

**Comment by ReinerBforartists** [comment]
Hm, yeah. But you know what feature requests means ...

**Comment by ReinerBforartists** [comment]
... on the other hand, this would indeed be the job of the Blender developers. We could just work around. And keeping it under the mouse while dragging is imho no valid workaround. It would jump away in the moment when you release it.

What is left is the workaround. A panel maybe, with buttons for the different methods. Maybe even by an addon. The different translation methods are available by python.

I would say leave it open. Maybe i have some days left for this idea at one point.

**Comment by ReinerBforartists** [comment]
I did some experiments with some simple buttons. And geez what a orientation chaos. We have two contradicting orientation dropdowns. And so i cannot convince the buttons to always work in the same direction than the widget. 

Giving up at it. Not worth the hassle.

![orientationchaos](https://user-images.githubusercontent.com/13919702/197332890-10647a93-b572-44eb-9ed3-c3570618f099.jpg)
