### ISSUE TITLE
3.2.2 Release

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3184]
![Annotation 2022-08-06 105556](https://user-images.githubusercontent.com/25552173/183247716-75e3cfca-4866-4f9a-be4c-81c9ff5ed21b.png)

**Comment by iyadahmed** [comment]
This is my release notes file @ReinerBforartists , what should I change
[bfa_322_release_notes.txt](https://github.com/Bforartists/Bforartists/files/9274945/bfa_322_release_notes.txt)

**Comment by iyadahmed** [comment]
files
Linux Deb: https://drive.google.com/file/d/1uzzg0g7mQ6kbOC3ilPisMBu46-EVnllo/view?usp=sharing
Windows Installer: https://drive.google.com/file/d/1yrn97Cr_IkFi_ecCkqM1MhwL6GGHSHQX/view?usp=sharing

**Comment by ReinerBforartists** [comment]
Windows Zip?

**Comment by ReinerBforartists** [comment]
The release notes seems to have a problem with encoding

> Release Notes â€“ Bforaritsts 3 Version 3.2.2 â€“ 06.08.2022

Also, i usually put a summary above it in the version that i put into the zip file.

For example:

> You can report bugs in the Github tracker: https://github.com/Bforartists/Bforartists/issues
> Official Webpage: http://www.bforartists.de
> 
> Bforartists 3 Version 3.2.1 is a maintenance release to keep Bforartists updated with the latest changes from Blender 3.2.1. This release also includes two new painting modes for the Bforartists Brush Panels addon for the toolshelf - select your paint brushes with one point and click. Now in Vertex, Texture Paint and Weight Paint modes (activate the addon in the Preferences).
> 
> --------------------------------------------------------------------

>Release Notes -  ......

**Comment by iyadahmed** [comment]
here but it doesn't have release notes:
Windows ZIP: https://drive.google.com/file/d/1WaeyqbG9LV8Xawo04uzyK1nQ38RXWswv/view?usp=sharing

**Comment by iyadahmed** [comment]
will put it and update the file

**Comment by ReinerBforartists** [comment]
Many thanks. I can add it. No problem :)

WIndows installer works fine. But the deb not :/

And we need the tar.xz too :)

And of course at one point the mac version ...

![deb](https://user-images.githubusercontent.com/13919702/183256440-c813ac7f-5dc5-4ba3-9e69-21ab12995e37.jpg)

**Comment by iyadahmed** [comment]
ok very great, sending the tar.xz asap

**Comment by ReinerBforartists** [comment]
Um, did you compile a Windows release version or a developer version?  Or did you add 100 mb new content? The zip file is 345 mb big. But it should be around 250 Mb with a release version.

**Comment by ReinerBforartists** [comment]
Hm, the deb seems also a bit big.

**Comment by iyadahmed** [comment]
mm I added the hip binaries maybe that's it

**Comment by iyadahmed** [comment]
it was a release

**Comment by ReinerBforartists** [comment]
But they shouldn't add 100 mb. Curious. This is what i mean with official supported tools. Maybe we run into a problem with your custom compiler here.

**Comment by ReinerBforartists** [comment]
This will need a while to compile. I am not sure if i can manage it today.

**Comment by iyadahmed** [comment]
> This will need a while to compile. I am not sure if i can manage it today.

I can recompile but I assure you it is a release, I will recompile no worries, but it is very possible those new binaries

you can try to diff the files with meld or so

**Comment by ReinerBforartists** [comment]
Yeah sure, no problem. I believe you. But something is odd here. And i want to know where the problem is and fix it. It's always about the solution :)

Ah, with the tar, make sure you have the fitting folder structure so that we can build the appimage from. We need a release here at github to create the appimage version ...

**Comment by ReinerBforartists** [comment]
Mh, part of the release is to create a release branch too ...

**Comment by ReinerBforartists** [comment]
I hate it. Hip did already work ...
![hip](https://user-images.githubusercontent.com/13919702/183257364-aa9fd128-9c09-46bc-8a37-09c32fe1fed3.jpg)

**Comment by ReinerBforartists** [comment]
Unfunny part is that it is busy now with compiling cuda first for minimum half an hour ...

**Comment by iyadahmed** [comment]
https://github.com/Bforartists/Bforartists/tree/bfa3v3.2.2

**Comment by ReinerBforartists** [comment]
My Ubuntu VM is kidding me. Again the warning that installation is not possible. But it installs just fine. Both versions, the one that you created, and the one that i have created just before a few moments to check for the problem.

However. My version has 20 mb fewer content. Makes me wonder what you compile into the binary here :D


![difference](https://user-images.githubusercontent.com/13919702/183258327-38318972-d9ef-4d21-8b7a-b1b6831e552a.jpg)

**Comment by ReinerBforartists** [comment]
I am lost with hip. Seems that i am out of business. I cannot manage to compile it. The path is correct from what i can see. It just  simply doesn't work :/

Giving up for today ...

![hipcc](https://user-images.githubusercontent.com/13919702/183258525-cd3f4216-82f5-4d7f-8df3-eb94dd71fc2e.jpg)

**Comment by iyadahmed** [comment]
ah, the solution is simple, the problem is this executable is for linux
hipcc.bat is for windows and it needs perl to be installed
https://strawberryperl.com/

**Comment by ReinerBforartists** [comment]
Hm, thanks,  but as told, i had it already working. I have cleared the cmake cache now and am ready to compile from scratch again. Maybe the Cmake cache is kidding me here. But as told, i will finish it tomorrow. It is evening now here :)

**Comment by iyadahmed** [comment]
I just used the Blender make.bat with release option

`./make release`

**Comment by ReinerBforartists** [comment]
I never found out how you can do this at Windows :D

**Comment by ReinerBforartists** [comment]
\o/

Cmake cache was indeed kidding me. VS does not need an extra perl installation.

And the zip has indeed grown by 30 mb, but not by 100. As told, will do another compile tomorrow, with the Blender release settings ...

![cmake](https://user-images.githubusercontent.com/13919702/183260643-3882b840-e91f-4188-819f-feaf94c76dde.jpg)

**Comment by iyadahmed** [comment]
Ah it is easy cmd in the folder then make release, ok see you tomorrow I'm currently working on the linux build again

**Comment by iyadahmed** [comment]
I suspect because the blender make script adds more stuff than we do via manual cmake, stuff that should be added to match a Blender release

**Comment by ReinerBforartists** [comment]
Well, i normally do check if we have all release settings on. By hand. The config files are in build_files\cmake\config

But i haven't checked for quite a while if something vital has changed. Possible that i have overlooked something.

**Comment by Draise14** [comment]
The addon with the default library may be a few more MB.but not that much but it adds something.

**Comment by ReinerBforartists** [comment]
Okay, saw the Perl error in the console now. And i think i found what causes the bigger size. Compiling with **make release** compiles with the Hip binaries. And then you need perl.

But i thought the binaries are not necessary to compile by ourselves yet because of the big compile time, and that they are precompiled already. Hm. Let's install Perl. They need it in the release, so we do it ...

![hipbins](https://user-images.githubusercontent.com/13919702/183277070-43ae0e9c-be68-495e-b87a-2a0cab666831.jpg)

**Comment by ReinerBforartists** [comment]
For finishing the release, i will use the ones from you now. We can figure out the details at a later point. Compiling everything with the right settings simply takes too long and blocks my pc ...

I still miss the tar and the zip file :)

**Comment by ReinerBforartists** [comment]
The release note is quite incomplete. And misses several entries.

What makes it complicated is that the log does not distinguish between our commits and the commits from Blender developers.  So in this case it would be better to use our tracker instead. At least to pick the committer names. Ayoub is cl3m3c7 ...

And it contains again issues without issue number. Iyad, i know it's hard, but please always make a tracker issue, and always commit with issue number. These not referenced issues are not to follow anymore ...

![incomplete](https://user-images.githubusercontent.com/13919702/183277740-682a0f39-1e63-48b9-ab4d-bb600eb016e0.jpg)

![notreferenced](https://user-images.githubusercontent.com/13919702/183277750-283a7553-85aa-4d81-a6f2-1ec2a90aca26.jpg)

**Comment by ReinerBforartists** [comment]
... and don't call it Bforaritsts ^^

The corrected release note is attached. Please also take care that you don't call it bfa in official documents. We haven't rebranded Bforartists.
[releasenote_bforartists3_321.txt](https://github.com/Bforartists/Bforartists/files/9276283/releasenote_bforartists3_321.txt)

**Comment by ReinerBforartists** [comment]
Still in trouble. Perl is installed, the path is changed, but i still get the error. Will empty the cmake cache now and do a from scratch compile in the afternoon. 

![stilltroubled](https://user-images.githubusercontent.com/13919702/183279454-198e1ce8-a98a-42ff-b0fc-f28f5d359b32.jpg)

**Comment by ReinerBforartists** [comment]
I did now the linux version of make release. And it is three mb smaller than by hand :D

Something is very very odd here. Waiting for the tar.xz to compare the two versions ...

**Comment by ReinerBforartists** [comment]
Ah, the optix path trap, that's why ...

![optixtrap](https://user-images.githubusercontent.com/13919702/183280391-07d402b3-d4b6-4183-b532-0f6b8903e491.jpg)

**Comment by iyadahmed** [comment]
Also for perl you need to replace the word “perl“ in the file hipcc.bat with full path to perl.exe

Everything else in hipcc.bat has to stay the same even the @ before the word perl and the words after perl

**Comment by iyadahmed** [comment]
Linux tar.xz
https://drive.google.com/file/d/18fVaP-YvmcZqSzHqAHSNprZJ6cjI_Y14/view?usp=sharing

**Comment by iyadahmed** [comment]
Uploading deb now

**Comment by iyadahmed** [comment]
here: Linux deb
https://drive.google.com/file/d/1VIgzrheVkqx1oDvIQk-uM7Ooo6oLEFwH/view?usp=sharing

**Comment by iyadahmed** [comment]
> The release note is quite incomplete. And misses several entries.
> 
> What makes it complicated is that the log does not distinguish between our commits and the commits from Blender developers. So in this case it would be better to use our tracker instead. At least to pick the committer names. Ayoub is cl3m3c7 ...
> 
> And it contains again issues without issue number. @iyadahmed @cl3m3c7, I know it's hard, but please always make a tracker issue, and always commit with issue number. These not referenced issues are not to follow anymore ...
> 
> ![incomplete](https://user-images.githubusercontent.com/13919702/183277740-682a0f39-1e63-48b9-ab4d-bb600eb016e0.jpg)
> 
> ![notreferenced](https://user-images.githubusercontent.com/13919702/183277811-2d9fec1b-9e45-4e5a-809f-85143e377015.jpg)

The ones that miss issue number don't have a github issue created usually, it is committed directly

**Comment by ReinerBforartists** [comment]
> The ones that miss issue number don't have a github issue created usually, it is committed directly

That's the problem. Please always make tracker issues :)

I or somebody else might want to comment at one of these commits. Or request changes. Or we might need to return to such an issue. And then we are doomed.

So please always make tracker issues. No direct commits when you can avoid it.

**Comment by iyadahmed** [comment]
ok :+1:

**Comment by ReinerBforartists** [comment]
> Also for perl you need to replace the word “perl“ in the file hipcc.bat with full path to perl.exe
> 
> Everything else in hipcc.bat has to stay the same even the @ before the word perl and the words after perl

Ah, that's the trick. Awesome. Many thanks. Now it compiled :)

To document the needed changes of hipcc.bat:

```
@set HIPCC="%~dp0/hipcc"
@C:\Strawberry\perl\bin\perl.exe %HIPCC% %*
```

The result remains odd. The zip file from you has 366 Mb. Mine has 307 Mb. I will check again this in the evening ...


![works](https://user-images.githubusercontent.com/13919702/183286856-c4b54c97-a51a-4727-a04d-fec5be828e73.jpg)

![sizedifferences](https://user-images.githubusercontent.com/13919702/183286857-44b8119c-421c-45e3-8d00-0253b769b91a.jpg)

**Comment by ReinerBforartists** [comment]
Also linux shows a significant difference in size.

![difference](https://user-images.githubusercontent.com/13919702/183287019-0f1aea18-a872-4233-9f72-e01874230487.jpg)

**Comment by iyadahmed** [comment]
how was the self compiled made, `make release` ?
I used `make release BUILD_CMAKE_ARGS=-DOPTIX_INCLUDE_DIR="~/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64/include"`

because I installed optix to that path, that way it uses the Blender release cmake config + path to optix correctly, because it doesn't detect path to optix automatically

**Comment by iyadahmed** [comment]
btw I'm creating a release to speed things up we can edit the files later if needed but be assured I'm sure everything is done correctly

![image](https://user-images.githubusercontent.com/25552173/183287154-34b0ac75-4efd-4935-841f-719de7b7c7d3.png)

**Comment by ReinerBforartists** [comment]
Sure, this is also part of the job :)

**Comment by ReinerBforartists** [comment]
> how was the self compiled made, `make release` ? I used `make release BUILD_CMAKE_ARGS=-DOPTIX_INCLUDE_DIR="~/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64/include"`
> 
> because I installed optix to that path, that way it uses the Blender release cmake config + path to optix correctly, because it doesn't detect path to optix automatically
> 
> and also I use `cpack -G TXZ` in the output build folder to generate the tar.xz

Yes, simply with **make release**

The packing is not the problem. Also the unpacked files shows a siginificant difference.

![difference](https://user-images.githubusercontent.com/13919702/183287251-744ae366-8e07-4c31-9c43-3a79bb3cbdc1.jpg)

**Comment by ReinerBforartists** [comment]
Give me a rest please. I go on in the evening. In 5 hours ... ^^

**Comment by iyadahmed** [comment]
hmm, then cpack is the difference I guess, it is not the bin folder packed to tar.xz, cpack should pack things correctly
sure please rest, no worries

**Comment by ReinerBforartists** [comment]
No, it's not cpack. You have a few files more than i have. For Linux it's fatbin files in the cycles directory. What are the fatbin files in the cycles addon folder good for? I miss these. What do i overlook here? 

But i haven't found the extra 100 mb in the windows installation yet. Just that your Windows Optix version might be outdated. I run 7.4 here. Yours seems to be compiled with 7.1. But this does not explain the 100 mb more content in your file. I am simply lost where this comes from. We both pull from the same master in the end.

Anyways, your tar.gz will not allow you to create the appimage version. It requires a special folder structure. Please download the tar from the latest release and have a look. You need to repack it :)

![fatbin](https://user-images.githubusercontent.com/13919702/183300096-40289481-a524-4302-b853-f0f4bbdd68b0.jpg)

![version](https://user-images.githubusercontent.com/13919702/183300112-5cf56293-c58b-49a9-b525-fcd7fc59422d.jpg)

**Comment by ReinerBforartists** [comment]
Mh, fatbin. which cuda version do you use? At Linux i am at 11.6 from what i remember. But at Windows I am still at 11.4.

**Comment by ReinerBforartists** [comment]
Riddle solved. Iyad still compiles with an older cuda version. Means old cuda files onboard :)

**Comment by ReinerBforartists** [comment]
Hm, adding the (still) missing release note to the zip file crashed my pc. @iyadahmed what do you use to create the zip file? I use 7zip here.

**Comment by ReinerBforartists** [comment]
Is the manual also at its way?

**Comment by iyadahmed** [comment]
> Hm, adding the (still) missing release note to the zip file crashed my pc. @iyadahmed what do you use to create the zip file? I use 7zip here.

hmm how crashed this is just a normal zip file, windows ships with a zip explorer

**Comment by iyadahmed** [comment]
> Is the manual also at its way?

hopefully yes

**Comment by iyadahmed** [comment]
I will add release notes

**Comment by ReinerBforartists** [comment]
> > Is the manual also at its way?
> 
> hopefully yes

:D

I guess this means Draise is at it ^^

**Comment by ReinerBforartists** [comment]
> hmm how crashed this is just a normal zip file, windows ships with a zip explorer

YIKES !

Do yourself a favour and use 7zip. Faster, better packing. And Windows zip is known to have problems. Like my blackscreen while trying to add a file by drag n drop at a zipfile. This just works with 7zip :)

https://www.7-zip.org/

**Comment by ReinerBforartists** [comment]
Release is live. Files are up, release note is updated. Writing the news at the usual places at the moment. The few that i know of.

Misses the manual and the mac version.

**Comment by ReinerBforartists** [comment]
Oh and the next merge is also overdue :)

**Comment by iyadahmed** [comment]
Working on it now

**Comment by iyadahmed** [comment]
It seems vscode changed their merge ui :(

**Comment by Draise14** [comment]
Phew, a lot for me to catch up on. 

I will work the documentation after work or tomorrow first task before work.

**Comment by Draise14** [comment]
I

**Comment by Draise14** [comment]
Ok, finally got some time this morning. Will work documentation and publicity now.

**Comment by ReinerBforartists** [comment]
I need the single pdf files please :)

**Comment by Draise14** [comment]
Yes, on the nextcloud now. I have also taken note of the differences. More info here:
https://github.com/Bforartists/Manual/issues/335

**Comment by Draise14** [comment]
Ok, now I guess is pushing the release publicity. I will go through the release notes now and see what I can make to get some noise.

**Comment by ReinerBforartists** [comment]
Excellent :)

**Comment by ReinerBforartists** [comment]
A release video maybe, explaining the new default asset and the brush addon? That's two biggies that we haven't made really public yet. I can add it to our youtube channel then :)

**Comment by Draise14** [comment]
Started making some images to post, will make some quick short videos soon too.
