### ISSUE TITLE
Website - Critical error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3189]
![Screenshot_20220809-091657-163](https://user-images.githubusercontent.com/35357409/183672668-ce020eea-e63c-4661-a3a9-331421e0d78b.png)

Website is offline at the moment. I haven't touched anything. Not sure what to do here. 

Reported by a user on Twitter

**Comment by ReinerBforartists** [comment]
Yes, Wordpress update and such ...

Working at it

**Comment by ReinerBforartists** [comment]
Page is back working. An addon update ran amok ...
