### ISSUE TITLE
Outliner - Library Override context menu needs to be rebuilt

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3197]
**Bforartists**
![image](https://user-images.githubusercontent.com/35357409/185007586-1960b6c9-567b-4b4d-b89f-aaa2f3dd1c94.png)

**Blender:**
![image](https://user-images.githubusercontent.com/35357409/185007338-e08752e1-5b4f-4359-ad90-fe36db4a7c31.png)

This context menu is now missing, and needs to be added with iconography and all the operators. This also will need new documentation, the library override system as a UX has been rebuilt from the ground up by the looks of it. 

It is also 3 sub-menus deep......
![image](https://user-images.githubusercontent.com/35357409/185007450-17bab7ea-4ca6-49e4-923a-896b990c3c11.png)

And.. the labeling is not clear at all creating confusing with the previous method and current method (though the same)..... goddamn. Another task for another day.

**Relevant Blender Task**
https://developer.blender.org/rBc73cc15e07ea6b0e2e4d1f7fa419e428291f45ad

**Comment by ReinerBforartists** [comment]
Sure that we want to have it like in Blender? Separators should be more than sufficient here. The deeper the hierarchies, the more you battle with the menus.

**Comment by ReinerBforartists** [comment]
Hm. On the other hand, the C menus exists ...

**Comment by Draise14** [comment]
I would move everything up a hierarchy and make the naming conventions a bit like the older naming conventions. Though I have yet to take a look at the code.

**Comment by Draise14** [comment]
Gonna need this later today, so will commit.

**Comment by Draise14** [comment]
![bforartists_frcbcXA2zD](https://user-images.githubusercontent.com/35357409/186746573-ec28606b-272c-46d6-b2a7-3a82627dcb73.gif)


Update:
- Moved the library overrides up a level in the context menu
- Added iconography
- Renamed the top entries to be explicit (though still a mouthfull)

I did give a try to move up the enumerated operator to run two simple ones (create hirarchy or single) which as a UX I prefer... but that will have to be another day as a new custom operator or class would have to be built maybe.

**Comment by Draise14** [comment]
Now time to document.
