### ISSUE TITLE
Create Social media publicity - 3.2.2 Release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3199]
![Update - Bforartists3 - Official Release 3 2 2](https://user-images.githubusercontent.com/35357409/185019138-18ce63a2-3db8-4abb-9c13-f2391614fe58.png)

Create Social media and videos for the release

- Images
- Videos

**Comment by Draise14** [comment]
Recorded a video, a little informal but will upload to Nextcloud now.

**Comment by Draise14** [comment]
Video now on Nextcloud, pushed to Discord.

**Comment by Draise14** [comment]
Pushed to Blender Artists, Blender Today community, to the discord servers I'm in.

**Comment by ReinerBforartists** [comment]
Great work. I have done it now again, but don't forget to approve the reddit entries. Else just you can see the new post :)

Shall i upload the video to our youtube channel?

**Comment by ReinerBforartists** [comment]
Video is live. Thanks :)

**Comment by Draise14** [comment]
Wait, I have to approve my own posts on reddit?

**Comment by ReinerBforartists** [comment]
Crazy, but Yes :)
I never found a way to auto approve ...

**Comment by ReinerBforartists** [comment]
Shouldn't we close this task? We have arrived at 3.3.0 already ...

**Comment by Draise14** [comment]
Ah yeah.
