### ISSUE TITLE
Default Addons - Activate Node Wrangle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3200]
The Node Wrangler addons was once activated by default. Now it's not. Would be good to have it activated by default.

**Comment by ReinerBforartists** [comment]
Hm, i don't think it ever was. Since the by default activated addons needs an entry in source\blender\blenkernel\intern\blendfile.c

But yeah, why not.

Please note though that we have quite a few hotkey conflicts between the addon and our official keymap.

**Comment by Draise14** [comment]
Oh? I've used it for years. What are the conflicts?

**Comment by ReinerBforartists** [comment]
I think it already starts with the viewer node, but i would have to check again.

**Comment by ReinerBforartists** [comment]
One last note here before you really think about activating the addon by default, we need to document the tools then. They show in the UI. And we might need to add icons. And to tweak the addon here and there. 

Maintaining addons ...

**Comment by Draise14** [comment]
Oh... hmm.. then in this case it might be worth it still. Every user has to activate this anyway to really have a good UX with nodes. 
It's mostly iconography and documentation.. hmm.......

**Comment by ReinerBforartists** [comment]
Postponing for after the 3.3.1 release

**Comment by ReinerBforartists** [comment]
I am still not keen to do this one here. The nodes works just fine without the addon. And everybody who dives deeper activates it anyways. And it is around and available. 

To activate it by default would put a big burden to us though.

**Comment by Draise14** [comment]
Postponed for 3.6.0

Would require documentation updates, cleanup of the addon if applicable, and making sure there are no hotkey conflicts - though it is heavily requested by users to have this as a default.
