### ISSUE TITLE
3D View - Grease Pencil - Edit Mode - Stroke - new Outline operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3203]
![image](https://user-images.githubusercontent.com/35357409/185997011-be519ee8-4b6c-4c8d-aac7-2d2b22f35ace.png)

**Outline, Convert stroke to perimeter** operator exists. Need iconography and documentation. This also needs to be added to the toolshelf. 

![image](https://user-images.githubusercontent.com/35357409/185997189-37d63ac3-0256-47c9-a587-811b29908d48.png)

**Comment by ReinerBforartists** [comment]
Duplicate, already fixed and documented here

https://github.com/Bforartists/Bforartists/issues/3216
