### ISSUE TITLE
File Browser - New view Pie Menu added needs to be exposed to GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3205]
![image](https://user-images.githubusercontent.com/35357409/186000856-00b437ed-e23b-48ee-a46f-1c28fb8476a9.png)

New view Pie Menu added needs to be exposed to GUI, documented. Hotkey also needs to be added (though it doesn't work or exist on a Spanish keyboard)

![image](https://user-images.githubusercontent.com/35357409/186001018-1705e62e-4dc9-40c0-8dec-267ecd0e07d0.png)

**Comment by ReinerBforartists** [comment]
Postponing for after the 3.3.1 release

**Comment by ReinerBforartists** [comment]
Couldn't resist. Fixed

Updating manual ...

![piemenus](https://user-images.githubusercontent.com/13919702/194742987-c1f194ee-0922-4a7d-bce0-6ee82c0aeb6b.png)
