### ISSUE TITLE
File Browser - View menu - missing icon on Frame Selected

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3206]
![bforartists_KyKV5LGRWG](https://user-images.githubusercontent.com/35357409/186001337-a5ed695c-f721-40cd-9460-d6fd7c40c2b3.png)

A missing icon in the view menu of the file browser is... missing. Needs to be sorted, and double checked if documented.

**Comment by ReinerBforartists** [comment]
While i agree that it doesn't hurt to add the missing icon, this menu is usually completely hidden. Users are not even aware that this menu exists. It is a fragment from the past.

**Comment by ReinerBforartists** [comment]
Fixed in master
