### ISSUE TITLE
Outliner - Make Library Override common operators go to top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3212]
![bforartists_2lebwN3zmy](https://user-images.githubusercontent.com/35357409/186752278-e570a471-7e60-4e82-9d56-c8350d1b6b7e.png)

Right now we have 12 nice library operators.. but the most common is to make single or hierarchy. These two in Blender and Bforartists 3.2.1 were top level like this:

![bforartists_Bj5FUTRzNQ](https://user-images.githubusercontent.com/35357409/186752379-37db5647-9915-41e5-bb0d-cea2e3707f8a.png)

But now they are hidden under a large chunk of text with no iconography. We don't put icons on operator sub-menus per the standard (only exception is the Add Menus) - so... maybe we can move a couple up a level? Maybe just the make ones (3 top level with iconography)? 

I gave a shot and tried to put those sub-enumerated menus up a level, but it was beyond my skill at the time being. 

@ReinerBforartists and @iyadahmed any ideas how to do it?

**Comment by ReinerBforartists** [comment]
Hm, for me it looks good as it is. The downside of having it top level is to crowd this menu.

And i fear this is also behind my skills ^^

**Comment by Draise14** [comment]
Yeah.. it is a bit of a double entry if moved up and disorganized.... I use these over and over and over when doing layout, but a hotkey or using the quick menu in the Outliner may help. 

Hope Blender makes up their mind on the final form. 

I'll close for now.
