### ISSUE TITLE
Request - put Hide in context menu

### ISSUE THREAD

**Issue by redwolfen** [Bforartists/Bforartists#3214]
the hide and reveal in the right click menu was added in blender 2.9x in alpha not sure, but was abandoned in the release.  although  having a shortcut in ALT+H to hide object, for me it is much better to be added in the right click context menu as you are selecting object and right clicking is much easier and hide or reveal object using the mouse or stylus.

**Comment by ReinerBforartists** [comment]
Um, may i fix the title and put the text into the body? :)

**Comment by Draise14** [comment]
It's this for the 3D view or outliner context menu? Or both?

**Comment by ReinerBforartists** [comment]
I guess he means the 3d view.

**Comment by ReinerBforartists** [comment]
Postponing for after the 3.3.1 release

**Comment by ReinerBforartists** [comment]
This task is still not decided from what i know. Shall we do or shall we decline?

**Comment by Draise14** [comment]
The whole context menu is a double, so ok having it there. With the right comment in the code it might be easy to maintain there. Let's do it, why not..

**Comment by ReinerBforartists** [comment]
Because i hates it :D

As told, we then should do it in all context menus of the editors where show / hide is available ...

**Comment by Draise14** [comment]
Hate is never a justified reason! =P 

Righteo so then, makes sense to make it consistent elsewhere, makes the task larger but ok. It is a bit of a hotkey reliant operator anyway.

**Comment by Draise14** [comment]
Postponed for 3.6.0

**Comment by Draise14** [comment]
Nearly done.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/492d0810-ce71-4c10-bae3-693052ba9eef)

Added to these menus. 

The sculpt menu has some operators, but I think it doesn't make too much sense since that workflow.. is jank and may need future love.

**Comment by Draise14** [comment]
Working documentation.

**Comment by Draise14** [comment]
Oops, Armature pose mode had these at a top level.

**Comment by Draise14** [comment]
Documentation done, was a big chunk.
