### ISSUE TITLE
Inaccurate Scrambling Multiplier Tooltip

### ISSUE THREAD

**Issue by StandingPadAnimations** [Bforartists/Bforartists#3215]
**Describe the bug**
In the current release of BFA, an older UI bug was fixed where the Automatic Scrambling Distance options were greyed out when Adaptive Sampling was enabled (as Automatic Scrambling Distance works fine with Adaptive Sampling in newer versions of Cycles)

However, it seems like the tooltip for Scrambling Multiplier has not been updated yet, as it still claims that Adaptive Sampling needs to be disabled in order to use it

**Desktop (please complete the following information):**
Windows 10
Nvidia GTX 1660 Super
BFA 3.2.2

**Screenshots, Example Files**
![image](https://user-images.githubusercontent.com/75058058/188322165-48ce11df-3856-484a-bd94-c408a9ff4364.png)

**Comment by ReinerBforartists** [comment]
Good chatch. Thanks for the report. Seems that we need to revert the tooltip then :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/188809716-7588dad0-d932-4649-a598-d1dd2125d585.jpg)
