### ISSUE TITLE
3D View - Grease Pencil - Edit Mode - Outline Operator needs iconography and cleanup

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3216]
![image](https://user-images.githubusercontent.com/35357409/188630582-3d3eabf7-5ce2-4316-8c70-abb15047b4b5.png)

Currently we have a double Outline operator in the Stroke header menu. This is found in the 3D View, Grease Pencil, Edit mode, Stroke mode. This needs the following:

1. Iconography
2. Documentation
3. Add to the toolshelf

**Comment by ReinerBforartists** [comment]
Fixed in master. 
Commit went to the wrong issue sorry. Copy n paste problem ...

New operator from Blender: GPencil stroke set start #3230

![outline](https://user-images.githubusercontent.com/13919702/190849931-6168985f-580c-435e-9051-d1e3a9bc4f63.jpg)
