### ISSUE TITLE
Geometry and Shader Nodes - New Mix node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3217]
![image](https://user-images.githubusercontent.com/35357409/188632052-d68f9722-0cb3-4bd5-9646-fbcec8ed8c60.png)

New Mix node needs iconography, documentation and then added to the toolshelf.

**Comment by ReinerBforartists** [comment]
Mix node icon already exists from the now deprecated former mix node.

**Comment by ReinerBforartists** [comment]
Part of the task: We need to remove the mix rgb node from the Color panel. It is deprecated now.

![mixrgb](https://user-images.githubusercontent.com/13919702/188922798-e7ddcecf-3a28-4d2d-a750-58c639dafdd1.jpg)

**Comment by ReinerBforartists** [comment]
Same goes for the manual. Remove the deprecated node from the Color chapter. (not without simply copying over the content before deleting it, which saves us some work)

**Comment by ReinerBforartists** [comment]
Related. Shader Nodes - Converter - New Mix node #3218

This node is reused in the shader editor too. So let's make it one task, and fix it all at once.

**Comment by ReinerBforartists** [comment]
Fixed in master
