### ISSUE TITLE
Shader Nodes - Converter - New Mix node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3218]
![image](https://user-images.githubusercontent.com/35357409/188632515-55ba2098-97ed-456f-9d0b-0f8e50a35cc1.png)
New Mix node needs iconography, documentation and then added to the toolshelf.

**Comment by ReinerBforartists** [comment]
Mix icon already exists from the former now deprecated mix node.

**Comment by ReinerBforartists** [comment]
This node is the same as the shader node in node editor. It is reused. So closing this task as a duplicate, and continue with the other.
