### ISSUE TITLE
Shader Nodes - Mix RGB node still works but no longer listed in Add Menu, add back

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3219]
![image](https://user-images.githubusercontent.com/35357409/188633416-629b5c1c-c774-48cd-894c-831f62d4849e.png)

This node is now deprecated, but it is still functional and in our add toolshelf and still usable (for now). This is replaced by the "Mix" node. 

In my opinion, the deprecated node should still be accessible from the GUI in a consistent mannor. This is what I think should be done:

1. Add it back to the Add header menu
2. Change the tooltip to show that it is legacy or deprecated
3. Change title a little if possible to show it is legacy or deprecated

**Comment by ReinerBforartists** [comment]
When it's deprecated, then remove it!

Blender has removed it, and so should we.

**Comment by Draise14** [comment]
Here's the thing. They haven't removed it.

**Comment by ReinerBforartists** [comment]
:D

Then we have a bug :)

**Comment by ReinerBforartists** [comment]
Draise, is it removed or not? When they have removed it from the UI, then it is deprecated. In this case we should remove it too. Everything else will just make big trouble at our end. We simply cannot document and maintain deprecated content.

They keep it under the hood to keep it compatible with older blend files. That's all.

**Comment by ReinerBforartists** [comment]
We still misunderstood each other :)

It IS removed when it is removed from the UI. So why should we put it then back into the UI?

**Comment by Draise14** [comment]
Because it is a hidden feature.

**Comment by ReinerBforartists** [comment]
No it is not. It is a deprecated feature. You shall not use it anymore. That's the difference. It makes no sense to add it back when you sould not use it :)

The old node is removed from the UI to have no conflict with the new node that they have added recently.

**Comment by Draise14** [comment]
Ah ok.. so I guess this would close as not necessary. I would think a transition period for the end artist would be important so they can recreate old trees. But if not then that's ok. Less work.

**Comment by ReinerBforartists** [comment]
Don't make it over complicated. We better stick to the official available nodes in Blender. And deprecate them when they deprecate them :)

And yes, please close as not necessary :)

**Comment by ReinerBforartists** [comment]
Closing ...
