### ISSUE TITLE
Geometry Nodes - Color - Mix RGB node still works but no longer listed in Add Menu, add back 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3220]
![bforartists_wiEZAwaG7T](https://user-images.githubusercontent.com/35357409/188635942-6b3fe558-2eca-4c27-ab01-8e1d1c7d2d5a.png)

This node is now deprecated, but it is still functional and in our add toolshelf and still usable (for now). This is replaced by the "Mix" node.

In my opinion, the deprecated node should still be accessible from the GUI in a consistent mannor. This is what I think should be done:

- Add it back to the Add header menu
- Change the tooltip to show that it is legacy or deprecated
- Change title a little if possible to show it is legacy or deprecated

**Comment by ReinerBforartists** [comment]
As told in other threads, deprecated nodes are deprecated for good reason. It is a bad idea to add them back then.

Closing.
