### ISSUE TITLE
Shader Nodes - Converter - Squeeze Value node doesn't exist in GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3221]
![image](https://user-images.githubusercontent.com/35357409/188640055-8d9be0d2-5d3b-4545-970b-4a43f93466c1.png)

This node has snuck in un-noticed and not till recently was this brought to light. 

This node is only accessible in the search or drag off UX. There are no GUI entries, not even in the Add Menu.

**Comment by ReinerBforartists** [comment]
And in Blender? Remember there's a complete old set of nodes in the code here and there still.

**Comment by Draise14** [comment]
Node exists there, just not in the GUI. It also.. seems to not be searcheable unless you drag off a value socket. Talk about discovery....

**Comment by iyadahmed** [comment]
blender
![image](https://user-images.githubusercontent.com/25552173/188756768-c3c63211-dcd7-4f50-9f98-997bb40e78ab.png)

**Comment by iyadahmed** [comment]
Blender master build
![image](https://user-images.githubusercontent.com/25552173/188756903-4dad03a8-7b1d-4c7d-a454-79d5ad31e27f.png)

**Comment by iyadahmed** [comment]
More validation, the node is missing from 3.x blender docs

**Comment by ReinerBforartists** [comment]
Whenthis node is missing from the menu and is not documented, then there is no action required at our end. Just maintain the official nodes. Everything else will just make big trouble at our end. These nodes are deprecated for good reason. The user shall not use it anymore.

I will close this issue therefore.
