### ISSUE TITLE
Showstopper Bug - Eevee - Custom Attribute with Alpha Clip issue 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3226]
I have been trying to work the release builds, but found a bug in production. This I would consider a show-stopper bug and may require another merge to fix. I cannot reproduce in Blender. 

**Blender 3,4 on today date 08-09-2022 (desired result)**
![blender_2LE0KOTCiK](https://user-images.githubusercontent.com/35357409/189152570-ea3599a0-a855-4f92-bea2-72b755429789.png)
Take note of the hole in the alpha clip. 

**Issue in the devbuild-03-09-2022 and the Master today**
![image](https://user-images.githubusercontent.com/35357409/189153152-88199001-8798-466d-a588-34414f0c6987.png)

1. Load this scene
[3.4 Troublshooting 02.blend.zip](https://github.com/Bforartists/Bforartists/files/9527829/3.4.Troublshooting.02.blend.zip)
2. Go to the Shading workspace
3. Load the Console
4. Take note the Alpha clip is not working
5. Take not in console an error like this:
![powershell_EZrOFWSgz9](https://user-images.githubusercontent.com/35357409/189152898-d192c978-834c-4c77-bb04-8814708a0ab1.png)

In the Object Custom properties I have tested with the GUI custom properties and custom properties I made with an addon. Both cause the issue (the Custom Attribute) node. This in turn causes an issue when Alpha Clip is activated with Eevee. It's an obscure but also a show stopping bug since Custom Attributes are used in materials all the time.

**Comment by ReinerBforartists** [comment]
Hm. I am lost with this bug. I have no idea what is going on here.

First step, Try to find the last working Bforartists version. The developer builds of the last three months are still in the bfa cloud.

**Comment by Draise14** [comment]
Last working version **devbuild-27-08-2022**. Have already tested and will continue this to deliver the deadline - but I am assuming to fix this in the master will require a new merge? Since in Blender master it's ok?

**Comment by ReinerBforartists** [comment]
No, it requires to find what causes this bug. Most probably something at the last merge went wrong :)

**Comment by Draise14** [comment]
Hmm...

This would be out of my domain. @iyadahmed could you take a look at this one? We can't do a release with this bug, so we have to find what's up.

**Comment by Draise14** [comment]
With things like this, a merge con awry, how would you roll back to do it again?

**Comment by ReinerBforartists** [comment]
In case everything else fails you need to do a code comparison against Blender ...

**Comment by ReinerBforartists** [comment]
> With things like this, a merge con awry, how would you roll back to do it again?

Going back to a state where the code worked. And continue from there. But, oh boy ... :D

**Comment by Draise14** [comment]
Just what I needed....

**Comment by ReinerBforartists** [comment]
Always expect the unexpected ;)

I've been in this situation more than once. Maybe not this bad that you are trapped by such a rascal now. Learning by doing. But i was in the lucky situation that i did the merges too. And so i roughly knew what was going on. Your best bet is that Iyad may have an idea here.

The second best solution is to have a look at the single commits. And have a closer eye at the changes that might have to do with the issue.

You could also follow down the node in question, and compare this code part with the blender code. 

And as told, in case everything else fails, do a code comparison between BFA and Blender source code. Usually you always find something that slipped throug. You just need to be lucky enough that the real trouble maker is one of the first ones that you find ... :D

**Comment by Draise14** [comment]
Custom attribute is still crash in master, making a clean build just in case.

**Comment by Draise14** [comment]
We found some more changes. Being worked on..

**Comment by iyadahmed** [comment]
Fixed by https://github.com/Bforartists/Bforartists/commit/6ed67260a41714fb8c5963792c2ffc640a45b1b2
