### ISSUE TITLE
Enums compatibility problem with Blender by changed order

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3227]
![image](https://user-images.githubusercontent.com/25552173/189248907-264c1f12-010c-4d05-b128-6a204a585a39.png)

this effectively tricks the user, if he chose one method it will be the other internally

to change order we change UI not switch internal things

**Comment by iyadahmed** [comment]
another one
and please correct me if I'm wrong
![image](https://user-images.githubusercontent.com/25552173/189249596-98343e62-bca0-42d5-8078-09b9c6f73ef2.png)

**Comment by ReinerBforartists** [comment]
Is it dsysfunctional? Then it needs a fix. But it worked when i implemented it. Hm.

**Comment by Draise14** [comment]
The second one is intentional, done by me, and changes the default creation of the strips. "Replace" made the NLA default pretty much useless for animation layering as a default, when it should be "non linear". Relevant Task: #3028 

From a quick test to double confirm, the UX still works as expected from the GUI, when you create a new NLA strip or action script then push down, it will create in "Combine" mode in the GUI, and work with expected UX on the drop downs. This was tested quite a bit. This change doesn't change the UX of which menu enum  is what and the GUI is not changed, only what the strip mode creates on (which now is "combine") - and it is technically working. I think the reason this works is because there are operator "classes" that are enum agnostic here, then the enum menu calls these array orders to from top to bottom from another file, which was not changed. This file you are looking at only refers to which is "first" by user default. 

![image](https://user-images.githubusercontent.com/35357409/189333691-62f7621b-10c3-4023-a6dc-a9a94e7e5259.png)

Occasionally Bforartists tries to improve UX by improving defaults, not just GUI.

**Comment by iyadahmed** [comment]
> The second one is intentional, done by me, and changes the default creation of the strips. "Replace" made the NLA default pretty much useless for animation layering as a default, when it should be "non linear". Relevant Task: #3028
> 
> From a quick test to double confirm, the UX still works as expected from the GUI, when you create a new NLA strip or action script then push down, it will create in "Combine" mode in the GUI, and work with expected UX on the drop downs. This was tested quite a bit. This change doesn't change the UX of which menu enum is what and the GUI is not changed, only what the strip mode creates on (which now is "combine") - and it is technically working. I think the reason this works is because there are operator "classes" that are enum agnostic here, then the enum menu calls these array orders from top to bottom from another file, which was not changed. This file you are looking at only refers to which is "first" by user default.
> 
> ![image](https://user-images.githubusercontent.com/35357409/189333691-62f7621b-10c3-4023-a6dc-a9a94e7e5259.png) ![bforartists_4PXI99EhMK](https://user-images.githubusercontent.com/35357409/189335914-0661e1fd-4d4a-4b7c-8769-33f8c5ea4ed3.gif) [ ![bforartists_4PXI99EhMK](https://user-images.githubusercontent.com/35357409/189335914-0661e1fd-4d4a-4b7c-8769-33f8c5ea4ed3.gif) ](https://user-images.githubusercontent.com/35357409/189335914-0661e1fd-4d4a-4b7c-8769-33f8c5ea4ed3.gif) [ ](https://user-images.githubusercontent.com/35357409/189335914-0661e1fd-4d4a-4b7c-8769-33f8c5ea4ed3.gif)
> 
> Occasionally Bforartists tries to improve UX by improving defaults, not just GUI.

The thing is this is not default, what these changes essentially did is swap the names of things, so any logic will be broken

these are neither defaults or UI enums, these are C enums which should stay the same,

I agree with you we can change defaults, but these are not the defaults sadly the changes have to be made somewhere else

**Comment by ReinerBforartists** [comment]
I can just speak for the Display Stretch. I haven#t investigated into the other case yet.

The order of the enum influences the default here. And so i switched them. I found this the only way to make it default. And switching the positions does the trick. We have default Area. Blender has default Angle. And Angle is Angle, and Area is Area. There is nothing switched.

When you find a better way, then you are welcome :)


![area](https://user-images.githubusercontent.com/13919702/189391603-d978d02b-db08-4ea3-a4ec-a31a3165a107.jpg)

**Comment by Draise14** [comment]
Ah ok, now I see the issue. Changing the enum to change the default will break Blender/Bforartists. When the NLA clip is combined in BFA, it will still be Replace in Blender, and thus break the animation. And same with the UV defaults, they will swap when working with Blender. 

So yeah, this will need work in the other tasks... re-opening. And.. yeah, revert these changes to stay compatible with Blender..

**Comment by ReinerBforartists** [comment]
Never noticed this. Good catch. And a sad one. I would suggest to postpone this until after the release. A rushed solution will not help anybody.

**Comment by iyadahmed** [comment]
it breaks compatibility with Blender files, it will break user files that come from Blender in a very bad way

**Comment by ReinerBforartists** [comment]
I see. So what is the solution to make our defaults the defaults instead then?

**Comment by iyadahmed** [comment]
the changes would be made somewhere else, no worries it should be easy

**Comment by ReinerBforartists** [comment]
Famous last words XD

I look forwards with what you come up with :)

**Comment by iyadahmed** [comment]
This was fixed, but I do not want to close it until I change defaults properly

**Comment by iyadahmed** [comment]
Defaults changed in 
https://github.com/Bforartists/Bforartists/commit/f2b49617456d6cda55c2abcdb4da975b1d5d4398
and
https://github.com/Bforartists/Bforartists/commit/03fe00baca9ac9e0303c6821561a07348cec57f8
