### ISSUE TITLE
New operator from Blender: GPencil stroke set start

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3230]
![image](https://user-images.githubusercontent.com/25552173/189548920-cefba255-b6d4-4d20-9f05-37de43702481.png)

**Comment by ReinerBforartists** [comment]
First needs a new icon.

**Comment by ReinerBforartists** [comment]
Hm, needs entry into the tool shelf too i guess.

![startpoint](https://user-images.githubusercontent.com/13919702/190847450-8759a8d0-5ee6-4558-aefc-13d990b693c8.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
