### ISSUE TITLE
New operator from Blender: UV align rotation

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3231]
![image](https://user-images.githubusercontent.com/25552173/189549930-4c27ad21-e607-43a6-88d3-0b2f9e866bd4.png)

**Comment by ReinerBforartists** [comment]
I guess we should also have a look if we can add it to the toolbar.

**Comment by ReinerBforartists** [comment]
-.-

![problem](https://user-images.githubusercontent.com/13919702/190844329-74bff9f7-26f0-4630-9ffd-3ed3c219a055.jpg)

**Comment by ReinerBforartists** [comment]
Okay, this is another issue. I will make a bug report.

**Comment by ReinerBforartists** [comment]
Fixed in master
