### ISSUE TITLE
Geometry Nodes - Add Shelf - Interpolate Domain name "Field on Domain" needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3239]
![image](https://user-images.githubusercontent.com/35357409/190926754-0827ae68-3574-4bfd-8fd9-5708634c54dc.png)

They changed this name, missed the memo.

**Comment by ReinerBforartists** [comment]
Draise, please bigger screenies. Now i have to guess in which category it is ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
![fixed](https://user-images.githubusercontent.com/13919702/192472841-63569ee8-964c-448a-8fa9-27e1c138320a.jpg)
