### ISSUE TITLE
developerbuild startup bug

### ISSUE THREAD

**Issue by Davis-BfA** [Bforartists/Bforartists#324]
When I try to open the developer build I get the following error message:
---------------------------
bforartists.exe - Systemfehler
---------------------------
Die Ausführung des Codes kann nicht fortgesetzt werden, da VCRUNTIME140D.dll nicht gefunden wurde. Durch eine Neuinstallation des Programms kann das Problem möglicherweise behoben werden. 
---------------------------
OK   
---------------------------

**Comment by Draise14** [comment]
I got no issue opening it up, but that's because maybe I have Visual Studio installed?

**Comment by ReinerBforartists** [comment]
Most probably yes. And i think i know the cause. It's a debug build :D

Let me compile a release version quickly ...

**Comment by ReinerBforartists** [comment]
I have replaced the previous version in the download section. Release Version is also much smaller now ^^
Please test.

https://www.bforartists.de/content/download#devbuild

**Comment by Davis-BfA** [comment]
Yes, that works. ... Great to see the iconized node menu back in the shading workspace. :D

**Comment by Draise14** [comment]
As reported in the forum, Dev Build  Bforartists 2 - Alpha 0.8.0 was again built in Debug mode. 
![firefox_2019-11-21_16-30-10](https://user-images.githubusercontent.com/35357409/69378368-39989380-0c7c-11ea-912d-47929053f357.png)
![firefox_2019-11-21_16-30-17](https://user-images.githubusercontent.com/35357409/69378371-3b625700-0c7c-11ea-8760-64169210cc66.png)

**Comment by ReinerBforartists** [comment]
YIKES!

Will fix it immediately. But please make it a new bug report the next time :)

**Comment by ReinerBforartists** [comment]
I have created a new thread. Closing this one.
