### ISSUE TITLE
Sequencer - two rows where it should be one

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3241]
![image](https://user-images.githubusercontent.com/35357409/190928483-333fd76d-19c8-4198-808a-b78e4c9dae8b.png)

Looks like 1 column view it not drawing correctly for some reason. This code may need some updating.

**Comment by Draise14** [comment]
Though... zooming in an out a little makes it snap correctly, so might be a default theme issue from an old layout in the templates. the templates may need some rebuilding.

**Comment by ReinerBforartists** [comment]
Isn't it this issue ? https://github.com/Bforartists/Bforartists/issues/3237

**Comment by ReinerBforartists** [comment]
While at it, the home key (pos 1 key at a german layout) resets all toolbars under the mouse to the default zoom ...

**Comment by Draise14** [comment]
Ah, maybe it's the same issue. But yeah.

**Comment by Draise14** [comment]
But at "default" zoom the toolshelf is going to double column in single column mode in the Sequencer. Matybe that's an issue in itself. 
![bforartists_siI0CkDa00](https://user-images.githubusercontent.com/35357409/191042211-90281dc7-71fe-4cfd-9196-78375970693b.gif)

**Comment by Draise14** [comment]
I updated the task to be specific here.

**Comment by ReinerBforartists** [comment]
That's another issue

**Comment by ReinerBforartists** [comment]
I have updated the title too ^^

**Comment by Blenux** [comment]
I know what the issue here can fix.

**Comment by Blenux** [comment]
hmmm was only part of the issue, still have a issue with the toolshelf width stays small when opening in a new window.
![Screenshot 2022-09-22 233152](https://user-images.githubusercontent.com/25260650/191760772-c5826d76-528a-4de8-bf3b-66fc2a5ebe09.png)

**Comment by ReinerBforartists** [comment]
That's another issue. The default snapping point starts without our toolbar. You have to snap int once ...
