### ISSUE TITLE
Armored addon works in Blender 3.4 alpha, but not in Bforartists 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3243]
Usually the cause why an addon does not work can be that we are simply one or two versions ahead. 

The armored toolkit addon though works just fine in Blender 3.4. But fails in Bforartists.

The error message seems to contain a menu name. Possible that we miss this menu in Bforartists. 

Investigating ...

![armored](https://user-images.githubusercontent.com/13919702/191431792-93538e3c-27b6-40a8-87b3-85e7ee65feb0.jpg)

**Comment by ReinerBforartists** [comment]
Yes, We simply miss the menu ...

Now let's have a look if we have a double menu then when we reimplement it.

![selectbytrait](https://user-images.githubusercontent.com/13919702/191433283-15d960bc-256d-42cd-bae6-c7c65fbfd569.jpg)

**Comment by ReinerBforartists** [comment]
-.-

We have invested so much work to have everything top level UI ...

**Comment by ReinerBforartists** [comment]
Okay, it is just this one menu. And just one level deep. So i think the best solution is to really reuse the Blender menu structure here. 

This problem raises the question though what to do with legacy menu entries that exists in Blender, but not longer in Bforartists? Every missing menu is a possible reason why an addon does not start

**Comment by ReinerBforartists** [comment]
Fixed in master

Updating the manual ...

![working](https://user-images.githubusercontent.com/13919702/191437052-90e543d6-9c1a-470f-9bc9-41cf42d8474f.jpg)

**Comment by Draise14** [comment]
Damn, I liked these up a level.... 

Yeah this is a tricky balance with addons. I usually modify the addon to register elsewhere if it comes to this. It is really rare this happens, but it is a common complaint WHEN it happens.

**Comment by ReinerBforartists** [comment]
Yes, tricky one ...
