### ISSUE TITLE
Gap under the toolbar, templates broken

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3245]
When saving the startup.blends with a 1920 x 1080 resolution we get a gap below the toolbar with resolutions that are taller. I use a 1920 x 1200 resolution at my mainscreen. And now i have this gap.

Seems that i have to fix and resave all the layouts at one point ...

![gap](https://user-images.githubusercontent.com/13919702/191796012-be2a0aaf-d6b5-461b-b388-50cc32a7c5a5.jpg)

**Comment by Blenux** [comment]
I'll do some testing today to see if 1440p can help with this if needed, though probably still have issues with other resolutions higher then that.

**Comment by ReinerBforartists** [comment]
Yes, we cannot test nor fix 4K ...

**Comment by Draise14** [comment]
Wasn't this an issue from Blender? We reported it and nothing. So we now only do the layout on a standard HD 16:9 monitor. Users have to manually fix it and save the startup on other dimensions. 

Maybe we can put a note on the editor empty space?

**Comment by ReinerBforartists** [comment]
let's have a look ...

**Comment by ReinerBforartists** [comment]
The 2d animation layout is destroyed. I wonder for how long ...

![2danimation](https://user-images.githubusercontent.com/13919702/192082214-14e88c9c-1e6d-427e-afaf-d48a709ddc40.jpg)

**Comment by ReinerBforartists** [comment]
3.2.2 release was the last working version. Grabbing the startup.blend from here.

**Comment by Blenux** [comment]
I did notice this and thought I might have done it by mistake, but I tried a older build and it was the same, Video Sequencer Template also may need to be fix.

**Comment by ReinerBforartists** [comment]
Am at it ^^

**Comment by ReinerBforartists** [comment]
Sculpting is destroyed ...

**Comment by ReinerBforartists** [comment]
You named it already. VFX is destroyed
![vfx](https://user-images.githubusercontent.com/13919702/192082544-67cfff03-7eab-4049-8727-57a4f54def2c.jpg)

**Comment by ReinerBforartists** [comment]
And Video Editing too. Looks like it's all the same startup.blend instead of having the different template startup.blends. The only one that looked ok'ish was the All. But i better make sure not to miss anything here, and revert it too.

![destroyed](https://user-images.githubusercontent.com/13919702/192082642-25fd686e-b6e9-4c93-9a45-b8850d615505.jpg)

**Comment by ReinerBforartists** [comment]
Next problem. The VFX template refuses to work. I remember that we have one template more than Blender, and think that something broke with the manual merge. Investigating ...

**Comment by ReinerBforartists** [comment]
> I did notice this and thought I might have done it by mistake (sorry if it was), but I tried a older build and it was the same, Video Sequencer Template also may need to be fix.

Before i forget, always make a task then. Better one time too often and a false alarm than to overlook such a biggie here.

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by ReinerBforartists** [comment]
>3

![troublemaker](https://user-images.githubusercontent.com/13919702/192138967-188b8bfd-c45c-4dff-a97d-526f3d353530.jpg)

**Comment by ReinerBforartists** [comment]
This is crazy. When i have a look at the blank template then the toolbar fits. When i add a cube and enter the UV editing template, then the snapping does not fit anymore.

**Comment by Blenux** [comment]
I've been looking into this all day, I've got some info, just writing everything down so I can explain it correctly (though it's getting late so will post when can).

**Comment by ReinerBforartists** [comment]
So you know about it already? :D

I think it's best to make a new issue for this. It seems to have another cause than the initial issue.

**Comment by ReinerBforartists** [comment]
As promised, created the other task. Closing this one.
