### ISSUE TITLE
Update Blender themes

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3250]
We have our own default theme. And so changes at the default Blender theme doesn't automatically arrive at us. 

The Blender Dark and Bright themes are a bit out of sync nowadays. Needs a fix.

![blender](https://user-images.githubusercontent.com/13919702/192483108-6944af7d-73e9-4bbe-bba2-b69970240475.jpg)

![blender2](https://user-images.githubusercontent.com/13919702/192483132-04101e7c-2c61-47d1-960b-cc6a8cf5d5d8.jpg)

**Comment by ReinerBforartists** [comment]
Hm, quite a few changes. But we still miss the yellow text in the dope sheet ...

![yellowmissing](https://user-images.githubusercontent.com/13919702/192485515-885f8807-8ca5-482b-988b-6deb12c9f6df.jpg)

**Comment by ReinerBforartists** [comment]
Ah, appdata content made fun to me here. Fixed in master.

**Comment by Blenux** [comment]
Would it be possible to get the themes names Capitalized like Blender has, looks more cleaner imo.
![bthemes](https://user-images.githubusercontent.com/25260650/193299266-508417b4-323c-4c06-8395-3e95bade7db8.png)
