### ISSUE TITLE
Geometry Nodes - New Face Set Boundaries node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3252]
![image](https://user-images.githubusercontent.com/35357409/192634342-036d5507-1fb1-411f-a92b-3f1bc54f2100.png)

New node, new iconography, add to Add shelf and documentation.

**Comment by ReinerBforartists** [comment]
While at it, fixing different name is face planar ...
![isfaceplanar](https://user-images.githubusercontent.com/13919702/194538984-a7ff91c2-d591-4ea1-bf1e-93d34f7e218b.jpg)

**Comment by ReinerBforartists** [comment]
Code part is fixed. On with the manual.

![facesetboundaries](https://user-images.githubusercontent.com/13919702/194539905-aefa7d10-63bf-44e6-add0-345d42b7bb70.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
