### ISSUE TITLE
Geometry Nodes - New Distribute Points in Volume node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3253]
![image](https://user-images.githubusercontent.com/35357409/192634810-a0f17f81-a007-4068-a34a-9e205b964e53.png)

New Distribute Points in Volume node means new iconography, new entry to the add shelf, and documentation.

**Comment by ReinerBforartists** [comment]
I cannot finish this task at the moment. My python environment is shot down. But the icon was anready finished ...

![VOLUME_DISTRIBUTE](https://user-images.githubusercontent.com/13919702/194691053-553a13b7-008c-421f-9526-73e8f485fc54.png)
![VOLUME_DISTRIBUTE](https://user-images.githubusercontent.com/13919702/194691055-278cf014-ca01-496a-a7fb-a4d175f30030.svg)

**Comment by ReinerBforartists** [comment]
Unassigning.

**Comment by ReinerBforartists** [comment]
Meow?

**Comment by iyadahmed** [comment]
Still having issues with dat file snot generating even after modifying code :/
Unasigning

**Comment by iyadahmed** [comment]
Ok will do

**Comment by ReinerBforartists** [comment]
Excellent. Because i am doomed again, at least when it comes to the icons. It has definitely worked before i have reinstalled Miniconda. But i need Miniconda for my movies. And i don't have the time to reinstall yet again everything from scratch.


![doomed](https://user-images.githubusercontent.com/13919702/195887768-61db232b-6e9b-45c0-b464-c58d38705d8b.jpg)

**Comment by ReinerBforartists** [comment]
Haha, i was in the old branch still where i tested for the other python problem. Phew. And this one still worked with the script that uses Python 2.7x. The branch was from 2021 ... :D

I swear Python will bring me a heart attack one day ...

![working](https://user-images.githubusercontent.com/13919702/195891397-076fbf74-b6b0-451c-b7c5-ee152d637034.jpg)

**Comment by ReinerBforartists** [comment]
I forgot to mention one step. New icons always also needs to go into the file repository. At least the single svg file

https://github.com/Bforartists/files/tree/master/iconset_bforartists_2

I'll do this tomorrow ...

**Comment by ReinerBforartists** [comment]
I see a problem. reopen. The toolshelf needs two entries, not just one. One for the text version, one for the icon version. But will be an easy fix. And the manual needs a new screenshot too.

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/195972570-1b8240ff-fbd0-476d-a9be-47d308d84b0c.jpg)
