### ISSUE TITLE
Image Editor - Mask Mode - Add mask operators to toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3256]
![image](https://user-images.githubusercontent.com/35357409/192802780-823886e6-1d07-48a3-8513-a30e0b36f8cb.png)

Just discovered the power of masks for compositing today... it's really really useful. 

Currently to work masks, you have to either use hotkeys or go into the header repeatedly. These operators could be exposed to a top level to the toolshelf. 

_Can this be done? If so, how can the toolshelf be mode dependent? I might need a bit of guidance how to do this briefly._ 

**Suggested Panels:**
- Transform Panel
- Mask Panel
- Animation Panel
- Handle Type
- Add Tab + Panel

**Comment by ReinerBforartists** [comment]
Postponing for 3.6

**Comment by ReinerBforartists** [comment]
Fixed

![masktoolshelf](https://user-images.githubusercontent.com/13919702/233618442-13f1734f-9133-4e79-95df-e14073eef296.jpg)
