### ISSUE TITLE
Play Rendered Animation - eventual Bug

### ISSUE THREAD

**Issue by pikachu1001000** [Bforartists/Bforartists#3260]
After awhile of previewing my rendered animation by pressing Ctrl F11, it will stop working and produce the error in the title.
Only fix is to restart the program.

Windows 11, Nvidia 3070

![image](https://user-images.githubusercontent.com/35357409/193592706-e05a7fc7-2eb2-4600-9e9a-172b4d99fa70.png)

```
Python: Traceback (most recent call last): File "C:\Program Files\Bforartists 3\3.3.0\3.4\scripts\startup\bl_operators\screen_play_rendered_anim.py", line 163, in execute print("Executing command:\n ", " ".join(quote(c) for c in cmd)) OSError: [WinError 233] No process is on the other end of the pipe
```

**Comment by Draise14** [comment]
Ok, tried to give it a go, let it playback a while without any issue. Looks like it previews from folder your rendered to - you may need to check the image sequence and double check if any files are corrupt. Sometimes a render doesn't go 100% smoothly.

**Comment by pikachu1001000** [comment]
Here's something interesting I found. When I open Bforartist, it also opens a cmd along with it, not sure if this is intentional or not, but regardless, I found if I close it that's when the error starts happening!

**Comment by Draise14** [comment]
The command prompt on load should not be closed. This is what runs both Blender and Bforartists.

**Comment by pikachu1001000** [comment]
> The command prompt on load should not be closed. This is what runs both Blender and Bforartists.

Well, this solves my problem. I just don't remember the command prompt staying open before.

**Comment by ReinerBforartists** [comment]
I cannot reproduce. Question, can this behaviour be repeated in Blender?

**Comment by pikachu1001000** [comment]
> I cannot reproduce. Question, can this behaviour be repeated in Blender?

The cmd remains open in Blender, but when I close it, it closes Blender along with it. When I close the cmd in Bfor it does not close along with it.

**Comment by ReinerBforartists** [comment]
I mean to reproduce the error message. This seems to be the problem :)

Just curious, how do you close the cmd window? The close button is greyed out in Blender and Bforartists since Blender 2.80 from what i remember. You have to use the menu item, which we have hotkeyed in Bforartists with alt f5.



![closebuttungreyedout](https://user-images.githubusercontent.com/13919702/193811888-a5586ed5-4535-4e59-a58c-38ffc00ed08a.jpg)

**Comment by pikachu1001000** [comment]
> I mean to reproduce the error message. This seems to be the problem :)
> 
> Just curious, how do you close the cmd window? The close button is greyed out in Blender and Bforartists since Blender 2.80 from what i remember. You have to use the menu item, which we have hotkeyed in Bforartists with alt f5.
> 
> EDIT, hmm, could also be a Win 11 issue. I have no environment to test, unfortunately. Still Win 10 here. And it will most probably remain this way until Win 10 is EOL.
> 
> ![closebuttungreyedout](https://user-images.githubusercontent.com/13919702/193811888-a5586ed5-4535-4e59-a58c-38ffc00ed08a.jpg)

Closing the cmd in Bfor is what produces the error for me. Very strange it's not greyed out for me. It's not a terrible huge issue, knowing now I just have to leave it open.

**Comment by ReinerBforartists** [comment]
Does Blender also have the x button not greyed out for you?

**Comment by pikachu1001000** [comment]
> 

Blender's cmd x button is not greyed out for me. Could be a Windows 11 thing.

**Comment by ReinerBforartists** [comment]
Many thanks for having a look. Then it's definitely a Win 11 thing with Blender and the X button being not greyed out. I am just if it makes sense to report it to Blender. 

You say the bug itself with the error message just happens with Bforartists, and not with Blender. And so they will simply decline this part as us being responsible for it. And I don't have a Win 11 to test. And i think my other team members neither. The error message itself doesn't make any sense to me neither, Which means there is nothing that we can do at this point, sorry. I'll leave it in Draises hands what to do here.

**Comment by Draise14** [comment]
Hmm.. yeah, not much we can do.. so I'll close for now.
