### ISSUE TITLE
3D View - Object Types Visibility eye icon double entry

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3261]
![image](https://user-images.githubusercontent.com/35357409/194114437-88de4cb1-67be-458e-9fbd-7bdadbbff885.png)

Got a suggestion in Discord:
1. Remove the double entries of the eye visibility icon - redundant and broken imo

_Should this be two tasks? One or both I'd love._ - Split to two tasks

**Comment by ReinerBforartists** [comment]
Yes, sounds like two tasks. So i would make it two.

**Comment by ReinerBforartists** [comment]
Postponing. This should be tackled after the 3.3.1 release.

**Comment by ReinerBforartists** [comment]
Please just one task per task ... ;)

Tackling the double entry ...

**Comment by ReinerBforartists** [comment]
Fixed in master

![double](https://user-images.githubusercontent.com/13919702/195978256-50e2160c-8a3d-4f20-b0c5-223bc1351d7a.jpg)
