### ISSUE TITLE
3D View - Object Types Visibility drop down could have iconography iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3262]
![image](https://user-images.githubusercontent.com/35357409/194213672-be3d453b-a93e-48a2-8f70-114cf097443c.png)

Add obeject type iconography, which I think is sound.

**Comment by ReinerBforartists** [comment]
Postponing. This should be tackled after the 3.3.1 release.

**Comment by ReinerBforartists** [comment]
The icons at the front is something complicated. This whole part is enumerated. It's not that you can simply place a icon in front.

**Comment by ReinerBforartists** [comment]
Let's have a look if there is a solution ...

**Comment by ReinerBforartists** [comment]
So far so good, But we have a width problem. Not enough space left for the text. Investigating ...

![widthproblem](https://user-images.githubusercontent.com/13919702/196136706-15c6cee3-ce77-43f2-a7ee-b75f0006550d.jpg)

**Comment by ReinerBforartists** [comment]
This for the width. Now let's add the correct icons ...

![uiunits](https://user-images.githubusercontent.com/13919702/196139745-4b97df93-337b-46ff-a12c-a70c24199ee4.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/196143524-b405f484-bf0b-4d62-bd6a-3ac87fe00c9e.png)

**Comment by ReinerBforartists** [comment]
Hm, still unhappy with the big gap. But with widht 8 we have cut off text again. Investigating ...

**Comment by ReinerBforartists** [comment]
No, not to improve. So fixed.
