### ISSUE TITLE
Hotkeys - Right Click context menu change to Single click (from double click)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3263]
This year I've had a number of new users, and the usual first thing they request or ask is how to trigger the context menu. Most often they search with a single right mouse click. A user on Reddit also mentioned we are being inconsistent with most software workflow - he has a point. So I did some experimentation and found a solution while still keeping RMB to rotate view.
 
 Here it is working, single RMB click to call the context menu and press and hold to rotate the view with the same RMB. 
![bforartists_GwWme1F4gJ](https://user-images.githubusercontent.com/35357409/194213929-ef6d9365-51c7-4299-a820-64926d6977d6.gif)

**Changes**
![bforartists_sqJ83AhH75](https://user-images.githubusercontent.com/35357409/194213996-5cce5e31-6404-47a7-bb8d-1621c4768674.png)

Where relevant, the call.menu operator for the context menus in all the modes and object types would then need to change and.. viola, context menu with single right click and it would be consistent, more discoverable and... a fullfilled user request for a few.

**Comment by ReinerBforartists** [comment]
Worth a shot.

**Comment by ReinerBforartists** [comment]
EDIT But make sure and test hard that we don't accidentally call the rmb menu all the time.

**Comment by Draise14** [comment]
Ok. Testing. 

1. In viewport and most editors, great. As predicted from other software. The click makes it not trigger easily, since it's not on press. So you have press and release to activate, so no accidentals unless intentional. 

2. In the animation editors, `press `was to place the time cursor. But this usually is done in the header of the timeline in most software, so a compromise to get single `RMB` for context click is to make the cursor placement done by `click+drag`, for easy controlled playback... Not sure if this is ok. If we make the `RMB` context double in the animation/sequencer/clip editors, and the rest not.. it might be inconsistent. But in turn, I feel it's a lot more predictable, contextually editing a keyframe without needing to rely on hotkeys to pull up custom assigned hidden panels or heading to the header to zigzag. To preview frames click and drag the `RMB`. I'll be doing animation next week to double test.

**Comment by ReinerBforartists** [comment]
Postponing. This should be tackled after the 3.3.1 release.

**Comment by ReinerBforartists** [comment]
Draise, do you want to tackle this? I fear to miss too much entries, i don't use BFA as much as you do :)

**Comment by Draise14** [comment]
Yep. I've been testing it. So far so good. Still have to test it more in animation and the VSE. Every where else feels as expected.

**Comment by Draise14** [comment]
Ok, animation editors, it's a little awkward still - placing the cursor with a single right click is a hard habit to change. 3D View though and the VSE (and most other editors) in general though does greatly benefit from the easier context menu. Much more discoverable and useful. 

I am now testing if placing a cursor to location with something else will make sense - most software you use the header exclusively, but it can be ergonomic in the active animation tracks.

**Comment by ReinerBforartists** [comment]
Try to come from the Blender standards.

**Comment by Draise14** [comment]
Ok, Blender standard is.. don't move time cursor in tracks at all, only use header - like in other software.

**Comment by ReinerBforartists** [comment]
Don't overdo. The task was to change the double click to single click. Other changes should imho go into a separate task.

**Comment by Draise14** [comment]
Ok.. that's a wrap for today.. gotta do documentation, and get back to work. I'm back logged still.....

**Comment by Draise14** [comment]
Ah, just to say, the animation in the editor is now `RMB` on `CLICK DRAG` so single click will call the context menu consistently everywhere. No other conflicts found, and have used this setup for a month and half now.
