### ISSUE TITLE
Official Release - 3.3.1

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3264]
It's that time of year again.... so soon - a new release of Blender 3.3.1 LTS means a new release of Bforartists. 

So.. I have organized some tasks to the release project to finish and clean up - and then we can branch, feature freeze and then release. We just finished doing a merge so the release branch and tasks should be done soon. Everything else should be postponed. 

I am unfortunately tied up with work at the moment with no time this weekend to do anything - as I now have a full time employment till the end of the year and two clients still, so two full time jobs - and being recently sick pushed my work back 2 weeks - but I can tie up some loose ends next week hopefully after delivering one of the clients tomorrow....... But my time is... goddamn limited right now. 

With that timing, I am not sure if this will conflict with the next merge and the branching of the official release, since we still have some pending tasks to close that still need to be done. @ReinerBforartists what do you recommend we do concerning timing and the next merge for this release? How are you for time? Would you be able to do this release? 

_I'm debating skipping this release since this is an LTS release and wait for the Blender 3.4 release due to limited time, and do a good new release with a few more substantial updates later..._

**Comment by ReinerBforartists** [comment]
I hear you. 

A point upgrade comes with some vital fixes. So even when there is nothing new from us, there i something new from Blender. So do not skip this release. It would break the promise to deliver a new version with every new Blender version. This costs trust.

I am unfortunately also bound to another job at the moment. I told you this year is to finish my album and to do some other things. And there was a reason why i have given away the leadership, which is still valid. My health makes still trouble. Which will not become any better anymore. I can spend a few hours, no problem. I can just not promise to do all the work. Currently i compile a full release. So preparing the binaries and the installer shouldn't be a problem. 

Fingers crossed that it compiles with the right cuda version though. The other task to create videos for my music has installed me Cuda 11.6, but Blender still uses 11.4 ...

**Comment by Draise14** [comment]
We are far from that point! I will only have this job for 3 months. And with Iyads help and others I do wanna take it places. Can't work without it. 

I will try do a bit today before work with documentation and some tasks. Iyad has the Linux and windows builds going so you don't need to worry about that for now. I got windows going ok here too. 

I guess most help is cleaning up the tracker. I will also go through the commit log to make sure we aren't missing anything.

**Comment by ReinerBforartists** [comment]
At my way in the tracker :)

**Comment by ReinerBforartists** [comment]
Feature freeze! All vital tasks are tackled. I will now start to create the binaries for 3.3.1.

**Comment by ReinerBforartists** [comment]
Release is done. Misses the Mac version. Draise? :)

**Comment by Draise14** [comment]
@seanr looks like we can do another mac build as an official release - when you're around, let us know!

**Comment by Draise14** [comment]
Ok, pushed up some publicity to twitter, reddit, facebook and instagram. Will work on scripting the video today - not a lot to say so should be short.

**Comment by ReinerBforartists** [comment]
No news from sean?

**Comment by Draise14** [comment]
He said he'd be on it after some work things. So he's aware to do it.

**Comment by ReinerBforartists** [comment]
Friends, seriously, it's two weeks now already again.

**Comment by ReinerBforartists** [comment]
I call for a new maintainer at the moment at our download page. At least for this release. We cannot let our users down for weeks.

**Comment by ReinerBforartists** [comment]
Do you want to ask in the discord if somebody has some spare time left? But better try to contact sean beforehand again a last time.

**Comment by ReinerBforartists** [comment]
We still need a new mac maintainer

**Comment by Draise14** [comment]
Got no leads. I will push to the socials.

**Comment by ReinerBforartists** [comment]
Closing. Sean is back, and we have our Mac version available.
