### ISSUE TITLE
Warning on startup

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3266]
```
Warning: TypeError('bpy_struct: item.attr = val: enum "SHOW_ALL" not found in (\'TOGGLE\', \'SHOW_ACTIVE\', \'HIDE_ACTIVE\', \'INVERT\')')
Warning: TypeError('bpy_struct: item.attr = val: enum "SHOW_ALL" not found in (\'TOGGLE\', \'SHOW_ACTIVE\', \'HIDE_ACTIVE\', \'INVERT\')')
```

**Comment by Draise14** [comment]
I see it.

**Comment by ReinerBforartists** [comment]
I fear it O_O

**Comment by ReinerBforartists** [comment]
Investigating

**Comment by ReinerBforartists** [comment]
Sculpting mode, Facesets menu. Investigating further ...

![sculpting](https://user-images.githubusercontent.com/13919702/194694425-51cf7d72-ce63-4bf6-8fac-0fff671a59eb.jpg)

**Comment by ReinerBforartists** [comment]
We have a problem in the last operator ...

![lastoperator](https://user-images.githubusercontent.com/13919702/194694999-5d933c9a-a264-4fd7-ac3d-4edd1d393648.jpg)

**Comment by ReinerBforartists** [comment]
Just to compare, this is the Blender one: 
![last](https://user-images.githubusercontent.com/13919702/194695209-0bb204d5-bcbd-4a76-951d-9553f74700de.jpg)

@iyadahmed i fear this is your department. You have added the second entry, and i have not even an idea what you are trying to achieve here.


![problem](https://user-images.githubusercontent.com/13919702/194695374-cdf0828b-7525-44fe-b59e-413be73fdad3.jpg)

**Comment by ReinerBforartists** [comment]
And the problem itself is more complicated than thought. Clicking in the tool shelf at Toggle Visibility crashes to desktop. And the last operator shows four possible entries. The Blender menu just two. We have already all four entries in the sidebar. But not longer in the Face Sets menu. So we need to add them back...


![sgaodhijüfsa](https://user-images.githubusercontent.com/13919702/194695785-db35c55b-67b9-40da-b5ec-314572816124.jpg)

**Comment by ReinerBforartists** [comment]
We miss something here. Using the show hide tools from the sidebar crashes to desktop now.

**Comment by ReinerBforartists** [comment]
Cool, it crashes from the menu too \o/

**Comment by ReinerBforartists** [comment]
Hm. Menu content is showing again. But now we have the same hotkey for Invert and Show.

![hotkey](https://user-images.githubusercontent.com/13919702/194696532-ef8ef6d8-bf1f-4c55-b79d-390e22c72ca4.jpg)


And we have the crash.

Oh, and the console warning at startup is still there :D


![console](https://user-images.githubusercontent.com/13919702/194696541-3de1144d-bdfb-4456-b501-c57596794767.jpg)

**Comment by ReinerBforartists** [comment]
Ah, now it works. Remains the crashbug and the hotkeys.
![fun](https://user-images.githubusercontent.com/13919702/194697225-2fd2322c-6446-494e-80b1-3c96fdec3be7.jpg)

**Comment by ReinerBforartists** [comment]
```
# Blender 3.4.0, Commit date: 2022-10-07 22:39, Hash 67cc5450af8b
bpy.ops.mesh.primitive_cube_add(size=2, enter_editmode=False, align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))  # Operator
bpy.ops.sculpt.sculptmode_toggle()  # Operator
bpy.ops.sculpt.face_set_change_visibility(mode='INVERT', mode='INVERT')  # Operator

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF7AB172147
Exception Module      : bforartists.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000000


Stack trace:
bforartists.exe     :0x00007FF7AB172110  SCULPT_face_set_visibility_set E:\bforartists\Bforartists\source\blender\editors\sculpt_paint\sculpt.c:378
bforartists.exe     :0x00007FF7AB1001D0  sculpt_face_sets_change_visibility_exec E:\bforartists\Bforartists\source\blender\editors\sculpt_paint\sculpt_face_set.cc:920
bforartists.exe     :0x00007FF7AB100540  sculpt_face_sets_change_visibility_invoke E:\bforartists\Bforartists\source\blender\editors\sculpt_paint\sculpt_face_set.cc:962
bforartists.exe     :0x00007FF7AA805E20  wm_operator_invoke E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm_event_system.cc:1446
bforartists.exe     :0x00007FF7AA8054D0  wm_operator_call_internal E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm_event_system.cc:1652
bforartists.exe     :0x00007FF7AA808400  WM_operator_name_call_ptr_with_depends_on_cursor E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm_event_system.cc:1891
bforartists.exe     :0x00007FF7AB230F50  ui_apply_but_funcs_after E:\bforartists\Bforartists\source\blender\editors\interface\interface_handlers.c:1018
bforartists.exe     :0x00007FF7AB23C810  ui_handler_region_menu E:\bforartists\Bforartists\source\blender\editors\interface\interface_handlers.c:11408
bforartists.exe     :0x00007FF7AA804940  wm_handlers_do_intern E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm_event_system.cc:3217
bforartists.exe     :0x00007FF7AA803D70  wm_handlers_do E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm_event_system.cc:3337
bforartists.exe     :0x00007FF7AA80A2E0  wm_event_do_handlers E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm_event_system.cc:3928
bforartists.exe     :0x00007FF7AA7F0090  WM_main E:\bforartists\Bforartists\source\blender\windowmanager\intern\wm.c:643
bforartists.exe     :0x00007FF7A98C1320  main E:\bforartists\Bforartists\source\creator\creator.c:580
bforartists.exe     :0x00007FF7AFB33C00  __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
KERNEL32.DLL        :0x00007FFD44B77020  BaseThreadInitThunk
ntdll.dll           :0x00007FFD465C2680  RtlUserThreadStart
```

**Comment by iyadahmed** [comment]
I didn't add anything, it must have resulted from the merge

**Comment by ReinerBforartists** [comment]
Merges are evil !

**Comment by ReinerBforartists** [comment]
Which part shall we keep?

**Comment by ReinerBforartists** [comment]
The show_all error happens also in Blender. Reported: https://developer.blender.org/T101694

**Comment by ReinerBforartists** [comment]
Cannot catch the crash. On with at least a fix for the hotkey.

**Comment by ReinerBforartists** [comment]
I have removed our code now. And added the one liner tooltip to the original operator.

Remains the crash. I think we should make a new task for it.

**Comment by ReinerBforartists** [comment]
This task is fulfilled. I have separated the crash bug
