### ISSUE TITLE
Missing icons after merge

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3275]
Blender added two new icons for Grease Pencil modifiers, build fails,
The envelope and outline modifier,
the solution is to either create alternative icons or use existing alternative icons, the non gpencil envelope modifier, and the ICON_OUTLINE icons seem suitable

**Comment by ReinerBforartists** [comment]
Yes, use existing icons where possible. They alread exists. And we are not bound to Blender here. When we add new icons, then we might create unused old icons. And we're wasting space and time.

**Comment by ReinerBforartists** [comment]
One note, you commit a fix here for a merge that is not finished yet. Means this code does not exist in the repo yet. Such things are usually part of the merge. And doesn't require an extra task. Since the job of the merge is to merge the code bases and make the result compile.

**Comment by iyadahmed** [comment]
I didn't, all merged into sync blender master now, but fails to merge with master will fix it today

**Comment by ReinerBforartists** [comment]
O_O
It works in the sync_blender_master but fails in the master? Shouldn't be possible, since the first thing you do is to merge the master into sync_blender_master. And when it works in the sync_blender_master then it should also work in the master. I scratch my head here :D

**Comment by ReinerBforartists** [comment]
> I didn't, all merged into sync blender master now, but fails to merge with master will fix it today

Totally forgot, I did a commit with a change at space_view3d.py. Is this the trouble maker? Python files usually doesn't prevent from compiling though. 

https://github.com/Bforartists/Bforartists/issues/3262
