### ISSUE TITLE
Saving startup file removes toolbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3276]
I stumbled across a very very unfunny bug. When saving the startup.blend, then the toolbar is removed, and the editor type switches to info editor. And it is not to convince to start with the toolbar anymore.

We eagerly need to find out what is going on here. That's a showstopper bug.

![savestartupfiledilemma](https://user-images.githubusercontent.com/13919702/197349692-b46b348b-cb1e-4e51-b69c-d3ac935db1f3.jpg)

**Comment by ReinerBforartists** [comment]
Has the enumeration of the editors changed recently? We had this crash trouble with the toolbar enumeration before ...

**Comment by ReinerBforartists** [comment]
Bforartists 3.3.0 is fine. Bforartists 3.3.1 is troubled.

**Comment by Draise14** [comment]
Wait... This is a bug? I was noticing this just yesterday. 

I'll try reproduce surely.

**Comment by ReinerBforartists** [comment]
Yes it is. It worked in 3.3.0.

**Comment by ReinerBforartists** [comment]
This kind of bugs is why it is so important to read what arrives new with the newest merge, go carefully through the commits in the logs, and keep your eyes open for everything that could affect our functionality.

**Comment by Draise14** [comment]
I went through the commit logs from about 3 weeks back, couldn't find anything obvious. I did find a lot of things I hadn't put inot the tracker though.

**Comment by Draise14** [comment]
Gonna call in the big guns. @iyadahmed this one has a bounty 🥇

**Comment by iyadahmed** [comment]
I have to fix this asap, I'll be home very shortly

**Comment by ReinerBforartists** [comment]
I`ll help out in the tracker when these two showstopper bugs are tackled. A commit in the current state could be in the way for them.

**Comment by ReinerBforartists** [comment]
Investigated a bit while my pc is busy with rendering video images ...

source\blender\blenkernel\intern\screen.c has changed. It misses the whole else if list with all the editors now. Find out the commit in screen.c who changed this, and we might have our trouble maker.


![troublemaker](https://user-images.githubusercontent.com/13919702/197481981-8957847d-cd7f-4d92-a0eb-1ca8846c9b96.jpg)

**Comment by ReinerBforartists** [comment]
Here it is. The method has changed. Away from spaghetti brain towards what is known as self-managing code. Which is a good thing. The consequence is though, we now need to modify the files for our space_toolbar editor in 

\source\blender\editors\space_toolbar

The changes in the other editors should tell us how to do it.

![troublemaker](https://user-images.githubusercontent.com/13919702/197483552-b9801d28-1d8d-4cdc-a0f3-c30283c3ed66.jpg)

**Comment by ReinerBforartists** [comment]
How high is the bounty ? :D

**Comment by ReinerBforartists** [comment]
:D

**Comment by Draise14** [comment]
Yeah, pinged Iyad this morning, I think he has started Uni again, and I'm pending a payment to sponsor this more with the bounty. But he's working on it. @iyadahmed keep us posted on progress!

**Comment by ReinerBforartists** [comment]
Problem here is, the two showstopper stops me from helping. And i am so impatient sometimes. Sorry for nagging :)

**Comment by Draise14** [comment]
Yeah, I'm in the same boat, I'm working in 3.3.0 because of this.

**Comment by iyadahmed** [comment]
> Yeah, pinged Iyad this morning, I think he has started Uni again, and I'm pending a payment to sponsor this more with the bounty. But he's working on it. @iyadahmed keep us posted on progress!  

Will do, no worries not sure why a merge didn't fix it

**Comment by ReinerBforartists** [comment]
The change slipped through, as simple as that. That's development :)

**Comment by Draise14** [comment]
The merge and this fix is delayed. Iyad still has no internet, the ISP is failing.

**Comment by ReinerBforartists** [comment]
You make bunny cry :(

**Comment by Draise14** [comment]
Ok, Iyad found a way to work the internet a bit. Hopefully progress soon!

**Comment by ReinerBforartists** [comment]
Fingers crossed !

**Comment by Draise14** [comment]
hell yeah, I could dance!

**Comment by ReinerBforartists** [comment]
*dance*
