### ISSUE TITLE
Geometry Nodes - New Self Object Node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3277]
![image](https://user-images.githubusercontent.com/35357409/197363045-6221afea-c35c-471f-a7c5-703203d3fce2.png)

Another new geometry nodes, this time to get the self object. Add to the node shelf, documentation and iconography must also be done. 

Location: Geometry Nodes Editor>Add>Input

Documentation Task:
https://github.com/Bforartists/Manual/issues/358

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/200186018-bca259b0-d96f-47ee-b3d9-9ec2b0fd7bd6.jpg)
