### ISSUE TITLE
Geometry Nodes - remove "transfer attribute" node for to 2 new nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3278]
![image](https://user-images.githubusercontent.com/35357409/197363283-34de5ad8-5f1d-460b-961d-a2f4939b1ce7.png)

Old node is now two new nodes. Requires iconography, documentation, and update to the toolshelf. This also needs removing an old attribute node. 

Location: Geometry Nodes>Add>Geometry

Nodes:
- Sample Index
- Sample Nearest

Former location and node to be removed: Add>Attribute>Transfer Attribute
![image](https://user-images.githubusercontent.com/35357409/197363313-2c53d269-2182-49a1-8ee0-13921e10af1f.png)

Relevant Documentation Task
https://github.com/Bforartists/Manual/issues/359

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/200260165-64e9fa88-5147-4904-879e-3929f7913618.jpg)
