### ISSUE TITLE
Geometry Nodes - New Sample Nearest Surface node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3279]
![bforartists_2vOdCvWRbl](https://user-images.githubusercontent.com/35357409/197363505-aca74dd0-2391-4fb7-a1ca-4ee3ef3f79d7.png)

New node, new iconography and documentation and feature in the add toolshelf. 

Location: Geometry Nodes>Add>Mesh

Relevant Documentation 
https://github.com/Bforartists/Manual/issues/360

**Comment by ReinerBforartists** [comment]
Merged into Geometry Nodes - New Sample UV Surface node #3282
