### ISSUE TITLE
Geometry Nodes - New Set Curve Normals node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3280]
![image](https://user-images.githubusercontent.com/35357409/197363660-878af462-262f-4dd2-9a7a-02d792d8a035.png)

New node, new documentation, iconography, and feature in the add shelf.

**Location**
GeometryNodes>Add>Curve

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/200166924-005eb458-512f-4af6-9b3b-4f7c176d9f82.jpg)
