### ISSUE TITLE
Geometry Nodes - New Sample UV Surface node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3282]
![PowerToys_akm9bVtkre](https://user-images.githubusercontent.com/35357409/197363953-f08be3bf-2733-4546-a614-4a2887414030.png)

New node, new documentation, iconography, and feature in the add shelf.

**Location:**
Geometry Nodes>Add>>Mesh

Relevant Documentation Task
https://github.com/Bforartists/Manual/issues/363

**Comment by ReinerBforartists** [comment]
Will also tackle Nearest Surface in this task.

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/200163011-e4675191-6a77-4a2e-acd6-976e1616d66a.jpg)
