### ISSUE TITLE
User Preferences -Input - Touchpad + NDOF panel - Aligh props left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3284]
![image](https://user-images.githubusercontent.com/35357409/197364280-88d34ce7-ba88-48b6-a602-8800d091028f.png)

On the wrong column. Shift left.

**Comment by ReinerBforartists** [comment]
The panel below the Touchpad is the more interesting one. So i extended this task.

![NDOF](https://user-images.githubusercontent.com/13919702/199184818-711c0794-46ab-424e-b0fa-80497b4a5642.JPG)

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/200108527-c6f05874-c45d-43cd-b3cc-ce89a34ace89.jpg)
