### ISSUE TITLE
Nodes - New Duplicate Linked operator hotkey ALT+D

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3286]
![bforartists_0jIYxGt2ZZ](https://user-images.githubusercontent.com/35357409/197365307-dacffb1e-b85d-41dc-b829-cbfa800ff3a9.png)

New hotkey should be added to the node editors to duplicate linked. `ALT+D`

**Comment by ReinerBforartists** [comment]
Mh, that's a hotkey confict. Now Detach does not work anymore :)

Reporting to Blender.

![keyconflict](https://user-images.githubusercontent.com/13919702/200041838-b518f30d-0629-43af-ba55-51596b4044c5.jpg)

**Comment by ReinerBforartists** [comment]
Reported https://developer.blender.org/T102276

**Comment by ReinerBforartists** [comment]
Blender devs have removed the hotkey from the detach item, and added it to the duplicate linked menu item. So i guess we should do the same. Since we face the same issue like them, we run out of useful hotkeys in this area.
