### ISSUE TITLE
Grease Pencil - Outline Modifier display broken

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3288]
When i create a grease pencil in Blender, and add the outline modifier, then i have immediately a result displayed. 
Not in Bforartists. Needs toying around with render settings and rendering until the outline shows. Haven't found out yet what exactly triggers the draw then.

![update1](https://user-images.githubusercontent.com/13919702/199203195-42d498b1-ecdc-4b6d-9ce1-1fc87e23dc49.jpg)

![update2](https://user-images.githubusercontent.com/13919702/199203209-70360c3a-2b4e-44f2-bd48-461eaf31ee73.jpg)

**Comment by Draise14** [comment]
Cannot reproduce. You have to select all the strokes you want to outline before using the outline operator. 
Concerning the outline modifier, it also works immediately on my end. 

![image](https://user-images.githubusercontent.com/35357409/199572554-52c3f208-65da-4c20-ae52-c7fd8e684764.png)
![bforartists_r2iRHP29V1](https://user-images.githubusercontent.com/35357409/199572588-bdc53519-5a92-4549-8b88-5864899074ca.gif)
![bforartists_KiABMmBQlI](https://user-images.githubusercontent.com/35357409/199572592-5c7834e2-d03a-4ade-af6c-f4b765a9d0c2.gif)

**Comment by ReinerBforartists** [comment]
I do the same steps than in Blender, but in Bforaritsts the outline stroke does not display then. Something is different here.

**Comment by Draise14** [comment]
The default outline is 1px in Bforartists, maybe that's it? The gifs show that it is working

**Comment by ReinerBforartists** [comment]
No. This is not what i mean. I will make a video tomorrow.

**Comment by Draise14** [comment]
You do have to be aware the the GP outline modifier is to the active camera view, not the viewport angle. So it might look broken at certain angle unless viewed from camera.

**Comment by ReinerBforartists** [comment]
Here's the video: 

https://cloud.bforartists.de/index.php/s/qif4MBSFPymribM

**Comment by ReinerBforartists** [comment]
Crazy :/

But in the videos you can see the trouble that i have.

**Comment by Draise14** [comment]
Yeah, I don't know what's up there.. Maybe it's a CUDA version issue we used to compile? Blender has a different one? On your card it caused the issue due to that maybe?

 I'll try it on my laptop just to make sure it's not just my main machine.

**Comment by ReinerBforartists** [comment]
I don't compile with Cuda at all for the build that i use here. And Blender works just fine at the same pc. Hmm.

**Comment by Draise14** [comment]
Confirmed, both the Laptop and my main machine work as intended based on your Blender recording, immediate feedback.

**Comment by Draise14** [comment]
I'll try test with a Lite build, that won't have some of the big dependencies compiled in.

**Comment by ReinerBforartists** [comment]
I hate such bugs ^^

**Comment by ReinerBforartists** [comment]
Tested it at my VM. But the graphics solution in there hates grease pencil strokes ^^

![failed](https://user-images.githubusercontent.com/13919702/200040133-e540bd47-ee7f-4c1c-81c9-7670ad1ca5e9.jpg)

**Comment by ReinerBforartists** [comment]
> Confirmed, both the Laptop and my main machine work as intended based on your Blender recording, immediate feedback.

Try the latest devbuild. It has for me the same problem. No immediate update. Then we know if it is a problem at my pc, or a problem with compiling at my pc. In the first case it just affects me.  In the latter case all users ...

https://www.bforartists.de/data/dev/devbuild-22-10-2022.zip

**Comment by ReinerBforartists** [comment]
Poke !

**Comment by iyadahmed** [comment]
Still outside

**Comment by ReinerBforartists** [comment]
No hurry. The bugs doesn't run away :)

**Comment by ReinerBforartists** [comment]
> Try the latest devbuild. It has for me the same problem. No immediate update. Then we know if it is a problem at my pc, or a problem with compiling at my pc. In the first case it just affects me. In the latter case all users ...

Somebody finds the time to test it?

**Comment by Draise14** [comment]
I have tested latest builds, masters, devbuilds, releases, on main PC and Laptop - cannot reproduce. I have even built a lite build without CUDA and a no-cycles build - cannot reproduce.

**Comment by ReinerBforartists** [comment]
Yes, my card is also pretty new now. A Nvidia 3060 TI. Maybe that's where the issue comes from. I still work with Cuda 11.4. But Blender too. And Blender works just fine here. It remains a riddle.

I'm running out of ideas here. Sometimes you simply can't find a solution.

**Comment by Draise14** [comment]
Found a clue:

The factory default scene carries something wrong, because my factory default is fine, but not the inbuilt one. 

To fix, unhide camera and light, and save startup again. Reload the new startup.blend with a new scene or session, test.. it will work.

**Comment by ReinerBforartists** [comment]
Woah, what a catch. But we cannot unhide camera and light. We have hidden it away since it is to 99% in the way :)

**Comment by ReinerBforartists** [comment]
There is still something odd. I can in Blender completely remove camera and light, and the display is still not broken.

**Comment by ReinerBforartists** [comment]
Hmm. In Blender when i remove the camera and create the outline afterwards then the outline does not show. And when i create the outline and remove the camera, then the outline is still there. 

I think i gonna report this :)

**Comment by ReinerBforartists** [comment]
Recreating the camera seems to do the trick. It can then remain off. But with a new camera object in the default files our problem seems to be gone. I have to compare the settings. To replace every camera in all our workspace would be a killer job ...

Nevertheless gonna report the problem to Blender. It should work with the viewport camera alone.

**Comment by ReinerBforartists** [comment]
> The factory default scene carries something wrong, because my factory default is fine, but not the inbuilt one.

May i remind to always put the appdata folder out of the way when testing? :)

**Comment by ReinerBforartists** [comment]
Hm. Settings of a new created camera and the old camera from our startup files are identical. Let's have a look how much hassle it is to replace the camera in all workspaces ...

**Comment by ReinerBforartists** [comment]
It is how you create the camera. From the toolbar, or from the add menu. This is crazy stuff O_O

When i empty the scene, add a camera from the toolbar, add a grease pencil, then the outline will not work.
When i empty the scene, add a camera from the add menu, add a grease pencil, then the outline works.

The settings and the python command is the very same from what i can see. 

Related: Camera creation from add menu versus from toolbar #3304

**Comment by ReinerBforartists** [comment]
... and when i save and recompile the startup file with the camera created from the add menu, then we are back at position zero. No outline -.-

**Comment by ReinerBforartists** [comment]
I managed to recreate the problem in Blender \o/

Second report is at its way.

**Comment by ReinerBforartists** [comment]
Second report: https://developer.blender.org/T102375

**Comment by Draise14** [comment]
Re :
> Second report: [developer.blender.org/T102375](https://developer.blender.org/T102375)

Ah, another clue. The outline won't work till you have set the second duplicated camera as the active camera. The outline modifier needs an active camera. The viewport is never the active camera in the scene, so the outliner won't work till it has an existing active camera set. This would be true of the default startup too I think, a hidden camera or the scene settings may not have the camera as active.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/200835179-313ea92c-6b86-4692-8182-4f1d3ebb4ec4.png)

Sure enough, the factory default has no active camera, the outliner modifier won't work without it.

**Comment by ReinerBforartists** [comment]
Ah, so that's the trick 

It remains a usability problem though. How can the user know that he needs a active camera to get this modifier to work?

**Comment by Draise14** [comment]
Maybe in tooltip or a note in the modifier panels?

**Comment by Draise14** [comment]
Yeah, I think a redesign might be a bit much, the lineart modifier also works exclusively by active camera too.

**Comment by ReinerBforartists** [comment]
Yikes. 

Okay, the first report is already closed as works as designed. Since the modifier needs a camera. Let's have a look what happens with the second report.

Furthermore, the fix here is to save the startup.blends with setting the camera as the active one in the Scene properties, right? Let me check this ...

**Comment by ReinerBforartists** [comment]
Manual is updated. 

This commit brings the active camera to all of our templates. It is still inactive. But outline creation works.

Question, shall we have a look if we can improve the tooltip too? Or call this job a day and close the issue?

![outlinenotshowing](https://user-images.githubusercontent.com/13919702/200898547-6d5da415-44d5-4d33-aa2f-3205656846b5.jpg)

**Comment by ReinerBforartists** [comment]
Okay, improved the tooltip now too.  Fixed.

Now a little manual update, the outline tool ...

![outline1](https://user-images.githubusercontent.com/13919702/200903474-947748bc-8971-4651-a90a-e667cab6414c.jpg)

![outline2](https://user-images.githubusercontent.com/13919702/200903486-d0b31c9e-db46-49c5-857d-3db51524a808.jpg)
