### ISSUE TITLE
Ubuntu fails to compile

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3292]
I have still the problem that i cannot compile at Ubuntu. And the error is more than cryptic to me.

![ubuntuproblem](https://user-images.githubusercontent.com/13919702/199665842-0fbc6913-f194-4261-8f93-992990558c72.jpg)

**Comment by ReinerBforartists** [comment]
Let's have a closer look here. We need a devbuild at the weekend ...

**Comment by ReinerBforartists** [comment]
Spotted a difference in the file. 

![difference](https://user-images.githubusercontent.com/13919702/199668601-1b9764d8-99a8-40dc-b847-665d90efabe8.jpg)

**Comment by ReinerBforartists** [comment]
Narp. Not the trouble maker.
![nope](https://user-images.githubusercontent.com/13919702/199668934-0b382f50-9137-4551-8d2c-99e832d3540c.jpg)

**Comment by ReinerBforartists** [comment]
Yet another one of those mysterious code differences. And not the only one in this file. We eagerly need to do a code comparison. Something is miserably wrong here.

![wrong](https://user-images.githubusercontent.com/13919702/199669913-04f78756-d2c4-4865-ac68-c4bb7a41910c.jpg)

**Comment by ReinerBforartists** [comment]
Still not the cause. Unfunny.
![sheesh](https://user-images.githubusercontent.com/13919702/199670604-c32e6ae2-65b1-4952-8327-3c448f1d0e88.jpg)

**Comment by ReinerBforartists** [comment]
I will stop here now, do the big code comparison, fix the differences, and afterwards return to this problem. Chances are that this issue is fixed then. 

Nevertheless, here the cmakeerror.log and cmakeoutput.log

[CMakeError.log](https://github.com/Bforartists/Bforartists/files/9926573/CMakeError.log)
[CMakeOutput.log](https://github.com/Bforartists/Bforartists/files/9926576/CMakeOutput.log)

**Comment by ReinerBforartists** [comment]
Not fixed by doing the general code comparison. 

@iyadahmed, could you please check if it compiles for you at linux?

**Comment by iyadahmed** [comment]
Yes it compiles here
Ubuntu 20.04

**Comment by ReinerBforartists** [comment]
Hmmm. What cmake version do you use? I have 3.16 here still.

**Comment by iyadahmed** [comment]
Not sure 😅 away from home now, but i think it is cmake 3.2x

**Comment by ReinerBforartists** [comment]
Thanks :)
It's definitely not cmake that is the problem though. Installed 3.2.4 ...
![notcmake](https://user-images.githubusercontent.com/13919702/199713395-1c666db1-5af7-4909-a5ea-e3352e879a94.jpg)

**Comment by ReinerBforartists** [comment]
I will have a look to clone Blender in the evening, and see if it works.

**Comment by ReinerBforartists** [comment]
Houston we have definitely a problem. Github actions Ubuntu fails with the same error. Testing Blender now ...

![problem](https://user-images.githubusercontent.com/13919702/199782353-81e42611-e481-4bc6-bf8d-30c4fff295b0.jpg)

**Comment by ReinerBforartists** [comment]
And Blender fails too. I start to wonder how it can work for you O_O

Let's try Ubuntu 22. Maybe we have reached EOL here with Ubuntu 20 ...

![blender](https://user-images.githubusercontent.com/13919702/199785786-4c5ce1e9-8b94-4532-8869-8d0a9d15e169.jpg)

**Comment by ReinerBforartists** [comment]
Asking at Blender developer for help ...

**Comment by ReinerBforartists** [comment]
LazyDodo means we should try WITH_GHOST_WAYLAND=Off . That's the next thing i have a look at. Still at cloning the repo at Ubuntu 22 ...

**Comment by iyadahmed** [comment]
as said Ubuntu 20.04 works
we jsut need to install the extra dependencies
from blender website
```sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
```

and yess turning off wayland options will make the error go away, because then it dosn't need the extra deps
https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu

**Comment by ReinerBforartists** [comment]
You mean! Now you tell me :D

Didn't know about the extra dependencies. Thanks for the hint :)
Just not sure if i shouldn't wait for the fix now.

**Comment by iyadahmed** [comment]
I just found out :sweat_smile:

**Comment by ReinerBforartists** [comment]
Let's wait for the official fix. In the meantime i will use wayland off for the devbuild.

**Comment by iyadahmed** [comment]
it is the official fix, there's no bug :), they updated their official guide
![image](https://user-images.githubusercontent.com/25552173/199794417-9ebdd18a-c0be-41f4-acc7-e679bf00778f.png)

**Comment by iyadahmed** [comment]
what we were missing is libxkbcommon-dev which is right there in the guide

**Comment by ReinerBforartists** [comment]
Then this must have changed. I use my Ubuntu since eons now, and it never moaned about this missing bit.

Hmm, when it is documented then i should try it. Ubuntu 22 runs through without error at the moment. 

But we also need to update our github actions build then.

**Comment by iyadahmed** [comment]
yes it changed, ubuntu 22 worked because it has those deps installed :(
we just need to install the deps on 20.04 :(

**Comment by ReinerBforartists** [comment]
:/
Missing bit goes here?

![missingbit](https://user-images.githubusercontent.com/13919702/199795963-23a89df5-f0c5-4557-be09-18a10bb89b22.jpg)

**Comment by iyadahmed** [comment]
yes

**Comment by iyadahmed** [comment]
I would just copy the exact commands from here
https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu

**Comment by ReinerBforartists** [comment]
Is now compiling here. Issue resolved. Thanks for help :)

**Comment by ReinerBforartists** [comment]
Narp, the github actions part is not resolved -.-

It fails.

**Comment by ReinerBforartists** [comment]
Curious enough still the same error it seems. I will have another look tomorrow.

**Comment by ReinerBforartists** [comment]
I cannot find out how to make a new run. When i repeat the old run then it uses still the old xml file with the missing dependencies.

**Comment by ReinerBforartists** [comment]
New action is running. Let's see :)

**Comment by ReinerBforartists** [comment]
Works now. The label at the front page will update with the next regular run, which is sunday night from what i remember. I have run it at a branch ...

So closing.
