### ISSUE TITLE
Geometry nodes - add back the tooltip title and node info to the tool tips in the tool shelf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3299]
Merge regression. In previous versions we had a "Adds a xxx geometry node" in every tooltip since in the sidebar the tool name does not show. And the nodes showed the tool name. I guess this gots killed with one of the merges when Blender finally decided to use tooltips in the nodes. Now we are back to the old Blender way. No tooltip title, no information what kind of node gets added.

In BFA 3.3.0 it looked like this.

![working](https://user-images.githubusercontent.com/13919702/200166674-69a14df8-1546-4eef-a38a-e1bc1e49390a.jpg)

Now we are back to this:

![addback](https://user-images.githubusercontent.com/13919702/200166533-40867c24-ab21-4c4c-b043-ec08459cb860.jpg)

**Comment by ReinerBforartists** [comment]
Hm, no idea at which point the title gots lost, and with what change. @iyadahmed do you have an idea here?

**Comment by iyadahmed** [comment]
No idea will check asap, currently out of house

**Comment by ReinerBforartists** [comment]
Ah wait, the title was missing before already with the icons. This drama was never fixed :D

The current code grabs the button label. And when there is no label then there is no tooltip title. Adding back our subline with "Adds a xxx geometry node" is the current workaround. 

Please be careful with the merges not to remove it again. This job did hurt my neck ^^


![colinfo](https://user-images.githubusercontent.com/13919702/200293041-170be139-e656-453e-900d-b994cc61891e.jpg)


![fix](https://user-images.githubusercontent.com/13919702/200293064-e502d3f8-60e0-42df-9abb-2b9c1e447c99.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
