### ISSUE TITLE
Crash with Dyntopo in 3.3.1

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3302]
I have a user report that Dyntopo in version 3.3.1 crashes for him while Blender works fine.

Needs investigation.

**Comment by ReinerBforartists** [comment]
Is reproduceable in 3.3.1. First i had some weird display issues. The second attempt crashed to desktop. 

It is back working in the latest devbuild. So it is already fixed. The question is if this glitch makes a new BFA point upgprade necessary.

**Comment by ReinerBforartists** [comment]
> It is back working in the latest devbuild. So it is already fixed. The question is if this glitch makes a new BFA point upgprade necessary.

@Draise14 ?

**Comment by Draise14** [comment]
Yeah that's two showstopper bugs fixed... I vote another point release.. I can try make time for it. I'm trying to sort better habits in the morning for my two jobs. 

Counter argument. 3.4 is in beta and has a release candidate. May come soon?

**Comment by ReinerBforartists** [comment]
Wasn't it start of december?

**Comment by ReinerBforartists** [comment]
Ah, didn't see the official beta at builder. I would say we cancel the idea of a point upgrade. And let's close this issue then. It is resolved.
