### ISSUE TITLE
blender_theme_as_c.py - creation of userdef_default_theme.c fails

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3303]
We currently cannot create a new userdef_default_theme file anymore since the creation with the python file fails.

source\tools\utils\blender_theme_as_c.py

Related: Dopesheet - Grease Pencil Object - Grease Pencil track theme bug - theme creation fails #3240

![195804800-21b46150-a9d8-496c-a1a2-1fc1c8b99c10](https://user-images.githubusercontent.com/13919702/200517761-37d8ada7-10c5-46bd-a90c-f17acfd1438a.jpg)

**Comment by ReinerBforartists** [comment]
Reported https://developer.blender.org/T102351

**Comment by ReinerBforartists** [comment]
Bug is fixed, will come with the next merge

**Comment by iyadahmed** [comment]
Yesss

**Comment by ReinerBforartists** [comment]
Is working again. I took the opportunity to update the userpref.blend in the tools/utils folder ...
