### ISSUE TITLE
Duplicate code in release/scripts/startup/bl_ui/properties_paint_common.py

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3315]
![image](https://user-images.githubusercontent.com/25552173/203445309-d8e4a019-f399-4f64-9868-b2bdb23b17fd.png)

**Comment by ReinerBforartists** [comment]
First let's find out where this prop shows. Then you can say which one is double.

**Comment by ReinerBforartists** [comment]
One thing i can say is, there was just one prop before the merge. So this change was introduced by the current merge.

![justone](https://user-images.githubusercontent.com/13919702/203504039-4647103a-7a58-4df7-9e42-c28cc342dee0.jpg)

**Comment by ReinerBforartists** [comment]
First, @iyad, there is just one version of the prop left at the moment. 

Cavity and Cavity Inverted shares the same settings, that's why it looks a bit confusing. But there is no double entry to see.

So nothing to fix. Closing.
