### ISSUE TITLE
Asset Browser - Activate default library addon and de-activate the minilightlib and turn off Material Library VX

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3316]
Initial issue: Error when matlib addon is loaded for first time.

Deactivate the Matlib and minilightlib
Activate the Default Asset LIbrary

**Comment by ReinerBforartists** [comment]
It's by design. And it is not about the first time the addon is loaded, but the path must be created when you run BFA the first time. 

The addon relies at the content in the appdata directory. And wants to place its libs there. But the directory is not created yet. And so the addon moans about the missing path. Blender has the same addon included, but not activated by default. Else they would have the same problem.

**Comment by Draise14** [comment]
This addon could also be legacy since the materials are now in the default asset library.

**Comment by ReinerBforartists** [comment]
We thought about it, yes. But the asset manager is not on by default yet, right?

**Comment by Draise14** [comment]
The default library no, but the asset browser is not experimental for materials, objects, collections, poses and world assets. 

Another addon minilight library also would be redundant if the default library addon was turned on by default.

**Comment by ReinerBforartists** [comment]
Seems we have a task then :D

**Comment by Draise14** [comment]
Sure!

**Comment by ReinerBforartists** [comment]
Do you want to have the pleasure? :)

**Comment by Draise14** [comment]
I'll try do it this evening after dinner.. Long days anyways.

**Comment by ReinerBforartists** [comment]
Okay :)

The by default activated addons are defined in source\blender\blenkernel\intern\blendfile.c

![defaults](https://user-images.githubusercontent.com/13919702/203610323-9628b0f6-41f3-43e1-a6e9-bed5989ce84f.jpg)

**Comment by Draise14** [comment]
Thank you, should be a quick commit after dinner. I'll try do the other hotkey ones in another pull/branch too.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/203820815-dbc61466-ac43-40e0-a076-a55ade1cbd10.png)

Ok, pushing now.
