### ISSUE TITLE
Asset Browser - Make the dragdrop modes dropdown toggles into buttons instead

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3317]
## Issue:
Right now, to change the mode of an asset from append to link requires going into a drop down - has no icons, and... it's slow and clunky and you change this often when working on layout. 

Imagine you need to append some objects you want to model for blockout, link in the props and characters, then append some grease pencil objects, and so forth.. all in one session. You've toggled this prop over and over. 

Ideally... a single click would be good - and make it visual and easy to hit. 

**Example (from the view toggles)**
![bforartists_l6RGcSBUG7](https://user-images.githubusercontent.com/35357409/203611849-3830cb82-fb1c-41ff-a978-86bd3f4143ae.png) 

@Blenux has started working on an idea for it. I have also dug a little. Would you like to tackle this task? 

Here is a working prototype already done. 
![image](https://user-images.githubusercontent.com/35357409/203612090-e64c9f99-dc28-4c21-96bc-de8fde875a4f.png)

Right now, we don't know how to add the icons exactly, but I assume this is done in the props defined in C
![image](https://user-images.githubusercontent.com/35357409/203612456-d14d71e7-debd-481e-8c6c-efab99923814.png)

Clues: 
I assume you'd have to add the icons here like in other enumerated icon menus we've done. 
![Code_1WvFMJ9o3i](https://user-images.githubusercontent.com/35357409/203612607-36e3a29a-84e3-4309-ad98-4c4a0a56d331.png)

**Comment by Blenux** [comment]
Sure will have a look when can.

**Comment by Blenux** [comment]
Got it, though I'm not sure what to use for the **Append (Reuse Data)** has a icon.

![Screenshot 2022-11-24 115548](https://user-images.githubusercontent.com/25260650/203671061-dc0c408d-fe55-42dd-b695-bf033a22efaf.png)
![image](https://user-images.githubusercontent.com/25260650/203671094-5dd7d1a9-a540-4d8d-8745-8d48a288ddb4.png)

**Comment by ReinerBforartists** [comment]
You already use the right icon :)

But just curious, do you really want to middle align the prop? Our rule is left menus, right options ...

![append](https://user-images.githubusercontent.com/13919702/203734263-6f3c66fc-50e1-4279-93aa-862e512b6052.jpg)

**Comment by Draise14** [comment]
Looks like we need a new icon. 

Concerning the center, this was the default method we had inhereted from Blender. We could make it consistent with the GUI ethos and float right. These are changed relatively often, so center is ease of access on the way to the center of the 3D view - but yeah, it's not as responsive this way. 

Maybe I'd like add a label too before the buttons.

**Comment by ReinerBforartists** [comment]
I am no friend of centered elements. That's three places to watch then. This is why we have made it left menus and right options then. Regarding the label, don't overdo. You usually hover once over it, and then you know what it is good for. A label is more visual noise.

**Comment by Blenux** [comment]
Yeah was thinking that,  should I just commit this with the question icon for now or need to make icon first?

**Comment by Draise14** [comment]
Sure, in a branch can do, then I can make an icon - just gotta confirm I still can in my environment.

**Comment by Blenux** [comment]
ok created the branch for now

**Comment by Draise14** [comment]
Ok, getting back into the mood to code again, finished the move enough! This will be my first one.

**Comment by Draise14** [comment]
@Blenux I can't seem to find this branch. What is it called?

**Comment by Draise14** [comment]
I got this, rebuilt it with the new 4th option, found some fitting icons.
