### ISSUE TITLE
Asset Browser - Catalog Service - Path not found (Linux)

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3324]
Notice this while on Linux (KDE Neon), Linux paths needs / not \

Windows = \Default Library\
Linux = /Default Library/

![Screenshot_20221126_201030](https://user-images.githubusercontent.com/25260650/204083586-d17abf38-07ce-4636-ad65-45af00800b7e.png)

![Screenshot_20221126_222533](https://user-images.githubusercontent.com/25260650/204086351-fa369e5a-c1dd-4684-992a-37d7992779ae.png)

**Comment by ReinerBforartists** [comment]
Uh that's a showstopper since we have turned off the mini ligthlib and the materials fx addon in favour of the asset lib ...

**Comment by Draise14** [comment]
Ah. Should be an easy fix. I'm out today but I can do that tomorrow.

**Comment by Draise14** [comment]
Ok, got it going on Windows with a system that SHOULD work on linux, but I don't have not tested on linux yet.

**Comment by Draise14** [comment]
@Blenux could you give it a quick test? It's in the master now.

**Comment by Blenux** [comment]
Can see the Catalogs, though at first nothing shows, did some tests and one has to re-save the asset library with the 3.5 alpha build for them to show.

![before_asset](https://user-images.githubusercontent.com/25260650/204169391-431e48d7-9303-4bb4-a3dc-d7981928d592.png)
![after_asset](https://user-images.githubusercontent.com/25260650/204169398-c39b591e-adc9-431b-94c7-1f8916ca2c16.png)

(Same for Blender also).

**Comment by Draise14** [comment]
Oh... Thats why my asset libraries stopped working. Also a refresh also reloads sometimes, but doesn't stick. Thought it was a bug and was gonna report to Blender! 

I'll open another task for this.
