### ISSUE TITLE
Geometry Nodes - Icon Button - Wrong operator type.

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3325]
Notice this while checking out Task #3251 (which is strange).

![Screenshot_20221126_225116](https://user-images.githubusercontent.com/25260650/204087440-6e57c48d-b783-4b5c-8c6b-69349cb7724f.png)

https://user-images.githubusercontent.com/25260650/204087151-acb7a194-9011-4653-8459-a9ee268c522e.mp4

**Comment by ReinerBforartists** [comment]
Oops ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
