### ISSUE TITLE
Compile problem with Hip at Windows

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3327]
I knew this will make us trouble at one point. It seems that the Hip version that we have does not longer allow us to compile with it at Windows. It throws an error. Linux worked fine. But the Windows build not.

I stumbled across this when i tried to create the current devbuilds. Could somebody please confirm?

![trouble](https://user-images.githubusercontent.com/13919702/204108756-bd06791e-3e43-4dd8-9034-f7829216ff14.jpg)

**Comment by ReinerBforartists** [comment]
New pulled Blender build errors out the same way. So we have really a problem with our Hip version.

Let's see if it helps to create it without Hip 

![error](https://user-images.githubusercontent.com/13919702/204125387-ca39383b-3636-4b56-8ebd-f25148b8afcb.jpg)

**Comment by ReinerBforartists** [comment]
Yes, it is Hip. Compiling without it lets the build succeed.

As a consequence, the newest dev build will come without Hip.

**Comment by ReinerBforartists** [comment]
While at it, the ETA for Blender 3.4 is december the 7th. So we need a quick solution here.

**Comment by Draise14** [comment]
I've asked for an update on Devtalk

**Comment by Draise14** [comment]
Though, they have been taking a while to respond - this is so not opensource at all. We may have to just build without it....

**Comment by ReinerBforartists** [comment]
Have you digged through the log for the current merge? Last week it still worked ...

**Comment by Draise14** [comment]
I'll double check once I'm back to the house. Currently running errands now.

**Comment by ReinerBforartists** [comment]
Commit in question

SHA-1: c94583cd64b4effe489c6a0fb73c1c7fa69c9a17

* Cycles: enable AMD RDNA3 GPUs and upgrade HIP compiler

* Enable AMD RDNA3 GPUs
* Fix T100891: performance regression with RDNA2 cards
* Workaround new compiler issue with Vega, by using -O1

Differential Revision: https://developer.blender.org/D16507

**Comment by ReinerBforartists** [comment]
Shall we try to revert the changes? Or shall we simply skip HIP? It will always strike back as long as the HIP windows compiler is not public.

**Comment by Draise14** [comment]
Getting directly in touch with AMD would be nice. Seems my ping on Devtalk got nowhere... I'll ping again today. 

If not, maybe just disabling instead of reverting for smoother sailing till they release these libraries....

**Comment by Draise14** [comment]
I had a quick investigation and pinged again, but looks like the HIP libs only work on some cards, is really.. specific and still... closed. I suggest disabling it for now, and wait till blender has it fully ok. If a user asks for it, we can try insist - but for now maybe our user base for this type of hardward is very limited.

**Comment by ReinerBforartists** [comment]
Okay boss :)

**Comment by Draise14** [comment]
Got a new link! 

I have uploaded it to the Nextcloud. They mention they'll probably have these open by early next year, but for now we have the files with zero support from AMD.

**Comment by ReinerBforartists** [comment]
\o/

**Comment by ReinerBforartists** [comment]
Will test it once the merge is done :)

**Comment by ReinerBforartists** [comment]
In which folder have you added it? I can't see it. Is it even shared?

**Comment by Draise14** [comment]
The software folder

**Comment by ReinerBforartists** [comment]
There is none :)

I guess you have not set it to public. In this case just you can see it. Even other admins not.

While at it, can you see the developerbuilds folder?

![files](https://user-images.githubusercontent.com/13919702/204521559-51eca86d-0d44-4a46-91ac-b4aa27660dde.jpg)

**Comment by Draise14** [comment]
I don't see the developer build folder. Why is this nextcloud server not default to the correct perms? Does it always have to be opt in every folder change?

Typically this should allow and sync to the users on the team without needing to opt in the changes manually. I've used this with another client, changing permission shouldn't be a thing.. It would work every sync automatically.

**Comment by ReinerBforartists** [comment]
I feared it. Rights settings is really black magic in Nextcloud XD

Well, they make it as secure as possible. And the most secure setting is hide everything from everybody for everybody. 

I guess best would be to simply use the share folder. Every content in it should be shared already. And is accessible by everyone.

**Comment by ReinerBforartists** [comment]
Hrm. I logged in with my test account. And there i have a Devbuilds folder which i have long deleted. But i can't see this folder as an admin anymore. Nextcloud -.-

**Comment by Draise14** [comment]
Ah, everything should be in the shared folder now.

**Comment by ReinerBforartists** [comment]
Thanks, have found the HIP_SDK file, and am downloading :)

Will do some more tests if i can make the Developerbuild show up for everybody. There must be a way ...

**Comment by ReinerBforartists** [comment]
Have it. In the Shared sidebar you need to add the Share (Group) to the folder. This can be done by clicking at the Name, email or Federated Cloud ID edit box at the top. 

You can also type in a single user here, and just share with this user. Type in a letter to access the list.

The Developerbuild folder should be visible for everybody now :)

![shared1](https://user-images.githubusercontent.com/13919702/204602330-cc84fcb9-7625-4432-a675-635ceeca30ff.jpg)

![share2](https://user-images.githubusercontent.com/13919702/204602358-8912f0d7-e216-40de-9b39-e0d8861fb12f.jpg)

**Comment by ReinerBforartists** [comment]
Nevermind. Will test tomorrow ^^

**Comment by ReinerBforartists** [comment]
Back in business. Compilation worked fine. Many thanks @Draise14 :)
