### ISSUE TITLE
Asset Browser - Default Library - Needs to be resaved as 3.5 to load correctly

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3329]
At the moment, you can see the Catalogs, though at first nothing shows, did some tests and one has to re-save the asset library with the 3.5 alpha build for them to show. The catalog system got some updates. 

Current Build behavior.
![image](https://user-images.githubusercontent.com/35357409/204327615-dfc3b36e-81cc-47de-b524-7a633262bf05.png)

Re-saved with 3.5 Alpha
![image](https://user-images.githubusercontent.com/35357409/204327622-eba351bb-6135-4498-950b-bcaf1e1c6a3b.png)

(Same for Blender also).

**Comment by ReinerBforartists** [comment]
Ah, had some old settings in the appdata. Mean trap is a mean trap !

All well ...

**Comment by ReinerBforartists** [comment]
Fixed in master
