### ISSUE TITLE
Adjust last operator - align props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3337]
One makes it ... you guess it

![smartuv](https://user-images.githubusercontent.com/13919702/205504402-5460f5b7-545e-4d6d-ac4a-a51ecc9d2d67.jpg)

**Comment by ReinerBforartists** [comment]
This is a general problem with all adjust last operator panels. We are back to middle aligned :/

@iyadahmed, could you please have a look here when you find time?

![general](https://user-images.githubusercontent.com/13919702/205505051-6e7414e5-90f3-40f3-8063-29efc43286fa.jpg)

**Comment by ReinerBforartists** [comment]
This gots introduced with the today merge. So let's do a code comparison. Even when i have no idea where to start ^^

**Comment by ReinerBforartists** [comment]
Correction, this came with the merge from last week. Latest devbuild already shows the behaviour. So we need to go back by two weeks. Phew ...

**Comment by ReinerBforartists** [comment]
Not to catch so far :/

We had before two weeks lots of changes in the source/blender/editors/interface region with portings from c to c++. But i simply cannot nail it down which change is responsible for left alignment and got lost with the changes. I fear this fish is too big for me.

**Comment by ReinerBforartists** [comment]
Gotcha \o/

I went through the whole \source\blender\editors\interface folder, starting with code from before two weeks. And catched the baddie by comparing the code with Blender. I also found some icons that slipped through. The change from c to c++ made really trouble here.

Fingers crossed and until next time ...

![fixed](https://user-images.githubusercontent.com/13919702/205601001-3184d44a-c989-4deb-8606-b6da101e543f.jpg)

**Comment by iyadahmed** [comment]
Im worried about this part 😅
![image](https://user-images.githubusercontent.com/25552173/205814302-80818484-d07e-49f2-a5ed-12e2a156a3d3.jpeg)

**Comment by ReinerBforartists** [comment]
Shall we reopen? :)

Just fix what is broken. At the moment it seems to work :D

**Comment by iyadahmed** [comment]
It would be a different issue if my guess is right ;), lets leave this one closed
