### ISSUE TITLE
Transform Panels - Misaligned keyframe buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3339]
![image](https://user-images.githubusercontent.com/35357409/206014188-6ac5d073-f377-4863-84ca-8062ae7c4ff2.png)

Just made a build from master, and the keyframe buttons are misaligned a row.

**Comment by Draise14** [comment]
Might be a bad build. Will make a new one tonight after work... I also found no colour icons in the collection colors context menu. 

![image](https://user-images.githubusercontent.com/35357409/206031150-5332f058-4ff0-49ba-82c6-06b24f3e0af5.png)

**Comment by iyadahmed** [comment]
We meed to add back these 3 lines back where they were, hopefully nothing else is broken
![image](https://user-images.githubusercontent.com/25552173/206103465-be9902d6-f87c-4602-b368-ade3b6944bef.jpeg)

**Comment by iyadahmed** [comment]
https://github.com/Bforartists/Bforartists/commit/5cd69c567e40a75014e08dbe9bc2c402a7b5188c

**Comment by ReinerBforartists** [comment]
Shall i try or do you want to do this @iyadahmed ? :)

**Comment by Draise14** [comment]
I think Iyad recently formatted and reinstalled his environment the past couple of days, which means he may be updating libs atm. Sometimes his internet is difficult. It's close to 2 am here for me, have to throw on some renders - but before work tomorrow I could try compile with these lines unless you'd like to give it a go @ReinerBforartists , go ahead and see. Might work.

**Comment by ReinerBforartists** [comment]
On my way ...

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/206113069-66567396-e9bd-4412-98cc-0bc39d493d54.jpg)
