### ISSUE TITLE
Bug - Can't click and drag props

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3340]
The devbuild has this issue...
![bforartists_cJmVG6BDNy](https://user-images.githubusercontent.com/35357409/206101514-3642b530-9f4f-476f-9197-225534c5ed4a.gif)

But Blender does not. And the master neither, but good to keep in mind to see if it's truly fixed for the next release. 

Desired UX
![blender_VJo2PkRGxz](https://user-images.githubusercontent.com/35357409/206101601-934f5134-1052-4001-a19d-14dfdc75af5e.gif)

**Comment by ReinerBforartists** [comment]
Works as designed here. Fingers crossed ^^

**Comment by ReinerBforartists** [comment]
Closing this one as a temporary hiccup that gots fixed in the master already.
