### ISSUE TITLE
Bug - Outliner - Collection colours have wrong icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3341]
![image](https://user-images.githubusercontent.com/35357409/206104114-f2425855-d60f-4256-8a63-71d64ecd57ad.png)

When using the collection context menu to assign colours, you'll see broken icons.

**Comment by ReinerBforartists** [comment]
Hmmm. In the latest devbuild it works. And there was basically just one change that i did since then. 

https://github.com/Bforartists/Bforartists/issues/3337

**Comment by ReinerBforartists** [comment]
Fixed

"Catched" the wrong icons in former commit ...

![fixed](https://user-images.githubusercontent.com/13919702/206117736-1d51ce65-d18b-4b85-ac17-955434cf18ec.jpg)
