### ISSUE TITLE
Bforartists 3.4 Release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3345]
Blender 3.4 is out! Here is a threada to To keep track. 

@Draise14 will do the splashscreen and prepare the master, working on that now
@ReinerBforartists can do most of the builds easily enough, eta probably tomorrow
@iyadahmed can do a linux build
@seanr is doing the Mac Build. 

The binary installers and release - I guess I can try do that. 
Documentation.

**Comment by ReinerBforartists** [comment]
You should compile the Windows version at your pc. It's about to have a working setup ...

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/206264801-c1d3cdb5-afb2-4e2b-a6db-a12b4bf5db15.png)

Got the versioning updated in the build so far, with splashscreen. Will commit and pull.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/206266163-7bf68490-1350-47a3-933e-6539afc138c4.png)

Ok, building a release build to test while having lunch. `ocloc` (oneApi binaries) were not found. That might be an extra step. Are we supposed to ship those binaries? HIP is fine!

**Comment by Draise14** [comment]
Yep. Have done so. Will upload the zip and make the installer in first break.

**Comment by Draise14** [comment]
Ok, done this so far. Sean is on the mac build, hit a bit of an issue. Hopefully it's only the hip stuff.

- Did the release notes
- Uploaded the dev
- Uploaded the tar.xz with release notes
- Uploaded the zip with the release notes
- Updated the release notes webpage
- Made a github release
- Uploaded the windows installer 

I tried to do the appimage, but the VM is missing oneapi?
![vmplayer_RvhyQzZTGD](https://user-images.githubusercontent.com/35357409/206812677-c9fbda6a-1e23-4b00-a6ae-be50edf6742d.png)

I had the default app generation, followed instructions, but not sure. Is there a new appimage recipe thing to figure out?

**Comment by Draise14** [comment]
Ah @ReinerBforartists the installers are on the nextcloud. Though I am not sure who did the deb and tar.xz

**Comment by Draise14** [comment]
Ok, updated the homepage with the github links momentarily. When on the server, you can update them! Appimage and the mac build is what's left.

**Comment by Draise14** [comment]
Mac has hit a wall. It's not building at all. We have added the hip dependencies, and the libs are up to date, he's still getting this issue. 

```
ck_region.cc.o
[  4%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/trklt_region_tracker.cc.o
[  4%] Linking CXX static library ../../lib/libbf_intern_libmv.a
[  4%] Built target bf_intern_libmv
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by ReinerBforartists** [comment]
> Mac has hit a wall. It's not building at all. We have added the hip dependencies, and the libs are up to date, he's still getting this issue.
> 
> ```
> ck_region.cc.o
> [  4%] Building CXX object intern/libmv/CMakeFiles/bf_intern_libmv.dir/libmv/tracking/trklt_region_tracker.cc.o
> [  4%] Linking CXX static library ../../lib/libbf_intern_libmv.a
> [  4%] Built target bf_intern_libmv
> make[1]: *** [all] Error 2
> make: *** [all] Error 2
> ```

I am unfortunately lost with Mac . But this looks like a dependency issue with Libmv. Funny enough this seems to be a Mac lib. Not one that comes with the bundled libs.

**Comment by ReinerBforartists** [comment]
Updated the files at the server. Missing is Mac and Appimage so far.

**Comment by ReinerBforartists** [comment]
Found something to improve for future releases. @Draise14 , you used png files for the screenshots. That's roughly 2/3 bigger than a jpg file. And for web needs jpg is still to prefer. It makes a difference if you download 1mb or 300 kb when you are at a smartphone with limited bandwidth for example.

So please use jpg in the future :)

**Comment by Draise14** [comment]
Ah ok, updated the github page. I have 300mb down so it has felt irrelevant - but yeah, keep forgetting a lot of the world doesn't have that kind of bandwidth. Maybe I should see if Webp is getting more love and use.  

And yes, saw your comments about the appimage, I was trying to do it the traditional way.

**Comment by ReinerBforartists** [comment]
Yeah, something's broken here. One of those unlucky releases where everything tends to break it seems :/

**Comment by seanr** [comment]
https://www.dropbox.com/s/uxj7rj15tg8hqak/Bforartists-v3.4.0-Mac.dmg?dl=0

**Comment by Draise14** [comment]
Sweeeeeet, you managed. Fill upload to github and update the page link. It will be on the server maybe tomorrow.

**Comment by iyadahmed** [comment]
> Found something to improve for future releases. @Draise14 , you used png files for the screenshots. That's roughly 2/3 bigger than a jpg file. And can in extreme casese go much much higher. For web needs jpg is still to prefer. It makes a difference if you download 1 or 2 mb, or 300 kb when you are at a smartphone with limited bandwidth for example.
> 
> 
> 
> So please use jpg in the future for everything that goes to the page :)
> 
> 
> 
> EDIT, updated the images in the news post at the page to jpg.

Tiny png can help too

https://tinypng.com/

**Comment by ReinerBforartists** [comment]
Yes, thanks. But jpg is still to prefer. It's simply still the web default :)

And i am glad that the creation of the Mac version finally worked. Uploading. Remains the appimage trouble maker ...

**Comment by ReinerBforartists** [comment]
Mac has arrived at the server

**Comment by ReinerBforartists** [comment]
I vote to close this task. It makes no sense to create a appimage with the new linux libs since we decided to switch to Ubuntu 22.04 too. So we will have new libs and a new glibc version, and then this version is already too far away from Bforartists 3.4.0 release. Let's wait for the next Blender point upgrade before we offer a new appimage version.
