### ISSUE TITLE
Ubuntu 22.04 LTS - OneApi build problem

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3349]
I managed to migrate a copy of my 20.04 LTS VM to 22.04. The goal was to test out if the aged libs from 20.04 could be the problem why the Appimage does not start. 

Instead i ran into the same problem than @Draise14 before when i tried to compile **make release**. OneAPI makes trouble. It will not compile. 

Ideas? It's the same libs and files than in 20.04. And there it worked.

![oneapi](https://user-images.githubusercontent.com/13919702/206900715-2d07fdc5-bbc1-41b8-94b2-89ae9b18702b.jpg)

**Comment by ReinerBforartists** [comment]
I guess the next step is to compile Blender, and have a look if i can reproduce the problem ...

**Comment by ReinerBforartists** [comment]
Same error \o/

**Comment by ReinerBforartists** [comment]
Asked at Blender developers for help. Fingers crossed ...

**Comment by ReinerBforartists** [comment]
No answer so far, and it now also happens at my old 20.04 vm. Seems that we are not longer able to build with oneapi. Something vital has changed. But first let me check if a build without oneapi even finishes. Maybe we have more than one problem here. The error.log points towards a missing arm_neon.h file ...

![neonbuildproblem](https://user-images.githubusercontent.com/13919702/208099765-31976220-bd34-4f7a-8fc3-0fd33ddcda00.jpg)

**Comment by ReinerBforartists** [comment]
It remains as it is: no oneapi for now.

**Comment by iyadahmed** [comment]
I guess it is better to use Ubuntu 20.04

**Comment by ReinerBforartists** [comment]
This was Ubuntu 20.04 :D

They have made oneapi not compiling anymore at Linux. I tried it now at two of my VM's. You can test it too if you find the time for. And maybe you come through to them. My post gets ignored.

**Comment by iyadahmed** [comment]
same issue here for me on 22.04 vm

**Comment by ReinerBforartists** [comment]
Also Blender is affected by the way. But as told, they don't react. I can just hope that in a few weeks it is back working.

**Comment by ReinerBforartists** [comment]
Posted in discord already. But just that i post it here too. We don't have a linux devbuild at the moment. It does not start anymore. Even with oneapi off.

And oneapi was also the troublemaker for our appimage build


![linuxdevbuild](https://user-images.githubusercontent.com/13919702/208233840-3e16aa5d-e063-453a-ba47-de0d35cb063d.jpg)


![oneapi](https://user-images.githubusercontent.com/13919702/208233863-b2e5e5cc-ee76-4f00-b543-b18265ebed19.jpg)

**Comment by ReinerBforartists** [comment]
This issue is solved. The solution was to install g++12 

sudo apt install g++-12
