### ISSUE TITLE
Mark Asset context menus have missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3358]
![image](https://user-images.githubusercontent.com/35357409/209259937-5c4fd2b4-afd3-4297-82c6-02cd5b9d90a4.png)

![image](https://user-images.githubusercontent.com/35357409/209260073-86e1ff2a-7a18-4bb4-9346-16ba9bd725fb.png)

Looks like the context menu from the Node editor to mark assets from data dropdowns are missing.

**Comment by ReinerBforartists** [comment]
In which editor is this?

**Comment by ReinerBforartists** [comment]
As a note, i think we are at a Blender bug here. Clear asset does not work. And mark a material as an asset can really just be done from the outliner? O_O

And the clear asset item in the rmb menu is dysfunctional too.

![unreachable](https://user-images.githubusercontent.com/13919702/209298132-875d0caf-fad8-41f6-a01a-bce435a5564e.jpg)

![disabled](https://user-images.githubusercontent.com/13919702/209297834-8042db88-e731-4f5b-9ff7-a63022239bba.jpg)

**Comment by ReinerBforartists** [comment]
> In which editor is this?

**Comment by ReinerBforartists** [comment]
Found so far just one entry without icon in the interface_context_menu.cc. But again, i have no possibility to check here since i still don't know how to reach this menu.

![noicon](https://user-images.githubusercontent.com/13919702/229054771-1560c37d-531d-4f7b-8189-3488b84bc3c0.jpg)

**Comment by ReinerBforartists** [comment]
Found it. Fixed it. I don't think that we have it documented yet though. Making a task.

![clearfixed](https://user-images.githubusercontent.com/13919702/229067906-fee1b389-2062-459c-a9fc-63bfb5fc6498.jpg)
