### ISSUE TITLE
Devbuild link is broken on Website

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3359]
![image](https://user-images.githubusercontent.com/35357409/209260524-13bba3e4-6a30-49d7-9c1c-92ee199e6215.png)

![image](https://user-images.githubusercontent.com/35357409/209260578-063aabee-6d88-49bd-9c81-d26d22171c54.png)

Look like the windows devbuild link is broken.

**Comment by ReinerBforartists** [comment]
Oops. Fixed.
