### ISSUE TITLE
Context menu insanity - Specials menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#336]
Blender devs had in the past the so called Specials menu. A wild mixture of double menu entries and tools that did not have a menu entry in the regular menu at all. 

This was just a handful.

Now they have refined the concept, and made it even more insane. Every mode and object type has now a context menu. With the usual double menu entries and tools that should have regular menu entries. But much much more now.

Shading, snap and parent should NOT be hidden. But accessible from a regular menu.

And on top of the story they are blocking the right mouse button with this nonsense menus now. That's our navigation hotkey ...

What to do here needs further investigation and thinking. We will for sure remove the double menu entries. And put the common tools into regular header menus. But we cannot easily remove this menus completely. We were trapped by this before. When an addon tries to write itself into this menu, then it becomes disfunctional.

![contextmenus](https://user-images.githubusercontent.com/13919702/49994924-130dab00-ff8b-11e8-87b5-b38aa623bc1a.jpg)

**Comment by ReinerBforartists** [comment]
Under the hood they are still called specials menus. This task needs a split into the several context menus available.

![specials](https://user-images.githubusercontent.com/13919702/49995580-de9aee80-ff8c-11e8-925e-a9c66b1d1acd.jpg)

**Comment by ReinerBforartists** [comment]
It's inconsistent.

**Comment by ReinerBforartists** [comment]
Let's fix this chapter here ...

**Comment by Draise14** [comment]
What's your plan? I would love the quick menu combined with contextuals. No point having both.

**Comment by ReinerBforartists** [comment]
What do you mean with quick menu? A pie menu?

The first step is to make a list of all available context menus in the 3D view. Then let's put everything that is just in the specials menu into the regular menus. It makes imho not this much sense to give them a hotkey again. But maybe we find a free one for just this specials menu. But definitely not with the right mouse.

**Comment by ReinerBforartists** [comment]
This is even more messy than thought. In object mode you will have object type dependant entries. For light for example you have energy and radius. So i need to go through the whole menu code of the specials menus, menu item by menu item. Makes no sense to make a snapshot of every possible combination, which i have started, but abandoned then. Menu by menu in the code is easier.

And the context menu also exist in other editors, with some special entries just in this right click menu. Outliner for example.

Let's get our feet wet, and start with the biggest one, the 3D view.

![rclickoutliner](https://user-images.githubusercontent.com/13919702/52997859-fa55c180-3421-11e9-8727-2693af04fda2.jpg)

![rightclickmenus3dview](https://user-images.githubusercontent.com/13919702/52997854-f75ad100-3421-11e9-9409-ab6ebe4bc252.jpg)

**Comment by ReinerBforartists** [comment]
I will also try to add available icons here. Icons that we need to create will become its own task.

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_object vs VIEW3D_MT_object_Specials

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_particle  vs VIEW3D_MT_particle_specials

**Comment by ReinerBforartists** [comment]
... -.-

The funny part here is, this part just shows in particle select mode Point. While the normal Select menu shows them in all particle modes. Well doesn't hurt to be able to select all or none in the other modes, doesn't it?

![particle](https://user-images.githubusercontent.com/13919702/53004591-cd110f80-3431-11e9-9581-833956d3e6ae.jpg)

![selectmenu](https://user-images.githubusercontent.com/13919702/53004605-d0a49680-3431-11e9-88ab-5974016fad05.jpg)

**Comment by ReinerBforartists** [comment]
Nothing to fix here. This entries all exists already.

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_pose versus VIEW3D_MT_pose_specials

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_edit_mesh vs VIEW3D_MT_edit_mesh_specials

![editmode](https://user-images.githubusercontent.com/13919702/53008109-eff2f200-3438-11e9-8d95-fd033b287ccb.jpg)

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_edit_curve vs VIEW3D_MT_edit_curve_specials

The right click calls one menu for both, curve and surface object. In edit mode we have two separate menus for this object types. So missing content must go into both menus.

![curve](https://user-images.githubusercontent.com/13919702/53033810-2b5de280-3472-11e9-9a8b-aeb5c7fb62c0.jpg)

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_armature vs VIEW3D_MT_armature_specials

**Comment by ReinerBforartists** [comment]
Bones in Pose Mode

VIEW3D_MT_pose vs VIEW3D_MT_pose_specials

![pose](https://user-images.githubusercontent.com/13919702/53073014-25eeaf80-34e7-11e9-9480-e79f0ab21b8c.jpg)

**Comment by ReinerBforartists** [comment]
They really had me for a moment here ...

![double](https://user-images.githubusercontent.com/13919702/53074490-30ab4380-34eb-11e9-82fe-195fe98ae1b4.jpg)

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_edit_gpencil vs VIEW3D_MT_gpencil_edit_specials

Edit mode

![gpspecials](https://user-images.githubusercontent.com/13919702/53076848-ff357680-34f0-11e9-8835-8e15fd37db2b.jpg)

**Comment by ReinerBforartists** [comment]
Hm, grease pencil in sculpt mode lacks of a header menu. The whole specials menu content is missing here.

![sculpt](https://user-images.githubusercontent.com/13919702/53078896-7bca5400-34f5-11e9-98af-96810cf819fd.jpg)

**Comment by ReinerBforartists** [comment]
But first let's fix this rascal here ...

![colnotdefined](https://user-images.githubusercontent.com/13919702/53078971-af0ce300-34f5-11e9-9de9-b2712c892174.jpg)

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_weight_gpencil vs VIEW3D_MT_gpencil_edit_specials

![sculptmenu](https://user-images.githubusercontent.com/13919702/53081337-ef229480-34fa-11e9-8e32-8df51de16d92.jpg)

**Comment by ReinerBforartists** [comment]
VIEW3D_MT_paint_gpencil vs GPENCIL_MT_gpencil_draw_specials

![draw](https://user-images.githubusercontent.com/13919702/53082952-3b230880-34fe-11e9-89f2-c81f4c5b73ea.jpg)

**Comment by ReinerBforartists** [comment]
Outliner ...
![outliner](https://user-images.githubusercontent.com/13919702/53085356-f5b50a00-3502-11e9-8824-dad4bab463d4.jpg)

**Comment by ReinerBforartists** [comment]
Okay, the rest is not so easy to catch. Going through the Blender keymap now ...

**Comment by ReinerBforartists** [comment]
IMAGE_MT_uvs vs IMAGE_MT_uvs_specials

![uveditor](https://user-images.githubusercontent.com/13919702/53109722-c7065600-3539-11e9-90cc-1dd1d75562f5.jpg)

**Comment by ReinerBforartists** [comment]
NODE_MT_node vs NODE_MT_specials

![node](https://user-images.githubusercontent.com/13919702/53111431-52351b00-353d-11e9-849b-36cb19c2ebf0.jpg)

**Comment by ReinerBforartists** [comment]
All double, nothing to fix here.

**Comment by ReinerBforartists** [comment]
DOPESHEET_MT_ channel vs DOPESHEET_MT_specials

![dopesheet](https://user-images.githubusercontent.com/13919702/53151043-65360280-35b2-11e9-80d3-232f1eae6903.jpg)

**Comment by ReinerBforartists** [comment]
All double, nothing to fix here.

**Comment by ReinerBforartists** [comment]
GRAPH_MT_specials. Funny here is that this menu cannot be called. RMB is occupied by set cursor, graph.cursor_set , and overrides the calling of this specials menu. Good job folks :dagger: 

Turned off set cursor to make the screenshot. Let's check ...

![fcurvespecials](https://user-images.githubusercontent.com/13919702/53152031-d2e32e00-35b4-11e9-894f-1cac28e0a00b.jpg)

**Comment by ReinerBforartists** [comment]
All double, nothing to fix here.

**Comment by ReinerBforartists** [comment]
TEXT_MT_toolbox

Not a specials menu. But a right click context menu one. All double, nothing to fix here.

![texteditor](https://user-images.githubusercontent.com/13919702/53153791-7c2c2300-35b9-11e9-902d-4b8305a10594.jpg)

**Comment by ReinerBforartists** [comment]
CLIP_MT_tracking_specials

![clip](https://user-images.githubusercontent.com/13919702/53154110-463b6e80-35ba-11e9-85d1-ab3a0e9997fc.jpg)

**Comment by ReinerBforartists** [comment]
All double, nothing to fix here.

**Comment by ReinerBforartists** [comment]
That's it. Thorugh with all call menus that gets called by right mouse button.
