### ISSUE TITLE
Most icons are not displayed

### ISSUE THREAD

**Issue by Gilraiser** [Bforartists/Bforartists#3362]
**Bug Description**
Icons with colors are not displayed anywhere in the program. 

**Operating System:** Arch Linux                      
**Kernel:** Linux 5.15.85-1-lts
**Architecture:** x86-64

**Graphic card information:**
[AMD/ATI] Kabini [Radeon HD 8400 / R3 Series]
Kernel driver in use: radeon
Dedicated video memory: 2048 MB
Total available memory: 2075 MB

**Screenshots**
![Bforartists-bug-icons-01](https://user-images.githubusercontent.com/45057390/209585078-fe5a50b0-c6bb-40a1-a6ad-d5d17ad6c50f.png)
![Bforartists-bug-icons-02](https://user-images.githubusercontent.com/45057390/209585079-aff60217-5fba-4847-8956-4356d7c773a6.png)

Thank you very much for the excellent work :)

**Comment by Draise14** [comment]
Yikes! In the console (Window>Console) what kind of errors are you getting? 

With Blender, can you download a 3.5 build and test?

**Comment by ReinerBforartists** [comment]
> Dedicated video memory: 2048 MB

Hey Gil, thanks for the report. Looks like a bit few vram. Is this a VM? If not then your graphics card could be deprecated. A card with 2 Gb is a bit aged.

**Comment by Gilraiser** [comment]
Hello, best regards. The work area works well, I can visualize and manipulate objects and meshes. Icons is the only thing missing. When I run the appimage (Bforartist 3.3.1) or tar.xz file (Bforartist 3.4.0) it prints the following:

radeon: Failed to allocate a buffer:
radeon:    size      : 41943040 bytes
radeon:    alignment : 16384 bytes
radeon:    domains   : 6
radeon:    flags     : 20
radeon: Failed to allocate a buffer:
radeon:    size      : 41943040 bytes
radeon:    alignment : 16384 bytes
radeon:    domains   : 6
radeon:    flags     : 20

In the python console the following is printed:

Bforartist 3.3.1
PYTHON INTERACTIVE CONSOLE 3.10.2 (main, Apr 26 2022, 10:33:12) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, gpu, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

Bforartists 3.4.0

PYTHON INTERACTIVE CONSOLE 3.10.8 (main, Oct 24 2022, 20:47:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, gpu, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

I have Blender 3.4.1 installed from the official Archlinux repositories and I just installed Blender 3.5 Alpha and it runs fine so far. You're right about the card, it's very old already :)

I hope it helps, thanks for the excellent work
![3 5-Alpha](https://user-images.githubusercontent.com/45057390/209723129-982a29f0-9aee-468c-abb4-333dd107622a.png)

**Comment by ReinerBforartists** [comment]
Many thanks for checking again :)

> radeon: Failed to allocate a buffer:

This is where it fails to initialize your old card. Mh, have you tried our latest devbuild? As told, Blender developers heavily changes things under the hood at the moment. Also possible that our release version came with a bad piece of code in this regards. But i would really not hang my hopes high here. It is very likely that the devbuild will also fail.

And as told before, there is unfortunately nothing that we could do :/

**Comment by ReinerBforartists** [comment]
I'll close this task now. Sorry that we cannot do more here.
