### ISSUE TITLE
Asset Browser - Catalog Category - Add icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3367]
![image](https://user-images.githubusercontent.com/35357409/210858917-63370912-884a-4ad6-9662-531699304d4e.png)

The Asset Browser has a new header category, the Catalog. This means there are two operators shown without iconography. 

- New Asset Catalogs
- Save Asset Catalogs

They can be the same icons as the panel to the side.

**Comment by ReinerBforartists** [comment]
Documentation has already a task here: https://github.com/Bforartists/Manual/issues/391

**Comment by ReinerBforartists** [comment]
Fixed 

![catalog](https://user-images.githubusercontent.com/13919702/211142075-415cabd8-ff86-467b-a890-94f0188e4d62.png)
