### ISSUE TITLE
Asset Browser - Asset Menu - Create Pose Asset needs icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3368]
![bforartists_lJ054nVu7D](https://user-images.githubusercontent.com/35357409/210860182-ffc63ac6-feb6-4c6f-b56b-2cb850a6dffd.png)

With an armature selected, and the bones selected and animated, you can then Create a Pose Asset in the Asset Browser header. But this has no icon. 

_Double check to see if this is documented._

**Comment by ReinerBforartists** [comment]
I always do the documentation too when i finish a task. Then you don't need to double check. But it is simply habit.

**Comment by ReinerBforartists** [comment]
I'll reuse the Pose_hlt icon here.

![POSE_HLT](https://user-images.githubusercontent.com/13919702/211140424-1bfe3784-4f0c-49f8-98bd-a863b185096c.png)

**Comment by ReinerBforartists** [comment]
Uh. This is an addon. And it is activated by default. So we have to. 

So, one more rascal to keep in mind when merging addons ...

**Comment by ReinerBforartists** [comment]
This task has a sibling. There is more than one button coming from this addon.
![morethanone](https://user-images.githubusercontent.com/13919702/211140695-22b65a51-b60e-41a1-9f9f-3eec4b803324.jpg)

**Comment by ReinerBforartists** [comment]
And we don't have a convert icon yet. Hm, i think we can leave the convert button alone.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/211141057-52b6368e-7bc0-4c73-81a9-54e89da6c176.jpg)
