### ISSUE TITLE
Bforartists 3.4.1 Release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3371]
New blender version was release last week of December, we finally have the branch ready to also do it with the bug fixes.

**Status:**
- Splashscreen and version number and test build is done. 
- I've got windows build, ready to pack and make the installer.
- @iyadahmed  is working on some linux builds
- I'll ping @seanr about a mac build. 
- I guess later today I'll pack up the documentation and make the github release.

**Comment by Draise14** [comment]
Manual documentation updated and uploading.

**Comment by ReinerBforartists** [comment]
Tar and deb are up. Appimage gave me big trouble. The VM to create the appimage versions has quit working. Old version was not happy with the tar that was made with 22.04. And updating the VM to 22.04 broke the scripts then.

**Comment by ReinerBforartists** [comment]
Release is live.

**Comment by seanr** [comment]
Mac version here: https://www.dropbox.com/s/zo12itkp3leape2/Bforartists-v3.4.1-Mac.dmg?dl=0

**Comment by Draise14** [comment]
Mac linked on github, and on homepage, though linked to the github one. I did some grammar/formattings updates on the release notes and downloads page. 

Working on publicity now.

**Comment by ReinerBforartists** [comment]
Release is done, so closing this issue. You can do the promotion without the issue ^^
