### ISSUE TITLE
Asset Browser - Asset library dropdown - add icon to new item All

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3380]
New item, needs icon, needs update in the manual.

![all](https://user-images.githubusercontent.com/13919702/212675650-3c76a71b-9687-4276-9910-46fd6552d5d4.jpg)

**Comment by Draise14** [comment]
Hey cool, that's a nifty good category, but phew that's gonna take a while to load with larger asset libraries.

**Comment by ReinerBforartists** [comment]
We are young, we can wait :)

**Comment by Draise14** [comment]
![bforartists_dLw3MqswdS](https://user-images.githubusercontent.com/35357409/212967004-35662078-8b0d-4b43-976b-dabb3055cf67.png)

Done, added the DOCUMENTS icon here, thought it made most sense, multiple files/documents that it is referenceing.
