### ISSUE TITLE
UV Seam Design

### ISSUE THREAD

**Issue by RussiaGhost** [Bforartists/Bforartists#3385]
Hello. Is it possible to make the choice of displaying seams on the model several types in the program?
1 standard as of now.
![11s](https://user-images.githubusercontent.com/123579239/214626218-f3abe76a-c764-4534-b312-f8359a80a385.png)
2 More dense as done for example in 3ds max?
![1s](https://user-images.githubusercontent.com/123579239/214626516-aeb5daa3-58ae-479f-9b69-14540943ecfa.png)
examples in pictures.
I would like thicker seams so that they are more visible.
in 3ds max there is a switch in the modifier.
Ideally, I would like to be able to change this in the theme settings and set the thickness, for example, you can set the size of the vertices.

**Comment by ReinerBforartists** [comment]
Hello Russiaghost,

I see what you mean. The green line should infact be drawn on top of the grid line. But this goes deep into the drawing engine of Blender. And is unfortunately nothing that we could fix at our end. 

I would suggest to report this issue directly to Blender. 

Kind regards
Reiner

**Comment by RussiaGhost** [comment]
Hello. I wrote the idea on the site https://blender.community/c/rightclickselect/B61Y/. I'm not sure if developers will do this at all, but maybe there is a chance to get it.

**Comment by ReinerBforartists** [comment]
Many thanks. Fingers crossed :)
