### ISSUE TITLE
Weight Paint in vertex select submode - Select menu -  Select Linked

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3395]
New menu item in this mode. Needs icon. Needs documentation.

We also need to check the hotkey here. Blender has the global hotkey Ctrl L . I think we don't have a hotkey for it.

> SHA-1: 04aab7d51620d74c408d7e3e8f5296ce2af793f3
> 
> * Animation: Add "Select Linked Vertices" to Weight Paint Mode
> 
> Adds two operators to select linked  vertices in weight paint mode.
> Similar to how it works in edit mode.
> Press "L" to select vertices under the cursor,
> or CTRL + "L" to select anything linked to the current selection.
> 
> Reviewed by: Sybren A. Stüvel, Hans Goudey, Marion Stalke
> Differential Revision: https://developer.blender.org/D16848
> Ref: D16848

![selectlinked](https://user-images.githubusercontent.com/13919702/218687364-ba23ef5c-4c93-40fc-8c69-27c6600b47fd.jpg)

**Comment by Draise14** [comment]
`CTRL+L` for select linked everywhere would be nice.

**Comment by ReinerBforartists** [comment]
> CTRL+L for select linked everywhere would be nice.

This would be a own task i guess. Just wanted to make sure that we don't run into a conflict here.

**Comment by ReinerBforartists** [comment]
Fixed.
