### ISSUE TITLE
Showstopper bug - can't select objects anymore

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3397]
I can't select objects in the 3d view anymore. Not with box select, not with tweak. Lasso and Circle select still works.

Needs investigation.

![tweakproblem](https://user-images.githubusercontent.com/13919702/218706115-85c9212c-1447-416c-9a22-cfa435166397.jpg)

**Comment by ReinerBforartists** [comment]
This problem is new. Latest devbuild still works as expected.

**Comment by ReinerBforartists** [comment]
Keymap from latest build has just marginal changes. I nevertheless checked if the old keymap works. No luck. 

Something is broken with the newest merge. And i have unfortunately no idea where.

**Comment by ReinerBforartists** [comment]
Selection seems to work again. Phew

**Comment by iyadahmed** [comment]
Fixed in

https://github.com/Bforartists/Bforartists/commit/48a90b4fad02cd87e1a6ca5e653ffc87c48cb29c
