### ISSUE TITLE
No log from the latest merge

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3398]
Blender has changed the infrastructure. Which we have already applied to our local repos. But the actual merges from Blender does not add any log entries. It is unclear if the merge works at all. And if any of the commits even arrives in the Bforartists repo. We are basically stopped in further development. No log entry after the 07.02.2022

https://code.blender.org/2023/02/new-blender-development-infrastructure/

![blender](https://user-images.githubusercontent.com/13919702/219101610-fa64afc6-c1c2-4670-b34f-af0275e2ec40.jpg)

![end](https://user-images.githubusercontent.com/13919702/219101641-81f63a2f-d395-4bf2-841c-3da0f6eb9ad9.jpg)

**Comment by Draise14** [comment]
I'll assign you this one.

**Comment by iyadahmed** [comment]
Fixed in

https://github.com/Bforartists/Bforartists/commit/48a90b4fad02cd87e1a6ca5e653ffc87c48cb29c
