### ISSUE TITLE
Asset Browser - Asset menu - missing icon for create pose asset

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3400]
Icon is missing.

![missingicon](https://user-images.githubusercontent.com/13919702/219327287-159b36a8-391a-4319-b68d-71b6202cb045.jpg)

**Comment by Draise14** [comment]
This one reverts often...

**Comment by ReinerBforartists** [comment]
This one is an addon. One has to be careful while merging  ^^
