### ISSUE TITLE
Dopesheet and Graph editors - Channel menus - add Frame Channel menu item

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3409]
Slipped through on the latest merge. Blender has added a Frame Channel menu item to the channel menus in dopesheet and graph editors. 

Attention, this requires to have a look at the keymap too. It is another menu item than the frame selected from the view menu. Blender uses the same hotkey for both though. We might want to find another hotkey here, or leave the hotkey away.

> SHA-1: d7dd7ee24caf5dd695ed8b95c8bc10464492f945
> 
> * Animation: Add "Frame Channel" operators
> 
> When animating it is often useful to frame the Graph Editor/Dope Sheet to whatever frames are in a given channel.
> This patch adds the option to frame on selected channels OR frame on whatever channel is under the cursor.
> 
> If a preview range is set it will only focus on keys in that range.
> 
> Supports FCurve and keyframe data
> 
> Frame to selected is called with
> * Right click in the channel section -> Frame Selected Channels
> * or in Channel → Frame Selected Channels
> * or hitting . on the numpad
> 
> Frame to channel under cursor is done with
> 
> ALT + Middle Mouse Button
> 
> Co-authored-by: Christoph Lendenfeld <chris.lenden@gmail.com>
> Pull Request #104523

![missing](https://user-images.githubusercontent.com/13919702/220060445-9ef221c5-8e8e-4891-b6e7-750d6cb2e7ba.jpg)

**Comment by ReinerBforartists** [comment]
Hotkey conflict reported to Blender.

https://projects.blender.org/blender/blender/issues/104963

**Comment by ReinerBforartists** [comment]
No conflict, but usual Blender design. The one works with pressing the hotkey, and the other works with pressing the hotkey. The result is arbitrary, dependant if the mouse is over keyframes ...

Make sure we use either two different hotkeys, or leave the one hotkey away.

**Comment by Draise14** [comment]
This hotkey would be our `F` correct?

**Comment by ReinerBforartists** [comment]
Ah, well spotted. We need to change the hotkey too.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/228687098-ea35e851-4c77-45a1-834a-3bf71c4310a9.png)

Got the menu entry in with icon, now need

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/228690463-cd254c86-10a7-4203-bebf-3a101ad45668.png)

Compiling test to factory
