### ISSUE TITLE
Geometry nodes context menu - rename Online Manual link

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3410]
We do not link to Blender since we are Bforartists. Remove this link.

Context menu comes up when you right click at a node.

> SHA-1: e95ba8a70e1922fc8a593ed57f311dbf3250b6a9
> 
> * Nodes: Add 'Online Manual' to context menu
> 
> Finding the documentation for nodes can be time consuming.
> By adding the online manual to the right click context menu in the node
> editor the user gets easier access to the documentation.
> 
> Can also be used by custom nodes add-ons by registering a manual-map.
> 
> Pull Request #104833

![remove](https://user-images.githubusercontent.com/13919702/220067235-59d3e043-f8cb-4de8-a195-9cfc6c50a015.jpg)

**Comment by Draise14** [comment]
Is this link dynamic?

**Comment by Draise14** [comment]
I think personally, as UX for documentation, this is excellent.. but we'd need a URL for each node which means.. an online library that isn't connected to PDF documents - maybe it's time to work a project to convert the documentation to some kind of website.. I will think about that..... 

The potential for this is.. limitless, we could use this code for almost everything in the interface to online documentation.

**Comment by ReinerBforartists** [comment]
Yeah, but we are Bforartists, not Blender. And we don't have such a documentation like Blender :)

**Comment by Draise14** [comment]
Maybe we can leave this up to Blender to maintain, and change the tooltip and operator to "Online Blender Documetnation" /n "Load online Blender Documentation on the clicked node" to not maintain the hyperlinks and still have the UX to access a quick access to documentation. I think removing it all out is not a very helpful solution. 

Maybe another project after I get better at merges and feature development habits, I can think about the website dev... But that won't be for a while.

**Comment by ReinerBforartists** [comment]
May i repeat that we are not Blender? ^^

Dunno if it is a good idea to link to Blender docs then. It explains the Blender side of things. We have exactly one link to Blender, that's the API, but here we don't differ. In the rest we do.

**Comment by Draise14** [comment]
Yeah.. No Bforaritsts online documentation per node, and link back to Blender... it's super useful and I use it often - but yeah, it's not truly Blender. 

Can we comment this out till further notice? Instead of remove completely.

**Comment by ReinerBforartists** [comment]
Sure

**Comment by ReinerBforartists** [comment]
Not happy with keeping this one, as told we are not Blender. And we should never rely at any Blender manual source. But since it is so important for you we'll keep it.

Changed the description and the name though.

![manuallink](https://user-images.githubusercontent.com/13919702/225588346-eed4489e-f1e7-4885-917e-c3f59fda837a.jpg)
