### ISSUE TITLE
Nodes Editor - iconize Hair sub menus, add to sidebar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3414]
We have a whole new chapter of nodes. Hair. A ton of new nodes. They all need new icons, and an entry into the sidebar.

![hair](https://user-images.githubusercontent.com/13919702/221351624-d5ec9128-75ed-49e9-ae57-23ae17ceb0df.jpg)

**Comment by ReinerBforartists** [comment]
Related: https://github.com/Bforartists/Manual/issues/408

**Comment by Draise14** [comment]
Holy crap, this is a big one. 

Though bare in mind, this category are node groups called in from the Asset Browser, from the essentials library.

**Comment by Draise14** [comment]
I think for asset browser groups that get scraped and added here should have.. a generic icon - like node group or asset or something
![image](https://user-images.githubusercontent.com/35357409/221382293-22c3a17c-cef5-4c5a-aaec-99674f4a1116.png)

**Comment by ReinerBforartists** [comment]
![two](https://user-images.githubusercontent.com/13919702/227892089-8e678004-b57f-4cdb-88ee-1f64c9d5a89a.jpg)

**Comment by Draise14** [comment]
Yeah, these are no ordinary nodes, but marked asset node groups, in fact.. ALL asset library node groups append here, even from user libraries. Maybe adding the "Marked Asset" or the "Node Group" icon to these would make sense and call it a day.

**Comment by ReinerBforartists** [comment]
Indeed. 

But i fear this would be a task for Iyad. No idea how to add this icon here.

**Comment by ReinerBforartists** [comment]
Mh, just noticed that we can't add it to the sidebar. This would require a unique icon for each nodegroup ...

**Comment by ReinerBforartists** [comment]
Mission impossible. This comes from an asset library, which i can't even locate. I had reported a typoe in the tooltip of the hair asset nodes a while ago . And it was fixed in a blend file called procedural_hair_node_assets.blend, which is in lib\assets\publish\geometry_nodes. But i cannot find the bit where this content appends to the add menu in the nodes editor.

**Comment by Draise14** [comment]
Yeah, close. All assets even from personal libraries will show here. All Geometry Node Groups. It's recursive.
