### ISSUE TITLE
Timeline Editor - Move "Set Start Frame" and "Set End Frame" up a level to the header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3416]
![bforartists_tl6kMMyMMz](https://user-images.githubusercontent.com/35357409/221382764-7f349228-c4a9-4d41-a843-60e61c053295.png)

# Issue
When you're working with a long shot with a lot of frame sequence to compo, preview, or when animating... you set the start and end of a frame sequence over and over and over again. Having this at a top level would be very nice. Right now you have to go to the edge of the timeline editor, go into Playback options, then use the buttons in the panel - which is quite the zigzag for an often used operator or two. 

## Solution:
Add a button to the left and right with icon to the left and right of the frame range start and end - so you can quickly mark the start and end of a sequence to playblast or render preview. 

Examples where this is used at a top level: Blackmagic Fusion , Adobe Premiere, and Nuke and Cinema 4D (with a frame range slider)

**Comment by ReinerBforartists** [comment]
More consistent would be in both cases behind the edit box. But i like the idea.

**Comment by ReinerBforartists** [comment]
Shall we use icons or text?

![iconsornot](https://user-images.githubusercontent.com/13919702/227715756-376570f8-520f-4103-ad53-2b7cfa8f1c6a.jpg)

**Comment by ReinerBforartists** [comment]
Tiny icons are tiny ...

![tiny](https://user-images.githubusercontent.com/13919702/227716106-8ff02400-ed37-4a16-a91d-06544cf6eafc.jpg)

**Comment by ReinerBforartists** [comment]
This would be your solution @Draise14 

Which one shall we use?

![draisesolution](https://user-images.githubusercontent.com/13919702/227716426-7c66f81a-af46-47aa-b78f-6a03b1bdd005.jpg)

**Comment by Draise14** [comment]
I'm loving that last one! ❤️ Normal button size feels more harmonious. Icon only is perfect.

**Comment by ReinerBforartists** [comment]
Perfect. Then it's final at that end :)

Now let's remove the tools from the option. They don't belong there anymore.

**Comment by ReinerBforartists** [comment]
Fixed in master. Updating manual.
