### ISSUE TITLE
Sequencer - Proxy "Set Selected Strip Proxies" double operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3419]
![pcoip_client_f61WZSTHCX](https://user-images.githubusercontent.com/35357409/221383737-5776ce3a-b2bc-42fb-955a-f5f75b7b60dd.png)

The button is the same as the check box.... hide one? It's confusing.

**Comment by ReinerBforartists** [comment]
Well. It's different operators. Above are general settings. Below for the selected strip. The strip proxy timecode panel appears when you have a movie clip selected. These are the settings for just this movie clip.

That the whole VSE is confusing is more a thing of how the Blender devs have shaped it. We can just fix it to some degree. And here i don't see a useful way. So i'll close this task as invalid.
