### ISSUE TITLE
Addons - Node Wrangler is repeated

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3421]
![image](https://user-images.githubusercontent.com/35357409/221384021-c89059ae-c802-447a-ba52-7daa6f418f27.png)

I am getting a warning that I have two node wranglers in the master. I looked into the master code, sure enough. Probably should keep.. one of them over the other.

**Comment by ReinerBforartists** [comment]
Check against the Blender node wrangler folder. Most probably a merge problem. Blender does not throw an error.

**Comment by ReinerBforartists** [comment]
Fixed
