### ISSUE TITLE
3D View - Object Mode - Add more "object" operators to toolshelf + view toggle for optional tabs

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3422]
![image](https://user-images.githubusercontent.com/35357409/221384279-806d494f-d49c-43ae-912b-85984598ce65.png)

Right now there are a lot of the the header operators that aren't in the toolshelf - but we have tabs and space to have them top level if necessary. 

I would love to have a lot of these in another tab or two with operators, atleast to a single level.

A couple of users asked why the toolshelf isn't complete (no select operators and not all the object operators) - maybe we can start making it more complete - or have toggleable sections like in the header toolbar. 

Consistency, user personalization, and top-level GUI access are design pillars we could hit by exposing these to the toolshelf.

**Comment by ReinerBforartists** [comment]
14 more tabs might crowd the tool shelf too much.

**Comment by Draise14** [comment]
This design proposal has two new tabs and tries to focus on one level deep as panels. 

But this can postpone for 3.6.

**Comment by Draise14** [comment]
I think I'll break this up.
