### ISSUE TITLE
Default Template - Brush name prefixes to make it easier to link and append between files

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3424]
# Issue 
Right now the default template has grease pencil, sculpt and other brushes all in the same brush category - I know Blender may overhaul this when brushes go to the asset library.. but till then there is no way to know what brush is for what - making appending or linking brushes a nightmare. 

We could do a quick fix to this. 

## Solution
![image](https://user-images.githubusercontent.com/35357409/221627439-88fbc49c-8036-41e8-b242-a840ab240ce9.png)

If we use prefixes, we can help define what brush is for what mode or object type - making it easier to append and link different brushes to and from Bforartists files. 

Grease Pencil = **as is**
Grease Pencil Sculpt = GP_S_
Grease Pencil Vertex + W = GP_V_W_
Sculpt = **S_**
Vertex + Weight = **V_W_**
Vertex Only = V_
Weight Only = W_
Texture Paint = T_

etc. 

### Reasons
I would like to include a better grease pencil and sculpt brush library that could come with the brush panel addon, meaning some good nomeclature would be necessary for a better user experience. We could also prepare the brush data and settings for the future when Brush assets become a thing, it would be neatly organized and ready to migrate to the new system if and when it happens.

**Comment by ReinerBforartists** [comment]
Just to remind, you don't need a feature request label anymore. I will moan when i am not green with a feature ;)

**Comment by Draise14** [comment]
I was doing some investigation - they do some crazy voodoo spagetti that appends and un-links a default brush pack with a Grease Pencil object, and some of the weight and vertex paint brushes are the one and the same brush settings.... 

![image](https://user-images.githubusercontent.com/35357409/223159652-0efe534e-42f0-40c2-8dec-16f377db7196.png)

So ultimately, we can only name the brushes that are NOT grease pencil brushes, and anything different is assumed different and should be tagged so - so worth naming only the different ones with prefix to not change any core code.

**Comment by Draise14** [comment]
ok, found a way to change name of GP defaults that isnt' too invasive in the `brush.cc` file

**Comment by Draise14** [comment]
Waiting on merge be done to merge in the master again, then commit this. I solved it. 

**Updates:**
- Added in the prefixes to all the brushes
- The Grease Pencil brushes and Sculpt brushes has some preset overrides, so those are changed in a deeper level.
- The rest is done by template.

**Comment by iyadahmed** [comment]
can be merged now ^^
