### ISSUE TITLE
Brush Panels addon: split sculpt brush panels to multiple tabs

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3425]
The sculpt mode has many panels and many brushes. The more brushes we add to this - the more bloated this will be.

So we need to create tabs per color category or group of brushes to make things manageable in the brush panel.

**Comment by Draise14** [comment]
Adding a bounty to this one!

**Comment by Draise14** [comment]
Postponed for 3.6.0

**Comment by Draise14** [comment]
Close but no cigar. But the idea of group the colours is about right! 

**Tabs:**
- Draw (blue)
- Surface (orange)
- Deform (yellow)
- Misc (others)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/964ca159-acc5-4483-8fcc-9bdfbd108e5b)

**Comment by ReinerBforartists** [comment]
Still the 24 pixel icons? O_O

**Comment by Draise14** [comment]
That's another task, still being worked on.
