### ISSUE TITLE
Brush Panels addon: fix misaligned icon buttons

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3427]
When using big icons the icon is not aligned well as you see in the picture, small icons work ok though for some reason

We could look at Blender's native Python toolbar, and see where we differ (UI scale or something),
even though the code should work as is, and this is probably an issue in Blender's C UI code

![image](https://user-images.githubusercontent.com/25552173/222214665-4379a35a-1672-4c36-881b-5f6df1501565.png)

**Comment by ReinerBforartists** [comment]
We differ in our implementation of the tabs :)

**Comment by iyadahmed** [comment]
Ah yes in the brush panels addon the big icons are misaligned for some reason,
even though same icons display fine in Blender original brush toolbar

**Comment by ReinerBforartists** [comment]
But they don't use our toolbar tab code

**Comment by ReinerBforartists** [comment]
The solution is simple. Use 16x pixel icons.

**Comment by Draise14** [comment]
Postponed for 3.6.0

**Comment by iyadahmed** [comment]
I think this is now fixed?

**Comment by iyadahmed** [comment]
Fixed in https://github.com/Bforartists/Bforartists/commit/62b4965a10e09308152c283ec7d277f217a407ad waiting for build to confirm

**Comment by Draise14** [comment]
I think this will need new custom icons assigned per brush type, like what we did with the Grease Pencil brush panel.

**Comment by Draise14** [comment]
![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2Qzb2tkM3NxZ3hqOW9uY3Npcm50cDJqZ2VsejJpcTk0bDV2NHYzOCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IwXLzyVC3qWogwp9Va/giphy.gif)

Assigned the brush icons here instead.
