### ISSUE TITLE
Remove number "1" being printed after closing the window

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3431]
Left over print statement 🤔 
![image](https://user-images.githubusercontent.com/25552173/222224337-9fc655e4-ab34-4b5f-b79b-8a24a58b9571.png)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/222229747-1e23adee-661e-426d-8b91-89eca6cefe88.png)

Probably from the Default Library, I have a bad habit of commenting what I do cause I don't know what's happening - this one got left behind.
