### ISSUE TITLE
Geometry Nodes - Mix Color and Mix Vector create wrong node

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3432]
Clicking the Mix Color and Mix Vector buttons in node shelf creates Mix Float nodes, needs to be fixed
![image](https://user-images.githubusercontent.com/25552173/222226905-eead15f7-7512-44ae-8a5b-fdffc55cb9a4.png)

**Comment by ReinerBforartists** [comment]
You're my hero :D
I still don't understand why my way didn't work. But i guess it is not longer important ^^
