### ISSUE TITLE
Geometry Nodes - Reverse Curve from add nodeshelf broken

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3436]
![bforartists_EpoyjktE69](https://user-images.githubusercontent.com/35357409/222277482-97a389f0-b4de-4943-9b0d-1d4a784b1bda.png)

Right now it seems this operator in the nodeshelf add panels (curve>operations panel) seems to be broken.

**Comment by ReinerBforartists** [comment]
You always manage to make screenshots so that you don't see which area it is ^^

Searching for the right panel ...

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/13919702/222365553-80524a92-1681-4183-b53c-f09da60c2a73.jpg)
