### ISSUE TITLE
3D View - Grease Pencil Object - Draw Mode - Download brushes needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3439]
![image](https://user-images.githubusercontent.com/35357409/223163845-8959da44-7491-4ead-9b9f-7fb7b7f662aa.png)

New operator that snuck through, you can now download Pepelands brush pack directly from the GUI - from the tool brush settings drop down for iconography, you can find the button there. It's not obvious, but it's there. 

Found it from a video. 

May also require documentation.

**Comment by ReinerBforartists** [comment]
Sure that this comes from BFA? Our regular menu does not show this entry.


![reset](https://user-images.githubusercontent.com/13919702/229080439-847c2980-3bd2-4fb4-991f-c2464836fb73.jpg)

**Comment by ReinerBforartists** [comment]
Yes, comes from the import brush pack addon.

Difficult chapter, we should not maintain addons. And the icon will most probably be gone with the next merge anyways ^^

**Comment by Draise14** [comment]
That's an addon?!

**Comment by ReinerBforartists** [comment]
Yep :)

Always test with defaults ^^

**Comment by Draise14** [comment]
Will close then.
