### ISSUE TITLE
The Outliner's header is missing all it's buttons and it's impossible to get them back

### ISSUE THREAD

**Issue by rossunger** [Bforartists/Bforartists#3446]
**Describe the bug**
The Outliner's header is missing all it's buttons. I didn't do anything to make this happen. Tried restarting and it still happens

**Desktop (please complete the following information):**
win10

**Screenshots, Example Files**
![image](https://user-images.githubusercontent.com/9280839/225413616-434b5d1f-32b7-4d01-938a-da2bfe02466f.png)

**Comment by rossunger** [comment]
I'm using bforartists 3.4.1 based one 3.5 alpha...
i can right click on the header and it looks like this:
![image](https://user-images.githubusercontent.com/9280839/225416255-99421fd1-8f89-4773-a14b-57602ddfc205.png)

The only thing I did that might be funky is that I copied my preferences folder in %appdata from Blender 3.4 to bforartists

The only errors I have in the console are:
Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.4.1\3.5\scripts\startup\bl_ui\space_outliner.py", line 24, in draw
    addon_prefs = preferences.addons["bforartists_toolbar_settings"].preferences
KeyError: 'bpy_prop_collection[key]: key "bforartists_toolbar_settings" not found'
Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.4.1\3.5\scripts\startup\bl_ui\space_toolbar.py", line 24, in draw
    addon_prefs = preferences.addons["bforartists_toolbar_settings"].preferences
KeyError: 'bpy_prop_collection[key]: key "bforartists_toolbar_settings" not found'
Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.4.1\3.5\scripts\addons\materials_utils\menus.py", line 121, in draw
    icon_value = material.preview.icon_id
AttributeError: 'NoneType' object has no attribute 'icon_id'
Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.4.1\3.5\scripts\addons\materials_utils\menus.py", line 57, in draw
    icon_value = material.preview.icon_id)
AttributeError: 'NoneType' object has no attribute 'icon_id'

**Comment by rossunger** [comment]
I fixed it. I deleted the preference files and it works now. Sorry to bother you!

**Comment by ReinerBforartists** [comment]
Glad you got it back working :)

Looking at the error message, it can be that you deactivated the addon by accident that is needed for the toolbar. There is no way to protect it, unfortunately.

![toolbar](https://user-images.githubusercontent.com/13919702/225421815-8f2ce7b1-6569-4023-918c-24494af7e879.jpg)
