### ISSUE TITLE
3D View - Sculpt Mode - Sculpt Header menu needs iconography and documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3447]
![image](https://user-images.githubusercontent.com/35357409/225429119-ff50df15-1056-41f3-a5d9-aca168a750f8.png)

New operators were added from the filter brush and transform brush also to the header - which means either removing due to redundency or adding iconography and documentation. 

I vote keeping these, it makes it easier for a user to directly right click and assign a hotkey or adding it to a quick menu.  

> Revision: da65b21e2e0169633b8ffe72fc0c59a921753792
> Sculpt: Add Transform, Trim, and Mesh Filter operators to Sculpt menu
> 
> Hello, this is a small PR to check that my understanding of #102427 is correct before moving on to the rest of the issue.
> This PR contains the updated UI of the `Sculpt` menu only. Other menus will be submitted for review later.
> 
> Currently exposed operators:
> * Move
> * Rotate
> * Scale
> * Box Trim (Trim Mode ="Difference")
> * Lasso Trim (Trim Mode ="Difference")
> * Box Add (Trim Mode ="Join")
> * Lasso Add (Trim Mode ="Join")
> * Line Project
> * Smooth
> * Surface Smooth
> * ~~Scale (Could be left out?)~~
> * Inflate
> * Random
> * Relax Topology
> * Relax Face Set Boundaries
> * Sharpen
> * Enhance Details
> * Erase Displacement
> 
> The original issue specifies `Relax Face Set Boundaries` and `Erase Displacement`. I'm not quite sure if this is done in the UI code or somewhere else.
> 
> Reviewed By: Joseph Eagar & Julian Kaspar
> Pull Request: https://projects.blender.org/blender/blender/pulls/104718
> ----
> Modified: scripts/modules/bl_keymap_utils/keymap_hierarchy.py
> Modified: scripts/presets/keyconfig/keymap_data/blender_default.py
> Modified: scripts/startup/bl_ui/space_view3d.py
> Modified: source/blender/editors/include/ED_sculpt.h
> Modified: source/blender/editors/sculpt_paint/sculpt_face_set.cc
> Modified: source/blender/editors/sculpt_paint/sculpt_filter_mesh.cc
> Modified: source/blender/editors/sculpt_paint/sculpt_intern.hh
> Modified: source/blender/editors/sculpt_paint/sculpt_ops.cc
> Modified: source/blender/editors/space_api/spacetypes.c
> 
>

**Comment by ReinerBforartists** [comment]
Holy ....

**Comment by ReinerBforartists** [comment]
We might want to put some content into sub menus. This looks amazingly crowded now.

**Comment by ReinerBforartists** [comment]
Holy molly, that's something to do here ...

**Comment by ReinerBforartists** [comment]
First step, add icons

**Comment by ReinerBforartists** [comment]
So much show hide ... 


![showhide](https://user-images.githubusercontent.com/13919702/227466609-a44495fd-2a81-47fc-a820-efda9bbb9331.jpg)

**Comment by ReinerBforartists** [comment]
16 icons to shape
![icons](https://user-images.githubusercontent.com/13919702/227477511-5298d096-d253-4341-a91f-b53e03f06206.jpg)

**Comment by ReinerBforartists** [comment]
![icons](https://user-images.githubusercontent.com/13919702/227507557-59c0691a-6b7f-48d3-a817-fafb52071f8b.jpg)

**Comment by ReinerBforartists** [comment]
Added icons. Unassigning for now.

**Comment by ReinerBforartists** [comment]
Postponing until after 3.5 release. Blender might fix the one or another thing here too ...

**Comment by Draise14** [comment]
This.. only is documentation now right? Seeing these here makes me thing of.. a new tab and panels.

**Comment by ReinerBforartists** [comment]
It is already documented. But we might want to put some things in sub menus. Show / Hide for example. And i guess Blender devs wants this too. That's why i said wait a bit. This menu will surely receive some refinement.

**Comment by ReinerBforartists** [comment]
Making a new task for the toolshelf entries

**Comment by ReinerBforartists** [comment]
Done
