### ISSUE TITLE
3D View - Sculpt Mode - New Operator Mask from Cavity needs iconography and documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3448]
![image](https://user-images.githubusercontent.com/35357409/225429861-25ee94bb-2e2f-4b36-bd3f-9426ddf950c1.png)

New operator means documentation and iconography.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/229614750-33176442-6108-4852-b64c-b154a6b1ab75.png)

Looks like this hit a regression, it's not in master at the moment..?

**Comment by ReinerBforartists** [comment]
Crazy enough, the commit shows that the icon was added ^^
