### ISSUE TITLE
3D View - Sculpt Mode - Face Sets - remove double "Show All Facesets"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3449]
![image](https://user-images.githubusercontent.com/35357409/225430325-bec42c97-8590-40fc-8a57-1fc857a28195.png)

This might be a regression, but an icon is missing - may need documentation.

**Comment by ReinerBforartists** [comment]
Looks like a double. Right above the operator is the same operator, with icon.

**Comment by Draise14** [comment]
Good point.

**Comment by ReinerBforartists** [comment]
Done
