### ISSUE TITLE
3D View - Sculpt Mode - remove missing operator "Dirty Mask"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3451]
![image](https://user-images.githubusercontent.com/35357409/225430828-b7c0997a-e539-4bce-a1bd-8b78dd4448b3.png)

It's gone from the Mask menu, was replaced with another.. related to #3448

**Comment by ReinerBforartists** [comment]
Fixed 
![mask](https://user-images.githubusercontent.com/13919702/227180530-592f8586-6dd1-4433-9cca-a10edd96376b.png)
