### ISSUE TITLE
3D View - Weight Paint - Remove the "vertex_group_fix" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3452]
![image](https://user-images.githubusercontent.com/35357409/225439614-75144498-3471-42b0-adbd-ed29235280e4.png)

Removed operator should be removed. Also from documentation. 

![image](https://user-images.githubusercontent.com/35357409/225439682-a7fd169e-8fb0-4e84-8aeb-57dfc0dfb631.png)

> Revision: f5c56b4cd6d87d7beaf20d34ad1aa71c7ea6701f
> Author: Sybren A. Stüvel <sybren@blender.org>
> Date: 3/2/2023 10:58:14
> Message:
> Animation: Remove the 'Weight Paint: Fix Deforms' operator
> 
> The code of the 'Fix Deforms' operator was hard to read and inefficient, doing `O(num_vertices * num_vertex_groups)` evaluations of the mesh. It caused multiple issues and got in the way of improvements to Blender, and seems to be used very little (if ever).
> 
> It was decided in [last week's module meeting](https://devtalk.blender.org/t/2023-02-23-animation-rigging-meeting/27757#patch-review-decision-time-5) that this operator should be removed.
> 
> Pull Request #105237
> ----
> Modified: scripts/modules/rna_manual_reference.py
> Modified: scripts/startup/bl_ui/space_view3d.py
> Modified: source/blender/editors/object/object_intern.h
> Modified: source/blender/editors/object/object_ops.c
> Modified: source/blender/editors/object/object_vgroup.cc

**Comment by ReinerBforartists** [comment]
Fixed
