### ISSUE TITLE
Asset Browser - Current File missing icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3460]
![image](https://user-images.githubusercontent.com/35357409/226695721-30c3e372-4803-42e3-af32-f080f5fa847c.png)

The "Current File" icon in the `space_filebrowser.py` is missing or broken.

**Comment by ReinerBforartists** [comment]
I can for the life of me not reproduce to flood the console with the needed warning here. How to reproduce?

**Comment by Draise14** [comment]
I'll try record the steps.

**Comment by ReinerBforartists** [comment]
Hmm. Blender has this icon. So we might want to create one.

**Comment by ReinerBforartists** [comment]
This is what Blender uses

![currentfile](https://user-images.githubusercontent.com/13919702/227285747-4513d44f-29c7-4aeb-898e-ed1b54edbbed.jpg)

**Comment by ReinerBforartists** [comment]
Draise, could you please check if adding the icon has fixed it? I am as told still lost how to reproduce this one, even when i have found the code bit for it.

**Comment by Draise14** [comment]
I'm migrating and rebuilding my environment on W11 now. Still out of action! I just got the upgrade of the decade and a new workstation.

**Comment by ReinerBforartists** [comment]
Meow?

**Comment by Draise14** [comment]
Yeah, no issue now. Can close.
