### ISSUE TITLE
Default Startup.Blend - Strokes Objects were saved.

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3462]
Notice this after a fresh compile, General shown below and one also in Sculpting Template .Blend

(General)
![Screenshot 2023-03-22 221424](https://user-images.githubusercontent.com/25260650/226891271-766dee99-d38d-4e93-b790-e12040730c4b.png)

(Sculpting)
![image](https://user-images.githubusercontent.com/25260650/226892039-e24f8cef-836a-4978-b244-a653ea41f676.png)

**Comment by ReinerBforartists** [comment]
And fixed. I also closed the gap in our toolbar while at it ...
