### ISSUE TITLE
Default Templates - All startup files needs polish

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3466]
The blend mode is wrong.

![wrongmode](https://user-images.githubusercontent.com/13919702/227162519-7c5a7a8b-084c-4a27-ae5a-52f65b65d4bf.jpg)

**Comment by ReinerBforartists** [comment]
Related task 

Default Template - Brush name prefixes to make it easier to link and append between files #3424

SHA-1: 0bef06038e9299021fd8e108e73b18903881fd36

**Comment by ReinerBforartists** [comment]
Now we really have a problem. Template cannot be reverted this easily. We end in the Blender defaults.

![problem](https://user-images.githubusercontent.com/13919702/227170390-5a3a6736-7be0-4fc9-b001-dbcee517d0c3.jpg)

**Comment by ReinerBforartists** [comment]
Draise, your turn. I unassign for now ...

**Comment by ReinerBforartists** [comment]
Does somebody remember how we solved the sds issue in the sculpting template before? I can't remember what we did ...

**Comment by Draise14** [comment]
I'll work this.

**Comment by ReinerBforartists** [comment]
May i remind to fix this one with highest priority? Blender 3.5.0 is to be released next week.

**Comment by Draise14** [comment]
Sure. I'm not at the computer today but will continue tomorrow. 

I'll have to postpone the select linked for the image editor task for 3.6.

**Comment by Draise14** [comment]
working, will commit soon.

**Comment by Draise14** [comment]
Ah the other defaults need the brush setup per mode. Not only sculp mode. I think I needed more specifics in the description. Thanks for clarifying 

Concerning the header... Hmm.. windows 11 changed the taskbar height which changes the default layout dimensions. So windows 10 will show the bar but not W11. And will happen viceversa.


Should I build this on a 1080p monitor on W11 still?

**Comment by Draise14** [comment]
- Made sure sculpting template starts on the draw brush
- Made sure the sculpt workspace has the tool tab open for the brush settings
- Also did this on W10 on a 1080p monitor, should get rid of that little bar (unless you are on a different monitor or OS scale. )

**Comment by Draise14** [comment]
If there is anything else in the template that needs improving, we can make a new task. I don't mid working these, I re-work these every point release for my left hand workflow often.

**Comment by ReinerBforartists** [comment]
Grabbing this one.

**Comment by Draise14** [comment]
This is not the sculpt template.

**Comment by Draise14** [comment]
I'm not sure how to fix the gap. I have a defaults taskbar on Windows 10, 1080p standard monitor, scale at 100% and it has no gap on my side. 

If you have any other resolution or GUI scale, it may show the gap.

**Comment by ReinerBforartists** [comment]
I have a 1920x1200 monitor. That's how i can fix it. 

But another question, what is this good for? 

![whatisthis](https://user-images.githubusercontent.com/13919702/228900741-aed731ba-612a-4e2e-9f67-535dce5dd0ab.jpg)

**Comment by Draise14** [comment]
Silhuette view, it's a Zbrush feature and standard, and a few addons have this and are paid to the same - when it could be free. You sculpt and do shape language with it - having it built in is something that can help many users that don't know you can do it. 

This could be another task, I have to admit - so if you want to remove it, go ahead.

**Comment by Draise14** [comment]
Ah ok, so 1200px tall would cover anything smaller, but since you'r larger than 1080px, you see the gap. Sucks any taller monitors will show the gap regardless of what you do..

**Comment by ReinerBforartists** [comment]
Yes, i know. The gap issue is just to solve when you have a monitor in the given height. I'll do this kind of task in the future. I thought you have a bigger monitor like i have.

For now let's remove the zbrush window i would say. It will imho confuse new users, and just a very small fraction will really benefit from it. Please make a issue if you want to add it to the defaults.

**Comment by ReinerBforartists** [comment]
Fixed
Fingers crossed ...
