### ISSUE TITLE
Node editors - Rename needs a top menu entry

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3470]
Currently Rename is just available in the right click menu. It needs a menu entry in the Node menu. All three node editors are affected. Compositor-, Shader- and Node Editor.

![rename](https://user-images.githubusercontent.com/13919702/228495807-1e007047-95d7-49ef-a246-238bb1b11d35.jpg)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/228680925-a39c54e5-6d3f-4061-8b95-350be4b40742.png)

Done. Should this be documented?
