### ISSUE TITLE
Fcurve Editor - Slider Operators - new Ease Operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3474]
![bforartists_2gkjVj6dV6](https://user-images.githubusercontent.com/35357409/228674446-7ea31152-052d-4a87-94b9-235254faca45.png)

Needs iconography and documentation.

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/228774128-089191df-9f4e-49d1-a46b-5468137de1cc.jpg)
