### ISSUE TITLE
Dopesheet - Right Click context menu - Extrapolation Method - Needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3476]
![bforartists_wGMe1SKALG](https://user-images.githubusercontent.com/35357409/228690755-28abdc45-2843-4022-9484-6817c41e9375.png)

![bforartists_zp5qVsqljk](https://user-images.githubusercontent.com/35357409/228690757-e965763a-7a7a-4405-81e8-88f1af877b35.png)

A context menu has a sub menu without icons. Probably should be fixed. 

Do these right click context menus need to be documented?

**Comment by ReinerBforartists** [comment]
Sure it needs documentation. Context menus are documented in the first chapter of an editor.

**Comment by ReinerBforartists** [comment]
Fixed in all editor types

![fixed](https://user-images.githubusercontent.com/13919702/228759972-a0636a95-15e6-4de4-b4c2-7721ec7b680a.jpg)
