### ISSUE TITLE
Solution to previously unsolved (but closed) issue: "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

### ISSUE THREAD

**Issue by muchuelo** [Bforartists/Bforartists#3480]
Issue was closed by ReinerBforartists with comment beginning "There is no solution, ...."

There IS a solution, and it's a simple one to implement. It's here: 

https://github.com/nalexandru/api-ms-win-core-path-HACK

It's pretty self explanatory.

**Comment by ReinerBforartists** [comment]
Hi muchuelo.

This is a hack at the user end. And, as told, nothing that we can fix. I unfortunately have to close it again.
Feel free to post it at our forum or at the Discord channel so that the "solution" does not get lost in case other users wants to use it.

Kind regards
Reiner
