### ISSUE TITLE
Toolbar - Missing operator "object.vertex_group_fix" in the edit weight group 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3484]
![bforartists_HHSuy4CHIw](https://user-images.githubusercontent.com/35357409/229184679-efcdab71-5fa9-4a92-8e1f-e4a9888e464d.png)

The Edit - Weight sub-group there is a missing operator in the toolbar. Probably should be removed.

**Comment by ReinerBforartists** [comment]
Definitely. Should be an easy fix. Don't forget to update the manual then.

**Comment by ReinerBforartists** [comment]
Okay, assigning, but this is the last one for a while ...

**Comment by ReinerBforartists** [comment]
Fixed
