### ISSUE TITLE
Bforartists App Image - GLIBC3.4 not found nor working on distros that are based on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3488]
> Bforartists 3.41 and 3.5 won't run: "Can't find Glibc3.4..." I'm on Debian 11 bullseye, and the AppImage won't even run on LXLE distro (tried in Live session) which is based on Ubuntu 20.04.4 LTS. At least the Appimage should work on a Ubuntu based system?

A report from Discord. 

> Got really curious about it, but apparently the Appimage doesn't run on Opensuse. 

A report from Twitter

Maybe the appimage is broken at the moment? I am about to head out and won't be back till Tuesday, so can't verify nor setup my remote environment again. Anyone else can test?

**Comment by ReinerBforartists** [comment]
Appimage should be independent from glibc. That's the whole purpose of Appimage  -.-

**Comment by ReinerBforartists** [comment]
As a note, 20.04 is pretty outdated. We have the 22.04 line now ...

**Comment by ReinerBforartists** [comment]
Does this sound familiar? https://github.com/RPCS3/rpcs3/issues/7465

I think we should report it to Appimage

**Comment by Draise14** [comment]
Does look familiar. I can't reproduce just yet till I get the VM's downloaded and working.

**Comment by ReinerBforartists** [comment]
Problem is that we build at Ubuntu 22. And it will not run on linux distributions with older libs then. Just newer. This even cuts off Debian in this case. Debian is known to be conservative. But we cannot return to Ubuntu 20. So there is little that we can do. 

https://discourse.appimage.org/t/will-a-new-appimage-run-on-older-distributions/84/2

> Yes, a “new” AppImage will run on “old” systems if you build on the oldest system you are targeting. The AppImage will run on this system and all newer systems. E.g., if you produce an AppImage on CentOS 6 then it will run on Ubuntu 16.04 just fine. 

I will close this issue now.

**Comment by ReinerBforartists** [comment]
I have at least updated the description at the webpage.
