### ISSUE TITLE
3D View - Weight Paint/Vertex Paint mode - New Operators Select More and Less

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3494]
![bforartists_MexzmfugNU](https://user-images.githubusercontent.com/35357409/231612736-ae4e16c9-501d-41eb-bd12-c8f30aafdeb6.png)

![bforartists_LyLAqTKy48](https://user-images.githubusercontent.com/35357409/231612863-902b9ab7-75e4-45e0-87e9-3fefcf97a1bd.png)

When in vertex and face mode of the weight paint and vertex paint mode - the select header entry has "Select More" and "Select Less"

We could do this:

1. Iconography
2. Remove the "Select" part of the name in the GUI since it's implicit in the header. 
3. Document it.

**Comment by ReinerBforartists** [comment]
In all other select menus the more less functionality is hidden in a sub menu. So putting this one into its own sub menu too , for consistency reasons.

![selectmenu](https://user-images.githubusercontent.com/13919702/231691263-ed3b1729-31eb-4d58-9af0-6d60c2552468.jpg)

**Comment by ReinerBforartists** [comment]
We miss the hotkeys too.

![hotkeys](https://user-images.githubusercontent.com/13919702/231692930-5a4220cb-b7a6-4fce-b706-519a127d4519.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![select](https://user-images.githubusercontent.com/13919702/231708176-cd1cf351-eddd-4c3b-aaef-b6b1b66c5395.png)

![select2](https://user-images.githubusercontent.com/13919702/231708187-89eb2e7c-f7b8-4c94-874e-b49d4b88ca9d.png)
