### ISSUE TITLE
Socials - Add mention that this is an opensource project

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3495]
A user on twitter asked if this was opensource, the suggested we probably should mention it. We are totally opensource - but it is taken for granted that we are. We should be explicit about it. 

# Task
Mention the opensource nature of the project on the homepage.

**Comment by ReinerBforartists** [comment]
We already do. Bforartists is a complete, free and **open source** 3D suite to create CG content.

**Comment by Draise14** [comment]
Hmm.. wonder how that was missed. Maybe I should mention it in twitter, youtube and facebook more explicitly?

**Comment by Draise14** [comment]
Twitter and facebook is ok.. I will close this.
