### ISSUE TITLE
Addon - All Headers - Add operator to select the floating panel (to make it easy to assign hotkeys and make discoverable)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3500]
![image](https://user-images.githubusercontent.com/35357409/232820156-bcd76602-e698-43a6-8a31-688f1654806a.png)

Seeing what I found I could do with the select linked in the image editor in the https://github.com/Bforartists/Bforartists/issues/3204 task, maybe we can add a floating panel button to the GUI on all sub-menus everywhere so you can quickly "right click and assign hotkey" to any floating menu a user may want to use then we wouldn't need to assign any hotkeys - leave it up to the user.

This will also make all hidden floating menus exposed to the GUI with their hotkeys (if they exist).

And they all could have the same icon too, and placed in the header or footer of the menus. 

Right now to assign a floating panel addon, you need to know the operator to call menus, know the location they are in, then know their panel name (unknown unless you can read the python). It's not user friendly. 

An example I was trying out that sourced the idea:
![bforartists_BRr7xkswRr](https://user-images.githubusercontent.com/35357409/232822352-c42b73d3-8513-4ae3-89ee-a76d16d2667d.png)

## Pros
- User can discover floating panels
- User can right click and assign hotkeys whenever they want
- This will solve the issue of many blender hotkeys users like, and make it easier for them to get them back (ei, Select Similar can easily be applied per user request) 

## Cons
- Adds an extra seperator and operator to all sub-menus
- Is a big task, might need splitting up.

**Comment by ReinerBforartists** [comment]
This is a monster task. And we should only have one hotkey to call hidden floating menus. Right click ...

**Comment by Draise14** [comment]
Yeah, in an ideal world - but Blender has all menus potentially floating, and they are "hidden" in the GUI. We expose all things hidden in GUI, and if we were to follow most industry software standards, these panels could be "torn" to pin and float from anywhere permenantly... but alas, that's not gonna happen anytime soon. This would be the next best thing, atleast to show the arquitecture below. We can't hide and pretend the floating menus don't exist. 

But yeah, it's a big task... probably should be split up per editor.

**Comment by ReinerBforartists** [comment]
Yeah, Blender. But we are Bforartists :)

**Comment by Draise14** [comment]
Right click on the sub menu to assign hotkey, yeah that would be nice. A bit hidden, but nicer. But yeah, that would be another level challenge of code that.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/232838905-aa01f234-d001-498f-89fc-1430d1e948df.png)

I wonder if it's possible, I mean the quick favorites detects the right click on the sub-menu - adding that little "Assign Hotkey" riiiiight here would be awesome.

**Comment by ReinerBforartists** [comment]
Yes. That would be awesome

**Comment by ReinerBforartists** [comment]
What about the idea to manage this by an addon instead? I hate to crowd the UI even more ...

**Comment by Draise14** [comment]
Yeah.. could be a better idea. I think the right click idea is cool, but that's probably better at blender or on downtime experiment time. 

The addon and entries could then a user preference.

**Comment by Draise14** [comment]
A friend of mind has started the attempt already with a step up, a dreamed UX I've wanted a while. 

Blender Tear Off Menu
https://github.com/adamearle/Blender-Tear-Off-Menu/tree/main

**Comment by ReinerBforartists** [comment]
That's why we have the tabs. They stay open.

**Comment by Draise14** [comment]
The I guess we have to make the tabbed toolshelf more consistent and complete with the header menus... In some cases sub menus and operators are not shown in the tabbed toolshed panels.

Maybe more customizable? Show sub menus toggle?

**Comment by ReinerBforartists** [comment]
It plays against the non overlapping UI design. That's my concern with this approach. You will sooner or later end in a dozen open floating panels and start to sort them out of the way all the time: I know this game from many other software that utilizes floating panels.

**Comment by Draise14** [comment]
Having used Autodesk Softimage for 5 years, Fusion some, and knowing a lot of Max and Maya users, they often miss this, including myself (though the toolshelf and toolbar help ease that need for it). If this were ever developed or possible, I would maintain it as opt-in and de-activated per default. It is somewhat popular a user request per Rclickselect and talking to users I know coming from elsewhere, it's a hot feature people would like. 

https://blender.community/c/rightclickselect/T8gbbc/?sorting=hot
https://blender.community/c/rightclickselect/0Llv/?sorting=hot

But yes, it would be a against the GUI of no overlapping panels, thus keeping it off could be nice.

**Comment by ReinerBforartists** [comment]
Will close this one. You can in fact already assign shortcuts to every menu that is present in the UI. Without any further complication.

![works](https://github.com/user-attachments/assets/1d55377b-d1fe-46a0-8f31-3974d9151423)

**Comment by Draise14** [comment]
What.. when did they add this!? Nice. Had no idea.

**Comment by ReinerBforartists** [comment]
Me neither. I just checked some old issues here ^^
