### ISSUE TITLE
Node Editors - Exit Group menu entry now up arrow now permenant - revert

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3509]
### Discussed in https://github.com/Bforartists/Bforartists/discussions/3493

<div type='discussions-op-text'>

<sup>Originally posted by **Draise14** April 13, 2023</sup>
![image](https://user-images.githubusercontent.com/35357409/231610079-b62a6dba-adcf-47b5-bce9-d0731246ee3c.png)

Blender now shows the Exit Group menu entry, even if it's not a group - it's now permenantly in the header and when you can't go "up" it will grey out. 

Question:
Should we.. revert this? Make this hide when on surface level instead of disable? 

**Commit in Question**
https://projects.blender.org/blender/blender/pulls/106643</div>

**Comment by ReinerBforartists** [comment]
Let's hide it away instead of greying out

**Comment by ReinerBforartists** [comment]
Turns out to be a bit more complicated. I have no idea how to determine if we are in a group or not. Python API wasn't this helpful so far.

**Comment by ReinerBforartists** [comment]
No idea. Unassigning

**Comment by iyadahmed** [comment]
> No idea. Unassigning

Maybe we could check if parent is None 😄 this means top lovel can't go back up any further

**Comment by ReinerBforartists** [comment]
I haven't found how ^^

**Comment by Draise14** [comment]
The way to leave groups by the arrow was there before this patch, reverting the patch won't remove that - only on a top top level they decided to show it with this particular patch, which is greyed out now. Previously, there was no arrow if you are on a top level, but an enabled arrow if you were one level in.

**Comment by ReinerBforartists** [comment]
Did i miss something? :D

Do you have the patch?

**Comment by Draise14** [comment]
Yes, Blender worked like this BEFORE their committed patch, it's reverting their patch listed in the description to hide the top level greyed out arrow.

**Comment by ReinerBforartists** [comment]
Okay :)

**Comment by Blenux** [comment]
So like this?


https://user-images.githubusercontent.com/25260650/235430692-2659249f-1348-48a1-a3e2-344208a62e00.mp4

**Comment by ReinerBforartists** [comment]
Exactly like this :)
