### ISSUE TITLE
Can't run Bforartists from inside Visual Studio

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3510]
I opened the CMakeLists.txt using Visual Studio (it supports it)
![image](https://user-images.githubusercontent.com/25552173/233918334-1734459c-ea57-40cb-83ad-4fb073844acd.png)

Mean while in Blender I'm able to run it
![image](https://user-images.githubusercontent.com/25552173/233918547-210c80ba-278c-4e0b-a1b7-db1a3d070d3e.png)

This could be a bug from our modifications in CMake files

**Comment by ReinerBforartists** [comment]
O_O

**Comment by ReinerBforartists** [comment]
Or the one is compiled and the other not. Which cmakeliusts.txt file is it? The one in root?

**Comment by ReinerBforartists** [comment]
The only difference is that we have replaced the term Blender by Bforartists. Possible that we miss a path somewhere else that still points to Blender instead. But good luck finding the needle in the haystack.

**Comment by iyadahmed** [comment]
> Or the one is compiled and the other not. Which CmakeLists.txt file is it? The one in root?

I opened both in the exact same way, yep both in root

**Comment by iyadahmed** [comment]
False alarm deleting things and opening from scratch works
![image](https://user-images.githubusercontent.com/25552173/234132830-da803b21-574b-4d9e-b57d-c97e2b5928c5.png)
