### ISSUE TITLE
File Browser - New OS File operations in context menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3516]
![image](https://user-images.githubusercontent.com/35357409/236638238-693de5dd-f774-4158-889c-8fc5a9cf1561.png)

New Operation System file operators need iconography and documentation. This may also need to be exposed to header operators for discoverability. 

Take note, some icons were regressed here. Oops... 
![image](https://user-images.githubusercontent.com/35357409/236638257-af288ee0-7159-46a4-bc71-3f0ec71a8078.png)

**Relevant task**
> SHA-1: 694f792ee186f236036b487d63bfb15945a88082
> 
> * UI: OS File Operations Within File Browser
> 
> Adds a submenu to the File Browser selected item context menu that
> allows opening the item or viewing the location in an OS browsing
> window. On Win32 also allows other actions like editing, searching,
> opening command prompt, etc.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/104531

**Comment by ReinerBforartists** [comment]
One task for one Issue please.

**Comment by ReinerBforartists** [comment]
This task is to fix the icons.

**Comment by ReinerBforartists** [comment]
There is more than just two menu items. It is an enum with 15 menu items. And the content shows dependant of where you right click at.

And this means, this menu cannot be exposed to the regular gui anyways.

![more](https://github.com/Bforartists/Bforartists/assets/13919702/127f2182-4643-4f21-bc3d-49cc12dc27c4)

![enum](https://github.com/Bforartists/Bforartists/assets/13919702/4466db66-48ba-4fa3-89f4-fe0ce6b87cbd)

**Comment by ReinerBforartists** [comment]
U kidding me? -.-

![kidding](https://github.com/Bforartists/Bforartists/assets/13919702/e79ae049-6592-4f2e-a778-dc3b88883032)

**Comment by ReinerBforartists** [comment]
There is no error, the icons are at the right place, the header contains the needed includes to work with icons, but they are simply not displayed in the menu. Curious.

![nogo](https://github.com/Bforartists/Bforartists/assets/13919702/1354e706-11bf-41e7-a71e-743780bdabb7)

**Comment by ReinerBforartists** [comment]
This is the place where the menu is drawn. But it uses the enum. The icons should arrive. 

No idea, unassigning.

![ifelse](https://github.com/Bforartists/Bforartists/assets/13919702/bbdaa9e5-a10b-41ad-b664-a8d26926d8ed)

**Comment by iyadahmed** [comment]
> @iyadahmed , do you have an idea here?

apologies for delay just saw message, working on it now ^^

**Comment by iyadahmed** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/25552173/f14ad7b8-e154-4add-934d-9ea9083b99ea)

**Comment by ReinerBforartists** [comment]
Awesome :)
I knew we had to add our icon somewhere, just didn't know where :)

**Comment by ReinerBforartists** [comment]
Don't forget documentation ...

**Comment by ReinerBforartists** [comment]
Made it a task

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/da39edb4-75cc-4dd1-9100-2a3528d73839)

Looks like we have a regression, also went out to release.. damn.

**Comment by ReinerBforartists** [comment]
That's a lot of regressions lately.

**Comment by ReinerBforartists** [comment]
Fixed

And i know why it was removed in the next merge. The changed code to draw the icons wasn't commented. Now it is.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/56c4af99-61ee-4bfc-912a-5376e4ce39e0)
