### ISSUE TITLE
3D View - Text Object - Edit Mode - New move to test start/end operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3517]
![image](https://user-images.githubusercontent.com/35357409/236638356-0a7ea1fe-97ba-47d8-b736-a78c04242fab.png)

New Text Begin and Text End operators on the text object need iconography and documentation. 

> SHA-1: 6d2351d26bd60308ed155b226bcf15c61a66e7c0
> 
> * Text object: operators to move cursor to the top or bottom
> 
> This adds new movement types TEXT_BEGIN and TEXT_END to allow
> FONT_OT_move and FONT_OT_move_select operators move the text
> cursor (caret) to the top and bottom of the text.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/106196

**Comment by ReinerBforartists** [comment]
Added icons

Documenting.

![added](https://user-images.githubusercontent.com/13919702/236781924-7ced5f4a-ec25-43c7-ab7a-5cd1c98c2119.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
