### ISSUE TITLE
Default Hotkeys - Add CTRL+TAB to use Object Mode pie menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3518]
![image](https://user-images.githubusercontent.com/35357409/236638558-647abfde-a62c-4a81-89c1-6c9eeaf961ff.png)

Right now with some objects, like the Text Object, swapping out of the edit mode to object mode is impossible, since hitting 1 will write 1 instead of go to object mode. If the CTRL+TAb default for the object pie menu was a default, this would not be an issue.

**Comment by ReinerBforartists** [comment]
Ah the key manager ... Adding the hotkey from the menu adds it to the wrong category. It gets added in the Windows category. It should be added to 3D view / object non modal though.

**Comment by ReinerBforartists** [comment]
Fixed it manually now. Hotkey shows in the menu. At least this ...
![hotkey](https://github.com/Bforartists/Bforartists/assets/13919702/1c66c182-2452-4e57-9a88-586f85ad9ab2)
