### ISSUE TITLE
3D View - Grease Pencil Object - Weight Paint - Option Autonormalize added, align left and document

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3519]
![image](https://user-images.githubusercontent.com/35357409/236638679-3e1e7d96-4729-4452-b398-4e500e32e263.png)

New property in the Options panel of the grease pencil weight paint tools "Autonormalize" need to align left per standards and also needs documentation. 

**Relevant Task:**
> SHA-1: 397a14deff2d72b0e5614069c6de29b1e9efb084
> 
> * GPencil: Several Weight Paint additions
> 51
> This patch adds several tools and options to the weight paint mode of Grease Pencil.
> 
> * Blur tool: smooths out vertex weights, by calculating a gaussian blur of adjacent vertices.
> * Average tool: painting the average weight from all weights under the brush.
> * Smear tool: smudges weights by grabbing the weights under the brush and 'dragging' them.
> 
> * With the + and - icons in the toolbar, the user can easily switch between adding and subtracting weight while drawing weights.
> * With shortcut `D` you can toggle between these two.
> 
> * The auto-normalize options ensures that all bone-deforming vertex groups add up to 1.0 while weight painting.
> * With `Ctrl-F` a radial control for weight is invoked (in addition to the radial controls for brush size and strength).
> * With `Ctrl-RMB` the user can sample the weight. This sets the brush Weight from the weight under the cursor.
> 
> * When painting weights in vertex groups for bones, the user can quickly switch to another vertex group by clicking on a bone with `Ctrl-LMB`.
> For this to work, follow these steps:
> * Select the armature and switch to Pose Mode.
> * Select your Grease Pencil object and switch immediately to Weight Paint Mode.
> * Select a bone in the armature with `Ctrl-LMB`. The corresponding vertex group is automatically activated.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/106663

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/13919702/236670450-a3fdeb0d-4622-45a7-9240-22ae76a41911.png)
