### ISSUE TITLE
3D View - Greasepencil Object - Weight Paint mode - new tools in Toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3520]
![image](https://user-images.githubusercontent.com/35357409/236638914-5fe42ee2-b59e-4bf6-84d3-efd23fcb1828.png)

New grease pencil weight painting functionality is added, meaning new default hotkeys and GUI discoverability - also documentation.

New tools in the toolshelf
- Blur
- Average
- Smear

New Hidden Operators from Blender Hotkeymap:
- CTRL+LMB to select bones
- CTRL+RMB to sample weight
- D to swap plus and minus
![image](https://user-images.githubusercontent.com/35357409/236639008-00aae73b-3b45-42db-9f23-dfb878e5e021.png)

Documentation Update:
- Weight silder in the RMB context menu
- + and - icons in the toolbar

![image](https://user-images.githubusercontent.com/35357409/236639015-803d7ee7-95e6-4dbe-b78c-c51a35f2f3ff.png)
![image](https://user-images.githubusercontent.com/35357409/236639025-f71ec0db-2a3b-4619-809d-508fd5d01021.png)

Tasks:
1. Add Select Bones to header, could be in the Weight sub header menu
2. Add Sample Weight to header, could be in the Weight sub header menu
3. Add swap button to plus and minus for user discoverability (similar to vertex paint and texture paint)
4. Document the rest
5. Add hotkey V for weight strength, same standard as the other paint modes 

If this becomes too big, split to another task, refer this one. 

**Relevant Blender Task:**
> SHA-1: 397a14deff2d72b0e5614069c6de29b1e9efb084
> 
> * GPencil: Several Weight Paint additions
> 
> This patch adds several tools and options to the weight paint mode of Grease Pencil.
> 
> * Blur tool: smooths out vertex weights, by calculating a gaussian blur of adjacent vertices.
> * Average tool: painting the average weight from all weights under the brush.
> * Smear tool: smudges weights by grabbing the weights under the brush and 'dragging' them.
> 
> * With the + and - icons in the toolbar, the user can easily switch between adding and subtracting weight while drawing weights.
> * With shortcut `D` you can toggle between these two.
> 
> * The auto-normalize options ensures that all bone-deforming vertex groups add up to 1.0 while weight painting.
> * With `Ctrl-F` a radial control for weight is invoked (in addition to the radial controls for brush size and strength).
> * With `Ctrl-RMB` the user can sample the weight. This sets the brush Weight from the weight under the cursor.
> 
> * When painting weights in vertex groups for bones, the user can quickly switch to another vertex group by clicking on a bone with `Ctrl-LMB`.
> For this to work, follow these steps:
> * Select the armature and switch to Pose Mode.
> * Select your Grease Pencil object and switch immediately to Weight Paint Mode.
> * Select a bone in the armature with `Ctrl-LMB`. The corresponding vertex group is automatically activated.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/106663

**Comment by ReinerBforartists** [comment]
So what is the task here? I mainly see documentation.

**Comment by ReinerBforartists** [comment]
Ah here it is.,

> Add Select Bones to header, could be in the Weight sub header menu
> Add Sample Weight to header, could be in the Weight sub header menu
> Add swap button to plus and minus for user discoverability (similar to vertex paint and texture paint)
> Document the rest
> Add hotkey V for weight strength, same standard as the other paint modes

Unfortunately four tasks in one. Please just one task per issue :)

**Comment by Draise14** [comment]
Time to split

**Comment by Draise14** [comment]
Split, found a bunch of things a long the way. Will close this.
