### ISSUE TITLE
Geometry Nodes - New Index of Nearest node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3522]
![image](https://user-images.githubusercontent.com/35357409/236640115-dd97c2d0-e38f-40a3-b553-cb5d8b8ab69e.png)

Found in Geometry - Sample add menu. Needs to be documented, new icon, and placed into the toolshelf respectively.

**Comment by ReinerBforartists** [comment]
No idea what icon i should shape here

**Comment by ReinerBforartists** [comment]
Fixed in master

Documenting ...


![fixed](https://user-images.githubusercontent.com/13919702/236769794-08a00358-f2f7-4d7e-a1c3-312254238b67.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
