### ISSUE TITLE
Fcurve Editor - Header - Frame Selected Channels has a missing icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3523]
![image](https://user-images.githubusercontent.com/35357409/236640445-003d8bea-9056-47c6-a7a5-b8d988fd3f1f.png)

Overlooked operator from the context menu has a missing icon. The context menu has it already, so just make it consistent. 

![image](https://user-images.githubusercontent.com/35357409/236640461-6f20bcd1-4804-4ea6-962f-cdbbccbaae2e.png)

**Comment by ReinerBforartists** [comment]
Fixed

![move](https://user-images.githubusercontent.com/13919702/236668155-f22401bd-8174-4a6b-9a73-230046b0e2c0.png)
