### ISSUE TITLE
Fcurve Editor - Insert Only Active Keyframes needs iconography and documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3524]
![image](https://user-images.githubusercontent.com/35357409/236640513-78d413ca-8f6a-485d-8020-a5beae959a4e.png)

New method to insert hotkeys in the dopesheet. Needs iconography (same) and documentation.

**Comment by ReinerBforartists** [comment]
Fixed
![insert](https://user-images.githubusercontent.com/13919702/236667436-18d5eb2d-3d3d-4918-b9a2-cd8199390805.png)
