### ISSUE TITLE
3D View - Add new tab and panels for the Tools from the Toolbar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3525]
![image](https://user-images.githubusercontent.com/35357409/236641776-4c88edfe-0872-4726-8e66-72a966e743f4.png)
A few users have requested this, so I thought to avoid bloat, and for user preference, have an additional tab with panels from remaining common operatores from the toolshelf as we would for the toolbar.

The first tab could have these operators for the object mode: Each section is a panel. 

Tab Name:
- Relations

Panels:
- Parent
- Object Data
- Link to SCN
- Linked Objects
- Join
- Data Transfer
- Relations

In this case we don't need ALL object tool operators but have user preference, either toolbar, or toolshelf. 
![image](https://user-images.githubusercontent.com/35357409/236641671-171090d4-0ce2-4d98-bc50-5356a2691c3e.png)
_Ignore "Assets" in this capture_

**Reference Idea:** 
#3422

> Right now there are a lot of the the header operators that aren't in the toolshelf - but we have tabs and space to have them top level if necessary.
> 
> I would love to have a lot of these in another tab or two with operators, atleast to a single level.
> 
> A couple of users asked why the toolshelf isn't complete (no select operators and not all the object operators) - maybe we can start making it more complete - or have toggleable sections like in the header toolbar.
> 
> Consistency, user personalization, and top-level GUI access are design pillars we could hit by exposing these to the toolshelf.

**Comment by ReinerBforartists** [comment]
As a note, we haven't updated the toolbar at the top for a pretty long time now. There is vice versa quite a few new things that could go there. The culprit is always, Blender's tool system mostly requires to use the tool in the right context, means most tools does not work from the toolbar since it is another editor ...

**Comment by ReinerBforartists** [comment]
Postponing

**Comment by Draise14** [comment]
This could be one new tab with all those operators. Will have to look in the header.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8f833186-6fb7-49b6-a575-61aa3447184f)

Tab Name: Relations (like in the Node Tab Shelf)

I'll make another task for a Misc tab, which would be nice to have these exposed to a top level sometimes, specially the convert panel....... I use that one a lot, and rigid body assignments.

**Comment by Draise14** [comment]
Nearly done. Called it "Utilities Tab" and won't do another - the animation, rigid body, show/hide/cleanup and quick effects, and subdivide... those are rare use cases. The others are more popular. Convert is used a lot.

**Comment by Draise14** [comment]
Huh, there is only mention of the tabbed toolshelf, but the operators are all listed once in the headers - so I guess... this doesn't need extensive documentation?

**Comment by Draise14** [comment]
https://github.com/Bforartists/Bforartists/assets/35357409/9f235f22-14fe-44d2-9ce5-d52df22b6e6b

Here it is.

**Comment by Draise14** [comment]
Nice to do some fan service, will use this. The convert panel, will save me a complex hotkey.

**Comment by ReinerBforartists** [comment]
> Huh, there is only mention of the tabbed toolshelf, but the operators are all listed once in the headers - so I guess... this doesn't need extensive documentation?

Correct :)
