### ISSUE TITLE
Default Startup - 3D View - Default tool mode should be "Active Tool".

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3526]
![image](https://user-images.githubusercontent.com/35357409/236649591-c0e5b66b-c495-4a62-be06-5491735171e4.png)

This is setup in the startup blends lost something we had as a default - and most tools should default to their tool setting - not tweak. We have `D` to tweak. 

Other task that got reverted. 
https://github.com/Bforartists/Bforartists/issues/3073

**Comment by ReinerBforartists** [comment]
Yeah, this is most probably one of the accidental changes of the startup.blend files that could not be reverted ....

**Comment by ReinerBforartists** [comment]
Task is invalid. @Draise14 , always make sure to remove all data in the appdata directory before testing such things.

![invalid](https://user-images.githubusercontent.com/13919702/236666602-45030f36-93a8-4633-b83e-8a0adea1fe85.jpg)
