### ISSUE TITLE
Add icons to import/export .3ds menu entry

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3531]
We have icons for those but they are not set for some reason (maybe happened in a merge), in any case the .3ds addon is not activated by default (even in Blender), but we can still set the icons
![image](https://github.com/Bforartists/Bforartists/assets/25552173/683e0700-f938-4edb-b878-7768270c698c)

**Comment by ReinerBforartists** [comment]
Yes, a merge regression

**Comment by ReinerBforartists** [comment]
Nope, no merge regression. 3DS addon did not exist anymore in version 3.4.0 or even earlier. The addon was removed at one point, and readded now. And it is also not activated by default. We also need to activate it in BFA first.

But the icons still exists. So i have readded them to the addon.

![one](https://github.com/Bforartists/Bforartists/assets/13919702/66c4cd28-712e-4280-985c-48916f5629de)

![two](https://github.com/Bforartists/Bforartists/assets/13919702/1ccdcb6a-94f5-4547-93e8-bd204d2e3ab5)
