### ISSUE TITLE
User Preferences - Expose Save Preferences to header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3532]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c088054e-1544-43b8-b587-a543f2a012f9)

Right now when you add a hotkey to the GUI, or change the tool bar settings or sometimes addon prefs - you have to go into user preferences, go into a sub menu, then hit save preferences. This is very annoyingly slow. Autosave also is useless here, saving startup also. 

It would be nice to have a force save at the top level in the Edit header menu. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/05a7f171-2d1d-4ab3-9623-56353344cdd8)

**Comment by ReinerBforartists** [comment]
Autosave should handle this. It does not?

**Comment by Draise14** [comment]
Nope, doesn't handle it.

**Comment by ReinerBforartists** [comment]
Mh, does Blender update in this case? Could be worth a bug report

**Comment by Draise14** [comment]
I think it stops working and only autosaves settings from the most recent instance of Blender, and one at a time. If I have multiple versions, only the most recent autosaves, but any changes to the original instance won't autosave. This is probably why it's not working for me on most cases.

**Comment by ReinerBforartists** [comment]
Yeah, and this is a bug in Blender then. Just tested, adding a hotkey works fine here. Changing the toolbar works fine. Addon prefs works fine.

The point is, the save preferences feature is hidden for good reason.

**Comment by ReinerBforartists** [comment]
The problem is, 99% of the users will not need it in their whole life. So everything speaks against putting it into the main toolbar.

What about you add a hotkey for it?

**Comment by Draise14** [comment]
I found an addon that made an op for it, then a hotkey does it or quick menu. I guess you're right, it's a rare case you have more than multiple instances of the software open.
