### ISSUE TITLE
Fcurve Editor - Key header menu - rename "Jump To Keyframe" -> "Jump to Selected"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3539]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e2bfea33-1c76-4ecb-9f63-c9a98f1762c0)

Blender change, makes sense. Didn't merge it in nicely, so will do it here. 

<details>
<summary>Relevant Blender Task</summary>
SHA-1: 5e1470d1b3eb219bfabfab6cb524421fef8cec3d

* Animation: Clean up "Key" menu in Graph Editor

* remove "Keyframe" label from the Key menu
* "Jump To Keyframe" -> "Jump to Selected"
* added a new menu "Density" with Decimate, Sample and Clean operators
* removed the "Clean Channels" entry. It does the same as the "Clean" operator but also removes channels IF the remaining keys are at the default value. The feature is still available in the redo panel
* Split the slider operators out by functionality
* Move Euler filter to Channel menu
* Remove "Add F-Curve modifier" from Key menu (it already is in the Channel menu)
* Move Bake/Unbake Curve functions to Channel menu
* Move "Bake Sound to FCurves" to Channel menu

Pull Request: https://projects.blender.org/blender/blender/pulls/106113

</details>

**Comment by ReinerBforartists** [comment]
Not fixed. Half of the menu is missing. Most probably a merge regession.

![error](https://github.com/Bforartists/Bforartists/assets/13919702/1530bc38-2e3e-4a1b-a9cf-ca4d60111b88)

**Comment by Draise14** [comment]
Yeah, they moved these to the channels, and we haven't added them back. That's why I made tasks for them.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f7aff372-33a4-4b41-83e0-4df9d72ff388)

Fixed the missing menu entries, should be more aware of these nuances next merge. Still learning! My bad.

**Comment by ReinerBforartists** [comment]
> ![image](https://user-images.githubusercontent.com/35357409/241750406-f7aff372-33a4-4b41-83e0-4df9d72ff388.png)
> 
> Fixed the missing menu entries, should be more aware of these nuances next merge. Still learning! My bad.

No apologies needed. This is development :)
Glad you got it fixed !
