### ISSUE TITLE
Splash Screen UI - First launch error.

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3542]
Line 3170 was commented out in #3533, causing this issue at **first launch only,** after first launch it goes away.

![image](https://github.com/Bforartists/Bforartists/assets/25260650/2ac8461f-2481-41dc-8699-9007f4769c2b)

```
Python: Traceback (most recent call last):
  File "C:\Blender-Git\bfa_build_windows_x64_vc17_Release\bin\Release\4.0\scripts\startup\bl_operators\wm.py", line 3171, in draw
    if label == "Presets":
UnboundLocalError: local variable 'label' referenced before assignment
```

![image](https://github.com/Bforartists/Bforartists/assets/25260650/f023ffa3-f361-477c-8bd7-d75e04f29dc1)

**Comment by ReinerBforartists** [comment]
Can confirm

**Comment by Draise14** [comment]
Oops. Sorry. For some reason it was like that before? I've been sick and not in full order. Feel free to commit the fix.

**Comment by Blenux** [comment]
Done, get well soon @Draise14

**Comment by ReinerBforartists** [comment]
> Oops. Sorry. For some reason it was like that before? I've been sick and not in full order. Feel free to commit the fix.

All good. That's what the tracker is good for :)

And get well soon from me too !
