### ISSUE TITLE
Hotkeys - Animation Editors - Select Channel Range more with CTRL

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3545]
![blender_DJ0Cbv3M7L](https://github.com/Bforartists/Bforartists/assets/35357409/631117d6-992e-4c61-b933-7e43523bac60)
To keep consistent with the outliner, (and to accomodate new features from Blender) we probably should update the ability to select channel ranges while holding down SHIFT+LMB and select additional with CTRL+LMB.

**Relevant entries**
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ec4e100b-d337-4bf2-bf5f-85a52318404e)

**Current in BFA**
![image](https://github.com/Bforartists/Bforartists/assets/35357409/7c2ecbc0-284c-446d-a428-30d7253d9116)

**Relevant Blender Task:**

> SHA-1: 80feb136653195551ae0b5bd49567d57e0ed6810
> 
> * Allow select range in animation editor
> 
> This patch will add support to select all channels between active channel
> and last-clicked channel without deselecting previous selection. `Shift` key is
> now assigned for the range selection and `ctrl` key to extend the selection. This
> changes will make multi-selection similar as outliner tree-elements. New function is
> created `animchannel_select_range` to handle the range selection of channels.
> 
> Old Differential revision: https://archive.blender.org/developer/D17079
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/104565

**Comment by ReinerBforartists** [comment]
We miss this hotkey, it is not that an existing hotkey needs to change.
![missing](https://github.com/Bforartists/Bforartists/assets/13919702/83c2048e-7aa6-4293-a09b-b1020d63539f)

**Comment by ReinerBforartists** [comment]
Oops, flag was set wrong. Fixed in master
