### ISSUE TITLE
Theme - Blender Dark is almost the same as Bforartists

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3546]
**Bforartists**
![bforartists_sUoHDdnVQj](https://github.com/Bforartists/Bforartists/assets/35357409/6050a762-8e3d-443f-94fb-54ede7d1db20)

**Bforartists - Blender Dark**
![bforartists_4wGngBQGcO](https://github.com/Bforartists/Bforartists/assets/35357409/bbcbb4a0-6936-4f34-852b-fcd187fb3bf7)

**Blender default**
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e8253af1-c237-48a6-ac88-a5dbf75b6b25)

The blender dark theme seems to be incorrect.

**Comment by Blenux** [comment]
Yeah this is weird one, has nothing is even in the blender_dark.xml file, history on the file only shows sub-module change?.

userdef_default_theme.c has the defaults for the theme, so perhaps they are building the theme during compiling now???

**Comment by ReinerBforartists** [comment]
We had it transfered at one point. But as you found out, the Blender dark theme simply uses the defaults. And our defaults are the Bforartists ones.

Grabbing the xml file from BFA version 3.3.1 should fix the issue. Maybe resaving it, to add all the latest changes too. And while at it also resave the light theme, just in case ...

**Comment by ReinerBforartists** [comment]
Fixed in master
