### ISSUE TITLE
Default Workspaces - 2D Animation has a GP frame spots, should be clean

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3553]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a193d163-d5dc-4555-a962-e4926008c80d)

Workspace has a test grease pencil object. Should be clean.

**Comment by ReinerBforartists** [comment]
We haz surely a gap now under the toolbar ...

**Comment by ReinerBforartists** [comment]
And fixed.
