### ISSUE TITLE
Sequencer - View - Remove redundant operator "Go to Current Frame"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3557]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/46556317-36b6-4f7f-84b6-433d2b80b3b5)

Blender decided to add this to the view menu. We already have it in our own navigation header menu - so.. remove the new one. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/23d186dd-4e8c-4de4-a1ec-0642ae60413d)

**Comment by Draise14** [comment]
Good point, consistency with other editors would make sense.

**Comment by ReinerBforartists** [comment]
Moving it from navi to view.

**Comment by ReinerBforartists** [comment]
Updating manual

**Comment by ReinerBforartists** [comment]
Fixed
