### ISSUE TITLE
3d View - Edit Mode - Live unwrap check box should float left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3558]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f5d86ff4-b87b-4058-8e79-1145ad1bfea9)

This operator somehow is now not floating left. They moved things around, now it's a mess in Bforartists.
Header titles also need to be organized since Transform and UVs are now repeated and disorganized. 

<details>
<summary>Relevant Blender Commit</summary>

SHA-1: 560e9c654bd5fb0841fae59d85d8afea2d2f99ac

* UI: Edit Mode Options panel cleanup

AutoMerge is a property of transform operations, so it seems more
convenient to have this option bundled with transform settings.

Another thing is that the 'Live Unwrap' option has no real relation to
Transform.

Therefore, remove the 'AutoMerge' sub-panel and create two sub-panels
for the Options Panel:
- Transform
- UVs

Merge the 'AutoMerge' settings into the 'Transform' sub-panel.

Move 'Live Unwrap' to the 'UVs' sub-panel.

Pull Request: https://projects.blender.org/blender/blender/pulls/108056

</details>

**Comment by ReinerBforartists** [comment]
Interesting. The code is the same than in 3.5.1. No idea where this extra bits comes from ^^

**Comment by ReinerBforartists** [comment]
Fixed in master

I have while at it also grouped the content like in Blender now. Two groups, Transform and UV.

![options](https://github.com/Bforartists/Bforartists/assets/13919702/35e61cde-7105-4ae1-9a58-33cf61a19663)

**Comment by ReinerBforartists** [comment]
Downside ...

But i think we can live with it.

![downside](https://github.com/Bforartists/Bforartists/assets/13919702/2b387384-10bb-497d-8ff9-c0d67504be0e)
