### ISSUE TITLE
Properties editor - Object Tab - Move Lightgroup Shader sub-panels to own Panel (instead of Shader)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3559]
![bforartists_uouAVLbQEm](https://github.com/Bforartists/Bforartists/assets/35357409/caa55e63-89e3-4fd1-a9cd-ecb30b35ef55)
There are new Lightgroups, but...... it's not intuitive right now. 

![bforartists_1tw4rCfnyV](https://github.com/Bforartists/Bforartists/assets/35357409/25abc08b-c345-4f08-9a23-d73ac89e149e)
I would LOVE to put this into it's own panel. Right now it's under "Shading" and it took me about 3 minutes to find them - and that makes no sense. 

These need to be discoverable where they make sense.

**Comment by Blenux** [comment]
Like this?

![Screenshot_20230609_221811](https://github.com/Bforartists/Bforartists/assets/25260650/1852d21d-2c6f-4f15-840b-8207ef813350)

or?

![Screenshot_20230609_222314](https://github.com/Bforartists/Bforartists/assets/25260650/f547e38d-659b-493a-a512-61dacf74faaf)

**Comment by ReinerBforartists** [comment]
Everything light group should imho be in one panel. So in this case, three sub panels in one panel called Light Grouping for example.
