### ISSUE TITLE
Asset Browser - Add toggle "Instance" to header to avoid linking/appending issues with collections

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3562]
![bforartists_vmzEhkZEuJ](https://github.com/Bforartists/Bforartists/assets/35357409/0f9c0ed2-df73-47bf-96ec-7779abe37329)

# Issue
Right now when you link or append collections, you have the option in the Repeat Last operator to instance or link to scene. When you link to scene, it will place the container contents to the cursor, then when you switch to Instance, it will offset the center of the collection contents by the offset from world center. There is little or no way to fix this manually and it is a pain in the butt when working with collections. 

On top of that, there is no way to know if you are appending or linking in a collection as an instance or not. It's a wild card with frustrating results. 

# Solution
Ideally, this toggle should be an opt in BEFORE you drag in collections, so you know what you are going to get when you drag and drop. Is it an instance? Will it link to scene? 

If you know it's an instance, you won't accidentally drag in "link to scene" with the global offset, then regret changing it to instance after with the broken offset, no-longer able to use collections as instances when doing layout (necessary center of origin needed). If you know you will "link to scene" ei, not an instance, you know that it will come it ready to be overridden at cursor placement. 

## Task
- Find a way to add the Repeat Last operator to the header so that you can optionally link or append collections with an intentional UX to avoid issues repeat last instance conversion in the future.

**Comment by iyadahmed** [comment]
progress
![image](https://github.com/Bforartists/Bforartists/assets/25552173/4913977f-f37c-4674-b3ad-534cdc3d95bd)

**Comment by Blenux** [comment]
Notice some weirdness with undo when toggling the instance,  and some objects of the collection will be offset a bit.


https://github.com/Bforartists/Bforartists/assets/25260650/ad8319a2-803c-4bb9-96de-1d18ab38b290

**Comment by ReinerBforartists** [comment]
Can this be reproduced in Blender?

**Comment by Draise14** [comment]
Yes, this is an issue about Blender and the way it does placement of object data and how you instace it. Instanecs have COW (center of world) account for any offset of the original mesh data.

**Comment by Draise14** [comment]
Building the test

**Comment by Draise14** [comment]
> Notice some weirdness with undo, and using use instance before and after the collection is already in the scene, and some objects of the collection will be offset a bit.
> 2023-06-04.12-29-41.mp4

I can confirm this is still and issue when "link collection to scene" (ei, toggle off) - since the linking offsets the collection data to a new Center of World (COW). So when you link as instnace, the COW will be completely off breaking the UX. 

I will make a new task. 

Meanwhile, the rest is great! 

To close this task, could you be able to make the toggle to icon only @iyadahmed? Then we can merge to master. Love it already, it half attacks the issue and makes this experience much more predictable. Nice work!
![bforartists_Y4YtAoZ36K](https://github.com/Bforartists/Bforartists/assets/35357409/10d80c2c-b449-457f-85af-0fd99e51eb6f)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/44a2ca02-ced1-4409-b0ee-3a9abd4eaaa7)

Quick update, looks like it's working as intended! I think this could be merged to master now.

**Comment by Draise14** [comment]
The branch for this task:
https://github.com/Bforartists/Bforartists/tree/asset_system_drop_collections_as_instances_boolean_UI_property

**Comment by Draise14** [comment]
Merging to master
