### ISSUE TITLE
How to display edge length of the object

### ISSUE THREAD

**Issue by Wonderer11** [Bforartists/Bforartists#3571]
Please use the official forum at the Bforartists webpage for questions about useage if possible. The tracker is to maintain the development of Bforartists. https://www.bforartists.de/forum

I just switch from Blender to Bforartist and the UI is quite different to me as I cannot find the option of displaying edge length in the viewpoint, I don't know if it has been removed by the team.

https://www.youtube.com/watch?v=66VqYNfQyPw&t=0

**Comment by ReinerBforartists** [comment]
Hi Wonderer11,

No, it is at the same location where it is in Blender. In the overlays.

Just curious, do you see a error message in the console? 

![edgelength](https://github.com/Bforartists/Bforartists/assets/13919702/4ac189d7-5b12-4efe-acf8-5b7481becaf9)

**Comment by Wonderer11** [comment]
Thank you, I found it now.
