### ISSUE TITLE
Showstopper bug with remesh and the sculpt template - remeshing freezes Bforartists

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3577]
This bug was reported at the forum by fas42.

Basically, remeshing in the sculpting template freezes Bforartists while Blender behaves pretty solid and normal.

The default remesh values are the same. The resolution is the same. But when i click at voxel remesh then the mouse cursor turns into the busy symbol. And remains in this state until i kill BFA. There is no error message in the console. I guess we need to make a debug build here.

https://www.bforartists.de/forums/topic/remesh-bug/#post-25478

![remesh](https://github.com/Bforartists/Bforartists/assets/13919702/5684efe3-49b4-4d55-9437-6fe1bfdf685c)

![frozen](https://github.com/Bforartists/Bforartists/assets/13919702/6445d32a-af4c-49f9-8cfe-0bc215db9c48)

**Comment by ReinerBforartists** [comment]
Remeshing seem to work fine when you don't work in the Sculpting workspace. But as an observation, we have completely different default values here. Blender too by the way.

![values](https://github.com/Bforartists/Bforartists/assets/13919702/b1f78b38-4680-49fb-b65d-16b521a9c442)

**Comment by ReinerBforartists** [comment]
Nope, it's not the values. Remeshing in the default workspace also works with the defaults from the sculpting workspace.

**Comment by ReinerBforartists** [comment]
Version 3.4.1 worked. Broken since version 3.5.0

**Comment by ReinerBforartists** [comment]
Another thought, since it works in default workspace, the problem is most probably the sculpting template. I fear we might need to create it from scratch.

**Comment by Blenux** [comment]
Interesting that deleting the default sphere mesh in the sculpting template and adding a new mesh doesn't crash.

Here it is after using it on the cube,
![Screenshot_20230609_220634](https://github.com/Bforartists/Bforartists/assets/25260650/c10219cd-b7e2-4b66-a6fb-3337f398adf1)

**Comment by ReinerBforartists** [comment]
Yes, something at the defaults of the template is broken.

**Comment by fasteinke** [comment]
To "complicate" things, using another method of subdividing that template mesh doesn't appear to work correctly - as per a video on Blender sculpting, I 

Add Modifier -> Multiresolution -> Unsubdivide -> Unsubdivide -> Unsubdivide ... to a cube

If I then do a single Subdivide, I get the template sphere back; which won't then Unsubdivide

I then tried, delete the sphere, add a cube, which subdivided OK, but then wouldn't unsubdivide. Also, some combination of sudivide and un-, on the cube, caused program to crash, at one point - can't repeat, so far.

**Comment by fasteinke** [comment]
BFA is not having a good day here ... probably should be a separate issue ...

Tried, on a clean start, to import a 31 Meg .fbx file; program crashed. A current version of 3DF Zephyr had no trouble loading, and displaying the object. This was from the sample Habitat 67 project, by RealityCapture.

**Comment by ReinerBforartists** [comment]
Many thanks for the report :)

When it's not in the sculpting template, then yes, please make it a separate issue :)

**Comment by Draise14** [comment]
Probably the method of how the modifier is set. We might be already using multires instead of sub-divide - then the script could be adding in a new on on it. The script for the template applies the SDS of the cube, or multires, forgot which it has - then it starts the sculpting - so you start on a rounded cube. For some reason they use a script to do this when they could bake it in.... probably to save a mb or two.

**Comment by Draise14** [comment]
This one I think I can fix.

**Comment by ReinerBforartists** [comment]
I'll resave the layout then afterwards, to remove the gap ...

**Comment by Draise14** [comment]
Can no-longer reproduce from latest merge.

**Comment by ReinerBforartists** [comment]
Indeed, seems to be gone.

**Comment by Draise14** [comment]
I guess I'll close.
