### ISSUE TITLE
Notice: Default Library has been unregistered

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3578]
I think this comes from us. We have a warning in the console that the default library has been unregistered. Wasn't this an issue at one point before?

![unregistered](https://github.com/Bforartists/Bforartists/assets/13919702/85fc6187-799f-49f5-bbf0-2afbd4d1ac12)

**Comment by ReinerBforartists** [comment]
Ah, okay. Rule is, no message when no message is necessary. So i would indeed remove it.

**Comment by Draise14** [comment]
I'm on a roll, let's do this one too. Then commission work.

**Comment by Draise14** [comment]
Commit to master
