### ISSUE TITLE
Sculpt mode, remeshing panel - indent prop

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3579]
Color attributes is part of the preserve group. We should indent it. And align if possible.

![indent](https://github.com/Bforartists/Bforartists/assets/13919702/cca5e182-f669-4592-a579-95a40a6e9290)

**Comment by Blenux** [comment]
![Screenshot_20230609_215851](https://github.com/Bforartists/Bforartists/assets/25260650/09a68f82-e69c-4742-98a3-a72dd592ea7a)
