### ISSUE TITLE
Geometry Nodes - New Add Corners of Edge node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3585]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/805bc8bf-a060-4cf6-b344-2cf061790e2c)

New node means.. new entry in the toolshelf, icon, and documentation. 

Location: Mesh>Topology

<details>
<summary>Blender Task</summary>

SHA-1: fdc3ed798d434111555a811e96b77bcd27ea7a78

* Geometry Nodes: Add Corners of Edge node

Adds the "Corners of Edge" topology node to geometry nodes.
Combining this node with the "Face of Corner" node allows getting
informations about the faces connected to an edge. The behavior is
slightly non-obvious-- the node only gives the corner neighbors
that come *before* the current edge in directly neighboring faces.
This allows the operation to be easily reversed and reduces
redundancy between nodes.

See the devtalk thread: https://devtalk.blender.org/t/29379

Pull Request: https://projects.blender.org/blender/blender/pulls/107968

</details>

**Comment by ReinerBforartists** [comment]
Fixed in master.

Updating the manual ...

**Comment by ReinerBforartists** [comment]
Fixed
