### ISSUE TITLE
3D View - Texture Paint Mode - New Select Looped operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3587]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fe4572ba-b5ed-4ffd-8e21-207ee4a6ee22)

When in texture paint mode with face mask mode turned on, you can now select loops. We have this exposed to the header under the Select menu in most modes and editors, so we can re-use the icons and add to header also for discoverability. 

# Task
1. Hotkeys to add
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c755591a-65dd-4ab8-937f-a0d4c8c5de0a)
2. Add operators to select menu
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a4486286-5800-4d52-a96e-7a46fb1454fe)

* ALT click: select loop
* ALT Shift click: add loop while retaining current selection
* ALT Shift Ctrl click: deselect loop

<details>
<summary>Blender Task</summary>

SHA-1: 98d48c16a33789388dfebfff2e16592f26f9f62f

* Paint: Add loop select for faces

Add loop selection identical to the behavior of ALT+Click in Edit Mode.

* ALT click: select loop
* ALT Shift click: add loop while retaining current selection
* ALT Shift Ctrl click: deselect loop

Pull Request: https://projects.blender.org/blender/blender/pulls/107653

</details>

**Comment by ReinerBforartists** [comment]
Documenting ...

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/0b25603f-ed3e-4bf9-869f-f466eee2f2d7)

**Comment by ReinerBforartists** [comment]
This menu is not documented yet. Just Vertex and Weight Paint mode. Made it a task. This task here is finished.

**Comment by ReinerBforartists** [comment]
We need to change the names. Select and extend is in real a add , and extend loop is in real a subtract.

**Comment by ReinerBforartists** [comment]
Oh, and the loop selection just works in texture paint, but the menu items shows in vertex paint and weight paint.

**Comment by ReinerBforartists** [comment]
Fixed

![menu](https://github.com/Bforartists/Bforartists/assets/13919702/74cbe1bf-3334-45b9-9c0c-7f7d25f58715)
