### ISSUE TITLE
Animation Editors - NLA - New "Start Tweaking Strip Actions (Lower Stack)" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3588]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b87db8ac-c019-4572-a88f-b71406ec75db)

There is a new operator to toggle strips to lower stack, or full stack. Probably could have the same icon, then be documented. 

The icon we could use is similar to the icon we have here - but may need a swapperoo:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/70a2be5c-7126-4a69-ba8d-c3f42e653cc6)

Blender:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/df80ec3e-e97f-477e-b315-8dd365d30a43)

<details>
<summary>Blender Task</summary>

SHA-1: b95cf5ff0f3da57738303b653c2c01326d663e46

* Animation: Update NLA "TAB" tweak mode to be full stack evaluation

This PR updates the key mapping (TAB) for Tweak mode (Lower stack) to Full stack for the NLA editor

[Issue](https://projects.blender.org/blender/blender/issues/108026)

Pull Request: https://projects.blender.org/blender/blender/pulls/108050

</details>

**Comment by ReinerBforartists** [comment]
Still not sure what the task here is. We have the switch to enter edit mode exposed in the header.

**Comment by Draise14** [comment]
There is a new method, full stack and lower stack. Our top level switch is to lower stack only, which is not the desired UX. 

This task is to add he entry "Full Stack" toggle to the header. We don't have it exposed at the moment. It's hidden in BFA.

**Comment by Draise14** [comment]
Done in  #3589
