### ISSUE TITLE
Animation Editors - NLA - Missing operator "Start Editing Stashed Action"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3589]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2208d43f-090d-48ed-9c58-afc1f9288a3f)

This operator slipped through, and we don't have it currently, probably should be added. Naming could be less convoluted though.  

This was the former "Tweak" action clip action:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/df03c375-587f-41e1-8d91-89667b5f182c)

This is what we have in Bforartists:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/87b6a377-4932-4cdb-9c2f-8e254e8f07d4)

**Comment by ReinerBforartists** [comment]
Also here. Still not sure what the task here is. We have the switch to enter edit mode exposed in the header.

**Comment by Draise14** [comment]
Dibs. It's a new operator, so not in the header. Will work this tomorrow.

**Comment by Draise14** [comment]
Ok! Fixed. 

Tasks done for this:
- Updated keymap so that fullstack is tweaked on `TAB`
![bforartists_9kYLu0uBXU](https://github.com/Bforartists/Bforartists/assets/35357409/cdc3d146-b80c-4bfb-888e-380de8611de2)
- Made the context menu and header menu consistent
![bforartists_sQT7667lIP](https://github.com/Bforartists/Bforartists/assets/35357409/9638a993-b1c2-45d0-99f6-2fc4151bea64)
![bforartists_g9T0sPf8on](https://github.com/Bforartists/Bforartists/assets/35357409/1bc2f2bd-856e-4dd1-98bb-5fbce8904170)
- Named the operators to "Tweak Isolated Action" and instead of "tart Editing Stashed Action" making it "isolated" for consistency with explicit naming conventions so that Tweak + Isolate is the same as "Tweak Isolated Action", to keep it consistent with the header toggles also. 
![bforartists_xlcNG1vDJ1](https://github.com/Bforartists/Bforartists/assets/35357409/6c3a56d5-19e9-4227-b35a-496d3cd918a8)

Will update documentation now. 

This make the workflow so nice, and.. now we actually have proper isolation and animation layers due to the full stack evaluation. And no hidden operators.

**Comment by Draise14** [comment]
Pending documentation.

**Comment by Draise14** [comment]
Documentation done.
