### ISSUE TITLE
Animation Editors - NLA - Set the header Tweak button to Full Stack evaulation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3592]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b37d78b1-4818-4a1b-a14c-03d4c7071f47)

Right now, there is a much better UX to now use animation layers in the NLA per default, but the tweak is in the old isolated way regardless of the isolated toggle. If we set this operator to `use_upper_stack_evaluation` to True, then it will be a better UX.

**Comment by ReinerBforartists** [comment]
And the third issue that should be one. Still not sure what the task here is. We have the switch to enter edit mode exposed in the header.

**Comment by Draise14** [comment]
Done via  #3589
