### ISSUE TITLE
File - New "Save Incremental" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3593]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6e8a5fb5-4a39-4dae-b374-068238e72d9b)

New operator, useful one, exists. Needs and icon, to be added to the toolbar and added to documentation. 

<details>
<summary>Blender Task</summary>

SHA-1: a58e5ccdec308873c77f8f672bf7e0210fb69957

* UI: File Save Incremental Operator

Operator for the TopBar File Menu that saves the currently open file
with a numerically incremented name.

Pull Request: https://projects.blender.org/blender/blender/pulls/104678

</details>

**Comment by ReinerBforartists** [comment]
We have now two save incremental operators. Makes me think if we should remove the old operator from the menu.

**Comment by Draise14** [comment]
Oh good point, we had one already. Totally glossed over that. Which one is better?

**Comment by ReinerBforartists** [comment]
Dunno, haven't tested the new one yet. I still ask me why Blender has invented a second one. Left hand and right hand i guess ...

**Comment by ReinerBforartists** [comment]
These two operators does the very same. One has to go.

**Comment by ReinerBforartists** [comment]
Hmm, on the other hand, the new Blender operator does not have the Unsaved hint ...

![unsaved](https://github.com/Bforartists/Bforartists/assets/13919702/d93ef34b-cc24-4bf7-8a25-9d67b191f2a4)

**Comment by ReinerBforartists** [comment]
Documenting ...

**Comment by ReinerBforartists** [comment]
Done
