### ISSUE TITLE
Text Editor - New View Zoom In and Out operators needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3594]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6a275f33-010f-4619-b28e-939ef9b8cec3)
New zoom in and out operators are set in Blender. This means we should expose them to the GUI too. The merge brought them to the header, which I like - but may need iconography and documentation. 

Bforartists:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8d311aef-09a3-4843-a06e-6740c39378b0)

<details>
<summary>Blender Task</summary>

SHA-1: 240a1edfa16e67eaffbdd898bfd201f5e3501c2f

* UI: add text editor zoom in/out to view menu

Ref !108430.

</details>

**Comment by ReinerBforartists** [comment]
I don't really like to have these two buttons crowding the header. Usually you don't zoom in and out all the time. And when you do, then you do it by hotkey like in any other text editor too. So i would vote to put these buttons back into the View menu like in Blender.

**Comment by Draise14** [comment]
Into the header, you're right. Makes sense instead of in the header.

**Comment by ReinerBforartists** [comment]
fixed

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/4f56cd47-4a18-4169-9057-187669cb9c8c)
