### ISSUE TITLE
Text Editor - File - New operator "Edit Externally"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3595]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/195284e4-efd5-4cd6-88eb-1b10ba3f9ace)

New operator to edit the text file in an external application (if set) is now possible directly from the editor. Probably should be iconized and documented. 

Options here:
![bforartists_AsibFKmxMD](https://github.com/Bforartists/Bforartists/assets/35357409/25268ddc-db17-4a6f-8967-65ec0d2dc648)

<details>
<summary>Blender Options</summary>

SHA-1: e16ec95a16669d7d0dada95a57dcc7528de98df7

* UI: Add a custom text editor preference

Add a user preference to set up a custom text editor for editing text
files with the "Edit Source" action in the UI context menu.

- An operator TEXT_OT_jump_to_file_at_point has been added.
- A custom editor can be set in the user preferences.
- A preset has been included for "Visual Studio Code".
- When the editor is not set, use Blender's internal editor.

Ref !108299.

</details>

**Comment by ReinerBforartists** [comment]
Fixed
