### ISSUE TITLE
Textuer Paint - use_frontface seems to have an issue

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3599]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/54e32787-178b-4e0a-ab79-47fb0bd0322b)

When going to texture paint mode, the console is complaining.

**Comment by ReinerBforartists** [comment]
Off with the head!

**Comment by Blenux** [comment]
easy fix

**Comment by iyadahmed** [comment]
Fixed by https://github.com/Bforartists/Bforartists/commit/33a2687b8a4fadd3b45c37221e1658ec452c4047
