### ISSUE TITLE
Grease Pencil Pie menus included in hotkeys, not available as feature/conflicts

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#36]
The hotkeys D+S, D+W, and D+Q in Edit Strokes mode are disfunctional. They should call grease pencil pie menus.

The Blender developers have changed the names of the menus. And so the call goes into nirvana. Affected is just the Bforartists keymap. The menu names in the Blender, Maya and Max keymaps are already fixed by a merge.

The issue is already fixed in the bforartists keymap. https://github.com/Bforartists/Bforartists/commit/a4fe852b62e2bfed79fb05514d8549ce6ddea90d

But needs to be repeated in the Full Keymap, which is currently developed.

 In the keymap replace

GPENCIL_PIE_tool_palette **by** GPENCIL_MT_pie_tool_palette

GPENCIL_PIE_settings_palette **by** GPENCIL_MT_pie_settings_palette

GPENCIL_PIE_sculpt **by** GPENCIL_MT_pie_sculpt

![names](https://user-images.githubusercontent.com/13919702/37240097-9088728e-2446-11e8-8438-9039049e0919.jpg)

**Comment by Draise14** [comment]
Done. Version 0.9.1

**Comment by ReinerBforartists** [comment]
When it's fixed, then close it :)
