### ISSUE TITLE
Find and replace in text editor 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3601]
The find dialog in the Blender scripting editor bothers me since i know of it. For many many years. It is inconvenient to use. You always drag around the sidebar to be able to type in the string. And is then in the way when you are done.

Idea 1: put this panel into the header, as a popover. And with a convenient width that you can really type in text and read it. The con here, fixed width. Could become fuzzy with moving the mouse then ...

Idea 2: instead of opening the sidebar with ctrl f, open a popup window under the mouse that provides the search functionality. Could become fuzzy with moving the mouse then ...

Idea 3: a search field at the bottom of the editor. Like in Libre Office for example. This would be my favourite. But is hardest to achieve. We might need to dive into C code. 

Maybe also a combination of all three methods. 

Needs some experiment what can be achieved, and if it is really an improvement then. Preferable method is as an addon. Maybe this even exists already. 

Popover in header mockup:

![popoveridea](https://github.com/Bforartists/Bforartists/assets/13919702/4c22fdc1-7c02-4825-ab69-20880551b509)

Popup like in Notepad++ . Opens up at a fixed location. Other editors opens such a popup also under the mouse.

![popup](https://github.com/Bforartists/Bforartists/assets/13919702/348aca4f-74ec-4730-b244-97c472dd1802)

Search field like in Libre Office

![permanentbottom](https://github.com/Bforartists/Bforartists/assets/13919702/dc66c264-c7a9-437b-bfc5-f2e2fcf9e86d)

**Comment by ReinerBforartists** [comment]
Hmm, or we try to put this search into the toolbar. Then we can place a toolbar at the bottom ...

**Comment by Blenux** [comment]
Something like this? (posted zip on the discord)

https://github.com/Bforartists/Bforartists/assets/25260650/0cbf2b04-eaa5-4b09-a9c8-b5480c85f28c

**Comment by ReinerBforartists** [comment]
This is exactly what i talk about. Please include in BFA :)

**Comment by Blenux** [comment]
Done (not sure if done right), let me know if there is any trouble or improvements needed can fix later (running on no sleep atm).

**Comment by ReinerBforartists** [comment]
Ah too slow with my second answer, you already included it :D

The addon needs imho a bit fine tuning. There are a few redundancies in the addon. The icon and assets folder for example. There are trailing whitespaces in the code. I use a addon in both, vs code and visual studio to remove them automatically. It's just cosmetics, but ... ^^

And this code is imho highly confusing: split_B80B2 = row_B3D6C.split(factor=0.6499999761581421, align=False)
A simple split = row.split(factor=0.6499999761581421, align=False) should do it too.

But yeah, amazing work. Many thanks :)

**Comment by ReinerBforartists** [comment]
And shall we activate it by default?

**Comment by Blenux** [comment]
> 

Yeah that's one problem I find with serpens, they have a internal number reference ID thing with their code, fixing up code now and yeah can enable by default has shouldn't interfere with anything.

**Comment by Blenux** [comment]
done with cleanup, hopefully should be all good.

**Comment by ReinerBforartists** [comment]
> And this code is imho highly confusing: split_B80B2 = row_B3D6C.split(factor=0.6499999761581421, align=False)
> A simple split = row.split(factor=0.65, align=False) should do it too.

MEOW ?

**Comment by Blenux** [comment]
yeah made it simpler

**Comment by ReinerBforartists** [comment]
Ah kk ^^

**Comment by ReinerBforartists** [comment]
Let's merge it and continue from there.

**Comment by ReinerBforartists** [comment]
All is well, many thanks :)
