### ISSUE TITLE
Sequencer - keymap conflict. Right Click context menu click is not working

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3605]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ebdd68ce-7eac-4d7f-b82c-ecbf01c29afa)

We have a double hotkey and conflict. RMB is select and both context menu. Should only be Context menu. Remove the select one, we already do that with LMB.

**Comment by ReinerBforartists** [comment]
Fixed
