### ISSUE TITLE
Text editor, View, Zoom In, Zoom out, separate tooltips, add a tooltip that makes sense

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3607]
The zoom in / zoom out tooltips in the text editor are the same, and makes no sense. 

Separate the tooltips, and write a tooltip that makes actually sense.

![tooltips](https://github.com/Bforartists/Bforartists/assets/13919702/9e324643-6554-4670-874a-494d1efecf80)

**Comment by ReinerBforartists** [comment]
Hmm, cannot catch it. The commit just adds the python code. No idea where we could split the tooltip here, except making our own operators.

> SHA-1: 240a1edfa16e67eaffbdd898bfd201f5e3501c2f
> 
> * UI: add text editor zoom in/out to view menu
> 
> Ref !108430.

**Comment by ReinerBforartists** [comment]
Unassigning.

**Comment by ReinerBforartists** [comment]
Hmm, one tooltip makes sense. It's up and down with the scrollwheel. Let's at least update the description a bit.

**Comment by ReinerBforartists** [comment]
I would love to get rid of the word Cycle, but i have no idea where this resides. So good enough. Misses some adjustments at the manual.

![zoom](https://github.com/Bforartists/Bforartists/assets/13919702/885c1977-de60-4306-bcb7-625e59d2964e)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e2bbb446-fbcf-4974-b14a-329c5057d176)

Hit a regression....

**Comment by Draise14** [comment]
Ok, this is a global issues, tooltips no-longer are displaying the operator title....

**Comment by ReinerBforartists** [comment]
Then i ask myself why you did close it again ^^

But don't worry, is most probably fixed here already. Your shown menu is showing the titles again. Missing Tooltip Title in (not only) Add menu #3893

![backworking](https://github.com/Bforartists/Bforartists/assets/13919702/156db49c-ac8b-4f71-9fbc-e73343e61ea1)
