### ISSUE TITLE
Theme - Outliner results and selected colour needs more "contrast" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3612]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/18763dd4-4ece-444c-8dc9-c434bccf08a7)

Right now when you search in the outliner, the filters show up as green. When you select multiple entries, Active is clear, but not selected (also green). 

A better more consistent color coding should be used here.

**Comment by Blenux** [comment]
Black?
![Screenshot 2023-06-29 174636](https://github.com/Bforartists/Bforartists/assets/25260650/2fee7e0e-d52d-40e5-85a7-d8b7a3ff1511)

**Comment by ReinerBforartists** [comment]
As a note, this should be done after the release. Every change brings now the chance to break things.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4714b8b5-dd60-482e-a384-1feaa18aa138)

Thought to stick to the blue highlight of Bforartists, which contrasts with the orange. If I change the orange of the selected it also changes the filter off look. I also made it darker so the highlighted and selected text is more legible - the previous green was quite luminous. 


![image](https://github.com/Bforartists/Bforartists/assets/35357409/a20d19d2-17f1-4ae0-b7f4-25e6aaa0b1da)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1251cb8f-4ee8-4b0d-8025-88cd04332ea7)

**Comment by Draise14** [comment]
Went through documentation, didn't see a capture with search results, so done. Will pull.
