### ISSUE TITLE
Do a Meld check

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3613]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ba904676-42e2-47b4-b1ab-bd96791c8f60)

Go through everything with meld to compare and check if everything is up to date.

**Comment by iyadahmed** [comment]
Everything is ^^

**Comment by ReinerBforartists** [comment]
Not here ^^

@Draise, do you have the changes in a local branch?

**Comment by Draise14** [comment]
In local yes. Not commit nor pushed yet. Should I commit in chunks? 
I still have a few documents to go through.

**Comment by ReinerBforartists** [comment]
First finish :)

**Comment by Draise14** [comment]
Working it..

**Comment by Draise14** [comment]
OK.. gone through, now doing a test compile

**Comment by Draise14** [comment]
Going through issues now, debug build, and release build. 

You were right @ReinerBforartists, a lot of files were not quite up to day, not sure if it was cause I pulled blender yesterday after the merge.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f93dfa0c-087a-4532-adda-790a51b4b682)
I got one warning with a debug build. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/d70b5a78-4ca9-406c-a382-ad372eb6fafc)
And another warning on release build. 

Is this tolerable? Or should they be fixed?

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ce2dd5fe-55ca-4867-8b44-cc45aa8fd1b8)
Ah damn, missed this, a missing icon.

**Comment by Draise14** [comment]
Gah, spent ALL day doing this, and I got this issue. It's compiling, and there were changes I theoretically merged in, but now I don't know what I broke.

**Comment by ReinerBforartists** [comment]
Just compare the Blender icons.cc file with ours

**Comment by ReinerBforartists** [comment]
> You were right @ReinerBforartists, a lot of files were not quite up to day, not sure if it was cause I pulled blender yesterday after the merge.

This is one of the reasons why i insisted to do a check. I noticed quite a few differences.

But be careful, you should compare the Blender repo from the day at which we did the merge. And not pull three days later the next Blender changes. Never do this!

This makes this meld check from you worthless now that you did. Since now you drag in quite a few new changes already. What you could do is to switch Blender to the day and latest issue that arrived in Bforartists. But we have a job to do, and we are under time pressue. So i think best is that i take over now. I have the old files still from the merge day. Which might already differ from the state in which Iyad did the merge by one or two issues. But not three full days.

**Comment by ReinerBforartists** [comment]
Hmm, even i was a few dozen commits behind already. Blender devs are highly active at the moment.

**Comment by ReinerBforartists** [comment]
@iyadahmed , i spotted a difference where i am not sure if it is a typoe or by purpose. We have a bfa comment above. But i think this was because we removed the if statement.

But what is the " | " sign good for? Is this by purpose? Or a unwanted difference?

source/editors/animation/keyframing.c

![sign](https://github.com/Bforartists/Bforartists/assets/13919702/5532dda7-df2e-4745-be1b-0f1a534793e7)

**Comment by iyadahmed** [comment]
> @iyadahmed , i spotted a difference where i am not sure if it is a typoe or by purpose. We have a bfa comment above. But i think this was because we removed the if statement.
> 
> But what is the " | " sign good for? Is this by purpose? Or a unwanted difference?
> 
> source/editors/animation/keyframing.c
> 
> ![sign](https://github.com/Bforartists/Bforartists/assets/13919702/5532dda7-df2e-4745-be1b-0f1a534793e7)
> 
> 
> 
> 
> 
> 

This is om purpose not a typo, the "or" operator, because we also need the previous values of "changed" to be taken into account

**Comment by ReinerBforartists** [comment]
I am pretty sure that all the changes in source/blender/editors/space_clip/clip_buttons.cc comes from us. Since we remove labels where we can. But they are not commented.

![notcommented](https://github.com/Bforartists/Bforartists/assets/13919702/e9381f4c-9650-46c4-a919-47f7eb9eaecb)

**Comment by ReinerBforartists** [comment]
Same problem at space_view3d/view3d_buttons.c. Lots of uncommented code where i am unsure that it comes from us. 

![uncommented](https://github.com/Bforartists/Bforartists/assets/13919702/a21472f4-96ef-40ea-9498-46e380e82f98)

**Comment by iyadahmed** [comment]
> Same problem at space_view3d/view3d_buttons.c. Lots of uncommented code where i am unsure if it comes from us.
> 
> ![uncommented](https://user-images.githubusercontent.com/13919702/249705045-a21472f4-96ef-40ea-9498-46e380e82f98.jpg)

yes this comes from us too

**Comment by ReinerBforartists** [comment]
I killed the toolbar \o/

![killedtoolbar](https://github.com/Bforartists/Bforartists/assets/13919702/7e9a6675-314e-44f6-a3f5-83c573f2238d)

**Comment by ReinerBforartists** [comment]
> > Same problem at space_view3d/view3d_buttons.c. Lots of uncommented code where i am unsure if it comes from us.
> > ![uncommented](https://user-images.githubusercontent.com/13919702/249705045-a21472f4-96ef-40ea-9498-46e380e82f98.jpg)
> 
> yes this comes from us too

Will have a look to add a few more comments then. Thanks :)

**Comment by ReinerBforartists** [comment]
Must have melded the wrong folder ...

**Comment by ReinerBforartists** [comment]
Sure. You can simply switch/checkout to a specific commit, which i did then. 

![switchcheckout](https://github.com/Bforartists/Bforartists/assets/13919702/7af2c63e-4713-4a8e-bd15-ccb4caa7630a)

**Comment by Draise14** [comment]
Oh, had no idea. Will keep that in mind next time. It was a good exercise to go through it all - but yeah, we need even comments. Never enough.

**Comment by ReinerBforartists** [comment]
As a note, i was tricked here too. I was used to do the merge, and then you really have the exact commit in both repos. But iyad did the merge. And when i pulled the Blender repo, it already had a few dozen commits more than the bfa repo. And that's what made me think we miss a few things.

But i nevertheless found a few things by the meld check then after switching. So it was no bad idea to do it.
