### ISSUE TITLE
Delete Dialogues - Add to hotkeymap and clear code

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3615]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a48ea73a-f0e8-4a5a-87c7-ce256dff2d60)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/0adb47e3-5861-46db-9dd7-3e25ea3d9c31)

You can now use the hotkeymap to add or remove delete confirmation dialogues, meaning our code changes we compile to remove them can be a user opt in in the hotkey preferences. Our default hotkeymap can now use define it - meaning.. to not break functionality, let's clear that out then update the keymap. 

_Then.. people can be happy to confirm delete with the Blender keymap and hopefully opt for Bforartists keymap instead. huehue_ 

Note: This may take a bit of digging. Searching `// bfa - turned off the confirmation dialog.` might help

**Comment by ReinerBforartists** [comment]
Hmm, i don't even want to give the user a choice really. Not needed confirmation dialogs are not needed. So why give an option to turn it on again?

**Comment by Draise14** [comment]
So the blender hotkeys suck again. (Even in Bforartists)

User opts to Bforartists hotkeys.

**Comment by ReinerBforartists** [comment]
Is this a yes or a no? And if yes, yes to what? :D

**Comment by Draise14** [comment]
As in, yes, add it back so blender hotkeys are not broken and they can realize how silly it is - with Bforartists keymap UX still the same. Or else we.. have a broken toggle in the keymap editor. 

Some of the confirm dialogues can still be removed, since they are not in the keymap, but a few can be restored then baked into the keymap as off to not have broken toggles in the keymap.

**Comment by Draise14** [comment]
Gonna postpone this for after 3.6.1

**Comment by ReinerBforartists** [comment]
Yeah, it is a bigger operation

**Comment by ReinerBforartists** [comment]
I will start with a few entries now. I think this is best done at a one by one base.

**Comment by ReinerBforartists** [comment]
I will skip for now the entries that we did not modify so far. And just tackle the ones that we did turn off in the C code.

![hasone](https://github.com/Bforartists/Bforartists/assets/13919702/e60a54b7-6459-4e8b-a9ae-6c9f5a5ed0a7)

**Comment by ReinerBforartists** [comment]
Okay, this one sucks. Removing.

![deletemetaball](https://github.com/Bforartists/Bforartists/assets/13919702/fac7f9f7-e3c1-43a8-baba-2e62c4072fc8)

**Comment by ReinerBforartists** [comment]
Confirmation dialog for delete Track was never turned off.

![deletetrack](https://github.com/Bforartists/Bforartists/assets/13919702/f1b839ae-fb57-4f0e-8b4f-053480e0d2dd)

**Comment by ReinerBforartists** [comment]
And through. No more bfa - turned off the confirmation dialog strings to find.

@Draise14, i leave the decision what to do with the listed items into your hands. I can't even find them ^^

**Comment by Draise14** [comment]
Nice catches. I'll turn off the dialogue in the Bforartists Keymap then I'll close.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5dd62854-08da-4f75-9744-a7edfb85c434)

Ok, found this one.

**Comment by Draise14** [comment]
Ok, disabled the found confirmations for consistency, and removed doubles, and reverted the track confirmation, now it's ok in keymap.

Fixed in master here:
https://github.com/Bforartists/Bforartists/commit/4e9a300a7c0f2324be66a71fa89985d9ae7f33c6
