### ISSUE TITLE
3d view - resolve hotkey conflict B for box select and snap base

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3619]
We have a hotkey conflict in the 3d view. B is both, box select, and snap base. Well, it works when you are careful, but you end too often in box select then.

Take care of the hotkey tip in the footer here. We might need to change it manually and hardcoded.

![snapbase](https://github.com/Bforartists/Bforartists/assets/13919702/1de496cc-d4a6-4303-8ad2-1ad43a698bbe)

**Comment by ReinerBforartists** [comment]
Related https://github.com/Bforartists/Bforartists/issues/3572

**Comment by Draise14** [comment]
When in transform mode, B for box didn't work? No?

**Comment by ReinerBforartists** [comment]
Yes it does. But you end to 90% in box select then.

**Comment by ReinerBforartists** [comment]
Postponing. Doesn't need to be resolved for the release.

**Comment by Draise14** [comment]
This was discussed in another thread - there is no technical conflict and if we were to fix this, we would have to fix a dozen other conflicts like this even if they are in different modes of UX. So will close. 

> > Hmm.. I think with this case, I will close since the conflict is a post-operation issue after a rarely accessed modal chained operation, so B will be box select by association most times. And if this were to be resolved, we would technically have to resolve X, Z, ALT, CTRL, etc.. since they too are used in object mode when not in modal mode for other operations.
> 
> Additionally, during the modal transformation there is no technical hotkey conflict - and in Bforartists, the modal keys are only available while transforming, and the transform modals are not sticky, ei, you move, place, modals are immediately gone. You access them only after you've decided you're transforming with modals by holding down mouse and sticking to modal mode - so you gotta intentionally stick to moving to then learn to hit B for another mindset of operations - those are not exposed to object mode. So it is not necessarily accessed often. So B to snap bounding as association won't be the UX by default, so fallback to Box select is still ok..
> 
> And.. well the Blender hotkeys that are sticky to modals... it's the same issue, or similar, and if you're a Blender hotkey user in Bforartists, let Blender worry bout that conflict.
