### ISSUE TITLE
UV Editor - Pack Islands menu needs cleanup, again... 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3620]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/906c4fac-b2b9-4e3e-b7d1-cb53b05470e2)

Float left, indent. Update Documentation. 

<details>
<summary>Blender Task</summary>

SHA-1: e2dbc4779eac0a3f5d29d2c31a0502d65cc6c84a

* UI: change the UV packing pin option into a toggle & drop-down

Exposing both the option not to use pinned islands and to skip pinned
islands in the same drop-down was confusing.

Now there is a checkbox "Pin", when disabled, pinned UV's don't
have any impact on the packed result.

When enabled, the pin-method selects how pinned islands are handled.

Also remove the "ignore" option from the UI as this didn't fit well with
other methods of handling pinned islands. Instead, islands to be ignored
can be de-selected by the user.

Ref !108733.

</details>

**Comment by ReinerBforartists** [comment]
Huh?

**Comment by ReinerBforartists** [comment]
You mean this one? Git fetch, git pull?

![alreadydone](https://github.com/Bforartists/Bforartists/assets/13919702/2a0b5b6b-0502-4339-920a-41cd932b5660)

**Comment by ReinerBforartists** [comment]
Already fixed with a previous commit. Closing.
