### ISSUE TITLE
Development - Official Linux build environment VM based on the official Blender Rocky8 Environment

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3622]
Right now we have been using Ubuntu 22.04 LTS to build. But recently it has proven sometimes troublesome. 

At the moment Blender officially builds on Rocky 8 for the official releases, we could (and probably should) stick to that as close as possible and have a VM ready for it for other developers so we get less surprises. 

### Blender Documentation
https://wiki.blender.org/wiki/Building_Blender/Other/Rocky8ReleaseEnvironment

<details>
<summary>Details</summary>
# Rocky 8 Release Build Environment

The official Blender builds are done on the Rocky 8 system. This makes it possible to have a portable build which will work on VFX reference platform compatible systems.

This page describes how the official setup is created. This setup allows to compile Blender itself, as well as the Blender dependencies.
Preparing Rocky 8 Environment

The release environment is based on the Minimal Install of the Rocky 8. This document does not cover the steps needed to get the OS installed: it is rather straightforward and the default installation will get to where the systems needs to be.

The` linux_rocky8_setup.sh` script is then run as a root on the freshly installed system. It takes care of installing all dependencies.

_Note: Some system-wide changes are performed, so it is recommended to use a dedicated virtual machine for the release build environment._

Congratulations, the base system is now ready!

Follow the Building Cycles with GPU Binaries for the instructions related to installing the GPU compute toolkits.
Building Blender

Blender is built from sources using the precompiled Rocky 8 libraries. Follow the Download Sources and Download Libraries sections from the Linux Quick Setup. Note that all packages have already been installed, so that step from the Quick Setup should be skipped. Also make sure to get precompiled libraries for Rocky 8.

The build is to be performed using gcc-11 toolchain. It is activated using the scl command:

```
scl enable gcc-toolset-11 bash
cd ~/blender-git/blender
make release
```

</details>

## Task
- Create the environment on a VM with the essentials
- Upload it to nextcloud for anyone

**Comment by ReinerBforartists** [comment]
Just curious, at which GlibC version is a actual Rocky Linux?

And also, please keep an eye at the red hat drama. Rocky is based at RedHat. And RedHat has pulled the plug for the public repository. Means Rocky Linux cannot longer simply pull the RedHat code.

At the moment the Ubuntu VM still works. So we can still continue for a while, the pressure is not this big. It just crashes at certain actions now with the by us required Cuda 12. And there is no sign of an answer or fix at the bug report that i have sent to Ubuntu. So we really should switch. Ubuntu has become unreliable.

**Comment by Blenux** [comment]
Have you read that the Rocky Linux Developers seem to have found a way around this **for now** 

> One option is through the usage of UBI container images which are based on RHEL and available from multiple online sources (including Docker Hub). Using the UBI image, it is easily possible to obtain Red Hat sources reliably and unencumbered. We have validated this through OCI (Open Container Initiative) containers and it works exactly as expected.
> 
> Another method that we will leverage is pay-per-use public cloud instances. With this, anyone can spin up RHEL images in the cloud and thus obtain the source code for all packages and errata. This is the easiest for us to scale as we can do all of this through CI pipelines, spinning up cloud images to obtain the sources via DNF, and post to our Git repositories automatically.
> 
> These methods are possible because of the power of GPL. No one can prevent redistribution of GPL software. To reiterate, both of these methods enable us to legitimately obtain RHEL binaries and SRPMs without compromising our commitment to open source software or agreeing to TOS or EULA limitations that impede our rights. Our legal advisors have reassured us that we have the right to obtain the source to any binaries we receive, ensuring that we can continue advancing Rocky Linux in line with our original intentions.

[Their Response here](https://rockylinux.org/news/keeping-open-source-open/)

**Comment by ReinerBforartists** [comment]
Yeah, for now ^^

Fingers crossed :)

**Comment by Draise14** [comment]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/552ab843-7ad7-454a-a149-e7bc4c7e34f3)

Iyad has been making progress, from Discord.

**Comment by ReinerBforartists** [comment]
Any news at the vm? ^^

**Comment by ReinerBforartists** [comment]
\o/

![error](https://github.com/Bforartists/Bforartists/assets/13919702/e510a497-fd94-4df5-a6df-2a147bddd893)

**Comment by ReinerBforartists** [comment]
Is there any working linux distribution out there? -.-

**Comment by ReinerBforartists** [comment]
Finally \o/

And Gnome. Yet another ass forward UI UX design in Linux manner XD

![assforward](https://github.com/Bforartists/Bforartists/assets/13919702/74c15697-c9de-4cc5-9f42-722406d37ca2)

**Comment by iyadahmed** [comment]
Mate is nice :)
https://docs.rockylinux.org/guides/desktop/mate_installation/

> Finally \o/
> 
> And Gnome. Yet another ass forward UI UX design straight from hell in Linux manner. And i thought the Ubutu desktop is bad XD
> 
> ![assforward](https://user-images.githubusercontent.com/13919702/262740122-74c15697-c9de-4cc5-9f42-722406d37ca2.jpg)

**Comment by ReinerBforartists** [comment]
Thanks for the hint :)

Not sure though if we should do this. I want to keep it as vanilla as possible. Either way, i need to redo the whole procedure anyways. I didn't give it enough ram and hdd space. I guess that's why it errored out with the first try.

And then i need to set up the compilation ...

**Comment by ReinerBforartists** [comment]
My blood pressure is already at 400 or so again.

Rocky does not use apt. What else is it using? What is the equivalent to sudo apt update and upgrade?

**Comment by ReinerBforartists** [comment]
Ah okay, dnf is the new apt ...

**Comment by ReinerBforartists** [comment]
I hate it. End of road. I cannot install the dependencies.

![endofroad](https://github.com/Bforartists/Bforartists/assets/13919702/3c7b5d58-3e8c-48dd-95ce-eca02d9e3ce1)

**Comment by ReinerBforartists** [comment]
Ah wait, i did download the html file instead of the raw ...

**Comment by ReinerBforartists** [comment]
\o/

![donwloading](https://github.com/Bforartists/Bforartists/assets/13919702/b202ff09-a6c1-4184-83ca-478a54212ac4)

**Comment by ReinerBforartists** [comment]
Fresh installed bare minimum rocky linux 8 VMware vm with 64 gb hdd space and 16 gb ram setting. https://cloud.bforartists.de/index.php/s/JPNWAmNMWcJQN8Z

Password is x, user is x. As usual.

Working at getting a compile result with blender now. But had already my fun with creating the target folder. I opened the terminal from Downloads, and Blender created the blender-git in the Home directory instead. wtf?

![canteven](https://github.com/Bforartists/Bforartists/assets/13919702/dc96c9df-83fe-4c5d-9f37-7cd7f7557288)

**Comment by ReinerBforartists** [comment]
Next trap. The gcc requirement. I have version 11.2.1 installed and it finds 8.5.0 at a vanilla installation? O_O

Sorry, but i stop here. Let's trash Linux support until the Linux developers supports humans.

![vanilla](https://github.com/Bforartists/Bforartists/assets/13919702/bce85fcf-8151-4f36-89ae-6385c0b0fe61)

**Comment by ReinerBforartists** [comment]
The vm where i am stuck with the gcc problem. Everything x. User, admin, password ...

https://cloud.bforartists.de/index.php/s/d6epNC2FFrJ5PKw

**Comment by ReinerBforartists** [comment]
Meow?

**Comment by iyadahmed** [comment]
> Meow?
add `source scl_source enable gcc-toolset-11` to your `~/.bash_profile`

form out docs :D
https://github.com/Bforartists/Bforartists/wiki/Building-a-Bforartists-(or-Blender)-3.5-release-build-on-Rocky8-Linux#update-and-build-a-release-with-path-to-optix-supplied

**Comment by ReinerBforartists** [comment]
Ah, totally overlooked it. Many thanks. Will give it a try in the next days :)

**Comment by ReinerBforartists** [comment]
Back at this problem ...

**Comment by ReinerBforartists** [comment]
Nope. scl enable gcc-toolset-11 bash does not help. And so it also makes no sense to add it to the bash profile.

![gccproblem](https://github.com/Bforartists/Bforartists/assets/13919702/6279ae26-e71a-45d5-b84b-56bdd0884ed5)

**Comment by ReinerBforartists** [comment]
Funny enough, the bash tells me version 11 is installed ...
![gcc2](https://github.com/Bforartists/Bforartists/assets/13919702/82a811e1-a526-4007-9a03-0c7c0a2a477f)

**Comment by ReinerBforartists** [comment]
Giving up 2.0 ^^

I've asked at Blender Developer now.

**Comment by iyadahmed** [comment]
> Giving up 2.0 ^^
> 
> I've asked at Blender Developer now.

maybe you should have done a clean build and remove the build folder ^^

**Comment by ReinerBforartists** [comment]
Sheesh, that's indeed it. Trapped by the cmake cache :D

Many thanks @iyadahmed , now let's have a look to get the other things working.

**Comment by ReinerBforartists** [comment]
Are we still at Optix 7.3 for Blender? Nvidia has released Optix 8 meanwhile ...

**Comment by ReinerBforartists** [comment]
Installled all needed now. Compiling. Let's have a look if everything arrives and the compilation finishes without errors.

![compiling](https://github.com/Bforartists/Bforartists/assets/13919702/0dadfb2d-50a9-4d20-ae6f-6fdbb340e33b)

**Comment by ReinerBforartists** [comment]
Done. No errors. Zipping and uploading the vm to the cloud.

![rocky](https://github.com/Bforartists/Bforartists/assets/13919702/7fc5eec0-bc83-4713-8d78-3a5bbde67c92)

**Comment by ReinerBforartists** [comment]
Done. Rocky VM is up. It can be found in the cloud in the shared folder.

Direct download here, around 20 gb https://cloud.bforartists.de/index.php/s/fHgGy33s4TW8iyY

Let's wait for the next release before i remove everything ubuntu. You never know ...

But this thread is fulfilled. Closing.
