### ISSUE TITLE
bfa_find_and_replace addon, attribute error NoneType has no attribute keymaps

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3623]
We have recently added a addon called bfa_find_and_replace addon. And this one now throws an error at compiling at Linux. We should add a check for none i guess ....

![compileerror](https://github.com/Bforartists/Bforartists/assets/13919702/e486e73a-cb5f-4f3d-bc2e-14d8cbd27c5a)

**Comment by Blenux** [comment]
I'll look into this sometime today.

**Comment by Blenux** [comment]
still trying having compile issues :(

**Comment by ReinerBforartists** [comment]
Hmm, this is at registering the keymap. We cannot add a check here.

@Blenux, what would be your idea here to solve the problem? I can compile to test it. Just make a branch and push your changes.

![problem](https://github.com/Bforartists/Bforartists/assets/13919702/453419f4-eca3-4ff5-b66c-3331f8e4b996)
