### ISSUE TITLE
Addon - Text Editor Find popup - Expose Shift+RMB to interface for discoverability

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3624]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6c43c410-1253-4717-964e-a237c15fb48b)

Took me a second to find this new BFA feature, maybe a header button to show discoverability may help that registers with icon with the addon. We usually try keep hidden panels somewhere in the GUI too.

**Comment by ReinerBforartists** [comment]
Yes, would be a nice improvement of the addon.

**Comment by Blenux** [comment]
Hows this?

![Screenshot_20230706_101255](https://github.com/Bforartists/Bforartists/assets/25260650/17de2c35-2694-4e5f-80f2-a17b46281e9a)

**Comment by ReinerBforartists** [comment]
I'm a bit biased here. I want to show as few buttons in the ui as possible. But yeah, looks like a good solution. In this case though i would change the hotkey to have ctrl f to open the popup, and not longer the sidebar. Or we put the addon into one of the text menus. view or edit.

**Comment by ReinerBforartists** [comment]
Hm, the other search functionality can be found in the edit menu. So i would say, append the addon here too.

![findineditmenu](https://github.com/Bforartists/Bforartists/assets/13919702/6c53023f-f725-4521-9311-0c916e49d290)

**Comment by ReinerBforartists** [comment]
ah, it's a panel, which cannot be appended to a menu ... and my brain.exe is out of order today. Too hot here ...

**Comment by ReinerBforartists** [comment]
I would've loved to have it in the edit menu. But it's a dead end. Wouldn't help with the hotkey issue anyways since this would go across an extra operator, even when i would manage to fix this error. So i stop here.

Hmm, what options do we have now? Header would be one. Investigating.

**Comment by Blenux** [comment]
Will look into it, might even rewrite the addon proper if needed.

**Comment by ReinerBforartists** [comment]
Too late, already fixed :D

Is appended in the header now. What didn't work is that the popup panel shows the tooltip. And you cannot change the hotkey neither. But that's the case for all panels. And i have simply added the info as a tooltip text. So i'm happy with this solution.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/24bc83f6-177e-4ba7-81f8-f25ab7fbec5f)

**Comment by ReinerBforartists** [comment]
I made it a bit wider if you don't mind. From 16 units to 20. I am always in trouble with showing the full text ...
