### ISSUE TITLE
Geometry Nodes Editor - Add Menu - Group - Add label to indicate marked and listed nodgroups as assets

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3626]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/9d0e6439-2b88-454a-a766-47bc5cc244eb)

Right now when you have assets marked as node groups (and in the future, as Hair Curve nodegroup operators in the 3D View), there needs to be a GUI indication of how it's done or what they are. 

Ei.. an icon and a label to say "Node Group Assets" or something would be nice. 
Even better with a tooltip to say "All marked nodegroup assets in your library will be listed here"

**Comment by Draise14** [comment]
Unfortunately no, since it loads all user node groups assets too.

**Comment by ReinerBforartists** [comment]
So we could call it assets? :D

**Comment by ReinerBforartists** [comment]
I would vote to leave as is. No further icon, the icons are already at the menu items. And we usually don't iconize menus, just menu items ( some exceptions aside like in the add menu. And renaming this would confuse users coming from Blender.

**Comment by Draise14** [comment]
Yeah, I guess now with the node group icon there, it's all ok and clear enough.
