### ISSUE TITLE
3D View - Annotation D hotkey conflicts with Tweak D hotkey

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3630]
![bforartists_kOe4xk6YjO](https://github.com/Bforartists/Bforartists/assets/35357409/608834d7-6388-4a2d-88ef-7cc134b95387)

Right now, both Annotation draw and Tweak hotkeys are conflicting with `D`, with priority to Tweak. Meaning.. it's impossible to use the annotation tool easily till you select it. Might need some improvement there. 

### Issue
0. Make sure you have an annotation layer and switch to any tool other than tweak
1. Press and hold D
2. Draw an annotation
3. Notice you also switched to tweak.

**Comment by ReinerBforartists** [comment]
Could you please add a screenshot and further informations?

**Comment by ReinerBforartists** [comment]
Ah, here it is. Amazingly overlooked. And interesting problem. Annotate tools doesn't have any UI entries? Hotkey only?

*sad cat noise*

![interesting](https://github.com/Bforartists/Bforartists/assets/13919702/1e37df7b-0d46-42dd-a6a6-62c3f8ac09ee)

**Comment by ReinerBforartists** [comment]
Hmm, well besides that it does in fact reset the tools to tweak tool it seems to draw under all circumstances. And i don't explicitely select it. You need to have a valid annotation tool though.

**Comment by Draise14** [comment]
The legacy annotation tool indeed does not have a GUI entry.. huh

**Comment by ReinerBforartists** [comment]
Hmm. Ii still don't see a way to solve it in a good way. Ideas?

**Comment by Draise14** [comment]
Here is an idea

1. Change D to Tweak to Click instead of press, so that when I press D and draw, it won't change to tweak automatically and you remain in the tool you want. 
2. Add the legacy operator for Grease Pencil drawing tho show the hotkeys and operators in the GUI under the View header menu. 

_I tested, and yeah, on tweak D with click it removes the double operator trigger thus the conflict._

**Comment by ReinerBforartists** [comment]
Sounds nice.

**Comment by Draise14** [comment]
![Carnac_B3TR7fZF3g](https://github.com/Bforartists/Bforartists/assets/35357409/dc5320ae-2b05-41ce-aacc-cea6198e7dba)

There we go, now tweak is hit when you hit, and drawing annotations doesn't trigger. Will now add to GUI then do documentation. 

I think I will review one or two more before doing the release branch later today.

**Comment by Draise14** [comment]
![bforartists_OZ8Jrvnf1m](https://github.com/Bforartists/Bforartists/assets/35357409/34815ea0-f3e2-46ac-b7a3-a3f99945467f)
![bforartists_HaBvwpC9YM](https://github.com/Bforartists/Bforartists/assets/35357409/b9677cca-8347-4d68-b497-ccb0a3ed456c)
![bforartists_KCHBP26aYK](https://github.com/Bforartists/Bforartists/assets/35357409/72fdae44-a683-4ec7-a9a7-0105ee7aecea)
![bforartists_omiUGixfjV](https://github.com/Bforartists/Bforartists/assets/35357409/e0b991db-6c06-4796-a7e4-2e6466ceff16)

# Update:
- Tweak is now D Click (instead of conflicting press)
- D B is now Add Annotation Layer  (before it was only a grease pencil operator, ei, broken UX)
- D Delete is Erase Annotation Active Keyframe (before it was only a grease pencil operator, ei, broken UX)
- All annotation operators are exposed to the the View Menu after the legacy or checkbox group. 

Now documenting this one, may be big...

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/26822e84-2605-4e61-bef2-c6100f55aa29)

Named it "Annotations (Legacy). I think this is done now.
