### ISSUE TITLE
My meshes we're corrupted

### ISSUE THREAD

**Issue by Eamaru** [Bforartists/Bforartists#3632]
**Describe the bug**
I was working on several projects, but then i opened up one and it was a crappy, broken mesh, i opened another one, same thing, also, all the other backups we're corrupted as well

**Desktop (please complete the following information):**
The Operating system. Windows 11 What graphics card? Intel(R) UHD Graphics

**Screenshots, Example Files**

![Captura de pantalla 2023-07-17 200459](https://github.com/Bforartists/Bforartists/assets/82003665/77f904ed-b794-4c6e-91a7-1c48e1e0284d)
![Captura de pantalla 2023-07-17 201345](https://github.com/Bforartists/Bforartists/assets/82003665/3e3f33b9-dd58-4721-ac3d-f37ff1fb49cb)

**Comment by Draise14** [comment]
Can you give us more info about your graphics?seems like a driver issue or a draw issue. 

Could you attach one of the corrupt files?

**Comment by ReinerBforartists** [comment]
Yes, looks like a display problem with your Intel onboard graphics chip.

**Comment by Eamaru** [comment]
As in the picture, the original structure is completly gone (sorry for my english)
The topology is completly broken and there is aparently no way to turn it back

**Comment by Eamaru** [comment]
> 

Sure! https://www.mediafire.com/file/5ez3rila10lsilv/yayos2.blend/file Sorry, i have to send it in this format, github doesn't allow .blend files

**Comment by Eamaru** [comment]
Wait... it just went back to normal. I'm sorry to complain about this, i didn't try re-opening the files, but this is still a weird issue, if it happens again i'll post it on this forum, thanks a lot
