### ISSUE TITLE
Fcurve Editor - Key - Smooth - Operators needs iconography / New Buttersworth Smooth operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3636]
![image](https://github.com/Bforartists/Manual/assets/35357409/563e5eca-69cf-455a-907e-85aaf4713a31)

This may also be a regression, but these icons are missing, also there is a new operator, but could be the same icon. 

This will require additional documenation, so will make a task for that. [#455](https://github.com/Bforartists/Manual/issues/455)

**Comment by ReinerBforartists** [comment]
Already fixed with this issue: Fcurve Editor - Key - Blend - Remove double entries #3637
