### ISSUE TITLE
 Fcurve Editor - Key - Blend - Remove double entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3637]
![bforartists_oj0ZT7rLB4](https://github.com/Bforartists/Manual/assets/35357409/66990100-e86c-49d5-910a-58f42f41b641)

This may be a regression, but many of these operators lost their icons. Documentation may need double checking.

**Comment by ReinerBforartists** [comment]
All i can see here is that you have added the Blender menu back. And added double content with it. Except one entry, the smooth (gaussian) is new.

Question is which menu to keep.

![doubles](https://github.com/Bforartists/Bforartists/assets/13919702/1f19b994-01a4-436b-ba25-2e894c47ce35)

**Comment by Draise14** [comment]
Ah, that's where they are. 

I vote.. move them all up a level, no sub menu.

**Comment by ReinerBforartists** [comment]
be aware of the blender hotkeys. we need to keep at least the classes of the menus

![blendermenu](https://github.com/Bforartists/Bforartists/assets/13919702/f8dd5523-6da4-4e2f-aed9-72789c655bdb)

**Comment by ReinerBforartists** [comment]
Hm, i hate it to do it the Blender way. Blend and Smooth doesn't tell you the slightest what tools are inside of these menus. But the Blender way exposes the hotkeys. Hmmhmmm.

**Comment by ReinerBforartists** [comment]
On the other hand, we don't have hotkeys for these sub menus. So, let's iconize and hide the sub menus away, but keep them to be called with the Blender hotkeys.

**Comment by ReinerBforartists** [comment]
Fixed

Sub menus still exists for the Blender keymap. And has icons now.

Updating the manual, we have new menu items.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/da16ca6e-93b2-4de6-b5eb-178743a12cdc)
