### ISSUE TITLE
3D View - Add "Move to Collection" to Object menu located in context menu only / Expose Collection operators again

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3638]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5d6a5c81-dcf8-4730-9d3b-2d8f7a745ccd)

# Case
Right now the operator `bpy.ops.object.move_to_collection` is in the right click context menu in the 3D View and can work from there, but not in the header. We removed it a while back as redundant and in Outliner exclusively.. but every first of Bforaritsts use I miss managing object data in collections directly from in the 3D Viewport, and setting it up again and quickly and to assign the hotkey again requires finding that one operator in the context menu or knowing it pre-exists in the API for the 3D viewport to be set in the keymap entries. Andother collection operators are not discoverable in the 3D View at all. 

So.. yes, the same operator is in the outliner, but we should either have consistency and/or discoverability in relevant editors that use these operators. I vote to have the operator discoverable in the 3D view also like in the outliner and not only the outliner (since you can't call outliner hotkeys from the 3D view) after assigning from the GUI. 

This is the hidden blender menu removed to reduce repeat operators in the overall GUI. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ea5e3d5d-5aa5-49d9-8e88-df652d515464)

In Bforartists, these operators only show from outliner and can be used only from outliner, no-longer possible in the 3D View after assigning hotkeys. They are not discoverable in the 3D Viewport. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4069ace5-200f-4d50-9e3b-a5f64c4286cb)

# Solution
Expose these to the header again

# Reason
After trying to use Bforartist over a year since we cleaned that up, I haven noticed I mostly drag and drop into collection in the outliner, and the operator to move to collection I use most from the 3D Viewport. For a user coming in from Blender, might make sense to expose that - and for a user coming from elsewhere, would be good to show that you can arrange collections from the 3D View just like you can with Bone Layers, Grease Pencil layers, Vertex Groups, and more. We probably should make these discoverable also from 3D View. 

To justify the double entries.. they are similar to "view" operators of multiple editors, they are are common operators between two editors, so they should be exposed in both editors seperately, not only one and assume the user knows they can also do this in the 3D View....

**Comment by ReinerBforartists** [comment]
Not exactly sure what exact menu items you want to move where here, so leaving this to you.

**Comment by Draise14** [comment]
Ah, it's one that's only in a context menu.

**Comment by Draise14** [comment]
Ok, one more, then lunch, then release - at least windows and the documentation.

**Comment by Draise14** [comment]
Commit to master
