### ISSUE TITLE
Missing transform icons in Object > Transform menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3641]
Lost in merge i guess ...

![scale](https://github.com/Bforartists/Bforartists/assets/13919702/6b6f91e9-df5f-4823-b784-49180cb9bef0)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/240d8352-cd70-4180-9fa7-bb4301f337c8)

Done, committing to master
