### ISSUE TITLE
Linux - change the targetfolder name

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3646]
Currently both, Blender and BFA compiles with a make into a folder called build_linux. Which conflicts with each other then.

We should rename our build_linux target folder to build_linux_bfa or bfa_build_linux

![targetfolder](https://github.com/Bforartists/Bforartists/assets/13919702/e941fdb4-03f6-4641-9ad7-23a27599524e)

**Comment by ReinerBforartists** [comment]
Curious one. I thought this is one of the easiest tasks ever. But the string is not to find :D

**Comment by ReinerBforartists** [comment]
In case we can catch it, we would need to change it for the github actions too.

![actions](https://github.com/Bforartists/Bforartists/assets/13919702/bdff967e-e9b5-4e0b-8a27-9e7e3b580ba6)

**Comment by Draise14** [comment]
Yeh, this would be a nice touch.

**Comment by Blenux** [comment]
ah I was about to see if we could change too :D

**Comment by ReinerBforartists** [comment]
Just do it, i still try to find where this hides :D

**Comment by ReinerBforartists** [comment]
I think it's in the GNUmakefile. Just still at figuring out if we need to add our bfa string to the single build configurations below line 240. Or if i can find the BUIL_DIR definition.

**Comment by Blenux** [comment]
![Screenshot 2023-07-28 092412](https://github.com/Bforartists/Bforartists/assets/25260650/dc004505-dff0-4915-90ea-84b1cd6eb070)

**Comment by ReinerBforartists** [comment]
Yeah, looks good. Do you want to commit it? :)

**Comment by Blenux** [comment]
Can do

**Comment by ReinerBforartists** [comment]
Excellent. I had a look at Windows meanwhile, and i think i have already catched the windows build folder in the past. This should also work with a simple make.

But don't forget the linux.yml in the .github\workflows folder :)

![build](https://github.com/Bforartists/Bforartists/assets/13919702/d54b2a2b-4b58-4cac-859f-040eecc831cd)
