### ISSUE TITLE
Ubuntu crash with Bforartists and Blender - OpenGL version too low at Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3647]
Separated from this thread here: https://github.com/Bforartists/Bforartists/issues/3640

I am not longer able to compile Bforartists or Blender at Ubuntu. Better said, it compiles fine, but doesn't start anymore. And throws an error.

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

Alsoft is audio driver.

I have so far tested both, Blender and Bforartists, and also used a old backup of the VM to rule out that a Ubuntu update has something to do with the problem. 

Next test is to setup Blender again on one of the blank backups of the VM. I think i have a copy in the cloud.

**Comment by ReinerBforartists** [comment]
![255317034-c9aecfdb-9c1a-47cd-a749-bf327d3ba393](https://github.com/Bforartists/Bforartists/assets/13919702/f9681d5b-d2c4-41ae-8a55-cc34782c98d9)

![255384491-b7598494-055e-426e-9b9e-a98a43e933f0](https://github.com/Bforartists/Bforartists/assets/13919702/1e9f2459-141f-4f70-a725-9420f50fa062)

**Comment by ReinerBforartists** [comment]
Same on a completely fresh Ubuntu 22.04 VM. The one that i used to test if Ubuntu crashes with Cuda 12 ...

I think i will ask at Blender Developer now. Maybe somebody there knows what is going on.

**Comment by ReinerBforartists** [comment]
Okay, Audio has nothing to do with it. Turning off With_Audaspace will let the error messages in the console go away. But the crash remains. I load it currently with the linux debugger gdb. Let's see what this brings up.

**Comment by ReinerBforartists** [comment]
This is what i get

![segfault](https://github.com/Bforartists/Bforartists/assets/13919702/6b7c867c-2fe1-41fd-aa01-4d8863b5da93)

**Comment by ReinerBforartists** [comment]
Ah, an actual version from builder.blender.org crashes the same way.

**Comment by ReinerBforartists** [comment]
Turns out that the minimum version for OpenGL has risen to 4.3. And a vanilla Ubuntu 22.04 LTS just provides version 4.1. 

Sounds like the end of our linux versions. I cannot build it anymore.

**Comment by ReinerBforartists** [comment]
![ogl](https://github.com/Bforartists/Bforartists/assets/13919702/7317624a-f4a2-4428-8b43-49d844199085)

**Comment by Draise14** [comment]
Looks like Rocky 8 VM time.

**Comment by iyadahmed** [comment]
Also note that this is just a problem with running Blender and Bforartists not compiling, an Ubuntu with Nvidia drivers should work I suppose

**Comment by ReinerBforartists** [comment]
Sheesh Ubuntu. I checked three times now if i do something wrong with the installation, and started over from scratch. No idea why Ubuntu doesn't let me in ...

![password](https://github.com/Bforartists/Bforartists/assets/13919702/e230226b-cf8c-4237-bb5b-d2f328308c40)

**Comment by ReinerBforartists** [comment]
Savest OS ever. Even Users cannot damage it ...

**Comment by ReinerBforartists** [comment]
Okay, after once more the biggest effort ever, Ubuntu 23 has OpenGL version 4.3. So we have at least a test vm. Will check tomorrow if really true ^^

![ubuntu23](https://github.com/Bforartists/Bforartists/assets/13919702/0d1ac76c-e6aa-4dca-97cd-0ef462c90951)

**Comment by ReinerBforartists** [comment]
Ah, nothing than trouble with Linux. Copy n Paste does not work for this VM. So i have still no way to test the build from the 22.04 version -.-

**Comment by ReinerBforartists** [comment]
I can copy and paste text. So in general it works. But i cannot copy and paste files. Crazy. I tried now everything that i found in the internet. But my only option seems that i upload the file to the cloud and download it then.

We need also with Rocky a way to test if our compilation works. Because i expect that also Rocky 8 has a too low OpenGL number.

**Comment by ReinerBforartists** [comment]
Well, at least i can now say the problem is really OGL 4.1 at Ubuntu 22.04. And that the compiled result works at Ubuntu 23.

![works](https://github.com/Bforartists/Bforartists/assets/13919702/15cd0330-2f72-440a-a31b-3eee9f0303e7)

**Comment by ReinerBforartists** [comment]
Closing this task. We found the cause. But we can simply don't do anything besides having a linux distribution to test what we compile. 

Related https://github.com/Bforartists/Bforartists/issues/3622
