### ISSUE TITLE
Error when compiling master

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3649]
More C -> C++ woes

![WindowsTerminal_Mdc9kEZDAF](https://github.com/Bforartists/Bforartists/assets/35357409/4abe0187-b098-4752-ac73-ad6c80d03f10)
![WindowsTerminal_nSOeeO7rfK](https://github.com/Bforartists/Bforartists/assets/35357409/37a4ef54-2784-46d2-9d7b-f061687a0a13)

**Comment by iyadahmed** [comment]
Fixed in https://github.com/Bforartists/Bforartists/commit/fdd07a7daceb8539e97befa9b2bbc442deb86822
