### ISSUE TITLE
Default Workspaces - All Compositing is not the same as VFX Compositing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3651]
## VFX Compositing 
![bforartists_d38neekfiP](https://github.com/Bforartists/Bforartists/assets/35357409/38b7fe63-494e-478a-9836-816e55056d4a)

## All Compositing
![bforartists_3opQRcmFsg](https://github.com/Bforartists/Bforartists/assets/35357409/485b4c42-c7cc-4354-a308-40179ad657b6)

They should be the consistent, with the first being the target.

**Comment by ReinerBforartists** [comment]
Close enough

![closeenough](https://github.com/Bforartists/Bforartists/assets/13919702/c39279d9-5f6d-4734-9f09-2b1bf6c5ce7d)
