### ISSUE TITLE
3D View - Sculpt Mode - Sculpt operators -  New "Invert Visible" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3657]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/eef20f20-55ea-48d4-a5f7-47cac0e8a462)

New operator "Invert Visible" needs iconography, adding to toolshelf and documentation.

**Comment by ReinerBforartists** [comment]
Double of 3D View - Sculpt Mode - Sculpt Operators - New "Hide Masked" operator #3658

Closing.
