### ISSUE TITLE
3D View - Sculpt Mode - Sculpt Operators - Remove double "Hide Masked" and "Invert Visible" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3658]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1b41cd35-ddaa-47d3-96d0-04eef4fff039)

New operator "Hide Masked" needs iconography, adding to toolshelf and documentation.

**Comment by ReinerBforartists** [comment]
These two operators are not new. But a merge regression. A double menu entry coming from Blender.

Please don't develop Bforartists back to Blender ^^

![showhide](https://github.com/Bforartists/Bforartists/assets/13919702/bb4384e8-8f81-48ac-b880-c0fef7c45817)

**Comment by Draise14** [comment]
Oh, it's there already. So remove the double. Didn't notice, sorry.
