### ISSUE TITLE
Merge - Sunday July 30th 2023

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3663]

**Comment by iyadahmed** [comment]
First step I update my local Blender repo using `make update`, since I have my "blender" remote URL set to local repo, saves internet bandwidth I only have to download things once, I do similar thing with lib folder, I use a symbolic link so both Blender and BFA use same folder
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b0665b8d-8f89-463e-826f-db193937b03b)

**Comment by iyadahmed** [comment]
Next I run `git fetch blender main` inside the Bforartists repo
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b30a400e-a42b-494d-9f3a-4dbac3472f8a)

**Comment by iyadahmed** [comment]
let's also pull `master` and `sync_blender_master` in case there were changes submitted by friends

**Comment by iyadahmed** [comment]
let's checkout `sync_blender_master`
and run `git merge master`
so `sync_blender_master` includes all changes from `master`
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b72557a0-bd43-4409-a4d2-5bc0aded2f78)

**Comment by iyadahmed** [comment]
Now we can run `git merge blender/main`
![image](https://github.com/Bforartists/Bforartists/assets/25552173/5604dea4-d54a-4c07-a01f-bd26a814b65c)

**Comment by iyadahmed** [comment]
82 files have conflicts
![image](https://github.com/Bforartists/Bforartists/assets/25552173/9a46afd1-47d4-42fa-ba45-407ee6c39323)

**Comment by Draise14** [comment]
A mammoth merge this one.

**Comment by iyadahmed** [comment]
Yep working on it ^^

**Comment by iyadahmed** [comment]
63 to go ^^, I went to aunt ^^
![image](https://github.com/Bforartists/Bforartists/assets/25552173/1988d473-7173-4446-be40-2d3e9c990229)

**Comment by iyadahmed** [comment]
37 to go
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b431e21a-5533-4192-a11b-5c4bc420b6a2)

**Comment by iyadahmed** [comment]
always nice to see these ^^, Blender finally catching up to some of the stuff we did ^^, like exposing hidden stuff ^^
so finally that line of code is the same ^^
![image](https://github.com/Bforartists/Bforartists/assets/25552173/08b6d401-c60d-44e4-af6a-73def9a29745)

**Comment by iyadahmed** [comment]
Finally finished all files, now to testing build and updating addons
![image](https://github.com/Bforartists/Bforartists/assets/25552173/9ab46be0-20d3-4e2e-86af-2e225862b0af)

**Comment by iyadahmed** [comment]
Making modifications to fix build errors
![image](https://github.com/Bforartists/Bforartists/assets/25552173/8d6b1c54-4883-43ed-b7fa-7480809b67a5)

**Comment by iyadahmed** [comment]
A roadblock, unused function, that is used...
![image](https://github.com/Bforartists/Bforartists/assets/25552173/25c2844f-760c-4f06-9b73-046f9e71a465)

**Comment by Draise14** [comment]
I found a similar issue last merge. The C toC++ makes the Bforartists split comments break, and they need some updates sometimes.

**Comment by iyadahmed** [comment]
Have just found it, was an extra bracket ^^,
a reminder to look at the very first compiler error not last

**Comment by iyadahmed** [comment]
Successful!
![image](https://github.com/Bforartists/Bforartists/assets/25552173/622bdfff-0c57-4410-be5e-216840e0e43a)
next is updating addons

**Comment by iyadahmed** [comment]
getting these warning though hmm
![image](https://github.com/Bforartists/Bforartists/assets/25552173/69e1d7b6-8a7b-4559-88c6-2e8acee7a74d)

**Comment by iyadahmed** [comment]
I think it is related to this, the "ui_mode" of image editor, needs a separate issue
![image](https://github.com/Bforartists/Bforartists/assets/25552173/93c5ca05-8668-4252-8273-9c8d4c9a047c)
in any case addons are now upadted pushing to master soon

**Comment by iyadahmed** [comment]
Done :white_check_mark: 
we should probably check if the light issue still exist, I don't remember how to reproduce that, and my Discord is deleted
https://github.com/Bforartists/Bforartists/commit/5d297f3b6a052fc4accbdb259b04efbce3c2b710

**Comment by Draise14** [comment]
Tested the eevee issue, now gone. Thank you.
