### ISSUE TITLE
Compile Warning - Space_Toolbar.c - info_blende_write no-longer used.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3664]
![vmplayer_4LzzEvUJQQ](https://github.com/Bforartists/Bforartists/assets/35357409/bd0b1db8-0cac-4ed0-b1d2-5a7cb845b07f)

Something is amok here, should be cleaned up.

**Comment by Draise14** [comment]
Commented out, so far compile did no more warning, and toolbar is still there.

**Comment by ReinerBforartists** [comment]
Fingers crossed ^^
