### ISSUE TITLE
Shader Nodes - Cycles - Rename Velvet BSDF to Sheen BSDF

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3667]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/709144d5-17c1-4771-8b47-f58cdd7498a7)

Velvet BSDF is now Sheen BSDF. Probably needs to be updated in documentation too, this also is relevant only to Cycles

<details>
<summary>Blender Task</summary>

SHA-1: b220ec27d7db68aca9a8c500ecd8c99efcdecbc5

* Cycles: Update Velvet BSDF to Sheen BSDF with new Microfiber sheen model

This patch extends the old Velvet BSDF node with a new shading model,
and renames it to Sheen BSDF accordingly.

The old model is still available, but new nodes now default to the
"Microfiber" model, which is an implementation of
https://tizianzeltner.com/projects/Zeltner2022Practical/.

Pull Request: https://projects.blender.org/blender/blender/pulls/108869

</details>

**Comment by ReinerBforartists** [comment]
Blender devs, adding name confusion since 1784 ...

**Comment by ReinerBforartists** [comment]
Updating manual

**Comment by ReinerBforartists** [comment]
Fixed
