### ISSUE TITLE
Compositor Editor - Options - Performance Panel - Float checkbox left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3669]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a8cdc8e1-3900-481a-a95e-dce915b7f8b2)

Middle aligned checkbox should be left.

**Comment by ReinerBforartists** [comment]
Updating manual 

![left](https://github.com/Bforartists/Bforartists/assets/13919702/5448bff4-a178-4a74-8b13-7d51dc153268)

**Comment by ReinerBforartists** [comment]
No manual update necessary. This was a merge regression.
