### ISSUE TITLE
Default Theme - Preferences and File Browser execution and tab background went dark

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3670]
# Issue
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2462d5d0-9424-437b-a472-da8979143062)

With Blender, some background colours were changed in our default theme. 

## Notes
I have tried to fix it, but it looks like the Userpref.blend file `blender_theme_as_c.py` to setup the factory theme is somewhat broken. So I haven't had luck generating the factory theme. 
![WindowsTerminal_3oxhM4cJUc](https://github.com/Bforartists/Bforartists/assets/35357409/b3ced0a3-a1aa-444e-8abb-d48d9e6a39e7)

I'm following these instructions for theme updates:

> To do changes to the default theme, you have to recompile them to the repository. The theming is not stored in the startup.blend. But needs to be recreated.
> 
> 	1. Save the theme to disk from the theme Editor in the User Preferences. The Add Preset button does this then saves it in to the user preferences folder. 
> 	2. Grab the *.xml from the appdata folder, and replace the one in the \scripts\presets\interface_theme with the new one.
> 
> 	1. To change the factory presests you need to save a userpref.blend, throw it into \tools\utils
> 	3. Then open the blender_theme_as_c.py file, and follow the instructions there. 
> This script recreates the userdef_default_theme.c in the \release\datafiles\userdef then.

# Fix

Suggested Fix:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/42a6df85-6e09-442d-a2b8-d9531ef10f95)

Preferences Editor
![bforartists_OblBMZPCjP](https://github.com/Bforartists/Bforartists/assets/35357409/e2f6e15c-cc3e-47e1-a5e9-380b2b96ce08)

File Browser
![bforartists_ceqJ3huFQh](https://github.com/Bforartists/Bforartists/assets/35357409/4e2b9d9f-7790-4a6a-b2b2-a24880483227)

**Comment by Draise14** [comment]
Reported Blender theme making bug
https://projects.blender.org/blender/blender/issues/110732

**Comment by Draise14** [comment]
Blender bug was fixed. I nearly was ignored since they don't track compiler bugs in the the Blender tracker. 

Here is the commit. Now we can compile theme changes, but I would have to merge this file in. 
https://projects.blender.org/blender/blender/commit/1f612605ab4c515edb00d472835d46b885f4740c

**Comment by ReinerBforartists** [comment]
Yes, i also ran into this in the past. I find it odd. But they want to have such things reported at Blender Developer, and not in the main tracker. But i am happy that they have fixed it :)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/40128af2-d70c-4d98-a43f-c97358e16f4e)
 
 New script worked. Will commit to this branch.
