### ISSUE TITLE
Mac build (Intel) fails

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#3671]
**Describe the bug**
Attempting to build the latest dev version, I get the following errors and the build fails:

```
/Users/seanr/Projects/bforartists-git/bforartists/source/blender/editors/space_toolbar/space_toolbar.c:144:13: warning: unused function 'info_blend_write' [-Wunused-function]
static void info_blend_write(BlendWriter *writer, SpaceLink *sl)
            ^
1 warning generated.
/Users/seanr/Projects/bforartists-git/bforartists/source/blender/editors/space_clip/tracking_select.cc:43:14: warning: unused function 'dist_to_crns' [-Wunused-function]
static float dist_to_crns(const float co[2], const float pos[2], const float crns[4][2]);
             ^
1 warning generated.
/Users/seanr/Projects/bforartists-git/bforartists/source/blender/blenkernel/intern/blender.cc:379:9: warning: 'LIST_SWAP' macro redefined [-Wmacro-redefined]
#define LIST_SWAP(id) \
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/queue.h:551:9: note: previous definition is here
#define LIST_SWAP(head1, head2, type, field)                            \
        ^
1 warning generated.
```

**Desktop (please complete the following information):**
MacOS 13.4 (Intel)

**Comment by seanr** [comment]
Note that I tried upgrading cmake and python, but still get the error. My XCode tools are up to date.

**Comment by ReinerBforartists** [comment]
Hm. There are just three warnings. And none of it should have anything to do with a successful build. Is there more information?

This one could be the problem, but i am lost with this:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/queue.h:551:9: note: previous definition is here
#define LIST_SWAP(head1, head2, type, field)
```

**Comment by seanr** [comment]
This LIST_SWAP was what it marked, just updated the lead comment to add a line I accidentally omitted pointing that out. The next thing I get is this:

```
cp: build_darwin/bin/Bforartists.app: No such file or directory
```
That's from my shell script, so nothing happened in the build after those initial four warnings.

**Comment by ReinerBforartists** [comment]
Thanks Sean, the directory Bforartists.app exists. What we have double in this directory and what should not longer be needed is the Blender.app directory. But this should not conflict neither.

Question, does Blender compile? First we need to find out if it is a general problem, or a problem with Bforartists.

**Comment by Draise14** [comment]
With that screen capture and report, it looks like it's looking in the subfolder, when it's up one. there is not `darwin/bin/Bforartists.app` but `darwin/Bforaritsts.app` is ok.

**Comment by ReinerBforartists** [comment]
But it builds. And then the Bforartists.app must be in the bin folder.

I am unfortunately completely lost with anything Mac related. So the first important information is if Blender compiles or not. We cannot fix Bforartists when it is a Blender problem.

**Comment by seanr** [comment]
I think we can close this as I was able to get it to build finally with the following:
```
git fetch
git checkout bfa3v3.6.1
make update
make
```
Prior attempts I think may have gotten a wrong branch.
