### ISSUE TITLE
Crashes with typing in values while transform operations

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3680]
I have a user report that Bforartists regularly crashes when doing some transform operations. I have experienced such a crash too. But wasn't able to reproduce it in any way then. We should have an eye at it.

**Comment by Draise14** [comment]
I haven't experienced this yet, but I have seen some instability with AMD graphics reports on discord. There was one devbuild that was very crashy though - but that's in the past now. 

What specs are they using?

**Comment by ReinerBforartists** [comment]
I cannot say it. He also uses a older build of Bforartists i guess. I'll ask him.

The crucial part is, it happened to me. I way toying around with BFA for the release. But as told, not to reproduce so far.

**Comment by ReinerBforartists** [comment]
Not to reproduce. Finally giving up here. We need a proper way to reproduce the problem.
