### ISSUE TITLE
Object renders black

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3682]
Hey,

I have a user report at the forum about a scene that doesn't want to render the content. The object renders black.

https://www.bforartists.de/forums/topic/object-renders-black/

The attached blender file shows some oddities. For example, loading the blend file with a double click crashes Bforartists. I have to drag it into an open Bforartists instance to load the file. I also have yet to find out what the "Early morning birds eye view.001" object is.

The next thing is that the object in question is not to convince to render with a material even with adding the missing material. I also tried switching to Eevee, no success. The pink world background is a failing world shader setup. But fixing this didn't help neither.

And the last thing, the outliner in display mode Scenes shows me the whole content outside of the View layers. But i cannot move the collection inside of the View layer. It tells me it has, but nothing happens. And the View layer shows me the content correct.

So we have more than one problem. First step is to isolate the problems one by one, and make a task out of each.

And i am currently lost what is going on with the rendering. Somebody an idea why it renders black? It also renders black in Blender.

**Comment by ReinerBforartists** [comment]
[legobrick.zip](https://github.com/Bforartists/Bforartists/files/12319037/legobrick.zip)

Added the zip file here too.

![problems](https://github.com/Bforartists/Bforartists/assets/13919702/aa83c017-1904-4f1b-ab69-c1c44e5551e3)

**Comment by ReinerBforartists** [comment]
A, the early morning bird file is a world texture. That's why the pink background.

Remains black object and the crash with double clicking at the file.

**Comment by iyadahmed** [comment]
@ReinerBforartists 
same issue in Blender,
there's duplicate geometry, weld modifier fixes it

**Comment by ReinerBforartists** [comment]
Ah, didn't notice it. Thanks :)

**Comment by ReinerBforartists** [comment]
The crash is not invalid ^^

**Comment by ReinerBforartists** [comment]
Ah solved the crash. I had still a previous version installed. And blend files are not backward compatible ...

So, remaining is the outliner. Ideas? Shall this display in this way? Imho the content should be grouped under the scene collection.

**Comment by iyadahmed** [comment]
> Ah solved the crash. I had still a previous version installed. And blend files are not backward compatible ...
> 
> So, remaining is the outliner. Ideas? Shall this display in this way? Imho the content should be grouped under the scene collection.

what was the cause for crash?

**Comment by ReinerBforartists** [comment]
A too old BFA version. As told, blend files are not backwards compatible anymore. You need the equal or a newer version ...

**Comment by ReinerBforartists** [comment]
I am still baffled that the Scenes view doesn't show the objects hierarchically sorted under the collection where it belongs. But okay, Blender acts the same way. So let's finally close this issue.


![display](https://github.com/Bforartists/Bforartists/assets/13919702/a8c8e597-52c7-4abc-a4df-1f0aa62fb593)
