### ISSUE TITLE
Lux Core Render not working anymore in Bforartists 3.5 and above

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3685]
A user report. The BlendLuxCore addon seems to have quit working with Bforartists 3.5 and above. But works fine in Blender.

I expect this to be a problem with the Blender 4 code already.

https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1

**Comment by Draise14** [comment]
There is nothing we can really do here, so I will label as "Known Issue"

**Comment by ReinerBforartists** [comment]
Closing this issue for now. We all know the API drama, and there is nothing we can do.
