### ISSUE TITLE
3D View - Side Bar - Vertex Paint - Tool - Smooth stroke label missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3686]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f1f609da-7ee3-4bc2-b89f-5112932b43bb)

Missing Smooth Stroke label here.

**Comment by ReinerBforartists** [comment]
We have a bigger problem here. We have the exact same code than Blender. But for us the label does not show.

Now go figure ...

**Comment by ReinerBforartists** [comment]
Hmm, my guess is it's the panel import at the top. But why? Blender code works without, BFA goes crazy when we remove it.

![panel](https://github.com/Bforartists/Bforartists/assets/13919702/1c0764d2-43da-4add-9585-316f519ff8d7)

**Comment by ReinerBforartists** [comment]
Either way, needs a fix. 

Fixed.

I have while at it also indent the props in the popup panel. I would've loved to hide it away. But in this special Blender case (as usual) we can't without to rewrite lots of code. The prop is in the header, so we cannot add a triangle button easily ...

![indent](https://github.com/Bforartists/Bforartists/assets/13919702/ed1ebf8d-c6a6-43d4-b810-813cb8d83f46)

**Comment by ReinerBforartists** [comment]
Updating Manual ...

**Comment by ReinerBforartists** [comment]
Ah manual still fits. Closing.
