### ISSUE TITLE
3D View - Header - View - Viewer Node toggle should move to Overlay settings

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3687]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/68c83955-4597-43ce-9f7c-cecea5fa84eb)

There is a checkbox for the Viewer Node inthe header view menu that could be an overlay toggle. We probably should move that to overlays. It is an overlay.

**Comment by ReinerBforartists** [comment]
Yeah, options should be in optios menu. Some always makes it through ^^

**Comment by Blenux** [comment]
There is a option in Overlays already, with option to adjust Opacity, best to remove the header one?




https://github.com/Bforartists/Bforartists/assets/25260650/4da0fd8e-8fdb-4272-86c2-07f0aa70de0e

**Comment by ReinerBforartists** [comment]
Yes.
