### ISSUE TITLE
Webpage - Downloads are slow

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3691]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5d6fa2a3-e13e-4b09-8591-594a511bfe41)

A user on discord and twitter has reported slow or no ability to use the website. I also cannot download efficiently, even with 100mb/s download. So I wonder if something back-end is up?

**Comment by Draise14** [comment]
Speeds are back.

**Comment by ReinerBforartists** [comment]
As told at the discord, it is a cheap hoster. And has some hiccups from time to time.

Did i mention that the webspace is cheap? ^^
