### ISSUE TITLE
Functional differences in the class def brush_shared_settings(layout, context, brush, popover=False):

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3693]
We have a functional difference in the properties_paint_common python file.  use_frontface is not longer used in the Blender pyton file. Or never was?

Does somebody know what is going on here? Is this a deprecated prop, or a feature from us?

![use_frontface](https://github.com/Bforartists/Bforartists/assets/13919702/6d37ecb9-d37e-4391-a7a7-44903707a36c)

**Comment by ReinerBforartists** [comment]
Hmm, a few lines downwards there is use_frontface also in the blender file ...

![usefrontface](https://github.com/Bforartists/Bforartists/assets/13919702/400e21ef-a5b3-4c98-9d89-ba2ca4b788cb)

**Comment by Draise14** [comment]
I'll have to see where the prop is in what node for what object type. As far as I know it shouldn't be deprecated but blender had it inconsistently hidden. We may have had it exposed in a consistent way.

**Comment by ReinerBforartists** [comment]
Yeah, i had the same thought. This is one of the rare cases where a comment would make sense then.

**Comment by ReinerBforartists** [comment]
Blender has the term use_frontface six times in the code. We 11 times. 

I will try to remove the ones that are not in the Blender code.

**Comment by ReinerBforartists** [comment]
Found even an operator that we did miss. 

Fingers crossed that this cleanup was successful. Haven't encountered any console warnings so far.
