### ISSUE TITLE
Keymap - Double click marker to rename marker

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3697]
Double click LMB on marker renames marker

Blender did a good consistent thing here, double click to rename marker. I think we should do the same for our defaults. 

> For speed and consistency with other areas in Blender like Outliner,
UILists, animation channels, etc.

> This is additionally to F2 (Enter in Industry Compatible keymap),
that shortcut is still valid.

<details>
<summary>Blender Task</summary>

SHA-1: 26dcc961f575336c4e1ffa45cf310b7c9b07668f

* Markers: Use double-click to rename

For speed and consistency with other areas in Blender like Outliner,
UILists, animation channels, etc.

This is additionally to F2 (Enter in Industry Compatible keymap),
that shortcut is still valid.

Pull Request: https://projects.blender.org/blender/blender/pulls/111264

</details>

**Comment by ReinerBforartists** [comment]
We have already two methods to rename the marker. When we add the double click then it's three.

I will remove the ctrl M method and replace it by the left mouse double click.

**Comment by Draise14** [comment]
Good call.

**Comment by ReinerBforartists** [comment]
Done. Documenting.

**Comment by ReinerBforartists** [comment]
Done.
