### ISSUE TITLE
Create a Bforartists Full keymap

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#37]
The current Bforartists keymap is reduced to the essence. But adding own keys that doesn't conflict with other key combos is a daunting task. The blender keymap manager is not capable to deal with conflicts. You find it out when it breaks. We cannot bother the user with that. And so we need a full keymap. Which is this task.

This task is in development since a pretty while. And nearly done. So i won't copy over the whole discussions from the Bforartists tracker.

**Comment by Draise14** [comment]
Ok, good to see it here.

**Comment by ReinerBforartists** [comment]
Ah, good to see you here already. I'll invite you now to the team. So that you have full access.

**Comment by Draise14** [comment]
This weekend is a labour holiday, meaning I may have some time to polish the merge up a bit, apply the Numpad_0 over D fix check and remove unnecessary comment code and then start the experimental map as I move on to the new task of checking for conflicts/resolving/documenting Blender conflicts.

**Comment by ReinerBforartists** [comment]
Please first commit the full keymap before you start with the experimental keymap.

**Comment by Draise14** [comment]
Ok, now just need to learn to compile the repository and commit to a branch. 
Then I'll close this and just make smaller tasks for conflict resolution. Merge with Blender 2.79 is complete.

**Comment by ReinerBforartists** [comment]
Looking forward to it :)

When everything else fails, you can still give me the keymap and i'll include it then.

**Comment by ReinerBforartists** [comment]
Any news here? Shall i include the full keymap? And you have a look how git and things works at a later point?

**Comment by Draise14** [comment]
My deadlines never seem to end, currently in another. I have not tried the git system on the other workstation yet, nor been able to sign contracts with the guy who'll help me out. Maybe I'll get my artist to install the software and get the ball rolling. 

Should I upload the current progress here?

**Comment by ReinerBforartists** [comment]
Any news here? :)

**Comment by Draise14** [comment]
[bforartists - full - ver 0.9.1.zip](https://github.com/Bforartists/Bforartists/files/1915772/bforartists.-.full.-.ver.0.9.1.zip)

Here is the latest version - still needs cleaning up and still under verification process. 

All Blender shortcuts are commented, all changes are commented, all known conflicts are commented, all floating menus are mostly commented and noted to be changed to pie menus, and all sections are commented "Done" if checked and ok with no conflicts.

**Comment by ReinerBforartists** [comment]
Thanks a bunch. I'll include it now :)

Mh, the conflicts should be issues in the tracker. But we can do this at a later point. I have other tasks first to solve.

**Comment by Draise14** [comment]
Ah ok, the conflicts I noted are exclusively Blender to BFA mostly, meaning Blender's get's changed. Everything else BFA related is pretty much identical to current map.

**Comment by ReinerBforartists** [comment]
Before i forget, many thanks for your effort so far. I know this was/is a huge task :)

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch. Keymap is added. 
https://github.com/Bforartists/Bforartists/commit/e07902d9cc55ce3e121c16808e1bb0567c167f60
