### ISSUE TITLE
Addon + Keymap - Default addons that add hotkey entries to the keymap will double with every modification

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3700]
One of the addons is adding keymap entries with every further modification. 

First, please take an eye at it when doing modifications at the keymap. One entry is enough. Second, we should start to find out which addon causes it. I think it could be our asset addon. 

![poselibaddon](https://github.com/Bforartists/Bforartists/assets/13919702/3d226686-b84a-4ad8-a593-57cfd8f4c27c)

**Comment by ReinerBforartists** [comment]
Ah, and the find and replace addon does it too ...

![findandreplace](https://github.com/Bforartists/Bforartists/assets/13919702/609c3796-8800-4186-bc7f-8b371338346f)

**Comment by Draise14** [comment]
The asset library addon shouldn't be registering any hotkeys.

**Comment by ReinerBforartists** [comment]
Good catch. And Blender does even have it activated by default too. I guess the only reason why it doesn't cause the same problem than with BFA is that Blender doesn't resave the keymap file with changes, but does the changes directly at the code.

I don't see a way around this problem. Addons that are activated by default and adds a keymap entry will add to the keymap every time we modify the BFA keymap by the keymap manager. I don't write changes by hand in the code. So shall we close this as a known issue, with a hint to take care when modifying the keymap?

**Comment by Draise14** [comment]
Yeah, will put that to my docs to publish soon. 

Right now it's two addons writing keys?

**Comment by Draise14** [comment]
Ok, disabled the found confirmations for consistency, and removed doubles, and reverted the track confirmation, now it's ok in keymap.

**Comment by Draise14** [comment]
Oops, commit to the wrong task. I will tag this one as a known issue. 

**Addon entries doubling up:**
`BFA_PT_FIND_AND_REPLACE`
`poselib.apply_pose_asset`

**Comment by ReinerBforartists** [comment]
Then let's close it. Just take care that you don't add dozens of entries over the time.
