### ISSUE TITLE
Keymap - 3D View - Mesh Edit context menu is Double RMB, should be single click

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3701]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6d20bf7c-5979-4c2e-94a9-6da91a2dd738)

Right now the mesh edit context menu is double RMB instead of single click. This is inconsistent, and not a nice UX. Changing it to be the same as the object mode and other modes will make it easier to discover and use.

**Comment by ReinerBforartists** [comment]
I thought we had catched them all ...

**Comment by Draise14** [comment]
Aye me too... Maybe it's a regression from the buggy keymap system.

**Comment by Draise14** [comment]
Grease pencil context menu too

**Comment by ReinerBforartists** [comment]
Aww. just pushed the first fix ...

**Comment by ReinerBforartists** [comment]
Done.
