### ISSUE TITLE
3D View - Grease Pencil - Weight Paint mode - Sample Weight operator need iconography 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3702]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/95cd3400-5529-40a2-8135-32b6bc667d22)

I thought we did this one already, but it may be new. Will require documentation too.

**Comment by ReinerBforartists** [comment]
Manual needs update, but we have trouble in the chapters. Will make a task for it.

This task here is done.
