### ISSUE TITLE
3D View - Grease Pencil - Vertex Paint mode-  Default draw brush is green, should be black with white

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3708]
![bforartists_EqQoCBbBpY](https://github.com/Bforartists/Bforartists/assets/35357409/449a12f6-0b6b-45a9-bdac-c019059c39e6)

This confused me, but realized it wasn't my user startup but the default. This means saving the startup.blend with the right brush colour.

**Comment by Draise14** [comment]
I think this will mean a startup.blend scale down from a larger monitor if I commit this one, for you to do @ReinerBforartists? 

_I wonder if I have a bigger monitor lying around._

**Comment by ReinerBforartists** [comment]
It waits in the store :D

**Comment by ReinerBforartists** [comment]
I do think that green as a default color is fine. We start with a white canvas.

**Comment by Draise14** [comment]
Ah ok, so not an issue, but a feature.
