### ISSUE TITLE
Window - Split icons in the Window context menu are inversed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3710]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e4f1f6fe-8ca5-47ad-a817-0a5c6c768a04)

Horizontal is vertical, and vertical is horizontal in the icons.

**Comment by ReinerBforartists** [comment]
Ahaha, never noticed it :D

I think the best is to swap the icons in the iconset here, and to recreate the icons. And we need to update the two files in the file repository then too.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a9417c28-ed9c-4d55-8c3a-e80f54af3857)

Done. Will commit to master.

**Comment by Draise14** [comment]
Added a screen capture to the documentation. Commit to master.
