### ISSUE TITLE
3D View - Refine the Object Types Visibility Popup

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3716]
First, Blender has a new name for it. Selectability + Visibility.
Close the gap between Grease Pencil and Armature.
We have quite big gaps in general between the items which we can reduce.

![refine](https://github.com/Bforartists/Bforartists/assets/13919702/1a9810d4-9387-43ee-b7a7-18567472f85d)

**Comment by ReinerBforartists** [comment]
Hmm, or we make blocks of five, which makes navigation easier.

**Comment by Draise14** [comment]
4-7 blocks I would appreciate yeah.

**Comment by Draise14** [comment]
Funny story, they did this after seeing a comparison tweet I did on the Bforartists socials.

**Comment by ReinerBforartists** [comment]
Yes i know, i followed the story :)

And great to see that sometimes they do listen to what happens in Bforartists. That was the initial plan when i started the fork, to give examples of improvements. Better late than never :)

**Comment by Draise14** [comment]
![bforartists_uB3glLUajT](https://github.com/Bforartists/Bforartists/assets/35357409/14337281-7278-4717-b7e5-c551b1b732b2)

Looks like we got an extra column here to be fixed too.

**Comment by ReinerBforartists** [comment]
Updating the manual

**Comment by ReinerBforartists** [comment]
Fixed. Thee blocks

![selectability](https://github.com/Bforartists/Bforartists/assets/13919702/fab3d6f9-bb42-4f35-87af-a8d1409b5c96)
