### ISSUE TITLE
3D View - Sculpt Mode - Dyntopo missing Sample Detail button for hidden hotkey operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3717]
![bforartists_DDCYDdNwJg](https://github.com/Bforartists/Bforartists/assets/35357409/6a0c2250-0650-4ae6-9ab1-cd4ba1c64b3b)

This may be a regression from a long time ago, but we probably should add the SHIFT+D button (sample detail operator) to the Dyntopo panel. 

Old Task that made it cooler:
https://github.com/Bforartists/Bforartists/issues/357

Similar function in Remesh panel
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8efadf77-1161-44ab-a39b-a5a4f5298884)

**Comment by ReinerBforartists** [comment]
I'll grab this task from you. Needs a fix at the tooltip too.

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/9ad547ca-d686-47f7-8a61-6cc7cead22a0)

**Comment by ReinerBforartists** [comment]
Hmm, the whole design is a bit wonky. The resolution is called Resolution, Detail Size and Resolution Percentage, dependant of the mode. And i guess i could also have used the pipette icon, and put the button besides the slider. But anyways ...

Shall i keep this open for refinements?

**Comment by ReinerBforartists** [comment]
We should put the mode button at the top ...

**Comment by Draise14** [comment]
I have the task nearly done with documentation. 

You have stepped on toes here 😂😅

We did double work.

My work is the brush scale icon inline with the slider - en north showing when relevant. Like we have with other brush scale buttons. I vote for consistency. It also is more compact.

**Comment by Draise14** [comment]
![bforartists_lm5y1KCBH5](https://github.com/Bforartists/Bforartists/assets/35357409/1a537505-0ad1-47e9-9ba9-ba3b8123bc16)
![bforartists_pYoTDNTqdV](https://github.com/Bforartists/Bforartists/assets/35357409/bb539cd6-bcc3-431e-a29f-aa259df10f70)
![bforartists_sCTjFmhgxC](https://github.com/Bforartists/Bforartists/assets/35357409/9e862cc7-ab50-4052-a0e4-ee6ffc87091e)
![bforartists_KQR9lDpwfT](https://github.com/Bforartists/Bforartists/assets/35357409/a6a1399e-7478-45db-aa22-544005a3aee2)

Here is my solution.

**Comment by ReinerBforartists** [comment]
Sorry for double work ^^

As told, i would move the detailing mode top UI. And you show set detail size in all modes, which is afaik not correct.

**Comment by Draise14** [comment]
I tested the UX, you can set detail size in 3 modes other than the brush mode, the hotkey works in the other modes - so I exposed it accordingly. 

I guess I can move it up to top.

**Comment by ReinerBforartists** [comment]
Okay :)

**Comment by Draise14** [comment]
Will do cap'! 😁

**Comment by Draise14** [comment]
![bforartists_tAJltO0x8i](https://github.com/Bforartists/Bforartists/assets/35357409/a0eaf654-e10a-4274-ac06-7ba88f5fa41e)
![bforartists_JvVxFeUXcU](https://github.com/Bforartists/Bforartists/assets/35357409/bf4d22db-dcab-453f-a6fb-47501b48c485)
![bforartists_ejQGRT1iXR](https://github.com/Bforartists/Bforartists/assets/35357409/8e088b5c-1525-4548-b0b8-a785d6fdbfbb)

I stand corrected, the sample detail only works on constant and manual. not relative. So removed from relative - but added the set size with names and comments to top. Will update documentation.

**Comment by ReinerBforartists** [comment]
Hah, old man knew something :D

**Comment by ReinerBforartists** [comment]
Mh, wasn't the plan to put the detailing mode prop to the top?

**Comment by Draise14** [comment]
The Detail fill one? Sure, i can do that too. I misunderstood.

**Comment by ReinerBforartists** [comment]
It's the mode that decides what content is displayed. And this should imho be at the top, and the corresponding content below it ...

**Comment by ReinerBforartists** [comment]
![mode](https://github.com/Bforartists/Bforartists/assets/13919702/6bc3a2a6-c7f2-4671-ac2f-1b85730646f5)

**Comment by ReinerBforartists** [comment]
And of course, the set detail size button should be below the detail size prop. Maybe even in the way like in your design here: https://github.com/Bforartists/Bforartists/issues/3717#issuecomment-1731429103

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/366be476-6c55-4ef0-b615-e8f34ea196e5)

I think I understand now. Like this? Good to keep this in mind. Kinda good you're still around so I know every little nuance.

**Comment by ReinerBforartists** [comment]
Yeah, this works :)

**Comment by Draise14** [comment]
Documented.
