### ISSUE TITLE
3D View - Sculpt Mode - Remesh panel consitency and iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3718]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1da39be1-3706-4507-9703-1860fef750d9)

Another regression, we lost icons to the remesh and symmetry panels - but what probably kinda hits me the most is that the remesh panels in the Mesh data panel of the properties editor is inconsistent with the 3D View. You can't Quad Remesh from the remesh panels in the 3D View. This should be rectified. 

Regressions:
https://github.com/Bforartists/Bforartists/issues/357
https://github.com/Bforartists/Bforartists/issues/84

**Comment by ReinerBforartists** [comment]
Let's have a look here ...

**Comment by ReinerBforartists** [comment]
Hmm, Blender did remove two of the preserve options ...

![twotoomuch](https://github.com/Bforartists/Bforartists/assets/13919702/d2310a9c-d21f-4b8a-a0c8-d41d8512b761)

**Comment by ReinerBforartists** [comment]
Content is now equal. We don't have space for icons in the sidebar. And i think it would be too much visual noise in this area. It's only two options. So no big chance to miss it. And so no icons here.

Documenting.

![one](https://github.com/Bforartists/Bforartists/assets/13919702/41b081e0-4735-4dd0-80fe-2d786d534f2f)

![two](https://github.com/Bforartists/Bforartists/assets/13919702/05eafe97-8096-4bf8-8750-d6d75099953c)

**Comment by ReinerBforartists** [comment]
Fixed
