### ISSUE TITLE
Geometry Nodes - Remove Group Input and Output from Add tab in Node shelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3720]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fa595f3c-4dad-465a-8c74-7a4495a5a950)

They removed something redundant from the Add menu, double Group Input and Output nodes, now only under the Group category. We have those already in the Group panel in the Relations tab, so we should remove these too for consistency.

Don't forget documentation updates! 

<details>
<summary>Details</summary>

SHA-1: 550c15bccd5abde9396a102ea4b0a1644d58076d

* Geometry Nodes: Move tool-specific nodes to proper menus

Instead of putting all the tool specific nodes (inputs, operations, etc)
in a single menu, use the existing categories. This is similar to how
the shader editor shows nodes depending on which render engine
is enabled. It's also more scalable for when more tool-specific nodes
are added.

---

I discussed this with Pablo on Tuesday-- it came up when we talked
about the organization of the compositor add menu.

Pull Request: https://projects.blender.org/blender/blender/pulls/111449

</details>

**Comment by ReinerBforartists** [comment]
Already fixed with reordering the content.
