### ISSUE TITLE
Default Startup - Light Colors overlay should be turned on

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3722]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/23257ca2-4609-4c8f-a0cb-bfccd7051180)

Right now working with lights, you can see their colour on the yellow color coding - which I think is a nice UX. Should be on by default - not many may now this is an opt-in. And doing it for all viewports is a bit much for an artist to store all the time and turn on all the time - so let's bake it in.

**Comment by ReinerBforartists** [comment]
Let's see if i can catch all workspaces here ...

**Comment by ReinerBforartists** [comment]
Documenting ...

**Comment by ReinerBforartists** [comment]
Fixed
