### ISSUE TITLE
Windows Installer - Add version number to the shortcut

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3728]
Sometimes you are completely blind to the obvious things. Blender always shows the correct version number at the desktop shortcut when installed with the installer. We should have a look if we can manage it too with the next release. 

This is most probably a change for Blender 4.0.0 then.

![versionnumber](https://github.com/Bforartists/Bforartists/assets/13919702/0a741da6-5f5d-4df2-b9d5-e2d87bc6d711)

**Comment by Draise14** [comment]
Is this setup in the Inno setup? Or in the repository somewhere?

**Comment by ReinerBforartists** [comment]
This should be done in the inno setup

**Comment by Draise14** [comment]
Will try now

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2eaec23e-2711-485c-a409-9778595db53e)

Seems to have worked?

**Comment by Draise14** [comment]
Will upload to nextcloud to test.

**Comment by Draise14** [comment]
Could someone test? The official release? I hope it worked.
