### ISSUE TITLE
User Preferences - Auto-Offset toggle 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3730]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/780bb9fe-b9c5-4628-ae42-95a4da911300)

Float checkbox left and update documentation. This previously was in the node editor options but for some reason in Bforartists I can't find it in older versions.

> Move Auto-Offset toggle from Node Editor View menu
> into the Editing > Node Editor section of User Preferences,
> to reflect its use as a workflow option not configured
> per editor or per file

<details>
<summary>Details</summary>

SHA-1: 411cd827b736ae2c6aa390607f205917a442c64c

* Nodes: Move Auto-Offset toggle to User Preferences

Move Auto-Offset toggle from Node Editor View menu
into the Editing > Node Editor section of User Preferences,
to reflect its use as a workflow option not configured
per editor or per file.

Pull Request: https://projects.blender.org/blender/blender/pulls/111589

</details>

**Comment by ReinerBforartists** [comment]
Checking manual ...
