### ISSUE TITLE
Properties Editor - Add icons to Bone Groups panel buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3731]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/3e312a58-7896-4e93-baa5-49684878f8e7)

EDIT: panel is now Bone Collections. 

New buttons, need some iconography

These are similar or equal operators from the 3D View - Pose header operators. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6d75a194-7379-4b18-8b59-88b8348738f2)

Double check if documentation here is up to day.

**Comment by ReinerBforartists** [comment]
Shall we really add icons here? It's text buttons ...

**Comment by Draise14** [comment]
Yes please. We had it this way before a while back. They got lost. 

We iconize operators where possible. These are operators. Also... who likes reading? 😜 also consistency for the similar UX in other editors.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/7b3ef7e5-6576-442f-85a7-49436f478f7c)

Here is an example with Motion Paths, so.. best be consistent here.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5815672f-5f3b-4a20-a1cf-d97c740efada)

Now to documentation.

**Comment by Draise14** [comment]
Documented here. Commit to master. 
https://github.com/Bforartists/Manual/commit/f6cc80c7ede1921355399da9965f2acd078fc394
