### ISSUE TITLE
Node Editors - Group Tab - Interface panel - Add add buttons and/or column labels for column read and top access

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3733]
![bforartists_VM4TzAnq0T](https://github.com/Bforartists/Bforartists/assets/35357409/60bce207-6b90-43d8-85a3-cfda2fe5f1b7)

With the new interface panel for group nodes, you can now add sub-panels, input and output sockets into the same list.  BUT.... it is not obvious to see nor know what is an output socket or input socket at first glance. Users in Erindales discord sever (heavy node users) reported they weren't happy with that - hard to know/see. 

Solution:
1. Add column labels: left is input, right is output. 

OR

2. Add buttons for adding input, output and panel (middle) to also double as a top access and label. 
![bforartists_jv8U26hCxZ](https://github.com/Bforartists/Bforartists/assets/35357409/3ac0e172-74a6-4c34-923d-7bc4c740b81d)

Here we expose the add buttons to a top level (no digging)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a79c1dfe-e15a-4156-a183-fc75ae9e3025)

<details>
<summary>Details</summary>

SHA-1: e071288ab2901f43a5cde82a49c02101cd579aad

* Nodes: Panels integration with blend files and UI

Part 3/3 of #109135, #110272

Switch to new node group interfaces and deprecate old DNA and API.
This completes support for panels in node drawing and in node group
interface declarations in particular.

The new node group interface DNA and RNA code has been added in parts
1 and 2 (#110885, #110952) but has not be enabled yet. This commit
completes the integration by
* enabling the new RNA API
* using the new API in UI
* read/write new interfaces from blend files
* add versioning for backward compatibility
* add forward-compatible writing code to reconstruct old interfaces

All places accessing node group interface declarations should now be
using the new API. A runtime cache has been added that allows simple
linear access to socket inputs and outputs even when a panel hierarchy
is used.

Old DNA has been deprecated and should only be accessed for versioning
(inputs/outputs renamed to inputs_legacy/outputs_legacy to catch
errors). Versioning code ensures both backward and forward
compatibility of existing files.

The API for old interfaces is removed. The new API is very similar but
is defined on the `ntree.interface` instead of the `ntree` directly.
Breaking change notifications and detailed instructions for migrating
will be added.

A python test has been added for the node group API functions. This
includes new functionality such as creating panels and moving items
between different levels.

This patch does not yet contain panel representations in the modifier
UI. This has been tested in a separate branch and will be added with a
later PR (#108565).

Pull Request: https://projects.blender.org/blender/blender/pulls/111348

</details>

**Comment by Blenux** [comment]
How about this layout?

![Screenshot_20231008_110734](https://github.com/Bforartists/Bforartists/assets/25260650/f1e5d3a8-b3f0-4efd-af20-2cb2c2f268d1)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5417415c-b639-462a-a48a-d98c5d3acb66)

Has bug.

**Comment by Draise14** [comment]
Found it, missing line from Blender in node.py

**Comment by Draise14** [comment]
Wondering if a little add label will help the user know what the buttons do. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/dd839efc-eb4a-43eb-a7a5-8abd7a83dcb2)

Alternative that lines up with the column of the list a bit.
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0c9da5f1-283f-4da9-a959-4c352febd9b6)
