### ISSUE TITLE
Sequencer - New Audio Modifier "Equalizer"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3734]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/86e2971d-b77d-4cf9-b22e-12877ea8e525)

New modifier can be added to audio strips now, an equalizer. Needs iconography and documentation.

<details>
<summary>Details</summary>

SHA-1: 1015bed2fd89c5a8f741c5f1dd22099a9441bea0

* VSE: Sound equalizer modifier

The sound equalizer is using the Audaspace FFT Convolver.
The blender part creates an array of descriptions of power per "band"
and orders the creation of Equalizer (ISound) in the Audaspace.

Modifier can be created on sound strips. It lets you define
amplification or attenuation over frequency range from 30Hz to 20 kHz.
The power is limited to -30 db - 30 db. This is done using curve
mapping widget.

Co-authored-by: menda <alguien@aqui.es>
Co-authored-by: Richard Antalik <richardantalik@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/105613

</details>

**Comment by ReinerBforartists** [comment]
Fixed

![document](https://github.com/Bforartists/Bforartists/assets/13919702/c1c713af-ef00-4b60-b354-cf268fc15798)

**Comment by ReinerBforartists** [comment]
Whoopsie, first push, then close ...
