### ISSUE TITLE
Compositor - Add menu re-organized and needs sub-panels

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3735]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ce2a2fa6-5fca-486a-a38e-61f701cac9e3)

They coming for all the add menus! Now with more sub-panels. The add shelf should update to make sure.. it's still easy to fin nodes. I like the consistency, but wow.. still a lot of digging. I am SO happy we have the node add shelf. 

Documentation will need to be updated too.

**Comment by ReinerBforartists** [comment]
Ah, this game again. Three hierarchies deep is two too much for my flavour -.-

**Comment by Draise14** [comment]
I agree here.... You aren't the only one unhappy about this, they "mitigated" this by adding the abiliity to search directly when menu is open - and we mitigate by exposing to a top level... but even then.

Just you wait till you see the new modifier stack add sub-menus................

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f824904c-2e2a-49ca-8c23-d1b9f0826858)

Started. Question, can these new panels prepend?

**Comment by ReinerBforartists** [comment]
I am not sure. But should be possible.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/29cdb2ba-a211-4fd0-afc6-9f2bd0b7fab3)

I can't figure it out at the moment, so will focus on first updating the panels. In Geometry nodes we haven't got the correct order, sub-panels are appended at the end - so will stick to that till I find a way later - then will update later in another task.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fd44f412-0891-4103-89bb-f1f8a39be53a)
This one is done. Next

**Comment by ReinerBforartists** [comment]
Ah this is what you mean. Subpanels always appends to the rest of the content. There is no way to put the buttons underneath the subpanels, sorry.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/51a5b99d-35d6-4ec2-b2c9-74d6f37d5dc5)

Progress, this is.. a big slow task.

**Comment by Draise14** [comment]
https://github.com/Bforartists/Bforartists/assets/35357409/9556f6bb-c159-41d6-b4ab-9bc13f0632b7

Got it. Now.. the documentation. Probably large task too.

**Comment by ReinerBforartists** [comment]
The bigger part. New chapters ...

**Comment by Draise14** [comment]
I've started working documentation. But I have a meeting and family for the rest of the weekend. I'll continue on Monday early morning and get it out of the way.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/7b15abd3-3aa1-429b-b867-80a1735359c4)

Back at it.

**Comment by Draise14** [comment]
Sweet, will pull now. DONE.
