### ISSUE TITLE
Fcurve Editor - Key - Key Slide Operators - New "Shear" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3737]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/284528ed-cd39-4504-a2e6-6627a0ebd69e)

Currently missing in Bforartists. Should be added, with an icon and documented. 

_I'm starting to wish we had an operator panel for these operators in the nodeshelf now..... they are useful but 2 sub-menus deep._ 

<details>
<summary>Details</summary>

SHA-1: 9d0aed6589aae514cf0a46b9f3202b629d524e37

* Animation: Shear operator for Graph Editor

This is a combination of two PRs from Ares Deveaux: #106521 and #106522

This adds a new operator that allows shearing keys
based on the position of the segment ends.
By pressing `D` while the operator is in modal you can
switch if the operator takes the left or the right segment end as a reference.

Co-authored-by: Ares Deveaux <aresdevo@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/111735

</details>

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Fixed.

I would suggest to make a task in case you want them to be in the header. But the header is already pretty crowded ...

**Comment by ReinerBforartists** [comment]
![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/190f4ec4-76a8-40fa-a8bb-a49d29565acc)

**Comment by ReinerBforartists** [comment]
Hm, a pie menu maybe?
