### ISSUE TITLE
3D View - Weight Paint - Add invert and smooth keymap operators like in the Sculpt Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3739]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5cd34049-9fbc-4a14-957b-bdfdbc45b49b)

This feature slipped through, didn't realize it was possible in weight paint mode, but now you can invert and smooth like in sculpt mode - but in weight paint mode. We probably should add that too, intuitive and consistent.

**Comment by Draise14** [comment]
Commit to master, documenting.

**Comment by ReinerBforartists** [comment]
Is this a hotkey only operator?

**Comment by Draise14** [comment]
The tools exist in the Toolshelf (smooth) and header (weight 0.000). I had another task open to try expose inverse in the GUI instead of a slider. But that's another experimental task.
