### ISSUE TITLE
3D View - Grease Pencil - Weight Paint mode - Hidden Swap weight operator needs to be exposed to GUI like in other modes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3747]
![236639008-00aae73b-3b45-42db-9f23-dfb878e5e021](https://github.com/Bforartists/Bforartists/assets/35357409/1a466b40-2738-43e4-88f1-17a54769897e)

In Blender hotkeys, we have `D` to swap plus and minus. This could be a "swap" button in the header by the plus and minus button with a swap icon. _Typically you'd hold down` CTRL+LMB` to inverse paint, but here it swaps... yay for Blender consistency._ 

New header button location here:
![236639025-f71ec0db-2a3b-4619-809d-508fd5d01021](https://github.com/Bforartists/Bforartists/assets/35357409/49b881ff-7ace-4d51-8d63-3d9fe1772bc0)

Reference Task:
https://github.com/Bforartists/Bforartists/issues/3520

**Comment by ReinerBforartists** [comment]
Also here, be careful. This "new" location comes from the order of the tools in the sidebar.

**Comment by Draise14** [comment]
Ah, so should be also added to sidebar?

**Comment by ReinerBforartists** [comment]
Yes. Then it automatically appears in the header too.

**Comment by ReinerBforartists** [comment]
For swapping, you weightpaint towards the target value anyways. So what is this swap good for?

**Comment by ReinerBforartists** [comment]
Ah, now i understand what you want to do here. We don't have this hotkey. And so it is also not hidden. Which makes the task invalid. I will close it.

Maybe we could add the hotkey, and give a hint towards it in the tooltips for the direction buttons. But this would steal a free hotkey from the users. 

As a reminder, we are not Blender, and we should not mimic the Blender keymap. Our goal is to have _**as few default hotkeys as possible**_. Not as much Blender hotkeys as possible. It's one of the things where we differ. To have a good working graphical UI instead a hotkey chaos.

Either way, a swap button makes definitely no sense. Since the original elements that you want to swap are already in place. It would be exactly the same click that you need to click at the plus or minus button. And the hotkey is something for high end power users. Not for the average user.

**Comment by Draise14** [comment]
Consistency and discoverability is also the Bforartists way. We have the swap swatches button in some modes. We should make it consistent in all modes for consistency and expose hidden operators even if there are no hotkeys. This also justifies not needing to add a hotkey for hidden features a user would thus never discover.

We should at least expose it like in the other painting modes that do have it.

**Comment by Draise14** [comment]
Texture and Vertex paint modes has it, but I can see the consistency with color selection and is an expected color painting UX. No removal. 
![bforartists_nlvfIDQJRd](https://github.com/Bforartists/Bforartists/assets/35357409/5d246466-ce86-4a55-8683-f42904777989)
![bforartists_CiVL7dBY08](https://github.com/Bforartists/Bforartists/assets/35357409/838f4c26-283d-42e4-8c43-c4ba63c2d067)
![bforartists_8Hwh3AVyoY](https://github.com/Bforartists/Bforartists/assets/35357409/3bcafefc-f0ab-4778-8a6a-f3f9a5263dc4)
![bforartists_iXVptiHhJS](https://github.com/Bforartists/Bforartists/assets/35357409/eceef5c4-4a72-48af-92f3-f75f62e10ca4)

Grease Pencil and Weight paint are not consitent right now - not with each other nor anyone else. 
![bforartists_k7iwRLBcN5](https://github.com/Bforartists/Bforartists/assets/35357409/5ff910d7-798c-47a0-9825-c2e6b9e1e1b0)
![bforartists_v69sQI1Z6n](https://github.com/Bforartists/Bforartists/assets/35357409/cad5fe0a-ce20-41ae-8ad9-1401e26af76a)

I guess we COULD make it consistent to also add plus/minus to the weight paint mode with this task: https://github.com/Bforartists/Bforartists/issues/3742

Then close here... Fair enough. Sorry bout the debate... I though exposing hidden operators was part of the guidelines for Bforartists, so was wondering where.

**Comment by ReinerBforartists** [comment]
I feared it :D

Okay, i wasn't good enough in explaining, sorry.

No, this is not the same use case, but a completely different one. What you show here is to swap the primary and secondary color. You can't swap these colors with the color fields. And so you need a button to swap the colors.

In our case though we already have a button to switch between add and subtract. It is this one:

![alreadyit](https://github.com/Bforartists/Bforartists/assets/13919702/1ecefe84-7897-4793-844d-98ef12b8b333)

And what you want to do now is to add yet another button that does the very same, and even want to put it directly besides. Just with another look. And this is bad UX design. When you are unhappy how the existing button works, then you better change the existing button. We could make it a toggle for example. But i see the current design not as a bad one. Yes you have to aim and decide, but you immediately see in which state you are. Which is not clear with a toggle. Is highlighted now add or subtract?

And the hotkey is another chapter then. As told, we theoretically could add the hotkey, and put a hint into the tooltip of the button that the hotkey exists. But Bforartists stands for a reduced hotkeymap. Not an excessively blenderized keymap. 

I know it's hard sometimes. But the goals of Bforartists keymap is to let the user decide the hotkeys that he needs for his workflow. And unfortunately Blender, and so also Bforartists, doesn't allow to add a hotkey to the prop by UI. But i simply don't know how we could add a RMB entry here.

> Sorry bout the debate

It's the opposite. I have to apologize that my first answer wasn't clear enough. For me it was too obvious and basic, i didn't thought that it needs closer explanation. It is in fact important to discuss such things. And for me it's important that you understand the reasoning behind my decisions in case i decide different from you. I am not around forever. So when something is unclear, then ask. You know that i am very open to discussions. And i can also easily be convinced by facts. But this is one of the rare cases where i have to veto. And i hope you have understood better now why i do :)

**Comment by Draise14** [comment]
All good. This task was never about adding a hotkey but exposing a hidden operator. But yes, it would be better for the add or subtract for weight painting and should be consistent there both in GP and Object weight paint modes. 

_Blender adding more methods instead of consistent methods..... sigh_

**Comment by ReinerBforartists** [comment]
Yeah but this "hidden" operator is meant for the existing button :)

**Comment by Draise14** [comment]
Makes sense now. Will add the plus minus to the object weight paint mode for a similar consistent UX.

**Comment by ReinerBforartists** [comment]
Mh, maybe better report this to Blender instead. What they fix ...
