### ISSUE TITLE
3D View - Weight Paint mode - CTRL+LMB select is hidden from GUI, expose for discoverability

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3749]
![bforartists_NPdShDBFmz](https://github.com/Bforartists/Bforartists/assets/35357409/4ac3a194-004e-4ccd-8f1b-fdcec0fdd414)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0cb95857-10c5-494b-afc9-2fed1606733d)

Add Select Bones to header, could be in the Weight sub header menu or in a new select header menu. This is mainly for discoverability since this is a hotkey only operator as `CTRL+LMB`. 

Don't forget to also add this in the grease pencil weight mode too.

**Comment by ReinerBforartists** [comment]
We might want to update our important hotkeys addon here too. It shows the wrong keybinding. And has other shortcomings too.

![importanthotkeys](https://github.com/Bforartists/Bforartists/assets/13919702/9320682a-66a2-4925-84d0-58e51266830b)

**Comment by ReinerBforartists** [comment]
Related: Fix and update the Important Hotkeys addon #3757

**Comment by ReinerBforartists** [comment]
What about the footer?

![footer](https://github.com/Bforartists/Bforartists/assets/13919702/a1ca1d83-3f88-4582-a443-d19113bd3be1)

**Comment by Draise14** [comment]
Hmm.. It doesn't really show in the footer other than "Select". We have LMB as select also -, so it doesn't show the 3D View Select, or "inter-mode select" aspect of the special case.
