### ISSUE TITLE
3D View - Weight Paint - Headers - Make slider order consistent between object and greasepencil headers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3751]
The weight paint modes header sliders are.. NOT consistent. Come on! 

**Object**
![bforartists_D2WHbJQIL2](https://github.com/Bforartists/Bforartists/assets/35357409/4c120a53-b1ac-4bf1-8b63-752c5bf31b23)

**Grease Pencil**
![bforartists_9nq82h4CWv](https://github.com/Bforartists/Bforartists/assets/35357409/18872760-d2b4-4e3b-a627-0be3c53259d7)

**Comment by ReinerBforartists** [comment]
Be careful here, the order here is the order of the panels in the tools tab in the sidebar.

**Comment by Draise14** [comment]
Ah ok, yeah good point. A bit bigger this task.

**Comment by ReinerBforartists** [comment]
Looks like one little change.

**Comment by ReinerBforartists** [comment]
Ah, now i see what you mean :D

Sheesh the brush engine ...

**Comment by ReinerBforartists** [comment]
Mh, Weightpainting for objects does not have add or subtract. Crazy UX anyways. I have no idea what this is good for. You paint towards the weight value anyways. No matter if positive or negative.

@Draise, do you have an idea here what the add or subtract direction is good for?

![wp](https://github.com/Bforartists/Bforartists/assets/13919702/69dea2b4-37c4-4e54-add4-8194ad292306)

**Comment by ReinerBforartists** [comment]
I would have loved to put the weight value behind radius and strength. But the brush engine didn't let me. So it is now in front of the two props like for weight painting a mesh.

Documenting.

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
Ah, wait, the right click menu is missing.

It does not have the add / subtract buttons though.

**Comment by ReinerBforartists** [comment]
That's better.

I have kept the +- button small here for purpose. To have them across the whole length looked like massive visual noise, and just cried for wrong clicks when you want to change a slider ...

![direction](https://github.com/Bforartists/Bforartists/assets/13919702/29dc4dc9-4bd6-44ea-bbbe-cac94b37d43b)

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Fixed
