### ISSUE TITLE
3D View - Hair Curves Object - Object - Convert - "to Particles" needs iconography and potentially documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3753]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b91366a9-2b08-46f9-9410-823c7345c96a)

An operator needs an icon. When you select a Curves object, the convert menu has a new operator to convert to particles. It has no icon and may have no documentation.

**Comment by ReinerBforartists** [comment]
Fixed and manual updated
