### ISSUE TITLE
3D View - Hair Curves - Set Parent to "Object (Attach Curves to Surface)" is missing from header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3754]
![bforartists_tTB9YQ87rJ](https://github.com/Bforartists/Bforartists/assets/35357409/c80d03c9-c16e-4703-b3f2-be607222b364)

When you have a Hair Curves object (fur) selected, and want to parent it to surface, you can CTRL+P to call the menu then attach to surface, but this is not possible from the header. This would be a hidden operator. It also has no icon and may need documentation. 

![bforartists_Kc2EQ1EQDm](https://github.com/Bforartists/Bforartists/assets/35357409/4db91110-b1f7-4f58-b9ed-a7e959d83eac)

**Comment by ReinerBforartists** [comment]
Good catch!

**Comment by ReinerBforartists** [comment]
Haha, funny, no python yet :D

![nopython](https://github.com/Bforartists/Bforartists/assets/13919702/56c66100-8270-4c3d-9060-b613faa5387c)

**Comment by ReinerBforartists** [comment]
Ah wait it's a C menu, but has a python term for it. Investigating ...

**Comment by ReinerBforartists** [comment]
No python. The whole parent sub menu is a enum. Now let's hunt this enum ...

` layout.operator_enum("object.parent_set", "type")`

**Comment by ReinerBforartists** [comment]
Hmm, in the popup it is a menu item. This menu item doesn't work in the enum. And i am in big trouble here to get it to work.

Maybe we can at least append it with python

![uiitemtoenum](https://github.com/Bforartists/Bforartists/assets/13919702/902ba3ca-5eb9-4508-86aa-54e209102816)

**Comment by ReinerBforartists** [comment]
Did it the python way. Fixed in master. And reused the PARENT_CURVE icon here.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/3b676089-1291-426e-9ead-8cb8b93060fa)
![fixed2](https://github.com/Bforartists/Bforartists/assets/13919702/27c944ee-baa4-427f-8cc2-5c1bcf312db1)

**Comment by ReinerBforartists** [comment]
Documenting ...

**Comment by ReinerBforartists** [comment]
Done
