### ISSUE TITLE
Archimesh built-in addon mostly not working

### ISSUE THREAD

**Issue by antonmeleshkevich** [Bforartists/Bforartists#3756]
Half of the objects that Archimesh addon creates aren't created. For example "Door" object. When clicking, here is what happens:

![bforartists_5g2uayzmN9](https://github.com/Bforartists/Bforartists/assets/34407001/7bfad86a-171e-4158-b8bd-9baf093edd11)

Windows 11. NVidia RTX 4070. Bforartists 3.6.2

`Python: Traceback (most recent call last):
  File "C:\Program Files\Bforartists 3\3.6.2\4.0\scripts\addons\archimesh\achm_door_maker.py", line 42, in execute
    create_object(self, context)
  File "C:\Program Files\Bforartists 3\3.6.2\4.0\scripts\addons\archimesh\achm_door_maker.py", line 68, in create_object
    shape_mesh(mainobject, mainmesh)
  File "C:\Program Files\Bforartists 3\3.6.2\4.0\scripts\addons\archimesh\achm_door_maker.py", line 150, in shape_mesh
    create_doorframe(mp, tmp_mesh)
  File "C:\Program Files\Bforartists 3\3.6.2\4.0\scripts\addons\archimesh\achm_door_maker.py", line 504, in create_doorframe
    mymesh.from_pydata(verts, [], faces)
  File "C:\Program Files\Bforartists 3\3.6.2\4.0\scripts\modules\bpy_types.py", line 627, in from_pydata
    self.polygons.foreach_set("vertices", vertex_indices)
TypeError: foreach_get(attr, sequence) sequence length mismatch given 95, needed 96
`

And thanks a ton for all the work! Just discovered the project and seems like it can really help me to learn Blender and 3DCG overall.

**Comment by Draise14** [comment]
Glad you are liking it! Looks like the issue maybe a Blender 4.0.0 API change. Could you kindly test the same addon with Blender 4.0.0 alpha? Latest release? 

We have to cover our bases and make sure the addon is fine in Blender.

**Comment by antonmeleshkevich** [comment]
You're right. The same error in Blender 4.0. But it works in Blender 3.6.2 if it helps in any way.

**Comment by Draise14** [comment]
Ah ok. Bforartists is a version ahead of the Blender version back end. Official releases usually contain 1 month of code ahead of the Blender version since we can only develop from the main branch. If this is the case jump back a version and it may work. BFA 3.6.1 or 3.6.0 or even 3.5.1.

**Comment by ReinerBforartists** [comment]
As a note, the last Bforartists version that relied at Blender 3.6.x code was Bforartists 3.5.1. So that's where Archimesh should work flawless.

As Draise said, there is unfortunately nothing that we can do. So let's close the issue.

It will become better once Blender 4 is out and the addons out there gots updated. But that's still a few months away.
