### ISSUE TITLE
Asset Browser - Drop collections/instances at world origin toggle is buggy

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3761]
https://cdn.discordapp.com/attachments/459746732209864714/1150857310000910519/bforartists_wYoSNvTTUy.mp4

> When the instance toggle is off, you still get the collection as instance (instead of add to scene as linked collections)
[8:16 PM]
And the center also dissappears in instance mode.
[8:17 PM]
So append/link as instance toggle is still currently broken.

**Goal:**
- When Drop Collection as Instance is OFF = show Origin to World Center
- When Origin to World Center is ON = link collection to world center, but only if both Instance is OFF and World Center is ON. When Instance is ON, World Center should be OFF automatically. 
- When Origin to World Center is OFF = the collection should revert to normal behaviour with placement at mouse origin (this is the bug, it doesn't)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/9c62f1e0-d832-4154-9e3f-5646520f8302)

Right now the method to inset to world origin doesn't "reset" when off, so for some reason the repeat last operator remembers the new set values, so can't toggle off.

**Comment by Draise14** [comment]
Going to hide the entry for this prop for the release, then postpone. Don't want intentional broken UX in till this is ready.
