### ISSUE TITLE
Texture Node Editor - Add icons to Add header menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3763]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c573f850-a1de-4499-bb27-4cfeb6bb7e4e)

Looks like they are starting to add back love to the Texture nodes editor. We should probably do the same... Though it is going to be "rewritten"

Add nodes to the Add header menu.

<details>
<summary>Details</summary>

SHA-1: 5fac8f822b9357554a999f6370ecad81acd79314

* Texture Nodes: Refactor Add menu

Refactor the Add menu in Texture Nodes, with manually created menus,
inspired by Geometry Nodes and more recently Shader and Compositor.

Minor sorting adjustments by splitting categories in groups, with
separators in between groups, and sorted alphabetically.

Unlike other node editors, this menu will not feature assets for the time
being. Doing so would add (more) burden of maintenance to a system
that is deemed end-of-life, and likely to be rewritten before long.

Part of #111746

Pull Request: https://projects.blender.org/blender/blender/pulls/111838

</details>

**Comment by ReinerBforartists** [comment]
Texture node editor hasn't seen any updates since years and we haven't documented it neither. So i would say, simply close.

**Comment by ReinerBforartists** [comment]
Closing. We don't develop nor document the texture editor.
