### ISSUE TITLE
Geometry Nodes - Add - Mesh - Read - new "Is Edge Smooth" node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3766]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ffef4229-814f-456d-a071-17f205e8fcf0)

New node, new iconography, to add shelf and documentation. 

<details>
<summary>Details</summary>

SHA-1: 4e97def8a32147b245759f04ceceeefd937b43f5

* Geometry Nodes: Expose sharp edge status with builtin nodes

Change the existing "Is Shade Smooth" node to be named "Is Face Smooth"
and add a new "Is Edge Smooth" node. Also give the "Set Shade Smooth"
node the ability to set face or edge smoothness.

The fact that the nodes process "smooth" data reversed from the builtin
"sharp" attributes can be reversed with versioning in a separate commit.

While it's tempting to abstract the sharpness status into a single node,
face and edge smoothness are accessed separately in edit mode, and the
subtlety of interacting with data on different domains would make that
confusing. Instead, a separate "Is Shade Smooth" node group asset will
give all the sharp elements taking into account both builtin attributes.

The fact that sharpness is stored separately on two domains makes the
best design for simple operations non-obvious. For example, you should be
able to remove all sharpness or make everything flat with a single node.
The behavior depends on whether the two attributes exist and the
combination of values between the domains.

---

![image](/attachments/c3f053c4-2b0f-44ac-9227-62071065fe56)

![image](/attachments/fd489fb3-314b-42ff-a5a9-e79578cbdfe7)

Pull Request: https://projects.blender.org/blender/blender/pulls/112029

</details>

**Comment by ReinerBforartists** [comment]
This sounds for two new icons then. One for face smooth and one for edge smooth. And we better prepare for vertice smooth too ...

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Done
