### ISSUE TITLE
Properties Editor - Modifiers - "Move to nodes" needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3767]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6307448a-25f2-40eb-9b0c-5b4a05a4bcc2)

The Move to Nodes operator in the drop down of the modifier stack needs documentation and an icon. 

_That theme issue.. it's killing me.._

**Comment by ReinerBforartists** [comment]
Fixed. Documenting.

![movetonodes](https://github.com/Bforartists/Bforartists/assets/13919702/67f47210-6142-49a9-852e-800c882b1f57)

**Comment by ReinerBforartists** [comment]
Done.
