### ISSUE TITLE
Properties Editor - Modifiers - Save as Shape Key needs new icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3768]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0ce99911-a9c8-470e-a752-11c9c180ba1c)

They split these icons up, so we should add a new one here. You only see these on modifiers under the "Deform" category. 

<details>
<summary>Details</summary>

SHA-1: 24fe81e602a83d9395f9152e5b0c137ee989161d

* UI: Do not repeat icon in modifier options menu

"Apply as Shape Key" and "Save as Shape Key" shared the same icon, it
is good practice to not use the same icon for two consecutive items
in the same group in a menu.

Also add a separator to split Shape Key-related items from the rest.

</details>

**Comment by ReinerBforartists** [comment]
Sheesh, still the same tooltip too. So no way to find out what the difference really is. I'll make it a new task.

![sametooltip](https://github.com/Bforartists/Bforartists/assets/13919702/b5a2f440-b1b9-4626-bbe0-2ae4bb6021a3)

**Comment by ReinerBforartists** [comment]
For the icon, i think it is valid to use the same one. Apply and Save is close to the same, functionalitywise.

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/6395cf93-e4e9-4bae-a31e-b7917cba4619)

**Comment by ReinerBforartists** [comment]
Done. This was by the way a regression. The manual chapter showed the save as shape key menu item already. And this since a pretty while.
