### ISSUE TITLE
Fcurve Editor - Key - Submenu parity with Blender for better organization and maintenance

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3771]
Right now the maintenance of this menu is getting a little bit slippery, now that multiple merges haven't bleed new features in. And it's also getting a bit bloated and disorganized in Bforartists - with a large Slider sub-menu in the middle of others - with a large wall to scan. In this case the sub-menus from Blender (with parity) may make this easier to maintain and also dig into. 

Blender
![image](https://github.com/Bforartists/Bforartists/assets/35357409/23df0044-ee6c-476b-9c4f-d26cf98cff4c)

Bforartists
![bforartists_bLzXirh4P6](https://github.com/Bforartists/Bforartists/assets/35357409/54fb3f4c-4ad5-436b-96e7-1c5f7abef5d6)

To remedy the digging, we can create flow add panel with icons/shelf into the sidebar a bit like the node add shelf for top level access.

**Comment by ReinerBforartists** [comment]
Isn't this the nearly same issue? Fcurve Editor - Add a tab with panels to run fcurve operators from a top level #3772

**Comment by Draise14** [comment]
Smooth keys, blend keys. I think it implied as "X keyframes" ei, the selection. 

This is a separate issue from #3772, though if we move to header then it would be the same. If it were a toolshelf in the sidebar it would  be a user choice and a double entry per toolshelf standards. If it were only organized to header, pull it up one level, then it would be a single entry and moved from here and yes... Be the same task.

**Comment by ReinerBforartists** [comment]
We can either have it like in Blender, or expose the operators to the header. Both is not possible. And looking at how crowded these sub menus has become i would say let's fix this issue here instead. And close the other issue.

**Comment by ReinerBforartists** [comment]
Documenting

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/41f20341-b981-4138-bbe9-8be15d065c52)

**Comment by ReinerBforartists** [comment]
Ah, a double

![double](https://github.com/Bforartists/Bforartists/assets/13919702/8dfdc288-7e32-4701-b40e-04a565248264)

**Comment by ReinerBforartists** [comment]
Fixed
