### ISSUE TITLE
Fcurve Editor - Add a dropdown to run fcurve operators from a higher level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3772]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1f42a10d-5149-45e9-8a09-f4cadfefe8bf)

To remedy the digging for now the numerous yet useful Fcurve operators, we can create flow add panel with icons/shelf into the Fcurve sidebar a bit like the node add shelf for top level access similar to the workflow of the Node Add Shelf of the node editors. 

Like this - but to run the operators. 
![bforartists_yx7ehdqN0x](https://github.com/Bforartists/Bforartists/assets/35357409/f7a287c8-8ef2-43ff-98e9-8bde84202656)
![bforartists_VF4gOs6lvz](https://github.com/Bforartists/Bforartists/assets/35357409/9027d672-cab2-4eaa-87ce-65df4f0bb2bc)

**Comment by ReinerBforartists** [comment]
Wouldn't be a header location the better way? I know it's already a bit crowded over there, but in the sidebar you might tab around ...

![headerlocation](https://github.com/Bforartists/Bforartists/assets/13919702/0f146bb7-0d94-468b-8152-50f7135ada40)

**Comment by Draise14** [comment]
Header may be more consistent, but still a step deeper than top level that could be pinned for serious animators. 

I guess we can add them to header... I do use the drop downs a lot. 

_I love the toolshelf Incase you didn't notice 😂_

**Comment by ReinerBforartists** [comment]
We unfortunately can't pin everything with over 2000 operators ^^

**Comment by ReinerBforartists** [comment]
Closing in favour of task Fcurve Editor - Key - Submenu parity with Blender for better organization and maintenance #3771
