### ISSUE TITLE
3D View - Modifiers add shelf in the tooshelf or sidebar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3773]
![PowerToys_5f1XPyh51z](https://github.com/Bforartists/Bforartists/assets/35357409/f9da2284-a3c5-4d5d-9cb0-8c87fda24671)

Right now the modifiers are now.... in a 3 level deep sub-menu. This is not the Bforartists way. This used to be a 2 level deep method to add them, but now it's.. not. 

A friend had a good idea and that was to have a similar Modifiers Add panels and tab in the 3D View - similar to how we have the Node Add shelves with buttons. I thought this is a good idea since this allows 3D Modifiers directly onto objects with a single click and it would be consistenty with other workflows we have in the Node Editors. 

In this case, we can have a tab to quickly mouse over and add a modifier directly from the 3D Viewpor in their respective panels.  

![bforartists_yx7ehdqN0x](https://github.com/Bforartists/Bforartists/assets/35357409/3b0e3c36-84f6-44a3-8b01-c15038d9939c)
![bforartists_VF4gOs6lvz](https://github.com/Bforartists/Bforartists/assets/35357409/117f11bb-eaa9-411b-95f8-dc57eb98cee5)

**Alternatives:**
- This could be in the toolshelf instead of the property shelf. 

**Drawbacks:**
- We probably cannot list the asset library node groups, but the asset shelf should technically allow that. 
- We would still have no way to change the stack order or edit the modifiers, but the addons like Modifier List allows this directly in the sidebar, so not a biggie.

**Comment by ReinerBforartists** [comment]
When there would be a way to separate the node groups from the single nodes, then i would vote to add a second add menu in the header.

**Comment by Draise14** [comment]
I'm talking of a higher acces to the Edit, Generate Deform, and Physics built-in modifiers either from viewport or... 

Your idea of pull up these by one level directly to properties panel modifiers header... Hmm or a new modifiers add menu.Ill make some mockups today. 

The fixed modifiers could be a top level in 4 panels in the toolself or sidebar alternatively/too as per the idea above. Mockup wasn't clear though.

_For the record, geometry nodes operators in their own nested menu in header is being developed in Blender.._

**Comment by ReinerBforartists** [comment]
LOL, now i realize what they did here. Are they kidding us? :D

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ab20905b-3fbf-4c63-88c6-ff5719e27974)

Here is an idea.. move the 4 sub-panel up to their own buttons on a top level. So you don't get a wall of built in modifiers, and you also don't have to dig so deep to get to them. We could have also some iconography for the groups or 2 column 2 row buttons with text and similar add icon. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/6bbbf737-966b-4ebb-bec3-37b0503643e2)

Or... two buttons, one for geomtry nodes modifiers, then the built in modifiers.

**Comment by Draise14** [comment]
Addons have popped up for solutions, so yes, this is a public need to make it a level up somehow (or top level opt in). But I will postpone the prototyping for 4.1.

**Comment by Draise14** [comment]
A developer (and splashscreen winner) has made an addon that solves this, and they are happy to include it in the repo is we want, so will close this and open another.
