### ISSUE TITLE
Rework Hair Modifiers panels to align props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3774]
The hair modifiers were not progressed by us so far. They all have the middle aligned Blender design. Needs a fix. 

But i'll wait a few cycles first, they are for sure not done with making it worse.

![hairmodifiers](https://github.com/Bforartists/Bforartists/assets/13919702/736e8cfa-0d05-44ac-81d9-641a3f8b9f40)

**Comment by Draise14** [comment]
We could not tackle this since this was fusioned code of dynamic labeling of Geometry Node groups. These are node groups...

**Comment by ReinerBforartists** [comment]
:/

**Comment by Draise14** [comment]
Yeah, we tried hard to figure this out - but it's a dynamic user build prop done inside a weird nested way of building the custom panels - here were our experiments. 
https://github.com/Bforartists/Bforartists/issues/3435

**Comment by ReinerBforartists** [comment]
*sad cat noise* :(

**Comment by ReinerBforartists** [comment]
Wow, when even Grep is lost ...

**Comment by ReinerBforartists** [comment]
Giving up. Let's close this issue.
