### ISSUE TITLE
Default Theme - Dark background boxes needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3775]
New theme settings (but not greyed out fix yet)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/edca355e-860c-4672-9e1d-6e076b4c37e4)

**Desired Settings:**
![bforartists_1wYrR6wOU9](https://github.com/Bforartists/Bforartists/assets/35357409/872b1cc5-c985-44ea-aa69-ac5a0ce42d88)

Previous colour and highlight 
![bforartists_xDmfJOouG0](https://github.com/Bforartists/Bforartists/assets/35357409/b20aaef6-8422-4580-893b-13dfe29487f4)
![bforartists_s9QAqDQQ6o](https://github.com/Bforartists/Bforartists/assets/35357409/101d5095-19d3-4a81-bbeb-c53fbc2f520b)

**Comment by ReinerBforartists** [comment]
:/

**Comment by ReinerBforartists** [comment]
Task is invalid, we have reverted the theming. Closing.
