### ISSUE TITLE
Preferences - System - For All Users checkbox float left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3776]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1f8fbfa3-da26-47fa-91b5-525dc0b90ad5)

New checkbox should float left.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
![set](https://github.com/Bforartists/Bforartists/assets/13919702/5ac2c29d-c760-4dc7-b267-2fc2117831ba)
