### ISSUE TITLE
Node Editors - Add Menu Search now hidden, revert and expose operator to GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3778]
Now
![image](https://github.com/Bforartists/Bforartists/assets/35357409/36a3ff4d-53cd-45a5-b61c-207556d84eef)

Previous:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5e0b99c3-825d-49b0-9f5c-460583a8103e)

The new Node Search in the add menus is.... now a hidden feature where you write what you want to start searching immediately, kinda nice but not discoverable. There is no GUI search operator to add nodes now, and... personally I believe this should be discoverable. You're not gonna hit random keys here to find something at first, it's disconnect. 

They changed it all up, removed the old way, have a new way... so this might be a harder task to expose that hidden feature. 

**Commits in question:**
This menu or operator might be what we need to trigger from in the add menu and/or context menu... 
`WM_OT_search_single_menu`
https://projects.blender.org/blender/blender/commit/7f9d51853c978ff

<details>
<summary>Details</summary>

SHA-1: 974edc588547e357184b63a4d5b07babd0e65ce3

* Cleanup: Remove unnecessary "add node search"

Now that specific menus can be searched directly (see 7f9d51853c978ff),
there is no need to maintain separate search functionality for adding
nodes. This PR removes the add node search. In a way this brings us
closer to the `NodeItem` situation before, but the setup is more
flexible since the menus are more standard and easier to customize.

In the few ways we customized the node search items before, this gives
us the same results as before. Overall the searching is less flexible,
but I think that is just a tradeoff we have to accept for the simplicity
of searching menus. In the future menus could be made more dynamic,
with each builtin node's menu path stored on the node type, similar to
assets. That might be a nice compromise. In the meantime this code
is just dead weight.

Pull Request: https://projects.blender.org/blender/blender/pulls/112056

</details>

**Comment by ReinerBforartists** [comment]
Crazy functionality

**Comment by ReinerBforartists** [comment]
Here is the commit in question. Quite a few things ...

https://github.com/Bforartists/Bforartists/commit/974edc588547e357184b63a4d5b07babd0e65ce3

I would wait a few days here, i am sure Blender will get some bad feedback here.

**Comment by Draise14** [comment]
Yeah, that whole operator was removed completely for another one. I wonder if the new operator can be called from the menu regardless, this it would kinda help the discoverability. 

I'll wait.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d1ea867f-bf0f-457e-aab1-ffc757de3d2f)

Yeah, they aren't rolling back yet. But they are talking of "adding an indication that it's possible" somewhere. A button we could hotkey and use per the old paradigm might be better........

**Comment by Draise14** [comment]
![bforartists_wznEoL1Xty](https://github.com/Bforartists/Bforartists/assets/35357409/a4f812d6-6458-46f8-825e-af17d9bc2d8a)
![bforartists_hN4DOrGPdI](https://github.com/Bforartists/Bforartists/assets/35357409/00ca9316-d092-4980-96bd-a6c9d1fb529c)

Operator to search nodes still is there, not exposed. We could have it exposed now traditionally, like we have in the toolbar to the top. The search seems editor contextual too now. So.. let's add it back for discoverability, ease of assigning hotkey, and with a good tooltip to show both methods of using it.

**Comment by ReinerBforartists** [comment]
Yeah, add it back i would say.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ceb5ff58-261f-4de0-b380-74240c689e0b)

Search operator is added back to the add menu, but not in the header now.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c7524942-1226-41f3-9baa-0431c9174e5b)

https://github.com/Bforartists/Bforartists/assets/35357409/94c056ab-9a42-4526-bb6e-a22c4a718c7a

That's better.

**Comment by Draise14** [comment]
Documenting.

**Comment by Draise14** [comment]
Done.
