### ISSUE TITLE
Asset Shelf - Display Settings - Float name checkbox left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3779]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0896ea10-7676-4653-9fb5-be338bf8b453)

Select Armature, go to Pose mode, see the shelf. Now.. in the overlay panel, the name check box needs to float left. And may need documenation.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
https://github.com/Bforartists/Manual/issues/486

Solved
