### ISSUE TITLE
Asset Browser - Display Mode - Thumbnails - Add button row for quick thumbnail sizes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3780]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/48372fd1-d4c2-464b-a35e-0384bc2afc52)
New slider for thumbnails now possible, but the quick presets for standard views would be nice. 

- Tiny 48
- Small 96
- Medium 128
- Large 256

Previous options:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/af42e09b-79ec-4730-9624-76130c0a4657)

Operator for the new buttons row
`bpy.context.space_data.params.display_size = 96`

**Comment by Blenux** [comment]
Like so?

https://github.com/Bforartists/Bforartists/assets/25260650/9378288b-cc7c-4a3b-850a-2c9c0fb13e01

**Comment by Draise14** [comment]
Yeah that's really nice!
