### ISSUE TITLE
Default User Preferences - Turn on "Auto Close Pairs on Selected Text"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3781]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4dd95b50-91cb-455b-9fd9-9ddb94d19720)

This could be nice turned on per default, like in Visual Studio Code

<details>
<summary>Details</summary>

SHA-1: 96339fc3131789e6caa41f7ef01cc1edf5a38a28

* Text Editor: Auto Close Pairs on Selected Text

When the auto-close preference is enabled & brackets or quotes are
entered with a selection, the selection is surrounded by those
characters - instead of replacing the selection.

Match functionality from visual-studio code.

Ref !111900.

</details>

**Comment by ReinerBforartists** [comment]
I find this a dangerous default. "Auto" on by default was never a good thing ...

**Comment by Draise14** [comment]
This is on in VScode per default.
