### ISSUE TITLE
3D View - Armature - Pose mode - Add Move to Bone Collection operators to header for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3786]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ab9e1b4b-fe9c-4121-98a0-bf1a0bbc091c)

You can do this in pose and edit mode now mode, a hotkey only operator. Make common operators discoverable.

**Comment by ReinerBforartists** [comment]
Don't crowd the header with elements that just 1% of the users will ever use.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/70159b73-d467-4e87-89c5-af17c47a48e2)

I've worked with riggers and the operator is designed to work in both modes. The riggers might be the 1%, but it's all of them... Maybe the blender devs will add it.

**Comment by ReinerBforartists** [comment]
Yeah but we have over 2000 operators, and crowding the headers with all of them is not the solution. Even when it becomes a bit more cumbersome here and there for a fraction of the people then.

**Comment by Draise14** [comment]
When switching to the blender hotkeys, these operators will exist and  be hidden in the pose mode. We also are about discoverability to be hotkey free also. 

Bforartists: discoverability (to be hotkey free), consistency, point and click usability, 

Minimism is the last of our priorities. 

It is+1 sub sub-menu with a consistent UX. We do the same with operators from fcurve and dopesheet (expose common to both).

Though we can give it time to decide since the bone collections UX is still wip by blender.

**Comment by Draise14** [comment]
Yep, as predicted. They have the "Move to Bone Collection" operator now for both modes

> SHA-1: 62639080bcec58ce90800958b443b30e34fe948f
> 
> * Anim: armature edit mode, replace 'bone layers' operator with collections
> 
> In armature edit mode, replace the 'bone layers' operator with the 'move
> to bone collection' operator. This operator now works in both pose mode
> and edit mode, and is available with the 'M' hotkey in either mode.


But now ironically it's missing in pose mode now as exclusive to hotkey. Should be exposed. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1f6f18bb-5cf7-4307-910e-5ca3d379db38)

**Comment by Draise14** [comment]
Already consistent due to blender commits and using the same menu code in both modes - thanks Blender..! Closing.
