### ISSUE TITLE
Default Theme - Script editor colours need updating, force merge conflict with changes at userdef_default_theme.c

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3787]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a797edff-8b16-420b-8aae-89482fc6d49e)

More theme colours breaking behind the scenes... hurr durr.

**Comment by ReinerBforartists** [comment]
One could really think this is by purpose ...

**Comment by ReinerBforartists** [comment]
Friends, please, when there is a change at the userdef_default_theme.c file, then do not to blindly copy over the values -.-

The fix is most probably as simple as using the old userdef_default_theme.c file ...

![FILE](https://github.com/Bforartists/Bforartists/assets/13919702/0f6855e4-7003-4d7b-8285-d1684abfb8f6)

**Comment by Draise14** [comment]
Ah ok, new entries were added to the theme templates. I guess these would need to be re-generated with the updates or they may default to Blender's new theme entries - forgot to note that down in my merge checklist..

**Comment by ReinerBforartists** [comment]
Indeed, we just need to grab the old version of the file. But we also need to check if it is a vital change that we need to do too. And we need to update the blender themes.

Mh, i need to have a look if we can make sure that changes at this file throws a merge conflict. I think this is currently not the case. Let's have a look if i can alter the blender_theme_as_c.py file to add a bfa comment.

**Comment by ReinerBforartists** [comment]
Fixed colors.

And i made now sure that changes doesn't easily slip through anymore. By adding a comment that should hopefully force a merge conflict.

![nomoreslippingthrough](https://github.com/Bforartists/Bforartists/assets/13919702/8561fb19-0832-4b35-8ba8-6c01cfbf95c6)
