### ISSUE TITLE
Armature - Pose Mode - Select Group and Layer is now "Collection" and "Color" and should be updated. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3789]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0157b509-3cba-46e3-82f0-8c24890b2b28)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/13a5378c-d780-4343-83f8-ced3057d07b2)

Name changing. This may need icon changes too. Documentation too. 

<details>
<summary>Details</summary>

SHA-1: d5329eeea23bfbd4e97829f58e35647a5551820e

* Anim: armature edit mode 'select by bone collection' operator

In the armature edit mode 'select similar' operator, replace 'select by
layer' with 'select by bone collection.

-----------

SHA-1: e59944dba4eb60f6cadad9f666f10576ebaa3aed

* Anim: armature edit mode 'select by bone color' operator

In the armature edit mode 'select similar' operator, replace the 'select
by same bone group' operator with 'select by same bone color'.

</details>

**Comment by ReinerBforartists** [comment]
Updating manual
