### ISSUE TITLE
Cleaunp - Tooltip Labels may not be necessary now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3790]
Seems the tooltip labels system has improved accross the board with their new system - meaning our workaround (currently broken) may not be needed. I need a ground truth to reproduce the issue here to know if it is still necessary though. 

Right now this is commented out in the master, but might need a revisit. 
![Meld_cRJJefCz22](https://github.com/Bforartists/Bforartists/assets/35357409/7556df94-95f0-4c58-a68c-7ec761cb04b4)

**Comment by ReinerBforartists** [comment]
This would be cool !

**Comment by Draise14** [comment]
Do you know of an example where it used to work for us, but didn't in Blender, and how to test again? Which tooltip would use this former code?

**Comment by ReinerBforartists** [comment]
Nope, sorry, i can't remember.

**Comment by ReinerBforartists** [comment]
Hmm, when our method is broken and turned off anyways, and we cannot find any side effects, then i would say remove it. I haven't found anything obvious so far.

**Comment by ReinerBforartists** [comment]
Ah wait, now i remember why i once have implemented it. It was for the add menu and for the labels in the properties editor for example. And of course for the icon only buttons in the tool shelf. This is looking good now. So it seems that we can remove our code.

![looking good](https://github.com/Bforartists/Bforartists/assets/13919702/1506cea2-0d18-4c22-8d59-4ea0f5736b5f)

![problem](https://github.com/Bforartists/Bforartists/assets/13919702/f18948e9-7de5-4481-8ef7-97608ff7e0a4)

**Comment by Draise14** [comment]
So nice to see the fix upstream. ❤️ Will clean up today.

**Comment by ReinerBforartists** [comment]
> Seems the tooltip labels system has improved accross the board with their new system - meaning our workaround (currently broken) may not be needed. I need a ground truth to reproduce the issue here to know if it is still necessary though.
> 
> Right now this is commented out in the master, but might need a revisit. ![Meld_cRJJefCz22](https://user-images.githubusercontent.com/35357409/268810290-7556df94-95f0-4c58-a68c-7ec761cb04b4.png)

And i start to search again. Please make bigger screenshots. With the file name ;)

**Comment by iyadahmed** [comment]
Fixed in: https://github.com/Bforartists/Bforartists/commit/90120452cd9316b120c6d9b79840a5fc6addbc47
