### ISSUE TITLE
Dopesheet - Grease Pencil mode - Sidebar - Layers - "Disallow Locked Materials Editing" toggle for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3792]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c4a49fae-dafd-4212-a051-42649ac406d8)

Expose "Disallow Locked Materials Editing" toggle for consistency in the layers panel in the grease pencil mode of the Dopesheet.

**Comment by ReinerBforartists** [comment]
Are you sure? Then we have a double menu entry.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Fixed
