### ISSUE TITLE
Dopesheet - Regression - Key menu need iconography and cleanup

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3793]
![bforartists_Chx7JnzFdD](https://github.com/Bforartists/Bforartists/assets/35357409/1e6aab1b-f182-4d01-b595-bd13c3e826a8)

Though I hit this in the merge, but it bleed through. These were updated backend.

**Comment by ReinerBforartists** [comment]
The content has changed, that's why.

**Comment by ReinerBforartists** [comment]
Ah, here is your missing icons, it's a double entry ^^

![cleandouble](https://github.com/Bforartists/Bforartists/assets/13919702/91aad929-1ecb-4215-b451-d1a37e4b8840)

**Comment by ReinerBforartists** [comment]
Fixed. Updating the manual.

![keymenu](https://github.com/Bforartists/Bforartists/assets/13919702/623a1417-5198-4a00-bad6-449458a61b18)

**Comment by ReinerBforartists** [comment]
Sample keyframes is renamed to bake keyframes. Riddle solved.

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
Not really, both fills the gaps with keyframes. Or better said filled. Sample keyframes seems to be deprecated :)

**Comment by Draise14** [comment]
I'll make a new task for it. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/9dab5cde-98bb-46cc-9f2b-707cbf1b31a8)
