### ISSUE TITLE
Extend Iconset

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3796]
We run out of icon space again. Who wants to extend the set? I know already how to do it ^^

Related task: https://github.com/Bforartists/Bforartists/issues/2145

![outofspace](https://github.com/Bforartists/Bforartists/assets/13919702/f8f8c833-53fa-49b9-b509-3c4a5ed58727)

**Comment by Draise14** [comment]
Would be good to know how.

**Comment by ReinerBforartists** [comment]
That's why i have linked the former commit ;)

But feel free to ask in case you get stuck :)

**Comment by Draise14** [comment]
Will tackle this after 4.0.0 release for 4.1.0

**Comment by Draise14** [comment]
It is time...

**Comment by ReinerBforartists** [comment]
It's mainly lots of work ^^

**Comment by iyadahmed** [comment]
But how? The link is broken I think, it would nice to share the link here

**Comment by ReinerBforartists** [comment]
No, the link is not broken, it is all here :)

https://github.com/Bforartists/Bforartists/commit/06f5652dab73a54b62dacbbb02202d3bffe5be29

You need to resize the blender_icons.svg to have (ten is a good number) more columns. Change the entries in blender_icons_updates.py to these new values.

Then you edit the UI_icons.h, and add these more columns there too. Use the def_icon_blank entries. And add a number behind. The line number is a good idea. First fix the handful remaining def_icon_blank entries to have new numbers.

Then you do the same with the cmakelists.txt file in the source\blender\editors\datafiles directory. Then there is the changes at  source/blender/editors/interface/interface_icons.c remaining, where you increase the icon_grid_cols to the new values. blender_icons_updates.py has also values here.

Then comes the drum roll, followed by recreating the icons, followed by compiling and the big chance that you start to cry because something is missing or doesn't work as expected ... i've been there, every time when i extended the sheet :D

**Comment by Draise14** [comment]
Will work it after some commission work. Thanks for the deeper explanation.

**Comment by ReinerBforartists** [comment]
You're welcome. Don't hesitate to ask in case you are stuck :)

**Comment by Draise14** [comment]
Compiling debug, got it I think.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/298d62fc-dc9c-4130-82db-5db5a2559bd8)

Maybe spoke too soon. Can't find two icon ID's.

**Comment by ReinerBforartists** [comment]
It's a trap !

**Comment by ReinerBforartists** [comment]
internals like Blenkernel has nothing to do with addons.

The error message does not show here though, i have recreated the icons, did a clean compile, and do not get these kind of errors. All works well. Clearing the cmake cache may help.

**Comment by Draise14** [comment]
Will recompile from scratch, good point.

**Comment by Draise14** [comment]
Found the issue, was an old addon referencing icons the wrong way, by index instead of name.
