### ISSUE TITLE
Animation editors channel menus clean up - channel settings belongs into the channel settings sub menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3799]
I have at one point explicitely created the channel settings menu to get this channel settings crap out of the way. To control this functionality from a menu far far away from the channel shelf is plain crazy. 

Now we have double entries again in the channel menus that crowds the menus. Needs a fix.

![channelsettings](https://github.com/Bforartists/Bforartists/assets/13919702/9d9bee1c-c446-47c9-a47b-f78fa2f26c7c)

**Comment by ReinerBforartists** [comment]
And where does this greyed out content come from? O_O

Keys to samples, Samples to Keys and Sound to Samples does not belong into this menu. Needs investigation too.

**Comment by Draise14** [comment]
Looks like it has double entries too.

**Comment by Draise14** [comment]
The sub-menu is loaded from the fcurve sub-menu - and they are sub-menu operators that might be doubled up. Checking.

**Comment by Draise14** [comment]
![bforartists_6X93iff9OV](https://github.com/Bforartists/Bforartists/assets/35357409/db565ac9-b112-43e8-8f4d-e8218cc0da7f)
![bforartists_ZtDFaUqXxL](https://github.com/Bforartists/Bforartists/assets/35357409/e7467b1d-8548-4d36-87a0-275bb483e99a)
![bforartists_yyhlb3u3iv](https://github.com/Bforartists/Bforartists/assets/35357409/1b3563f8-45e1-466e-a743-adf50c0b1133)

Updated Dopesheet and Fcurve editor, made the Fcurve operators conditional, commented things clearly, and also made the context menu consistent in name and dividers.

**Comment by Draise14** [comment]
Documenting.
