### ISSUE TITLE
Properties Editor - Pysics - Simulation Nodes - Float "Cache" checkbox left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3803]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/82efe788-fd33-4b23-b59a-b1dbbdcd4265)

Missed this one.

**Comment by ReinerBforartists** [comment]
I'm lost with the documentation, i haven't figured out the simulation nodes yet, and most probably never will. Do we even have this documented yet?

Either way, this is fixed. I'll make a documenting task for it.

![simu](https://github.com/Bforartists/Bforartists/assets/13919702/bd755d40-7ce6-4900-9a8d-bc6777a7310e)

**Comment by Draise14** [comment]
Yes, documented in the **12.1.32 Editors - Geometry Nodes Editor - Header - Add Menu - Simulation** chapter
