### ISSUE TITLE
Principled bsdf layout differences to Blender

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3809]
We should put the properties into the sub categories like Blender does.

And while at it, what happened to the Subsurface color? Not longer existent?

![principled](https://github.com/Bforartists/Bforartists/assets/13919702/b9bb824f-6811-40b3-8777-21dbbd1a2e18)

**Comment by Blenux** [comment]
The Subsurface Color now uses the Base Color has it's color input.

**Comment by ReinerBforartists** [comment]
So you can't have different colors anymore? :(

**Comment by Blenux** [comment]
![Screenshot_20230928_172901](https://github.com/Bforartists/Bforartists/assets/25260650/0fe86e04-4b14-43a7-aeb0-4f7b44c6e377)

Nope only the RGB Radius. (never use it here)

**Comment by Draise14** [comment]
Yeah, this changes all my SSS workflows....

**Comment by ReinerBforartists** [comment]
*sad cat noise*

**Comment by ReinerBforartists** [comment]
Mh, the newest merge seems to have fixed the issue. This, or somebody has fixed it meanwhile, and forgot to connect it to the issue.

Either way, issue is solved. Documenting.
