### ISSUE TITLE
3D View - Armature - Pose and Edit mode - Armature>Bone Collection menu - Make icons consistent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3811]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ac00ebf9-012d-4e35-86ac-8dce49479735)

They have updated the bone collection management in the edit and pose mode, but the icons are not correlative nor consistent. Let's make them consistent.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a9130cf9-7af4-46c9-affe-0fb7edbe3d65)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c5f31e2b-ef0b-423d-8e95-0aaad1d0db49)

Yeah,more consistent now, now they are "bone collections" with colours used in the group icons.

**Comment by ReinerBforartists** [comment]
Could you please also add these new icons to our file repository then?

**Comment by Draise14** [comment]
Yes, will do.

**Comment by Draise14** [comment]
Gonna have lunch, then will document.

**Comment by Draise14** [comment]
Documented.
