### ISSUE TITLE
3D View - Armature - Edit Mode - New "Move to Bone Collection" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3812]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1af7aff4-e26f-46f7-ab30-5f1e521ccdcd)

Need iconography and documentation

**Comment by ReinerBforartists** [comment]
Duplicate. Icons are already assigned. Closing.

3D View - Armature - Pose/Edit mode - Move to Collection submenu iconography and order for consistency #3878
