### ISSUE TITLE
3D View - Armature - Edit mode - wrong icons/label on "layer" and "group"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3813]
Theoretically the same operators to select colour and select collection under grouped in pose mode should also exist in edit mode. It still says "grouped" in edit mode, and the color method is missing in the "Select Similar" menu.

Label may also need to be double checked.

Desired new operators and iconography:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0afb6102-ecce-4709-8e93-5ad08ae22588)

<details>
<summary>Details</summary>

SHA-1: d5329eeea23bfbd4e97829f58e35647a5551820e

* Anim: armature edit mode 'select by bone collection' operator

In the armature edit mode 'select similar' operator, replace 'select by
layer' with 'select by bone collection.

</details>

<details>
<summary>Details</summary>

SHA-1: e59944dba4eb60f6cadad9f666f10576ebaa3aed

* Anim: armature edit mode 'select by bone color' operator

In the armature edit mode 'select similar' operator, replace the 'select
by same bone group' operator with 'select by same bone color'.

</details>

**Comment by ReinerBforartists** [comment]
A good screenshot saves lots of typing ;)

![selectmenu](https://github.com/Bforartists/Bforartists/assets/13919702/39c8640c-ff76-4f69-a76f-c6d15469dff3)

**Comment by ReinerBforartists** [comment]
This one slipped through a merge. It's a enum.

![enum](https://github.com/Bforartists/Bforartists/assets/13919702/f9a5c16d-ec13-4ebd-b83e-fdb1872cf129)

**Comment by ReinerBforartists** [comment]
Operators have changed. Documenting.

**Comment by ReinerBforartists** [comment]
Fixed
