### ISSUE TITLE
Default Preference - Regression - Enable "Auto Depth" by default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3814]
This is an old regression. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/edd2fb37-e688-420d-b954-c1f1979c2476)

> Is your feature request related to a problem? Please describe.
> While navigating the 3D viewport, when the user zooms in a lot they will reach a point where they cannot zoom in anymore and the viewport's camera is 'frozen'. The user cannot zoom in anymore, and they cannot pan the view either.
> 
> Describe the solution you'd like
> There is already a solution built into Blender. Open the Preferences and look at the Navigation section. Enable "Auto Depth" and the user will be able to continue zooming and to freely navigate after lots of zooming as long as there is an object under the cursor.
> 
> I propose that this checkbox should be enabled by default in Bforartists because it represents a better user experience than having it disabled by default (especially for satisfying new users who are trying out Bforartists after coming from other software). It is more consistent with other DCC programs that zoom this way and it has been reported by other users as desirable. [devtalk.blender.org/t/zoom-to-mouse-position-auto-depth/7033](https://devtalk.blender.org/t/zoom-to-mouse-position-auto-depth/7033)

 Enable "Auto Depth" by default #1657

**Comment by ReinerBforartists** [comment]
Fixed
