### ISSUE TITLE
3D View - Edit mode - Vertex Crease added to context menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3816]
![bforartists_C8mgWOqCgL](https://github.com/Bforartists/Bforartists/assets/35357409/ff9c4f42-82ba-4323-9d9a-fafe478015a6)

![bforartists_uk4D8RhlTN](https://github.com/Bforartists/Bforartists/assets/35357409/c27e37e4-f7e0-4ff9-be87-fcd53d203e4e)

Added to context menu, has no icon. Could be documented too. 

<details>
<summary>Details</summary>

SHA-1: 63fef34fdaeded5e0d28f24c154dc1924f10fb55

* UI: Add Vertex Crease operator to vertex context menu

Add Vertex Crease operator to vertex context menu. This is consistent with
edge context menu having Edge Crease menu.

Pull Request: https://projects.blender.org/blender/blender/pulls/109146

</details>

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
fixed
