### ISSUE TITLE
3D View - Object - Remove icons from sub-folders

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3817]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/13081ac5-db9a-4214-b15c-731a07467bbf)

Blender added icons, but on a folder. That bleed through with the merge so will remove for consistency sake. Either all the folders has a representative icon, or no icon. 

_I've had users request multiple times for folder icons, but I understand the benefit of no icon on a folder for representation - but I am no fan of needing to read to find folder. But that can be talked another day._ 

<details>
<summary>Details</summary>

SHA-1: da495765b42cfbddeeb66556dc4d33ac6fd124ce

* UI: Add icon to Library Override menu entries

To create a connection with the icon that shows up in
ID templates and decorators once library is overriden.

Affects Outliner context and Object menu in 3D Viewport.
Similar to the Asset menu.

</details>

**Comment by ReinerBforartists** [comment]
Indeed. Menus are much easier to find and to separate from the other content when they have no icon. And it should be consistent then. I'm happy to see that i have convinced you at this point :)

We have an exception in the add menu in the 3d view. Where the icon tells you what content is to expect in the menu. But this should really stay an exception.

**Comment by Draise14** [comment]
I'm not 100% convinced to be honest, I do like some kind of visual folder indicator as I would with the folders of the file browser blend view or file explorer of an OS - but yeah, consistency here for now.

**Comment by ReinerBforartists** [comment]
Fixed
