### ISSUE TITLE
Fcurve Editor - New Push/Pull key slider operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3818]
![blender_wau1aaYVsY](https://github.com/Bforartists/Bforartists/assets/35357409/2e985aed-e6ab-4cd3-8027-a274850cb7ff)

![HNKcwkvsX3](https://github.com/Bforartists/Bforartists/assets/35357409/ff9f4e25-c07d-4f28-9e15-5d297bdc21f6)

Currently missing in Bforartists, it did not bleed through. Should be exposed and documented.

> Scales the selected keys from an imaginary line that
> runs from the start to the end of the segment.

<details>
<summary>Details</summary>

SHA-1: 25031f8a86d0a9d0e72568c69aef2b4a913d2720

* Anim: Graph Editor Push/Pull operator

This finishes the work that Ares Deveaux started here #106527

Scales the selected keys from an imaginary line that
runs from the start to the end of the segment.

Co-authored-by: Ares Deveaux <aresdevo@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/112388

</details>

**Comment by ReinerBforartists** [comment]
Documenting.

**Comment by ReinerBforartists** [comment]
done
