### ISSUE TITLE
Fcurve Editor - New Select Handle operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3820]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c14d4897-8769-42e5-bcea-56c73988ec3a)

New select handle operators. They have a lot of sub-options, so work the documentation! 

 

<details>
<summary>Details</summary>

SHA-1: be5cf8f8a1ac72a76c12b717f6c0f7d6efa8acfe

* Anim: add graph editor key/handles selection operator

This adds an operator `graph.select_key_handles` to the graph editor
that changes the selection of the different parts of a bezier keyframe.  It
operates on all keys that are either themselves selected or have either of
their handles selected, and changes whether the key itself and/or its handles
are selected.

The operator has three options:

- `left_handle_action`
- `right_handle_action`
- `key_action`

Each of which can be set to:

- Select
- Deselect
- Keep (do nothing)

Co-authored-by: cgtinker <Denys.Hsu@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/111143

</details>

**Comment by ReinerBforartists** [comment]
It is as usual one operator with a dozen sub modes. And as usual, they share the same tooltip. Needs a fix too.

![selectnonsense](https://github.com/Bforartists/Bforartists/assets/13919702/3a61e062-944e-4e58-9189-63259948710d)

**Comment by Draise14** [comment]
How do you do a split tooltip for these kinds of things?

**Comment by ReinerBforartists** [comment]
That's a python method. I thought more about the C way. Like here:

https://github.com/Bforartists/Bforartists/issues/3910

I am not sure which method is the better one here. C is definitely more elegant and faster. But what worries me here is the possible combination of all three props. So i am not sure if a separated tooltip makes even sense.

**Comment by Draise14** [comment]
Going with C now

**Comment by Draise14** [comment]
![bforartists_PR62HVhVwv](https://github.com/Bforartists/Bforartists/assets/35357409/714d2c8e-ec4a-4c81-b695-c6268ec534ea)

Also made a new icon. Will document.

**Comment by Draise14** [comment]
Documented.

**Comment by Draise14** [comment]
Commit to master
