### ISSUE TITLE
Fcurve Editor - Keys - New Time Offset slider

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3821]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0f096529-114a-461f-aa76-d05e1c2304cf)

Yet another slider operator. Icons, documentation, you know the drill... 

<details>
<summary>Details</summary>

SHA-1: 01927e1e459f392fedb4549557eb49eb1d20769a

* Anim: Time Offset Slider

This patch has been originally authored by Ares Deveaux #106520
I am just finishing it up.

This is a new operator for the Graph Editor.
It shifts the value of the keys in time,
while keeping the actual key positions in the same place.
It supports wrapping, so when offsetting beyond the range
of the F-Curve it will take values from the other end,
but offset in y-value so there is no jump.

This works best with dense key data.

Co-authored-by: Ares Deveaux <aresdevo@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/110540

</details>

**Comment by ReinerBforartists** [comment]
Already fixed with another task

Fcurve Editor - New Push/Pull key slider operator #3818
