### ISSUE TITLE
Python Console - Expose consistent text operators like in the Script Editor

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3823]
![bforartists_Q30B2k2bsc](https://github.com/Bforartists/Bforartists/assets/35357409/1cc0163a-e091-4e8c-8c27-737b09d906b9)

You can now do text selection in the Console Editor. We exposed these to the Text editor, would be good to do the same in this editor.

New Operators:
- Delete
- Cut
- Select All
- Deselect
- Select PREVIOUS_WORD
- Select NEXT_WORD
- Select LINE_BEGIN
- Select LINE_END
- Select PREVIOUS_CHARACTER
- Select NEXT_CHARACTER

<details>
<summary>Details</summary>

SHA-1: 18e07098ef25e7659e0c14e169a96b49c5a54cbf

* UI: Support additional console text operations

Adds the ability to set text cursor position in the Console editor
by clicking with the mouse and many other expected operations such as
cut, select all & deselect on text entry.

Ref !108626

</details>

https://projects.blender.org/blender/blender/pulls/108626

**Comment by ReinerBforartists** [comment]
Ah, the hotkeys are also missing. But first the new select menu.

**Comment by ReinerBforartists** [comment]
Documenting. 

![done](https://github.com/Bforartists/Bforartists/assets/13919702/8bb2d1e4-ef6a-43c0-9e2b-e46e8ec60e71)

**Comment by ReinerBforartists** [comment]
Whoops, wrong text is wrong

![wrongtext](https://github.com/Bforartists/Bforartists/assets/13919702/7278b030-923d-4d27-9888-947f042a8448)

**Comment by ReinerBforartists** [comment]
That's better

![select](https://github.com/Bforartists/Bforartists/assets/13919702/86ed68e4-0b42-4672-a455-ee5ec04895fa)

**Comment by ReinerBforartists** [comment]
Fixed
