### ISSUE TITLE
3D View- Sculpt Mode - Warning: property "not found in item 'OperatorProperties'"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3824]
![WindowsTerminal_Jz0L3q4awC](https://github.com/Bforartists/Bforartists/assets/35357409/93bafb88-a7f1-40a0-9270-5a576c3f42a4)

I'm getting these warnings when loading up on factory compile at the moment. Not sure what's up.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6b577bab-de0d-436d-8ae0-b54614067508)

Might be a keymap issue.

**Comment by Draise14** [comment]
Documenting.

**Comment by Draise14** [comment]
Documented.

**Comment by Draise14** [comment]
I removed the hotkeys here, were mask operators like expand.

**Comment by ReinerBforartists** [comment]
This one needs further work. 

Be careful with the MacOS keymap. Mac does not have CTRL, but the oskey ...


![machasnoctrl](https://github.com/Bforartists/Bforartists/assets/13919702/679a67f0-91c5-47b9-acce-2feead524293)

**Comment by Draise14** [comment]
Huh, these are pretty old entries. Will update.

**Comment by ReinerBforartists** [comment]
Fixed
