### ISSUE TITLE
Rocky Linux and DEB and Appimage

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3826]
We have migrated to Rocky Linux for building. 

What i haven't tested so far is if the tar made with rocky works on Ubuntu, and if we are even able to create a deb. Or if we loose the ability to build the deb.

**Comment by ReinerBforartists** [comment]
Phew, the tar made with rocky works at ubuntu 23. But not at Ubuntu 22, which was to expect since Ubuntu 22 doesn't meet the OpenGL requirements of 4.3 anymore. It comes with OGL 4.0

I'll have a look at the deb problem when i find time for.

**Comment by ReinerBforartists** [comment]
Okay, building works. But deb is not rpm. And so we cannot test the deb at rocky. So i need to keep a Ubuntu vm to test if the deb works. 

*sad cat noise*

Testing ...

![building](https://github.com/Bforartists/Bforartists/assets/13919702/031366fd-fb1e-4565-a686-674521211174)

**Comment by ReinerBforartists** [comment]
\o/

![works](https://github.com/Bforartists/Bforartists/assets/13919702/b6344850-2ced-41ba-9e09-8ae99c0936e9)

**Comment by ReinerBforartists** [comment]
Appimage needs a test too i guess.

**Comment by ReinerBforartists** [comment]
Unfunny. Did appimage move?

![not found](https://github.com/Bforartists/Bforartists/assets/13919702/b049810c-7e2c-40ff-9aee-9918d262b4c7)

**Comment by ReinerBforartists** [comment]
Link has changed. Is now 

https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage--x86_64.AppImage

**Comment by ReinerBforartists** [comment]
Aaand it hangs at the last step.

@iyadahmed , do you have an idea here?

![laststep](https://github.com/Bforartists/Bforartists/assets/13919702/9a07c05c-5fcf-4406-aecd-6a29b1125d40)

**Comment by iyadahmed** [comment]
> Aaand it hangs at the last step. GlibC 2.30 not found? O_O
> 
> @iyadahmed , do you have an idea here?
> 
> ![laststep](https://github.com/Bforartists/Bforartists/assets/13919702/9a07c05c-5fcf-4406-aecd-6a29b1125d40)
> 
> 

I'll look today ^^

**Comment by iyadahmed** [comment]
@ReinerBforartists 
you can do the building in rocky 8 and app image generation on Ubuntu ^^
(move the compresses build result from Rocky to Ubuntu then generate app image on Ubuntu)

**Comment by ReinerBforartists** [comment]
Uh, this doesn't sound healthy for our move away from Ubuntu :D

**Comment by ReinerBforartists** [comment]
Any news here? Point is, when we need to go back to Ubuntu for several steps then the whole migration to Rocky doesn't make sense ...

**Comment by iyadahmed** [comment]
Looking at it asap ^^

**Comment by ReinerBforartists** [comment]
No pressure. Yesterday is fast enough :)

**Comment by ReinerBforartists** [comment]
Rocky 8 has glibc version 2.28

**Comment by ReinerBforartists** [comment]
I found a thread with a similar problem. I found a thread with a similar problem. https://github.com/neovim/neovim/issues/19711

And it seems that Appimage has risen the requirements for appimage to glibc 2.30. Unfortunately the pkg2appimage. Appimage is a rolling release, and so there is no way back from what i can see. 

What options do we have now? Ideas? Using Rocky 9 instead? Ah Linux, nothing but trouble ...

**Comment by ReinerBforartists** [comment]
By the way, it can be that even our Ubuntu environment fails to build the appimage now. Testing ...

**Comment by ReinerBforartists** [comment]
Okay, Ubuntu has GlibC 2.35. This is quite a bit above the limit of 2.30. And the appimage builds.

**Comment by iyadahmed** [comment]
> It seems that the only valid option that we have is to upgrade to Rocky Linux 9 :/

This will also raise the glibc of Blender build making using rocky not very helpful we and blender use it so that Blender can work on more distros ^^

**Comment by ReinerBforartists** [comment]
Yeah, but Ubuntu 22 uses Glibx 2.35 already. And Rocky 9 is at 2.34. So still a gain to what we have used previously. The lousy ABI remains one of the disadvantages of linux. Nothing that we can fix here.

As told, the other option would be to build us our own pkg2appimage.Appimage version. And this would be one more thing to maintain ...

**Comment by ReinerBforartists** [comment]
I count this heart as green light to upgrade ^^
Will have a look in the next days.

**Comment by ReinerBforartists** [comment]
Seems that we better start over. This is not the first trouble ...

![fails](https://github.com/Bforartists/Bforartists/assets/13919702/8d6a6e4d-3481-4281-a649-a8a9aec8f08d)

**Comment by ReinerBforartists** [comment]
I really start to cry with this crap OS. The continue button is out of reach ...

![woweiter](https://github.com/Bforartists/Bforartists/assets/13919702/407abcf0-315b-483f-b1eb-389999b2d0ea)

**Comment by ReinerBforartists** [comment]
Ah, second try works.

**Comment by ReinerBforartists** [comment]
And now it doesn't start the graphical UI, but logs in at console. Nightmare OS ...

![console](https://github.com/Bforartists/Bforartists/assets/13919702/285d0e2f-913f-4c46-b7f2-e67667e3b6f5)

Starting over ...

**Comment by ReinerBforartists** [comment]
Ah it was the wrong iso. Minimal instead of DVD.

**Comment by ReinerBforartists** [comment]
![dankemerkel](https://github.com/Bforartists/Bforartists/assets/13919702/845761ae-efe0-49f6-bab8-fb1092955208)

**Comment by ReinerBforartists** [comment]
Okay, this is the same problem than with Ubuntu 23. Copy N paste, let alone drag n drop, does simply not work. VMWare player is up to date. And the open tools for vmware are up to date. Not sure what to do here now. Wasting more time with this or simply abandoning it.

**Comment by ReinerBforartists** [comment]
Managed to create a share folder so that i don't need to upload the material to the cloud that i want to share between windows and rocky all the time. Let's see if this leads to somewhere.

**Comment by ReinerBforartists** [comment]
\o/

On with further preparations.

![on](https://github.com/Bforartists/Bforartists/assets/13919702/0113f86a-29e9-4374-bdb1-ca2287583879)

**Comment by ReinerBforartists** [comment]
I smell a end of road here. The linux_rocky8_setup.sh already failed. And installing the needed libs manually, well, a handful ends in not found.

![endofroad](https://github.com/Bforartists/Bforartists/assets/13919702/96fa0c59-22b0-4250-af81-2226bf29ab12)

**Comment by ReinerBforartists** [comment]
End of road. There is no rpm to find at the page that provides the rpm.

https://rhel.pkgs.org/8/epel-aarch64/jack-audio-connection-kit-devel-1.9.14-4.el8.aarch64.rpm.html

**Comment by ReinerBforartists** [comment]
Hm, found it here https://dl.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/p/

On to next problem

**Comment by ReinerBforartists** [comment]
Powertools is known as crb under RL9.

dnf config-manager --enable crb

**Comment by ReinerBforartists** [comment]
Giving up. Nvidia drivers doesn't install because of missing dkms. And this missing dependency is not to convince to install. Most probably the next dependency that is not longer part of the Rocky eco system, and must be grabbed elsewhere. But this time i found no source.

This experiments showed me that Rocky Linux is a dead horse. Vesion 9 is not reliable anymore. Too much important dependencies are not longer part of Rocky Linux. Something that i already somehow expected after Red Hat pulled the plug. Version 8 doesn't allow us to build AppImage. Ubuntu is still a disaster and equal unreliable. We can build at Ubuntu 22, but not longer test if our build really runs.

So what shall we do? It makes simply no sense to go on with Rocky Linux when half of the work must be done at Ubuntu anyways.

Ideas, thoughts?

**Comment by ReinerBforartists** [comment]
Hmm. At least it compiles. And i could try to install cuda by the run file ...

**Comment by ReinerBforartists** [comment]
Okay, was no good idea to create the vm with a virtual disk with multiple files. The 20 gb partition is full, which stopped me to continue with installing cuda then. So full stop here.

**Comment by ReinerBforartists** [comment]
I might give it another shot once BFA 4.0 is out. But for now, postponing.

**Comment by ReinerBforartists** [comment]
I did the same mistake than with the rocky 9 try. The virtual disk has multiple files. And the 40 gb block is full now. Arrrgh.

**Comment by ReinerBforartists** [comment]
I have now extended the disk space to 80 gb. Have a block with 41 gb. None of the blocks is completely full. AND THIS CRAP OS MOANS ABOUT THAT THE DISK IS FULL AND THAT THERE IS NO MORE SPACE FOR 1 MORE GB?

Can we please finally abandon this os? I don't want to waste my life time with it anymore.

![crapos](https://github.com/Bforartists/Bforartists/assets/13919702/0bfbab0f-fa41-4ae1-82cc-9b850459fc25)

**Comment by ReinerBforartists** [comment]
I have still no idea where the system is missing the 20 gb of extra space i gave it. Just 64 of the 80 gb is really used. Gparted lists me 16 gb as unused, but i cannot find a way to make it "used". And the 60 gb is divided into these ominous "blocks", which gives me just 40 gb of these 60 gb for the directory where it wants to use and put the updates into. And here i have indeed just 7 gb free. Which is not enough for updating the nvidia drivers. And the failed updating of the drivers has killed the nvidia drivers now. No more cuda. Means this VM is now dysfunctional for our needs.

One of the resource hogs is funnily Rocm, which occupies 10 gb alone.

I never had such a problem under Ubuntu / Debian. And in fact, when i start to google for the error then i always land at fedora rhel based distros. So the next logical step is to install Debian now.

Linux, nothing than trouble ...

![crapos](https://github.com/Bforartists/Bforartists/assets/13919702/f1d9330b-af19-4ec3-8421-33d53e3ebc07)

**Comment by ReinerBforartists** [comment]
Hm, Debian 12 has glibc version 2.37. Debian 11 would have glibc version 2.31. But i don't want to land at yet another outdated version where our bfa doesn't start anymore. Ubuntu is meanwhile at 2.38.

**Comment by ReinerBforartists** [comment]
Giving up. I can't even find a debian iso to download. Must be super hard to put a download button at a webpage ...

**Comment by ReinerBforartists** [comment]
No blocks anymore \o/

But don't cheer too early. Let's see if i run into the same drag n drop trouble like under ubuntu and rocky 9 ...

![noblocks](https://github.com/Bforartists/Bforartists/assets/13919702/b050138a-9f2e-44a2-985f-b0c6d103eee9)

**Comment by ReinerBforartists** [comment]
And again i run from trouble to trouble. The rights system is borked already from the start. My user is not in the sudoers. Means i need to switch to root all the time at the console since login as root fails. Calling nautilus from the cmd throws errors ... 

![fubar](https://github.com/Bforartists/Bforartists/assets/13919702/43883331-9bb9-4c71-ba3c-16aacad19a52)

**Comment by ReinerBforartists** [comment]
So far so good. It compiles. Still missing cuda and optix of course, it was just a simple make. But doesn't make the trouble that Rocky 9 did. So this is imo the way to go.

Question remains if we should use Debian 11 or 12. Debian 11 has the lower glibc version. But Debian 12 is more future proof. And i don't want to run through the same loopholes next year again. This ruins my nerves.

Suggestions before i continue here?

![sofarsogood](https://github.com/Bforartists/Bforartists/assets/13919702/83bb1f65-7c09-41ba-a39b-8997fa0e0a83)

**Comment by ReinerBforartists** [comment]
> No blocks anymore \o/

After googling my fingers bloody again i understand what is going on here. Rocky uses the LVM file system. And this sets up three partitions by default. sda, home and root. And this is the blocks that we see then. And with these blocks we run into the space problem even when there is in general enough space, since the / partition itself is too small. 

In Debian i can choose to use the whole drive, which i did now. Or to use LVM, with its three partitions and the space trouble.

**Comment by ReinerBforartists** [comment]
Hopping from problem to problem again. Installed Debian 11, and i cannot call nemo / nautilus from console. Which makes it impossible to do root related stuff in the file browser. Linux wastes so much of my lifetime with trivial things that simply should not happen -.-

![ubuntu11](https://github.com/Bforartists/Bforartists/assets/13919702/ad94f4e3-23ec-4b1a-8a28-ed08346b9326)

**Comment by ReinerBforartists** [comment]
Ah, it's nemo at debian 11, not nautilus. At least with the current theme ...

![nautilusornemo](https://github.com/Bforartists/Bforartists/assets/13919702/96488c6b-f4eb-4faa-baa4-13fd6ddf0b09)

**Comment by ReinerBforartists** [comment]
I guess it's Cinnamon. Let's try Gnome.

**Comment by ReinerBforartists** [comment]
Nautilus, and no error message!
Yeah Baby \o/

![yeahbaby](https://github.com/Bforartists/Bforartists/assets/13919702/9649a498-4a10-46f0-aec4-e0684af10a43)

**Comment by ReinerBforartists** [comment]
Drag n drop does not work. Copy n paste does not work with folders. And the shared folder does not work neither -.-

**Comment by ReinerBforartists** [comment]
I should have known it. Every linux is different. And the official method with 

/usr/bin/vmhgfs-fuse .host:/ /home/x/shares -o subtype=vmhgfs-fuse,allow_other

does not work.

Following this advice here now: https://alexandrerosseto.medium.com/vmware-linux-how-to-share-folder-between-host-and-vm-62e63419ecbb#:

Image shows the non permanent method, which you have to repeat in every session. Let's have a look to add the info to the fstab file.
![share](https://github.com/Bforartists/Bforartists/assets/13919702/ae9ad02c-9929-40cf-931a-939aed8f5db1)

**Comment by ReinerBforartists** [comment]
-.-

![nope](https://github.com/Bforartists/Bforartists/assets/13919702/a47cf39c-7521-4641-9c37-ca893a15d3dd)

**Comment by ReinerBforartists** [comment]
Okay, then the pragmatic solution. Mount when needed.

![manualshare](https://github.com/Bforartists/Bforartists/assets/13919702/f9c8ca6b-7d2d-4999-bf9c-820f5d96780f)

**Comment by ReinerBforartists** [comment]
Ah , managed the auto sharing by adding the following line to etc/fstab:

.host:/	/home/x/shares	fuse.vmhgfs-fuse	auto,allow_other	0	0

**Comment by ReinerBforartists** [comment]
*angry gollum gif*

![gcctoolow](https://github.com/Bforartists/Bforartists/assets/13919702/0b79aebd-14b1-4fce-9913-d51f85084657)

**Comment by ReinerBforartists** [comment]
Test test 

https://www.cyberithub.com/how-to-update-or-upgrade-gcc-to-latest-version-on-ubuntu-debian/

**Comment by ReinerBforartists** [comment]
Nope.

Search continues ...

**Comment by ReinerBforartists** [comment]
Yep, broke my debian installation. No way to call the console at the current folder anymore.

**Comment by ReinerBforartists** [comment]
Okay, same problem as with rocky. You can install what you want. The old official supported version is still the one that is used. So let's have a look if the workaround from Rocky also works for Debian ...

![workaround](https://github.com/Bforartists/Bforartists/assets/13919702/b08a71aa-aa5c-4b0b-af22-01fd0479728a)

**Comment by ReinerBforartists** [comment]
And another dead end. scl is a redhat tool. And is non existent at Debian. So scl enable gcc-toolset-11 bash does not work.

Seems that we are stuck with either Ubuntu 22 or Debian 12 then. But let's do some further experiments first

**Comment by ReinerBforartists** [comment]
Woah what a battle. And a lengthy discussion with chatgpt too. But now i seem to have gcc 11 and g++ 1 installed. Now comes the funny moment to find out if it is borked or functional.

Drumrolls ....

![gcc11](https://github.com/Bforartists/Bforartists/assets/13919702/4e3ced92-903a-4a38-83e6-4f4456435b90)

**Comment by ReinerBforartists** [comment]
Friends, we are either back at Ubuntu, or we continue with Debian 12. Debian 11 is not to convince.

I will now continue to prepare Debian 12 ...

![nope](https://github.com/Bforartists/Bforartists/assets/13919702/5441839c-d0cf-449d-9498-b0b4e642eb47)

**Comment by ReinerBforartists** [comment]
Aww, it was me. Once more trapped by the cmake cache XD

Currently running a make. Then let's try the make release. And then let's test all the other stuff like appimage again.

![running](https://github.com/Bforartists/Bforartists/assets/13919702/7bd31bc5-1332-44fc-a242-e88a4e98fd28)

**Comment by ReinerBforartists** [comment]
The joy did not last long ...

Then it's debian 12!

![nope](https://github.com/Bforartists/Bforartists/assets/13919702/c8959d71-46ce-4d1b-bfa2-ac08afb9e794)

**Comment by ReinerBforartists** [comment]
Well. I started from scratch since i wanted to change a few things at the base installation, and again i cannot access nautilus as root. 

![debiancrash](https://github.com/Bforartists/Bforartists/assets/13919702/0ccacb1d-d4e0-443f-b165-211f80411b0c)

End of road. We don't have any reliable linux environment anymore, and i am simply running out of options. 

Rocky Linux 8 does not upgrade anymore. Rocky linux 9 is a dead end, caused by Red Hat pulling the dependency plug. Ubuntu 22 does compile, but not start BFA. And reaches slowly eol for our purposes anyways. Ubuntu 23 has massive problems. Debian 11 made massive trouble to get it even to compile. And does not start BFA then, like Ubuntu 22. And Debian 12 is too buggy to work with. When the default file browser in the default configuration, freshly installed, already fails at the most basic things ...

Unassigning. Not solveable. When it's for me then that was it with our Linux support. I don't see any useful way here anymore.

**Comment by ReinerBforartists** [comment]
Aww, shall i continue shall i not continue ...

Gave it a last try with the cinnamon desktop and turning off gnome. Not that the error message with nemo here is any better. But this time i am at least able to use nemo as root. It does not crash. Let's see where this leads to.

![stilltroubled](https://github.com/Bforartists/Bforartists/assets/13919702/9f28dc53-6665-44e9-9d45-4771e9370994)

**Comment by ReinerBforartists** [comment]
Now we are talking. Still misses cuda and optix. And some fine tuning at Debian. And the cinnamon desktop is something to get used to. But the base works now.

![working](https://github.com/Bforartists/Bforartists/assets/13919702/d0addb9d-389e-44de-a333-99f7f1da8e8a)

**Comment by ReinerBforartists** [comment]
I can't install optix it seems. The sh file shows the agreement ,and then it jumps to end. And that was it. No field to agree like i have seen before. Linux ...

![optixnogo](https://github.com/Bforartists/Bforartists/assets/13919702/f09e220d-c693-41ff-b343-acb83701f794)

**Comment by ReinerBforartists** [comment]
Still to early for cheering, but the make release did succeed. Let's do further tests.

![lookinggood](https://github.com/Bforartists/Bforartists/assets/13919702/699dcb1e-2bb1-455e-aaa4-574239c3d45a)

**Comment by ReinerBforartists** [comment]
Appimage creation works. And is starting.

![appimage](https://github.com/Bforartists/Bforartists/assets/13919702/baec042d-0fe7-46ea-9b0e-182ad552573f)

**Comment by ReinerBforartists** [comment]
Both, tar and appimage works at ubuntu 23 \o/

![ubuntu23](https://github.com/Bforartists/Bforartists/assets/13919702/0405ed0f-675e-49cb-91b0-2d9fa1980474)

**Comment by ReinerBforartists** [comment]
I will close this issue now. The Debian 12 vm with the full setup to compile Bforartists can be found in the cloud in the shared folder. Password and user is as usual x.
