### ISSUE TITLE
Preference s - Viewport - Indend Playback Samples checkbox and slider

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3828]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d5bc431a-9e8c-4de2-bb6f-7f5e6313df9e)

Make the checkbox for the samples and slider indendet, and maybe with a label too. It makes little sense at the moment.

**Comment by Blenux** [comment]
Hows this?

Current


https://github.com/Bforartists/Bforartists/assets/25260650/c9cc8cf5-7d70-4f04-89d6-40f8f09f6118



Edited


https://github.com/Bforartists/Bforartists/assets/25260650/8aa78cdc-ffe5-43ea-b56e-5c753bdb3bce

**Comment by ReinerBforartists** [comment]
I would avoid the extra line, and simply put the slider behind the prop. Saves you also the need to indent the second line ...
