### ISSUE TITLE
Bforartists Window Title - Missing save status in the label

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3829]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/29671631-466c-4eb8-aa2f-5e38c1959c41)

It's.. currently gone. Something changed.

**Comment by Draise14** [comment]
Relevant clues:

> SHA-1: 636f3697ee7edcf75647a3094716026e24f03c48
> 
> * UI: Window Title With Version
> 
> Include blender version information in title (including cycle), and
> also indicate unsaved and dirty status better.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/111998

**Comment by Blenux** [comment]
This look good?

![Screenshot_20231004_125939](https://github.com/Bforartists/Bforartists/assets/25260650/8e5b3abf-b309-47c1-ae5d-7333a4c77400)

![Screenshot_20231004_130019](https://github.com/Bforartists/Bforartists/assets/25260650/630ed156-050d-4fab-81b2-32649f0f5a10)

**Comment by Blenux** [comment]
@Draise14 added branch to check if all good with you?

**Comment by Draise14** [comment]
Looking good! I'll check morrow morn - today was crazy.

**Comment by Draise14** [comment]
Yeah, it's now working like it does in Blender. 

I would have loved Bforartists title first (for task bar listing) then the file save state, but till then.. that will be another task. Atleast it's 1:1 with Blender now. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/034a55df-6bb4-463d-b1ce-66e1f96ea108)

**Comment by Draise14** [comment]
Merged to master
