### ISSUE TITLE
Preferences - Interface - Missing Search "Sort by Most Recent" toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3830]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/28d110f1-6794-4eab-b44b-e1ffe6822ffd)

Didn't bleed through with merge. So should double check. Then label 

<details>
<summary>Details</summary>

SHA-1: 836256394928e20dcaab19c3b6ef5c2c215596c0

* UI: show recently selected items at the top of searches

The goal is to make the search faster to use by dynamically adapting to the user.
This can be achieved using the simple but common approach of showing recently
selected items at the top. Note, that the "matching score" between the query and
each search item still has precedence when determining the order. So the last used
item is only at the top, if there is no other search item that matches the query better.

Besides making the search generally faster to use, my hope is that this can also
reduce the need for manually weighting search items in some places. This is
because while the ordering might not be perfect the first time, it will always be
once the user selected the element that should be at the top once.

This patch includes:
* Support for taking recent searches into account in string searching.
* Keep track of a global list of recent searches.
* Store recent searches on disk similar to recently opened files.
* A new setting in the user preferences that allows disabling the functionality.
  This can be used if deterministic key strokes are required, e.g. for automated tests.

In the future this could be improved in different ways:
* Add some kind of separator in the search list to indicate which elements are at
  the top because they have been used recently.
* Store the recent search items per search, instead of in a global list. This way
  it could adapt to the user even better.

Pull Request: https://projects.blender.org/blender/blender/pulls/110828

</details>

**Comment by Blenux** [comment]
Now there, best to close this?

![Screenshot_20231006_100640](https://github.com/Bforartists/Bforartists/assets/25260650/ec7097b1-010a-4fee-bae3-725a8c7e1cc7)

**Comment by Draise14** [comment]
Huh.... now it's back. Odd.

**Comment by ReinerBforartists** [comment]
I've fixed it with another task ;)

**Comment by ReinerBforartists** [comment]
Related: https://github.com/Bforartists/Bforartists/issues/3832
