### ISSUE TITLE
Splashscreen - Update buttons and links (to not go to Blender)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3831]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ceb7f65d-ed3a-4364-b408-3c4124bfe111)

Keep it inhouse.

**Comment by ReinerBforartists** [comment]
So throwing out the link? Okay ...

The other problem is already solved. It says Bforartists now ^^

**Comment by ReinerBforartists** [comment]
Documenting.

![splash](https://github.com/Bforartists/Bforartists/assets/13919702/a5c8cd76-6041-47c0-aab8-f5b1ec6fd181)

**Comment by ReinerBforartists** [comment]
Done
