### ISSUE TITLE
Preferences - local variabl 'col' referenced before assignment

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3832]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6936e1fa-8da9-4236-a7c7-aca7eb6bbbf9)

Found when using the "Save Preferences" operator. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/a236b53d-a280-4808-890a-cb126e6090eb)

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/a22d35ba-06a7-4c5d-87e9-dfb8f48ee8a0)

**Comment by ReinerBforartists** [comment]
Done
