### ISSUE TITLE
Default Theme - Selected Channel Group colour too bright

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3833]
![bforartists_vPasWTFjbS](https://github.com/Bforartists/Bforartists/assets/35357409/95d6c303-547c-426f-97ed-6d6e180c8c11)
Bone channel colours no-longer drive the channel name colour, kinda nice for legibility. It's a little square to the side now. I guess this will need documentation too. 

Change here:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/30010fb5-d61b-40f3-9145-ee9970263d8d)

<details>
<summary>Details</summary>

SHA-1: c524fbe62393bdaba6503e1317c009e66be0df66

* Anim: Improve readability of channel colors in channel list

Draw anim channel colors as a little rectangle in the channel list,
instead of taking over the entire channel name background. This keeps
the channel names readable, regardless of the channel colors.

Channel colors are typically set via the bone colors, and since those
are chosen for visual contrast in the 3D Viewport, they aren't
guaranteed to also be a suitable background color for the channel list.
Because of this, it's no longer used as such.

The channel 'data' background (i.e. the keyframe area) is now drawn with
a consistent color, and much more subtle.

This also enables the 'Channel Group Colors' setting in the preferences
by default, as it is now way less obnoxious and invasive.

Design task: https://projects.blender.org/blender/blender/issues/69059
Reviewed-On: https://projects.blender.org/blender/blender/pulls/112861

</details>

**Comment by ReinerBforartists** [comment]
What is the job here?

**Comment by Draise14** [comment]
Make the active colour on the green channel group less bright so it's not so white text on light green but a reasonable green.

**Comment by Draise14** [comment]
Commit to Master

**Comment by ReinerBforartists** [comment]
Um, i don't see changes at the \release\datafiles\userdef\userdef_default_theme.c file here. Did you forget to recreate the defaults?

**Comment by Draise14** [comment]
![Screenshot_20240113-064039-174](https://github.com/Bforartists/Bforartists/assets/35357409/4ad759e8-198b-4e2c-b6b5-2b8d54edd667)

It's there in the commit. Ran it twice and compiled twice to test. It's a small change.

**Comment by ReinerBforartists** [comment]
Thanks :)
I'm getting old ...
