### ISSUE TITLE
Default Theme - Add header background transparency (for legibility)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3834]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ae928a8e-f76f-4432-81b9-ccc16eda7faf)

Alot of the header props are floating on.. nothing - with a lot going on it becomes hard to see what the rows are. They added the ability to make it.. kinda nicer. 

Let's make it at least the same transparency of the tabs backgrounds. This will make it easier to see the button rows, know it's a HUD for the 3D View and.. easier to read the light buttons and text on dark background.  

<details>
<summary>Details</summary>

SHA-1: 73460903fa94bc2302bbd39efdd8cc554447d642

* Asset Shelf: Transparent asset shelf header with background for buttons

Draw the background of the asset shelf header fully transparent, with an opaque
background with rounded corners behind sections containing buttons. This
reduces the visual space consumed by the asset shelf, and makes the header
follow a tabbed folder metaphor better. Also, this works much better with our
click-through feature, where transparent parts of regions without buttons are
passed through the region under it (we might want to consider unifying code
here a bit).

The edge to drag for region resizing respects the transparent sections.
When there is little space between sections, the sections get merged so that
there are no small gaps in the bar.

Part of #107881.

----

Note that the core of this is implemented in a generic way, so this can be
reused for other regions.

Pull Request: https://projects.blender.org/blender/blender/pulls/112241

</details>

<details>
<summary>Details</summary>

SHA-1: 55eaa755e3fcb0b9cb3417afee6f3e65b2c43d7b

* UI: Draw 3D view tools header transparent with background behind buttons

Makes use of the new buttons sections feature used by the asset shelf to
draw a background behind buttons, but the reset of the region fully
transparent. The UI team agreed on this as a way to minimize dead space,
but also as a better way to communicate our click through feature (where
dead space in overlapping regions forwards events to the underlying
region). The region background theme setting only affects the
non-transparent part of the region, the rest is always fully
transparent. With region overlap disabled, the bar is fully opaque still.

Also see #112241.

</details>

**Comment by ReinerBforartists** [comment]
I am not really happy with making the header areas semi transparent again. We loose a part of the viewport area this way. I like the full transparency more.

**Comment by Draise14** [comment]
I've been working a lot without it then with it. Over time with full render views,  it is less searching for target hit in the header background areas when mostly opaque. The header is already taking viewport space with the content. The parts that have no buttons or header entries are 100% transparent now anyway. 

Could be transparent background as an opt-out. I vote for legibility here over a small amount of realestate area gain.

**Comment by ReinerBforartists** [comment]
Okay. Just don't make it full opaque :)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d46baa23-c8cd-4d20-9bd5-46a62bffab28)

Another though, also makes it feel.. consistent with the toolshelf method of header coloring. Will compile and commit now.

**Comment by Draise14** [comment]
Commit to master

**Comment by ReinerBforartists** [comment]
I would give it a bit more transparency if possible. But yeah, difficult ...

**Comment by Draise14** [comment]
It's s running at the same transparency of the tabs background area. 80%. 

I guess we could drop both to 60%?

**Comment by ReinerBforartists** [comment]
Ah, right, this is connected to the tabs background. Then better leave it as is for a consistent look. I will get used to it ^^
