### ISSUE TITLE
Properties Editor - Modifiers/Tools - Unassigned needs better iconography and name

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3836]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e58dfad6-9610-44a6-9abc-276a31804db7)

Right now a marked asset with no category has no icon (we have these marked assets with the node group icon)

The folder also has an icon.. which I like, but for consistency we should remove.

**Comment by Blenux** [comment]
This a duplicated in https://github.com/Bforartists/Bforartists/issues/3837 ?

**Comment by ReinerBforartists** [comment]
No, the one task is a rename, this here is missing icon.

**Comment by Blenux** [comment]
Oh I see now 😅

**Comment by Draise14** [comment]
Got regressed from last merge, slipped into official release.

**Comment by Draise14** [comment]
Ah.. it's a different state. Will commit none-theless.

**Comment by Draise14** [comment]
![bforartists_9VGrKNRHZO](https://github.com/Bforartists/Bforartists/assets/35357409/978be73b-9c22-4585-ab09-f8eee0684d3a)

Missed one.
