### ISSUE TITLE
Asset Browser + Property Editor - Modifiers - Add - Change "Unassigned" to "Uncatalogued"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3837]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/babc4b72-a7d7-496c-8cd9-bd81b7cd8a0f)
![bforartists_k04YTwmRoy](https://github.com/Bforartists/Bforartists/assets/35357409/8e79af9b-6e2e-44a2-a05f-795751457583)

"Uncatalogued" might also be more.. to the point. "Unassigned" where? To the stack? To the project? To the object? To the selection? What on earth is it unassigned to? 

It's about the Asset Browser assets and the catalogues, we should make a connection to catalogues linguistically.

**Comment by ReinerBforartists** [comment]
Mh, we should stay close to the blender naming convention if even possible. So i would prefer something  like unassigned (catalogue) instead. Or uinassigned (group).

**Comment by Blenux** [comment]
I like Uncatalogued also, but keeping consistent to Blender is good also 🤔

![options](https://github.com/Bforartists/Bforartists/assets/25260650/d26b8cbb-5d30-4ac1-afc3-20710e307cdf)

also this needs to be to the Geometry Add Menu also no?

https://github.com/Bforartists/Bforartists/assets/25260650/15ed7997-6f03-4c29-bf28-59100f519ebd

**Comment by Draise14** [comment]
"Unassigned (Catalogue)" hits the best of both worlds. Good call.
