### ISSUE TITLE
Geometry Nodes - Group - Properties - Modifier and Tool better tooltips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3839]
![bforartists_AN7Hhc2oim](https://github.com/Bforartists/Bforartists/assets/35357409/75ab7648-8c31-472b-b7dd-b8a5080c6d38)

This tooltip has no mention that these are only relevant for marked nodegroups as assets.. NO MENTION. 

Improve the tooltip, and document. 

<details>
<summary>Details</summary>

SHA-1: af3461c387702b56f75201952125ec7c6c49df44

* Geometry Nodes: Require modifier tag for add menu, show non-assets

Any geometry node group with the "Is Modifier" tag is exposed in the add
modifier menu. Local node groups that aren't assets are displayed in a
subsection of the "Unassigned" menu, as they are "asset wannabees"
that function similarly but aren't shared to other files.

Only modifier node groups can be assigned to the geometry nodes
modifier. Because of this, existing node groups are versioned to have
the tag if they have a geometry output.

Internally, this means the operator that used to only handle node group
assets has to also add local geometry node groups. That change isn't
so large though. The other changes are just UI, or changes to the
node group property poll functions.

Note: For assets, saving the file to generate asset meta-data may be
necessary for the versioning to affect the add modifier menu.

Pull Request: https://projects.blender.org/blender/blender/pulls/112918

</details>

**Comment by ReinerBforartists** [comment]
... and put them left for gods sake ^^

**Comment by ReinerBforartists** [comment]
... and i am at searching again. @Draise14 , please, bigger screenshots ^^

**Comment by ReinerBforartists** [comment]
Fixed
![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/9c6ed824-f93a-42ba-a53c-add26bf7590d)
