### ISSUE TITLE
Sequencer - Retiming tool is changed to be act-once operators and removed from toolshelf...

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3840]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8f98a46f-00b6-4646-af03-f639217bce3e)

The old one was cool af, super intuitive with gizmos.... but alas. Now these work on all in selection. 

We could add icons, add to toolshelf, and.. document.. 

Bare in mind, the retiming tool is still modal..... ei.. could still be the same icon, same tool shelf button. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/cedca0ca-65cf-4214-bec3-3c28721a63ae)

*sigh*

<details>
<summary>Details</summary>

SHA-1: 86a0d0015ac7bb114cbc44a03dd6b422a5ac709f

* VSE: Improve retiming UI

Currently retiming is quite awkward, when you need to retime multiple
strips strips in sync. It is possible to use meta strips, but this is
still not great. This is resolved by implementing selection.

General changes:
Gizmos are removed, since they are designed to operate only on active
strip and don't support selection.
Transform operator code is implemented for retiming data, which allows
more sophisticated manipulation.
Instead of drawing marker-like symbols, keyframes are drawn to
represent retiming data. Retiming handles are now called keys. To have
consistent names, DNA structures have been renamed.
Retiming data is drawn on strip as overlay.

UI changes:
Retiming tool is removed. To edit retiming data, press Ctrl + R, select
a key and move it. When retiming is edited, retiming menu and
context menu shows more relevant features, like making transitions.
Strip and retiming key selection can not be combined. It is possible to
use box select operator to select keys, if any key is selected.
Otherwise strips are selected.
Adding retiming keys is possible with I shortcut or from menu.
Retiming keys are always drawn at strip left and right boundary. These
keys do not really exist until they are selected. This is to simplify
retiming of strips that are resized. These keys are called "fake keys"
in code.

API changes:
Functions, properties and types related to retiming handles are renamed
to retiming keys:
retiming_handle_add() -> retiming_key_add()
retiming_handle_move() -> retiming_key_move()
retiming_handle_remove() -> retiming_key_remove()
retiming_handles -> retiming_keys
RetimingHandle -> RetimingKey

Retiming editing "mode" is activated by setting `Sequence.show_retiming_keys`.

Pull Request: https://projects.blender.org/blender/blender/pulls/109044

</details>

**Comment by Draise14** [comment]
Happenstance need this now.

**Comment by ReinerBforartists** [comment]
Go Go Go !

The checkbox should imo be in the options ...

**Comment by Draise14** [comment]
It's not an option though.. more like a strip tool mode. 

Made progress:
![bforartists_awDSvnIN6N](https://github.com/Bforartists/Bforartists/assets/35357409/4f52fcbd-e334-4cb7-8366-6f13270c01d8)

The previous tool was this one - and I don't know what they are thinking to remove the toolshelf one. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ab9e644f-1e0e-4e01-88d6-61fdd98f1a55)

**Comment by ReinerBforartists** [comment]
Ah i see, more something for the header ...

**Comment by Draise14** [comment]
I have recently noticed.. this toggle only toggles the active trip "mode"... not all of them, so it's not an option nor an overlay. 

This is such a weird workflow.

**Comment by ReinerBforartists** [comment]
Sidebar maybe? There are more strip options ...

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f2a01810-fd0c-493e-aa1f-11563e5601fc)

Here? Or the Video Panel?

![image](https://github.com/Bforartists/Bforartists/assets/35357409/ab03ab31-c4b3-45d5-be1a-ccaa3ecc9a1e)

I feel the toggle is disconnect in the property shelf for the tool workflow - though it is a state of the strip to use the tools.... It would make sense and be consistent that it is a strip "property". 

General UX logic
1. Opt-In retime state to retime the strip on selection
2. Use the retime tools
3. Opt-out if not needed

Gui Location logic with two retiming areas:
1. Opt-in in the time properties panel
2. Go to retime tools in header or toolshelf 
3. Use the retime tools in the header or toolshelf
4. Go to time properties panel
5. Opt-out if not needed from the time properties panel

OR

1. Opt-in in the tool header or toolshelf (blender design)
2. Use the retime tools in the header or toolshelf
3. Opt-out if not needed from the time properties panel

I think they desinged it the latter way - but it's not consistent and somewhat not logical.

**Comment by Draise14** [comment]
**Question:**
- This is a button that does the toggle, ei.. an operator. It is not a prop checkbox. 

Would a button with the icon change look alright like this in the panel? 
![bforartists_ONuzNc595c](https://github.com/Bforartists/Bforartists/assets/35357409/47340e9a-6e5d-4f6b-b3b3-0007cd9ebebe)

**Comment by ReinerBforartists** [comment]
Would indeed look better

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/637e7d5c-679d-4412-a419-d1508e728f7f)

Added a better title for it too. 

Since this is an operator with button, instead of a property - maybe it does make sense to keep it in the header/toolshelf. They added a "checkmark" to pretend it's a property, but it's not really in the UX.

**Comment by Draise14** [comment]
I think moving that button is out of scope of this task, so I will make a new icon then commit. 

Update:
- Conditional to show that it only works on selected movie strips added
- Retiming Panel in Toolshelf added + conditional when key is selected
- Icons added to majority (one new one pending)

**Comment by ReinerBforartists** [comment]
Yeah, don't even try to fix everything at once :)

**Comment by Draise14** [comment]
And documented.

**Comment by Draise14** [comment]
Commit to branch, branch merged to master

**Comment by Draise14** [comment]
Oops, forgot retiming also works on image sequences.

**Comment by Draise14** [comment]
Hit a regression on the UX. Should hide these operators if not a movie or image strip.
