### ISSUE TITLE
PoseBone.bone_group missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3841]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8b9ecfd0-4a02-4bbe-91d6-2bd7744fab70)

This has been removed or replaced by the collection equivalent. There is a remnant to smoke out.

**Comment by ReinerBforartists** [comment]
Prop is deprecated and removed without replacement. Removing.

**Comment by ReinerBforartists** [comment]
The interesting part is to find this in the ui ...

**Comment by ReinerBforartists** [comment]
Searching for the panel for documentation ...

**Comment by ReinerBforartists** [comment]
Hmm, it is this panel. But relative parenting is at the end now. In Blender and previous version it is at the top.

![alreadyfixed](https://github.com/Bforartists/Bforartists/assets/13919702/31ae4dac-31b1-45f9-848e-12ebbe27ae91)

**Comment by ReinerBforartists** [comment]
Gotcha.
