### ISSUE TITLE
Current master not compiling

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3842]
I get an error at compiling from scratch. And cannot compile Bforartists.

![notcompiling](https://github.com/Bforartists/Bforartists/assets/13919702/01e79eb9-8ac8-417b-b161-49e3c8a1c21e)

**Comment by ReinerBforartists** [comment]
Hm, just dead ends. No idea where the problem resides.

**Comment by ReinerBforartists** [comment]
Ah, this magic again. 

I guess i should not give my cpu 120% work to do ... ^^

![notcompiling](https://github.com/Bforartists/Bforartists/assets/13919702/d5cd94eb-1253-418c-9964-57d82595588d)

**Comment by ReinerBforartists** [comment]
This one strikes back at compiling the windows devbuild. Something is odd here.

![bug](https://github.com/Bforartists/Bforartists/assets/13919702/60f1c522-a3be-4164-b0d5-e5e5ee313b89)

**Comment by ReinerBforartists** [comment]
Hm, and also this time, compiling it again fixes the problem.

**Comment by ReinerBforartists** [comment]
And we are at the dead ends again. No idea what the problem is ...


![animchannelgroup](https://github.com/Bforartists/Bforartists/assets/13919702/1969b6b1-d827-421a-8fed-369dd50cdef6)

**Comment by ReinerBforartists** [comment]
Linux version compiles. Now go figure ...

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/843d73e4-7472-477b-82e7-de7635e03d25)

Ok, now I see it. I assume it's the group colours for the anim_channels of some kind. It compiled though....

**Comment by ReinerBforartists** [comment]
Yeah, it remains curious.

I've compiled now manually with VS, and it did hang at Hip then. Turning it off did let it succeed then. I guess it's because it still links to the version in the libs. Buit i have installed HIP with the installer now. Will investigate again in the evening.

**Comment by Draise14** [comment]
I have yet to update HIP too.

**Comment by ReinerBforartists** [comment]
Hm, the advice at the Blender Wiki did not work for me. But i have to test it again on a new make.

Either way, this is the new hip path for the hip executable. Still compiling. And this time without errors.

And by the way, it seems that hip will be deprecated soon ....

![hippathnew](https://github.com/Bforartists/Bforartists/assets/13919702/779c3193-b8af-4c65-9e1a-c5638bd22263)
![variable](https://github.com/Bforartists/Bforartists/assets/139197
![deprecatedwarning](https://github.com/Bforartists/Bforartists/assets/13919702/fffe2fa4-4f5c-4ede-ac4e-35f40dc5a656)
02/9c3b124e-3a40-41f5-854f-acc5417d4402)

**Comment by Draise14** [comment]
Those particular errors I am not getting... I'll try a scratch build morrow too.

**Comment by ReinerBforartists** [comment]
This was done with a simple make

**Comment by ReinerBforartists** [comment]
Sheesh, it's getting worse. This one was already compiling ...
![troubled](https://github.com/Bforartists/Bforartists/assets/13919702/5336b243-353c-420c-9f63-5e0d73ed1d33)

**Comment by ReinerBforartists** [comment]
Can it be that they changed the way how to store the state of this flag? We have added it to the rna_define.cc file to have it on by default. I'll test to remove it, and activate it by the startup.blend

**Comment by ReinerBforartists** [comment]
Okay, when i understand the code right then the default is already on. Which makes our change obsolete. Testing.

![value](https://github.com/Bforartists/Bforartists/assets/13919702/77231d7b-949c-4fe4-b6ab-5b3288eaee8c)

![default](https://github.com/Bforartists/Bforartists/assets/13919702/3726e7f2-2703-410c-bc71-0166175e9f94)

**Comment by ReinerBforartists** [comment]
That was indeed it. Not that i know where this state is now stored :D

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/dd4fc3a6-bb6c-48a1-8be1-560ce1f5cd89)
