### ISSUE TITLE
Theming problem in preferences

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3844]
Blender theming is bleeding through down left.

![themingproblem](https://github.com/Bforartists/Bforartists/assets/13919702/20543f44-f14a-475f-b406-c5097f633c64)

**Comment by ReinerBforartists** [comment]
I'll reopen this. Our grey area is back :D

Seems that the step to change this color gots lost in the process.

![greyarea](https://github.com/Bforartists/Bforartists/assets/13919702/e7453f23-33ba-46dd-914e-1954934f74e9)

**Comment by ReinerBforartists** [comment]
Might be a good idea to also have a look for this black background in the adress line ...

![black](https://github.com/Bforartists/Bforartists/assets/13919702/835dd0dc-e444-4eba-92d4-23e5f8af1809)

**Comment by Blenux** [comment]
Ah shoot I did notice that file manager one, also can't seem to compile on master atm 😅 (testing clean build for this theme issue)

**Comment by ReinerBforartists** [comment]
The not compiling issue should be fixed. Just pull 

Was this issue: https://github.com/Bforartists/Bforartists/issues/3842

**Comment by Blenux** [comment]
ok pulled and don't get the issue here, only way I can recreate is only if loading previous preferences?

**Comment by ReinerBforartists** [comment]
Hmm, now the preferences looks fine. No idea what went crazy at my end then. Sorry for the false alarm.

I guess we can also make a new issue for the file browser problem then.
