### ISSUE TITLE
When a path is pasted in the "name" field of "Browse for file" window, the backslash (\) gets converted into underscore (_)

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#3848]
**Describe the bug**

When importing a file, we have to browse to the file and then click on it.
But if the file is located deep in a large+complex folder system, this becomes tedious.
It is far easier if we already know the complete path of the file.
We can simply paste it in the "Browse for file" window and press ENTER to complete the job. 

Indeed, this method works in the top field of the "Browse..." window.
But it does NOT work if we paste the complete path of a file in the "Name" field.
Instead of loading the file, B4A converts each instance of backslash (\) into underscore (_).

For example,
D:\HELP DOCS\STP guide\Sketchup models\
becomes-
D__HELP DOCS_STP guide_Sketchup models_

And then we are stuck.

**Desktop (please complete the following information):**
Win 11, Home (64 bits)
Acer Aspire A315-53 with i3, 12 GB RAM
Intel UHD Graphics 620

**Screenshots, Example Files**

A sample screenshot is shown below:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/478d01c3-90f8-4337-94b3-8474a1898bb2)

Here, I copied the path from the top and pasted it in the "Name" field at the bottom.
(Note: This was to illustrate the issue. In practice, I'd have the complete path of the file, including the filename and extension.)

If I press ENTER, I expect the file to be accepted.
Instead, in the pasted path, every instance of backslash (\) character gets converted into underscore (_).
Now this path is unreadable, and B4A cannot import the file.

**Comment by ReinerBforartists** [comment]
Many thanks for the report. This is most likely a bug that should be reported directly to Blender in case it is reproduceable there too. I'll have a look.

**Comment by ReinerBforartists** [comment]
I cannot reproduce the issue, sorry. I have even installed the sketchup importer. But can still not reproduce the problem. Not in Blender not in Bforartists. It could have something to do with your system.

Could you test if this also happens in Blender please? If so, then please report it to Blender directly.

**Comment by Draise14** [comment]
Ah, the file name is not the same as the path name. File names cannot contain slashes. If you want to navigate to the path, you use the path entry box at the top, then input the file name the file at the bottom.

Unlike the OS user experience, the file browser **_cannot_** navigate to folder from the file name entry box. This would be a feature request for Blender directly.

**Comment by ReinerBforartists** [comment]
Ah good catch. Didn't even thought about it :D
It remains curious though, since i did not have a problem to paste the whole path into the name field. The slashes remained.

**Comment by raindropsfromsky** [comment]
I am getting the same result with Blender 4.0 Alpha (the backslash gets converted into underscore). I am using Windows 11 Home.

BTW, this happens with any browsing window (nothing to do with importing skp files).
For example, it also happens in the browsing window you get when you use the **File > Open...** menu option.
(The only difference is that you paste the full path of a blend file. But here also, you'' face the same issue.)

**Comment by ReinerBforartists** [comment]
Then i would highly suggest to report it to Blender. They are better suited to fix this kind of bugs.

I just have Windows 10, and it might be a windows 11 thing, or also a local settings thing.
