### ISSUE TITLE
3D View - missing Manipulator Pie gui entry

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3852]
![bforartists_u9MJH82yLf](https://github.com/Bforartists/Bforartists/assets/35357409/c862dfb9-c5cf-44aa-9a72-cb27ed80b187)
![bforartists_BWZbBfR0GR](https://github.com/Bforartists/Bforartists/assets/35357409/ba80e743-9824-4cf9-a123-4ff1dcf0fb64)
![msedge_RqHHKfUGYD](https://github.com/Bforartists/Bforartists/assets/35357409/df55b1bc-2177-4f37-bb0c-8c4079dbe3fe)

Hotkey only pie is not listed in the Pie Menu area of the 3D View. This pie menu is the Manipulator menu. Also missing icons. 

Hotkey `ALT+SPACE`

**Comment by Blenux** [comment]
Is Transform (Alt R) not the same?

![Screenshot_20231007_164524](https://github.com/Bforartists/Bforartists/assets/25260650/86dd715e-5f0e-421f-bef0-ff013f167348)

Still no icon besides the one :thinking:

**Comment by ReinerBforartists** [comment]
I think we never cared for icons in the pie menus really.

**Comment by ReinerBforartists** [comment]
Made it a task 
Iconize Pie Menus #3855

**Comment by ReinerBforartists** [comment]
Task is invalid. This pie menu is not part of Bforartists and also not of Blender. It comes most likely from an addon.

Closing.
