### ISSUE TITLE
Iconize Pie Menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3855]
Every nearly pie menu has missing icons or no icons at all. Can be improved in all editors.

![missingicons](https://github.com/Bforartists/Bforartists/assets/13919702/e00db5cd-1304-4562-9c15-6068fd05048c)

**Comment by Blenux** [comment]
What about ones with checkboxs?

![Screenshot_20231009_162738](https://github.com/Bforartists/Bforartists/assets/25260650/19479119-dde1-4a80-867b-3f78b9ac5d35)

**Comment by ReinerBforartists** [comment]
I think icons would just confuse here. It's options, not operators.

**Comment by Draise14** [comment]
These seems to be mostly from the pie addon we have on per default? So I assume it's coming in from there. Will edit that. Are there any pie  menus built in?

**Comment by ReinerBforartists** [comment]
Phew, good question. I have no idea ^^

**Comment by Draise14** [comment]
Nearly done, testing

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/525ad8cb-8a85-47d2-9682-7a190a316672)

Done.

**Comment by Draise14** [comment]
Heads up @iyadahmed , the addon also got better pie menu icons. I tried to add comments absolutely everywhere, but do keep an eye out in future merges.
