### ISSUE TITLE
3D View - Armature - Pose/Edit mode - Move to Collection submenu iconography and order for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3878]
![bforartists_Utp7ALcf6f](https://github.com/Bforartists/Bforartists/assets/35357409/fe93400e-6a83-4e86-af9f-f619be584a99)

Lacking.. iconography. Already documented, small update. 

Should be somewhat consistent with the move to collection menu. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/bdcfda3b-7701-4460-a6f3-6f2563212c6d)

**Comment by Draise14** [comment]
Bit complex for me, will have to save this for later.

**Comment by Blenux** [comment]
Working on this, have got this far, just need to work out the separator :thinking: 

![Screenshot_20231013_150613](https://github.com/Bforartists/Bforartists/assets/25260650/db40f797-e34a-49fa-8c22-5b9ee17dccf3)

**Comment by Blenux** [comment]
Done :smile: 

![Screenshot_20231013_155933](https://github.com/Bforartists/Bforartists/assets/25260650/0052ac85-ac88-4b44-904f-48d2cf787f1f)

**Comment by Blenux** [comment]
Suggest a bone collection icon :smile: 

![Screenshot_20231013_160557](https://github.com/Bforartists/Bforartists/assets/25260650/3d55facb-21f6-425d-a5c6-99c9bd3eea81)

**Comment by Draise14** [comment]
Actually... good idea. Instead of the group and collection mixes. Another task for another day.
