### ISSUE TITLE
Sequencer - Sidebar - Show Retiming Keys Property float left / Or Hide (redundant)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3881]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a48d86c3-cc02-4076-93e7-acad8168b337)

Ok.. they decided it's a prop now. Damn. Document needs updating too. 

Now the button in the retiming sub-menu /tabbed toolshelf is... somewhat redundant? Though I consider it a nice UX similar to what it used to be. 

Also, they code removed the conditional, any strip can have this toggled but they don't show. It's broken... before I had it working on type of selection. But for some reason it stopped working.

**Comment by Draise14** [comment]
Could make it conditional like the tools on MOVIE and IMAGE strips - or else.. it simply makes no sense. You can't retime audio.

**Comment by ReinerBforartists** [comment]
Ah, UI elements dancing around <3

**Comment by ReinerBforartists** [comment]
And i would wait, maybe they find a way to retime audio too ..

**Comment by Draise14** [comment]
This prop doesn't hide for any strip type, you can toggle them even on effect strips, colour strips, fade strips.. it makes no sense. It's a ghost prop for all strip types other than IMAGE and MOVIE. 

I have code that can "show" when a strip can technically re-time, so adding in AUDIO if they ever add that won't be an issue and can be done when they allow that.

**Comment by ReinerBforartists** [comment]
Okay :)

**Comment by Draise14** [comment]
Progress from Blender devs...

<details><summary>Details</summary>
<p>

SHA-1: 01b617a3c6ebc0fc1a80d39916c78cbedd8f095d

* VSE: remove speed_factor RNA property from sound strips

Property `speed_factor` was used before retiming. It was kept for
potential versioning code for complex speed animation, that was
possible with even older `pitch` property.

Strips, where `speed_factor` is set to static value are already
correctly converted.

Such versioning code would be quite complex, possibly slow and maybe
could corrupt files. This is due to multiple factors:
- Sound seeking was broken, so conversion would have to ignore all
  keyframes before strip starts to map frames properly.
- Because some animation was effectively ignored, it may cause
  inconsistencies when doing conversion.
- It would have to integrate value of `speed_factor` to map keyframes
  to strip space, but the animation is not limited to strip length.
- For each keyframe where speed gradually changes, at least one smooth
  speed transition would be required, but there would be discrepancies
  that would have to be accounted for. With simpler strategy it is
  likely, that extent of ramps would be limited and thus animation would
  be quite different from original.

Because of these reasons, I think it is best to not convert
`speed_factor` animation.

Pull Request: https://projects.blender.org/blender/blender/pulls/114295


</p>
</details>

**Comment by ReinerBforartists** [comment]
:)

**Comment by Draise14** [comment]
Documenting.

**Comment by Draise14** [comment]
![bforartists_WNF1TLuQoH](https://github.com/Bforartists/Bforartists/assets/35357409/0efdb71b-cd54-461b-810d-45449c19a282)

Commit to master

**Comment by Draise14** [comment]
Documented
