### ISSUE TITLE
v4.1 fails to launch (several dll files are missing)

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#3888]
**Describe the bug**
I got the b4A alpha dated 13th Oct.
But it cannot be launched.

Four error messages pop up one after another, and then launching quits.
All the four messages are the same: 

System Error
The code execution cannot proceed because <dll name> was not found. 
Reinstalling the program may fix this problem.

The missing files are as follows:
embree4_d.dll
cycle6d.dll
MSVCP140D.dll
VCRUNTlME140D.dll

I reinstalled but this has not solved the problem.

**Desktop (please complete the following information):**
Win 11 Home

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment]
Many thanks for the report. I will look into it.

**Comment by ReinerBforartists** [comment]
I could swear i had tested it, but it is indeed broken. Let's compile it again ...

**Comment by ReinerBforartists** [comment]
New version is up. This time i have triple checked. Please test.

**Comment by raindropsfromsky** [comment]
B4A gets launched now, but the **EEVEE Next** is missing from the render engine drop-down!
(Blender 4.1 has both EEVEE and EEVEE Next.)

![image](https://github.com/Bforartists/Bforartists/assets/9047168/bb40068c-83af-4305-87ed-7aa63ed06ede)

Secondly, the download page says 
The current development build is based on Blender 4.0 Alpha !

Since 4.1 has a radically new component (EEVEE Next), the download page should point out this exciting new feature!

**Comment by ReinerBforartists** [comment]
Good hint. Thank you. Will change it. And thank you for checking.

I haven't followed if Eevee next was out of experimental for a while. But Eevee next is currently experimental. You have to activate it in the preferences.

![experimental](https://github.com/Bforartists/Bforartists/assets/13919702/6900a103-5f64-43ab-aec8-14ec0eb7c723)

**Comment by raindropsfromsky** [comment]
oh!

Well, Blender 4.1 Alpha does not need such activation.
The EEVEE Next is accessible out of the box (and that's the whole point of 4.1 release!)
 
So I didn't think of activating EEVEE Next in B4A either!

BTW EEVEE Next almost crashes the system (cannot do anything after selecting it).
I saw this in Blender as well.
So it may as well remain buried for now!

**Comment by ReinerBforartists** [comment]
We are always one week behind, maybe the next merge will put it out of experimental, i don't know :)
