### ISSUE TITLE
Geometry nodes sidebar - Group Tab - Interface panel - same tooltip for the add buttons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3891]
We have three new add buttons here. But they all show the same tooltip. This should be improved if possible.

![split](https://github.com/Bforartists/Bforartists/assets/13919702/b35e684d-1b98-44ce-838a-9b9754f5c168)

**Comment by Blenux** [comment]
Good or what's a better Label and description?

![add_input](https://github.com/Bforartists/Bforartists/assets/25260650/950a8867-ea79-49f6-8b4f-2d543f5a0b8a)
![add_panel](https://github.com/Bforartists/Bforartists/assets/25260650/a191abea-147c-4df3-867d-a41cd7db3fe9)
![add_output](https://github.com/Bforartists/Bforartists/assets/25260650/df192f4d-8e62-44ef-a25c-5a15baacf95d)

**Comment by ReinerBforartists** [comment]
Yeah, looks great :)
