### ISSUE TITLE
Geometry nodes sidebar - Group Tab - Interface panel - Horizontal row for add buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3892]
# Suggestion Ideas
![bforartists_j5Zdie7eIp](https://github.com/Bforartists/Bforartists/assets/35357409/81125b76-f10a-4900-ac6f-6c4d75aca8fd)
![bforartists_tYi5wnz6wU](https://github.com/Bforartists/Bforartists/assets/35357409/6a493b46-35de-40df-9ee7-53569917c27a)
![bforartists_Ut0VtK6qNU](https://github.com/Bforartists/Bforartists/assets/35357409/d7803f84-c2cf-4e11-bc0f-a75b48122f68)

Create a horizontal add box

**Benefits:**
- Shows the column labels for the 3 things in the list
- Doubles as convenient top level add buttons, consistent with all list add buttons being a top level
- Allows room for other buttons in the vertical sidebar for future move up/down buttons or secondary drop down. 
- Is more convenient than having a drop down to add items

# Issue
According to discussion here in #3889, we are not sure about the vertical add buttons exposed to a top level. 

Blender has an inconsistent and inconvenient way to have the add buttons for the list now in a sub-menu. For large trees you go to the button, drop down, click, go to the button, drop down, click, go to the button, drop down, click. 

We rectified it to a vertical column here thank to Juso, but it's somewhat disconnect still, and crowding the side. 

In blender we have an the drop down menu, which... is not convenient nor consistent with other list UX. 
![275259256-ff52b4a3-95ce-4e18-a49e-a44797b6cb84](https://github.com/Bforartists/Bforartists/assets/35357409/d8bf8a50-e1c3-4484-8576-38fa201db40d)

## Challenges
- Make it visually connect to the add/remove group of buttons. 

### Ideas
Instead of at the top, we can have it at the bottom of the list like we would with other list that have add buttons like the Bone Collection list, or vertex group lists. Top level and Consistency is the best UX imo.

**Comment by ReinerBforartists** [comment]
It's a two sided sword. Top Level UI entries crowds the UI. We have ways too much already for my flavour. And you don't add new inputs every three seconds. So i understand where Blender devs are coming from.

**Comment by Draise14** [comment]
Bforartists is not famous for being non-crowded, and it's not a GUI target we try do from what I've learnt over the years. Yes, we hide and indicate disabled sliders and props, and remove redundant repeat operators unless it's opt-in - but minimism in the GUI is not the name of the Bforartist game. It's usability. 

Working with node groups all the time, and knowing the community I mod in Erindales discord server with node groups, this will repeat adding behaviour will eventually irk people.

**Comment by Draise14** [comment]
Let's do a UX theory:

1. You build your tree as a shader artist or tech artist for a toolset in a project, you gotta make the asset. 
2. You have the tree working, now you're grouping it up and building the panels to either ship it or use it. 
3. You then need to make 4 panels, with over 10 properties. You're going to do this in one sitting
4. You hit the drop down, mouse over, select, drop down, mouse over, select, drop down, mouse over select. 14 times over and over within seconds of each other. 

5. Or you use accelerator hotkeys or quick menu selection... which is an extra step to prepare for that workflow either way (open menu, hotkey, open menu, hotkey). 

VS 

4. You hit the relevant column button in the footer or header, mouse over hit, mouse over, hit, mouse over hit. 

_The latter, top level.. even with accelerator and quick menu customization, is 50% faster as a UX when it comes to making the node group panel._

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/eeffdb48-5598-4462-acb5-d056da12cc22)

The alternative is make a box with an + label to hold the vertical add buttons together and keep them connected visually but still to the side.

**Comment by ReinerBforartists** [comment]
Yeah, a show hide button would be an idea. But then you have a show hide button too. One more element ...

Mh, there is an alternative to the menu from Blender here. A panel stays open as long as the mouse is over it :)

**Comment by Draise14** [comment]
![blender_7S090sgzbH](https://github.com/Bforartists/Bforartists/assets/35357409/b47cfe06-8f1e-4335-ad15-23a03d19e654)
Till you click.

**Comment by ReinerBforartists** [comment]
You show the menu behaviour from Blender here. I talk about a panel. And a panel stays open.

> Bforartists is not famous for being non-crowded, and it's not a GUI target we try do from what I've learnt over the years. Yes, we hide and indicate disabled sliders and props, and remove redundant repeat operators unless it's opt-in, and minimize the hotkeys - but minimism in the GUI is not the name of the Bforartist game. It's usability.
> 
> Working with node groups all the time, and knowing the community I mod in Erindales discord server with node groups, this repeat adding behaviour will eventually irk people.

Just wanted to answer this one. 

One of the goals of Bforartists UI UX design is to hide away what is not so often needed. To make the UI easy to discover. I know that you tend to put everything top UI. but Usability includes both. We win exactly nothing when we put all 2000+ operators top level UI. And we win exactly nothing when we hide them all away. It's about the balance to reach quickly what you use very often, and hide away the not so often used stuff so that you can easily reach the often used stuff.

Let me explain my approach how i decide if top level or not:

Using geometry nodes is a power feature. Used by maybe ten percent of all users. And this special feature here is even by power users not used this often that we talk about hours of extra work a day. More in the scope of a few dozen clicks every few days if even. It doesn't really disturb.

Having these menu items expanded though crowds the UI. This area is not so easy to discover anymore with one look. So in this particular case it's better to put these menu items into a panel. The panel has already a benefit compared to Blender. It stays open as long as you want to add something. And is the second best solution compared to expand everything by default.

**Comment by ReinerBforartists** [comment]
Let me have a look if i can add the panel here.

**Comment by ReinerBforartists** [comment]
Fixed. Documenting.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/a4ad9116-e9db-4cbf-a5dd-bd1e3ee70ad3)

**Comment by ReinerBforartists** [comment]
Fixed a whoopsie. Code formatting is important !
