### ISSUE TITLE
Missing Tooltip Title in (not only) Add menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3893]
We have a big regression here. The tooltip titles are missing in the add menu and a few other places. 

I remember a discussion about improvements regarding this. And that our code snippet was made dysfunctional. But cannot find the issue at the moment.

Either way, we need to make this code functional again it seems. Shot is from version 3.6.2

![missingtooltiptitle](https://github.com/Bforartists/Bforartists/assets/13919702/5a86c2b4-2397-41d9-bd23-deb591a98460)

**Comment by ReinerBforartists** [comment]
@Draise14 do you remember the issue? There was the code snippet linked ...

**Comment by ReinerBforartists** [comment]
Ah, here it is

https://github.com/Bforartists/Bforartists/issues/3790

**Comment by ReinerBforartists** [comment]
I think i found a way. The titles in the add menus are back. Please check and test. I hope it has no side effects like double titles. Haven't found any so far. Fingers crossed.


![titleisback](https://github.com/Bforartists/Bforartists/assets/13919702/8a259579-9e31-41e5-856d-dfe968f8caa1)

![addttitle1](https://github.com/Bforartists/Bforartists/assets/13919702/83b1e7b9-6891-4f71-8b85-039c8da5c662)

**Comment by ReinerBforartists** [comment]
Another proof of work

![backworking](https://github.com/Bforartists/Bforartists/assets/13919702/88555355-3975-4972-a4c7-2379a3238e80)

**Comment by iyadahmed** [comment]
This causes crash in asset editor

**Comment by ReinerBforartists** [comment]
:'3

**Comment by ReinerBforartists** [comment]
Thanks for checking. I can confirm the crash. This system is so crazy ...

**Comment by ReinerBforartists** [comment]
*sad cat noise*
![tooltipcrash](https://github.com/Bforartists/Bforartists/assets/13919702/31d395d4-2fba-4521-984a-4cbb92a32d0b)

**Comment by ReinerBforartists** [comment]
And what is the solution? O_O

**Comment by ReinerBforartists** [comment]
Ah i see. I would've never come up with this. Great job :)

**Comment by iyadahmed** [comment]
> Ah i see. I would've never come up with this. Great job :)

an I wasn't able to come up with your part ^^
the change was checking for null, because passing null to strdup crashes
