### ISSUE TITLE
BFA: use a map to map keying set IDs to icons

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3895]
Right now we use a finicky ugly two arrays solution acheive this
![image](https://github.com/Bforartists/Bforartists/assets/25552173/55c82981-049d-47f3-bf99-268ab50476b6)
![image](https://github.com/Bforartists/Bforartists/assets/25552173/e0e59bbf-7f7d-4417-baed-59da06e82fc9)

https://github.com/Bforartists/Bforartists/blob/6712faa73574d3ec9cdc6187e853d1c74c029a9a/source/blender/editors/animation/keyingsets.cc#L824

**Comment by iyadahmed** [comment]
> Isn't this a Blender task?

nope this our code that we added

**Comment by ReinerBforartists** [comment]
Every improvement is welcome :)
