### ISSUE TITLE
D for Grease Pencil and D for Focus Selection - conflict

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#39]
We had at one point mapped the center view key from Numpad 0 to D, since we thought this key is free. But we introduced a key conflict, since the D key is used for various grease pencil operations.

The key is already reverted to Numpad 0 in the Bforartists keymap. See here: https://github.com/Bforartists/Bforartists/commit/664a8ebe4ba1999a9cf0522cc4c5859568789555 and here: https://github.com/Bforartists/Bforartists/commit/ecd7055443373fad580fe6d4ddd8a5c94db6d95a

But not in the Full keymap, which is currently in development. So this part needs work.

**Comment by Draise14** [comment]
Not sure if I should close these, so just kept it as "Fixed"

**Comment by ReinerBforartists** [comment]
Don't you have a close and comment button down right of the text field? Hm. Then i'll close it :)

![closebutton](https://user-images.githubusercontent.com/13919702/37842471-86a7cebe-2ec2-11e8-88b7-08f420712d45.jpg)
