### ISSUE TITLE
Sculpt mode - double entry Auto-Masking

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3901]
Auto-masking in sculpt mode is now in the header. But also still in the sidebar. This is double.

I would suggest to remove the content in the Advanced panel.

![automaskingdouble](https://github.com/Bforartists/Bforartists/assets/13919702/f01bf267-0042-4464-b89e-cf3f77eea1f4)

**Comment by ReinerBforartists** [comment]
Not solveable by us. We have two different independent toolsets with independent operators here. And it is not clear which ones are now affecting the brush.

Reporting ...

![wichsetisactive](https://github.com/Bforartists/Bforartists/assets/13919702/2feff43a-31e6-414a-9a57-b629138e3fe5)

**Comment by ReinerBforartists** [comment]
Reported here: https://projects.blender.org/blender/blender/issues/114068

**Comment by ReinerBforartists** [comment]
Okay, the one in the header is global settings. And the per brush setting is per brush. But there is no way to switch to global settings from what i can see. The brush will always use the brush settings.

**Comment by ReinerBforartists** [comment]
This feature is around for much longer. Already exists in 3.6.2. And i cannot find the connected commit so far.

**Comment by ReinerBforartists** [comment]
Closed as works by design. And no answer to my question how this feature can be used.

**Comment by ReinerBforartists** [comment]
@Draise14 do you have an idea here? What is the trick to use the global settings instead of the local brush settings? What do i overlook here?

**Comment by Draise14** [comment]
Yeah. Tested:

1. Global Automasking overrides all brush advanced settings regardless
2. Bursh Automasking sets the advanced settings, so when global is off, it's advanced settings preserve 

**Example:**
1. I have a brush that paints over face set borders
2. I turn on the Global Automasking, now the face set borders are respected
3. I turn the Global Automasking off, now the brush paints over the border
4. Unless I turn on Face Set Automasking on the brush to store that behaviour in the brush. 

Facesets set
![bforartists_dUMFJBRySJ](https://github.com/Bforartists/Bforartists/assets/35357409/4cee67b3-f358-42e1-a049-52d7f634aeab)

Automask Facesets global on (or local advanced on)
![bforartists_6GrkHg3ErY](https://github.com/Bforartists/Bforartists/assets/35357409/674b88e7-c736-4e54-91eb-82fbb3b6e349)

Automasking Facesets off
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4140d45a-640b-422c-858e-ca55a0b42441)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1f0d41cf-5fe6-4412-bd0d-dbc733a4f04c)

Something like this... 

Gonna commit and document to avoid future confusion.

**Comment by ReinerBforartists** [comment]
Okay, and where do you turn on global?

**Comment by ReinerBforartists** [comment]
Woah i would have never thought of this :D

Many thanks. Remains the question if we should leave it as is or if we should improve here.

**Comment by Draise14** [comment]
Yeah, not a great UX at all, but hopefully the label helps. I'm documenting it now.

**Comment by Draise14** [comment]
![bforartists_ugtZmqmJKj](https://github.com/Bforartists/Bforartists/assets/35357409/24bdd739-8049-4d46-a787-7162674b431f)
![bforartists_NukW3FvBsQ](https://github.com/Bforartists/Bforartists/assets/35357409/a5831b1e-a9cd-4f7e-b150-cb0c137098d6)

Yeah, in python one is a scene level, the other is a brush level.

**Comment by ReinerBforartists** [comment]
Thanks. 

Hmm. We could add some info in the tooltip. Other than that i don't know how we could make it more obvious

**Comment by Draise14** [comment]
Both could help? Label and tooltip expansion?

**Comment by ReinerBforartists** [comment]
Lemme just check if tooltip is even possible or if it is the same.

Is this a one by one operator or does ticking any of the checkboxes override the defaults? And i still don't understand how this crazy system is meant to work. You might want to have a checkbox off instead of on ...

**Comment by ReinerBforartists** [comment]
One tooltip. And i don't see any way to separate it. Means a hint would also show in the tooltip of the local version.

Remains the solution with a info string in the panel. Suggestions?

**Comment by Draise14** [comment]
Yeah, the global checkbox would override any brush advanced checkbox. Let me make a mockup.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/7dad5daa-7af5-4b18-94c2-eefa6d902e35)

Something like this?

I noticed the hidden content was also inconsistent.

**Comment by Draise14** [comment]
Ok, made a branch with the mockup. 

**Done**
- Documented the Global Auto Masking (same Sidebar chapter)
- Added a note that it will override brush settings
- Added note icon
- Changed title of header drop down to "Global Auto Masking"
- Made the toggles consistent with hidden content

**Comment by Draise14** [comment]
Will let you review @ReinerBforartists, but code and documentation is good to go.

**Comment by ReinerBforartists** [comment]
I'm green with these changes. Please merge :)
