### ISSUE TITLE
Fix node editor background theming

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3912]
Just noticed that the background theming in the node editor is broken again. We had this nearly not to see dots problem before ...

![bgthemingbrokenagain](https://github.com/Bforartists/Bforartists/assets/13919702/27d1dac8-c888-4a72-8ab8-3379a1cd2464)

**Comment by ReinerBforartists** [comment]
Related: Update themes #3909

**Comment by ReinerBforartists** [comment]
I have no idea how we solved it the last time.

**Comment by ReinerBforartists** [comment]
Hmm. The dots are now smaller. And so they need to be brighter to be seen. I made them white here. Must be a change at the code base though, there is no setting to make the dots wider.

![brighter](https://github.com/Bforartists/Bforartists/assets/13919702/15448d12-4f53-48dd-9e41-37ab8718a1bc)

**Comment by ReinerBforartists** [comment]
@Draise14 , shall we make the theming brighter or shall i investigate here for the change? I like the bigger dots better ...

**Comment by ReinerBforartists** [comment]
Unassigning

**Comment by Draise14** [comment]
Now looking at this. Preferred the larger dots yeah. White here could be done. How is the scale of the dots defined in the repo?

**Comment by ReinerBforartists** [comment]
I have no idea. All i know is that it changed in the two weeks before i did the merge. So going through the logs could help. Or comparing the code base.

**Comment by Blenux** [comment]
This should help :D

https://projects.blender.org/blender/blender/pulls/111640/files

**Comment by ReinerBforartists** [comment]
Let's have a look if this helps. Many thanks :)

**Comment by ReinerBforartists** [comment]
Close enough i would say. The small dots are not as nice visible as with the old method. But it looks okish now for me.

![asclose](https://github.com/Bforartists/Bforartists/assets/13919702/2fecd3e8-ca8e-473f-b715-67a94ca1bfe8)

**Comment by ReinerBforartists** [comment]
Fixed in master
