### ISSUE TITLE
VSE with color strip -  align multiply alpha prop left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3914]
New prop, needs left alignment, and then documentation !

![vsealignleft](https://github.com/Bforartists/Bforartists/assets/13919702/9c574744-99fd-47fa-914b-4b2e63dac8c3)

**Comment by Draise14** [comment]
Documenting...

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/103a1074-3b5b-477e-afe3-c6a33fa4fad6)

Commit to master

**Comment by Draise14** [comment]
Documented.
