### ISSUE TITLE
In quad view, view controls' tips appear in wrong view

### ISSUE THREAD

**Issue by UndeadBee42** [Bforartists/Bforartists#3921]
**Describe the bug**
In view controls' tips appear in wrong view

**Desktop (please complete the following information):**
The Operating system. Windows 10, Nvidia 

**Screenshots, Example Files**

![Screenshot 2023-11-04 03-14-56](https://github.com/Bforartists/Bforartists/assets/55995165/488172b7-01ed-40b5-986b-174bafd79bb7)
![Screenshot 2023-11-04 03-14-58](https://github.com/Bforartists/Bforartists/assets/55995165/d913de67-5fd1-4179-b7cd-00a39f37dd25)
![Screenshot 2023-11-04 03-15-56](https://github.com/Bforartists/Bforartists/assets/55995165/e5e2187e-66fd-4689-aa9f-9a627395e57d)

**Comment by ReinerBforartists** [comment]
Cool catch. Many thanks for the report. This happens in Blender too, so it is best reported to the Blender developers. May i ask you for the favour to do so? We are a bit overloaded at the moment with Blender and Bforartists 4 around the corner ... :)

**Comment by UndeadBee42** [comment]
blender require creation of account on their git thing. This is ridiculous and i refuse to do so. hopefully someone else will file a bug report

**Comment by ReinerBforartists** [comment]
Reported it here: https://projects.blender.org/blender/blender/issues/114620

**Comment by ReinerBforartists** [comment]
Ah, issue already exists here. https://projects.blender.org/blender/blender/issues/87390

**Comment by ReinerBforartists** [comment]
I guess that's all we can do here. Closing.
