### ISSUE TITLE
Tooltip should appear when the mouse is hovered on ANY label, regardless of whether it has an attached control or not

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#3922]
**Describe the bug**
BFA shows extended tooltips only when we hover on all controls 
(Here, a "control" means any "click-and-act" element, such as a checkbox, spinner, drop-down list, toolbar button, widget, input box, etc.)
 
But these extended tooltips are not provided for section header labels.

As a result, we do not get a summary tip about what the overall section is supposed to do.
We only get an idea about what its individual controls can do.
But we have to only guess what the section is supposed to achieve on the whole.

**Desktop (please complete the following information):**
Windows 11 (not relevant for this issue).

**Screenshots, Example Files**

Some examples where extended tooltip exists:

On a search bar:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/19336a55-7b10-4066-8174-4bbe8639df83)

On a toolbar button:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/31c49e7f-1052-4132-b9fa-f36947af72ed)

![image](https://github.com/Bforartists/Bforartists/assets/9047168/61a16d06-4ef5-4d1b-ad43-56ce6e93edf5)

On a drop-down:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/1dd9cb73-ea4a-44ca-afb1-e9a05473fa17)

On a checkbox:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/b2cf1267-d27a-4368-addf-3aabc1b0acc8)

On a spinner control:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/66a1bd9d-a4d0-4f37-9d5a-d1d179bf6ea8)

All this is excellent.

But the tooltips are missing when the header only has a label but no control (check box, spinner or drop-down list, etc).

For example, the **Sampling** section:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/1f9e072c-d64f-4399-bcfe-4dc6f4d0a3a6)
I expected to see a short comment on what this section does.

Example#2: The **Depth of field** section:
![image](https://github.com/Bforartists/Bforartists/assets/9047168/4bf04f35-f47d-4d99-a80e-dfc00534e0a8)
What is this section supposed to do??

Secondly, even where a label has a control attached to it, the tooltip does not appear when we hover the mouse on the label itself.
![image](https://github.com/Bforartists/Bforartists/assets/9047168/d483fb50-8c33-469d-88cc-56e10e5bbe53)
Here, there is a checkbox attached to this label. Yet the tooltip does not appear when my mouse is on the label.

**Desired:**
Tooltip should appear when the mouse is hovered on ANY label, regardless of whether it has an attached control or not.

**Comment by ReinerBforartists** [comment]
Many thanks for your report. But Panel titles does by design not provide any tooltip. It's just the name of this panel, a label. Not an operator. A panel does nothing. The operators and properties in the panels does. And they have a tooltip. And this means that this behaviour is expected UX. 

When you hover over the property then you get the tooltip that you are looking for.

Kind regards
Reiner

![worksasdesigned](https://github.com/Bforartists/Bforartists/assets/13919702/072fb4ea-0f43-40b4-9a69-c31cc18b4f5a)

**Comment by raindropsfromsky** [comment]
I agree. The feature was intended to work like that.

I should have marked this as a feature request, not a bug.

But the point is, how to convey to a user what the section does on the whole (not a "control-by-control" explanation).

For example, the overall idea of "Depth Of Field" is not explained when the tooltips describe the controls in that section individually.
![image](https://github.com/Bforartists/Bforartists/assets/9047168/3be5fe61-25d0-4e78-b3be-575547b35ebc)

My idea was that the user should be able to hover the mouse on any section to get a comment on it.

**Comment by ReinerBforartists** [comment]
I know what you mean. But that's not the job of the label. The label just tells you that there are depth of field related settings in the panel. And while it would be nice to have tooltips for labels here and there to some degree, it would introduce a big amount of UI clutter and code overhead.
