### ISSUE TITLE
devbuild dated 04-11-2023 crashes on launch. Devbuild dated 20-10-2023 works well.

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#3924]
**Describe the bug**
devbuild dated 04-11-2023 crashes on launch. The UI is seen for a split-second before it vanishes.

devbuild dated 20-10-2023 worked well.

**Desktop (please complete the following information):**
Windows 11, 
i3-8130U CPU, 12 GB RAM
Intel UHD Graphics 620

**Screenshots, Example Files**

**Comment by raindropsfromsky** [comment]
Reinstalled the app. 

It works now.

**Comment by ReinerBforartists** [comment]
Yes, this unfortunately happens from time to time. The developer version can have its flaws. Sorry bout that.
