### ISSUE TITLE
File Browser - Add Thumbnail Button Sizes to keep consisten with Asset Browser

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3925]
![bforartists_vy6c32NCBw](https://github.com/Bforartists/Bforartists/assets/35357409/9086114d-4552-4d6c-adc4-ac232a8fba56)
Current

Suggestion to add (from the Asset Browser thumbnail view drop down):
![bforartists_lT1DzTe1o5](https://github.com/Bforartists/Bforartists/assets/35357409/cfc7a5e9-a42b-483f-bb57-402bd47fff53)

It would be nice to have the thumbnail size button also in the file browser. Not only for consistency, but great UX. 

Similar task and code from here: #3780

**Comment by Blenux** [comment]
Look good?

I put 'Thumbnail Presets' there compared to the Asset Browser version,  since there is already other words in the menu, otherwise would look out of place.

![image](https://github.com/Bforartists/Bforartists/assets/25260650/59bfc580-e140-4b65-9b94-1a66d98edf20)

**Comment by ReinerBforartists** [comment]
Looks good to me :)

**Comment by ReinerBforartists** [comment]
Shall i create the manual issue? :)
