### ISSUE TITLE
rebinding pan to keyboard results in empty hint at the bottom of the window with middle mouse icon

### ISSUE THREAD

**Issue by UndeadBee42** [Bforartists/Bforartists#3929]
**Describe the bug**
rebinding pan to keyboard results in empty hint at the bottom of the window with middle mouse icon
![image](https://github.com/Bforartists/Bforartists/assets/55995165/16a5dc58-7751-49c4-9af1-03162bd272f2)

**Desktop (please complete the following information):**
Windows 10 nvidia

**Screenshots, Example Files**
![image](https://github.com/Bforartists/Bforartists/assets/55995165/65e19ef2-da60-4c73-868d-50cd7307714d)

same happens in blender 
![image](https://github.com/Bforartists/Bforartists/assets/55995165/77c5de0c-a90f-4f31-a34d-b3e59ec37a44)

i rebinded it this way because this is how inkscape works and mouse will breaking after constant clicking which is extremely annoying

**Comment by ReinerBforartists** [comment]
Hi UndeadBee42,

Thanks for the report. This is once more a Blender behaviour. The Industry compatible keymap also shows it. When you change the default hotkey that is mapped to this info area, then it doesn't display anymore. Better said, the hotkey is still showing. It's the middle mouse button. But there is no action attached to it anymore.

Again there is little that we can do here. Except report it to Blender.

As a side note, i never had any problems with mmb in many years. It is one of the standard keys in many other software. Gimp for example. So we will not change it. But your change seems to work fine for you, except the hotkey not showing. Or better said the hotkey is showing, but no action attached to it anymore. So i would simply stick with it.

**Comment by ReinerBforartists** [comment]
Makes no sense to report this to Blender, it is a UI issue. The software itself works fine. And we cannot fix it. So closing the task.
