### ISSUE TITLE
Node Editors - Box Select in Keymap is disabled in the default user preferences

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3932]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f4b17e3c-2406-4417-bec6-37e01a07d730)

For some reason the box select on click drag is disabled in the node editor in the defaults.

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
Cool catch. We either remove inactive keymap items, or have it on. So this looks like a accident.
