### ISSUE TITLE
3D Viewport - Edit Mode - Edit Mesh Overlay - Show Edges Deprecated for Edge Mode Selection Theme.

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3933]
The show edges in edit mode overlay has been deprecated and now uses a new edge mode selection theme color instead.

[PR Here](https://projects.blender.org/blender/blender/pulls/111431)

Bforartists
![image](https://github.com/Bforartists/Bforartists/assets/25260650/aabdea0d-80f7-4982-a0fb-142915b71870)

Blender
![image](https://github.com/Bforartists/Bforartists/assets/25260650/93baeebe-25b8-47ba-9030-206c3e5761e4)

`rna_uiItemR: property not found: View3DOverlay.show_edges
`

User can now also change the color of the new Edge Mode Selection in the Theme Preferences.

This is the current Bforartists color
![image](https://github.com/Bforartists/Bforartists/assets/25260650/ea74e1ef-a221-4be3-a490-7f6b9f832b40)

This is what Blender uses color
![image](https://github.com/Bforartists/Bforartists/assets/25260650/9f49ce24-166c-449c-8bdd-3abefa7805f8)

Safe to use the new color, and to remove entry from space_view3d.py?

**Comment by ReinerBforartists** [comment]
Safe!

We can always improve later if needed. But we use in general nearly the same colors than Blender while modeling.

**Comment by Blenux** [comment]
ok will do later today when get back home unless someone else wants to do

**Comment by Draise14** [comment]
Looks like this may be a high priority one. Will finish off some tasks, then will hit the tracker again. @Blenux you got this one or should I put this next on my todo list?

**Comment by Draise14** [comment]
Dibs, gonna have lunch then fix. This also broke the selection theming.

**Comment by Draise14** [comment]
Pushed to master.

**Comment by Draise14** [comment]
Documented.
