### ISSUE TITLE
Properties Editor, Render tab, Eevee renderer Raytracing panel, denoising subpanel - align props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3937]
These props needs to go left.

![alignpropsleft](https://github.com/Bforartists/Bforartists/assets/13919702/97b6b7e6-c637-48cf-80f2-35142715aac2)

**Comment by ReinerBforartists** [comment]
Ah, there is more ...
![more](https://github.com/Bforartists/Bforartists/assets/13919702/555f75e8-66ed-460d-8ec1-fbc788be7065)

**Comment by iyadahmed** [comment]
They unified the three panels
![image](https://github.com/Bforartists/Bforartists/assets/25552173/9fd2249c-fa0e-446b-827f-40c6e953cc70)

**Comment by iyadahmed** [comment]
> Ah, there is more ... ![more](https://user-images.githubusercontent.com/13919702/282315054-555f75e8-66ed-460d-8ec1-fbc788be7065.jpg)

but actually wait what

**Comment by iyadahmed** [comment]
ah ok the commit also fixes it yep
![image](https://github.com/Bforartists/Bforartists/assets/25552173/19865cd2-7bb7-48fc-a78f-c9614f99686d)
