### ISSUE TITLE
Geometry Nodes - Tools Mode - New node Input>Scene>3D Cursor Node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3949]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2ee50897-2331-4b3d-bbc5-a6a6036a6c5b)

This snuck up on me hard... I wasn't aware of these nodes maybe cause it was experimental commits then they recently pulled this out of experimental.. totally unprepared for this release.....

**Comment by Draise14** [comment]
High priority.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b3d30e2f-5131-4e20-aca9-c0c0f1243210)

Documenting.

**Comment by Draise14** [comment]
Yeh, some sleep does make this much easier.

**Comment by ReinerBforartists** [comment]
I heard it's the oxygene ^^
