### ISSUE TITLE
Geometry Nodes - Tools - "Non Assets" should be something positive and implicative

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3955]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ca27db00-8e6e-4080-b3a3-a2ae7f38ca78)

Right now a "non-asset" could be understood as a broken feature. It also doesn't imply that you should mark your asset to make it any different. 

"Unmarked Assets" with a separator might make more sense, then you know they are assets. Future icon from #3953 shows it's a nodegroup. 

Or "Local" or "Unmarked", and implies it's not stored in a library and that it is a tool. The icon is implicit that it is a nodegroup, shorter.  

**"Local Unmarked Assets"**
- Shows they can be assets, but they are unmarked
- Shows they are only local, not in a library

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/54501513-a31f-4076-b680-abf77c4f6c6a)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2a7e5f0a-bebf-461d-8f8e-dd49afc8585d)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/886e5773-4043-401b-a70a-229104c5bafc)

Better. Also hitting #3836

**Comment by Draise14** [comment]
Documenting.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/387d4185-505f-44db-818f-0bd751d490c3)

Bit more.

**Comment by Draise14** [comment]
Fixed via https://github.com/Bforartists/Bforartists/commit/0d211b970a9a230a8703b75b1fb5fe6ef82edc6e

Sorry bout the double task for the same commits...

**Comment by ReinerBforartists** [comment]
Not happy with this change. Now we have another name for the tool than Blender without a good reason. Non asset nailed it pretty much. And the different name will give some people a hard time.

**Comment by Draise14** [comment]
Asset is still Asset in the new way. 

"Non" is latin used in non grata. It isn't used in English. 

Un-, in- are the English equivalents. But saying unasset or inasset makes no sense. Unmarked does. 

It's bad Grammer.

**Comment by ReinerBforartists** [comment]
Now you changed it. I just stated that i am unhappy with the change. More as a warning that we should be careful with changing Blender naming. It can make trouble.

**Comment by Draise14** [comment]
Ah. It's a label in the GUI no relation to a tool here. So thought it flexible. 

I can revert if it may cause API issues.

**Comment by Draise14** [comment]
Will remove "Local" from the label.
