### ISSUE TITLE
Bug - Region type not valid for this space type

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3956]
![WindowsTerminal_jxbRhu59Cc](https://github.com/Bforartists/Bforartists/assets/35357409/664438ba-723b-446d-8947-ebc990b5175a)

We got a nasty bug when saving custom workspaces in Bforaritsts 4.0.1 and master. 

**Steps to reproduce**
1. Open factory Bforartists
2. Duplicate main workspace 
3. Save startup
4. Close
5. Open Bforartists - notice a crash

```Stack trace:
ucrtbased.dll       :0x00007FFA68312E00  _threadid
ucrtbased.dll       :0x00007FFA68312E00  _threadid
ucrtbased.dll       :0x00007FFA6832AAF0  abort
bforartists.exe     :0x00007FF745F6CE90  _BLI_assert_abort C:\3D_Stuff\Bforartists\source\blender\blenlib\intern\BLI_assert.c:49
bforartists.exe     :0x00007FF7472D3080  ED_area_init C:\3D_Stuff\Bforartists\source\blender\editors\screen\area.cc:2093
bforartists.exe     :0x00007FF7472CB170  ED_screen_refresh C:\3D_Stuff\Bforartists\source\blender\editors\screen\screen_edit.cc:682
bforartists.exe     :0x00007FF7472CC960  ED_screens_init C:\3D_Stuff\Bforartists\source\blender\editors\screen\screen_edit.cc:710
bforartists.exe     :0x00007FF7462099D0  WM_check C:\3D_Stuff\Bforartists\source\blender\windowmanager\intern\wm.cc:492
bforartists.exe     :0x00007FF746216520  wm_homefile_read_ex C:\3D_Stuff\Bforartists\source\blender\windowmanager\intern\wm_files.cc:1478
bforartists.exe     :0x00007FF7462080A0  WM_init C:\3D_Stuff\Bforartists\source\blender\windowmanager\intern\wm_init_exit.cc:289
bforartists.exe     :0x00007FF744BC20E0  main C:\3D_Stuff\Bforartists\source\creator\creator.cc:554
bforartists.exe     :0x00007FF750E80960  invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79
bforartists.exe     :0x00007FF750E80710  __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
bforartists.exe     :0x00007FF750E806F0  __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331
bforartists.exe     :0x00007FF750E80A20  mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17
KERNEL32.DLL        :0x00007FFADA542560  BaseThreadInitThunk
ntdll.dll           :0x00007FFADB98AA30  RtlUserThreadStart
```

Observations and test:
- When hiding the Bforartists toolbar editor from all workspaces, the bug is no-longer there. This is also something wrong with how it's being stored in the startup.blend, bug goes from there.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/42c51983-4d4b-422e-a740-331d68668d6f)

I assume it's from here?

**Comment by Draise14** [comment]
I've hit a wall, I don't know how to debug well - and manually trying to back track to find why it crashes is.. not helping. I am not sure what to do nor where to begin to troubleshoot this. 

I'll but in a big bounty for this one.

**Comment by Draise14** [comment]
Another observation

1. Load factory
2. Duplicate Main Workspace
3. Remove toolbar editor
4. Create new toolbar editor
5. Save startup

No crash.

**Comment by ReinerBforartists** [comment]
Good catch. It's important to keep an eye at changes at the editor types. Most of the times we have to adopt it to our editor type then too ...
