### ISSUE TITLE
3D Sequencer - Add the ability to use Scene Strips to toggle 3D View scenes (Spa Studio patch by Znight)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3957]
https://github.com/Bforartists/Bforartists/assets/35357409/b527a07f-c783-4910-a2d6-ce1b52640bc9

This is a big patch, but I wanted to make a thread for it. I've been working with Znight (Trung Pham) to get the Spa Studios Sequencer code into Bforartists. We now have it working with the latest from Bforartists.. and it's.. HUGE.. HUGE. To make it work, a lot of extra handlers have to be added to C to make it work. 

This patch was originally created by Falk David in Spa Studios (repo here: https://github.com/The-SPA-Studios/blender) for feature film production. This makes the sequencer on feature parity with the Unreal Engine sequencer and Source Film Maker sequencer, a highly requested feature from the community. This ultimately turns the sequencer into a fully fledged 3D View video editor using the scene.sThis allows the ability to create multishot animations without needing to render them to disk with animation clips in the scene per shot, or to stick to very low frames per second in the sequencer preview system (old). I have also talked with Falk David personally at BCON, he's ok that we use the code. 

Branch: [Development-](https://github.com/Bforartists/Bforartists/tree/Development_3D_Sequencer)

**New Features:**
- Pins the sequencer to a master scene for timeline editing of scene strips and playback, adds the ability to syncronize the sequencer playback to 3D view plaback of multiple scenes
- Switches 3D View scenes based on the sequencer scene strips
- Adds a Dopesheet widget overlay to retime scene strips quickly and easily with click and drag
- Syncronizes various settings from the sequencer to the other editors, including greasepencil and animation editors with toggles
- Has a batch renderer included (optional)
- Adds a scene/camera switcher to the 3D View
- Adds common collection editing on all shots (for consistent editing of content) (optional)
- Adds ability to add, rename and manage strip nomeclature (optional)

Notes: 
- There are other features that are not needed (pipeline specific to Spa Studios) that we can remove, they are tagged "optional". 
- This doesn't have to be a default addon, but it's a great opt-in to include. 
- I can stress test this in a production once I migrate the painterly shader to Bforartists 4.0.1

## **Pending:**
- [x] #4009
- [x] Rename the addon to be Bforartists specific
- [x] #4011
- [x] #4012
- [x] Comment all the new code in the patch to maintain it well
- [x] Document Heavily
- [x] Test it on a production

**Round 2:**
- [x] #4019
- [x] Move strip toggle button to Strip menu to not be in the sidebar
- [ ] #4029
- [x] Make sure the overlays are drawing the Scene Strip labels correctly (per the original)
- [x] Create a 3D Sequencer workspace
- [ ] Add scene strip operators to toolshelf
- [x] #4021

**Comment by Draise14** [comment]
Merged to Branch, to start working.
https://github.com/Bforartists/Bforartists/commit/c0eea1070d0a27b2ee296484c77a139489f490a2

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2f2fdd13-c780-431a-90ee-6dd4b9f98382)

Got a couple of warnings left before the UX development.

**Comment by Draise14** [comment]
Got it. Compile now has no warnings.

**Comment by ReinerBforartists** [comment]
Um, what are you doing with our poor github actions? O_O

**Comment by Draise14** [comment]
Znight modified them for his own repository from a fork, I accidentally overwrote our one, then replaced it again with our one.

**Comment by ReinerBforartists** [comment]
Phew, don't scare an old man ^^

**Comment by Draise14** [comment]
**Update:**
- Stripped it back to the bare sequencer essentials
- Updated tooltips and added correct iconography
- Moved dopesheet widget over toggle to the options panel
- Added more explicit titles for panels and made panels consistent between editors (View tab, same panel name)
- Added an "Active Scene" indicator to now know we can "pin" scenes to the sequencer. Still not sure if "Pinned" is better label than "Active", to avoid confusion. Will have lunch then think about it. 
- Added an operator to "enter" or "update" the global scene to the active scene strip without needing to permanently be in sync mode. 

**Pending:**
- I think a new workspace is needed to make the most of it
- Full Documentation
- Maybe a button to "Set 3D View to Master Scene" with a single click since it's multiple steps to get it going, which is not intuitive yet.. the rest is though. 
- Maybe a button to toggle in and out of child/master scene strips

But it's getting bigger, yet smaller in code. And nearly ready to push to a production this week for testing. 

Unused code is still there, so may strip that back soon before merging to master. 

## What was stripped back
- Batch Rendering from sequencer
- Shared Collections from sequencer
- Scene creation and name management operators from sequencer
- Autoregistry of hotkeys..

**Comment by Draise14** [comment]
Documentation started. It is extensively documented already by Spa Studios, but it's more a tutorial. So will document the reference of the manual - and go from there.

**Comment by Draise14** [comment]
Gonna test now with a project, will pull to master next week.

**Comment by Draise14** [comment]
Slight improvement:
- Can unassign camera from the 3D View Sequencer Sync panel to reset the scene #4014

**Comment by Draise14** [comment]
Did a performance test and a full episode with it. Workflow UX has some kinks and inconsistencies with the BFA way, but those could be new tasks and documentation updates. In general, this works.

**Comment by Draise14** [comment]
Tested in production. It needs a bit of UX love, but it works like magic - can't go back to the old way now.

**Comment by Draise14** [comment]
![bforartists_SQGRO3LplO](https://github.com/Bforartists/Bforartists/assets/35357409/6cbe9508-71d2-415e-a6ea-98f08f3277d2)
![bforartists_7IbkBsiJ9u](https://github.com/Bforartists/Bforartists/assets/35357409/a78f34f4-9e6b-404b-98ce-d96ac1af2ead)

**Updates:**
- Made the button go to header
- Updated tooltip for clarity
- Improved the master scene selector in both 3D view and Sequencer panel
- Improved the camera assignment
- Exposed a hidden operator

**Comment by Draise14** [comment]
I think this is time to merge to master. Documentation is up to date, and now it's polish before release. It also is mostly uninvasive till you activate the addon, so it's an opt-in.

**Comment by Draise14** [comment]
Merged to master. Will continue work from there, or occasionally from this branch if it has bigger changes. 

Most will be addon work though, the core is done.

**Comment by Draise14** [comment]
Gonna close this for release. Anything new will come at a later date. This is functional, opt-in, has a workspace - and is documented. 

The rest is improved UX added to the addon for a later date.
