### ISSUE TITLE
Node Editors - Shaders - Musgrave texture is merged to Noise Texture node now...

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3958]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/3c5a4422-fd05-4d15-b55e-7753a23b87c1)

Musgrave is no-longer a shader node.... Remove from documentation and sidebar. Update Noise Shader node if necessary. 

<details><summary>Details</summary>
<p>

SHA-1: 0b11c591ec62d4ff405108c453f4a34bf3eaee91

* Nodes: Merge Musgrave node into Noise node

This path merges the Musgrave and Noise Texture nodes into a single
combined Noise Texture node. The reasoning is that both nodes
intrinsically do the same thing, which is the layering of Perlin noise
derivatives to produce fractal noise. So the patch de-duplicates code
and unifies the use of fractal noise for the end use.

Since the Noise node had a Distortion input and a Color output, while
the Musgrave node did not, those are now available to the Musgrave types
as new functionalities.

The Dimension input of the Musgrave node is analogous to the Roughness
input of the Noise node, so both inputs were unified to follow the same
behavior of the Roughness input, which is arguable more intuitive to
control. Similarly, the Detail input was slightly different across both
nodes, since the Noise node evaluated one extra layer of noise. This was
also unified to follow the behavior of the Noise node.

The patch, coincidentally fixes an unreported bug causing repeated
output for certain noise types and another floating precision bug
#112180.

The versioning code implemented with this patch ensures backward
compatibility for both the Musgrave and Noise Texture nodes. When
opening older Blender files in Blender 4.1 the output of both nodes are
guaranteed to always be exactly identical to that of Blender files
created before the nodes were merged in all cases.

Forward compatibility with Blender 4.0 is implemented by #114236.
Forward compatibility with Blender 3.6 LTS is implemented by #115015.

Pull Request: #111187

</p>
</details>

**Comment by Draise14** [comment]
A user on twitter would like the musgrave back, and personally I don't know how to reproduce the musgrave, maybe we should include this into the asset library alternatively.

**Comment by ReinerBforartists** [comment]
I am not sure if it makes sense to ship a separated musgrave node since the functionality is there. Just under the Noise texture now. It is hard enough to reach feature compatibility without such things.

**Comment by Draise14** [comment]
Yeah, best not. It could be a "preset" nodegroup in the asset library alternatively. I have plans to add more noises there. Users have already voiced concern for that convenient preset of a noise.
