### ISSUE TITLE
space_toolbar.cc - info_blend_write - definded but not used

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3959]
Think this is some left over code from #3956.

![Screenshot_20231125_105100](https://github.com/Bforartists/Bforartists/assets/25260650/9a7c16c1-ca4c-4acd-9a3c-1439d53581a1)

**Comment by ReinerBforartists** [comment]
Have you checked if writing to blend file still keeps the toolbar intact? I remember that we needed to add this for a reason ...

**Comment by Blenux** [comment]
Yeah I saved the duplicated the workspace, and the startup blend file, with a blank config folder, loaded it up again, changed the toolbar to something different, closed and open again and everything was fine.

**Comment by ReinerBforartists** [comment]
Thanks for checking.

Though, when i compare our space_toolbar.cc with the space_info.cc for example, then i spot that the change is a bit deeper, that some other things have changed too with the move to c++. And that there are some things missing. And simply removing this one line might bring us in trouble.

info_blend_write has become info_space_blend_write

There is also a change from area to region ....

Our little toolbar code file is heavily mixed up at the moment. This is why i said it is important to keep an eye at changes that happens at the space files for the editor types. Now we are in trouble :)

![mixedup](https://github.com/Bforartists/Bforartists/assets/13919702/112aefba-0203-4f31-b54e-dcf8773c092c)

**Comment by ReinerBforartists** [comment]
Ah, info_blend_write is wrong anyways. It should be toolbar_blend_write. Or in the new waya toolbar_space_blend_write.

**Comment by Blenux** [comment]
Yeah the toolbar_blend_write is already in there above the info_blend_write I removed, but yeah for consistency it should be renamed that.

**Comment by iyadahmed** [comment]
this change is actually nice, green light

**Comment by ReinerBforartists** [comment]
And what about the rest? ^^

**Comment by ReinerBforartists** [comment]
> I'm working on the rest ^^

<3

Shall we make a task for it? :)

**Comment by iyadahmed** [comment]
> > I'm working on the rest ^^
> 
> <3
> 
> Shall we make a task for it? :)

sure, let's make a task ^^
