### ISSUE TITLE
Select color in edit mode with face select now grey instead of orange

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3961]
**Describe the bug**

Selected face does not show selected orange color anymore. But grey. Needs a fix.

**Desktop (please complete the following information):**
Win 10

**Screenshots, Example Files**

![selectcolor](https://github.com/Bforartists/Bforartists/assets/13919702/29d1aefb-7ec6-4a11-839a-4c83108aec93)

**Comment by ReinerBforartists** [comment]
Hmm, it does not seem to be a theme problem. Switching to the Blender theme does not fix it.

**Comment by iyadahmed** [comment]
hmm maybe this is related to the goo engine patch we applied a while ago, maybe it got killed by Blender changes

**Comment by Draise14** [comment]
I thought I fixed this. I'll check the commit logs now.

**Comment by ReinerBforartists** [comment]
Friends, this is a showstopper that we need to fix ...

**Comment by Draise14** [comment]
It's a theme issue. Already fixed locally. I'm not at the computer till Sunday evening or Monday. But can do it then. 

Did it make it into the official release?

**Comment by ReinerBforartists** [comment]
Yes it has. 

The devbuild from 04-11-2023 did work fine. Everything behind this point is broken it seems.

**Comment by Draise14** [comment]
Will work this this afternoon, it is kinda annoying changing this often every new compile, so yeah. High priority. 

Would this be worth a 4.0.2 release?

**Comment by ReinerBforartists** [comment]
Your decision :)

**Comment by ReinerBforartists** [comment]
Meow?

Users becomes impatient ^^

**Comment by iyadahmed** [comment]
Sadly not sure what is the issue, I have to investigate when I  get home,
currently 11 AM at school

**Comment by ReinerBforartists** [comment]
@Draise14 said it is a theming issue. And that it is fixed at his end already. So i basically wait for the commit. And the decision if we make a point release since this is a showstopper bug.

**Comment by ReinerBforartists** [comment]
Don't you love the time before christmas ^^

**Comment by Draise14** [comment]
I do not love the time before Christmas... 😂

**Comment by Draise14** [comment]
Mode Face Selected is an additional layer of selection coloring when NOT in face selection mode. So it's easier to see what mode you're in (edge or vertex, though full face is selected). So as a UX, I think active and selected faces in face mode is typical orange and when in edge and vertex mode, selected faces is now the optional "selected" colour from the outliner, a blue, which allows to see edge and vertex selection better. 

**Updates:**
- I made the edge and vertex and face selected vs active the same colours
- Made the the edge and vertex face sub-selection a blue (like the outliner active vs selected) colours. 

https://github.com/Bforartists/Bforartists/assets/35357409/40bd42c8-d344-4746-b78c-f8f2acb17f16

**Comment by Draise14** [comment]
Pushed to master.

**Comment by ReinerBforartists** [comment]
Make it a task in the manual :)

**Comment by Draise14** [comment]
Righteo.
