### ISSUE TITLE
Dopesheet - Channel Context menu show/hide operators have no icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3963]
## Current iconography
![bforartists_fH16j7IgQx](https://github.com/Bforartists/Bforartists/assets/35357409/a120037d-5b9d-4ccc-9fdc-6ffac6f76bd4)

## Context Menu
![bforartists_k5xafInerd](https://github.com/Bforartists/Bforartists/assets/35357409/38c387eb-bdaa-4e1f-a830-4c8908d6b651)

Missing icons in dopesheet channels context menu. Needs... them to be consistent.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Done
