### ISSUE TITLE
Timeline - Make icon for "Insert Keyframe" in header consistent.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3965]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/ff7a5d15-1553-4140-aace-eb75f80237fd)

Right now you insert a general keyframe now, without a keying set, slider, prop or floating menu required. Good news. 

Current animation UX: you have to select from the a hotkey floating panel after pressing `I` and/or right click context or record buttons when available on sliders and properties throughout the entire interface. Or you turn on the autohotkey. "Insert Keyframe" now defaults to key channels or keying sets. And it now works without any context and works on a good default transform system - a bit like Auto-hotkey but as an opt in. And sometimes you want to force record the keyframe without changing editors

We have no hotkey to quick keyframe assigned, but exposing this to the timeline helps have an opt-in quick thokey key (like and opt-in Autothokey) without needing to be in Autohotkey mode. 

<details><summary>Details</summary>
<p>

SHA-1: a99e419b6e841d673a3542c372d5faec82c0d138

* Anim: Insert keyframes without keying sets

When animators want to key something in the viewport,
the code needs to know *which properties* should be keyed of that selected thing.
So far that was done with keying sets, and a pop-up that let's
you choose the keying set to use. You can get rid of the popup by
choosing a keying set ahead of time. But that is also not always desirable.

That pop-up is quite confusing and gives way too many options.
To simplify this process this PR adds a User Preference option to choose one or more of:
* Location
* Rotation
* Scale
* Rotation Mode
* Custom Properties

Now whenever the `I` key is pressed in the viewport,
and no keying set is enabled, it reads the preferences for which channels to insert.

# User Facing changes
* The popup will not be shown when pressing the hotkey,
 but you can still explicitly use keying sets by going to the menu
* Which channels are keyed is defined by a User Preference setting under animation
* when a keying set is used explicitly, the User Preference settings are ignored

Part of #113278

Pull Request: https://projects.blender.org/blender/blender/pulls/113504

</p>
</details>

**Comment by Draise14** [comment]
After sleeping on it, I think this should go ahead. Insert keyframe, like hit record on the keying set panel. Having this only in the 3D View in a sub menu doesn't make too much sense - or hidden behind a hotkey to the right of the keyboard - when you press this over and over and over again.

**Comment by ReinerBforartists** [comment]
We already have a insert keyframe operator in the play controls. Same operator. But different icon. 

I would vote to remove the entry from the Animation sub menu instead of fixing the icon. It is a double.

![double](https://github.com/Bforartists/Bforartists/assets/13919702/9e1647ae-717b-4082-b9dd-c1e901566466)

**Comment by Draise14** [comment]
Huh. Misused icon. I vote for the diamond plus icon. 

Removing it from the 3D view removes the ability to right click and reassign that hotkey or discover the hotkey in the 3D view.

**Comment by ReinerBforartists** [comment]
So what remains is to change the icon :)

**Comment by Draise14** [comment]
Done, commit to master via https://github.com/Bforartists/Bforartists/issues/4055
