### ISSUE TITLE
Default Hotkey - Change I to insert keyframe and CTRL+I to call the keyframe insert menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3966]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/8c7d4a14-a335-4fd8-9a3f-43e4901544b9)

New default keying set is now possible, meaning the two step hotkey is no-longer needed (1. Press hotkey, insert keyframe menu pops us 2. Select what to key). 

So for consistency, we should focus on the Delete menu workflow (`DEL `quick delete, `CTRL+DEL` to call menu). 

So:
`I` to quick key
`CTRL+I `to call meny

<details><summary>Details</summary>
<p>

SHA-1: a99e419b6e841d673a3542c372d5faec82c0d138

* Anim: Insert keyframes without keying sets

When animators want to key something in the viewport,
the code needs to know *which properties* should be keyed of that selected thing.
So far that was done with keying sets, and a pop-up that let's
you choose the keying set to use. You can get rid of the popup by
choosing a keying set ahead of time. But that is also not always desirable.

That pop-up is quite confusing and gives way too many options.
To simplify this process this PR adds a User Preference option to choose one or more of:
* Location
* Rotation
* Scale
* Rotation Mode
* Custom Properties

Now whenever the `I` key is pressed in the viewport,
and no keying set is enabled, it reads the preferences for which channels to insert.

# User Facing changes
* The popup will not be shown when pressing the hotkey,
 but you can still explicitly use keying sets by going to the menu
* Which channels are keyed is defined by a User Preference setting under animation
* when a keying set is used explicitly, the User Preference settings are ignored

Part of #113278

Pull Request: https://projects.blender.org/blender/blender/pulls/113504

</p>
</details>

**Comment by ReinerBforartists** [comment]
Uh nice change. Took just 20 years or so to overcome this crazy keyingset concept ^^

**Comment by ReinerBforartists** [comment]
Ctrl I is already occupied by (de)select all ...

**Comment by ReinerBforartists** [comment]
Oh, and shift and alt I too ... :)

**Comment by ReinerBforartists** [comment]
Always a miracle how one little tiny thing ends in renovating half the software ^^

**Comment by Draise14** [comment]
Delete "keying set keyframs" is not "delete keyframe". Two separate operators.

**Comment by ReinerBforartists** [comment]
Yeah, but we have add and delete keyframes in the header, so they should work with each other ...

**Comment by Draise14** [comment]
Blender made this keying set panel K, might not have conflict and is consistent with other animation software. 

They also added a new keying set pie menu... 

<details>
<summary>Details</summary>

SHA-1: 87fc8e8dddf6481030a956aaa77c2cde9c72d03f

* Anim: Add hotkey for keying set operators

This is in response to feedback to the changes from #113504
While it does simplify inserting keyframes,
sometimes artists want to insert keys only to e.g. Location.
This takes longer to do now, since the option is in a menu.

This PR changes the following:

* new `K` hotkey to bring up the "Keying Set" menu.
This will always show the menu, even if a keying set is active.

* `Shift + K` will open a menu to set the active keying set

* with "Pie Menu on Drag" enabled in the user preferences,
hitting `I` and moving the mouse will bring up a pie menu
to insert only specific transform channels

Conceptually this separates the keying set behavior from the
insert keyframe behavior.
`I` will always add keyframes.
While `K` always shows keying set options.

Pull Request: https://projects.blender.org/blender/blender/pulls/115798


</details>

**Comment by Draise14** [comment]
Won't add SHIFT+K, but the other two yes, to object mode and pose mode.

**Comment by Draise14** [comment]
huh, it's not working on the compile. Testing

**Comment by Draise14** [comment]
Currently missing in pose mode

**Comment by Draise14** [comment]
Commit to master, hopefully good here now.
