### ISSUE TITLE
3D View - Sculpt Mode - Remesh panel cleanup "Attribute" checkbox has extra space before button 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3968]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/05e45a98-c918-41ff-9db0-ef1772237f72)

The checkbox list here is now.. got a gap in the remesh panel in sculpt mode. Could have some cleanup. 

<details><summary>Details</summary>
<p>

SHA-1: ba1c8fe6a53a00c9324607db6a1836132cef5352

* Mesh: Improve remesh attribute transfer

Currently we have options to transfer the paint mask, face sets, and
color attributes to the new mesh created by voxel remesh. This doesn't
make use of the generic attribute design, where it would be clearer to
transfer all attributes with the same methods. That's reflected in the
code as well-- we do duplicate work for the mask and vertex colors, for
example.

This commit replaces the transfer options with a single checkbox for
all attributes. All attribute types on all domains are transferred with
basically the same method as the "Sample Nearest" node from geometry
nodes-- they take the value from the nearest source element of the same
domain. Face corners are handled differently than before. Instead of
retrieving the mixed value of all the corners from the nearest source
vertex, the value from the nearest corner of the nearest face.

---

Some timing information, showing that when interpolating the same
data, the attribute propagation is significantly faster than before.
Edge and corner attributes would add some cost (edges more than
corners), but might not always be present.

Before
```
voxel_remesh_exec: 3834.63 ms
BKE_shrinkwrap_remesh_target_project: 1141.17 ms
BKE_mesh_remesh_reproject_paint_mask: 689.35 ms
BKE_remesh_reproject_sculpt_face_sets: 257.14 ms
BKE_remesh_reproject_vertex_paint: 54.64 ms
BKE_mesh_smooth_flag_set: 0.15 ms
```

After
```
voxel_remesh_exec: 3339.32 ms
BKE_shrinkwrap_remesh_target_project: 1158.76 ms
mesh_remesh_reproject_attributes: 517.52 ms
```

Pull Request: https://projects.blender.org/blender/blender/pulls/115116

</p>
</details>

**Comment by ReinerBforartists** [comment]
Check the code, this looks like some problems and hidden content.

**Comment by Draise14** [comment]
Compred the code - got it. 

Documenting.
