### ISSUE TITLE
Double menu entries for a curve object in edit mode in Curve and Control Points menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3972]
We have double entries here.

![doubles](https://github.com/Bforartists/Bforartists/assets/13919702/dbdee089-f171-4eb1-be03-18d5949de1e5)

**Comment by Draise14** [comment]
Also double in documentation. Recalculate Handles also is here.  

I assume this is more a control point operator, so removing from the Curve area.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d6c18543-395f-40d5-b767-79f9010d0437)

Done

**Comment by ReinerBforartists** [comment]
Tilt and clear tilt is also double ^^

**Comment by Draise14** [comment]
That would be a control point operator too I assume. I'm back at the computer Monday. I can do that.

**Comment by ReinerBforartists** [comment]
I'll grab this one.

**Comment by ReinerBforartists** [comment]
Fixed
