### ISSUE TITLE
File - System operators missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3973]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/9688a084-3af5-4e1a-8418-bdac0ab48753)

Right now the Blender system operators are missing in Bforaritsts. They will need iconography and documentation too. 

I guess they can be a sub menu under Edit, or Window?

**Comment by ReinerBforartists** [comment]
Nope, they are not missing. We have just long moved it where it belongs to. It is scripting functionality.

Not sure if it really needs iconography therefore.

![outoftheway](https://github.com/Bforartists/Bforartists/assets/13919702/fbb2680d-0d3a-46f8-ac93-50e543d6e2d8)

**Comment by Draise14** [comment]
Ah. There they are. Silly me. I looked there but glossed over I guess.

**Comment by ReinerBforartists** [comment]
I remember that i was in trouble to add icons here ...

**Comment by ReinerBforartists** [comment]
> I remember that i was in trouble to add icons here ...

Ah, this was back in the time where i didn't know about the enums ...

**Comment by ReinerBforartists** [comment]
Quick and dirty

Updating the manual with a new image ...

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/afc8573d-cae6-40a5-a7ae-799a9559cd3f)

**Comment by ReinerBforartists** [comment]
Fixed
