### ISSUE TITLE
Webpage - fix footer

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3978]
We have a problem at the footer. God knows for how long Must've been introduced with the new widgets system in Wordpress, or one of the udpates at the oceanwp theme.

Formerly working (grabbed from the wayback machine: 

![footer](https://github.com/Bforartists/Bforartists/assets/13919702/c6e3cf39-caae-4169-b462-55ce7e824fc3)

And now:

![fixfooter](https://github.com/Bforartists/Bforartists/assets/13919702/149da3dd-2efe-49e3-a2f4-7aba7ec9c123)

**Comment by ReinerBforartists** [comment]
The cache drives me nuts. Let's wait until tomorrow ...

**Comment by ReinerBforartists** [comment]
Can't remove this extra footer :(

**Comment by ReinerBforartists** [comment]
Sure. When you can catch this one :)

**Comment by ReinerBforartists** [comment]
I was able to turn off the extra footer for other pages but the front page. So i smell a bug here in the oceanwp theme

**Comment by Blenux** [comment]
should be juso3d

**Comment by ReinerBforartists** [comment]
Congratulations, you are now admin of the page. I've made a snapshot of the server just in case. But be nevertheless careful ;)

**Comment by Blenux** [comment]
Yeah nah will be extreme careful but snapshots are always good :D.

**Comment by Blenux** [comment]
Problem does seem to be in the theme lke you mention,

![image](https://github.com/Bforartists/Bforartists/assets/25260650/867ee119-7a1a-4fa2-abea-d89bc19424d3)

one can hide and center is via custom css/js might be the easiest way?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/bac71ff8-f2a3-45a8-8a05-4a309a87531e)


```
#footer-bottom #footer-bottom-menu, #footer-bottom #copyright {
    width: auto
}

#footer-bottom-menu {
    display: none;
}

#footer-bottom #copyright {
    float: none;
    text-align: center;
    padding-right: 15px
}
```

**Comment by ReinerBforartists** [comment]
Hmm, footer bottom menu ...

**Comment by ReinerBforartists** [comment]
Giving up. Then be it that way. It's ugly, not dysfunctional. @Blenux, did you found a way besides modifying the code? If not then i will close this issue as known issue.

**Comment by Blenux** [comment]
Nah all leads to customizing the css (though did read that, using the custom css/js does stay after a OceanWP update)

**Comment by ReinerBforartists** [comment]
So it looks like a bug in the OceanWP theme then.

Hmm. One more adjustment in the css file with every update doesn't really make the drama any bigger. I'll have a look.

**Comment by ReinerBforartists** [comment]
And done. Many thanks for the css snippet.
