### ISSUE TITLE
Geometry Nodes - Geometry - Write sidebar has wrong "Set Position" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3980]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ec2623f0-fffa-46a8-8a00-b3301fb4daca)

Geometry Nodes - Add Sidebar - Geometry - Write - Transform Geometry should be **Set Position**

![image](https://github.com/Bforartists/Bforartists/assets/35357409/ac7423c5-7ab3-4f6b-80c2-2be067e8a3ff)

**Comment by ReinerBforartists** [comment]
Fixed ![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/9911643d-4fec-499c-8cd0-a0f147809b2e)
