### ISSUE TITLE
NLA Editor - New Track header entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3982]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f6738e2e-fa97-4216-acf6-d7d3a1fc75e0)

New "Track" menu with new operators, about half a dozen or so. Needs extensive documentation. 

<details><summary>Details</summary>
<p>

SHA-1: da83b2951d1d7ffdd62267f4bb262688b72ff797

* Anim: Add  "Add/delete" track operations to NLA context menu

Updating NLA context menu, adding in more relevant track operations (tracks add, tracks add above, tracks delete).

Pull Request: https://projects.blender.org/blender/blender/pulls/114202

</p>
</details>

**Comment by ReinerBforartists** [comment]
and icons ^^

**Comment by ReinerBforartists** [comment]
Duplicate

NLA Editor - Add menu - move channel and track related add operators to relevant menus #3986
