### ISSUE TITLE
NLA Editor - Add menu - move channel and track related add operators to relevant menus

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3986]
## New add menu in the LNA
![image](https://github.com/Bforartists/Bforartists/assets/35357409/427dc7ce-abe6-48d1-88ed-be1ed0f3ea1b)

# New location for add operators for Tracks
![image](https://github.com/Bforartists/Bforartists/assets/35357409/83571d5e-0005-42fa-9cac-fd958d23c4ff)

Not sure if this is a good thing or a bad thing. The add menu now is not about tracks, which to me feels inconsistent. In their effort to make the add menu concise, the tracks has the add operator in the track header menu. It does make it consistent with the tracks context menu to a degree....... but for discoverability, it is inconsistent. 

**Question:** should we preserve the old add menu to keep all add operators in one place? Or do we adopt splitting the track add operator into tracks for.... inconsistency sake?

**Debate:**
- The channels header menus of the other animation editors has "remove" operators, add/remove logically go there - but the other editors have not "add".  
- The new tracks header is like the "edit" header but now for tracks only. You edit after you add.. so you wouldn't add. You remove when you edit what is already added, so that could still logically remain out of the remove/add logic. 
- The add menu was already really small so making it "concise" seems.... redundant. 
- If we do it for track add operators, would we consistently have to do that with animation strip add operators too? Isn't the strip menu already too crowded? Why!? 

<details><summary>Details</summary>
<p>

SHA-1: 2cc65196921eb8c14da32bfbbdbcd02ad7ee9051

* Anim: Refactoring NLA menu into more sensible format

Updating NLA menu to be more inline with VSE / other Animation editors.

Remove "Edit" drop down, and instead split operators into "Track" & "Strip" Menus. Update Add menu to be more concise.

Pull Request: https://projects.blender.org/blender/blender/pulls/114805

</p>
</details>

**Comment by ReinerBforartists** [comment]
Consistent is better

**Comment by ReinerBforartists** [comment]
Did i mention that consistent is better? ^^

**Comment by ReinerBforartists** [comment]
Lemme clean up here ...

**Comment by ReinerBforartists** [comment]
Fixed.

Documenting.

**Comment by ReinerBforartists** [comment]
Done 

![track](https://github.com/Bforartists/Bforartists/assets/13919702/a91e996e-feaa-43fe-b909-6f913d7802ed)
