### ISSUE TITLE
Tooltip - Improve "Press Space to search" in the search in add menus to imply it can also work in all header menus

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3987]
![bforartists_w4m542j85q](https://github.com/Bforartists/Bforartists/assets/35357409/bbe1df02-f2b0-4336-bed1-cbad0dd6cf5b)
Improve "Press Space to search" in the search in add menus to imply it can also work in all header menus

**Comment by ReinerBforartists** [comment]
This way?

![tooltip](https://github.com/Bforartists/Bforartists/assets/13919702/13be112b-c5f7-4cef-beb2-7be753a56e16)

**Comment by Draise14** [comment]
This is for every single menu to ever exist..... 

Space.. search active menu.... This is why I suggest the tooltip hint directly on that operator... 

Or expose that operator somehow...

**Comment by Draise14** [comment]
Hmmm... Both are operator search menu dialogues/UX - one one is triggered by key or button and global and the other is.. triggered by hotkey only (unless in the add menus) and does the same... But with an operator filter by menu. 

Maybe in the add menu search operator tooltip? 
And we add that search operator in all the add menus? Even in the 3D view? 

So not all, but as an operator with the right relevant tooltip in the menu search.

Only place this IS exposed to a degree is there in the Node editor and sequencer add menu... Now I recall.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8287aeda-f036-4131-8908-b00288d81a2f)

Here, this could be where the tooltip could be clearer - and we should also add that search operator to the 3D View add menu - all add menus, to be consistent.

**Comment by Draise14** [comment]
Updated task.

**Comment by Draise14** [comment]
Problem with your tooltip in a header label - is.. that you can do this space bar to search in ANY menu, not only the add menus, if we add it to the add menu, we would also have to add that tooltip to every menu - so... only on add menus - it's still a rare tooltip you'd stumble upon by mousing over the Add menu by accident - this is fixed if you intentionally look for more info of of that menu search operator from somewhere in the GUI where it exists as a real in menu operator.

**Comment by ReinerBforartists** [comment]
Sure, but the search operator is imo the wrong place for it. It its not really connected to the menus, and also just exists in a handful menus.

**Comment by ReinerBforartists** [comment]
The search in the add menu of the nodes editor is another operator. Not the search menu. This is implemented by us. Makes me think if it is the correct operator here.

![different](https://github.com/Bforartists/Bforartists/assets/13919702/b9845cc1-11d2-40f6-ba01-8ac3fb01edaf)

**Comment by ReinerBforartists** [comment]
Done. I hope i have covered all cases. In the add menus you can start typing without spacebar. In other menus you need to press spacebar. 

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/754ff86d-77e0-47e8-897e-def8ebd0e85f)

As a sidenote, this feature now overwrites in the add menus the good old UNIX search where you type in a letter and the corresponding sub menu expands or the corresponding operator is performed. Not sure if the Blender developers are even aware of. Ever noticed the underlined letters in the menus? That's the shortcut. Pressing T expanted the Transform sub menu here ...

![menuunix](https://github.com/Bforartists/Bforartists/assets/13919702/f3daf514-1c0a-4f5f-8b27-1afe60a50891)
