### ISSUE TITLE
Icon creation with blender_icons_update.py fails with FileNotFoundError: [WinError 2] 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3991]
Houston we have a problem. blender_icons_update.py fails with FileNotFoundError: [WinError 2] . We cannot create new icons anymore.

This happens also with Blender. I haven't found a solution so far. 

![noicons](https://github.com/Bforartists/Bforartists/assets/13919702/02196162-1257-46c8-bcbf-f9421750a415)

![iconcreationproblem](https://github.com/Bforartists/Bforartists/assets/13919702/689ec895-b2d8-4603-9a1b-dc103d9c74b2)

**Comment by ReinerBforartists** [comment]
Related: Geometry Nodes - Utilities - New Index Switch Node #3970

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/975b2456-433c-4ebb-aa77-b2adb3319c21)

Got the clue, you need Blender 3.5.1 installed.
I also am ok with python 3.10

**Comment by ReinerBforartists** [comment]
Many thanks for checking. I'll do some tests with my python installation. I guess it's Python 3.11 that could be the problem here.

**Comment by ReinerBforartists** [comment]
Have it. Phew. 

The system variables made fun with me, and switched back to Blender 4.0. So i finally fixed it with a hammer and some nails. And you really need Blender 3.6 and lower to create the icons.

A look into the Windows event viewer showed me the problem. Blender 4 crashes with the job.

![viewer](https://github.com/Bforartists/Bforartists/assets/13919702/f048f378-9a78-46bc-8022-854448ad20ee)
