### ISSUE TITLE
Outliner - Blender API - Context Menu - Select Linked needs icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3992]
![bforartists_AQiOBZQMcQ](https://github.com/Bforartists/Bforartists/assets/35357409/ff8535ba-1fef-4ae8-a9c8-d9a9ae5918da)

Icon... And also most likely documentaiton maybe? An existing icon can do here.

**Comment by ReinerBforartists** [comment]
Documenting ...

**Comment by ReinerBforartists** [comment]
Done
