### ISSUE TITLE
Linked Data - Context Menu - Library Override menu needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3996]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/044c57b2-4011-4d0f-966f-6663b35517e2)

![bforartists_v7kKMKhYKS](https://github.com/Bforartists/Bforartists/assets/35357409/723f53e6-f376-47e6-97d1-205d3a36a793)

When right clicking on a linked data area of the interface, to override it, the context menu has no icons. Icons exist, so.. should just be about assigning.

**Comment by ReinerBforartists** [comment]
Menu is here. Thee missing icons ...

![menu](https://github.com/Bforartists/Bforartists/assets/13919702/d95c63c2-893b-46e6-953d-a4412448d0c0)

**Comment by ReinerBforartists** [comment]
Woah, i am a tad bit lost with documenting this. Liboverrides always made me knots in my brain ^^

![liboverride](https://github.com/Bforartists/Bforartists/assets/13919702/aed533ba-e143-4a29-90df-8211b62b952d)

**Comment by ReinerBforartists** [comment]
Ah and the object menu has changed too

**Comment by ReinerBforartists** [comment]
Change in Object menu is documented. Remains the right click menu. I am not sure if we have this even documented somewhere ...

**Comment by ReinerBforartists** [comment]
We don't have these kind of right click menus documented at all. Not sure what to do here.

**Comment by ReinerBforartists** [comment]
Too big. I cannot rewrite big parts of the manual just to update one little menu. This is a general problem that involves lots of documents to update. And we need to decide how we do it. Will make it a task. 

Closing, the issue itself is fixed.

**Comment by Draise14** [comment]
Yeah I think we mentioned this before in another debate. Context menus are like double entries, they exist in the GUI mostly, so the operators are already documented. 

No need to document them twice. 

Maybe in the interface chapter a quick mention that the GUI has context menus everywhere can help.
