### ISSUE TITLE
Sequencer - Select menu has wrong context

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3998]
I thought I reported and fixed this one -_-

![bforartists_OGVBHmouAX](https://github.com/Bforartists/Bforartists/assets/35357409/41ea1306-fde2-4ba7-b6dd-09f2398a2b77)
![WindowsTerminal_MhBHw04ST6](https://github.com/Bforartists/Bforartists/assets/35357409/32cc52eb-0d97-4c5c-b9c3-a986a70692a6)

Also went to official....

**Comment by ReinerBforartists** [comment]
A new point release? :D

**Comment by Draise14** [comment]
Not sure if worth a point release, but it is a very big issue.. hm............ If blender does a 4.0.3, we will too.
