### ISSUE TITLE
Experimental keymap - Make Timeline marker dragging in the Animation editors Left Click

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#40]
We use currently the right mouse to drag the timeline in the animation editors. Since left click is already mapped to drag the keyframes around. The idea is to find a solution to have the left mouse button for both actions. A job for the experimental keymap.

The following ideas files and conversation is from the old Bforartists tracker: 

---------------------------------------------------

 I had a chat on facebook with a talented Blender user here in Colombia, and he likes the Lclick default, BUT didin't like how it was inconsistent in the Dopesheet, Timeline and Grapheditor (possibly in the NLA too), meaning the changes are superficial as if Blender changed to "Left Click"  in the user preferences, which is not enough elsewhere in the UI for consistency.

He requested (and I'm all for it) to change that default to Lclick drag for the timeline frame change in the Dopesheet, Timeline, Graph Editor and NLA, like most software standards.

Shall we do this in the shortcuts by default?

-------------------------------------------------

 I already tried. You can either select the elements with left. Or drag the timeline with left. Even with shift ctrl or alt i wasn't able to find a good solution. I heravily dislike when i need to hold a key for standard features.

But you can try if you can find a solution here.

-------------------------------------------------

I'll have to look at the shortcut code and check it out, see how it works.

I wonder if making the "Move Keyframe/Element" with CTRL+Lclick might solve this and still keep it standard. I personally have accidentally moved keyframes annoyingly more often than I would have liked on just wanting to move the timeline out of muscle memory.

-----------------------------------------------------

 Ctrl lmb is afaik in use already. And i think there was something with alt and shift too ...

I just remember that i ended in a bigger and bigger mess. And decided to live with the rmb to move the slider then Smile

----------------------------------------------------

 Sure, I can be assigned. Started tackling it already.

I found I can either use 'LEFTMOUSE', 'RIGHTMOUSE', 'MIDDLEMOUSE', 'ACTIVEMOUSE', 'SELECTMOUSE' on certain functions. I notice that I cannot have the same mouse button for selecting and setting timeline cursors (unless I set an IF/ELSE testing conditional?!). But since the selecting is already heavily dependant on CTRL/SHIFT/ALT already, moving keyframes with a mouse hotkey combo is easy if you are used to normal LEFTMOUSE as "move timeline" from most software - or not... not sure. Maybe reorganizing the combo LEFTMOUSE for select might.. be second nature instead of Left click/right click workflow with a weird Right click to move timeline, or weird right click to select, but more Right click timeline as being weird. Rightclick combo to select/move is also weird and still pretty much a Blender standard.

I am not sure about swapping them around in essence either. Have to think about this one.

How could you make conditionals by testing to see if keyframe is under mouse in Python?  
EDIT
I could make selections work with a left double click, and scroll with single left click maybe.. with 'DOUBLE_CLICK' as a general item selection in all views - removing the idea of a Right Click to do things (adding function to like a pie menu or something for common actions/things?)

-----------------------------------------------

 Thanks. It's better when you assign yourself at a task where you work at. Makes it easier to follow who does what.  I've done it for you now. You can grab any open issue at any point and change even the status if required Smile

And i see you start to understand why it's not so easy Biggrin

As told, i had a crack at this problem before too. And ended with using rmb then. That's imo the best solution at the moment.

----------------------------------------------------------

 Ah right. Shall do that next time.

I posted some thoughts and ideas here, to try give a crack to the whole double mouse buttons for Selection/Active workflow that is probably what is confusing people and making things a bit complicat

--

 Ok, created a test.

Things I changed:

    Lclick + drag = move timeline
    DOUBLE Lclick = place timeline
    Lclick (on keyframe or handle) = select keyframe or handle
    Rclick + drag = move selected keyframe or handle
    W = move selected keyframe or handle (like BFA, normal)

I haven't changed the VSE system that much, but the Dopesheet and Timeline and Graphsheet and I think NLA work this way.

I noticed this is good for BFA because..there is a double entry here, you press W to move things, or you select and drag. I prefer the command of moving things intentionally instead of accidentally moving them when selecting. So select THEN move is a safer, solid way of animating (in my opinion). I don't know of other software that allows me to move things without having them selected first in action. It's just logical. This Lclick to timeline makes things just.. more standard, but also give the Rclick + drag to move selection still possible a la Blender (but as a secondary action). Also Rclick CLICK or RELEASE can be used for a BFA Pie menu system later on in life. 

Other things you can test out is the outliner:
Lclick PRESS + drag = box select (with Shift remove, Ctrl add, etc working after dragging)
DOUBLE Lclick (not on name) = select what is highlighted
Shift + DOUBLE Lclick = unselect highlighted

It has proven quite useful.
[bforartists - full - ver 0.6.py_.zip](https://github.com/Bforartists/Bforartists/files/1799221/bforartists.-.full.-.ver.0.6.py_.zip)

--------------------------------------

Thanks Draise, I will have a look at this solution Smile

 Hmm, i had a look at it, and am not convinced, sorry. The solution is not bad. But for me there is no win, but some losses. It's what i have feared.

The User now needs a tutorial for how to move the keyframes. The former solution with RMB to move the slider may be nasty and uncomfortable, but is easier to discover and to use. And now you need a hotkey to move the keyframes.

Other opinions here?

---

>      Other things you can test out is the outliner:
>     Lclick PRESS + drag = box select (with Shift remove, Ctrl add, etc working after dragging)
>     DOUBLE Lclick (not on name) = select what is highlighted
>     Shift + DOUBLE Lclick = unselect highlighted

Nice improvements. Border select conflicts with the standards though. It's not a good idea to have different standards across the editors. But traditional border select still works, so i don't mind.

Shift click has a problem though. You first need to border select, then hold down shift to subtract.

----------------------------------

 Yeah, the Border Select tool then Shift to change the modification is standard use in Blender...=( I tried to make that work easier, but couldn't get it going right. I'll try again later. You have to activate the tool first before hitting a modifier. I'll give that another go.

Not sure about your statement on the tutorial to train the Lclick timeline workflow... out of personal experience and training animators to work with Blender/BFA, I've had to teach the latter - how to move the timeline naturally, the more needed function. Rclick + drag to move keyframe is discoverable as much as moving the time line is in the Rclick, and Lclick to select a keyframe is normal expected use, and Lclick for timeline move is expected use in all animation applications I've used (other than Blender), and timeline change is the more common action over moving a keyframe , ultimately being that the debate be that the timeline should be Lclick, the dominant mouse click for the dominant timeline use. I am.. just thinking about the work with animators that I hire and have worked with and that is what I've noticed. And it's also first complaint they usually have.

I will do an evaluation based of a 3 step animation process me and my team have used, and others I've worked with, a 1. Blocking, 2. Timing, and 3. ANIMATION CURVE EDITING. The latter sometimes is a step we skip entirely for production efficiency purposes.

Goal:
Have Lclick be the dominant selection and timeline change system and Rclick as secondary function based off animation requirements and workflow to make the process organic and easy to train, saving time and animation difficulties.

Original Setup debate:
BLOCKING: Lcick move/pose then Rclick to change timeline makes a double finger alternating mess, less organic, harder to train animators after their other typical software muscle memory with only Lclick. Ultimately making the software less compatible with local animation talent from the getgo without training.
TIMING: Lclick to select and drag keyframe/handle has quick timing and curve tuning, also it is quick to move timing around after Blocking (which arguably is a task less required if animator does good blocking from the get go, making moving keyframes secondary), but this system also creates a finger alternation like mentioned earlier when changing timeline to see how changes look, making animating review slower with holding down Rclick more than Lclick in use and time, or having to play back animation from a time point or beginning with keyboard shortcut or switching to another view/toolbar to run animation controls - specifically normal if you're working from the dopesheet that have no timeline controls (and you know FPS in blender is terrible making playback choppy or very slow so timeline drag is best quick review solution) = stressing the less dominant finger over time for the more dominant action. 
ANIMATION CURVE TUNING: Modifying curves and keyframes with Lclick + Drag is easy, organic, and expected use - but from old muscle memory, triggering a timing error is very easy by having/adding selected keyframes then forgetting it was selected and moving, or by just trying to change selection moving old selection when you try move something else by missing a handle/selection then moving the timing of keyframe/old handle, thus moving all those frames/selections out of time from the previous step already established - with workflow being often with the ESC or Rclick at the ready to cancel, or by adding the concept that you have to Deselect before Selecting just to be sure you don't make a mistake, a new selection to move (by pressing A) workflow = adding time to the process by canceling often done from accidental timing changes on finetuning - ultimately adding time to the finetuning process overall; and out of experience I have had experienced to novice animators do this issue more than once where their final animations become corrupt from another user or the same animator accidentalliy moving things around from old muscle memory (instead of checking timeline to check animation/poses) - backlogging previous blocking/timing animation work on the final finetuning step making production even more expensive and time consuming as we fix accidental frame shifts repeating previous work.  

Things you'd win with the setup I propose:
BLOCKING: Lclick move/pose then Lclick change timeline to keyframe (with autokey) = fast blocking/posing, organic workflow, compatible wiht other animation workflows in other software.
TIMING: Rclick to drag keyframe without shortcut (feels similar to Rclick to change viewport) = fast (like Lclick + drag of BFA, though needs fixing as mentioned below) with secondary function of a dopesheet/timeline as discoverable as the primary action on a secondary mouse currently in BFA, moving the timline. Also feels like what a viewport Rclick is, changing perspective in 3D, like changing time perspective in the 1D environment of a timeline = creating consistency with the Lclick/Rclick workflow. Lclick is dominant timeline function to review timing, Rclick secondary to move frames/handles (or hotkey like the rest of the UI with W as move anything)
ANIMATION CURVE TUNING: Lclick select then T to change curve type, preserved functionality from earlier, but with added timing security = fast curve finetuning without risking changing timing on selection with work you'd have done in the Dopesheet timing/blocking process - with the option of Select+drag as secondary Rclick for a quick single click editing.

Improvments I can try implement to the proposal: 
It may feel like we loose a function from BFA, because we do.. the Select + Drag in one click press. I could try add Rclick PRESS to also select keyframe like Lclick RELEASE so the Select + Drag workflow with Rclick would be functional just like it was with Lclick PRESS + drag originally in BFA - essentially adding the timeline use as priority in Lclick, yet still have Lclick selection on keyframe (added functionality over BFA and consistent with other software) and also have the Rclick + drag functionality preserved from BFA just swapped over as a secondary action. You can see pro's to that mentioned above.

In general, for animation typical use of a timeline/dopesheet is moving the time over a time/frame count marker/time bar with Lclick, then Lclick+drag on frames/handles to move them - but keeping it all Lclick. We can't do that out of the sourcecode design. But it's what animators are used to, and these are the least technical 3D artists I know of... They are not used to alternating mouse buttons - but if they should learn to use the Rclick and alternate, it should be for a secondary action in the animation process - which is changing what they animate with new timing or different handles - not the principal method of how they work, with the timeline change and review hand in hand with the Lclick posing. 

---

 Feedback anyone?

I have updated the shortcut layout to fix a bug I found with a test build (the transform.translate/transform.rotate/transform.resize has somehow been somewhat deprecated and sometimes won't work unless I assign the old Blender transform.transform + modal).

I also finetuned the Lclick workflow.

    Lclick RELEASE = select
    Lclick PRESS and move = move timeline
    Lclick DOUBLE = place timeline
    Rclick PRESS and move = move keyframe/handle
    Rclick PRESS = select keyframe/handle (double entry, still not sure)

Please test, see if that solves the issue that I had on the previous!
[bforartists - full - ver 07py.zip](https://github.com/Bforartists/Bforartists/files/1799224/bforartists.-.full.-.ver.07py.zip)

I will close this once I finish checking the Full BFA Shortcuts, then make a duplicate with this system for user choice or personal use and upload it here.

**Comment by ReinerBforartists** [comment]
Postponing until the new keymap for Blender 2.8 has settled.

**Comment by Draise14** [comment]
I found a way to do this and mapped this. The Press Drag and Tweak is controllable. It's amazing! Everything in left click!

I'll upload the map soon.

**Comment by ReinerBforartists** [comment]
I am still a bit worried how it works. Looking forward to it :)

**Comment by Draise14** [comment]
... why had this closed when I haven't committed it yet?

**Comment by ReinerBforartists** [comment]
*slaps itself*

Added the task label, sorry ^^

**Comment by Draise14** [comment]
Ok, worked on this. 

## Conclusions:
- Graph Editor has to work in a different way than the timeline, dopesheet and NLA to unify the Lclick timeline drag and keyframe/handle manipulation. 
- Dopsheet works fine, but timeline dragging cannot be done below the tracks - now it's context sensitive?
- NLA works perfectly fine
- Sequencer works perfectly fine
- Clip Graph editors needed a workaround for Lclick - using NS tweak to move keyframes (they can not move EW natively) and the EW tweak is to set the time now - all left click
- Graph Editor has Lclick select to move the handles and keyframes, but you need to deselect to move the timeline with Lclick - like the time is locked when editing. I could not work around this in a predictive way (sometimes it works, sometimes not as expected through other systems - due to the tweak/drag system overlapping on pixel distance).  _I am wondering if I should adopt the same workflow of the Clip graph editor with EW tweak and the other tweak directions to edit the handles and frame times/position..? _
- To work around the graph editor issues, I made it easy to deselect (right click or double Lclick)

Extras:
- I added the double operator unification from **Related Task:  #620** to test the WER transforms with the widget activation. Press W and when dragging you are instantly transform though the legacy tool - though it was not active. Place and the translate widget will be active after entering the transform mode, and normal workflows continue without having to press the W hotkey again (or you can if you'd like). Widgets toggle really nicely, and visual feedback on the tool is wonderful and makes the toolshelf tool more responsive with the legacy tool working on the hotkey. 
- I also added double tap to toggle the widget so that they disactivate and you go to normal position/select tool (for quick pushing of vertices, objects, etc). 
- I found out this system works really well and can work for most tools using the Click Drag on legacy tools and activate the widget at the same time (and it hotkeys up the toolbar and adds visual feedback)

**File added:**
`bforartists experimental - Lclick Animation.py`

**Comment by Draise14** [comment]
Ok, last commit, I really should stop doing that and just test test test till it's perfect.

**Update**
- The Graph Editor now is unified with the L click for timeline and manipulation. It is more predictable now. You can have some (if you are exact) ability to click on an unselected frame and manipulate it - then move the timeline if necesary later.

**Comment by Draise14** [comment]
Ok.. forget that solution. 

I have overwritten to make the Graph Editor have the same tweaking system as the clip graph editor. Now EW is timeline and any other direction is to transform the selection. 

Now everything is working all well in Lclick. No need to change any thresholds in the preferences (better).

**Comment by ReinerBforartists** [comment]
*carefully keeps hands away from close and comment button*

Take your time. And no rush. Better check for conflicts and quirks one time too often. I'll have a look at it in the next days :)

**Comment by Draise14** [comment]
Here I am just trying it out and showing how it would work. 
https://youtu.be/wochZPGNqsI

**Comment by Draise14** [comment]
@ReinerBforartists had a chance to test it out? Just to see if the concept is working - before I start cleaning it up.

**Comment by ReinerBforartists** [comment]
Dang. I knew i had forgotten something XD

Thanks for the reminder. Checking now :)

**Comment by ReinerBforartists** [comment]
Hmmm, i have some bad news for your idea. I find the slider behaviour quite annoying. Sometimes i move the slider, sometimes i move the selected keyframes, sometimes i deselect the keyframes, which is the most fatal thing here. You shouldn't randomly deselect your selection. And i can't figure out under what circumstances i do what. And i also fear that this is not to control by the average user.

What alternatives do we have here?

**Comment by ReinerBforartists** [comment]
There is a problem in your keymap. Please check console.

![keymap](https://user-images.githubusercontent.com/13919702/53585397-1bd34d80-3b86-11e9-96be-f7a954e5a25b.jpg)

**Comment by Draise14** [comment]
As mentioned, needs some cleaning up. 

Yeah, the double Leftclick to toggle selection isn't a good idea and it's a double entry. I''ll probably remove

## Dopesheet and Timeline behaviour:
**Location - keyframe track:**
Click on keyframe, select
Click drag on keyframe, select and move
Click off keyframe - deselect
Click drag off keyframe with keyframe selected - move keyframe
Click drag off keyframe without selection - move timeline
Riclick - deselect keyframe
[defunct] Double Lclick - toggle selection/all

**Location - off keyframe track (below on empty space):**
Click drag keyframe selected - move keyframe
Click keyframe without selection - move timeline
Riclick - deselect keyframe
[defunct] Double Lclick - toggle selection/all

**Comment by ReinerBforartists** [comment]
To make it short, i am against click drag in the time line.

When you need to explain a behaviour indeep, then you are already at the wrong track. The behaviour should be self explaining. Click drag is not self explaining. And something to drive the users crazy here i fear. I know how it should work, and had big trouble already.

**Comment by Draise14** [comment]
*slaps fore head* 

You have to click drag with Rclick to move the timeline anyway. 

I'll keep testing and put my animator friends on it to finetune. They are very keen to have it all in one click. Rclick to move the timeline still isn't logical or intuitive. The only complication is now it's context sensitive to where you click and drag things - as most software is. At least with Lclick has a visual to kinetic discovery to it, not an exclusive kinetic discover with two mouse buttons.

**Comment by Draise14** [comment]
Is the issue mainly because when you move the timeline, it deselects the keyframe?
And/Or do you miss the single click = place timeline workflow?

**Comment by ReinerBforartists** [comment]
Draise the issue is that i randomly deselect the selected keyframes or move the keyframes instead of moving the slider. It conflicts. And this conflict is not to solve from what i can see.

**Comment by Draise14** [comment]
The random deselection is something I will fix (and then the result is as predicted, if you click off a keyframe - like in the original - you deselect it). 

The moving of a slider and of the keyframe conflict is a rare occurance which depends to the speed you tweak/drag the mouse and where you click and drag - it is very rare taht if you click and drag on a keyframe that you'll drag the timeline, as most predicted movement is click on a keyframe and drag, move the keyframe. Click off a keyframe and drag moves the timeline. You will drag the timeline if you miss clicking on a keyframe to drag it.

The only context is one you had never had to worry about in Blender/BFA is the empty space (not a keyframe track), will only drag what is active, or default on timeline drag.

**Comment by ReinerBforartists** [comment]
I know that i have to click drag. But it nevertheless fails. Sometimes it works fine. Sometimes i can get it one out of three times to move the slider, and not the keyframes. And sometimes i can't even move the slider at all. But am stuck at moving the keyframes around. I can't find the right behaviour to get the slider to work proper. And again, i know how it is meant to work. It just does not work.

The average user does not even know all this. And will get even more mad at the erratic behaviour. And even when you could get it to work to in 100% of the cases, giving the average user a tutorial for a simple thing like moving the slider is no option. Bforartists stands for simplicity and a self explaining and easily discoverable UI.

Draise, i would be as happy as you to get it to work in your way. I just can't see it happen. This conflict is unsolveable with a dragclick. And as sorry as i am, this feature will not make it into the main keymap. We need to search for another way here.

**Comment by Draise14** [comment]
AHA!

I now know why it''s not working for you. I know why it''s random and erratic, and this is because the click/drag threshold and tweak are not what I was troubleshooting to make the system work, but the factory default - those settingss they are not predictable nor workable, as you say. 

Here is the video to show how predictible and intuitive it can be with the preferences tweak.  

https://youtu.be/aJQnpJqSOw4

![carnac_2019-02-28_14-47-27](https://user-images.githubusercontent.com/35357409/53593933-cb4cf780-3b67-11e9-96dc-a0e04b71ea84.png)

**Comment by Draise14** [comment]
The error in the console also works with the default keymap on factory reset, mainly due to clicking on an empty space in the dopesheet/timeline. This is not the experimental map. 
![carnac_2019-02-28_15-03-42](https://user-images.githubusercontent.com/35357409/53594964-0fd99280-3b6a-11e9-876c-7d44fc751788.png)

I highlighted the area where the clicks work. 


Blender 2.8 Beta does the same, so must be a bug. 
![2019-02-28_15-09-51](https://user-images.githubusercontent.com/35357409/53595323-f38a2580-3b6a-11e9-9bec-b941dd8e9303.png)

**Comment by ReinerBforartists** [comment]
That's another bug :D

The one that i mean is when you switch to your keymap. How do you create it? By saving it out? Or do you manipulate the code?

![error](https://user-images.githubusercontent.com/13919702/53619263-fc243f80-3bee-11e9-9b20-cc767a97bb45.jpg)

**Comment by ReinerBforartists** [comment]
Just curious, where do you get the Tweak threshold from. It doesn't exist (anymore?)

![tweakthreshold](https://user-images.githubusercontent.com/13919702/53619531-f549fc80-3bef-11e9-93ad-e4b60764bf63.jpg)

**Comment by ReinerBforartists** [comment]
I have toyed around with a threshold of 15 now. And have still the same result. Sometimes it works, sometimes not. Sometimes i select or deselect all. The double click comes in the way here (Makes me think if double click for select deselect is really a good idea). This method is not reliable.

The problem is not one of tweaking. The problem is a systemic one. The user will not distinguish. He will try to  use the same method for both elements. He will click at the slider, and try to drag it. And he will click at the keyframe, and try to drag it. And will very often end in unexpected behaviour.

Draise, i know that you have fallen in love with this method. But sometimes you simply have to let an idea go. We can't do this.

**Comment by Draise14** [comment]
I have removed the double click and will send the one that doesn't cause me errors and will recommit. I will also rebuild (haven't since last week) try again with the dumbed down drag settings. I am not giving up on this because it seriously was working and the bugs you reported on it have been reproduced and fixable. 

And oh God... I think I remember Pablo Vasquez mention they removed the double tuning to unify those settings recently... "Because no one will understand them..." Idiots. Now tweak and drag is the same?! 
They just killed a feature! One has to be less than the other, or else one won't work correctly together and it works better with drag higher than tweak. The name convention makes sense. Tweak, move little, drag move alot. It's like assigning the same hotkey to two operators. Grrrr.... Are they phasing out tweaking? This is depressing. Not love. Depressing.

**Comment by Draise14** [comment]
They removed it as the Drag settings were influencing UI button/panel drag - so should be hidden. 

https://developer.blender.org/D4322

I found out that the system can still work predictably. I have made the timeline also limit to East West tweaking and a double click just places the timeline. The rest is working as expected. 

**Pro's** - all one click, things change where you click. It's self explanatory, no hidden functionality in a right click. Frees up the right click for context menus, pies, or more. Dragging can also add box select in diagonal angles if necessary (in dopesheet for example)
**Con's** - if there are frames on every frame, scrubbing is tricky unless you zoom in, unless you double click to drag timeline over the frames. Also, minor weirdness, graph editor instant drag left and right won't move the frame, but the timeline, but editing frames is typically diaganol movements or updown movements, so no biggie. 

I'm going to put my lead animator on it and do a rigged animation to test it out and see how he feels, then I'll get another animator friend of mine to test it out. 

But it's working predictably again in the latest commit.

**Comment by ReinerBforartists** [comment]
Nope. Still absoultely unreliable, sorry. 

When i click at the marker then i want the marker to move. Not the selected keyframes. And this part does simply not work.

**Comment by Draise14** [comment]
What do you mean? The marker cannot be selected natively even in rightclick, it can be dragged or placed.

**Comment by ReinerBforartists** [comment]
I mean that i cannot drag it. It does not work 9 out of 10 tries. I move the selected keyframes instead. It is the concept that is flawed. But i start to repeat myself.

**Comment by Draise14** [comment]
![carnac_2019-03-01_13-32-34](https://user-images.githubusercontent.com/35357409/53658331-791edb80-3c26-11e9-92cc-a6a06d3a62d4.png)

How are you not making this work? Can you record it? 

If you click on a keyframe and drag it, as predicted: you will move that keyframe. Like click dragging on any file in any explorer. 
if you click in any empty space on tracks or double click, you will drag the timeline (unless you click and drag below the tracks, then it will drag selection like normal Blender/BFA behaviour).

**Comment by Draise14** [comment]
Ok, I see what's going on. it's compiling the keymap incorrectly, thus the bugged out console. Also, a whole bunch of the work I did is not transferring with the bugouts. Importing manually works fine.

Try this one and drop the drag threshold to something like 5px. 
[bforartists experimental - Lclick Animation.zip](https://github.com/Bforartists/Bforartists/files/2920766/bforartists.experimental.-.Lclick.Animation.zip)

I re-committed to see if that would fix the console bugs.

**Comment by ReinerBforartists** [comment]
> If you click on a keyframe and drag it, as predicted: you will move that keyframe. Like click dragging on any file in any explorer.

Works

> if you click in any empty space on tracks or double click, you will drag the timeline (unless you click and drag below the tracks, then it will drag selection like normal Blender/BFA behaviour).

Fails. Double click see below.

> Double click and you place the timeline

Works

> Click one in empty space and you deselect it.

Deselect what? Timeline? It is not selected.

> You can now rightclick to add some kind of new functionality, like a pie or context menu.

That's not part of this task. And currently the RMB is still occupied with RMB to set the marker.

**Comment by Draise14** [comment]
> Deselect what? Timeline? It is not selected.

Deselect the keyframe. Normal behaviour. 

> Note, you can move the slider when nothing is selected. But that's not an option. We must be able to move the slider with keyframes selected too.

Just a question. Why do we need to preserve dopesheet selection when moving the timeline? 

The unfortunate thing is the way the **action.clickselect** works is that it will always deselect if you click off a frame with the same click, you can't make it stay selected once clicking anywhere outside the keyframe. Selection would have to be something else which is back at square one, two mouse buttons for an expected workflow .. They could all fix this if they jsts made the cursor selectable instead of the placing/dragging workflow they have had for a long time. 

So clicking in an empty space to move the timeline as ideally the case, is impossible to preserve selection. Clicking in the lower empty space is also not ideal as it will drag the keyframe instead of timeline till deselecting the keyframes. 

You also don't want to click anywhere to place the timeline with the same controsl as moving the keyframes, as you may want to move/select a keyframe and not the time anyway, so it's working - it's just deselecting as designed. 

> EDIT, i think i said it before. You should not hand edit the keymap python file if possible. Do the modifications in the key manager in the user preferences. Then save it out.

Yehp, I have since the beginning for this experiment. I am not sure what the issue is - but now I'm tired.

**Comment by ReinerBforartists** [comment]
>Just a question. Why do we need to preserve dopesheet selection when moving the timeline?

Because you may want to select some keyframes, move the timeline a bit, and drag the selected keyframes to a new position. And parts of this selection may be out of view then. You can't select this parts then anymore though, they are out of view now.

> EDIT: just to say, my animator says that when you move the timeline, the keyframe deselects - it is how Krita and Flash work, they deselect the frame to move the timeline, it is not annoying and not a requirement to animate.

For me it is. Both ^^

As told numerous times now, your way is a dead end. It will not go into Master. We need another solution here.

**Comment by Draise14** [comment]
Oh well. Was with the effort. 

Criteria:
1. Needs to move the timeline with the same click as move keyframe
2. Needs to select and move keyframe on one click 
3. Needs to click drag then move keyframe without moving timeline
4. Needs to click drag then move timeline without losing selection not transforming keyframe.
5. Needs to deselect when clicking on empty space. 
6. Timeline needs to be placed on click over keyframe and empty space, without losing selecting. 

Because of the criteria the logic is impossible with the current code. You cannot select the timeline. You cannot stop the deselecting when clicking off a keyframe. The only way around this is by making the cursor a handle you need to select to move like most 3D software in their dopesheets. 

I can see now why the criteria won't make it work even with the new click drag is because the way Blender and Bforartist handle time is flawed in essence with a game you cannot select and move for the gain of time placement and time movement. 

To put it all in one click requires modifier conditionals and the simplest is the two mouse button system instead of a hotkey. 

The rest would it could be a double click but that is more annoying than a right click. 

Sigh. Was worth the effort but damn... So many hours lost. 

In Graph editor the all left click system was working, selection preserving. But dragging directly left and right to retime a frame instead of it's value was a little tricky. This system cannot transfer to the dopesheets or other track systems.

**Comment by ReinerBforartists** [comment]
I feel with you. I know how hard it is to let some ideas go ^^

**Comment by Draise14** [comment]
I guess now I know what is needed. A time track and time handle like with the standards and define the edit section. Then it's all useable with one click in the space. Worth proposing a mock-up and the pros in Right-clickselect.

**Comment by Draise14** [comment]
This issue now has a new header timeline with the latest Blender updates that can be assigned to Lclick, freeing up the Rclick. 

Now there is a time header, and a workspace. This adds a new Lclick context.

**Comment by ReinerBforartists** [comment]
Indeed. This makes this task here obsolete. You have your LMB solution now :)

Let's close this issue.
