### ISSUE TITLE
Compositor - Split Viewer now updated to Split utility node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4001]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/213cb02d-9776-4349-9a00-165483b4253f)

Split viewer now.. a utility with an image out. Sidebar needs updating. 

Related documentation task:
https://github.com/Bforartists/Manual/issues/544

<details><summary>Details</summary>
<p>

SHA-1: 153f14be2b67fba0d3d92eb08eff7659f2dffae7

* Compositor: Make split viewer a regular split node

Changes:
- Renamed Split Viewer Node to Split Node
- Split Node is now under `Utilities` (similar to Switch node)
- Versioning: split viewer from 4.0 and before is replaced with the new split node connected to a new viewer node.

Pull Request: https://projects.blender.org/blender/blender/pulls/114245

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/f8c5cb8c-7810-4c96-9672-c46e4f536c95)
