### ISSUE TITLE
Geometry Node - Input - Active Camera

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4004]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0fa7d8d0-8970-4848-8ab2-2b4c9e1f2b73)

New node, new... routine. You know the drill. 

_Come to think of this, this would make my painterly camera reliant system much easier to link and override without selecting cameras over and over and over again.. NICE. Good call Blender. _
<details><summary>Details</summary>
<p>

SHA-1: 75f160ee96b93b7438c4e5900e93d7332fa1d323

* Geometry Nodes: Add Active Camera input node

This adds a new "Active Camera" input geometry node, per #105761.

The node outputs the the scene's current active camera. It is available
from Input > Scene > Active Camera in the geometry nodes Add menu.

Typical usage would be to connect this node to an Object Info node to
obtain its transform. This works as expected when the camera's
transform is animated, and also when there are markers on the timeline
that change the active camera.

In order to support the aforementioned changes in the active camera,
this implementation adds depsgraph relations for all cameras referenced
by timeline markers. This eliminates the complexity of updating the
depsgraph whenever the scene switches to a different active camera,
but of course it comes at the cost of including more objects than
strictly necessary in the depsgraph for scenes that switch cameras.
Dynamically updating the depsgraph upon camera changes could be a
future improvement if there proves to be sufficient need for it.

Pull Request: https://projects.blender.org/blender/blender/pulls/113431

</p>
</details>

**Comment by Draise14** [comment]
Probably should catch up here...

**Comment by ReinerBforartists** [comment]
Documenting 

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/550da376-4b31-4427-b468-0b6bb3915054)

**Comment by ReinerBforartists** [comment]
Done
