### ISSUE TITLE
Graph Editor - New Bake Channels operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4005]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/eb1d2731-4b92-4e56-987a-f5fa631d1387)

They added it back! Yay, with internal api now. We have an icon for this, so means updating and copying and pasting the documentation from the NLA or Dopesheet. 

<details><summary>Details</summary>
<p>

SHA-1: 1e931f5bd7e5177071efec26463a29034d955616

* Anim: Bake Channel operator

This is a replacement for the workflow that uses
"Bake Curve" and "Unbake Curve" to quickly generate
dense key data.

Compared to the existing workflow it has the advantage
of allowing the user more control over the key types,
and distance between keys, as well as the frame range affected.

Operator options

* Range: the range that will be baked.
Defaults to the scene range or preview range.

* Step: Distance between keyframes.
Can be used to bake on 2s or even bake to subframes.

* Remove Existing Keys: Boolean option that
if enabled also removes keys outside the specified baking range

* Interpolation Type: Choose a interpolation mode used
for new keys e.g. Constant or Bezier

* Bake Modifiers: If enabled bakes the effect of the
modifier stack to keys and deletes the modifier stack.
If false, the code disables the modifiers before baking,
so the resulting keys will behave as if the modifiers didn't exist

The operator can be found in the Graph Editor under `Channel->Bake Channels`

Part of: #111050

Pull Request: https://projects.blender.org/blender/blender/pulls/111263

</p>
</details>

**Comment by ReinerBforartists** [comment]
Did we have an icon for this? I made a new one for the node :D

**Comment by ReinerBforartists** [comment]
Hmm, we have bake keyframes and bake action. But no bake channels.

**Comment by Draise14** [comment]
It works similar to the Bake Keyframes operator, it... as a UX, the same thing. So I'll use the same icon as the Bake Keyframes.

**Comment by Draise14** [comment]
Ah, icon is there. Reviewing documentation.
