### ISSUE TITLE
Windows 11 - Pinning "bforaritsts.exe" to taskbar makes a "bforaritsts3" shortcut, file description needs update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4006]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/622e8fcb-d5fa-408a-b744-e07a9ebfee55)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/12ba313a-18c3-4cdf-aa94-639ba58a4ff4)

Right now, if you right click on the Bforartists.exe and pin to taskbar in Windows 11, it will create the shortcut file as "Bforaritsts3"

You can access Windows Task Pinned Shortcut Folder from Windows Run :

1. Windows + R
2. Type : shell:User Pinned\Taskbar
3. Press "OK" or "Enter"

This is due to the file description being set incorrectly
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f7a8f4f6-7504-48ca-92b0-926c8fc71578)

**Comment by raindropsfromsky** [comment]
Even the **Product name** field reads "Bforartists3" instead of the correct version.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b13a0e4e-d5c3-4173-b39c-955f987bfeb0)

Found it.

**Comment by raindropsfromsky** [comment]
Is this inserted manually? 
That's error-prone if the versions change frequently!

**Comment by Draise14** [comment]
These are not manual, but compiled. Version bumps happen every 1-2 years, so it's not frequent. Will keep it in mind for Bforartsts 5.0.0 slated 2025 or 2026

**Comment by ReinerBforartists** [comment]
What to change with a release is documented. But thanks to iyads fabulous changes we all thought it is autmated nowadays ^^
