### ISSUE TITLE
If debian package name was lowercase again

### ISSUE THREAD

**Issue by eMPee584** [Bforartists/Bforartists#4007]
![Bforartists-4 0 2](https://github.com/Bforartists/Bforartists/assets/1227833/6d88272c-f0c1-416b-8297-e1d3de6904c1)
.. my build tool would not obstruct 😅 (i guess)

**Comment by ReinerBforartists** [comment]
Ah, my bad. In the window world there is no difference between upper and lower case. So such things slips through.

So we need to deliver it with lowercase in the future?

**Comment by ReinerBforartists** [comment]
We talked about it, and we will have a look to deliver future versions with lower case again.

Many thanks for the report.
