### ISSUE TITLE
Fix the layouts

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#401]
Blender comes with lots of new layouts. We need to improve them one by one. For example, in 3D View, keep the properties window open. Modeling layout is not required at all. You switch to Edit mode, and here we go. And why does Texture painting require a own layout? This can be done in UV Editing layout or in Default layout. Shading does not require a file browser. And so on. Toolbars with TWO rows, not one ...

Our Toolbar should be open in all layouts, with the required tools.

Hide the editortype menus!

The switching between layout should also be consistent. For example, having the Image editor at the right side in UV Editing so that the Viewport at the left does not jump away ...

**Comment by Draise14** [comment]
This one I can do.

**Comment by ReinerBforartists** [comment]
Then assign. That's what the tasks are for  ;)

**Comment by ReinerBforartists** [comment]
Ah, forgot, please wait a few more days until the 2.8 stuff is in the master ...

**Comment by Draise14** [comment]
Hey there. I'm traveling in holidays right now and will get back to my studio this weekend. 

ETA is next Tuesday 8th. 

I can either unassign here to free up other tasks or take both startup related tasks for tuesday. What do you think?

**Comment by ReinerBforartists** [comment]
Ah, so you haven't started yet. No hurry. Relax and enjoy your holiday :)

You can assing to the other startup.blend related tasks then if you want. And when there is really something important, then i can still fix it immediately as long as you haven't started work yet.

**Comment by Draise14** [comment]
Righteo!
I'm gonna list my tasks for Monday for when I get to work. 

- Composite and Material layout can be the same (evaluate layout differences and uses)
- UV and Texture paint can too (evaluate viewport context and differences)

- [ ] hide editor type menus
- [ ] add header toolbar with common setting in all layouts
- [ ] remove redundant workspaces to limit all to 7 (brain limit concerning options count)
- [ ] keep properties view open 
- [ ] toggle properties panels to start closed
- [ ] mirror layouts from BFA 1 where applicable
- [ ] make all toolbars two column?
- [ ] add animation toolbar in footer in animation layouts? (NLA and Fcurve editor still have no native animation controls)
- [ ] rename workspaces to pipeline related names instead of workflow names?

**Comment by ReinerBforartists** [comment]
Looking good :)

**Comment by Draise14** [comment]
Ok, compiling and testing things now, ready to work on it tomorrow - it's taking a little while, but just wanna make sure I'm doing things right.

**Comment by Draise14** [comment]
Ok, can compile a new **Startup.blend** file, but found out there is a new template system with up to 4 different startup files that it pulls from to create new layouts and new tabs... meaning more work than expected. Might take me a bit longer to make sure it's all working smoothly. 

![explorer_2019-01-08_10-47-27](https://user-images.githubusercontent.com/35357409/50841776-71803c00-1333-11e9-9731-ffc302d9a1e1.png)

**Comment by ReinerBforartists** [comment]
Woah, have they changed the whole system? O_O

**Comment by ReinerBforartists** [comment]
Where do you find four different startup.blend files? I have just one here. And there is just one that you can save from the File menu.

**Comment by Draise14** [comment]
When you create a new workspace there are subcategories.
  
![blender_2019-01-08_11-58-01](https://user-images.githubusercontent.com/35357409/50846234-aa70de80-133c-11e9-8814-c404a852f753.png)

Here are those files with those layouts: 
`\Bforartists\release\scripts\startup\bl_app_templates_system`

**Comment by Draise14** [comment]
Ok, I compiled to test with the new **startup.blend** and got an access violation. Load Factory settings closes BFA, can't open BFA on new build. Something must be corrupt with the way I saved the startup file. 

![powershell_2019-01-08_12-32-05](https://user-images.githubusercontent.com/35357409/50848186-8b288000-1341-11e9-9b23-5e9b18202bb1.png)

Found out that creating from the general file (default startup.blend) that the toolbar goes corrupt. It is turned off in the default. Maybe this is the cause of the crash. 

![bforartists_2019-01-08_12-39-18](https://user-images.githubusercontent.com/35357409/50848507-77c9e480-1342-11e9-9f88-0338012e853c.png)

![bforartists_2019-01-08_12-40-39](https://user-images.githubusercontent.com/35357409/50848586-aa73dd00-1342-11e9-91d3-f7460fad5ae6.png)

Now.. how to make it store that settings in a build. I think this setting is a **userpref.blend** stored data. 

I still need to fix the workspace templates as they do get compiled into the build and to make new workspaces the default startup.blend is the "General" spaces and the other files are the other ones like 2D Animation layouts.

**Comment by Draise14** [comment]
It's a simple fix, I saved userpref separate from the startup file. Recompiling to test.

**Comment by Draise14** [comment]
Ah, that was it. Nice.

**Comment by Draise14** [comment]
Made a new branch **bfa2_defaults** and committed this. I think I accidentally made another one BFA2_defaults.

**Comment by Draise14** [comment]
Since I collapsed all of the top toolbar (it's a double menu entry), in Sculpt and Texture paint mode the brushes options is now in the properties view - you have to cross the mouse over and back the whole screen to change settings quickly. I am wondering if properties with the toolshelf both on the left is the way to go? Or to have the top toolbar options open in some layouts (though it cuts before the toolbar icons). I can see it as something organized and handy for these kinds of workflows - if only it was more flexible/positionable/customizable (or part of the BFA toolbar). 

![bforartists_2019-01-08_20-12-32](https://user-images.githubusercontent.com/35357409/50869388-c34fb300-1381-11e9-955a-98804d5e1d3f.png)

**Comment by ReinerBforartists** [comment]
Don't even try to fix everything at once here. One step after another is the way to go. Issues in question should be separated. Like double menu entries. They can and should be fixed at a later point and in its own task then. 

This task here is to fix the layouts.

**Comment by Draise14** [comment]
OK.  I'll just BFAize the new workspace templates that are left and close this task - then work on individual workspace case by case tasks.

**Comment by ReinerBforartists** [comment]
Yes, the smaller the task the better it is. It's also better to follow in the commits what changes did what then.

**Comment by ReinerBforartists** [comment]
Deleted the branch BFA2_defaults

**Comment by Draise14** [comment]
Sure. Sounds good. Again this is my first collaborative programming thing as I work principally as an artist, I'll get there! 

**So workflow for committing:**
1. Assign to a task
2. Do work
3. Create and push to a branch to not "eff up" the master
4. While working, merge branch with master when applicable
5. When I push, commit using the task name + number and exclusive descriptions
6. When done, request a pull request to merge to master

Eg, 
#401 fix the layouts: added templates with Bforartists standards to 2D animation, VFX, *etc* - closing toggles, adding toolbar, mirroring BFA1 templates and closing panels, also adding animation toolbar/dopesheet where required. 

Like that?

**Comment by Draise14** [comment]
Ok, done, committed to a branch called **401_layout_fix_branch**

Pull request done. 
https://github.com/Bforartists/Bforartists/pull/535

- Default: added rendering workspace (as it's everywhere for now)
- 2D Animation: added toolbar and hidden view toggles, fixed animation
- Sculpting: updated sculpting and materials from defaults
- VFX: updated compositing, motion tracking and rendering from defaults, updated masking to toggle viewport toggles, updated animation editors, made layout more consistent, added toolbar
- Video Editing: updated video editing and rendering from defaults
- All: made sure toolbar was activated on default

Things I didn't do:
- remove the cube, lot's of discoverable features using the workspaces gets activated on the object, which I think is good for newbies. 
- remove filebrowser from video editor and materials, for now, lot's of software have the filebrowser for content creation. This could be an asset manager later on in time. 

I am going to now let this go under review then close this. 

## Updates


### 2D Animation Full layout

 - added dopesheet timeline and minimalized it
 - added animation toolbar
 - added toolbar

![bforartists_2019-01-09_08-22-12](https://user-images.githubusercontent.com/35357409/50905881-d26e4980-13f1-11e9-9cdd-e233932e7b71.jpg)

### Rendering

 - added dopesheet timeline and minimalized it
 - added animation toolbar
 - added toolbar
 - Set default tab to rendering
 - closed preference panels
 - set to Render Output
![bforartists_2019-01-09_09-37-02](https://user-images.githubusercontent.com/35357409/50906340-dcdd1300-13f2-11e9-8889-8fcbc7a95b7f.png)

### 2D Animation Full

 - added dopesheet timeline 
 - added animation toolbar
 - added toolbar
 - opened side panel
 - closed preference panels

![bforartists_2019-01-09_08-26-01](https://user-images.githubusercontent.com/35357409/50905888-d5693a00-13f1-11e9-947f-587490f14c28.jpg)

### Masking

 - added Masking dopesheet timeline and minimalized it
 - added animation toolbar
 - added toolbar
  - closed preference panels
 ![bforartists_2019-01-09_09-34-15](https://user-images.githubusercontent.com/35357409/50905893-d9955780-13f1-11e9-9a66-78d6e134c165.jpg)

 ### Motion Tracking

 - added tracking dopesheet timeline and minimalized it
 - added animation toolbar
 - added toolbar
  - closed preference panels
  - swapped viewports around to be consistent with compositing
![bforartists_2019-01-09_09-34-21](https://user-images.githubusercontent.com/35357409/50905895-dac68480-13f1-11e9-96f8-9792afec08f8.jpg)

 ### compositing

 - moved view based vieports to top to be consistent with other layouts

![bforartists_2019-01-09_09-45-06](https://user-images.githubusercontent.com/35357409/50906512-44935e00-13f3-11e9-97b0-b66dba2b256c.png)

**Comment by Draise14** [comment]
I'm building with new files to test them again, seems preferences don't save settings for a factory reset (thus crash due to not having toolbar activated) if I already have a **userpref.blend** file in the %appdata% folder on saving the default.

**Comment by ReinerBforartists** [comment]
It would be better to do the pull request when the task is done ;)

I don't want to merge it piece by piece really.

**Comment by Draise14** [comment]
Yeah. The header and title of this task is vague. Not sure when "fixed" is done now. 

Ok, build with working startup is not working still. Maybe it be best to close this task and open a new task for the layouts - and more specifically about going through the error on factory reset and startup.blend generation on first use. The factory reset not storing the toolbar addon setting is something else.

**Comment by ReinerBforartists** [comment]
Yes. As told, separate the task into smaller subtasks when problem arrives. Or even without problems. The key is to have small fixable and handleable chunks.

The task is fixed when the main task is done. The separated tasks is another story then.

**Comment by ReinerBforartists** [comment]
> Things I didn't do:
> 
> remove the cube, lot's of discoverable features using the workspaces gets activated on the object, which I think is good for newbies.
> remove filebrowser from video editor and materials, for now, lot's of software have the filebrowser for content creation. This could be an asset manager later on in time

My thoughts at it:

Please remove the cube. It's one click to add it, we have the toolbar with the primitives direct at the top of the UI. But it's a gazillion clicks to remove it every time it's in the way. And it is always in the way. That's the reason why i have removed it in BFA1 at all.

For the file browser, we can readd it when the asset manager arrives. For now it's pretty useless.

**Comment by ReinerBforartists** [comment]
Okay, these changes are all lost now. Going through the list again.

**Comment by ReinerBforartists** [comment]
Hm. Seems that we have to close the panels in the sidebar by code in the ui python file(s). Separating the issue into own task.

**Comment by ReinerBforartists** [comment]
We have a problem with the hidden editortypes. When i edit them and remove them, then the layout is back to unedited.

Furthermore, every layout for animation shows the toolbar at the bottom. But it should display the timeline instead. 

Separating both problems.

**Comment by ReinerBforartists** [comment]
Closing this task. Most of it is fulfilled. For the rest we first need to fix the upper bugs. And then we can continue. In a fresh task.
