### ISSUE TITLE
Addons - Add GNU to Bforartists addon headers

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4010]
Add this to some addons:

1. Default Library
2. Brush Panels

```
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
```

**Comment by ReinerBforartists** [comment]
Which addons are meant?

In general the addon developers are responsible for the license. We cannot and are not allowed to relicense addon code.

**Comment by Draise14** [comment]
These are addons I've made, ei the Default Library addon. 

I had a double look, the brush panels addon is fine in the init, but could have a line in the other documents.

**Comment by StandingPadAnimations** [comment]
Saw this and wanted to clarify that all Blender addons are implicitly GPL (since BPY itself is GPL), so there won't actually be any relicensing issues (in theory at least)

**Comment by ReinerBforartists** [comment]
It's a can of worms since it is not clear if all addons must be GPL. Some says this, some says that. And the official statement at the Blender page says they must. Since they derivate from the Blender API. But as a matter of fact, even the onboard addon Cycles is for example under Apache license ...

**Comment by StandingPadAnimations** [comment]
The addon part of Cycles (the glue between Blender and the Cycles engine) is still GPL, but the Cycles engine itself (which is seperate and comes from a seperate project) is Apache.  

When any script imports BPY, they're linking to BPY, and GPL states that any code that links to a GPL covered library automatically has to be GPL (there is a version or GPL with the link time exception, but that's not used by BPY)
