### ISSUE TITLE
Sequencer - Context Menu - Copy Modifiers to Selected needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4013]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/21b61a99-3f5f-4e76-b270-6c54d9b56c9a)

Needs iconography and documentation

**Comment by ReinerBforartists** [comment]
I would say the simple copy icon is good enough here.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Ah, was a regression. No documentation necessary. Done
