### ISSUE TITLE
resetting the views.

### ISSUE THREAD

**Issue by fadi123go** [Bforartists/Bforartists#4015]
![tabs](https://github.com/Bforartists/Bforartists/assets/95540795/5dd014ca-92a3-438b-8af0-28d8a922cd6f)
Sometimes you miss around the the views by changing or splitting them .If  you want to go back to the original setup you should right click  the tab hit reset to original views.
You may also want to create custom view setup and save it as a new tab. Right clicking it should bring reset, and delete the tab options .

**Comment by ReinerBforartists** [comment]
Hey fadi123go,

It can already be done by Load Factory Settings. Is this what you are looking for?

![factorydefaults](https://github.com/Bforartists/Bforartists/assets/13919702/3b7ebd3b-728d-49bc-b3da-35e78453fc03)

**Comment by fadi123go** [comment]
Thanks , how about my second suggestion ,saving custom tabs?

**Comment by Draise14** [comment]
You can Add new workspaces based on factory default from the plus icon to the right of the tabs, and you can remove. You can duplicate a workspace or make a new one - and if you Save Startup, it will store in the next startup of the software. 

The user experience does unfortunately need to store this into the `startup.blend` file located in the user preferences folder, thus saving the startup stored your default changes  - Blender developers haven't stored the workspace settings this into separate systems as of yet, so a quick save of a workspace of an active file for future load ups is technically not possible.

**Comment by fadi123go** [comment]
Thanks again.
