### ISSUE TITLE
Preferences - Experimental - Missing property "use_override_templates"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4017]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2f221806-889c-4fe4-877b-2c331eecb739)

This is also true in Blender, not sure if to report or now. Will keep open till next merge.

**Comment by ReinerBforartists** [comment]
It's a bug !

**Comment by Draise14** [comment]
lol, they forgot to remove the GUI entry to the patch they had removed.

<details>
<summary>Details</summary>

SHA-1: 25ab53a4af571a25339cad7c8f687c9b72408269

* Cleanup: Remove LibOverride Template experimental feature.

This was added at the start of the project, as a way for the source
library to control what would be overridable by the user of the data
(production files).

The implementation never went beyond the experimental area, and only
exposed in the python API then. The idea has been superseeded by the
'cherry-pick' design, so there is no point in keeping this code any
longer.


</details>

**Comment by Draise14** [comment]
Fixed it, made a pull request.

Last time a one liner took about 7-9 days to merge, this may take the same.

**Comment by Draise14** [comment]
Fixed upstream.
