### ISSUE TITLE
3D View - Improve geometry nodes attribute overlay properties

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4018]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/cad1e4ee-230d-432c-a8c6-02c515d4cc97)

- Make the attribute Color Opacity slider contain a label and indend
- Indent the Attribute Text prop

**Comment by ReinerBforartists** [comment]
It was a double. Documenting.

![overlay](https://github.com/Bforartists/Bforartists/assets/13919702/fef81336-680f-48f5-81ca-60034bac4239)

**Comment by ReinerBforartists** [comment]
Done

**Comment by iyadahmed** [comment]
It works great but it doesn't say
Color opacity anymore,. fixing 
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b31de785-80c3-4bfe-ad4f-08d80864dd91)

**Comment by ReinerBforartists** [comment]
Why :D

We usually don't label sliders. The tooltip tells you the name ...

**Comment by Draise14** [comment]
Ah, labels in sliders usually is a no go, so tooltip should suffice. Label could be "Color Opacity" since Viewer Node > Viewer Node is redundant. 

Viewer Nodes > Color Opacity

**Comment by ReinerBforartists** [comment]
The checkbox activates the viewer node though ...

**Comment by Draise14** [comment]
Ah.. Good point. Two different props in one. 

I guess tooltip is fine. Anyway....  "color" for attribute opacity label is also confusing, so yeah, toolitp can do.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/db8ddcb0-4b38-45bb-a165-1db4112139e0)

Though, they are two unrelated props, would it be more like this as a hierarchy?

**Comment by ReinerBforartists** [comment]
Well, it is viewer node opacity. So i would leaveit in a row. Don't make easy things too complicated :)

**Comment by Draise14** [comment]
Attribute text depends on the viewer node being plugged in and activated yeah, since you need a value in the viewer to see the attribute as a text. Like.. point index.

**Comment by ReinerBforartists** [comment]
But we have already a viewer node label above, it is hierarchical already.

**Comment by Draise14** [comment]
I guess since the label says viewer node and the attribute text also requires a viewer node, the toggle UX for the "viewer node" makes no sense now. It is a color attribute toggle [from the viewer node, defined by label - not a viewer node toggle since the attribute text toggle is not a child of the viewer node toggle. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/c3a6eac9-ed89-4e3c-b9a0-a3163c2e7aae)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/ff2883ca-22a8-4216-be3f-38579c1b07ad)

**Comment by ReinerBforartists** [comment]
Well, Blender lists it under the viewer node label. Do as you like :)

**Comment by iyadahmed** [comment]
where did this come from ^^ are these local changes you made right?
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b1ea605a-59d5-470d-b1e3-c3c37491f917)

**Comment by ReinerBforartists** [comment]
Yes, a while back. Bu thtat's the old code that you show here.

**Comment by Draise14** [comment]
> Well, Blender lists it under the viewer node label. Do as you like :)

Yeh, blender be craycray. 😂

And yes, that is an old build.

**Comment by iyadahmed** [comment]
I've tried out the actual options and this is how it works ^^
![image](https://github.com/Bforartists/Bforartists/assets/25552173/5e73ee31-b40d-4d9a-b120-9d7915009067)

**Comment by iyadahmed** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/25552173/a74e5c37-28cb-4d71-a889-49fcf00295f6)

**Comment by ReinerBforartists** [comment]
You forgot to update the manual :)

**Comment by iyadahmed** [comment]
> You forgot to update the manual :)

ok updating ^^

**Comment by ReinerBforartists** [comment]
It's a trap!

**Comment by iyadahmed** [comment]
Done ✅ 
https://github.com/Bforartists/Manual/pull/555
