### ISSUE TITLE
Implement tab menu to switch between the animation editors

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#402]
We had this in BFA1. Should go into BFA2 too, it is useful.

Task: Implement tab menu to switch between the animation editors.

Maybe we can leave the Timeline away here. In Animation layout the timeline is already open at the bottom.

![anieditorswitching](https://user-images.githubusercontent.com/13919702/50212932-885af080-037c-11e9-991e-5a07bbc0a677.jpg)

**Comment by ReinerBforartists** [comment]
This requires a new icon for the drivers. So postponing.

**Comment by ReinerBforartists** [comment]
Unfunny. Drivers editor is not available through python. It is simply not in the enum.

![driversnothere](https://user-images.githubusercontent.com/13919702/53560944-d2ffa280-3b4d-11e9-90df-26300b324daa.jpg)

**Comment by ReinerBforartists** [comment]
Argh! Next unfunny thing. I haven't implemented the menu in the timeline yet. Just in the dope sheet. But the menu nevertheless shows in the timeline menu. What a can of worms :D

Unassigning and postponing for now. This needs deeper investigation, and is something for the next point release.

![canofworms](https://user-images.githubusercontent.com/13919702/53561451-363e0480-3b4f-11e9-8791-fefaff5f6698.jpg)

**Comment by ReinerBforartists** [comment]
Hm, the blender devs have implemented a toggle here in the view menu. Worth an investigation.

![toggle](https://user-images.githubusercontent.com/13919702/55533775-ad1c6f00-56b2-11e9-8ab2-f38395f93be5.jpg)

**Comment by ReinerBforartists** [comment]
Let's have a second look here.

**Comment by ReinerBforartists** [comment]
Still the old problem

![driversproblem](https://user-images.githubusercontent.com/13919702/67184234-9be34780-f3e3-11e9-85b0-7367a7ca8ed4.jpg)

**Comment by ReinerBforartists** [comment]
Hm, drivers is part of the graph editor. But how to reach it then?

**Comment by ReinerBforartists** [comment]
Three out of four is already an improvement. So let's first implement the three, and then have another look at the driver area.

**Comment by ReinerBforartists** [comment]
:'3
![tooltipproblem](https://user-images.githubusercontent.com/13919702/67189981-72c8b400-f3ef-11e9-8498-40a6a6bd44e5.jpg)

Okay, the old way, with own tooltips ...

**Comment by Draise14** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSS!!!!!!!!!!!!!!!!

**Comment by Draise14** [comment]
The driver editor is more accessible with righclick on any driver now (opens up a new window).

**Comment by ReinerBforartists** [comment]
Eek, i have closed this issue accidentally again ^^
 
I have meanwhile found a way to add the driver button too. But needs some polishing. Tomorrow.

**Comment by ReinerBforartists** [comment]
Fixed in master

Funny little challenge this was ...

![anitabs](https://user-images.githubusercontent.com/13919702/67272859-93f7d600-f4bd-11e9-9aca-15011b769997.jpg)

**Comment by Draise14** [comment]
I'm recompiling just for this feature.
