### ISSUE TITLE
Graph Editor - New "Scale from Neighbor" Blend operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4020]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2255823a-81a4-4a9c-b7a4-8a89118bc1d7)

New operator, new icon, new documentation... 

<details>
<summary>Details</summary>

SHA-1: b27718a9e73a8e5ae29fb68a439ec76fbb5d8080

* Anim: Graph Editor Scale From Neighbor

Combination of two operators by Ares Deveaux
#106524 and #106523

Introduces a new operator "Scale from Neighbor"
that scales selected keyframe segments from either
the left or right keyframe neighbor.

Pressing "D" during modal operation will switch
from which end of the segment the scaling happens.

This is useful to make a section of animation closer to a pose on either side.

Co-authored-by: Ares Deveaux <aresdevo@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/112387

</details>

**Comment by ReinerBforartists** [comment]
Documenting 

![scale](https://github.com/Bforartists/Bforartists/assets/13919702/99d510e9-25b2-4f64-b62b-48d0e5be3aba)

**Comment by ReinerBforartists** [comment]
Done
