### ISSUE TITLE
3D View - Regression - Insert Keyframe menu missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4022]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d13fb6fa-2d5d-43a3-b095-4b599f3ad07c)

Oops... came in from last merge.

**Comment by Draise14** [comment]
Related
https://github.com/Bforartists/Bforartists/issues/2565

**Comment by iyadahmed** [comment]
I have to look into this

**Comment by iyadahmed** [comment]
looking into it rn still waiting for build to finish
![image](https://github.com/Bforartists/Bforartists/assets/25552173/bc26afa8-8d3f-4e29-8efc-a18e03d75ff8)

**Comment by iyadahmed** [comment]
found the issue!
pushing soon
