### ISSUE TITLE
Cycles GPU rendering not working at apple silicon

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4023]
Digimooses has reported that the gpu rendering with cycles is dysfunctional at his mac. Version 4.0.2

See here: https://www.bforartists.de/forums/topic/apple-metal-is-not-working-on-bfa-4-0-2-apple-silicon-version/#post-25922

**Comment by Draise14** [comment]
Don't have any mac hardware at all to troubleshoot.

**Comment by ReinerBforartists** [comment]
Just to prevent misunderstandings, his trouble is about hardware accelleration. He can render with Cycles, it is just it renders at the cpu then, much slower.

**Comment by Blenderblunder** [comment]
Thanks Reiner I didn’t pick that up. Even weirder then. GPU rendering is working on mine, as is CPU. 
Metal is selected in his settings and I assume he has selected GPU render in the Outliner, hence the error message being thrown. 
I can only think it is a permissions issue but one particular to his setup - given he also had the issue with opening the application in the first place and now it seems to not find the libraries. Please let me know if anyone else flags it as an issue. (Although I can’t imagine what might be the underlying cause)

**Comment by ReinerBforartists** [comment]
Thanks for double checking. I really wish i could help here ...

**Comment by ReinerBforartists** [comment]
Let's close this issue since there is nothing that we could do here.

**Comment by Blenderblunder** [comment]
Yes. We can revisit if there are other reports.
