### ISSUE TITLE
Linux not compiling

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4025]
Currently the linux version is not compiling. Needs investigation.

It can be that the libs are too new for the code. I forgot to pull right after the merge.

![compilerror](https://github.com/Bforartists/Bforartists/assets/13919702/965c7128-5b11-4e75-bb2f-86805ba0998b)

**Comment by ReinerBforartists** [comment]
Yeah, lots of lib errors. I have no idea how to revert to a previous svn commit under linux. So, this week just a windows devbuild.

**Comment by Draise14** [comment]
I'll try here.

**Comment by Draise14** [comment]
Compiling lite now, so far so good. Libs updates successfully. 
Will compile a release soon then upload to nexcloud if all goes well.

**Comment by Draise14** [comment]
Ok, Lite failed, had this issue with windows too and reported to upstream. They fixed. Maybe it hasn't bleed down to linux cmake files yet.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a7ff0fc4-ffc9-46ac-afcb-3d2caa246388)

Blender has the same issue. Will report.

**Comment by Draise14** [comment]
Ok, talked to them, theoretically all should be fine. So I deleted the libs and re-checked them out. So a fresh build was successful with a lite solution. 

Compiling release now.

**Comment by Draise14** [comment]
Release build on linux succeeded.

**Comment by Draise14** [comment]
Lite Bforartists build now a success, doing a release with Optix now.

**Comment by Draise14** [comment]
Could compile a release on Debian once I checked out the libs again. Something must have stuck from old.

**Comment by ReinerBforartists** [comment]
So, basically repulling the libs should do the trick?

**Comment by Draise14** [comment]
Yep. Delete, redownload. 

I uploaded the release.devbuild to nexcloud.

**Comment by ReinerBforartists** [comment]
Aww, i already zipped the one that i have now compiled :D

And confirmed, there was a problem with the libs.
