### ISSUE TITLE
3D View- Curve object - Edit mode - Expose Set Handle Type to Header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4034]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/7f3defd4-3244-45cf-9549-2e64bce4773c)

A user pointed out that this may be a common operator, and from personal use.. yeah, these are common operators. In Inkscape, these are also exposed to a top level. I could be nice if we have set handle type also in the control point tab of the toolshelf tabs. 

**Note:** _This may need to be done with other Set Handle Type sub-menus of other object times like Curves object or Greasepencil... for consistency sake_

**Comment by ReinerBforartists** [comment]
In the animation layout we have these kind of options in the header. So it would be more consistent to add it to the header too here.

**Comment by Draise14** [comment]
Huh good point. Sometime I wish the animation editor had a customizable toonbar, but alas. 

So one level less deep,same method as the animation editors. Let's go.

**Comment by Draise14** [comment]
Ok, this is a bit too deep in know-how for me. So will have to postpone for this next release.

**Comment by ReinerBforartists** [comment]
Let's have a look what we can do here.

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/983136e3-6074-4a5b-856a-a357f9cb2e21)

**Comment by ReinerBforartists** [comment]
> Note: This may need to be done with other Set Handle Type sub-menus of other object times like Curves object or Greasepencil... for consistency sake

Just because it jumped into my eye here, you need to make a task for each of it then. "Fix everything" is too much at once :)

**Comment by Draise14** [comment]
So, should I open another task for Curves, Grease pencil edit mode, etc?

**Comment by ReinerBforartists** [comment]
> So, should I open another task for Curves, Grease pencil edit mode, etc?

Yes, that's better. One issue, one task.
