### ISSUE TITLE
Properties Editor - Camera Data - Background Image - View as Render float left 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4037]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/cce9eba3-b500-4737-a7a0-d2d3986a1d21)

1. Select camera
2. Go to Camera tab in Properties Editor
3. Enable Background
4. Load up an image
5. Notice properties check boxes

Float left. One is new and needs to be documented (View as Render)

<details>
<summary>Details</summary>
SHA-1: 29b1658124b8c36c17f0ae5e09e2699ffbc9b9e7

* UI: View As Render for Background Images

Add checkmark for "View as Render" to background
images in Properties / Camera data.

Pull Request: https://projects.blender.org/blender/blender/pulls/115120

</details>

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Ah wait, there hides more ...

![movieclip](https://github.com/Bforartists/Bforartists/assets/13919702/897d9c89-951e-423f-a4dd-6f05df5e8803)

**Comment by ReinerBforartists** [comment]
Documenting ...

**Comment by ReinerBforartists** [comment]
This is a bigger operation, the manual is as usual outdated here. I'll make it a task.
