### ISSUE TITLE
Icons - Update Trashcan icon to be consistent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4038]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fd9e127c-0d8b-44e2-a86e-4f36915c1e63)

Looks out of place, best use the same design language as the rest. This is an original Blender icon. Bare in mind to keep this a color icon.

**Comment by ReinerBforartists** [comment]
We have a clear icon already.

**Comment by Draise14** [comment]
Clear, yet inconsistent.. sure.... 

The former has no silhouette, form, nor colour coding.

**Comment by ReinerBforartists** [comment]
I talk about the clear icon that is used everywhere else :)

I'll do it.

**Comment by ReinerBforartists** [comment]
![clear](https://github.com/Bforartists/Bforartists/assets/13919702/a949d23c-686e-47c7-a0ef-211afd10e3a8)

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Done
