### ISSUE TITLE
3D View - Font Object - Edit Mode - Special Character now has.. special character in label (and one missing icon)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4039]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e607bcb4-c9a0-40df-9aeb-1b8b5be7cfdd)

Looks like the Special Characters operators now has special characters, lol 

**Question:** Should we remove the redundant characters from the label? 

Also, one is missing an icon (Euro)

<details>
<summary>Details</summary>

SHA-1: 0251701cd6cf353adeb116131493ebce9bcb5dfa

* Fix #116252: Corrections to Text Object Special Characters Menu

Small Corrections to the items on the Text / Special Characters menu.

Pull Request: https://projects.blender.org/blender/blender/pulls/116677

</details>

**Comment by ReinerBforartists** [comment]
Not sure what the task here is. Adding missing icon is clear. But what do you mean with operator has now special character?

**Comment by Draise14** [comment]
Ah, to clarify, in the name, we also have the special character + icon. 

**ICON (of special character) + Label + Special Character**
Example:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/065f151e-b8ef-4376-88be-5bb2e32d81d8)

This is new, and feels redundant.

**Comment by ReinerBforartists** [comment]
No, this is not redundant. Tools have all an icon at the front. The special sign in the text is part of the description then. Looks double of course, but for me it looks fine.

**Comment by Draise14** [comment]
One new icon, the Euro.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a841a884-1a68-4dac-a681-d6c3f49932c9)

Documenting

**Comment by Draise14** [comment]
Also got nuked here...

**Comment by Draise14** [comment]
Commit to master
