### ISSUE TITLE
3D View - Armature - Move to Bone Collection double entry

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4044]
![bforartists_0yJanNM28y](https://github.com/Bforartists/Bforartists/assets/35357409/b7da948c-dad5-454a-ac13-78fdf3311b95)

Looks like we have a double entry now, and one is on the root (I like) and in pose mode, it is still nested.

**Tasks:**
- Remove the double and make it consistent in both modes

**Question:**
Which to remove/add?

**Comment by ReinerBforartists** [comment]
How does Blender look here?

**Comment by ReinerBforartists** [comment]
As a side note, when we have different functionality, then it is no double.

**Comment by ReinerBforartists** [comment]
Hm, but the operator is the same. So it's simply a double. And it is double in Blender too.

@Draise you said the one behaves different. I cannot reproduce, and the operator is as told the same. It is both

bpy.ops.armature.move_to_collection()

Remove one ...

**Comment by Draise14** [comment]
Yeah I'll clean this one up when back at the computer

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ce1d5c70-f13d-449f-9b25-0e1960210fc2)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/26d9a1da-644d-4aee-810c-3cebd817884a)

Consistency first.

Move to Collection is in Context Menu and in a top level. The Collection submenu is actually in fact hidden under argument that it is a double entry used both in the outliner and 3D View, and should be only in Outliner.

**Comment by Draise14** [comment]
Done, and improved icons a bit too, was getting confusing. 

Will document in the morning, it is now late.

**Comment by Draise14** [comment]
Oops, missed one inconsistency - so.. did documentation also.

**Comment by Draise14** [comment]
Have to admit, not listing the collections directly and hiding the list in a floating menu is.. kinda annoying. I get why (big lists) - but it's not as convenient if at all.
