### ISSUE TITLE
Hotkeys - Change SHIFT+DBL LMB to select collection hierarchy to have it double click on icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4047]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5356e51c-0532-440a-844a-5a0e9143a32d)
![bforartists_m3XUsxz84o](https://github.com/Bforartists/Bforartists/assets/35357409/a9b51038-99a4-4e87-8e77-b84a5786b870)

Blender made it possible to double click on an active item icon to select hierarchy, also true for children objects, not only collections.

I find this a lot more discoverable and usable than holding down SHIFT to do it like how we had it.  

The new option added is "recurse" meaning.. it will select down the hierarchy. 

<details>
<summary>Details</summary>

SHA-1: 796577d76e208df0358cdf306e5553386e555fc9

* Outliner: Double-click on item icon to select contents/hierarchy

Allow double-clicking on Outliner items to select all child items.

Pull Request: https://projects.blender.org/blender/blender/pulls/110151

</details>

**Comment by Draise14** [comment]
Feature parity with Blender hit... Documented too. Commit to master.

**Comment by Draise14** [comment]
What on earth happened? How did this change get lost, it was in the master. Was it from a merge issue?

**Comment by Draise14** [comment]
I guess this will have to be.. forgotten in this release, and will come in next. Blender one ups us there. WTH, how did this revert?

**Comment by ReinerBforartists** [comment]
> What on earth happened? How did this change get lost, it was in the master. Was it from a merge issue?

Most probably. Maybe we edited each other edits away at one point. Such things happens :)

**Comment by Draise14** [comment]
Commit to master, hopefully sticks this time.
