### ISSUE TITLE
3D View - Text Object - Edit Mode - New Insert Unicode operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4048]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c0476c5a-7d12-441d-a23a-70e53466ce5b)

You can now use unicode operations with this operator. Needs icon and documentation. 

<details>
<summary>Details</summary>

SHA-1: 6d357dc60df233e84ce0c9d910f7158a71b82943

* UI: Dialog to Insert Unicode Characters for Text Objects

Dialog box that allows the entry of any Unicode character into a 3D
Text Object string by entering its hexadecimal codepoint value.

Pull Request: https://projects.blender.org/blender/blender/pulls/116966

</details>

**Comment by Draise14** [comment]
![image_processing20210620-25158-hrdc9y](https://github.com/Bforartists/Bforartists/assets/35357409/62294ccc-67e5-45e2-a985-4757972a5c43)

Huh, is this the Unicode icon?

**Comment by Draise14** [comment]
Not yet, unless it exists somewhere. Still digging, in the drawing board. Also brewing coffee for the day.

**Comment by Draise14** [comment]
Got it, making new icon.

**Comment by ReinerBforartists** [comment]
Go go go

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/50a9e95a-1314-4130-adfc-f65ce51e2395)

Documenting

**Comment by Draise14** [comment]
Commit to master

**Comment by Draise14** [comment]
Failed merge revert, hope the icon is still there!

**Comment by Draise14** [comment]
Commit to master
