### ISSUE TITLE
Asset Browser - Pose Asset context menu needs love, regression

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4050]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/966d4f26-5814-44fa-bbd7-2aa237317393)

Needs icons, and maybe documentation. The icons, I think we added them before - so they may have gotten nuked in a merge. 

1. Select an armature
2. Go to pose mode
3. Create a Pose Asset under the Asset header menu
4. Right click on the new Pose Asset
5. Notice the missing icons

Effectively, it did get nuked:
#3496

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/21818167-86ff-4e83-8cba-fed1a83cc67c)

Take note, the Pose Asset Shelf also needs this.

**Comment by iyadahmed** [comment]
Done
![image](https://github.com/Bforartists/Bforartists/assets/25552173/7bef757b-858f-47c2-968e-7df64f2a366a)

![image](https://github.com/Bforartists/Bforartists/assets/25552173/ec779511-902f-431d-a09d-693e45ff8589)
