### ISSUE TITLE
3D View - Delete Keyframe - Remove confirmation dialogue

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4060]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b3c24e56-9fa8-4cb4-8b62-290ae4b69997)

Why.. just why.... 

A user opts into deleting a keyframe by hitting the button. If they didn't opt in, they wouldn't have hit the button. 

Mistake? Undo.

**Comment by Draise14** [comment]
Commit to master, no need for documentation.

**Comment by Draise14** [comment]
Missed a thing.

**Comment by Blenux** [comment]
Note this can be down in the space_graph.py file.

Line 381  = layout.operator("graph.delete", text="Delete").confirm = False

**Comment by iyadahmed** [comment]
> Note this can be down in the space_graph.py file.
> 
> Line 381 ` layout.operator("graph.delete", text="Delete").confirm = False`

Thanks this is it!

**Comment by ReinerBforartists** [comment]
This wears the label fixed. Is it?

**Comment by iyadahmed** [comment]
> This wears the label fixed. Is it?

ummm I think it needs to be fixed again, one moment will do
