### ISSUE TITLE
User Preferences - Keymap - Is set to Blender, not Bforartists.

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#4074]
Should be Bforartists.

![Screenshot_20240211_210146](https://github.com/Bforartists/Bforartists/assets/25260650/a7a93052-4f0d-441e-a8b6-4e59598b5d1d)

**Comment by ReinerBforartists** [comment]
This ussally points at an error in the bfa keymap ...

**Comment by ReinerBforartists** [comment]
Hm, it is not to repeat. I guess you made a change to the keymap somewhere. And BFA is not happy with it :)

I have no content in the appdata directory, and it is looking fine.

![check](https://github.com/Bforartists/Bforartists/assets/13919702/2f178d4f-653b-41ff-8572-10089aa22039)

**Comment by Blenux** [comment]
hmmm, will check.

**Comment by Blenux** [comment]
Weird, this is a completely new compile, and nothin in Bforartists config folder?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/028613ce-923e-4f95-b914-6af82e45c957)

**Comment by Draise14** [comment]
First load won't have anything till the user preferences save on close or change. Factory defaults loads from Local, not User.

**Comment by Blenux** [comment]
Hmm will check again after work.

**Comment by ReinerBforartists** [comment]
Yes, the change that bothers BFA must be in the keymap files. Have a look at the console.

**Comment by iyadahmed** [comment]
I guess we could close this now, as mentioned on Discord the issue was local (because of `__pycache__`)

**Comment by Blenux** [comment]
Wasn't cause by the pycache, but the active keymap in userdef.default.c, making it uppercase makes it work (resaving startup and userpref didn't).
![image](https://github.com/Bforartists/Bforartists/assets/25260650/014f0003-26af-4dcb-8c1a-327b959e64ea)
