### ISSUE TITLE
3D View - Camera lock widget icon is inversed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4078]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/352d0cfb-d90f-4ba4-9427-164201b8c1a3)

Camera Lock icons are inversed right now

**Comment by Blenux** [comment]
Yep, notice this also last night, easy fix will do it now. 

Apparently, this simple change took 4 years to do :O

[PR Here](https://projects.blender.org/blender/blender/pulls/111076)

[Talk Here](https://devtalk.blender.org/t/lock-camera-to-view-it-was-torture-to-find-it/5473/1)

**Comment by Blenux** [comment]
done!

https://github.com/Bforartists/Bforartists/assets/25260650/4b0a9d3a-2929-4e28-975d-c1867e0f89fe
