### ISSUE TITLE
General GUI - Disclosure icons are inconsistent now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4084]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c7fdd61a-84d8-4f27-96fe-4f6f3dae1bf1)

Blender did an update to use only line icons, we had only triangle ones which show direction and silhuette, and don't get lost in text. We should make sure the "Chevron Disclosure" icons are triangles too. 

<details>
<summary>Details</summary>

SHA-1: 8d487704189509d61176da0e369fc58b303a6f8e

* UI: Consistent Use of Chevron Disclosure Icons

For icons that represent collapsible and collapsed content we use a
variety of icons: chevrons and closed triangles of varying
proportions. This PR makes everything use a chevron for consistency.

Pull Request: https://projects.blender.org/blender/blender/pulls/116240

</details>

**Comment by ReinerBforartists** [comment]
>We should make sure the "Chevron Disclosure" icons are triangles too.

Why? It separates the look. I like the triangle buttons better in this area.

**Comment by Draise14** [comment]
I prefer the former way we had it, all triangles. It now is visual Blnoise for the same functionality. 

Triangle = silhouette for hit box + direction indicator + now one consistent indicator for same function (expand, collapse)

V triangle + triangles = no silhouette and visual hotbox + can be confused with a letter due to being white lineart like a letter (no longer icon)  + interface now has two icons for one function... Noise. 

Also... Previous Bforartists was like this, only triangles. Now it's sorely inconsistent.

**Comment by ReinerBforartists** [comment]
Your decision :)

**Comment by Draise14** [comment]
We also made this decision already in the last to not use the Lineart triangles. Let's stick to that. 

https://github.com/Bforartists/Bforartists/issues/2735
