### ISSUE TITLE
Image Editor - new (old) rotate operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4085]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/107ae5f6-698c-4bf5-9f37-eb570b2f16bc)

new rotate operators. We have some icons already, so let's use existing. 

<details>
<summary>Details</summary>

SHA-1: 93562a1cc5403e48d0396c338d1faf3a4d21fb7e

* UI: Image Rotate

Operator to rotate images in 90 degree increments.

Pull Request: https://projects.blender.org/blender/blender/pulls/117352

</details>

**Comment by ReinerBforartists** [comment]
Ah, did they add them back ? :D

They were removed at one point ...

**Comment by Draise14** [comment]
Documenting
