### ISSUE TITLE
Hotkeys - Make SHIFT+A consistent in all relevant editors

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4097]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/70593740-1fc6-4162-b42d-24f0536d5dad)

Right now, the SHIFT+A add menu for the node editors exists, and assist with searching to add items. But in other editors where relevant, it is inconsistently not there.... 

Right now the 3D View, the Properties Editor add menus have an add menu (and potentially the outliner, but not sure if that's now redundant or a user customization)

* Add Object Add (Shift+A) to 3D View 
* Add Properties Editor add menus (Shift+A) to the properties editor consistently

For the sake of consistency, and also muscle memory for any artist following a tutorial or coming in from Blender... 

Related task that opens this question:
#4063

<details>
<summary>Details</summary>

SHA-1: 537d1752899a37155dfaf4577412298630efc6ce

* Outliner: Add shortcut to Add Object and Duplicate

Add shortcuts to the Outliner for consistency and convenience:
* Add Object (Shift+A)
* Duplicate (Shift+D)
* Duplicate Linked (Alt+D)

More info and images in the PR.

Pull Request: https://projects.blender.org/blender/blender/pulls/117922

</details>

**Comment by Blenux** [comment]
This Blender PR 117922 was reverted shortly after.

**Comment by Draise14** [comment]
Documenting.
