### ISSUE TITLE
3D View - Mesh Object - Edit Mode - Edge - New Set Sharpness by Angle operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4099]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/2fa2f960-a402-46e7-85ac-08a0053054dc)

Add icon, document. We may be able to sue the Smooth by Angle icon? Or a new one... hmm.. it does the same.
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/3ad5fdf5-6e96-44fc-b629-b9cc09ed4578)

Don't forget to also add to the toolshelf. 
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/b0135f3b-ea55-422d-9269-840a063cfdd4)

Also don't forget the context menu
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/ef821d51-796a-441d-9e25-164f84212ba6)

<details>
<summary>Details</summary>

SHA-1: 78963b466b1fabc0f827a2e298957b47ec2a971f

* Mesh: Add "Set Sharpness by Angle" operator

This simple  operator set the edge sharpness attribute on edges,
either extending the existing values or replacing them completely.
It's meant to make it more convenient to manually control the
sharpness now that there can be more reason to do that after
auto smooth became a modifier.

Pull Request: https://projects.blender.org/blender/blender/pulls/117918

</details>

**Comment by Draise14** [comment]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/4a36b14d-81e9-4668-8c95-e63005927428)
Though it "does" the same as setting normals smooth by angle... it doesn't quite.. fit the edge operator. 

So I'll make a new icon, but tomorrow. 
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/e19cd9bb-1196-4d9b-aa72-8cad4b569f4c)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ae918896-c18c-45eb-95e5-faa372f87dbf)

Better... A bit more consistent with the blue of setting "smoothing" and the angle, and make it based on the angle icon.

**Comment by Draise14** [comment]
Documenting.

**Comment by Draise14** [comment]
Commit to master

**Comment by Draise14** [comment]
![Uploading bforartists_EiuRjUMTyw.png…]()

**Comment by ReinerBforartists** [comment]
Sounds like a merge problem at one point. Do not wonder, simply fix. It happens ^^

**Comment by Draise14** [comment]
Commit to master.
