### ISSUE TITLE
Properties Editor - Lamp and Spotlight object - Light Tab - Float the new Soft Falloff option to the left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4100]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/69312aa6-3165-4867-8156-e75d5e92c2c3)

Also requires documentation. 

Note: Default lights have this on. The startup.blend light doesn't. Maybe we should update that.... 

<details>
<summary>Details</summary>

SHA-1: bd8a44e169aa7b101c15554476256b776ac5b9c2

* Lights: Option to use old point light falloff

Add new "Soft Falloff" option on point and spot light that uses
the old light behavior from Blender versions before 4.0. Blend
files saved with those older versions will use the option.

This option is enabled by default on new lights.

Fix #114241

Co-authored-by: Weizhen Huang <weizhen@blender.org>
Co-authored-by: Clément Foucault <foucault.clem@gmail.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/117832

</details>

**Comment by ReinerBforartists** [comment]
>Note: Default lights have this on. The startup.blend light doesn't. Maybe we should update that....

This would be another task then. I'll create it.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Overlooked Cycles ...

![cycles](https://github.com/Bforartists/Bforartists/assets/13919702/eb8a3837-bca0-4f98-a9b5-b20df50261ad)

**Comment by ReinerBforartists** [comment]
Fixed
