### ISSUE TITLE
UI - Clean Up (Purge) has redundant confirmation dialogue.... 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4102]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/78ab9289-aeb3-4a68-ae22-c28543e3488a)

We already have targeted operators for this, we don't need to double confirm intentional operations. This interactive confirmation dialogue is redundant as eff.... 

Remove.

All options are opt-in in the GUI here, no need to double confirm. 
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/2a028a86-c9ea-4bca-a4df-6f60f878c491)

<details>
<summary>Details</summary>

SHA-1: 0fd8f29e883de93dc38282f96a8c3dc04c222866

* IDManagement: Update the Purge operator to display an interactive popup.

Make the 'purge' operation show an interactive popup by default, with
a preview of the type and amount of data-blocks to be deleted.

Idea and initial UI/UX design are from @Harley (see PR !117242).

Pull Request: https://projects.blender.org/blender/blender/pulls/117304

</details>

**Comment by Draise14** [comment]
Quick fix! I would only comment the code out instead of fully remove, will make merge work a bit easier.

**Comment by Draise14** [comment]
**Tested:**
- Seems the number of total data types and what was purged is no-longer listed, but a total. 
- Do we want to show the user the data type totals? Or is this unnecessary from a user standpoint? 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e4165e96-9c74-4699-ab73-fa80d1801d95)

Seems the Blender way does show the totals, before they opt-in after they had opted in to purge. They changed how the data was drawn before. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5d77cdee-2c40-4626-9e58-0e9c6f2828cc)

**Comment by ReinerBforartists** [comment]
>Do we want to show the user the data type totals? Or is this unnecessary from a user standpoint?

I think it is a nice visual feedback for the user, even if completely unnecessary :D

>Here I would say "data(s)" to show if plural.
Me likes !

>IF we want to show how much data types were purged, and still keep the opt-in as operators instead of a 2-step confirmation, then.... maybe the Blender way is good.

When in doubt, use the Blender way first. Improvements can happen at a later point.

For the rest, i am too long away from the project i guess. I cannot say anymore which way would be the more user friendly one.

**Comment by Draise14** [comment]
Yeah, I think I will clean up our operators and default to the Blender way. Maybe we can add an icon to each prop to make it easier to go through without a wall of options and text......

**Comment by Blenux** [comment]
So we're keeping the popup dialogue?

**Comment by Draise14** [comment]
Meh, nuke it. I'll check the pull and go for it. 

Seeing total of what was purged is fine enough as the user gimmick "Nice, that many things got cleaned up", knowing what exactly was purged can be "seen" by the outliner view mode. It's redundant. 

If a user pipes up about the inconsistenty, then we can make another task to show the granular notice in the post-message of what was deleted. The old code used to do that so we have a fall back commit to reference when re-implementing that... But delete confirmations is basically what we try avoid, user has already opted in by triggering.
