### ISSUE TITLE
Mesh, Properties - Object Properties - Motion Paths - align bake prop left.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4108]
Left aligned please

![baketo](https://github.com/Bforartists/Bforartists/assets/13919702/c1663ba1-abf7-47b7-84a9-aca14893174b)

**Comment by ReinerBforartists** [comment]
Unassigning, i cannot commit at the moment.

**Comment by Draise14** [comment]
Duplicate:
https://github.com/Bforartists/Bforartists/issues/4094
