### ISSUE TITLE
UV Editor - Overlays - Move label of Stretch Opacity out of slider

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4112]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0baa66b0-3512-4760-928a-2c1add5984b2)

Set label to be out of slider, then document. 

<details>
<summary>Details</summary>

SHA-1: c958910e540ede1b8b64ababb351ce59db8f2885

* UV: support changing the opacity of the UV stretching overlay

This patch adds a new `Stretching Opacity` slider to the overlays panel in the UV Editor.
This allows users to tweak the opacity of the UV stretching overlay, so the image texture
can still be visible through it.

Pull Request: https://projects.blender.org/blender/blender/pulls/117381

</details>

**Comment by ReinerBforartists** [comment]
The geometry one has the same problem ^^

**Comment by ReinerBforartists** [comment]
C code ...

**Comment by ReinerBforartists** [comment]
I have while at it also hidden away two greyed out props.

Documenting

![part1](https://github.com/Bforartists/Bforartists/assets/13919702/a6c3aa7d-7634-4eff-ae85-9e0c4fa0d812)
![two](https://github.com/Bforartists/Bforartists/assets/13919702/82f852b6-c738-437e-90d8-387cf29ba098)

**Comment by ReinerBforartists** [comment]
Hm, we should update the tooltips too i guess -.-

**Comment by ReinerBforartists** [comment]
Fixed
