### ISSUE TITLE
Hotkeys - Sculpt mode - Set Detail Size needs update to be "Sample Detail Size"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4114]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/76b0d994-bc83-461e-b6cd-8f280d00d658)

Yeah... missing now.

**Comment by ReinerBforartists** [comment]
Ah, saw this too late. I have just removed the buttons here: 

Sculpting - unknown operator sculpt.set_detail_size in space_view3d_toolbar #4133

What is curious here is, sample detail size is not in the bfa keymap nor in the Blender keymap.

**Comment by ReinerBforartists** [comment]
I was right to remove the buttons. Sample detail size is the small eye dropper icon behind the resolution.

![done](https://github.com/Bforartists/Bforartists/assets/13919702/7111819d-564f-4337-90e1-9d026729d56a)

**Comment by ReinerBforartists** [comment]
Closed as already completed.
