### ISSUE TITLE
3D View - Sculpt Mode - New "Dyntopo detail size edit" widget needs to be exposed to GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4115]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/99c1fc23-226e-4a91-9432-cbe56f6f5ea0)

In the brush dyntopo settings in sculpt mode for Relative and Brush Detailing modes, you can now set the detail size via a new operators.

This is.. obviously, a hidden operator. We could add this to the interface like we did the the set detail buttons droppers. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/ff26c1bd-4a0d-4c48-b864-d128d75d9aa5)

Operator:
`sculpt.dyntopo_detail_size_edit`

<details>
<summary>Details</summary>

SHA-1: 28dae0c91736e3200f87e7603251758ee0074162

* Sculpt: Add dyntopo size edit support for BRUSH and RELATIVE modes

This PR adds support for the `SCULPT_OT_dyntopo_detail_size_edit`
operator for the `Brush Detail` and `Relative Detail` modes,
replacing the old generic radial menu.

## Changes
* Triangle grid shown for all detailing modes
* Support for modal left / right scaling and sampling added
* Status bar updates with current value while editing the parameter.

## Limitations
* The brush size percent value is no longer shown in the 3D viewport
when using this modal.
This will be added with later functionality in #106243

Addresses #108111

Pull Request:
https://projects.blender.org/blender/blender/pulls/118403

</details>

**Comment by ReinerBforartists** [comment]
We don't have this hotkey yet. Blender has the hotkey R for it. We might need another hotkey, we first need to check for conflicts.

**Comment by ReinerBforartists** [comment]
Yeah, we use R for scale :)

**Comment by ReinerBforartists** [comment]
Also, this is a widget at the surface of the object in the 3d space. But yeah, a hotkey entry and a visible way to know it is there would be nice to have.

![widget](https://github.com/Bforartists/Bforartists/assets/13919702/80194b42-805d-43b5-b0f5-b0b15a440ed1)

**Comment by ReinerBforartists** [comment]
And one more. Outside of the dyntopo the hotkey R also adjusts a resolution grid. And i cannot find where this value shows in our UI.

Can of worms is getting bigger and bigger ^^

![outsideofdyntopo](https://github.com/Bforartists/Bforartists/assets/13919702/7cfb5def-aa38-48c1-9825-85c0657115ee)

**Comment by ReinerBforartists** [comment]
Ah, Remesh Voxel size. And the hotkey that we use here is Shift R. Shall we change this to S? S seems to be free here.
![shiftr](https://github.com/Bforartists/Bforartists/assets/13919702/a5ba501a-b0f3-4844-b9d2-8a155952bce6)

**Comment by ReinerBforartists** [comment]
Hmm. The visible entry for the widget is already there. But it does not update. And has yet another hotkey assigned. Lemme check ...
![shiftd](https://github.com/Bforartists/Bforartists/assets/13919702/1982f4d3-6bc7-4845-ac51-b4ca5dccf4d6)

![alreadytherebutnotupdating](https://github.com/Bforartists/Bforartists/assets/13919702/4a4d7d10-a2dc-47b9-9206-cad0c12d24c3)

**Comment by ReinerBforartists** [comment]
Made it S now too.

**Comment by ReinerBforartists** [comment]
-.-

All i did was to add the shortcut ...

![whatthe](https://github.com/Bforartists/Bforartists/assets/13919702/711ce77c-3f0e-4dae-9e9c-4985ce7d7d60)

**Comment by ReinerBforartists** [comment]
The update problem affects Blender too. I'll make a report.

**Comment by ReinerBforartists** [comment]
And the one from above seems to be a graphical hiccup. Went away after recompiling. I have the feeling that it can also happen in Blender. Not so extreme though. Another report ...

**Comment by ReinerBforartists** [comment]
Documenting the new hotkeys

**Comment by ReinerBforartists** [comment]
Fixed. Now the reports ...
