### ISSUE TITLE
3D View - Sculpt Mode - Curve Shape header tools indent labels, collapse hidden content

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4116]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1c85020a-dbda-4d69-9f68-dfa5dcd6df69)

This new panel needs a lot of love. 

**Tasks:**
- Indent labels
- Make disclosure icons and hide disabled content below them. 
- Heavily document too

<details>
<summary>Details</summary>

SHA-1: 999dfce73609cdecccf5302099bcf0a410fa7ae6

* Sculpt: Add interpolate radius option for curve radius

Add the option to interpolate the radius from nearby curves and
add a fallback radius for when interpolation is turned off or when
there are no neighbors.

Resolves #117101

Pull Request: https://projects.blender.org/blender/blender/pulls/118339

</details>

**Comment by ReinerBforartists** [comment]
Ah. I knew something was confusing me here. Curve shape panel shows for density brush. But here the sidebar does not show any of these settings. So either it is missing for this brush in the sidebar, or is too much in the tool settings
![addbrush](https://github.com/Bforartists/Bforartists/assets/13919702/8d0c5773-a009-40d1-ae4a-fcbb6c508ce0)

![img2](https://github.com/Bforartists/Bforartists/assets/13919702/e3811c0c-ecf7-44f9-b891-95a333754c00)

**Comment by ReinerBforartists** [comment]
Reported https://projects.blender.org/blender/blender/issues/119197

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Fixed
