### ISSUE TITLE
Outliner - Add icon and move "Mange unused Data Operator" to the other modes View header menu. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4117]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/76331617-ac3e-49c3-be19-70db0cdbc145)

Kinda a short hand way to change modes in the outliner, by popping a new window out, could be redundant if you already in the outliner. Right now you can access this operator also in the orphan data of the Bforartists Unused Data mode, so that deffo is redundant there... so.. make it useful? 

Could use the same cleanup icon. 

> An operator that brings up a window with Outliner in "Unused Data" mode to allow users fine-grained control over protecting and purging.

In the File header, add seperator and icon. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/84f5dbf7-5b59-4eb8-9d5b-a4dd7ff70e65)

Then document... 

## Question
Should we remove, since it's redundant? Or do as I suggest, move to the view header of the outliner in other modes?

**Comment by ReinerBforartists** [comment]
You decide :)

I'm already too long away from it to have a useful saying here i fear.

**Comment by Draise14** [comment]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/40ca818e-675c-4c20-9675-20ee0861e280)

Got it, now documenting.
