### ISSUE TITLE
3D View - Sculpt mode - Sidebar - Symmetrize has a label, indent child content

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4118]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/aaeb5508-b048-4999-ba57-1c60e9492e68)

Indent. Update documentation.

**Comment by ReinerBforartists** [comment]
Documenting

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/970c8a9d-4737-478a-b1c6-a67141aaca13)

**Comment by ReinerBforartists** [comment]
Fixed
