### ISSUE TITLE
Update the github actions workflows

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4119]
We need to update the github workflow xml files. They all works still with svn for the libs ...

![updateworkflows](https://github.com/Bforartists/Bforartists/assets/13919702/1571e992-85df-4595-8b14-ae459ea3b40e)

**Comment by ReinerBforartists** [comment]
Lemme test this here.

**Comment by ReinerBforartists** [comment]
Fingers crossed. 

This one will fire with the next pull. Let's see how it turns out.

**Comment by ReinerBforartists** [comment]
Still fails -.-

@iyadahmed , human requestz assistance ^^

**Comment by ReinerBforartists** [comment]
> The required external libraries in lib/windows_x64 are missing
> 
> Would you like to download them? (y/n)Not downloading libraries, until this is resolved you CANNOT make a successful blender build.

It does not download the libs. I think make update does this O_O

**Comment by iyadahmed** [comment]
> Still fails -.-
> 
> @iyadahmed , human requestz assistance ^^

Will fix it no worries, but basically I think we don't need the `make_update.py --use-linux-libraries`
But we need to install git lfs

**Comment by ReinerBforartists** [comment]
Ah this is the part that i missed. Thank you.

At linux you need the make update.py part afaik

**Comment by ReinerBforartists** [comment]
Your turn :)
