### ISSUE TITLE
Timeline - Mute is now.. inversed to be "Play Sound"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4129]
# Blender
![blender_jp1rx2zO0I](https://github.com/Bforartists/Bforartists/assets/35357409/d09d3dd0-0e97-4a80-9340-c44f7822c20d)

# Bforartists
![bforartists_2HbOr3WL1r](https://github.com/Bforartists/Bforartists/assets/35357409/0a433447-cc14-45c7-bde5-09fe744c7659)

wth, why this change I don't know... but it screwed me over an hour trying to make the sound work, lol

# Task:
1. Rename label to be "Play Audio"
2. Make sure default installation has it "turned on"
3. Keep the API and UX the same as Blender. 
5. Update documentation

**Comment by Draise14** [comment]
Iyad brought up a good point. This toggle is now "Play Audio" in Blender. So if we load a blend file with it's setting stored as activated, it should also activate in Bforaritsts, or unmuted (inversed) in the same file setting.

**Comment by ReinerBforartists** [comment]
They changed it, so we should change it too for consistency reasons. Even if this introduces the same trouble than in Blender. We promised to deliver the same functionality ...

**Comment by iyadahmed** [comment]
> They changed it, so we should change it too for consistency reasons. Even if this introduces the same trouble than in Blender. We promised to deliver the same functionality ...

I think they didn't change it, it was always like this?

**Comment by Draise14** [comment]
Blender changed it recently. 

Yeah, this case would be KISS, and rename the label and make the default play instead of mute. 

I still don't know why they did this....

**Comment by Draise14** [comment]
Sorry bout the confusion @Blenux and burning your time, I should have been more explicit with the task.

**Comment by Blenux** [comment]
All good mate.

**Comment by Draise14** [comment]
Documenting

**Comment by Draise14** [comment]
Commit to master
