### ISSUE TITLE
registering .blend files with bforartists not working properly!

### ISSUE THREAD

**Issue by cl3m3c7** [Bforartists/Bforartists#4130]
**Describe the bug**
If I try to register .blend files with bforartists downloaded as a ZIP archive (not the installer!), I got back `Unable to register file association` error message!

`Preferences` -> `System` -> `Operating System Settings` -> `Open blend files with this Bforartists version` -> `Register`

**Desktop:**
The Operating system: Windows 10
Graphics card: NVIDIA GeForce GTX 1050 Ti

**Screenshots, Example Files**
![Untitled](https://github.com/Bforartists/Bforartists/assets/61097104/d5f2824a-79fe-4825-bc1d-08121e207b21)

**Note:**
I think the culprit is: `https://github.com/Bforartists/Bforartists/blob/0aca6797c521370ef8b4cff4ec84c7bf4c4f9337/source/blender/blenlib/intern/winstuff.cc#L172`, since I don't have the source at the moment, I couldn't neither test it nor make a pull request. sorry :)

**Comment by Draise14** [comment]
You will need to run Bforartists with administrator privileges to make it work. If not, it won't have rights to change system registries. If in Windows, right click, run as administrator, then try again.

**Comment by cl3m3c7** [comment]
no it is not the permissions, if you see the line of code, it looks for blender.exe in the path which does not exist :)

and the permissions needed only for all users and it will prompt UAC

**Comment by Draise14** [comment]
Ah, good point. Did a test now, will commit the fix. Compiling to see if that was it.

**Comment by Draise14** [comment]
Yep, that seems to have fixed it.

**Comment by cl3m3c7** [comment]
@Draise14 btw, is the fix will be available in the upcoming 4.1?

**Comment by Draise14** [comment]
Yeah, for sure.
