### ISSUE TITLE
Turn on soft falloff for the workspace default lights

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4137]
There is a new option called soft falloff. New created lights have it on. Our default light in the workspace has it off. 

Turn it on for consistency reasons.

Related: Properties Editor - Lamp and Spotlight object - Light Tab - Float the new Soft Falloff option to the left #4100

**Comment by ReinerBforartists** [comment]
![softfalloff](https://github.com/Bforartists/Bforartists/assets/13919702/4f07703b-3b69-42ea-8b74-b9502473557d)

**Comment by Draise14** [comment]
Would this be saved in the startup.blend files?

**Comment by Draise14** [comment]
Commit to master
