### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#4144]
**Describe the bug**
b4a crashes on launch (it vanishes even before I get to see the flash screen.)

**Desktop (please complete the following information):**
Win 11 Home,
devbuild-15-03-2024

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment]
Thanks for the report

Hm, at Windows 10 it still starts without flaws. Could you please start BFA from console and give us the output then?

**Comment by raindropsfromsky** [comment]
I deleted the contents of my installation folder, and unzipped the content once again.
Now it gets launched fine.

I could not conclude why it used to crash.

Blender 4.2 Alpha works fine (I have the last week's version).

**Comment by ReinerBforartists** [comment]
Ah, great that you got it working now. Maybe the content wasn't fully unzipped the first time :)
