### ISSUE TITLE
Geometry nodes - add icon to Sort Elements node, add to sidebar, document

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4155]
A slipped through node that needs icon and documentation.

![sortelementsnode](https://github.com/Bforartists/Bforartists/assets/13919702/d33a98d0-a68f-4cac-b7e1-acc2f7c417c9)

**Comment by Draise14** [comment]
Duplicate, I msut have mislabeled. 
 Geometry Nodes - Add - Geometry - Operatations - New Sort Index node #4087
