### ISSUE TITLE
Remote repositories showing up in git changes

### ISSUE THREAD

**Issue by esnosy** [Bforartists/Bforartists#4167]
![image](https://github.com/Bforartists/Bforartists/assets/25552173/a7619a47-2d87-40b9-97c3-4c6acb5f92f4)

I vote for making .gitignore closer to Blender, only ignoring directories that we have modifications in, leaving the rest same as Blender's .gitignore

**Comment by ReinerBforartists** [comment]
Sure. Every change must have a reason. And when such a reason is not given then we better go the Blender way.

**Comment by ReinerBforartists** [comment]
Mh, the libs though ... sometimes it's a good idea to be able to pull libs directly. So not sure if we should exclude them.
