### ISSUE TITLE
3D View - Sculpt Mode - Header Face Sets error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4171]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/024e5209-e408-43e6-b8fb-f7eaf02abeeb)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/65bb65c3-f4b1-4d66-b85e-17bab2b76b7a)

ALL not found (Outside or Inside)

**Comment by ReinerBforartists** [comment]
We have the two show hide face sets operators too many, they are not longer available. And miss the randomize color operator.

![facesets](https://github.com/Bforartists/Bforartists/assets/13919702/70b733e2-8fcc-4122-b5da-9329ecd0d216)

**Comment by ReinerBforartists** [comment]
Hmm, we need to reassign the ctrl I hotkey to invert mask.

**Comment by ReinerBforartists** [comment]
Related: Sculpting, Facesets menu - add hotkey only Face Sets Visibility operators #4173

That's also where the documentation happens then. This taks is fixed. Removed the two show hide operators.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/0132f727-18f9-4802-bc8b-a88d98aebf40)
