### ISSUE TITLE
Crash to desktop with switching to VFX template

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4176]
Surprise :D

Crash happens when switching to the VFX template. 

![vfx](https://github.com/Bforartists/Bforartists/assets/13919702/37c10e9c-37dc-4b61-9b50-2484f11b48f0)

![crash](https://github.com/Bforartists/Bforartists/assets/13919702/7a1b50c1-a5f0-41bd-8ac7-a6550d9fa6bb)

[bforartists.crash.txt](https://github.com/Bforartists/Bforartists/files/14801931/bforartists.crash.txt)

**Comment by ReinerBforartists** [comment]
Grabbed the 4.01 version, readded 3d sequencer workspace, fixed the toolbars.

Seems to work fine now again.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/eb5d91fd-b5c4-408b-8b99-5becf55eb264)
![repeat](https://github.com/Bforartists/Bforartists/assets/13919702/cd19d37e-6c26-43e2-9310-6b5ebcddc38b)

**Comment by Draise14** [comment]
The VFX workspace shouldn't have the 3D Sequencer, that's for the Video Editing and All
