### ISSUE TITLE
little typo!

### ISSUE THREAD

**Issue by cl3m3c7** [Bforartists/Bforartists#4186]
**Describe the bug**
typo in the description: `RRemoves a frame and nudges all frames on the left  towards the timeline cursor`, note the double R in the beginning.

`https://github.com/Bforartists/Bforartists/blob/7ee46e563603708c0d9d88a1f064b74885d8b0ee/scripts/addons/bfa_power_user_tools/ops.py#L117`

**Comment by esnosy** [comment]
Fixed many thanks for report!
