### ISSUE TITLE
3D View - Add "Remove Smooth by Angle Modifier" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4191]
![bforartists_xpyXoTcKXu](https://github.com/Bforartists/Bforartists/assets/35357409/8aaaab6c-bc14-4c7e-9857-1579dcf5d9b4)

Once you add a Smooth by Angle modifier (potentially from the 3D View in the near future) - you will have to go to the stack, dig for the modifier, then remove it. This could be automated. 

So if it's added, the button to remove should show. And do it on selected when holding down ALT. 

This would be more reliable and implicit that this is a modifier in the stack instead of a "state". 

**Relevant Tasks:**
#4187

**Comment by ReinerBforartists** [comment]
Not sure if good idea to add an operator to remove a modifier. We have, umm, around 100 modifiers?

**Comment by Draise14** [comment]
It would be an operator to only remove the smooth by angle modifiers, and on selected. Right now there is no way to remove this modifier from a selection of objects without doing it one by one by one by one.....

**Comment by ReinerBforartists** [comment]
Same counts for other modifiers too. SDS for example. Which has other operators to control the SDS modifier. Question is, how often do you need to change it? Does it justify to add another operator to steer this modifier?

**Comment by Draise14** [comment]
Ah, I guess the remove on selected should only work for modifiers added from the 3D View, which would be SDS and Smooth by Angle only. The rest is added and removed from the modifier stack. 

I would justify this since many users have requested this workflow (add/remove autosmooth) so the consistency would be to add the "remove SDS" on selected operator. 

The others are not added from the 3D View so don't require granular operators to add/remove on selected.

**Comment by Draise14** [comment]
If anything, maybe I could add this to the Power User Tools if this is considered bloat...

**Comment by ReinerBforartists** [comment]
You decide. I just pointed at a possible approach to decide if this is necessary or not :)

**Comment by Draise14** [comment]
Completely valid. If using the modifier stack was nicer... hmm.......... Maybe that's a better system. 

Made another experimental task to make the angle adjust too.

**Comment by ReinerBforartists** [comment]
Sorry for being mean, was not my intention ^^

**Comment by Draise14** [comment]
You know what, this remove operator.. let's close, and instead find a way to "remove from selected" directly inthe modifier stack, since we have copy to selected.

**Comment by ReinerBforartists** [comment]
That's the spirit !
