### ISSUE TITLE
3D View - Sculpt Mode - Repeat Sculpt header operators should be legacy

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4194]
![bforartists_nbDmGeaIvO](https://github.com/Bforartists/Bforartists/assets/35357409/8e9e464a-36e8-454d-8efe-f560b98480fc)

A bunch of operators are duplicates, already in the toolshelf. They are... new "legacy" operators. We could minimize the sculpt header by.. moving them up and out, and also can minimize the toolshelf a bit.

These also show in the tabbed toolshelf... Also remove
![bforartists_kEoZJyrZBk](https://github.com/Bforartists/Bforartists/assets/35357409/6cd8743c-0820-4ce0-8b14-6bfa76ff264b)

## Relevant Repeats:
- Box/Lasso Show/hide
- Box/Lasso Trim
- Line Project

**Exceptions:**
- Box Add
- Lasso Add are

**Comment by ReinerBforartists** [comment]
Good catch !

**Comment by ReinerBforartists** [comment]
Documenting ...

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/489fff3a-845f-4629-8046-c0f23657da65)
