### ISSUE TITLE
3D View - Sculpt - New Line Hide/Show tools (legacy)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4196]
![bforartists_zMdiEL997c](https://github.com/Bforartists/Bforartists/assets/35357409/3c2571c2-1888-4145-9b82-06028e05d294)

Needs icons, then moved to legacy. Related to #4194

Also documentation... it's the same as the toolshelf ones, so.... all good for documentation maybe? 

<details>
<summary>Details</summary>

SHA-1: 6e997cc75723b0dfc4d25d8246f373d46a662905

* Sculpt: Add Line Hide tool

This PR adds the *Line Hide* tool and the corresponding
`PAINT_OT_hide_show_line_gesture` operator to Sculpt Mode.

*Line Hide* supports common modal functionality including:
* Snapping to angles
* Flipping the selection area
* Moving selection area

Addresses one of the tools in #80390

Pull Request: https://projects.blender.org/blender/blender/pulls/119671

</details>

**Comment by Draise14** [comment]
Looks like some icons were added, and these were moved to legacy already, so will create the icons.

**Comment by ReinerBforartists** [comment]
These are already added. This task is already fulfilled. I did it when i moved the content to legacy :)

Git fetch git pull, compile ^^

![added](https://github.com/Bforartists/Bforartists/assets/13919702/a2985b0f-7fe6-4ceb-a4d6-8f5dac31cf96)

**Comment by Draise14** [comment]
I will make new icons for it eitherway for consistency. In process.

**Comment by Draise14** [comment]
![LINE_SHOW](https://github.com/Bforartists/Bforartists/assets/35357409/f8e3c37e-d541-486c-9870-25400784a0c6)
![LINE_HIDE](https://github.com/Bforartists/Bforartists/assets/35357409/6903bc95-b806-4e93-9378-be8c7255922b)

Two new icons.

**Comment by Draise14** [comment]
![bforartists_aH4UETitGP](https://github.com/Bforartists/Bforartists/assets/35357409/5fe00912-3813-4b9e-a694-571eab05683f)

Documenting, and pushing to master.
