### ISSUE TITLE
Timeline - Play In labels needs love

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4199]
![bforartists_lwUBlIClab](https://github.com/Bforartists/Bforartists/assets/35357409/4b7bfeed-eca6-4bb4-b360-fbd5af5d38c6)

1. `Play In` is gramatically incorrect (prepositions don't contain capitals)
2. The update to the Properties and Sidebars didn't bleed through

<details>
<summary>Details</summary>

SHA-1: 0b30cb1929f938c500847f39ffce850cc75ad8fc

* UI: Clarify Playback "Play In" option

The "Play In" > "Properties Editor" option is not only updating Property
Editors but also the sidebars of other editors (such as the 3DView).

This caused a bit of confusion since we also have "Play In" > "3D
Viewport" (which only updates the 3DView main region but not the
sidebar)

So now call the option "Properties and Sidebars" in the UI ("Editor" has
been stripped to fit the text - but also since the editor is usually
only called "Properties" e.g. in the editor dropdown).

Came up in #120012

Pull Request: https://projects.blender.org/blender/blender/pulls/120305

</details>

**Comment by ReinerBforartists** [comment]
A sidebar is now an editor? O_O

**Comment by Draise14** [comment]
Documenting
