### ISSUE TITLE
Toolbar - Add Subdivide to topbar toolbars in edit mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4200]
![bforartists_36CEplKJXS](https://github.com/Bforartists/Bforartists/assets/35357409/d2008772-eb60-4d73-bd56-73241102780d)
![bforartists_zWyOmAeScC](https://github.com/Bforartists/Bforartists/assets/35357409/2eb4d39a-f7ae-4fc1-8372-a4b9c3d93360)

Seems the subdivide group of the Mesh Edit Edges Subdiv group doesn't have.. Edge Subdivide..............

**Comment by ReinerBforartists** [comment]
It's the normal subdiv that is missing, not edge. Edge is there. But good catch :)

**Comment by ReinerBforartists** [comment]
The traditional toolbar is also affected. So fix code for both.

![both](https://github.com/Bforartists/Bforartists/assets/13919702/b5b5030c-05d7-40c5-84ab-3b4510e9dc15)

**Comment by ReinerBforartists** [comment]
Documenting
![sds](https://github.com/Bforartists/Bforartists/assets/13919702/18d030d8-502f-45a6-8b37-ea3eb30c228e)

**Comment by ReinerBforartists** [comment]
Documentation done.

**Comment by Draise14** [comment]
Huh, it wasn't documented? 😶

**Comment by ReinerBforartists** [comment]
Ah, forgot to push ... ^^

Did you document it?
