### ISSUE TITLE
Sequencer - Missing icons in context menu and Changel Scene strips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4202]
![bforartists_f3ARb0uX66](https://github.com/Bforartists/Bforartists/assets/35357409/9ff5ce14-d0a9-429c-a8a9-4618c7d61c85)
![bforartists_RfnwfC9nZj](https://github.com/Bforartists/Bforartists/assets/35357409/a3314e3d-96f1-4a2e-b1bc-1a59dbd7488d)

Update Frame Range and Change Scene Strips name has missing icons. May need documentation. 

Update Frame Range in the context menu is missing an icon, but one is already used.

**Comment by ReinerBforartists** [comment]
I don't think that we need an icon here. We usually don't iconize menus. And this is a menu that lists the active scenes.

![noicon](https://github.com/Bforartists/Bforartists/assets/13919702/91a96461-e577-43b4-9266-b82391598e78)

**Comment by ReinerBforartists** [comment]
Mh, but why three hierarchies deep? O_O

**Comment by Draise14** [comment]
The change scenes work may need some love in another task.

1. If few scenes it shows a sub menu that goes deep, if many scenes it shows an operator. 
2. This menu is dynamic and contextual based on selection.

**Comment by ReinerBforartists** [comment]
> 1. If few scenes it shows a sub menu that goes deep, if many scenes it shows an operator.

Can you please elaborate here? I cannot reproduce.

**Comment by Draise14** [comment]
![Image](https://github.com/Bforartists/Bforartists/assets/35357409/2e4c5e61-087c-4a6a-a96e-893796b4fbf7)

Here it is. Basically if there are less than 10 scenes, it will show an enum listing the 10 scenes. If more than 10, then it will show a single operator. Right now... the enum is a sub-menu in a single menu, the change one... now thinking how to do this....

**Comment by Draise14** [comment]
Ok, here's what's up. The Change sub-menu seems to be unneccassry and we could run the conditional directly in the strip menu, so these are contextual based on the strip selection directly in the strip menu instead of the change, then not need to use the change sub-menu (which could be singular.

**Comment by Draise14** [comment]
https://github.com/Bforartists/Bforartists/assets/35357409/728fd419-5543-4a2e-8722-eb69954f16b9

Ok, yeah, that's way better. And now the change file/path is also not in a single sub-menu, but on surface. 

Documenting.
