### ISSUE TITLE
Properties Editor - Armature Tab -  New rename collection operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4207]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/73df9b72-d497-44ae-9594-dd2685b49b2e)
Icon exists, add it and document it. 

Also.. add it to the side menu for discoverability per consistency (not hidden in context only)

<details>
<summary>Details</summary>

![image](https://github.com/Bforartists/Bforartists/assets/35357409/86c82ea4-1ac3-4af5-aac4-cd982bd9e34b)

</details>

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Hm, we don't have the right click menu documented yet.

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by Draise14** [comment]
Should we remove from Outliner too? This is now hotkey only.... 

We don't do that.

**Comment by Draise14** [comment]
Hang on, I'm not at computer so will review.

**Comment by ReinerBforartists** [comment]
Mh, we need to expose for the hotkey. That's why i have added it then ...

So all well :)
