### ISSUE TITLE
3D View - Hair Curves Object - Edit Mode - New Add menu, add hotkey SHIFT+A for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4208]
![image](https://github.com/Bforartists/Manual/assets/35357409/6b8c49d7-1580-4482-a7bd-8ed3d6652b67)

New add menu, two new curves you can add, SHIFT+A should be added for consistency to the default hotkeys here. 

<details>
<summary>Details</summary>

SHA-1: 549d02637af6844dca697b068f4aad8c6358263d

* Curves: add menu to add some primitive curves in edit mode

This adds operators to add a bezier and circle primitive in curves
edit mode. The operators support the same settings as in the
legacy curve edit mode. The `shift+A` shortcut is added as well.

Pull Request: https://projects.blender.org/blender/blender/pulls/120513

</details>

**Comment by ReinerBforartists** [comment]
![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/cfdb2ad0-6c0e-44c5-9322-2397d85bf46d)

Fixed
