### ISSUE TITLE
Properties Editor - Object Tab - Motion paths - Collapse hidden content (before and after colours)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4210]
![bforartists_T1Q8pIpoh1](https://github.com/Bforartists/Bforartists/assets/35357409/2b009ec0-23c5-4f33-847d-3ff50af8e1ef)
And also.. document this, this is a new feature where you can color before and after colours. 

<details>
<summary>Details</summary>

SHA-1: 883af6dd63d18c1eea11f60c05ef767ca1f62de1

* Anim: Add custom pre and post frame color to motion path

This PR adds an option to specify custom colors for a
motion path. One for frames before the current frame
and one frame for after. With this it is easier to see
the relation of the motion path to the current frame.
That was already the case with the default colors, but
not with custom colors.

On a technical side note, the colors pre and post the current
frame were already different.
The shader multiplied the custom color by 0.25
for anything pre current frame.

Pull Request: https://projects.blender.org/blender/blender/pulls/119375

</details>

**Comment by ReinerBforartists** [comment]
Manual frame range is also greyed out ...

**Comment by ReinerBforartists** [comment]
Uh, and cached range too. Let's separate these tasks.

**Comment by ReinerBforartists** [comment]
Hm, forgot to indent. Not too late ^^

**Comment by ReinerBforartists** [comment]
![indent](https://github.com/Bforartists/Bforartists/assets/13919702/a8465154-1908-4baa-8f97-07d109c926dc)
Better

**Comment by ReinerBforartists** [comment]
Done
