### ISSUE TITLE
Hotkeys - Update CTRL to OSKEY for Mac keymap

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4216]
Reported by @ReinerBforartists in discord, a lot of CTRL hotkeys bleed through. CTRl should be OSKEY for mac users, so update the keymap.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fc5e3ff3-6296-42f5-b729-815a953e7b1b)

Documenting

**Comment by ReinerBforartists** [comment]
We need to revert this. The Mac keymap is now not longer in sync with the windows keymap. And has partially different hotkeys. We cannot ship it in this state.

![desynced](https://github.com/Bforartists/Bforartists/assets/13919702/e1852d9e-ac7d-4db2-a92b-5466e8b285e5)

**Comment by ReinerBforartists** [comment]
Reminder. The only difference between the regular and the mac keymap shall be the little word oskey where we have ctrl in the regular map.

Another reminder, since i stumble across it now, NEVER mix tasks. This task was to udpate the mac keymap. Not to add all the things that you miss.

**Comment by ReinerBforartists** [comment]
These four entries are the only exception. I have no idea if mac has left and right oskey ...

![remaining](https://github.com/Bforartists/Bforartists/assets/13919702/e69b79dd-cf52-4d6c-b8fc-13aedddaafdb)

**Comment by ReinerBforartists** [comment]
Fixed. Please don't break it again ;)

What i can not revert is the documentation that you have changed. But that's mainly because i don't want to revert the other changes that you did besides updating the os keymap. I hope you remember what you did, and hope that it still fits ^^

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/07a11307-9e3e-4748-b546-af3270fdea00)

**Comment by ReinerBforartists** [comment]
Ah, indeed, now i see what you mean. Never noticed it. But there were entries that changed from shift to oskey with your update. And that's not how it should be.

One's for sure, it becomes a maintain nightmare when the osx keymap dramatically differs from the windows keymap. I suggest to revisit this problem after the release.

![macos](https://github.com/Bforartists/Bforartists/assets/13919702/556b364c-ec09-4be1-b05f-a19abcb29c95)

**Comment by Draise14** [comment]
![IMAG0161-843167357](https://github.com/Bforartists/Bforartists/assets/35357409/11c77d91-4bcb-4b4d-89f2-05d94ca771a7)

Maybe we don't need to use OSkey... Mac's have Ctrl.

**Comment by ReinerBforartists** [comment]
Let's ask our mac users :)

**Comment by ReinerBforartists** [comment]
Just thinking here. Ideally somebody with a mac should do these changes, then export the keymap. To do this at the python file is cumbersome and error prone.

**Comment by ReinerBforartists** [comment]
Okay, found a way to do it at Windows from within the keymap manager. We have in fact a button to add the MacOS command (also known as oskey) here ...



![ctrl](https://github.com/Bforartists/Bforartists/assets/13919702/99694d8e-d264-46ca-8faf-498ca608f7a3)

**Comment by ReinerBforartists** [comment]
First i fixed the order of alt and oskey. They have another order than in the regular map.

**Comment by ReinerBforartists** [comment]
Done. All remaining stuff like the modal maps are changed. Now we have eight of these remaining leftctrl and rightctrl entries. But as told, i think we can live with these not working.
