### ISSUE TITLE
Build blender thumbnailer and launcher

### ISSUE THREAD

**Issue by esnosy** [Bforartists/Bforartists#4217]
Right now blender thumbnailer is commented in the CMake code, and blender launcher is also not renamed to Bforartists-Launcher or something

the task is to ensire both of these work and maybe replace the name blender with bforartists (this is not the only needed change)

due to Blender Thumbnailer being commented out we also get this error when running CMake install
```
CMake Error at source/creator/cmake_install.cmake:689 (file):
  file INSTALL cannot find
  "F:/bfa-git/Bforartists/cmake-build-release-visual-studio/lib/Release/BlendThumb.dll":
  File exists.
Call Stack (most recent call first):
  cmake_install.cmake:105 (include)
  ```

**Comment by Draise14** [comment]
I guess the blender-launcher could be the Bforartists-Launcher..
