### ISSUE TITLE
Timeline Editor - Double props, should only be in the properties area

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4225]
![bforartists_hf9Z6BmmVi](https://github.com/Bforartists/Bforartists/assets/35357409/c7a15190-5ff3-4b59-8f03-4536d40b01e9)
![bforartists_LMphMBdK9n](https://github.com/Bforartists/Bforartists/assets/35357409/934de64f-38f0-44a0-9c9e-df915ba04017)

Looks like some bleed through with a merge. Remove from header, as most props shouldn't be there, unless interface toggling relevant.

**Comment by ReinerBforartists** [comment]
The order is also odd. Investigating.

**Comment by ReinerBforartists** [comment]
The manual is a tad bit outdated it seems. But first let's fix the menu.

**Comment by ReinerBforartists** [comment]
I have removed the out commented legacy code blocks. This does not make any sense in our python files. We would need to add the whole Blender python code then too ...

Documenting

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/56693628-eb55-43c9-92bb-4ed390ac323e)

**Comment by ReinerBforartists** [comment]
Fixed
