### ISSUE TITLE
Sequencer - Expose hidden "Delete Retiming Data" operator to GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4227]
https://github.com/Bforartists/Bforartists/assets/35357409/d506f634-cd5e-4178-9f06-f367857a4e6f

Right now in Bforartists there is no way to "delete" a retiming hotkey on a sequencer strip. In Blender too. But there is an operator that can (with an option of "Use Retiming Data". This is possible... but only if you happen to mouse over the retiming bar.... it ain't obvious. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/3271a82a-6c47-427a-998d-a82f1ff688fb)

This should be exposed to the retiming menu.... so you can assign a hotkey and find it.

**Comment by ReinerBforartists** [comment]
It would have been nice to know what exactly you are doing here. When writing an issue, imagine that the one who reads it is not you, and doesn't magically know all the steps involved.

Either ways, the operator already exists, it just misses an icon. The tooltip seems also off. And i am still riddled how this all even works. Sometimes it deletes the retiming keys, sometimes not. And you did not mention how your method with the mouse over works. I cannot get it to work.

And what is also mysterious is the adjust last operator that pops up when i am with the mouse over the retime key and press DEL

![emptyadjustlast](https://github.com/Bforartists/Bforartists/assets/13919702/c4baedfc-a938-4b9c-86fe-72ec66ecf668)

**Comment by ReinerBforartists** [comment]
Mh, can of worms. We miss a menu item compared to Blender here.

![rightclick](https://github.com/Bforartists/Bforartists/assets/13919702/8e5c20dd-aa43-4890-a479-dc9f6d62c30c)

**Comment by ReinerBforartists** [comment]
Let's create two bug reports for Blender here. Something is off. The last operator should not stay empty. And the hotkey X is dysfunctional.

**Comment by ReinerBforartists** [comment]
Huh, now it works as intended O_O

**Comment by ReinerBforartists** [comment]
Ah, the empty adjust last operator comes from deleting the strip. And Blender has a hotkey conflict here. Deleting strip is X, and deleting retiming hotkey is also X. So two issues to report ...

**Comment by ReinerBforartists** [comment]
https://projects.blender.org/blender/blender/issues/124090

**Comment by ReinerBforartists** [comment]
We should add a delete hotkey to the Delete Retiming Keys item like Blender has. I suggest to use the DEL key. Not the X key.

Task Summarize: 
Add hotkey
Add Icon
Add missing Delete Retiming Keys operator to the context menu.

Three tasks again ...

**Comment by ReinerBforartists** [comment]
Fixed tooltips. The one from deleting strips was also off.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/585b42df-f488-46d2-8c87-d607b95a9cb7)

**Comment by ReinerBforartists** [comment]
Task done, documenting ...

**Comment by ReinerBforartists** [comment]
Interesting. Hotkey did work when i tested it. Now it fails, the delete key from removing the stip overrides it. Must have something to do with how the keys are set up. Since in Blender the delete key works just fine.

I will make a new issue for it.
