### ISSUE TITLE
Devops - Get Bforartists on Windows Store (and in turn get it certified for the installer)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4229]
Iyad and I have had a quick look at getting Bforartists certified and on the Windows App store. It's doable, and has a side benefit that we would also get the installer certified. It also isn't as expensive as we thought, so I'm thinking to make a tracker to do, get on the Windows Store, and get the installer certificate while at it. 

> Benefits of Windows certification
> 
>     Participate in the multi-billion dollar Windows software market and biggest release of Windows
>     Be featured as compatible in the Windows setup compatibility report
>     Be listed in the Windows Store, with millions of potential customers around the world (Windows 8.1 only)
>     Have access to marketing assets and training from the Microsoft Partner Network
>     Earn certification logos to easily identify your app as high quality and Windows compatible
>     Give your customers confidence in the quality of your product

https://learn.microsoft.com/en-us/windows/win32/win_cert/windows-certification-portal

**Goal of this task is to:**
- Document the in's and out's of how
- Get the installer certified officially (I can purchase that if necessary)
- Put Bforartists on the Windows Store (free)

**Comment by esnosy** [comment]
https://www.microsoft.com/store/productId/9PD5L5XBRMR0?ocid=pdpshare

**Comment by Draise14** [comment]
HOLY CRAPPOLA! That's great! You did it!!!!!! What does this mean now!? We should update the website!

**Comment by esnosy** [comment]
> HOLY CRAPPOLA! That's great! You did it!!!!!! What does this mean now!? We should update the website!
> 
> How do we maintain this? What are the steps?

sorry for delay here are the steps, I have been preparing them this entire time

1. Make a release build
2. Open a "Developer Powershell for VS 2022" from using start menu search (comes with Visual Studio installed)
![image](https://github.com/Bforartists/Bforartists/assets/25552173/b2193136-c395-41e5-9858-a19f54ac25d4)
3. Navigate to where you have the source code using the `cd` command
![image](https://github.com/Bforartists/Bforartists/assets/25552173/6dd05bec-6d68-445c-b7f1-dc0904d6d305)
4. Run the script using python (replace 4.1.1 with correct version)
`python.exe .\create_msix.py ..\bfa_build_windows_Release_x64_vc17_Release 4.1.1 store`
![image](https://github.com/Bforartists/Bforartists/assets/25552173/8eea92e8-5404-4307-80a4-44f5373e402c)
5. Upload the .msix (you can find in a directory called "msix" one directory above the source code to somewhere where I can download it, or if you have direct access to the Windows Store you can upload it there
