### ISSUE TITLE
Sequencer - Sidebar - View panel - Snew Show Missing Media oeprator  float left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4231]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8655bdaa-e654-4755-bc89-9e289c970fd6)

New operator to show missing media exists now. 

Also has a new presentation for documentation. 
<img width="1211" alt="vse-missing-now" src="https://github.com/Bforartists/Bforartists/assets/35357409/3dfc84f2-6e8c-439d-b6b2-a2849c6df89f">

<details>
<summary>Details</summary>

SHA-1: c64050ecd23a1f5ba81076ba9ad71b59d8f66ca9

* VSE: Timeline strip visual design updates

Design updates as per #118288:
- Tweak text labels (colors, drop shadows)
- Strip border colors, inset outlines
- Muted strips are mostly gray, and their thumbnails are faded
- Overlapping strips are not semitransparent anymore
- Locked stripes only in content area
- Missing data blocks
- Updates to meta strips w/ missing data blocks

Pull Request: https://projects.blender.org/blender/blender/pulls/118581

</details>

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Fixed
