### ISSUE TITLE
Geometry Nodes - Utility - New Matrix category of nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4232]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5687a2c7-c784-46a8-ae3b-2a948596c00a)
These are now moved out of experimental. Located in the Utitility group, new nodes, new icons, new documentation - all about matrices. 

- Combine Transform
- Invert Matrix
- Project Point
- Multiply Matrices
- Separate Transform
- Transform Point
- Transform Direction
- Transpost Matrix

<details>
<summary>Details</summary>

SHA-1: 3cd1c365c38ea51544c770a78eccaf0c15993734

* Geometry Nodes: Add Project point matrix node

With the matrix socket being introduced into geometry nodes, we
are starting to deal with more complex transforms like perspective
projection. For those matrices projecting a point is not as simple
as just matrix multiplication, there has to be an additional normalization
step after. To solve that in an intuitive way consistent with how it's
typically solved in code, add a new "Project Point" node.

The canonical use case for now is in combination with the mouse
position, viewport transform, and raycast nodes, to find where the
mouse clicked on the edited geometry.

Pull Request: https://projects.blender.org/blender/blender/pulls/120597

</details>

**Comment by ReinerBforartists** [comment]
Let's have a look to shape a few icons here ...

**Comment by ReinerBforartists** [comment]
Okay, new Icons are in the svg folder. They are added to UI_Icons.hh and CmakeList.txt. The new entries are also in rna_nodetree.cc and NOD_static_types.h. But we have a problem with compilation ...

![compilationfail](https://github.com/Bforartists/Bforartists/assets/13919702/7625361d-868b-4382-8123-b2891394a092)

**Comment by Draise14** [comment]
As mentioned in discord, make sure the SVG file name is lowercase.

**Comment by ReinerBforartists** [comment]
Hmm ... they are lowecase now ...

![lowercase](https://github.com/Bforartists/Bforartists/assets/13919702/92f97ff9-8ed7-422e-98dc-3811689f39f6)

**Comment by ReinerBforartists** [comment]
Ah, the good old cmake cache trap :D

Will commit tomorrow. After i found out why transform direction shows the wrong icon :D


![compiles](https://github.com/Bforartists/Bforartists/assets/13919702/0370614f-8eea-4e63-9ecc-b76b7c9eb28e)

**Comment by ReinerBforartists** [comment]
Issue in the manual tracker exists already. So no documentation here.

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/7a5f8b1d-fb57-4df2-9bd0-36c09bde879d)
