### ISSUE TITLE
Geometry Nodes- Tools Mode - Input - Scene - New Mouse Position node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4235]
![bforartists_p3G8UIw58D](https://github.com/Bforartists/Bforartists/assets/35357409/14c243f2-4ee1-49df-ad96-3e23158b4931)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/beda4ded-5ac4-480a-83aa-23856267fa17)

new Mouse to Position node for the Tools Mode. Location in title. 

<details>
<summary>Details</summary>

SHA-1: ce224fe4010af75c85b300151363dbc37fbbcee6

* Node Tools: Add mouse position node, wait for cursor option

Add a "Mouse Position" node that outputs the location of the mouse
cursor in region space and the overall size of the region, both in pixel
units. Both outputs are integers to help reflect their pixel units.
If there the mouse position is ever accessible in sub-pixels, they can
easily be changed to floats.

Also add a "Wait for Cursor" option similar to the one for some built-in
operators that delay's the operator's execution until there is a mouse
click in the viewport. That way the operator can be called from menus
even though it is interactive. This option is placed in the node editor
header. When there are more options, it will be part of an "Options"
popover panel similar to the existing "Modes" and "types" popovers.

Combined with the viewport transform node, and other nodes like Raycast,
these features can allow making tools that create geometry where you
click in the scene.

Pull Request: https://projects.blender.org/blender/blender/pulls/121043

</details>

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/37f00734-b95b-40a2-b9e1-6bb1a35ef1c5)
