### ISSUE TITLE
Warning: property mode not found in item OperatorProperties

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4240]
We haz a warning in ze console ...

![warning](https://github.com/Bforartists/Bforartists/assets/13919702/678edbc1-d6f1-4f95-8bb4-b0e01a09cf71)

**Comment by Draise14** [comment]
I saw that... How do you find where this is? Is this a hotkey, a rouge operator?

**Comment by ReinerBforartists** [comment]
Mh, it could be a problem with the keymap. Didn't we have similar problems before?

**Comment by Blenux** [comment]
Think I found the issue, thing this was the cause.

https://projects.blender.org/blender/blender/pulls/120797

**Comment by Draise14** [comment]
Ah, silly me, should have tested more. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/8ca85306-a775-4984-9619-5f2fe15c79ed)

**Comment by Draise14** [comment]
I think you're right, the "mode" may need to be removed from those brushes.

**Comment by ReinerBforartists** [comment]
Neither the original error message nor the matches no enum problem shows anymore. At least not that i can see. Let's create a new task in case this strikes back. This one is already two disconnected issues again.
