### ISSUE TITLE
File Browser -Export/Import sub+panel theme needs to be same colour as header. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4246]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b230524b-0fb0-4470-b474-03ab1c1f0fd9)

Seems the headers are squished and have the wrong icons for the drop downs. These are for all exporters and importers. 

- [ ] File Browser - Refactor FBX addon sidebar panels to be consistent and float left (Addon)
- [ ] File Browser - Refactor OBJ sidebar panels to be consistent and float left (C++)
- [ ] File Browser - Refactor ABC sidebar panels to be consistent and float left (C++)

<details>
<summary>Details</summary>
IO: Use panels for Alembic, OBJ, PLY, and STL

Instead of using "box" layouts for these import/export operators, use
panels instead.

Motivation for doing so is two fold.

Firstly the use of panels instead of boxes is more consistent with other
parts of Blender and with other IO addons implemented in Python (FBX,
glTF, 3ds, etc.)

Secondly, in the case of an Import invoked from drag-n-drop or Export
configured on a Collection, the large number of options often exposed
results in very long layouts. Panels allow us to close some sections by
default and allows the user to open/close panels based on their own
needs in general.

Along the way some effort went into standardizing the layout and wording
used as much as possible.

USD is a bigger change and requires some additional coordination. It
will be submitted and reviewed separately.

Pull Request: [#121557](https://projects.blender.org/blender/blender/pulls/121557)

</details>

<details>
<summary>Details</summary>

SHA-1: b773eca1b5809a12e7161c6ec4c7c79c57642133

* IO: Use panels for Alembic, OBJ, PLY, and STL

Instead of using "box" layouts for these import/export operators, use
panels instead.

Motivation for doing so is two fold.

Firstly the use of panels instead of boxes is more consistent with other
parts of Blender and with other IO addons implemented in Python (FBX,
glTF, 3ds, etc.)

Secondly, in the case of an Import invoked from drag-n-drop or Export
configured on a Collection, the large number of options often exposed
results in very long layouts. Panels allow us to close some sections by
default and allows the user to open/close panels based on their own
needs in general.

Along the way some effort went into standardizing the layout and wording
used as much as possible.

USD is a bigger change and requires some additional coordination. It
will be submitted and reviewed separately.

Pull Request: https://projects.blender.org/blender/blender/pulls/121557

</details>

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/13fa08ba-b635-4397-a658-0f18af6715c1)

Ok, comparing to the BVH addon that doesn't have the broken header labels issue.. the formatting is borked.

**Comment by Draise14** [comment]
Maybe making the other defs more like a class or a different system might make sense?

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fa503b4d-4c0a-4269-b9a1-8cc7537c9308)

Found a way by not using the Blender way, and using the traditional panels way.

**Comment by Draise14** [comment]
![bforartists_S0g0i3Oe2L](https://github.com/Bforartists/Bforartists/assets/35357409/fa940d21-578c-4cd2-93dc-a67ec3e1d505)
![bforartists_mYZVdNhIAW](https://github.com/Bforartists/Bforartists/assets/35357409/2e137a22-bff9-48ba-9c12-555d9908d944)

Ok... this may need some work on a case by case (addon) basis. So will commit to a branch and go through.

**Comment by Draise14** [comment]
Updated description, we only need to really fix this for the ABC, OBJ and FBX importer and exporter. 

ABC and OBJ is in C++....... I can fix the FBX; but not the C++ version, that is beyond me right now..........

**Comment by Draise14** [comment]
This commit might help get back the old consistent panels that work nicer. 
https://projects.blender.org/blender/blender/commit/dc1400884796f032105390b25516276c14345f68#diff-6c7f7ee6232ae811561db97198dc4cba973a78a2

STL seems fine, legacy addon and extension
PLY may need work too.

**Comment by Draise14** [comment]
USD was also converted.. I still don't know why the headers are thin.

<details>
<summary>Details</summary>

SHA-1: 06581bde1b90a78898a2d0d8f1d9e5a69f152020

* USD: use panels for Import and Export

Instead of using "box" layouts for these import/export operators, use
panels instead. Many choices for the layout and organization has come
from the `universal-scene-description` branch though it's not a 1:1
equivalent.

Motivation for using panels is two fold.

Firstly the use of panels instead of boxes is more consistent with other
parts of Blender and with the other IO features.

Secondly, in the case of an Import invoked from drag-n-drop or Export
configured on a Collection, the large number of options exposed results
in a very long layout. Panels allow us to close some sections by default
and allows the user to open/close panels based on their own needs in
general.

Along the way some effort went into standardizing the layout and wording
used as much as possible.

Pull Request: https://projects.blender.org/blender/blender/pulls/122415


</details>

**Comment by Draise14** [comment]
Ideally this should fix to make maintenance easier in the future, with the new panel code... but for the life of me I have no idea how it is borked. Re-writing the C++ code to be the former layout might be a hard one to maintain.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/73aa42a5-2fe9-4436-a576-cff35fe4a7c8)

Solution... change the theme. 

KISS. 

They are not traditional sub-panels, but now all of of them look ok.

**Comment by ReinerBforartists** [comment]
May i remind that we decided not to maintain addons? This here will regularly slap back ...

**Comment by Draise14** [comment]
Sure thing.theme update it is.

**Comment by ReinerBforartists** [comment]
Is the small panel headers issue fixed ? Then the theme change would be another issue.

**Comment by Draise14** [comment]
I'll change the title to fix the theme.

**Comment by ReinerBforartists** [comment]
Yeah, but is the small header issue fixed? :)

**Comment by Blenux** [comment]
This was the issue for the sub panel headers,

![image](https://github.com/Bforartists/Bforartists/assets/25260650/12601457-fc46-4de0-af6f-a12a162d2fa4)

and then change col to panel->layout

**Comment by Draise14** [comment]
Fixed via.. the real fix #4397
