### ISSUE TITLE
Geometry Nodes - Utilities - New Align Rotation to Vector and Rotate Axis nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4248]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/073bae70-aa07-47d8-be28-49d96689ae48)
> A version of "Align Euler to Vector" with the rotation socket instead of the vector Euler socket. Other than that, and a few cleanups to use newer math functions, the node is the same.

One of these could use the Rotate to Eurler icon, the other might be a new icon. 

<details>
<summary>Details</summary>

SHA-1: 462e7aeeddd175ef6acca73869dd214bd56b4210

* Geometry Nodes: Add Align Rotation to Vector node

A version of "Align Euler to Vector" with the rotation socket
instead of the vector Euler socket. Other than that, and a few
cleanups to use newer math functions, the node is the same.

The old node is just "Deprecated" for now. We could remove
it with versioning, but we can also wait to do that.

In a simple test this node is about 1.7 times faster than the old one.

Pull Request: https://projects.blender.org/blender/blender/pulls/118565

</details>

<details>
<summary>More node Details</summary>

SHA-1: 25c134fd081be52134bfad1f6ae6e05622917b14

* Geometry Nodes: new Axes to Rotation node

This adds a new `Axes to Rotation` node which creates a new rotation.
In many cases, the primary and secondary axis inputs are a normal and
tangent of a mesh or curve. This provides a simpler and more direct way
to create this rotation compared to using two `Align Rotation to Vector` nodes.

This more direct way of computing the rotation also allows us to optimize
the case better.

The node rotates one axis (X, Y or Z) to the given primary axis direction. Then
 it rotates around that primary direction to align the second axis to the given
secondary direction. Ideally, both input axes are orthogonal. However, the node
still creates the "best" rotation when they are not orthogonal. If one or the axes
is zero or both are (close to) parallel, the resulting rotation is unstable. There is
not too much the node can do to make it more stable.

Pull Request: https://projects.blender.org/blender/blender/pulls/104416

</details>

**Comment by ReinerBforartists** [comment]
Align Rotation to Euler already exists. Axes to rotation not.

**Comment by ReinerBforartists** [comment]
Documenting ...

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/fb378efd-cfc6-4176-b42d-05977df20a82)

**Comment by ReinerBforartists** [comment]
Done.
