### ISSUE TITLE
3D View - Object Header - Modifier Sub-menu cleanup

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4254]
![bforartists_JCiDgXXEwo](https://github.com/Bforartists/Bforartists/assets/35357409/0d64a52e-d1d5-4858-947a-3cd0ed04edc6)
For some... reason.. consistency maybe?
They have added modifiers to the 3D View... 

Reasons this is not a good idea
1. Redundant bloat, where you manage modifiers from the Properties editor, so I'd expect to add from there only. Why from viewport?  
2. Modifiers don't use targets like constraints, so the consistency is inconsistent. 

## Tasks
- Remove icons from the sub-menu folders
- Add icons to the copy to selected operator (has a duplicate now.. another task)
- Add icon to clear modifiers operator (3D View exclusive)

<details>
<summary>Details</summary>

SHA-1: e63c8bb3c29b962f52b2ed0e688779a21b1fab26

* UI: Add Modifiers submenu to 3D view header

Add a menu similar to the "Object > Constraints" menu that allows adding,
copying, and clearing modifiers. The "copy all modifiers to selected" and
"clear modifiers" operators are new, to mirror the functionality we already
have for constraints.

The "Add" menu is the same that's used in the property editor. In the 3D
view, modifiers are always added to all selected objects.

Part of #120230

Pull Request: https://projects.blender.org/blender/blender/pulls/121286

</details>

<details>
<summary>More Details</summary>

SHA-1: a3627fe88e6555e7dd56a3249e436f7f76203900

* UI: Tweaks to Object > Modifier menu

- Moved Modifier menu above Constraints, so that order matches Properties panel
- Added icons for Modifier and Constraints menu (same ones as Properties)
- Renamed "Add" to "Add Modifier", so that it's easier to search for it with F3
- Renamed "Copy Modifiers" operator to match similar operator in constraints menu
- "Add Modifier" operator now doesn't appear if active object type doesn't support
  modifiers. I completely removed it because otherwise it was showing menu with
  empty items even on greyed out

Lastly, I added check for legacy GPENCIL object type, because it doesn't support
new modifier menus, and instead when active object is grease pencil instead of
menu it shows old Add Modifier operator, same one that is in properties panel.

After legacy grease pencil is removed that check won't be necessary anymore and
can be removed, but for now it's needed, otherwise it shows empty menu for grease pencil.

Pull Request: https://projects.blender.org/blender/blender/pulls/121344

</details>

**Comment by Draise14** [comment]
If we do keep the Add Modifier, then in that case it should be the floating menu for consistency (like the property shelf) and these could be also added to the Utility Shelf

![image](https://github.com/Bforartists/Bforartists/assets/35357409/0a7103fa-b4aa-448b-b5c5-7ac104a0435d)

**Comment by ReinerBforartists** [comment]
No, it's a double. The modifiers are added from the modifers tab. Let's remove it.

>For some... reason.. consistency maybe?

Don't aks for reasons, it's Blender :D

**Comment by ReinerBforartists** [comment]
Hmm, but the clear object modifiers is nice ...

**Comment by ReinerBforartists** [comment]
Mockup:

![mockup](https://github.com/Bforartists/Bforartists/assets/13919702/aa446e5b-9a83-48ef-a982-32934c7c6e4d)

**Comment by ReinerBforartists** [comment]
Related 3D View - Object Header - Double "Copy Modifiers" and "Copy Modifiers to Selected" #4255

**Comment by ReinerBforartists** [comment]
Closing this as a duplicate since the other issue is more clear in what to do already.
