### ISSUE TITLE
3D View - Object Header - missing icons in modifiers menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4255]
![bforartists_619DCgr0M7](https://github.com/Bforartists/Bforartists/assets/35357409/d1bd0036-822c-4a05-9630-65f00b2a94fe)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f6a6a8cd-1c8f-4801-8f53-adc20f603594)

We got a double operator that does the same thing. I like the exposure of copying modifiers in the modifier menu..... but one should go. 

The link menu could do without a "copy" entry, since linking modifiers doesn't actually link, but copy. 

<details>
<summary>Details</summary>

SHA-1: e63c8bb3c29b962f52b2ed0e688779a21b1fab26

* UI: Add Modifiers submenu to 3D view header

Add a menu similar to the "Object > Constraints" menu that allows adding,
copying, and clearing modifiers. The "copy all modifiers to selected" and
"clear modifiers" operators are new, to mirror the functionality we already
have for constraints.

The "Add" menu is the same that's used in the property editor. In the 3D
view, modifiers are always added to all selected objects.

Part of #120230

Pull Request: https://projects.blender.org/blender/blender/pulls/121286

</details>

**Comment by Draise14** [comment]
Postponed for after 4.2 release

**Comment by ReinerBforartists** [comment]
It is no double. It's two different operators.

bpy.ops.object.make_links_data(type='MODIFIERS')
bpy.ops.object.modifiers_copy_to_selected()

And i would say even the category fits. The one is data related, the other modifier related. Two different purposes.

So i will just fix the icons here.

**Comment by ReinerBforartists** [comment]
![missing](https://github.com/user-attachments/assets/6fa7fe73-00df-4444-8976-96698e00af54)

**Comment by ReinerBforartists** [comment]
I have used the pastedown icon by purpose here. It copies the modifiers, then pastes it down to the selected objects.
Documenting.
![fixed](https://github.com/user-attachments/assets/01f8e7f1-b4e2-4475-b796-59efea603c83)
