### ISSUE TITLE
Properties Editor - Camera - Depth of Field Eyedropper update from Blender

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4257]
## Blender
![image](https://github.com/Bforartists/Bforartists/assets/35357409/62553a94-15f8-4ae7-89b4-28e4ea732c03)

Blender finally added the camera eye dropper, a bit more elegant than our one, but we probably should update. 

Here is the code in `properties_data_camera.py`
``` py
        row.operator(
            "ui.eyedropper_depth",
            icon='EYEDROPPER',
            text="").prop_data_path = "scene.camera.data.dof.focus_distance"
```

<details>
<summary>Details</summary>

SHA-1: e8d028b7a50b0897bb9db3db2e1b11d6f1952ec9

* Fix #121338: Depthdropper ensure viewport camera

Depthdropper should ensure that the viewport is in camera view to use
active camera position, otherwise it should still use rv3d->viewinv[3]
to ensure correct distance result.

Pull Request: https://projects.blender.org/blender/blender/pulls/121339

</details>

<details>
<summary>More Details</summary>

UI: Add eyedropper button to camera focus distance

Blender already had the ability to sample the depth with an eyedropper
and fill the focus distance (see `"ui.eyedropper_depth"`). But this feature
was fairly hidden. You had to hover over the `focal_distance` property
in the camera data panel and then press `E` (then sample a distance
in the 3D viewport).

This patch adds a `prop_data_path` property to the `ui.eyedropper_depth`
operator to allow specifying the property that should be filled with the
depth value.

The idea for this is taken from `wm.radial_control`, which also uses this
approach to write to a property. This allows us to add the eyedropper
as a button.

Pull Request: [#121486](https://projects.blender.org/blender/blender/pulls/121486)

</details>

**Comment by ReinerBforartists** [comment]
Once again it is not clear what you want to do here. The eyedropper with exactly this code already exists. Is this now a double, and long fixed? Or do you mean something different? What is the task here?

![eyedropper](https://github.com/Bforartists/Bforartists/assets/13919702/a212b2b2-09e8-4357-a875-6d2e76d8ddc9)

**Comment by Draise14** [comment]
Ah, previously we had our own code to make this feature discoverable, atleast to show the tooltip. It must have been lost with a merge. 

I'll close, looks like you can now use it without hotkey only operations.

**Comment by ReinerBforartists** [comment]
Okay, thank you :)
