### ISSUE TITLE
Asset Shelf - Add thumbnail quick size toggles for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4258]
## Current
![image](https://github.com/Bforartists/Bforartists/assets/35357409/af5b56c7-e2bf-4775-bf97-54520f93dc8e)

## Suggested
![image](https://github.com/Bforartists/Bforartists/assets/35357409/9d9b3957-865d-4a4c-9ad2-07fc9b15a093)

Make the quick toggles to set asset shelf thumbnail size standards into the overlay settings of the asset shelf.

Remember.. this is only relevant in the Pose Mode of an armature when you have created a pose as an asset atm. 

This overlay panel also needs to be documented. 

<details>
<summary>Details</summary>

SHA-1: 05b125f399ced4cf8f60c069bcf1acdfe3447f43

* Asset Shelf: Add default preview size option

Allow changing the size of previews in a new asset shelf
when registering a new asset shelf type.

Pull Request: https://projects.blender.org/blender/blender/pulls/121358

</details>

**Comment by Draise14** [comment]
Postponed for after 4.2 release

**Comment by Blenux** [comment]
Done in #4689
