### ISSUE TITLE
Asset Shelf - Armature Pose Asset - Context Menu has missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4260]
## Current
![image](https://github.com/Bforartists/Bforartists/assets/35357409/59aad310-e35c-43ba-9fa9-aaa4448a5cc5)

## File Browser
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c4f0e3e4-c00e-42e5-bcf1-11152fc57081)

Right now there are two entries without icons, but the icons exist. 

<details>
<summary>Potential Details?</summary>

SHA-1: 798219225dab98c7a0908e730c9119d0f1e802a3

* Asset Shelf: Add optional operator to activate assets

The operator stored when registering the asset shelf will be called
with properties that reference the asset (a weak reference, split into
three properties already used in other asset-related operators). The
operator is called whenever a grid view item is activated, and is
meant to do things like import and activate a brush asset.

Previously Reviewed: https://projects.blender.org/blender/blender/pulls/117861

Pull Request: https://projects.blender.org/blender/blender/pulls/121402

</details>

**Comment by ReinerBforartists** [comment]
This menu comes from an addon.

Tough one. We had decided not to maintain addons. But this seems to be core functionality.

While searching for this i stumbled across that we have the pose library addon in both , the addons folder, and the addons_core folder. I guess one is redundant?

**Comment by ReinerBforartists** [comment]
Making a task ...

![double](https://github.com/Bforartists/Bforartists/assets/13919702/a0dccd43-0ffc-4b23-85f2-c95d31e7b77a)

**Comment by ReinerBforartists** [comment]
Related: Double addon set pose library #4292

The related issue should be fixed first ...

**Comment by Draise14** [comment]
Hmm... I will try migrate the legacy addons to extensions with our changes and see if I can get them to "ship" as a user default.

**Comment by Draise14** [comment]
Migrated, now can be fixed. This is now a core addon.

**Comment by Draise14** [comment]
Checking if it needs documentation

**Comment by Draise14** [comment]
Default addon, so documented it a bit better.
