### ISSUE TITLE
Geometry Nodes - Input - Constant - New Rotation node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4261]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/3b6de86a-f8d7-4cc9-b37e-6133ff57957a)

New rotation node, you know the drill. 

<details>
<summary>Details</summary>

SHA-1: 968b98be560f847d1cf6d797df477bf5329e8493

* Geometry Nodes: new Input Rotation node

This adds a new node input node for a constant rotation.
Similar nodes exist for vector, integer, boolean, etc. already.

Pull Request: https://projects.blender.org/blender/blender/pulls/120345

</details>

**Comment by ReinerBforartists** [comment]
Documenting ...

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/115f7c1c-e136-4a52-9f38-5ac64141dd59)

**Comment by ReinerBforartists** [comment]
Fixed
