### ISSUE TITLE
Sequencer - Text Strip - Box Shadow and Outline needs some love

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4262]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/fea78f85-c44f-4d5f-b170-b908b6d32cbf)

New text shadow and line feature has been added, but the interface is a mess. 

## Tasks
- Make hidden content collapse under check boxes with indicators
- Make checkboxes float right
- Document new feature

<details>
<summary>Details</summary>

SHA-1: d66598c16f47b84cbe89524004639442686ad119

* VSE: Text shadow blur / outline

Text strips in VSE got:
- Configurable shadow angle and offset (previously shadow location relative to
  text was fixed). Currently the shadow position is rounded to integer pixel
  locations; sub-pixel positioning might come later.
- Optional shadow blur amount.
- Optional outline, with color and outline width controls. Outline is
  implemented using jump flooding algorithm.

Images and more detail in pull request.

Pull Request: https://projects.blender.org/blender/blender/pulls/121478

</details>

**Comment by ReinerBforartists** [comment]
Long fixed. Closing as duplicate.

![longfixed](https://github.com/Bforartists/Bforartists/assets/13919702/91208977-58ee-4c76-be31-33cac38ea22e)
