### ISSUE TITLE
EEVEE (next) - Shader Editor - World Mode - Convert to Volume operator is hidden 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4264]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/47f942ff-a142-4252-8199-a74d72cfce4e)

Hidden operator is hidden... and property is also hidden to toggle if a volume is infinite or clipped. This is so bizzare, they added an operator that is not exposed in the GUI if at all.. dependant on a property, also not exposed to the GUI. 

# Task
- Add the hidden operator to the properties editor somewhere with a button, potentially in the volume related panel. 
- Then document

SHA-1: f01e84e3a551346d9418f28189277ee82f029d09

<details>
<summary>Details</summary>

* EEVEE-Next: Add operator to convert a world volume to mesh

EEVEE-Next world volume are infinite like Cycles. EEVEE-Classic world volumes
end at the clip_end of the camera/viewport. This can lead to confusion as
it would render different then expected.

This PR adds an operator to convert a world volume into a mesh volume. The
operator can be found in the shader editor (world mode) and in the properties
panel/World/Volume.

**Why an operator?**

As this alters the content of the scene we want the artist to be in control of
the conversion. Doing it automatic lead to a lot of complexity and cases that
might not be expected by the user.

Pull Request: https://projects.blender.org/blender/blender/pulls/119734

</details>

**Comment by ReinerBforartists** [comment]
Now we know that this operator is hidden. But what is the task here?

**Comment by Draise14** [comment]
Added info for the task. Looks like I may need to be more explicit instead of assume the obvious.

**Comment by ReinerBforartists** [comment]
Oh yeah. That would be nice :)

For me some things are not this obvious anymore. I don't use BFA regularly.

**Comment by ReinerBforartists** [comment]
I cannot find this operator. Can it be that you have turned on one of the experimental features? This would explain why it isn't in any menu yet ...

**Comment by ReinerBforartists** [comment]
Okay, found it. You need to be in the world submode with a shader. And then the menu finder lists the operator. So this would be the place to add this operator. Just not sure where to add this.

**Comment by ReinerBforartists** [comment]
Let's add it to the volume panel

![volumepanel](https://github.com/user-attachments/assets/eaeaca6c-a812-4772-89fc-4d0222fedc84)

**Comment by ReinerBforartists** [comment]
Okay, this code already exists. But what is the condition to show it? Principled volume node seems not enough.

![convertexists](https://github.com/user-attachments/assets/ec9bac1d-bb7e-41d7-a617-c067c826a53a)

**Comment by ReinerBforartists** [comment]
Same in Blender. Let's ask at Blender Developers.

**Comment by ReinerBforartists** [comment]
Made it a bug report

https://projects.blender.org/blender/blender/issues/127642

**Comment by ReinerBforartists** [comment]
It seems that the operator is hidden by design. It shows up when you load an older scene that was made with Eevee legacy. But let's wait for confirmation, mabye we get a change here.

**Comment by ReinerBforartists** [comment]
Turns more and more out this "hidden" operator exists by design, and just for Eevee legacy. It is not meant to be used with Eevee next. And in Blender the operator and menu search is hidden by default. Means you are not able to reach this operator in vanilla Blender at all.

They currently think about removing the operator completely. I just wait for the decision. But i don't think that after the decision there is something left to do for us, no matter what the decision is.

**Comment by ReinerBforartists** [comment]
Blender has closed the issue, and so do we.
