### ISSUE TITLE
Theme - Sub-panels inconsistent, make consistent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4265]
## Current
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8caa323d-fa63-4dcd-a028-d9f017288064)

## Targetted
![bforartists_V5mS2yjO1Q](https://github.com/Bforartists/Bforartists/assets/35357409/0c5b82a8-76d7-4633-ab90-56e87bde449a)

The new sub-panels system, with the wrong icon too, also is the wrong colour. Should be updated. I am not sure where or when this was set, so will require digging.

**Comment by Blenux** [comment]
The View3D one is a panel class (Transform) parented to another panel class (Options), which is the way Blender would normally do this, 

However, with the Geometry Nodes one, it used the newer appending to an existing class without the need for another class (like how the Transform Panel is its own class parented to the Options class mention above).

Problem with this is the Usage (Header) part isn't theme-able (uses the existing panels colour), just the contents is, not sure if this can be added though, 

good news is can change the icon, has show in pictures below.

![image](https://github.com/Bforartists/Bforartists/assets/25260650/63ffdf53-3820-4793-88df-bbb52333c2f8)
![image](https://github.com/Bforartists/Bforartists/assets/25260650/e00a7e73-0737-4c92-a75a-de5704e74313)

**Comment by ReinerBforartists** [comment]
Didn't we decide already that the color is fine as it is? I remember we discussed it. Everything is good readable, and so we should leave it alone.
