### ISSUE TITLE
General Properties Context Menu - New Copy Driver to Selected

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4267]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5d3f39e3-4fd6-43c3-b1b6-df59ce5c3837)

Copy Driver to Selected is new, and Copy All Drivers to Selected- But something may be broken since they are greyed out. It might have something to do with how they work with Copy to Selected? 

<details>
<summary>Details</summary>

Anim: implement "Copy Driver to Selected" operator

This allows the user to copy the driver(s) of a property to other selected items (e.g. objects, nodes, etc.) via the right-click menu.  The implementation is based on the "Copy to Selected" operator, and generally behaves the same except for copying drivers instead of values.

Resolves [#120518](https://projects.blender.org/blender/blender/issues/120518)

</details>

**Comment by ReinerBforartists** [comment]
Well, obviously you need to have two objects selected ^^

![copy](https://github.com/Bforartists/Bforartists/assets/13919702/15c5a9a8-5226-4e5c-bdf3-0a0739fcff8c)

**Comment by ReinerBforartists** [comment]
Added icons. Trying to fix the docs now. Context menus is glibbery stuff ...

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/cf9c589b-6553-4a59-b07e-d2c14b6ea425)

**Comment by ReinerBforartists** [comment]
Manual updated. Chapter 6 ...
