### ISSUE TITLE
3D View - Sculpt - Sculpt header - Move Polyline Hide to Legacy (and add icon and document)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4269]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6e86a35b-0f96-4ee6-9149-359548c4c512)

Another act-once operator added as legacy... 

<details>
<summary>Details</summary>

Sculpt: Polyline hide operator

This PR adds a polyline hide operator for sculpt mode as well as the
necessary generic callback code to allow using this gesture in other
selection tools.

Added features include:
* *Polyline Hide* operator
* `WM_gesture_polyline_*` callback functions for other operators
* Status bar text while using the polyline modal
* Common *Gesture Polyline* keymap for usage with the modal

Unlike the *Box Hide* and *Lasso Hide* operators, the *Polyline Hide*
operator does not provide a simple shortcut to click and show all
hidden elements in a mesh. This is because the existing operators
operate on a click-drag action while the new operator is invoked by
just a click.

Design Task: [#119353](https://projects.blender.org/blender/blender/issues/119353)

Pull Request: [#119483](https://projects.blender.org/blender/blender/pulls/119483)

</details>

**Comment by ReinerBforartists** [comment]
Is already in Legacy, but misses the icons

![sculptmenu](https://github.com/Bforartists/Bforartists/assets/13919702/8d71fba4-3a19-4834-b411-8025b43b486b)

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/d2fa232d-c576-430b-9442-406742d028c4)

**Comment by ReinerBforartists** [comment]
Done
