### ISSUE TITLE
Extensions - Add a "Bforartists" sub-filter for legacy addons and change filters to "tabs" like old Addons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4273]
![bforartists_2IpKGAXXwl](https://github.com/Bforartists/Bforartists/assets/35357409/2ed13a9c-fdae-4ece-9cd7-7b49b8872608)

Our convenient little category filter for Bforartists addons is no-longer listed or works in Extensions. We should add it there or find a way to work the titles of the addons to show (instead of say "Core" only)

This one might be more for you @Blenux 

Could work with these tabbed filters on another row. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/09020029-dc1e-498f-951a-adeeb2eaf5f0)

**Comment by Blenux** [comment]
Will check it out today

**Comment by Blenux** [comment]
Something like this or?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/6457146a-4996-4e54-b3fb-4f41289d856c)

**Comment by Draise14** [comment]
Yeah, that is looking much more familiar. Nicely done. Old icons on buttons and we're good to go.

**Comment by Draise14** [comment]
Filters are back baby!

<details>
<summary>Details</summary>

SHA-1: 4a117f3116f5ff1e4612a4f2587df7b156955bae

* Extensions: add popover to filter by tags

Since the categories from add-ons are no longer shown all extensions
are shown together. Support filtering by tags as an alternative.

</details>

**Comment by Draise14** [comment]
Now the filters would be only on the Addons tab.

**Comment by Draise14** [comment]
Fixed by Blender
