### ISSUE TITLE
Extensions - Make filters drop use labels and indents, float left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4274]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e5ed24a7-ba9a-4310-b7cd-60c6b751fe04)

Indent and float checkboxes left under titles per our standards.

**Comment by Blenux** [comment]
This?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/d4d98575-76d6-4406-966b-4c02888d2681)

**Comment by Blenux** [comment]
or this?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/557b648e-5f34-4352-8ace-0a88367f93d9)

**Comment by ReinerBforartists** [comment]
First one, but indent :)
