### ISSUE TITLE
Addons - Add new row of operators to bring common operators to top level, like legacy Addons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4275]
## Former
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0a260a1e-79c4-4fd2-b73f-20a8118f939b)

## New
![image](https://github.com/Bforartists/Bforartists/assets/35357409/dafc504e-6c2b-4b01-8b64-f50fd78fc61b)

The previous version was familiar and tested, with some tabs for quick filters and buttons on a top level for hassle free workflows. 

Let's make it consistent with the legacy addons by exposing these bottons to a new row at a top level with two rows.

**Comment by Blenux** [comment]
Been trying to see what the best layout without it being to crowded.

**Comment by Draise14** [comment]
It's gonna need two rows eitherway. I would rather consistency with the former (also two rows) and top level convenience of common operators than compact.

**Comment by Blenux** [comment]
How is this?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/8884c026-d7c3-4781-890b-80bc143221d2)

**Comment by Draise14** [comment]
Now I'm wanting this bit of code.. *drools*

**Comment by Draise14** [comment]
Addons tab is back, so make it like the old version, was easier to use.

**Comment by Draise14** [comment]
https://github.com/user-attachments/assets/6e52a33f-bda3-4a4a-8b75-89ad970d8ef4
