### ISSUE TITLE
Addons - Expose the "Uninstall" button to a top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4276]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e9760b31-021b-4dee-8d53-97b90712b2dc)

As the description, to uninstall something you gotta open it up, then move down, then uninstall... blergh. 

Install, uninstall.... top level, same UX. Keep it simple stupid.

**Comment by Blenux** [comment]
https://github.com/Bforartists/Bforartists/assets/25260650/496799a2-af8d-4c7a-87cb-fd9c26ae234b

**Comment by Draise14** [comment]
Absolutely beautiful.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/852c6bf6-2b47-4789-af01-367b6c359ddd)

Needs to also be applied to legacy addons.

**Comment by Blenux** [comment]
Yeah notice that, will do today when can.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e9760b31-021b-4dee-8d53-97b90712b2dc)

Got a regression, and now it's nested again.
