### ISSUE TITLE
Extensions - Add icons to install and uninstall buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4277]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4e27e780-6a6b-4aac-bd04-2e268ecc7bef)

Add icons to the install and uninstall icons.

**Comment by Blenux** [comment]
Add Icon for Install?
![image](https://github.com/Bforartists/Bforartists/assets/25260650/89b24207-7b09-43af-950c-7a0a4e7255e7)

Delete for Uninstall?
![image](https://github.com/Bforartists/Bforartists/assets/25260650/2ebe090e-2017-45a2-8f81-5ce1b2208d0c)

**Comment by Blenux** [comment]
done
