### ISSUE TITLE
Extensions - Upgrade Bforartists default addons to be "Extensions" to future proof them

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4278]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0ef1cebe-f893-4d41-bc1c-e89a4533e1ba)

Our addons now need to be future proofed to follow the extensions format, so if they pull the "legacy" system, our core addons won't dissappear when they finally phase out legacy addons. This is mostly done by including a "manifest" file. 

Obviously will need some experimentation..

## Documentation:
https://docs.blender.org/manual/en/dev/extensions/getting_started.html

**Comment by ReinerBforartists** [comment]
Sheesh, this is getting worse and worse. And why distinguish between an addon and an extension when the only difference is the zip format, which gets unzipped then anyways. Sometimes i don't understand them ...

Mh, some of our addons are fundamental. Maybe we should make some of them core code then? Is no good idea to turn off the toolbar for example.

**Comment by Draise14** [comment]
The toolbar addon is to store user settings. The rest is already core code.

**Comment by Draise14** [comment]
Since core addons don't get updated, are included.. they are not needing a manifest. Closing as invalid.
