### ISSUE TITLE
Extensions - Add a visual indicator to what is an "Addon" and what is a "Theme" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4279]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0c9e70dc-72a9-4203-a66f-ee0d3cbf79f3)

You can use filters... but ehm.. they aren't pinned to top so if you're in a massive list (and growing) and you don't want to loose position to apply a filter, you will need to ehm... guess if an addon is an addon or a theme. Adding a visual indicator based on the manifest type to show an icon would be useful. 

_I am guessing this would need to be done when polling the repositories....... damn, this is a whole new level of complexity._ 

# Task
- Find a way to show icons based on the manifest extension type.
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ecc9ad1c-3857-4669-a7f0-d0be120e252c)

**Comment by Draise14** [comment]
I think the `bl_extension_ui.py` file has most of the methods, might be easy...?

**Comment by Blenux** [comment]
How about this?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/daa85ecc-e55a-414a-a3d3-bc62cf2e1d27)

**Comment by Draise14** [comment]
Effing perfect!!!
