### ISSUE TITLE
Extension - Rename the "Install from disk" to "Install Extension"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4285]
![bforartists_Lz9EjO75iT](https://github.com/Bforartists/Bforartists/assets/35357409/197927b9-01f0-4fd8-9f14-b0f7fe1e2d68)

Right now users on twitter, discord and such have found trouble finding the right install method - not sure how it works. So to not "assume" a user knows what they are installing from disk, let's make it explicit in the label. "Install Extension" and clarify the tooltip.  This also now raises the question, do you also install themes from here? 

Now we also have two install methods for themes... Blender......

**Comment by ReinerBforartists** [comment]
What a mess -.-
