### ISSUE TITLE
Preferences, Extensions, Install menu - improve tooltip for Install Extension

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4289]
We all know that the Blender developers are not so good at writing tooltips. This tooltip here is such a case, which can be dramatically improved.

Typoe in the image. I mean from the web, not in the web. This menu item installs a local extension anyways. So Install a local extension may fit. But i am not happy with this term. Still thinking about what we should write here. Maybe from disk?

For the "extension or addon" part, i am not so sure. I don't look through yet how they distinguish between an addon and a extension. The one is a python file, and the other a python file? Sheesh. But "extension addon" sounds definitely wrong. It is a double double. For me the term extension alone would be enough. The menu item is called install extension ...

![improvetooltip](https://github.com/Bforartists/Bforartists/assets/13919702/fc3481a1-c2cd-4dc6-9615-69ee0b5ced68)

**Comment by Blenux** [comment]
My bad that was my doing, what would be the best tooltip?

**Comment by Blenux** [comment]
How about,

Install a Local Extension, into a Local Repository?

**Comment by ReinerBforartists** [comment]
No harm done. I am happy to sharpen your senses to this kind of issues :)

_Install an addon or extension from disk_ 

would imo be enough for me. Short, pregnant and on spot. That's what the user does and needs to know. Maybe we can explain the local repository part in a second line then. But it installs into a local repository anyways. The user has no big choice here. 

But let's hear what the others say :)

**Comment by Draise14** [comment]
Extensions are add-ons AND themes....and in the future even more feautures... 

More lines with more info is gonna be important. Many users on discord and xwitter are confused as hell, so be as explicit as possible with what's new.

**Comment by ReinerBforartists** [comment]
I am confused by local storage ^^ What about local drive?

"Install an extension, addon or theme from local drive"

>Extensions are add-ons AND themes

sadcat.gif

Why kill a working system so badly? -.-

**Comment by Draise14** [comment]
Sure, local drive works. Hard drive, USB drive

I dunno... I think it's to try consolidate a fractured addon community.

**Comment by ReinerBforartists** [comment]
Fixed in master
