### ISSUE TITLE
Double addon set pose library

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4292]
The pose library addon exists in the addons folder, and in the addons_core folder too.

![double](https://github.com/Bforartists/Bforartists/assets/13919702/424a40f0-c6b6-40aa-8927-da38f25fe0f8)

**Comment by ReinerBforartists** [comment]
Hmm, in Blender it's the same

**Comment by ReinerBforartists** [comment]
But not in the actual builder version. This baffles me. Seems to be something bigger.

**Comment by ReinerBforartists** [comment]
I don't get it. The updated Blender repo still contains the addons and addons_contrib folder. The repo from scratch has just the addons_core folder left.

What step do i miss here?

![whichone](https://github.com/Bforartists/Bforartists/assets/13919702/f0059f9c-667c-4db3-a488-9443ae360f84)

**Comment by ReinerBforartists** [comment]
I'm lost. Unassigning

**Comment by ReinerBforartists** [comment]
I have asked it at Blender developers now. Let's see ...

**Comment by Draise14** [comment]
From what I know, addons_contrib and addons is... Nuked. Only addons_core is left. So clear out the repo if possible.

**Comment by ReinerBforartists** [comment]
Okay, the addons_contrib and addons folders are really gone. So we should remove it from our repository too. 

I was told that you can simply delete these folders in the Blender repo since they are sub modules. I will test this tomorrow ...

**Comment by Draise14** [comment]
No longer an issue, legacy addons have been removed and are no-longer included.
