### ISSUE TITLE
Geometry Nodes - Tool Mode - Geometry - Read - New "Active Element" node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4295]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/564ab080-12dc-4c84-b6e9-8e6aad9e7ea7)

<details>
<summary>Details</summary>
SHA-1: 2fe92c63d3565e9b7c0da91317d3e47d0ebcbc72

* Geometry Nodes: Add Active Element tool node

This pull request adds an "Active Element" node that exposes the active
vertex, edge, or face index to the geometry node tool context. The
presence of an active element is available as a boolean.

This node enables the creation of "active-to-selected" style operators.

Co-authored-by: Hans Goudey <hans@blender.org>
Pull Request: https://projects.blender.org/blender/blender/pulls/121333

</details>

**Comment by ReinerBforartists** [comment]
Nice trap. Menu entries appears when in Tool mode ...

**Comment by ReinerBforartists** [comment]
Documenting

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/53508bdf-3323-47e9-bf41-129959a9e56b)

**Comment by ReinerBforartists** [comment]
Done
