### ISSUE TITLE
Linux build failing

### ISSUE THREAD

**Issue by esnosy** [Bforartists/Bforartists#4301]
![image](https://github.com/Bforartists/Bforartists/assets/25552173/d29df308-0810-4cc2-85ee-52c55aa3c9bb)

**Comment by Draise14** [comment]
Ah, do you think this was from one my my merges?

**Comment by esnosy** [comment]
> Ah, do you think this was from one my my merges?

it was me when I renamed blender-thumbnailer

**Comment by esnosy** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/25552173/e8fa7f33-0e22-4d75-a543-46fe1328c998)
