### ISSUE TITLE
rna_nodetree.cc icon enumeration, make order of enumeration the same as in NOD_static_types.h

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4302]
The order of our icon cases list should fit to the order of the NOD_static_types files. But it is once more out of order so to speak. Hard to find something when the order is not equal. And can lead to wrong entries. I am somehow lost where to add my new entry now.

![listorder](https://github.com/Bforartists/Bforartists/assets/13919702/5ef10965-cfe5-48ae-8117-5ee643d3e490)

**Comment by ReinerBforartists** [comment]
Hm, just realized that we miss a complete menu where we haven't added icons yet. Maybe that's these entries ...

**Comment by ReinerBforartists** [comment]
Related: https://github.com/Bforartists/Bforartists/issues/4232

**Comment by Blenux** [comment]
Still need this done?

**Comment by ReinerBforartists** [comment]
Always :D

But i guess we first need to add the missing nodes :)
