### ISSUE TITLE
Extensions - Refresh Addons (for legacy) needs to be exposed to GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4304]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/665301de-82d5-40a0-b0ed-694792f6e986)

Previously you could refresh the list to see which addons are in the addons folder. Not anymore. Legacy will be around a while, so we should still keep that legacy operator till they phase out the API. As you know.. that could be years. 

` bpy.ops.preferences.addon_refresh()`

**Comment by Blenux** [comment]
It's technically still there, just very buried under this,

![image](https://github.com/Bforartists/Bforartists/assets/25260650/97bb6f6c-0ecc-45ce-8cf9-2c5bc3bccfaf)

which adds all this in red, green is the refresh for all on file-system (another wording on top of others used lol)

![image](https://github.com/Bforartists/Bforartists/assets/25260650/41c62c60-8ce3-4b21-b8fd-5103e96cfdf2)

**Comment by Draise14** [comment]
They added it back to not be experimental. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5564709b-6686-4590-9abc-de80b7515989)

I added an icon. Now to document. 

<details>
<summary>Details</summary>

![image](https://github.com/Bforartists/Bforartists/assets/35357409/958fe309-4945-4e14-98db-a93b918c31b3)


</details>

**Comment by ReinerBforartists** [comment]
The structure has once more changed. The whole extensions, addons and themes tabs is completely different now. And we have dozens of tasks around the extensions open. So let's close this one. It will be documented once the other tasks are resolved.
