### ISSUE TITLE
Extensions - Add icon to "Update" button on extensions

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4306]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5a7e1bfe-1dbc-439b-81a6-7b58982c4c2a)

Add an icon to the update button.

_This is going to be a massive chapter for documentation eventually..._

**Comment by Blenux** [comment]
Would a refresh icon be ok for this?

**Comment by ReinerBforartists** [comment]
Refresh is better. Info tells the people that there is something to look at. Which isn't. It is updating. But we could create a green version of the refresh icon ...

**Comment by Draise14** [comment]
I am ok with white refresh, since the download white arrow is also white. White for the action. 

Green I think I would be confused with.. go.

**Comment by Blenux** [comment]
White Refresh - 1
Green Refresh - 1

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c530e060-fb91-47fa-a7e2-9a2042207a09)

Ah, when there is update, there also is an uninstall bellow.

**Comment by Draise14** [comment]
Should I run a poll in the server or call it?

**Comment by Draise14** [comment]
Changes were unfortunately reverted from last minute changes from Blender.... 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/32f04758-bb12-4456-852c-3af10d9260a0)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/99ce1e4e-6a1f-4a22-8584-dc8f4d657cce)
