### ISSUE TITLE
Paint Modes - Expose Color Picker to a top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4308]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/88a506ea-9a25-47f0-9492-b38ae96dfbf3)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/8b8d85a7-15c3-46cb-8354-e5cc5e0558be)

Right now the colour picker is inconsistent in the paint modes. It would be nice if this were an operator in the GUI in a top level set in a consistent way, not only for the color wheel - but to assist in using it without needing to be moused over the color swatch selector or color selector sub-panel.

**Comment by ReinerBforartists** [comment]
Is already at the top level for the primary color. In the brush menu. And is best done by hotkey. The color pickers from the single colors can be found in the color wheels then. It makes no sense to put them besides the colors too. We would have a inflation of color picker buttons then. With a 50% chance to click the wrong one.

I vote to close this task.
