### ISSUE TITLE
Properties Editor - Modifiers - New column for "Normals" needs fixes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4314]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/8d97754c-da50-4df1-badb-668a08c170c0)

Blender decided to add the Smooth by angle nodegroup to "show" under a new category "Normals", but we are all in the top level kind of way. So the merge kind botched this a bit, forgot to double check, so will need to rectify. 

<details>
<summary>Details</summary>
SHA-1: b0eb48c4dccbb11409b832cf2ab15596ed9dd5c0

* UI: Move Normal Edit and Weighted Normal modifiers to "Normals" menu

Though the whole modifier menu could use a reorganization, it probably doesn't
make sense to do that before we have a builtin library of node group assets.
We already have the "Normals" category though, so these two modifiers make
more sense there.

Pull Request: https://projects.blender.org/blender/blender/pulls/122168

</details>

**Comment by ReinerBforartists** [comment]
New column would be cleaner ...

**Comment by Draise14** [comment]
Will do. Might make it the far left..?

**Comment by ReinerBforartists** [comment]
Sounds good. 

A further reason why i think a new column would be better is that we have more normal functionality. And i expect it to appear here too in the future.

**Comment by Draise14** [comment]
![bforartists_ai4CWgZPId](https://github.com/Bforartists/Bforartists/assets/35357409/1d927aaa-6c19-4aeb-bada-0940b6abd957)

**Comment by Draise14** [comment]
Documenting
