### ISSUE TITLE
Properties - World/Lights - Settings - Shadow - Float Jitter Left, hidden disabled content

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4317]
![bforartists_z4gwIvCw5I](https://github.com/Bforartists/Bforartists/assets/35357409/7cc68e1b-2ad4-4afd-9d57-1614992a45a5)
Float the new "jitter" properte left and collapse slider to hidden. Document new feature. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/9decdbc2-4f62-417d-8516-df8913db8d92)

Also should be done to Light Shadow options

<details>
<summary>Details</summary>
SHA-1: b96b87a75c782e6a179b41e689b480adcd9bca32

* EEVEE-Next: World: Add shadow options

This adds jitter option and filter option.

EEVEE_WORLD_PT_sun_shadow

</details>

**Comment by ReinerBforartists** [comment]
Documenting
![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/b7a58ca5-5452-4105-a55e-bab8c3a761c2)

**Comment by ReinerBforartists** [comment]
Chapter is completely outdated. Needs a rewrite. I'll make it a task in the manual tracker.

**Comment by ReinerBforartists** [comment]
Manual fixed.
