### ISSUE TITLE
Top Toolbar - Add new "Image Mesh Plane" with new icon, remove legacy addon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4318]
![bforartists_XBiYRdrRb7](https://github.com/Bforartists/Bforartists/assets/35357409/b1196ba8-234e-409f-8cc3-1ddf00e389f0)
New "Image to Planes" operator to replace the addon. We could remove that from the legacy addons. This also needs to be added to the images group (which has a bug to fix). 

A new icon could be nice, like the image null icon, but with a little mesh data icon maybe in the corner. 

Documentation important. 

While at it, fix the missing operators for images too. 
![WindowsTerminal_08M3gMPLPt](https://github.com/Bforartists/Bforartists/assets/35357409/f31c341e-0177-4a23-8b76-23a682e7257b)

<details>
<summary>Details</summary>

SHA-1: 4b4ae728377f0c0d6645dcc8fa62a961dba0496c

* Import Images as Planes: improve option panels

- Layout changes
  - Use panels instead of boxes resulting in a more compact UI,
    more suitable to the drag-and-drop UI.
  - Make all enum options to drop-down menus.
  - Rename the title of `Position` box to `Transform`.
  - Remove sub-headers `Plane dimensions`,
    `Orientation` under Transform box.
  - Move offset related options to the bottom. Importing a single
    plane would be more common use case.
- Rename "Animate Image Sequences" to "Detect Image Sequences".
- Rename several labels and option names. Since drop-down allows more
  space, make some option names verbose.
- Remove the warning `'Opaque' does not support alpha`. It should be
  obvious from usual Blender usage, and doesn't need a special warning
  from the add-on.
- Disable Alpha Mode options instead of hiding it when use alpha is
  unchecked.
- Hide Track Camera option instead of disabling it when supported
  align modes are selected.
- Fix or rewrite several tool-tips.

Original PR by Sun Kim: blender/blender-addons!104936

Ref: !122345

Co-authored-by: Sun Kim <perplexing.sun@gmail.com>

</details>

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/8cde3f07-2b80-4bcb-bfac-381f641ad7e1)
