### ISSUE TITLE
3D View - Camera View - Header - Overlays - New "sh

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4319]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f40dc170-8d95-451d-9e6b-55d43f614453)
![CameraGuides](https://github.com/Bforartists/Bforartists/assets/35357409/f8145612-1b14-4bad-a2b7-ba644d0cc252)

Needs to be added, got missed in this merge. My bad. Documentation also needed. 

https://projects.blender.org/blender/blender/commit/bd3c55444781708fdc6b50ecb2fde0f9e087480c

```py
        if view.region_3d.view_perspective == 'CAMERA':
            sub.prop(overlay, "show_camera_guides", text="Camera Guides")
```

<details>
<summary>Details</summary>
SHA-1: 392ac52ebb74cbd62857045930dca035f1a3971d

* UI: Toggle Camera Guides in Viewport Overlays

Allow toggling camera composition guides in the 3DView Overlay popover.

Pull Request: https://projects.blender.org/blender/blender/pulls/121923

</details>

**Comment by ReinerBforartists** [comment]
Checking the docs ...

**Comment by ReinerBforartists** [comment]
Already documented. Closing.
