### ISSUE TITLE
Properties Editor - EEVEE-next - Sampling Panel - Shadow subpanel - Volume Shadows float left and hide content

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4320]
![bforartists_K3Lc5npPMR](https://github.com/Bforartists/Bforartists/assets/35357409/6886e5a4-2ba4-497e-b40d-ddd98fb78be5)

Float left, collapse slider.

**Comment by ReinerBforartists** [comment]
Damned, overlooked. Is now this task: https://github.com/Bforartists/Bforartists/issues/4421

Closing as duplicate.
