### ISSUE TITLE
3D View - Curves object - Edit Mode - Control Points - New Extrude and Move curves operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4321]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d5e3fce5-c224-40f1-875c-adc791f8794f)

New operator, could use an existing extrude icon... 

<details>
<summary>Details</summary>
SHA-1: afec41e8d3882ec69d760e6e179526571850a537

* Curves: add extrude operator to menu

</details>

**Comment by ReinerBforartists** [comment]
Documenting

![controlpoints](https://github.com/Bforartists/Bforartists/assets/13919702/b2996c86-f920-4167-bd8b-6fd6aadf9c19)

**Comment by ReinerBforartists** [comment]
Ah, this is with the hair curves object. Vital information ! Different menu ...

**Comment by ReinerBforartists** [comment]
Fixed
