### ISSUE TITLE
Geometry Nodes - Instances - New Transform Instances node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4322]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f45a4ea7-8659-4e49-9396-d456b8a49b6f)

You know the drill... icon, toolshelf, documentation.

<details>
<summary>Details</summary>

SHA-1: 905aaf439c8bf32be51c3f00735fc87aef346c6c

* Geometry Nodes: new  Set Instance Transform node

This node allows replacing the transformation of every instance by providing a matrix.

Before, this was only possible by using the Store Named Attribute node. It's more common
in Blender to have specialized built-in nodes for built-in attributes (e.g. Set Position, and Set ID).

Pull Request: https://projects.blender.org/blender/blender/pulls/121473

</details>

**Comment by ReinerBforartists** [comment]
Documenting
![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/3f3793f3-3c41-4107-81a7-7bed7993c7a9)

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
Interesting one. The icon gots created. But is not longer in the sheet. Seems that we had a merge conflict at one point, which killed the instance transform icon in the blender_icons.svg file then ...

**Comment by ReinerBforartists** [comment]
Let's add it back.

![notlongerthere1](https://github.com/Bforartists/Bforartists/assets/13919702/82ff46f9-936d-4bec-8e77-7a5bfb437bb9)

![ionstance](https://github.com/Bforartists/Bforartists/assets/13919702/ffd67d24-9434-4a9f-ba58-7fdadc37e140)

**Comment by ReinerBforartists** [comment]
And it's back.
