### ISSUE TITLE
Node Editors - Add SHIFT+CTLR+LMB to connect to preview node to header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4323]
![bforartists_t5YMns8nGX](https://github.com/Bforartists/Bforartists/assets/35357409/b993955e-3462-436d-9924-83a2b9962e61)

In geometry nodes, you can now CTRL+SHIFT+LMB to connect to a preview node. You can also technically do this in the shader nodes too. This was from the node wrangler, but now native. 

## Tasks
- Add the CTRL+SHIFT+LMB to the shader editor hotkeys
- Expose the preview linking operator to the GUI for discoverability, the Node menu in the header can do. 

<details>
<summary>Details</summary>

SHA-1: 61178b22a213e5e9d457fc20db87e03c11c9e468

* Nodes: port "Connect to Output" operator from Node Wrangler

As Node Wrangler add-on is moving to extensions platform and maybe isn't shipped
with Blender from 4.2 onwards, some of it's more important functionalities which are
crucial for Blender UX can be ported inside core. Also see #121749.

This PR ports "Preview Node" operator from add-on inside `scripts/startup/bl_operators`.

When Shift-Ctrl (or Shift-Alt) clicked on the node operator connects output socket of the
node to active Output node in the tree (group, material, light, or world output). For Geometry
Nodes this is just handy operator, but in Shader Nodes, because Viewer Node isn't
implemented, this has always been the only way to quickly preview nodes by connecting
it to Material Output.

Changes made from Node Wrangler version:
- Renamed operator from "Preview Node" to "**Connect to Output**", because node previews
  already mean a different thing in context of compositor and shader editor, and viewer node
  is used for previewing in geometry nodes. Connect to Output is correct name because in every
  context it's called that's what it does.
- Assigned shortcut Shift-Alt-Click in shader editor as well. Even though Shift-Ctrl click already
  works, it's good to have consistency with geometry nodes, so that users can use same shortcut
  in both contexts.

Operator doesn't work in compositor. It's not clear if that's wanted (to connect to Composite node),
and if it is it'll be added in separate PR.

Original authors of the add-on: Bartek Skorupa, Greg Zaal, Sebastian Koenig, Christian Brinkmann, Florian Meyer

Pull Request: https://projects.blender.org/blender/blender/pulls/122016

</details>

**Comment by ReinerBforartists** [comment]
Do we have a menu item here? I am no friend of adding a native hotkey to that. Else we might want to add native hotkeys to all other 500 nodes.

**Comment by ReinerBforartists** [comment]
Just don't forget the goal to have as few hotkeys as possible ^^

**Comment by Draise14** [comment]
Yep.

**Comment by Draise14** [comment]
Found the issue, hidden operator is added, double hotkey system, but it's necessary for Node Wrangler to work. 
![image](https://github.com/user-attachments/assets/7b4cffa4-cc8c-42f3-8689-d14644808149)

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Done
