### ISSUE TITLE
3D View - Overlays - Material mode is really Viewport Color mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4324]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1f13caed-2e42-4f5c-bb39-5a214f50a8b2)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ae4d4f06-210b-4d39-981e-065b4564af87)

A user in discord pointed out that the Material mode in shaded (workbench mode) is disconnect from the viewport colors. The material mode only shows the viewport colors of the material, not the actual material. 

We should update the tooltip and also maybe the label.

**Comment by ReinerBforartists** [comment]
Has Blender the same labeling mistake?

**Comment by Draise14** [comment]
Yes, Blender has the same.

**Comment by ReinerBforartists** [comment]
Tough one. Blender migrators might be in trouble with this other name here then.

**Comment by Draise14** [comment]
Maybe a tooltip update could do. Even if label is preserved, it would still be disconnect but the location and UX of the button remains the same. If the label changes, it would be more connected, tooltip improved.. and the UX remains the same for Blender heads. 

We target outside of Blender at the end of the day.

**Comment by ReinerBforartists** [comment]
What is the task now here? Relabel or change tooltip?

**Comment by ReinerBforartists** [comment]
Let's update the tooltip

**Comment by ReinerBforartists** [comment]
Hmm, now that i know how it currently works i don't think that this is done with a tooltip hint. I have reported it. Maybe they change the behaviour. But i don't have high hopes. Let's nevertheless wait a few moments what the outcome is before we continue here.

https://projects.blender.org/blender/blender/issues/130111

**Comment by ReinerBforartists** [comment]
Let's have a look to update the manual to make clear that Workbench does not use material colors at all.

![mat](https://github.com/user-attachments/assets/b6a7596a-35fd-4aed-a204-898bb06e6584)

**Comment by ReinerBforartists** [comment]
And fixed.
