### ISSUE TITLE
Proerpties Editor - Grease Pencil Object - Modifier - Duplicate to Selected needs an icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4331]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f8a25c59-8b08-420b-b4b8-f189fa7fe792)

In a grease pencil modifier stack, there is a missing icon in the Copy to Selected operator.

**Comment by ReinerBforartists** [comment]
Forgot to ask. Is this documented?

**Comment by ReinerBforartists** [comment]
Documents still fits.

But i knew there was something disturbing me. This task here was a regression. We have now the Apply button double. It was already removed at one point. I'll make a new task for it.
