### ISSUE TITLE
Node Editors - CTRL+DBL-LMB renames socket should be mentioned in a tooltip

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4335]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a0ba58c3-65b0-4ca1-a702-95c741bfa415)

You can now hold down CTLR then LMB click on a socket label to rename it. It is completely undiscoverable, so we should include this in a tooltip somewhere.... maybe on these socket types, or from the side panel label or something. 

And documented! 

<details>
<summary>Details</summary>

SHA-1: cd5eb4aa03ee93279d16d4f36ca09a2fc7717dff

* Geometry Nodes: support renaming some sockets in the node directly

This adds support for renaming some sockets in the node UI directly by Ctrl+Clicking
on them. This is sometimes more convenient than going to the sidebar. It affects the
Menu Switch and Bake node as well as the Simulation and Repeat zone.

Some related notes:
* The Group Input and Group Output node are not yet supported, because it currently
  breaks the right-alignment on the Group Input node. I couldn't find a workaround for
  this yet.
* Double-clicking on the socket name does not trigger renaming yet. This seems to
  be a deeper issue in the interface code.
* The highlighting when hovering over sockets that can be renamed is very dim
  making it hard to see. Alternatives like drawing a box around the label when hovering
  it (like in list views) have been discussed but seem to be much more difficult to get to work.

Despite these limitations, it seems reasonable to add this already, as it shouldn't affect
anyone negatively. The nodes still look like before.

Co-authored-by: Hans Goudey <hans@blender.org>
Pull Request: https://projects.blender.org/blender/blender/pulls/121945

</details>

**Comment by ReinerBforartists** [comment]
You cannot rename every socket name. Just some special ones. Let me dig for this tooltip ...

![suported](https://github.com/Bforartists/Bforartists/assets/13919702/c16f9165-5122-4791-80a0-1e34dd65d31b)

**Comment by ReinerBforartists** [comment]
Let's have a look if we can document this somewhere too

![fdixed](https://github.com/Bforartists/Bforartists/assets/13919702/df707146-8ce3-4274-bc09-5ab1fad9ada8)

**Comment by ReinerBforartists** [comment]
Fixed. It is mentioned in the first geometry nodes chapter as a general behaviour.

**Comment by Draise14** [comment]
"Hold CTRL and click on the label to rename"

Keep nomeclature the same as the sidepanel and use correct preposition.

**Comment by ReinerBforartists** [comment]
Fixed
