### ISSUE TITLE
Properties Editor - Pin to Last needs to be "unified" and exposed to top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4338]
![336502372-b4bdaa1b-13b0-480e-9636-97d96baf675b](https://github.com/Bforartists/Bforartists/assets/35357409/7d110827-2f54-4022-a31f-7efc3906a9f5)

Right now there is a way to pin, then two ways to unpin. There is one visual method, which is great, but you can't pin from a top level.

This is a bizzare workflow. (also, check box UX for something common shouldn't be a thing. Pinning is done in the header from a top level. Keep it consistent)

## Task
1. Move the Pin to Last to the top level
2. Make the icon change from pin to pinned state when doing so.

**Comment by Blenux** [comment]
Where should be the pin toggle?

https://github.com/Bforartists/Bforartists/assets/25260650/aaf541e1-c457-42ce-9ea8-fd5a418d865d

**Comment by Draise14** [comment]
Yeah, this is exactly how I envisioned it. Except, inverse the icons. Not pinned is on the side. Pinned is flat on.

**Comment by Blenux** [comment]
easy fixed, is the placement of it good?

**Comment by Draise14** [comment]
Yeah! Fine by me. Commit and let's go. Love it.

**Comment by Draise14** [comment]
Documented, but I am starting to see the header gettin gcrowded, maybe group into the 3 visibility one, then the 4 side ones. Instead of in it's own column. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/97184b17-5459-4243-bd20-eb304adedccd)

**Comment by Blenux** [comment]
Will try to get to this today.
