### ISSUE TITLE
Properties Editor - Armature - Bone - Per bone Shpae Custom Wire Width float left and move label out

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4339]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5f3c1039-edfe-41b6-aa7f-4dc5e84e4a5c)

Right now you can now define a custom shape wire width per bon, which is hella nice - buuuuut the GUI needs some love.

## Task
- Move the label out of the slider
- Float both below and make it collapsable when disabled.

<details>
<summary>Details</summary>

SHA-1: f9ea64b0baede1af60e33c2f5af23b373fcaad07

* Anim: Per bone wire width for custom shapes

The setting adds the "Custom Shape Wire Width"
option to the "Viewport Display/Custom Shape" section of a pose bone.
As the setting says, this controls how thick the wire is drawn in the viewport.

This is done by adding a geometry shader that makes two triangles out of a line.

The Anti-Aliasing is controlled by the setting
Viewport->Quality->Smooth Wires->Overlay in the user preferences.

## Artifacts
When increasing the line width, the lines start to separate at their vertices.
This comes from extruding each edge along the normal of its direction.
This could be solved by adding round caps in a later PR.

Pull Request: https://projects.blender.org/blender/blender/pulls/120176

</details>

**Comment by ReinerBforartists** [comment]
Documenting

[fixed](https://github.com/Bforartists/Bforartists/assets/13919702/459ae767-f2d5-4c25-b4fa-732d6fe2a23d)

**Comment by ReinerBforartists** [comment]
Fixed
