### ISSUE TITLE
Icon - New INTERNET_OFFLINE icon needed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4340]
![bforartists_ScwJFszU7I](https://github.com/Bforartists/Bforartists/assets/35357409/a0964616-0f53-409e-a84b-04f20a0432e7)

New icon needed. INTERNET_OFFLINE

I have inserted WIP comments for this icon in the merge to get them replaced with the new icon. 

<details>
<summary>Details</summary>

SHA-1: 35a3e64141518760d79df269c8403c4eb124ec70

* UI: Icons: INTERNET_OFFLINE

* INTERNET_OFFLINE icon was discussed here: !122225

Ref: !122486

</details>

**Comment by ReinerBforartists** [comment]
I will also shape a internet online icon while at it if you don't mind. Let's have a look at which point the Blender devs sees the need for it ...

**Comment by ReinerBforartists** [comment]
May i ask where you have added the delete icon here?

**Comment by ReinerBforartists** [comment]
Ah, found it. source\blender\editors\interface\templates\interface_templates.cc, line 6499

**Comment by Draise14** [comment]
Searching the repo for INTERNET_OFFLINE you'll find the instances where the icon should be added.

**Comment by ReinerBforartists** [comment]
This feature is buggy. I had the icon showing once. Then i allowed the internet access. And now i cannot make it showing again. Not with factory settings, not with removing the appdata folder.

Either way, the icon is there.

**Comment by ReinerBforartists** [comment]
Ah, found it. Show extensions updates is off by default. But why did it show then before? ^^

Either way, documenting.

![off](https://github.com/Bforartists/Bforartists/assets/13919702/de3fff11-2839-4778-a733-833f4dcba40b)

**Comment by ReinerBforartists** [comment]
Done
