### ISSUE TITLE
Geometry Nodes - Instances - New Instance Transform attribute input node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4342]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f2c8d3d4-de77-4aa4-bf92-a20ae2a3b52c)

Similar to #4322 but not. New node. This is a "Get" node. 

<details>
<summary>Details</summary>

SHA-1: fb6b9092a7e19378effa3930526cb38d9b87b189

* Geometry Nodes: new Instance Transform attribute input node

New node to access `instance_transform` built-in attribute of instances.

Pull Request: https://projects.blender.org/blender/blender/pulls/122477

</details>

**Comment by ReinerBforartists** [comment]
Was to expect ^^

Sheesh, why don't they simply insert a switch between get and set. Would save half of the nodes here ...

**Comment by Draise14** [comment]
Ah damn, that was my bad. I tried merging the icon sheet from head, but did it the wrong way and copied in an older version.

Still... ironing out merge kinks...

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4e1e7afc-b1b5-4268-84fa-1ac946ec46c1)

Documenting.
