### ISSUE TITLE
Addons - Install legacy and extension from local is the same operator now, expose to top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4343]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e124532d-526f-4f43-898f-5a6263c257dd)
This is now the one and the same operator, it detects if it is an extension or legacy and installs accordingly with the same operator.. which made our tooltip get lost and rename. So we should adopt the tooltip here and also see if we can expose this button to a top level for a similar workflow to former addons. 

<details>
<summary>Details</summary>

SHA-1: d568abea628bdcf3796985199da073fad928e285

* Extensions: Install From Disk operator handling both legacy and new

When a user has downloaded an add-on as a zip file, it's not clear in
advance if this is a legacy add-on or a new extension. So they would
have to use trial and error, or inspect the zip file contents.

This uses a simple heuristic to check if the file is a legacy add-on,
and if so automatically calls the legacy operator instead.

The operator now show both extension and legacy add-on properties,
with the latter in a default collapsed subpanel.

Pull Request: https://projects.blender.org/blender/blender/pulls/121926

</details>

**Comment by ReinerBforartists** [comment]
I would wait a bit here. There is change in this area ...

**Comment by Draise14** [comment]
Gah.. they really are shifting sands around here in the Blender Foundation.
Related duplicate task, simpler and more up to date. #4430
