### ISSUE TITLE
3D View - Sculpt Mode - Sculpt - Remove doubles

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4346]
![bforartists_WrZScAI8l6](https://github.com/Bforartists/Bforartists/assets/35357409/81b16d5c-9a5b-4064-bf36-074ac5974507)

My bad, merge pulled their re-organization, though we have had it all ok. I thought I rejected that, but apparently not.

**Comment by ReinerBforartists** [comment]
Killer :D

**Comment by Draise14** [comment]
Caused by this:

<details>
<summary>Details</summary>

SHA-1: 1fe8fbd93acbfe5fe7e669d2470723f9e24049e4

* UI: Reorganize mesh sculpt mode menus

Reorganization of the mesh Sculpt mode menu for simplicity and consistency.

Changes include:

- Moved transform operators into its own menu, consistent with other modes.
- Group Box, Lasso, Line, and Polyline Show/Hide operators
- Box, Lasso, Line, and Polyline Trim/Add operators moved to a new "Trim/Add"
- Cleanup and simplification of labels

Detailed explanation and example images in the pull request.

Pull Request: https://projects.blender.org/blender/blender/pulls/122437



</details>

Remind me to revert to head, then manually splice in new changes after comparing and finding the relevant commits. Auto-merge is not good here...

**Comment by Draise14** [comment]
Fixed by #4250
