### ISSUE TITLE
3D View - Sidebar - Fix merge regressions in View tab, View panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4347]
![image](https://github.com/Bforartists/Manual/assets/35357409/229cfa3a-0fc5-4ee0-82f0-091f11fc2b58)

When in the camera view, we need to add some love.

## Task
- Float View Lock - Lock checkboxes left
- Use Local Camera has a new "Passpartout" toggle, float left. 

<details>
<summary>Details</summary>

SHA-1: 10071caea8e8779b260d353d0d43b49ffbdaa50a

* UI: Show Passepartout When All Overlays Off

Bring back old behavior where passepartout is shown when all overlays
are disabled. Move the passepartout option to the sidebar.

Pull Request: https://projects.blender.org/blender/blender/pulls/122577

</details>

**Comment by ReinerBforartists** [comment]
Looks like a regression.

**Comment by ReinerBforartists** [comment]
And could you please make proper descriptions. This here is again not obvious. The "love" could also mean to completely remove these features. And the issue title says something completely different.

And please just one task per issue if possible :)

Turning off the prop in the defaults is one task. This is what you want in the issue title.
Align left the camera to view is one task.
To get the passepartout prop below the camera prop is one task.
The double menu entries camera to view and lock to 3d cursor is one task. 

Something is defintely weirdly off here, as told, i smell a heavy merge regression. So first i would compare it with an older version of BFA, then with Blender ...

**Comment by ReinerBforartists** [comment]
This is how Blender looks like here. 

![blender](https://github.com/Bforartists/Bforartists/assets/13919702/9c320106-8796-4242-8898-06b0cf8ca1f8)

And we have these problems since minimum 4.1.0 ...

![regression](https://github.com/Bforartists/Bforartists/assets/13919702/60f87040-291e-44b2-b52d-d82bde82a6ea)

**Comment by ReinerBforartists** [comment]
Also note how the Passepartout checkbox remains greyed out ...

**Comment by ReinerBforartists** [comment]
I have renamed the task ...

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/db28ca08-4c34-4c42-81bb-b5d62a625422)

Documenting.
