### ISSUE TITLE
Geometry Nodes - Capture Attribute has missing domains

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4349]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/de557ea3-dde6-4585-98cb-ca6915b4277e)
Got this.. not sure if from merge. Blender today is fine. Might need to repair with another merge. 

```
Python line lookup failed, interpreter inactive
uiItemR: property not found: GeometryNodeCaptureAttribute.domain
```

**Comment by Draise14** [comment]
I'll do a test merge morrow morning again, see if that fixes it, comparing documents with this referenced seems clean...

**Comment by ReinerBforartists** [comment]
Nice :)

**Comment by Draise14** [comment]
Will postpone after knocking down the tracker a bit.

**Comment by Draise14** [comment]
Ok, gonna start doing the merge to see if it was a bad issue from Blender.

**Comment by Draise14** [comment]
Merge didn't fix it, so will compare documents now.. something is weird.

**Comment by Draise14** [comment]
Ah.. it was in the NOD_static_types.hh file.
