### ISSUE TITLE
Unexpected commits in lib/windows64 and release/datafiles/assets

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4352]
Just a headsup. And that this commit is documented. 

I have two unexpected changes here without changing anything at the source. I have made a git fetch and a git pull, but these two changes are still there at my unchanged repo. So i'll commit them.

**Comment by ReinerBforartists** [comment]
Fixed.

**Comment by ReinerBforartists** [comment]
I have the problem again. Something is odd here. It is marked as rewind. Does somebody have an idea what this could be?

Not good when we reset our made changes by this.

![unexpectedcommit](https://github.com/Bforartists/Bforartists/assets/13919702/1d4e0a24-40fb-4cf8-ab7b-33389363717f)

**Comment by ReinerBforartists** [comment]
Hmm, this change appears when i do any change at the blender_icons.svg

**Comment by ReinerBforartists** [comment]
Whatever broke, i hope i have fixed it, i have marked these changes now as unchanged.

**Comment by Draise14** [comment]
I saw this yesterday, thought it was me and didn't commit these changes.
