### ISSUE TITLE
Node Editor - Add menu - Instances - Inconsistent icon for instance transform

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4359]
The base icon for get Instance transform differs from the Set Instance transform. It uses the base icon from Translate Instances. But should use the base for transform.

![trouble](https://github.com/Bforartists/Bforartists/assets/13919702/123386c8-5ba6-482f-9863-3baf1cbe2d5e)

**Comment by ReinerBforartists** [comment]
I took the opportunity to fix the missing name for Set Instance transform in the icon sheet.

**Comment by ReinerBforartists** [comment]
Updating docs

![fixed](https://github.com/Bforartists/Bforartists/assets/13919702/d4f1803e-cf8e-4ce5-92f0-080ed5b9e9bf)

**Comment by ReinerBforartists** [comment]
Why is the node not documented? Documentation is part of the issue.

**Comment by ReinerBforartists** [comment]
Ah, you named it instance translation ^^

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by Draise14** [comment]
Ah, got confused with transform and translate. My bad. Thanks for the fix.

**Comment by ReinerBforartists** [comment]
Four eyes are always better than two :)
