### ISSUE TITLE
Im and export menus - missing icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4362]
I guess it is known, but i cannot find a task for it. We miss the icons from a few im- and export extensions now.

![missingicons](https://github.com/Bforartists/Bforartists/assets/13919702/fbac8f8a-db59-400c-9583-2003a0802b90)

**Comment by Blenux** [comment]
Seems this got removed when the extensions platform came in.

![image](https://github.com/Bforartists/Bforartists/assets/25260650/c7bf084e-2193-40a2-927d-a481fab54b69)
