### ISSUE TITLE
Multiple Addons with the same name error

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4363]
I have actviated the Blender addon repository for another task. And now i get a warning about Multiple Addons with the same name. Plus messages about manifest problems.

I am still biased if we are at the right track with our new addon management ...

![trouble](https://github.com/Bforartists/Bforartists/assets/13919702/3f366415-da92-45b6-810d-64d1b24bcd03)

**Comment by Draise14** [comment]
Still working the legacy to extensions operator that will migrate user settings. But theory is working. Node Wrangler needs to be cleaned.

The errors here is a manifest list to dictionary issue fromBlender. 

I'll reference the other two tasks to clean this issue and close after breakfast. 

Extensions UX is still wip. Don't judge yet!

**Comment by Draise14** [comment]
#4345
#4325
