### ISSUE TITLE
General  - When creating a "new" item, it duplicates. Update icon and tooltip to reflect.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4367]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0b8c3ffe-fc8e-4ab1-a39d-b336a93bd636)

1. When you make a new geometry nodes, material, text object, brush or material from the properties editor, 3D sidebar or node editors, when the selector is empty, you get a plus icon. Good.
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6d83df91-96a2-40ab-8904-fbe8f84b323f)
2. Now if you have an item in the selector selected, and hit the plus icon again, it will **DUPLICATE** but the icon remains the same, ADD
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8cfe413f-e39c-4271-880f-1f150f999198)

# Task
- Make the second plus icon in the selectors become conditional to show "duplicate" icon instead and update the tooltip. 

## Relevant GUI's that would need the update
- Brushes panels (Sculpt, Texture Paint, Weight Paint, Vertex Paint + Grease Pencil Draw, Sculpt, Vertex Paint, Weight Paint)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/71955c4b-ad71-4274-a4b7-ab89f9a1d974)

- Text Editor
![image](https://github.com/Bforartists/Bforartists/assets/35357409/77f34980-08e7-4b60-8d8b-da549af823ed)

- Materials (Material Editor and Properties Editor
![image](https://github.com/Bforartists/Bforartists/assets/35357409/98a3ee8b-0567-4798-a972-423db49481a5)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/ecf09005-e2fe-40d1-a8ab-8c6e22e4e611)

- Geometry Nodes (Geometry Nodes Editor)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/3f13ff10-d313-479f-b9bc-e7af201893cb)
- Dope Sheet - Action Editor mode
![image](https://github.com/Bforartists/Bforartists/assets/35357409/eb96f3f0-6ae5-495b-a495-3295e8d1ee66)
 
The only place it doesn't do this as an expected UX is in the image editor. 
![bforartists_bxTOthiCXo](https://github.com/Bforartists/Bforartists/assets/35357409/b34b4b19-0fa1-4db5-8de4-046488186c2d)
 the add image button.

**Comment by ReinerBforartists** [comment]
And i think i will leave the icon alone. It is still the same purpose since many years. A new icon would just lead to confusion.

**Comment by ReinerBforartists** [comment]
![duplicate](https://github.com/user-attachments/assets/140c0459-3847-4026-abc8-0f8d7676107d)

**Comment by ReinerBforartists** [comment]
Text is not valid. It creates a new text file, and does not copy stuff over.

Brushes is not longer valid. The prop has changed.

![brushes](https://github.com/user-attachments/assets/0c06a003-301a-4547-b248-8153068f231b)

**Comment by ReinerBforartists** [comment]
New material

![newmat](https://github.com/user-attachments/assets/4e992abf-36f3-4515-863b-e0dd6f2be0d7)

**Comment by ReinerBforartists** [comment]
Texture
![newtexture](https://github.com/user-attachments/assets/ff3f6bc9-9fd6-406a-95d5-c009bd8565b6)

**Comment by ReinerBforartists** [comment]
Action

And that should be it. Manual update is not necessary, just the tooltips were updated.

![action](https://github.com/user-attachments/assets/7cf32243-4822-49a5-bd54-9674eaea1690)
