### ISSUE TITLE
Preferences, Extensions, double menu entries Check for updates and Install available Updates

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4375]
These two menu items are double entries. They exists in the Repository panel, and they exists in the menu right besides it.

Not sure what to do here. We could completely remove the menu, and place the install from disk button back into the header. Like it was before. Or we could remove the two buttons from the Repository dialog.

Either way, one set has to go ...

![double1](https://github.com/Bforartists/Bforartists/assets/13919702/ab8ba257-6bd5-4144-88a3-6fbed03845e9)

![checkforupdates](https://github.com/Bforartists/Bforartists/assets/13919702/d1a3b036-2afd-40df-b90e-2d37ada6392d)

**Comment by Blenux** [comment]
The ones in the Repository popover only updates the active selected repo (in this case the extensions.blender.org), while the one in the first pic refreshes all repos together.

same with the update, one is for the active and the other is for all.

**Comment by ReinerBforartists** [comment]
Interesting. It is the same operator.

**Comment by Blenux** [comment]
Tad confusing at first,

(Active)
![image](https://github.com/Bforartists/Bforartists/assets/25260650/a85bdbb6-4e1c-4c62-9043-b2bc360dfddb)

(All)
![image](https://github.com/Bforartists/Bforartists/assets/25260650/e8c44a1d-b348-4dae-b6ed-be65da1d9a1b)

**Comment by ReinerBforartists** [comment]
Okay, then let's update the manual instead.

**Comment by ReinerBforartists** [comment]
Done.
