### ISSUE TITLE
Github Actions - Windows build is failing (Clang version 17.0.0 or higher needed)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4379]
![firefox_SMgfMejyd1](https://github.com/Bforartists/Bforartists/assets/35357409/602ba850-f90c-442a-b2cd-162acca6ba9c)

Currently Windows actions on Github is failing, but I think it's an issue with clang. I will log here because.. I have no idea how to fix this. Local builds work fine. 

``` C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.40.33807\include\yvals_core.h(898,1): error G0AE52624: static assertion failed: error STL1000: Unexpected compiler version, expected Clang 17.0.0 or newer. [D:\a\Bforartists\Bforartists\bfa_build_windows_Release_x64_vc17_Release\intern\cycles\kernel\cycles_kernel_oneapi.vcxproj]
  _EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 17.0.0 or newer.");
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.40.33807\include\yvals_core.h:519:44: note: expanded from macro '_EMIT_STL_ERROR'
  #define _EMIT_STL_ERROR(NUMBER, MESSAGE)   static_assert(false, "error " #NUMBER ": " MESSAGE)
                                             ^             ~~~~~```

**Comment by ReinerBforartists** [comment]
Internet tells me that this is a visual studio update problem. Let's wait for next week.

**Comment by Draise14** [comment]
Windows passed this time. Closing.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/60875b33-06c0-424f-b685-1bf0449079ed)

Ah.. now it's OneAPI.

**Comment by ReinerBforartists** [comment]
Still an issue :(

**Comment by Draise14** [comment]
How do you typically fix these things? Is there a way to update the dependencies manually?

**Comment by ReinerBforartists** [comment]
I never had a need to. But yeah, we need to find the exact cause, and then toy around with the workflow ...

**Comment by ReinerBforartists** [comment]
I knew something was tickling me here. We have stopped updating VS because of the reason that i throws a too old error despite being too new. The workflow though pulls the brand new version. And so it throws the error that stops us from updating VS. The bad news is, we can most probably not stop it from doing so. So i am a tad bit lost here what to do.

**Comment by ReinerBforartists** [comment]
Ah wait. Oneapi is the problem. Different issue.

Mh, why do we compile a make release in the windows workflow at all? It was once just a simple make. Remember, the github actions is just to proof that our code compiles.

So the quick fix is most probably to change the workflow from make release to make. Line 27. But you better ask eyad here.

**Comment by ReinerBforartists** [comment]
Okay, this nags me too much. Let's replace the make release by a simple make and have a look if this helps. As told, the workflow is just to show that the code compiles.

**Comment by ReinerBforartists** [comment]
No moaning anymore. Let's close this issue for now.
