### ISSUE TITLE
SVG Importer - Import as Grease Pencil hidden operator (only works with drag and drop)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4380]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/0bea193f-98f1-402b-aa34-fe021b80d3d5)

For some reason you can drag and drop SVG as grease pencil, but the operator to do this.. is not in the GUI. Had no idea you could. Expose to GUI. 

<details>
<summary>Details</summary>

![image](https://github.com/Bforartists/Bforartists/assets/35357409/6a4edda3-d065-40e4-90e7-75a95537b77d)

</details>

**Comment by ReinerBforartists** [comment]
The task is invalid. The operator is in the import settings.

![yesitis](https://github.com/Bforartists/Bforartists/assets/13919702/e1210b65-379a-4e7a-a44d-32579661766f)
