### ISSUE TITLE
Documentation - Node Editors - Overlays - Toggle 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4382]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/01280ce5-6936-45c5-aa6b-c9b3ceb8d90e)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/cfa04522-f8c5-4510-84a2-a3d76a6f4b63)

When you label a reroute, then make another, it will add sub-labels. You can toggle these now. 

<details>
<summary>Details</summary>

SHA-1: db5d41016446467be11174a7e74a9f836fea4826

* Node Editor: add overlay to automatically label reroute nodes

Add an overlay option to automatically display a label on reroute nodes.

This automatic label is propagated through chained reroute nodes and
is based on the explicit label of linked reroute nodes.

The automatic label is dimmed to distinguish it from manually set ones.

Pull Request: https://projects.blender.org/blender/blender/pulls/113368

</details>

**Comment by Blenux** [comment]
What to do with this task?

**Comment by ReinerBforartists** [comment]
Yeah, looks more like a manual task

**Comment by Draise14** [comment]
Ah yeah, sorry bout that. Wrong tracker.
