### ISSUE TITLE
Icon - New TAG icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4383]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f5ed9ff6-a59b-4c8a-ae96-7e8c4177e296)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/aee87fb0-a26f-4d6d-a1a6-6bc8aeefd251)

New tag icon, typically used in the categories filter of the Extensions addon. 

Location: `bl_extension_ui.py line: 1092`

<details>
<summary>Details</summary>

SHA-1: 7b601464c36ec7d6cfe47bd69337077a23e09c3d

* UI: Add new TAG icon

Introduce a new icon: `TAG`. A generic tag/label, to be used anywhere
there are tags.

Details and images in the pull request.

Pull Request: https://projects.blender.org/blender/blender/pulls/122738

</details>

**Comment by Draise14** [comment]
Related:  #4374

**Comment by ReinerBforartists** [comment]
Documenting

![tag](https://github.com/Bforartists/Bforartists/assets/13919702/056a3ffc-9bd5-44cc-80b2-527eb679abc2)

**Comment by ReinerBforartists** [comment]
Done
