### ISSUE TITLE
EEVEE (Next) Move Scene>Light Probes to Render tab

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4384]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2ea6eb3e-5996-403b-91d4-cd460f6f2b4a)

Right now the SCENE_PT_eevee_next_light_probes is displayed in the Scene tab, not the render tab. This is a render setting, not a cene setting. IN EEVEE Legacy, this panel (Indirect Lighting panel) was in the render settings. 

Then document.... this is heavily different to the legacy EEVEE Indirect Panel, but has a similar setting.

**Comment by ReinerBforartists** [comment]
I would rethink this task. Eevee legacy had no light probes panel at all. And setting up light probes is in fact a scene setting.

Maybe you mean the Indirect lighting panel? This one is gone with the new Eevee.

![lefacy](https://github.com/Bforartists/Bforartists/assets/13919702/744ba102-25d0-4291-8eef-fda7a5f30262)

**Comment by Draise14** [comment]
Ah ok, we had another panel name (Indirect Lighting) for it with same functionality. They moved the panel, changed the name, and made it disconnect. 

I personally think looking for render settings in the Scene tab is super obscure. Specially if you need to bake a render setting (light probes) to render... 

The previous panel location made it more discoverable and sense.

**Comment by ReinerBforartists** [comment]
Your decision. I just wanted to raise my concern here. Blender has it in the Scene tab. And moving it to the render tab shows no benefit to me.

**Comment by ReinerBforartists** [comment]
May i raise my concern again that this change would be just for the sake of change, with no benefit and the danger for confusion for blender migrators?

**Comment by Draise14** [comment]
Hmm.. I could argue it's not a scene setting but a render setting as it affects render settings. But if it's.. too fine a line, less work is ok.
