### ISSUE TITLE
EEVEE - Light Probe Object - Properties Editor - Float Viewport Display checkboxes left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4385]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d24994d5-cb6d-4e11-b8d1-f9f79b3180f8)

Will require documentation too.

**Comment by ReinerBforartists** [comment]
Documenting

![documenting](https://github.com/Bforartists/Bforartists/assets/13919702/19d8d2c5-cc1b-455e-bf48-1891f4d52128)

**Comment by ReinerBforartists** [comment]
Done.

https://github.com/Bforartists/Manual/issues/642
