### ISSUE TITLE
Sequencer - Text Object - Style Box is permenantly disabled

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4387]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/178eab7b-8b25-472c-af12-5cfeb4dc661e)
Looks like it's broken, but it is indeed working. Make sure the check box for the Box is activating it's contents.

**Comment by ReinerBforartists** [comment]
I don't see anything greyed out here. So what is the problem?

**Comment by Draise14** [comment]
Updated the splash. Weird. It shows when Shadow box is on.

**Comment by ReinerBforartists** [comment]
Ah we have a little triangle button above. I guess it is still deactivating the props instead of hiding them.

**Comment by Blenux** [comment]
Hows this?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/83e4f0e5-b254-40c6-a1de-71b44c96fbe9)

**Comment by ReinerBforartists** [comment]
Looking good :)

**Comment by Draise14** [comment]
Documentation potentialy needs an update

**Comment by ReinerBforartists** [comment]
Wasn't this already documented in another task? Checking ...

**Comment by ReinerBforartists** [comment]
Yup, here https://github.com/Bforartists/Bforartists/issues/4388

Closing.
