### ISSUE TITLE
Sequencer - Text Object - Style Panel - Float Outline checkbox left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4388]
![bforartists_nhnBdVb9I8](https://github.com/Bforartists/Bforartists/assets/35357409/30cbef6b-ae9a-48b8-a071-1d4ac5a2144a)

Float the Outline checkbox left.

**Comment by Blenux** [comment]
This?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/53f51037-4d98-4b7a-8aac-4a44029fd33b)

**Comment by Blenux** [comment]
Fixed in #4399

**Comment by Draise14** [comment]
Now to documentation

**Comment by ReinerBforartists** [comment]
Documented.
