### ISSUE TITLE
Top Toolbar/File Import - Add addon conditional checks for some of the import/export operators in the GUI code

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4391]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/efffc8ef-e3b9-4f34-9bda-98de082c6584)

Some of the default addons could be turned off or uninstalled by user opt-out now, so we should add an addon check to some of the import and export groups of operators. 

If a user turns one off, they shouldn't get an error and blocked access to any other operator in the group that errors. 

**Import and Export**
- X3D
- STL
- FBX
- GLTF

**Comment by Blenux** [comment]
done, also added svg to the list

**Comment by Draise14** [comment]
Updating documentation. 

At the moment there is a merge conflict.

**Comment by Blenux** [comment]
Merge conflict should be sorted

**Comment by Draise14** [comment]
Documentation mention that these are addons might be good....

**Comment by ReinerBforartists** [comment]
Added a hint in the im and exporters menus. 

Fixed.
