### ISSUE TITLE
File Browser - Sub Panel Header issue

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#4397]
Some old code was making it more compact,

current
![image](https://github.com/Bforartists/Bforartists/assets/25260650/009ff048-08c7-44a1-9f40-6cc25046a47d)

fixed
![image](https://github.com/Bforartists/Bforartists/assets/25260650/cb2fbb57-43df-4dc7-9754-c60208d20ea3)

**Comment by Draise14** [comment]
Big bounty reward for this one. Thank you.
