### ISSUE TITLE
Default Addons - X3D is back to core, meaning pull from Legacy addons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4403]
![bforartists_TXEqKpdpVT](https://github.com/Bforartists/Bforartists/assets/35357409/2c1ad23c-d65d-457e-b2cf-64675254f631)

We get the x3D addon back to Core, meaning we can pull it from our default addons system.

**Comment by ReinerBforartists** [comment]
With core you mean online? Core is offline in addons_core folder ...

**Comment by Draise14** [comment]
Yes, it's offline.

**Comment by ReinerBforartists** [comment]
Now i am as clueless as before XD

I'll leave this task to you :D
