### ISSUE TITLE
Geometry Nodes - Input - Scene - Named Layer Selection

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4404]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/85783c8f-b99c-4417-af87-8557fa9db2ba)

This node is a little obscure, and has a bad title in the name. Probably a merge error. But add icon, clean it up, and document.

**Comment by ReinerBforartists** [comment]
It gets even more obscure. Blender does not have this node. So whatever went wrong here ...

![named](https://github.com/Bforartists/Bforartists/assets/13919702/e54fc4fe-4b59-43e9-ae8c-575ba3369049)
![named2](https://github.com/Bforartists/Bforartists/assets/13919702/4e2ce6fd-923d-49ad-8736-2146eac296bd)

**Comment by ReinerBforartists** [comment]
Does still not show up.

**Comment by ReinerBforartists** [comment]
Okay, newest Blender build shows the node. I meanwhile found the cause of the long title. You have put the tooltip into the title field ^^

**Comment by ReinerBforartists** [comment]
Ah, the semi colon is still there in the Blender code. Reporting.

**Comment by ReinerBforartists** [comment]
Documenting.

**Comment by ReinerBforartists** [comment]
Done
