### ISSUE TITLE
Sequencer - Movie Clip Strip - New Movie Clip panel - Float check boxes left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4405]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/9f5990c5-4870-41ea-b67b-3aebc5bf00ce)

When you create a movie clip strip for the sequencer (created in the Movie Clip Editor) then added to the Sequencer Editor as a Movie Clip, then there is a new panel with "Movie Clip". 

# Task
- Float checkboxes left
- Document

<details>
<summary>Details</summary>
SHA-1: 6079b16d5200a213804b084b083ac44bfdf9eb41

* VSE: Add movie clip panel

This moves move clip related properties to own movie clip panel as it
is done with other strip types that uses other datablocks. The clip
property is added to RNA, so this can be added to the panel.

Requested in #120357

</details>

**Comment by Blenux** [comment]
Manual in progress

**Comment by Blenux** [comment]
Manual Documentation done
