### ISSUE TITLE
Default Theme - Generated Keyframe Type could be improved

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4406]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/dbeee043-a1c9-400a-a0b2-ff9f304d6d13)
New "Generated" keyframe type - needs a theme update. 

This is from the Blender theme. I have't spliced it in, so theme would need to be re-generated. 
```
Userdef_default_theme.c  
    .keytype_generated = RGBA(0x585858ff),
    .keytype_generated_select = RGBA(0xa28962ff),
```

**Comment by ReinerBforartists** [comment]
Changing the theme does not work by changing values in the userdef_default_theme. Your changes did not arrive in the factory defaults. Needs to be done in the theming editor, then regenerated.

**Comment by ReinerBforartists** [comment]
Documenting.

![blendercols](https://github.com/Bforartists/Bforartists/assets/13919702/625447c8-8f07-4666-81f7-41a469182a56)
