### ISSUE TITLE
Default Theme - Sub-Sub Panel theme could be made consistent

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4407]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/44272195-1e1b-43aa-aafd-b4d0d337188d)

Right now the sub-sub panels of the exporters and importers in the File Browser are.. dark.. too dark. Probably inhereted from Blender. So update and make them a bit nicer.

**Comment by ReinerBforartists** [comment]
I find it fine as it is. It separates well, it sticks out well. It is good to read.

**Comment by Draise14** [comment]
Ah ok, yeah it is the same grey as the tab background grey, deep to the back, so I guess it makes sense.
