### ISSUE TITLE
Geometry Nodes - Geometry - Operations - Bake Node - Sidepanel properties - Float Custom Folder checkbox left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4408]
![bforartists_2cWrJ46O9j](https://github.com/Bforartists/Bforartists/assets/35357409/077b01be-c794-41d5-8a5f-668cbd000370)

Float the custom folder checkbox left of the Geomety Nodes bake node. 

Location: Geometry Nodes Editor - Add menu - Geometry - Operations - Bake Node - Sidepanel properties }

A mention of it in the documentation to boot could be nice.

**Comment by ReinerBforartists** [comment]
Documenting ...

**Comment by ReinerBforartists** [comment]
Hm, we don't have this kind of settings documented for each separate node. So let's call it a day here.
