### ISSUE TITLE
Preferences - Extensions - refactor Repository dropdown, Advanced

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4409]
A regression in the prop here. The string box was already left aligned , and went across the whole length. Which was much better to read. Couldn't find the old task so far.

![regrewssiom](https://github.com/Bforartists/Bforartists/assets/13919702/5a91f3f0-8383-4e1a-a0c7-47927f77afae)
![regression2](https://github.com/Bforartists/Bforartists/assets/13919702/febb6ada-be97-4725-a16a-fcef18627c12)

**Comment by ReinerBforartists** [comment]
There is more trouble hiding ...

![trouble](https://github.com/Bforartists/Bforartists/assets/13919702/46f1e4ba-2554-4562-a3f3-5f31f8b19599)

**Comment by Draise14** [comment]
Ergh, probably my bad code comparison in the last merge.

**Comment by ReinerBforartists** [comment]
Yeah, something went wrong :)

The source box is new ...

**Comment by ReinerBforartists** [comment]
No wonder you were in trouble. This part of the code is written in the typical blender manner. Hard to figure what belongs to what.

Documenting.

**Comment by ReinerBforartists** [comment]
Fixed
