### ISSUE TITLE
Properties Editor - Light Probe objects - Viewport Display - Float left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4412]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d2e24daa-e2f3-4c96-aae3-b1d07c54ade5)

Properties Editor - Sphere Light Probe Tab and object - Viewport Display Panel - Float left the checkboxes. Update documentation screen capture. 

While at it, collapse the Size Slider and remove the "Size" from the slider label, and make it a checkbox label per the Bforaritsts standards.

**Comment by ReinerBforartists** [comment]
Duplicate, already fixed.
![DUPLICATE](https://github.com/Bforartists/Bforartists/assets/13919702/ff397b38-0a4f-49b5-941a-e2df0f71320e)
