### ISSUE TITLE
3D View - Sculpt - Mask brushes - Float Active Tool props left (refression)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4414]
![bforartists_nutgTXcfxn](https://github.com/Bforartists/Bforartists/assets/35357409/8abc1aca-5c4f-4c22-aa31-4a692e2176ed)

These for some reason are not floating left anymore, but the Front Faces only and other Sculpt Mask brushes need to be floated left. In documentation it's fine.

**Comment by ReinerBforartists** [comment]
Fixed
