### ISSUE TITLE
blender_sync_main - Icons can only be Monochrome for now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4417]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5e4d86b5-a98c-4e75-86bf-820aef675ccb)

![blender_laWdjjWz1m](https://github.com/Bforartists/Bforartists/assets/35357409/b870945f-17be-4810-8b89-05854344032c)

Right now in the Blender main and sync_blender_main branch, colored icons are not supported yet. SVG icons are supported, but they can only be monochrome right now. 

Basically what the new system does:
1. All icons are now individual SVG files, with the brush files also slated to change.
2. Each SVG is drawn in a cache with the "text" draw system, which can scale responsively.. But only monochrome, so the icons draw in the text draw cache.
3. They haven't developed a colored text system yet, so coloured icons aren't stored in the cache yet.
4. We could have our icons, but all of them would need to be DEF_ICON (monocrhome) instead of DEF_ICON_COLOR - and they would all be monochrome, but it WILL compile and work. 

They are working to add color, Hans was good to work that. 

This is tracked here:
https://projects.blender.org/blender/blender/issues/123585

Coloured icons both in Blender and Bforartists does a hard crash:
[blender.crash.txt](https://github.com/user-attachments/files/16019382/blender.crash.txt)
[bforartists.crash.txt](https://github.com/user-attachments/files/16019383/bforartists.crash.txt)

**Comment by ReinerBforartists** [comment]
The icons are now colored. So this task is fulfilled.
