### ISSUE TITLE
3D View - Grease Pencil Object - Header: Remove double

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4426]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/d8d738c1-ceb9-4424-9772-a29e98f1cd41)

We got some double entries and things should be floated left.

**Comment by ReinerBforartists** [comment]
I have to slightly disagree. These buttons are mode buttons, and belongs to the left. Which is consistent with our design too, and is documented that way in our manual. Blender has it at the left side too.

So let's remove the doubles here.
![left](https://github.com/Bforartists/Bforartists/assets/13919702/6eba5964-3b03-4d9f-8c9c-cd216eccf605)

**Comment by ReinerBforartists** [comment]
Manual is still up to date.
