### ISSUE TITLE
3D View - Grease Pencil Object - Header: Remove the "Guides" label when activated

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4427]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e8bfe393-9ba6-43ce-a12d-51623b0637aa)

We don't show a label when a drop down is activated, and it takes up realestate. Remove the inconsistency and remove the Guides label.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Done

**Comment by ReinerBforartists** [comment]
![guides](https://github.com/Bforartists/Bforartists/assets/13919702/c09e0e7b-be8b-49e3-a316-edb48b4df1d9)
