### ISSUE TITLE
Preferences - Extensions - Move the "Uninstall" to top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4429]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/bd833bbc-b711-44bf-b1b7-7a0c85d010fa)

And make it also conditional so that if it says "update" you can still uninstall from the drop down.

**Comment by Draise14** [comment]
Similar to #4276

**Comment by Blenux** [comment]
Currently trying to do this one, but having issues with the following part,

if system_repo:
                layout.operator("extensions.package_uninstall_system", text="Uninstall", icon='CANCEL') #BFA - icon added
            else:`
 
 The extensions.package_uninstall is easy enough though.

**Comment by Draise14** [comment]
I think I'll keep this as the addon method, traditional (expand to uninstall)
