### ISSUE TITLE
Addons - Move Install and Refesh to a top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4430]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/15406c4b-f9bc-4a37-888b-c6560eeedd27)

These used to be a top level, now they aren't. Looks like they are missing vs the old method... so expose to top with icons. Document. 

Related task:
#4275

**Comment by Blenux** [comment]
How about this also with moving these to the header.

Making the Extensions and Add-ons Headers similar to each other? 

![top level](https://github.com/Bforartists/Bforartists/assets/25260650/59d52264-5f62-46dc-b814-8b1a7f5b78c1)

**Comment by ReinerBforartists** [comment]
Looking good to me
