### ISSUE TITLE
Extensions - Themes - Expose "Set/Clear" to a top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4433]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b0e9333c-e9e1-4532-8a10-e0b8d9549b59)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/16c7d8f0-933a-40ae-9c8a-80ff0854266e)

Right now to activate a theme.. you have to download it. It will activate again. But to toggle it off.. you have to go into a sub menu. Install another, then to toggle between themes.. you have to go into the sub menu and set it. 

# Task
Expose the Set/Clear theme to a top level to the far right, like a check box system to show which is on and off.

**Comment by Blenux** [comment]
Been working on this, close but have one issue to solve.

**Comment by ReinerBforartists** [comment]
Please assign to the issues that you are working at. Avoids double work ...

**Comment by Blenux** [comment]
Sorry for the delay, this look good?, not liking the checkbox icons on an operator button though, looks out of place.

https://github.com/user-attachments/assets/728dd010-8269-4d4a-b79c-b8b6be017db4

**Comment by Draise14** [comment]
Yeah you are right. The Checkbox feels off for a selection operator.  Check box columns are for various properties and at the same time.

A button "Apply" like install. When applied a notice to say it's applied?

**Comment by Blenux** [comment]
I kind of like the default Set and Clear Theme names,  

https://github.com/user-attachments/assets/0ec1758f-caaf-4b75-b65b-6c68a078c89e
