### ISSUE TITLE
Extensions - Change the Theme/Addonto a button row instead of drop down and add icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4434]
![bforartists_0xVag3RxBA](https://github.com/Bforartists/Bforartists/assets/35357409/94cc81af-c690-4ec5-9ed4-ab1075282e0a)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/cb5ff8e1-c6bc-4808-83b1-d9cc2fbf2a74)

Change the 2 entry drop down to button row. Better a "tab switch" than a activation, scroll, select. Activation, scroll, select. 

Also, add some icons to the selection and make the Extension "PLUGIN" icon in the Addon tab the same icon (currently COMMUNITY)

**Comment by Blenux** [comment]
Look good?

https://github.com/Bforartists/Bforartists/assets/25260650/8b84c17c-2637-421e-b7ff-734d0099ac4c

**Comment by ReinerBforartists** [comment]
Looks good to me.
