### ISSUE TITLE
Extensions - Add Addon/Theme icon indicator to listings

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4435]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/e83a05b8-6715-4d02-b9c8-4b3187458f63)

Right now there is little or no connect with the sub-tabs from Extensions to Addons/Themes. It would be nice to know what on earth we are downloading in a visual connected way. 

Add the PLUGIN and COLOR icons respectively per entry after the type filter, and also into the sub-tabs for addons and themes after extensions.

**Comment by Blenux** [comment]
How about icons for all on the side?

![image](https://github.com/Bforartists/Bforartists/assets/25260650/7271a0be-fa17-4eec-8d33-43bb5a22ee78)

**Comment by ReinerBforartists** [comment]
Yeah, would be more consistent. Manual update will kill us though ^^

**Comment by Draise14** [comment]
Yo, that looks actually.. awesome. I would be ok putting in work to the documentation there, Monday though. Go ahead and pull it in, now there is a better visual connect to themes and plugins, and more obvious read of the preferences.

**Comment by ReinerBforartists** [comment]
I think the View icon would fit better to the viewport tab?
![view](https://github.com/Bforartists/Bforartists/assets/13919702/2359cd21-4abe-47cc-bb64-6308061b922a)

**Comment by Blenux** [comment]
How does this look?


https://github.com/Bforartists/Bforartists/assets/25260650/437c5fe9-11fe-41ad-b117-87696a53c9f8

**Comment by ReinerBforartists** [comment]
Looking good to me.
