### ISSUE TITLE
3D View - middle aligned props in the header

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4436]
A regression. We once had the options in the header all right aligned. It was moved to the right to have a cleaner look. But the more i think about it, shall we keep it the Blender way? It adds some separation. And having everything at the right side makes it look cluttered.

![threesections](https://github.com/Bforartists/Bforartists/assets/13919702/bcfa0b67-bdcc-445f-889f-20f5f6b51f71)

**Comment by Blenux** [comment]
Yeah to me, it does look better to leave in the middle, gives it some separation of Object Pivot/Snapping to Viewport Options on the right.

**Comment by Draise14** [comment]
I am partial to full float right, but yes, the far right is getting cluttered and making this harder to hit the large group of icons - the heat maps for hitting certain ops is a little easier if groups, specially with user customizability when exposing more buttons there. 

In general the responsiveness argument of full right still is.. still ok when smaller width with center, as they all collapse into themselves anyway. 

Ehm.. maybe we can revert this change. 

But if so, would it also need to be reverted in the node editors, image editor and other other editors?

**Comment by ReinerBforartists** [comment]
> But if so, would it also need to be reverted in the node editors, image editor and other other editors?

Not necessarily. But in the 3d view the header is a bit crowded. I like the three way better now. And sometimes you have to change your mind. Nothing is ever written in stone. Except one thing, we search for the best possible solution. And here the three way seems to win.

> EDIT: Also, means a big screen capture update for the documentation right?

That's the problem here :D

 But the tools are documented. The layout does not play a big role. So i would udpate the docs when you have them open for another task anyways.

**Comment by Draise14** [comment]
Righteo, let's keep it, and update docs when we stumble on things.
