### ISSUE TITLE
Sequencer - dysfunctional hotkey for Delete Retiming keys operator

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4441]
I have added a hotkey to the Delete Retiming Data operator for this task here. It seemed to work: Sequencer - Expose hidden "Delete Retiming Data" operator to GUI #4227

While writing the manual i stumbled across that it has an override problem with deleting the strip. In Blender it works. The hotkeys doesn't override each other. So we might have a setting for the hotkey wrong.

In case everything else fails we can still assign hotkey X to it. That one works. But i would not be a fan of it.

Note that we first need to merge the upper task #4227 into master. 

![deleteproblem](https://github.com/Bforartists/Bforartists/assets/13919702/62d42390-35f0-41b3-94e5-e34d5844bf37)

**Comment by ReinerBforartists** [comment]
> but one has to be over the retiming track to work,

Yeah. And that's the part that fails currently ^^

**Comment by Draise14** [comment]
Relevant task:

<details>
<summary>Details</summary>

SHA-1: 1a887c06d95a2164c66e9de7c65c0a24ab18a443

* Fix #123543: Delete retiming keys deletes strip

Delete operator was shared for strips and retiming keys, which was not
ideal. Operator logic relied on invoke function setting proper context
which was also hidden from users.

Split these operators and make dedicated operators for removing retiming
keys - `SEQUENCER_OT_retiming_key_delete`.
This operator returns `OPERATOR_CANCELLED | OPERATOR_PASS_THROUGH` if
executed in non-retiming context, or no key is selected.

Pull Request: https://projects.blender.org/blender/blender/pulls/123767

</details>

**Comment by ReinerBforartists** [comment]
I'm still curious what is going on here. Lemme check if we can make the blender hotkey also dysfunctional ^^

**Comment by ReinerBforartists** [comment]
Documenting.
