### ISSUE TITLE
3D View - Grease Pencil Draw Mode - Convert tabbed toolshelf panel errors

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4443]
![explorer_r4z3h36qOG](https://github.com/Bforartists/Bforartists/assets/35357409/c018b753-a2f0-4089-8f43-baa05bd450c1)
![bforartists_Tm8osYrEXK](https://github.com/Bforartists/Bforartists/assets/35357409/275f1da7-5077-4e26-b1fa-86ae80fd91fb)

Right now GP3 has the old convert operators changed, so we should update them. Causes an issue.

**Comment by ReinerBforartists** [comment]
Nothing to document here.
