### ISSUE TITLE
Grease Pencil in draw mode, Guides setting not in Blender

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4454]
We have guides settings in the header when in draw mode. Blender not. I've searched around if it hides elsewhere, but it seems the feature is simply deprecated and gone with grease pencil 3

If that's the case, then we should remove it.

![guides](https://github.com/Bforartists/Bforartists/assets/13919702/a563fa0d-80df-444d-b5cc-666138ec3452)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/3aadf35a-edcc-45b6-81af-ebe4d426cb7c)

Guides still work, they probably have it missing as an oversight.  Maybe we should report this to Blender. 

![bforartists_AwjAWGHTmK](https://github.com/Bforartists/Bforartists/assets/35357409/5b88e58f-8950-4b81-b5d3-ee8148b55ed9)

**Comment by ReinerBforartists** [comment]
> Guides still work, they probably have it missing as an oversight. Maybe we should report this to Blender.

Definitely. We need to make sure that this is not a bug.

**Comment by ReinerBforartists** [comment]
Hmm, interesting. The code is there. But the tool is not displayed in the header. And i have no idea why. It is the same than our code O_O


![blenderfile](https://github.com/Bforartists/Bforartists/assets/13919702/f5340497-65ce-448b-b21f-58f47f3741b2)

**Comment by ReinerBforartists** [comment]
I was not able to find out why the prop does not show in Alpha 4.3. As told, the code is there, it should show. Yet it doesn't.

I have now reported it. Let's have a look.

https://projects.blender.org/blender/blender/issues/124272

**Comment by Draise14** [comment]
Confirmed in Blender. But we ok.. lol

**Comment by ReinerBforartists** [comment]
Mh. The guides are removed by design. Guides are not part of GP3 - yet ...

The issue is closed. So do we.
