### ISSUE TITLE
Toolbar , Primitives, blank icon for add point cloud

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4457]
Icon seems to be there, but shows blank.

![missingicon](https://github.com/Bforartists/Bforartists/assets/13919702/22c067c5-9f6e-4905-9ce9-05b96dbb4658)

**Comment by Blenux** [comment]
This may explain it, technically it's still there, lol

![image](https://github.com/Bforartists/Bforartists/assets/25260650/d0a1152a-ca2f-4b90-87a1-a8fe50eb8fd8)
