### ISSUE TITLE
Shader editor, World mode, Troubled icon for Background

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4460]
The conversion of the icons has some side effects. The Background icon has a regression. Needs a fix.

![missinglines](https://github.com/Bforartists/Bforartists/assets/13919702/c9a71673-68f7-4040-9cb9-0cd487bf44f7)

**Comment by Blenux** [comment]
![backgroundnode](https://github.com/Bforartists/Bforartists/assets/25260650/66129afc-5de3-4376-ad2b-1c4bca8a8056)
