### ISSUE TITLE
Shader Editor , World mode, missing icon for Wave Length node

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4461]
Icon is missing. Not sure if completely missing or a conversion fail.

![missing](https://github.com/Bforartists/Bforartists/assets/13919702/2c6cbc42-78c3-420f-ba65-5a256cf3cf4c)

**Comment by ReinerBforartists** [comment]
Ah is also missing in Object mode.

**Comment by Blenux** [comment]
same issue has #4457
