### ISSUE TITLE
All icons are horizontally offset by one pixel

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4462]
p.reign has beaten me to it. The icons are all horizontally offset by one pixel. Good to see at the camera icons or the Primitives. There must be a padding value in the way somewhere.

Above the new icons in current build. Below the icons in BFA 4.1

![offset](https://github.com/Bforartists/Bforartists/assets/13919702/9a84aacf-9cb3-4b46-8d74-c4d3b256d493)

**Comment by Blenux** [comment]
I've been looking into this all day, notice it also, can only fix it by manually editing each svg file, but doesn't seem right, trying to look in code, 

(here is Torus fixed, compared to rest)
![image](https://github.com/Bforartists/Bforartists/assets/25260650/c00fecbc-98ce-4db7-b457-1305236cf585)

**Comment by ReinerBforartists** [comment]
Editing every svg should not be the solution. There must be a padding defined in the code somewhere.

Have you checked if Blender has this issue with the new icons too?

**Comment by Blenux** [comment]
Yeah will look again, and nope just us.

**Comment by Draise14** [comment]
Blender SVG icons are no longer square. This is the issue. Harley said we could do square but apparently that isn't the case.

1600x1700 fixes this.

**Comment by ReinerBforartists** [comment]
Sheesh :D

**Comment by ReinerBforartists** [comment]
Draise thinks we should try to make our icons canvas wider by one pixel. Better said 100 units. Means we need to do a search n replace at all svg files to replace viewbox="0 0 1600 1600" by viewbox="0 0 1600 1700" . Could fix the problem. So worth a try.

![toall](https://github.com/Bforartists/Bforartists/assets/13919702/8b27051c-85ec-40cd-822e-73cca069dd6e)

**Comment by ReinerBforartists** [comment]
What still baffles me, we have the same code than Blender. We have the same icon size than Blender. But for us it offsets.

**Comment by Blenux** [comment]
Same been at it all day, nothing works  grrr

**Comment by ReinerBforartists** [comment]
Mh, let's do the code comparison from this task after the next merge. Maybe we find a missing bit that spits us into our soup here ...

https://github.com/Bforartists/Bforartists/issues/4466

**Comment by Draise14** [comment]
https://github.com/Bforartists/Bforartists/assets/35357409/8b9b1619-97bc-4686-9098-07728354eeb8

Did a scale test, and the icons indeed do jitter, so.. best we just resize the canvas to have a nice default, then live with it, not sink too much effort. I'll let Harley at Blender know eitherway.

**Comment by Blenux** [comment]
Try adding + 1.00 in blf_glyph.cc line 377,

const int dest_w = int(image->width * scale);

to

const int dest_w = int(image->width * scale + 1.00);

**Comment by ReinerBforartists** [comment]
Yup, this seems to fix our offset problem. Nice :)

Mh what i notice though, they made the display worse with different scaling than 1. All icons becomes blurry then.

Above scale 1, below scale 1.2 ...

![gridproblem](https://github.com/Bforartists/Bforartists/assets/13919702/318268a2-ed9d-4588-a9e7-7d779cd4cd44)

**Comment by ReinerBforartists** [comment]
Hmmmmm. Blender had this before the svg icons already. But it gots worse.

**Comment by ReinerBforartists** [comment]
Reported. https://projects.blender.org/blender/blender/issues/124390

**Comment by ReinerBforartists** [comment]
Stumbled across this change where i have no idea what it is good for. What buttons are higher now? Maybe related?

source/blender/windowmanager/intern/wmfiles.cc

![butttonheight](https://github.com/Bforartists/Bforartists/assets/13919702/9c309692-29d5-4df4-9899-0ae8f393681a)

**Comment by ReinerBforartists** [comment]
Mh, code comparison did not fix the issue. 

We have meanwhile the information that the grid for icons has decreased from 16 to 14 pixels. Maybe that's what makes us trouble here. 

The files in question seems to be in source\blender\blenfont\intern

**Comment by Draise14** [comment]
Compiling the test for the gliph +1.00 test.

**Comment by Draise14** [comment]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/2d387acc-be2a-431d-81d8-5375e03c76e7)

Yeah, that fixed. Will revert #4444

![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/e2afbdde-ce24-47f5-9ce0-ddc3bdf1c037)

**Comment by Draise14** [comment]
Gonna tag you into this task since you found the fix @Blenux

**Comment by Draise14** [comment]
They.. merged in the color icons, and the 1px offset is no-longer needed.
