### ISSUE TITLE
Shader Editor , World mode, missing icon for Gabor node

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4463]
Icon is missing. Not sure if completely missing or a conversion fail.

![gabor](https://github.com/Bforartists/Bforartists/assets/13919702/c712fd04-0cfb-4355-ba9e-786536dfb282)

**Comment by ReinerBforartists** [comment]
Also missing in Object mode.

**Comment by Blenux** [comment]
Notice this also, been meaning to get to but brain is slow lol

**Comment by ReinerBforartists** [comment]
Always make a tracker entry when you stumble across such things :)

**Comment by ReinerBforartists** [comment]
Is completely missing, and is also not documented yet.
