### ISSUE TITLE
Do a code comparison between Blender and Bforartists

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4466]
It's the time of the year where we need to do a code comparison between the Blender and Bforartists source again. Some things always makes it through, and so from time to time such a comparison is necessary.

I did a quick test already, and it is really necessary ...

![difference](https://github.com/Bforartists/Bforartists/assets/13919702/5aad4152-adc7-4c8d-811f-24a2f294ee19)
![overlooked](https://github.com/Bforartists/Bforartists/assets/13919702/72c2a616-8c7b-4fa1-a342-6d68f536b3d6)
![third](https://github.com/Bforartists/Bforartists/assets/13919702/6c8fadf1-3086-4701-94fe-6fdcc0611634)

**Comment by Draise14** [comment]
Things move fast I pulled Saturday. Not the same day I did the merge. 

And for the colored icons I had to pull a patch. I guess it needs more comments.

**Comment by ReinerBforartists** [comment]
That's why i made sure that our master is at the same commit than Blender :)

Mh, i think with the color patch it would be best to comment out the Blender code, and make the patch a block with bfa start and bfa end comment.

**Comment by ReinerBforartists** [comment]
Off we go. Let's have a look what i catch here.

**Comment by ReinerBforartists** [comment]
Mh, there is still a pull request in the queue ...

**Comment by ReinerBforartists** [comment]
Flight, we have go

**Comment by ReinerBforartists** [comment]
I Hates it ^^

![crash](https://github.com/Bforartists/Bforartists/assets/13919702/f3e480ca-4386-40e8-b7a6-2fb3b6796799)

**Comment by ReinerBforartists** [comment]
Mh, i assume that these bits that i had to revert are part of the color patch. Will comment these parts as such.

![colorpatch](https://github.com/Bforartists/Bforartists/assets/13919702/3e5a1869-6393-4a33-b7cc-8094bbf860c1)

**Comment by ReinerBforartists** [comment]
Catched a handful

![catched](https://github.com/Bforartists/Bforartists/assets/13919702/6c2adb21-7dca-431b-9a82-57327ed34fe4)
