### ISSUE TITLE
Lib folder differences between Bforartists and Blender

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4473]
I haven't really followed the further development of the libs once the lib folder was implemented into the repository. But by the code comparison i stumble across many outdated libs now. The lib folder that i have here differs dramatically from Blender.

I did already a make update instead of a simple git fetch and git pull. But it has no effect. What is the proper method to update our libs now? Merge in from Blender? 

![difference](https://github.com/Bforartists/Bforartists/assets/13919702/e49582d0-e3d2-4631-b2a2-5a6aa6f16b77)

**Comment by Draise14** [comment]
I don't actually know. It may be a submodule that you gotta update? I am finding the submodule update feature of tortoise git may be better at this than the default make update from terminal. 

I assumed these were updating automatically.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/900bb6f6-0cd5-4adf-a126-fac960d303d1)

Ok, figured it out. The submodule libs need to be "checked out" to the "main" branch, since they are probably headless. They don't "update" because they weren't checkout out correctly.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2fa8a077-6796-4d86-b142-b2d7560bbace)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/579f2b93-df21-4ad9-bddd-c2664b1ec69b)

Linux would also need to be checked out to main to then be able to pull.
Not sure why the libs did not do this automatically when building the repo, but should be a step we should document.

**Comment by ReinerBforartists** [comment]
Okay, got it. So we open the console inside of the lib that we need to update. Type in a git checkout main, then a git pull. Works :)

We might need to tell this to our mac maintainers too.

**Comment by ReinerBforartists** [comment]
Mh, how do we get the assets lib at Linux?

**Comment by ReinerBforartists** [comment]
Ah, the assets are in release/datafiles

**Comment by ReinerBforartists** [comment]
![assets](https://github.com/Bforartists/Bforartists/assets/13919702/500f5511-5ddf-4d1b-96d9-8faae1eb4ffc)

**Comment by ReinerBforartists** [comment]
And what shall we do with the rest of the submodules?

![rest](https://github.com/Bforartists/Bforartists/assets/13919702/b7363acf-95fb-4ecb-86e7-40cdb529c0ee)

**Comment by Draise14** [comment]
The addon_constrib are there to compare repo versions of the addons with our core addons. So leave them there.

**Comment by ReinerBforartists** [comment]
Mh, while thinking about the problem, the issue is that the sub modules expect to be in main branch, right? Shall we go the pragmatic route and develop in a branch called main now too? And dump the master branch?

**Comment by ReinerBforartists** [comment]
Hmm, might not help. It needs to be in Blender/main. We would be Bforartists/main ...

**Comment by BUGProtectionAssociation** [comment]
I think we needn't make a branch of branch.
Just keep in Blender/main. :)

**Comment by ReinerBforartists** [comment]
Doing a 

`git submodule foreach git pull --rebase origin main`

does the trick nowadays. I think we can close this task therefore.
