### ISSUE TITLE
Dope Sheet - New Bake Channel operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4474]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/49dade8e-d057-4e30-947f-03ed59bbd66c)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/70c35896-20cb-4ac9-87bd-4067cb1d35b7)

# Task
- Add icon, an existing one could do
- Add Bake Channels to documentation
- Add to the toolbars potentially

<details>
<summary>Details</summary>

SHA-1: af089bee98b2f06f07cc81351dd93c758795bef5

* Fix: Add missing Bake Channel operator to Dope Sheet

This PR adds the operator "Bake Channels" to the "Channels" menu of the dope sheet.
The operator was already in the "Channels" menu of the Graph Editor.

Pull Request: https://projects.blender.org/blender/blender/pulls/123559

</details>

**Comment by ReinerBforartists** [comment]
Documenting
![bake](https://github.com/user-attachments/assets/4077b52c-e1fa-4559-a694-54b156da222b)

**Comment by ReinerBforartists** [comment]
Fixed
