### ISSUE TITLE
Default Workspaces - UV Editing - Console warnings

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4475]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2ea3651b-820d-451a-9585-4403be294710)

Right now when switching to the UV Editing workspace, the console is spammed with error. These are fixed when you save a new startup after removing the old image editor. 

# Task
- Remake the startup file to have a clean UV Editing workspace.
- Do the same with the All group.

**Comment by ReinerBforartists** [comment]
The error comes back in the moment when you create a new UV Image Editor. Houston we have a problem ...

**Comment by ReinerBforartists** [comment]
Related https://github.com/Bforartists/Bforartists/issues/3236

**Comment by ReinerBforartists** [comment]
Ah, happens in Blender too ^^

**Comment by ReinerBforartists** [comment]
Bug report created https://projects.blender.org/blender/blender/issues/124647

**Comment by Blenux** [comment]
Found the error, please report to blender has the site won't load for me.

Simply need to add this in rna_space.cc 

`SI_ITEM_UV,`

to

static const EnumPropertyItem rna_enum_space_image_mode_ui_items[] = {


![image](https://github.com/user-attachments/assets/c1a3ffae-e859-40a3-8bdd-e33b9d36abb7)

**Comment by ReinerBforartists** [comment]
Good catch. I have forwarded it to the report. Mh, shall i mention your name there?

**Comment by Blenux** [comment]
Yeah I think it's Firefox, seems to load better in Vivaldi

**Comment by Draise14** [comment]
Fixed it momentarily in the merge.
