### ISSUE TITLE
Sequencer - Preview & Sequencer Preview Snapping properties float left

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4476]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/c73331f5-7d98-40af-990f-758ce935ff7a)

New snapping in Sequencer & Preview mode. This means we can snap things in the preview mode in certain ways. 

# Task
- Float the Preview Snapping properties left

<details>
<summary>Details</summary>

SHA-1: 406554c11e1be649ec6f035e7229542755d639de

* VSE: Add snapping in preview area

Adds snapping in the VSE preview area.

Source points are the four corners and origins of all selected, visible
image quads. Targets can be preview borders, preview center, or
corners/origins of other strips.

Pull Request: https://projects.blender.org/blender/blender/pulls/122759

</details>

**Comment by ReinerBforartists** [comment]
![snap](https://github.com/user-attachments/assets/804cf766-ec57-4a3a-b186-e12fa941da30)

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Documented.
