### ISSUE TITLE
Sequencer - Add Preview Snapping header buttons to Preview mode 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4477]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f3eb0333-d052-4022-bca8-cee7d4d8feb3)
Right now you can get preview snapping, but not in the Preview mode of the sequencer editor. It might be a good idea to consistently expose the preview snapping to the Preview only mode. Not sure why Blender left this out, you can't even transform this in the Sequencer & Preview mode. 

# Task
- Add the snapping panel to Preview mode only, and show only the Preview Snapping toggles
- Document

<details>
<summary>Details</summary>

SHA-1: 406554c11e1be649ec6f035e7229542755d639de

* VSE: Add snapping in preview area

Adds snapping in the VSE preview area.

Source points are the four corners and origins of all selected, visible
image quads. Targets can be preview borders, preview center, or
corners/origins of other strips.

Pull Request: https://projects.blender.org/blender/blender/pulls/122759

</details>

**Comment by ReinerBforartists** [comment]
I would say let's wait a few days until Blender devs realizes this ...

**Comment by ReinerBforartists** [comment]
... ah, what the heck ...

**Comment by ReinerBforartists** [comment]
documenting 
![all](https://github.com/user-attachments/assets/60090973-4d74-4aa8-b07e-bc591811f12c)

**Comment by ReinerBforartists** [comment]
Done
