### ISSUE TITLE
3D View - Armature - Pose Mode - Selection Sets is now a panel and needs consistent iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4479]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/2e6fc8ec-464d-4418-b77b-22d9e7349c9e)
Bone Selection sets panel is now a thing. It has buttons very similar to the Bone Collecitons panel, and our iconography should be implemented into it. 

# Task
- Add icon to Assign button
- Add icon to Remove button
- Add icon to Select/Deselect buttons

![image](https://github.com/Bforartists/Bforartists/assets/35357409/1ac27583-b4c7-478d-bdde-a4658c8500e8)
- Add icon to the selection set in the 3D view selection header menu
- Document extensively

<details>
<summary>Details</summary>

SHA-1: 9d3dc77e051ce31213272ff106f267aadc5e85ca

* Anim: move Bone Selection Sets add-on into Blender

The functionality of the Bone Selection Sets add-on is now integrated
into Blender itself. Rigify has been updated to no longer check for the
add-on, but just assume that the functionality is available.

The keymap is still the same, and so are all the class names. This
ensures that there are no conflicts when people still have the old
add-on enabled somehow. And there is versioning code to remove the
'add-on enabled' state so that Blender won't complain it cannot find it
any more.

Compared to the add-on, the following changes are made:

- The 'bone' icon has been removed from the list of available selection
  sets. It was the same for each entry anyway, and thus didn't provide
  any information.
- The code has been split up into multiple files, with the UI elements
  in `scripts/startup/bl_ui/properties_data_armature.py` and the
  operators in `scripts/startup/bl_operators/bone_selection_sets.py`.
- Helper functions and classes are prefixed with `_` to indicate that
  they are not part of any public API.
- The `Operator` helper subclasses have been transformed to mix-in
  classes. This way the only subclasses of `Operator` are the actual
  operators.
- Comments & descriptions have been updated for clarity & consistency.

This commit contains code by the following authors, ordered by number of
commits in the original add-on repository, highest first:

Co-Authored By: Ines Almeida <britalmeida@gmail.com>
Co-Authored By: Sybren A. Stüvel <sybren@stuvel.eu>
Co-Authored By: Campbell Barton <ideasman42@gmail.com>
Co-Authored By: meta-androcto <meta.androcto1@gmail.com>
Co-Authored By: Demeter Dzadik <Mets>
Co-Authored By: lijenstina <lijenstina@gmail.com>
Co-Authored By: Brecht Van Lommel <brechtvanlommel@gmail.com>
Co-Authored By: Aaron Carlisle <carlisle.b3d@gmail.com>

For the full history see the original add-on at:
https://projects.blender.org/blender/blender-addons/commits/branch/main/bone_selection_sets.py

Reviewed On: https://projects.blender.org/blender/blender/pulls/124343

</details>

**Comment by ReinerBforartists** [comment]
The Bone Selection Set submenu in the select menu is dynamic. That's behind my skills to add an icon here.

**Comment by ReinerBforartists** [comment]
Documenting.

![selectionset](https://github.com/user-attachments/assets/74f6f74d-3047-4cbc-a04e-8b203ad7f63e)
