### ISSUE TITLE
3D View - Sculpt Mode - Facesets Panel - Missing operator "sculpt.reveal_all" in the tabbed toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4480]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/6cc7cf7b-c70b-4baf-8366-4dbe67c30ed0)

There is a missing facesets operator in the Face Sets tab of the tabbed toolsehfl. 

# Task
- Go through and make sure these are consistent. 

```
rna_uiItemO: unknown operator 'sculpt.face_set_invert_visibility'

C:\3D_Stuff\bfa_build_windows_Lite_x64_vc17_Release\bin\4.3\scripts\startup\bl_ui\space_toolsystem_toolbar_tabs.py:3826
rna_uiItemO: unknown operator 'sculpt.reveal_all'
```

**Comment by ReinerBforartists** [comment]
Um. I have fixed the issue in the screenshot. Which was missing operators in the sidebar :D

Okay, let's have a look what the bug is ...

![added](https://github.com/Bforartists/Bforartists/assets/13919702/ad160512-67fe-47de-8077-e13c78fea3fb)

**Comment by ReinerBforartists** [comment]
This should do the trick.
