### ISSUE TITLE
Crash to desktop with Edit Source in the UI

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4484]
Wanted to edit some UI code, right clicked at it, did choose Edit source, and found myself at the desktop.

Blender had the same problem. Newest builder.blender.org works. The build from our merge not.

![crash](https://github.com/Bforartists/Bforartists/assets/13919702/7b1b6ca9-10fa-442c-9a25-45330f550a97)

**Comment by Draise14** [comment]
I can reproduce in Blender pulled today. Reported to Blender. There "is" a fix, we'll see if they do it. It's beyond me to fix.. 
https://projects.blender.org/blender/blender/issues/124470

**Comment by Draise14** [comment]
Fixed by blender. Will come in the next merge. 

https://projects.blender.org/blender/blender/issues/124470#issuecomment-1236977

**Comment by ReinerBforartists** [comment]
Mh, i need it naow ^^

Lemme add it to our code base, then we can continue ...

**Comment by ReinerBforartists** [comment]
Hm, and again commits regarding the sub modules. No idea how to prevent that. Either way, crash is gone \o/
