### ISSUE TITLE
3D View - Sidebar - Brush Settings - Expose operators to top level in a consistent data management method

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4487]
![bforartists_ydFbiuRhQb](https://github.com/Bforartists/Bforartists/assets/35357409/fa24a023-8996-448b-b461-f911bc5fa9f2)

These operators are pretty standard for managing data from lists - but Blender shoved them all into a sub-menu. Without icons. Inconsistent and inconvenient. 

Standards would follow this example where we can duplicate, delete and potentially do other common operators from a top level on the bottom row and to the side. Much more consistent and elegant. 
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/5a717cce-1d90-4220-aa58-018868d4f9ba)

# Task
- Move operators to a top level
- Add common remove/duplicate to bottom
- Add preview, update and revert to sidebar
- Add icons to all
- Keep the rest in the sub-menu

**Comment by ReinerBforartists** [comment]
It's a space problem. Adding these operators to the panel will make the panel burst. I suggest to keep this menu as is, and just add the missing icons. You don't use this operators every two seconds. More rarely up to never.

**Comment by Draise14** [comment]
Tested it in my Grease pencil drawing practice. Yes. You do use it often. In one 5 minute sitting I made 3 new brushes. 

I vote to move some of the common ones top to 1. Be consistent and 2. Be convenient. 3. Discoverability. 4. Familiarity (similar to previous system)

Without it, you are stuck with only one brush setting till you dig and find a way to make new brushes.

Previously we could hit the plus icon on a top level.

**Comment by ReinerBforartists** [comment]
>Tested it in my Grease pencil drawing practice. Yes. You do use it often. In one 5 minute sitting I made 3 new brushes.

Don't forget, you're a power user :)

It's really a tough decision. It will make the UI crowded. And most users will never ever create new brushes, but simply use what is available.

Here i once more wish we would have a system to switch between two states. One for the normal user who barely will ever touch the functionality. And one for the power users like you.

**Comment by ReinerBforartists** [comment]
The more i think about it, we could of course add this functionality. Replace the menu by a panel, add a pin, and when pinned, show the content expanded in the UI.

**Comment by Draise14** [comment]
If we add that kind of panel pinning for data management to unclutter the GUI (which imo wasn't before, so we are "reverting" a regression), we may need to add that consistently to all the other methods of data management (bone collections, selection groups, materials, vertex groups, node properties, and more).

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/c135a2c3-d53a-43f2-a90e-dfe538d3032d)

Here is what we had, we could do something similar.

**Comment by ReinerBforartists** [comment]
A line with tools below? Well, yeah, we could. But as told, this menu is a menu that a normal user will usually never touch. Your decision :)

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/bcef4717-c29e-4341-a601-ac4322700b77)

Closer.

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/5fd3f4fe-bf5f-4222-a9b0-048c1daf667a)

Hell yeah, much better.

**Comment by Draise14** [comment]
Will document in the brush rewrite.
