### ISSUE TITLE
Geometry Nodes - Geometry - Input - New Gizmo nodes for modifier mode 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4490]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/fb09b121-af5e-450d-b600-d782b44bbbeb)
We got a new group of Gizmo nodes, add icons and document. These are cool. 

Only in Modifier mode. 

Nodes:
- Gizmo Dial
- Gizmo Linear
- Gizmo Transform

![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/627ec877-b356-46b3-afc8-44c86eefb4bf)
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/8de624c6-9dba-45b3-b1aa-adcf1a68c848)

<details>
<summary>Details</summary>

You can read the rest of the info here:
https://projects.blender.org/blender/blender/pulls/112677

</details>

**Comment by ReinerBforartists** [comment]
I think we can use the icon that is already to see in the nodes ...

**Comment by ReinerBforartists** [comment]
... or not. It's three nodes -.-

**Comment by ReinerBforartists** [comment]
Manual update is too big to do it with the task. It is a new chapter. So making it a task.
