### ISSUE TITLE
Sculpt Workflow: Tab Tools > Stroke - Advanced zip group

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#45]
This task is part of the Sculpting Workflow task set.

In Sculpt Mode, there is a Tools tab with a Stroke panel - which doesn't have a lot to improve on, maybe an advanced panel

Create Advanced zip group

Why? Because the smooth brush settings are used less often and is just bloat clutter that could be toggled away on normal workflow.

![epicpen_2018-02-27_10-17-13_0](https://user-images.githubusercontent.com/13919702/37240697-693b08fa-244f-11e8-9604-23c0a9f1c1cd.png)

----

oops, wrong image. Forget the blue text in image. Just the advanced panel.

**Comment by ReinerBforartists** [comment]
Let's add a subtab here.

**Comment by ReinerBforartists** [comment]
Hm, do we really need a subtab here? Let's have a look to hide the sliders when smooth stroke is not ticked.

**Comment by ReinerBforartists** [comment]
Fixed in master

https://github.com/Bforartists/Bforartists/commit/d5f5eeca9129d7bdf3e70d6491f969b1ea0e6c2b

![smoothstroke](https://user-images.githubusercontent.com/13919702/37588899-eb0e6226-2b63-11e8-90f9-4c15481092bf.jpg)

**Comment by Draise14** [comment]
Good call.
