### ISSUE TITLE
Remove not longer used branches

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4500]
We have a whole bunch of branches that are not longer needed. We should remove them. They are in the way when i try to switch locally. It's basically the ones with the issue number in front ....

![toomuch](https://github.com/user-attachments/assets/4ac915cd-9214-4343-8738-9f8ec304869c)

**Comment by Draise14** [comment]
How do you prune these? From GitHub directly?

**Comment by ReinerBforartists** [comment]
Yup
Take care not to delete our master ^^

![branches1](https://github.com/user-attachments/assets/2fcd0f9f-c5a0-4ffc-92e3-f69af40bbb8a)
![branches2](https://github.com/user-attachments/assets/ecc749d2-f7c6-4121-88a8-008bcc33a69a)

**Comment by ReinerBforartists** [comment]
And once done, do a _git remote prune origin_ at your local repository.

**Comment by Blenux** [comment]
Deleted branches I created

**Comment by ReinerBforartists** [comment]
Wasn't the task to remove the ones that are not longer needed? ^^

**Comment by ReinerBforartists** [comment]
Okay, i'll clean up.

**Comment by ReinerBforartists** [comment]
Ah you catched most of them already. 

Task done.
