### ISSUE TITLE
Preferences - Extensions + Tab move tags to far right

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4505]
![image](https://github.com/user-attachments/assets/5a9d7015-d063-4e5c-a49e-db149aea75b4)
![image](https://github.com/user-attachments/assets/1c30f1c0-e549-4742-94b8-20179e44cd4d)

Typically we have filters and overlay settings float far right, tags are like filters - so float right consistently.

Similar layout is in both the Outliner, File Browser and Spreadsheet.
![image](https://github.com/user-attachments/assets/16b97ef3-6f77-40fd-a014-6a3494fc2093)

**Comment by Blenux** [comment]
This already done?

![image](https://github.com/user-attachments/assets/d48e3fe7-572a-419e-ab04-c7b9702a371f)

**Comment by Draise14** [comment]
Ah yeah. Forgot to tag it.
