### ISSUE TITLE
Preferences - Addons - Move the uninstall button to top level

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4506]
![image](https://github.com/user-attachments/assets/a81547cf-ca4c-4a7e-90f3-eb1991203820)

Will make it consistent with future method to uninstall extensions. This will also make it discoverable. Previously in extensinos you would have to unisntall from a drop down, now you have to open description for the same.. the workflow is disjointed, messy and looks bad.

This also is a regression, we already had this with the previous extensions system. 

# Task
Move the addon uninstall button to a top level by the icon

**Comment by Blenux** [comment]
is this for all (built in, extensions) or just user added icons (legacy)

**Comment by Draise14** [comment]
All extension and legacy add-ons..not built in though... 

Right now to uninstall an extension listed in the addon tab means... Switching to the extension tab, recall name search, go to a sub menu, uninstall... When it's listed with all addon.....

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/785c3930-d2d4-4049-a2e6-c5154f892e98)
