### ISSUE TITLE
Preferences - Extensions - View Details needs an icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4507]
![image](https://github.com/user-attachments/assets/a07d017a-f1b3-4bed-87de-eac85258e46c)

You can now view details of the addon which will swap over to the addon tab, like a quick jump. We should add an icon there. 

I think maybe the eye (hide) icon or the addon plugin icon.

**Comment by Blenux** [comment]
Think the eye looks the best.

![image](https://github.com/user-attachments/assets/15e57cc4-eaa5-4a88-9d00-30984bc2133b)

![image](https://github.com/user-attachments/assets/4697c4f8-ec5e-4530-b857-34e0b68380d2)

**Comment by ReinerBforartists** [comment]
You can also use the info icon

**Comment by Blenux** [comment]
hmm true

**Comment by Draise14** [comment]
Ingo icon yesh
