### ISSUE TITLE
Preferences - Extensions - Add operator to "jump" to theme editing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4509]
![image](https://github.com/user-attachments/assets/0a34b86c-5ff7-42b2-9432-7cf7ca7eb79f)

Right now, you can "View" an addon directly from extensions which will jump to the addon settings. The theme extension workflow and operator could do with the same love and UX - jump to theme editing settings. 

# Task
Add a new opeartor that "jumps" to the theme editing settings. 

Similar to this:
![bforartists_2rzTznJ4Sm](https://github.com/user-attachments/assets/5f546916-e644-46d2-967e-e86493584fe5)

**Comment by Blenux** [comment]
Like so?
https://github.com/user-attachments/assets/3245e9aa-e0ce-4c52-9841-c76d50767737

**Comment by Draise14** [comment]
Aye
