### ISSUE TITLE
Hard Crash when scaling a Grease Pencil after drawing a stroke

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4518]
https://github.com/user-attachments/assets/a7cb73aa-bd1f-4d58-9989-5c734ea26829

Hard crash when you draw a grease pencil stroke, then scale the brush pressing X. 

1. Go to the `blender_sync_main` branch
2. Build and open
3. Create a grease pencil
4. Go to draw mode
5. draw a line
6. Press "X" to radial scale the brush
7. Instacrash

For the record, this doesn't crash in Blender
This also is not a keymap issue it seems

**Comment by Draise14** [comment]
Can't release like this, so will do a merge....

**Comment by Draise14** [comment]
[bforartists.crash.txt](https://github.com/user-attachments/files/16355996/bforartists.crash.txt)

Here is the crashlog if anyone has an idea!

**Comment by ReinerBforartists** [comment]
Does this happen in Blender too? Then report it to Blender.

Does it just happen in Bforartists? Then compare the files from the crashlog with ours. 

> Stack trace:
> bforartists.exe     :0x00007FF77A7432E0  GreasePencil::get_active_layer C:\3D_Stuff\sync_blender_main\source\blender\blenkernel\intern\grease_pencil.cc:2763
> bforartists.exe     :0x00007FF77A659CA0  radial_control_set_initial_mouse C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_operators.cc:2641
> bforartists.exe     :0x00007FF77A658740  radial_control_invoke C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_operators.cc:3199
> bforartists.exe     :0x00007FF77A64C050  wm_operator_invoke C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_event_system.cc:1602
> bforartists.exe     :0x00007FF77A649100  wm_handler_operator_call C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_event_system.cc:2665
> bforartists.exe     :0x00007FF77A64B0B0  wm_handlers_do_keymap_with_keymap_handler C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_event_system.cc:3057
> bforartists.exe     :0x00007FF77A64A660  wm_handlers_do_intern C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_event_system.cc:3387
> bforartists.exe     :0x00007FF77A649830  wm_handlers_do C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_event_system.cc:3530
> bforartists.exe     :0x00007FF77A645EB0  wm_event_do_handlers C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm_event_system.cc:4209
> bforartists.exe     :0x00007FF77A626D50  WM_main C:\3D_Stuff\sync_blender_main\source\blender\windowmanager\intern\wm.cc:639
> bforartists.exe     :0x00007FF77A5CDF20  main C:\3D_Stuff\sync_blender_main\source\creator\creator.cc:601
> bforartists.exe     :0x00007FF77BA058F4  __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

**Comment by ReinerBforartists** [comment]
Blender does not crash. But has also no action assigned to X from what i can see.

May i ask what X does in Bforartists?

**Comment by ReinerBforartists** [comment]
This bug is in our keymap. Switched to Blender keymap and no crash. 

I guess one of the hotkeys from us is not longer available.

**Comment by Draise14** [comment]
Operation is the grease pencil brush radius, after drawing

Crash in blender didn't happen. 
I compared the files in report and only difference is the 3D sequencer code, which should have nothing to do with it. The rest of the docs are identical. I will triple check today with a fresh mind. 

Blender keymap did crash for me with the same operator (F). Will compare either way. Maybe it's my cache. Fresh mind. 

Znight found some potential clues to test today. 

> Base on the crash file that you have I trace down this
https://github.com/Bforartists/Bforartists/blob/sync_blender_main/source/blender/windowmanager/intern/wm_operators.cc#L2641
https://github.com/Bforartists/Bforartists/commit/619ea62850fb9ca6783723ab7318d1a1febe5a9f#r144570601

*edit: the commit for that change 
https://projects.blender.org/blender/blender/pulls/124883

**Comment by ReinerBforartists** [comment]
Ah. Can confirm. F with the blender keymap crashes. But just in BFA, not in Blender.

We have quite a few hotkeys with F here. But we nevertheless need to find out which one quits.

![lots](https://github.com/user-attachments/assets/8a4454fe-e3d0-4477-89db-4182cb731ed3)

**Comment by Draise14** [comment]
Already tested. It is only the grease pencil paint radius.

**Comment by ReinerBforartists** [comment]
Then make a debug build

**Comment by ReinerBforartists** [comment]
Okay. operator call is the same in blender and bfa.

Funnily, the debug build crashes already at startup here. Ah, i wish i would have time for this fun ...

![crashatboot](https://github.com/user-attachments/assets/0fa2082d-de40-4736-989f-041c8b40123b)

**Comment by Draise14** [comment]
Yes. Maybe these are linked. Seems one of the nodes having trouble are experimental, and if those are having trouble then the new GO nodes for GN might also be having troubles after the fact. Since the go bug is not being able to insert to the active layer correctly or something?

I'm back at the medical checkup, but after I will resume and try get the debug build going... And learn how to properly debug with breaking points... I don't even know how to do that right.

**Comment by ReinerBforartists** [comment]
And i have forgotten how it works. You better ask somebody else  ^^

Fun fact, Blender debug build starts. So we have a baddie here, connected or not.

**Comment by Draise14** [comment]
[bforartists.crash.txt](https://github.com/user-attachments/files/16369433/bforartists.crash.txt)

Step closer. Now when you search in the hotkeys, you get a BLI_asset fail, so now something is mc-gucky with the hotkeys indeed.

**Comment by ReinerBforartists** [comment]
Not with the hotkey itself, but with the operator call.
