### ISSUE TITLE
Top Menu - Help - add "About Bforartists" hidden operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4521]
![Discord_YvMqE3dXBV](https://github.com/user-attachments/assets/ca259924-548a-45f4-a075-679b13c4caa3)

We have an "About Blender" operator, should be "About Bforaritsts" and exposed to GUI. 

# Tasks
- Update the panel to mention Bforaritsts
- Remove donate button to Blender
- Try make logo full color version (monochrome right now)
- Expose operator to the help menu

**Comment by Blenux** [comment]
Was planning on doing this (When I remembered to), the hardest part still trying to work out is making the icon be colour.

**Comment by Blenux** [comment]
I cheated and asked Harley bah

![image](https://github.com/user-attachments/assets/cc80189a-2d24-42ef-9034-3457c7f2fd1b)

**Comment by Blenux** [comment]
Almost there, fix one thing, but then that changes another bah.
