### ISSUE TITLE
Grease Pencil - Draw Mode - Brush Settings panel regression

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4522]
## Former
![bforartists_a1LxkASzyJ](https://github.com/user-attachments/assets/0c9ba914-aba7-4896-9c20-181b7fe3702a)

## Current:
![bforartists_C1G7zfJkvj](https://github.com/user-attachments/assets/885b9c27-5999-4b13-82a1-ecf3dabcb3c4)

Major brush settings panel regression. We gotta compare with 4.1.1 official release and update. This is due to the Grease Pencil 3 update.

**Comment by Draise14** [comment]
I think it's here: `brush_basic_grease_pencil_paint_settings`

![Image](https://github.com/user-attachments/assets/cf5dbf5b-9331-4490-9a8a-128d9140c3f8)

**Comment by Draise14** [comment]
Got my eyes on this one.

**Comment by ReinerBforartists** [comment]
Meanwhile in the double menu entry department ... 

THIS is the reason why you don't keep legacy code. You shoot yourself into the foot. The mix becomes unmanageable. When you need to readd it later, then readd it later. And not now in advance.

![doubles](https://github.com/user-attachments/assets/24a26ce1-608a-48bd-b8ca-878504436f81)

**Comment by ReinerBforartists** [comment]
Will make it an extra task.

**Comment by ReinerBforartists** [comment]
Okay, what is left is the Cursor dropdown. No idea how to bring this one back. The old code doesn't help me in any way. So when it's about me then i would leave it as is. Maybe report it to Blender. Since the whole tool settings can be hidden away.

And @Draise14 , i think what confused you most is these curves props. They just needs to be collapsed in our defaults. They are implemented in a different way now.

![remainingprob](https://github.com/user-attachments/assets/f8d8f8fc-9580-40dd-add1-59a4acbacbc4)

**Comment by ReinerBforartists** [comment]
As as reminder. the space_view3d.py file is comparable with Meld. So when something looks odd or does not work, grab the Blender code, and start from there.

**Comment by Draise14** [comment]
Yeah, those douple entries and moving cursor down could all be individual tasks and came in with the last merge - but may be cleaned up with this merge.

**Comment by ReinerBforartists** [comment]
Um no, i have cleaned them up :)

**Comment by ReinerBforartists** [comment]
Hmm, not done by saving startup.blend. Not done by saving preferences. I can't remember how to turn this toggles off by default.

**Comment by ReinerBforartists** [comment]
changing source\blender\makesrna\intern\rna_brush.cc and adding a boolean_default also fails. It doesn't compile anymore then, exiting with exit code 1. Also had a look at userdef_default.c, but no idea how to add the state of the flag there. You usually remove the ones that should be off, and just add the ones that should be on ...

I am pretty clueless at this point :)

![off](https://github.com/user-attachments/assets/2153c985-6004-49e1-a729-51f470381cba)

**Comment by ReinerBforartists** [comment]
I had a battle with ChatGPT, and it unfortunately just knows Blender 3.3 code as the last one. There is no way to find out where the function that we need is moved to. 

I had, assisted by chatgpt, this code here working for a normal brush with a mesh object for the brush area radius pressure in the BKE_brush_add function.

brush->flag2 &= ~BRUSH_AREA_RADIUS_PRESSURE;

But no way to find the right place for the new grease pencil. All classes names and variables have changed. It is now GP 3.

I personally am at the point to simply let go. We cannot fix everything. But if somebody has still an idea ...

**Comment by ReinerBforartists** [comment]
I will separate the issue with the panels into its own task now. The rest of this issue is long solved.
