### ISSUE TITLE
Core Addon - Remove 3D Viewport pie menus and include in legacy

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4531]
![image](https://github.com/user-attachments/assets/7ef0ecc0-a212-473a-bd56-23be34f6e9c0)

A class is registered already (built in?) - may need a cleanup.

**Comment by ReinerBforartists** [comment]
When you can't use something then it's a bug ;)

**Comment by ReinerBforartists** [comment]
Mh, the addon is for Blender 2.8.0 ...

**Comment by ReinerBforartists** [comment]
Our version is 1.3. The online version is 1.6.2. But does not contain our changes anymore then.

**Comment by ReinerBforartists** [comment]
As another note, this may not be our only outdated addon ...

**Comment by ReinerBforartists** [comment]
Mh, Blender 4.3 breaks the compatibility with the old version of the addon completely. Version 1.6.2 is a complete rewrite, and not to compare. 

I vote to remove the old pie menu that we currently have built in therefore.

https://extensions.blender.org/add-ons/viewport-pie-menus/

**Comment by Draise14** [comment]
We maintain our version of this one to have consistent icons in the pie menus with the other one, so might be worth adding that to the extension compare and update.

**Comment by ReinerBforartists** [comment]
Yeah, but we need to pimp the new version now.

**Comment by Draise14** [comment]
I will include the extension as is in the core, but remove it from our core. Let's not maintain it.

**Comment by ReinerBforartists** [comment]
Good decision :)
