### ISSUE TITLE
Hip binary kernel not found

### ISSUE THREAD

**Issue by NullPointerEcho** [Bforartists/Bforartists#4537]
Hi there,

On a portable install of Windows 4.2.0 of BforArtists with a AMD Radeon 7800 XT on Windows 10 I'm getting the error:
"HIP binary kernel for this graphics card compute capability (11.0) not found."
Cycles engine in supported or experimental both - But, Eevee works fine. Occurs in viewport and when attempting to render, resulting in showing just the transparency grid (see attached).
![HIPBinaryKernel - Copy](https://github.com/user-attachments/assets/48f6cf94-588a-448c-970a-93bda6e305f5)

Tested vanilla Blender 4.2 and did not encounter the issue and was able to render, filesizes for related files that I could find seem the same too, so I'm not really sure what the cause is. 

Any assistance is appreciated, thanks!

**Comment by ReinerBforartists** [comment]
Many thanks for the report. We will look into it.

**Comment by ReinerBforartists** [comment]
Since we depend at the main branch of Blender, which is always minium a month ahead, could you please check if the problem occurs with the newest Blender alpha version? It can be found here: https://builder.blender.org/download/daily/

**Comment by NullPointerEcho** [comment]
Thanks for the quick response as well!

I tried with the latest:
"Blender 4.3.0 - Alpha - Reference 0c09d3877448 - SHA - 30 Jul 03:49 - x64"
No error and able to render viewport and F12.

So I tried stepping back through versions, also no errors and able to render both:
"8c779cfade7d - SHA - 15 Jul 03:29"
"3b23dc4b4d47 - SHA - 10 Jul 01:55"
"addf1fa84b75 - SHA - 05 Jul 03:45"
"de7e3f992b13 - SHA - 30 Jun 03:28"
"7997d6259860 - SHA - 20 Jun 03:53"
"f371f46a5057 - SHA - 10 Jun 01:54"
"e114467a5463 - SHA - 05 Jun 23:41"

Was hoping doing that might provide more useful for information, but apparently not :P

Let me know if there's any more info I can provide though and I'll try and do so ASAP :)

Thanks again!

**Comment by ReinerBforartists** [comment]
Many thanks for the tests :)

Mh, the newest version is compiled by @Draise14 , while i made the earlier versions. Possible that simply the HIP version mismatches.

**Comment by Draise14** [comment]
Huh, maybe it got updated. I'll double check.

**Comment by Draise14** [comment]
Yeah, seems I had the wrong (old) SDK from the previous release. Will recompile with the HIP binaries again and re-deploy.

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/a4250d29-48d0-4e2e-b871-072c28fa2f7a)

Found the problem, the environment system variables Path and Paths were not defined to the C:\Program Files\AMD\ROCm\5.5\bin path. I'll try with 6.1.

**Comment by esnosy** [comment]
Install it to a path without spacesSent from my iPhoneOn 31 Jul 2024, at 8:04 PM, Draise ***@***.***> wrote:﻿
image.png (view on web)
Found the problem, the environment system variables Path and Paths were not defined to the C:\Program Files\AMD\ROCm\5.5\bin path. I'll try with 6.1.

**Comment by Draise14** [comment]
Ok, compiling a windows release build. @NullPointerEcho would you be ok if this be released as 4.2.1 which may come soon?

**Comment by NullPointerEcho** [comment]
Sorry it's been a rough ride with this release. With so many exciting things coming, no doubt there's so many new ways for things to break too, unfortunately.

But, I greatly appreciate both your efforts. And I will eagerly await the fix release then! Thanks and have a good one :)

**Comment by Draise14** [comment]
![Notepad_cNR4TDqZ7b](https://github.com/user-attachments/assets/e8dd94ee-996c-473b-ba0d-2f801ea8e1dc)

Sang too early. Still got compiling errors.

**Comment by esnosy** [comment]
I already told the solution, please uninstall all HiP ask from Windows settings, then run the installer again, then expand first entry, you will find a text box for path, choose a path that doesn’t have spaces, this is the solution I swear by god on my soulOn 1 Aug 2024, at 7:27 PM, Draise ***@***.***> wrote:﻿
Notepad_cNR4TDqZ7b.png (view on web)
Sang too early. Still got compiling errors.

**Comment by Draise14** [comment]
Ah, couldn't read with the weird github stuff. So in other words, install HIP not to "Program Files" but another area with no spaces. Will try that again.

**Comment by esnosy** [comment]
> Ah, couldn't read with the weird github stuff. So in other words, install HIP not to "Program Files" but another area with no spaces. Will try that again.
> 
> 
> 
> 

Yep

**Comment by esnosy** [comment]
Also please use HIP 5.5

**Comment by Draise14** [comment]
# Instructions for Windows 
![image](https://github.com/user-attachments/assets/2a551a56-889a-4616-8861-bfd23ade196f)

1. Make sure you have Perl installed correctly in your system. https://strawberryperl.com/
	a. Install
	b. Check if it detects in terminal through perl --version
2. Download and install AMD HIP SDK for your OS. Version 5.5.1 should be latest. 
	Make sure all previous or future versions and dependencies of previous versions are removed from the uninstall programs settings. 
	Download from here: https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
	Install to a path that has no spaces in the name. The default Program Files on Windows won't work. Example:C:\AMD\ROCm
3. Restart the computer
4. After installation, add these paths to the environment variables:
	HIP_PATH = C:\AMD\ROCm\5.5
	Path = C:\AMD\ROCm\5.5\bin
	
5. Now do a release build with make release or make ninja release
	1. If you don't want to do the following steps, a simple solution is commenting out two GPU's in step 9
	
	
(Steps 6-9 still evolving, couldn't get it to work yet)

<details>
<summary>Steps 6-9 (not working?)</summary>

6. After build error, remove the GPU's from the build solution: 
    a. Build, let it error, cancel build
    b. Then in the CMakeCache.txt file in the solution, remove the gfx1150;gfx1151 from the list.

```
//AMD HIP architectures to build binaries for
CYCLES_HIP_BINARIES_ARCH:STRING=gfx900;gfx90c;gfx902;gfx1010;gfx1011;gfx1012;gfx1030;gfx1031;gfx1032;gfx1034;gfx1035;gfx1036;gfx1100;gfx1101;gfx1102;gfx1103;gfx1150;gfx1151
```
c. Save file , and build again.  
_Reason being is that the latest versions of GPU's are not used in the official AMD HIP ROCm 5.5 and Blender doesn't use the 5.7 version._ 

7. Now do a release build again with make release or make ninja release
With that, it should build fine. 

8. If you don't want to change the build file, you will need to modify the source code to not include GPUs that work with HIP 5.5.1, including gfx1150 and gfx1151
   a. In the blender_release.cmake file, add the following a new line lines:102, this will add a new set of GPU's in the list, and remove the incompatible ones. 

```
if(WIN32 AND NOT (WIN32 AND "$ENV{VSCMD_ARG_TGT_ARCH}" STREQUAL "arm64"))
  set(WITH_CYCLES_DEVICE_HIPRT ON CACHE BOOL "" FORCE)
  # BFA - gfx1150, gfx1151 are temporarily removed from the [\\CMakeList.txt](file:///) list, as they are not included in AMD HIP ROCm 5.5.1.
  # BFA - Blender (thus our code) doesn't support HIP 5.7 on Windows.
  set(CYCLES_HIP_BINARIES_ARCH "gfx900;gfx90c;gfx902;gfx1010;gfx1011;gfx1012;gfx1030;gfx1031;gfx1032;gfx1034;gfx1035;gfx1036;gfx1100;gfx1101;gfx1102;gfx1103;")
  list(REMOVE_ITEM CYCLES_HIP_BINARIES_ARCH "gfx1150" "gfx1151")
endif()
```
  b. Delete the CMakeCache.txt in the build solution
  c. Rebuild with with make release or make ninja release
  d. If all is well, it should build fine

</details>

![image](https://github.com/user-attachments/assets/ab36f8e2-a56c-417b-805f-0481bb6818a6)

9. Alternative Solution: if still not working, GPU's would need to be removed from the **CMakeList.txt** to build. 
```
	  set(CYCLES_HIP_BINARIES_ARCH
	    gfx900 gfx90c gfx902
	    gfx1010 gfx1011 gfx1012
	    gfx1030 gfx1031 gfx1032 gfx1034 gfx1035 gfx1036
	    gfx1100 gfx1101 gfx1102 gfx1103 #gfx1150 gfx1151
	    CACHE STRING "AMD HIP architectures to build binaries for"
)
```

**Comment by ReinerBforartists** [comment]
We could add our own cmake file, completely without hip. Or with the needed changes to get it working.

**Comment by Draise14** [comment]
I pushed the comment to remove the two gfx1150 and gfx1151 from the CMakeList.txt file, so that we can use AMD HIP SDK 5.5.1 without a problem. Added a comment to show that it is temporary. Let's revisit this when Blender can compile correctly.

**Comment by ReinerBforartists** [comment]
Is there progress?

**Comment by Draise14** [comment]
HIP compiles on Windows now if you have the environment installed and configured in the paths. Linux also compiles with the right environment, but I don't know how to set that up yet. 

Technically this is resolved since the last release.
