### ISSUE TITLE
Hotkeys - Sequencer- Q to quick menu is not working

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4540]
![image](https://github.com/user-attachments/assets/b4fc506d-5811-4241-bc5c-d68cf5c0a2f9)

Q to quick menu is not working atm. In the video sequencer.

**Comment by Draise14** [comment]
Strange that this went missing, it was in the keymap previously. 

![imagen](https://github.com/user-attachments/assets/5ef83b18-647e-4918-9b42-bb6f63eb5ec3)

**Comment by ReinerBforartists** [comment]
Overriding problem?
