### ISSUE TITLE
File Browser - Icon issues in thumbnail mode

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#4542]
Some icons are off-centre and when setting 256 size, the colours go black and white.

This doesn't happen in Blender.

https://github.com/user-attachments/assets/5e22cd4d-63e4-428c-b460-b6eb21aa73c5

**Comment by Draise14** [comment]
Seems the large folder icon drawing is still monochrome? I would first check the large icon def type in the UI_list.hh file.

**Comment by Blenux** [comment]
Can't find a file called UI_list.hh?

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/d102463c-b551-4d1a-9d74-4ed559e902e9)

Never mind, it seems to be ok in the `UI_icons.hh` file (mistyped, was on the phone). The system does an image render of the SVG, and it must be doing it in black and white.

**Comment by Blenux** [comment]
The folder icons are also that large, they hit the folder names too.

![image](https://github.com/user-attachments/assets/16d2d92f-ad9b-41a9-b279-28aa6836738d)

**Comment by Blenux** [comment]
Slowly getting there, 

![image](https://github.com/user-attachments/assets/8bc6548a-12fd-4a02-bf97-9c7f89cd9e2c)

**Comment by Draise14** [comment]
Oh, what was the issue in the end? I feel I could learn a lot from what you do.

**Comment by Blenux** [comment]
Had to adjust the icon_x and icon_y postitions in file_draw.cc and also had to add a .01 to the BLF_svg_icon_bitmap in file_lists.cc file to stop the black and white icons, have no idea why these need to be done for our icons to work same has blender's.

also had to adjust the .svg file folder icons has they are not centered in tthe grid (2 grid spaces on top, one grid on bottom), will fix it all up later today when I get back home.
