### ISSUE TITLE
Simplifying Theme Creations

### ISSUE THREAD

**Issue by mack7963** [Bforartists/Bforartists#4543]
I think that most users of B4artist would like never to have to wade through the theme editor, so heres a possible suggestion to make it as simple as it can possibly get.
![Theme NEXT](https://github.com/user-attachments/assets/d98e3d6b-8cd6-44b8-b386-647ee2219dfe)
The idea is that when you click on the themes button in the edit preferences window another window pops up, this window has the palette creator and a colour picker icon, however in this case the colour picker is used as a colour delivery system. 
the user selects which screen they wish to theme, then clicks the colour they want to use and then clicks whichever section of the interface they want to colour.
this basically removes the very long winded process currently in use, and once the colour has been applied a list of all other parts of the screen have been affected, and because the edit preferences window stay open navigating the different screens will make theme consistency a lot easier to achieve.

**Comment by Draise14** [comment]
This is quite a large feature request! Would take a while to sort out.

But if you need something sooner, there are a few addons out there that try to solve this request:

# Quick Theme Editor for Blender
https://ludvikkoutny.gumroad.com/l/exmrx

# Theme Editor
https://pragma37.gumroad.com/l/theme_editor

# Theme Editor Lite
https://pragma37.gumroad.com/l/theme_editor_lite

# Theme Maker
https://blendermarket.com/products/theme-maker

**Comment by mack7963** [comment]
Hi Draise, I'm under no illusion as to the complexity this request involves and as a non programmer i wouldn't even know where to begin, i hope it can be done.

**Comment by ReinerBforartists** [comment]
Friends, a bfa theme creator is simply above our manpower budget. We usually don't do or maintain addons, asides from some very special cases. And here there are even already several addons available that tackles this area. I will close this request therefore if you don't mind.

**Comment by mack7963** [comment]
Hi, yeah i get how big this suggestion is in both time and manpower, thank
you for letting me know the suggestion is going to be closed.


                            Sincerely


                                    Mack

**Comment by ReinerBforartists** [comment]
Thanks for your understanding :)

You could contact one of the addon developers. Maybe somebody has an open ear for the one or another idea.

**Comment by mack7963** [comment]
Hi, I'm currently working on the features i think would make this a
worthwhile project, such as getting Blender to report back which aspects
are live and what else is live across other editors as I've found out that
quite a few of the colour options aren't even active in most of the
editors, once I have an outline to that then I can present it to an addon
developer, have an amazing day.



          sincerely



                        Mack
