### ISSUE TITLE
3D View - Grease Pencil - Edit Mode - Make operators show in the correct context and header menus

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4551]
![bforartists_wmtW11O3zI](https://github.com/user-attachments/assets/aac8dcbe-41a2-4e74-834a-65f121fa7877)

The Simplify operator only works on points, but not on selected strokes. This operator shows both in strokes context menu and strokes header menu - but it's a points operator only, and points context menu entry. 

Clean that up.

**Comment by Draise14** [comment]
A carryover from legacy...

**Comment by Draise14** [comment]
Oops, commit to the wrong task. I think I need a quick break.

**Comment by ReinerBforartists** [comment]
Okay, it's the menu items simplify and trim, one time in the stroke menu, one time in the context menu.

Digging ...

**Comment by ReinerBforartists** [comment]
Mission impossible. I will separate it into its own issue.
