### ISSUE TITLE
Icon - Update Geometry Set icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4557]
![image](https://github.com/user-attachments/assets/d4ec597d-7c55-40e2-8b77-1fe1314de302)

New icon, should make it our style. 

https://projects.blender.org/blender/blender/pulls/125293

<details>
<summary>Details</summary>
SHA-1: ae129da4f72904b31f7c6f593fc778cdefec8a5a

* UI: new Geometry Set icon

This icon can be used when refering to a "geometry set" which can contain
potentially multiple geometries of different types (such as mesh, volume, etc.).

It was designed by Simon Thommes as part of #125293.

</details>

**Comment by Draise14** [comment]
I think for this release, I will postpone. There are a number of icons that need updating, so will push for an icon update for 4.3

**Comment by ReinerBforartists** [comment]
Oh, and once again, just one task for one issue please. DON'T make a bunch out of it. This is not manageable. One by one is the key.

**Comment by Draise14** [comment]
Yes. This is one task. One icon. 

"Geometry set" icon.

**Comment by ReinerBforartists** [comment]
I can't get it to show up -.-

**Comment by ReinerBforartists** [comment]
Let's add some color here. When i remember right then this chapter isn't documented anyways.

**Comment by ReinerBforartists** [comment]
![geometry_set](https://github.com/user-attachments/assets/0c3b8f58-349e-4a2c-8f08-4a088fdc12dc)
