### ISSUE TITLE
Icons - New info bar keyboars icons, update to our system

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4559]
![image](https://github.com/user-attachments/assets/5f527ee7-692f-476e-9f69-48aec7d6e8ec)

We got a bunch of "key" icons that could have a splash of color or have our style. Update them if necessary.. though they are relatively ok. 

<details>
<summary>Details</summary>

SHA-1: a57c3be05e26b77acd0b993f13fbdd61972fcb3b

* UI: Add SVG Icons for Status Bar Event Use

This adds 26 SVG icons (13 unfilled/filled pairs) for use on the Status
Bar for keymap indication. No other functional changes.

Pull Request: https://projects.blender.org/blender/blender/pulls/125868

</details>

**Comment by ReinerBforartists** [comment]
Hm, honestly, i don't see a single one that needs color. Info bar icons are traditionally nearly all white icons anyways.

**Comment by ReinerBforartists** [comment]
They have an odd size O_O

**Comment by ReinerBforartists** [comment]
So, after looking at it, it is on or off state. I would say let's have a look to turn the on state green.

**Comment by ReinerBforartists** [comment]
![updated](https://github.com/user-attachments/assets/2aad39a0-3587-48eb-9b79-e859c73d8cf7)

**Comment by ReinerBforartists** [comment]
I am pretty sure that we don't have the different icons in the taskbar documented at all. So leaving the documentation part alone.
