### ISSUE TITLE
Icons - Cleanup icon order in UI_icons.cc and cmake file

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4564]
Right now the new icon set is one big alphabetical mess - and our system for icons is not alphabetical nor is it concurrent with each other anymore. 

Ideally we can make the SVG files, the UI_icons and the rest mostly in the same alphabetical order.

The only exception is sytem icons that Blender has grouped in a separate way. 

Order is irrelevant now, but we need an atleast consistent thought process here... 

# Task
- Organize most icons alphabetically
- Organize footer icons equally (out of alphabetical order
- Group into letter based chunks so it's easier to navigate or jump alphabetical groups

**Comment by ReinerBforartists** [comment]
Notepad++ offers a sort alphabetically option under edit / line operations. Which should speed up the process.

![sorting](https://github.com/user-attachments/assets/c432a7e7-9635-4d44-a8bd-d8d984c2fae3)

**Comment by Blenux** [comment]
I was only thinking that we should match it close to Blenders has possible and have our icons in appropriate places marked has ours (commented with # BFA, or iconname_bfa etc)

**Comment by Draise14** [comment]
We have over a thousand more than Blender, but the ones that line up to Blenders could indeed make life easier when doing a merge, but in that case the alphabetical order would be lost.

**Comment by ReinerBforartists** [comment]
Alphabetical order makes imho most sense. With over 1000 more icons a comparison with the Blender UI_icons.hh file is impossible anyways. I even fear that a automatical merge could damage our code then.

**Comment by ReinerBforartists** [comment]
Interesting result is interesting

![interesting](https://github.com/user-attachments/assets/7f56ebed-79e3-4e36-a83b-c67b718b78b2)

**Comment by Draise14** [comment]
Oh damn, something got nuked? Maybe there is a key order on some icons?

**Comment by ReinerBforartists** [comment]
Detected some possible trouble makers. I am not sure though if this comments doesn't regard the now gone svg file. But it's worth a shot.

![troublemakers](https://github.com/user-attachments/assets/0f4355a5-ce03-4e8c-bc3b-718134672af3)

**Comment by ReinerBforartists** [comment]
Nope, no problem anymore to change the order here. So, let's continue in small chunks ...

**Comment by ReinerBforartists** [comment]
Smaller chunks needed it seems ^^

![smaller](https://github.com/user-attachments/assets/6967a37f-719d-48c7-b901-034a2ba47990)

**Comment by ReinerBforartists** [comment]
This starts to become cumbersome. Doing it in chunks of 10 at the moment to find the baddie ...

**Comment by ReinerBforartists** [comment]
Great, quits but no baddie in sight -.-

![nobaddie](https://github.com/user-attachments/assets/5ce4ec2f-1cf9-41f9-85c9-6aac1cb6c99a)

**Comment by ReinerBforartists** [comment]
Oh man, the cmake cache makes also fun here. Doing it in chunks of 10 and always need to compile from scratch can take a while ...

**Comment by ReinerBforartists** [comment]
Now i am baffled. Compiled from scratch, changed the very first ten icons, and the problem is already present.

**Comment by ReinerBforartists** [comment]
Hah !

This one needs to remain at the top it seems. Fingers crossed ...

![hah](https://github.com/user-attachments/assets/cd7903af-e3ef-4c6f-8659-f407e6069d25)

**Comment by ReinerBforartists** [comment]
Shortened the issue title

**Comment by ReinerBforartists** [comment]
Note that some icons are at the top and at the end, and are not sorted alphabetically with the rest. The problem is the def_icon, and that our icons are not just def_icon_color. But that's just a handful. The rest is ordered now.

Let's test if it compiles at linux too before making the pull request ...

![unordered](https://github.com/user-attachments/assets/9bdc7725-5f30-4e71-b4c8-d80b450f0c91)

**Comment by ReinerBforartists** [comment]
Compiles. I cannot test though if it starts ...

**Comment by Blenux** [comment]
Linux builds and runs fine (posted this on the PR also)

![image](https://github.com/user-attachments/assets/ac6a9f78-92e9-4b85-844e-505314af5f7b)

**Comment by ReinerBforartists** [comment]
Many thanks for testing :)
