### ISSUE TITLE
Icons - Grease Pencil lineart icons need consolidation and consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4593]
![image](https://github.com/user-attachments/assets/3e554066-df33-4ca7-acba-9c210842a72e)
![image](https://github.com/user-attachments/assets/0df04af1-2748-4b95-b4d2-a9121f6d6e7f)

Right now the icons we have been using for grease pencil lineart modifiers, object times and operators have.. eh... become quite varied. 

# Task
- Consolidate the GP lineart iconography design, the little pencil I like, and the object with outlines is useful.

**Comment by Blenux** [comment]
Do we just want to use these for that menu?

![image](https://github.com/user-attachments/assets/9b373c23-400d-49d0-a5d0-8385cf3f9d5e)

**Comment by ReinerBforartists** [comment]
Looks good.

**Comment by ReinerBforartists** [comment]
Documenting

![lineart](https://github.com/user-attachments/assets/19b0b84f-6773-4959-95ac-2bfb33aff01d)

**Comment by ReinerBforartists** [comment]
Ah, this was a regression. Manual fits already.

![regression](https://github.com/user-attachments/assets/1ec34279-5fa7-4342-bae5-94cdf56fc084)
