### ISSUE TITLE
Topbar - Primitives - Lightprop group - wrong icons assigned

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4597]
![image](https://github.com/user-attachments/assets/780a2361-b912-4349-8f98-5289608d45d1)

![image](https://github.com/user-attachments/assets/9bb4a07d-4e72-4291-9c78-71c99714ec4b)

The light probe operators need icon updates (not updated since legacy EEVEE was pulled recently)

**Comment by ReinerBforartists** [comment]
Ah, the double set strikes back. One without an object, and one with an object in the scene ...

**Comment by ReinerBforartists** [comment]
There is more hiding. Friends what did you do to my poor topbar ^^
