### ISSUE TITLE
Font problem with the info text up left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4606]
Unreadable ...

![fontproblem](https://github.com/user-attachments/assets/cbcd6263-4dc9-48b0-93a9-fcad9c1636d1)

**Comment by Draise14** [comment]
This isn't present in my builds, so might be something else? A theme setting?
![image](https://github.com/user-attachments/assets/c340d27a-1df9-40c1-83fb-05d5d0169fae)

**Comment by ReinerBforartists** [comment]
Ah, this time i made the mistake with not posting the whole UI. Sorry buddy. It's in the 2d animation layout.

![ani](https://github.com/user-attachments/assets/230a6089-69a5-460c-baac-a5978dbf9489)

**Comment by ReinerBforartists** [comment]
Uh, we have a problem here anyways. The shot from above is from the All Template. This here is from the 2D Animation template. Black letter with white background is by design.

We need to fix the All template then.

![ani2](https://github.com/user-attachments/assets/d40f4145-f68b-457d-8be0-517375a9a517)

**Comment by ReinerBforartists** [comment]
Let's do it

**Comment by ReinerBforartists** [comment]
Hmm. when i open the 2D Animation workspace in the All template then the white background is gone. Where does this come from?

**Comment by ReinerBforartists** [comment]
Okay, Blender behaves the same. Let's do a report ^^

**Comment by ReinerBforartists** [comment]
Reported

https://projects.blender.org/blender/blender/issues/126922

**Comment by ReinerBforartists** [comment]
No bug. Intended behaviour. See Blender bug report.

@Draise, shall we close then? Or do you know a solution here?

**Comment by Draise14** [comment]
WHAT, so the text outline is.. viewport color based? What!? 

Nothing to do, unless we change core font code, and that would be a mess and a witch hunt. 

Or update the viewport rendering stored in the blend file. I am not sure how to store the view mode or setting in the blend files, sometimes they default to only workbench mode - not rendered - but for GP you would need rendered mode.

**Comment by ReinerBforartists** [comment]
Okay, then let's leave it alone. Closing.
