### ISSUE TITLE
Regression - Selected Pose Bones should keyframe single channel while holding ALT with the keyframe prop

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4607]
![340779688-b187c7d9-3607-4565-a803-6e97d72cd49b](https://github.com/user-attachments/assets/ea695806-60fd-48fc-87ec-ccaaf8243b1f)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/b187c7d9-3607-4565-a803-6e97d72cd49b)

Right now Blender has unified keyframing operators, but this broke our system to hold down ALT on a keyframe button and it would record on all selected pose bones or objects at the same time. 

This is a core feature that has an edge over Blender, so we should add it back. 

Eyad did a good job to migrate the majority of the work - but we still don't have the ability to keyframe selected pose bones (though it was built in theoretically). 
![image](https://github.com/user-attachments/assets/fdb9eb44-dcfc-4ab1-886b-88710d35a2cf)

I assume the `insert_key_multi` may need some work, and/or houw the vector pointers detect the pose bones. 

The task that broke it: `* Refactor: combine insert_keyframe() and insert_key_rna() into a single function`

<details>
<summary>Details</summary>
SHA-1: 1a4f084806952e5337cc7807429be8b20e04de90

* Refactor: combine insert_keyframe() and insert_key_rna() into a single function

The goal of this PR is to merge `insert_keyframe()` and `insert_key_rna()` into
a single function, `insert_keyframes()`, that fully accommodates the
functionality of both.  This results in a bit of a mega function, which isn't
great, but it centralizes a lot of otherwise redundant keyframing code so it
only needs to be changed in one place in the future.

Future PRs can work to reduce the "mega" aspect of this function, stripping it
down to its core functionality and eliminating left over incidental redundancy
(e.g. passing both `scene_frame` and `anim_eval_context`).

As a wonderful side effect, this PR also makes layered action keyframing work in
most of the remaining places left over from #121661, such as buttons, the
dopesheet, the graph editor, etc.

Pull Request: https://projects.blender.org/blender/blender/pulls/122053

</details>

**Comment by ReinerBforartists** [comment]
Wasn't this fixed already again?

**Comment by Draise14** [comment]
Unfortunately no. Only weekend in objects, not pose bones.

**Comment by Draise14** [comment]
Fixed by Eyad, nicely done!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 💙💙💙💙
