### ISSUE TITLE
Grease pencil in draw mode - legacy Layer prop

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4619]
This greyed out prop is not longer used with GP 3. It does not exist in Blender. So let's remove it.

![legacy](https://github.com/user-attachments/assets/61146263-03f6-4ab0-a303-2142bc367ab3)

**Comment by ReinerBforartists** [comment]
Ah, it's not so easy. Blender still contains the code. It just doesn't show in the UI. No error message.

Needs deper investigation.

![missing](https://github.com/user-attachments/assets/e2438abe-f592-4097-9119-31503af0a191)

**Comment by ReinerBforartists** [comment]
Made it a report

**Comment by Draise14** [comment]
I think the task here should be to update this panel to GP3. The GO3 layers panel exists. 

I tried on Thursday but the gpencil data context used to show it in the right context didn't work on GP3. I did use Greasepencil 3 modes to show the panel alternatively, but couldn't rebuild the layers panel code correctly yet.

**Comment by ReinerBforartists** [comment]
Doesn't really matter imho. Since they work at it. Let's wait what happens :)

**Comment by ReinerBforartists** [comment]
I get your point, but let's not do double work if necessary. There is no pressure since we do a release at the moment anyways.

**Comment by ReinerBforartists** [comment]
Now the layer panel is really gone. Closing. Documentation happens with another task together.

**Comment by ReinerBforartists** [comment]
Ah wait, not removed. Moved. It is now in the center group. Documentation is at its way.

**Comment by ReinerBforartists** [comment]
Documented.
