### ISSUE TITLE
Node Editors - Pin node tree icon has wrong icon when activated

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4628]
![bforartists_WxGJwAaBsE](https://github.com/user-attachments/assets/84395904-a2f0-4296-b527-2a317c94ae64)
![bforartists_Q1KsetnBnt](https://github.com/user-attachments/assets/b09ef0be-6c6e-4cb7-b214-3d5af91df062)

https://github.com/user-attachments/assets/16ca06d3-6025-4381-b9ca-1123ea0bcf31
For some reason the pin icon in the node tree toggle when on is the wrong icon. Might be a regression.

**Comment by ReinerBforartists** [comment]
Related Preferences - Hotkeys - Dropdown icon is wrong icon #4631

**Comment by ReinerBforartists** [comment]
fixed with commit to Preferences - Hotkeys - Dropdown icon is wrong icon #4631
