### ISSUE TITLE
Properties Editor - Modifiers - View toggle has wrong icon when on

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4629]
![image](https://github.com/user-attachments/assets/95377740-600f-41b0-a3aa-063c8aa96648)
![bforartists_zXPDZkkccS](https://github.com/user-attachments/assets/ea99dfaa-d13f-469f-aede-566093d18912)
https://github.com/user-attachments/assets/2e3bcf35-c309-4836-8912-551c474333c9

The modifier view toggle also has a wrong icon.

**Comment by Draise14** [comment]
Also true in the outliner. 
![image](https://github.com/user-attachments/assets/02ecc825-4a2e-484f-9939-b5863908d4cc)

**Comment by Draise14** [comment]
I know how to fix, all the toggle icons needs the +1, so might pull these out of the alphabet for these cases.

**Comment by ReinerBforartists** [comment]
Related: Preferences - Hotkeys - Dropdown icon is wrong icon #4631

**Comment by ReinerBforartists** [comment]
Fixed with commit to Preferences - Hotkeys - Dropdown icon is wrong icon #4631
