### ISSUE TITLE
Shader Nodes - Hint Shader AOV output from Cycles and realtime compositor 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4630]
![imagen](https://github.com/user-attachments/assets/3ba454f3-d810-48ac-bb7b-b7553d218915)

Shader AOV's are not compatible with Cycles in the realtime compositor. 

I have seen users report Shader AOV not working.. cause it's not working in Cycles only.

Add the mention of it in the tooltip or add a warning to the interface when in Cycles mode.

**Comment by Draise14** [comment]
Tooltip is incorrect, it IS compatible with EEVEE, not Cycles.

**Comment by ReinerBforartists** [comment]
Oh did i forget the cycles part? XD

**Comment by ReinerBforartists** [comment]
Added
