### ISSUE TITLE
Preferences - Hotkeys - Dropdown icon is wrong icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4631]
![bforartists_Z5hfFajIST](https://github.com/user-attachments/assets/2e523ea6-767b-4be2-86eb-da9632de86d9)
![bforartists_RKN2p1K4OG](https://github.com/user-attachments/assets/52f71eb1-1160-4769-9b55-3cf71d9b2eeb)

When toggling down a hotkey in the preferences, it shows the wrong icon.

**Comment by ReinerBforartists** [comment]
Ah i think i know, some icons are determined by the order in the list. And we have changed this order. One of those crazy design issues in Blender. The code does not call the icon directly, but calls one icon, and the next icon is the current icon plus one in the list. This will become a tough one to fix.

**Comment by Draise14** [comment]
Let's see if I can fix one.

**Comment by Draise14** [comment]
![bforartists_Hs1gz8HeDx](https://github.com/user-attachments/assets/69b03776-3964-4fef-bb36-24f6f3a693f2)

Ah ok, it's a matter of finding it and changing the order a little. Doable.

**Comment by Draise14** [comment]
Ah.. this might explain it.

<details>
<summary>Details</summary>

SHA-1: d563926d737593a8674523ac53e9c6cd5d5e2a67

* Cleanup: UI: Shuffle icons and group them in categories

No functional changes.

The comments in the file are used as categories by some of our ICON
reading tools.

This also groups the TOGGLES icons together, with comments about their
order. This only includes the icons actively used as toggles at the
moment.

Note that ICON_NONE has always to be the first one in this file since
some parts of the code (e.g., the code to turn RECORD_ON into colored,
and the code for the popover chevron) have no-icon hardcoded as 0.

Ref: !127197


</details>

**Comment by ReinerBforartists** [comment]
There is more. I want to dig into this. So i reopen the issue.

**Comment by ReinerBforartists** [comment]
Outliner is also bugged.

![outliner](https://github.com/user-attachments/assets/213d3764-7088-44d8-9ef4-a357e4a193b8)

**Comment by ReinerBforartists** [comment]
![transform](https://github.com/user-attachments/assets/a6a42279-8a5e-401f-94f9-67826f945206)

**Comment by ReinerBforartists** [comment]
Fixed. I hope i have catched them all. 

We should at one point fix the underlying idiocracy with the +1 code.
