### ISSUE TITLE
Shader Nodes - New Metallic BSDF node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4633]
![image](https://github.com/user-attachments/assets/a5c68285-3116-4e7d-8357-bc136195daf8)

New kid on the block, the metallic shader node

<details>
<summary>Details</summary>

SHA-1: 6ccb33e9fe14a5c312348dbd3deab37ad3057ca9

* Shader: Add Metallic BSDF Node

Add Metallic BSDF Node to the shader editor.

This node can primarily be used to create more realistic looking
metallic materials than the existing Glossy BSDF node.

This commit does not add any new closures to Cycles, it simply exposes
existing closures that were previous hard to access on their own.

- Exposes the F82 fresnel type that is currently used by the
metallic component of the Principled BSDF. Results should match
between the Metallic BSDF and Principled BSDF when using the same
settings.
- Exposes the Physical Conductor fresnel type that was previously
limited to custom OSL scripts. The Conductor fresnel type accepts
IOR and Extinction coefficients to define the appearance of the
material based off real life measurements.

EEVEE only supports the F82 fresnel type with internal code to convert
the the physical conductor inputs in to a colour format for F82,
which can lead to noticeable rendering differences with
some configurations.

Pull Request: https://projects.blender.org/blender/blender/pulls/114958

</details>

**Comment by ReinerBforartists** [comment]
Documenting 

![documenting](https://github.com/user-attachments/assets/9fae7d38-1707-492c-a52e-1ee62980a1ab)
