### ISSUE TITLE
Geometry Nodes - Output - New Warning node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4634]
![image](https://github.com/user-attachments/assets/88560b2f-1f87-4ff6-a087-a70d7b887de7)
New warning nodes for the Node tab of Geometry Node groups. This is a bit of a nuanced node. 

## Tasks
- Add to node add shelf in the Output category
- Document

<details>
<summary>Details</summary>

SHA-1: e8b81065bcd7f1999f685801f690a6434ad3b116

* Geometry Nodes: support custom warnings in node groups

This implements the `Warning` node that allows node groups to communicate
expectations about input values to the user.

By default, the `Warning` node is only evaluated if the node group that contains
it is evaluated in any way. This is better than always evaluating it, because
that could trigger lots of unnecessary evaluation in parts of the potentially
large node tree which should be ignored. In this basic mode, the output of the
node should not be connected to anything and it must not be in a zone.

For more fine-grained control for when the `Warning` node should be evaluated,
one can use the boolean output which is just a pass-through of the `Show` input.
If this output is used, the `Warning` node will only be evaluated if its output
is used. A simple way to use it is to control a Switch node with it that e.g.
"disables" a specific output when the inputs are invalid. In this case, the
`Warning` node may also be in a zone.

The node allows the user to choose between 3 severity levels: Error, Warning and
Info. Those are the same levels that we use internally. Currently, the error and
warning mode are pretty much the same, but that may change in the future.

Pull Request: https://projects.blender.org/blender/blender/pulls/125544

</details>

<details>
<summary>Moar Details</summary>

SHA-1: 1ee6a8fad540f2468df175b96befface55188b45

* Geometry Nodes: support customizing warning propagation

Previously, all errors, warnings and info messages were propagated from the node
that generates it to the top level node group. This is a good default, but may
not always be desirable. For example, someone may build a node group asset that
generates some warning that is irrelevant to the user to the asset. Now, the
asset author can selectively disable propagating warnings from that node.

Each node has a new `Warning Propagation` setting. It controls if warnings from
this node should be propagated to the parent group node. By default, everything
is propagated. One can also choose to propagate nothing, only errors or only
errors and warnings.

Note, this does not affect whether the warning is shown in the node itself, only
if the warning is propagated one level up!
Pull Request: https://projects.blender.org/blender/blender/pulls/126786

</details>

**Comment by ReinerBforartists** [comment]
Hm, i am unsure what to do here. It seems that the icon in question is supposed to appear at other nodes too. So no good idea to remove the original icon, it exists by purpose.

I would say we use two icons at this node. But a warning icon as the one in the menu, since it is the warning node.

![error](https://github.com/user-attachments/assets/34168615-fc14-4180-8a81-4205307d96be)

**Comment by ReinerBforartists** [comment]
Ah yes, depends of the type ...

![type](https://github.com/user-attachments/assets/4f5925ef-943f-4175-b04d-b9d290af66db)

**Comment by ReinerBforartists** [comment]
Documenting

![node](https://github.com/user-attachments/assets/2d2b58b1-b9d3-4ef3-8e72-12239a6b2fb4)

**Comment by ReinerBforartists** [comment]
Fixed
