### ISSUE TITLE
Icons - File Browser Folder icon could be improved

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4635]
![image](https://github.com/user-attachments/assets/288ed99c-b140-4a99-b8a3-53bbb24cff03)

Right now the fold icon has a line that goes through the other icons, which kinda doesn't work... The alignment needs love. 

These are the _LARGE icon types

<details>
<summary>Details</summary>

SHA-1: d9971d641483350562e3601796049dbb4c9a57f1

* UI: Detailed Large File & Folder Icons

Changes to the icons used for document and folder when in thumbnail
view in File Browser. A bit more detail, less chunky, more in tune
with OS versions. Better match for the recent increased fidelity of
the "type" icons that are shown in their centers.

Pull Request: https://projects.blender.org/blender/blender/pulls/126760

</details>

**Comment by ReinerBforartists** [comment]
It is also the position of the sub icons, i think we had moved them down already at one point. Seems that this gots lost. So much regressions ^^

![oldshot](https://github.com/user-attachments/assets/6c2108fa-bdbc-4068-aace-022f6e372a73)

**Comment by ReinerBforartists** [comment]
Yup, version 4.2.0 broke it

**Comment by ReinerBforartists** [comment]
Okay, subicons are now a bit bigger. So let's change the folder icon a bit ...

![bigger](https://github.com/user-attachments/assets/8c9e72ab-47a2-4b97-804a-1dd1a7a6f800)

**Comment by ReinerBforartists** [comment]
That's quite a rat tail here. We have quite a few icons with a folder symbol ...

**Comment by ReinerBforartists** [comment]
Hmm, i just change the small ones, not the big one. Where does this rascal hide? -.-

**Comment by ReinerBforartists** [comment]
Fixed

![fixed](https://github.com/user-attachments/assets/88cbb857-a246-4531-8d02-ad44cea601af)
