### ISSUE TITLE
Geometry Nodes - Utility - Math - New Hash Value node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4636]
![image](https://github.com/user-attachments/assets/0c8b08cf-4869-46a3-9dbe-56fb6a240984)
This node has a bad label at the moment, probably should fix that in the nod_static file. 

## Tasks
- Create and add a new icon, the # icon might work
- Fix the label
- Add this to the sidebar
- Document

<details>
<summary>Details</summary>
SHA-1: 294994e4b93e39053b9fd0933ca30e3ba72db116

* Geometry Nodes: new Hash Value node

This node hashes various types into an integer. Note that hashes
cannot generally used as unique identifiers because they are not
guaranteed to be unique. It can be used to generate somewhat
stable randomness though in cases where White Noise does not
offer enough flexibility.

It uses hash functions from BLI_noise.hh. These are also used in
the White Noise node.

Pull Request: https://projects.blender.org/blender/blender/pulls/110769

</details>

**Comment by ReinerBforartists** [comment]
Documenting
![fixed](https://github.com/user-attachments/assets/59409b8e-a616-4fa9-ac57-7c4eb5683b09)

**Comment by ReinerBforartists** [comment]
Fixed
