### ISSUE TITLE
Icons - Update new Blender icons monochrome icons to be DEF_ICON_COLOR the Bforartists way

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4638]
![image](https://github.com/user-attachments/assets/43586710-1353-4a00-9d8b-fbace4b20b79)

Right now we have a few new icons from Blender that have been slipping through, but not getting updated. They should be updated or replaced with existing icons. If they are repeat icons, maybe we could consolidate them to and remove the duplicates. 

<details>
<summary>Details</summary>

SHA-1: 4d4ad34f4ceadd9dca252344fbfc2259dd2618f7

* Anim: Action Slot icon

Add an icon for Action Slots. Design task: #123372

Pull Request: https://projects.blender.org/blender/blender/pulls/127102

</details>

**Comment by ReinerBforartists** [comment]
I would leave them as is. And tackle them in case they come in the way in the UI at a one by one base. 

Removing unused icons is no good idea at all. We've been there before. You never know what Blender does with these icons in the future ...

**Comment by ReinerBforartists** [comment]
This taks is not to solve from the icons end. You need to see the icons in context. And when you do that, then you quickly realize that most of these icons that looks like they are left over are in fact not. Just two examples in the screenshot.

I will close this task. Icons are just solveable at a one by one base and in context where you see it. When you find an icon that does not fit, then we can take action.

![nottosolve](https://github.com/user-attachments/assets/3aad0a47-d9d6-4989-a7e7-d1f5f81b9a3a)
