### ISSUE TITLE
Clean Up menus - Add Clear Recent Files operators for ALL and Missing to GUI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4639]
![bforartists_7Fm76xjZ1j](https://github.com/user-attachments/assets/d8b69a4b-2c45-4177-924f-1fa453f76640)

![bforartists_umzNo9iVLN](https://github.com/user-attachments/assets/b9310147-0d14-4b44-b285-3f425f82e83c)

Clear Recent All and Missing Files operators are no-where to find in the interface, only in a prompt. There is now two operators we can call, but it's hidden now from a top level. 

`bpy.ops.wm.clear_recent_files(remove='ALL')`
`bpy.ops.wm.clear_recent_files(remove='MISSING')`

You can clear recent files, but you will be prompted. The Bforartist way is usually skip the prompt, go direct. Expose to GUI (UV Unwrap, Clear Unused Data, etc). 

**Question:** Should we do this also with the clear recent list for files?

<details>
<summary>Details</summary>

SHA-1: 4317f50f5fba8c6fee052d18b7e901c57a90a92c

* UI: Clear Recent Cleanup Option

Adds an option to the "Clear Recent Files List" operator to allow it
to remove only items that are not found.  By default it clears "All
Items" but this can be changed to "Items Not Found".

Pull Request: https://projects.blender.org/blender/blender/pulls/127024

</details>

**Comment by ReinerBforartists** [comment]
I have no particular opinion here, sorry.

**Comment by ReinerBforartists** [comment]
The more i think about it the more i think we should leave as is. There is no benefit for the user in clearing the recent list.

**Comment by ReinerBforartists** [comment]
Leave it the Blender way. I will close the issue now.
