### ISSUE TITLE
Icon order - Change icon code from calculation back to hardcoded icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4641]
We had and have a handful icons that are calculated by the order in the ui_icons.cc file. As we got reminded with a handful issues shortly.

We should have a look if we can change these icons back to hardcoded icons instead of the calculation of the icon position +1 or -1

https://github.com/Bforartists/Bforartists/issues/4629

**Comment by ReinerBforartists** [comment]
Hm, harder than thought, I don't even have an idea how to catch it. Tried to go along the existing icon. But i cannot find the code part that determines the second icon then.

Shall we even keep this issue alive? Or close it as won't fix?

**Comment by Draise14** [comment]
I think trying to change how these icons draw deep down might be a fish too big to fry and maintain. I would just change the icon order - maybe keep those toggles out of the alphabetical list - and... leave it at that. 

We could introduce other bugs...

**Comment by ReinerBforartists** [comment]
The icon order is already fixed again. 

Okay, then let's close this issue as won't fix
