### ISSUE TITLE
File - External Reserouces - Unpack menu needs iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4642]
![bforartists_0eSvNBOfBA](https://github.com/user-attachments/assets/aa2ce1f7-e8db-4617-9e1a-1320c6a709ad)

![image](https://github.com/user-attachments/assets/8bcf74c1-4d32-402f-a5b1-f92bb10bf486)

This menu is.. a chore. Let's atleast add icons.

**Comment by ReinerBforartists** [comment]
The option checkbox burns in my eyes. We don't mix menus with options usually. But i don't see a better location for it. Ideas?

**Comment by Draise14** [comment]
User Preferences under save and load?

**Comment by ReinerBforartists** [comment]
Would be an idea, yes.

**Comment by ReinerBforartists** [comment]
I'll make it a task.

**Comment by ReinerBforartists** [comment]
Hmm, reminds me that we eagerly need an option panel in every editor in every view with every object type and mode

**Comment by ReinerBforartists** [comment]
Lemme look again.

**Comment by ReinerBforartists** [comment]
Real life in the way. Unassigning.

**Comment by ReinerBforartists** [comment]
Documenting.

![unpack](https://github.com/user-attachments/assets/9713096b-a1b4-43b2-a09b-1fde8c63cd71)

**Comment by ReinerBforartists** [comment]
Done
