### ISSUE TITLE
Object menu in 3D View - move modifiers sub menu to the modifiers panel in Properties editor.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4646]
Currently you have to go to the Object menu to the Modifiers sub menu to clear the modifers or to copy them over to other objects. This menu belongs to the modifiers panel. And the menu point Modifiers is a double then.

Task, move the Modifiers submenu over to the Modifiers tab

![problem](https://github.com/user-attachments/assets/fb59cb52-e9c7-462e-a582-ad06e557fbc3)

**Comment by ReinerBforartists** [comment]
Related 3D View - Object Header - Modifier Sub-menu cleanup #4254

**Comment by ReinerBforartists** [comment]
Documenting

![documenting](https://github.com/user-attachments/assets/edc88d62-e654-4c1a-a02a-ae731c25017c)

**Comment by Draise14** [comment]
Very good call.
