### ISSUE TITLE
Keymap - Add forward and back mouse buttons to File Browser

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4653]
Blender did this one, kinda agree here. Should we too? I know we should be minimal, but this is a one hand mouse no-brainer specially since it's built into other explorers. 

<details>
<summary>Details</summary>

SHA-1: 095aab986bf66a38b8217564db88dec632a1c80a

* Keymap: Map Back/Next mouse buttons in File Browser

Assign mouse button 4 and 5 to navigate back/next in the
File Browser. These button numbers are usually mapped to
this actions on browsers.

Additionally to the existing Alt/Option+Left/Right shortcuts.
Both in Blender default keymap and Industry Compatible.

Pull Request: https://projects.blender.org/blender/blender/pulls/127413

</details>

**Comment by Blenux** [comment]
Yes! File Managers and Web Browsers also have this, pretty standard thing these days.

**Comment by ReinerBforartists** [comment]
Common standard is good to have.

**Comment by ReinerBforartists** [comment]
Documentation is missing. Reopening.

**Comment by ReinerBforartists** [comment]
Done
