### ISSUE TITLE
Properties Editor - Grease Pencil - Grease pencil layer menu shows wrong icon for group

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4654]
![image](https://github.com/user-attachments/assets/fb9f4ed9-38ff-4219-801f-b96b6d724264)

Right now when you create a new "group" for grease pencil layers, you will find a new menu and icon type when right clicking a group, which is a little folder, but you can tag them with colors. 

# Tasks:
- Improve the group icon to work with colors
- Add icons to the other two new operators.
- Make operators in context menu show in specials menu also

**Comment by ReinerBforartists** [comment]
It shows the wrong icon doesn't it?

**Comment by ReinerBforartists** [comment]
Oh, and please just one task per issue. Separating the missing icons  ...

**Comment by ReinerBforartists** [comment]
Related Properties editor with greasepencil - Object Data Properties, Grease pencil layer menu, missing icons #4657

**Comment by ReinerBforartists** [comment]
>Make operators in context menu show in specials menu also

Please make a task

**Comment by ReinerBforartists** [comment]
Okay, back to this one issue. Blender shows already the wrong icon here. But i cannot really catch it -.-

Oh and we have yet another issue. The colors doesn't show in our menu.

![wrongicon](https://github.com/user-attachments/assets/0208b493-d41d-4e7d-8c75-49a9a222e2da)

**Comment by Draise14** [comment]
Collection icon for all? Keep it consistent with bone groups, view layer collections and such. 

Or.. make our group icons use a "folder" in it's iconography nomeclature?

**Comment by ReinerBforartists** [comment]
Then the collection icon everywhere. It is already fitting for colors, we use it in the outliner already. This would make this task obsolete then. 

Properties editor with greasepencil - Object Data Properties, Grease pencil layer menu, missing colors at the group icons #4659

**Comment by ReinerBforartists** [comment]
Let's go hunting again

**Comment by ReinerBforartists** [comment]
Gotcha. Documenting

![gotcha](https://github.com/user-attachments/assets/ada78d33-ebb1-4754-a391-9b2f5a1a1e7d)

**Comment by ReinerBforartists** [comment]
Fixed
