### ISSUE TITLE
Properties editor with greasepencil - Object Data Properties, Layers panel, masks subpanel. add icons to specials menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4661]
Missing icons.

![missing](https://github.com/user-attachments/assets/3760ecb1-d87d-4871-8ea6-93024f370343)

**Comment by ReinerBforartists** [comment]
Mission impossible. The content of this menu gets added dynamically, and is dependant of the chosen layer type. There is simply no place to add an icon. At least none that i know of. Any takers?

![dynamic](https://github.com/user-attachments/assets/42c4357b-1c6d-47ff-bbfc-af9c1f29a8a6)

**Comment by Blenux** [comment]
![image](https://github.com/user-attachments/assets/08a73207-211a-49ab-a108-a82fe7460083)

**Comment by Blenux** [comment]
>             found = True
>             props = layout.operator("grease_pencil.layer_mask_add", text=layer.name, icon="GREASEPENCIL")
>             props.name = layer.name
> 
>         if not found:
>             layout.label(text="No layers to add", icon="ERROR")

![image](https://github.com/user-attachments/assets/17d0a677-8f4c-47d7-8dfc-edd96296cebc)

**Comment by ReinerBforartists** [comment]
Ah, stupid me, i counted three different items, layers, colors and lines, and expected three different icons XD

**Comment by ReinerBforartists** [comment]
Okay, let's fix this then.

**Comment by ReinerBforartists** [comment]
Documenting
![fixed](https://github.com/user-attachments/assets/74a64714-08e9-490e-a2a0-b73fbac4d597)
