### ISSUE TITLE
3D View - Asset Shelves - Add the ability to see GN node groups too

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4673]
https://github.com/user-attachments/assets/5b20b7a4-a9a5-41b2-8bd7-276b4f423ef7

You can now drag and drop the new geometry node groups to items, should make them discoverable from the asset shelf too.

**Comment by ReinerBforartists** [comment]
How? What is the task here? What exactly do you mean with discoverable? Just mention it in the manual? Does a mockup exist?

**Comment by Draise14** [comment]
This is backend. 

Right now the object mode asset shelf supports collections, objects,materials,worlds. Geometry nodegroups could also be added, but maybe through prefix or tag filtering. 

So task is to add those filters in the backend.

**Comment by ReinerBforartists** [comment]
Thanks :)

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/68932073-f0a4-4dc9-a9a4-5d13577b2e42)

Now shows geometry nodes assets if they node group has a tag "Geometry Nodes"
Added the ability to detect if a node group has a tag "Compositor" "Geometry Nodes" or "Shader" instead of only the prefix. 
This unfortunately exposes some of the essentials assets into the shelves, as they don't have categories, but they could be improved later with our own modified version of essential assets?
