### ISSUE TITLE
Properties Editor Grease Pencil - Layers - Expose "move to top/bottom" as operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4675]
![image](https://github.com/user-attachments/assets/2a71a1a1-3c02-4887-9b11-95e7902005d2)

Right now you CAN move layers to the top or bottom in the API, but no buttons to do it. We could add it, maybe for Blender directly? 

![image](https://github.com/user-attachments/assets/18216d45-08f4-40ce-9d46-4bc5d8c0ec68)

https://docs.blender.org/api/4.3/bpy.types.GreasePencilv3Layers.html

**Comment by Blenux** [comment]
Location good?

![image](https://github.com/user-attachments/assets/8c0f070d-a58f-4f2a-a6dd-7428e31abe63)

**Comment by ReinerBforartists** [comment]
Looks good to me :)
