### ISSUE TITLE
3D View - Animation - Update Bake Grease Pencil Animation to GP3

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4678]
![image](https://github.com/user-attachments/assets/942699c6-55a5-48eb-b3b0-d940cab8b5be)

Update the bake objectr transforms to grease pencil to GP3. This is so messy, changing underlying API for the exact same thing...

<details>
<summary>Details</summary>

SHA-1: bd7c6208b7dc8b6d69b7cf110a4b7d2b28a80700

* GPv3: Add Bake Grease Pencil Animation operator

This commit ports over the legacy Grease Pencil "Bake Object Transform
to Grease Pencil" (`GPENCIL_OT_bake_grease_pencil_animation`) to GPv3.

It is accessed in the same location as the old operator, via the menu
path Object > Animation > Bake Object Transform to Grease Pencil

Pull Request: https://projects.blender.org/blender/blender/pulls/126581

</details>

**Comment by ReinerBforartists** [comment]
Update says me nothing, sorry. What exactly is the task here?

EDIT. The menu is the same than Blender, the operator is the same than in Blender. Nothing to do here. Closing.
