### ISSUE TITLE
Properties Editor - Armature - Edit and Pose mode - Bone - Viewport Display panels needs consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4679]
![image](https://github.com/user-attachments/assets/b61efbbf-8a7f-46c0-ab8e-d59e3120930f)
![bforartists_Z5EYlpatUK](https://github.com/user-attachments/assets/1e5bf93a-dec5-4e64-b3aa-c16840910947)

Right now the Properties Editor - Armature - Edit and Pose mode - Bone - Viewport Display panels are not the same, and you can hide and it will also toggle selectability, so it should be.. better implied and also make the layout similar in both panels. 

# Tasks
- Make layout similar
- Collapse disabled content

<details>
<summary>Details</summary>

SHA-1: b58f61a91ada6a9a84ee196256aebea46d842d23

* Fix: inconsistent bone selection after hiding or changing selectability

In blender, hidden items should not be selected.
Also, making an item unselectable should deselect it.

- in armature editmode (unlike posemode), hiding a bone through RNA
(unlike though the Outliner) would not deselect the bone
- in armature editmode (unlike posemode), hiding a bone through RNA
would not update the Outliner
- in armature posemode (unlike editmode), making a bone unselectable did
not deselect it (at least it did not update properly)

To resolve, add deselection to the RNA update functions and add needed
depsgraph tagging
Also add Bone selectability checkbox to Properties Editor (could be
split in a separate commit) -- came up in #127180.

Pull Request: https://projects.blender.org/blender/blender/pulls/127340

SHA-1: 52be15071f07d375879c19c7d9cc5e4bec2b1f90

* UI: dim the hide_select property whenever the bone is hidden

suggestion by @dr.sybren in !127340

</details>

**Comment by ReinerBforartists** [comment]
These panels provides different functionality, dependent of the mode. You cannot unify them.

**Comment by ReinerBforartists** [comment]
documenting
