### ISSUE TITLE
3D View - Header - Overly toggle on icon is wrong

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4681]
![bforartists_RMavfMOhZh](https://github.com/user-attachments/assets/a2c7f277-14d8-4d69-a76b-b422fce845c1)

Hidden overlays icon is is the wrong icon, needs a fix. 

Related:
#4629  #4628 #4631

**Comment by ReinerBforartists** [comment]
Icon order again ...

**Comment by ReinerBforartists** [comment]
![fixed](https://github.com/user-attachments/assets/1885f011-7989-40ed-8b89-a9b78d0c810e)
