### ISSUE TITLE
Geometry Nodes - New Integer Math node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4683]
![bforartists_JJp3dK0wan](https://github.com/user-attachments/assets/750ef8ba-42bc-45bd-bfaf-aa95762357dc)

Community likes this one, a new integer math node, more precise. 

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/72e5db74-c71e-4f71-857a-d44b213a904d)

</details>

**Comment by ReinerBforartists** [comment]
Hmm, we have a integer icon already. But also a integer node. So we need a new icon here ...
![intmath](https://github.com/user-attachments/assets/021a8cd7-19b5-4070-b195-614ba0d51388)

**Comment by ReinerBforartists** [comment]
Documenting
