### ISSUE TITLE
3D View - Grease Pencil - Edit mode - New (old) reset UV operator need iconography

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4686]
![image](https://github.com/user-attachments/assets/b476264f-c675-44c3-8514-1189bf9ce149)

New old operator, legacy icon and documentation to be done.

**Comment by ReinerBforartists** [comment]
Same applies to a mesh object.

**Comment by ReinerBforartists** [comment]
Ah wait, that's another issue. Will open it.

**Comment by ReinerBforartists** [comment]
Documenting
