### ISSUE TITLE
Hotkeys - Add wheel scroll to User Interface for UI Lists

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4696]
# To be added
![image](https://github.com/user-attachments/assets/20d488d5-8b00-483f-af4d-a2eadf2cdda4)

# Blender
![image](https://github.com/user-attachments/assets/4599f3c6-0374-4c7b-ade2-2560715ad389)

This was added to Blender, we should have it too, or else we can't scroll in the new UI Lists with mouse.

**Comment by ReinerBforartists** [comment]
Documenting
