### ISSUE TITLE
Secondary Window label - Change to "Bforartists" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4697]
![bforartists_AHiYl5KEQM](https://github.com/user-attachments/assets/b96bf253-87de-41b8-bc7f-8c002317dd6b)

Right now secondary floating windows has the Blender label, shoooould be a quick fix. This one slipped through with a merge conflict.

**Comment by Blenux** [comment]
Which secondary floating window exactly? fresh compile on windows (on laptop) I can't reproduce.

**Comment by Draise14** [comment]
Click on a corner of any editor, hold SHIFT then drag LMB, then the window will "pop-out" to a secondary floating window.

**Comment by ReinerBforartists** [comment]
Same here. Can this be a Win 11 problem? I still run Win 10 ...

**Comment by ReinerBforartists** [comment]
Possible cause here. source\blender\windowmanager\intern\wm_window.cc, line 503

I just cannot test, since i cannot reproduce ^^

![possiblecause](https://github.com/user-attachments/assets/2c7fe359-4755-4d72-a951-475f331ac4d1)

**Comment by Blenux** [comment]
My laptop has Windows 11, not sure why can't reproduce.

**Comment by ReinerBforartists** [comment]
Then we need more information.

**Comment by ReinerBforartists** [comment]
@Draise14 , is this still an issue? We cannot reproduce ...

**Comment by Draise14** [comment]
Will test today. And apply the suggestion too. Might be a  multi monitor thing.

**Comment by ReinerBforartists** [comment]
I have two monitors, and i cannot reproduce so far.

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/301e7eec-2b99-4059-ad71-5a26209b02dd)

Yep, still there. I guess it happens when you have another "main window" with multiple docked editors.

**Comment by ReinerBforartists** [comment]
Try to change the code above. It should fix it.

**Comment by ReinerBforartists** [comment]
Please test
