### ISSUE TITLE
Edit Mode, 3D view + UV Editor UV menu, last operators Unwrap , align content left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4700]
The uv mapping methods in the UV menu in both, 3D view and UV Editor have their adjust last operators middle aligned. Align left.

![lastoperator](https://github.com/user-attachments/assets/45a652dc-40d9-4a2e-94cc-819b2d024507)

**Comment by ReinerBforartists** [comment]
Looks good :)

**Comment by Blenux** [comment]
how about some separators lines ?

![image](https://github.com/user-attachments/assets/4bc05885-d43f-444d-b6d2-fe7bc65dfda0)

**Comment by ReinerBforartists** [comment]
Hmm, i don't think that they are necessary here, but do as you wish :)

**Comment by Blenux** [comment]
Ok cools, I'll leave out for now, something we can add later.
