### ISSUE TITLE
3D view + UV Editor , UV menu , add icon to new unwrap method Minimum stretch

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4701]
New operator needs new icon.

![addicon](https://github.com/user-attachments/assets/6941cea2-8e77-4240-b01c-a6bde662ff8e)

**Comment by Draise14** [comment]
Duplicate
https://github.com/Bforartists/Bforartists/issues/4682

**Comment by ReinerBforartists** [comment]
No duplicate. The parent task is simply more than one issue. And especially documentatiowise too much to chew at once. Always make the tasks as small as possible. 

Documenting.

![documenting](https://github.com/user-attachments/assets/357c95fe-16bf-4ab5-94a3-96ee381e53a4)
