### ISSUE TITLE
3D view + toolbar , add unwrap method Minium Stretch to toolbar and toolshelf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4705]
New unwrap method needs to be in toolbar and toolshelf too.

![minimumstretch](https://github.com/user-attachments/assets/86ad93c4-f463-402b-817d-d5201526cc4f)

**Comment by Draise14** [comment]
Related to #4682

**Comment by ReinerBforartists** [comment]
Documenting

![fixed](https://github.com/user-attachments/assets/2dee30fd-1336-49b7-a90f-501598f0b9a1)
