### ISSUE TITLE
Topbar - Meshedit group - Swap icons for Mark and Clear sharp seam

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4706]
![imagen](https://github.com/user-attachments/assets/f37ec504-7dc5-409f-8305-63fea748375f)

Seems these icons are inversed. 

![imagen](https://github.com/user-attachments/assets/5e45a6b5-e885-41a2-ae2e-a1298e6bc484)

**Comment by ReinerBforartists** [comment]
Not necessarily. Red is marked, Green is unmarked, it is cleared again.
