### ISSUE TITLE
Extension - Colorista - Enabling crashes application

### ISSUE THREAD

**Issue by PsychoNerd91** [Bforartists/Bforartists#4730]
I've updated to bfa 4.2.2. When trying to enable to Colorista extension it will crash and when opened again the setting will be unchecked. Tried redownloading to try again, but still crashes.

Running Linux Mint 22, Geforce RTX3070.

**Comment by Blenux** [comment]
Yep can confirm, seems to be a issue in the ColoristaGizmos class for reason and the bl_idname

**Comment by ReinerBforartists** [comment]
Friends, remember that we are always one version ahead. 4.2.2 is based at Blender 4.3 ...

**Comment by Blenux** [comment]
the addon also works on Blender 4.4 alpha

**Comment by Blenux** [comment]
Working this out still, this error comes up when crashing, code is same to blender though.

`BLI_assert failed: source/blender/makesrna/intern/rna_wm_gizmo.cc:227, rna_Gizmo_bl_idname_set(), at '0'
  setting the bl_idname on a non-builtin operator
`

**Comment by Blenux** [comment]
@PsychoNerd91 I found the issue, in the def setup of the ColoristaGizmos class, where you have gz.icon = "AREA_SWAP", if the icon name is different and/or can't be found the addon crashes both Blender and Bforartists, which our AREA_SWAP has a different name.

Bforartists area swap icon name  = "AREA_SWAP"
Bforartists area swap icon name = "SWAPS_AREA"

![image](https://github.com/user-attachments/assets/6cb75b6a-2ab6-44ff-b205-cb3227348c9c)
Vid

https://github.com/user-attachments/assets/62d2b365-f8d4-4ab8-8b7f-2079a985f5b3

**Comment by ReinerBforartists** [comment]
Curious one. Then we should change our icon ...

**Comment by Blenux** [comment]
Yep should be same so issues like this dont come up constantly

**Comment by Blenux** [comment]
Ok so confused, further checking it's actually the line 115 in the gizmo.py and combination with the icon name of AREA_SWAP seems to be causing the issue too.

gz.bl_idname = "ColoristaButton"

**Comment by Draise14** [comment]
Ah, good catch.

**Comment by Draise14** [comment]
Ok, the icon swap is merged to master, guess it needs testing now.

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/232f5ae4-072d-4b0a-8d3a-6226ebeaa099)
![image](https://github.com/user-attachments/assets/013e9800-9996-4096-b4d5-27489a73a6b0)

After installing and enabling, it still crashes, but when reloading Bforaritsts and enabling the extensions, it doesn't crash anymore. But.. it still is broken.

I suggest this may be an addon issue over a Bfoartists issue?

**Comment by Blenux** [comment]
Yeah same happens in Blender, thinking more of a addon issue.

**Comment by Draise14** [comment]
I guess if this is happening with Blender now, we have done what we can.. it's now an addon issue and should be reported to the addon developer.
