### ISSUE TITLE
3D View - Edit Mode-  Select by trait - New Select by Pole Count operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4738]
![image](https://github.com/user-attachments/assets/d0f781ee-05f2-42b9-9fe3-19ba00a199e1)

Add icon, document. 

<details>
<summary>Details</summary>

SHA-1: 51eb5e2803c97eafa87d835130ec5d10896f9f44

* Edit Mesh: add an operator to select by pole count

Adds a new "Select by Trait" option to select all 3-poles, 5-poles, etc.
Given the impacts of 3 & 5-poles in topology, operator default is to
select all poles which do not have 4 edges to allow easy inspection.

Select connected vertices/edges/faces based on the mode.

Ref: !128493

</details>

**Comment by ReinerBforartists** [comment]
Documenting
![polecount](https://github.com/user-attachments/assets/7e4ed845-0180-417f-a7d7-f6fb11f99c8a)

**Comment by ReinerBforartists** [comment]
done
