### ISSUE TITLE
Grease Pencil - Edit mode - Stroke - New Join operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4739]
![image](https://github.com/user-attachments/assets/a1733df2-b080-4d7b-be90-9617b52988e1)

Join opreators are back for GP. Might already be documented. 

# Task: 
Add icons, document, and make sure it's consistent in the context menu too. 

<details>
<summary>Details</summary>

SHA-1: dc652aeedb89b71c95175f29e181336bd3fd99bf

* Fix: UI: Restore GP3 Join operator in menu

This was accidentally removed in https://projects.blender.org/blender/blender/commit/d70b10dcd4

</details>

**Comment by ReinerBforartists** [comment]
This is a new implementation.

**Comment by ReinerBforartists** [comment]
Documenting

![join](https://github.com/user-attachments/assets/bdac949c-f2ee-4da5-b284-401f5b898844)

**Comment by ReinerBforartists** [comment]
Fixed
