### ISSUE TITLE
Greae Pencil - Edit Mode - Remove redundant Seperate menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4740]
![image](https://github.com/user-attachments/assets/e8182d49-c694-4c22-84d2-90f8e27bf4a3)

Hide this menu from the interface, but keep it there if blender hotkeys call this menu. 

We exposed the separate operators up a level.

**Comment by ReinerBforartists** [comment]
Just one task per issue please. We are while at it all the time  ^^

**Comment by Draise14** [comment]
Ah, thought it the same task. 

So one per menu?

**Comment by Draise14** [comment]
Now only for the redundant separate menu.

**Comment by ReinerBforartists** [comment]
Ah, damn. Solved it in another task now. My fault. Either way, fixed :)

Edit mode - Grease pencil menu - remove double menu entries #4753
