### ISSUE TITLE
Grease Pencil - Edit Mode - New Duplicate (move) operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4741]
![image](https://github.com/user-attachments/assets/48b091f9-2e8e-46c2-bb76-1e57f2c8b980)

Add icon (exists) and document.

**Comment by ReinerBforartists** [comment]
Documenting

![DOCUMENTING](https://github.com/user-attachments/assets/796ff03a-1ccc-496f-be80-a687b1e47415)

**Comment by ReinerBforartists** [comment]
Not documenting. We have a double entry here. Show Hide. Will document with this fix.
