### ISSUE TITLE
Grease Pencil - Edit Mode - Select Grouped needs updating to GP3

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4742]
![image](https://github.com/user-attachments/assets/b888a97e-b362-49b7-b589-749dcbf3caf7)

![image](https://github.com/user-attachments/assets/4c0aebe3-465b-4f02-a654-062cd2524094)

Gotta update to GP3

**Comment by ReinerBforartists** [comment]
When it throws an error then it is a bug ...

**Comment by ReinerBforartists** [comment]
Select grouped is no more. Removing ...

![grouped](https://github.com/user-attachments/assets/50a0f26a-6859-4a71-b384-0df5e14cdd86)

**Comment by ReinerBforartists** [comment]
Oops, committed to the wrong issue. Here is the fix: 

https://github.com/Bforartists/Bforartists/commit/2a115fb55a725c6c9bfdaf983499d8319fa9fafc

**Comment by ReinerBforartists** [comment]
Documenting.

**Comment by ReinerBforartists** [comment]
Done
