### ISSUE TITLE
Grease Pencil , Drawmode, cleanup options

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4758]
Blender has the options for the grease pencil at the right side. Which is imo better since options are at the right side in our editors also. There is one option missing compared to Blender. And the multi-frame editing is wrong in this mode. Remove it.

One operation: cleanup and rearrange.

Another task is to recolor the icon for the new option. Will make a task for it.

![refactorneeded](https://github.com/user-attachments/assets/6f64671e-88fc-405d-9d19-d324e80a41c3)

**Comment by ReinerBforartists** [comment]
Ah wait, multiframe editing belongs to draw mode.

**Comment by ReinerBforartists** [comment]
Another slipped through merge change ...

![slippedthrough](https://github.com/user-attachments/assets/9ebadbdf-3df8-4e28-9de6-8d598fe7c75c)

**Comment by ReinerBforartists** [comment]
Documenting
![rearranged](https://github.com/user-attachments/assets/e16e9993-6298-44d6-91ff-5cd95587a575)

**Comment by ReinerBforartists** [comment]
Documented

**Comment by Draise14** [comment]
Yeah, do meld compare all the time. 
¨[

**Comment by ReinerBforartists** [comment]
Great. Then it's that my blender version is not exact merge date :)
