### ISSUE TITLE
Grease Pencil Layer panel - missing icons in Specials menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4762]
Missing icons for merge are missing.

![missing](https://github.com/user-attachments/assets/3f3d8b9a-9fa4-4539-a1ba-b3a7d2b2a553)

**Comment by ReinerBforartists** [comment]
Fixed. Documentation happens with another task already.

**Comment by Draise14** [comment]
Ah, these are new.

**Comment by ReinerBforartists** [comment]
And already fixed :)
