### ISSUE TITLE
Dopesheet - Action Editor mode - Hide "Show Selected" since it is now useless

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4767]
![image](https://github.com/user-attachments/assets/5f8634ff-eaae-4acd-b86f-7d790d1f7214)

Right now when you have a "Show Slot", the "Show Selected" doesn't actually do anything now. It should have a conditional to hide when it does nothing.

https://github.com/user-attachments/assets/6a5284ab-3c47-4691-84ac-8ff2cf396c5f

# Task
- Make the "Show Selected" toggle hide in Action Editor mode of the Dopesheet

<details>
<summary>Details</summary>

SHA-1: 43d7558e5b00a14b39e473aec345e5080a5e76d2

* Anim: Remove 'Slotted Actions' experimental flag

This commit takes the 'Slotted Actions' out of the experimental phase.
As a result:

- All newly created Actions will be slotted Actions.
- Legacy Actions loaded from disk will be versioned to slotted Actions.
- The new Python API for slots, layers, strips, and channel bags is
  available.
- The legacy Python API for accessing F-Curves and Action Groups is
  still available, and will operate on the F-Curves/Groups for the first
  slot only.
- Creating an Action by keying (via the UI, operators, or the
  `rna_struct.keyframe_insert` function) will try and share Actions
  between related data-blocks. See !126655 for more info about this.
- Assigning an Action to a data-block will auto-assign a suitable Action
  Slot. The logic for this is described below. However, There are cases
  where this does _not_ automatically assign a slot, and thus the Action
  will effectively _not_ animate the data-block. Effort has been spent
  to make Action selection work both reliably for Blender users as well
  as keep the behaviour the same for Python scripts. Where these two
  goals did not converge, reliability and understandability for users
  was prioritised.

Auto-selection of the Action Slot upon assigning the Action works as
follows. The first rule to find a slot wins.

1. The data-block remembers the slot name that was last assigned. If the
    newly assigned Action has a slot with that name, it is chosen.
2. If the Action has a slot with the same name as the data-block, it is
    chosen.
3. If the Action has only one slot, and it has never been assigned to
    anything, it is chosen.
4. If the Action is assigned to an NLA strip or an Action constraint,
    and the Action has a single slot, and that slot has a suitable ID
    type, it is chosen.

This last step is what I was referring to with "Where these two goals
did not converge, reliability and understandability for users was
prioritised." For regular Action assignments (like via the Action
selectors in the Properties editor) this rule doesn't apply, even though
with legacy Actions the final state ("it is animated by this Action")
differs from the final state with slotted Actions ("it has no slot so is
not animated"). This is done to support the following workflow:

- Create an Action by animating Cube.
- In order to animate Suzanne with that same Action, assign the Action
  to Suzanne.
- Start keying Suzanne. This auto-creates and auto-assigns a new slot
  for Suzanne.

If rule 4. above would apply in this case, the 2nd step would
automatically select the Cube slot for Suzanne as well, which would
immediately overwrite Suzanne's properties with the Cube animation.

Technically, this commit:
- removes the `WITH_ANIM_BAKLAVA` build flag,
- removes the `use_animation_baklava` experimental flag in preferences,
- updates the code to properly deal with the fact that empty Actions are
  now always considered slotted/layered Actions (instead of that relying
  on the user preference).

Note that 'slotted Actions' and 'layered Actions' are the exact same
thing, just focusing on different aspects (slot & layers) of the new
data model.

The "Baklava phase 1" assumptions are still asserted. This means that:
- an Action can have zero or one layer,
- that layer can have zero or one strip,
- that strip must be of type 'keyframe' and be infinite with zero
  offset.

The code to handle legacy Actions is NOT removed in this commit. It will
be removed later. For now it's likely better to keep it around as
reference to the old behaviour in order to aid in some inevitable
bugfixing.

Ref: #120406

</details>

**Comment by ReinerBforartists** [comment]
What the heck is a slottet action? Moar buzzword confusion for the user ...

**Comment by Draise14** [comment]
Yeah, this is early days, but basically... object channel in a mutually assigned action clip between objects.

**Comment by ReinerBforartists** [comment]
Hm, the show hidden doesn't do anything in normal mode neither. Did it lose its purpose at its way?

In general find this whole new action thing highly confusing. And am lost to fix and document what i don't even understand.

**Comment by ReinerBforartists** [comment]
I would wait until Blender removes this functionality. Currently it is still in the Blender UI. And who knows ...

**Comment by ReinerBforartists** [comment]
I will close this task. It's up to Blender to remove this prop if not longer needed.
