### ISSUE TITLE
3D View - Grease Pencil - Vertex Paint mode - Update color swatches in sidebar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4772]
![image](https://github.com/user-attachments/assets/215aa66f-2417-4ccc-8460-234bb66fddfa)

The color swatch swap in the brush settings for vertex paint is the legacy one still, not the new one - and the two color swatches and color swap could and should be exposed to the header in a consistent way. 

# Task
- Fix color swap in toolshelf to be the new operator

**Comment by ReinerBforartists** [comment]
We have now three tasks for the basically same job. Clean up the color swap mess. It's just not clear which task for what. At least not for me. So who ever claims this task should solve all three at once.

Related: 

3D View - Grease Pencil - Vertex Paint mode - Split color selector in header #4774
3D View - Grease Pencil - Vertex Paint mode - Expose color swap to header #4773

**Comment by ReinerBforartists** [comment]
Closing since the main task is merged.
