### ISSUE TITLE
3D View - Grease Pencil - Vertex Paint mode - Expose color swap to header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4773]
![image](https://github.com/user-attachments/assets/215aa66f-2417-4ccc-8460-234bb66fddfa)

The color swatch swap in the brush settings for vertex paint could and should be exposed to the header in a consistent way. 

# Task
- Expose color swap in header

**Comment by ReinerBforartists** [comment]
Closing since the main task is merged.
