### ISSUE TITLE
Grease Pencil Trim Tool

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4776]
We have the trim tool in the stroke menu in edit mode.

It is permanently greyed out. There is no hint how to get it to work. The manual is not helpful neither. No information how to use it or how to activate it.

The original task was to hide it when greyed out. But first we need to find out how to activate it. And then document it. A hint in the tooltip would be nice too. And then remains the question if we want to hide it at all. Since then no user will be able to even discover it.

Related: 3D View - Grease Pencil - Edit Mode - Make operators show in the correct context and header menus #4551

![trrim](https://github.com/user-attachments/assets/50286602-c013-4f7a-9729-7ce758909fdb)
![trim](https://github.com/user-attachments/assets/12deeae3-d947-41f1-85af-b9ab39924034)

**Comment by Draise14** [comment]
To use it, you gotta be in stroke section mode, sletect a stroke, then Trim. It's the third selector the top left.

**Comment by ReinerBforartists** [comment]
If it would be this easy ^^
This operator is greyed out in all modes :)

![point](https://github.com/user-attachments/assets/87cf7804-e90b-409b-b8f5-6169080e2e67)
![stroke](https://github.com/user-attachments/assets/f0735dce-1fb8-47da-9d69-6d47af20a39d)
![segmentmode](https://github.com/user-attachments/assets/d0b71c3b-0ce7-4fae-a3fa-88cd2176990e)

**Comment by ReinerBforartists** [comment]
Blender issue. Works in 4.3, fails in newest build.

Made it an issue: https://projects.blender.org/blender/blender/issues/129784

**Comment by ReinerBforartists** [comment]
Okay, the trim tool was never meant to be used in edit mode. Blender devs have removed the operator now from the menu. And so do we.

**Comment by ReinerBforartists** [comment]
Documenting

**Comment by ReinerBforartists** [comment]
Fixed
