### ISSUE TITLE
Dopesheet - Action Editor mode - Improve Action Slots icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4778]
![bforartists_kUuWsI30Nt](https://github.com/user-attachments/assets/9c541be3-8af3-4335-9752-f1b3c2d6abbb)

Action slots has landed out of experimental, but it comes with an ugly icon that doesn't sit well. 

A slot is an animation track per object inside the action clip. So.. we can base this icon off the action clip icon.

**Comment by ReinerBforartists** [comment]
I don't think it's bad at all. Just a bit ... monochhrome ^^

**Comment by ReinerBforartists** [comment]
Fixed.
I will make a task for the documentation part. That's too big here. I have just added an icon ...

![color](https://github.com/user-attachments/assets/547c1571-0070-441f-85f4-92dff7a6ef2d)
