### ISSUE TITLE
Outliner - Colored collection rows

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4779]
https://github.com/user-attachments/assets/b9674cfa-3681-41d7-8076-a3c2ec40ab31

![bforartists_a2tBfJxDQZ](https://github.com/user-attachments/assets/029fe542-81e7-4eb9-b04b-50db50961851)

For user experience, and out of conversation with users - this seems to be a hot requested feature. And Pablo Vasquez made a prototype. I have since adopted the diff and made an experiment.

I am debating making a toggle for it, and I am now trying to make a design for nested collection to not draw the full width.

**Comment by Draise14** [comment]
https://github.com/user-attachments/assets/aaa858c3-477b-495e-8e9c-bf3f8640b4df


Here is the more final look. Ready for feedback!

**Comment by ReinerBforartists** [comment]
Hmm. Looks decent enough now.

Just curious, isn't this a feature that ist to expect to land in Blender anyways? So why not wait until it does, and then fine tune?

**Comment by Draise14** [comment]
Proposal was vetoed, thus Pablo Vasquez shared it with us directly on Xwitter. Development branch for it got nuked. 

It won't go to Blender.

**Comment by ReinerBforartists** [comment]
Ah, now it makes sense :D

**Comment by Draise14** [comment]
Have tested it all week.. Now I can't go back to the bland outliner without colors. This simply is a win. 

Should I try build in a user prop to toggle colors? Or shall we merge to main? Major 4.3 update.

**Comment by ReinerBforartists** [comment]
Why not both ? ^^

**Comment by Draise14** [comment]
Yeah, seems making a property to implement in C then implement in python is not a simple thing - since this is C change, though aggregate so uninvasive.

**Comment by Draise14** [comment]
I'll merge, then make a new task to make the toggle.

**Comment by ReinerBforartists** [comment]
Yes, that's nothing trivial, unfortunately.

**Comment by Blenux** [comment]
Yeah I like and a toggle is always good for people that don't.

**Comment by Draise14** [comment]
I'll commit this and merge to master, then make a new task for the user opt-out. I am pressed tight for time and will travel Saturday 2nd to the Blendiberia conference, then I present Bforartists there in Spanish, will be back to work on the 14th.

**Comment by Blenux** [comment]
If you make the opt out task, I could do that one.
