### ISSUE TITLE
Theming issue with new action editor functionality in dope sheet in the channels

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4781]
Black letters at dark grey background is hard to read ...

![theming](https://github.com/user-attachments/assets/434336f1-5d81-4adb-8d14-da5f9bbed19f)

**Comment by ReinerBforartists** [comment]
Hm. Not themeable. It uses the bg color of the panel.

**Comment by Blenux** [comment]
Which one did we wanna change here, text our the background?

**Comment by ReinerBforartists** [comment]
Background i guess. Text color changes with selecting or deselecting it.

**Comment by Blenux** [comment]
How about this, changed some alpha values just a tad on the following,

Window Background
Source List
 

![image](https://github.com/user-attachments/assets/4e27bde1-1c09-4b06-b4a5-f96c278908d5)

**Comment by ReinerBforartists** [comment]
Not so happy with it, the sidebar becomes too bright. Plus all the bright text is now worse to read. And that's the majority. It's the reason why i have chosen a darker color. Yes, dark letters are better to read this way. But the better method would be if we could theme this little spot instead of destroying the color balance of the theme. Still a bit baffled that it is not part of theming.

Let's ask @Draise14 here.

**Comment by ReinerBforartists** [comment]
Comparing the timeline with the dope sheet in your shot shows me that this is more likely a bug. In the timeline it shows the correct color. In the dope sheet not. So i think it is worth a bug report instead of changing our theme.

**Comment by ReinerBforartists** [comment]
Let's report it.

**Comment by ReinerBforartists** [comment]
Ah, closed as no bug. I should've known it. It's UI UX design ...

**Comment by ReinerBforartists** [comment]
Closing as known issue. This is behind our skills and manpower, and is not our task.
