### ISSUE TITLE
Default Library - Geometry Nodes - Add new Grease Pencil utilities

### ISSUE THREAD

**Issue by Quackarooni** [Bforartists/Bforartists#4785]
![image](https://github.com/user-attachments/assets/9b1b28d5-81a9-4038-b91e-853915de34cc)
Add Grease Pencil related helper nodegroups to BFA's Default Library.

## Nodegroups
- **Set Stroke Softness** : Sets softness to the specified value, only applies to strokes.
- **Set Grease Pencil Opacity** - Sets opacity to the specified value. *(Can be toggled between Stroke/Fill modes.)*
- **Set Grease Pencil Color** - Sets color to the specified value. *(Can be toggled between Stroke/Fill modes.)*
- **Stroke Info** - Provides convenient access to stroke-related attributes.
- **Fill Info** - Provides convenient access to fill-related attributes.
- **GP Layer Size** - Returns the point & spline count of each layer as a field.
- **GP Delete Empty Layers** - Removes any grease pencil layer that doesn't contain any points.

**Comment by Quackarooni** [comment]
I've decided to shelve the **GP Fill to Mesh** nodegroup and leave it for a future update.

Getting good topo that avoids artefacting is a harder problem than I initially expected.
And I just don't have the time for that rn.

![image](https://github.com/user-attachments/assets/2c58d59e-571a-47b4-92f0-8b974b8a9b26)

**Comment by Draise14** [comment]
Yeah, the curve fill to mesh solutions out there are novel and tricky, might be good to take a look at what's out there and see how they are doing it - in theory a curve spline fill group should work in a similar way.

**Comment by Draise14** [comment]
Will review thumbnails later today after some work

**Comment by Draise14** [comment]
Had a talk with Daniel Lara, the investor and creator of Pepeland and the Clay Motion grease pencil fill tools coming out soon, in person in the Blendiberia in Spain. He shared his secret, resample the GP, create a curve sphere and remap it to eh positions of the GP by index - then work the topology from there, I am not sure how he's tessellating it, but might be another trick by Higsas that does have a tessallation system.

**Comment by Draise14** [comment]
Assigning you back for the bounty. Doing thumbnails and building in some notes and tooltips.

**Comment by Draise14** [comment]
![bforartists_uTEs0gZPYg](https://github.com/user-attachments/assets/e81dd5cf-65c0-456a-bbd9-59a96a2d9c73)
