### ISSUE TITLE
Show Toolshelf Tab property C code, change NULL to nullptr

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4789]
An overlooked issue. For the Toolshelf Tab property C code we need to change the NULL pointer to nullptr. NULL is the old C way. In C++ you use nullptr. This can make us trouble ...

source\blender\makesrna\intern\rna_space.cc

![null](https://github.com/user-attachments/assets/42f03865-aa34-4b48-bcf6-3fc42c20be76)

**Comment by ReinerBforartists** [comment]
Related: Outliner - Add a user toggle to turn collection color block highlights on or off #4788

**Comment by ReinerBforartists** [comment]
There is one more NULL that should be nullptr. Task still fits, same file, same problem.

![morenull](https://github.com/user-attachments/assets/dfcf334e-e1c0-41cf-a653-c489c18e5ba9)

**Comment by ReinerBforartists** [comment]
As a rule of thumb, when i spot such a problem, then i check the whole file for it ...

**Comment by Blenux** [comment]
ah I see, I searched for NULL with a space instead of NULL, bah
