### ISSUE TITLE
Brushes - update Brush asset panel

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4792]
The brush assets panel not longer has any further functionality. All that is left is that you can rename it.

We still have a delete and a save as button here, which we need to remove.

![383068635-b0d253a5-b3b9-4a32-96f9-72f12666a9cb](https://github.com/user-attachments/assets/99f2b184-b77e-4935-a88c-72b60948f1b4)
![383068651-89eaae71-5433-41d5-8e94-876c1af5fffd](https://github.com/user-attachments/assets/d66e6345-de96-49b0-a556-2e0e204c0039)

the revert button is also obsolete. And the menu is also missing entries.

This affects all brushes in all modes with all objects.

![383069638-999691f3-90ef-419d-8b99-06b4fa532e46](https://github.com/user-attachments/assets/f010e81b-6702-44ac-9b34-436c9be37c14)

**Comment by ReinerBforartists** [comment]
We could split it into two tasks. But we can also simply make two commits instead. One for the menu, one for the rest.

**Comment by ReinerBforartists** [comment]
Here: https://github.com/Bforartists/Bforartists/pull/4787

**Comment by ReinerBforartists** [comment]
Now let's check if we have anything outliner related in the prefs.

**Comment by Draise14** [comment]
Warning. I exposed these to top for consistency and are intentional. 

They are used when an asset becomes a user asset. They are not broken.

**Comment by Draise14** [comment]
Also was implemented for user discover ability after control and test group couldn't figure it out.

**Comment by Draise14** [comment]
These enable also when an asset is a user asset, not built in.

**Comment by ReinerBforartists** [comment]
Remains the menu ...

**Comment by ReinerBforartists** [comment]
Hm. delete is then of course a double. And we need to change the icon. Paste is not new.

**Comment by ReinerBforartists** [comment]
I have already understood that this change is by purpose. But i still see work to do here.

>This task will need to be either more specific or closed.

- Revert the icon. It is wrong. This wrong icon leads to confusion. Everywhere else we have the + icon, since this is what happens here. We add a new asset. If we duplicate or copy over does not play any role.
- The menu misses at least one entry. Save changes to asset for example.

This is why i have reopened it.

**Comment by Draise14** [comment]
Save changes to asset is exposed to top level when there are changes to be saved. It's there already on a top level. 

The duplicate icon duplicates the brush, since it's not a new brush, but a duplicate. 

But I opened another task where you updated the tooltip instead of clarifying when things are duplicated or when you create new blank data.

**Comment by ReinerBforartists** [comment]
Tooltip update has to happen here now, since i went through the other task already, saw that the whole prop has changed and the add button was gone. But no biggie.

Lemme do this here now.

**Comment by ReinerBforartists** [comment]
This is what my eagle eye spotted: The save button is not always present it seems.

![missing](https://github.com/user-attachments/assets/d223d8c4-b9c1-4218-bcb1-fbf35ac6df0d)

**Comment by Draise14** [comment]
You can only have as asset after you duplicate a brush. You can't save an essential brush as asset.

**Comment by ReinerBforartists** [comment]
>The duplicate icon duplicates the brush, since it's not a new brush, but a duplicate.

This is the point where i heavily disagree and want to pull one of my rare vetos if you don't mind. It is a new brush. A duplicate, no doubt, but a new one.

The user adds a new brush with this button. What happens under the hood is of no interest for the user. It's a trap that imho also Blender developers falls into regularly. They explain detailed what happens under the hood, but forgets what the main functionality is.

We had for many years the add icon in this place. Since this is what happens. You add a new brush. You add a new material and so on. Now ypu changed the icon, and the user overlooks the button since he thinks it is gone. Happened to me here, else i would have udpated the tooltip already in the other task.

So i will revert the icon.

**Comment by ReinerBforartists** [comment]
> You can only have as asset after you duplicate a brush. You can't save an essential brush as asset.

So you mean the save assets button is missing by purpose? But in Blender it is active.

**Comment by ReinerBforartists** [comment]
This is a copy, and still no save button

![copy](https://github.com/user-attachments/assets/f1633d49-e9a7-4d78-9c38-45ee01b81089)

**Comment by Draise14** [comment]
If it is not showing, something must have broken from an API change, but it used to show. This would be another task. But the code and conditional is there.

**Comment by ReinerBforartists** [comment]
No, it is this task ^^

**Comment by Draise14** [comment]
So the icon change + fix the save as asset conditional
All good

**Comment by ReinerBforartists** [comment]
Plus the tooltip. Will investigate now :)

**Comment by Draise14** [comment]
Save asset should be top level on the side, and with the user notice. Too many users werent sure how it worked. The code is there, so it might be reviewing the conditional.

**Comment by ReinerBforartists** [comment]
Agreed, top level is a great idea here.

**Comment by ReinerBforartists** [comment]
Let's have a look at the manual ...

![fixed](https://github.com/user-attachments/assets/afde19dc-6459-44b5-b3ed-17e50242bbbb)

**Comment by ReinerBforartists** [comment]
Too big. I'll make it a manual tracker task.
