### ISSUE TITLE
View > Area menu, horizontal and vertical split and its icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4797]
A user pointed to that the horizontal icon is for the vertical tool. In fact the horizontal operator splits the window vertical. It divides the window into an upper and a lower. Horizontal would be left and right.

So, it's imho the operator that acts wrong. But it also acts wrong in Blender. Question is what to do here. Swap the operators? Simply change the icons back and leave the wrong operator names alone? Report it to Blender?

By the way, we have been at this before, and swapped the icons already. See here: https://github.com/Bforartists/Bforartists/issues/3710 And now it seems to be back to the wrong state. Watch the order of the operators in the commit. In the shot of this old commit vertical comes first, then horizontal. In the current shot horizontal is first.

![horizontal](https://github.com/user-attachments/assets/bd2b4741-84f1-40e8-8fa6-54268684dc8c)

**Comment by ReinerBforartists** [comment]
Report to Blender makes no sense, it is ui ux design. So we decide. Quickest fix would be to swap the icons back.

**Comment by Blenux** [comment]
Just need to switch the names over
