### ISSUE TITLE
Goo Engine - Add 'Hide in Outliner' option to pose bones and new outliner

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4806]
Separated task. Parent task see here: [Include features from GooEngine Blender fork](https://github.com/Bforartists/Bforartists/issues/3683#top)
#3683

https://github.com/dillongoostudios/goo-engine/commit/f6917850f6243ca4b1c6157d275b5a42adf95a3a

**Comment by ReinerBforartists** [comment]
Here i already have to give up at the patch itself. The classes to do the changes at are not longer existent.

**Comment by Blenux** [comment]
https://github.com/user-attachments/assets/09e12cd7-baab-4373-b185-d49540223077

**Comment by Blenux** [comment]
forgot to do a pr for this, doing now.
