### ISSUE TITLE
Grease Pencil in Draw mode - sidebar - tool tab - brush settings panel - collapse curves into sub-panels like with GP2

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4810]
The curve panels are useless when you don't use a tablet. And even with a tablet they are simply in the way most of the times. So better would be to turn this off by default.

We had already tried quite a few things to get it to work. So far without any result. The default state of this buttons does not store in the startup.blend or the preferences, is not defined in the userdef_defaults.c file. Also defining a default bool state in the property code did not help. ChatGPT was also clueless. It knows just Blender 3.3 code. And too much has changed since then.

Related issue: Grease Pencil - Draw Mode - Brush Settings panel regression #4522

![buttons](https://github.com/user-attachments/assets/5373350d-29dc-4cfa-a11f-3937459e46c0)

**Comment by ReinerBforartists** [comment]
Got an answer at Blender Developer. This state is saved with the brush. No wonder this was not to find. So what we would most probably need is to resave every brush to have the collapsed state.

**Comment by Draise14** [comment]
I think changing the essentials sub-module with our own fork is unmanageable - since we can't compare code from Blend files. 

With out Grease Pencil 2 UX, we had these curves show, but as collapsed sub-panels.
![image](https://github.com/user-attachments/assets/48d47869-0276-4d6a-8f6d-d106026cec1a)

We could change this task to revert this regression to how we had it before - which hides the rarely changes curves into sub-panels and minimizes the UX - without changing anything else.

**Comment by ReinerBforartists** [comment]
It is no regression. It is further development. They plan to make the default brushes editable again. But this won't solve our issue. 

You name it already, this fish is most probably too big for us. So i vote to close this task as won't fix.

**Comment by Draise14** [comment]
We can make the curve subpanels easily enough - so the GUI is similar to what it was. I'll try do that today. Former code could be a good clue, it's only interface code that changes here. Then not worry bout the changes to essentials brushes - I think pressure on defaults is fine. 

# Current:
![TabTip_xOrGpdl7Jc](https://github.com/user-attachments/assets/f6734c51-f0d7-4939-9b6e-67a02327b7d0)
# Proposed:
![TabTip_Ut7Nd1BVSx](https://github.com/user-attachments/assets/1f504825-87fa-4a88-9f62-569942caab0c)

**Comment by Draise14** [comment]
Also, GP is mostly for tablet users from the get go, as drawing with mouse is.. not really feasible anyway.

**Comment by ReinerBforartists** [comment]
Don't want to stop you toying around here. But the old prop was GP 2 code. The current code is GP 3. Now the prop is tied to the brush. The old way will most probably be dysfunctional. 

Let's have a look what your experiments says :)

**Comment by Draise14** [comment]
https://github.com/user-attachments/assets/d864f60a-33bf-4a41-96ea-25197b20106a

Better, and the material selector got fixed too.
