### ISSUE TITLE
Appdir Caching - moving to our own folder name.

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#4812]
I notice a while ago that if users use both Blender and Bforartists on their systems, each program will overwrite the caching folders set in the appdir.cc file, these locations are

 * - Linux: `$HOME/.cache/blender/`
 * - Windows: `%USERPROFILE%\AppData\Local\Blender Foundation\Blender\`
 * - MacOS: `/Library/Caches/Blender`

These include folders of, 

asset-library-indices
gl-shader-cache
vk-pipeline-cache
vk-spirv-cache

Thinking since we use code from alpha, we should have our own folder for this to help with any problems that may occure.

**Comment by Draise14** [comment]
Ah, good point. Should go to the Bforartists folder.
