### ISSUE TITLE
Hard Crash - When editing a text object in the official release

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4827]
Another show-stopper bleed through... a hard crash when going into a text object edit mode. 

The new overlays... I assume. They decided to once again merge the experimental to master, and also doubled to make it default. 

[bforartists.crash.txt](https://github.com/user-attachments/files/17962521/bforartists.crash.txt)

**Comment by ReinerBforartists** [comment]
It's a bug !

**Comment by Draise14** [comment]
Merge didn't fix it.

**Comment by Draise14** [comment]
Wait. Found a potential fix

**Comment by Draise14** [comment]
Yeah, the merge fixed it.
