### ISSUE TITLE
Important Hotkeys addon dysfunctional

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4829]
The Important Hotkey addon is currently dysfunctional. Worked in 4.2.2.

![importanthotkeys](https://github.com/user-attachments/assets/ef8d9df8-dac3-4cc4-9aee-8721ea954af3)

**Comment by ReinerBforartists** [comment]
The error tells me nothing. Just that it is not working. Not the reason, not the line in question.

**Comment by ReinerBforartists** [comment]
Introduced between devbuild from 01.11.2024 and the one from 08.11.2024. Let's have a look at the commits ...

**Comment by Blenux** [comment]
Yeah breaking changes introduced with 4.4 code, 

https://projects.blender.org/blender/blender/issues/129699
https://developer.blender.org/docs/release_notes/4.4/python_api/
https://docs.blender.org/api/4.4/bpy.types.Operator.html#bpy.types.Operator

fixes mention in these links, got the operator to work, but no text appears in the viewport,

![image](https://github.com/user-attachments/assets/52293463-6430-486d-b25f-5960df01bdd6)

**Comment by ReinerBforartists** [comment]
Man, what an "improvement" -.-
