### ISSUE TITLE
Mesh object with Hair object in sculpt mode - brushes differences

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4834]
Not sure if bug or feature. But in Blender all the brushes are displayed when you are in sculpt mode. In Bforartists not. Made me search the missing brushes ...

![brushesproblem](https://github.com/user-attachments/assets/889d0ed0-ff8b-4869-9bb5-b4c3b02ea37e)

**Comment by Draise14** [comment]
Maybe show active tool brushes is on by default.

**Comment by Draise14** [comment]
We added this by default since sculpt mode shows way too many be defaults and you can group by the brush tool, or else you have two methods of changing brush nodes... Redundant redundancy.

**Comment by ReinerBforartists** [comment]
Ah okay.

Mh filtering is great. But the Blender way is faster. And it's not this much brushes. Different story of course with custom brushes then. Is there a way to make the filtering optional maybe?

**Comment by Draise14** [comment]
Yeah, the filter on is when we have more brushes, and for sculpt mode it's necessary - but elsewhere not so much if less than 7 brushes (to avoid "choice overload")

FIltering is in the overlay settings of the asset shelf to the right, and will be remembered with preferences.

**Comment by Draise14** [comment]
If you want, you can revert this task. 
https://github.com/Bforartists/Bforartists/issues/4765

**Comment by ReinerBforartists** [comment]
No, it's your decision. I just stumbled across it since i missed the brush to immediately paint hair onto the mesh.

Wasn't that the old default?

**Comment by Draise14** [comment]
Old default was no active brush filter per brush. We made it active by default. 

The Blender way is off.

**Comment by ReinerBforartists** [comment]
Hmm. In Blender you don't have to switch the tool, but can simply pick the brush.

But okay, let's close.
