### ISSUE TITLE
Grease Pencil in Draw mode - Box tool in toolshelf errors

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4836]
We haz a bug- Calling the box tool floods the console.

Related: Grease Pencil in Draw mode - Brush settings - align props left #4835

First finish the related task if possible since it's the same files that we need to edit. We don't want a merge conflict ...

![box](https://github.com/user-attachments/assets/0668f89f-1ca2-4055-b213-5f55ff399a9d)

**Comment by ReinerBforartists** [comment]
Other task is fixed. This is now free to tackle.

**Comment by ReinerBforartists** [comment]
This is a problem at our end. Blender works fine.

**Comment by ReinerBforartists** [comment]
We miss the brush settings.

![missingsettings](https://github.com/user-attachments/assets/6ac6b8a5-5929-4c75-9393-18f2400b176a)

**Comment by Draise14** [comment]
Damn. I wonder where that went! Pretty big.

**Comment by ReinerBforartists** [comment]
Was a merge regression. Better said a change that did not arrive at us.

Manual task already exists. https://github.com/Bforartists/Manual/issues/675

So closing as fixed.

![fixed](https://github.com/user-attachments/assets/84e18481-e4e4-41b5-b06f-8a8c4acfea5c)
