### ISSUE TITLE
Launching Bforartists from the provided command scripts are only for Blender

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4842]
![image](https://github.com/user-attachments/assets/1450fce4-191b-43b2-b93a-88996a8deea2)

![image](https://github.com/user-attachments/assets/99b906e4-c927-440e-b94e-8dde8c2153c9)

The Blender Launcher V2 uses these scripts to launch Bforartists (or Blender) under different conditions. We never updated these to Bforaritsts and they indeed try launch Blender instead - though we ship them.

They need to be updated. 

# Relevant Task
https://github.com/Victor-IX/Blender-Launcher-V2/issues/180

**Comment by Blenux** [comment]
Yep notice this a while back but forgot to make a task for it bah
