### ISSUE TITLE
3D View - Drawing primitives from the toolbar fails

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4850]
A user report.

Adding a primitive from the toolbar currently does not work as expected. You can draw a yellow line. And that was it. 
With a further click you can create the primitive then. But there is no control over the shape.

Current Blender version does not show this behaviour. So i hope that the current merge fixes this. Fingers crossed ...

![dysfunctional](https://github.com/user-attachments/assets/b68bc566-580c-4a41-8788-0d4d3db8d8d0)

**Comment by Draise14** [comment]
Fixed in the merge.
