### ISSUE TITLE
3D View - Header overlays - Toggle ground grid only toggles ortho grid

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4854]
![image](https://github.com/user-attachments/assets/4727fd12-0535-4958-9037-72d4d985f61e)

Right now the floor grid is a seperate toggle, and the 3D View overlay buttons only toggles the ortho grid, not the ground grid. 

This must be something new from Blender?

**Comment by ReinerBforartists** [comment]
Is it? Check the manual :)

**Comment by Blenux** [comment]
Looked in this, and all our changes were lost with the overlay next merge.

**Comment by ReinerBforartists** [comment]
Ah, cool, a merge regression \o/

**Comment by Blenux** [comment]
already fixed :D
