### ISSUE TITLE
Animation Tab does not Obey Tool Shelf Tabs Toggle when Armature is in scene

### ISSUE THREAD

**Issue by TaiRakasha** [Bforartists/Bforartists#4856]
**Describe the bug**
If there is an armature in the scene, Tool Shelf Tabs Tools and Animation will always be visible, no matter the Tool Shelf Tabs View option toggle.  If there is no armature, the tabs dis/appear as expected.

**Desktop (please complete the following information):**
Windows 10; nvida rtx 3080

**Screenshots, Example Files**
![image](https://github.com/user-attachments/assets/cd033360-6fdd-4354-b60f-bbe8ef7a8e1e)

**Comment by Draise14** [comment]
Thanks for reporting.

**Comment by Blenux** [comment]
Yes that width issue has be tricky one to fix :(
