### ISSUE TITLE
 polyquilt/4.3.0,4.3.1

### ISSUE THREAD

**Issue by MajikDuck** [Bforartists/Bforartists#4860]
In both versions 4.3.0 and 4.3.1 I get a gizmo error when I try to use Polyquilt. I've tried resetting to factory defaults, uninstalling and reinstalling polyquilt, disabling everything except polyquilt and uninstalling and reinstalling the whole program.

Ive tried on both windows 10 and 11. i have a 5900x, 32gb ram, and a 6700 xt 

![image](https://github.com/user-attachments/assets/dde5a045-76b6-4244-bfb1-d40b23d91c52)
![image](https://github.com/user-attachments/assets/7b458c94-9ab2-43aa-8490-9ba594a3772c)
![image](https://github.com/user-attachments/assets/45c812d2-9343-4d42-8d21-57134c773b14)

**Comment by ReinerBforartists** [comment]
Hi majikduk,

Many thanks for the report. Could you please have a look if the addon fails the same way in newest Blender Alpha version, which can be found here?

https://builder.blender.org/download/daily/

Most probably the addon needs an update for the newest Blender Alpha version. We are always one version ahead compared to the release version of Blender. And so newest Bforartists version is already based at Blender 4.4, not the Blender 4.3 release

Kind regards
Reiner

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/a383aa38-a13f-4953-bf22-7410b9479185)

I also recommend using the extension fork of Polyquilt, this is actively maintained and works fine.

**Comment by Draise14** [comment]
![image](https://github.com/user-attachments/assets/87992624-9468-4642-8938-09d9846d61af)

Confirmed, same error in Blender 4.4

**Comment by ReinerBforartists** [comment]
I will close this issue. There is nothing that we can do at our end.

Thanks for making us aware.
