### ISSUE TITLE
Experimental Keymap - Grease Pencil - Mode hotkeys

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#488]
We need hotkeys to switch between the modes for the Grease Pencil object. Seems that the hotkeys for the normal objects are not valid here, and the Grease Pencil object has its own set somewhere. Object mode hotkey shows, but the rest is empty.

![modehotkeysforgpencil](https://user-images.githubusercontent.com/13919702/50571433-792b6800-0daa-11e9-89a7-aa457efe4e76.jpg)

**Comment by ReinerBforartists** [comment]
Mission impossible. Running into a Blender bug here. The created keys from the grease pencil object are the same than for the rest of the objects. And at this point things goes fubar ...

Creating a bug report at the moment.

**Comment by ReinerBforartists** [comment]
Task created https://developer.blender.org/T63273

Postponing until we know what the blender devs thinks here.

**Comment by ReinerBforartists** [comment]
The whole keymap is fubar. This one is not to solve until they rewrite it i fear. And i am not able nor willing to do that.

So closing. Won't fix.

**Comment by Draise14** [comment]
I have it setup this way in general my workflow, no conflicts so far - the entries are.. just listed twice, based on object context? I guess I'll do a compilation test to see if they save correctly.

**Comment by ReinerBforartists** [comment]
Ah, you managed it? Doesn't it get lost when you save a change? This is what happens all the time for the pose hotkey. 

The problem here is that you can enter edit mode of the grease pencil with the normal hotkey too. As told, this keymap part here is fubar.
