### ISSUE TITLE
Adjust the User Preferences to the Bforartists 1 defaults

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#493]
Blender has some odd defaults. We have changed quite a few in Bforartists 1. Now they are back, and we need to tweak them again. For example to rotate around the selection.

Task: Adjust the User Preferences to the Bforartists 1 defaults.

![userprefs](https://user-images.githubusercontent.com/13919702/50584219-89a51680-0e6e-11e9-9df9-5b602988b16d.jpg)

**Comment by Draise14** [comment]
Just a question, where are these saved (typically it's in the %appdata%/bforartists/2.80/config/ as a **userpref.blend**) but to have this written on a compile.. where are these saved? 

I can do this, just need to know where. 

They also changed the whole user prefs system... which feels messy, but oh well.

**Comment by ReinerBforartists** [comment]
It should also go into the startup file. That was at least the case when i did it the last time. If not then we have a problem. Then we must change this in the code.

And yes, the new system is ugly. Just not sure if we should return to the old system. This one was messy.

**Comment by ReinerBforartists** [comment]
Duplicate of this issue: https://github.com/Bforartists/Bforartists/issues/401

Closing.
