### ISSUE TITLE
3D View -  Iconize the Object menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#497]
The Object menu in Blender 2.80 is lots of menu items missing now. User has to guess most important tools again. Hotkey only tools is no go. And it has double menu entries.

Task, reimplement the Object menu from Bforartists 1. It has all the tools and icons implemented already. Or add from the old BFA1 object menu what is missing. Whatever turns out to be easier. We can refine it a bit more with this step already.

Take care of the modes and object types!!! There is more than just than what you can see here.

![objectmenu](https://user-images.githubusercontent.com/13919702/50602640-17f1ba80-0eb8-11e9-8191-eb4e8a611d63.jpg)

**Comment by ReinerBforartists** [comment]
Neither way works, since we have a complete new situation here. We don't have a toolbar anymore. So task is, iconize the operators. Refining, like looking for double menu entries and cleanup work comes at a later point when all menus are iconized again.

**Comment by Draise14** [comment]
Some of these tools cannot go into the toolshelf anymore? Is the new toolshelf editable?

**Comment by ReinerBforartists** [comment]
It's a complete new system with its own icons. And it has no tabs anymore. We first have to investigate what is possible here. That's a thing for later. First let's consolidate BFA2 to have the state of BFA1.

**Comment by ReinerBforartists** [comment]
Let's iconize as far as we can go.

**Comment by ReinerBforartists** [comment]
Fixed in master

![objectmenu](https://user-images.githubusercontent.com/13919702/51072447-0c915280-1661-11e9-8ba1-43f785953810.jpg)
