### ISSUE TITLE
View Menu - Area - Horizontal and vertical Split needs a icon

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#508]
View Menu - Area - Horizontal and vertical Split needs a icon. We don't have a icon for it yet.

![split](https://user-images.githubusercontent.com/13919702/50630112-c3921d80-0f3f-11e9-80ef-688a3c48316f.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
![area](https://user-images.githubusercontent.com/13919702/53488187-ddf2fe00-3a8d-11e9-92e6-594817a78d05.jpg)

**Comment by slippystance** [comment]
The "Horizontal" and "Vertical" icons seem incorrect.  From my viewpoint, the icon used for the "Vertical Split" should be used for the "Horizontal Split" and vice-versa.
![areasplitbug](https://user-images.githubusercontent.com/57046940/71999491-5a9a5100-31f6-11ea-9b47-8194117bdb33.jpg)

**Comment by ReinerBforartists** [comment]
Ah, thanks for the missing icon report. The icons in the second picture are correct though. Just test it. when you split  a window horizontally then you add a vertical line :)
