### ISSUE TITLE
"Manual" button in "Help" goes to an Error Page...

### ISSUE THREAD

**Issue by michaelbuet** [Bforartists/Bforartists#514]
"Home /Page does not exist: Manual
Page does not exist: Manual
The page Manual does not exist.

You can create the page as:"

![image](https://user-images.githubusercontent.com/16169389/50673421-58be0200-0f92-11e9-9dcb-ee495e8ad16b.png)

**Comment by ReinerBforartists** [comment]
Thanks for the report Michalebuet.

I see what happened here. We have Bforartists 2 in development now. And renamed the old manual to Bforartists 1 manual.

Hm, i have to think about a solution here. A new Bforartists 1 version is not possible. So either we leave it as is, or fix the manual link again.

**Comment by ReinerBforartists** [comment]
Fixed. The link in the Bforartists help menu should now lead to the manual again.

**Comment by michaelbuet** [comment]
THANKS!!!   Really excited to start using Bforatists 2.) When it comes out!
Sincerely,

Michael

Michael Buet,
LEAN/Six-Sigma-Black-Belt (LSSBB)
EE/ME - ISO Certification/CI Consultant
Dana Point, CA 92629
(843)489-6505

Punctuation is everything:
*I'm-possible...*
