### ISSUE TITLE
Webpage - Upgrade to a newer cms

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#52]
Drupal 7 has reached end of life. And so we need to upgrade the webpage to Drupal 8 at one point. Means when this is even possible. Tracker makes me really headache here. The links are in the release notes, and in the repository too ...

----

Very very big can of worms. I expected that i can update the page. But that's not how it works. We need to start with a fresh Drupal 8 installation, and migrate the content.

The current situation in Drupal 8: No forum, no tracker, no wiki, and from the other functionality half of the modules isn't available for Drupal 8 neither. They have made Drupal 7 deprecated ways too early. The port is impossible in the current Drupal 8 state. We couldn't even rebuild the page without a database port, which is the main goal.

This means for us that for now it's end of road. Either we wait until the for us important modules gets portet. Or we switch to another CMS. Not a happy bunny here.

Fact is, Drupal 7 is deprecated, and is not longer maintained. So we have to move on, sooner or later.

**Comment by ReinerBforartists** [comment]
One problem is solved. We use the Github tracker now. So one worry ferwer. Let's have a look how the port of our Wiki pages turns out. Maybe we migrate this content also to Github.

**Comment by ReinerBforartists** [comment]
Forget Drupal 8. It's not worth the hassle, and a downgrade. New plan is to us another cms. And start blank. again. And we should do this soonish. Before the community grows too big.

**Comment by Draise14** [comment]
Another CMS? No backup documentation? What will be the alternative?

**Comment by ReinerBforartists** [comment]
Dunno. Currently at evaluating. Most probably a cms based at Laravel. October CMS or PyroCMS for example. Maybe even a pure Laravel page. Laravel is a PHP framework. And the next big thing at the moment. Downside is that most cms based at it are commercial solutions. The cms itself may be free, but  the plugins costs money then. We will see.

The pressure isn't too big as long as the drupal 7 installation still works. But this can change with every update. And in my test installation for drupal 8 exactly this happened. I can't even login anymore since today's security update. One of the modules makes trouble now. And i haven't found out which one. Now imagine this would happen at our live installation ...

I'm simply tired of it. I definitely don't want to continue with Drupal anymore. It was a really good cms at its best days. But those days are over.

**Comment by ReinerBforartists** [comment]
Hm, October, a CMS based at Laravel, is really nice. But it requires lots of work to build a page with it.

https://octobercms.com/

Now i have to decide if i want to pick the sparrow in the hand. Drupal 8 would go faster. But its future is not really bright. Released before three years, and big parts of the addons not ported, and never will. The community is more and more unresponsible, looks like it is vanishing. And the functionality of version 8 is more limited than in version 7.

Or if i want to pick the pigeon at the roof. October is more flexible and future proof. With the price to have a much higher development time. Not so much addons available. And you find lots of paid addons here.

**Comment by ReinerBforartists** [comment]
Seems that we are back at Drupal. Laravel and October is still ways too much PHP coding. Without lots of visual help. It's a PHP framework, and you feel it. Creating the page isn't even the biggest problem. But maintaining it in the future then is.

Drupal is nasty here and there. But manageable. And should work a few more years. So let's have a look how far we can go with Drupal.

**Comment by ReinerBforartists** [comment]
Or we have to use October, since the drupal forum has made some nasty regressions in Drupal 8. Or we simply leave it as it is, means with Drupal 7, as long as it works.

Awww, i cannot decide XD

**Comment by ReinerBforartists** [comment]
Still not a happy bunny with neither Drupal 8 nor October CMS. Next candidate to check is http://b2evolution.net/

This one once started from the same code base than Wordpress.

**Comment by ReinerBforartists** [comment]
Tinkered around a bit more with this problem.

Drupal 8 has no fully working forum anymore. Advanced forum port is abandoned since two years. Things like autor pane are not ported, and most probably never will. Furthermore, every update ruins the page. I had not a single update that worked out of the box so far. And this is no go for a productive page. Drupal 8 in its current incarnation is useless.

October CMS is too bare bone. The only available wysiwyg addon is disfunctional, and kills the page by adding %20 here and there with every edit. No solution to this problem to find, no answer in the community, no answer at the Github page of the addon. The plugin developer is gone it seems. And this means that every change at the page would have to happen directly in the code. No go. The community of October CMS is in general everything but responsible and rather small. All in all also here, no go for a productive page. A promising solution that gots stuck in the promising state it seems.

I run out of options. I will definitely not build the page with Wordpress. That's a spam magnet. And not suited for a community page with an image gallery anyways.

Let's wait until august. We still have to decide if and how to continue the fork at all. And then have another look at it.

Unassigning again ...

**Comment by ReinerBforartists** [comment]
Well, we continue with the fork, so let's have a look at it again. 

The situation is still the same. I would love to move away from Drupal. It makes more and more trouble. But the effort is enourmous nowadays. 

Wordpress dominates the market, and has more or less killed the other CMS solutions. But Wordpress is the worst community solution. I will definitely not run the Bforartists page at it. Not even as a split solution with Wordpress as the frontend, and a external forum. I have better things to do than to clean up the spam every morning. 

Solutions like October turned out to be no solution at all. Never use a software that has no active community ...

What would be left is to write our own solution. With the PHP framework Laravel for example. And that's an enourmous effort as told.

To make a long story short, for now i decided to run Drupal as long as possible. And revisit the problem when Drupal finally gives up working. 

For now, closing.
