### ISSUE TITLE
Black Icons at mouseover in menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#525]
When we are above a menu item then the icon turns black. That's not how it should work.

![blackiconsmouseover](https://user-images.githubusercontent.com/13919702/50739124-ed677080-11db-11e9-9418-f3f3814729de.jpg)

**Comment by Draise14** [comment]
I noticed this across the UI board.

**Comment by ReinerBforartists** [comment]
This is a theming issue it seems. Factory defaults displays the icons just fine.

Investigating ...

**Comment by ReinerBforartists** [comment]
Got it. User Interface - Menu Item - Text Selected. Make it white, and the icons are fine then.

Draise, do you want to finish this task in your branch? It's a default :)

![textselected](https://user-images.githubusercontent.com/13919702/51128549-7019ac80-1828-11e9-8b28-b84f64140544.jpg)

**Comment by Draise14** [comment]
Sure thing.

**Comment by ReinerBforartists** [comment]
Fixed in master

![brighticons](https://user-images.githubusercontent.com/13919702/52047036-74440a80-2548-11e9-94ca-eb20545e6936.jpg)
