### ISSUE TITLE
BFA Icons are opaque in general UI 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#529]
**Bug**
General icon UI wide are opaque compared to original icons luminance. Most are without it's correct luminance like there is some kind of overlay. 

Left: BFA2 dev build - Right: BFA1
![bforartists_2019-01-08_14-55-04](https://user-images.githubusercontent.com/35357409/50855361-92f21f80-1355-11e9-850f-279403061a3c.png)
![bforartists_2019-01-08_14-59-50](https://user-images.githubusercontent.com/35357409/50855534-127fee80-1356-11e9-93b5-b506b9967c1d.png)

**Desktop (please complete the following information):**
Windows 10, Nvidia GTX1060
Bforartists - build 08/01/19

**Comment by ReinerBforartists** [comment]
Yes, there is something odd going on with the new recoloring code from Blender. Seems that i have to dive into the commits. But i am not really sure if we can fix this issue. And it's something for later.

**Comment by ReinerBforartists** [comment]
Solution will come here, it's the same cause: Black colored icons at mouse over in the header dropdown boxes #614 

Closing as duplicate.
