### ISSUE TITLE
Improve Text field highlight colour

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#530]
**Theme update Request**
The text highlight is a saturated blue, and the text cursor also - which makes it hard to select a text field and edit it. 

I suggest to make the text field the same as the number field. 

*Example of contrast issue*
![bforartists_2019-01-08_16-29-42](https://user-images.githubusercontent.com/35357409/50860079-0189aa00-1363-11e9-8de5-2bd92bc5daad.png)

**Describe the solution you'd like**
Better contrast on highlight. 

![bforartists_2019-01-08_16-32-22](https://user-images.githubusercontent.com/35357409/50860070-fdf62300-1362-11e9-8dcb-9ec01e0741cc.png)

**Describe alternatives you've considered**
Maybe a darker blue? Less saturated? 
Make it the same as the text field? 

![bforartists_2019-01-08_16-35-36](https://user-images.githubusercontent.com/35357409/50860270-7b219800-1363-11e9-9d91-120631e4a048.png)
![bforartists_2019-01-08_16-35-41](https://user-images.githubusercontent.com/35357409/50860275-7ceb5b80-1363-11e9-9c76-4ed9b418ed98.png)

**Comment by ReinerBforartists** [comment]
Requires to recreate userdef_default_theme.c.

Related task: https://github.com/Bforartists/Bforartists/issues/537

**Comment by ReinerBforartists** [comment]
Draise, what exact edit box is meant here?

**Comment by ReinerBforartists** [comment]
Now i see what you mean. The caret is hard to spot. Let's have a look for a better color that doesn't conflict with other edit boxes.

**Comment by ReinerBforartists** [comment]
The caret color would be more interesting here ...

**Comment by ReinerBforartists** [comment]
Bad karma. The caret color seems to be hardcoded. And i have no idea where to even start with the search. 

Sliders have the same problem than the text editing props. And changing the color of the slider is no good idea. It is what identifies the slider as a slider. Perfect trap -.-

**Comment by Draise14** [comment]
![bforartists_2019-05-03_11-16-24](https://user-images.githubusercontent.com/35357409/57150831-f1279000-6d94-11e9-9bbf-f28b4c9bc0a8.png)
![bforartists_2019-05-03_11-16-44](https://user-images.githubusercontent.com/35357409/57150833-f2f15380-6d94-11e9-9d86-7869bdce6c3b.png)

I would just change the highlight of a text box to just lighter grey, same as sliders, same as text boxes. 

Theme>Interface>Text - change Inner Selected from blue to same grey as elsewhere (it's inconsistent anyway)

**Comment by ReinerBforartists** [comment]
Fulfilled as  requested :)

![fixed](https://user-images.githubusercontent.com/13919702/57151567-8cd6f180-6dd1-11e9-8f82-bc878bc5a5d1.jpg)
