### ISSUE TITLE
Toolbar: Primitive Section/Lamp Subsection - point lamp error

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#534]
## **Issue**
Toolbar Primitives section has buggy subsection specifically the Lamp subsection. This blocks all other subsections in that area. Seems the point lamp is causing a bug. 

1. Toggle Create Primitives section
2. Add "Lamps" subsection
3. See other subsections and sections disappear. Lamp section doesn't show

![bforartists_2019-01-09_07-55-27](https://user-images.githubusercontent.com/35357409/50900693-f2970c00-13e3-11e9-9c09-5796187cf5cd.png)

**Screenshots**
![bforartists_2019-01-09_07-52-37](https://user-images.githubusercontent.com/35357409/50900610-b82d6f00-13e3-11e9-951f-49223dddf5c1.png)

**Desktop:**
Windows 10, Bforartists build 08/01/19

**Comment by ReinerBforartists** [comment]
Lamp is now light, and there is no hemi anymore. 

Fixed in master

https://github.com/Bforartists/Bforartists/commit/323c2e97408744f49138778e18a8860f49579d7d

![light](https://user-images.githubusercontent.com/13919702/51020239-4a697a80-157e-11e9-9f23-7f480fd78f82.jpg)
