### ISSUE TITLE
Default Theme: darker viewport colour default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#536]
**Issue**
Currently the default theme has a light grey gradient, but with the ground grid and default shader view being grey, it creates an eye strain due to a lack of contrast. 
![bforartists_2019-01-09_09-48-17](https://user-images.githubusercontent.com/35357409/50906894-18c4a800-13f4-11e9-98f0-76ec3bbea75b.png)

**Solution**
The default world colour is a good contrast and easy on the eyes, popping out the necessary details. The theme should also have a similar background colour. 
![bforartists_2019-01-09_09-48-25](https://user-images.githubusercontent.com/35357409/50906902-1b270200-13f4-11e9-81dd-ca4b530043a7.png)

**Describe alternatives you've considered**
I've personally used a light blue gradient to add a sky feel to the default, and adds a bit of logo like branding colour to the software. That also could contrast ok with the grey, like grey clouds on a blue sky. Tranquil.

**Comment by ReinerBforartists** [comment]
The bright color comes from the ground grid going into infinite compared to the BFA1 viewport. Don't make it too dark ...

**Comment by ReinerBforartists** [comment]
See also here: https://github.com/Bforartists/Bforartists/issues/568

Newest merge has killed the gradient. So we need to make it new anyways.

**Comment by ReinerBforartists** [comment]
I don't want to have a flat color here. I find it more comfortable with a gradient. Draise, what about these values? 0.2 for the lower, and 0.35 for the higher gradient color. It doesn't bite this much like the old gradient.

![gradientcolor](https://user-images.githubusercontent.com/13919702/51129069-be7b7b00-1829-11e9-8992-cf2d754a8916.jpg)

**Comment by Draise14** [comment]
Sure, I'll apply this change.

**Comment by ReinerBforartists** [comment]
A bit brighter than suggested, but darker than the previous defaults.

Fixed in master.

![gradient](https://user-images.githubusercontent.com/13919702/52048805-89229d00-254c-11e9-862a-c8cdce73a62c.jpg)
