### ISSUE TITLE
Default Theme: improve active tool readout contrast

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#537]
**Issue**
Currently the default theme has a black on a dark grey text readout on active tool (like transform), it creates an eye strain due to a lack of contrast.
![bforartists_2019-01-09_09-55-29](https://user-images.githubusercontent.com/35357409/50911740-883f9500-13fe-11e9-9966-04b96349d6ba.png)

**Solution**
Maybe changing the text to white would help?

**Comment by ReinerBforartists** [comment]
Ah, overlooked. And requires to recreate the userdef_default_theme.c file.  Postponing for version 0.2. Maybe we find a few more things, and can do this in one go.

**Comment by ReinerBforartists** [comment]
This task is related, and possibly a duplicate: Toolbar theming issue - black string at black background #616

**Comment by ReinerBforartists** [comment]
Duplicate. Closing.
