### ISSUE TITLE
Default Theme: opaque property shelf tabs background

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#538]
**Issue**
Currently the default theme has a transparent bar for the property panel tabs. This makes the floating properties shelf panels feel broken or as if they should be a pop up that dissappears. 
![bforartists_2019-01-09_09-55-43](https://user-images.githubusercontent.com/35357409/50911947-f08e7680-13fe-11e9-8cbc-a76e55996f14.png)

**Solution**
Making this are opaque and the same colour as the tabs background in the properties view might be consistent and easier to understand that the panels are attached to the side.

**Comment by ReinerBforartists** [comment]
Yes, filled is better. Even when we loose a bit viewport area by this.

**Comment by ReinerBforartists** [comment]
Fixed in master. It is not completely opaque though. I made it semi transparent a bit. Lets the viewport look a bit bigger.

![opaque](https://user-images.githubusercontent.com/13919702/52116585-c7ce5b00-2611-11e9-9de5-d1a8948e9f26.jpg)
