### ISSUE TITLE
Crashbug - removed Default Workspaces in factory settings.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#539]
**Bug**
After adding the toolbar to the layouts, using a factory reset on the default startup.blend file (no matter if Startup is saved without any userpref.blend file overrides) or loading a fresh compilation of Bforartists with new default layout with changes can creates an access violation.  

![powershell_2019-01-09_11-18-00](https://user-images.githubusercontent.com/35357409/50912844-1583e900-1401-11e9-8dc8-9f368aaa827b.png)

Fresh start, no startup.blend file generated on first use.

![explorer_2019-01-09_11-28-20](https://user-images.githubusercontent.com/35357409/50913174-c8ecdd80-1401-11e9-83e9-12a17aa10ea9.png)

Apparently, the file has trouble saving theme and toolbar settings with the factory settings reset. 

**Possible solution**
This is not a solution, but having the startup.blend file in the %appdata%/Bforartists/2.8/configs/ folder fixes this issue, as the setting for the toolbar apparently is saved in the startup.blend file. But a factory reset and fresh start pulls the user preferences from somewhere else it seems. 

**Desktop:**
Build on the #401_fix_layouts_branch on Windows 10.

**Comment by ReinerBforartists** [comment]
> Having the startup.blend file in the %appdata%/Bforartists/2.8/configs/ folder fixes this issue,

This is no solution. Bforartists does not come with that folder :)

Ah, i see lots of fun ahead here -.-

**Comment by Draise14** [comment]
Ok. I am trouble shooting now. 

- I disabled the toolbar and recompiled. Factory Reset still crashes. 

This means.. that maybe a layout I have is corrupt by some other factor. I'm going to now strip it down and try rebuild.

**Comment by Draise14** [comment]
Ok. It no-longer is crashing with bare bones and new edits, but it's also not really working on factory reset. 

### Compiled file setup and internal saved preferences
![bforartists_2019-01-09_13-25-04](https://user-images.githubusercontent.com/35357409/50919898-1113fc00-1412-11e9-8053-d4632246fba3.jpg)

### Factory Reset with compiled file
![bforartists_2019-01-09_13-24-51](https://user-images.githubusercontent.com/35357409/50919902-11ac9280-1412-11e9-9a5a-9ef0deac3ef0.jpg)

![bforartists_2019-01-09_13-28-22](https://user-images.githubusercontent.com/35357409/50920079-75cf5680-1412-11e9-8c3b-c1daef0b10b3.png)

- Toolbar settings didn't save
- Theme didn't save
- Hotkeys did save 
- hidden viewport toggles did save

**Comment by Draise14** [comment]
I'm stuck. I posted for help on the stackexchange, blender artists and blender dev forum. 

Unassigning.

**Comment by ReinerBforartists** [comment]
Have you found out what caused the crash?

**Comment by Draise14** [comment]
I can't figure it out. I've tried all the combos I can think of. As soon as I save any startup file that's heavily fixed up, save the **startup.blend**, overwrite the repository copy, then the factory reset gets corrupted on build with the same errors. 

`Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6FE602DF4`

or 

`Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7BB7CD7F4`

**Built tests:**
- theme is not it
- hotkeys are not it
- activated Toolbar addon is not it
- all other addons deactivated are not it


**Factors that could be causing a crash**
- stored toolbar settings
- double toolbars in workspaces
- other toolbars present in other workspaces (not just a single default bare minimum change)
- topbar closed on some layouts by default

The fact that a working bare minimum workspace change and edit does a factory reset to Blender default theme and toolbar settings resets to default might be a clue..

**Comment by ReinerBforartists** [comment]
I need the exact steps to reproduce the crash. Then we can make a debug build and have a closer look where the crash is coming from.

**Comment by Draise14** [comment]
Sure. I will document till I get the crash again and post here today. 

But I found a clue:

The default startup has settings stored, but more so the reset has settings programmatically stored in another C file. 

`versioning_defaults.c`

**Comment by Draise14** [comment]
**FOUND THE BUG**

I removed the "UV Editing" layout and it will make it hard crash when I build the **startup.blend** file.

**Comment by ReinerBforartists** [comment]
Thanks. So this is in the 401_fix_layouts_branch, right? I will have a look at it tomorrow.

You have green ligth except for point four. Why do you want to remove Cycles from Bforartists? :D

And too bad that they changed the system so hard. The old method with compiling everything into the startup.blend was definitely more hassle free ...

**Comment by ReinerBforartists** [comment]
Oh, and please make a own task for each of this steps. As told, one big monster task is not good.

**Comment by ReinerBforartists** [comment]
Ouch, just reread it. So you catched the bug? And fixed the crash? I am blind XD

**Comment by ReinerBforartists** [comment]
Aand one more comment. When working with the code base, please add comments what you changed. And best add a "bfa -" prefix in the comment. Then we know it's our code.

**Comment by Draise14** [comment]
I have found the bug, but not fixed nor changed anything. 

I will make new tasks then close this one. Then assign and fix them one by one, I suppose. (in a few hours)

Yes, I will do the commits on the layout and default preferences tasks to **401_layouts_fix_branch**

The C code doesn't look so hard and the theme has another script that creates the default theme, so that one is easy. The rest is fairly easy too, I think. 

Noted on the comments tip, found your system when looking the other day! Thought it smart. I'll follow through! 
Noted on the cycles addon, haha! 

_COOL. I'm actually starting to be useful._

**Comment by ReinerBforartists** [comment]
Regarding the crash, this crash should not happen. And does not happen with Blender. Here you can remove layouts, save the startup file, compile with it, and Blender will then start with the layouts removed.

This is a bug at our end and needs investigation.

**Comment by ReinerBforartists** [comment]
Defaults are now in version 0.1.0. Every further change is a new issue. Closing. This task has fulfilled its purpose.
