### ISSUE TITLE
Promotional Work

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#54]
We need to make Bforartists a bit better known. So we spread the news at various boards and pages. It's also time to write a Wikipedia article. This task here is about all this promotional work.

**Comment by ReinerBforartists** [comment]
So far ...

English pages:

https://forum.unity.com/threads/bforartists-0-9-4-released.495712/
http://polycount.com/discussion/184041/blender-fork-bforartists/p1?new=1
http://forums.cgsociety.org/showthread.php?f=59&t=1466944
https://www.gamedev.net/forums/topic/692162-blender-fork-bforartists-version-094-released/?tab=comments#comment-5356531
https://www.united3dartists.com/forum/viewtopic.php?f=13&t=5336
https://www.reddit.com/r/3DMA/comments/70obag/blender_fork_bforartists_version_094_released/

German pages:

http://www.3d-ring.de/3d/forum.php?post_id=33379
http://www.gimpforum.de/showthread.php?p=158904#post158904
https://zfx.info/viewtopic.php?f=10&t=3867&start=75
https://www.3d-board.de/index.php/Thread/32906-Blender-Fork-Bforartists-Version-0-9-4-erschienen/?s=b82c25dc27be3392b7a500e29cf41afd15aee12d

Contacted ZDNet, and waiting for response. Contacted CGPress, and waiting for response.

Download pages:

http://www.softpedia.com/get/Multimedia/Graphic/Graphic-Editors/Bforartists.shtml
http://softgui.de/softwares/bforartists

**Comment by Davis-BfA** [comment]
I´ll drop this here, the logo needs to be updated on alternativeto. https://alternativeto.net/software/bforartists/

**Comment by Davis-BfA** [comment]
Here is a list of blogs and websites I contacted today to include BfA into their articles or software lists:
https://www.easyrender.com
https://all3dp.com
http://www.3ders.org
https://www.lifewire.com
https://windowsreport.com
https://www.sculpteo.com
https://www.hongkiat.com
https://blog.capterra.com
https://www.3dnatives.com
https://3dprinting.com
https://www.matterhackers.com
https://www.dobot.cc
http://3dprintingforbeginners.com
https://www.shapeways.com
https://en.99designs.de
https://www.digitaltrends.com
https://mashtips.com
http://innov8tiv.com
https://www.scan2cad.com
http://teknologya.com
https://www.pannam.com
http://www.viralhax.com
https://medium.com
https://help.sketchfab.com
https://ultimaker.com
https://makezine.com
https://www.topbestalternatives.com
https://ubernerd.com.au
https://www.opensourcealternative.org

**Comment by ReinerBforartists** [comment]
Good job!

**Comment by ReinerBforartists** [comment]
I will have a look to update the graphics at alternativeto tomorrow.

**Comment by ReinerBforartists** [comment]
Images at aternative.to updated. They are currently pending ...

**Comment by Davis-BfA** [comment]
We made it onto the Make: blog.
https://makezine.com/2018/03/23/painless-blender-interface/
I also got a comment approved on the mashtips list.
https://mashtips.com/3d-modeling-tools/

**Comment by ReinerBforartists** [comment]
Yay \o/

**Comment by ReinerBforartists** [comment]
We have a news at CG Channel and CG Press. 

http://cgpress.org/archives/bforartists-1-0-released.html
http://www.cgchannel.com/2018/05/bforartists-team-releases-bforartists-1-0/

**Comment by ryliejamesthomas** [comment]
I've mentioned it in my Game Making Tools Wiki ;3

https://www.gamemaking.tools/wiki/index.php/Bforartists

**Comment by ReinerBforartists** [comment]
This is great. Many thanks :)

**Comment by ReinerBforartists** [comment]
Resurrecting this thread. It's time to spread the word again, now that we have a stable version of Bforartists 2

**Comment by ReinerBforartists** [comment]
Announced Bforartists at the usual places. 
Plus
https://www.psd-tutorials.de/forum/threads/bforartists-2-erschienen.182158/#post-2724522
And 
https://cgpress.org/archives/bforartists-2-released.html

**Comment by ReinerBforartists** [comment]
Not my favourite job. But we have a few more announcements now. The good thing is, the fork is known enough that it spreads by itself now. It was not necessary to post it at gamedev.net again for example. And also other pages have picked up the release.

Still waiting if the german magazine digitalproduktion will write an article about Bforartists 2 again. I was in contact with them. But i guess this time it will be much shorter, if even.

That should be enough for now. Unassigning. On with other things.

**Comment by ReinerBforartists** [comment]
Ah and when somebody finds the time to write a wikipedia article ... XD

**Comment by ReinerBforartists** [comment]
I'm moving this one out of the tracker since it is no task to solve really. But fits perfectly into the discussion.
