### ISSUE TITLE
Bone Roll in Edit Mode - put the recalculate roll menu one hierarchy upwards

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#543]
Two hierarchies is one hierarchy too deep.

Task: Bone Roll in Edit Mode - put the recalculate roll menu one hierarchy upwards. Set roll and clear roll can be in the first hierarchy. Names needs a change too then. Set Bone roll ...

![recalcroll](https://user-images.githubusercontent.com/13919702/50963538-4893ae80-14cd-11e9-8111-90f9fe8758b5.jpg)

**Comment by Draise14** [comment]
Is this an easy task to do?

**Comment by ReinerBforartists** [comment]
Nothing is really easy. But it would cost me around five minutes or so. So i guess it can be defined as an easy task. Assign and try out :)

The task is as simple as hovering with the mouse over the Armature menu to get the class ( Turn OFF the feature to open the menu with hovering over it, then the Python class name for the menu will show), have a look how everything is connected, and put the menu in question one hierarchy upwards.

**Comment by Draise14** [comment]
Sure, I'll give it a go. Worth learning all the ins and outs - sometimes I want to get into production with things but then quirks slow me down. 

I'm just been spending the past few days trying to clean up my personal settings into a template (such a weird system) and merge the master.

**Comment by ReinerBforartists** [comment]
Haven't tried this yet. But doesn't sound really good ^^

Good luck. I am here in case you have questions.

**Comment by Draise14** [comment]
Correct me if I'm wrong, but I've been merging the master to the branch this way:

1. - I switch/checkout to master, 
2. - fetch, 
3. - pull, 
4. - then switch/check out to the branch, 
5. - then merge from master to the branch. 

I've made it a daily habit now. 

I won't be keeping the template in the branch, it's in the %appdata% in another folder, and I can remove the config changes and do factory resets to defaults without it affecting my personal settings in the template - so I can keep on doing production work and still develop.

**Comment by ReinerBforartists** [comment]
Sounds legit :)

**Comment by Draise14** [comment]
Wait, so when I fetch and pull from the branch, it also downloads/pulls from the master?

**Comment by ReinerBforartists** [comment]
When you fetch the master yes. Origin should also work.

**Comment by Draise14** [comment]
Ah, I see the toggle now, so.. fetching from **Origin** does the fetch from all branches? Or just the branch you are in?

**Comment by ReinerBforartists** [comment]
Origin should fetch everything. But you can also just fetch and merge the master branch.

**Comment by ReinerBforartists** [comment]
Damn, i start to become unsure. Git ... :D

**Comment by Draise14** [comment]
Quesiton outside of merging:

1. The now old sub-menu code... is that supposed to be removed now - should I comment it out for revision? 
2. Is it ok I comment heavily all my changes so it's easier for you to review and know what I did? For the pull request and commit.

**Comment by Draise14** [comment]
![bforartists_2019-03-12_12-05-52](https://user-images.githubusercontent.com/35357409/54220335-2b745f80-44bf-11e9-86a8-07f84b739b26.png)

Nice, did it. Was easy enough. I left the old sub-menu code there, but commented that maybe it could be removed. 

I added "Bone" to the 3 operators/menus
I moved up the Recalculate menu
I moved up the two bone roll operators up to the root menu. 
I commented what could be removed

**Comment by ReinerBforartists** [comment]
Remove the obsolete code. There are some cases where obsolete code should remain for compatiblity. Like all the context menus. Or places where addons usually adds itself. But i doubt that a addon dev will ever try to add a entry here.

When it helps you then comment the code that you work at as much as you want. You are the one who works at it, and you are the one that needs this help.

At the beginning you might even comment things that are self explaining. That's normal. And i don't have anything against it as long as you don't start to comment all available scripts to death. For me the UI code is already self explaining. I rarely add comments here anymore.

**Comment by Draise14** [comment]
Ok, will remove the code and clean up the comments, then recommit - I can see when you commit that Git shows all the changes anyway.

**Comment by Draise14** [comment]
@ReinerBforartists , just to confirm, how often, and when should I do the pull request? 

When I close a task? When I have multiple tasks closed? Per task? Or.. just when everything is ok? 

Also, is it better to do the pull request through Git here online or through Tortoise?

**Comment by ReinerBforartists** [comment]
We said every commit should be a pull request now, so that i can review it. Task is solved at your end. So Do it now please! 

> When I close a task? When I have multiple tasks closed? Per task? Or.. just when everything is ok?
You close a task when you are finished with it. When it's not okay then it is not finished. And every task is a unique task. Nothing to do with other tasks.

In case we have problems at the pull requests, then we can solve this problems in the pull request. I can approve it and then merge into the master. Or i can reject it, and request further changes. That's what it is good for. We can even open new tasks from there if necessary.

> Also, is it better to do the pull request through Git here online or through Tortoise?
Good question. I have no idea, never tried through Git or Tortoisegit. I always made the pull request here at github. The vital part is that i get a pull request message here at github. Which i should get in both cases.

**Comment by Draise14** [comment]
Yes, pull system per task is a good idea. All for it... I really don't like screwing stuff up. 

I think it be best the pull requests from Git online, the tortoise system is rudimentary. 

Pull request created.

**Comment by ReinerBforartists** [comment]
And merged.

In the future it may take some time from pull request to merge. Here i had my fingers into creation too. Next time i need to check first ...

**Comment by Draise14** [comment]
Sure, no worries. The workflow should be fine with time, I'm in no rush! I'm glad I managed a task without knowing too much. I feel the hackerman power again.
