### ISSUE TITLE
Write a Wikipedia article

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#55]
Blender has a Wikipedia entry. Bforartists so far not. Maybe time to change that ...

**Comment by Davis-BfA** [comment]
There is also a list of 3d software on wikipedia, that is missing BforArtists sofar.
https://en.wikipedia.org/wiki/List_of_3D_modeling_software

**Comment by ReinerBforartists** [comment]
Do you want to write the articles there? :)

**Comment by ReinerBforartists** [comment]
Looking great. Thanks for the entries :)

Licensing, GPL2 is wrong here. It is the same than Blender. Gpl2+ and Apache. So you could simply copy it :)

**Comment by Davis-BfA** [comment]
Thanks for checking. I fixed the license in this entry

**Comment by Davis-BfA** [comment]
It seems we need an article to stay on the list. It got removed with the note "(removed program without article, deemed not notable)"

**So I added a request for an article.**  It is recommended by wikipedia anyway to have an article written by someone else to avoid any bias or advertising.

https://en.wikipedia.org/wiki/Wikipedia:Requested_articles/Applied_arts_and_sciences#Technology_and_tools

**Comment by ReinerBforartists** [comment]
Too bad. So we made the second step after the first one.

The biased thing is what made me stay away from writing the article by myself ^^

**Comment by ReinerBforartists** [comment]
I have just for fun written an article at the german wiki. Immediately flagged as a delete candidate ... 
Was worth a try ^^

**Comment by ReinerBforartists** [comment]
Closing this one. Wikipedia is not relevant for us. Maybe somebody writes an article about Bforartists at a later point. But this is not in our hands.
