### ISSUE TITLE
Workspaces Defaults: Rewrite the userdef_default_theme.c to have Bforartists default theme

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#576]
## Reason:
The default startup has settings and workspaces generally stored in a startup file, but default load up and factory reset has settings programmatically stored in another C file listed below. 

`versioning_defaults.c`

**Location:**
//source/blender/blenloader/intern

These tasks are to  rectify the Bforartists defautls and new workspaces. 

**Examples**
The C file resets the theme to the blender default:
![atom_2019-01-10_10-13-42](https://user-images.githubusercontent.com/35357409/50977654-b8e80300-14c0-11e9-8047-0d0c58576fe1.png)

## Task
Re-generate new theme C file.  The following file needs to be generated by another file in the repository. 

`userdef_default_theme.c`

  **Location**
\release\datafiles\userdef

By using this file:

`blender_update_themes.py`

**Location**
   //source/tools/utils/blender_theme_as_c.py

**Command**
`./source/tools/utils/blender_theme_as_c.py ~/.config/bforartists/2.80/config/userpref.blend`
    

## Branch
401_layout_fixes_branch

## Related task:
- Set Bforartists keymap to be the default keymap #494
- Default Theme: darker viewport colour default #536
- Black Icons at mouseover in menus #525
- Fix the layouts #401

**Comment by Draise14** [comment]
Great, now I don't know how to parse a file in Python. 
Any help? 

This is one clue: [Stackoverflow Thread](https://stackoverflow.com/questions/36167685/how-to-pass-file-as-argument-in-python-script-using-argparse-module)

**Comment by Draise14** [comment]
They have one python file that loads up the Userpref.blend file and writes the default template into the C file for the default theme override. 

Problem is I am not sure how to run the script with the command they commented to do that. 

Technically I need to "pass" the file through that py script. The command is in the comments. 

I haven't ever done that before. 

Or..... I could just remove the default theme override to the C theme file in the factory setting file and make it go back to the old way. *evilgrin*

**Comment by ReinerBforartists** [comment]
Ah, i see. This one works similar to what you do to update the icons. Open up Windows Commandline. I have a shortcut to cmd.exe here at my desktop.

Then you navigate to the folder with the script. And run the script with python, followed by the file that you want to read.

So in my example i switch to drive H by typing in **h:**
**cd** for switching the directory, followed by the path to the script. In my case H:\bforartists\Bforartists\source\tools\utils

then type in **python blender_udpate_themes.py** to run the script with python

The unfunny part here is, i get an error. Need to investigate here what the script expects. Maybe we need to move the file to another location, or add the file to change into the folder.

This would for example be python blender_udpate_themes.py userpref.blend. But also this has thrown an error. But bpy is the blender python module. So it can most likely be that you need to load this script into Blender/Bforartists, and run it from the text editor.

I have also spotted a blender_theme_as_c.py script. So i expect it to be a bit more complicated.

I will check again in the evening.

![console](https://user-images.githubusercontent.com/13919702/51178239-49a84f80-18c2-11e9-8669-d18e40bf7199.jpg)

**Comment by ReinerBforartists** [comment]
Okay, first hurdle was, the script in the repository was an old one -.-

Is now updated. The newest version is in the repository.

Then i have navigated to the compiled version of Bforartists. We need the exe to run the script. So

cd H:\bforartists\bforartists_build64\bin\Release

In that folder i have run the command

bforartists.exe --background --python H:\bforartists\Bforartists\source\tools\utils\blender_update_themes.py

This executes the script. And a xml file gets changed. Not sure which one though. Need to check the console message one by one first.

And we have unfortunately still lots of error messages when the script executes. Mainly at our own addons. Seems that we first need to tell our bforartists that these scripts are part of the show.

![updatescript](https://user-images.githubusercontent.com/13919702/51197727-a3c10900-18f2-11e9-9e86-8c83e4349386.jpg)

**Comment by Draise14** [comment]
Ok, I see what's happening and how to do it now. Great. Thanks Reiner! You da man. The C file template that the Factory Reset calls is another C file and the generation file for the theme gets made from the userpref.blend you can specify, so I'll give that a go.  

_I'm currently moving the studio so will be awol for the next couple of days, but will get back to this asap._ 

_This whole factory reset funny business sucks. Means the common artist/layman can no-longer make his own factory reset from the UI._

**Comment by ReinerBforartists** [comment]
Yes, this story is a bit unfunny now.

I will separate the problem with the error message by running blender_update_themes.py now. This does not belong into this thread.

**Comment by ReinerBforartists** [comment]
Oh and good luck with your studio move :)

**Comment by ReinerBforartists** [comment]
Draise, how's the move going? :)

We reach closely a point where we could release the first alpha version ...

**Comment by Draise14** [comment]
Ok, finally finished moving. Just setting up sound. Took a while to get internet going again. Should be back at it next week.

**Comment by ReinerBforartists** [comment]
Congratulations :)

**Comment by ReinerBforartists** [comment]
Changing the theme is done with the blender_theme_as_c.py script. Unfortunately this script seems to be broken. I even tested it with vanilla blender so that nothing from Bforartists is involved. Still a syntax error in the console. Seems that we have to ask the blender devs here.

![syntaxerror](https://user-images.githubusercontent.com/13919702/52110715-c6953200-2601-11e9-9766-e3a3e3fce4d0.jpg)

**Comment by ReinerBforartists** [comment]
Not sure if we will ever see this script fixed by the Blender devs soon. They have their theme already ...

Looking into the C file now. Even when it is not recommended to edit the file by hand. We need a solution here.

**Comment by ReinerBforartists** [comment]
The values are binaries. -.-

**Comment by ReinerBforartists** [comment]
Sometimes the solution is really simple. The script is a python 3 script, not a python 2 one.

py -3 blender_theme_as_c.py userpref.blend 

does the trick.

![themewithpython3](https://user-images.githubusercontent.com/13919702/52161313-93b37280-26c3-11e9-938b-45309b864ea8.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
