### ISSUE TITLE
Workspace Defaults: rename/remove UV Layout factory reset check

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#577]
## Reason:
The default startup has settings and workspaces generally stored in a startup file, but default load up and factory reset has settings programmatically stored in another C file listed below. 

`versioning_defaults.c`

**Location:**
//source/blender/blenloader/intern

These tasks are to rectify the Bforartists defaults and new workspaces. 

**Examples**
when I rename/remove spaces, there is a check to apply fixes to certain layouts with certain names that could crash - specifically the "UV Editing" layout which I had renamed:
![atom_2019-01-10_10-22-45](https://user-images.githubusercontent.com/35357409/50978110-ba65fb00-14c1-11e9-8533-076a5a59a0b1.png)

## Task
Remove or rename the workspace check for the UV Layout. 

## Branch
401_layout_fixes_branch

## Related task:
- Default Workspaces: Rewrite the userdef_default_theme.c to have Bfoartists default theme #576
- Fix the layouts #401

**Comment by ReinerBforartists** [comment]
Didn't expect it to be this complicated. Are you sure that you can manage this task?

**Comment by Draise14** [comment]
This one is an easy one that I understand.

**Comment by ReinerBforartists** [comment]
Okay :)

**Comment by ReinerBforartists** [comment]
Just noticed that UV and Image Editor are now two separated editors. Means it is no good idea to remove the UV layout. We would have no layout to edit the UV's anymore ^^

**Comment by ReinerBforartists** [comment]
As told, we must keep the UV layout. What we eventually need to deactivate is modeling and painting layouts. Still at evaluating if there isn't an easier way than to change the hardcoded values in versioning_defaults.c

**Comment by ReinerBforartists** [comment]
Already mentioned in another thread, saving the startup.blend with the changes should work just fine. I don't see a need to change anything at this file here. We just need to get rid of the crash.

Closing this task, it is invalid. Reopening a task for just the crash ...
