### ISSUE TITLE
Workspace Default: add exception or remove addon in default factory reset.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#578]
## Reason:
The default startup has settings and workspaces generally stored in a startup file, but default load up and factory reset has settings programmatically stored in another C file listed below. 

`versioning_defaults.c`

**Location:**
//source/blender/blenloader/intern

These tasks are to  rectify the Bforartists defautls and new workspaces. 

**Examples**
Here the addon prerefences are cleared, thus the toolbar going to default:
![atom_2019-01-10_10-25-20](https://user-images.githubusercontent.com/35357409/50978259-0e70df80-14c2-11e9-8836-30eeabf95585.png)

## Task
The toolbar doesn't preserve it's settings on a factory reset, which is a key addon in Bforartists. So we need to create an exception or remove addon setting reset in the default factory reset settings. 

## Branch
401_layout_fixes_branch

## Related task:
- Fix the layouts #401

**Comment by ReinerBforartists** [comment]
This task is invalid. We do NOT edit versioning_defaults.c. I was told that just user created startup.blend deal with this c file. And not the factory defaults. So hands away from the versioning_defaults.c file!

Closing.
