### ISSUE TITLE
Node editor - Node menu - separate tooltips for edit Group and exit Group

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#599]
Each operator should have its own tooltip.

Task: Node editor - Node menu - separate tooltips for edit Group and exit Group

![exit](https://user-images.githubusercontent.com/13919702/51829775-8d517f00-22ee-11e9-83ee-3d668b5876a7.jpg)

**Comment by Draise14** [comment]
Dibs! Gonna give this one a go.

**Comment by Draise14** [comment]
Ah nope, there is only one entry and I wouldn't know how to change it. if anything, Here are the files:

\\release\scripts\startup\bl_ui\space_node.py
\\release\scripts\startup\bl_ui\space_node_toolshelf.py

And here is the tooltip:
\\source\blender\editors\space_node\node_group.c
Lines 156-171

Not sure hot to add a new tooltip with the conditional (since it's a true/false boolean operator entries)

**Comment by ReinerBforartists** [comment]
You need to create a new class for that. Have a look for the classes with a 

# Workaround to separate the tooltips

comment above it. We have quite a few in the space_view3d.py file. Study how everything is connected. When you have questions, i am here. Or you claim an easier task ;)

**Comment by Draise14** [comment]
Ok. Found the code. It's 3 entries to do it in the document. I copied one and am trying to make it work now. I'll post progress tomorrow.

**Comment by ReinerBforartists** [comment]
I hope the comments were good enough to explain how it works. I am there in case you are stuck. And will have an eye at the commit.

Now imagine you would have the usual Blender comments here. None ...

**Comment by Draise14** [comment]
Ok, today I'm gonna tackle it again. Had a busy week with work, well looking for work - need.. cash.

**Comment by ReinerBforartists** [comment]
When you have questions, i am here :)

**Comment by Draise14** [comment]
![2019-02-22_09-16-13](https://user-images.githubusercontent.com/35357409/53247941-8f56f580-3682-11e9-8533-6a28ae98a78c.png)
There. I got it going! Now to finish this task and commit. 
hehe, I feel like a hackerman.

**Comment by Draise14** [comment]
![bforartists_2019-02-22_09-26-52](https://user-images.githubusercontent.com/35357409/53248581-06d95480-3684-11e9-99c2-303e4b030d46.png)

Ok, cleaned it up and put in a more logical tooltip. Gonna commit now.

**Comment by ReinerBforartists** [comment]
Looking good. Congratulations. That's how it starts :)

One little thing regarding Blender name conventions. PT is panel. MT is menu. And OT is Operator. Our own tooltip is a new operator. But at the same time a menu. So i would use 

NODE_MT_exit_edit_group

here as the class name.

**Comment by Draise14** [comment]
Ok, recommitted it with MT, fixed it up and compiled it to test. All good now.
