### ISSUE TITLE
Tooltips needs tool names - add title to tootips in Motion tracking Solve Panel

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#604]
Tooltips needs the tool names. 

Task: add title to tootips in Motion tracking Solve Panel, and the ones in reach. There are quite a few missing.

![tooltipsneedsnames](https://user-images.githubusercontent.com/13919702/52039759-ac8e1d80-2535-11e9-9bef-213711b8c3ec.jpg)

**Comment by ReinerBforartists** [comment]
How to:

Grep for tooltips that have no title yet.

![setplane](https://user-images.githubusercontent.com/13919702/52474057-acc29480-2b97-11e9-8ab1-bd183f9d10a2.jpg)

Then put the operator name in front of the tooltip , separated with a \n for new line.

![nameinthetool](https://user-images.githubusercontent.com/13919702/52474137-e09dba00-2b97-11e9-8dc3-17e6cef2849e.jpg)

Compile and test. Result should look like this then for example:

![setsceneframes](https://user-images.githubusercontent.com/13919702/52474221-22c6fb80-2b98-11e9-8d5d-c9b31ce80e03.jpg)

There is a motion tracking dataset available now in the files repository.

https://github.com/Bforartists/files

**Comment by Draise14** [comment]
Aha. I'll do this one.

**Comment by Draise14** [comment]
Compiled, tested, done. 
6 tooltip entries fixed in the Sovle Panel.
