### ISSUE TITLE
Editing the layouts, hidden layouts doesn't keep the edits.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#617]
When i edit one of the hidden layouts and remove it, and then reopen it, then the old unedited layout comes back.  I have three times edited the 2D Animation layout before i realized that there is something wrong going on. We must miss one step here.

![hiddenworkspaces](https://user-images.githubusercontent.com/13919702/52163203-5e1c8280-26df-11e9-99e5-7070a0ec3503.jpg)

**Comment by Draise14** [comment]
Each if these are a separate startup.blend file. When you save the startup, it writes a subfolder and it's sub file. When you compile you also need to overwrite these startup files. I got it going this way.

**Comment by ReinerBforartists** [comment]
Postponing. This is something for version 0.2

**Comment by ReinerBforartists** [comment]
Ah, i see. Many thanks for the hint :)

**Comment by ReinerBforartists** [comment]
Ah, i think i know how it is meant to work. Testing ...

**Comment by ReinerBforartists** [comment]
Gotcha. 

File New - 2D Animation, fix the layouts, save startup file. Grab startup file from appdata Bforartists\2.80\config\2D_Animation and put it into release\scripts\startup\bl_app_templates_system\2D_Animation.
File new - Sculpting, fix the layouts , save startup file. Grab startup file from appdata Bforartists\2.80\config\Sculpting ...

Fixed in master. Layouts have now the timeline again.
