### ISSUE TITLE
Firststart, Blender dark theme + Blender dark theme is now Bforartists theme

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#619]
Not sure if they belong to each other, but we have a problem in the themes. At first start we have still the Blender Dark theme as the default entry. And switching between the Bforartists theme and Blender Dark makes no difference. Either the Blender dark theme is currently corrupted. Or the Blender dark theme grabs the factory defaults ...

Needs investigation. We need Bforartists theme as standard theme, and Blender Dark theme working ...

![blenderdark](https://user-images.githubusercontent.com/13919702/52175668-650ec800-27a7-11e9-9f8b-f63f017cba85.jpg)

**Comment by ReinerBforartists** [comment]
Postponing for version 0.2.0. No need to fix everything at once.

**Comment by ReinerBforartists** [comment]
It is indeed as i have feared. The dark theme grabs the defaults. And our defaults are now Bforartists.

**Comment by ReinerBforartists** [comment]
Also fixed. Closing.

**Comment by Draise14** [comment]
Is this now in the master? 

_Finally finished moving, so will be back in the studio working a bit more normally and with less splintered work focus!_

Just tried out the BFA2 Alpha 0.1.0 and.. it started on Blender dark theme still. 
![bforartists_2019-02-06_15-47-10](https://user-images.githubusercontent.com/35357409/52372651-b11b7000-2a26-11e9-8152-e35fc49faec8.png)

**Comment by ReinerBforartists** [comment]
That's just the label of the Theme dropdown box, which is already fixed. But after the release. Will come with 0.2 then. 

Can't find the commit at the moment. But just look at the dropdown box color. Blender has grey, we have blue :)

**Comment by ReinerBforartists** [comment]
Ahaha, it's the second commit in this issue ^^
