### ISSUE TITLE
Keymap: unification of double operators due to new toolshelf - Feature Request

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#620]
## **Problem**
The new 2.8 toolshelf has introduced a new workflow and set of operators that do essentially the same as older operators, eg: transform, rotate, box select, etc. The issue here is that with that, you can only assign one hotkey to one kind of operator at a time, and they are double entries for the same workflow. 
Some of the older operators are more instantaneous, eg. Press W and the object moves immediately with the mouse. If I press W assigned to the transform tool of the new toolshelf, it will only activate the widget but not move anything, feeling broken - making transformation a two step process. Thew new system has great visual feedback and control, but it's more clunky sometimes. 

## **Proposal**
I have played around a bit and found a new function called "Click Drag" for hotkeys. Meaning, for more instantaneous workflows, I can use the instant old operator and still activate the correct transform widget tool at the same time. 
 
**Eg.** 
 1. Change the traditional **transform.translate** operator to Click Drag (now when I want to move something, I will click and move the mouse to move the object like in a normal workflow.)
![bforartists_2019-02-06_17-15-29](https://user-images.githubusercontent.com/35357409/52377851-0f9b1b00-2a34-11e9-9bd8-1005d326186f.png)
 2.  Now when I transform, maybe I want more visual feedback after moving, or I want to move visually with more control to limit an axis (instead of pre-thinking and memorizing multikey combos to limit an axis, which is ridiculous) Now add W as **press** to the transform tool/mode in the toolshelf. Due to the **press** functionality of the new toolshelf tool, now the transform widget is activated when I move traditionally - I get the instant transform feature of pressing W to move immediately when I move the mouse with the hotkey AND toggle the widget from the new toolshelf tool with a visual feedback of whatever mode I want and the extra options in the viewport from the widget. 
No more multikey combo workflows to memorize after activating the tool and no more keyboard gymnastics to do. 
![bforartists_2019-02-06_17-16-06](https://user-images.githubusercontent.com/35357409/52377852-10cc4800-2a34-11e9-9163-0b63659df8d6.png)

**Additional context**
This can be applied to some operators, most really, that have instant feedback from traditional operators and the toolshelf version with widgets that are not so instant (or vice versa). 

We could implement this with tasks for the keymap tool by tool that has a double entry for essentially the same system/workflow. 

Immediate application would be in 
- Transform, Rotate, Scale
- Selection toggle systems
- Extrude and other mesh edit tools
- etc

## Benefits
- We could unify two toolsets with one hotkey. 
- We could technically remove the double operator entry and/or rename the legacy operator to another
- We would make the workflow a little more user friendly by toggling toolshelf functionality with instant usability
- We would have iconized visual feedback of what mode we are in when using hotkeys
- We can allow the artist to not worry about secondary keyboard combo controls and lean more on the widgets
- We can make the toolshelf/hotkey workflow a bit more streamlined and pleasant/instant to use

**Comment by Draise14** [comment]
Here is a video me showcasing the feature request. 
https://youtu.be/tP7UxyXOyGw

**Comment by ReinerBforartists** [comment]
This would be a task for the experimental keymap.

I am in general still unsure what to do here. Two contradicting systems is simply a no go. Go explain a user why you have two hotkeys for the same operation that even acts a bit different ...

**Comment by ReinerBforartists** [comment]
This would also conflict with removing the double tool set. When you have a hotkey, then you need the tool for it in the ui. 

Oh what have they done here ...

**Comment by ReinerBforartists** [comment]
Hm, the solution with the mouse move would work for operators where you in fact move the mouse to perform the action. But what about other operators? Thinking about consistency here ...

Ideally we should be able to add two hotkeys to the tools in the tool shelf. The new one across the new tool shelf code, and the old one that goes directly to the operator. Then we could remove the old ones in the text menus.

This issue is for sure a very sensible one. It affects quite a few decisions for the future. And needs lots of testing and thinking. Dunno if we shouldn't let the Blender devs do this job instead. Or at least ask if they are even aware of the problem.

**Comment by Draise14** [comment]
I guess they will eventually migrate legacy functionality to the toolbar..... Over the next few years. 

We don't need to change anything and adapt to more gesture based usability and fix splintered operators without breaking anything, right now soon.

I suggest we make some rules for this.

**Rule 1.**
If a legacy tool and toolshelf tool have essentially the same functionality and one operator requires movement to use, define which tool is the gesture sensitive one to apply the click drag unification.
1. Add click drag hotkey to movement reliable operator (legacy tool, eg)
2. Add same press hotkey to passive visual feedback operator (toolshelf tool, eg)
3. Document and modify the documentation explaining what is the legacy and toolshelf tool and how to use the **one** hotkey for both with gesture control.  
4. Change UI name of legacy operator to be "legacy/quick _____ " to not make a double entry but two systems (activated by one minimalistic hotkey with gesture modifer)
5. Take note to eventually move the similar tool into the toolshelf and toolbar (to later have a subicon showing the legacy tool in the same toolshelf tool, then remove from the header menu, hotkey is **not** cyclic to unify functionality)

**Rule 2**
If a double entry tool has the same name and different functionality, define which is the most efficient workflow for the default hotkey:
1. Assign different hotkeys by using a modifier key to the secondary operator.
2. Change name of legacy operator to be "legacy/quick _____ " to not make a double entry but two systems (activated by two unique hotkeys)
3. Document and modify the documentation explaining what is the legacy and toolshelf tool and how to use the unique workflows for both. 
4. Take note to eventually move the different tool into the toolshelf and toolbar (to later have a subicon that can then **cycle** from the tool category on the same hotkey from the toolshelf to then remove from the header menu and not double up hotkeys)

The context to judge the difference in both legacy and toolshelf tools is by the post settings panels. Is the end result and settings the same or different? 

If yes, the same, Rule 1. If no, different, Rule 2. 

*I can do this job in the experimental map and learn how to rename tools in the UI in a branch if you want. Tool by tool tasks. Then I branch the documentation.*

Later in time we can learn how to move legacy operators into the toolshelf and create subicon toolshelf buttons for new/similar operators or remove legacy when they merge operator functionality (if ever).

**Comment by ReinerBforartists** [comment]
Sure. You can do some tests already, and see how it all works. This issue requires a completely independant branch anyways. This is nothing to develop in the master. Too much pitfalls.

Mh, this is connected with quite a few issues here in the tracker already where we have listed those double menu entries. I think one solution for the double menu entries of those tools is to make a legacy menu entry in the menu where this double menu enrtry resides. And then move the old operators that has an entry in the tool shelf already one by one into this legacy menu. That way the operators are still in the UI, and you can still change or assign a hotkey. But they are out of the way then.

I have to test this idea with the legacy menus first though. It has some pros and some cons.

For now i am still at consolidating BFA2 with what we had in BFA1. Icons everywhere and such things. Big changes like this one is for me still far away.

**Comment by ReinerBforartists** [comment]
Let's postpone this issue until we arrive at it. We have a tracker full of issues to solve first, and minimum one release before we need to pick up this one.

I will postpone the related double menu entry issues too.

**Comment by ReinerBforartists** [comment]
This task is too general. We need to catch them one by one and menu by menu.

Closing.
