### ISSUE TITLE
Toolbar - Tools with last operator problem

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#640]
I just discovered that performing a tool from the toolbar means to have no last operator in the 3D view. This affects for example creating a primitive. And makes as a consequence our toolbar in big parts disfunctional.

This has worked in Blender 2.79 and BFA1 before. So the cause is the Blender 2.80 code.

Question is if we even manage to get this one to work. This is deeply burried in the Blender C code. And it is changed, new code. 

![lastoperator](https://user-images.githubusercontent.com/13919702/52774006-9a83a300-303c-11e9-8c20-a69174a1af96.jpg)

**Comment by ReinerBforartists** [comment]
Bug reported to Blender https://developer.blender.org/T61529

**Comment by ReinerBforartists** [comment]
They won't fix it. It's no bug for the Blender developers.

**Comment by ReinerBforartists** [comment]
This one needs some further experiments. We have to implement our own way. And we night end in no solution at all. This problem is deeply burried in the new way how the Last operator is implemented.

**Comment by Draise14** [comment]
Oh dear. This is very annoying.. so scripting operator view context is now harder? Maybe scripting to run the Last Operator in sequence after each operator run from the toolbar will work around this (since it's run from the Edit menu originally anyway?) I can assign a hotkey and sure enough the toolbar can still pull that menu after funning the operator.

**Comment by ReinerBforartists** [comment]
Indeed, very annoying.

Scripting to display the Last Operator would mean to implement our own operators, for all tools in our toolbar. And it displays under the mouse then. That would be even more annoying. But feel free to do some experiments. I am open to any suggestion. I have currently no idea if and how to solve this.

**Comment by Draise14** [comment]
You'd think there should be some kind of uniform toggle to the Last Used operator panel to either be sticky/refresh or hidden. Must be still a WIP.

**Comment by Draise14** [comment]
Maybe you can add a button to the toolbar that calls up the Last Operator (floating albiet) but there in the UI for a mouseover (not hotkey, relatively clear position and predictability)

**Comment by ReinerBforartists** [comment]
Task already exists ;)

https://github.com/Bforartists/Bforartists/issues/641

The problem here is that the Blender devs are not unwilling here. But that the new concept does not allow to call the last operator panel when you call the tool from another editor. It is not longer just one last operator panel. But the 3D view has one, the UV editor has one, the Image editor has one ...

Luckily there is still the old way. Adjust Last Operation in the edit menu of the header. But this one is not integrated in the UI. That's a popup in C code. And so i am still lost what to do here.

**Comment by Draise14** [comment]
Is there any way to move the contents of the Last Operator panel into the Tools tab of the Properties view? Not only would it make sense to look there, but it might solve things?

![firefox_2019-02-22_09-24-39](https://user-images.githubusercontent.com/35357409/53248514-e610ff00-3683-11e9-86a9-c4547365d042.png)

**Comment by ReinerBforartists** [comment]
Tough one. I tried with 2.7 and Python already. With no success. Too much C code involved. We would have to study how everything is implemented. And also have a look what Blender devs have removed for 2.8 here. The last operator in the tool shelf in 2.7x was a global one like the one in the header, but implemented in the UI. Maybe we can resurrect it in the one or another way.

I personally hate to touch the C part in Blender. The code is bad commented if even, and weird. My C skills are still pretty weak, i would have to learn a lot here. And every change at the C code makes my life with maintaining the code between Blender and Bforartists harder. One little change can kill everything.

Either way, for me this task has a very low priority. Too much other tasks first.

**Comment by ReinerBforartists** [comment]
There is no solution to this dilemma. We have a last operator button in the toolbar already. That's the closest that we can get.

Closing.
