### ISSUE TITLE
Toolbar - File inport and output need to readd Icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#643]
## Issue
The file output and input lists have no icons in recent dev builds of BFA 2. 

![bforartists_2019-02-15_11-39-00](https://user-images.githubusercontent.com/35357409/52870812-afcd0000-3116-11e9-89c8-1a9b503173f0.png)
![bforartists_2019-02-15_11-41-56](https://user-images.githubusercontent.com/35357409/52870824-b52a4a80-3116-11e9-85e5-12439b458b5f.png)

## Task
Add icons to the file import and output drop down lists. 

## Reference
In BFA1 they had icons. 

![bforartists_2019-02-15_11-42-48](https://user-images.githubusercontent.com/35357409/52870880-d5f2a000-3116-11e9-8ea9-c6307af178d5.png)

**Comment by ReinerBforartists** [comment]
It's the same menu than the File Im and Export menus. Here the icons are also still missing.

![fileimandexport](https://user-images.githubusercontent.com/13919702/52871613-b7a69780-314a-11e9-8f16-bfe3b19370b3.jpg)

**Comment by ReinerBforartists** [comment]
Okay, most of them comes from the addons, and appends itself to this menus.

**Comment by ReinerBforartists** [comment]
gITF2 is a new standard format. And does not only need a new icon, but also a new entry in the toolbar. Making a own issue of it.

**Comment by ReinerBforartists** [comment]
Fixed in master.
