### ISSUE TITLE
Orthographic view has no grid

### ISSUE THREAD

**Issue by emilsvfx** [Bforartists/Bforartists#654]
In Orthographic view has no grid in view. It appears only with adjusting clip start. 
It`s fade in higher value grid fade low value.
In Blender there it works fine.

OS:Win10 
BFA:devbuild-18-02-2019

https://i.imgur.com/E1yfhmD.gifv

**Comment by ReinerBforartists** [comment]
Interesting catch. Thanks for the report. 

I have no idea what is going on. We use the same code than Blender here. Let's wait for the next merge. Possible that this issue was fixed shortly after the current merge.

**Comment by ReinerBforartists** [comment]
As expected, fixed with the newest dev build :)

Closing.
