### ISSUE TITLE
Pose Mode - Pose Menu - Bone settings sub menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#656]
I have no idea how the menu items works. I have no idea how this implementation works. There is no enum, just an empty class.

```
class VIEW3D_MT_bone_options_toggle(Menu, BoneOptions):
    bl_label = "Toggle Bone Options"
    type = 'TOGGLE'
```

Task: find out how the menu items are meant to work.
Task: implement a proper menu with icon buttons.

![bonesettings](https://user-images.githubusercontent.com/13919702/53283820-3b184800-374c-11e9-8477-d85a8d1c230b.jpg)

**Comment by ReinerBforartists** [comment]
I knew that i had this trouble before ...

https://www.bforartists.de/content/armature-edit-mode-armature-menu-iconize-bone-settings-menu

Unfixable and not to iconize because of the very special nature of this menu. Closing.

**Comment by ReinerBforartists** [comment]
class VIEW3D_MT_bone_options_toggle(Menu, BoneOptions):

-> Menu, BoneOptions calls the class BoneOptions here. That's why this class is empty.

Vital comment parts of the upper conversation, in case the old tracker vanishes completely: 

SUBMITTED BY DRAISE ON MON, 02/05/2018 - 14:22
These entries exist to "Apply
These entries exist to "Apply to Selection" compared to the double entry in the Bone tabs - which only applies to specific bone, the active in a selection. These weight systems also work in the pose mode, and should, as posing goes hand in hand with testing armature weights and modifying them, saving time always needing to toggle modes to change the weights. The bone lock also is used in posing.

All of these would be awesome if they were a button in the actual Bone tab areas with "Toggle ______ to Selection" instead of a sub menu - for a consistent easy access experience.

Or, I'd somehow try make the toggles in the Bone tab function as "Apply to Selection" out of default from the tab properties (if you only want it on one bone, just select that bone), like most software and remove the submenu entries all together.

Altimately, just find a way to "Apply to Selection" with those entries...  I wish everything in Blender behaved this way, including tranform panels, clear keyframes, etc; it makes me sad they only seem to make this work here in these entries and with no explanation anywhere...

SUBMITTED BY REINER ON MON, 02/05/2018 - 17:52
Thanks Draise,

I see. Haven't noticed that you can do multiple objects that way. So this is nothing to remove, and nothing redundant. But even something to optimize if possible.

To put it into the properties is impossible. Those settings are single object related. We could put it into the tool shelf instead in a future build. Will keep this one in mind. And this task stays of course open.

SUBMITTED BY REINER ON THU, 02/08/2018 - 12:02
This one is unfixable. We

This one is unfixable. We cannot give this menu icons it seems. I see at least no way without to break the functionality. And writing our own operators for the job is no alternative here.

At least i understand the code a bit better now. This special toolset iterates through all selected bones. And this means we cannot simply grab the props from the tool shelf, and put it into a menu. This one just works for the active bone. Not all selected ones.

Giving up. Closing. It remains as it is.

**Comment by Draise14** [comment]
Just to mention, with some study I have found these entries to be a double entry. 

1. By present ALT then using the toggles in the preferences panels on the bone selection does the same. 
2. These menus do the same but without pressing ALT. They just apply the same toggles from the bones panels to selection. 
3. These menu entries are inconsistent with the rest of the UI workflows - hold ALT to apply to all in selection with all common attribute changes is the norm, these menu workflows are not. 

## Solution
Either pressing ALT needs to be explained that this modifier changes attributes to all in selection in your hotkey helper add-on (I only learnt this after years of use by accident by a stray comment in Rclickselect) and the menu removed.
or
The tooltips need to explain the ALT modifier for the consistent workflow with the rest of the UI and make the menu defunct. 

Could be new tasks.

**Comment by ReinerBforartists** [comment]
Hm, i don't even see a way to change the tooltip here. This would be something bigger i fear.

But we can keep it open if you want. I will postpone it though. First let's finish the chapter cleaning up after merge.

**Comment by ReinerBforartists** [comment]
I still don't see a way to fix this. Yes it's a double entry. But there is a ton of other double entries in this scope in the 3D view so that you don't have to dive into the properties editor all the time.

Closing this one. It remains uniconized, and we keep it the way it is.
