### ISSUE TITLE
Greasepencil object - make Interpolate and Sequence hotkeys consistent across modes

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#667]
In Edit mode Interpolate and Sequence have a standard hotkey. In Draw mode not. Inconsistent. Either have this hotkey in all modes, or in none. This feature isn't used often from what i know, and has odd hotkeys. So i would vote to remove it.

![interpolate](https://user-images.githubusercontent.com/13919702/53679546-0701d180-3cce-11e9-99ae-5b81288d1552.jpg)

**Comment by ReinerBforartists** [comment]
Ah, and i see a name inconsistency here with delete. In Edit mode it's Delete Frame(s), in Draw mode it's Delete all active frames.

**Comment by ReinerBforartists** [comment]
@Draise, do you want to have a crack at this? It requires to update the startup.blend too ...

**Comment by Draise14** [comment]
Ehm.. ok. Sure. 

For the minimal BFA map, yeah, remove. 
For Full BFA map I'll make consistent.

**Comment by ReinerBforartists** [comment]
Um, we don't have a full BFA map anymore :D

**Comment by Draise14** [comment]
Ah, true, there is no full BFA map anymore. I guess I would have to rebuild that one oneday? Or is that just the Experimental?

**Comment by ReinerBforartists** [comment]
No, experimental is to test changes at the standard keymap. You could rebuild a full keymap if you want. Better said have a look to port the old full keymap from Bforartists 1. But i am not sure if this is really necessary. I leave this decision into your hands :)

**Comment by ReinerBforartists** [comment]
Before progressing, please make a merge of the master into your branch. Lots has changed, and especially the changes at the startup.blend would make trouble with your old settings.

**Comment by ReinerBforartists** [comment]
I'll reclaim this task here. It blocks too much other tasks.

**Comment by ReinerBforartists** [comment]
Fixed in master
