### ISSUE TITLE
Close the footer in the default layout

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#675]
We have put the info bar into the toolbar. Means we can get rid of the footer. Nobody needs this cryptic mouse symbols ...

Let's close the footer at least in the default layout.

![statusintoolbar](https://user-images.githubusercontent.com/13919702/53751238-25bdbf00-3eac-11e9-925d-fdec7c19e7f2.jpg)

**Comment by Draise14** [comment]
I can do this.

Ehm, so close the bar that shows the UI helpers? Isn't that artist friendly? 

Just to confirm, I collapse this area?:
![bforartists_2019-03-04_12-55-22](https://user-images.githubusercontent.com/35357409/53752521-ca280d00-3e7c-11e9-8498-bff83280d7fa.png)

**Comment by Draise14** [comment]
Also to confirm. 

**Question 2:** 
Do I collapse in all workspaces? Or some?

**Comment by ReinerBforartists** [comment]
Hm, so you want to keep it? Then i'll hide it in the toolbar again. We don't need it double.

**Comment by ReinerBforartists** [comment]
Okay, let's keep it open. I'll make the info string off by default in the toolbar then.
