### ISSUE TITLE
Workspaces - toolbar not present in some layouts

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#676]
## Issue
Some of the layouts don't have a consistent file/misc toolbar. 

## Proposal 
Add the toolbar to all layouts. 

 - UV layout has the file toolbar to the right, instead of the full length 
 - Shading doesn't have the toolbar
 - Compositing doesn't have the toolbar
 - Rendering doesn't have the toolbar

![bforartists_2019-03-04_12-32-25](https://user-images.githubusercontent.com/35357409/53751514-6d2b5780-3e7a-11e9-8def-f5e4a7eb4e45.png)
![bforartists_2019-03-04_12-32-28](https://user-images.githubusercontent.com/35357409/53751515-6d2b5780-3e7a-11e9-9af4-59adc6b2569e.png)
![bforartists_2019-03-04_12-31-19](https://user-images.githubusercontent.com/35357409/53751516-6d2b5780-3e7a-11e9-91ff-b5af4e5e9316.png)
![bforartists_2019-03-04_12-31-24](https://user-images.githubusercontent.com/35357409/53751517-6d2b5780-3e7a-11e9-9220-f70a7dc4e901.png)

## Benefits
So the file toolbar is available in all new layouts with consistency for quick muscle memory in all layouts/workspaces. 

# Task
Add toolbar to layouts without toolbars.

**Comment by ReinerBforartists** [comment]
Do it!

Maybe you can also catch this problem here. But you need to do a merge first. I have commited the info string change before a few minutes ... : https://github.com/Bforartists/Bforartists/issues/675
