### ISSUE TITLE
Limit remesh octree depth?

### ISSUE THREAD

**Issue by EternityForest** [Bforartists/Bforartists#70]
Hey! Not sure if it's a blender or a b4artists issue, but I just noticed that it's fairly easy to increase the octree depth when remeshing to a value high enough that everything hangs for quite a while. Maybe those settings work fine on really powerful machines, but it seems like some kind of confirmation dialog would be useful for parameters that cause issues when cranked up.

**Comment by ReinerBforartists** [comment]
Hi EternityForest,
Thanks for the repoft. That's a Blender issue. So you should report it to the Blender developers.
Kind regards
Reiner
