### ISSUE TITLE
Align Props left

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#704]
This is something that tickled me, but i didn't know why. Until i realized that some of the props are now right alligned, with the checkbox at the right side, but some are still left aligned. Which is inconsistent. Clearly to see here for example, where i have put some props from the regular menu into the options menu. Now we have left aligned props and right aligned props mixed. And guess which ones are better readable ...

This is most probably a monster task. Nearly all props in the Properties editor and preferences are aligned in the new way. And i am not sure if we can catch the baddies easily. It's all this *new* UI code that should *improve* the readability. But does in real the exact opposite, as usual.

![readability](https://user-images.githubusercontent.com/13919702/54668992-8d048180-4af0-11e9-8f8d-a3dde12ce055.jpg)

**Comment by ReinerBforartists** [comment]
Postponing for now.

**Comment by ReinerBforartists** [comment]
Unfunny: in the panels up right the alignment of the props happens also right sided, for same code ...

![align](https://user-images.githubusercontent.com/13919702/54671536-63e6ef80-4af6-11e9-99c3-24f9829e9e9d.jpg)

**Comment by Draise14** [comment]
These panels indeed are so bonkers, I would love to make these more visual and consistent too...... What is their code like?

**Comment by ReinerBforartists** [comment]
I have yet to find out. You know that i am a single minded guy, just working at one task at a time. And i haven't arrived at this one yet :)

You can have a look into the class. Go to scripting layout. Hover with the mouse over the menu, right click, and choose edit sorce. The right file should open. Now find the class in this file.

![spacetopbar](https://user-images.githubusercontent.com/13919702/55378985-9394ef00-551b-11e9-915b-db9140a3ce9e.jpg)

I expect that it has something to do with how the props are arranged by code here in the python file. But it could also be a C problem. As told, i would have to dive into the problem.

**Comment by ReinerBforartists** [comment]
layout.use_property_split = True splits the props into a text part and the prop part. 

Example slider with layout.use_property_split, and without.

![false](https://user-images.githubusercontent.com/13919702/55388058-dc0bd700-5532-11e9-9994-812e35719c5a.jpg)

![splittrue](https://user-images.githubusercontent.com/13919702/55388069-e29a4e80-5532-11e9-8b26-b568fbaa0390.jpg)

**Comment by ReinerBforartists** [comment]
Not sure if this also counts for the panel code from above.

**Comment by ReinerBforartists** [comment]
Yes it does. There are a few problems then though when we simply turn it off ...

![propsplit_true](https://user-images.githubusercontent.com/13919702/55389649-f98e7000-5535-11e9-9738-9830834413b2.jpg)

![false](https://user-images.githubusercontent.com/13919702/55389656-fd21f700-5535-11e9-9e41-3d98cdbf2fdc.jpg)

**Comment by ReinerBforartists** [comment]
Enough investigation for now. First let's empty the tracker a bit more ...

**Comment by ReinerBforartists** [comment]
We have to make different tasks out of this one. The different panel content differs too much. And it's lots of panels to change.

Let's create a few tasks here.

**Comment by ReinerBforartists** [comment]
Whole preferences has right aligned content ...

![prefs](https://user-images.githubusercontent.com/13919702/55546957-938a2000-56d0-11e9-9b6f-9ac72a0d38a9.jpg)

**Comment by ReinerBforartists** [comment]
Have it 

H:\bforartists\Bforartists\source\blender\editors\interface\interface_widgets.c , line 1882

Here they align the splitted props right. Easiest method is to choose align left here too. Then we have this result. But needs a bit more experimenting. 

![alignleft](https://user-images.githubusercontent.com/13919702/55686670-4a51fe80-5964-11e9-98df-d53d7059e076.jpg)

**Comment by ReinerBforartists** [comment]
Hm, now i kow why the Blender devs have aligned the text right. Sometimes the gap between the text and the edit box can be pretty large.

Let's have a look if we can change the ratio between text and edit box size a bit ...

**Comment by ReinerBforartists** [comment]
Ah, can't do this. Then it doesn't align with split content anymore. Two buttons besides ...

**Comment by ReinerBforartists** [comment]
Or we use the old method ...

![oldmethod](https://user-images.githubusercontent.com/13919702/55705919-35b34c00-59e0-11e9-8e2b-318217a5fd74.jpg)

**Comment by ReinerBforartists** [comment]
This was the general alignment of the text.

Now we have to check for all checkbox props, editor by editor ...

**Comment by ReinerBforartists** [comment]
3D View ...

**Comment by ReinerBforartists** [comment]
To have it here too. animatable checkboxes looses the add keyframe button when not split. 

Problem seems to reside in source\blender\editors\interface\interface_layout.c
UI_PROP_DECORATE

But my C fu is too weak here to find my way through the uncommented code.

Leaving animated checkboxes out for now. They remain right aligned.

**Comment by ReinerBforartists** [comment]
Separated this issue ...
Align props with animate property left #794

**Comment by ReinerBforartists** [comment]
Closing this task. Main work is done, and the trouble issue is separated.
