### ISSUE TITLE
Add icon_geom.blend to the repository

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#709]
Everything required to create Bforartists should be included in the repository. This includes icon creation. 

Task: Add icon_geom.blend to the repository. It is the blend file with which you create the big icons for the new tool shelf.

**Comment by ReinerBforartists** [comment]
Added in master

**Comment by ReinerBforartists** [comment]
Hm, the blend file is missing again. So reopen it.

**Comment by ReinerBforartists** [comment]
File is here: And the svn link to the blend file is here: https://svn.blender.org/svnroot/bf-blender/trunk/lib/resources

**Comment by ReinerBforartists** [comment]
Hm. We will not use the blend file, but create single images if possible. Which would make this task obsolete. 

Postponing until we managed (or not) to write a scipt to create single dat files. See here

https://github.com/Bforartists/Bforartists/issues/1318

**Comment by vic3t3chn0** [comment]
Sure. I am taking care of it. Next release.

**Comment by ReinerBforartists** [comment]
I think you misunderstand the issue ^^

Blender devs creates the dat icons from two sources by a script. The one is from a svg file, the other is from a blend file. We wanted to include this blend file into the repository now, like we already did with the svg file.

But this would blow up the repository since every change of this blend file would add the size of this file to the repository. It's 20 mb when i remember right. Make ten changes and we are at 200 mb already ...

Now the idea is to create a script that creates one dat file from one source image. So that we can bypass this crazy blender way of creating the icons. That way the artist can decide how he creates the png files from which the icons gets created then. One by one.

**Comment by ReinerBforartists** [comment]
Hm, but we could put it into the file repository. Mundayz, brainz not working ^^

**Comment by ReinerBforartists** [comment]
Uploaded it to the file repository here: https://github.com/Bforartists/files/commit/d89b95c3cb8c2367ccd657fc3a798963eaaf07ce

Fixed
