### ISSUE TITLE
Bforartist crashes during Dyntopo sculpting

### ISSUE THREAD

**Issue by Petresko** [Bforartists/Bforartists#731]
Bforartists frequently crashes when sculpting with Dyntopo enabled. At first it seemed that it happens when using Undo , but it also crashes on LMB releases.
There's no error message - the software simply closes.
Other times Bforartists crashes with an "Bforartists stopped working" error and in the console a message pops up saying "Couldn't unmap memory".

Could this be happening because of lack of RAM?
If so is there a way to allocate more RAM?

PC Info :
Win7 64-bit
Intel(R) Core(TM) i7-4720HQ
2.60Ghz
8GB RAM
NVIDIA GeForce GTX 950M

**Comment by ReinerBforartists** [comment]
Hi Petresko,

Thanks for your report. Yes, running out of ram could be one cause. But it could also have other causes, which we don't have nailed yet.

Dyntopo is also under Blender not the most stable feature, unfortunately. This is known. And we from Bforartists just modifies the UI. We don't touch the core features of Blender. We simply don't have the resources to fix broken Blender features too.

This means there is little that we can do here, sorry. You could try to reproduce the problems in Blender, and report it to the Blender developers then.

Kind regards

Reiner
