### ISSUE TITLE
Update the keymap to latest Blender changes

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#733]
https://devtalk.blender.org/t/1-april-2019-upcoming/6353

> The view3d.select_or_deselect_all operator has been removed, replaced by a deselect property on view3d.select. Keymaps will need to be updated to account for this.

Hmmmm ....

**Comment by Draise14** [comment]
I also fixed the experimental keymap, now it works fine. I committed it to my branch and made a pull request for it.

**Comment by ReinerBforartists** [comment]
Well done.
