### ISSUE TITLE
Reorder all select menus to have the same order

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#750]
Blender 2.80 has brought us the same mess than we had before the fork. The select menus are inconsistent in order and look. Doesn't really help the muscle memory.

For example, in some menus the more/less menu items is in a sub menu. In other it is not. Or dopesheet vs graph. In one the Linked is at the end, in the other in the middle of the menu. Video sequencer has less more instead of more less order. And so on.

Task: Reorder all select menus to have the same order where possible.

![selectmenus](https://user-images.githubusercontent.com/13919702/55667704-34f3ac00-5860-11e9-90ae-2031b9deeee2.jpg)

**Comment by Draise14** [comment]
Phew, what a mess.

**Comment by ReinerBforartists** [comment]
Yes, they have carried it over from Blender 2.79 :)

**Comment by ReinerBforartists** [comment]
Let's tackle this one

**Comment by ReinerBforartists** [comment]
Fixed in master.

Order is now the same everywhere where possible. Only the more / less menu in edit mode makes a difference. The menu would become too long with putting this six operators also into the main menu.

![selectmenusrefine-after](https://user-images.githubusercontent.com/13919702/56454523-71400580-6352-11e9-9908-6aaa749a2f49.jpg)
