### ISSUE TITLE
Iconsheet. Make the monochrome icons colored.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#751]
We need to create colored versions of the Blender 2.80 icons to make them more consistent with the rest. 

If this requires to redo the icon, or if we simply recolor the existing icon will be a case by case decision. And the mouse icons can remain as they are. 

Most of the monochrome icons are at the right side of the sheet.

![monochrome](https://user-images.githubusercontent.com/13919702/55667791-586b2680-5861-11e9-82c3-d4ff55fd1867.jpg)

**Comment by ReinerBforartists** [comment]
Off we go. First row ...

**Comment by Draise14** [comment]
Can't wait to solidify silhouette get rid of all the line-art..

**Comment by ReinerBforartists** [comment]
THREE_DOTS seems not in use. Let's remove it, and have a look if Bforartists moans at compile somewhere.

**Comment by ReinerBforartists** [comment]
The align icons will remain as they are. This is not to improve. 

![alignicons](https://user-images.githubusercontent.com/13919702/59048879-16715780-8887-11e9-8505-b564022f8e58.jpg)

**Comment by ReinerBforartists** [comment]
Haha, not so easy. This are the crap icons from Blender, with a this odd structure that you can't even scale them proper. Okay, let's redo them.

**Comment by ReinerBforartists** [comment]
The file new icon is also one of those icons that exists in many different flavours -.-

**Comment by ReinerBforartists** [comment]
Same for locks ...

**Comment by ReinerBforartists** [comment]
Okay, grease pencil icons needs a fix. I was a bit too fast with making them the same ...

![gp_problem](https://user-images.githubusercontent.com/13919702/59566403-2eec2980-9060-11e9-8703-411e2adf7fbb.jpg)

**Comment by ReinerBforartists** [comment]
That's better ...

![fixed](https://user-images.githubusercontent.com/13919702/59585905-e07f6f00-90e1-11e9-84f8-756f895dbda1.jpg)

**Comment by ReinerBforartists** [comment]
Hm, the outliner top hierarchical icons are all orange. Except our lamp ... XD

**Comment by ReinerBforartists** [comment]
Better. Fine tuning will follow when all icons are converted. But at least the general color coding works now.

![troubleicons](https://user-images.githubusercontent.com/13919702/59667904-d3cd4a80-91b7-11e9-89b8-a43f992895db.jpg)

**Comment by ReinerBforartists** [comment]
FILE_3D and FILE_CACHE seems to be obsolete icons. It's nowhere used. And i have never ever seen this icons in the ui somewhere. But with the crazy "plus minus current icon" blender system you never know ...

![nottofind](https://user-images.githubusercontent.com/13919702/59866184-43dffa00-938b-11e9-916e-f7edf3d71e60.jpg)

**Comment by ReinerBforartists** [comment]
And done. Fixed in master.

The single base files are added to the file repository here: https://github.com/Bforartists/files/tree/master/iconset_bforartists_2
