### ISSUE TITLE
Video Sequencer - Select menu needs icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#753]
VSE misses icons in general. Let's start with the select menu.

![vsenoicons](https://user-images.githubusercontent.com/13919702/55667824-bb5cbd80-5861-11e9-9ab4-79dad2054f4e.jpg)

**Comment by Draise14** [comment]
I'm going to first check for necessary icons and created ones, then make the missing ones. Then when you are ready @ReinerBforartists , I can give them to you here to add to the icon sheet (since you are working on it)?

**Comment by ReinerBforartists** [comment]
Yes.

**Comment by Draise14** [comment]
@ReinerBforartists , since you've done the icons mostly now, should I also do a commit of the code to add these icons to the repository?

**Comment by ReinerBforartists** [comment]
Mh, icons in the file repository should mirror what is already in the sheet. So the better thing would be first to add the icons to the sheet. Also, the icons in the file repository should contain two files, the single svg, and the base file from which you created them. In my case a png file.

As told before, attach the icons that you need here in this issue. I will add the icons to the sheet and the UI_icons.h file then, and also to the file repository.

I am by the way ways not done with the icons. We have now 250 of 1400. I am just having a break from the icons for a few days. To fix some other issues first before i return to the icons.

**Comment by Draise14** [comment]
Ah yeah, know the workflow. 

So, still needs work and you're still on the Iconsheet. 

So the answer is no, don't compile them into the repository, just upload the icon files here. Got it.

**Comment by Draise14** [comment]
![bforartists_2019-07-05_14-49-48](https://user-images.githubusercontent.com/35357409/60742796-669a1300-9f34-11e9-949a-709be707df9e.png)

Menu has changed per 2.8 thingies....

**Comment by ReinerBforartists** [comment]
We need to get this task done at one point ...

**Comment by ReinerBforartists** [comment]
Select handle and channel needs new icons. Currently a place holder icon ...

![handlechannel](https://user-images.githubusercontent.com/13919702/67844014-4b639c80-fafd-11e9-8df4-dcc6c25e1457.png)

**Comment by ReinerBforartists** [comment]
Hm, do we really need unique icons here? A select mouse pointer should do the trick already.

**Comment by ReinerBforartists** [comment]
Fixed in master
