### ISSUE TITLE
Video Sequencer - Strip menu needs icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#765]
We need some icons here.

![sequencerstripmenu](https://user-images.githubusercontent.com/13919702/55671909-2f648900-5895-11e9-9622-5cbbf37b225b.jpg)

**Comment by Draise14** [comment]
Maybe I can learn how to put in icons with this task? I use the VSE a lot.

**Comment by ReinerBforartists** [comment]
Have a look here :)

https://www.bforartists.de/data/tuts/Icontutorial.pdf

**Comment by Draise14** [comment]
Hey cool. I added an Icon to the UI. It already existed so.. piece of cake! The tutorial is really helpful, bit all over the place - yet I like how more info is better. I wish everything was like this. 

![bforartists_2019-04-11_11-58-57](https://user-images.githubusercontent.com/35357409/55976250-56cea380-5c51-11e9-9a42-c80ff2058c16.png)

Looking at the sheet I've found a lot of design inconsistencies everywhere... but what a huge artistic feat it would be to design consistent icons across the board! 

Now I'll.. try put in existing icons first then create any new ones later.

**Comment by ReinerBforartists** [comment]
Gratulations :)

Yes, There's a ton of inconsistency. Starts with the icon names already as you may found out with the copy icon already ^^

I think somebody is already working at a new icon sheet. But not sure. He is so quiet at the moment ^^

**Comment by Draise14** [comment]
Oh there is someone working on it? The new design for all should be fun. 

Re-opened. Hang on, I haven't finished nor committed this one yet.

**Comment by Draise14** [comment]
Who is assigned to the Icon redesign?

**Comment by ReinerBforartists** [comment]
I hate the close button XD Sorry ^^

Somebody at the forum. Rayman. He hasn't created a github account yet. So not sure if he is still working at it. It's a monster task for sure.

**Comment by Draise14** [comment]
Ah right, yeah, would make sense. I'll use another instance of Inkscape to do the creation, then copy/paste in. No issue. 

Would be great to see Rayman here on Github.

**Comment by ReinerBforartists** [comment]
You can drag svg files directly into the sheet. No need for copy n paste.

**Comment by ReinerBforartists** [comment]
Sorry for poking, but any progress here? The task is blocking all the other tasks where icons are missing Makes no sense to add new icons when you commit an old icon sheet then :)

**Comment by Draise14** [comment]
Yes. I have done progress. But in other SVG files locally. Go ahead and do icon work. I'll merge in later. I'll keep my eye out on what is happening.

**Comment by ReinerBforartists** [comment]
Damn, have i closed it again? The close button is killing me :D

**Comment by Draise14** [comment]
No problem, when you are done, I'll paste and then do the code part, nothing will be lsot. Right now I'm just designing, trying to understand the BFA icon designs.

**Comment by ReinerBforartists** [comment]
A few colors, no gradients, and whatever fits. There are currently no design rules. We need to make them from scratch anyways ^^

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/56935625-ea103180-6ab7-11e9-98ac-14144297d43d.png)

I have finished making the icons for this header entry. I'm now ready to do the code part. @ReinerBforartists, are you working on the icons file anywhere? 

*I've noticed I should also probably re-organize these menu's eventually...*

**Comment by ReinerBforartists** [comment]
Yes i do. I have just yesterday committed a new icon. I wanted to do the icon related issues so that you can do this task here. But i can do some other things now until you have finished this one.

**Comment by ReinerBforartists** [comment]
I would say let me finish the current icon related tasks first. Then you have all the time in the world.

**Comment by ReinerBforartists** [comment]
Okay, finished all icon related tasks in the tracker for now. You have green light :)

**Comment by Draise14** [comment]
Ok, giving this a go. I need to install python.

**Comment by Draise14** [comment]
![powershell_2019-05-01_20-11-14](https://user-images.githubusercontent.com/35357409/57052516-5b351d80-6c4d-11e9-99f9-d62b18d9a856.png)

I hit an error when trying to make the icon DAT files. I have updated the **UI_icons.H** file, I have updated the **blender_icons.svg** - I have run command promt (and Windows Powershell) to make it do the bat things.. and nope. 

Gonna try update Python 3.x.x and check and see... and triple read again. I must be missing something.

**Comment by Draise14** [comment]
I switched to the master to see if that fixed it, same issue. Looks like a file is getting lost, like my environment variables are wrong?

**Comment by Draise14** [comment]
I have been trying to run the **python blender_icons_update.py blender_icons.svg** command from command prompt in the \release\datafiles folder, but without any luck. I get these errors: 

`FileNotFoundError: [WinError 2] The system cannot find the file specified`

Line 10 (in the **blender_icons_update.py**)  when it does the **run(cmd)** in line 33. 
`subprocess.check_call(cmd)`

Something is wrong with the subprocess. What is the fix?

I have correct Python versions installed (2.7 and 3.5.0), Blender 2.79b installed, and... what is missing?

**Comment by ReinerBforartists** [comment]
The errror says it all. You need Python 3.70 meanwhile. 3.50 is too low :)

Seems that i need to update the tutorial ...

**Comment by Draise14** [comment]
![explorer_2019-05-02_09-35-01](https://user-images.githubusercontent.com/35357409/57083063-940cdb00-6cbd-11e9-8cf1-fe1298e0bc3a.png)
I updated uninstalled and re-installed to 3.7.0 and 3.7.3 and still have the same error. This is frustrating. The file exists, the paths exist, python exists...

**Comment by Draise14** [comment]
![powershell_2019-05-02_09-52-15](https://user-images.githubusercontent.com/35357409/57085047-0df29380-6cc1-11e9-890f-9f9aae4904f4.png)
I tried installing Python 3.7 to a custom path, still no fix. But when I set the Path environment variables things are ok... 

**You need the repository.** - Done, tried on Master and branch and files reverted to originals
**You need to have Python 2.7x and 3.xx installed.** - 2.7.9, 3.5.3 and 3.7.0 installed, in default. 3.7.3 installed on custom C:\Python37
**You need Inkscape.** - Installed 0.92.4 x64bit - then added that to the Path Environment Variables (didn't work without)
**You need to have Blender installed to convert the icons from svg to dat** - Blender 2.79b installed by it's *.exe to custom folder (not default) - and I added that to the Path Environment variable (as they also didn't add and wouldn't work without)

So.. the tutorial needs to make sure the requirements have the environment paths correctly placed.

**Comment by ReinerBforartists** [comment]
Glad you got it working.

I think i have described the steps with the environment variables in the general compiling tutorial somewhere. Do you want to update the icon tutorial ?

**Comment by Draise14** [comment]
I must have read it half a dozen times and missed the memo, so maybe yeah. I think I can update it sure, why not? It's in the Files repository, right?

**Comment by ReinerBforartists** [comment]
Yes it is located here: https://github.com/Bforartists/files/tree/master/tutorials

For me it's sometimes a bit difficult to catch all necessary steps for the tutorial. I have set up everything before years ...

**Comment by Draise14** [comment]
I'll do it after a successful compile and closing this task.

**Comment by Draise14** [comment]
I have found another difficulty:

`operator_menu_enum`

How do you iconize these ones?

**Comment by ReinerBforartists** [comment]
This is done in the C code.

You can either create a python menu by using the single operators. That's what i have done in the past for some menus. Or you search for this special enum, and change the icons there.

The downside of making a new python menu is that changes at the C code by the Blender developers may be lost by us. So nowadays i change the enum where possible.

Changing icons in a c enum is a bit more tricky. Usually empty icon slots are defined by a zero in the expression. Different from a python menu, where you just add the icon name, you have to add a ICON_ in front of the icon name. And the black magic here is to find the enum at all. Search for the tooltip. Then you usually also find the enum ...

Here you can find a example commit where i have added three new icons to such a enum. Should make things more clear: 

https://github.com/Bforartists/Bforartists/commit/16ea465d4795379f0c8d35f2f88cdbe964428b2c

**Comment by Draise14** [comment]
Ah, ok I'll do it in the python part. Ifgured out how to convert them to `layout.operator`. The C does look messy right now.

**Comment by ReinerBforartists** [comment]
Just try it, it is not this hard, it's just new :)

I can have a look at it too if you want.

**Comment by Draise14** [comment]
![atom_2019-05-02_12-22-44](https://user-images.githubusercontent.com/35357409/57094006-fe7d4580-6cd4-11e9-8dd1-aba26f43cf0b.png)

I had a quick look at the C. Found where the operator gets defined, and the tooltip. I can do it now. but now.. I don't want these in their own menu, 3 levels deep. As in: #843 So I will do the python version and add the icons that way up one level.

**Comment by ReinerBforartists** [comment]
Okay. Your decision :)

**Comment by Draise14** [comment]
![bforartists_2019-05-02_14-58-30](https://user-images.githubusercontent.com/35357409/57103202-c680fd00-6cea-11e9-8990-855c906402ab.png)

Ok! Got the Enumerated version working. 

But.. now I've found a whole bunch of hidden option in the menu that change on selection. These would also be part of this task no? 

![PureRef_2019-05-02_15-03-55](https://user-images.githubusercontent.com/35357409/57103508-938b3900-6ceb-11e9-8845-48debd7e7872.png)

Back to the drawing board.

**Comment by ReinerBforartists** [comment]
You should make it an extra task. It becomes too much at once.

Golden rule, just fix what is part of the current task. Don't fix all other problems that you stumble across while fixing this issue. Make them a own issue instead. And then fix them one by one.

**Comment by ReinerBforartists** [comment]
Draise, have you already started to create new icons and modified the blender_icons.svg? I fear you need to do a new pull, sorry.

To fix this bug here i had to add the missing three icons. https://github.com/Bforartists/Bforartists/issues/846

**Comment by Draise14** [comment]
I have already done this task, technically. I'll make a new task for the other dynamic entries, and merge #846, then commit and close this.

**Comment by Draise14** [comment]
Ok, merged. Had my backups elsewhere.. I guess my paranoid backup system is working. I'm re-generating the icons, will re-compile, test, then commit my branch and close this task and #843.

**Comment by ReinerBforartists** [comment]
That's why i had linked the task. You could've simple grabbed the iconsheet and the changes in the code from there :)

Icon recreation is of course required.

**Comment by Draise14** [comment]
Ok, compiled on full and lite and no issues. I found that Master had new VSE caching included and that was not merged in. I also fixed up the icon sheet, no all is working well, atleast for me. I committed only this task.

**Comment by Draise14** [comment]
Oops committed the wrong space_sequencer.py file, now this last commit has the correct version with the correct shorthand.
