### ISSUE TITLE
NLA - marker menu - put prop into sidebar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#771]
Settings doesn't belong into the text menus. Put it into the sidebar.

![nlamarker](https://user-images.githubusercontent.com/13919702/55672159-01cd0f00-5898-11e9-86c3-406c7463c992.jpg)

**Comment by ReinerBforartists** [comment]
Hm, this marker menu is a generic menu that exists across all animation editors.

This means we need to add the new marker panel in all animation editors.

**Comment by Draise14** [comment]
Yes! .. for some reason I lived with this not being consistent everywhere and it slipped my mind, but it would make a lot of sense to have the marker panel everywhere.

**Comment by ReinerBforartists** [comment]
This task is just about the checkbox ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
