### ISSUE TITLE
Insert keyframe needs a home

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#775]
Hotkey only functionality is no go. 

Insert keyframe is a popup menu under the mouse. No menu entry yet from what i can see. This needs a home somewhere. The object menu is pretty crowded already though. So not sure what to do here.

Ideas?

![insertkeyframe](https://user-images.githubusercontent.com/13919702/55703560-3c3ec500-59da-11e9-8b9c-490d243da878.jpg)

**Comment by Draise14** [comment]
I would put this by the Keying sets and/or the record button in the timeline and dopesheet editor, or in the animation toolbar as an optional latter - this is animation based, and now all attributes has a button to hit record, this panel is more like a sub-level of a keyingset. I would not place this in the 3D View, but the animation views that correspond.

**Comment by ReinerBforartists** [comment]
This menu must stay in the 3D view to remain functional. That's unfortunately the way it is.

The animation views does have this menu already:

![insertkeyframe](https://user-images.githubusercontent.com/13919702/55732309-0fab9d00-5a1c-11e9-9a65-6b5b573a4410.jpg)

**Comment by Draise14** [comment]
Oh right. In the....... Transforms panel as a button? 

Divide the object panel up a bit with a new header like "Transforms"  menu with all snap, origin, Delta, apply transform, animation and others?

**Shoots in the dark**

**Comment by ReinerBforartists** [comment]
It's a tool, not a setting. So it should be at the left.

**Comment by ReinerBforartists** [comment]
Haha, already exists. \o/

Closing. Nothing to fix here.

![insertkeyframe](https://user-images.githubusercontent.com/13919702/56116514-4c205100-5f66-11e9-936a-d8588ee39ca5.jpg)
