### ISSUE TITLE
Timeline editor - put active keying set back into the header

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#776]
Adding a keying set should not be hidden in a sub menu. Put it back into the header. That's where it was in BFA1.

![addkeyingsetprop](https://user-images.githubusercontent.com/13919702/55704076-a015bd80-59db-11e9-8381-a91633a24dc7.jpg)

**Comment by Draise14** [comment]
Oh yes please.

**Comment by ReinerBforartists** [comment]
Fixed in master.

What was options is now at the right. Makes more sense to me. Consequently we should also put the clock icon at the right. But ...

And now i know why they have hidden this away. When you insert a keyframe with hotkey I, then no keyingset is created. So we have two contradicting keyframe concepts here. 

Anyways. The red autokeyframe button setting requires a keying set. So it makes sense to have this controls at top UI level.

![insertkeyframe](https://user-images.githubusercontent.com/13919702/56115818-9e607280-5f64-11e9-9504-8a70c460d82c.jpg)
