### ISSUE TITLE
Timeline editor - put options at the right side

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#777]
In all other editors the options are at the right side. In the Timeline it is at the left side. Inconsistent.

![optionsposition](https://user-images.githubusercontent.com/13919702/55704337-187c7e80-59dc-11e9-81f5-a686704d2c74.jpg)

**Comment by Draise14** [comment]
OH yes please.

**Comment by ReinerBforartists** [comment]
Fixed in master

Having the playback controls at the right sucked. So i have put it back into the middle. This is still consistent, since left menu and right options ...

![controls](https://user-images.githubusercontent.com/13919702/56078012-2d458180-5de3-11e9-9cc5-3166bc3ae1dc.jpg)

**Comment by Draise14** [comment]
SOOOOOO much better.
