### ISSUE TITLE
Outliner/Properties Editor, make the switch menu a toggle

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#778]
We have two buttons in the outliner and the properties editor, to switch between outliner and properties editor. This can be solved by one button only, and frees space!

![toggle](https://user-images.githubusercontent.com/13919702/55704487-7d37d900-59dc-11e9-9830-857ec8d1d319.jpg)

**Comment by Draise14** [comment]
How would it work? I like the exposed toggle and highlighted feedback.

**Comment by ReinerBforartists** [comment]
I could leave it the current way. But then we have two buttons.

How it works is that i simply remove one of the buttons. Then just the button to jump to the other editor will remain.

**Comment by Draise14** [comment]
OH ok, makes sense. It was a little mysterious to know what they were at first use, so having the both exposed made sense - and having the animation toggles at 4 or more buttons elsewhere in the same way, it would be consistent to have them be the same no? The animation toggles (which I used and miss a lot btw), are not a binary switch...

**Comment by ReinerBforartists** [comment]
The animation toggles is now a nasty story. They have implemented the new editors not like the old editors, but in a very special way. I haven't found out yet how i could reimplement our buttons here. 

Timeline editor gets labeled as dopesheet editor in the info editor. And Graph Editor appears as Unknown Enum. But that's another story.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/56118002-a5d64a80-5f69-11e9-9e79-65d86e276072.jpg)
