### ISSUE TITLE
Reduce the areas in the header to two

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#779]
The header is divided into three sections. This makes the whole UI looking crowded and unorganized. Too much places to look at. And introduces long mouse movements.  From one area to another.

As a first step, let's reduce this header areas to maximum two. Left tools and menus, right everything options.

![3dview](https://user-images.githubusercontent.com/13919702/55704885-af960600-59dd-11e9-84f5-a84e829ee21b.jpg)

**Comment by ReinerBforartists** [comment]
This counts for all editor types. Go through them all ...

**Comment by Draise14** [comment]
Just left and right?

**Comment by ReinerBforartists** [comment]
Do you want to keep the middle area?

**Comment by Draise14** [comment]
Hmm.... Not sure. I like the idea of left right division of workflow. 

Left:
Tools, tool controls and header

Right:
Panels and editor controls

That I am all for. 

But Viewport drop downs over the panels is annoying. And middle area is a quick access either from left or right... 

With that controversy is that view toggles and options are both left and right. 

But for responsiveness left/right is less complicated and the centered area now won't ever cut into the other. Ideally I'd have a centered double column so no drop-down goes over the toolshelf and properties shelf. 

How would you arrange the global header system?

**Comment by ReinerBforartists** [comment]
As told, just have two areas. Left tools, right options ...

**Comment by ReinerBforartists** [comment]
Fixed in master

Cleaning up the timeline header is another task ...

![twoareas](https://user-images.githubusercontent.com/13919702/56077656-06854c00-5ddf-11e9-8a36-72e047916ac5.jpg)
