### ISSUE TITLE
Compiling problem with Ubuntu 18

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#793]
We have a report that the compilation fails with an icon problem.

See forum thread here: https://www.bforartists.de/content/ubuntu-kompilierproblem#comment-9334

**Comment by ReinerBforartists** [comment]
removed the trouble icon from the cmakelists.txt file. Fingers crossed.

ktotheoz übernehmen sie!

**Comment by ReinerBforartists** [comment]
Another attempt to get rid of the icon check. This time i have commented out the whole class ...

**Comment by naetherm** [comment]
Seems to work.

**Comment by ktotheoz** [comment]
Changes made by @ReinerBforartists seem to work. Cannot reproduce compilations errors.

**Comment by ReinerBforartists** [comment]
Most probably because the changes have fixed it ;)

The main problem behind this is not solved. It starts to recreate the icons with cmake. But the main problem is solved. And creation of the png file from the icon sheet doesn't cost this much time. Even when it's not required. So yeah ...
