### ISSUE TITLE
Icons - Transform icons missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#798]
**Describe the bug**
![bforartists_2019-04-10_17-21-58](https://user-images.githubusercontent.com/35357409/55917550-4a950880-5bb5-11e9-9b9a-81b3b55afa77.png)
Transforms icons under Objects>Transforms have gone missing. 

In BFA1 and Alpha 0.2.0 these were present. Maybe a bad merge?

**Comment by ReinerBforartists** [comment]
Yes, most probably. Move rotate and scale is in the Navi menu already. So this one is a double menu entry.

I know i have made a task for it already. But can't find it at the moment. Will merge it once i stumble across it again.

**Comment by ReinerBforartists** [comment]
Found it. Closing as duplicate ...

https://github.com/Bforartists/Bforartists/issues/754
