### ISSUE TITLE
Default theme, make the unticked checkbox stick a bit more out

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#802]
The unticked checkboxes are a bit hard to see. We should make them a bit more sticking out.

![morevisibleplease](https://user-images.githubusercontent.com/13919702/56032466-8ef1e700-5d22-11e9-8b2b-661760d98315.jpg)

**Comment by ReinerBforartists** [comment]
Hmmm. No matter what i try, it looks worse than before ^^

Grey could be an option. But then the unticked checkbox sinks in all the other grey.

![checkbox](https://user-images.githubusercontent.com/13919702/56075949-cd42e100-5dca-11e9-9b20-e92159a65a07.jpg)

**Comment by Draise14** [comment]
I feel the light grey tick boxes actually stand out more than the dark blue, as the dark blue is also on a dark grey. Light grey on a dark grey has more contrast- well to me. Maybe boost the light grey just a tad to be the same grey as the text?

**Comment by ReinerBforartists** [comment]
You can assign if you want :)

**Comment by ReinerBforartists** [comment]
Fixed in master

![brightercheckboxes](https://user-images.githubusercontent.com/13919702/57127760-a3f5ef00-6d91-11e9-8279-600126f5ab3b.jpg)
