### ISSUE TITLE
Topbar - Edit Menu - what to do with the Lock Object Modes prop

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#806]
As the title says. What shall we do with the Lock Object Modes prop? It does not belong into the text menu. But where should we put it? Is it often enough needed to have it at top UI level?

![lockobjectmodes](https://user-images.githubusercontent.com/13919702/56204805-97ab2b80-6048-11e9-9882-6408419de2fa.jpg)

**Comment by Draise14** [comment]
Into user preferences and turned off by default - to me would make sense. I'd put it under the "Editing" category under "Miscellaneous". 
![bforartists_2019-04-16_09-00-48](https://user-images.githubusercontent.com/35357409/56215963-2b1f3500-6026-11e9-96b3-5044e42e618f.png)

**Comment by ReinerBforartists** [comment]
I see it equal. Let's have a look if we can put this prop there. I remember that user preferences settings are a very special beast at its own ...

**Comment by ReinerBforartists** [comment]
Prefs is no good place. Let's put it into the sidebar. A edit panel.

**Comment by ReinerBforartists** [comment]
Fixed in master.

And prop is off by default now.

![prop](https://user-images.githubusercontent.com/13919702/56278428-80cb0e80-6106-11e9-9e21-fcbac051c6d6.jpg)
