### ISSUE TITLE
Remove double menu entries in new Topbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#816]
Newest Blender version has brought us a topbar integration into the single editors. And it brings a double entry.

Remove them from the topbar.

![doubleheader](https://user-images.githubusercontent.com/13919702/56653690-7d97cb80-668e-11e9-913f-ec2035e6f17d.png)

**Comment by Draise14** [comment]
This here is quite ridiculous. Will this adhere to the L/R layout scheme now?

**Comment by ReinerBforartists** [comment]
I try to make it left right, yes. Left tools, right settings.

In this case we simply remove the double set from the topbar.

**Comment by ReinerBforartists** [comment]
I think  i gonna change my mind here. The header is too crowded already. The topbar provides the space for this elements that is missing in the UV layout.

We could have a look to align them at the right though.

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/56724504-6e2a8800-674b-11e9-9567-8bb3afaee5ac.jpg)
