### ISSUE TITLE
New topbar - remove double editor type menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#817]
We have a double entry in the new topbar. The editor type menu. One entry is enough.

![editortypemenu](https://user-images.githubusercontent.com/13919702/56653807-cc456580-668e-11e9-96de-d2d9a6d72dbc.jpg)

**Comment by Draise14** [comment]
Yikes. Which one will you remove?

**Comment by ReinerBforartists** [comment]
The upper i guess. For consistency reasons. In all other editors this menu is in the header, not the topbar.

**Comment by ReinerBforartists** [comment]
Fixed in master
