### ISSUE TITLE
Toolbar - Animation - Add keyframe Interpolation and Handle, like Keyframe Type list

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#822]
## Issue
Right now, the toolbar>Animation has keyframe types, but it doesn't have a dropdown for handles or interpolation. Traditionally these menu's would be pulled by a hotkey, or by a 2 step multi mouse move in Bforartists through the header menu's. These are accesses almost repetitively and often, having them on mouseover or a 1 step multimouse move in BFA via the toolbar would be great. It would save SO MUCH TIME. 

## Solution
Since the Keyframe Type is already existent, it would be consistent to also add the the other two list for keyframe attributes: Handle Type and Interpolation Mode

**Screenshots, Example Files**
![PureRef_2019-04-25_16-08-05](https://user-images.githubusercontent.com/35357409/56768745-c1fd9700-6774-11e9-88bb-53ac64151e56.png)

## Other solutions
Another option could be to put these drop down lists to 1 level in the header of the animation editors, by the snapping. 

Another option is to add the dropdown list operators or all of them individually as buttons in the properties sidepanel in it's own panel/tab, since they are properties of the keyframe, and having them without a popover, floating menu or hidden in sub-menu's would make the workflow that much better. 

If too hard, maybe since the default system of BFA has no hotkeys for these panels, maybe also just doing a quick fix and adding them back might also help (as it is very hard to assign floating menu's a hotkey).

**Comment by ReinerBforartists** [comment]
We could run into the limit that those tools needs to be performed in the editor where they are required. But is worth a shot.

**Comment by ReinerBforartists** [comment]
Related: Reorder animation toolbar to have the same order than the time line header #832

**Comment by ReinerBforartists** [comment]
Okay, we can't put it into the toolbar. Action and graph editor have their own type set.

**Comment by ReinerBforartists** [comment]
Fixed in master

Don't aks me why in the dopesheet there is a gap at the right ...

![fixed](https://user-images.githubusercontent.com/13919702/60329172-1e0cb380-9990-11e9-8da3-b23a5364e914.jpg)
