### ISSUE TITLE
Keymap: Rotate viewport with R Mouse and pan Middle Mouse for consistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#823]
## Request 
In Bforartists 1, the default rotation for the view was Right click, and pan was Middle click. 
In Bforartists 2, the default is Middle click for rotation and Right click for pan..... 

This is disorientating, a little inconsistent throughout the UI, and I feel it is more natural to rotate the viewport with Rclick and Middle. 

## Solution
Update the hotkeymaps by inverting these two mouse buttons. 

## Implications
I understand the Rclick is consistent throughout the entire interface as the button to pan the node editor, image editor, etc, but right now it is inconsistent with the Middle mouse button to scroll properties and panels sidebars, like panning in the UI. 

## Reason to change back
1. Middle Mouse to pan throughout the interface, including node editors, would be consistent with scrolling/panning in properties/shelves. 
2. Right Mouse is free'd up for future functionalities (BFA Pie contextual menu's?)  
3. Right mouse to rotate the view feels more intuitive as it's used more than panning, and the Rmouse is used more than Middle. 
4. It would be consistent with people who have worked in Bforartists 1.

**Comment by ReinerBforartists** [comment]
Hmm, i can't remember what the reason was to change this in the current way. Let's change it back and have a look.

**Comment by ReinerBforartists** [comment]
Fixed in master
