### ISSUE TITLE
Keymap: Left hand hotkey for Pose Mode - Armatures

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#824]
## Feature Request
I would like a hotkey to switch to Pose Mode for Armatures. 
![bforartists_2019-04-25_16-30-57](https://user-images.githubusercontent.com/35357409/56769729-b1025500-6777-11e9-8a73-e3520e6d0829.png)

## Issue
Right now there is no hotkey for this workflow, so when rigging and animation between multiple objects and elements, the switch to modes is a 2 step process (open mode menu either in a pie or in header, then choose pose). It should be as easy since animation toggles often and rigging also toggles often.  

## Solution
Add hotkey to defaults: **Shift+1**

## Reasons
Since Pose mode is similar to transforming in Object mode, it would make sense to have it the same hotkey with a modifier. Keeping it to the left side of the keyboard also keeps it nice and easy to access. 

## Alternatives
Maybe since both are transform related, one could be 1, and the other double 1.

**Comment by ReinerBforartists** [comment]
This is doomed. I have given up at it. Any change at the keymap will remove this hotkey. But feel free to try it.

**Comment by Draise14** [comment]
What? this hotkey doesn't save when there are changes? I've never hit this bug.

**Comment by ReinerBforartists** [comment]
It does save. And gets removed sometimes when you do some changes at the keymap afterwards. Ran into this a few dozen times. There is a bug in the keymanager somewhere.

**Comment by ReinerBforartists** [comment]
As a side note, Shift 2 would make more sense somehow. 1 is object mode, 2 and higher is edit mode.

**Comment by ReinerBforartists** [comment]
Fixed in master

Let's see how long it lasts until it breaks again ...
