### ISSUE TITLE
Toolbar - Animation - margin between play and forward buttons on playback

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#826]
## Issue
Right now the Toolbar>Animation controls for play and forward has a weird margin when you press play. 

**Screenshots, Example Files**
![bforartists_2019-04-25_16-42-47](https://user-images.githubusercontent.com/35357409/56770354-5bc74300-6779-11e9-9845-70c960718daf.png)

## Solution
Ah.. probably shouldn't happen.

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by ReinerBforartists** [comment]
Ack, this was too fast committed. Throws an error now. Reopening.

**Comment by ReinerBforartists** [comment]
Fixed in master
