### ISSUE TITLE
Theme - Graph Editor: Increase handle and vertex size

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#827]
## Issue
Right now the handles and vertex sizes are at 3 px in the BFA default theme, which on HD screens are reaaaally hard to grab and move around. 

![PureRef_2019-04-25_16-48-35](https://user-images.githubusercontent.com/35357409/56770645-240ccb00-677a-11e9-98ff-f033c2417fd6.png)

## Solution
Increase their sizes to either 6 or 7 pixels, so it's easier to grab and see, also looks more user friendly.

**Comment by ReinerBforartists** [comment]
Interesting catch. I have no idea where to even search for this though :D

**Comment by Draise14** [comment]
I can do this one, it's pretty easy, just a theme thing.

**Comment by ReinerBforartists** [comment]
Ah, theming. Okay :)

**Comment by Draise14** [comment]
Wait. Any theme change requires creating the C file through python commands for theming now, confirmed? To compile it?

I'll unassign here, still out of my league a bit. 

But here are the settings to change:
![bforartists_2019-04-29_18-27-09](https://user-images.githubusercontent.com/35357409/56933228-8cc2b300-6aac-11e9-83f0-d657df7c5083.png)

**Comment by ReinerBforartists** [comment]
:D

I try to tackle this one :)

**Comment by ReinerBforartists** [comment]
It is by the way described in the blender_theme_as_c.py file how to use the script. I have added a short how to in the comments when i did this first. Just in case that you want to try it at one point :)

![description](https://user-images.githubusercontent.com/13919702/57008547-3ca13900-6bf1-11e9-84f1-dee491298834.jpg)

**Comment by ReinerBforartists** [comment]
... and good that you haven't claimed this taks here. The script still uses the old wrong terms. We have to edit the userdef_default_theme.c script afterwards. I had completely forgotten about this nagger :/

![oldterms](https://user-images.githubusercontent.com/13919702/57008749-90605200-6bf2-11e9-8104-8e0d46e1979c.jpg)

**Comment by ReinerBforartists** [comment]
In case you run into this, compare the new file with the old file with Meld. And replace the wrong terms. They start now with a **space_** in front of the name ...

**Comment by ReinerBforartists** [comment]
Fixed in master
