### ISSUE TITLE
Video Sequencer - Strip menu - Swap enumerated operators menu move up one

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#843]
![bforartists_2019-05-02_11-55-55](https://user-images.githubusercontent.com/35357409/57092549-400bf180-6cd1-11e9-8d84-e4fa65ce1ae0.png)

## Task
Move the Sequencer Swap operators up one, so it's easier to access. 

## Issue
They are enumerated menu items, though you can make them into `layout.operator` items - though being enumerated. 
![atom_2019-05-02_11-53-50](https://user-images.githubusercontent.com/35357409/57092552-413d1e80-6cd1-11e9-8d75-0ef5dcf92cea.png)

**Comment by ReinerBforartists** [comment]
Do it! :)

**Comment by Draise14** [comment]
I have brought these up one level, renamed the tooltip, added icons (both in the Enumerated menu and in the python menu, and it's in the commit will be in the #765 task.

**Comment by ReinerBforartists** [comment]
Please commit every single issue as a single commit. One big commit that contains everything is a nightmare to maintain and to follow.

**Comment by ReinerBforartists** [comment]
Ah, and please make a separated pull request for every finished task. Not one pull request for everything. This puts me under pressure since the amount of code to check is much bigger then.

Work in small chunks!

**Comment by Draise14** [comment]
Ah ok. How do I do this when the tasks are all in the same file? I probably should have finished the other task before even starting this one. I jumped the gun when I got assigned, as it was easy, lol

**Comment by ReinerBforartists** [comment]
Yeah, now we have a problem it seems.

Not a happy bunny with that. As told, work in smallest possible chunks. But now it is as it is. We will see how we can handle the pull request then.

**Comment by Draise14** [comment]
There was a merge regression here, so re-committing.

**Comment by Draise14** [comment]
Ok, done. 

![bforartists_2019-05-21_12-38-31](https://user-images.githubusercontent.com/35357409/58118009-9039ed80-7bc5-11e9-9f6a-0237e34a2ab4.png)

**Comment by Draise14** [comment]
I just realized when I do a pull request, all my commits on different tasks go to that one pull request. 

Does this mean that if a pull request is per task/commit ideally.. I have to pause work on any new tasks till the pull is resolved?

**Comment by ReinerBforartists** [comment]
Yes. This would make my life muuuch easier when i just need to check one issue ...

**Comment by Draise14** [comment]
Slows things down if I ever happenstance wanna get a few hours a day in, but makes sense. I guess this will be relaxed. Small tasks at a time is quite alright.

**Comment by ReinerBforartists** [comment]
We had a bad merge once, which has cost me weeks now. I don't want to repeat this mistake. So better the things goes a bit slower instead of wrong ;)
