### ISSUE TITLE
Animation - Easier access to common display filters

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#845]
## Issue
Very common view filters in the animation eidtors (Fgraph, Dopesheet, NLA, Timeline, etc) are the selected only, hidden, etc. This trio I use often, when doing animation, sometimes multiple times every few minutes. Right now you have to go into a drop down menu, move moust right to the top part of it, then click to change the filter. Every single time. Open, move, change; open, move, change; open, move, change. 

## Solution
It would be great to have them somewhat more accessible like they are in Bforartists 1 - right in the header (or in a toolbar). A step can be removed for this repeated work, and just mouse over to activate them. 

![bforartists_2019-05-02_15-46-24](https://user-images.githubusercontent.com/35357409/57110031-c689f880-6cfc-11e9-9f35-0e496ea892e6.png)

## Alternatives
Buttons in a sidepanel?

**Comment by ReinerBforartists** [comment]
No problem, now that we have freed a bit space here. Do we talk about all three props ?

**Comment by ReinerBforartists** [comment]
Toolbar is out. These settings are editor dependant. You can have two editors have different settings here.

So header ...

**Comment by ReinerBforartists** [comment]
This code is weird. It has too many possible modes, and is really ugly connected with each other.

There is a chance that the Blender devs will fix it for us. There is a comment in space_dopesheet.py:

> # XXX: Perhaps we want these to stay in the header instead, for easy/fast access

Unassigning for now. Waiting a few more weeks doesn't really hurt.

**Comment by Draise14** [comment]
Hope they do it! I would just be happy with only selected and hidden, the rest is a bit too special per editor, true. The first two are the only consistent ones and used the most.

**Comment by ReinerBforartists** [comment]
As told, it is not this easy to just grab those two props. It is much more work. Much more ...

**Comment by Draise14** [comment]
Looks like the Blender Dev's have done this one.

**Comment by Draise14** [comment]
![blender_2019-05-13_20-29-21](https://user-images.githubusercontent.com/35357409/57664476-ec957f80-75bd-11e9-9fa4-949625160a9d.png)
![blender_2019-05-13_20-29-14](https://user-images.githubusercontent.com/35357409/57664478-ee5f4300-75bd-11e9-89ad-cc531fd17b02.png)
![blender_2019-05-13_20-29-06](https://user-images.githubusercontent.com/35357409/57664482-ef907000-75bd-11e9-8d9f-26af0b248b8a.png)

Only editor is the Timeline that doesn't have this.

**Comment by ReinerBforartists** [comment]
Some things fixes itself ^^
