### ISSUE TITLE
Video Sequencer - Strip Menu needs icons on context sensitive entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#847]
![](https://user-images.githubusercontent.com/35357409/57103508-938b3900-6ceb-11e9-8845-48debd7e7872.png)

I've found a whole bunch of hidden option in the Strip menu that change on selection.

## Task
These need to be iconized.

**Comment by Draise14** [comment]
So, this is postponed? Should I take up the VSE a bit more as a practice ground for more iconology and menu organizing (then unpostpone?) I have no tasks, so can take dibs on this one.

**Comment by ReinerBforartists** [comment]
Ah, forgot to unpostpone the tasks that were postponed for the new version. Just grab it :)

**Comment by Draise14** [comment]
Ok, I'm going to un-assign incase anyone wants to do Icon work to the repository (but I will be doing the icon creation locally). I'm going to start creating or organizing the icons THEN I'll merge the master, assign, and take the icon work to the required files. I don't want to hold anything up, and I don't want to have merging conflicts with any other person's work when I have the icons and when I am ready to do file changes. 

BUT DIBS! I'm technically working on this one, just not on the repository.

**Comment by Draise14** [comment]
![inkscape_2019-05-18_20-52-33](https://user-images.githubusercontent.com/35357409/57976805-e3862300-79ae-11e9-8adb-3568abcf5fa8.png)

Ok. Done the icons. I won't make a whole bunch of new ones, but will recycle node ones for the effects, and use other existing ones for similar functionality.

**Comment by ReinerBforartists** [comment]
There is no commit, so it is not fixed.

Please add just a fixed label when you have committed the code

**Comment by Draise14** [comment]
lolz 

I committed, thus the label. 

I closed due to pulling it. 

haha, so funny. I'm doing this right, right?

**Comment by ReinerBforartists** [comment]
We had a cross posting here ;)

I saw the fixed label and no commit. So i commented it. Maybe for the future, first commit, then change label :)
