### ISSUE TITLE
Task #846 icon work is still not part of Draises_branch due to merge conflict

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#849]
Some icon files from the task #846 icon work is still not part of this branch Draises_Branch, which also has some tasks done to the same files, thus a conflict.

```
release/datafiles/blender_icons.svg
release/datafiles/blender_icons16.png
release/datafiles/blender_icons32.png 
```

## Task
This requires copying in the new icons to the SVG file, updating the H file for the new icons, and re-doing the icons DAT generation to merge.

**Comment by Draise14** [comment]
@ReinerBforartists , should I do this one for you? Then do another pull? Everything would be fixed and normal - pulling and merging your changes from that task directly with the work I did just now.

**Comment by ReinerBforartists** [comment]
Hm, that's the bad part when working with the icon sheet. I fear you have to wait with this task until the pull request is fulfilled. Which is not before the new version is out.

**Comment by Draise14** [comment]
Sure, no prob - next week it will be! :)

Now we know only one person can do Icons at a time, only one Icon assignee! =P

**Comment by ReinerBforartists** [comment]
Yeah, you never stop learning ^^
