### ISSUE TITLE
Hotkey conflict 3D view - Ctrl C - menu for copy popup not found

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#851]
This is two issues in one. The hotkey should not exist. Ctrl C should copy already. 

And the menu is missing for the Blender keymap ...

And we have two entries instead of one ....

But first check if this menu exists in the Blender keymaps. Could be one of those that got removed ...

![copypopup](https://user-images.githubusercontent.com/13919702/57191879-ae97bc00-6f2a-11e9-92e1-761dee69fb13.jpg)

![callmenu](https://user-images.githubusercontent.com/13919702/57191923-2534b980-6f2b-11e9-9332-8ce5065d0934.jpg)

**Comment by Draise14** [comment]
Wasn't this addon enabled by default in BFA1?

**Comment by ReinerBforartists** [comment]
Addon? O_O

Hm this could explain the double entry. But i have no idea what addon this could be.

**Comment by ReinerBforartists** [comment]
I start to understand what is going on here. Draise, have you experimented with the copy attributes addon? We had this ugly merge where some of your experimental settings made it into the master. Seems that we just found one more :/

It's more than just this one entry. See def register()

release\scripts\addons\space_view3d_copy_attributes.py

**Comment by Draise14** [comment]
I use this addon in production daily, yes. Must have slipt through. I highly recommend it as a default, ever since the 0.9.3 days I had it a default always, and must have forgot it wasn't a BFA default. 

The CTRL+C default is an enigma in the 3D Viewport, not sure what it copies. With this addon it's very clear what you are copying and it's very useful. 

Sorry about the F*** ups.

**Comment by ReinerBforartists** [comment]
No problem as long as we can catch the baddies :)

The problem here imho is, copy should copy, and not open a popup. This popup is in the way. Blender doesn't have it on by default, and i don't want to have it on by default neither.

**Comment by Draise14** [comment]
Ah ok. Hmm.. these features are invaluable to me, specially copying constraints, and copying modifiers, and copying transforms... But yeah, it is out of place on CTRL+C

**Comment by ReinerBforartists** [comment]
Well,  in theory we couuuld change the addon here. But that's a quesiton of manpower. Even Blender doesn't maintain addons for good reason. Maintaining addons too would kill us.

The addon is still included. You can turn it on when you need it :)

**Comment by ReinerBforartists** [comment]
Fixed in master
