### ISSUE TITLE
Merge regression - make the proportional editing and snapping settings hidden when off again

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#855]
The newest merge has killed our work at the proportional editing and snapping props. The settings are visible again when the tool is off.

Means we need to redo this step ...

![regression](https://user-images.githubusercontent.com/13919702/57192884-b90b8300-6f35-11e9-8385-23968323be0b.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by Draise14** [comment]
The CTRL button activates snap momentarily and the snap settings need to be changed without the need of activating perma-snap to show the toggles. Shouldn't the snap methods be exposed all the time?

**Comment by ReinerBforartists** [comment]
Ah, you are right. Seems that i need to revert this change :/

**Comment by ReinerBforartists** [comment]
Fixed in master. The snapping settings are now visible all the time again.
