### ISSUE TITLE
Keymap - 3d view - mesh - remove hotkeys for F2 addon

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#857]
One more addon hotkey entry that made it through. The F2 addon is turned off by default.

Remove this hotkey.

![f2addon](https://user-images.githubusercontent.com/13919702/57315364-b5bdf600-70f3-11e9-9d88-6281dfd07d7f.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by Draise14** [comment]
In Bforartists 1, this addon was turned on by default.

**Comment by ReinerBforartists** [comment]
Hm, but in Blender 2.80 it is off.

Shall we reactivate it?
