### ISSUE TITLE
Tool Settings Header - snap toggles hide when toolbar hides

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#881]
![bforartists_2019-05-13_20-33-54](https://user-images.githubusercontent.com/35357409/57668695-cb3c8f80-75cd-11e9-9896-98695cf313d8.png)
**Describe the bug**
Right now in BFA, the snap settings for tools are now to the right of the tool settings header (where I prefer). But now when you hide the tool settings header, these snap tools dissappear also. In Blender, these tele-transport to the center of the header (swap headers, as they were in the center). 

## Possible solutions
- Make the tool settings header unhideable
- Make move the snap settings elsewhere (into the header)? 
- Snap these settings somewhere when the tool settings header hides?

**Comment by ReinerBforartists** [comment]
Yes. These settings must go back into the header now.

**Comment by ReinerBforartists** [comment]
Fixed in master

Now it's like in Blender. When the tool settings are hidden, then these props schows in the header instead.

![fixed](https://user-images.githubusercontent.com/13919702/58159297-80c9ab80-7c7c-11e9-9f73-92c513bd9a8a.jpg)

**Comment by Draise14** [comment]
Nice solution.
