### ISSUE TITLE
Global/Toolbar - "New Scene" conflict of interest due to new workspace templates workflow

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#887]
## Issue
Right now there are two methods to creating a new scene. 
1. File>New>Template
2. Toolbar>New Scene

The location and operation of both systems are file management based systems (load/save/new) but they are both inconsistent concerning the number of steps to get a new scene mixed the function of new workspace templates (as the "New" from the file manager is essentially for new workspace templates). 

Eg. New Scene will load a new scene with the default template. 
![bforartists_2019-05-14_15-25-03](https://user-images.githubusercontent.com/35357409/57729863-cd016400-765c-11e9-9268-12545b0ef2a8.png)

In the File>New, this is not the case, as this will load a new scene + new workspace template. There is no File>"New Scene" entry.. and likewise, there is no "New Workspace Template" in the toolbar. 

![bforartists_2019-05-14_15-24-48](https://user-images.githubusercontent.com/35357409/57730084-50bb5080-765d-11e9-8053-4cd6b8795309.png)

## Solution
- Add a "New Scene" single click entry into the File menu
- Change name of "New" to "New from Template" naming convention to make sense
- Add "New from Template" to the toolbar

**Comment by ReinerBforartists** [comment]
Fixed in master
