### ISSUE TITLE
Video Sequencer - View Options, double entry for "Show Seconds"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#896]
![bforartists_2019-05-19_00-26-21](https://user-images.githubusercontent.com/35357409/57978553-a7b28400-79d5-11e9-80d6-24b5390cb574.png)

## Issue
The side panel View tab > View Options panel has a double entry for Show seconds. 

## Task
- Remove one?

**Comment by ReinerBforartists** [comment]
Definitely ^^

**Comment by Draise14** [comment]
Just waiting on a pull on my branch to then do this one later. ;)

**Comment by ReinerBforartists** [comment]
Check if this is a panel that is used elsewhere. Not that you remove one entry and then in another panel it is missing then.

**Comment by Draise14** [comment]
Good point. I'll have to check how the panels are implemented, this is more a learning task.

**Comment by Draise14** [comment]
These no-longer show up.
