### ISSUE TITLE
Remove Blender menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#897]
The next merge brings us a useless Blender menu in the header. We need to remove it. 

Of interest is the temporary reset to factory settings button. What the heck is this good for? Reset to factory settings is already temporary. Until you save the startup file ...

![blendermenu](https://user-images.githubusercontent.com/13919702/57985030-408ee100-7a62-11e9-8740-95c8767c39fd.jpg)

**Comment by Draise14** [comment]
Thank God. This was the blender icon they decided to make into a menu. It consistent of any OS and people started to get confused. I like these menus where they were.

**Comment by ReinerBforartists** [comment]
I have still no idea what this second load factory settings button should be any good for. Our system works perfect, and doesn't confuse the people. I will ignore this button for now. We can try to readd it at a later point in case it really turns out to be needed.

**Comment by ReinerBforartists** [comment]
ROFL Now i know what they did there :D

>  For loading factory settings, there is now the option to do it permanently to overwrite existing preferences, or temporarily for testing. 

So the temporary button resets to factory defaults, like it did before. When you close Blender, then this settings are lost. The load factory settings button now resets to factory defaults, overwrites everything, saves it, and all your custom settings ARE LOST WITHOUT ANY WARNING!

XD

Will not do that! We will not kill the work of the users in an unexpected way.

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by ReinerBforartists** [comment]
Ah, autosave preferences is the killer here. That's why they implemented a temporary reset to factory defaults.

Okay, this means that we will implement the temporary button here too. I am just not sure how. The most elegant way would be to call a sub menu where you can choose to load factor settings temporary or permanently.

**Comment by ReinerBforartists** [comment]
Woah, not so easy. App Template involved ...

**Comment by ReinerBforartists** [comment]
Fixed in master. Made it a sub menu.

![factorydefaults](https://user-images.githubusercontent.com/13919702/58016389-c9a72600-7afd-11e9-9a69-94902c4f56d5.jpg)
