### ISSUE TITLE
Outliner, Theming problem with active element

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#898]
The next merge brings us a theming problem in the outliner. Active items are black. Not good ...

![themingproblem](https://user-images.githubusercontent.com/13919702/57985038-66b48100-7a62-11e9-9987-d86c576b6ef5.jpg)

**Comment by Draise14** [comment]
Yep. Looks broken. Also, where are the rows now's?

**Comment by ReinerBforartists** [comment]
Ask the blender developers :)

**Comment by ReinerBforartists** [comment]
Okay, both is a theming issue. They have changed something at the theming code. And now we need to fix our theme.

**Comment by ReinerBforartists** [comment]
Yep, values are shot down. Makes sense to have a look if there are other problems like this ...

![allblack](https://user-images.githubusercontent.com/13919702/58005044-0adf0c00-7ae5-11e9-9b16-30f4dbc0918e.jpg)

**Comment by ReinerBforartists** [comment]
Node editor needs a fix too ...

![nodeeditor](https://user-images.githubusercontent.com/13919702/58005745-a755de00-7ae6-11e9-90ba-996d015c7210.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
