### ISSUE TITLE
Auto save preferences

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#899]
The new merge has brought us auto save preferences. This is a dangerous feature. And it is hidden. The second part is even more dangerous.

Let's make it at least visible, so that the user knows the settings are saved when you modify it.

![autosaveprefs](https://user-images.githubusercontent.com/13919702/58008792-6f05ce00-7aed-11e9-9c23-192e36c782b0.jpg)

**Comment by ReinerBforartists** [comment]
Hm, for our toolbar editor this is great. Now the changes are recognized without the need to save the user preferences.

But as told, the invisible part is what i dislike here.

**Comment by ReinerBforartists** [comment]
Edit 2: this does NOT work with changes at the theming ...

**Comment by Draise14** [comment]
Weren't they exposed with mouseover buttons last week? Jeepers, the Blender foundation really goes fast, but too fast that it trips up over themselves.

**Comment by ReinerBforartists** [comment]
Ah, there is panel code involved. No way to add a simple menu link with text here. It becomes a dropdown box that occupies the whole width then.

Hmm. so nothing really to do here. The small button is already the best solution to the dilemma. We could change the icon. But the collapsed menu icon is also no bad choice.

Closing. Won't fix.
