### ISSUE TITLE
Timeline based Editors - Mouse action cleanup and clickdrag off selection to start box-select

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#900]
## Issue
Right now in BFA, we have two methods to move the timeline: 
1. Rclick
2. Lclick on the new timeline header space

We also have no contextual transform/selection controls in the editing space
1. Lclick anywhere with anything selected will move what is selected, or do nothing when nothing is selected, regardless of context
2. Click drag does nothing but move the object if selected (instead of typical software functionality of box select to select)
3. You can not move multi-selections with click drag on the selection AND deselect when clicking anywhere but on the selection (right now in BFA, selection is preserved with no way to unselect by the mouse or a key combo)

This applies to the following editors:

- VSE
- Timeline
- Dopesheet
- NLA
- Graph Editor

The only exception is that in the Node editor, you can click off and drag to box select, and you can click drag on multi-selections to move them all or click drag on one to select and move. This is the prefered functionality, but not consistent with the rest. 

## Solution
1. Add clickdrag when nothing selected to start a box box select
2. When there is a multi selection of keyframes or strips, the group moves on clickdrag
3. When you clickdrag on an element you select and move that keyframe/strip
4. Free up the Rclick for something else
5. Add mouse functionality to deselect (double click? Click off selection?)

## Alternatives
There is a possibility that by design (deselect when click off), you can not make a selection and move then move the group with a clickdrag, but you can work the keymap to work with clickdrag to draw a box select when something is not selected (it is programmed in Blender Lclick keymap to a degree already). 

![blender_2019-05-20_16-12-45](https://user-images.githubusercontent.com/35357409/58053009-f36f4580-7b1b-11e9-9d0f-bbc7c00dee70.png)

**Comment by ReinerBforartists** [comment]
Ah, overlooked this request. This is not so easy to decide. I would need a mockup to play around  to test out if the change can really be useful.

A task for a experimental keymap i would say :)

**Comment by Draise14** [comment]
Eh, I have played around with this already and have my own map - though it has other features like F for focus, R for radius, and missing hotkeys I use often from the Full keymap or Blender.

**Comment by ReinerBforartists** [comment]
Yes, please isolate it :)

**Comment by ReinerBforartists** [comment]
Any news here?

**Comment by ReinerBforartists** [comment]
I consider this task as done. Lots has changed meanwhile. You can scrub with lmb at the top, and rmb in the keyframe area. Functional and working.

So closing.
