### ISSUE TITLE
Video Sequencer - Strip Menu needs missing icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#903]
![image](https://user-images.githubusercontent.com/35357409/58118614-dd6a8f00-7bc6-11e9-8ce0-80137b4a58a9.png)

## Task
Add missing icons to: 

- Snap Strips to Playhead
- Clear Strip Offset
- Toggle Meta

**Comment by Draise14** [comment]
![inkscape_2019-05-30_17-34-24](https://user-images.githubusercontent.com/35357409/58669254-2e822d80-8301-11e9-8812-8e6e5edf53ef.png)

Ok, made an icon. Gonna unassign incase anyone wanna do icons. But DIBS, this one is mine.

**Comment by Draise14** [comment]
![inkscape_2019-05-31_09-15-55](https://user-images.githubusercontent.com/35357409/58711915-210e8700-8385-11e9-8b84-61797fc305bc.png)
 
A little more progress. I have one more icon to work on then I'll generate icons, do the code and commit.

**Comment by Draise14** [comment]
Gonna pause this one till task #924 is merged.

**Comment by Draise14** [comment]
DONE! 

- Added 3 new icons
- assigned some reused ones to similar functionality

**Comment by Draise14** [comment]
![bforartists_2019-07-03_10-45-55](https://user-images.githubusercontent.com/35357409/60605771-be434d80-9d7f-11e9-9651-7cc5261e78ac.png)

# Task
Re-add icons that have gone missing.

**Comment by ReinerBforartists** [comment]
Sorry ^^
