### ISSUE TITLE
Hotkeys - Video Sequencer Transform hotkey 'W' missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#904]
![bforartists_2019-05-21_12-51-16](https://user-images.githubusercontent.com/35357409/58118807-3fc38f80-7bc7-11e9-8c8b-3c32d7420a5d.png)

## Issue
Right now the transform hotkey in the Video Sequence Editor has no hotkey, like.. you can only transform via mouse but not keyboard. 

## Task
Add back the W hotkey to strip transform to keep it consistent with the rest of the editors.

**Comment by ReinerBforartists** [comment]
Fixed in master

![selectmenutrouble](https://user-images.githubusercontent.com/13919702/58156498-7dcbbc80-7c76-11e9-9571-a57c712bcb81.jpg)
