### ISSUE TITLE
This file has not been saved yet dialog - make the buttons bigger

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#907]
The buttons are cumbersome to click with the current standard height of 20 pixels. Make them higher when possible.

![buttonhigher](https://user-images.githubusercontent.com/13919702/58230373-6ce18080-7d34-11e9-96b9-961325141193.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master

![bigger](https://user-images.githubusercontent.com/13919702/58947472-4d147880-8788-11e9-8366-4464b8e34f31.jpg)

**Comment by Draise14** [comment]
Very cool. <3
