### ISSUE TITLE
VSE - Remove hotkey to call the Change menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#909]
Hotkey C calls a Change menu. This already exists in the regular menu. Remove it

![changemenuvse](https://user-images.githubusercontent.com/13919702/58234202-49233800-7d3e-11e9-851d-cc078b8848c5.jpg)

**Comment by Draise14** [comment]
These entries already exist in the header under the Strip Menu.

**Comment by ReinerBforartists** [comment]
Have i overlooked it? Thanks for the headsup.

Shall we cancel the task completely? Or remove the hotkey? You know i am no friend to call a menu under the mouse ...

**Comment by ReinerBforartists** [comment]
I can still not locate it. Do you need to have video material loaded?

**Comment by ReinerBforartists** [comment]
I can find parts. With other name. And mixed with other content. But this change menu does not exist in the UI yet.

![effectstrip](https://user-images.githubusercontent.com/13919702/58274492-4b63b180-7d93-11e9-9a3f-4c3346c3a304.jpg)

**Comment by Draise14** [comment]
Yes, you need effect strips applied to something (and selected) to call the menus from the header (else they hide)
![bforartists_2019-05-23_12-45-31](https://user-images.githubusercontent.com/35357409/58274521-acba5f00-7d58-11e9-85d4-4e0b5c17ca4f.png)

**Comment by Draise14** [comment]
These menu entries are.. contextual to the Strip Header to what is selected (and there are more depends on selection, eg. audio).

**Comment by Draise14** [comment]
I guess the idea here is to grey out the header menu instead of hide them when the context is incorrect. 

This would be the true task in my opinion (then remove the hotkey to the floating one).

**Comment by ReinerBforartists** [comment]
Oh my XD

**Comment by ReinerBforartists** [comment]
Draise, i put the decision here in your hands. When i start to touch the VSE then i would just start to redo everything from scratch ^^

**Comment by Draise14** [comment]
I would love to start the whole VSE thing from scratch too.. hmm.... I'll make individual tasks once I think about where to begin. For now, let's just remove the hotkey to the floating menu and we can close this.

**Comment by ReinerBforartists** [comment]
Okay. I'll do this. I'm still at the keymap anyways.

**Comment by ReinerBforartists** [comment]
Fixed in master
