### ISSUE TITLE
Hotkey to jump to pose mode is broken

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#910]
As expected, when you do changes at the keymap, at one point this hotkey simply breaks.

Hotkey to jump to pose mode is currently broken.

![posemodekey](https://user-images.githubusercontent.com/13919702/58234857-d9ae4800-7d3f-11e9-92ff-8a36786f7a93.jpg)

**Comment by Draise14** [comment]
So random. I've used custom maps from external files and have edited them heavily and it has never corrupted. Maybe this is an error upon compilation from the repository?

**Comment by ReinerBforartists** [comment]
Fixed in master

This problem happens at changing the keymap, and then export it. But i was never able to nail it down to a specific cause.

**Comment by ReinerBforartists** [comment]
Now i start to cry ...

![modes](https://user-images.githubusercontent.com/13919702/58310936-22c9cf00-7e08-11e9-8115-7ac8c8651a5f.jpg)

**Comment by ReinerBforartists** [comment]
Fantastic. The more i try to fix it with the keymanager, the more it breaks. I really wish i could reproduce it in Blender. I have a suspicion here, but i cannot reproduce it.

Let's fix the problem in the keymap.py file directly

**Comment by ReinerBforartists** [comment]
Wow, just found out that in Blender the switch to different modes with hotkeys is currently completely broken. I hope that we don't pull this into Bforartists ...

**Comment by ReinerBforartists** [comment]
Okay, i think i nailed it down. Bug report to Blender is at its way.

**Comment by ReinerBforartists** [comment]
https://developer.blender.org/T65064

**Comment by ReinerBforartists** [comment]
Hoptkey is back working - for now.

Thread remains open until the bug report at Blender is dealt with.

**Comment by ReinerBforartists** [comment]
LOL. still not fully fixed. Now switching to object mode is 7 ...

**Comment by ReinerBforartists** [comment]
Autosave preferences had trapped me here ... -.-

**Comment by ReinerBforartists** [comment]
The issue remains of course valid. The main cause is not fixed. But we have the mode buttons in our keymap stable since a pretty while. So let's close this stone old task here.
