### ISSUE TITLE
New Icon set. Get rid of unneeded "node" icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#912]
I made the mistake to create special node icons. And this even for icons that already existed. Textures mostly. The node icons have all a square up right to make them node icons.

It's not this much. two or three dozen or so where we really have normal pedants already that could be reused in the node editor. But this space can be saved. We could remove quite a few not necessary icons that way. And in the new icon set i want to remove this square up right in the icon anyways.

Task: Get rid of unneeded "node" icons. This includes to remove them from the code and from the icon sheet and the UI_icons.c file, and add the normal pedants in the code.

The area in question is the sidebar in the node editor.

![sidebar](https://user-images.githubusercontent.com/13919702/58269613-3cc3cd00-7d88-11e9-8085-632ace3f86b3.jpg)

![stucciexample](https://user-images.githubusercontent.com/13919702/58269617-3fbebd80-7d88-11e9-881c-25d0950b64de.jpg)

**Comment by Draise14** [comment]
Ouch, this is a big task. I was wondering what that little square was for.

**Comment by ReinerBforartists** [comment]
To mark this icons as node icons. Nobody's perfect, and this was everything but a glorious idea. At that time i thought it is one :)

**Comment by ReinerBforartists** [comment]
Have to do this job first so that i can continue with preparations ...

**Comment by Draise14** [comment]
Ah ok. The icons I made have the little square for consistency are as independant paths/objects - so that will be easy to remove from the SVG file directly.

**Comment by ReinerBforartists** [comment]
Roughly three dozen double icons to remove.

OUTLINER_DATA_CAMERA - CAMERA_DATA

GAME ???

NODE_ALPHA - IMAGE_ALPHA
NODE_BLEND - BLEND_TEX
NODE_CLOUDS - CLOUD_TEX
NODE_COLOR - COLOR
NODE_DIFFERENCE - SELECT_DIFFERENCE
NODE_DISPLACE - MOD_DISPLACE
NODE_DISTANCE - DRIVER_DISTANCE
NODE_DISTORTEDNOISE - NOISE_TEX
NODE_FILTER - FILTER
NODE_FLIP - FLIP
NODE_HAIRSHADER - HAIR
NODE_IMAGE - ICON_FILE_IMAGE
NODE_LEVELS - LEVELS
NODE_MAGIC - MAGIC_TEX
NODE_MASK - MOD_MASK
NODE_MOVE - TRANSFORM_MOVE
NODE_MOVIE - FILE_MOVIE
NODE_MUSGRAVE - MUSGRAVE_TEX
NODE_NOISE - NOISE_TEX
NODE_NORMAL - RECALC_NORMALS
NODE_RENDERLAYER - RENDERLAYERS
NODE_ROTATE - TRANSFORM_ROTATE
NODE_SCALE - TRANSFORM_SCALE
NODE_SCRIPT - FILE_SCRIPT
NODE_STUCCI - STUCCI_TEX
NODE_SWITCH - SWITCH_DIRECTION
NODE_SWITCHVIEW - VIEW_SWITCHACTIVECAM
NODE_TEXTURE - TEXTURE - TEXTURE_DATA - SEQ_PREVIEW
NODE_TIME - TIME
NODE_VORONI - VORONI_TEX
NODE_WOOD - WOOD_TEX
NODE_WORLDOUTPUT) - WORLD_DATA - ICON_WORLD
NODE_LAMP - LAMP_SUN
NODE_MARBLE - MARBLE_TEX
NODE_UVMAP - ICON_GROUP_UVS

![threedozen](https://user-images.githubusercontent.com/13919702/58366733-06e12e80-7ed7-11e9-812c-aeb9da7219d5.jpg)

**Comment by ReinerBforartists** [comment]
Okay, the game icon remains for now. There might be addons who uses it.

**Comment by ReinerBforartists** [comment]
SEQ_PREVIEW, hmmm. We should make a unique item here. It's the texture tab icon ...

![seqpreview](https://user-images.githubusercontent.com/13919702/58367477-013c1680-7ee0-11e9-9d32-49642f7d6b8b.jpg)

**Comment by ReinerBforartists** [comment]
And done. Fixed in master.

Draise, i have changed a few icons in the space_sequencer.py file. You might want to do a pull before you continue with your task(s).
