### ISSUE TITLE
Outliner - different heights in different workspaces

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#915]
I just realized that the outliner has different size in different workspaces. And so the properties editor dances around when you switch to another workspace. 

It would be more consistent with an equal size. But shall we even fix this? Different workspaces have different needs, and the outliner is not so important in the UV Editing workspace.

![differentheight](https://user-images.githubusercontent.com/13919702/58539459-b1b75c80-81f7-11e9-8680-6e2e734e57ff.jpg)

**Comment by ReinerBforartists** [comment]
What we need to fix is the toolbar. Sometimes it is above the outliner, sometimes it ends at the outliner. This is inconsistent.

![position](https://user-images.githubusercontent.com/13919702/58541511-f47b3380-81fb-11e9-9d3d-df996a54d13c.jpg)

**Comment by Draise14** [comment]
Yeah, that would be make it more consistent for both item. I would vouch for consistency, but making it a similar dimensions in all workspaces must be tricky! You'd need an overlay measure right?

**Comment by ReinerBforartists** [comment]
We will see ;)

**Comment by ReinerBforartists** [comment]
Fixed in master
