### ISSUE TITLE
Workspace - BFA Toolbar not present in Shading causing inconsistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#918]
![bforartists_2019-05-29_22-44-24](https://user-images.githubusercontent.com/35357409/58607022-7fdbdf80-8263-11e9-9f49-5157f4a19298.png)

## Issue
The shading workspace layout on default startup has no toolbar (inconsistent with the rest of the UI)

This appears to be a regression from a merge somewhere. 

## Task
Just add it back to the **startup.blend** file

**Comment by ReinerBforartists** [comment]
Our toolbar was never present in this layout. Do you mean the tool settings? They are active. That's the grey area. It's just there are no tools active in your shot, and so there is no content. And we have removed the editortype menu from this area. So it is completely blank when there is no tool active.

What we have here is a name problem. They made the Tool Shelf at the side to the Toolbar. Our toolbar is the one at the top ...

I will make a new task for it. And close this one as invalid.

![toolsettings](https://user-images.githubusercontent.com/13919702/58611772-952b2b00-82b0-11e9-9384-5b6050729302.jpg)

**Comment by Draise14** [comment]
I was referring to the toolbar from BFA. We have had all workspaces with the base file and undo toolbar sections as in BFA1 and we did this for 2 also. I worked on it and have previous builds with all workspaces with the toolbar. It's a regression.  

It is inconsistent if the toolbar doesn't show in some layouts.

**Comment by ReinerBforartists** [comment]
Ah, that's what you mean. Yeah, it is present in the UV Editing workspace. But in this workspace the Image editor is just to show an image, not to modify it. Ways too small for that. And i don't want to eat even more UI space by a toolbar that you don't even use.

Closing ;)

**Comment by Draise14** [comment]
I am not being clear. 

The BFA toolbar is not present in the Shader layout when it all other layouts it's there. The material layout has it even (almost the same workspace). 

## Issue:
![bforartists_2019-05-30_11-34-10](https://user-images.githubusercontent.com/35357409/58648261-f19d4300-82ce-11e9-8e65-44e5e28115e6.png)

## Consistency:
![bforartists_2019-05-30_11-33-57](https://user-images.githubusercontent.com/35357409/58648233-e8ac7180-82ce-11e9-8a98-cfc274b12fb6.png)
![bforartists_2019-05-30_11-33-49](https://user-images.githubusercontent.com/35357409/58648234-e8ac7180-82ce-11e9-8233-8d9555529753.png)
![bforartists_2019-05-30_11-33-40](https://user-images.githubusercontent.com/35357409/58648235-e8ac7180-82ce-11e9-94f8-9b2540dcb32b.png)
![bforartists_2019-05-30_11-33-33](https://user-images.githubusercontent.com/35357409/58648236-e8ac7180-82ce-11e9-93a8-b006dc2de4a0.png)
![bforartists_2019-05-30_11-33-27](https://user-images.githubusercontent.com/35357409/58648237-e8ac7180-82ce-11e9-8f57-c04e37b59895.png)
![bforartists_2019-05-30_11-33-19](https://user-images.githubusercontent.com/35357409/58648238-e9450800-82ce-11e9-8282-c0aed827ba94.png)
![bforartists_2019-05-30_11-33-12](https://user-images.githubusercontent.com/35357409/58648240-e9450800-82ce-11e9-965a-8efcca47ee3e.png)
![bforartists_2019-05-30_11-33-04](https://user-images.githubusercontent.com/35357409/58648242-e9450800-82ce-11e9-8cf7-7c0ae1029ae9.png)
![bforartists_2019-05-30_11-32-54](https://user-images.githubusercontent.com/35357409/58648243-e9450800-82ce-11e9-971f-3d6493dcbfeb.png)
![bforartists_2019-05-30_11-32-45](https://user-images.githubusercontent.com/35357409/58648244-e9450800-82ce-11e9-9207-4522b8712d2a.png)
![bforartists_2019-05-30_11-32-37](https://user-images.githubusercontent.com/35357409/58648245-e9450800-82ce-11e9-9cb2-650f5571a8bf.png)
![bforartists_2019-05-30_11-32-28](https://user-images.githubusercontent.com/35357409/58648246-e9dd9e80-82ce-11e9-8687-cbda6885bf1b.png)
![bforartists_2019-05-30_11-32-17](https://user-images.githubusercontent.com/35357409/58648249-e9dd9e80-82ce-11e9-8310-3a3802028067.png)
![bforartists_2019-05-30_11-32-06](https://user-images.githubusercontent.com/35357409/58648250-e9dd9e80-82ce-11e9-85c9-042a3e511ce5.png)

**Comment by ReinerBforartists** [comment]
Draise, could you please leave closed issues closed? Thanks.

**Comment by ReinerBforartists** [comment]
There is no toolbar in this layout present at all. I already explained that the tool area is there, that it is just empty since there is no active tool. There is nothing to do or to fix here. I will not crowd this layout with our toolbar even more.

**Comment by ReinerBforartists** [comment]
Okay, we have the toolbar in this layout in the ALL template. Now there is a reason to reopen it. That's inconsistent. The templates must look equal.

![toolbar](https://user-images.githubusercontent.com/13919702/58686752-f53cd280-837f-11e9-82c4-727f12ad4faa.jpg)

**Comment by ReinerBforartists** [comment]
Related. Where the heck comes the Material workspace from? It is nothing else than the Shading workspace. And doesn't exist in Blender.

![material](https://user-images.githubusercontent.com/13919702/58687145-1e119780-8381-11e9-963c-685858fd740a.jpg)

**Comment by ReinerBforartists** [comment]
Made a task for it

Material Workspace versus Shading Workspace #923

**Comment by ReinerBforartists** [comment]
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/58693631-7d77a380-8391-11e9-85f8-4b433121de41.jpg)
