### ISSUE TITLE
Toolbar - make the Misc/Undo/Last Operator/Search consistent in order

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#922]
## Issue
Right now we have two toolbar type icon row menus that are consistent globally in all the interface, the toolbar types **File** and **Misc**. 
The issue right now is that Misc floats left and is at the end of the stack, meaning it jumps around in the toolbar depending in which layout you are in due to different activated toolbar types inbetween. There is a risk of loosing access (without scrolling the toolbar by middle click) to this menu type all together when all menu types are activated. 

This is difficult for muscle memory, consistency and feels a bit broken. 

![bforartists_2019-05-30_11-50-50](https://user-images.githubusercontent.com/35357409/58649505-e3045b00-82d1-11e9-9bf4-61e4ba750757.png)

## Solution
Solution 1: Move the toolbar type up with the File, so that they stop jumping around when the workspace changes. 
Solution 2: Make the Misc type float right so it's always to the toolbar right in all workspaces

## Alternatives
An alternative is changing/re-ordering the Misc operators around so that the Undo/Redo/History/Search and Last Operator entries go into the File menu and leave the Misc where it is with whatever is left.

**Comment by ReinerBforartists** [comment]
Fixed in master
