### ISSUE TITLE
Video Sequencer - Add Modifier double entry name inconsistency

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#926]
## Issue 
![bforartists_2019-05-31_10-02-23](https://user-images.githubusercontent.com/35357409/58724081-52954b80-83a1-11e9-806e-9a7064ec581c.png)
I need to clarify what kind of task I need to turn this into. BFA tries to reduce redundency and make discoverability all in familiar places and not done twice over unless with a customizable toolbar. 

Right now there are now two ways to add strip modifiers:
1. Through the Modifiers tab in the sidepanel
2. Through the header in a sub-menu. 

The only issue is it's in two places AND the naming conventions are different. 

## Solution
Solution 1: change names of the header entries to be consistent
Solution 2: remove the header entries entirely and keep it to the modifiers tab

What should we do about this? Is this a task?

**Comment by ReinerBforartists** [comment]
Is of course a task.

What would you prefer? To have it in the tool shelf, or in the menu? How was this solved in BFA1?

**Comment by Draise14** [comment]
This menu had no entry in the header on BFA. They added it in 2.8. 

Right now I'm not sure what the UI design consistency should be. Unlike BFA1. 

1. Every single operator should be discoverable in the header and everything else in toolshelves, property shelves, hotkey menus and operators, pies and toolbars would be an accessibility justified double entry?

2. Every operator should be instanced max twice and the initial area will be according to accessibility (toolshelf) as priority  the header is the container for everything else? (Similar to BFA1)

I'd just fix the naming for now. Personally.

**Comment by ReinerBforartists** [comment]
It's simple. Operators should be called from either the tool shelf or the text menus in the header. Sidebar is for settings. Left tools, right settings.

**Comment by Draise14** [comment]
Ok, changed name for consistency sake.
