### ISSUE TITLE
Video Sequencer - Move view properties from Header to View Tab

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#927]
## Issue
![bforartists_2019-05-31_09-59-14](https://user-images.githubusercontent.com/35357409/58724544-89b82c80-83a2-11e9-99f1-ab2c21d19881.png)

This is a regression from a merge, but the view properties from the Video Sequencer strip view that usually are displayed in the View tab of a sidebar are back in the header entries. They need to be moved back to the view tab. 

## Solution
Move them back to a panel in the View Tab of the sidebar?

**Comment by ReinerBforartists** [comment]
Merges ... -.-

**Comment by ReinerBforartists** [comment]
Hm, it's not only this handful props. It's much more. The merge in question has killed every change, also in other menus.

Former view menu ...
![viewold](https://user-images.githubusercontent.com/13919702/60324096-1e06b680-9984-11e9-98bf-cc34b8861df6.jpg)

**Comment by ReinerBforartists** [comment]
Okay, made a drastic remerge with the old code. Draise i need your help here now. Please check for lost functionality. I expect that i might have killed some things now. And i don't know the VSE good enough to find those tools.

**Comment by Draise14** [comment]
Ok, will go through it today with a video edit and check things.

**Comment by Draise14** [comment]
![bforartists_2019-07-05_12-51-31](https://user-images.githubusercontent.com/35357409/60742665-d8259180-9f33-11e9-979e-15d994773b83.png)

Ok! The only view option left is the Preview Backdrop. Should I take this on and try move it over? I think I'm getting familiar with how everything works in the VSE to do it.

**Comment by ReinerBforartists** [comment]
Yeah, sure :)

**Comment by Draise14** [comment]
Ergh, the Grease pencil changed just now, forgot to update the file. I'll have to recommit, one sec.

**Comment by Draise14** [comment]
Ah.. well I used the original from master and did the change and it still shows the GP lines - but makes sense...? 

I'll pull it.

**Comment by Draise14** [comment]
![bforartists_2019-07-31_09-05-41](https://user-images.githubusercontent.com/35357409/62221339-22edca00-b377-11e9-8aa8-d816b07d1098.png)
