### ISSUE TITLE
Node Editor - View Menu pulls an error and is empty

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#928]
## Issue
The view menu is empty and pulling an error in the Node Editor. Is my building doing funny things? I merged these files in today to my branch and now I get these errors. 

![image](https://user-images.githubusercontent.com/35357409/58726337-19f87080-83a7-11e9-982d-de430dbcea61.png)

**Desktop (please complete the following information):**
Windows 10. Nvidia GTX 1060

**Comment by Draise14** [comment]
![atom_2019-05-31_13-36-50](https://user-images.githubusercontent.com/35357409/58727172-2e3d6d00-83a9-11e9-8529-8f18ef4e40a4.png)

Ah, found it. The Snode was not being defined in the definition of that particular menu. So.. I defined it with one entry (from the other menu's) then it fixed itself. 

@ReinerBforartists , is this a bug/task? Or was it just a merge issue on my branch?

**Comment by ReinerBforartists** [comment]
It's a bug!

**Comment by ReinerBforartists** [comment]
Fixed in master
