### ISSUE TITLE
Video Sequencer - Strip Menu broken

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#930]
We have still a icon problem somewhere And the strip menu is cut off.

![iconproblem](https://user-images.githubusercontent.com/13919702/58745323-e02f7480-844f-11e9-817b-b75e68a80c14.jpg)

**Comment by ReinerBforartists** [comment]
KK, first things first -.-

**Comment by ReinerBforartists** [comment]
Fixed in master

**Comment by ReinerBforartists** [comment]
Draise, please always check what you change.

**Comment by Draise14** [comment]
huh? I re-compiled and tested and didn't get this. I'll check to see what was the fix. weird.

**Comment by Draise14** [comment]
Ah I see. The "icon" name was included. These are present in the icon svg IDs on some so I trusted it. 
So to make sure best to guide from the H file...? 
I could swear I checked and had no error. Sorry bout that. Next time I'll try place the old compile on another desktop. I might have confused myself. Hmm.

**Comment by ReinerBforartists** [comment]
That's development. I was trapped by this before. And sometimes such things simply slips through. I just mentioned it since now you will check twice with icon names. I learned it the hard way too ;)
