### ISSUE TITLE
3D View Header - Remove names in panel dropdown menus 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#935]
Blender devs have removed the names from the panel dropdown menus for Overlays and Shading. A good thing. We should do the same.

Not so sure with the View dropdown menu ...

![panelsnonames](https://user-images.githubusercontent.com/13919702/58746312-3ce55c00-845d-11e9-9f3a-ab0a04e69fa7.jpg)

**Comment by Draise14** [comment]
The same? No name?
Or in the title in the submenu/tooltip?

**Comment by ReinerBforartists** [comment]
No name saves UI space. Do you want to keep them?

**Comment by Draise14** [comment]
No no. Tooltip or within the panel when opened and shown. I'm agreeing with you.

**Comment by ReinerBforartists** [comment]
Fixed in master
