### ISSUE TITLE
Icons doesn't update at compile

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#936]
When changing the icons and recompiling the changes, then the icons doesn't arrive in Bforartists. All is correct, icons are in the sheet, and the conversion isn't troubled neither. It's either the cmake cache where still the old icons reside, or the VS cache.

This is new to me. In earlier builds changed icons did change without the need to rerun cmake from scratch or to rebuild everything.

We have at one point removed the list of icons in a cmake file, since it made lots of trouble. Let's have a look if this is the cause.

**Comment by ReinerBforartists** [comment]
Let's first add all icons to the cmake file, and see if it works then ...

**Comment by ReinerBforartists** [comment]
Hm, cmake file is updated, still no luck -.-

**Comment by Draise14** [comment]
I usually build and re-build off the same Cmake file. But to do it right, I have to "Rebuild" on a already compiled version from VS. If I don't want to rebuild on a VS build, I have to remove the build by removing it from the VS bin, then "Build" again in VS from the same Cmake to see the changes. 

For quick UI changes to test the icon changes, I run a "lite" Cmake version that take 5-7 minutes to finish, then finally a "full" version that takes me the usual 20-30 minutes to test.

**Comment by ReinerBforartists** [comment]
As told, this wasn't necessary before. A simple recompile without the need to do from scratch once did the trick. But i cannot find out what has changed. Sad :(

Well then, then it's really rebuild from scratch all the time ...

**Comment by Draise14** [comment]
I had no idea VS could update a build after changes to the repository??

Wait, you can just recompile (rebuild), that's what I was trying to imply.
 
1. VS loads up the project
2. VS loads up the repository
3. VS compiles - see changes
4. VS has build in a BIN folder
4b. Rebuild/compile after updating the VS project with the repository changes
4c. See changes

Option 2:
5. Remove BIN build
6. Build/Compile after updating VS project with the repository changes
7. See changes

It's not technically from scratch, no? What was the workflow before? (just curious, thanks for the time answering!)

**Comment by ReinerBforartists** [comment]
The workflow as i remember was to create cmake from scratch, then just build in VS every time you updated the iconsheet. Just build, not rebuild. Hmmm.

**Comment by ReinerBforartists** [comment]
Removing the exe from the bin folder so that it gets recreated seems to be the closest that we can achieve at the moment. 

Giving up and closing this issue.
