### ISSUE TITLE
Export Dialogue Improvement

### ISSUE THREAD

**Issue by CyberFoxHax** [Bforartists/Bforartists#937]
Not sure what it's internal name is. But the export options is in the lower right corner and the actual export button on the right side of the monitor. (Unless you doubleclick a file).

An easy solution would be to shrink the entire UI.

A longer solution would be to rearrange the UI. Leaving the save button somewhere in the bottom so it creates a natural top to bottom flow.

(also the fbx export options jumps up and down in a strange way when used)

**Comment by ReinerBforartists** [comment]
Hi CyberFoxHax,

Thanks for your suggestions. It's actually not this easy. The im- and export settings are extra, and exists in every addon for the file formats. For FBX it's so much different settings that you need to divide it. And that's where things starts to jump around, when you switch to the different chapters.

We can't shrink the im and export dialog neither. It's not a popup like for other software. It is an editor type like all the other editor types too. And implemented in a very special way.

We will have a look what we can improve here. But please don't expect fast results. This issue has low priority.

**Comment by ReinerBforartists** [comment]
Hm, C code. I hate it :'3

**Comment by ReinerBforartists** [comment]
Blender has started a branch to redesign the file browser. So i guess it's wiser to wait a bit longer. Especially since my tries to find out how the file browser code is connected wasn't really successful so far ...

https://developer.blender.org/diffusion/B/browse/filebrowser_redesign/;ce6e34e131840c99b25c2ca98a532ea7ec73f510

**Comment by CyberFoxHax** [comment]
Good work. I agree it's wiser to wait and see what happens to canon.

**Comment by ReinerBforartists** [comment]
Honestly, the Blender devs did a pretty good job here with the redesign. There is nothing left to improve from my angle of view.

So closing.
