### ISSUE TITLE
Cycle through the unsaved changes dialog

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#941]
Not sure if we can even manage this. But it would be nice when you could cycle through the three buttons in the unsaved changes dialog. So that you don't need the mouse to reach the discard changes button. This is very common in quite a few software ...

![cyclethrough](https://user-images.githubusercontent.com/13919702/58949710-5b18c800-878d-11e9-8b49-93eab34a05ed.png)

**Comment by ReinerBforartists** [comment]
Investigating the possibilities ...

**Comment by ReinerBforartists** [comment]
This part is done in pure C. No access by python. And Blender does not support such tabbing from what i know.

Well, was a nice dream. Closing.

**Comment by ReinerBforartists** [comment]
kthotheoz wants to have a look at it. Maybe he finds a way.

**Comment by ReinerBforartists** [comment]
Dialog is in source\blender\windowmanager\intern\wm_files.c

**Comment by ReinerBforartists** [comment]
I think it is safe to close this issue. We haven't touched it since over a year, and will most likely never touch it. 

Closing.

**Comment by ReinerBforartists** [comment]
@iyadahmed, do you see a chance here? If not, no problem. Then we will close this issue again :)

**Comment by iyadahmed** [comment]
I'll give it a try :)

**Comment by iyadahmed** [comment]
just curious, would this be done through arrow keys, scroll wheel or so?, I think it is already done by OS using tab key

**Comment by ReinerBforartists** [comment]
Arrow keys usually. That's how it works in Gimp for example. Tab key does not work here.

**Comment by iyadahmed** [comment]
oh ok, will give it a try after other task

**Comment by ReinerBforartists** [comment]
No pressure :)

**Comment by ReinerBforartists** [comment]
Okay, this simply lasts too long now. No takers since eons. I have no idea how to fix it. So let's finally close it. We can't fix everything. To fix the things that we are able to is more than enough.

**Comment by iyadahmed** [comment]
> Okay, this simply lasts too long now. No takers since eons. I have no idea how to fix it. So let's finally close it. We can't fix everything. To fix the things that we are able to is more than enough.

Yep and if we ever find a way we can always make it
