### ISSUE TITLE
Datablock props - Fake, New and Load icons 

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#944]
The datablock props have their own icons now without any reason. There is a new Plus icon and a new Folder icon while the old icons still exists and are in use in the icon sheet. At least the Plus sign is at more than one location ...

The Blender icons are really alien now. The useage is not to recognize anymore. I prefer the old add button, which is a plus. And the fake user icon looks also different with every new incarnation. The Protect shield does definitely not fit. This has nothing to do with a fake user. We should go back to F like it was before.

![obsolete](https://user-images.githubusercontent.com/13919702/59048560-5ab02800-8886-11e9-9b2b-fcd193652be3.jpg)

![blender](https://user-images.githubusercontent.com/13919702/59048679-a82c9500-8886-11e9-87de-6f79b26256e8.jpg)

**Comment by ReinerBforartists** [comment]
The old plus sign is zoom in. It is quite a few times reused. Also in addons. So we can't remove this icon easily. The new icon called ADD is basically unsearchable in the code because of its name. Also not to remove. 

So we end in two icons with same look here. That's the easiest solution.

**Comment by ReinerBforartists** [comment]
The fake user heart is not used anymore. It's now two icons. FAKE_USER_OFF and FAKE_USER_ON

**Comment by Draise14** [comment]
I feel like the devils advocate these days, sorry man...

If it wasn't called "Fake User" but what they really area: datablocks - then the protect shield and "duplicate" symbol would make sense - of which it is does (protect/store the datablock and duplicate the datablock instead of add a new "duplicate" and fake use?/store a datablock). 

"Fake user" is.. a little bit abstract and as a new user to Blender/Bfa a few years back, this had me so confused till I understood these were controls to work with datablocks.

**Comment by ReinerBforartists** [comment]
I hope that they remove this whole concept at one point. It should not be the users choice to care that the software does not forget vital components.

**Comment by ReinerBforartists** [comment]
Fixed in master. As wished, we also have a shield icon now for the fake user button ...

![fake](https://user-images.githubusercontent.com/13919702/59143076-f301f600-89c7-11e9-9432-f8b5d6228b15.jpg)

**Comment by Draise14** [comment]
> I hope that they remove this whole concept at one point. It should not be the users choice to care that the software does not forget vital components.

I agree. It's only useful for... libraries? But an asset manager would make this so redundant.
