### ISSUE TITLE
Outliner - Viewport Visibility icon not showing in Scene View

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#955]
# Issue
![bforartists_2019-06-14_21-06-11](https://user-images.githubusercontent.com/35357409/59545729-4bfdec80-8ee8-11e9-9b7f-74088d4090f3.png)

Outliner doesn't show the Viewport visibility icon, though it should be a broken eye icon. (Or is it supposed to be a monitor/screen icon??) 

## Build info: 
![bforartists_2019-06-14_21-08-09](https://user-images.githubusercontent.com/35357409/59545743-8a93a700-8ee8-11e9-819f-28236bdc760f.png)

**Comment by ReinerBforartists** [comment]
Hmm, not to reproduce, here it works fine. The new icon needs a fix though. The white outline makes trouble ...

![iconshowing](https://user-images.githubusercontent.com/13919702/59548096-e7737980-8f49-11e9-8f32-d6c3c2189b18.jpg)

**Comment by ReinerBforartists** [comment]
Compiled from scratch. The fixed icon looks clearer now. Still no problem though. Draise, do you have a error message in the console?

![worksfine](https://user-images.githubusercontent.com/13919702/59549604-6ecbe780-8f60-11e9-8441-0f8dba088eb3.jpg)

**Comment by Draise14** [comment]
Hmm... I'll try compile from master. 

I get this error in console:
![bforartists_2019-06-15_08-04-13](https://user-images.githubusercontent.com/35357409/59551774-433b0400-8f44-11e9-88f4-fde8837bb3b3.png)

**Comment by Draise14** [comment]
Ok, opened from a blank scene, got the same issue but no console error. Must be from something else. I'll compile from master and recreate the Cmake.

**Comment by ReinerBforartists** [comment]
al lib is the sound card driver part. Shouldn't have anything to do with the icon.

**Comment by Draise14** [comment]
![bforartists_2019-06-17_09-56-55](https://user-images.githubusercontent.com/35357409/59614374-42da6e80-90e6-11e9-80d9-61f92e051052.png)

Recompiled and it fixed.

**Comment by ReinerBforartists** [comment]
\o/

This was most probably a cache issue with cmake :)
