### ISSUE TITLE
Node Editor - selecting a node causes a console bug

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#956]
# Issue
![bforartists_2019-06-15_08-50-25](https://user-images.githubusercontent.com/35357409/59552294-b0ea2e80-8f4a-11e9-9cda-04c93c8f10e2.png)

When you click and select a node in the material mode of the Node Editor, it pulls up 3 errors in line 554 of the bl_ui\space_node.py file. Functionality doesn't appear to be of any harm, just.. it's weird. 

```
node = context.active_node
NameError: name 'context' is not defined

```

**Comment by ReinerBforartists** [comment]
Thanks for the report. Seems that i should do a few tracker issues next week ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
