### ISSUE TITLE
3D View - Header toggle shown twice on new 3D View (with tool settings off)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#957]
# Issue
![bforartists_2019-06-17_09-54-01](https://user-images.githubusercontent.com/35357409/59614199-dfe8d780-90e5-11e9-9700-b466ecb81cda.png)

When you divide the 3D view, then hide the tool settings, and when unhide the Editor Types, you'll automatically get TWO Editor Type entries. With the Hide Editor Types on, you'll get one. 

This is not true with the original 3D View, only new UI divided 3D Views. 

## How to Reproduce
1. Divide the 3D view
2. Toggle and hide the tool settings in the new 3D View
3. Toggle the Hide Editor Type in the new 3D View (optional)
4. See two Editor Type entries/or still see the Editor Type even though it's hidden

**Comment by ReinerBforartists** [comment]
Nice bug. I could swear i had ironed this one out already ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
