### ISSUE TITLE
Video Sequencer - Cleanup Strip menu icons after merge regression

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#961]
# Issue
Some of the icon entries to the Strip menu of the VSE were reverted to nothing, and others moved to new menu's and a couple repeated. 
![bforartists_2019-06-19_12-17-39](https://user-images.githubusercontent.com/35357409/59787016-25480900-928e-11e9-9920-7bbe6a003df3.png)
![bforartists_2019-06-19_12-21-44](https://user-images.githubusercontent.com/35357409/59787019-2711cc80-928e-11e9-9935-681bd53fbe91.png)

# Task
Add them back as they all exist still in the iconsheet lists. This regression from the merge was part of the task #765, so it's doing that.

**Comment by Draise14** [comment]
Ok, fixed this up. I have NOT committed yet till AFTER I have the current pull from #960 done. I will tag this as done. 

_Kinda sucks I can only do only one commit/task per day....._

**Comment by Draise14** [comment]
![bforartists_2019-06-19_13-03-25](https://user-images.githubusercontent.com/35357409/59789022-a43f4080-9292-11e9-80d0-d3e666ac2f12.png)
![bforartists_2019-06-19_13-04-07](https://user-images.githubusercontent.com/35357409/59789061-bcaf5b00-9292-11e9-8cf9-a0c73bfb2da3.png)

Here are the fixes.

**Comment by ReinerBforartists** [comment]
Please don't label issues as fixed as long as they are not in the repository. They are not fixed until that point.
