### ISSUE TITLE
3D View - Viewport Shader mode icons revision

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#962]
# Issue
Right now the new shader mode icons are clear, but not as pretty nor consistent as the former shader mode icons. The former shader mode icons still exist in the icon sheet. The wireframe icon also is confusing with the overlays and show xray icon, as it's a square on square instead of a circle. 

Current:
![bforartists_2019-06-19_12-57-46](https://user-images.githubusercontent.com/35357409/59789185-12840300-9293-11e9-956d-89b04bab30d4.png)

Former:
![inkscape_2019-06-19_12-54-33](https://user-images.githubusercontent.com/35357409/59789194-17e14d80-9293-11e9-90f4-f68365243040.png)

Conflicting icon interpretations:
![bforartists_2019-06-19_13-07-53](https://user-images.githubusercontent.com/35357409/59789351-5d057f80-9293-11e9-9af2-59957d04da7b.png)

The rendered shader mode ball with the scanline also is not true to symbolism as both Eevee and Cycles do not ever use scanline systems to render, one is a raytracer with tiles and the other is a rasterizer. They both look beautiful. The beautiful former sphere made sense for all render modes. 

# Solution
1. Change the wireframe icon to the former
2. Improve the new icons to be similar to the former
3. Remove redundant icons from Iconsheet and UI_icons.h list.

**Comment by ReinerBforartists** [comment]
I will see what i can do here

**Comment by Draise14** [comment]
![bforartists_2019-06-19_14-14-02](https://user-images.githubusercontent.com/35357409/59793783-043ae480-929d-11e9-8d22-3ac822bd5ad2.png)

Yeah, they can be simplified to a degree to have better contrast - they would need to be improved/minimized. I found the file where these can be changed: **\\Bforartists\source\blender\makesrna\intern\rna_space.c**

**Comment by ReinerBforartists** [comment]
Um. No. This is not the place to improve icons. What are you trying to do there? O_O

**Comment by Draise14** [comment]
I just tested reverting to the former icons to see how it would look. Nothing committed, nothing changed to the repository, mainly to learn and do the screencap. The wireframe on a sphere definitely is more harmonious.

**Comment by ReinerBforartists** [comment]
Ah okay. I will revert it to sphere.

**Comment by ReinerBforartists** [comment]
![improved](https://user-images.githubusercontent.com/13919702/59832259-baf1a000-9343-11e9-94e2-c4d1d3c56ad9.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master.
