### ISSUE TITLE
Translation in U.I. ??

### ISSUE THREAD

**Issue by DarthMoulByte** [Bforartists/Bforartists#964]
How can I do this, to create corrections and translations of the interface, or create a new translation?

![image](https://user-images.githubusercontent.com/24207840/59797063-6e0abc80-92a4-11e9-9fcd-dcae83c9729e.png)

https://wiki.blender.org/wiki/Process/Translate_Blender
https://svn.blender.org/svnroot/bf-translations/

**Comment by ReinerBforartists** [comment]
Hi DarthMoulByte,

For the |18n branches edit box, you need to add a link to the folder with your po files in the repository. That's usually mydrive\myrepository\release\datafiles\locale, while mydrive and myrepository are your local paths at your drive.

To be honest, i never managed to get translation to work. Best would be to ask the Blender developers here.

**Comment by ReinerBforartists** [comment]
I'm closing this one for now.

**Comment by DarthMoulByte** [comment]
> Hi DarthMoulByte,
> 
> For the |18n branches edit box, here you need to add the path to the folder with your po files in the repository. That's usually mydrive\myrepository\release\datafiles\locale, while mydrive and myrepository are your local paths at your drive.
> 
> To be honest, i never managed to get translation to work. Best would be to ask the Blender developers here.

thank you for the answer, I think the route is fine, just that you need to assign or mention the container file of the translation, even though the help is a big step forward
