### ISSUE TITLE
Preferences - Addons categories Icons need indice or tooltips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#967]
# Issue
Addons now have icon categories or something - but no indice or tooltip to show what the icon is for (is it a category for Contrib, internal or third party?). Right now it's unclear what they are supposed to show. 

![bforartists_2019-06-21_15-16-55](https://user-images.githubusercontent.com/35357409/59949061-a1318500-9437-11e9-9511-e1697e08ce2f.png)

## Solution: 
- Add tooltips
- Add an indice?
- Add the icons to the filter button to make up for the indice needs?

**Comment by ReinerBforartists** [comment]
Never did this before. Will be interesting :)

**Comment by ReinerBforartists** [comment]
Hm, we could save us the tooltip when we would add the icons to the buttons ...

**Comment by ReinerBforartists** [comment]
Bad karma. There is no way to add an icon to the current enum from what i can see. Never seen this kind of implementation before. It is not meant to contain an icon. 

Same trouble goes by the way for the try to add a tooltip to the icons at the addons.

Giving up. Too much other things to do first ...

![enum](https://user-images.githubusercontent.com/13919702/60009630-7e40e400-9676-11e9-8d24-103c4d6871be.jpg)

**Comment by ReinerBforartists** [comment]
Draise, maybe you want to try here? You would most probably need to ask a Blender developer here though ...

**Comment by ReinerBforartists** [comment]
This is crazy, it should work, but it doesn't

http://blender.45788.x6.nabble.com/SVN-commit-data-svn-bf-blender-54055-trunk-blender-source-blender-Fix-31338-python-enum-properties-cg-td103562.html

And the error message even states this. It expects an icon if available. I have no idea in what format though, have played around, and no luck so far.

![errormessage](https://user-images.githubusercontent.com/13919702/60012660-cf53d680-967c-11e9-8194-907827853a1d.jpg)

**Comment by ReinerBforartists** [comment]
Have it. It expects a unique number too. 

> ... an icon name and unique number ...

Okay, let's iconize this three buttons.

**Comment by ReinerBforartists** [comment]
Fixed in master

The crazy thing is, the last item in the tuple requires the unique number 4. Functionality will break with unique number 3. Only Blender devs knows what exactly is conflicting here ...

![uniquenumber](https://user-images.githubusercontent.com/13919702/60021404-40ea4f80-9692-11e9-848b-000c5379c7f6.jpg)

**Comment by ReinerBforartists** [comment]
Riddle solved. The required 4 has to do with the ENUM_FLAG. A power of two ID value is required for every new menu item. 

https://blenderartists.org/t/enum-property-with-enum-flag/627069/5
