### ISSUE TITLE
Preferences - Addon has community icon with white square background, breaking silluette

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#968]
# Issue 
![bforartists_2019-06-21_15-08-17](https://user-images.githubusercontent.com/35357409/59948682-827ebe80-9436-11e9-81dc-4ab95931e45e.png)

The people icon also has a white background that breaks the silluete recognition of the symbol. 

## Solution: 
- Remove the white background of the people icon.

**Comment by ReinerBforartists** [comment]
Ah, there is this icon ^^

**Comment by ReinerBforartists** [comment]
Fixed with this commit: https://github.com/Bforartists/Bforartists/commit/89619a62f6a81d0d93bc65ed93546cd90f5b6712
