### ISSUE TITLE
Redo the Modifier icons

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#971]
Working through the icons one after another. The goal is to have simplified icons, and to get rid of the old Blender icons. But not simplified down to monochrome and line art like in Blender. 

This task is about converting the modifier icons, not to reinvent them. The icons and their shape are already well known.

While at it anyways, a color code could help to distinguish and easier refind the different modifiers a bit better. Currently it's one big blue wall of icons, and you are always at reading the text until you arrive at the needed ones. See mockup below. Just not sure how to group the colors. There is no group of modifiers that could make much sense. 

Maybe we can use the same color in the first five icons of each row, then the next color for the next five icons of the row ...

![modifier1](https://user-images.githubusercontent.com/13919702/59966248-d7473580-9519-11e9-9fd4-f759820ee7cd.jpg)

![modifier2](https://user-images.githubusercontent.com/13919702/59966249-f219aa00-9519-11e9-8745-438e44ea1d1b.jpg)

**Comment by ReinerBforartists** [comment]
AAAAAAAAAAAAAAAICONSAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Draise14** [comment]
What a feat of a job. Hang in there! You're my digital hero!

**Comment by ReinerBforartists** [comment]
First iteration. Side effect: now you can better see which icons are reused. Mesh Cache and Mesh Sequence Cache deserves a own icon i would say. And the Bomb icon needs improvement. For the rest, hmm. Doesn't look this bad.

![firstiteration](https://user-images.githubusercontent.com/13919702/60607725-2022a800-9dbe-11e9-954c-e9095d7dcd8a.jpg)

**Comment by Draise14** [comment]
Hard work! I personally liked the muted colour proposal more..? - where all the modifiers had one colour/saturation in common to harmonize, with the colour hue to differentiate. 

But yes, the grouping does help a lot.

**Comment by ReinerBforartists** [comment]
Double use of icons is here and there a bit in the way for that ...

Either way, and for now, fixed in master

![modicons](https://user-images.githubusercontent.com/13919702/60660190-81e32080-9e57-11e9-89e6-a5fe0a82ab74.jpg)
