### ISSUE TITLE
Add a hotkey to access the so called context menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#973]
Some addons writes itself just to this nonsense non contextual context menus that you can call with the right mouse with the Blender keymap. We would loose these addons with our current keymap. And i am not willing to rewrite and maintain the addons in question. We had this drama in BFA1 already.

So we need to find a substitute for the rmb mouse click to call this menus. And add it to our keymap. Alt RMB for example. Be careful, possible conflicts ahead ...

**Comment by Draise14** [comment]
Double R click has no conflict anywhere. What about that?

**Comment by ReinerBforartists** [comment]
Double click is dangerous feature. I would love to avoid this one.

**Comment by ReinerBforartists** [comment]
Drama. Shift, Ctrl and Alt with right mouse are in use for several painting operations -.-

**Comment by ReinerBforartists** [comment]
After digging around to find a useful key, it seems that the double right click is our best bet here. I hope this doesn't conflict too much with navigation. We will see.

**Comment by ReinerBforartists** [comment]
Fixed in master

Very unhappy with this commit. I hate to do nonsense to stay compatible.

Note that there is one quirk left in animation editor. In Blender they call the context menu with the right mouse. But this overrides the former hotkey to move the time line with the right mouse button. We use double rmb, and so the timeline cursor jumps to the mouse position now. Which can be irritating.

**Comment by Draise14** [comment]
Hmm.. ah yeah. That is the only conflict, the R press and R double click.
