### ISSUE TITLE
Properties View - Modifier Stack - BFA1 global modifier header toggle features

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#977]
# Issue
In Bforartists 1, there is a handy modifier stack system for toggling all, hiding all, deleting all and applying all. This no-longer exists in Bforartists 2

**Before**
![bforartists_2019-06-26_14-01-56](https://user-images.githubusercontent.com/35357409/60207444-8a19db00-981b-11e9-9a6a-b077bc6050dd.png)

**Now**
![bforartists_2019-06-26_14-06-27](https://user-images.githubusercontent.com/35357409/60207471-99008d80-981b-11e9-86b4-696eadd2139e.png)

## Solution
Add them back? It's an addon, so it would just need to be included by default startup and activated. 

These are surprisingly really useful. 

### Alternative Solutions
Adding the Modifier Stack Manager addon to add functionality and the box to re-order and change with the missing features listed as a default addon could also work. 

https://github.com/salaivv/modifier-stack-manager

![MOdifier Stack](https://raw.githubusercontent.com/salaivv/modifier-stack-manager/master/screenshots/modifier_stack_manager.JPG)

**Pro's**
It adds the typical material/particle/texture/vertex groups box navigation and makes the modifier stack more consistent with the rest of the UI\
The work would all ready be done, it's just activating the addon and including it in the repository
The functionality of the addon adds better workflows and features than the BFA1 stack toggle header buttons

**Con's** 
It's a third party addon.. 
It's a little harder to understand the stack due to the new system? Not sure.
Might be buggy??? (because it's still a WIP)
The arrow organization and visibility now feels redundant as now they show twice? 
There is no need to have two stacks now due to being redundant?

**Comment by ReinerBforartists** [comment]
The addon is work in progress. So at this point it is a no. Maybe in the future.

There is one thing speaking against it in general: it is not included with Blender. And maintaining third party addons is something that i want to avoid. 

I will nevertheless just postpone it for now. Maybe it even gets included with Blender ...

**Comment by Draise14** [comment]
![bforartists_2019-06-27_15-09-35](https://user-images.githubusercontent.com/35357409/60305455-30d8a700-9902-11e9-900c-56d3c3ad5a9e.png)

I worked a little more on the addon, and it looks like it could be maintained easily enough. I would just need to submit this to Blender directly, but crikey what a bureaucratic system to get things submitted! Geez...

**Comment by ReinerBforartists** [comment]
Addon is included into Blender now. Closing this task.

![addon](https://user-images.githubusercontent.com/13919702/75342352-9072c200-5896-11ea-8890-2d80bb81f0dd.jpg)
