### ISSUE TITLE
Outliner - Add Context menu items to Header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#979]
# Issue
The outliner has some pretty hefty Rclick menus. But they don't exist in the outliner header. You have to Rclick on items to discover them. There is no access to them to aid in adding hotkeys and discoverability, unless I righclick, which is somewhat inconsistent with the rest of the UI philosophy (have everything in headers and not hidden in floating menus hotkey or mouse cliick exclusive).

![bforartists_2019-06-27_13-19-56](https://user-images.githubusercontent.com/35357409/60290560-9e72dc00-98de-11e9-8de6-a6e74393a327.png)

# Solution
Add some or all of these menus and sub-menus into the header.

**Comment by ReinerBforartists** [comment]
Crazy. Where did you find that? I thought i had them all ^^

**Comment by ReinerBforartists** [comment]
We cannot add this context menu to the header for already told reason. Won't fix.

Closing.

**Comment by Draise14** [comment]
Hey wow, a true context menu!!!!!!! Maybe it's a matter of time when the rest of the UI is actually context sensitive in those menus. 

I was wondering about if this was truely necessary... as yes, collections and objects pull up different menu's.
