### ISSUE TITLE
Outliner - move context menu select item to top

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#980]
# Issue
Right now the Rclick context menu over objects in the outliner defaults to copy and paste under mouse on activation; but due to the issue of the outliner not selecting what you highlight, the selecting, selecting hierarchy, etc are more typical. But right now you have to move down to get to them quickly, decreasing time on typical right click functionality. You'd want to select what is highlighted first, later copy. 

# Solution
![bforartists_2019-06-27_13-26-20](https://user-images.githubusercontent.com/35357409/60290910-60c28300-98df-11e9-8d46-931df0015d0b.png)

Move the select group of context operators to top for quick easy access before copy and paste.

**Comment by ReinerBforartists** [comment]
Fixed in master

![Uploading select.jpg…]()
