### ISSUE TITLE
Movie Clip Editor - View Menu - property not found

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#984]
We have a problem in the view menu of the movie clip editor ...

![propertynotfound](https://user-images.githubusercontent.com/13919702/60356929-8a100b80-99d2-11e9-989c-948d97ca8831.jpg)

**Comment by Draise14** [comment]
I can't compile, would this be causing this?

**Comment by ReinerBforartists** [comment]
Definitely not. This is a python code problem.

**Comment by ReinerBforartists** [comment]
Blender bug. 

Reported: https://developer.blender.org/T66240

**Comment by ReinerBforartists** [comment]
Fixed in master
