### ISSUE TITLE
Painting - put available brushes into the toolbar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#99]
The paint panels are not really comfortable to work with. It would be better when some things could  be separated.

Let's try if we can put the brushes into the toolbar. I remember that there was a double menu entry with the brushes anyways. So if everything else fails we could at least put those removed double menus into the toolbar.

![brushesintoolbar](https://user-images.githubusercontent.com/13919702/37758642-3c8c3192-2db1-11e8-8901-263583e5fae3.jpg)

**Comment by Draise14** [comment]
What is the double menu entry of the brushes?

**Comment by ReinerBforartists** [comment]
It was one. The whole brush menu existed once in the header, with small icons. Have a look in Blender ... ah, but it was just checkboxes. No icons. Hmmmm. We will see :)

![brushes](https://user-images.githubusercontent.com/13919702/37786142-2d589b84-2dfc-11e8-9023-dfbe30b35936.jpg)

**Comment by Draise14** [comment]
Ah right. 
Maybe instead of having brush icons all in there in a row (since brushes can be created, meaning the icons would be dynamic?), just have one icon that open up the floating brush select panel - which can open on hover over with Blender prefs.

**Comment by ReinerBforartists** [comment]
Could happen that this is mission impossible. The menu from above is the blend mode. There was and is no menu for brushes available. There is also no easy way to enumerate the available brushes. Which is fatal. Since you can add and remove brushes. 

A simple menu with the standard brushes is possible. The Blender keymap has even hotkeys to switch between them. But makes not much sense since this menu can look completely different from the modified brushes then.

I would love to have a look at the addon that displays the brushes in a panel. If they have found a way to enumerate, or if they also just display the standard brushes ...

**Comment by ReinerBforartists** [comment]
Investigating ...

**Comment by ReinerBforartists** [comment]
... discouraging result . It remains the way it is. No way to enumerate the brushes. It's a C Prop, and so we have no access to it by Python.

We could still make menus with the default brushes. But i am not a happy bunny with that.

**Comment by Draise14** [comment]
I should give you a look at the advanced  sculpt addon. They somehow made a python floating dialogue of the brushes that was dynamic with new brushes and also had filters.

**Comment by ReinerBforartists** [comment]
Yeah, i would highly interested in how they did this.

**Comment by Draise14** [comment]
[Advanced-Brushes.zip](https://github.com/Bforartists/Bforartists/files/1845720/Advanced-Brushes.zip)

Here, take a look.

**Comment by ReinerBforartists** [comment]
Thanks, i will have a look :)

I have read the description meanwhile, and it seems that he uses indeed a completely custom solution. With an external Python framework. So i am not sure if i can find anything useful for our case here. We will see.

**Comment by ReinerBforartists** [comment]
This fish is too big for me. Giving up for now. Maybe this door opens at a later point.

**Comment by ReinerBforartists** [comment]
Reassigning. Found this Blender bug report here, which deals with enumerating brushes ...

https://developer.blender.org/T50426

Now i need to find out how to separate it by modes. It enumerates all of them.

**Comment by ReinerBforartists** [comment]
That was an easy one =3

Implementing ...

![justsculpt](https://user-images.githubusercontent.com/13919702/37896082-4af589f6-30e3-11e8-8c05-7658d0891599.jpg)

**Comment by ReinerBforartists** [comment]
Running into some problems here. Icons does not arrive in the toolbar. The active pencil is not set. And the biggest fish is: i cannot switch brushes from here ^^

![problems](https://user-images.githubusercontent.com/13919702/37898593-845768bc-30e9-11e8-81e3-ca05d8467baf.jpg)

**Comment by ReinerBforartists** [comment]
And unassigning again. Wasting too much time here with the try to make the square wheel round, while other tasks could be done and fixed meanwhile.

**Comment by ReinerBforartists** [comment]
Related issue: https://github.com/Bforartists/Bforartists/issues/57

**Comment by ReinerBforartists** [comment]
Closing this one. Maybe with 2.8. But for now it's too much hassle.
