### ISSUE TITLE
Eevee - rendering blank

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#994]
# Issue (?!)
I'm trying to render out from Eevee, and right now it renders nothing. 

1. Render Image = blank
2. Render Animation = desktop image (!?)

**Scene**
![bforartists_2019-07-01_11-49-50](https://user-images.githubusercontent.com/35357409/60453790-b9539200-9bf7-11e9-840d-54b66b3f2869.png)

**Result (!???)**
![bforartists_2019-07-01_11-50-09](https://user-images.githubusercontent.com/35357409/60453793-bfe20980-9bf7-11e9-8e53-4d04871f5d0b.png)

Here is the test scene:
[EEVEE TEST.zip](https://github.com/Bforartists/Bforartists/files/3346647/EEVEE.TEST.zip)

OpenGL render from view works fine.... But not normal render.

**Comment by Draise14** [comment]
Ok, tested it out in Blender 2.8.0, latest build, and..same issue... what!?

**Comment by Draise14** [comment]
![bforartists_2019-07-01_12-39-16](https://user-images.githubusercontent.com/35357409/60455861-43522980-9bfd-11e9-91b2-dc6db47aa200.png)

Ok, something must be up with my scene file, as older scenes do render - but not new ones. I get no console readout right now.

**Comment by Draise14** [comment]
It's with my default scene setup for some reason. Resetting to factory fixes the issue, but any scene saved with the default is bugged out. I will append each thing bit by bit to try find the issue....

**Comment by ReinerBforartists** [comment]
Woah, i really need to do some renderings in the future. Where are the world settings? Maybe there is something disconnected?

**Comment by ReinerBforartists** [comment]
Ah, found it. Everything's okay there. Hm. Interesting problem. I hope you find the cause.

**Comment by Draise14** [comment]
I imported all the objects only and remade the collections and scene materials. It.. works. So it's not the objects...

**Comment by ReinerBforartists** [comment]
I am unfortunately also clueless what breaks here, sorry. Have checked it a few times now. I miss the right idea ...

**Comment by Draise14** [comment]
I worked around it. I'll let this remain a mystery. The work around is to append the objects of the corrpt to a new scene.
