### ISSUE TITLE
Video Sequencer - Strip Menu: double menu entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#999]
![bforartists_2019-07-02_17-14-21](https://user-images.githubusercontent.com/35357409/60605584-6c022c80-9d7f-11e9-9c92-25a30418d6f8.png)
# Issue
There now are two enrties that are shown twice. Some are pulled up in the menu by Blender Devs, so they need to be cleaned up. 

# Task
Remove the double entry. 

Do we move them up one? Or keep them in the Transform Submenu?

**Comment by ReinerBforartists** [comment]
Good question. How is it in Blender?

**Comment by Draise14** [comment]
They moved it up one, surprisingly (not in the transform sub-menu).

**Comment by ReinerBforartists** [comment]
Then let's do the same. Doesn't harm :)

**Comment by Draise14** [comment]
Done.

![image](https://user-images.githubusercontent.com/35357409/60684845-929a9300-9e65-11e9-8753-572398e52cda.png)
